### PR TITLE
Increase Bypass Adapter timeout value.

### PR DESCRIPTION
**Pull request by ozevren**
At least one problem seems to be connectivity between PolicyBackend and Mixer. This looks like it is due to delay of DNS update, as otherwise the service seems to be active.

This PR updates configuration generation to use the direct address of the PolicyBackend when generating Mixer configuration.

### CODE REVIEW

**Comment by ozevren** [comment]
Do you have a suggestion? I considered changing the bypass adapter to wait
more or do connection lazily but that seem to be much bigger surgeries and
i am not sure if they are the right thing to do given Mixer v2 plans
anyways.

**Comment by kyessenov** [comment]
Insert a delay? Given that DNS is eventually consistent, we can't force it to be faster than it currently is. There is a real issue with gRPC LB having hard 30s timeout that we're going to mask with the change to IP addresses.

**Comment by kyessenov** [comment]
Until we have a viable Mixer v2 implementation, we are stuck with Mixer v1 fulfilling critical requirements. So I think it is important to test it well.

**Comment by ozevren** [comment]
How long? A minute? (The Bypass adapter code in Mixer already has a
retry/backoff loop in the order of a minute, so this would be in addition
to that). Delays themselves are hacky. There is no guarantee that they
would work, and they tend to make tests run for much longer time (e2e Mixer
tests are a good example, where most of the test is actually waits and took
~40 minute to complete last I checked). If we're going to hack through the
problem, I'd much rather do the IP address solution as it categorically
avoids a particular vector for flaky behavior by eliminating DNS related
issues.

**Comment by kyessenov** [comment]
A minute is not long enough. Ultimately, this is a gRPC issue since it hard codes 30s fixed retry timeout. The solution is either start things in the right order (e.g. wait for DNS to become available before Mixer), fix gRPC (by piling on the issue or replacing LB backend), or add longer timeout. Longer timeout is the easiest fix.

**Comment by kyessenov** [comment]
Please don't refer to delays as flakes. This is working as intended, since lots of underlying components (DNS, gRPC) are eventually consistent and _do_ expect slow initialization for things to settle. You can't expect the overall system to stabilize immediately without working through every single library / dependent system. However, replacing these systems with instant mocks means we don't test the actual thing, which in the case of gRPC or DNS is more important than faking them.

**Comment by ozevren** [comment]
First, I am not sayin delays are flakes, I am saying they are hacks. :) Second, they are hacks, as a delay and a retry loop are different things. And we have an ample amount of the former in numerous tests. They contribute to flakes and test run times. The test framework and components already have numerous retry loops in various places, precisely to make them work resiliently in an eventually consistent system. Also there is already a retry loop in Mixer bypass adapter with a 1 minute range, and it is failing to solve this problem, so it looks like the propagation delays are either longer than that, or there is some other issue at play.

I can add a DNS lookup from the test framework to further reduce the window, but even that is possibly not the right solution. Most likely, the check needs to be done from the Mixer pod itself.

**Comment by kyessenov** [comment]
Given that gRPC only retries DNS every 30s, 1 minute delay is far from enough. 5 minute is more realistic.

**Pull request merged**
