### PR TITLE
listener: move grpc status filter to well known names

### PR DESCRIPTION
**Pull request by ramaraochavali**
Given this issue https://github.com/envoyproxy/envoy/issues/10445, we should enable gRPC stats filter only for sidecars or control it via a feature flag.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@kyessenov Is this reasonable or should we control enablement via a feature flag so that people who want can enable?

**Comment by ramaraochavali** [comment]
@kyessenov ignore my comment above. Realized that this code path is coming only for sidecar. So I just changed it to use wellknown names. Do you think we should still enable it based on user preference via feature flag or is it ok to enable it by default?

**Comment by kyessenov** [comment]
I'd prefer if it was not enabled by default, but between an EnvoyFilter and doing it in the code, I choose the code. The stats blow-up issue you mentioned is being fixed upstream.

**Comment by ramaraochavali** [comment]
If this is needed primarily for mixer telemetry (I guessing that is the case), should we enable it based on this https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L64? or some other flag?

Yeah, I saw the PR in Envoy to contain the stats blow up issue

**Pull request merged**
