### PR TITLE
Grafana hardcoded service name prevents Ingress to work

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**

### CODE REVIEW

**Comment by costinm** [comment]
Why ? I mean - what does the hardcoded name have to do with the ingress not working ? The ingress should use the same name ( and likely be converted to a VirtualService ).

**Comment by sebastien-prudhomme** [comment]
@costinm Because the ingress is referencing the backend servicename with another name.

In ingress.yaml:

```yaml
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "grafana.fullname" . -}}
...
            backend:
              serviceName: {{ $serviceName }}
...

So either the ingress uses "grafana" as the service name or the service name uses the name provided by the helper template. I choosed the last solution to follow Helm chart best practices.

**Comment by costinm** [comment]
For pilot, mixer, etc we use the names - and I think that is the best practice in case of Istio. Having names modified by templates leads to confusion and support issues in case someone is actually changing the names, and there are not very good reasons to allow arbitrary customization, like the names of services. There are other places in the system where the names matter ( generated certs, configs, etc).

**Comment by costinm** [comment]
BTW - this change is probably not needed since Ingress is not supported in istio gateway ( will be optional, off by default AFAIK ). Could you instead add a Gateway - and use grafana service name directly.

**Comment by sebastien-prudhomme** [comment]
I really don't want to rework all the charts... I'm just evaluating Istio to see how good it is. As i found problems in the charts i propose patches to the community but if it it that hard to make accept a small modification, i'm not sure it worths the time spent.

**Comment by sdake** [comment]
@sebastien-prudhomme - thanks for the contribution and thanks for the evaluation.  We have deviated in some Helm best practices.  One of these is what you have run into.  We "hardcode" names since Istio internals depend heavily on the names.  We definitely want to improve the Helm charts over time.  Check here for a long list of items, most of which are improvements, from @stono in need of Helm expertise:
https://github.com/istio/istio/issues/6037

There are many other improvements we can make as well.

Cheers
-steve

**Comment by costinm** [comment]
Having too many options, or over-configuration are not 'best practices'. If there is a common use case for users to change the name of a service or deployment - we can support it, but it needs to be clear why, have some testing - and we need to make sure this change is propagated wherever something may need it. Helm and k8s are not the only way to run Istio - we support other environments, and we want to simplify  the installation in general for all platforms, so it doesn't depend on helm too much. 

I appreciate the contribution - and we clearly need to fix how grafana is accessed. Switching to a VirtualService is likely the right solution, since that's how Istio is configuring ingress, and it can be pointed to an internal (non-public) ingress  for example. 

Keep in mind there is no security in grafana, so having an Ingress exposed to the internet is also a risk, and might be safer to just remove the ingress until proper security is available ( unless we go with exposing only over an internal load balancer or a gateway that is private )

**Comment by costinm** [comment]
PR 7127 is moving to gateway and adds user/pass. Closing this.

**Pull request closed without merging**
