### PR TITLE
Backport regex: remove safe regex validation and default program size

### PR DESCRIPTION
**Pull request by jnodorp**
Backport of #19212 to release 1.4.

### CODE REVIEW

**Comment by jnodorp** [comment]
@googlebot I signed it!

**Comment by ericvn** [comment]
Looks like this also needs consent from @ramaraochavali

**Comment by jnodorp** [comment]
@ramaraochavali, if you are okay with your changes being backported to 1.4  please comment with `@googlebot I consent.`. Thanks!

**Comment by ramaraochavali** [comment]
@googlebot I consent

**Pull request merged**
