### PR TITLE
AGE column for istioctl

### PR DESCRIPTION
**Pull request by esnible**
_istioctl get_ should include an AGE column similar to _kubectl_.

### CODE REVIEW

**Comment by ayj** [comment]
General question: There's been quite a few PR's recently making istioctl behave like kubectl. Why not use kubectl directly?

**Comment by esnible** [comment]
@ayj My original inspiration for _istioctl get_ improvements was so that there could be calculated custom fields summarizing deployment configuration.  See https://github.com/istio/istio/issues/5538

I implement the custom fields, but to make the PRs small and manageable I broke the implementation into several PRs and the last and most interesting one is not yet delivered.

I believe there is some easy low-hanging fruit with _istioctl_ improvements.  Today I spent 90 minutes debugging a clients 404 issues.  Turns out an Istio VirtualService had been modified with `kubectl edit` bypassing Istio validation.  After a bogus change was made `kubectl get virtualservice` showed no apparently problem, but `istioctl get virtualservice` showed
```
json: cannot unmarshal object into Go value of type []json.RawMessage
```
My hope is that a few short changes to _istioctl_ will help medium-skilled operators from shooting themselves in the foot.  (I realize the particular validation problem described here is better fixed by https://github.com/istio/istio/issues/1894 )

**Comment by ayj** [comment]
Thanks for taking time to improve the overall user experience. My comment was more in reference to _issues_ (I mistakenly said _PRs_) that have suggested feature enhancements to bring istioctl in-line with kubectl, e.g.

- https://github.com/istio/istio/issues/6025 - istioctl should support get multiple resources 
- https://github.com/istio/istio/issues/6004 - Enable `istioctl edit` to edit some resources 
- https://github.com/istio/istio/issues/5911 - Introduce `istioctl apply` to update resources 

> kubectl can't do any validation; at least with istioctl we now know something is wrong.

Server-side validation (#1894) will be enabled by default in 1.0 at which point we should remove client-side validation from istioctl. Server-side validation is also available in 0.8 but disabled by default.

**Comment by esnible** [comment]
Closing; I will create a new PR after I find a fool-proof way to add a dependency.

**Comment by esnible** [comment]
Marking this WIP because I suspect the failure in *ci/circleci: e2e-pilot-auth-v1alpha3-v2* is real.  I introduce a new field, model.ConfigMeta.CreationTimestamp and I suspect that some code compares ConfigMeta with DeepEqual() and the timestamps cause the comparisons that previously returned `true` to become `false`.

**Pull request merged**
