### PR TITLE
gateway: ignore virtual services when https redirect is set

### PR DESCRIPTION
**Pull request by rshriram**
Fixes an UX issue that was recently encountered with an end user

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    # redirect all traffic on :80 to :443
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
      tls:
        httpsRedirect: true
    # handle only a single domain
    - port:
        number: 443
        name: https
        protocol: TLS
      hosts:
        - "login.foo.com"
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foologin
spec:
  hosts:
  - "login.foo.com"
  gateways:
  - istio-system/public-gateway
  tls:
  ...
  # if we remove this stanza, the redirect from 80 to 443 on the gateway stops working
  http: # we should not need the http route since all http is redirected to tls
  - route:
    - destination:
        host: blah
```

### CODE REVIEW

**Comment by rshriram** [comment]
I would love to but we dont have any integration tests for gateway in our test suite! Didn't we have one in the beginning?

**Comment by hzxuzhonghu** [comment]
lgtm

**Comment by howardjohn** [comment]
Wow we should add some.. can be a follow up

**Comment by rshriram** [comment]
@esnible this needs an analyzer. FYI

**Pull request merged**
