### PR TITLE
Merge changes from istio template (#38837)

### PR DESCRIPTION
**Pull request by sanjaypujare**
* Merge changes from istio template

* Remove security section

* Missing end

* Make gen, remove the ifs and add lifecycle - grpc starts very fast

* Few debug statements to figure out why wait doesn't work

* Use the agent ready port

* Rever the deugging changes

* make gen

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by sanjaypujare** [comment]
@costinm as discussed. Once you are okay I will change from draft to regular PR

**Review by costinm — APPROVED** [review]
This is a safe change to merge - it only impacts proxyless gRPC, which is still an experimental feature.

**Comment by costinm** [comment]
Will need to be approved by the release managers. I think it is very good to merge since it helps with increasing the number of users of proxyless gRPC, in 1.14 it doesn't work very well without this change.

**Comment by sanjaypujare** [comment]
> This is a safe change to merge - it only impacts proxyless gRPC, which is still an experimental feature.

Thanks @costinm . I believe I can't merge this but will need to be merged by the release manager?

**Review by lei-tang — APPROVED** [review]

**Comment by sanjaypujare** [comment]
The tests are still waiting, how does that get unblocked? @lei-tang ?

```
release-notes_istio_release-1.14 Expected — Waiting for status to be reported        Required
```

**Comment by lei-tang** [comment]
> The tests are still waiting, how does that get unblocked? @lei-tang ?
> 
> ```
> release-notes_istio_release-1.14 Expected — Waiting for status to be reported        Required
> ```

Similar to https://github.com/istio/istio/pull/38837, add a release-notes-none label to this PR to unblock the test release-notes_istio_release-1.14.

**Comment by sanjaypujare** [comment]
> ...
> Similar to #38837, add a release-notes-none label to this PR to unblock the test release-notes_istio_release-1.14.

Thank you.

**Comment by sanjaypujare** [comment]
From the output:

```
=== RUN   TestWebhook
2022-08-12T16:47:04.217830Z	info	tf	=== BEGIN: Test: 'pilot[TestWebhook]' ===
    webhook_test.go:85: Config rejected: false, expected config rejected: true
2022-08-12T16:47:04.304342Z	info	tf	=== DONE (failed):  Test: 'pilot[TestWebhook] (86.505776ms)' ===
2022-08-12T16:47:04.304453Z	error	tf	=== Dumping Namespace echo-2-55861 State...
2022-08-12T16:47:04.304484Z	error	tf	=== Dumping Istio Deployment State...
2022-08-12T16:47:04.304509Z	error	tf	=== Dumping Namespace external-1-139 State...
2022-08-12T16:47:07.255751Z	info	tf	istioctl ([x internal-debug --all configz]): completed after 0.0340s
2022-08-12T16:47:07.286943Z	info	tf	istioctl ([x internal-debug --all mcsz]): completed after 0.0296s
2022-08-12T16:47:07.329873Z	info	tf	istioctl ([x internal-debug --all clusterz]): completed after 0.0427s
--- FAIL: TestWebhook (9.30s)
=== CONT  TestValidation
...
FAIL
2022-08-12T16:47:15.919272Z	info	tf	=== FAILED: Test Run: 'pilot' (exitCode: 1) ===
...
FAIL	istio.io/istio/tests/integration/pilot	290.402s
...
NoCleanup:         false
...
FAIL
...
```

This does not seem related to the change in the PR. @costinm or @lei-tang could you confirm?

**Pull request merged**
