### PR TITLE
Upgrade base image to add user istio-proxy

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

this PR is for adding user istio-proxy to base image to allow the istio components can be running as user istio-proxy.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by clyang82** [comment]
we don't have automation of building base images yet. so just use private repo for testing purpose. once passed the testing, will switch to `docker.io/istio`. Sorry for the noise for other WGs.

**Comment by clyang82** [comment]
@howardjohn please help to approve pushing the base image. Thanks.

**Comment by howardjohn** [comment]
@clyang82 thanks, I'll approve once we swap out your fork for the real one.

Switch in Makefile.core.mk: `BASE_VERSION ?= 1.4-dev.2`

**Comment by clyang82** [comment]
Thanks @howardjohn

**Pull request merged**
