### PR TITLE
Quote Istio revision and service canonical name in chart templates

### LINKED ISSUE #50366: Gateway template for service.istio.io/canonical-revision is rendering int instead of str
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Template [here](https://github.com/istio/istio/blob/366edfc208a49c1d168af3d2d0c8b3d2c94f2642/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L37C9-L37C45) is rendering `service.istio.io/canonical-revision` as an int when using `version: 12345` label, generating the following error:
```
Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field ObjectMeta.spec.template.metadata.labels of type string
```
This is a change introduced by https://github.com/istio/istio/pull/43388 in 1.19.

We need to make sure whatever canonical-revision is picked up, it comes out of the render as a string.

### Version

```Text
client version: 1.20.0
control plane version: 1.17.4
data plane version: 1.17.4 (11 proxies)
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by nacx**
**Please provide a description of this PR:**
Fixes https://github.com/istio/istio/issues/50366
The values of the canonical revision and Istio revision are set by the user and we can't control if those values are just numbers. The current Helm templates do not quote the configured values, leading to unmarshalling errors.
This change just checks all the usages of the revisions and quotes the values.

### CODE REVIEW

**Comment by nacx** [comment]
This works fine, except for a couple files: `kube-gateway.yaml` and `waypoint.yaml`. On the following lines:

https://github.com/istio/istio/blob/12b77bc7c1fcaaac91ee0480b026b7e87db05ff9/manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml#L49-L57

If I change the Isito revision line and add a quote:
```
(strdict "istio.io/rev" (.Revision | default "default" | quote)) 
```

It is not rendered as expected and some tests fail:
```
    deploymentcontroller_test.go:373: Failed validating golden file testdata/deployment/simple.yaml:
        @@ -50,5 +50,5 @@
               annotations:
                 ambient.istio.io/redirection: disabled
        -        istio.io/rev: default
        +        istio.io/rev: '"default"'
                 prometheus.io/path: /stats/prometheus
                 prometheus.io/port: "15020"
```
Any suggestion on how should I get it properly quoted on those two files?

**Comment by nacx** [comment]
Ah, you're right. It should be good to go then. Thanks!

>FWIW revision already cannot be a number I think

I don't know if there is any validation, but for example, the `istioctl manifest generate` would generate unquoted revisions if someone explicitly sets just number, and even if that is validated/rejected later it's good to have it quoted so it just works.

**Review by howardjohn — APPROVED** [review]

**Comment by zirain** [comment]
need backport？

**Pull request merged**
