### PR TITLE
Bump quic-go for go 1.17 support

### PR DESCRIPTION
**Pull request by howardjohn**
This fixes the issue on using go mod vendor as well

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by nmittler — APPROVED** [review]

**Comment by ericvn** [comment]
Does this version fix `go mode vendor` issue that was reported the last time we updated versions?

**Comment by howardjohn** [comment]
yes

**Comment by ericvn** [comment]
Just verifying and see it does. Thanks.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
