### PR TITLE
[build] bazel_to_go: do not overwrite the files if the generated ones are same

### PR DESCRIPTION
**Pull request by jmuk**
**What this PR does / why we need it**:

Currently bazel_to_go.py overwrites the generated files, but that could be problematic, sometimes the generated files have meaningless differences, like the name of the source files. With this PR, bazel_to_go.py checks their contents and makes the copy only when there's changes, and it explicitly exclude the contents for source files.

With this PR, I think now presubmit should always invoke bazel_to_go and then check if there are meaningful changes on the generated files -- presubmit should fail in such case; that would be done by another PR.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: updates #1515

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by jmuk** [comment]
@mandarjog, please try this on your environment -- I actually haven't set up the environment of different source paths yet.

**Comment by mandarjog** [comment]
@jmuk there is always changes in the `FileDescriptorProto`, so just checking the `proto.RegisterFile` is not enough.

I have verified that this is indeed the case.

**Comment by jmuk** [comment]
😢 it's harder to ignore the part of descriptor bytes in the go file with this scheme let me think.

**Comment by jmuk** [comment]
@mandarjog 
added a few more patterns, I think this captures your points. Please take another look.

**Comment by costinm** [comment]
I'm confused - which files are the problem ? The .pb.go files have relative paths, simply cp from baze-genfiles is enough and git will not find changes.

**Comment by jmuk** [comment]
ask @mandarjog for the details; I've heard that some path relatives can be different on some platform (like starting from bazel-genfiles or including local-fastbuild or not, etc). I haven't seen this on my environment though.

**Comment by mandarjog** [comment]
/lgtm
@jmuk it works on a Mac now. Thanks.

**Pull request merged**
