### PR TITLE
[WIP] Add dumping services to dumpK8Env in the mixer e2e test

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
This will allow, in particular, checking the LoadBalancer public IP of `istio-ingress`, and comparing it with the IP that is used to access the tested application via Istio Ingress.

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
@douglas-reid each test has a different problem:

1. `prow/istio-pilot-e2e.sh`: fails on accessing `httpbin.org`. Either `httpbin.org` has some DNS issues or it started to filter our requests to prevent DOS. We can consider to cancel Egress tests, or to access our own servers, or to try some other external service like `cnn.com`.
2. `prow/istio-pilot-e2e-envoyv2-v1alpha3`, `
ci/circleci: e2e-pilot-noauth-v1alpha3-v2`, `ci/circleci: e2e-pilot` fail on multiple GRPC tests, and TestControllerCacheFreshness, TestControllerClientSync, TestControllerEvents.
3. `prow/e2e-suite-rbac-auth.sh` failed on upgrade test, it should be fixed by https://github.com/istio/istio/pull/5316
4. `prow/e2e-bookInfoTests-v1alpha3.sh` will be fixed by https://github.com/istio/istio/pull/5055

**Comment by vadimeisenbergibm** [comment]
@douglas-reid I have updated my previous comment:
>prow/istio-pilot-e2e.sh: fails on TestRBAC

**Comment by costinm** [comment]
(and maybe ramp down the different ways to get logs and dumps after tests - consolidating on the tool, since the tool will be what we'll recommend to users to generate debug info)

**Comment by vadimeisenbergibm** [comment]
> There is a script ( called from make dumpsys ) - can we call that at the end, so all tests get consistent logs ?

@costinm Good idea, let me do it.

**Pull request closed without merging**
