### PR TITLE
Remove ConfigFetchIntervalSec from mixer args

### LINKED ISSUE #9320: Mixer arg ConfigFetchIntervalSec is not used any more
There is no flag for [ConfigFetchIntervalSec](https://github.com/istio/istio/blob/d12f96e07abc9d0f7fb971cff42178401b6a40a4/mixer/pkg/server/args.go#L67), and it is not used any more.  So we can remove it.

### PR DESCRIPTION
**Pull request by supereagle**
Fix #9320

### CODE REVIEW

**Comment by douglas-reid** [comment]
/lgtm

cc: @bianpengyuan (who i think has looked at this recently)

**Comment by supereagle** [comment]
@bianpengyuan  PTAL

/assign @bianpengyuan

**Comment by supereagle** [comment]
@bianpengyuan  The lint failure is not related with this PR, how can we merge this?

**Pull request merged**
