### PR TITLE
[1.2] Fix Citadel using in-memory cert without writing to secret issue.

### PR DESCRIPTION
**Pull request by myidpt**
Fix on 1.2 for https://github.com/istio/istio/issues/14512.
Integration test is also included.

### CODE REVIEW

**Comment by myidpt** [comment]
@incfly I think this is fine. It's a useful info for debug. And it's only printed once, so not very spammy :)

**Comment by fpesce** [comment]
Need to wait for the master version of that work to pass tests and be merged there.
c.f. point 5 of [1.2 Release branch cut](https://discuss.istio.io/t/1-2-release-branch-cut/2372)

**Comment by fpesce** [comment]
Also this change is a very small subset (no tests) of #14513 .
We want the test landing here too so our CI reflects accurately the quality of the code.

**Comment by howardjohn** [comment]
@myidpt can you update this to include the tests

**Comment by fpesce** [comment]
@myidpt  would you mind putting the unit test from original PR in that PR?

**Comment by myidpt** [comment]
@fpesce @howardjohn 
This feature is hard to implement unit test. I wrote an integration test for it:
https://github.com/istio/istio/pull/14513
Do you want me to add the integration test here?

**Comment by howardjohn** [comment]
Yes would be great to just have the exact change that is in master (the integration test)

**Comment by myidpt** [comment]
Done adding the integration tests.

**Pull request merged**
