### PR TITLE
Remove post-install job and (kubectl) apply security policy CRs to k8s directly

### PR DESCRIPTION
**Pull request by diemtvu**
Given CRDs are installed in separate step, we don't need to run a post installation job in inject default policy. This clean up the installation process, also fix the problem that post-install job wasn't triggered for update.

Issue: #10946

### CODE REVIEW

**Comment by morvencao** [comment]
Try to switch `release-1.1`?

**Comment by sdake** [comment]
@diemtvu can you get a bug filed for this problem so it can be triaged and sorted for 1.1?

Cheers
-steve

**Comment by diemtvu** [comment]
> @diemtvu can you get a bug filed for this problem so it can be triaged and prioritized for 1.1?
> 
> Cheers
> -steve

You mean this one https://github.com/istio/istio/issues/10946

**Comment by diemtvu** [comment]
Fix the typos, test works better now. PTAL. I can make a cherry pick to 1.1 after this submitted. 

e2e-pilot-cloudfoundry-v1alpha3-v2 still fail, but I don't think the issue come from this PR. 

Thanks.

**Pull request merged**
