### PR TITLE
Update istioctl tls-check tool to reflect autoMTLS

### PR DESCRIPTION
**Pull request by diemtvu**
Please provide a description for what this PR is for.

Update the tool to reflect the behavior after https://github.com/istio/istio/pull/17621

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

### CODE REVIEW

**Comment by incfly** [comment]
istioctl changes, less risky, should be CP-ed as implementation to 1.4 for
consistency.

**Comment by diemtvu** [comment]
Hold to verify with Greg's PR again

**Comment by diemtvu** [comment]
Correct the status when mTLS disabled. @incfly PTAL

**Pull request merged**
