### PR TITLE
[KIALI] Add possibility to choose login strategy

### PR DESCRIPTION
**Pull request by anthonyhaussman**
Add possibility to choose login strategy into Kiali.
Set to "login" by default.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by anthonyhaussman** [comment]
I signed it!

**Comment by jmazzitelli** [comment]
this is a virtual duplicate of https://github.com/istio/istio/pull/15459

**Comment by anthonyhaussman** [comment]
Indeed @jmazzitelli.
I close this duplicate MR and waiting for the other one to be merge.
Sorry for the inconvenience.

**Comment by jmazzitelli** [comment]
@anthonyhaussman you might want to re-open this and submit your CLA. The other PR has been stuck waiting for the committer to submit a  CLA for a while. If you want this in (and someone else just asked for this as well), might be faster if you do it. First one in, wins :)

NOTE: change the name of your setting - don't call it just "strategy" -- call it "authStrategy" like that first PR.

**Comment by anthonyhaussman** [comment]
@jmazzitelli It is done and the CLA submit. :)
Feel free to review it,

**Comment by anthonyhaussman** [comment]
Closing after #15016 was merged.

**Pull request closed without merging**
