### PR TITLE
Disable strict_1xx_and_204_reponse_headers in envoy bootstrap config

### PR DESCRIPTION
**Pull request by Monkeyanator**
Addresses #28433. In short, this change is needed to keep certain requests from 1.7 proxies -> 1.6 proxies from 503ing.

Having the `strict_1xx_and_204_response_headers` envoy config enabled (default-on) makes it so that proxies will reject http responses having code 1xx/204 and having the "Transfer-Encoding" header present. Our proxies <=v.1.6.x will send such responses by default (this [envoy change](https://github.com/envoyproxy/envoy/pull/11458) was just merged ~5mos ago), resulting in our 1.7 proxies 503ing in those cases.

My main concern here (and I have been able to confirm this) is that this will introduce the same compatibility issue between 1.7 proxies that have this feature enabled -> 1.7 proxies that don't (since from the relevant Envoy PR, disabling the `strict_..._response_headers` flag both allows requests received with 204 + Transfer Encoding header to succeed _and_ causes the envoy instances _sending_ those responses to continue sending 204 responses with Transfer Encoding set). 

So due to this issue, from what I can tell, 1.8 proxies will either also have to have this disabled to avoid issues or we'll have to enable the config on 1.7 proxies at that point.

cc @howardjohn @lambdai 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
So the flag conrols not just *allowing* the TE headers, but also *sending* them?

So today

Version|Send TE|Accept TE
|-|-|-
|1.6|Y|Y|
|1.7|N|N|

This PR

Version|Send TE|Accept TE
|-|-|-
|1.6|Y|Y|
|1.7|Y|Y|

Ideal state

Version|Send TE|Accept TE
|-|-|-
|1.6|Y|Y|
|1.7|N|Y|


Is that right? So we are essentially defering the problem, since at some point we will need to move over and we cannot do that

a quick curl on 1.6 I didn't see the TE or content length headers, not sure if I did it wrong though...
```
/ $ curl --raw httpbin/status/204 -v
*   Trying 10.40.10.72:80...
* Connected to httpbin (10.40.10.72) port 80 (#0)
> GET /status/204 HTTP/1.1
> Host: httpbin
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< server: envoy
< date: Sat, 31 Oct 2020 00:09:19 GMT
< content-type: text/html; charset=utf-8
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 2
<
* Connection #0 to host httpbin left intact
```

**Comment by Monkeyanator** [comment]
From `1.6.13` sleep container to `1.7.3` httpbin:

```sh
/ # curl -sI 10.4.35.208:8000/status/204
HTTP/1.1 204 No Content
server: envoy
date: Sat, 31 Oct 2020 00:55:55 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3
transfer-encoding: chunked
```

but also

```sh
/ # curl --raw -v 10.4.35.208:8000/status/204
*   Trying 10.4.35.208:8000...
* Connected to 10.4.35.208 (10.4.35.208) port 8000 (#0)
> GET /status/204 HTTP/1.1
> Host: 10.4.35.208:8000
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< server: envoy
< date: Sat, 31 Oct 2020 00:56:58 GMT
< content-type: text/html; charset=utf-8
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 3
<
* Connection #0 to host 10.4.35.208 left intact
```

Not sure on why the `transfer-encoding: chunked` header shows up on `curl -sI` but not `curl -v --raw`....

Agreed on your breakdown of what's going on now and what would be happening after this change, and agreed that the "ideal" situation would be where 1.7 accepts TE encoding but does not send it.

**Comment by nrjpoddar** [comment]
@Monkeyanator thanks for taking a crack at fixing this. Can we make sure we add an integration test as this seems like something that will be fragile and can break from one release to other?

**Comment by Monkeyanator** [comment]
Happy to add an integration test 👍  As it stands though, I think there are a few unresolved questions around how we would disable this flag in the future without breaking things in the same way they are broken now

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
we should probably add a release note. Basically just saying we fixed this, so update, there should be no user action needed

**Comment by howardjohn** [comment]
Discussed with @lambdai , we should do this now and followup with envoy to allow the "ideal state" mentioned in https://github.com/istio/istio/pull/28450#issuecomment-719852578 so we can smoothly migrate.

**Comment by lambdai** [comment]
I created the issue in wrong repo...

**Comment by tariq1890** [comment]
Hey everyone, the related issue to this PR broke things for us in our production cluster when we some of our pods at 1.7.4 were talking to other pods whose proxies were upgraded from 1.7.4 to 1.7.7 :'(

If I understand @howardjohn's truth table comment, it looks like 1.7.7 doesn't embody the ideal state.

We never faced this issue when all of our clusters were on 1.7.4. I am assuming that's because 1.7.4 never sends TE even though it may not necessarily accept TE with 1xx/204 response codes.

**Comment by Monkeyanator** [comment]
Yeah unfortunately this PR introduced an upgrade issue as [described here](https://istio.io/latest/news/releases/1.7.x/announcing-1.7.5/#upgrade-notice). We'd like to move forward with two separate runtime flags which is contingent on progress on [this envoy issue](https://github.com/envoyproxy/envoy/issues/13868)

**Pull request merged**
