### PR TITLE
fix package imports for pilot

### PR DESCRIPTION
**Pull request by kuafou**
#8687

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I think this is the only way now since I can not rerun your circle ci.

**Comment by kuafou** [comment]
> I think this is the only way now since I can not rerun your circle ci.

Does this means the original upstream/master that this PR based on has failed on some circle ci test ?

**Comment by GregHanson** [comment]
@kuafou there was a build failure that was introduced yesterday due to a bad merge.  Should be resolved.  If you merge with master and update your branch, things should pass

**Comment by kuafou** [comment]
> @kuafou there was a build failure that was introduced yesterday due to a bad merge. Should be resolved. If you merge with master and update your branch, things should pass

**Comment by kuafou** [comment]
> @kuafou there was a build failure that was introduced yesterday due to a bad merge. Should be resolved. If you merge with master and update your branch, things should pass

Why there has a bad merge!!!  If i merge with master and update my branch, this will involve another google CLA issue, just like #8687!  I don't even know how to do. So will close this, sorry for that.

**Comment by hzxuzhonghu** [comment]
@kuafou  Can you rebase your code and reopen ?

**Comment by venilnoronha** [comment]
@kuafou I'd just do `git fetch`, `git rebase upstream/master` and `git push qi_imports -f` to update the PR with the latest changes from `upstream/master`. This should be enough to update the PR without causing any CLA issues.

**Pull request closed without merging**
