### PR TITLE
install: helm values for tls certs in side car injector

### PR DESCRIPTION
**Pull request by ramaraochavali**
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>

Makes TLS certs configurable for sidecar injector via Helm values. Implements https://github.com/istio/istio/issues/15001

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by morvencao** [comment]
Do we really need this? The default /ca/cert/key is mounted at `/etc/istio/certs`, changing the path in values won't work, isn't it?

**Review by morvencao — COMMENTED** [review]
Do we really need this? The default /ca/cert/key is mounted at `/etc/istio/certs`, changing the path in values won't work, isn't it?

**Comment by ramaraochavali** [comment]
Yes. As mentioned in https://github.com/istio/istio/issues/15001, we manipulate the configmap of sidecar injector and configure pilot-agent with different cert locations to use non default cert locations. We need this to avoid manipulating configmap

**Comment by howardjohn** [comment]
I'm somewhat with @morvencao on this.. it seems you are the only user that wants this. I'm not sure it makes sense to add 3 new values here (and I'm sure some other config elsewhere) for some unique case. At some point does it make sense to do some postprocessing with Kustomize or other tools rather than making a new setting for everything? Or is this something that is actually universally useful?

We are trying to reduce the number of helm values. Especially untested ones

**Comment by ramaraochavali** [comment]
@howardjohn I think having configurable cert locations is generally useful - especially folks using existing PKI infrastructure that puts certs in location defined/governed by it.

I am open to any options/suggestions.

**Review by costinm — COMMENTED** [review]
This won't work - the certs are mounted from a secret.
If you add a test changing the value from the default - pretty sure it'll fail. 

(majority of settings in values.yaml lack tests and probably don't work - but it's not a good reason to add more...)

**Comment by costinm** [comment]
Most likely what you want is to change the volume mount instead - if you want to use a different secret. 
But you can mount any secret in the /etc/certs.

**Comment by ramaraochavali** [comment]
@costinm I see. Thanks for the pointer. I will try to use Volume Mount and also try to see if I can add a test

**Comment by costinm** [comment]
Manually testing is fine (with a description of how it was tested).

Note there is already an option to allow arbitrary volumes and secrets to
be mounted into a sidecar. And we already have a setting to
configure the 'base' directory for the certs. The primary use case for
custom cert directory is mesh expansion ( raw VMs ) or non-k8s
environments - but those cases don't use the injector anyways.

Do you need the actual files inside the directory to be configurable ?

On a related note - we are hoping to move soon to SDS and stop using
mounted secrets, so I don't think we should spend too
much time on more complexity around secret mounting... Could you describe
your exact requirements, maybe we can
have a simpler short-term solution ?

**Comment by ramaraochavali** [comment]
We want the actual files to be configured. We will discuss internally again and come back, for now I will close this PR.

**Pull request closed without merging**
