### PR TITLE
go.mod: bump to Kubernetes 1.28 libraries

### PR DESCRIPTION
**Pull request by howardjohn**
This is pre-release for now, but we are planning to adopt before 1.19.
Upgrade early to start getting testing in

The changes to inject/ package are expected - they were broken before due to using the old API library. It only impacts an experimental, off-by-default feature.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Test GatewayConformance failure maybe related to gateway api bump

**Review by jacob-delgado — APPROVED** [review]

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
