### PR TITLE
Rename Service's field: Addresses -> ClusterVIPs

### PR DESCRIPTION
**Pull request by ronenschafferibm**
This PR is related to issue https://github.com/istio/istio/issues/5498. It renames `Addresses` field of Service to `MulticlusterAddresses`.

While being a part of large refactoring, this PR is useful in itself, to clarify the difference between the `Address` and `Addresses`, and to document by the name of the variable what `Addresses` are used for.

### CODE REVIEW

**Comment by rshriram** [comment]
Rename to clusterVips

**Comment by vadimeisenbergibm** [comment]
@rshriram  So the field name should be `ClusterVIPs`, correct? (cc @ronenschafferibm)

**Comment by ronenschafferibm** [comment]
@rshriram, I renamed it.

**Comment by rshriram** [comment]
rebase to master branch

**Pull request merged**
