### PR TITLE
Hide operator's golden test data changes in pull requests by default

### PR DESCRIPTION
**Pull request by ayj**
The operator manifest's unit tests use golden test files. These files
are (re)generated by running tests with UPDATE_GOLDENS=1. This
produces largest pull requests for even minor changes to the
manifests. 

This PR reduces the visible set of changes in pull requests by
hiding these auto-generated files by default so reviewers can focus on
the more important manifest changes.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I think this is a good idea, but @ostromart does not so I will let him comment before approving

**Review by elfinhe — COMMENTED** [review]
+1 for hiding the golden files.

**Comment by ayj** [comment]
Do reviewers inspect the generated test data? I understand the theory of not hiding these. However, in practice I suspect many want to focus more on the original manifest change and tend to ignore the generated files, trusting that UPDATE_GOLDEN=true did the right thing. I know I do. Reviewers can still expand the collapses diff when they feel it necessary.

**Comment by howardjohn** [comment]
> Do reviewers inspect the generated test data? I understand the theory of not hiding these. However, in practice I suspect many want to focus more on the original manifest change and tend to ignore the generated files, trusting that UPDATE_GOLDEN=true did the right thing. I know I do. Reviewers can still expand the collapses diff when they feel it necessary.

Agreed. just because its hidden doesn't mean you cannot inspect the changes if you want. Its impossible to review any of these changes because of all the generated junk getting in the way.  I think the idea of not wanting to hide these is to promote reviewing them all, but it ends up doing the opposite and making me not review the real changes at all

**Review by howardjohn — APPROVED** [review]
I approved but with a hold to give @ostromart a chance to object

**Comment by ostromart** [comment]
How about a compromise: let's expand just _one_ golden output file for manifest-generate. I don't think it's unreasonable to expect a user to look at changes in one file. 
Completely collapsing everything will lead people to completely ignore golden outputs, short circuiting an important sanity check.

**Comment by ayj** [comment]
All but one golden file are now hidden by default. @howardjohn @ostromart PTAL

**Review by ostromart — APPROVED** [review]
Thanks @ayj!

**Comment by ayj** [comment]
This may take a while to get in. The generated output files frequently have merge conflicts which need to be manually resolved. I believe @howardjohn raised a similar issue on slack about this toil.

**Comment by ostromart** [comment]
hey @ayj normally for merge conflicts in golden outputs, it's better to pull, and instead of manually resolving the conflicts, update the goldens again after the merge and just eyeball a couple to see that the diffs are reasonable.

**Comment by ayj** [comment]
Right. In this case "manually resolve" meant git wouldn't automatically resolve the merge :) I still need to manually pull, refresh golds, and re-push.

**Pull request merged**
