### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hiyosi**
Signed-off-by: Tomoya Usami <usami.tomoya@gmail.com>

correct the word. s/SPIFFEE/SPIFFE/

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by hiyosi** [comment]
I'm not sure. It seems not to be related to this change.

**Pull request merged**
