### PR TITLE
Add ability to set gateway container's lifecycle hooks

### PR DESCRIPTION
**Pull request by den-is**
**Please provide a description of this PR:**

Fulfills https://github.com/istio/istio/issues/47265 https://github.com/istio/istio/issues/47779 https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2131
In my company, we do not have any `kustomize` workflows or the ability to add it to our CI/CD.
The addition of the ability to set container `lifecycle` hooks does not interfere with any existing setups.

**Tests**
Test values yaml
```yaml
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh","-c","sleep 300"]
```

Render template
```sh
helm template \
./istio/manifests/charts/gateway \
--set name=istio-ingressgateway \
-f values-gw-test.yaml \
-s templates/deployment.yaml \
--dry-run --debug
```

Output with enabled preStop lifecycle hook:
```yaml
# Source: gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: kube-system
  labels:
    helm.sh/chart: gateway-1.0.0
    app: istio-ingressgateway
    istio: ingressgateway
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingressgateway
  annotations:
    {}
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: istio-ingressgateway
        istio: ingressgateway
    spec:
      serviceAccountName: istio-ingressgateway
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          env:
          lifecycle: 
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - sleep 300
          ports:
          - containerPort: 15090
            protocol: TCP
            name: http-envoy-prom
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
```

Output with empty `lifecycle: {}` var:
```yaml
# Source: gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: kube-system
  labels:
    helm.sh/chart: gateway-1.0.0
    app: istio-ingressgateway
    istio: ingressgateway
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingressgateway
  annotations:
    {}
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: istio-ingressgateway
        istio: ingressgateway
    spec:
      serviceAccountName: istio-ingressgateway
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          env:
          ports:
          - containerPort: 15090
            protocol: TCP
            name: http-envoy-prom
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
```

### CODE REVIEW

**Comment by ymesika** [comment]
/ok-to-test

You will probably want to add a release note for this

**Comment by den-pluto** [comment]
@ymesika 
Can't find anything about it in the Contribution notes.
Can you show me an example on how to add release notes?

**Review by howardjohn — CHANGES_REQUESTED** [review]
see my comments in https://github.com/istio/istio/issues/47779,this is not the right approach. If the current way doesn't meet use cases we should enhance it.

**Comment by den-pluto** [comment]
> see my comments in #47779 is not the right approach. If the current way doesn't meet use cases we should enhance it.

I'm not going to argue.
"I want this feature."
This is a very native kubernetes container feature which can be present in the default template in the official chart.

It is up to me whether enable it or not, and my responsibility - same way as if I insert it using kustomize, or cloning your chart and hosting altered version for myself.

And yes, I'm using `terminationGracePeriodSeconds + terminationDrainDuration` to solve the issue.

**Comment by howardjohn** [comment]
Thanks I understand your point of view but the projects position (after much discussion)is to keep the helm charts opinionated.

**Comment by linsun** [comment]
Adding a few @istio/wg-environments-maintainers for input.

@den-is is the requirement/pain point to not have gateway ready too fast so you add pre-stop hook?

**Comment by akamac** [comment]
I used to have preStop hook configured for Nginx Ingress + AWS ALB for zero downtime ingress updates. On receiving the SIGTERM I make health check to fail for ALB, while Nginx still accepting connections. Only once the target is down in AWS, the pod can be safely terminated.

**Comment by costinm** [comment]
I think the actual feature - ability to configure drain duration - is a pretty important one. 
I agree with John that adding the lifecycle hook is not the right approach - but I think adding an option ( or annotation on the gateway ) to indicate the desired drain duration/grace period as first class is not bad. 

The implementation should also take into account the new way of creating Gateways - managed 
by Istiod, which is what other non-Istio Gateways are using, we should not add features that only work on the helm-self-managed install.

**Comment by clayvan** [comment]
Please re-open and let this PR through.

> Thanks I understand your point of view but the projects position (after much discussion)is to keep the helm charts opinionated.

Yet, the helm chart allows configuration of several other fields such as tolerations, topologySpreadConstraints, affinity, etc.

> we tend to approve helm values PRs when there are multiple people/vendors asking for it.

There are tons of people in https://github.com/istio/istio/issues/47779 and https://github.com/istio/istio/issues/47265 asking for this. Having lifecycle hook support is critical for any ingress controller helm chart, they all have it except istio gateway.

> see my comments in https://github.com/istio/istio/issues/47779 is not the right approach. If the current way doesn't meet use cases we should enhance it.

This issue is still open because people can't agree on the fact the current way does not work. I would love it if there was native istio configuration to prevent this, but I don't believe it does from my testing. Whereas this lifecycle hook 100% works and is the simplest way for any ingress controller to avoid downtime. 

> is the requirement/pain point to not have gateway ready too fast so you add pre-stop hook? In the past

@linsun , no this preStop helps avoid downtime during gateway terminations. Please see https://github.com/istio/istio/issues/47265#issuecomment-1793535504

This PR will help your end users avoid downtime during rolling restarts. @howardjohn  Please reconsider your "projects position" on this PR as it has no downsides, and only major upsides.

**Comment by ryanmac8** [comment]
@howardjohn `terminationDrainDuration ` isn't a viable solution because we need a prestop hook so that we have a chance to inform the load balancer to remove the node from service and mark it as unhealthy before envoy receives a sigterm. Without the prestop hook and just `terminationDrainDuration `, the load balancer isn't made aware of envoy no longer receiving active connections and will cause client side errors.

**Comment by howardjohn** [comment]
@ryanmac8 can you help walk me through why a prestop informs the LB but terminationDrainDuration?

When envoy gets a SIGTERM **it does not stop serving traffic**. It immediately marks itself (or really, k8s does for us) as NotReady (which should stop the LB from sending it traffic). It also starts telling the LB to goaway directly with `connection:close` and `GoAway` messages.

I would expect preStop to be _worse_ because it doesn't send `connection:close` or `GoAway`

**Comment by howardjohn** [comment]
> terminationDrainDuration and SIGTERM causes new connections to close. This means that connections now are being denied.

Can you provide more details? That is neither how it was designed, nor how it works in out testing. If it is, it is a bug.

**Comment by dglushenok** [comment]
I'm facing the same issue with Envoy not accepting new connections in grace period. Here is the log:
```
2024-05-14T12:10:36.458809Z	info	Status server has successfully terminated
2024-05-14T12:10:36.458917Z	error	accept tcp [::]:15020: use of closed network connection
2024-05-14T12:10:36.458926Z	info	Agent draining Proxy
2024-05-14T12:10:36.459891Z	info	Graceful termination period is 5s, starting...
2024-05-14T12:10:38.008177Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2024-05-14T12:10:40.008368Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2024-05-14T12:10:41.461878Z	info	sds	SDS server for workload certificates started, listening on "./var/run/secrets/workload-spiffe-uds/socket"
2024-05-14T12:10:41.461119Z	info	Graceful termination period complete, terminating remaining proxies.
2024-05-14T12:10:41.461163Z	warn	Aborted proxy instance
2024-05-14T12:10:41.461193Z	warn	Aborting proxy
2024-05-14T12:10:41.461668Z	info	Envoy aborted normally
2024-05-14T12:10:41.461683Z	info	Agent has successfully terminated
```

Since 12:10:36 new connections to the terminating pod getting timed out (but external load balancer still routing them to the pod).

Istio v1.19.7, Kubernetes v1.27.3.

**Comment by ku524** [comment]
@howardjohn
Hmm, but istio docs says as following:
>The amount of time allowed for connections to complete on proxy shutdown. On receiving SIGTERM or SIGINT, istio-agent tells the active Envoy to start gracefully draining, discouraging any new connections and allowing existing connections to complete. It then sleeps for the termination_drain_duration and then kills any remaining active Envoy processes. If not set, a default of 5s will be applied.
source: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/

Doesn't the term "discourage" mean "deny"? What do you mean it's not design?

**Comment by ku524** [comment]
Oh I found issue in envoy repo. They says it block new connection when graceful shutdown starts. ([Link](https://github.com/envoyproxy/envoy/issues/19369#issuecomment-1028140920))

**Pull request closed without merging**
