### PR TITLE
setup access logs for BlackHoleCluster too

### PR DESCRIPTION
**Pull request by dwradcliffe**
Fixes https://github.com/istio/istio/issues/14110

cc @aaronmell

### CODE REVIEW

**Comment by aaronmell** [comment]
Awesome!

**Comment by howardjohn** [comment]
@dwradcliffe looks like there are some merge conflicts?

**Comment by dwradcliffe** [comment]
Rebased

**Comment by lei-tang** [comment]
https://github.com/istio/istio/issues/14364

Based on https://github.com/istio/istio/commits/master, the test istio.io/istio/tests/integration/security/sds_vault_flow in prow/integ-security-k8s-presubmit-tests.sh
starts to fail after this commit 3ef69ae. Before the commit 3ef69ae, this test succeeds (e.g, 41ea3ce, 52539f3, and e750114). Therefore, this commit 3ef69ae breaks the test istio.io/istio/tests/integration/security/sds_vault_flow in prow/integ-security-k8s-presubmit-tests.sh.

@dwradcliffe, can you revise this PR to not break prow/integ-security-k8s-presubmit-tests.sh?

**Pull request merged**
