### PR TITLE
remove resource version from service

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

it is useless, current we do not convert k8s service.rv to it

### CODE REVIEW

**Comment by howardjohn** [comment]
don't we set it here: https://github.com/istio/istio/blob/4952ac4d8c4d7a27678476fce56c1a9b2161040a/pilot/pkg/serviceregistry/kube/conversion.go#L120?

**Comment by hzxuzhonghu** [comment]
Yes, we set it, but not used later. I could not imagine what's the use case for future

**Comment by howardjohn** [comment]
the original PR was to use it for adsc xds client. Not sure more context
but I don't know that it's useless.

Unfortunately we don't have any tests and I am not familiar with the use
cases

**Comment by hzxuzhonghu** [comment]
But the original pr does not convert k8s svc resource version only SE rv, so i think no one is using it

**Comment by howardjohn** [comment]
It does here https://github.com/istio/istio/blob/4952ac4d8c4d7a27678476fce56c1a9b2161040a/pilot/pkg/serviceregistry/kube/conversion.go#L120?

**Pull request closed without merging**
