### PR TITLE
gateway-api: update types to read v1beta1

### PR DESCRIPTION
**Pull request by howardjohn**
The upstream API is dropping support for the v1alpha2 types for
HTTPRoute, Gateway, and GatewayClass in the next release. So, unlike
Istio where we always read the alpha versions in Istiod, we must
switch to reading the beta types or users on v0.6.0 (next release of
API) will be broken.

This means that the minimum version of the API is v0.5.0; most users are
upgrading quickly since v0.4.0 was still an alpha API.

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Review by costinm — APPROVED** [review]

**Comment by costinm** [comment]
I think API moving to beta is a perfect moment to start recommending users, starting with 1.16, to use HttpRoute and k8s Gateway in preference to VS/old Istio Gateway. 

And maybe start updating istio.io examples.

**Comment by howardjohn** [comment]
Frank is working on a huge docs pr for this:
https://github.com/istio/istio.io/pull/12021

**Pull request merged**
