### PR TITLE
Optimize istioctl pc workload summary

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Grouping workloads by namespace and then by name makes the summary more straightforward, including info like waypoint, protocol...

### CODE REVIEW

**Comment by GregHanson** [comment]
not sure if this has come up before, but should we mimic the ordering returned by `istioctl ps`?
```
istioctl ps | awk '{print $1}'
NAME
httpbin-86869bccff-jj4xb.default
httpbin-86869bccff-qwfkz.test
istio-ingressgateway-665d458c4-rdjds.istio-system
sleep-9454cc476-lmf4s.test
sleep-9454cc476-pw9kw.default
```
there is no `NAMESPACE` column since namespace is appended to `NAME`, and list is sorted alphabetically on the joined value

**Comment by hanxiaop** [comment]
> not sure if this has come up before, but should we mimic the ordering returned by `istioctl ps`?
> 
> ```
> istioctl ps | awk '{print $1}'
> NAME
> httpbin-86869bccff-jj4xb.default
> httpbin-86869bccff-qwfkz.test
> istio-ingressgateway-665d458c4-rdjds.istio-system
> sleep-9454cc476-lmf4s.test
> sleep-9454cc476-pw9kw.default
> ```
> 
> there is no `NAMESPACE` column since namespace is appended to `NAME`, and list is sorted alphabetically on the joined value

@GregHanson I do think we can have the similar format to these summaries, however not sure which one is better.
This optimization is similar to `kubectl -A get`, where the summaries are sorted by namespace firstly.

Since we have things like namespaced waypoint, I was thinking we could do similar things to improve the readability of the summary. Or how do you think about adding a similar namespace filtering like https://github.com/istio/istio/pull/45919?

**Review by GregHanson — APPROVED** [review]

**Comment by hanxiaop** [comment]
Add `release-notes-none` since currently this command is still hidden to users.

**Pull request merged**
