### PR TITLE
pilot: cluster use select all endpoints if label is empty

### LINKED ISSUE #23821: TLS origination for egress traffic gets 503
**Bug description**
I am following the user guide and testing this step
https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-tls-origination/#tls-origination-for-egress-traffic

$kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - http://edition.cnn.com/politics
HTTP/1.1 503 Service Unavailable
date: Wed, 13 May 2020 18:32:28 GMT
server: envoy
content-length: 0

curl to https succeeds
$kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - https://edition.cnn.com/politics
HTTP/2 200 
content-type: text/html; charset=utf-8
x-servedbyhost: ::ffff:127.0.0.1

**Expected behavior**
curl command should return 200

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$istioctl version
client version: 1.6.0-beta.1
control plane version: 1.6.0-beta.1
data plane version: 1.6.0-beta.1 (3 proxies)

**How was Istio installed?**
$istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

### PR DESCRIPTION
**Pull request by lambdai**
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

Thanks @howardjohn 

Fix #23821

### CODE REVIEW

**Comment by lambdai** [comment]
See if existing tests passes

**Comment by jacob-delgado** [comment]
This should also be put into `master` once we get this merged.

**Comment by lambdai** [comment]
> This should also be put into `master` once we get this merged.

With additional tests :)

**Comment by ericvn** [comment]
Manual cherrypick to master in https://github.com/istio/istio/pull/24468

**Pull request merged**
