### PR TITLE
Finish Spin-off of Prow Unit Tests and Fix Typo

### PR DESCRIPTION
**Pull request by chxchx**
See [Istio Prow Presubmit Profiling and Improvement Plan](goo.gl/csC4Tr) for more details

/assign @yutongz @sebastienvas

### CODE REVIEW

**Comment by chxchx** [comment]
Doc now linked in the PR description

**Comment by ldemailly** [comment]
out of curiosity which PR broke it and how come that PR passed tests ?

**Comment by rkpagadala** [comment]
test-infra codebase enabled the test, which surfaced broken tests in this repo.

**Comment by chxchx** [comment]
@ldemailly 
This PR actually fixed the failing prow unit tests. The error was the extra space in `# !/bin/bash`. Since Prow config was in test-infra repo, there is no way to do an atomic PR to both create the test and enable the test. After I updated the Prow config the bug I just mentioned surfaced and I fixed it in 10 min. Unfortunately, this job takes longer than that to run, and many PRs were testing with the buggy unit test job.

TL;DL It has been fixed!

**Comment by ldemailly** [comment]
sorry I wasn't clear, I know it was fixed by this pr, I asked when/how did break (which PR this PR fixes)

**Comment by hklai** [comment]
Yes it will be good to root cause this and find the PR that broke things, and prevent that from happening again. Charles, do you know?

**Comment by chxchx** [comment]
@ldemailly @hklai 

The issue of having an extra space in `# !/bin/bash` was introduced when the file `prow/istio-unit-tests.sh` was first created in this PR https://github.com/istio/istio/pull/2740, which passed all checks because `prow/istio-unit-tests.sh` was not triggered, and for Prow to trigger this test we have to add this job to the config map of Prow in istio/test-infra, a **different** repo from istio/istio that https://github.com/istio/istio/pull/2740 based on. Therefore, like aforementioned, there is **no way to atomically create the test and enable the test**. After the test was enabled in testinfra, the issue of having an extra space in `# !/bin/bash` surfaced and was fixed under 10 minutes. However, other PRs that started testing in this period had yet to pick up the fix and were therefore failed.

**Comment by hklai** [comment]
I see. Thanks Charles.

**Comment by ldemailly** [comment]
thx for the details @chxchx !
I hope we get that vm test integrated soon (though I'm concerned it may be broken on master again by now)

**Pull request merged**
