### PR TITLE
revert caching server state

### PR DESCRIPTION
**Pull request by ramaraochavali**
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
/retest

https://github.com/istio/istio/issues/18032

**Comment by ramaraochavali** [comment]
@howardjohn  Thanks for merging this. Looking at the readiness probe a bit more, I see inconsistency with how `receivedFirstUpdate`  is used https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/status/ready/probe.go#L79. For hot restarts we do not look at this - Even if we look at stats at the time of hot restart, the child Envoy will have the same stats values as parent Envoy (as counters are copied over) even though child did not receive an update from pilot. 

So what is the expectation here - during hot restart should we care about Envoy receiving a first update? If yes, we need to think about a different approach here. 

One another thing I was thinking about caching these states in general is, since we are concerned about hot restart, should we reset the cached values at the time of hot restart - so that we get the benefit of not pinging Envoy every time for the value which does not change  but also take care of the the concern during hot restart?

@lambdai @hzxuzhonghu WDYT?

**Comment by howardjohn** [comment]
@ramaraochavali during a hot restart we copy LDS and CDS from the child, right? so we have always received the "first update" in that sense? Resetting on hot restart sounds good but I am not sure how it would work? There is a 60s period of time where we have both Envoys still running, at which point do we reset the stat?

**Comment by ramaraochavali** [comment]
> during a hot restart we copy LDS and CDS from the child, right?

No during hot restart - the new (child) Envoy get all the config again from Pilot. It does not copy from old (parent) envoy.

> Resetting on hot restart sounds good but I am not sure how it would work? There is a 60s period of time where we have both Envoys still running, at which point do we reset the stat?

That is a good point.  I have n't exactly thought about where exactly to reset it, but if it is a direction we want to pursue, I can dig deep

**Comment by lambdai** [comment]
@ramaraochavali Thank you for the change!

> One another thing I was thinking about caching these states in general is, since we are concerned about hot restart, should we reset the cached values at the time of hot restart - so that we get the benefit of not pinging Envoy every time for the value which does not change but also take care of the the concern during hot restart?

SG. Although I think the value is rather small, since I think envoy should be able to handle the /server_info in time. My general point is that we'd better don't rely on the implementation details of hot restart. It is usually tricky and best efforts. 

I also need to admit that some details are critical. Such as the stat reset. Thank you for looking into it!

**Comment by ramaraochavali** [comment]
@lambdai I think for the first problem, we should look at the presence of `membership_total` metric of `BlackHoleCluster` - That would not be imported during hot restart and that cluster is guaranteed to be created on the first CDS response from Pilot - The absence of it indicates Envoy did not receive first response. We do not have to look at LDS also.  For now, we can make a  change to look at this stat every time (remove caching) so that we can catch hot restart missing issue. 
Once it is done, we can look a the optimization of caching the state and resetting it later if it becomes a real problem later. WDYT?

**Comment by ramaraochavali** [comment]
@lambdai pushed this PR https://github.com/istio/istio/pull/18164 - see if this makes sense.

**Pull request merged**
