### PR TITLE
Backport: #17866 Allow setting lifecycle to proxy containers

### PR DESCRIPTION
**Pull request by k0da**
This is backport of https://github.com/istio/istio/pull/17866

Signed-off-by: Dinar Valeev <k0da@opensuse.org>

### CODE REVIEW

**Comment by k0da** [comment]
@rlenglet done

**Comment by rlenglet** [comment]
The [`integ-new-install-k8s-tests_istio_release-1.3` test failure](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/19540/integ-new-install-k8s-tests_istio_release-1.3/147) doesn't seem related to this PR:
```
+ make test.integration.new.installer
KUBECONFIG=/root/.kube/kind-config-istio-testing kubectl apply -k github.com/istio/installer/kustomize/cluster
error: rawResources failed to read Resources: Load from path crds-namespace.gen.yaml failed: evalsymlink failure on '/tmp/kustomize-852665822/kustomize/cluster/crds-namespace.gen.yaml' : lstat /tmp/kustomize-852665822/kustomize/cluster/crds-namespace.gen.yaml: no such file or directory
tests/integration/tests.mk:67: recipe for target 'test.integration.new.installer' failed
make: *** [test.integration.new.installer] Error 1
```
@sdake does that ring a bell?

**Comment by k0da** [comment]
@rlenglet It doesn't looks like I have a permission to add anything to a release notes draft

**Comment by rlenglet** [comment]
> It doesn't looks like I have a permission to add anything to a release notes draft

@k0da that'd weird. Please post in a comment here and I'll add it. Thanks!

**Comment by k0da** [comment]
@rlenglet 
**installation**
- **Feature** added an ability to set lifecycle for proxy containers (https://github.com/istio/istio/pull/19540)

**Pull request merged**
