### PR TITLE
stats: bump wasm to v3

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
/assign @jplevyak 
I think it's just the version, the structure is the same.

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
I put a hold in case you want @jplevyak to review as well - feel free to remove though

**Comment by kyessenov** [comment]
The tests will validate.

**Comment by kyessenov** [comment]
/retest 
Flake #1.

**Comment by kyessenov** [comment]
/retest
Flake #2

**Comment by mandarjog** [comment]
@kyessenov all multi cluster tests are failing, is it related to the change ?

**Comment by kyessenov** [comment]
I don't really understand what failed.

**Comment by bianpengyuan** [comment]
Superseded by https://github.com/istio/istio/pull/23265.

**Pull request closed without merging**
