### PR TITLE
Introduce remote secret name parameter for "istioctl x create-remote-secret"

### PR DESCRIPTION
**Pull request by libesz**
In certain managed Kubernetes environments, there may be multiple secrets linked to a newly created ServiceAccount by default (i.e. RedHat OpenShift on IBM Cloud). Following the instructions covered [here](https://istio.io/latest/docs/setup/additional-setup/external-controlplane/#set-up-the-control-plane-in-the-external-cluster) in these environments will fail currently with the following error:

```
❯ istioctl x create-remote-secret \
  --context="${CTX_REMOTE_CLUSTER}" \
  --type=config \
  --namespace=external-istiod
error: could not get access token to read resources from local kube-apiserver: wrong number of secrets (2) in serviceaccount external-istiod/istiod-service-account
```

`istioctl x create-remote-secret` command is currently restricted in a way that it cannot succeed if there are more than one secret linked to the `remote` ServiceAccount, which is the base of the credential generation in the current cluster.
This PR eliminates the limitation by introducing a new CLI parameter for the command. The parameter is required only when there are more than one secrets, which means the functionality is meant to be BW compatible.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by linsun** [comment]
@libesz thanks for your first contribution!  LGTM - @esnible & @stevenctl  could you take a look?

**Review by nmittler — APPROVED** [review]

**Review by stevenctl — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]
Thanks

**Pull request merged**
