### PR TITLE
minor refactor to dns proxy

### PR DESCRIPTION
**Pull request by ramaraochavali**
Allow only one query to same Qname, Qtype and Qclass and use the same response for other queries.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Just searched coredns usage, this option is disabled.

https://github.com/coredns/coredns/blame/5b9b079dabc7f71463cea3f0c6a92f338935039d/notes/coredns-008.md#L45

**Comment by ramaraochavali** [comment]
Right now  we have one issue with dns proxy, where when a pod sends a health check requests to another pod that is not available (so not available in our name table) - it just fills with dns logs (to multiple search  domains) and during that time the dns proxy is not able to respond to regular DNS queries(that are available in the name table also) -  I was guessing that it is swamped with upstream queries and this might help. If it is disabled - Is there any alternative? Does it cache? or should we cache  no answers/nxdomain responses with  a TTL?

**Comment by howardjohn** [comment]
>  and during that time the dns proxy is not able to respond to regular DNS queries(that are available in the name table also)

Why not? it should allow parallel queries?

I am a bit concerned with using a setting coredns does not

**Comment by ramaraochavali** [comment]
> Why not? it should allow parallel queries?

Yes It should.  I am wondering if going to upstream for multiple queries is causing this thing to happen.

> I am a bit concerned with using a setting coredns does not

I agree. When I added this PR - I did not know that it is not being used by coredns.

Let me debug more and I will update the PR

**Comment by ramaraochavali** [comment]
@howardjohn @hzxuzhonghu I spent some time today trying to understand the reason for the flag removal in core dns. Here is the PR that removed it https://github.com/coredns/coredns/pull/717 and as mentioned in the PR - it was removed because it was interfering with upstream health checks. Since we do not use that - I think it is safe to use.

Also this comment from miekg  - indicates it is nice to use and seems better than caching.
```
Singleinflight does have some nice properties, but I've opted to rip it
out entirely. Caching should almost (but not quite) as good.
```

Let me know what you think.

**Comment by hzxuzhonghu** [comment]
@ramaraochavali Dns proxy is unlike coredns, it is mostly serving only one application dns requests, so most of the time very idle.

**Comment by ramaraochavali** [comment]
> Dns proxy is unlike coredns, it is mostly serving only one application dns requests, so most of the time very idle.

I think it is only partially true if the application in our case where this problem exists is a monolith (combination of multiple services that does DNS lookups in parallel. Is there any downside of adding it?

**Comment by hzxuzhonghu** [comment]
From the original issue: https://github.com/coredns/coredns/issues/715 

If dns proxy has three upstream dns servers(kube-dns), after enabling singleInflightQuery, if one instance failed, all the concurrent dns requests would fail.

**Comment by ramaraochavali** [comment]
Yes. That is caused by health check not by that flag. The combination of flag and healthcheck caused that issue. See the resolution notes here coredns/coredns#717 .

IMO it is not a problem to use for us because we do not use health checks. But if it is controversial - I can remove that flag and leave the rest of refacor.

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
