### PR TITLE
Patch bootstrap

### PR DESCRIPTION
**Pull request by GregHanson**
**Please provide a description of this PR:**

Resolves https://github.com/istio/istio/issues/38285

### CODE REVIEW

**Comment by GregHanson** [comment]
Also, appears https://github.com/istio/istio/pull/38264 may also dependent on https://github.com/istio/istio/pull/38124 which I included in this PR.  I'm not sure if any other changes between master and release-1.13 are also required to be pulled in

**Comment by GregHanson** [comment]
cc @yangson1

**Comment by GregHanson** [comment]
adding `hold` until confirmation that no further changes are required for this cherry-pick

**Comment by GregHanson** [comment]
cc @stevenctl

**Review by stevenctl — APPROVED** [review]

**Comment by stevenctl** [comment]
Do we still need the hold?

**Pull request merged**
