### PR TITLE
add MultipleYAMLDiff func and fix invalid unit test

### PR DESCRIPTION
**Pull request by nicole-lihui**
**Please provide a description of this PR:**
- add multiple YAML diff fun
- fix operator_test invalid unit test

### CODE REVIEW

**Comment by nicole-lihui** [comment]
not stale

**Review by morvencao — COMMENTED** [review]
thanks!
this looks good, but we have many other places still using the `YAMLDiff` function, did you tried to replace all of them?

**Comment by nicole-lihui** [comment]
> thanks! this looks good, but we have many other places still using the `YAMLDiff` function, did you tried to replace all of them?
@morvencao 
Good idea, I will finish it next

**Review by morvencao — APPROVED** [review]

**Pull request merged**
