### PR TITLE
convert galley validation metrics to opencensus

### PR DESCRIPTION
**Pull request by tangiel**

### CODE REVIEW

**Comment by tangiel** [comment]
Hmm, didn't realize that one of these test failures was actually relevant. It seems that because Opencensus doesn't export 0 state metrics, it's causing the dashboard test to fail.

**Comment by tangiel** [comment]
Can we somehow trigger the cert key metric in question? I'm not familiar enough with Galley to know what would need to be done, but it looks like the test setup triggers some traffic, presumably to generate graph data.

**Comment by ayj** [comment]
`galley_validation_cert_key_updates` is only updated when the cert/key changes. We could update the metric on the initial cert/key load [here](https://github.com/istio/istio/blob/1d01280b2e36956ddc7d084546f309cb86a2cf20/galley/pkg/crd/validation/webhook.go#L172) to workaround the problem. 

Are there any other metrics that are failing?

**Comment by tangiel** [comment]
We could add a workaround, but if I'm going to add more graphs, we might encounter the same issues. I didn't see any other metrics failing, but not sure if the test stops at the first failure or not (my understanding is "not").

**Pull request merged**
