### PR TITLE
istioctl workload: put proxyConfig.proxyMetadata in cluster.env

### LINKED ISSUE #29125: istioctl x workload entry configure --autoregister does not work as doc'd
On Istio 1.8, you use the 

```
istioctl x workload entry configure -f workloadgroup.yaml -o "${WORK_DIR}" --autoregister
```

command to create a set of files that can be used to configure a VM to participate on the mesh. 

Part of that is a file called `mesh.yaml` which eventually should be placed in `/etc/istio/config/mesh` on the VM. This produces a file like this:

```
discoveryAddress: istiod.istio-system.svc:15012
proxyMetadata:
  CANONICAL_REVISION: latest
  CANONICAL_SERVICE: python-http
  DNS_AGENT: ""
  ISTIO_META_AUTO_REGISTER_GROUP: python-http
  ISTIO_META_CLUSTER_ID: Kubernetes
  ISTIO_META_DNS_CAPTURE: "true"
  ISTIO_META_MESH_ID: ""
  ISTIO_META_NETWORK: ""
  ISTIO_META_POD_PORTS: '{}'
  ISTIO_META_WORKLOAD_NAME: python-http
  ISTIO_METAJSON_LABELS: '{"app":"python-http","service.istio.io/canonical-name":"python-http","service.istio.io/canonical-version":"latest"}'
  POD_NAMESPACE: vm-services
  SERVICE_ACCOUNT: my-vm
  TRUST_DOMAIN: cluster.local
tracing:
  zipkin:
    address: zipkin.istio-system:9411
```

When you star the proxy, the correct metadata as specified by this meshConfig file does not get placed correctly into the bootstrap/proxy/metadata segment. The reason for this is it's not a properly formatted meshConfig object and in this line where we try parse/extract it:

https://github.com/istio/istio/blob/47a5927bdc7df6d9ebde75c426c8b6d5ca2dc493/pkg/config/mesh/mesh.go#L153

Even after this formatting is fixed, the metadata is still not properly placed on the node for autoregistration to work.

/cc @stevenctl

### PR DESCRIPTION
**Pull request by stevenctl**
fixes #29125 

Setting the environment via istioctl via the proxyConfig annotation or any values we generate in the proxy config. 
This will work to properly use meshConfig/proxyConfig for VMs but only when using istioctl. 

I do think agent should be capable of using proxyConfig directly, or should emit warnings for all values specified in proxyMetadata via the proxyConfig _file_ that aren't also in the environment. It seems confusing that we ignore so much of this file.

cc @howardjohn @christian-posta

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM. Since this doesn't touch any tests I am guessing that means we are lacking some test coverage somewhere... possibly as unit tests for the command?

**Comment by howardjohn** [comment]
Test failure looks real

**Comment by stevenctl** [comment]
The new test doesn't really cover everything, especially flags, but it does bring us from 25% to 75% coverage.

**Review by howardjohn — APPROVED** [review]
Thanks for adding tests as well!

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
