### PR TITLE
Adjust code logic in push_context.go

### PR DESCRIPTION
**Pull request by sniperking1234**
Adjust code logic in push_context.go

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Can you give more info about what bug you are fixing and add a test case to cover this?

**Comment by sniperking1234** [comment]
@howardjohn In the previous version, if the length of `matchedEnvoyFilters` is equal to 0, there is no need to enter the following for loop. So I put this code in the above if judgment statement. This change will not affect other functions.
image

**Comment by carolynhu** [comment]
> @howardjohn In the previous version, if the length of `matchedEnvoyFilters` is equal to 0, there is no need to enter the following for loop. So I put this loop in the above `if` judgment statement. This change will not affect other functions.
> image

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/wiki/Development-Conventions#superfluous-changes. I am not sure what benefit this has

**Comment by sniperking1234** [comment]
In my IDE this code has warnings. So I changed the code order and did not affect the function.
If this is superfluous, please close this PR.
image

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
