### PR TITLE
test framework: don't require UID 1 for echo container

### PR DESCRIPTION
**Pull request by dgn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by dgn** [comment]
> doesn't this mean it will run as root by default? I think someone added this so it does _not_ run as root

> Or if you have a PSP to say run as UID X-Y it will automatically assign one? Not very familiar with PSP

Oh, that changes things. Yes, PSPs restrict to UID and will not allow pods with containers where runAsUser=0 - but on OpenShift, you'll usually be assigned a random one automatically, and if you specify one that isn't in the range, it fails.

**Comment by dgn** [comment]
I just checked: PSPs with runAsUser restrictions will reject illegal UIDs but also default to the first UID in the legal range: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups

**Comment by howardjohn** [comment]
Got it, we may have previously explicitly set to 0 before which prompted
the PR to change to 1. Sounds like this should work ok. Thanks

**Comment by dgn** [comment]
Thank you for checking!

**Pull request merged**
