### PR TITLE
Add unit test for clusterID Equals.

### PR DESCRIPTION
**Pull request by Chen-Xintong**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
Please add some more valuable tests

**Comment by Chen-Xintong** [comment]
> Please add some more valuable tests

Hi @hzxuzhonghu, do you mean we need to add more test cases for this function or this test case is not needed? Thx.

**Comment by hzxuzhonghu** [comment]
I mean this is invaluable.

**Comment by Chen-Xintong** [comment]
> I mean this is invaluable.

Sure, we can close this PR.

**Pull request closed without merging**
