### PR TITLE
add http cookie test case

### PR DESCRIPTION
**Pull request by ramaraochavali**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
do you want to test session persistence? I am not sure how this works, it just call successed without checking requests being handled consistently by one instance, right?

**Comment by ramaraochavali** [comment]
The callOptions use consistentHostChecker and I think that does that validation that the request goes to the same pod.

**Review by hzxuzhonghu — COMMENTED** [review]
I believe we donot set cookie on client side, the correct way is to set http.Client.Jar

**Comment by ramaraochavali** [comment]
First case is envoy generated cookie.

**Comment by hzxuzhonghu** [comment]
Yes, no matter how, the client should be able to take the cookie when it calls server

**Comment by hzxuzhonghu** [comment]
@ramaraochavali In the test, the HTTP client is initiated each time it sends a request, so it will never take the cookie from previous response when envoy generate the cookie.

**Comment by ramaraochavali** [comment]
> In the test, the HTTP client is initiated each time it sends a request, so it will never take the cookie from previous response when envoy generate the cookie.

Ok. Let me take a look.

**Comment by ramaraochavali** [comment]
@hzxuzhonghu Can you point me where a different client is created for each request?

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
@ramaraochavali [pkg/test/echo/server/forwarder/util.go#L114~140](https://github.com/istio/istio/blob/master/pkg/test/echo/server/forwarder/util.go#L114-L138) look at here, each request is initiated with a separate go routine.

So definitely it has not respected the response cache.

**Comment by hzxuzhonghu** [comment]
I am OOO in Kubecon cloud-native Con China, and next week, it is the Chinese festival, I will be back until the seventh of October

**Comment by ramaraochavali** [comment]
@hzxuzhonghu PTAL - I have updated the code to pass back the cookie

**Review by hzxuzhonghu — COMMENTED** [review]
It is almost correct, but one left, still need to control sending requests in serial https://github.com/istio/istio/blob/master/pkg/test/echo/server/forwarder/util.go#L114-L138

**Comment by ramaraochavali** [comment]
> still need to control sending requests in serial

did not know about this. Thanks

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
