### PR TITLE
Use a single shared SDS cluster

### PR DESCRIPTION
**Pull request by howardjohn**
Split out of https://github.com/istio/istio/pull/21038 because that PR
got a bit too complicated

### CODE REVIEW

**Comment by howardjohn** [comment]
for https://github.com/istio/istio/issues/20697

**Comment by JimmyCYJ** [comment]
Is there any performance improvements by replacing Google gRPC with Envoy gRPC?

**Comment by howardjohn** [comment]
This has huge performance impact on Pilot, since the XDS response size is greatly reduced. I didn't get hard numbers on that impact yet though. In terms of the performance for SDS, I don't think that is a major factor we are worried about. The reason for the switch is that we can't have a single cluster with google gRPC as far as I can tell

**Comment by howardjohn** [comment]
I'll run some tests and update this

**Comment by howardjohn** [comment]
This drops XDS response size by 10%, so pretty substantial for such an easy change

**Pull request merged**
