### PR TITLE
Fix Docker build on OSX

### PR DESCRIPTION
**Pull request by nmittler**
Adding cross-compile targets for linux and always include linux images in Docker.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Note that if you want to create the Docker images with the current Makefile, you can with `GOOS=linux make clean init test-bins build docker  docker.push HUB=x TAG=y` which will build the binaries for Linux so the correct images are built and pushed. 

That said, I'll be glad to take a look at this..

**Comment by nmittler** [comment]
@ericvn 

Understood, but that's not a great developer workflow.  It should just work.

**Pull request merged**
