### PR TITLE
Inject CSI volume for GKE workload certificates

### PR DESCRIPTION
**Pull request by lei-tang**
**Please provide a description of this PR:**
https://github.com/istio/istio/issues/35385

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Monkeyanator — APPROVED** [review]
LGTM, approved with hold pending a nit on the field documentation

**Comment by lei-tang** [comment]
@howardjohn All review comments have been addressed. Can you take another look? Thanks!

**Review by howardjohn — APPROVED** [review]
networking changes lgtm

**Pull request merged**
