### PR TITLE
Specify resources for the proxy_init container

### PR DESCRIPTION
**Pull request by wmuizelaar**
The resources can we set with helm through 
--set global.proxy_init.resources

### CODE REVIEW

**Comment by ostromart** [comment]
We're trying to limit the helm options as it's already getting out of hand. This strikes me as a rather specific/narrow rather than general option since it's just one particular container.
What's the use case and who's asking for it?

**Comment by ostromart** [comment]
Sure, that seems reasonable. @costinm thinks there may be something already doing this in the pipeline but I couldn't find it so please go ahead.

**Comment by wmuizelaar** [comment]
@ostromart ok, pushed a new commit!

**Comment by GregHanson** [comment]
@wmuizelaar does `make test` pass locally for you?  The the helm inject unit tests are failing in prow and circleci

**Comment by wmuizelaar** [comment]
@GregHanson I'm sorry - no. I'm trying to get all the local things setup now to get them fixed, will update the PR when done!

**Comment by wmuizelaar** [comment]
@GregHanson I saw the e2e-bookinfoTests-v1alpha3.sh fail on other PR's as well - couldn't find a link in the output to my specific changes. Can you confirm? Thanks!

**Comment by wmuizelaar** [comment]
anyone? @GregHanson @ostromart

**Comment by GregHanson** [comment]
@wmuizelaar the prow unit test job had a bug, should be fixed now.  Please resolve the conflicts in your branch and then it should be good to go after the tests rerun

**Comment by wmuizelaar** [comment]
@GregHanson I think I hit another test-failure on master when I rebased...  :/

**Comment by wmuizelaar** [comment]
@GregHanson and did a rebase again, it now looks better, at least all the required tests are succesful now!

**Pull request merged**
