### PR TITLE
Update istio logo for grafana istio-mesh-dashboard

### LINKED ISSUE #27553: grafana dashboards: istio logo is black on dark grey (almost invisible) - used to be white I believe
**Bug description**
grafana dashboards: istio logo is black on dark grey (almost invisible) - used to be white I believe

the best fix might be to change 
https://github.com/istio/istio.io/blob/master/static/img/istio-logo.svg
to be back to white like it was
https://github.com/istio/istio.io/blob/401989fba6fc0bb14fca4bd3c421854a1ceef16a/static/img/istio-logo.svg

but that may break other links who started to rely on the logo being black?

or start using https://github.com/istio/istio.io/blob/master/static/img/istio-bluelogo-nobackground-unframed.svg
(ie https://istio.io/latest/img/istio-bluelogo-nobackground-unframed.svg ) but that means it's only fixed in future releases/patches

there is probably some stylesheet or other magic to change the color irrespective of what is in the svg (but that's above my html knowledge)

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Visible logo

**Steps to reproduce the bug**
Open /istio-mesh-dashboard?orgId=1&refresh=5s
Screen Shot 2020-09-25 at 9 44 45 AM

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7

**How was Istio installed?**
/samples/addons/grafana.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
n/a

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/27553 and https://github.com/istio/istio/issues/24618

The black logo is not visible
https://github.com/istio/istio.io/blob/master/static/img/istio-logo.svg

```
$ kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons/grafana.yaml
```
old-grafana

Replaced by the blue logo.
https://github.com/istio/istio.io/blob/master/static/img/istio-bluelogo-nobackground-unframed.svg

```
$ kubectl apply -f https://raw.githubusercontent.com/shamsher31/istio/grafana-logo/samples/addons/grafana.yaml
```

grafana-istio-logo

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Review by ldemailly — APPROVED** [review]
Thank you! will this show up in 1.7 patches in addition to master/ 1.8

**Review by howardjohn — CHANGES_REQUESTED** [review]
Please update the source in `manifests/addons/dashboards`

**Comment by shamsher31** [comment]
> Please update the source in `manifests/addons/dashboards`

Will do. Thanks.

**Review by howardjohn — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
