### PR TITLE
Istioctl move handlers.go and move/add tests

### PR DESCRIPTION
**Pull request by irisdingbj**
- move istioctl/cmd/handlers.go into istioctl/pkg/util/handlers/handlers.go and move some common utility function into it

- move kubeinject test into it's own test file to align with the overall code structure.

- add tests for handleNamespace*

### CODE REVIEW

**Comment by howardjohn** [comment]
@irisdingbj needs a rebase

**Comment by irisdingbj** [comment]
> @irisdingbj needs a rebase

Thanks, just submitted the new one

**Comment by irisdingbj** [comment]
@esnible since I force pushed, the `lgtm` label is removed, can you add it again? the code change is the same.

**Comment by howardjohn** [comment]
/lgtm

for the rebase

**Pull request merged**
