### PR TITLE
Fix cannot get meshpolicies.authentication.istio.io

### LINKED ISSUE #16103: Kiali can't get meshpolicies.authentication.istio.io
**Bug description**
When installing and accessing Kiali via a Helm deploy I'm getting the following error message.
image

This can also be seen in the Kiali logs.
>I0807 14:38:42.179426       1 kiali.go:67] Kiali: Version: v0.20.0, Commit: 140969bc2ef1a77ca7387b47f8b23dcbd4818bd0
I0807 14:38:42.182276       1 kiali.go:68] DEBUG: Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml -v 4]
I0807 14:38:42.183506       1 config.go:461] DEBUG: Reading YAML config from [/kiali-configuration/config.yaml]
I0807 14:38:42.187114       1 kiali.go:203] Using authentication strategy [login]
I0807 14:38:42.189746       1 kiali.go:88] Kiali: Console version: 0.20.0
E0807 14:38:42.196942       1 kiali.go:106] Jaeger is not available : Get http:///api/services: http: no Host in request URL
I0807 14:38:42.198614       1 server.go:49] Server endpoint will start at [:20001/]
I0807 14:38:42.198649       1 server.go:50] Server endpoint will serve static content from [/opt/kiali/console]
I0807 14:38:42.198666       1 metrics_server.go:18] Starting Metrics Server on [:9090]
I0807 14:38:42.200218       1 kiali.go:135] Secret is now available.
I0807 14:40:08.297545       1 client.go:180] DEBUG: Rest perf config QPS: 175.000000 Burst: 200
I0807 14:40:08.298061       1 client.go:180] DEBUG: Rest perf config QPS: 175.000000 Burst: 200
I0807 14:40:08.404006       1 versions.go:140] DEBUG: Detected Istio version [root@ced2af60-b3ec-11e9-b2dc-4e6c8cb30ee5-docker.io/istio-1.2.3-c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty-Modified]
I0807 14:40:08.407193       1 discover.go:107] DEBUG: Kiali is looking for Tracing/Jaeger service ...
I0807 14:40:08.407343       1 discover.go:117] DEBUG: Kiali didn't found Tracing/Jaerger
W0807 14:40:08.601051       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a logentries list
W0807 14:40:08.606517       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a listentries list
W0807 14:40:08.612860       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a opas list
W0807 14:40:08.615699       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a fluentds list
W0807 14:40:08.626997       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a kubernetesenvs list
W0807 14:40:08.628208       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a edges list
W0807 14:40:08.632096       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a deniers list
W0807 14:40:08.632283       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a metrics list
W0807 14:40:08.632390       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a quotas list
W0807 14:40:08.632671       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a authorizations list
W0807 14:40:08.632784       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a stdios list
W0807 14:40:08.632900       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a listcheckers list
W0807 14:40:08.633318       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a statsds list
W0807 14:40:08.633444       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a cloudwatches list
W0807 14:40:08.633565       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a signalfxs list
W0807 14:40:08.633650       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a rbacs list
W0807 14:40:08.633751       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a redisquotas list
W0807 14:40:08.633853       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a stackdrivers list
W0807 14:40:08.633882       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a checknothings list
W0807 14:40:08.634007       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a apikeys list
W0807 14:40:08.634101       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a tracespans list
W0807 14:40:08.633949       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a noops list
W0807 14:40:08.634298       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a dogstatsds list
W0807 14:40:08.634349       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a circonuses list
W0807 14:40:08.634403       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a zipkins list

**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[x ] Developer Infrastructure

**Expected behavior**
To see the Istio MeshPolicy. This was working until recently.

**Steps to reproduce the bug**
- Uninstall _Istio_
- Uninstall _Istio-Init_
- Remove _Istio_ CRDs
- Delete _istio-system_ namespace
- Reinstall _Istio-Init_
- Reinstall _Istio_

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

> client version: 1.2.2
> citadel version: 1.2.3
> galley version: 1.2.3
> ingressgateway version: 1.2.3
> pilot version: 1.2.3
> policy version: 1.2.3
> sidecar-injector version: 1.2.3
> telemetry version: 1.2.3

> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <clyang@cn.ibm.com>

Fixed https://github.com/istio/istio/issues/16103

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jmazzitelli** [comment]
This PR most likely is not going to work. You cannot simply bump up the kiali version without also adding in addition things in the helm charts that that new kiali version needs (like additional permissions in its role).

The correct way to do this is to integrate the Kiali operator in the Istio installation and there will be less to have to worry about. So we need to get that work done sooner rather than later.

But in the meantime, this PR is most likely not going to work because moving from 1.1 to 1.4 likely going to need additional changes to the helm chart. Check out the 1.4 Kiali yaml files and do a diff to see what other changes are needed:  https://github.com/kiali/kiali/tree/v1.4/operator/roles/kiali-deploy/templates/kubernetes

**Comment by clyang82** [comment]
> This PR most likely is not going to work. You cannot simply bump up the kiali version without also adding in addition things in the helm charts that that new kiali version needs (like additional permissions in its role).
> 
> The correct way to do this is to integrate the Kiali operator in the Istio installation and there will be less to have to worry about. So we need to get that work done sooner rather than later.
> 
> But in the meantime, this PR is most likely not going to work because moving from 1.1 to 1.4 likely going to need additional changes to the helm chart. Check out the 1.4 Kiali yaml files and do a diff to see what other changes are needed: https://github.com/kiali/kiali/tree/v1.4/operator/roles/kiali-deploy/templates/kubernetes

I will revisit my previous PR for kiali operator in new installer and make it move forward. I just tried with version 1.4, it seems it is working. anyway, I will check if need adding more additional changes. I think we should fix this issue because the error will be popped up in each refresh.

**Comment by jmazzitelli** [comment]
> I think we should fix this issue because the error will be popped up in each refresh.

yup - that's why I wrote up this issue a while ago: https://github.com/istio/istio/issues/16435 "istio operator should be using kiali operator"

**Comment by clyang82** [comment]
> This PR most likely is not going to work. You cannot simply bump up the kiali version without also adding in addition things in the helm charts that that new kiali version needs (like additional permissions in its role).
> 
> The correct way to do this is to integrate the Kiali operator in the Istio installation and there will be less to have to worry about. So we need to get that work done sooner rather than later.
> 
> But in the meantime, this PR is most likely not going to work because moving from 1.1 to 1.4 likely going to need additional changes to the helm chart. Check out the 1.4 Kiali yaml files and do a diff to see what other changes are needed: https://github.com/kiali/kiali/tree/v1.4/operator/roles/kiali-deploy/templates/kubernetes

@jmazzitelli I compared 1.1 with 1.4. only service.yaml/ingress.yaml/deployment.yaml had changed since version 1.1. And  I do not think we need to make changes accordingly. some changes are already in and some changes are related with kiali operator. Thanks.

**Comment by clyang82** [comment]
close this PR since https://github.com/istio/istio/pull/16993 was in

**Pull request closed without merging**
