### PR TITLE
Patch #14973 to release-1.2

### PR DESCRIPTION
**Pull request by wattli**

### CODE REVIEW

**Comment by linsun** [comment]
@wattli seems only logging changes, can u explain why this is important for 1.2.x?

**Comment by wattli** [comment]
If makes the mTLS debugging much easier

**Comment by wattli** [comment]
@fpesce PTAL

**Comment by fpesce** [comment]
@wattli Any particular reason for why you didn't apply the label action/merge-to-release-branch and let mergify cherry pick that ?

**Comment by wattli** [comment]
@fpesce , i created once with the label, but it gave a mess :/

**Pull request merged**
