### PR TITLE
Fix incorrect ALS config

### PR DESCRIPTION
**Pull request by rshriram**
We were logging metadata headers incorrectly in the access log service.
These would log the same arbitrary value on both sender and receiver
and create problems in all the analysis systems. Per istio/envoy#121
and (preceding work on logging filter state), the correct way is to log
the filter state objects created by the metadata exchange filters.

If the filter state does not exist, the operation would be a no-op

Signed-off-by: Shriram Rajagopalan <rshriram@tetrate.io>

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@rshriram Seems there is an incompatibility bumping the api, so it is better to separate this pr into two: one is for api , and the other is for ALS

**Comment by rshriram** [comment]
But I can’t fix als without the api update :(

**Pull request merged**
