### PR TITLE
add volumes/volume mounts to ztunnel helm values/daemonset

### PR DESCRIPTION
**Pull request by EItanya**
**Please provide a description of this PR:**

This PR adds the ability to customize the zTunnel with additional volumes/volumeMounts.

this can be useful for adding certificates to the zTunnel or other tasks that require file system access.

### CODE REVIEW

**Review by kdorosh — APPROVED** [review]
lgtm

**Comment by EItanya** [comment]
Would this require release-notes?

**Comment by dhawton** [comment]
> Would this require release-notes?

No

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
