### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by jfcg**
Add Github CodeQL security checks for Go and Python.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Can you provide some context for this change?

**Comment by jfcg** [comment]
CodeQL has many checks, beneficial for web apps especially. An example for list of checks done: https://github.com/jfcg/sorty/runs/2319161287

**Comment by howardjohn** [comment]
I don't think we want to add a dependency on github actions.

Additionally, we already run a pretty large set of linters so it would be good to understand why this is better

**Comment by jfcg** [comment]
it is not a replacement for existing checks, and it does not have to be required for merging, but two eyes are better than one. maybe it'll catch something you are not checking.

**Comment by jfcg** [comment]
Btw in my fork under `/security/code-scanning` I see:

istio

**Pull request closed without merging**
