### PR TITLE
cherry pick the commit of the weight for pod antiaffinity term.

### PR DESCRIPTION
**Pull request by morvencao**
Merge https://github.com/istio/istio/pull/14419 to release-1.2

(cherry picked from commit 67846c4a068e9692e7d2a4d3dccf3cc99b9b35c7)

### CODE REVIEW

**Comment by sdake** [comment]
/hold

See master PR for proper technique for handling backports with new (to 1.2) infrastructure.  If that doesn't work (I know its active in docs repo, not certain about istio/istio), could you cherry-pick -x after that PR merges?  Also of note you can label a PR after it has merged and a backport will be triggered.  Pretty cool!

Cheers
-steve

**Comment by morvencao** [comment]
Auto-merge doesn't work for now, have cherry-picked he commit to release-1.2

**Comment by howardjohn** [comment]
I removed @sdake's hold as concerns have been addressed.

This fixes https://github.com/istio/istio/issues/14034

I think it is safe because only users who opt into affinity will be impacted

/lgtm

**Pull request merged**
