### PR TITLE
Add query reporter drop-down for Service and Workload Dashboard

### PR DESCRIPTION
**Pull request by carolynhu**
Do not review until community discussion is done.

Please provide a description for what this PR is for. https://github.com/istio/istio/issues/27595

After community discussion, we decide to add a query reporter drop-down to let user chose between either "reporter=source" or "reporter=destination" for the Service and Workload Dashboard

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by carolynhu** [comment]
Service Dashboard:
(1) General Section
1-1: "reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/1YEYl9cfTBhra04ZQwGnXkyFWxn46p2g?orgId=2
1-2: "reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/FO5W114pn5EKJdenHYlHF9TS8z4dEH1D?orgId=2

(2) Client Workloads Section:
2-1: "reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/mMqSprQQEUrQyELzYJnRVmMaaSJJ1wLQ?orgId=2
2-2: "reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/LekV026uU567CxOCyUbzDJUdQnr3CPzu?orgId=2

**Comment by carolynhu** [comment]
Workload Dashboard:
(1) General Section
1-1: "reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/P2XpzaejDh31BfguiGHxuZyDGr9i0ZsZ?orgId=2
1-2: "reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/Ow0zpBPrxT1YiHpoC5K2gR2v2NWH8qi0?orgId=2

(2) Inbound Workloads Section:
2-1: "reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/qivlqYUpKMLgwQ0o0AaBT2VYMMa2UT3V?orgId=2
2-2: "reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/dOZp344KjQJG475rN3UXTEiQPoGkfvaa?orgId=2

**Comment by douglas-reid** [comment]
Looking quickly at this, my reaction is that having multiple drop-down selectors for reporter is too much. If we go the drop-down route, let's keep it to a single one.

**Comment by howardjohn** [comment]
I agree with Doug, I was a bit confused about what each drop down did. I
think a single one will be more clear

**Comment by carolynhu** [comment]
hmm... my initial intention is to let user select reporter for different sections, okay, if that seems too much, let me shrink them into one

**Comment by carolynhu** [comment]
Update:
(1) Service Dashboard:
"reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/tgll8pZMRgEebOVo0d37dORnsiaz4bb2?orgId=2
"reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/ZwmPqHU7YhG5QpxFigM90Imh97nIFBhZ?orgId=2

(2) Workload Dashboard:
"reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/zVcSextJ1cqPOM43YQDARk60VpNmgt4n?orgId=2
"reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/33pqQoAXeTJ6vT1P3HVi6PXJsR60GXXG?orgId=2

**Comment by carolynhu** [comment]
Update:
(1) Service Dashboard:
"reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/SVuGenHApGGUkFuLUkN7KqpSqJAsHYfx?orgId=2
"reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/GescHkKEWx4L2F5Y3tIdpgQO5r8VbfNT?orgId=2

(2) Workload Dashboard:
"reporter=source"
https://snapshot.raintank.io/dashboard/snapshot/PuVjs0p9SgQ2oyfdWVmCxO89VJZQALOo?orgId=2
"reporter=destination"
https://snapshot.raintank.io/dashboard/snapshot/I4DuUpRNdJFPM5CY6LhhydosoGczPvjw?orgId=2

**Comment by carolynhu** [comment]
@douglas-reid @howardjohn ptal

**Comment by douglas-reid** [comment]
I think we need to figure out a better term for it. Is it possible with those drop-downs to have a different value than the text displayed?

Maybe we could call the drop-downs `Proxy` instead ?  Would that be obvious to someone not intimately familiar with Istio? 

@jmazzitelli what do you think here?

**Review by douglas-reid — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
