### PR TITLE
fix(helm): render service account properly when adding annotations

### PR DESCRIPTION
**Pull request by schahal**
**Please provide a description of this PR:**

This should fix `Issue`: https://github.com/istio/istio/issues/51289

Though that issue is `Closed`, I don't think the PR linked in that ticket _actually_ fixed it.

## Proof 

By running `helm template test --debug --set 1-23-x.pilot.serviceAccountAnnotations.foo=bar .` on latest 1.23.x (v1.23.3) chart

**Before the fix**:

```
# Source: [...]/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod-1-23-x
  namespace: istio-system
  labels:
    app: istiod
    release: test
  annotations:    foo: bar
```

**After the fix**:

```
# Source: [...]/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod-1-23-x
  namespace: istio-system
  labels:
    app: istiod
    release: test
  annotations:
    foo: bar
```

## The Fix/Bug

The dash (`-`) directly after the opening brackets on that line makes Helm/Go templating chomp all whitespace before it (including newline). This causes the bad formatting.

So replacing `indent` with a newline indent (`nindent`) gets us what we want.

**Maintainers**: Is it possible to get this in the next patch version of v1.24? Without this, we have to maintain a custom Istio chart with this fix.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by schahal** [comment]
@zirain @howardjohn I noticed the `cherrypick/release-1.24` label has been added to this PR...

Is there any action I need to make sure this gets on there? Or is that part of some automated flow which will take care of it?

**Comment by ilrudie** [comment]
@schahal, it looks like the cherry-pick didn't apply cleanly for 1.23, so someone will need to fix it up if we want that

**Comment by schahal** [comment]
> so someone will need to fix it up if we want that

Thanks for initiating it @ilrudie ! We can track discussion on that issue: https://github.com/istio/istio/issues/54184#issuecomment-2518846975

**Pull request merged**
