### PR TITLE
fix analyze vs trriger panic when  spec.routes.destinations[].destination null

### PR DESCRIPTION
**Pull request by nicole-lihui**
**Please provide a description of this PR:**
fixed https://github.com/istio/istio/issues/52806

### CODE REVIEW

**Review by MorrisLaw — CHANGES_REQUESTED** [review]
Can you share any output or tests showing this was fixed with this change?

**Comment by nicole-lihui** [comment]
> Can you share any output or tests showing this was fixed with this change?

No problem. I will add unit tests

**Review by MorrisLaw — APPROVED** [review]
thank you, good work!

**Pull request merged**
