### PR TITLE
Fix lint error (goimport-ed)

### PR DESCRIPTION
**Pull request by holgero**
Co-authored-by: Holger Oehm <holger.oehm@sap.com>

### CODE REVIEW

**Comment by holgero** [comment]
I consent to merging this.

**Comment by jsPlachetka** [comment]
I give my consent

**Comment by louiscryan** [comment]
@holgero @jsPlachetka please sign the CLA otherwise this PR will have to be backed out

Please visit https://cla.developers.google.com/ to sign.

**Comment by louiscryan** [comment]
@holgero has signed the CLA, this was validated by the bot in

https://github.com/istio/istio/pull/10425#issuecomment-459721248

**Pull request merged**
