### PR TITLE
Citadel trust domain fix

### PR DESCRIPTION
**Pull request by cmanzi**
Reopening [17111](https://github.com/istio/istio/pull/17111) to fix [17093](https://github.com/istio/istio/issues/17093), with unit tests added.

### CODE REVIEW

**Comment by cmanzi** [comment]
@cart Thanks for figuring this out, this had me stuck for a few days. I created some unit tests so this could get merged in, hope you don't mind.

**Comment by cmanzi** [comment]
@googlebot I signed it!

**Comment by cart** [comment]
Thanks for taking this over the finish line!

**Comment by cart** [comment]
@googlebot I consent.

**Comment by cmanzi** [comment]
@loewenstein @smawson I saw that you reviewed the previous PR to fix this issue, would either of you mind talking a look at this one? I believe it's ready to be tested.

**Comment by myidpt** [comment]
Thanks for the fix, @cmanzi . LGTM

**Comment by dkiser** [comment]
Any idea what release this will be in?

**Comment by somethingnew2-0** [comment]
@dkiser this fix is available as a docker container image in GCR [gcr.io/istio-testing/1.5-alpha.c6ecff62d0d1ac2b0b89a7c11f930801d1076706](gcr.io/istio-testing/1.5-alpha.c6ecff62d0d1ac2b0b89a7c11f930801d1076706).  It is likely already in the Istio 1.5.0 beta releases.

**Comment by dkiser** [comment]
@somethingnew2-0 Thanks! Ended up cherry picking the changes and building a citadel container yesterday based on 1.4.5 release tag. 

This in conjunction with `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` allowed for a cross-cluster demo between two clusters where each cluster had distinct `trustDomain` values set, distinct intermediate CAs, and a common shared root to cross-talk.

**Comment by drzdbd1** [comment]
looks like the fix made its way to 1.5.0-beta.2 but no further in any 1.5 official releases. Any ideas why?

**Comment by shyimo** [comment]
@drzdbd1 any updates ? we have the same issue on our production clusters
we are using 1.14.7 version and don't sure the issue is resolved in 1.5.x and above major's

**Comment by drzdbd1** [comment]
> @drzdbd1 any updates ? we have the same issue on our production clusters
> we are using 1.14.7 version and don't sure the issue is resolved in 1.5.x and above major's

Citadel is deprecated in 1.5 in favor of istiod, from my initial testing the fix seems not needed. Can you try 1.5?

**Pull request merged**
