### PR TITLE
use cp topology as default cfg topology

### PR DESCRIPTION
**Pull request by stevenctl**
When running tests locally, I noticed that this topology `--controlPlaneTopology 0:0,1:0` had what should have been a remote cluster being deployed as a "config cluster". Because the defaults for ConfigClusterValues are not baked into the framework code, but are in the externalistiod test main, these clusters are probably being deployed as if they're independent primary clusters. 

The logs in this PR confirm that switching this deploys things properly:

```
2020-09-09T07:27:20.926092Z	info	tf	setting up cluster-0 as primary cluster
...
2020-09-09T07:27:39.710299Z	info	tf	setting up cluster-2 as primary cluster
...
2020-09-09T07:28:00.393005Z	info	tf	setting up cluster-3 as primary cluster
...
2020-09-09T07:28:25.447590Z	info	tf	setting up cluster-4 as remote cluster
2020-09-09T07:28:25.447601Z	info	tf	setting up cluster-1 as remote cluster
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by stevenctl** [comment]
cc @irisdingbj

**Comment by stevenctl** [comment]
seems like tests pass with this change.. and without it. Added logging to see for sure what's happening.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
