### PR TITLE
Cleanup unneeded sleep

### PR DESCRIPTION
**Pull request by howardjohn**
`10167 runs so far, 0 failures (100.00% pass rate). 2.434597227s avg, 3.95269576s max, 660.065395ms min`

**Please provide a description of this PR:**

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
seems the failure related

**Comment by ramaraochavali** [comment]
Yeah. It failed, when I tried to remove it. Could n't spend time on why it is actually needed though

**Comment by howardjohn** [comment]
If 0s sleep fails then 10ms sleep is almost guaranteed to fail as well I
think, CI environment has a lot of hangs etc. Simple things can take >1s

**Comment by ramaraochavali** [comment]
Earlier it was 100ms which wasn't failing. I have increased it further in another PR but let us see if we definitely need 100ms.

**Pull request closed without merging**
