### PR TITLE
sverhoeven - namespace, extraVolumes and extraVolumeMounts configurable ingress gateway

### PR DESCRIPTION
**Pull request by sander-verhoeven**
…extraVolumes ,extraVolumeMounts

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [x ] Configuration Infrastructure
- [ ] Docs
- [x ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ x] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Advanced customizations can be done like https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by sander-verhoeven** [comment]
> Advanced customizations can be done like https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

Don't you think this should be a standard to add volumes and volume mounts, instead of this approach:

````yaml
{{- range $gateway.secretVolumes }}
        - name: {{ .name }}
          mountPath: {{ .mountPath | quote }}
          readOnly: true
        {{- end }}
        {{- range $gateway.configVolumes }}
        {{- if .mountPath }}
        - name: {{ .name }}
          mountPath: {{ .mountPath | quote }}
          readOnly: true
{{- end }}
{{- end }}
````

**Comment by howardjohn** [comment]
This is the legacy gateway chart anyways: https://artifacthub.io/packages/helm/istio-official/gateway

**Comment by sander-verhoeven** [comment]
> This is the legacy gateway chart anyways: https://artifacthub.io/packages/helm/istio-official/gateway

Ah I see, so we need to migrate to the new chart. I think we can close this pull request and we will do a migration to the new chart.

**Comment by sander-verhoeven** [comment]
I take a look at the new chart but no volume has been configured in this chart. Shall I implement the extraVolumes/Volumemount in the new chart? @howardjohn

**Comment by howardjohn** [comment]
I think that can be done using the kustomize as mentioned.

**Comment by costinm** [comment]
For the 'new' helm chart - I would appreciate some research on how this is
done by popular charts ( and if there is any recommendation ).
If it is a common pattern - I don't mind it, but I would like the config to
look like a Pod ( i.e. not 'extraSomething' or new keywords, but closer
to what kustomize would look like ).

For the even newer install method - Istiod automatically creating the
deployment when K8S Gateway resources are created - I believe the
approach is to also create a Deployment with whatever volumes and settings
you need ( as if you were creating a regular install ), and Istiod will
just patch it ? John, can you confirm if this is the intended long term or
just a step ? I was wondering what will happen when ambient gets broadly
adopted - keeping injection around just for gateway seems overcomplex (
Istiod creates the pods and has all info, no need for another roundtrip ),
having
a 'template' that Istiod can apply without injection would  be simpler. And
we can keep the template in the same syntax as a Pod.

If you are currently using the old template - maybe worth moving directly
to the new 'new method', or at least try it and provide feedback
on any gaps.

**Pull request closed without merging**
