### PR TITLE
Fixed wrong directory and delete not required kubectl command

### PR DESCRIPTION
**Pull request by ichigism**
When trying to move Ansible playbook, an error occurs. Because kubernetes yaml file's directory has changed. Also, I deleted a line in the jinja2 file in order to avoid the error caused by productpage already existing.

### CODE REVIEW

**Comment by gyliu513** [comment]
@ichigism can you please sign the CLA?

**Comment by ichigism** [comment]
I signed it!

**Comment by ichigism** [comment]
> @ichigism can you please sign the CLA?

I apologize for this late reply. the CLA sign has been done.

**Pull request merged**
