### PR TITLE
Remove test that was moved to istio/pkg repo

### PR DESCRIPTION
**Pull request by esnible**
This work is in preparation for https://github.com/istio/istio/issues/14794

The removed file, _version_test.go_, was moved to istio/pkg as part of https://github.com/istio/pkg/pull/28

### CODE REVIEW

**Comment by esnible** [comment]
@howardjohn The CLI coverage has gone down.  Do you recommend a change to _/codecov.threshold_ or restoring enough of the moved test to keep the numbers high?

**Comment by esnible** [comment]
@howardjohn Your `/lgtm` fell off when I pushed a test of remote mocking.

**Comment by esnible** [comment]
/test istio-lint-master

What would cause istio-lint to fail with `Process did not exit before 15s grace period`?  Overloaded build machines?

**Comment by howardjohn** [comment]
@esnible the cluster that runs the tests was upgraded to a new k8s version, and due to how our tests are run this is apparently NOT a zero downtime situation, which I think caused some tests to get interrupted unfortunately. Hopefully with the upgrade things will be smoother in the future.

If you do see lint issues in the future though can you let me know, we recently switched the lint from circle to prow because it was getting OOMkilled on circle. It somehow uses 16gb of memory. Prow seems to handle it ok but I want to keep an eye on it

**Pull request merged**
