### PR TITLE
gateway-api: gateway.networking.k8s.io/v1beta1 -> gateway.networking.…

### PR DESCRIPTION
**Pull request by frankbu**
…k8s.io/v1

**Please provide a description of this PR:**

Use v1 version of Gateway API resources.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
If we switch to reading v1, we will break anyone that has not installed v1 and has beta. This will result in Istiod never becoming ready and can cause an outage.

is there value to doing this? For instance, we still read VirtualService v1alpha3 despite v1beta1 existing for many years.

Given beta will not be removed and is identical to v1, I don't think there is a rush to do this.

Note this doesn't apply to _all_ places -- our tests can use v1 without issue really. But mixed versions in different places can cause bugs in k8s (https://github.com/kubernetes/kubernetes/issues/122130)

**Comment by costinm** [comment]
More concretely - GKE currently still has beta, and the upgrade process is gradual and intentionally slow. I don't know about other vendors, but it would be unfortunate to break GKE.

**Comment by frankbu** [comment]
> is there value to doing this?

@howardjohn Sorry, I got carried away 😃 I think the value is only in changing the samples and docs, especially doc links to the v1beta1 resources which are broken (e.g., https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1beta1.Gateway)?

I now removed the change from everything but the samples.

**Review by howardjohn — APPROVED** [review]

**Comment by frankbu** [comment]
> More concretely - GKE currently still has beta, and the upgrade process is gradual and intentionally slow. I don't know about other vendors, but it would be unfortunate to break GKE.

Hmm, in that case, maybe we don't even want to change the samples?

**Pull request closed without merging**
