### PR TITLE
fix: Fix the link address

### PR DESCRIPTION
**Pull request by pinxiong**
**Please provide a description of this PR:**

The CNI plugin repo is not correct because its branch is renamed from master to main

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by zirain** [comment]
@pinxiong you may commit with a wrong email?

**Review by ericvn — APPROVED** [review]

**Comment by pinxiong** [comment]
> @pinxiong you may commit with a wrong email?

Thanks for your reminder! I've changed my email address.

**Pull request merged**
