### PR TITLE
Remove env var ENABLE_CA_SERVER

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>

**Please provide a description of this PR:**

When I was debugging some configuration issues, I noticed that `ENABLE_CA_SERVER` shouldn't be required, because Istio can decide whether it should create CA server without this flag. Currently, this flag is enabled by default and it's necessary to disable it when custom certs are provided for istiod and `values.global.caAddress` is set. I cannot find other use cases when that flag must be explicitly disabled.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
We use this, can you give us some time to look into if this will break us?

**Comment by jewertow** [comment]
Sure. If there is a use case when this must be explicitly disabled, I will close this PR.

**Comment by shankgan** [comment]
This change would shutdown citadel as long as custom TLS certificates were provided, even if these TLS certificates were not intended to sign workload certificates; One corner case: user provides custom TLS certificates for control plane communication, but user still expects the workload certificates to be signed by plugin "cacerts".

**Comment by jewertow** [comment]
> One corner case: user provides custom TLS certificates for control plane communication, but user still expects the workload certificates to be signed by plugin "cacerts".

Ok, you're right. Taking this into account we can't remove this env variable. Thanks.

**Comment by costinm** [comment]
Please leave this in - we do use it and the auto-detection is not sufficient.  In our case - we have a separate managed CA. Istiod runs in a controlled sandbox - and does not have any certificates available, all certs are handled by the gateway in front. Note that we may still want to revive this mode ( gateway in front of Istiod ).

In general - all features of Istiod should be optional, and admin should be able to explicitly turn them off.

**Pull request closed without merging**
