### PR TITLE
Add extra volumes and volumemounts and make namespace configurable.

### PR DESCRIPTION
**Pull request by sander-verhoeven**
**Please provide a description of this PR:**
I have created this pull request to add extra volumes and volume mounts. We also created a umbrella chart for the components we use that is why we needed the Namespace to be configurable. 

With this setup configVolumes and secretVolumes could be removed.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [x ] Configuration Infrastructure
- [ ] Docs
- [x ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by zirain** [comment]
https://istio.io/latest/docs/setup/additional-setup/customize-installation/ will be better?

**Comment by sander-verhoeven** [comment]
> https://istio.io/latest/docs/setup/additional-setup/customize-installation/ will be better?

Hi Zirain. You want us to deploy the istio application with the Istioctl instead of using Helm or patch it afterwards? I think this change will be helpful to add Volumes of any kind.

````yaml
      {{- range $gateway.secretVolumes }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName | quote }}
          optional: true
      {{- end }}
      {{- range $gateway.configVolumes }}
      - name: {{ .name }}
        configMap:
          name: {{ .configMapName | quote }}
          optional: true
      {{- end }}
````
this part could be removed and replaced with the extraVolumes/Volumemounts part.

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by sander-verhoeven** [comment]
Created new pull request with trouble of changing contributer name on commit https://github.com/istio/istio/pull/42572

**Pull request closed without merging**
