### PR TITLE
Cherry-pick from 1.0 to 1.1 - Fix deployment namespace #7446 (#7477)

### PR DESCRIPTION
**Pull request by ericvn**
original commit:

Signed-off-by: Sébastien Prud'homme <sebastien.prudhomme@gmail.com>

### CODE REVIEW

**Comment by ericvn** [comment]
@sebastien-prudhomme Are you OK with me cherry picking the changes forward to master and release-1.1? Asking to get the required CLA sign-off.

**Comment by ericvn** [comment]
Second portion of #13625

**Comment by ericvn** [comment]
Will reassign to oz since the other related cherry-pick was

**Comment by linsun** [comment]
https://github.com/istio/istio-installer is the new project for installer - we are holding off changes to istio/install/kubernetes folder

**Comment by ericvn** [comment]
@linsun This PR is for `release1.1`. Are we also replacing the installer there?

**Pull request merged**
