### PR TITLE
remove delayed close timeout feature flag

### PR DESCRIPTION
**Pull request by ramaraochavali**
Fixes https://github.com/istio/istio/issues/35239
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by mandarjog — APPROVED** [review]
Lgtm

**Review by howardjohn — APPROVED** [review]

**Comment by MrRagga-** [comment]
It just got added a couple of month ago. What was the reason to remove it again?

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/issues/35239 @MrRagga-  Please see

**Pull request merged**
