### PR TITLE
Improve tracing of test framework timings

### PR DESCRIPTION
**Pull request by howardjohn**
Just to help debugging, especially as we look at slow tests now

### CODE REVIEW

**Comment by howardjohn** [comment]
I tested locally with
```bash
#!/usr/bin/env bash

ARTIFACTS=/tmp/traces

# Output a message, with a timestamp matching istio log format
function log() {
  echo -e "$(date -u '+%Y-%m-%dT%H:%M:%S.%NZ')\t$*"
}

# Trace runs the provided command and records additional timing information
function trace() {
  log "Running '${1}'"
  start="$(date -u +%s.%N)"
  "${@:2}"
  elapsed=$( date +%s.%N --date="$start seconds ago" )
  log "Command '${1}' complete in ${elapsed}s"
  # Write to YAML file as well for easy reading by tooling
  echo "'${1}': $elapsed" >> "${ARTIFACTS}/trace.yaml"
}

function func() {
  head -n1 "go.mod" "go.sum"
}

rm ${ARTIFACTS}/trace.yaml
trace should-echo echo bar baz "multi args"
echo
trace want-read head -n1 "go.mod" "go.sum"
echo
trace want-fail head -n1 "go.mod go.sum"
echo
trace func func
echo
trace "long name with spaces" func
echo
trace sleep sleep 0.5
echo
trace sleep-long sleep 1.5
echo
trace global ls *
```

**Comment by howardjohn** [comment]
Example output:
```
'init': 4.003591506
'setup kind cluster': 101.207147968
'setup kind registry': 5.850345867
'build images': 76.852788918
'test': 190.031989638
```

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
