### PR TITLE
Sync collab-gce-identity with master branch.

### PR DESCRIPTION
**Pull request by pitlv2109**

### CODE REVIEW

**Comment by pitlv2109** [comment]
@incfly After this PR has been merged, let's update the OWNER file for this collab branch for faster development.

**Comment by incfly** [comment]
I don't quite rember if we need admin to do non-squash merge or not, in order to preserve history. If that's needed, you need admin's help to enable that.

**Comment by pitlv2109** [comment]
Are you talking about updating the OWNER file? If so, admins need to approve that PR, similar to this https://github.com/istio/istio/pull/11746

**Comment by incfly** [comment]
no, i'm talking about the github merge. By default it's using squash merge, thus merging back to master might run into some issues because histories are not preseved.

Or just follow with whatever we're doing in authv2 branch is also fine.

**Pull request merged**
