### PR TITLE
add new flag on pilot-agent cmd to pass log-path to envoy

### PR DESCRIPTION
**Pull request by zirain**
[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Can you describe a bit of the use case? Generally best practice is to write logs to stdout/stderr. Writing to file seems suspicious to me

**Comment by zirain** [comment]
> Can you describe a bit of the use case? Generally best practice is to write logs to stdout/stderr. Writing to file seems suspicious to me

Just output the log to custom paths that already had configed by tools like logrotate etc.
If your pass nothing to "proxyLogPath", the behavior keep same as before.

**Comment by hzxuzhonghu** [comment]
I think the sidecar has a read-only file system, it does not allow write

**Comment by qudongfang** [comment]
> Can you describe a bit of the use case? Generally best practice is to write logs to stdout/stderr. Writing to file seems suspicious to me

@howardjohn I have a use case here not sure if it makes sense to you.

Istio-sidecar running on the VMs. 
Both the pilot-agent and envoy logs are sent to the stdout which isn't ideal. 
Because they have different log formats and use-purpose.
the pilot-agent log is more system/platform related, and on the other hand, the envoy access log is more data-plane application related.

Any suggestions would be greatly appreciated!

**Comment by howardjohn** [comment]
We do write them to the same stream in Kubernetes... they have the same
format. The envoy *access* logs are different and can already be configured
to write anywhere

**Pull request closed without merging**
