### PR TITLE
Updated prometheus to alllow configurable image

### PR DESCRIPTION
**Pull request by brian-avery**
Please provide a description for what this PR is for.
Allows the Prometheus image to be configurable and updates it to use the same behavior for image as many of the other Istio components. 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by morvencao** [comment]
If we allow configurable prometheus image, we should also make other images configurable.

**Comment by brian-avery** [comment]
Agree. Many of our images are already configurable, (all of the Istio components afaik) using tag, hub, and image. Grafana is configurable through a registry field. There's a couple of other ways that we do it. Would be great if we could make everything consistent but I'm not sure how feasible that is without deprecating fields.

**Comment by brian-avery** [comment]
Looks like Jaeger, Zipkin, Certmanager, and Kiali are all the same as Prometheus. Configurable hub and tag but hard coded image. I can add those to this PR as well.

Coredns encodes the entire image in a single field rather than using tag, hub, and image. 

Grafana uses a registry field to configure the image and hub and also supports a tag. 

Everything else uses hub, tag, and image.

**Comment by howardjohn** [comment]
related: https://github.com/istio/istio/pull/14815

**Comment by sdake** [comment]
@brian-avery in the related pr that @howardjohn pointed out, the other third party components have already been sanitized.  That PR needs a rebase.

**Comment by brian-avery** [comment]
@howardjohn @sdake Thanks. Didn't see that one. Looks like it includes this. Closing this one.

**Pull request closed without merging**
