### PR TITLE
Add preserveUnknowField to CRDs

### PR DESCRIPTION
**Pull request by jasonwzm**
In response to https://github.com/kubernetes/kubernetes/pull/82653, so that our CRDs are structural. This provides no restriction than before. We need to the field to keep the CRDs structural so that `kubectl explain` still works.

No API changes, so it is safe to merge to 1.4 release branch.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
If this will break k8s 1.14 then we can't merge this for like 6 months at minimum it sounds like?

**Comment by jasonwzm** [comment]
Closing this PR for now, as we can't support it fully yet.

**Pull request closed without merging**
