### PR TITLE
Remove mcs schema register

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by GregHanson — APPROVED** [review]

**Comment by nmittler** [comment]
The previous code was there to support experimentation with different implementations of the MCS API. Please do not submit this.

**Comment by hzxuzhonghu** [comment]
Why do you think this has relationship with implementation? This pr is reusing the schema from the upstream api

**Comment by nmittler** [comment]
GKE, for example, is currently using their own group name and version until the OSS API goes GA.

**Comment by hzxuzhonghu** [comment]
@nmittler Good to know, how about gateway apis

**Comment by nmittler** [comment]
I'm actually not sure about Gateway. Maybe @howardjohn knows more?

**Comment by howardjohn** [comment]
gateway is fine I don't think anyone is shipping custom types

**Comment by hzxuzhonghu** [comment]
Thanks for clarification, will close

**Pull request closed without merging**
