### PR TITLE
Preventing duplicate route entries

### PR DESCRIPTION
**Pull request by mbanikazemi**
Addresses issue #13267
Adds unit tests

### CODE REVIEW

**Comment by frankbu** [comment]
Shouldn't this be targetted to the `release-1.1` branch, since it's a pretty nasty bug with a pretty straightforward fix?

**Comment by mbanikazemi** [comment]
Sure I will submit a PR against release 1.1 after this is reviewed here. Does that sound reasonable?

**Comment by mbanikazemi** [comment]
Removing [WIP] as this works as intended in my testings.

**Pull request merged**
