### PR TITLE
[Auto Release] Update istio.Version

### PR DESCRIPTION
**Pull request by xiaolanz**
Update istio.Version

### CODE REVIEW

**Comment by sebastienvas** [comment]
Are you positive the same api version is used in every repo ? Also once you run the first command, you need to wait for the build jobs to complete.

**Comment by sebastienvas** [comment]
Pilot seems to be broken again.

**Comment by xiaolanz** [comment]
I will make a note to release guide to "wait for the build jobs" I have a PR in progress.

**Comment by xiaolanz** [comment]
abandon this PR.

**Pull request closed without merging**
