### PR TITLE
Validate: envoyfilter patch value should not be empty

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
I have seen invalid envoyfilters during upgrade, we should prohibit empty value if the operation is not remove

```
    patch:
      operation: INSERT_BEFORE
      value: {}

```

### CODE REVIEW

**Comment by howardjohn** [comment]
@kyessenov  @mandarjog is there any real use case for inserting {}? I am thinking no so we should do this?

**Comment by kyessenov** [comment]
Yeah sometimes empty proto has a meaning, like in http2_protocol_options or router filter config.

**Comment by hzxuzhonghu** [comment]
It is different, this requires providing a root field at least. For `http2_protocol_options`, at least the field name should be set.

**Comment by hzxuzhonghu** [comment]
In other words, this is not checking the value of the subfields

**Pull request closed without merging**
