### PR TITLE
Add x alias to experimental istioctl command

### PR DESCRIPTION
**Pull request by liamawhite**
I'm super lazy and experimental is far too much effort to type

Signed-off-by: Liam White <liam@tetrate.io>

### CODE REVIEW

**Comment by rshriram** [comment]
not even exp ?

**Comment by liamawhite** [comment]
SUPER lazy 😂

I can add an additional alias though.

**Comment by fisherxu** [comment]
Is it possible to conflict with other commands only ‘x’? :-)

**Comment by liamawhite** [comment]
Yes, but no other commands do.

**Comment by ayj** [comment]
`exp` seems reasonable. 

cc @esnible

**Comment by linsun** [comment]
@wenchenglu can we get this merged?

**Comment by esnible** [comment]
@liamawhite I have tried retesting the required prow/e2e_pilotv2_auth_sds.sh and it keeps failing.  I don't think your change would break that test.  However ... is it possible for you to rebase it on a later build that might pick up some other fixes?

**Comment by liamawhite** [comment]
@esnible done 🙂

**Comment by linsun** [comment]
schedule this for 1.1.1?  @duderino

**Comment by esnible** [comment]
The tests are all passing and everything is approved.  @liamawhite do we want to retarget this to master?  Or should we find someone to force it?

**Pull request merged**
