### PR TITLE
change inbound VirtualHost name from service port to instance port

### LINKED ISSUE #36112: error `virtual_hosts` name in inbound `route_config`
### Bug Description

since 1.8.0 (from this pr https://github.com/istio/istio/pull/30979 ), istio will use Service TargetPort to generate inbound listener, but the `virtual_hosts` name is still using Service Port. It's a bug or not?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: nginx
```
```json
{
    "route_config": {
        "name": "inbound|80||",
        "virtual_hosts": [
            {
                "name": "inbound|http|8080",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "inbound|80||",
                            "timeout": "0s",
                            "max_stream_duration": {
                                "max_stream_duration": "0s",
                                "grpc_timeout_header_max": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "nginx.default.svc.cluster.local:8080/*"
                        },
                        "name": "default"
                    }
                ]
            }
        ],
        "validate_clusters": false
    }
}
```

`virtual_hosts[0].name` is `inbound|http|8080`, I think it should be `inbound|http|80`

### Version

```prose
$ istioctl version
client version: 1.10.4
control plane version: 1.10.4
data plane version: 1.10.4 (1 proxies)

$ kubectl version --short
Client Version: v1.21.5
Server Version: v1.21.5
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dozer47528**
**Please provide a description of this PR:**

fix #36112

### CODE REVIEW

**Comment by dozer47528** [comment]
any progress?

**Comment by jacob-delgado** [comment]
cc @ramaraochavali @howardjohn @hzxuzhonghu Can you guys take a look at this PR?

**Comment by howardjohn** [comment]
I share the same concerns @hzxuzhonghu had in the issue. This is more correct than me but it only impacts EnvoyFilter matches. This will break all users that currently use vhost name EnvoyFilter match.

**Comment by dozer47528** [comment]
> I share the same concerns @hzxuzhonghu had in the issue. This is more correct than me but it only impacts EnvoyFilter matches. This will break all users that currently use vhost name EnvoyFilter match.

I understand your concerns. Be more accurate, this will break users using vhost name EnvoyFilter match who has service with different service port and target port.w

We can add this change to BEFORE YOU UPGRADE section in the release note.

**Comment by hzxuzhonghu** [comment]
I am ok with a note in release notes, rather than back and forth

**Pull request closed without merging**
