### PR TITLE
provide istioctl get command

### PR DESCRIPTION
**Pull request by irisdingbj**
rewrite istioctl get command to get all supported resources.

### CODE REVIEW

**Comment by fisherxu** [comment]
Is there a discussion or issue for the change? Because the istioctl get have deprecated before :)

**Comment by irisdingbj** [comment]
> Is there a discussion or issue for the change? Because the istioctl get have deprecated before :)

https://docs.google.com/document/d/1nmBv2W_PUw8mgw3XoAhGIm3R-1lUIxHrF3j3OQj4O1E/

@fisherxu

**Comment by jwendell** [comment]
We can use `kubectl get istio-io`, right? Why resurrect `istioctl get all`?

**Comment by esnible** [comment]
@jwendell For the rationale see https://github.com/istio/istio/issues/13260

**Pull request closed without merging**
