### PR TITLE
add retry logic for TestProxySDS

### PR DESCRIPTION
**Pull request by williamaronli**
ref: https://github.com/istio/istio/issues/24680

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by williamaronli** [comment]
@myidpt

**Review by howardjohn — CHANGES_REQUESTED** [review]
I do not think this is a good idea. EVERY integration test under security/pkg is flaky and extremely slow. They are like 10 of the top 15 slowest unit tests. We should be investigating the root cause not slapping retries on it

**Comment by myidpt** [comment]
@howardjohn Just give my 2 cents here.

This test spins up a couple of services (including a real Envoy) locally, and verify the backend workloads E2E. I think that's why they are slow. I think there are two directions to improve:

1) Treat this test as an integration test and move to tests/integration. Give more time for retries. My thought is this test is much faster (and less flaky?) than other tests in tests/integration (let me know if I'm not correct).
2) Use a mocked client to represent Envoy. Do not verify backend workloads can talk to each other, but instead just verify the return of the SDS API. This will shorten the time cost and make it less flaky, but it is much weaker than the original test. We don't want to do this unless we have good E2E tests.

WDYT? @JimmyCYJ @howardjohn

**Pull request closed without merging**
