### PR TITLE
fix init container crash when iptables exist

### LINKED ISSUE #23288: Istio 1.5.1 is installed on the Alibaba server istio init. Initialization error
## Bug description

- k8s：v1.16.6-aliyun.1
- istio: v1.5.1

Istio 1.5.1 is installed on the Alibaba server istio init. Initialization error
use namespace injection sidecar

## Environment

```
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
```

## Variables

```
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
```

Writing following contents to rules file:  `/tmp/iptables-rules-1587896609463992300.txt031496377`

```
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1587896609463992300.txt031496377
iptables-restore: line 2 failed
iptables-save 
# Generated by iptables-save v1.6.1 on Sun Apr 26 10:23:29 2020
*mangle
:PREROUTING ACCEPT [109941:361621593]
:INPUT ACCEPT [109941:361621593]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [103494:575994556]
:POSTROUTING ACCEPT [103494:575994556]
COMMIT
# Completed on Sun Apr 26 10:23:29 2020
# Generated by iptables-save v1.6.1 on Sun Apr 26 10:23:29 2020
*nat
:PREROUTING ACCEPT [3806:228360]
:INPUT ACCEPT [4032:241920]
:OUTPUT ACCEPT [797:56682]
:POSTROUTING ACCEPT [1119:76002]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Sun Apr 26 10:23:29 2020
# Generated by iptables-save v1.6.1 on Sun Apr 26 10:23:29 2020
*filter
:INPUT ACCEPT [109941:361621593]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [103494:575994556]
COMMIT
# Completed on Sun Apr 26 10:23:29 2020
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0xd819c0, 0x9739b8, 0x10, 0xc00000cc00, 0x2, 0x2)
	istio.io/istio@/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0000f5d30, 0x7f497dbc5001, 0x0, 0x0)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:474 +0x3aa
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0000f5d30)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:481 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0000f5d30)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:428 +0x24e2
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0xd5c740, 0xc0000d4700, 0x0, 0x10)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:56 +0x14e
github.com/spf13/cobra.(*Command).execute(0xd5c740, 0xc00001e130, 0x10, 0x11, 0xd5c740, 0xc00001e130)
	github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd5c740, 0x40574f, 0xc000082058, 0x0)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
istio.io/istio/tools/istio-iptables/pkg/cmd.Execute()
	istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:284 +0x2d
main.main()
	istio.io/istio@/tools/istio-iptables/main.go:22 +0x20
```

### LINKED ISSUE #24101: Istio 1.6.0 -  sidecar injection prevents pods from starting
[istio-dump.tar.gz](https://github.com/istio/istio/files/4682721/istio-dump.tar.gz)
I installed Istio v1.6.0 demo profile for testing. I applied the label to the default namespace to enable sidecar auto injection. I deployed the bookstore app and it fails to start the pods. If I remove the label the app deploys successfully. I uploaded the dump_kubernetes.sh for your review.
 
Don

### LINKED ISSUE #24148: Istio init container crash
istio init container crash

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.0
pilot version: 1.5.0
istiod version: 1.6.0
data plane version: 1.5.0 (8 proxies), 1.6.0 (3 proxies)

**How was Istio installed?**

version 1.5.0:
istioctl manifest apply

version 1.6.0:
istioctl install --set revision=canary -f values.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

CentOS Linux release 7.7.1908 (Core)

init container logs
```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1590592535343591764.txt532247932
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1590592535343591764.txt532247932
iptables-restore: line 2 failed
iptables-save
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*mangle
:PREROUTING ACCEPT [1076136:140933167]
:INPUT ACCEPT [1076136:140933167]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [915772:172731597]
:POSTROUTING ACCEPT [915772:172731597]
COMMIT
# Completed on Wed May 27 15:15:35 2020
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*raw
:PREROUTING ACCEPT [1076136:140933167]
:OUTPUT ACCEPT [915772:172731597]
COMMIT
# Completed on Wed May 27 15:15:35 2020
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*nat
:PREROUTING ACCEPT [28633:1717980]
:INPUT ACCEPT [94041:5119196]
:OUTPUT ACCEPT [48620:4173884]
:POSTROUTING ACCEPT [48620:4173884]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Wed May 27 15:15:35 2020
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*filter
:INPUT ACCEPT [1076136:140933167]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [915772:172731597]
COMMIT
# Completed on Wed May 27 15:15:35 2020
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x38e0918, 0x21a3e72, 0x10, 0xc0003dba80, 0x2, 0x2)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc000653d68, 0x2199a01, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:482 +0x387
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000653d68)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:489 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000653d68)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:436 +0x25ef
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x388e180, 0xc000155600, 0x0, 0x10)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:64 +0x148
github.com/spf13/cobra.(*Command).execute(0x388e180, 0xc000155500, 0x10, 0x10, 0x388e180, 0xc000155500)
	github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x388e420, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:504 +0x2d
```

### PR DESCRIPTION
**Pull request by erdun**
Prevent init container crash when iptables chain already exists.

Fixes #23288
Fixes #24148
Fixes #24101

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
If you're trying to deal with `istio-init` crashing and restarting, then I'd prefer fixing the issues that make `istio-init` crash in the first place.

**Comment by erdun** [comment]
1. The init container is cleaned and kubelete create a new container, the new one will be crash because iptables chains has been inited #24148
2. #23288, #24101 Seems unknown cause that triggered the scripts twice

This commit make sure scripts can run succes even more then one time

**Comment by howardjohn** [comment]
@rlenglet I don't think its the container crashing and failing the second time. Instead, people are deleting the stoppped init containers. This triggers k8s to restart it, which then fails. So its trying to run the init container twice. IMO its a bug in k8s

**Comment by lambdai** [comment]
My two cents: the init container should not be deleted at the very beginning. An administrator could damage the k8s service/pods in 1 million ways. I am not sure we would fix 1 by 1.

Istio-init should not pretend to reports OK under this condition, either.

The triage is indeed painful. I recommend adding diagnose log.

If we concede the harmful administration is inevitable, we should use repair controller to fix by deleting the pod. That repair is more aggressive but it is more reliable in terms of "repair"

**Comment by erdun** [comment]
Deleting the pod may lead to app 503 and conflict with kube-controller.I don't think the repair controller is a good way

**Comment by zhaohuabing** [comment]
Should we remove the chains first to prevent the panic reported by istio-init container?

**Comment by willemm** [comment]
According to the k8s docs (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), there are legitimate cases where init containers may sometimes be restarted.  "All containers in a Pod are terminated while restartPolicy is set to Always, forcing a restart, and the init container completion record has been lost due to garbage collection."

**Comment by rlenglet** [comment]
> Should we remove the chains first to prevent the panic reported by istio-init container?

I wouldn't do that. If a connection is received while the chains are deleted, it would bypass the sidecar. That's not safe.

**Comment by erdun** [comment]
Why not check the chains whether existed, if not, create one, else do nothing. Just like kube-proxy do.

**Comment by rlenglet** [comment]
> Why not check the chains whether existed, if not, create one, else do nothing. Just like kube-proxy do.

IMHO, that wouldn't be sufficient, as it wouldn't detect partial failures, e.g. when the chain has been created but not all the rules are inserted. We already call `iptables-restore`, which is supposed to atomically reset the rules in the chains. I would focus on generating the right input to `iptables-restore` to not balk when the chains already exist, if that's at all possible.

**Pull request closed without merging**
