### PR TITLE
Enable disabled mixer tests in New Test Framework

### PR DESCRIPTION
**Pull request by gargnupur**

### CODE REVIEW

**Comment by kyessenov** [comment]
Changes to config look good. Any idea why local integration test is failing? Is this same as #13155 ?

**Comment by gargnupur** [comment]
@kyessenov : yes, looks similar, it has same error:

error	Handler not found: handler='handler1'
2019-04-08T20:59:19.690645Z	error	No valid actions found in rule

Fixed this in policy backend by changing handler rule in native component too, to  be in the new format.

**Comment by gargnupur** [comment]
@kyessenov , @ozevren , @nmittler : looks like disabled mixer tests are passing now...

**Comment by nmittler** [comment]
@gargnupur looks like test-integration-kubernetes is failing on Circle. Maybe unrelated?

**Comment by gargnupur** [comment]
@nmittler : Yes, it's mtls_healthcheck test that's failing in setup...

**Comment by nmittler** [comment]
ok, can you re-run to confirm it's a flake?

**Comment by gargnupur** [comment]
@nmittler : Yes, it was a flake.. looks like its passed now..

**Pull request merged**
