### PR TITLE
Improve dashboard test robustness

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR is an attempt to improve the stability of the dashboard tests, which
have demonstrated a bit of flakiness (especially in rbac-auth tests). 

There appear to be two possible explanations for test flakiness:
1. Mixer configuration for handlers is not received before traffic is handled by Mixer.
1. Metrics exposed by Mixer have not been processed by Prometheus in time for test.

This PR adds two wait-loops to address these issues:
1. in `Setup()`, the test now checks a Mixer metric to confirm that Mixer has the expected number of handlers configured (kubernetesenv, stdio, prometheus).
1. in `TestDashboard`, a set of sentinel queries are executed to confirm that Mixer scraping is working as expected.

Together, these polling operations should significantly reduce (if not fully eliminate) observed flakes in the dashboard tests caused by timing issues.

cc: @xiaolanz (oncall)

Fixes: #4420

### CODE REVIEW

**Comment by douglas-reid** [comment]
@kyessenov you were super quick on this one. I have some more changes I'd like to add here, as I realized that this may be a config issue and not a prometheus timing issue. I'll ping when it is fully ready.

**Comment by douglas-reid** [comment]
PTAL. I added logic to wait for full Mixer configuration before beginning testing as well.

Example logs:
```
...
2018-03-21T17:27:50.012662Z     info    Get all pods running!
2018-03-21T17:27:50.012706Z     info    Waiting for Mixer to be configured with correct handlers: 0s
2018-03-21T17:27:50.135350Z     info    Waiting for Mixer to be configured with correct handlers: 5s
2018-03-21T17:27:55.176723Z     info    Waiting for Mixer to be configured with correct handlers: 15s
2018-03-21T17:28:10.240836Z     info    Waiting for istio-ingress to get external IP
...
--- PASS: TestDashboards (4.80s)
        dashboard_test.go:82: Validating prometheus in ready-state...
        dashboard_test.go:446: Waiting for prometheus metrics: 0s
        dashboard_test.go:453: Value found for: 'round(sum(irate(istio_request_count[1m])), 0.001)'
        dashboard_test.go:453: Value found for: 'sum(irate(istio_request_count{response_code=~"4.*"}[1m]))'
        dashboard_test.go:453: Value found for: 'sum(irate(istio_request_count{response_code=~"5.*"}[1m]))'
        dashboard_test.go:87: Sentinel metrics found in prometheus.
...
```

**Comment by xiaolanz** [comment]
addresses #4420

**Pull request merged**
