### PR TITLE
Remove RequireSingleCluster for sds related tests

### PR DESCRIPTION
**Pull request by jtrbs**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
is this actually deploying gateway/certs in multiple clusters and calling all of them?

**Comment by jtrbs** [comment]
Currently it uses the default cluster https://github.com/istio/istio/blob/master/tests/integration/security/sds_ingress/ingress_test.go#L69

**Pull request merged**
