### PR TITLE
turn on protocol sniffing for inbound

### PR DESCRIPTION
**Pull request by yxue**
Turn on protocol sniffing for inbound

### CODE REVIEW

**Comment by howardjohn** [comment]
Can you provide more context on why we decided to do this now and why it is safe now (if it is)?

**Comment by yxue** [comment]
Using unnamed ports is unsecured as expected and it's part of permissive mode. We are going to document the situation and remind the user to use named ports, strict mTLS for security.

**Review by rshriram — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
