### PR TITLE
honor global hub and tag in ztunnel

### PR DESCRIPTION
**Pull request by rwong2888**
**Please provide a description of this PR:**

ztunnel does not honor global values

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This should be fixed in https://github.com/istio/istio/pull/51749. If it doesn't work LMK a `helm tempalte` command that gives the wrong output

**Comment by rwong2888** [comment]
I will try again when the next helm chart gets released

**Comment by bleggett** [comment]
xref: https://github.com/istio/istio/issues/51943

**Comment by bleggett** [comment]
Also xref: https://github.com/istio/istio/issues/52034

since the underlying issue here again is lack of consistent templating for image values across charts.

**Pull request closed without merging**
