### PR TITLE
Experimental: create a helm release from `istioctl install`

### PR DESCRIPTION
**Pull request by howardjohn**
part of https://github.com/istio/istio/issues/44814

With this change, Istioctl will output a helm release. This means the install shows up in `helm ls`, and a user can seemless switch to helm.
Without this, helm will barf with 

```
Error: Unable to continue with install: PodDisruptionBudget "istiod" in namespace "istio-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "pilot"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"
```

We can make a change to istioctl to do a one-off migration, but it is not ideal IMO.

### CODE REVIEW

**Comment by Stono** [comment]
You could just set the annotations on the resources which would allow helm to "adopt" them?

```
  metadata:
    annotations:
      meta.helm.sh/release-name: istio
      meta.helm.sh/release-namespace: istio-system
 ```

**Comment by howardjohn** [comment]
Yeah if we don't do this, we will likely create a helper like https://github.com/helm/helm/issues/2730#issuecomment-2128275312. The thought was this might have other benefits. 

Largely the goal is to make `istioctl install` behave identically to `helm install`. It might not make sense to have this intermediate step, and instead wait for https://github.com/istio/enhancements/issues/166 which would allow us to rip out a lot of the cruft

**Comment by bleggett** [comment]
:+1: on

> It might not make sense to have this intermediate step, and instead wait for https://github.com/istio/enhancements/issues/166 which would allow us to rip out a lot of the cruft

Even if it doesn't let us rip it all out, even if we still need this, it will shrink + clarify the problem.

**Comment by whitneygriffith** [comment]
This is a great path forward! And I think should be done [https://github.com/istio/enhancements/issues/166](https://github.com/istio/enhancements/issues/166)

Will this still be relevant when transitioning to the Helm comandeer approach when [helm/helm#2730](https://github.com/helm/helm/issues/2730#issuecomment-2128275312) is resolved?

**Pull request closed without merging**
