### PR TITLE
Set INET class for CNAME response

### LINKED ISSUE #29681: Proxy agent DNS response incompatible with glibc AF_INET resolver
**Bug description**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Well formed DNS responses accepted by all implementations.

**Steps to reproduce the bug**

* enable DNS proxy and set REGISTRY_ONLY
* add a serviceentry

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
spec:
  exportTo:
    - .
  hosts:
    - www.google.com
  ports:
    - name: http
      number: 80
      protocol: HTTP
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS
```

`curl www.google.com` from a container works, but multiple other tools have issues with the responses, for example Java:

```java
InetAddress dnsresult[] = InetAddress.getAllByName(domain);
for (int i = 0; i < dnsresult.length; i++)
        System.out.println(dnsresult[i]);
```

throws `UnknownHostException`.

It turns out the difference between `curl` and the above code in Java is that it sets

```c
struct addrinfo hints;
hints.ai_family = AF_INET;
```

This triggers a different code path/parser in glibc, which does not handle the response from the dns proxy.

https://sourceware.org/git/?p=glibc.git;a=blob;f=resolv/nss_dns/dns-host.c;h=91c0a3b0e488af36b7f23b7fd5d0431f1fbe7788;hb=HEAD#l801

```c
 801       if (__glibc_unlikely (class != C_IN))
 802         {
 803           /* XXX - debug? syslog? */
 804           cp += n;
 805           continue;                     /* XXX - had_error++ ? */
 806         }
```

It's also visible with `nslookup` and `dig +search`:

```
$ nslookup www.google.com
;; Warning: Message parser reports malformed message packet.
Server:		172.20.0.10
Address:	172.20.0.10#53

Non-authoritative answer:
www.google.com.namespace.svc.cluster.local	canonical name = www.google.com.
Name:	www.google.com
Address: 240.240.0.13
** server can't find www.google.com: NXDOMAIN
```

```
dig +search www.google.com
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> +search www.google.com
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36747
;; flags: qr rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.google.com.namespace.svc.cluster.local. IN A

;; ANSWER SECTION:
www.google.com.namespace.svc.cluster.local. 0	RESERVED0 CNAME	www.google.com.
www.google.com.		30	IN	A	240.240.0.13

;; Query time: 0 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; WHEN: Thu Dec 17 09:02:11 UTC 2020
;; MSG SIZE  rcvd: 212
```

**Version**
1.8.1

**How was Istio installed?**
preview profile with istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS

### PR DESCRIPTION
**Pull request by chlunde**
The answer records for the CNAME did not have any class. This works for
some code paths in glibc, but it does not work when `ai_family` is set to
`AF_INET`.

	$ nslookup www.google.com
	;; Warning: Message parser reports malformed message packet.
	Server:		172.20.0.10
	Address:	172.20.0.10#53

	Non-authoritative answer:
	www.google.com.namespace.svc.cluster.local	canonical name = www.google.com.
	Name:	www.google.com
	Address: 240.240.0.13
	** server can't find www.google.com: NXDOMAIN

Fixes #29681

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
lgtm

**Comment by ramaraochavali** [comment]
lgtm. leaving it open for @howardjohn  to take a look

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
@chlunde Add a release note

**Pull request merged**
