### PR TITLE
Test EndpointSlice in CI

### PR DESCRIPTION
**Pull request by howardjohn**
As part of this work:
* Upgrade to EndpointSlice beta - alpha is not present on clusters running in CI or vast majority of users clusters
* Refactor pilot tests so we can reuse the test for endpointslice/normal setup

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
>Upgrade to EndpointSlice beta 

Want to be sure in which version does Endpointslice beta

**Comment by howardjohn** [comment]
> Want to be sure in which version does Endpointslice beta


1.17

**Comment by hzxuzhonghu** [comment]
yeah, donot we want to support istio running on lower k8s version(1.15, 1,16)?  From what i know, k8s now support a release one year from released

**Comment by howardjohn** [comment]
@hzxuzhonghu there is a big difference betweensupporting Kubernetes 1.15/1.16 and supporting an alpha API. There are roughly ~0 users of EndpointSlice Alpha - the vast majority of users are not enabling alpha APIs, nor should it be encourage. I see no reason to continue to support it. If you are a user that somehow depends on the EndpointSlice alpha, they should also be able to upgrade to a support k8s version. btw, k8s 1 year support is not retroactive - only starting in 1.19

**Comment by howardjohn** [comment]
Basically, anyone that has the endpointslive alpha api can just upgrade. But users who only have the beta API cannot get the alpha api. Without this pr basically anyone on gke/aks/eks cannot use endpointslice

**Comment by hzxuzhonghu** [comment]
> Basically, anyone that has the endpointslive alpha api can just upgrade

This would require users to upgrade the k8s version, from what i know, many users can not upgrade so fast.

>But users who only have the beta API cannot get the alpha api

I could not understand this.

**Comment by howardjohn** [comment]
I doubt there are users who are depending on and aloha feature if kubernetes that is disabled on every single cloud k8s provider and also cannot upgrade.

Basically we need to choose to support either:
* alpha users who are running alpha code (not recommended) and refuse to upgrade
* beta users

the second set of users include ALL users in gke, eks, iks, and aks. I care much more about that set of users

**Comment by howardjohn** [comment]
alpha is also behind a feature flag (which means very few k8s users use it ) and beta is enabled by default

**Comment by howardjohn** [comment]
Actually I don't think we even need those arguments - istio 1.8 supports k8s 1.17, so there is no reason to hurt users to support a Kubernetes 1.16.

**Comment by hzxuzhonghu** [comment]
We could not make the dependency on k8s new api block users(hard to upgrade fundamental k8s infra, especially those who have customized modification) from upgrading to new istio. 

The fundamental theory should keep a wider compatible scope, furthermore, we donot see any improvement in API schema. This is similar to admission api upgrade, not so urgent from my view.

**Comment by howardjohn** [comment]
This is not the same as the webhook... no user of kubernetes provided by a cloud provider (vast majority of users) can use endpointslice without this change....

**Review by hzxuzhonghu — APPROVED** [review]
EndpointSlice is a alpha api, which is not suggested to use. So rare risk of breaking compatibility.

**Pull request merged**
