### PR TITLE
Support for smart dns using istio-cni

### PR DESCRIPTION
**Pull request by nikhilag09**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

Solves: https://github.com/istio/istio/issues/29511

### CODE REVIEW

**Comment by howardjohn** [comment]
@stewartbutler reading environment vars for config feels like a pretty fragile implementation. Do you think its a good short term approach though?

**Comment by stewartbutler** [comment]
Is there anything preventing this from being set as an annotation?

CNI already uses annotations to pass around config (since it is the only way to pass pod-specific configuration to the CNI binary at this time), I'd rather reuse an existing hack than add an entirely new one.

**Comment by nikhilag09** [comment]
@googlebot I signed it!

**Comment by nikhilag09** [comment]
@howardjohn  @stewartbutler : 
I added ENV variable as currently DNS capture is enabled by ISTIO_META_DNS_CAPTURE proxy metadata which is populated as part of ENV variable. Don't have much context around why this was used as ENV variable in place of annotation which is generally used for passing config as stated by _stewartbutler_ . 

For the fix, there were 2 options. 
1. Reading istio cluster config ( which could be fetched from API server, but with this, we will be making extra calls to API server and will break the existing config pass method) 
2. Reading sidecar ENV variable: I preferred this as a short term fix because we already have pod information and migration from ENV to annotation will be simpler if we choose to migrate ISTIO_META_DNS_CAPTURE config to annotation.

**Comment by tmshort** [comment]
As of right now (1.8, and apparently 1.9), the DNS capture and CNI features are mutually exclusive. Being able to use them together would be a boon.

**Comment by nikhilag09** [comment]
@howardjohn : May you add cla: yes label and merge this if everything looks fine. 

I can't comment from the account nikhilag09-zz  ( This belongs to me as well and have lost access to it )

**Comment by nikhilag09** [comment]
@adiprerepa : May you check this. Let me know if anything is missing from this.

**Comment by venkatk-25** [comment]
any update on this. We also use CNI, and are blocked on SmartDNS not being supported for doing multi-cluster

**Comment by bianpengyuan** [comment]
@nikhilag09 will you be OK for me to take over this change? My planned change will be partially the same as this, but it will parse the whole ProxyConfig to get DNS capture enablement.

**Comment by nikhilag09** [comment]
@bianpengyuan: sure you can go ahead taking over this change. 
I am also waiting for this to be fixed in the official release.

**Pull request closed without merging**
