### PR TITLE
1.6 patch for issue #27427

### PR DESCRIPTION
**Pull request by aattuluri**
[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by aattuluri** [comment]
The below test has failed:
```
FAIL
Makefile.core.mk:545: recipe for target 'mixer-racetest' failed
```
I am not sure how this change is related to this test.

**Comment by aattuluri** [comment]
@nmittler @howardjohn any inputs?

**Comment by jacob-delgado** [comment]
> @nmittler @howardjohn any inputs?

cc @howardjohn @nmittler Waiting for SME approval due to the size of this PR and that the auto cherry pick failed.

**Review by brian-avery — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Comment by aattuluri** [comment]
@brian-avery I see you added a `do-not-merge/hold` label, is there a decision to be made?

**Pull request merged**
