### PR TITLE
Kiali v0.5.0 on Helm Installer

### PR DESCRIPTION
**Pull request by gbaufake**
Hi Istio Team,

Kiali was updated to 0.5.0 (fsupport for Istio 0.8.) - more info on https://medium.com/kialiproject/kiali-sprint-7-istio-0-8-support-4df62e5291f2.

Best Regards,
Guilherme Baufaker Rêgo

### CODE REVIEW

**Comment by gbaufake** [comment]
cc @sdake @gyliu513 @ymesika

**Comment by sdake** [comment]
@gbaufake if this works against release-1.0, can you submit this PR against that branch?  master is currently frozen (thats  what the needs-admin check is about).  Might as well have latest and greatest, especially is Kiali is broken in release-1.0 (which you seem to indicate as the rev to 0.8 happened).

Cheers
-steve

**Comment by gbaufake** [comment]
@sdake 
OK. Kiali next release should be ready for Istio 1.0
Considering that, should I open a PR for Kiali 0.5.0 on 0.8.0 branch or wait until next kiali version then submit an update PR to master?
Best Regards,
Guilherme Baufaker Rêgo

**Comment by gyliu513** [comment]
@gbaufake I think you can submit this PR to 1.0 branch.

**Comment by rshriram** [comment]
yes please move to 1.0 branch, given that we are unlikely to do a point release for 0.8..

**Comment by gbaufake** [comment]
Closing in favor of #7007

**Pull request closed without merging**
