### PR TITLE
Update base image version for bookinfo-reviews sample app

### PR DESCRIPTION
**Pull request by johnma14**
Update the base image version from websphere-liberty version 19.0.0.4-javaee8 to
19.0.0.5-javaee8.

Fixes: #15477

### CODE REVIEW

**Comment by howardjohn** [comment]
I am sure its fine but what do we need in the update?

**Comment by johnma14** [comment]
The old version had vulnerabilities and this version is good.

**Comment by frankbu** [comment]
Is this needed to address a vulnerability scan issue? If so, should we also cherry pick this to the release branch and rebuild/publish the new image to dockerhub?

**Pull request merged**
