### PR TITLE
fix(deltaXds): the env variable ISTIO_DELTA_XDS not take affect

### PR DESCRIPTION
**Pull request by whalecold**
**Please provide a description of this PR:**

ref: https://github.com/istio/istio/issues/42002

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I remember we have integration test for delta xds

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/blob/55d4e69431d5a59bf894e3dc3e7db03b87a2b6f1/pkg/bootstrap/config.go#L85 - It is already handled

**Comment by hzxuzhonghu** [comment]
This one is inject the env to sidecar.  Not sure without this how the test passed

**Comment by ramaraochavali** [comment]
I guess it is because of this https://github.com/istio/istio/blob/e3ddbb4a22f142afe54e4bfd68c01f53280d388d/pkg/test/framework/components/echo/common/deployment/echos.go#L250

**Comment by whalecold** [comment]
it seems to have no checking in the test, https://github.com/istio/istio/blob/cccb39dee06dea6bac07df1a22d347fb6d02c5ce/pkg/kube/inject/fuzz_test.go#L23

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is meant to be set in the agent, not Istiod.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Pull request closed without merging**
