### PR TITLE
Switch CA from using RSA 2048 to ECC P256

### PR DESCRIPTION
**Pull request by aaronjwood**
From discussions:
https://github.com/istio/istio/issues/6148
https://groups.google.com/forum/#!topic/istio-security/Cp-uy5O1MiM

### CODE REVIEW

**Comment by costinm** [comment]
As I mentioned, I do not believe 'switching' is acceptable, and breaks upgrade requirements. 
Adding EC256 as an option is fine - removing RSA is not. 
/hold

**Comment by aaronjwood** [comment]
The [RFC](https://tools.ietf.org/html/rfc3280#section-4.1.2.7) outlines that CA signature algorithms do not need to match that of which they are signing. How do you see this breaking upgrades?

**Comment by rshriram** [comment]
We have some pregenerated certs somewhere. Please update them.

**Comment by rshriram** [comment]
@costinm he is right. I checked docs. Virtually every browser client out there supports ECC. Envoy has supported both since beginning. The thing that we need to ensure is to run this new CA with older istio 0.8 deployment and make sure mTLS still works.

**Comment by costinm** [comment]
Even if browsers support that, there is still no good reason to _remove_. As I mentioned multiple times, adding is ok, and _after_ it is tested in a release we can discuss making it the default, and after that we can discuss removing RSA, if we find that indeed there is no interoperability or upgrade issue. 

Passing the tests is not sufficient - Istio must run in many environments.

So I remain strongly against this PR - and request adding ECC as an option, with a flag (off by default
in at least 1.1). In general all big features must have a flag - and go trough the process of alpha/beta/etc.

**Comment by aaronjwood** [comment]
I can rework my PR to support both. How should the switch be done? Just another flag to the `generate_cert` command + a flag to the CA service?

**Comment by costinm** [comment]
A flag to the CA service for sure, probably the tool as well ( not sure if it's used except for testing).

I think it's reasonable to generate both RSA and EC, and in a future version switch pilot to direct sidecars to use the EC variant, and users who want only EC can change the flag to only use EC.

When we confirm no users need RSA we can drop the code.

Thanks for this PR - I think it is great to start adding EC, but we need to do it gradually.

**Pull request closed without merging**
