### PR TITLE
Revert custom TLS termination at sidecar for now

### PR DESCRIPTION
**Pull request by rshriram**
Due to a host of complications arising from the ALPN matches and
supporting TLS termination with permissive mode, for the moment,
we decided to revert this work in the networking WG. We will revisit
this in the 1.7 timeframe.

Also updated the API.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by nrjpoddar — APPROVED** [review]
@rshriram is there corresponding api repo commit(s) that you also reverted?

Secondly, is there a bug/customer issue that we know was dependent on this. We should update it with the new 1.7 milestone.

**Comment by hzxuzhonghu** [comment]
Not yet, this feature is only on master branch, haven't released yet

**Comment by rshriram** [comment]
>@rshriram is there corresponding api repo commit(s) that you also reverted?

Yes.

**Review by howardjohn — APPROVED** [review]

**Comment by jacob-delgado** [comment]
Correct me if I'm wrong, but this is related to this task, 
https://docs.google.com/spreadsheets/d/1y4Beb6shwWVsTYSDLZS3oUz8iRNhH2M7Hgw-kwrRhso/edit#gid=874001216&range=A11, correct?

**Comment by hzxuzhonghu** [comment]
@jacob-delgado Yes, but there is a new API on the way.

**Pull request merged**
