### PR TITLE
Added a new file to route request between v2 and v3.

### PR DESCRIPTION
**Pull request by gyliu513**
Many test cases in doc want to use jason+v2 and v3 reviews, so it is better update this file to support.

Such as 
- https://istio.io/docs/tasks/security/basic-access-control/#before-you-begin
- https://istio.io/docs/tasks/policy-enforcement/rate-limiting/#before-you-begin

/cc @frankbu @rshriram

### CODE REVIEW

**Comment by frankbu** [comment]
The traffic management tasks use this file and they require v2/v1.

The actual problem is that nobody has updated the policy and security tasks for v1alpha3 yet. They don't work. They might need a new yaml file, but `route-rule-reviews-test-v2.yaml` needs to stay as it is.

**Comment by gyliu513** [comment]
@rshriram @frankbu comments for this?

**Comment by frankbu** [comment]
I'd prefer to see the tasks changed, instead of adding more yaml files that aren't really needed.
See https://github.com/istio/istio.github.io/pull/1475#discussion_r194090916

**Comment by gyliu513** [comment]
@frankbu  I still prefer using this file, if you take a look at the content here https://istio.io/docs/tasks/security/basic-access-control/#access-control-using-denials , you may see all of the follow up test cases are based on v3 and there are also some YAML template like https://raw.githubusercontent.com/istio/istio/release-0.8/samples/bookinfo/kube/mixer-rule-deny-label.yaml .

If I do not create this PR, then I will need to update the YAML file of https://raw.githubusercontent.com/istio/istio/release-0.8/samples/bookinfo/kube/mixer-rule-deny-label.yaml .

**Pull request merged**
