### PR TITLE
Istio OSS Release Process Doc

### PR DESCRIPTION
**Pull request by hklai**
This is the Istio OSS release process that we have reviewed in the working group meeting yesterday. 
https://docs.google.com/document/d/1r36tGVhH9R7VhQT9q_nltRMjUjUA02ntpKMi8Bl7vyA/edit?ts=5a750deb#

Lin, please review and also approve the Google Doc (i.e. add a "X" next to your name) if you approve the process.

### CODE REVIEW

**Comment by hklai** [comment]
Thanks Lin.

It was partially documented in Martin's doc (*https://goo.gl/dcSBxF
<https://goo.gl/dcSBxF>) about LTS releases.*

There will be discussion around whether we make 0.7 an LTS (or quarterly,
fully supported release). It is mainly a manual process on top of the
regular scheduled release process as documented here. We can amend this doc
later if needed. WDYT?

**Comment by linsun** [comment]
Yes, it is ok to append.  I just think that is an important thing to put out in the website as our monthly release and unstableness has caused many concerns.

**Comment by hklai** [comment]
Agreed. And I added some basic info in
https://docs.google.com/document/d/1r36tGVhH9R7VhQT9q_nltRMjUjUA02ntpKMi8Bl7vyA/edit#heading=h.zapoyhjl32gq
until we have a more established process around it.

If that looks fine, please explicitly approve the doc as well. I will also
copy the addition to the README.md in this PR.

Thanks!

**Comment by hklai** [comment]
I have added information about quarterly release in https://docs.google.com/document/d/1r36tGVhH9R7VhQT9q_nltRMjUjUA02ntpKMi8Bl7vyA/edit#, and also updated README.md accordingly.

Thanks Lin for the approval!

**Pull request merged**
