### PR TITLE
Fix ingress name conflict

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/31833

I am fairly sure, but not 100% sure, that this will not break anyone as the name is internal impl detail only.

### CODE REVIEW

**Review by stevenctl — APPROVED** [review]

**Review by hzxuzhonghu — COMMENTED** [review]
why not make the ingress ns as gateway ns

**Comment by howardjohn** [comment]
Our recommendation has been to have the Gateway live in the same namespace
as the Deployment so I figured I would keep it. There is even a env var to
enforce it happens

**Review by hzxuzhonghu — COMMENTED** [review]
As you can see the controller.List method is not quite right, the ns passed in is not equal to returned.
Not a big matter, i believe this is a legacy issue.

**Pull request merged**
