### PR TITLE
Document release steps

### PR DESCRIPTION
**Pull request by sebastienvas**
This change is [Reviewable](https://reviewable.io/reviews/istio/istio/279)

### CODE REVIEW

**Comment by sebastienvas** [comment]
Good idea. Do you want to be next ?

**Comment by ldemailly** [comment]
Happy to try yes

**Comment by ldemailly** [comment]
looks like @rshriram has a need for a new release before I'll get around to try

**Comment by sebastienvas** [comment]
already working on it

**Pull request merged**
