### PR TITLE
Refactor translateRoute by extracting two functions to process redire…

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Extract functions out to reduce its complexity and to achieve better maintainability

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
cc @howardjohn minor change

**Comment by hzxuzhonghu** [comment]
@ramaraochavali

**Comment by ramaraochavali** [comment]
Sorry
 I am OOO for next 3 days
 Will take a look when I am back if John does not get to it by then

**Comment by hzxuzhonghu** [comment]
ping @ramaraochavali, suppose you are back

**Review by ramaraochavali — APPROVED** [review]
Sorry. I missed this yesterday

**Comment by hzxuzhonghu** [comment]
NP, thank you

**Pull request merged**
