### PR TITLE
support print filename and linenum

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by ozevren** [comment]
Wouldn't this increase output size considerably? Perhaps it should be behind a flag?

**Comment by hzxuzhonghu** [comment]
@ozevren The output with this like `2018-10-10T08:17:54.722320Z	warn	istioctl/main.go:141	Platform 'kube' not supported.`

BTW glog and many other log driver print filename and line by default. Is it worth the effort adding a flag all over the repo?

**Comment by ozevren** [comment]
The flag only needs to be added to LogOptions. And the default should be backward compatible.

**Comment by geeknoid** [comment]
I don't believe we want this change. The default should be oriented towards users of Istio, not developers of Istio. There are already options to enable this kind of output, we should leave the default as it is.

**Comment by sdake** [comment]
@hzxuzhonghu thanks for the work.  Istio operators should not care if main.go is called, nor when it was called.  Istio and the diagnostics it generates is targeted at operators not developers.  Developers have to suck it up and add debug in a way that makes sense for them :)

Cheers
-steve

**Pull request closed without merging**
