### PR TITLE
Remove templates

### PR DESCRIPTION
**Pull request by sdake**
The environment workgroup wants to deprecate the install/kubernetes/templates directory.

A few addons are left in the repository so they may be diffed against the Helm chart.

If there is any file you want to remain in repo, please speak up now.

### CODE REVIEW

**Comment by costinm** [comment]
Pilot tests seem to be failing due to '--kubeconfig=' ( no value ). Not sure how it relates to the change.

**Comment by vadimeisenbergibm** [comment]
Note that there is a reference to `install/kubernetes/templates` at https://github.com/istio/istio/blob/master/Makefile#L598

**Comment by ldemailly** [comment]
where would I make the following fix, in the new world:

https://github.com/istio/istio/pull/5028/files#diff-17e443480eea200223e3547be4382604

**Comment by linsun** [comment]
Is there a way to see the release binary with this PR before this PR is merged?   I 'd like to look at it to make sure we aren't missing anything major.  cc @hklai 

@sdake thanks for opening the PR to track this big concern.

**Comment by douglas-reid** [comment]
In the PR description, we mention keeping the addons, but I think we actually want to remove some of them (and then transition the other ones). In particular, the duplicative `grafana`, `prometheus`, and `zipkin` templates should disappear (as they are outdated).

**Comment by costinm** [comment]
Yes, for 0.8 we need to cleanup both the tree and release. Zipkin
deprecated addon was used in tests.

**Comment by sdake** [comment]
@linsun I'm not sure how to produce a binary release.  After having a good look at the codebase, this change may be dangerous as I don't entirely understand all of the variants in the templates directory and who needs what.

@douglas-reid i'll remove the addons as well, although I am not sure we have sorted out a solution for generating addons from via ```make generate_yaml```.

@ldemailly agree that is the goal of this PR, however, it feels risky given that convergence on the helm charts has not completely finished as evidenced by the changes going into this directory.

**Comment by costinm** [comment]
I don't think we need to generate the same yaml - except for istio.yaml and
istio-auth.yaml maybe.
We agreed that supporting/testing all combinations is not needed for 1.0,
and the -namespace
variants can be removed.

The 'official' install options are real helm+tiller or
helm-template/istioctl. For 0.8 to ease migration
we may still generate the old istio.yaml - with clear warnings it is
deprecated and not meant for
production.

The goal is to get to 1.0 - and we agreed on how the install will look
like. We have 1-2 weeks to
polish the 0.8 release - and making sure we're not testing deprecated
configs that will not be used
by our users seems pretty important given how much we rely on the automated
tests. They
can't test configs we won't ship - if removing the old templates breaks the
test it means the tests
were already broken.

**Comment by sdake** [comment]
@costinm sounds good.

One tactical problem - I am loaded on documenting multicluster for the next 4 days and then i am traveling to Copenhagen returning May 5th.  I can work on improving this PR after the docs are resolved, and even during travel but I'm not certain I have enough time to finish the job if the job involves convergence into the main helm chart (to enable a functional automated testing for example).

**Comment by sdake** [comment]
Here is citadel standalone - https://github.com/istio/istio/pull/5292.

Convergence of each of these templates into the main chart will take some time - I think not viable for 0.8.

**Comment by sdake** [comment]
abandoning this PR as most of the work has been done by other folks.  I will continue forward to make citadel standalone work properly from the main helm chart.

**Pull request closed without merging**
