### PR TITLE
update istio-operator version to 1.9

### LINKED ISSUE #31019: Chart manifest version issues / conflicts.
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

It seems that chart versions have not been updated when changes are made to the repos. The side effect of this is cicd processes can often fail or end user mistakes since the resulting .tgz will always be 1.7.0 which is confusing to the end user.

Ideally the chart version should be reflective of the version of istio being deployed. i.e 1.9.0 should be 1.9.0 if this includes changes to the charts.

https://github.com/istio/istio/blob/master/manifests/charts/istio-operator/Chart.yaml

[X] Installation
[X] Upgrade

**Expected behavior**

Generally charts should be incremented with changes.

**Steps to reproduce the bug**

**Version** 1.7 >

**How was Istio installed?**

Istio operator via helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/31019

Related:
https://github.com/istio/istio/pull/25785

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
I was thinking updating the chart version in script so that we don't need to update it manually, maybe with https://github.com/istio/istio/blob/master/operator/scripts/update_version.sh

**Comment by pramodrj07** [comment]
LGTM

**Comment by shamsher31** [comment]
> I was thinking updating the chart version in script so that we don't need to update it manually, maybe with https://github.com/istio/istio/blob/master/operator/scripts/update_version.sh

Not sure when that script is executed?

**Comment by howardjohn** [comment]
@jacob-delgado I think you had some thoughts around this in the past? I don't remember, but I think the gist is that release-builder dynamically updates this and we should not be touching it here. All other charts are `version: 1.1.0`

**Comment by shamsher31** [comment]
cc: @jacob-delgado

**Pull request closed without merging**
