### PR TITLE
Revert switch to jaeger

### PR DESCRIPTION
**Pull request by douglas-reid**
It was discovered that the image we wanted to use for jaeger tracing has problematic memory profiles by default. Instead of trying to tune the images and find a production-ready deployment scheme, this PR reverts the changes as a starting point -- particularly to unblock release. When a better approach to running with Jaeger is developed, we can go forward with this transition.

cc: @objectiser

### CODE REVIEW

**Comment by ldemailly** [comment]
for #5782

**Comment by hklai** [comment]
@douglas-reid  Are the automatic tests good enough to validate this? Is any additional / manual testing required?

**Comment by douglas-reid** [comment]
The existing tests should be sufficient. We we're testing manually with this setup during the first release testing day.

**Comment by douglas-reid** [comment]
I can manually verify from a daily build when next in the office. 

Peter can also verify quickly.

**Comment by mandarjog** [comment]
Everything passes except flaky e2e-pilot tests.
Unfortunately that means there are no zipkin tests that I see.

**Comment by objectiser** [comment]
Based on [this recent comment](https://github.com/istio/istio/issues/5782#issuecomment-391741160) it looks like zipkin has the same issue - so maybe would be better to unrevert this change and we will try to get a fix for jaeger asap?

**Comment by ldemailly** [comment]
i mentionned it yesterday too (that regpatrol/jose saw the same issue with zipkin)

what is odd is it was working before so something else changed ?

re test: pilot is where “addons” are tested afaik

**Comment by mandarjog** [comment]
https://github.com/istio/istio/pull/5840   switching back to jaeger.

**Pull request merged**
