### PR TITLE
Added dynamic namespace selector for mutating webhook

### PR DESCRIPTION
**Pull request by rahtr**
**Please provide a description of this PR:**
There are instances when users can't use the static namespace selectors. This PR makes the namespace selector as an optional input value. If it isn't provided then use the defaults.

### CODE REVIEW

**Comment by howardjohn** [comment]
Can you give more context on the use case?

These selectors are extremely finnacky, complex, and error prone. Would be good to be really sure we need it before introducing more complexity

**Comment by rahtr** [comment]
We manage a fleet on K8s multi-tenant clusters which are exposed to our internal teams via various homegrown tools. These tools are managed by different teams and have different ways to provision namespaces. When these namespaces are provisioned, there are certain prefixes that are added to the labels/annotations which are governed by the security policies. For example, if a team wants to create a namespace `foo` on multi-tenant clusters which has a label with a key `istio.io/rev`, a prefix like `infosec-istio.io/rev` automatically gets added to the namespace label.

This PR would take care of such scenarios and make the mutating webhook configuration more dynamic.

**Comment by rahtr** [comment]
@howardjohn , could you please review my comment above and see if this use case sounds reasonable for this fix?

**Review by costinm — COMMENTED** [review]
If your use case is that you add a prefix to the label - why not just add a prefix setting, instead of the far more complicated selector ?

**Comment by rahtr** [comment]
> If your use case is that you add a prefix to the label - why not just add a prefix setting, instead of the far more complicated selector ?

Could you please share an example? Where do we add this prefix setting?

**Review by howardjohn — CHANGES_REQUESTED** [review]
I suggest tackling this problem outside Istio. The webhooks already cause nightmares of complexity as is, and I am not very much in favor of introducing more complexity unless we are 100% sure we require it. https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/ may be an alternative approach to solve this out of band

**Comment by rahtr** [comment]
> I suggest tackling this problem outside Istio. The webhooks already cause nightmares of complexity as is, and I am not very much in favor of introducing more complexity unless we are 100% sure we require it. https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/ may be an alternative approach to solve this out of band

There are many ways to tackle this outside this, however this looks like a straightforward approach. 
This looks like a pretty common approach for managing selectors. For example check this webhook configuration for cert manager(https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml#L17).

**Comment by howardjohn** [comment]
I am aware that other projects have different offerings. However, Istio's webhooks are far more complex due to various factors (legacy decisions, namespace + pod labels, revisions) that make them far less appealing to support customization directly in the project.

**Comment by rahtr** [comment]
> I am aware that other projects have different offerings. However, Istio's webhooks are far more complex due to various factors (legacy decisions, namespace + pod labels, revisions) that make them far less appealing to support customization directly in the project.

Wouldn't the problem you highlighted persist if we change the namespace via Kustomize? Moreover this is an optional feature.

**Pull request closed without merging**
