### PR TITLE
Fix IP reshuffling when add/remove duplicated hostname

### PR DESCRIPTION
**Pull request by krutsko**
**Please provide a description of this PR:**

Fix for https://github.com/istio/istio/issues/49809

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]
Thank you for the fix

**Comment by hzxuzhonghu** [comment]
we need backport

**Comment by jbilliau-rcd** [comment]
hey all, 2 questions:

1.) Any idea what Istio release this will make its way into? We definitely want to get this fix deployed out asap, we've run into this a few times now in production.

2.) Is this a separate, ad-hoc fix than the DNS Autoallocate @howardjohn  is talking about in this comment? https://github.com/istio/istio/pull/45330#issuecomment-2143031350

If so, sounds like this will likely make its way into Istio sooner, so I won't have to wait for the revamp to get this fix. Is that accurate?

**Comment by hzxuzhonghu** [comment]
This is fixing a corner case, not that like https://github.com/istio/istio/pull/45330#issuecomment-2143031350 proposed. The ideal solution should be discusssed there

**Pull request merged**
