### PR TITLE
re-enable v2 integration test with updated proxy 

### PR DESCRIPTION
**Pull request by bianpengyuan**
Add vm_id as an addition to change in https://github.com/istio/istio/pull/17915. This fixes issue in an istio proxy test: https://github.com/istio/proxy/pull/2466. I am trying to see if it fixes the test here. 

Also it looks like EnvoyFilter is namespace-ed and gateway EnvoyFilter has to be defined within `istio-system` namespace?

### CODE REVIEW

**Comment by mandarjog** [comment]
@jplevyak is it per your expectation that we need to specify both vm and root with nullvm?

**Comment by rshriram** [comment]
So, if you want to apply the EnvoyFilter to everything, it has to be in the ConfigRootNamespace [i.e. istio-config namespace]. If you put this in the istio-system namespace, and someone defines istio-config as the root namespace, then once again the telemetry will break.

**Pull request merged**
