### PR TITLE
RFC: Commit vendor

### PR DESCRIPTION
**Pull request by jwendell**
Inspired by https://groups.google.com/forum/#!topic/istio-dev/vpz5w1C-C_0

This is an initial approach to have the vendor dir checked in. It brings the benefit of a totally reproducible and offline build. The normal workflow for building Istio with this feature in would be just 1) Download it (tarball tgz for example) and 2) run `make`. It should work out of the box in an offline system.

It's worth noting that other [big] projects like kubernetes do this way. I believe it brings more pros than cons (like a bigger repo).

Thoughts?

### CODE REVIEW

**Comment by ldemailly** [comment]
we should not do this and we need to make sure the pr itself doesn’t bloat up the repo size

**Comment by ZackButcher** [comment]
[Here's the mailing list thread for those that're interested.](https://groups.google.com/d/msg/istio-dev/vpz5w1C-C_0/rb5B9IvHAAAJ)

Creating the PR doesn't hurt anything and helps drive the discussion forward, since it'd stalled in the mailing list.

**Comment by costinm** [comment]
I think this is an important decision - we'll never reach 100% consensus,
but would be good to discuss
it more formally in the appropriate WG. I'm personally +1 on some form of
vendor checkin - and
I think air-gaped builds are a valid and critical requirement, and vendor
provide other benefits.

Given the strong opinions - I think it's worth trying first with a vendor
git sub-module. We can create
another istio/vendor git tree for that. For me the test is if 'go get' will
download the sub-module
correctly and finally work for istio. While git sub-modules have their own
problems we may get
the same benefits.

It is important to be consistent with other projects - like kubernetes,
etcd, etc - using vendor,
so I don't think the argument that istio devs will suffer terribly if we
check it in is valid. "dep" is great
and we'll continue to use it to keep vendor in sync with semver, but it
can't provide the isolation.

I agree with the concern that vendor update PRs will be large - but it is
also a chance to at
least superficially see/review what changed in projects we depend on when
we do the periodic update.

Costin

**Comment by zachgersh** [comment]
Gave the single submodule for the whole vendor dir a quick try this morning - `go get` will totally fetch it. This will work but it feels like the wrong approach still. Whether your dependencies are in the same project or in a different repository you will end up downloading all of the code to your machine regardless. A repositories dependencies are just as important to the project history as its own source - so I don't mind dependency only commits being in the same repo.

Side note: when all of these dependencies were originally vendored with dep it seems like we failed to run `dep prune` (I can tell because I see a whole bunch of `_test` files in each of the dependencies). So the project could potentially drop quite a few LOC just by running that.

**Comment by jwendell** [comment]
I'm experimenting with submoduling vendor.

Here's an issue: When you run `dep` it will delete and recreate the vendor dir, thus erasing the submodule status, making vendor dir an ordinary dir.

I'm afraid that, in order to workaround situations like this, we'll have to create an unnecessary complex Makefile/scripts solutions.

Also, we should make sure that releases would include vendor dir by default in tarballs.

Do you know of a golang project that has vendor as a submodule? I guess that if it's so good as it sounds, projects like kubernetes would use it, no?

**Comment by zachgersh** [comment]
@jwendell would you also mind running the `dep prune` on your PR. I'd love to know how many fiels we are going to drop.

**Comment by jwendell** [comment]
@zachgersh thanks for the `dep prune` hint. It indeed saved a lot of bytes!

Before prune:
```
19515 files changed, 7844506 insertions(+), 1 deletion(-)

$ du -csh vendor/
363M	vendor/
```

After prune:
```
5291 files changed, 1627481 insertions(+), 2 deletions(-)

$ du -csh vendor/
65M	vendor/
```
I've made this change and force-pushed to this PR.

It's worth to note, in this PR, only the first commit (Add vendor to SCM) is the giant one, others are easy to review :-).

**Comment by kyessenov** [comment]
We should ask Kubernetes folks what their plans are. Some choices that the
team made were way before tools like dep, faster "go", and some github
features existed, so it's not necessarily true that they would make the
same choices now.

**Comment by ldemailly** [comment]
> Here's an issue: When you run dep it will delete and recreate the vendor dir, thus erasing the submodule status, making vendor dir an ordinary dir.

> I'm afraid that, in order to workaround situations like this, we'll have to create an unnecessary complex Makefile/scripts solutions.

We need a target / automation to update the vendor either way (basically dep ensure + commit script). I don't see how it'd be more complicated to do so in a submodule than the base. With the benefit of not trashing the main repo with hundreds of file changes each time we rev up a dependency

**Comment by costinm** [comment]
I don't think this thread will reach agreement - please write a small
proposal and add it to the agenda for next release
WG meeting, with the 3 options.

I'm +1 on checking in vendor as in your PR, but I think the submodule
option (while it creates complexity and is
not used by any project I know) is more likely to sail trough.

Either way - releasing a .tar.gz with all source and vendor as part of the
release is a MUST.

To be clear: this is not an issue of space or downloads. No matter what,
the developer will download all the
vendor - either just the vendor files from one repo ( your PR), from 2
repos ( submodule ), or 100 repos ( dep ensure).
In the 100 repo we'll actually download much more - the entire git history
of all deps is downloaded, and then
a copy is made to vendor. The first 2 options will use far less space.
The download time is also much faster from 1 or 2 repos.

It's also not a burden on github - they likely dedup on SHA, so they'll not
waste a lot of disk.

I think the main valid concern raised is that 'vendor' update PRs will be
large, hard to review/submit - and create
aesthetic discomfort to some developers.

Costin



On Fri, Jan 19, 2018 at 10:53 AM, Laurent Demailly <notifications@github.com

**Comment by costinm** [comment]
BTW - if possible, please do a 'time git clone ...istio -b your_pr'  on a
clean directory, as well as
a 'time git clone istio' and 'time dep ensure --vendor-only'. And a 'du
-sh' on the istio directory in both
cases, as well as a du -sh in the pkg directory (for the space taken by dep
cloning all dependency git)
Good to have data.

Costin

**Comment by ldemailly** [comment]
cc @geeknoid

**Comment by mattdelco** [comment]
If offline and reproducible are the main motivations then there will need to be a story on a build that doesn't make queries to git (mostly via bin/get_workspace_status).  Ideally the behaviors of an on-line and off-line build have minimal differences--few people will test offline builds, and even fewer will check that the result of the build is the same.  I suppose it's possible to have make run get_workspace_status and store the results in a file somewhere that's consumed by the other components but I don't have any decent ideas on how/when to trigger a refresh of the file.

This vendor/ directory might only address the go part of the build, as the docker part seems to pull from remote locations (via actual pull, or "apt get"), though I'm not sure if it's up to istio or proxies to make this work offline.

I'm not strictly for or against at this point--I haven't done any analysis yet since presently I'm still focused on getting things migrated over to make (& addressing regressions, not all of which are attributable to make) while trying to keep a partial eye out for other changes that break things or complicate things (reproducibility or otherwise).

**Comment by sdake** [comment]
air-gapped builds are a must as @costinm points out.  However, as @ldemailly points out, I'm not a fan of checking in thousands of files that may change in the main repo creating a monstrous repository over the long term in terms of size and review requirements.

Someone in this thread suggested checking with the Kubernetes team if they would make the same choice again or if they would suggest a different approach.  This seems like a pretty valid idea to me.  Would someone mind following up on that request?

Cheers
-steve

**Comment by smarterclayton** [comment]
I can speak to Kube a bit - generally, we have decided against submodules for a number of mechanical reasons:

* the complexity to tooling, such as extra steps required in the various automation tools around the ecosystem
* explaining to new users
* the scope of the dependencies and their management
* problems with submodules and symlinking directories to break sub vendor directories (this is the biggest - you have to omit the nested vendor directory)

Some of this is "we've been vendoring, and the effort to change isn't worth it", but there are various things in submodules that make them just painful enough that they aren't seen as a step forward.

A note on tools: at the scale and complexity of kubernetes, none of the dependency management tools for strict vendoring are a clear win - glide at this point is the best, `dep` is getting there but is still having challenges against our dependency tree.  But managing dependencies is hard no matter what once different vendored tools depend on different versions of commonly exposed interfaces.

**Comment by costinm** [comment]
I think one of the arguments was that K8S (and the many other projects
using vendor) are having major problems - with the
changes in vendor, repo size, etc - and are in process or plan to soon drop
vendor and switch to dep.

If vendor works for k8s - and it's not painful enough that they want to
switch - I think it will work well enough for us, since
they have far more deps and complexity.

We have no reason to invent new things in dep management, or just do thing
differently.

**Comment by jwendell** [comment]
Some numbers...

Istio repo, as of today:
```
$ git clone https://github.com/istio/istio
Cloning into 'istio'...
remote: Counting objects: 41216, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 41216 (delta 103), reused 106 (delta 102), pack-reused 41096
Receiving objects: 100% (41216/41216), 12.67 MiB | 380.00 KiB/s, done.
Resolving deltas: 100% (26562/26562), done.

$ cd istio
$ dep ensure -vendor-only
$ du -csh
407M	.
407M	total
```
This PR (with vendor checked in):
```
$ git clone -b commit-vendor https://github.com/jwendell/istio istio-with-vendor
Cloning into 'istio-with-vendor'...
remote: Counting objects: 65193, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 65193 (delta 107), reused 114 (delta 106), pack-reused 65063
Receiving objects: 100% (65193/65193), 71.41 MiB | 382.00 KiB/s, done.
Resolving deltas: 100% (31890/31890), done.

$ cd istio-with-vendor
$ du -csh
160M	.
160M	total
```
I didn't measure time because it might vary depending on the network. In fact even here on my environment, issuing two consecutive `git clone`s timing was different, due to network speed being different.

**Comment by zachgersh** [comment]
The final argument for just committing all of vendor without a submodule:

its easier to convert from a simpler solution (just vendoring everything) to a more complex solution (submodules) than to go the other direction. I'd like to see this merged as is.

**Comment by ldemailly** [comment]
> its easier to convert from a simpler solution (just vendoring everything) to a more complex solution (submodules) than to go the other direction. I'd like to see this merged as is.

that's not correct where it matters, which is the git history gets permanently bloated once this gets in (unless we rewrite the history like we did for the mono repo cleanup)

**Comment by zachgersh** [comment]
@ldemailly - I respectfully disagree as the simplicity I was referring to was the developer workflow of not having to think about a submodule when adding/removing/changing dependencies. 

You can ignore the commits where we are merely adding / bumping dependencies. Changing the commit workflow to not squash all the commits into one would keep the history just as clean.

**Comment by rshriram** [comment]
I think this comment alone sold me on committing vendor
https://github.com/istio/istio/pull/2691#issuecomment-360142399 . Downloading a single 160Mb code base vs downloading a half a GB worth of code from github to compile istio is a big difference. It would also simplify the ci/cd pipeline, as we would no longer be breaking our heads over caching/cache invalidation. (cc @costinm )

The benefits outweigh the concerns, in my opinion.

**Comment by rshriram** [comment]
One thing I would say is that we need to have a discipline. We need to have separate PRs that add vendors vs those that add actual code. PRs that update both vendors and code should be disallowed, as it makes it hard to review such PRs.

**Comment by rshriram** [comment]
cc @geeknoid / @louiscryan what do you guys think? (getting rid of dep management tools, and dependency caching in circleci/prow is a big win imo).

**Comment by costinm** [comment]
There are clear trade-offs - but Kubernetes and many other larger projects
seem to be willing to trade some bloat in commit history
and have vendor checked in ( and time/space saved on the dep ensure ).

Ability to see what changed in the deps ( == history bloat ) is also a good
feature in some cases.

I'm well aware of the simplification and time improvements that vendor has
over running dep - that's why I asked for
'time', it's also part of the trade-off benefits.

In terms of 'du -sh' - please also do a du in the GOPATH/pkg/dep directory
- 1.3 G is there.

**Comment by kyessenov** [comment]
I would listen to @smarterclayton and not consider committing vendor strictly better. It's hard no matter what we do, for reasons not related to where the code is pulled from (incompatible versions). I personally dislike the commit noise with the vendored code, and also not happy about the never-ending churn in the development processes. But these are just personal preferences, and I can live with either choice.

**Comment by costinm** [comment]
Well, I am listening to what other projects actually use and do.

Vendor is obviously not strictly better - it has many problems, like the
ones discussed in this thread. Yet most projects seem to chose
to accept that and make the trade-off, including k8s - and that's what we
should follow.

**Comment by kyessenov** [comment]
There is one drawback with generated files since we vendor them. With vendor if I need to modify a proto, I have to:
1. commit proto change to istio/api
2. commit change to .pb.go to istio/api along with it
3. commit the change to istio/api to istio/istio/vendor

vendor gives no automation, dep automates step (3), bazel used to automate (2) and (3).

**Comment by jwendell** [comment]
Note that I touched circleci config dropping the dependencies target, so this "ci/circleci: dependencies" test might not be never executed.

**Comment by rshriram** [comment]
> Note that I touched circleci config dropping the dependencies target, so this "ci/circleci: dependencies" test might be never executed.

Thats the whole point. No dependency phase :).

**Comment by sdake** [comment]
@costinm Agree with your framing of the issue.

Cheers
-steve

**Comment by linsun** [comment]
/LGTM
pending test passing, given this reduces binary we need to bring from 400M to 160M and following k8s's lead.

**Comment by ldemailly** [comment]
/approve cancel 
we have decided to get more information about why the alternative would not work before merging this

**Comment by linsun** [comment]
That is fine, I just wanted to record my vote as it has don't merge tag anyway.

**Comment by kyessenov** [comment]
Re: kubernetes lead. Let's hear their _experience_ and make an _informed
decision_, not things that might be there by chance.

**Comment by linsun** [comment]
https://github.com/kubernetes/kubernetes/tree/master/vendor - does this indicate k8s uses vendor dir?

**Comment by ldemailly** [comment]
yes @costinm made that point multiple times, we are waiting to hear though "why" and "if they would start today would they make the same choice"

**Comment by costinm** [comment]
Yes, k8s and most projects I know do use vendor dir.

As an update - on the WG meeting we seemed to have agreed that it is
valuable to have vendor, and the main pending issue is to
understand if submodule is a viable option or not, some people expressed
concerns that all the projects using vendor failed to
try submodule or have checked in vendor before 'dep' or godep or glide were
available.

The action is to gather feedback from k8s and other projects on their
experience with submodules or alternatives to vendor.

It was also agreed by most people that vendor is not perfect - but people
want more information on why k8s and everyone else
made this tradeoff.

It was also proposed for people who have strong opinions and feel this PR
would help should indicate so, and eventually
use this as a data point in the decision ( which hopefully will be made at
next week WG meeting ).

**Comment by kyessenov** [comment]
Well, k8s is heading towards Bazel if we're serious about copying other
projects verbatim :) k8s uses Godeps, glide (?), bazel, vendor, all at the
same time, using quite a complex machinery to keep everything in sync.

**Comment by ldemailly** [comment]
Irrespective of whether we commit vendor or not, we need to do #2875 (first)

**Comment by ldemailly** [comment]
here is the alternative: #3348 - 8mbytes sub module - PTAL

**Comment by knrc** [comment]
It appears this comes down to a question of trade-offs, i.e. is it worth checking in the vendor directory to istio/istio and keeping things simple or modifying the build process to support sub-modules and coordinating releases across multiple repos.

We were supposed to discuss this in yesterday's call but did not manage to do so as it was pushed down the agenda, it would be good to make this a high priority issue on next week's agenda if we cannot get a consensus through these discussions.

**Comment by hklai** [comment]
Noted and agreed. We should get a closure since it has been dragging for
weeks. I will put this as the first agenda next week

**Comment by ldemailly** [comment]
there is no “modifying the build process” difference between submodule or direct checkin - either way a small change is needed

**Comment by knrc** [comment]
@ldemailly Unfortunately I believe you are missing some important aspects but I will try to elaborate on the problems with submodules on the other PR.

I also don't believe they both require changes, with the submodule approach you will have to modify the scripts to use git rather than dep however when committing to the same repo they should work without any necessary changes.  Of course submodules also changes the developer flow which could lead to more serious issues but please take a look at the other PR and comment there.

**Comment by ldemailly** [comment]
the current istio build has a bunch of dep run logic which will need to be removed/moved to a separate target either way (when a dependency update is needed instead of mandatory to build)

**Comment by ldemailly** [comment]
Thanks for having brought up the issue !

Fixed through #3348  #3678 #3697 
and the growing https://github.com/istio/istio/wiki/Vendor-FAQ

**Pull request closed without merging**
