### PR TITLE
Enable TestTunnelingOutboundTraffic and configure access log in forward proxy

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>

**Please provide a description of this PR:**

Related issue: #39586

I investigated config dumps from few failed tests and I can't find any misconfiguration. I didn't encounter similar problem on my computer - the tests always pass. So the first step to understand the problem better is adding access log to the forward proxy. I would like to know what status code and flag are returned.
After merging this PR I will look for failing post-submit tests and will try to solve to cause of the problem (I have some ideas, but I am not sure at the moment) or disable test again.

### CODE REVIEW

**Comment by jewertow** [comment]
JFYI: I found the real cause of fails on multi-cluster setup. I will push fixes soon.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/38982 is the root cause of many issues we see in other tests. But it seems odd to trigger here since this is mostly testing gateways.

I was waiting to approve since you said you had found a fix. Do we need to merge to get more diagnostics?

**Review by howardjohn — APPROVED** [review]

**Comment by jewertow** [comment]
TestReachability still fails

**Pull request merged**
