### PR TITLE
Make metrics command ready for web scale.

### PR DESCRIPTION
**Pull request by PiotrSikora**
This change makes the output denser and easier to read.

Example usage (bookinfo example):

```
$ istioctl experimental metrics productpage reviews ratings details
    SERVICE    TOTAL RPS    ERROR RPS  P50 LATENCY  P90 LATENCY  P99 LATENCY
productpage        7.873        0.000         40ms         80ms         98ms
    reviews        7.909        0.000          4ms          9ms         21ms
    ratings        5.309        0.000          2ms          4ms          4ms
    details        7.873        0.000          3ms         38ms         48ms
```

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@douglas-reid ALL CAPS IT IS! :)

**Comment by douglas-reid** [comment]
@PiotrSikora looks good! maybe retarget this to the 0.8 release branch (as master is locked) ?

**Comment by PiotrSikora** [comment]
@douglas-reid @nmittler I couldn't find a way to retarget this on GitHub, so I created another PR https://github.com/istio/istio/pull/5289 for 0.8 release.

**Comment by douglas-reid** [comment]
Can we close this now?  Was this merged back into master ?

**Comment by PiotrSikora** [comment]
@douglas-reid Yeah, it was merged into `master`. Thanks!

**Pull request closed without merging**
