### PR TITLE
Moving trustbundle library after CA initializaton

### PR DESCRIPTION
**Pull request by shankgan**
Moving trustbundle library after CA initializaton

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Isn't there any test now?

**Comment by ramaraochavali** [comment]
Can we add a test case for this if possible?

**Comment by shankgan** [comment]
> Can we add a test case for this if possible?

I am already planning to add an e2e test. Will look into adding a unit test as well.

**Comment by hzxuzhonghu** [comment]
Thanks, e2e is necessary to guarantee this feature works

**Pull request merged**
