### PR TITLE
Fix empty response from verify-install

### LINKED ISSUE #32730: istioctl verify-install cmd respond empty content if can not access k8s cluster
**Bug description**
istioctl verify-install cmd respond empty content if can not access k8s cluster

[X] Installation

**Expected behavior**
output the error details.

**Steps to reproduce the bug**
use wrong kubeconfig to call istioctl with: `istioctl verify-install -r default --kubeconfig /tmp/x`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.2

**How was Istio installed?**
istioctl

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix #32730

### CODE REVIEW

**Comment by kebe7jun** [comment]
@istio/wg-user-experience-maintainers PTAL.

**Review by shamsher31 — APPROVED** [review]
Thanks

**Pull request merged**
