### PR TITLE
waypoints: use unique identity, allow namespace-wide

### PR DESCRIPTION
**Pull request by howardjohn**
Implements
https://docs.google.com/document/d/1N5Qcta-3tBLR0nzIxrc_qVATvyhbvtPE4wp1qnp4cew/edit#

Fixes https://github.com/istio/istio/issues/42955

Depends on https://github.com/istio/ztunnel/pull/364

**Please provide a description of this PR:**

### CODE REVIEW

**Review by dhawton — APPROVED** [review]

**Comment by GregHanson** [comment]
@howardjohn not sure if this was intentional, by not auto appending `-waypoint...` to the waypoint proxy, this creates some collisions when the gateway name is the same as the deployment of the targeted backend service/service account.

for example:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: httpbin
  annotations:
    istio.io/service-account: httpbin
spec:
  gatewayClassName: istio-mesh
```
fails to create a deployment because there is already a httpbin deployment present.  Log from istiod:
```
2023-01-31T22:12:31.526042Z	info	waypointproxy	Updating waypoint proxy "httpbin-waypoint"	gateway=default/httpbin
2023-01-31T22:12:31.526056Z	debug	Handle event add for configuration gateway.networking.k8s.io/v1beta1/Gateway/default/httpbin
2023-01-31T22:12:31.546338Z	error	controllers	error handling default/httpbin, retrying (retry count: 0): waypoint deployment patch error: Deployment.apps "httpbin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"istio.io/gateway-name":"httpbin"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable	controller=waypoint proxy
2023-01-31T22:12:31.546397Z	debug	controllers	handling update: default/httpbin	controller=waypoint proxy
2023-01-31T22:12:31.546417Z	info	waypointproxy	Updating waypoint proxy "httpbin-waypoint"	gateway=default/httpbin
2023-01-31T22:12:31.563937Z	error	controllers	error handling default/httpbin, retrying (retry count: 1): waypoint deployment patch error: Deployment.apps "httpbin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"istio.io/gateway-name":"httpbin"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable	controller=waypoint proxy
2023-01-31T22:12:31.564002Z	debug	controllers	handling update: default/httpbin	controller=waypoint proxy
2023-01-31T22:12:31.564024Z	info	waypointproxy	Updating waypoint proxy "httpbin-waypoint"	gateway=default/httpbin
2023-01-31T22:12:31.576639Z	error	controllers	error handling default/httpbin, retrying (retry count: 2): waypoint deployment patch error: Deployment.apps "httpbin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"istio.io/gateway-name":"httpbin"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable	controller=waypoint proxy
2023-01-31T22:12:31.576693Z	debug	controllers	handling update: default/httpbin	controller=waypoint proxy
2023-01-31T22:12:31.576715Z	info	waypointproxy	Updating waypoint proxy "httpbin-waypoint"	gateway=default/httpbin
2023-01-31T22:12:31.588603Z	error	controllers	error handling default/httpbin, retrying (retry count: 3): waypoint deployment patch error: Deployment.apps "httpbin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"istio.io/gateway-name":"httpbin"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable	controller=waypoint proxy
2023-01-31T22:12:31.596987Z	debug	controllers	handling update: default/httpbin	controller=waypoint proxy
2023-01-31T22:12:31.597053Z	info	waypointproxy	Updating waypoint proxy "httpbin-waypoint"	gateway=default/httpbin
2023-01-31T22:12:31.610681Z	error	controllers	error handling default/httpbin, retrying (retry count: 4): waypoint deployment patch error: Deployment.apps "httpbin" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"istio.io/gateway-name":"httpbin"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable	controller=waypoint proxy
```

**Comment by howardjohn** [comment]
This is semi-intentional. We probably need to be careful to not overwrite users own resources. But this now matches the behavior of https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment.

maybe we can check the existing deployment and only write it if the manged-by label is there

**Comment by GregHanson** [comment]
should service account follow the same behavior then?  When istiod creates a service account for the new waypoint proxy, it appends `-waypoint` which prevents name conflicts.  The failed Gateway above results in the following:
```
kubectl get sa
NAME               SECRETS   AGE
default            0         94m
httpbin            0         83m
httpbin-waypoint   0         9s
```

**Comment by howardjohn** [comment]
That is a good point. We probably want to be consistent.

If we do no-suffix, we should probably add `-waypoint` in all our examples where we deploy one.

If we add suffix, we don't need to, but then we lose consistency with ingress - unless we do the same for ingress.

cc @costinm

**Comment by linsun** [comment]
I think we should auto append `-waypoint` for auto generated waypoint deployments, what @GregHanson runs into could be fairly common imho.

**Comment by kyessenov** [comment]
Is there a good reason to run waypoints in the application namespace? Lots of other things like k8s RBAC will interfere.

**Comment by howardjohn** [comment]
@linsun I don't think it will be common if all our docs have proper naming - most users copy paste.

@kyessenov I had thought about this in the past. Waypoints live in the trust domain of a namespace, so running in the same namespace is a natural fit. Namespace admin has appropriate permissions to operate (access logs, deploy HPA, etc). The primary alternative, I'd imagine, is a single namespace for all waypoints (?) which runs into RBAC issues when trying to grant namespace owners permission to access their waypoints

**Comment by kyessenov** [comment]
@howardjohn I am not fully convinced. I think we were forced to run in the same namespace because of k8s token exchange model in the past (e.g. we couldn't get SA for a workload in a namespace without running in that namespace).

In my view, the operation of waypoints may not be explicitly exposed to the users. We can design telemetry around it so that the users never need to inspect the waypoints directly. The issue of trust is already solved by ztunnel being a "super-user" that can access and validate any SAs in the trust domain. A lot of actions could also be done via delegation - waypoint controller (cluster admin level) operating the waypoints but consuming namespace admin hints on HPA, etc.

Ultimately, user don't really want to debug their waypoints if they can, so optimizing for that level of expertise seems counter-productive.

**Comment by howardjohn** [comment]
I could buy an argument for it - I had originally hoped to run them
elsewhere initially but leaned to same namespace for previously mentioned
reasons. It's probably worth exploring moving them out more.

**Comment by bleggett** [comment]
> I don't think it will be common if all our docs have proper naming - most users copy paste.

Might not be - but adding a suffix/prefix specific to us has minimal cost and obviates the problem, regardless of what users do, and for that reason I favor it.

IMO any resources we create that are _not_ part of an Istio-specific API namespace should have autoprefixes/postfixes - Deployments, ServiceAccts, etc etc.

**Comment by linsun** [comment]
Discussed in today's ambient meeting, append the class makes sense to waypoint deployment.  Will also look into the istio-mesh as class name for waypoint.

**Pull request merged**
