### PR TITLE
Bump up mixer tools codecoverage > 90 ~ 95.

### PR DESCRIPTION
**Pull request by guptasu**

### CODE REVIEW

**Comment by guptasu** [comment]
@geeknoid friendly ping

**Comment by guptasu** [comment]
@geeknoid @ldemailly  can we force merge this; the failing test is well known https://istio.slack.com/archives/C6RHFVB44/p1520711185000017

**Comment by ldemailly** [comment]
merged per ^

**Comment by guptasu** [comment]
Thanks @ldemailly

**Pull request merged**
