### PR TITLE
Fix the duplicate test cases because of multiple b services deployed and skip the current failed ca_custom_root test cases in multicluster setup

### PR DESCRIPTION
**Pull request by jtrbs**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by jtrbs** [comment]
Test passed at https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28928/integ-security-multicluster-tests_istio/1328492144289124352

**Comment by jtrbs** [comment]
```

security: TestReachability/beta-mtls-on/b_in_cluster-0 | 0s
-- | --
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_http_to_a:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_ws_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_tcp_to_a:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_grpc_to_a:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_http_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_ws_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_tcp_to_b:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_grpc_to_b:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_http_to_headless:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_ws_to_headless:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_tcp_to_headless:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_grpc_to_headless:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_http_to_naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_ws_to_naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_tcp_to_naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_grpc_to_naked:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_http_to_vm:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_ws_to_vm:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_tcp_to_vm:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_grpc_to_vm:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_http_to_headless-naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_ws_to_headless-naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_tcp_to_headless-naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-0/with_scheme_grpc_to_headless-naked:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-1 | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_http_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_ws_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_tcp_to_a:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_grpc_to_a:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_http_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_ws_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_tcp_to_b:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_grpc_to_b:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_http_to_naked:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_ws_to_naked:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_tcp_to_naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-1/with_scheme_grpc_to_naked:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2 | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_http_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_ws_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_tcp_to_a:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_grpc_to_a:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_http_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_ws_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_tcp_to_b:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_grpc_to_b:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_http_to_naked:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_ws_to_naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_tcp_to_naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-2/with_scheme_grpc_to_naked:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3 | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_http_to_a:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_ws_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_tcp_to_a:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_grpc_to_a:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_http_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_ws_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_tcp_to_b:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_grpc_to_b:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_http_to_headless:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_ws_to_headless:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_tcp_to_headless:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_grpc_to_headless:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_http_to_naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_ws_to_naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_tcp_to_naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_grpc_to_naked:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_http_to_vm:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_ws_to_vm:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_tcp_to_vm:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_grpc_to_vm:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_http_to_headless-naked:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_ws_to_headless-naked:http | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_tcp_to_headless-naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-3/with_scheme_grpc_to_headless-naked:grpc | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-4 | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_http_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_ws_to_a:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_tcp_to_a:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_grpc_to_a:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_http_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_ws_to_b:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_tcp_to_b:tcp | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_grpc_to_b:grpc | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_http_to_naked:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_ws_to_naked:http | 1s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_tcp_to_naked:tcp | 0s
security: TestReachability/beta-mtls-on/b_in_cluster-4/with_scheme_grpc_to_naked:grpc


```

**Comment by jtrbs** [comment]
To fix https://github.com/istio/istio/issues/28893

**Review by yangminzhu — COMMENTED** [review]
LGTM, can you update the PR title to better describe the change, thanks

**Comment by jtrbs** [comment]
@yangminzhu sure! Updated.

**Review by stevenctl — APPROVED** [review]

**Review by yangminzhu — APPROVED** [review]

**Pull request merged**
