### PR TITLE
Test for CI jobs using the build-tools container.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by geeknoid** [comment]
@fejta I've created a bunch of jobs marked as optional and skipped in this repo. We thought using "/test all" would cause these jobs to run and appear in the GitHub status report, but that doesn't seem to be the case. What's the magic to invoke skipped jobs?

Thanks.

**Comment by howardjohn** [comment]
skipped meaning always_run=false by the way

**Comment by fejta** [comment]
There's `/skip` and `status-reconciler` to handle jobs no longer being required.

There is `/override` to force a context to passing.

**Comment by fejta** [comment]
If the job is `always_run=false` (and doesn't have a run_if_changed, etc) then you'll need to explicitly `/test foo` in order to trigger it.

**Pull request closed without merging**
