### PR TITLE
Remove istioctl.exe as its not being created

### PR DESCRIPTION
**Pull request by sebastienvas**

### CODE REVIEW

**Comment by sebastienvas** [comment]
@rvkubiak this might help you.

**Comment by ldemailly** [comment]
are we dropping support for windows ? (/why)

**Comment by sebastienvas** [comment]
Pilot is not creating it anymore.
https://github.com/istio/pilot/blob/master/bin/upload-istioctl#L45

**Comment by ldemailly** [comment]
@kyessenov how come the windows creation is commented out ?

**Comment by sebastienvas** [comment]
Closing this. It seems that Windows was disable to speed up presubmit.

**Comment by my3sons** [comment]
so is there not a windows compatible version of istioctl?  I am trying to run istio with minikube on my windows 10, and I have everything running fine, except that I find any way of running the current istioctl binary to actually deploy sidecars with my pods.

**Comment by ldemailly** [comment]
there is:

https://github.com/istio/istio/releases/download/0.2.7/istio_0.2.7_win.zip

is that not working for you? if so please file a new istio/issues/issues/new

**Comment by my3sons** [comment]
Thanks Laurent!  looked for something like that, just couldn't find it, should be good now :-)

**Pull request closed without merging**
