### PR TITLE
using k8s rand string and cleanup unused utils

### PR DESCRIPTION
**Pull request by Chen-Xintong**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Can you describe the benefit of this? As is I prefer things the way they are.

**Comment by Chen-Xintong** [comment]
> Can you describe the benefit of this? As is I prefer things the way they are.

I would like to unify the random string method in Istio, since I found that some parts of the code have adopted the standard library of k8s, so we don't have to recreate the function with the same functionality to simplifying the code.

**Review by douglas-reid — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
