### PR TITLE
add liveness probe for citadel.

### PR DESCRIPTION
**Pull request by morvencao**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
LGTM, but I will leaves to security owners @incfly

**Comment by linsun** [comment]
/lgtm

@incfly or @wattli can someone from security WG review?

**Comment by stuart-warren** [comment]
we need this, noticed an issue this morning that was resolved by manually restarting citadel.

we had cluster issues and citadel never came back on its own

**Comment by morvencao** [comment]
@duderino Please consider merging this into release 1.1.x

**Comment by duderino** [comment]
Thank you @morvencao.  This will be in 1.1.3 which should release on 4/15

**Comment by stuart-warren** [comment]
@duderino @morvencao should this change be made to master branch too? only in release-1.1

**Comment by morvencao** [comment]
@stuart-warren see:https://github.com/istio/istio/pull/13547

**Pull request merged**
