### PR TITLE
Delete OWNERS files since we're now using CODEOWNERS.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by howardjohn** [comment]
good luck getting owners approval from everyone...

**Comment by howardjohn** [comment]
Seems github doesn't specify which folders still need owners approval, that is annoying

**Comment by yangminzhu** [comment]
Not related to this PR, I'm just wondering is the [CODEOWNERS](https://github.com/istio/istio/blob/123b96c4daf4db42c9fe28f1ff0ea6ff104a72a6/CODEOWNERS#L36-L35) auto-generated? I feel it could look much better if we just don't repeat the names in every line.

**Comment by geeknoid** [comment]
@yangminzhu I manually produced the file. In the future, the file should get much simpler as we switch to using GitHub  teams rather than individuals in there.

As for repeating things, it's necessary. If you are on the foo/ line, it doesn't mean you can approve changes in foo/bar/. Your name has to be both on foo/ and foo/bar.

**Comment by geeknoid** [comment]
Not waiting for a million useless reviews, force-merging...

**Pull request merged**
