### PR TITLE
Update Pilot config descriptor lists

### PR DESCRIPTION
**Pull request by ijsnellf**
Use model.IstioConfigTypes instead of hardcoded lists.

### CODE REVIEW

**Comment by ayj** [comment]
This (re)enables`IngressRule` and `DestinationRule` as CRD types. `IstioConfigTypes` should be updated if that isn't desirable.

**Comment by ijsnellf** [comment]
Good point. Let me fix the PR.

**Comment by andraxylia** [comment]
e2e-smoke fails because of #3320

**Comment by andraxylia** [comment]
pilot-e2e fails like in all PRs when auth is enabled, unrelated to this change.

**Pull request merged**
