### PR TITLE
Improve cluster builder dual stack unit testing

### PR DESCRIPTION
**Pull request by adams-shaun**
**Please provide a description of this PR:**

This is part of an ongoing attempt to improve unit test coverage around code paths affected by the features.EnableDualStack flag.  I'm hoping to improve test coverage in small, targeted PRs to prevent regressions in the future.

### CODE REVIEW

**Review by bleggett — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by kfaseela** [comment]
@adams-shaun : i think you have to rebase the PR

**Pull request merged**
