### PR TITLE
#11779 Race condition getting pod IP and sending listeners list

### PR DESCRIPTION
**Pull request by rvansa**
Issue reference: #11779

The race is still happening on release-1.1 branch in my deployment.

### CODE REVIEW

**Comment by rshriram** [comment]
@hzxuzhonghu thoughts?

**Comment by hzxuzhonghu** [comment]
This is indeed a issue.
How about moving the full-push logic here
https://github.com/istio/istio/blob/d2638c6c767ab977d2b8666b1e4892a1754bc9c5/pilot/pkg/proxy/envoy/v2/eds.go#L474-L477

**Comment by rvansa** [comment]
@hzxuzhonghu I can do that, but I'd either have to do a full push every time or add another parameter to `WorkloadUpdate`, and since that is an interface, it could be an API change. Is `XDSUpdater` considered a public API?

Btw., should I care about the test failures?

**Comment by hzxuzhonghu** [comment]
a full push 

```
 w, f := s.WorkloadsByID[id] 
 if !f { 
     // trigger full push 
   ...
```


> should I care about the test failures? 

maybe related

**Comment by rshriram** [comment]
XDSUpdater is internal API. dont worry about changing the interfaces inside pilot.

**Comment by rvansa** [comment]
I am sorry about neglecting this, but I don't have access to the lab where I could test out the changes right now.

I've forced the full update from `eds.go` though I am not sure if `s.WorkloadsByID[id] == nil` implies `pc.keys[ip] == nil`.

**Comment by hzxuzhonghu** [comment]
This can be closed , fixed by #13229

**Pull request closed without merging**
