### PR TITLE
Pilot [networking]: Add upstream idle_timeout to cluster definition

### PR DESCRIPTION
**Pull request by arianmotamedi**
This is cherry-picked from https://github.com/istio/istio/pull/13066.

### CODE REVIEW

**Comment by arianmotamedi** [comment]
@GregHanson @linsun fyi.

**Comment by arianmotamedi** [comment]
Darn, looks like the GolangCI ran out of memory: `fatal error: runtime: out of memory` 😞

**Comment by howardjohn** [comment]
> Darn, looks like the GolangCI ran out of memory: `fatal error: runtime: out of memory`

Its a known issue

**Comment by arianmotamedi** [comment]
@howardjohn can this be merged without golangci passing? this is the same exact change as https://github.com/istio/istio/pull/13066. golangci passed on that one a few days ago 😁

**Comment by arianmotamedi** [comment]
@linsun can this be merged?

**Comment by arianmotamedi** [comment]
Is anyone able to merge this @howardjohn @rshriram @GregHanson @linsun ?

**Pull request merged**
