### PR TITLE
Allow setting priorityClassName in Istio gateway helm chart

### LINKED ISSUE #47459: [release-1.19] Allow setting priorityClassName in Istio gateway helm chart
Manual cherrypick required.

#47152 failed to apply on top of branch "release-1.19":
```
Applying: Allow setting priorityClassName in Istio gateway helm chart
Using index info to reconstruct a base tree...
M	manifests/charts/gateway/templates/deployment.yaml
M	manifests/charts/gateway/values.schema.json
M	manifests/charts/gateway/values.yaml
Falling back to patching base and 3-way merge...
Auto-merging manifests/charts/gateway/values.yaml
CONFLICT (content): Merge conflict in manifests/charts/gateway/values.yaml
Auto-merging manifests/charts/gateway/values.schema.json
CONFLICT (content): Merge conflict in manifests/charts/gateway/values.schema.json
Auto-merging manifests/charts/gateway/templates/deployment.yaml
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Allow setting priorityClassName in Istio gateway helm chart
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by kolorful**
Allow setting priorityClassName in Istio gateway helm chart. 

Cherry-picked #47152

Fixes #47459

### CODE REVIEW

**Comment by linsun** [comment]
@ksubrmnn okay with you for approving this?

**Comment by linsun** [comment]
Adding release note none label as the master PR has it

**Comment by dhawton** [comment]
> Adding release note none label as the master PR has it

If master has it, this one needs it as well otherwise it won't populate the changelog on the next 1.19 release

**Comment by linsun** [comment]
> > Adding release note none label as the master PR has it
> 
> If master has it, this one needs it as well otherwise it won't populate the changelog on the next 1.19 release

I mean master has the release note none label.

**Review by ksubrmnn — APPROVED** [review]

**Pull request merged**
