### PR TITLE
wip: create in-cluster mcpc agent for diagnostic and load testing

### PR DESCRIPTION
**Pull request by ayj**
TODO:

- add README.md
- use spf13/cobra for command line and flag management.
- Refactor main.go into more manageable pieces
- Add simulated NACK percentage rate
- Add re-connection frequency parameter
- Add scale parameter for additional connections (alt: simply scale the number of replicas)

### CODE REVIEW

**Comment by ayj** [comment]
cc @mandarjog, thoughts on putting this mcpc debug agent here or under https://github.com/istio/tools/tree/master/perf?

cc @ozevren @nmittler - any other options we may want to add for load testing Galley re: endpoints or other config churn?

**Comment by mandarjog** [comment]
The code in istio/istio and helm charts in tools

**Comment by ozevren** [comment]
frequent disconnect/reconnect?

**Comment by ozevren** [comment]
Would be nice to get this in soon, as stale bot seems pretty insistent on closing this one (even with the no stale bot label!).

**Comment by duderino** [comment]
@ayj @ozevren if this is still needed please send it to master

**Pull request closed without merging**
