### PR TITLE
Galley: introduce custom fake for kubernetes.Interface

### PR DESCRIPTION
**Pull request by nmittler**
Benchmarks have shown the provided kubernetes fake to create a lot of garbage and it also causes spurious panics due to filling the watch channels.

This is an incomplete implementation of the interface that resolves these issues for the galley tests.

### CODE REVIEW

**Comment by ozevren** [comment]
I assume this is just a mechanical repoint of the same PR?

**Comment by nmittler** [comment]
@ozevren 

> I assume this is just a mechanical repoint of the same PR?

Yes, that's right ... this is targeting master.

**Comment by nmittler** [comment]
@rshriram @geeknoid could one of you approve?

**Pull request merged**
