### PR TITLE
Revision based deployments for ingressgateways

### PR DESCRIPTION
**Pull request by elfinhe**
### First revision installation
```
$istioct install -y --set revision=rev1
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
```
Pods, Deployments, and Services
```
NAME                                   READY   STATUS    RESTARTS   AGE     REV
istio-ingressgateway-c9d467ff6-65w2f   1/1     Running   0          29s     rev01
istio-ingressgateway-c9d467ff6-mvn86   1/1     Running   0          38s     rev01
istiod-rev01-65f8757d5c-6nsbq          1/1     Running   0          6m12s   rev01
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE
istio-ingressgateway   2/2     2            2           39s
istiod-rev01           1/1     1            1           6m13s
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                                                      AGE     REV
istio-ingressgateway   LoadBalancer   10.24.15.234   35.192.6.114   15021:32050/TCP,80:30247/TCP,443:32306/TCP,15012:32459/TCP,15443:31408/TCP   6m9s    rev01
istiod-rev01           ClusterIP      10.24.10.231   <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP                                        6m12s   rev01
```

### Second revision installation
when user wants a new ingressgateway deployment without overwriting the existing one to have more control of moving the traffic pod by pod)
```
$istioct install -y --set revision=rev2  --set values.gateways.istio-ingressgateway.deploymentRevision=rev0b
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
```

Pods, Deployments, and Services
```
NAME                                          READY   STATUS    RESTARTS   AGE     REV
istio-ingressgateway-c9d467ff6-65w2f          1/1     Running   0          9m3s    rev01
istio-ingressgateway-c9d467ff6-mvn86          1/1     Running   0          9m12s   rev01
istio-ingressgateway-rev0b-85db56b954-nddc5   1/1     Running   0          28s     rev02
istiod-rev01-65f8757d5c-6nsbq                 1/1     Running   0          14m     rev01
istiod-rev02-699b49b5c5-dbzkf                 1/1     Running   0          32s     rev02
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
istio-ingressgateway         2/2     2            2           9m13s
istio-ingressgateway-rev0b   1/1     1            1           29s
istiod-rev01                 1/1     1            1           14m
istiod-rev02                 1/1     1            1           33s
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                                                      AGE   REV
istio-ingressgateway   LoadBalancer   10.24.15.234   35.192.6.114   15021:32588/TCP,80:30264/TCP,443:31846/TCP,15012:31497/TCP,15443:31321/TCP   14m   rev02
istiod-rev01           ClusterIP      10.24.10.231   <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP                                        14m   rev01
istiod-rev02           ClusterIP      10.24.9.37     <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP                                        33s   rev02
```

### [Optional] Reduce the pod# of ingressgateway rev01
So users can move the percentage of traffic from rev01 to rev02, pod by pod:
```
$kubectl -n istio-system scale --replicas=1 deploy istio-ingressgateway
deployment.apps/istio-ingressgateway scaled

$kubectl -n istio-system scale --replicas=0 deploy istio-ingressgateway
deployment.apps/istio-ingressgateway scaled
```

### [Optional] Update istio-ingressgateway service to only use the rev02 ingress gateway
This is optional depending on how graceful connection shutdown and liveness probe is implemented on ingressgateways. From what I heard and tested, graceful shutdown is already implemented starting from Istio 1.8. And patching service is a quite risky operation, also not declarative to do gitops. Just list the option here, users still have the control on selecting the pods behind the service. 

```
$kubectl patch service -n istio-system istio-ingressgateway --type='json' -p='[{"op": "add", "path": "/spec/selector/service.istio.io~1canonical-revision", "value": "rev02"}]'
service/istio-ingressgateway patched
```

### Update all dataplanes to use rev02
Similar to the steps in https://istio.io/latest/docs/setup/upgrade/gateways/#upgrade-with-istioctl
- Label workload namespaces with istio.io/rev=rev02.
- Restart the workloads
- Verify that the workloads are injected with the new proxy version and the cluster is functional.

### Remove rev01 installation
This will also remove the ingressgateway deployment in rev01
```
$istioctl x uninstall -y --set revision=rev1
There are still 1 proxies pointing to the control plane revision rev01
istio-ingressgateway-c9d467ff6-mvn86.istio-system
If you proceed with the uninstall, these proxies will become detached from any control plane and will not function correctly.
You are about to remove the following gateways: istio-ingressgateway. To avoid downtime, please quit this command and reinstall the gateway(s) with a revision that is not being removed from the cluster.
Proceed? (y/N) y
  Removed HorizontalPodAutoscaler:istio-system:istiod-rev01.
  Removed PodDisruptionBudget:istio-system:istiod-rev01.
  Removed Deployment:istio-system:istio-ingressgateway.
  Removed Deployment:istio-system:istiod-rev01.
  Removed Service:istio-system:istiod-rev01.
  Removed ConfigMap:istio-system:istio-rev01.
  Removed ConfigMap:istio-system:istio-sidecar-injector-rev01.
  Removed EnvoyFilter:istio-system:metadata-exchange-1.8-rev01.
  Removed EnvoyFilter:istio-system:metadata-exchange-1.9-rev01.
  Removed EnvoyFilter:istio-system:stats-filter-1.8-rev01.
  Removed EnvoyFilter:istio-system:stats-filter-1.9-rev01.
  Removed EnvoyFilter:istio-system:tcp-metadata-exchange-1.8-rev01.
  Removed EnvoyFilter:istio-system:tcp-metadata-exchange-1.9-rev01.
  Removed EnvoyFilter:istio-system:tcp-stats-filter-1.8-rev01.
  Removed EnvoyFilter:istio-system:tcp-stats-filter-1.9-rev01.
  Removed MutatingWebhookConfiguration::istio-sidecar-injector-rev01.
✔ Uninstall complete

```

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
What problem are we trying to solve?

**Comment by elfinhe** [comment]
> What problem are we trying to solve?
Problem: ingress gateways are always upgraded in-place. Users have no control of moving the traffic between revisions gradually, and are not able to easily rollback to the previous revision.

Similar to: https://docs.google.com/document/d/1_LAo8k6wmjbiv-o18qPUTaitLo_fpA9M8PCB95Zrth0/edit#

**Comment by howardjohn** [comment]
IMO, this is already possible by creating a custom gateway, or for simpler use cases https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit?ts=5fa915aa# will also help. Maybe we need this too, but its not immediately obvious to me that its the right approach.

For example, as a user, how do I know if I should make a new `foo` revision or just a new gateway named `foo`?

**Comment by elfinhe** [comment]
> IMO, this is already possible by creating a custom gateway, or for simpler use cases https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit?ts=5fa915aa# will also help. Maybe we need this too, but its not immediately obvious to me that its the right approach.
> 
> For example, as a user, how do I know if I should make a new `foo` revision or just a new gateway named `foo`?

Custom gateway will create a customer service, which will be bound to a new external IP, load balancer. Users need to hack more to get it selected by the original gateway service.

Agreed that injector V2 will help a lot, but it will take much longer time to implemented.

**Comment by howardjohn** [comment]
> Custom gateway will create a customer service, which will be bound to a
new external IP, load balancer. Users need to hack more to get it selected
by the original gateway service.


I think they can control the selector/labels today right? I would imagine
its fairly similar complexity as this new flag, people will probably be
copy+pasting from whatever doc we have anyhow

> Agreed that injector V2 will help a lot, but it will take much longer
time to implemented.

This should be done in 1.9. Although it will probably not be default

**Pull request closed without merging**
