### PR TITLE
Enable rewriteAppHTTPProbe by default for better UX

### PR DESCRIPTION
**Pull request by johnma14**
Manual cherry-pick of https://github.com/istio/istio/pull/17941

Fixes: #10357

### CODE REVIEW

**Comment by howardjohn** [comment]
This seems like we are adding a feature in a patch release. Is there any strong reason we need this in 1.5.1 and not 1.6?

**Comment by fpesce** [comment]
Looks like this PR needs a make gen

**Comment by johnma14** [comment]
ran health checks to test the changes. Working on another PR so that it does not generate fields with empty values. Most of the generated files in here have - 
          name: ISTIO_KUBE_APP_PROBERS
          value: '{}'

**Comment by johnma14** [comment]
@howardjohn this PR is big only because of all the generated files. The actual change is just to 2 or 3 files which enables this annotation by default. The only thing that was blocking this from getting merged in 1.5 was the timeout issue related to this: https://github.com/istio/istio/pull/21755. That feature got merged in 1.5. This has been tested very well with the annotation enabled by default and the users will see no difference/issues in their 1.5.x install because of enabling this and it does not add any overhead fro the user. On the other hand, it will make things easier for them to do readiness and liveness checks since this is one less step they have to do otherwise.

**Comment by howardjohn** [comment]
I am not concerned about the size of the PR, but the potential impact on users. I understand its been well tested, but as a general rule we do not add new features in patch releases, because its a horrible UX to upgrade to a "patch" release and some new feature breaks your cluster. However, this is up to the release manager to decide if this is a reasonable feature to add in a patch release - which is why I said any of them can feel free to remove my hold

**Comment by linsun** [comment]
my 2 cents - this is not a large feature - something we wanted to enable since 1.3.  Enabling this won't cause user issue but not having this will break user's microservices at the very moment when they enable mTLS for the microservices if there are healthcheck enabled for these microservices which are common practice.  These services will stop running because health check will fail as soon as mtls is enabled.

**Comment by johnma14** [comment]
Upgrading a cluster to the 1.5.x with this annotation enabled by default should not cause any issues or break the cluster since all it is doing rewriting the pod spec to use the 15020 port  for health checks  to work under mutual TLS. This is the port assigned for health checks and I do not see how this could break the cluster during the upgrade process.

**Comment by howardjohn** [comment]
> I do not see how this could break the cluster during the upgrade process.

I have seen this comment pretty commonly before a change breaks users :slightly_smiling_face: . Any change introduces risk. I am not saying the feature is broken, or that it does not work, or that it **will** break someones cluster, just that it **might** because we are introducing risky changes in a patch release. Its a great feature, I am just not sure it should be enabled in a patch release - but again, not my call to make

**Comment by fpesce** [comment]
Please, @johnma14 & @linsun, do not hesitate to run some additional testing in your clusters with the a build that follows this merge before we cut 1.5.2

**Comment by johnma14** [comment]
will do @fpesce.

**Pull request merged**
