### PR TITLE
move to 0.2.9 in download script

### PR DESCRIPTION
**Pull request by linsun**
Is this supposed to be covered by a script?

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
A user reported this on slack:

btw: it looks like `curl -L https://git.io/getLatestIstio | sh -` still gets you 0.2.7.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ayj** [comment]
This is noted in the deprecated manual instructions [here](https://github.com/istio/istio/blob/master/release/README.md#finalizing-the-release). Looks like that step isn't part of the semi-automated release. /cc @istio/test-infra-hackers

**Comment by yutongz** [comment]
This version is updated in release-0.2 branch in [this PR](https://github.com/istio/istio/pull/1185). It's covered in step 5 in `Semi-automated`. I guess the confusion is should we always put the latest release version in master or we should only update it in its own branch.

**Comment by ldemailly** [comment]
Oic so maybe we can make it option on the script whether or not to change master

Maybe it's time to change the stable one too (to 0.2.7?)

**Comment by yutongz** [comment]
Yeah, we can make it optional. It really depends on what we want customers to use. It's kind of making sense because, if it's a weekly scheduled release, we don't necessarily need to push it to customers. But that's another story if this release includes a patch for critical bugs

**Comment by linsun** [comment]
I agree there may be cases where we don't want to auto promote the latest build.  ideally, would be nice to have a flag to have that configured.

**Comment by chxchx** [comment]
@yutongz @ldemailly @sebastienvas 
This is really weird. The auto release tool does update the download script and the finalizing release PR by @ayj was merged
https://github.com/istio/istio/pull/1185/
But why is this file not changed? If you check the history of this download script https://github.com/istio/istio/commits/master/release/downloadIstioCandidate.sh, jason's commit is gone.

**Pull request merged**
