### PR TITLE
Fix typo in injector template trustDomain/meshId

### PR DESCRIPTION
**Pull request by howardjohn**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by pitlv2109** [comment]
@howardjohn Can we also cherry-pick this to 1.3? Also put a P0 to get this through quicker?

**Comment by rlenglet** [comment]
Does istio/installer need a corresponding PR + backport?

**Comment by howardjohn** [comment]
there is an open PR for this in installer

**Pull request merged**
