### PR TITLE
s/nodeaffinity/nodeAffinity in kubernetes helm charts

### PR DESCRIPTION
**Pull request by tariq1890**
This PR is for better naming.

### CODE REVIEW

**Comment by tariq1890** [comment]
@sdake Can you ok-to-test and approve this?

**Comment by tariq1890** [comment]
Is the failure related to my change?

**Comment by ostromart** [comment]
I appreciate the good intent behind this PR but consider that this breaks existing configs silently i.e. when users upgrade they lose their node affinity without any errors emitted from helm. 
For that reason, until we have a schema validation, we are stuck with having to be extremely conservative with these types of changes.

**Pull request closed without merging**
