### PR TITLE
Add @sdake to OWNERS file in tools dir

### PR DESCRIPTION
**Pull request by sdake**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
I hope your first move as an owner is to delete most of `tools` :slightly_smiling_face: . It is included in our release and should not be - we have completely deprecated stuff like performance testing stuff which is now in the tools repo, and nothing is documented. We also have a bunch of tools that maybe are useful/used by us like the license tool, but should not be in the release

**Comment by mandarjog** [comment]
@sdake  we need to get rid of most tool here, or move them to the tools repo.
Were you planning a major expansion here?

**Comment by sdake** [comment]
@mandarjog mainly I wish to be able to approve reviews in the .mk files as I've written or updated most of them after @nmittler wrote them originally.  Perhaps they are in the wrong place.

i don't intend any addition - and as @vadimeisenbergibm points out, could remove the junk here if people like :)

Cheers
-steve

**Pull request merged**
