### PR TITLE
Move StackDriver dependencies to its own repository

### PR DESCRIPTION
**Pull request by jwendell**
Closes: #13592.

### CODE REVIEW

**Comment by jwendell** [comment]
@kyessenov Following up the discussion on https://discuss.istio.io/t/go-mod-x-dependencies/2214/3

So, I moved that vendor code to a repo (temporarily at https://github.com/jwendell/stackdriver-deps). Should we create this repo on Istio org?

**Comment by kyessenov** [comment]
@geeknoid 

We need a home for stackdriver auto-generated dependencies. istio/gogo-genproto would be OK except it has gogo generated files, while stackdriver dependencies use the standard protobuf toolchain.

Can we move stackdriver-deps repo into istio? Other than that, this change looks fine to me.

**Comment by douglas-reid** [comment]
@kyessenov I'm not sure we want to have those live anywhere officially. If this isn't pressing, my proposal would be to leave them where they are for now and then just remove them entirely when they are no longer needed. @quentinmit thoughts here?

**Comment by jwendell** [comment]
The problem in leaving they where they are right now is that 'downstream' projects are unable to import `istio.io/istio` code due to those dependency problems.

**Pull request closed without merging**
