### PR TITLE
modify some wrong typos of kubernetes

### PR DESCRIPTION
**Pull request by gy95**
some typos of `kubernetes` is not correct, fix these wrong typos

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by gy95** [comment]
cannot merge, @hzxuzhonghu , what's the reason

**Comment by ramaraochavali** [comment]
@istio/wg-user-experience-maintainers can you PTAL?

**Comment by gy95** [comment]
ping @istio/wg-user-experience-maintainers , PTAL, could you please give me some advice why i cannot merge this pr?

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
