### PR TITLE
fix istio chart upgrade issues.

### PR DESCRIPTION
**Pull request by morvencao**
Move back the `post-install` hook due to upgrade issue: https://github.com/istio/istio/issues/12154

### CODE REVIEW

**Comment by linsun** [comment]
@ostromart I noticed our upgrade test didn't catch this issue... should we create an upgrade test for mtls enabled?

**Comment by linsun** [comment]
@diemtvu - can you pls review this?

I'm okay with the restore to keep the upgrade going, unless there is strong objection.

cc @ostromart @duderino

**Comment by linsun** [comment]
@morvencao can we create a update test for helm upgrade if you intend to support it?   similarly as how it is created in the release qualification today, e.g. upgrade_test.sh.

**Comment by morvencao** [comment]
@linsun Yep, I would do that.

**Comment by sdake** [comment]
note these are *hopefully* short term hacks.  With the introduction of the new installer, we will be using helm *only* as a templating system.  For those that want a one step experience, we _may_ offer a job based operator-like approach that organizes the helm templates around specific workflows like upgrade/rollbacks.

Cheers
-steve

**Comment by ostromart** [comment]
@linsun I've created https://github.com/istio/istio/issues/12229 to track adding test cases.

**Comment by sdake** [comment]
This more or less works (upgrade and rollback work) - but there is a different problem:
```
sdake@beast-01:~/go/src/istio.io/istio/install/kubernetes/helm$ kubectl get pods -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-74f4cd887f-swbgk            1/1     Running     0          85s
istio-galley-55cc48d879-kp5d5             1/1     Running     0          86s
istio-ingressgateway-6c786866bc-7xqnh     1/1     Running     0          86s
istio-init-crd-10-bd56p                   0/1     Completed   0          6m35s
istio-init-crd-11-cxbr9                   0/1     Completed   0          6m35s
istio-init-crd-certmanager-10-gtdv5       0/1     Completed   0          6m35s
istio-pilot-7c597c8f86-9lddc              2/2     Running     0          86s
istio-policy-547d64b8d7-bqfff             2/2     Running     0          8m44s
istio-policy-6c7b848b87-ntjkf             2/2     Running     0          86s
istio-sidecar-injector-55d468cffb-sfkbz   1/1     Running     0          85s
istio-telemetry-65947b547-jnxxl           2/2     Running     0          86s
istio-telemetry-c5488fc49-njz5l           2/2     Running     0          8m44s
prometheus-66c9f5694-vj24p                1/1     Running     0          85s
```
note two policy and telemetry pods - 1 is from 1.0.6, and 1 is from 1.1.0.  Lets merge this, and solve that problem.  This also might generally just need a rebase which would solve the problem (I seem to recall somoene fixed a similar problem).

Rollback:
```
sdake@beast-01:~/go/src/istio.io/istio/install/kubernetes/helm$ helm rollback istio 3
Rollback was a success! Happy Helming!
sdake@beast-01:~/go/src/istio.io/istio/install/kubernetes/helm$ kubectl get pods -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-6f444d9999-9r9zk            1/1     Running     0          113s
istio-egressgateway-6d79447874-jh2cl      1/1     Running     0          114s
istio-galley-685bb48846-ns2t6             1/1     Running     0          114s
istio-ingressgateway-5b64fffc9f-jdxqf     1/1     Running     0          114s
istio-init-crd-10-bd56p                   0/1     Completed   0          8m57s
istio-init-crd-11-cxbr9                   0/1     Completed   0          8m57s
istio-init-crd-certmanager-10-gtdv5       0/1     Completed   0          8m57s
istio-pilot-8645f5655b-rpsfb              2/2     Running     0          113s
istio-policy-547d64b8d7-bqfff             2/2     Running     0          11m
istio-sidecar-injector-5d8dd9448d-74srf   1/1     Running     0          113s
istio-telemetry-c5488fc49-njz5l           2/2     Running     1          11m
prometheus-76b7745b64-4xkch               1/1     Running     0          113s
```
cheers
-steve

**Comment by costinm** [comment]
So the root problem is that since in 1.0 we created with a job, we can't change it ? 
I guess another reason to move to the new installer ASAP. 

/lgtm ( not really looking good, it looks quite bad - but no other option until we get rid of helm )

**Comment by linsun** [comment]
@costinm yes AFAIK, very unfortunate.

/lgtm

@wenchenglu @duderino can we get this in 1.1 to fix upgrade issue?

**Comment by sdake** [comment]
@costinm yes, lesson learned painfully - in the future, we should use helm only as a templating system, **IF AT ALL**.

Cheers
-steve

**Pull request merged**
