### PR TITLE
Configure certificate TTL

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/21944.

Expose configuring SECRET_TTL as an installation option to allow operators to configure workload cert lifetime.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is already supported today, I don't think we need yet another option. See

```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        SECRET_TTL: 10m
```

**Comment by weibohe** [comment]
I don't see `proxyMetadata` in https://istio.io/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig ?

**Comment by myidpt** [comment]
@weibohe I don't see `proxyMetadata` in the reference. Maybe we need to update it. But it can be set:
`istioctl manifest apply --set values.global.tag=$TAG --set meshConfig.defaultConfig.proxyMetadata.SECRET_TTL=10`
This sets the TTL on the client side.

**Comment by lei-tang** [comment]
Based on the review comments, this PR is closed for now.

**Pull request closed without merging**
