### PR TITLE
Add operator/installer artifacts to release tar

### PR DESCRIPTION
**Pull request by ostromart**

### CODE REVIEW

**Comment by ostromart** [comment]
Changed it per your suggestion. What values can CB_BRANCH take?

**Comment by howardjohn** [comment]
Appears I am not an owner

@linsun @duderino can you take a look?

**Comment by duderino** [comment]
Hello operator!

**Comment by howardjohn** [comment]
Is it possible to fix the nesting before we merge to release-1.3?

**Pull request merged**
