### PR TITLE
Pilot [networking]: Add upstream idle_timeout to cluster definition

### PR DESCRIPTION
**Pull request by arianmotamedi**
Per https://github.com/istio/istio/issues/9113, implementing support for upstream idle_timeout in cluster generation. PR for changes to the API (DestinationRule): https://github.com/istio/api/pull/891

This allows `DestinationRule.ConnectionPoolSettings.HTTPSettings.IdleTimeout` to map directly to
`core.HttpProtocolOptions.idle_timeout` in the [cluster definition of Envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-httpprotocoloptions).

### CODE REVIEW

**Comment by arianmotamedi** [comment]
@utka any idea why `ci/circleci: lint` failed? I only see

> Makefile:272: recipe for target 'depend.diff' failed
> make: *** [depend.diff] Error 1

in the logs, but doesn't say why.

**Comment by GregHanson** [comment]
@arianmotamedi I take it you made the change in vendor manually since https://github.com/istio/api/pull/891 is still open?  That is probably why the linter is complaining.  It's kind of a chicken/egg situation.  Your PR in istio/api must merge first, then you should run `dep ensure --update "istio.io/api"` for this PR in order to update the vendored version of the repo.

What you have now is great, because you added additional tests for the feature and also demonstrated it's a non breaking change to existing e2e tests/features.  So this should expedite the merge of your api PR.  But you will have to revert the vendor changes you have currently and run the dep command I provided above once the api PR merges

**Comment by arianmotamedi** [comment]
@GregHanson yep, I ended up adding a constraint to my gopkg.toml to pull istio.io/api from my fork repo which had the proto schema changes to dev and test Pilot locally. I checked in those vendor files but removed the constraint in gopkg.toml. I didn't think about the race condition. I think once the api PR is merged we should be able to run the ci job again and `dep ensure` should pull everything from the right repo.

**Comment by arianmotamedi** [comment]
Alright looks like API changes got merged. @GregHanson how would I trigger the circleci job again?

**Comment by GregHanson** [comment]
@arianmotamedi only those in the Istio Github Org can re-run the circleci tests.  The lint test is still failing with the same error.  Just looking at the diff of Gopkg.lock, I can see that the istio.io/api digest has not been updated to a more recent commit which I suspect is the underlying problem

**Comment by arianmotamedi** [comment]
Done. Reverted vendor changes and reran dep ensure against istio.io/api:master. Let's see if it's any better 🤞

**Comment by arianmotamedi** [comment]
Looks like all required checks passed. @utka @GregHanson does this look good?

**Comment by linsun** [comment]
don't forget doc PR for this as this will allow user's to configure the idle_timeout.

**Comment by arianmotamedi** [comment]
@linsun doc pr has been merged for preliminary.istio.io: https://github.com/istio/istio.io/pull/3954. If this is going to make it in 1.1, I'll open up another pr to merge it there.

**Comment by GregHanson** [comment]
@arianmotamedi since this could improve 503 resiliency, I would recommend cherry-picking it into release-1.1 branch.  You will have to do the same thing in istio/api as well

**Comment by arianmotamedi** [comment]
@GregHanson https://github.com/istio/api/pull/896 for the api. Once this is merged I'll open up a PR for pilot changes.

**Pull request merged**
