### PR TITLE
Restore Set.InsertAll

### PR DESCRIPTION
**Pull request by nmittler**
This was removed by https://github.com/istio/istio/pull/38140, but should not have been. The Insert/InsertAll separation avoids a needless array allocation for the vast majority of Insert calls.

**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
I think this is a good compromise between the two. I put a hold in case @hzxuzhonghu has concerns?

**Comment by hzxuzhonghu** [comment]
OK. let's have a benchmark test to see the difference.

**Comment by hzxuzhonghu** [comment]
```
goos: linux
goarch: amd64
pkg: istio.io/istio/pkg/util/sets
cpu: Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz
BenchmarkSet_Insert-8      	48236504	        34.43 ns/op
BenchmarkSet_InsertOne-8   	47176616	        30.24 ns/op
PASS
ok  	istio.io/istio/pkg/util/sets	3.156s

```

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM with 10% improve

**Pull request merged**
