### PR TITLE
consolidate scripts in bin directory in istio components

### LINKED ISSUE #1844: Remove any redundant stuff from */bin
Can you go through all the content in mixer/bin, pilot/bin, security/bin, and broker/bin and delete anything redundant relative to what is now in the top-level directory? Anything left in those directories problably should be moved to the top-level bin directory.

Thanks.

### PR DESCRIPTION
**Pull request by jmuk**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1844

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by rshriram** [comment]
And please fix circleci broker test.

**Comment by geeknoid** [comment]
I rather have a single "bin" directory which contains everything that can be run, whether an actual binary or a script. It doesn't matter to the user of this thing, except for having the thing in their path.

**Comment by jmuk** [comment]
the broker failure looks like circleci's flake. rerun seems to fix the issue.

I don't have strong opinion on the name of directories, but it's been `bin/` for each of those projects, I don't see strong reasons to be renamed now.

**Comment by jmuk** [comment]
Thank you for merging, but please don't merge changes like this manually. Some other things are merged meanwhile, which makes the presubmit fail. See https://github.com/istio/istio/pull/1890

**Comment by rshriram** [comment]
Shouldn't those changes respect the style/lint etc. ?

**Pull request merged**
