### PR TITLE
Configure sidecar-injector webhook to fail close

### PR DESCRIPTION
**Pull request by ayj**
Configure the sidecar-injector webhook failurePolicy to fail
close. Without this change, sidecar proxies may not be injected if the
webhooks is rescheduled due to node upgrades, pre-emptible instances,
etc.

fixes https://github.com/istio/istio/issues/3716

### CODE REVIEW

**Comment by alexkoturanov** [comment]
I think there might be and issue with this approach, consider the following scenario:
* *istio-sidecar-injector* pod is not available (being re-scheduled or simply scaled down to 0)
* an application pod is rescheduled (i.e. deleted manually)

In this scenario a new application pod is not created until *istio-sidecar-injector* is available. What if it is not available due to misconfiguration or other reason?

I think injection into deployment object would more consistent.

**Comment by ayj** [comment]
> What if it is not available due to misconfiguration or other reason?

A similar problem exists if someone accidentally scale down Pilot replicas to zero. Any newly created pod with a sidecar would not receive any traffic and routing would be broken. The injection webhook should be configured to be HA in such scenarios to avoid the problem your described. Fortunately the webhook is fairly lightweight (~1.5us per injected pod), stateless, and is easily horizontally scalable, i.e. k8s api-server will load balance injection requests across all webhook pod instances.

> I think injection into deployment object would more consistent.

Injecting into the controller level resource (e.g. deployment) doesn't work well for custom controllers that create pods.

**Comment by ldemailly** [comment]
I think this should be configurable, for people not using auth; fail open may be better in case the injector goes haywire ?

**Comment by ayj** [comment]
> I think this should be configurable, for people not using auth; fail open may be better in case the injector goes haywire ?

It is already configurable unless I'm missing the point? The provided mutating webhook registration yaml [here](https://github.com/istio/istio/blob/b831fad7ac13c40b3949b9475e797f03382c8ce7/install/kubernetes/templates/istio-sidecar-injector.yaml.tmpl#L90) is a one line yaml file change to switch between fail open/close. Were you suggesting adding another configuration layer on top of the k8s yamls?

Also, it's almost seems more desirabled to fail closed consistently in this regard. Failing open and then getting random reports of dropped policy checks and and reports because a sidecar is missing sounds like a pain to track down.

**Comment by ayj** [comment]
@costinm, @ldemailly - any other concerns with this PR? Regardless of where injection occurs, we probably ought to provide consistent and reliable injection method that doesn't randomly fail when nodes are upgraded or pods rescheduled. User's can easily "undo" this change by adjusting the configuration yaml (i.e. no code / build changes required).

**Comment by ldemailly** [comment]
I don't see it in your [link](https://github.com/istio/istio/blob/b831fad7ac13c40b3949b9475e797f03382c8ce7/install/kubernetes/templates/istio-sidecar-injector.yaml.tmpl#L90) (the open/close switch) but I trust you

re the issue of rescheduled/upgraded: do webhooks also have a number of copies like pod deployment ? I expect you'd need 3 copies to be able to sustain rolling upgrades etc without downtime, like for pods ?

**Comment by ayj** [comment]
> I don't see it in your link (the open/close switch) but I trust you

I linked to the current registration which relies on the default policy (fail open). his PR configure it to "fail close" (see [here](https://github.com/ayj/istio/blob/3037845012dccb1bfd0e0676564fd1010e90e6a4/install/kubernetes/templates/istio-sidecar-injector.yaml.tmpl#L90-L110)). In the end, most automatic injection configuration would occur in the sidecar template (via configmap) or by tweaking the registration yaml (see below).


```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: {ISTIO_NAMESPACE}
        path: "/inject"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
```

**Comment by ayj** [comment]
> do webhooks also have a number of copies like pod deployment?

Webhooks are implemented as a deployment accessed by kubernetes via k8s service. So, yes, it is capable of being horizontally scaled like most other Istio components. The default is 1 replica for demo / bookinfo. HA configuration should probably be addressed as part of over all Istio HA install setup.

**Comment by ldemailly** [comment]
I guess can you mark 3 copies right away,
the difference between the injector and the other istio component going down is that when say pilot or mixer go down you get a temporary disruption of service while it's down; while when the injector is down you get "permanent" damage (non injected deployments unable to talk to the mesh until deleted/redeployed, if I understand correctly) so it's worth just putting 3 replicas right away ?
(which we should do for mixer too...but again less critical)

**Comment by ayj** [comment]
> while when the injector is down you get "permanent" damage

That was only true if fail-open webhook. With fail-close, the deployment/replicaset control loop will continue to retry pod creation until desired==actual number of pods.

**Pull request merged**
