### PR TITLE
support common name in certs generated by cidatel

### PR DESCRIPTION
**Pull request by quanjielin**
check in https://github.com/istio/istio/pull/7155 (commit https://github.com/istio/istio/pull/7155/commits/301e1c181a5f55d535566acd776f5cbe6e2fb665) into master 

Context: https://github.com/istio/istio/issues/7153

### CODE REVIEW

**Comment by justinburke** [comment]
Hi Quanjie, based on current discussion in issue 7153, we don't want to support this PR as is.

**Comment by quanjielin** [comment]
@justinburke that's a long thread :)  personally I feel supporting common name is a useful use case(even gRPC requires CN); recently I generated certs using citadel and use the certs to setup gRPC/TLS, gRPC throw below error without CN.

/cc @costinm @wattli what do you think ?

```
[{"match":{"prefix":"/service/1"},"route":{"cluster":"local_service_tls"}}]}],"name":"local_route"},"stat_prefix":"ingress_http","codec_type":"auto"}
E0720 23:50:50.471758021       8 ssl_transport_security.cc:251] Could not get common name of subject from certificate.
[2018-07-20 23:50:50.472][8][trace][grpc] external/envoy/source/common/grpc/google_async_client_impl.cc:46] completionThrea
```

**Comment by justinburke** [comment]
Right, we don't expect SPIFFE certificates to be useful out of the box with gRPC. It does currently require custom processing code. (Soon gRPC will support SPIFFE without custom code, but that's not the case yet.)

But I think the appropriate place to flush out our concerns about this PR would be in issue 7153. A number of objections have been raised by me as well as another SPIFFE maintainer there. If we're going to proceed with this PR over objections, it would be helpful to have responses to those objections documented in issue 7153.

**Comment by myidpt** [comment]
/hold

Please put this PR on hold until we have a clear solution.

**Comment by wattli** [comment]
Agree with Justin/Oliver, this is out of scope of Citadel to support common name because we don't need it in our service-to-service mTLS. 

Common name is a legacy field which should be deprecated, unfortunately not everyone update their code. But I am okay to add this feature in security/tools/generate_certs, does that make sense?

**Comment by quanjielin** [comment]
only change in generate_certs lgtm, @justinburke @myidpt  ?

**Comment by justinburke** [comment]
A quick code search doesn't reveal how `generate_cert` is used. How and when is that utility used?

I don't think that this feature should be added into Istio certificates by default. If you want to make it optional (ie. CN added to certs when a specific flag to `generate_cert` is used), that approach would be most reasonable and would provide a path for users to customize their certificates. I would suggest that documentation should be added to indicate that the functionality is "off spec" and "experimental", perhaps by including some indication in the name of the flag itself. (Ie. `--experimental-common-name`)

**Comment by myidpt** [comment]
@justinburke `generate_cert` is used in the file pkg/pki/ca/ca.go. Did we discuss this in the SPIFFE community meeting (sorry I couldn't attend since it's midnight here)?

**Comment by evan2645** [comment]
@myidpt SIG-Spec did not meet yesterday. I will add this topic as an agenda item for Thursday next week.

**Pull request closed without merging**
