### PR TITLE
ADS: cleanup

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
1. remove `RoutePercent`

1. remove `onConnect` param of `pushLds`

### CODE REVIEW

**Comment by venilnoronha** [comment]
Rebase with `master` to fix the lint error. See #8064 for more details.

**Comment by hzxuzhonghu** [comment]
rebased

**Comment by hzxuzhonghu** [comment]
rebased

**Comment by hzxuzhonghu** [comment]
re-add 
/lgtm

**Pull request merged**
