### PR TITLE
Add support for apple silicon

### PR DESCRIPTION
**Pull request by howardjohn**
For https://github.com/istio/istio/issues/29596

Next step is include it in the release

Manually built at
http://storage.googleapis.com/howardjohn/tmp/istioctl-osx-arm64. Please
test it, I don't have a mac.

### CODE REVIEW

**Comment by ericvn** [comment]
Do we want to rename the current to include amd-64 so it becomes osx-{architecture} like we do for the linux flavors?

**Comment by howardjohn** [comment]
> Do we want to rename the current to include amd-64 so it becomes osx-{architecture} like we do for the linux flavors?

Yes and no. I do because its consistent. I don't because it is a breaking change.

**Comment by cagataygurturk** [comment]
```
$ file /Users/cguertuerk/Downloads/istioctl-osx-arm64
/Users/cguertuerk/Downloads/istioctl-osx-arm64: Mach-O 64-bit executable arm64
$ /Users/cguertuerk/Downloads/istioctl-osx-arm64 version
client version: 1.10-dev
control plane version: 1.8.0
data plane version: 1.8.0 (6 proxies)
$ /Users/cguertuerk/Downloads/istioctl-osx-arm64 proxy-status
NAME                                                   CDS        LDS        EDS        RDS        ISTIOD                     VERSION
istio-ingressgateway-745bc594df-llldd.istio-system     SYNCED     SYNCED     SYNCED     SYNCED     istiod-dcf67cc87-n4rn6     1.8.0
```

❤️ 

@howardjohn Works like a charm ;)

**Review by ericvn — APPROVED** [review]

**Pull request merged**
