### PR TITLE
Fix e2e_pilot test when sidecar injection is enabled.

### PR DESCRIPTION
**Pull request by yusuoh**

### CODE REVIEW

**Comment by cmluciano** [comment]
@yusuoh Is there a make flag that I can use to test this locally?

**Comment by yusuoh** [comment]
@cmluciano Yes. You can run cmd like this:

KUBECONFIG=~/.kube/config make e2e_pilot TESTOPS="--use_sidecar_injection=true"

**Comment by cmluciano** [comment]
Thanks, testing now

**Comment by cmluciano** [comment]
This works locally @yusuoh 

@sebastienvas Can you please approve this when you get the chance? I believe this is blocking the submit queue

**Pull request merged**
