### PR TITLE
[tf] load templates outside of init func

### PR DESCRIPTION
**Pull request by akshayjnambiar**
This makes sure that the flags are parsed and the new values mentioned in the flags are used.

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by nmittler** [comment]
Out of curiosity, do you know why init wasn't being called?

**Comment by stevenctl** [comment]
The issue is that the `init` that loads the template is called before `flag.Parse`.

**Review by stevenctl — APPROVED** [review]
LGTM

**Review by nmittler — APPROVED** [review]

**Pull request merged**
