### PR TITLE
Remove go-bindata init call

### PR DESCRIPTION
**Pull request by ostromart**
This removes a call to go-bindata library which is suspected to cause https://github.com/istio/istio/issues/16660.

### CODE REVIEW

**Comment by rlenglet** [comment]
The `istio-pilot-e2e-envoyv2-v1alpha3-release-1.3` test will be fixed by https://github.com/istio/istio/pull/16682.

**Comment by ostromart** [comment]
Not sure why this is not merging, does it require a manual merge?

**Comment by rlenglet** [comment]
> Not sure why this is not merging, does it require a manual merge?

We had ~6 backport PRs unblocked by https://github.com/istio/istio/pull/16682.
They are all going through the merge queue: https://prow.istio.io/tide
No worries, this will get merged tonight.

**Pull request merged**
