### PR TITLE
fully use buf to generate go from proto

### PR DESCRIPTION
**Pull request by mmorel-35**
**Please provide a description of this PR:**

fully use buf to generate go from proto:
- move `buf.yaml` at the root
- declare `buf.build/googleapis/googleapis` and `buf.build/k8s/api` dependencies
- remove `common-proto/k8s.io`

### CODE REVIEW

**Comment by costinm** [comment]
> @ericvn WDYT of this?
> 
> This puts a dependency on buf.build servers at build time (like we depend on the golang module proxy)

Do we still support offline builds (disconnected from internet) / without buf.build ? ( I assume we can build without golang module proxy ).

At the very least the PR description should make this more clear and explain how to use without.

**Comment by costinm** [comment]
Offline usage: "I am on an airplane" or "isolated environment is required
for security reasons".

I assume the buf.build servers are only used in 'make generate' - so not a
problem.

In context of XZ, it is a good idea for PR descriptions to be more clear -
like "this PR will use an external service
to generate some code - reviewers must pay extra attention to PRs including
generated code, in case
buf servers are compromised and start generating backdoors". We
probably should reflect this
into some Istio docs -  I never paid attention to generated code, but now
even binary test blobs
need to be carefully considered...

**Comment by howardjohn** [comment]
fwiw - The codegen still runs locally, just the proto sources are pulled from buf instead of checked into git. They do also have remote codegen but this PR isn't introducing it

**Comment by costinm** [comment]
That's a bit better - but still something that should be in the PR
description.

I assume someone modifying the proto sources is less critical - at worse
they may remove security fields but the tests should catch that.

The difference between this and golang module proxy is that the
module proxy is untrusted - go still verifies the SHAs from go.sum.

Given Istio use as a security product - and our insane build and code
complexity - we need to start paying very close attention to this, and make
sure "add a test" or "improve build time" PRs don't 'accidentally' do other
things like change the security model of the build.

( I do like 'buf' a lot - happy to see this PR, wouldn't even mind codegen
- but I see very little security considerations in PR description and
reviews )

**Comment by costinm** [comment]
And for my understanding - by 'pull from buf instead of checked into git' -
do you mean we make http requests on each "make gen" to some server, or is
it a git repo that has all the protos in an organized structure ?

Protos-in-git allow using standard/well-known tools to see the difference
between versions, has some caching and mirroring for hermetic builds, etc -
it's not only security
that needs some good explanation.

**Comment by bleggett** [comment]
> That's a bit better - but still something that should be in the PR description. I assume someone modifying the proto sources is less critical - at worse they may remove security fields but the tests should catch that. The difference between this and golang module proxy is that the module proxy is untrusted - go still verifies the SHAs from go.sum. 

This effectively does the same thing as `go.sum` but with `buf.lock` - either way, any mutation of the protos changes the SHA and would require a `buf.lock` update - which would generate a Git commit on our end.

So the risks here are the same risks we have today around the potential for someone to start compromising Go code we're pulling - no better and no worse.

**Comment by bleggett** [comment]
> I assume the buf.build servers are only used in 'make generate' - so not a problem.
> https://buf.build/docs/bsr/faqs#use-modules-offline

I'm assuming this means we would be hitting buf servers at least once-per-CI-run? And if their servers were down our CI would start to fail? Unless we retain local state between runs which I don't think we do.

It also looks like there might be some caveats with the local cache, depending on whether you use plugins: https://github.com/bufbuild/buf/issues/2543

**Comment by costinm** [comment]
No, John mentioned earlier that it's not using the buf servers at all. If
that's correct, and we are getting some stuff from their git repos - I have
no other concerns.

Also I don't even mind even hitting buf servers - just want to make sure it
is well understood from (build) security and review perspective, in context
of recent events.

**Comment by ericvn** [comment]
My first thought reading this was that we will use a local cache, then their servers, and if not available, we can get from another source (although I'm still not sure of the last item). I think that should be easy to test. If that all works, then I think this is an acceptable idea. I wouldn't want to eliminate off-line builds. Last question is if we would want to create a local cache to use across CI jobs.

**Comment by costinm** [comment]
Well - we do need better PR descriptions... I don't know what it's using -
it's opaque code. My first thought was that it's going to
Jia Tan's server - but according to John it's all local based on some SHA
that someone knows what it does.

IMO - after binary test blobs, auto generated boilerplate is probably the
second least carefully reviewed thing, followed by build infra code.

**Comment by howardjohn** [comment]
While the security risk is probably low/acceptable, TBH I don't really see the benefits here. We are talking about adding a cache, security, availability... what benefits do we get? Seems like little to none

**Comment by costinm** [comment]
I agree - while we need to start paying more attention to those things, I
don't think this PR or using buf is a real problem - or we need
even more complexity. If a vendor needs air-gapped builds - and they find
it's not so air-gapped - we can fix it.

+1 on merging it, but I would still appreciate a more detailed description
and confirmation on where do we actually get
the generated protos, in case anyone else is curious.

**Comment by bleggett** [comment]
> While the security risk is probably low/acceptable, TBH I don't really see the benefits here. We are talking about adding a cache, security, availability... what benefits do we get? Seems like little to none

Only real benefit is it removes ~20k lines worth of vendored protos from our tree. If we have concerns about caching/availability for CI I am OK holding off on this until we have good answers.

**Comment by jacob-delgado** [comment]
Are we able to reproduce any build if we go down this route? I don't like having checked in protos, but as long as we can have something in the manifest as to which shas from protos we checked in that'd be great.

I use buf often in smaller projects and I enjoy using it compared to using protoc. So overall it's a +1 from me.

**Pull request closed without merging**
