### PR TITLE
Update vault api dependency to a version compatible with modules

### PR DESCRIPTION
**Pull request by jsternberg**
The vault repository was split into three different modules. Importing
the old version caused a few different problems.

1. It unnecessarily imported dependencies for the vault binary itself
   rather than just the portion necessary for the API.
2. If istio.io itself was imported into a project, the dependency would
   conflict with the newer vault api dependency because they had
   overlapping paths.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

### CODE REVIEW

**Comment by jsternberg** [comment]
Resolved the conflicts. It appears that vendor is no longer committed from what I can see.

I'll try to see if the change in the vault dependency would cause any kind of problem. I am not under the impression that it should, but I am not the most familiar with the vault client so I am unsure about whether it would cause an issue.

**Comment by jsternberg** [comment]
I tried to look over the code for the vault API differences between v0.10.0 and v1.0.4 and I didn't see anything I thought was a breaking change between the two. Some of the API structs seem to have added attributes and there's a backoff mechanism that was included for retries, but I didn't see anything that would cause the documentation to change. The client is still configured in the same way and the same environment variables are used.

**Comment by lei-tang** [comment]
@jsternberg Thank you for checking that! Can you also verify whether this PR will break the user guide on https://istio.io/docs/tasks/security/vault-ca/? And whether this PR will break the integration test on https://github.com/istio/istio/tree/master/tests/integration/security/sds_vault_flow?

**Comment by jsternberg** [comment]
I'll be updating this PR and getting the CLA signed some time during the next week. Sorry for the delay.

**Comment by howardjohn** [comment]
Thanks, feel free to mention me when you do, it's easy to loose track of
older PRs

**Pull request closed without merging**
