### PR TITLE
ci(deps): setup dependabot

### PR DESCRIPTION
**Pull request by mmorel-35**
**Please provide a description of this PR:**

Setup dependabot to update gomod and python dependencies when they are availables

### CODE REVIEW

**Comment by howardjohn** [comment]
@istio/wg-test-and-release-maintainers WDYT?

I have a general aversion to doing this, but I can't concretely place why. Maybe its NIH. At the very least, its clear we could implement a better version pretty trivially since dependabot will not run `make gen` afterwards which is required for a few dependencies (go-control-plane).

I have also found that most of the time we update deps we end up needing code changes, anyways. I worry this may mean we end up with extra churn OR we miss out on changes we *should* have made (e.g: if I upgrade dep, I check for new features and use them; if its automated I would not notice)

**Comment by ericvn** [comment]
/ok-to-test

Let's see if this falls a `go mod tidy`

**Comment by ericvn** [comment]
I tend to agree with @howardjohn on not integrating this. I recall in the past that this would open a PR for each dependency update, so we might have a few each month. I don't recall if a `go mod tidy` would be done on each.

Also, the go.mod changes in this PR seem to be moving some from the indirect side to the direct side. I'm not sure why that is. I know I run into that issue in other repos if I haven't clean'd them back to not including some other source.

**Comment by ericvn** [comment]
`go-mod-update`, recommended by John in another thread, points out other modules to update (beyond the security) and might be something to automate (may also need go mod tidy, but maybe not). I'm not sure if that's good either, since we seem to need code changes occasionally with these package updates.

**Comment by ericvn** [comment]
And the other issue I have is with the samples updates as we don't have anything today (that I know of) to verify that the samples build and then generate new samples with the updates and the follow-up yaml updates. You can see the README in the samples/bookinfo for that process.

**Comment by ericvn** [comment]
As a FYI, I did run a dependabot dry-run and here were the changes (I know some of these won't work if the PR as created):
```
+---------------------------------------------------------------------------+
|                    Changes to Dependabot Pull Requests                    |
+---------+-----------------------------------------------------------------+
| created | cloud.google.com/go/monitoring ( from 1.10.0 to 1.11.0 )        |
| created | github.com/hashicorp/golang-lru ( from 0.6.0 to 1.0.1 )         |
| created | github.com/prometheus/prometheus ( from 0.36.2 to 0.41.0 )      |
| created | cloud.google.com/go/compute ( from 1.14.0 to 1.15.1 )           |
| created | cloud.google.com/go/iam ( from 0.8.0 to 0.10.0 )                |
| created | cloud.google.com/go/longrunning ( from 0.3.0 to 0.4.0 )         |
| created | github.com/onsi/ginkgo/v2 ( from 2.6.1 to 2.7.0 )               |
| created | cloud.google.com/go ( from 0.107.0 to 0.108.0 )                 |
| created | github.com/BurntSushi/toml ( from 1.1.0 to 1.2.1 )              |
| created | github.com/VividCortex/ewma ( from 1.1.1 to 1.2.0 )             |
| created | github.com/alecthomas/participle ( from 0.4.1 to 0.7.1 )        |
| created | github.com/emicklei/go-restful/v3 ( from 3.9.0 to 3.10.1 )      |
| created | github.com/fvbommel/sortorder ( from 1.0.1 to 1.0.2 )           |
| created | github.com/go-errors/errors ( from 1.0.1 to 1.4.2 )             |
| created | github.com/goccy/go-json ( from 0.9.7 to 0.10.0 )               |
| created | github.com/google/btree ( from 1.0.1 to 1.1.2 )                 |
| created | github.com/google/gnostic ( from 0.5.7-v3refs to 0.6.9 )        |
| created | github.com/huandu/xstrings ( from 1.3.3 to 1.4.0 )              |
| created | github.com/inconshreveable/mousetrap ( from 1.0.1 to 1.1.0 )    |
| created | github.com/jonboulle/clockwork ( from 0.2.2 to 0.3.0 )          |
| created | github.com/klauspost/compress ( from 1.15.12 to 1.15.14 )       |
| created | github.com/lestrrat-go/blackmagic ( from 1.0.0 to 1.0.1 )       |
| created | github.com/lestrrat-go/iter ( from 1.0.1 to 1.0.2 )             |
| created | github.com/lestrrat-go/option ( from 1.0.0 to 1.0.1 )           |
| created | github.com/magiconair/properties ( from 1.8.6 to 1.8.7 )        |
| created | github.com/marten-seemann/qtls-go1-18 ( from 0.1.3 to 0.1.4 )   |
| created | github.com/marten-seemann/qtls-go1-19 ( from 0.1.1 to 0.1.2 )   |
| created | github.com/mattn/go-colorable ( from 0.1.12 to 0.1.13 )         |
| created | github.com/mattn/go-runewidth ( from 0.0.13 to 0.0.14 )         |
| created | github.com/mdlayher/netlink ( from 1.4.1 to 1.7.1 )             |
| created | github.com/mitchellh/go-wordwrap ( from 1.0.0 to 1.0.1 )        |
| created | github.com/pelletier/go-toml/v2 ( from 2.0.5 to 2.0.6 )         |
| created | github.com/prometheus/procfs ( from 0.8.0 to 0.9.0 )            |
| created | github.com/prometheus/statsd_exporter ( from 0.22.7 to 0.23.0 ) |
| created | github.com/rivo/uniseg ( from 0.2.0 to 0.4.3 )                  |
| created | github.com/shopspring/decimal ( from 1.2.0 to 1.3.1 )           |
| created | github.com/spf13/afero ( from 1.9.2 to 1.9.3 )                  |
| created | golang.org/x/crypto ( from 0.3.0 to 0.5.0 )                     |
| created | golang.org/x/tools ( from 0.4.0 to 0.5.0 )                      |
| created | sigs.k8s.io/kustomize/kyaml ( from 0.13.9 to 0.13.10 )          |
+---------+-----------------------------------------------------------------+
```

**Comment by ericvn** [comment]
I did create a PR that includes a majority of the dependabot specified changes. Note that there were 3 that I couldn't make as they would cause some issues like lint-go failures or other packages to be updated which breaks things.

I still think this is something we should do manually, at least currently, as each scan will create PRs for items that we currently don't have fixed (and at least I don't know that we can).

**Comment by ericvn** [comment]
A dependabot update that was recently opened: https://github.com/istio/istio/pull/42814

**Comment by howardjohn** [comment]
Thanks for the PR. Looks like there is consensus to not move forward with this.

**Pull request closed without merging**
