### PR TITLE
Implement Mixer RBAC adapter 

### LINKED ISSUE #1233: Istio Native RBAC
"batteries included" adapter that enforces Role Based Access Control (RBAC) for Istio-enabled services in the mesh.

[Design Doc](https://docs.google.com/document/d/1dKXUEOxrj4TWZKrW7fx_A-nrOdVD4tYolpjgT8DYBTY/edit)

Owner: https://github.com/liminw

### PR DESCRIPTION
**Pull request by liminw**
What this PR does / why we need it:
This change implements Mixer RBAC adapter. 

Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #1233

Special notes for your reviewer:

Release note:

### CODE REVIEW

**Comment by wora** [comment]
I recommend you submit the proto files first with sufficient documentation.
Currently service role doesn't have type or name, but role ref has type and
name. How can a role ref work if the role definition doesn't have a name?

For each field documentation, there should be at least one example showing
what is a valid value. We need to make sure everyone can understand how to
use it.

Please don't refer to any Google doc. When we submit the proto, the doc
should be converted to readme.md as official spec. The corresponding Google
doc should be deprecated soon.

**Comment by douglas-reid** [comment]
/hold

please adapt the pb.go generation and inventory integration to the new model (recently committed as part of the move away from bazel-based generation logic).

**Comment by geeknoid** [comment]
Hi,

So this code is embedding specific knowledge of the RBAC resources in Mixer. This is not what we want. If a specific adapter needs to reads CRDs of its own, the logic to read the CRDs must be contained in the adapter code itself. Otherwise, the general-purpose Mixer starts to have adapter-specific logic, which would be a bad thing.

So please implement all this logic in the adapter proper, and remove any changes to generic Mixer code

**Comment by liminw** [comment]
Hi @geeknoid, thanks for the comments. I added the RBAC code to the general Mixer code for a couple of reasons:
1. Mixer already implemented CRD read and watch mechanism today. If this has to be moved to adapter, there will have to be a lot of duplicated code. 
2. As I understand, Istio native RBAC ServiceRole and ServiceRoleBinding will be first-class objects that shipped with Istio. Istio will also manage its config rollout. I think it is ok for Mixer to understand ServiceRole and ServiceRoleBinding CRDs by default. 
3. Most of the RBAC logic is encapsulated in rbacStore.go. It won't affect the rest of the Mixer logic. 
4. Adapter is just a way to enable RBAC. There is a "rbacEnabled" flag in the code, which is enabled only if the RBAC adapter is configured. If RBAC adapter is not configured, Mixer will not process RBAC CRDs.

**Comment by geeknoid** [comment]
Sorry, the Mixer is about routing requests to adapters. It doesn't have any specific knowledge of any of the behaviors of the adapters it is routing to. I do not want to compromise on this point. It's not architecturally appropriate.

If the issue is about code duplication, perhaps the right path here is to create a generic utility package that both Mixer and the RBAC adapter can share. Maybe Pilot and Istio-CA can use that same package as well. This is similar to what we're doing with istio/pkg/log.

**Comment by wora** [comment]
I totally agree with Martin.

Have we considered implementing this logic in Envoy?

**Comment by geeknoid** [comment]
The plan is to have the RBAC logic both in Envoy and in Mixer.

The operator will eventually be programming the system using high-level
config. Based on what the operator intends to do, Galley will be able to
decide whether the proxy's RBAC logic should be used, or whether Mixer
needs to be used instead. Mixer has a richer environment so it can do more
than Envoy can.

**Comment by geeknoid** [comment]
Thanks Mandar for the detailed instructions.

**Comment by liminw** [comment]
Thanks for all the suggestions. I am going to close this PR for now, and open two PRs later, one for API proto change (to istio/api repo), and one for RBAC adapter change.

**Pull request closed without merging**
