### PR TITLE
Build CNI images along with others

### PR DESCRIPTION
**Pull request by jwendell**
`make docker` now builds CNI images as well.

### CODE REVIEW

**Comment by jwendell** [comment]
Part of https://github.com/istio/istio/issues/24610

**Comment by howardjohn** [comment]
I don't think our CNI test is using these yet right? I see that is on the TODO list actually so :+1:

**Comment by jwendell** [comment]
Yeah, I'm porting `release-builder` to the new location, and it relies on `make docker` to actually generate `install-cni` image.

**Pull request merged**
