### PR TITLE
Fix `make docker` on a Mac to build linux binaries

### PR DESCRIPTION
**Pull request by ericvn**
Fixes https://github.com/istio/istio/issues/19381

### CODE REVIEW

**Comment by ericvn** [comment]
I did verify _make_ versions:

```
make -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```
while _brew_ has a later make:
```
brew info make
make: stable 4.2.1 (bottled)
Utility for directing compilation
https://www.gnu.org/software/make/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/make.rb
==> Caveats
GNU "make" has been installed as "gmake".
If you need to use it as "make", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
==> Analytics
install: 4,665 (30 days), 13,925 (90 days), 50,318 (365 days)
install-on-request: 4,195 (30 days), 12,494 (90 days), 44,465 (365 days)
build-error: 0 (30 days)
```
I did install _gmake_ and running _gmake_ does indeed solve the issue.
@howardjohn Are we OK with requiring MacOS developers to install additional tooling and use that? I guess I would have to update the wiki with some information.

**Comment by howardjohn** [comment]
@ericvn if we can fix it on the old make that would be ideal, I am not sure where the breakage is... I just found out this was broken yesterday from someone having the same old version

**Comment by ericvn** [comment]
I'll add a comment in the wiki about using a newer `make` version for now (I have to put another update in it as well). Then I'll see if I can figure out how fix things to work with the older make (and then remove from the wiki). I'll add another commit in this PR if/when I figure something out.

**Comment by sdake** [comment]
> @howardjohn Are we OK with requiring MacOS developers to install additional tooling and use that? I guess I would have to update the wiki with some information.

@ericvn It depends on the scenario:

If your building with BUILD_WITH_CONTAINER=0, you will need to hunt and hunt for the proper toolchains and dependencies to build Istio
If your building with BUILD_WITH_CONTAINER=1, you should be able to use pristine MacOS with (only) Docker+Xcode installed. Note this mode is not quite finished. The implementation is taking place in PR: https://github.com/istio/istio/pull/19322

Cheers
-steve

**Comment by ericvn** [comment]
@sdake I agree that it's preferable to not to have developers hunt for the appropriate tools, which is why we want to go to the build container. Without the build container (what's in the repo as I type this), we do require at least Mac developers to get a newer version of `make` or know that they need to add an additional target to get the Docker images to build. Hopefully, I (or someone) can figure out how to change the makefile to work with the older versions of make. Or we get the build container integrated into the istio/istio repo which will allow the Docker images to be built. But it also prevents some from pushing their images to their specified image repository. There is code that allows pushing to work if your destination repository is Docker Hub and your are able to select non-default Docker functionality (note that there is no way for me unselect the default, Mariam can, and not sure about others so I cannot do from within the current build container logic).

**Comment by ericvn** [comment]
@howardjohn Looking at the makefile doc:
```
The define directive is followed by the macro name and a newline. The body of the macro includes all the text up to the endef keyword, which must appear on a line by itself.
```
doesn't mention the `=` that was in the makefile and removed it. The change fixes the issue I was seeing on my Mac and didn't impact the build when using the newer _gmake_.

**Pull request merged**
