### PR TITLE
Tag must be type interface{} for unmarshaling

### LINKED ISSUE #19921: istioctl --set cannot handle numeric strings
```
$ ik manifest apply --set hub=localhost:5000 --set tag=1578154376
Error: failed to generate and apply manifests, error: failed to generate tree from the set overlay, error: bad path=value: tag=1578154376
```

This works in helm with --set-string if I understand correctly

### PR DESCRIPTION
**Pull request by ostromart**
Fixes https://github.com/istio/istio/issues/19921.
Depends on istio/api#1275.

### CODE REVIEW

**Comment by ostromart** [comment]
Depends on https://github.com/istio/api/pull/1275.

**Review by morvencao — APPROVED** [review]

**Review by sdake — APPROVED** [review]

**Review by elfinhe — APPROVED** [review]

**Pull request merged**
