### PR TITLE
Add sts port into node metadata

### PR DESCRIPTION
**Pull request by bianpengyuan**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by JimmyCYJ** [comment]
Thanks for the change. Can we add some tests once the code change is completed?

**Comment by bianpengyuan** [comment]
@JimmyCYJ Sure will do. Just want to make sure this is the clean way to get the sts enablement information into envoy.

**Comment by bianpengyuan** [comment]
@JimmyCYJ ptal. this change does not have integration test coverage. It does not introduce any real usage of the node metadata. Integration test could be added later.

**Pull request merged**
