### PR TITLE
Update metallb

### PR DESCRIPTION
**Pull request by howardjohn**
We see timeouts in CI. Example:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49162/integ-basic-arm64_istio/1753222587070025728

This is just a lot of things taking slightly too long. On the failures,
the image pull typically takes ~30s. this is slow, but not
unreasonably slow.

Then the containers need to actually get marked ready. The upstream has
probes poorly defined for this, so I modified them (as well as updating
the image) to startup faster. Now they start in a couple seconds vs
~15s.

This needs to land in istio/common-files, so probably we don't want to merge this (though we can)

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
blocked by https://github.com/metallb/metallb/issues/2274

**Review by jacob-delgado — APPROVED** [review]
LGTM. Let's get this in common-files

**Pull request merged**
