### PR TITLE
Istio does not use Cluster_LOGICAL_DNS, so remove it

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by GregHanson** [comment]
@hzxuzhonghu do we know if this is something we ever want to support?
Also some other line references in cluster.go to LOGICAL_DNS on 207 and 268
cc @rshriram

**Comment by hzxuzhonghu** [comment]
removed

**Comment by potterhe** [comment]
@hzxuzhonghu  请教一下，istio 不支持 Cluster_LOGICAL_DNS 的原因是什么？根据envoy的文档https://www.envoyproxy.io/docs/envoy/v1.6.0/intro/arch_overview/service_discovery#logical-dns，与在大型web服务交互时，更推荐使用 “Logical DNS” 这种服务发现方式。

**Comment by hzxuzhonghu** [comment]
In most k8s scenarios, there is no difference for the two types.

**Pull request merged**
