### PR TITLE
Abstract some common codes in istioctl/pkg/kubernetes/client.go

### PR DESCRIPTION
**Pull request by m1093782566**
Functions `PilotDiscoveryDo`, `EnvoyDo` and `AllPilotsDiscoveryDo` all call Kubernetes client to execute some commands in container of Pod. We can refactor these functions and abstract the common piece of codes.

### CODE REVIEW

**Comment by m1093782566** [comment]
@esnible

**Comment by m1093782566** [comment]
@ayj 

Would you please take a look when you have chance?

**Comment by liamawhite** [comment]
/lgtm 

@m1093782566 you will need to retrigger the tests though, try making a cosmetic change to the existing commit and force push?

**Comment by m1093782566** [comment]
@liamawhite 

Seems flaky test failures are gone after rebasing to the HEAD. Woud you please take a look again?

**Comment by m1093782566** [comment]
Thanks @liamawhite!

**Pull request merged**
