### PR TITLE
[Release-1.3] Sort filterchains for inbound virtual listeners

### PR DESCRIPTION
**Pull request by nrjpoddar**
The fix in `master` is in https://github.com/istio/istio/pull/18091.

Fixes: #18088

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
Updated the discussion to link to the `master` PR https://github.com/istio/istio/pull/18091.

**Comment by rshriram** [comment]
I would suggest that we revert this patch. We should have used filter chain names here as well so that the logic is consistent across the board. At this point, 1.3 will have one way of sorting while 1.4 will have a different way of sorting. So, anyone who is transitioning from 1.3 to 1.4 will see a deluge of connection drops due to different filter chains. :(

**Comment by nrjpoddar** [comment]
> I suggest that we revert this patch. We should have used filter chain names here as well so that the logic is consistent across the board. At this point, 1.3 will have one way of sorting while 1.4 will have a different way of sorting. So, anyone who is transitioning from 1.3 to 1.4 will see a deluge of connection drops due to different filter chains. :(

May be I am not understanding this correctly, so when are you're upgrading from 1.3->1.4, once your control plane upgrades, the Pilot produces the new style Envoy config. Where is the ambiguity which will lead to conns dropping? Plus, between 1.3 & 1.4 there will be lot of other Envoy filter and listener changes so isn't this expected behavior. If the new norm is that between LTS releases you cannot change the way Pilot serializes Envoy configuration I wasn't aware of that.

Instead of reverting, why not keep it so that folks who currently can't use 1.3.3 can take the daily builds and we can add a new PR with better code based on your suggestions and reverting this change as one unit?

**Comment by rshriram** [comment]
> May be I am not understanding this correctly, so when are you're upgrading from 1.3->1.4, once your control plane upgrades, the Pilot produces the new style Envoy config. Where is the ambiguity which will lead to conns dropping? 

Not necessarily. We dont change style of envoy config. 1.4 pilot will emit names for all filter vhains (inbound/outbound). These will be sorted by these names and not by the original listener name as done by this PR. Since the order is different, listeners will drain.

> Plus, between 1.3 & 1.4 there will be lot of other Envoy filter and listener changes so isn't this expected behavior. If the new norm is that between LTS releases you cannot change the way Pilot serializes Envoy configuration I wasn't aware of that.

most of changes [new filters] are guarded. So they dont make it to older proxies. Given that the goal of this change is to actually eliminate 503s, causing fleetwide reload of all listeners seems to beat the purpose. 

Anyway, I dont mind this PR as long as it gets overwritten by proper naming scheme from #18091

**Comment by howardjohn** [comment]
> Not necessarily. We dont change style of envoy config. 1.4 pilot will emit names for all filter vhains (inbound/outbound). These will be sorted by these names and not by the original listener name as done by this PR. Since the order is different, listeners will drain.

Won't we trigger a drain just by nature of adding the name?

Draining listeners is not great, but its not something we need to go out of our way to make sure it *never* happens. I think during an upgrade causing a drain is fine... they will already get drains any time they apply certain CRDs. Draining generally won't cause 503s, the original issue here was requests that lasted minutes, which isn't very common.

I also don't see why the order would change between 1.3 and 1.4, given that in 1.3 we sort by metadata (which only has the name in it) and 1.4 we sort by name?

> Anyway, I dont mind this PR as long as it gets overwritten by proper naming scheme from #18091

Just to clarify, you are fine with this for 1.3 as long as in master/1.4 we use `name`?

**Comment by Stono** [comment]
Hey, not _quite_ true; we saw 503UCs in some short requests too which were resolved fully by the fix: https://github.com/istio/istio/issues/18089

**Comment by howardjohn** [comment]
@Stono thanks for pointing that out. Seems like we probably need some fixes on envoy side to handle the drain better

**Comment by nrjpoddar** [comment]
> Hey, not _quite_ true; we saw 503UCs in some short requests too which were resolved fully by the fix: #18089

What's your drain duration setting?

**Comment by Stono** [comment]
45s

**Pull request merged**
