### PR TITLE
[release-1.16]  Manual cherry-pick to fix #43590 and #43783

### LINKED ISSUE #43783: [release-1.16] AccessLogging: fix the issue where disable accesslogging does not take effect
Manual cherrypick required.

#43770 failed to apply on top of branch "release-1.16":
```
Applying: AccessLogging: fix the issue where disable accesslogging does not take effect.
Using index info to reconstruct a base tree...
M	pilot/pkg/model/telemetry.go
M	pilot/pkg/model/telemetry_logging_test.go
M	pilot/pkg/networking/core/v1alpha3/accesslog.go
M	pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/networking/core/v1alpha3/accesslog_test.go
CONFLICT (content): Merge conflict in pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Auto-merging pilot/pkg/networking/core/v1alpha3/accesslog.go
Auto-merging pilot/pkg/model/telemetry_logging_test.go
Auto-merging pilot/pkg/model/telemetry.go
CONFLICT (content): Merge conflict in pilot/pkg/model/telemetry.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 AccessLogging: fix the issue where disable accesslogging does not take effect.
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by fatedier**
**Please provide a description of this PR:**
Fix #43590
Fix #43783

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by ZiyangXiao** [comment]
wait https://github.com/istio/istio/issues/43783 as howard said in https://github.com/istio/istio/pull/43590#issuecomment-1456416305

**Comment by fatedier** [comment]
@ZiyangXiao I have cherry-picked these two PRs （#43372 and #43770） together because picking them separately would have led to some issues.

**Comment by ZiyangXiao** [comment]
@fatedier thanks, LGTM!

**Review by ZiyangXiao — APPROVED** [review]

**Pull request merged**
