### PR TITLE
Remove Jobs in istio-init

### PR DESCRIPTION
**Pull request by johscheuer**
In the current helm setup the CRDs for Istio are installed via Jobs this has some drawbacks:

- If you are running in a restricted env you must ensure that the Jobs (actually the ServiceAccount) have an appropriate PSP associated
- If you delete a resource and you rerun the `istio-init` steps nothing will happen until you delete the Jobs
- Using `kubectl apply --prune` is nearly impossible which means you need to cleanup manually (e.g. if you upgrade to a new release which removes some CRDs)
- Also a benefit is that `istioctl verify-install` works now

It seems like others feel the same: https://github.com/istio/istio/issues/17638

In the current setup I removed the jobs completely (we could also add a variable "jobless" (hopefully with a better name). Are there any reasons not to completly remove the jobs ?

Running this locally against my GKE cluster seems fine:

```bash
$ kubectl apply -f <(helm template  ./install/kubernetes/helm/istio-init)
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io created
...
$ istioctl verify-install  -f <(helm template  ./install/kubernetes/helm/istio-init)
...
Checked 24 crds
Checked 0 Istio Deployments
Istio is installed successfully
$ kubectl create namespace istio-system
$ kubectl -n istio-system apply -f <(helm template install/kubernetes/helm/istio --namespace istio-system \
    --values install/kubernetes/helm/istio/values-istio-demo.yaml \
    --set global.controlPlaneSecurityEnabled=true \
    --set global.mtls.enabled=true)
...
$ istioctl verify-install -f <(helm template install/kubernetes/helm/istio --namespace istio-system \
    --values install/kubernetes/helm/istio/values-istio-demo.yaml \
    --set global.controlPlaneSecurityEnabled=true \
    --set global.mtls.enabled=true)
...
Checked 0 crds
Checked 9 Istio Deployments
Istio is installed successfully
```

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
Did you test upgrade case? If we remove these jobs and upgrade with tiller, it may complain that `resource with name xxx not found` issue, this is the same reason why we didi't remove post-install job in citadel.

/cc @sdake

**Comment by johscheuer** [comment]
Good catch I need to test the upgrade case with Tiller (normally I only use `helm template`).

**Comment by johscheuer** [comment]
It seems like this change will break all `tiller` users (see: https://github.com/helm/helm/issues/6031) and i can repro this issue:

```bash
helm upgrade istio-init install/kubernetes/helm/istio-init --namespace istio-system
UPGRADE FAILED
Error: kind CustomResourceDefinition with the name "gateways.networking.istio.io" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind CustomResourceDefinition with the name "gateways.networking.istio.io" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```

This means that users would need to delete the CRD's before upgrade (which in fact means deleting all CR). :(

**Comment by johscheuer** [comment]
Currently I see two options:

1.) We stick with the setup like it is (which can be annoying for `helm template` users)
2.) We add an option for "jobless" deployments but the default will be via jobs

**Comment by sdake** [comment]
> Currently I see two options:
> 
> 1.) We stick with the setup like it is (which can be annoying for `helm template` users)
> 2.) We add an option for "jobless" deployments but the default will be via jobs

I am ok with attempting #2. There must be no impact to the upgrade scenario in the new tiller model (we have had trouble with this prior, because of the `crd-install` annotation.............). The reason we have this jobs model was to switch away from the crater left by the `crd-install` functionality in Helm... A special option for `helm template` users seems acceptable.

If the CRDs are merged in with the manifest in tiller mode, all kinds of bad happens.

We are not doing that.

Cheers
-steve

**Comment by howardjohn** [comment]
It seems at best we should add an option to do this (which would result in this PR being about 8 lines of code added and none removed I think? I don't think there is much point investing the effort it would require to make this change the default when we are moving to deprecate this installation method

**Comment by howardjohn** [comment]
Hi, sorry this change has been sitting for a while. In the next release we will be deleting the install/ folder, so I don't think this is a change we can accept. All future releases will use the helm charts under manifests/ which does not use Jobs

**Comment by johscheuer** [comment]
Hi Howard, thanks for your response ! I close this PR.

**Pull request closed without merging**
