### PR TITLE
fix wrong italic format

### PR DESCRIPTION
**Pull request by waret**
Please provide a description for what this PR is for.
protoc-gen-docs parsing underline occors error, please refer to:
https://istio.io/docs/reference/config/policy-and-telemetry/adapters/redisquota/#Params-Quota

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by geeknoid** [comment]
Could you run "go generate" in that directory in order to regenerate the .html files and other things?

Thanks.

**Comment by waret** [comment]
Finally understand how to run mixer_codegen.sh. sorry to have submitted so much.

**Pull request merged**
