### PR TITLE
Fix build break due to https://github.com/istio/istio/pull/11406.

### PR DESCRIPTION
**Pull request by ozevren**
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11645/istio-integ-local-tests/5215

### CODE REVIEW

**Comment by kyessenov** [comment]
/lgtm
/approve

@wenchenglu please merge to unbreak the build

**Comment by nmittler** [comment]
do we know how this happened? Did we merge something, ignoring CI failures?

**Comment by ozevren** [comment]
I *suspect* this was a case of conflict of changes on back-to-back merges.
Since we're in the admin-only merge mode in release 1.1, the PRs don't get
rebased and go through a single queue.

**Comment by kyessenov** [comment]
codecov jobs will fail since it can't build the base of the PR...

**Comment by ozevren** [comment]
@wenchenglu, this fixes a build break.

**Pull request merged**
