### PR TITLE
[kiali] fix problem where istioctl is pulling in wrong version of kiali

### LINKED ISSUE #21526: Istio 1.5-beta.3 pulls in Kiali 1.9.1 in demo profile
**Bug description**
An older version of Kiali is installed in the Istio 1.5.beta.3 build. It installs 1.9.1 and should be 1.13 instead.

Kiali_Console_-_Firefox_Developer_Edition

**Expected behavior**
It is expected to pull in Kiali 1.13 instead of the older 1.9.1

Related Kiali 1.13 PR: https://github.com/istio/istio/pull/20866

**Steps to reproduce the bug**
`istioctl dashboard kiali`
Then in Kiali click on the question mark in the upper right of the screen, then there will be an `About` menu item that will take you to the Kiali about page with version info.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
~/istio-1.5.0-beta.3 istioctl version                                                                   09:32:59
client version: 1.5.0-beta.3
control plane version: 1.5.0-beta.3
data plane version: 1.5.0-beta.3 (15 proxies)
```

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes: https://github.com/istio/istio/issues/21526

### CODE REVIEW

**Review by sdake — APPROVED** [review]
LGTM.

**Comment by jmazzitelli** [comment]
I don't understand the magic going on here - but changing "default.yaml" is what made "make gen" put the 1.14 update (overwriting the old 1.9) in the auto-generated files. I *think* this also will give you this latest kiali version in the demo profile (even though i didn't touch demo.yaml - it doesn't specify "tag" in there).

I'd like to locally test this, but since the monorepo work finishes, the istioctl --installPackagePath option isn't working for me (I can't just point to my local repo anymore and get istioctl to install with my local changes). So something changed - how do you now test istioctl with local changes?

**Comment by sdake** [comment]
> I don't understand the magic going on here - but changing "default.yaml" is what made "make gen" put the 1.14 update (overwriting the old 1.9) in the auto-generated files. I _think_ this also will give you this latest kiali version in the demo profile (even though i didn't touch demo.yaml - it doesn't specify "tag" in there).
> 

This should an improvement to our developer wiki:

`make gen` executes MANY targets. The two that are relevant for install are `update-goldens` and `gen-charts`. These two targets do the following:
- `update-goldens` generates test files
- `gen-charts` generates a blob of data via go-bindata containing the charts.

> I'd like to locally test this, but since the monorepo work finishes, the istioctl --installPackagePath option isn't working for me (I can't just point to my local repo anymore and get istioctl to install with my local changes). So something changed - how do you now test istioctl with local changes?

please file a bug.

**Comment by jmazzitelli** [comment]
> please file a bug.

https://github.com/istio/istio/issues/21530

**Comment by jmazzitelli** [comment]
The cherry-pick failure was due to a conflict - this PR fixes it but needs to be merged now into the 1.5 branch: https://github.com/istio/istio/pull/21543

**Pull request merged**
