### PR TITLE
Fix node agent error processing and improve logging

### PR DESCRIPTION
**Pull request by myidpt**
Cherrypick the change https://github.com/istio/istio/pull/19341 to 1.4.

### CODE REVIEW

**Comment by myidpt** [comment]
John, this is a blocker for us. I can chat with you tomorrow.

**Comment by howardjohn** [comment]
this just can't be merged until after 1.4.2 or it makes things complicated with the private patches

**Comment by myidpt** [comment]
I see. Thanks.

**Comment by myidpt** [comment]
Can we get this in? @howardjohn

**Pull request merged**
