### PR TITLE
Register new RequestAuthentication API

### PR DESCRIPTION
**Pull request by diemtvu**
Register RequestAuthentication API.

Issue: https://github.com/istio/istio/issues/18399

### CODE REVIEW

**Comment by howardjohn** [comment]
Running this locally breaks pilot with `Configuration not synced: first push for [istio/security/v1beta1/requestauthentications] not received`

@sushicw I thought we handled missing CRDs now? is that just in Galley code not pilot, or not enabled by default?


Anyhow you probably need the CRD first

**Comment by jasonwzm** [comment]
Adding the CRDs here: https://github.com/istio/api/pull/1169

**Comment by sushicw** [comment]
> Running this locally breaks pilot with `Configuration not synced: first push for [istio/security/v1beta1/requestauthentications] not received`
> 
> @sushicw I thought we handled missing CRDs now? is that just in Galley code not pilot, or not enabled by default?
> 
> Anyhow you probably need the CRD first

I believe Galley handles missing CRDs with reasonable grace when running with the new Galley pipeline (which is on by default now), but I don't know about Pilot.

**Comment by jasonwzm** [comment]
@diemtvu the API PR is merged. You can update the api version and run `make update-crds` to get the new CRD here.

**Comment by diemtvu** [comment]
> @diemtvu the API PR is merged. You can update the api version and run `make update-crds` to get the new CRD here.

Done. Do I have to do anything with installer too? Looks like new-install test fail because the CRD is not recognized.

**Comment by diemtvu** [comment]
Not sure if it is the right way, but I copy the `crd-all.gen.yaml` to installer repo and create https://github.com/istio/installer/pull/553. I guess it need to be committed first for the `integ-new-install-k8s-tests_istio` to pash.

**Comment by jasonwzm** [comment]
I'm not very familiar with that test, but from the logs it seems the CRD is not being added. After updating installer, also update operator?

**Comment by howardjohn** [comment]
I updated operator but you still need to pull in the dependency to Istio/istio with `go get istio.io/operator@master`

**Comment by diemtvu** [comment]
> I updated operator but you still need to pull in the dependency to Istio/istio with `go get istio.io/operator@master`

Thanks. Everything is good now.

**Review by howardjohn — APPROVED** [review]
Related: https://github.com/istio/istio/issues/13559

This is not a new problem or one specific to this CRD, but this will mean users cannot use pilot `master`/`1.5` with Galley 1.4, which makes upgrades a bit more challenging, as well as development. I guess istiod may improve this

**Review by jasonwzm — APPROVED** [review]

**Pull request merged**
