### PR TITLE
removed omitempty from Route TimeoutMS

### PR DESCRIPTION
**Pull request by prune998**
the `omitempty` keyword in the Route definition is preventing an empty timeout (=0) to be defined. This leads to the Envoy Default Timeout of 15s which breakes the long lasting connections, like the ones used in gRPC Streaming.

With this change, the Timeout is alway 0 (no timeout) except when you set it to another value in a RouteRule.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by prune998** [comment]
PR is linked to https://github.com/istio/istio/issues/1667

**Comment by kyessenov** [comment]
LGTM. thanks!
/lgtm
/approve

**Comment by prune998** [comment]
@kyessenov I just changed the test dataset to add the timeout_ms field, please rest when you can.
Thanks

**Comment by rshriram** [comment]
Hi, I think you need to sign the CLA.

**Comment by prune998** [comment]
CLA signed

**Comment by prune998** [comment]
hummm ? What should we do now ? There was 3 commits, one from @rshriram  and 2 from me, so who did author the commits ?

**Comment by rshriram** [comment]
ignore that.. I am more worried about why the tests are failing.

**Comment by rshriram** [comment]
Please update the golden files again..I think some other PRs went in and added new golden files.

**Comment by wora** [comment]
Almost all istio configs and schemas are defined using proto3. By design, all proto3 fields are default to 0 or "". If we use proto3, we should stick to the language spec across istio components. If you want to produce default value 0 in the json output, you should use google.protobuf.Int64Value. I don't think we should modify the proto3 semantics.

AFAICT, this PR only affects json. If we ever use proto binary as wire format, it would not work. So I recommend we don't override the behavior and use other ways to work around the problem.

**Comment by kyessenov** [comment]
@wora what is the correct way to represent default values that are not 0 in proto3? There are legitimate cases when value 0 is not the right default value in the API. Using an empty wrapper?

**Comment by kyessenov** [comment]
By the way this PR is not using proto3. We're using native JSON serialization in golang for Envoy v1 config.

**Comment by wora** [comment]
proto3 does not support custom default value. The reason we removed default value from proto3 spec is that the default value is hardly ever correct. A default value useful for server is hardly ever right for mobile.

envoy.api.v2 is using proto3. If this is for envoy.api.v1, I am fine to keep the existing behavior as is.

**Pull request merged**
