### PR TITLE
[WIP] test authz deny

### PR DESCRIPTION
**Pull request by jtrbs**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
Can you give some more context on the DR/PA changes?

**Comment by jtrbs** [comment]
Hi @howardjohn thanks for checking! This PR is for some debugging on https://github.com/istio/istio/pull/31620/files TestAuthorization_Deny. We found that for allow test cases such as `newTestCase(b, "/allow", true),`, responses are only within the clusters of same network. Thus wanna check why this is the case. Do you know possible reasons for it? Thanks!

**Pull request closed without merging**
