### PR TITLE
remove file from file certs before triggering call backs

### PR DESCRIPTION
**Pull request by ramaraochavali**
Fixes https://github.com/istio/istio/issues/44824

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
I would prefer using the filewatcher under istio.io/pkg, you donot have to rewatch the file

**Review by howardjohn — APPROVED** [review]
Looks reasonable. Is it feasible to get test coverage?

**Comment by ramaraochavali** [comment]
>  Is it feasible to get test coverage?

I could not think of a way to write test. I will spend more time and see if I can craft a test

**Comment by LithiumSR** [comment]
Would it be possible to add the cherry-pick label for this?
Older and still supported versions are also affected

**Comment by ramaraochavali** [comment]
Sure. Added

**Pull request merged**
