### PR TITLE
change monitoring address default

### PR DESCRIPTION
**Pull request by ramaraochavali**
Changes monitoring address to be accessible only on local host by default.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Looks like istioctl depends on this endpoint, so closing this

**Comment by howardjohn** [comment]
doesn't prometheus depend on this too?

**Comment by ramaraochavali** [comment]
I was n't sure about prometheus - one istioctl related test failed. There is a Dashboard test that failed - Is that related to prometheus?

**Pull request closed without merging**
