### PR TITLE
cds: cache well known clusters

### PR DESCRIPTION
**Pull request by ramaraochavali**
Currently, we build standard well known clusters like Blackhole cluster and Passthrough clusters every time for every proxy. We can build them once, and reuse them whenever CDS is being built. This PR implements cache of these well known clusters.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Benchmark results of `BuildClusters` 

Before    	   59734	     17394 ns/op	   14797 B/op	     229 allocs/op
After  	   74468	     15992 ns/op	   11935 B/op	     202 allocs/op

Benchmark results of 'Anywithcache`

Before    	 1370701	       874 ns/op	     272 B/op	       3 allocs/op
After    	27717297      43.5 ns/op	       0 B/op	       0 allocs/op

**Comment by ramaraochavali** [comment]
Yeah. Only connect timeout is non static. I am thinking about how to reset them when that config is changed - one way I am thinking is to hold the connect timeout in a var and if it
changes reset these clusters - any other better way?

**Comment by howardjohn** [comment]
What performance improvement in a real cluster are we seeing with this?
adding all this caching is a slippery slope of complexity and subtle bugs
so if we do it as should make sure it's worth it.

**Comment by howardjohn** [comment]
And if we assume it's just mesh config that impacts this, we could just
clear the cache on mesh config updates potentially

**Comment by ramaraochavali** [comment]
> What performance improvement in a real cluster are we seeing with this?

I was not able on a big enough cluster to validate how signigicant this performance improvement is. Was just trying with basic benchmarks.

> adding all this caching is a slippery slope of complexity and subtle bugs
so if we do it as should make sure it's worth it.

Completely agree with this - given the dependency on mesh config (and probably some other things in future), It can lead to subtle bugs.

**Comment by ramaraochavali** [comment]
I am closing this for now, will open again once I test and confirm the perf improvement on real big enough cluster.

**Pull request closed without merging**
