### PR TITLE
Add vendor related owners

### PR DESCRIPTION
**Pull request by ldemailly**

### CODE REVIEW

**Comment by geeknoid** [comment]
Could we use teams here so we have a consistent story overall?

**Comment by ldemailly** [comment]
@geeknoid sure, can you create a team ? istio-vendor-reviewers ? (with the names on this pr)
thx

**Comment by geeknoid** [comment]
To follow our convention to date, the team is 

Reviewers - istio/vendor

and has the names included.

**Comment by ldemailly** [comment]
so reviewers-istio-vendor in the file, right ?

**Pull request merged**
