### PR TITLE
Disable MCP by default

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by howardjohn** [comment]
This is in preparation for disabling galley by default for Istiod. Probably does make much sense without https://github.com/istio/istio/pull/19985 though

**Comment by ayj** [comment]
I'm not sure the order really matters. It actually might be easier for this PR to merge before https://github.com/istio/istio/pull/19985 so I can completely disable the galley deployment when istiod is enabled.

**Comment by howardjohn** [comment]
Good point. If it is easier I marked this as "Ready to review". I mostly meant we would not make this change if we weren't also going to land yours - I agree the order does not matter. I am happy to make your life easier :slightly_smiling_face:

**Comment by howardjohn** [comment]
Turning off galley might be non-trivial to get passing tests though since we have galley pretty integrated into the test framework. Or it might just work.. not sure

**Comment by elfinhe** [comment]
I tested this config yesterday with master, seems like the ingress gateway does not work on bookinfo. Maybe it is waiting for the merge of galley.

**Comment by ayj** [comment]
Are we keeping MCP on for the legacy charts? I'm not sure those are tested anymore?

**Comment by howardjohn** [comment]
@ayj the legacy charts are still used in the `e2e/` folder (for now.. we really need to migrate them over so we can kill it), and we also test them in postsubmit in the integration/ folder. The current plan is to not touch anything there for istiod/telemetry v2

**Review by ayj — APPROVED** [review]

**Comment by howardjohn** [comment]
@rshriram @hzxuzhonghu the intent here is to fallback to the pilot internal CRD reading for 1.5 so we can remove the galley deployment. The main thing we lose here is people relying on galley as an MCP source, but thats a very rare use case, and they can just enable galley. For normal case, there shouldn't be anything user facing as far as I know

**Review by nmittler — APPROVED** [review]

**Comment by ayj** [comment]
We'll need to integrate some of Galley's processing into Pilot to support analysis and CRD status.

**Comment by howardjohn** [comment]
> We'll need to integrate some of Galley's processing into Pilot to support analysis and CRD status.

My understanding is that in 1.5 Status is not ready or default (not sure which one or both). For analysis, same story, right? `istioctl analyze` still works since it just uses the galley processing locally anyways. Is that correct?

**Comment by ayj** [comment]
@sushicw @therealmitchconnors, can you comment on the status of "CRD status" for 1.5? The original goal was to turn this on by default in some form for 1.5.

**Comment by hzxuzhonghu** [comment]
OK.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by howardjohn** [comment]
not sure why it's failing randomly now.. will investigate

**Comment by hzxuzhonghu** [comment]
/hold

integ-pilot-k8s-tests_istio is failing so frequently, seems something wrong

**Comment by hzxuzhonghu** [comment]
This has something todo with `IngressControllerMode`

**Comment by howardjohn** [comment]
> This has something todo with IngressControllerMode change?

In order to support Ingress, which was previously done over MCP, we need to enable the pilot Ingress code. Must be some issue there, looking into it.

**Comment by howardjohn** [comment]
I think it was just broken by https://github.com/istio/istio/commit/5ae7795d3b87b7d8e301bac1f347098d614c280a, will fix

**Pull request merged**
