### PR TITLE
Update proxy SHA to fix prom filter label

### PR DESCRIPTION
**Pull request by bianpengyuan**
This is to pick up a bug fix in 1.3: https://github.com/istio/proxy/pull/2406

### CODE REVIEW

**Comment by rlenglet** [comment]
The istio-pilot-e2e-envoyv2-v1alpha3-release-1.3 test will be fixed by https://github.com/istio/istio/pull/16682.

**Comment by bianpengyuan** [comment]
cc @mandarjog

**Comment by mandarjog** [comment]
@rlenglet please merge before nightly build :-)

**Comment by rlenglet** [comment]
> please merge before nightly build :-)

@mandarjog have faith in the Tide. :)

**Pull request merged**
