### PR TITLE
operator/cmd/mesh/testdata: remove docs

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

They aim to test, not user affect,

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by carolynhu — DISMISSED** [review]
What's the purpose of this PR? I don't think we should remove any of those files in data-snapshot, those are generated via run_update_golden_snapshots.sh which in sync with manifests files. Might be ok to close? if you do not have any other related to change.

**Comment by daixiang0** [comment]
Now `run_update_golden_snapshots.sh` has updated, i do not see bot auto remove them, so post this pr.

**Comment by carolynhu** [comment]
Ok, I just checked, you updated the golden snapshot script yesterday https://github.com/istio/istio/pull/28454

well, the less misleading way to help us review your code is to either `make change in 28454 and this PR the same PR` or `when you doing this PR link to your previous PR`. I have to say, this doesn't have to be updated. Anyways, if this is what you want to improve, it's fine. But next time, please make it much more clear to save us time to review your code. Thanks for your collaboration!

**Comment by daixiang0** [comment]
Thanks for your review!

**Review by carolynhu — COMMENTED** [review]
lgtm

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
