### PR TITLE
Fixed waypoint proxy to respect trust domain

### LINKED ISSUE #53736: Waypoint proxy does not respect trust domain
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When deploying a waypoint proxy in an environment with a customized trust domain, the trust domain is not respected and the ROOTCA signature fails.

```yaml
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
  trustDomain: <CUSTOM_TRUST_DOMAIN>
```

### waypoint proxy logs

```
{"time":"2024-10-31T08:32:28.051222Z","level":"warning","scope":"envoy config","msg":"StreamSecrets gRPC config stream to sds-grpc closed: 2, failed to generate secret for default: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure","caller":"external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:176","thread":"13"}
{"level":"error","time":"2024-10-31T08:32:28.122838Z","scope":"citadelclient","msg":"failed to sign CSR: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure"}
{"level":"info","time":"2024-10-31T08:32:28.123199Z","scope":"citadelclient","msg":"recreated connection"}
{"level":"error","time":"2024-10-31T08:32:28.123233Z","scope":"cache","msg":"resource:ROOTCA failed to sign: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure"}
```

### istio-csr logs

I am using istio-csr and will provide its log.
However, the use of istio-csr has nothing to do with the nature of this problem.

```
E1031 08:32:28.049937       1 auth.go:115] "failed to match URIs with identities" err="[spiffe://<CUSTOM_TRUST_DOMAIN>/ns/default/sa/waypoint] != [spiffe://cluster.local/ns/default/sa/waypoint]" logger="grpc-server" serving-addr="0.0.0.0:6443" identities="spiffe://<CUSTOM_TRUST_DOMAIN>/ns/default/sa/waypoint"
```

This occurs because `TRUST_DOMAIN` is missing from the waypoint proxy template environment variable.
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/waypoint.yaml#L123-L200

### Version

```Text
$ ic version
client version: 1.23.2
control plane version: 1.23.2
data plane version: 1.23.2 (7 proxies)

$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.4
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by frauniki**
**Please provide a description of this PR:**

- Fixed waypoint proxy to respect trust domain
  - fixed #53736

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [x] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM

**Review by zirain — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by frauniki** [comment]
@hzxuzhonghu @zirain @howardjohn 
Hi!
When are you planning to release these changes?

**Comment by howardjohn** [comment]
Looks like this will be in 1.25 which is releasing in 2 weeks

**Pull request merged**
