### PR TITLE
Revert "Update versions and cleanup"

### PR DESCRIPTION
**Pull request by ozevren**
Reverts istio/istio#3151

### CODE REVIEW

**Comment by rshriram** [comment]
Hi, why this PR? Are you sure that this is what broke the e2e smoke test?

**Comment by ozevren** [comment]
No I am not sure. I am testing to see if this is indeed the case.

The pr is marked with do-not-merge.

**Comment by mattdelco** [comment]
I'm pretty sure.  It removed the dependency on depend/init, so just try "make clean istioctl" and it'll fail.

**Comment by hklai** [comment]
Prow shows that the post submit tests (superset of the e2e smoke test) started failing consistently after #3151.
https://prow.istio.io/?type=postsubmit&job=e2e-suite-rbac-auth

**Comment by ldemailly** [comment]
let's hope #3331 is enough/works

**Pull request closed without merging**
