### PR TITLE
Change the drain strategy to immediate

### PR DESCRIPTION
**Pull request by mandarjog**
resolves https://github.com/istio/istio/issues/31403

During drain Envoy notifies clients using GO-AWAY or connection:close (or other protocol specific methods).
The default is to gradually notify clients, this changes it to immediately notify clients.

The drain duration is unaffected, just that clients have more time to gracefully react to impending termination.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
looks right to me. @lambdai @ramaraochavali any concerns?

**Comment by hzxuzhonghu** [comment]
i remember we donot have hot restart now

**Comment by howardjohn** [comment]
drain still happens when listener/cluster changes and when the pod shuts
down

**Comment by ramaraochavali** [comment]
LGTM

**Comment by howardjohn** [comment]
@mandarjog test needs an update

**Comment by howardjohn** [comment]
> @mandarjog test needs an update

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
