### PR TITLE
Reconcile webhook in pilot

### PR DESCRIPTION
**Pull request by howardjohn**
This is a short term solution to get sidecar injector working until @lei-tang gets the webhook management into istioctl/operator so we can start testing this out.

If its easier to review, I made the first commit moving stuff out of `main.go` and the second adds the new stuff (a couple of lines calling the moved code)

### CODE REVIEW

**Comment by lei-tang** [comment]
Is this PR to move the Sidecar Injector's webhook configuration management from Sidecar Injector to Pilot?

**Comment by howardjohn** [comment]
@lei-tang in order to avoid high cost of migration we want to start adding istiod functionality into pilot. See https://docs.google.com/document/d/1jO2oM9zdm9h7tUqOpnAG3dh1xavtW1L7zQ5LyraYRAs

The original plan was to wait for istioctl to support managing the webhook, but in the short term so that we can start testing this ASAP I am adding it to pilot as well.

Note that for 100% of current Pilot users this change will have no impact, as they will not have the injection enabled. Once we have this in, I will add some config to istio/install to start turning this one and add tests here that use the istiod (in pilot) deployment

**Comment by lei-tang** [comment]
istioctl managing the webhooks is already supported, please refer to the guide at https://istio.io/docs/tasks/security/webhook/.

Two more questions: 
- Is this PR only applied to istiod, or to both istiod and Pilot?
- Will the webhook configuration privilege be issued to istiod only, or to both istiod and Pilot?

**Comment by lei-tang** [comment]
Based on https://docs.google.com/document/d/1jO2oM9zdm9h7tUqOpnAG3dh1xavtW1L7zQ5LyraYRAs, is the following understanding correct: Pilot will become istiod and there is no istiod anymore?

**Comment by howardjohn** [comment]
@lei-tang today we have a more or less working istiod with a very simple setup. The problem is we have had issues in the past with switching over to new things in Istio. In order to make istiod work, we need to fix every single test that expects pilot, make istioctl support calling istiod instead of pilot, etc -- just a lot of extra work. Instead, we will iteratively move everything into the pilot deployment, and as a transition period still keep legacy Services around. So for instance, right now we have added the injection code. We can remove the injector deployment now and point the sidecar-injector Service to pilot and things will work.

At the end of this process there will be a single deployment, pilot, with all of the required features of istiod. However, it will not be as simple as istiod, so at that point we will try to trim it down.


As far as the `istioctl webhook` command, what I meant was until it is part of `istioctl manifest apply`. Right now its not feasible to use the webhook command as part of the tests because the tests just declare some values config but istioctl webhook requires being passed the full webhook yaml

**Comment by lei-tang** [comment]
The integration test of the istioctl webhook command at https://github.com/istio/istio/tree/master/tests/integration/istioctl/webhook takes two full webhook configuration yaml files ([galley-webhook.yaml ](https://github.com/istio/istio/blob/master/tests/integration/istioctl/webhook/config/galley-webhook.yaml) and [sidecar-injector-webhook.yaml](https://github.com/istio/istio/blob/master/tests/integration/istioctl/webhook/config/sidecar-injector-webhook.yaml)), which shows that the istioctl webhook command can be used as part of the tests.

**Comment by howardjohn** [comment]
I guess it might work, that only takes a static yaml file though while the injection template has a bunch of different templated parameters

**Comment by lei-tang** [comment]
This PR has following impacts on existing Istio code, tests, and user guides. With this PR moving Sidecar Injector webhook to Pilot: 
- The implementation of [istioctl webhook managing the webhook configuration](https://github.com/istio/istio/blob/master/istioctl/cmd/webhook.go) of Sidecar Injector needs to changed from managing the webhook configuration at Sidecar Injector to manging the webhook configuration on Pilot. 
- Correspondingly, the [unit tests ](https://github.com/istio/istio/blob/master/istioctl/cmd/webhook_test.go)and [integration tests](https://github.com/istio/istio/tree/master/tests/integration/istioctl/webhook) of istioctl webhook managing the webhook configuration at Sidecar Injector also need to be updated.
- The [user guide](https://istio.io/docs/tasks/security/webhook/) of istioctl webhook managing the webhook configuration at Sidecar Injector also need to be updated.

**Comment by howardjohn** [comment]
None of those things need to change, the webhook configuration is identical as before. the only change is what docker image is behind the sidecar-injector Service.

There is still the exact same webhook istio-sidecar-injector, which points to the same sidecar-injector.istio-system.

**Comment by howardjohn** [comment]
I am not trying to break your webhook work, I just don't want istiod to be blocked waiting for it to get added into the operator

**Comment by howardjohn** [comment]
@lei-tang any thoughts? Do you think we should move forward with this PR?

**Comment by lei-tang** [comment]
I think we should schedule a meeting to discuss this direction.

**Comment by howardjohn** [comment]
Can you talk to @costinm or here? I am out of office for a bit and do not want to be blocked by this

**Comment by lei-tang** [comment]
I am trying to schedule a meeting to discuss this direction; but with folks traveling for Kubecon and coming Thanksgiving, it may be challenging to round up the stakeholders.

**Comment by howardjohn** [comment]
@lei-tang istiod has been approved by ToC and my understanding has already had a lot of discussion around security. Rather than attempt to get a meeting together, which isn't feasible within at least 2 weeks, can we have discussion here or in some other asynchronous form? I don't think we should block istiod

**Comment by lei-tang** [comment]
istiod was planned as an option (the default is still Pilot+Galley+Sidecar Injector+Citadel) so users can try it and provide feedbacks. But with the new proposal in https://docs.google.com/document/d/1jO2oM9zdm9h7tUqOpnAG3dh1xavtW1L7zQ5LyraYRAs, Pilot is replaced by istiod, which becomes the default. The impacts of this new proposal have not been fully discussed yet, e.g., the impacts on stability, migration/upgrade, security, release of other features, etc. I think it will be more efficient to reach an agreement/approval on this new proposal before merging PRs.

**Comment by howardjohn** [comment]
@lei-tang none of these features are enabled by default. This does NOT impact existing users whatsoever. Without explicitly configuring this, this will not be enabled and thus there is no security implications. In this way it is no different than the original istiod model which is opt

**Comment by lei-tang** [comment]
@howardjohn Thanks for the clarification! LGTM based on the following quote:
```
@lei-tang none of these features are enabled by default. This does NOT impact existing users whatsoever. Without explicitly configuring this, this will not be enabled and thus there is no security implications. In this way it is no different than the original istiod model which is opt
```

**Comment by howardjohn** [comment]
Thanks! one thing to note that while that is the current state today, I don't want that to be true in the future (hopefully 1.5 this is default). So we should continue our discussion around this

**Comment by howardjohn** [comment]
Cloes in favor of https://github.com/istio/istio/pull/19107/

**Pull request closed without merging**
