### PR TITLE
adds validation of referential integrity for mixer configs

### PR DESCRIPTION
**Pull request by jmuk**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by kyessenov** [comment]
Is there a design doc for referential integrity validation? If we drive istio through git CI/CD, does the definition have to precede the use? Wouldn't that work badly with lousely-coupled deployment scripts?

**Comment by ayj** [comment]
cc @gjwestlife

**Comment by gjwestlife** [comment]
https://goo.gl/vpthPX outlines the architecture of Galley where the all syntax, semantic and referential integrity checks should happen. I think the validation in this PR will eventual converge with Galley.
@geeknoid

**Comment by kyessenov** [comment]
I'm aware of the proposal. AFAIK Galley is still being designed. This PR on
the other hand changes the user experience of the operator, and will have
visible effect on istio users. I don't think we should just the UX without
thinking through design implications.

**Comment by costinm** [comment]
Since this was started on Dec: 
1. What is blocking it ? 
2. What are the risks (would it break anything or cause backward incompatibilites)
2. Is it still a critical issue, or we can close this and pursue it again after 1.0 ?

**Comment by mandarjog** [comment]
Yes we should get this in before 1.0. We cannot go out with faith based validation.

Plan
1. If e2e-test is using 1.9 alpha with mutating webhooks, Both pilot and mixer webhooks should be part of the standard test deployment package. That way there are e2e tests for them.
2. Add a flag to enable or disable referential integrity check.
3. Add `istioctl validate`  subcommand to enable CI/CD validation of config. At this time, it will directly call the mutating webhook and later on it will transition over to calling Galley if it makes sense.

**Comment by mandarjog** [comment]
@jmuk this code makes changes to pkg/runtime which is scheduled to be sunset.
Please move it to pkg/runtime2

Thanks.

**Comment by kyessenov** [comment]
If you have two configs A and B that depend on each other but together are
invalid, and they arrive in different orders to different Mixers/Pilots,
which one stays valid?

**Comment by jmuk** [comment]
@kyessenov 
I don't think current config structure is that complicated. But theoretically if such thing happens, then both will be rejected because;
- mixer1 receives A first, says it valid, and then sees B. it rejects B (it remembers the validated A in a cache)
- similarly mixer2 says B is valid, but rejects A.
- k8s apiserver aggregates the result, and both A and B look invalid since at least one webhook says invalid.

**Comment by kyessenov** [comment]
Thanks @jmuk . I was thinking in terms of pilot configuration constraints. We have a list of strings in configs that should not overlap. That means you have to pick a winner or not pick either of them. The problem with invalidating both is that it is allowing interference between authors. I can invalidate your config by sending my config that happens to collide.

**Comment by jmuk** [comment]
@kyessenov Not sure I got what you meant for the last sentence. Correct me I'm wrong.

It would be possible that someone malicious interferes normal config edits by intentional collides, as you pointed out. But to do so, the attacker needs to have the write access to the config entities (i.e. they are the cluster admin or istio operator). So that's kinda access control problem, and I believe that's addressed by rbac properly.

Also, if the attacker has the write access, anyways the attacker can overwrite any configs, they don't have to seek the chance of interfering.

**Comment by kyessenov** [comment]
My concern is that the "hosts" field in routing config does not align with
the regular scoping domains for RBAC. I don't think a single role for the
cluster operator is viable. E.g. config in different namespaces can
reference the same hosts, and there's an inherent conflict between them.

**Comment by jmuk** [comment]
I'm still confused. Let me make a bit more specific:
- there's a pilot1 in ns1, and pilot2 in ns2.
- pilot1 has a route rule (say it as configA.ns1), also pilot2 has configB.ns2. Both actually specify rules on a namespace, say ns3.
- each config looks sane by itself, should control ns3 effectively. However, they are contradicting each other; configA.ns1 does not make sense with configB.ns2 and vice versa.
- if configA.ns1 already exists, adding configB.ns2 would be invalid, should be rejected, and that's fine.
- similarly, rejecting configA.ns1 would be fine given configB.ns2 exists.
- however, rejecting both wouldn't be good, since effectively there're no rules in the cluster.

Under this situation, rejecting both would be okay if those config operations are done by human operators, since they can resolve the conflict manually. The problem happens because those configs are created automatically, like as a reaction to pod changes. Is that the case?

If that's the case, it is very hard for me and I don't have solution right now. Maybe some application specific logic needs to be implemented, like retrying as long as everyone is rejected. Another idea would be deferring to some entity (like the upcoming galley) for the decision and coordination.

Anyways, I don't think those type of concerns aren't directly related to this PR, because this implements the validation logic specific to Mixer.

**Comment by kyessenov** [comment]
@jmuk what you described is a difficult problem, and I had in mind is something even easier. It's one pilot, two configs in the same namespace / two namespaces that conflict with each other (e.g. because they are trying to claim the same host "google.com"). If the configs are auto-generated, then there is no guaranteed ordering, and it's up to a chance which one is effective, or whether either is effective at all.

Invalidating them together is also strange, if you have three configs: A, B, C such that {A,B} are conflicting and {B, C} are conflicting. Then you can invalidate either pair, and you end up with either C or A, randomly.

**Pull request merged**
