### PR TITLE
[helm/subcharts] Allowing customization of subchart image names

### PR DESCRIPTION
**Pull request by marcostvz**
There are some hard-coded image names, this PR allows to customize them if needed.

### CODE REVIEW

**Comment by sdake** [comment]
We have had alot of debates in the community around permitting the customization of image names.  I don't have a strong feeling on this topic, but others do (I believe @nmittler ?)

Cheers
-steve

**Comment by linsun** [comment]
What is the user case for customizing it?  

We already expose the Values.global.proxy.image for proxy as we allow folks to have their own envoy.

**Comment by marcostvz** [comment]
In our case, we have one customer that requires us to have all the docker images in their registry. Also, in their registry we cannot nest images (as registry/istio/image) so we have to prepend all istio images with `istio-`.  The reason to prepend that is to avoid collision with other images with the same name.

**Comment by linsun** [comment]
@marcostvz thanks, makes sense

/lgtm

**Comment by linsun** [comment]
@ostromart pls speak up if you feel strongly against this.  I think it is good to offer this flexibility plus we have pushed all these detailed config nobs to subchart now.

**Comment by marcostvz** [comment]
Hey @linsun, I switched default value of kubernetes image to global values.yaml to avoid errors on the tests. Could you be so kind of taking a look and enabling tests again? Thanks! :)

**Pull request closed without merging**
