### PR TITLE
Bring the install in line with current pilot and istioctl. 

### PR DESCRIPTION
**Pull request by costinm**
This is needed if the new istioctl is used.

Unfortunately the change is not backward or forward compatible - IMHO the right 
solution is to fix istioctl and config loading or revert the change - but this PR will get
the istio/istio work again with current istioctl.

```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
verified c09e19c7205fa36b7e8e9d9966cff08b84fe8f2f is recent pilot
/lgtm
but I think the routing rules are broken so it won't pass/land with that pilot/mixer combo

**Comment by costinm** [comment]
How do you suggest we proceed ? Force it ? Wait until we fix the rules ?

**Comment by kyessenov** [comment]
Deflake the test. Route rules seem to work locally, so it's either a flake or something is in the cluster.

**Comment by kyessenov** [comment]
No forcing please.

**Comment by rshriram** [comment]
Please wait. I am almost done with my PR. This one has no docs, no comments on the variable values..

**Comment by kyessenov** [comment]
@rshriram this is just to bring sanity. improvements to defaults come later.

**Comment by kyessenov** [comment]
Passed locally at SHA fe18026

**Comment by andraxylia** [comment]
Updated the branch to pick up RBAC fixes.

**Comment by douglas-reid** [comment]
this passes on my local cluster with rbac:


```
$ tests/e2e.sh --rbac_path=install/kubernetes/istio-rbac-beta.yaml --auth_enable
...
****************************************************
Tests Summary
PASSED: //tests/e2e/tests/mixer:go_default_test
PASSED: //tests/e2e/tests/bookinfo:go_default_test
```

**Comment by ldemailly** [comment]
we merged this despite rbac errors because it's better anyway and the rbac issue is solved or tracked in ... ?

**Comment by andraxylia** [comment]
istio/istio#769 should fix all rbac errors.

**Pull request merged**
