### PR TITLE
Concurrent optimization addSecret

### PR DESCRIPTION
**Pull request by RachaelLuo**
Signed-off-by: yipping.luo <yinping.luo@daocloud.io>

**Please provide a description of this PR:**
Concurrent optimization addSecret

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by RachaelLuo** [comment]
@kebe7jun cc

**Comment by SpecialYang** [comment]
Can't understand why we need the parallel mode. There is no block operation.

**Comment by RachaelLuo** [comment]
> Can't understand why we need the parallel mode. There is no block operation.

frist, The network is unreliable，previous time-consuming calculation formula was (n1 n2 n3 n4), and now the time-consuming calculation formula is max(n1,n2,n3,n4), which reduces the time complexity from O(n) to O(1)

second, I used chan

**Comment by RachaelLuo** [comment]
> Where is the "network calls" in this function?
> 
> Can you provide real world data suggesting this improves performance? its not clear to me it would.

Sorry, I was wrong

**Pull request closed without merging**
