### PR TITLE
[Ansible Installer] Updating Kiali Installation, Fixes #9519

### LINKED ISSUE #9519: [Ansible Installer] Kiali is being installed twice.
**Describe the bug**

- Since https://github.com/istio/istio/pull/9084, Kiali is part of the default files.  So if it is executed `ansible-playbook main.yml -e '{"istio": {"delete_resources": true, "addon": ["kiali"]}}'` as the documentation states on https://preliminary.istio.io/docs/setup/kubernetes/ansible-install.html, Kiali would be installed twice (one because of the default value and second one because of addon enabled"

I have tested on 1.1.0-snapshot.2 and faced that situation.

**Expected behavior**
- Kiali should be installed just once.

**Steps to reproduce the bug**
- Download 1.1.0-snapshot.2 
- Execute `ansible-playbook main.yml -e '{"istio": {"delete_resources": true, "addon": ["kiali"]}}'`

**Version**
- 1.1.0-snapshot.2

### PR DESCRIPTION
**Pull request by gbaufake**
Hello Everyone,

This PR fixes #9519 (kiali was installed twice because is enabled as default on ansible installer)

cc @gyliu513 @sdake @jmazzitelli, @ymesika 

Best Regards,
Guilherme Baufaker Rêgo

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@gbaufake using the retest command does not restart the circleCI tests - it only re-runs the prow tests.
We need someone on the istio hackers group to re-run those tests (I do not have permissions).

**Comment by gbaufake** [comment]
@linsun 
Can you merge it?

**Comment by linsun** [comment]
I'd prefer you get the required circleci tests passing - could you try rerunning it?

**Comment by linsun** [comment]
@gbaufake you can just rerun the failed test in circle CI:  https://github.com/istio/istio/wiki/Working-with-CircleCI

retest will trigger rerun all of your passed tests in prow and it only works for prow based tests :-(

**Comment by linsun** [comment]
and only the required tests :)

**Comment by gbaufake** [comment]
@linsun 
I think I don't have permissions to run just the failed tests on CircleCI

**Comment by linsun** [comment]
@gbaufake hmm, you should have.  I checked you are already in istio hackers group.  You need to make sure you connect/login with your GitHub id when looking at your circle CI failed test.

**Comment by gbaufake** [comment]
@linsun I didn't think the failures it is related to this PR specifically. Can you check what do I need to do to make the tests pass it.

**Comment by linsun** [comment]
ok, all required tests have passed, congrats!!

**Pull request merged**
