### PR TITLE
Use distroless multi-arch image for proxyv2

### PR DESCRIPTION
**Pull request by ecliptik**
Address https://github.com/istio/istio/issues/26652 by using a multi-arch distorless images and making the `COPY` architecture agnostic. Doesn't fully solve the issue of multi-arch building, but it's a start.

A similar patch was used to build multi-arche amd64/arm64 images here: https://github.com/istio/istio/issues/21094#issuecomment-702429990

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X ] Test and Release
[ ] User Experience
[X ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ecliptik** [comment]
@googlebot I signed it!

**Review by howardjohn — APPROVED** [review]
/ok-to-test

**Comment by ecliptik** [comment]
Test **integ-distroless-k8s-tests_istio** is failing with an error `iptables-restore v1.6.1: unknown option "--dport"` in the *istio-init* container in the  *a-v1*, *b-v1*, *multiversion-vistio*, and *headless-v1* pods.

Prow logs,

- https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27700/integ-distroless-k8s-tests_istio/13979/artifacts/security-ee4974ea08f94bf3a637c0/TestReachability/_test_context/reachability-1-94171-state201945898/cluster-0/a-v1-dcc9ffc75-xbcgk_istio-init.log
- https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27700/integ-distroless-k8s-tests_istio/13979/artifacts/security-ee4974ea08f94bf3a637c0/TestReachability/_test_context/reachability-1-94171-state201945898/cluster-0/multiversion-vistio-c4c7f77d7-dvqzs_istio-init.log
- https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27700/integ-distroless-k8s-tests_istio/13979/artifacts/security-ee4974ea08f94bf3a637c0/TestReachability/_test_context/reachability-1-94171-state201945898/cluster-0/headless-v1-6cd9d784f5-l98hr_istio-init.log

Looking into the reason why this would happen as the changes a minor and comparing a container build from `master` and one from this PR show the same files under `/usr/lib/x86_64-linux-gnu/`. The version of iptables is the same (`1.6.1-2ubuntu2`) as well. Seems like it may be related to Docker networking after some initial searches.

Example error from an `istio-init` container log.

```
iptables-restore --noflush /tmp/iptables-rules-1601680477199687860.txt343480718
iptables-restore v1.6.1: unknown option "--dport"
Error occurred at line: 6
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-save 
# Generated by iptables-save v1.6.1 on Fri Oct  2 23:14:37 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Fri Oct  2 23:14:37 2020
panic: exit status 2

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x4a7f020, 0x2ca983d, 0x10, 0xc00129ee60, 0x2, 0x2)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc00183fd70, 0x7fa636ff2e01, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:554 +0x38a
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc00183fd70)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:561 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc00183fd70)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:499 +0x2b7b
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x4a1f3a0, 0xc0007a8c00, 0x0, 0x10)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:58 +0x150
github.com/spf13/cobra.(*Command).execute(0x4a1f3a0, 0xc0007a8b00, 0x10, 0x10, 0x4a1f3a0, 0xc0007a8b00)
	github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x4a1f640, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:497 +0x31
```

**Comment by ecliptik** [comment]
Closing out bad rebase for PR.

**Pull request closed without merging**
