### PR TITLE
Include debug/authenticationz in pilot dump output

### PR DESCRIPTION
**Pull request by yangminzhu**

### CODE REVIEW

**Comment by mandarjog** [comment]
@Tahler this is changing the same file that you did yesterday, can you take a look?

**Comment by Tahler** [comment]
Yes I effectively did the first part of your changes yesterday. For consistency, @yangminzhu, could you cherrypick [f622e9ce38b5c084f245f3e13d1c07dfae47b488](https://github.com/istio/istio/commit/f622e9ce38b5c084f245f3e13d1c07dfae47b488) from the release-1.0 branch, which moves the script to tools/ (and tools/ gets copied to the archive)?

**Comment by yangminzhu** [comment]
@Tahler Thanks for doing this, I'm not sure how will we merge `release-1.0` back to `master`, probably someone will merge it back to `master` manually once it's closed. I cherrypicked @Tahler's change and this shouldn't introduce any conflict later when we merge `release-1.0` back to `master`.

**Pull request merged**
