### PR TITLE
Update proxy SHA for build 1.2.3

### PR DESCRIPTION
**Pull request by fpesce**
Please provide a description for what this PR is for.
Update Envoy / Proxy for 1.2.3

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by fpesce** [comment]
Attempt at triggering CircleCI by closing/opening PR

**Comment by howardjohn** [comment]
didn't you already build 1.2.3?

**Pull request closed without merging**
