### PR TITLE
Leverage docker default seccomp policy for istio init container

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

related: #4500

### CODE REVIEW

**Comment by cmluciano** [comment]
@thoraxe Can you try this out and see if it works for #4500? 

I just noticed this added into the [istio addon in k8s](https://github.com/kubernetes/kubernetes/commit/a8a24849c02fc85e0e6f8873a80f78d38a3f104d)

**Comment by cmluciano** [comment]
I'm not sure if the failures are related to my change or not @andraxylia @ZackButcher

**Comment by andraxylia** [comment]
Can you try to put a /hold and rebase on top of release-1.0 ? The tests are not flaky there.

**Comment by andraxylia** [comment]
The tests that failed are TestTLSMultiplexing, I am not familiar with it the author no longer works on Istio, but that test is not required. If the required tests pass, you should be able to merge.

**Comment by andraxylia** [comment]
I would like this fix in 1.0.1 anyway @costinm wdyt?

**Comment by douglas-reid** [comment]
Attempting to unblock.

/lgtm

**Comment by ZackButcher** [comment]
Is this still relevant today in light of work happening by @tiswanso et al?

Otherwise, the failures look unrelated, and a rebase and re-push should kick circleci and get the PR moving.

**Comment by cmluciano** [comment]
@ZackButcher I think it's still relevant depending on how long we want the enhancements to pod-controller or CNI plugins to bake. Regardless, I think the template might still be leveraged at some level of Istio config.

**Comment by cmluciano** [comment]
@ZackButcher @andraxylia closing since significant progress has been made on the CNI front

**Pull request closed without merging**
