### PR TITLE
Adding back envoy next to Istiod, part 1

### PR DESCRIPTION
**Pull request by costinm**
Option to run a sidecar/gateway alongside Istiod, as we did in 1.4 - but without the hardcoded 
envoy config. Instead it will use localhost and the certs generated by istiod.

Currently envoy will configure itself as a gateway - we may use this for 'tiny' deployments
of istio or tests, and as a separate gateway for control-plane components, possibly using 
internal load balancers. If someone choose to take advantage of this feature - the 'main' gateway will continue to be used for normal ingress, and the istiod-gateway can be used for control
plane or multi-network, without an external IP. 

In addition this mode will allow us to possibly do better load balancing. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by mandarjog** [comment]
When Istiod terminates connection after 15mins, will this envoy interfere with that lifecycle?

**Comment by howardjohn** [comment]
Yes, it will, see https://github.com/istio/istio/issues/11181

**Comment by costinm** [comment]
I'm not sure: AFAIK Envoy has or we can add a way to terminate a connection after some time. 
If it is a problem for Istiod load balancing connection - it would also be a problem for any other server handling long-lived connections.

So we should check with @PiotrSikora  and envoy people if it is already possible, if not it shouldn't
be extremely hard. 

In addition we should be able to solve the problem WITHOUT closing connections - the real issue
is that a Istiod will get too many connections. Envoy has circuit breakers - it is a bit more complicated setup, but no different from what we would use with the normal Gateway and non-istiod applications that handle long-running connections. Again - if it is a problem that envoy can't handle, we should fix envoy so all apps benefits instead of a istio specific hack.

**Comment by costinm** [comment]
In other words: 
- backup plan: envoy terminates connections after 15 min, new setting if not already possible.

- backup plan 2: Pilot sends a 'Go away' message, possibly with the IP of another less loaded istiod. Envoy may need to change to support this - or if we use agent as a proxy we can handle it without envoy changes 

- my preference (maybe in 1.8): the gateway will forward to 2 clusters, localhost and 'all other istiod'. For the second cluster we may need a second port ( that goes only to localhost ) to avoid loops.

**Comment by mandarjog** [comment]
Http protocol options supports max_connection_duration  and max_stream_duration   Which I think will work.

**Comment by jwendell** [comment]
@costinm is this something you had in mind for 1.7? Branch cut happens tomorrow.

**Pull request closed without merging**
