### PR TITLE
ambient: remove baggage in waypoints

### PR DESCRIPTION
**Pull request by kyessenov**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by zirain** [comment]
move to MDS?

**Comment by kyessenov** [comment]
@zirain Yes, it was using WDS for upstream already, so this makes it use for downstream as well and eliminate the requirement to send baggage.

**Review by zirain — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
@kyessenov do we need a feature flag here for safety

**Comment by kyessenov** [comment]
@hzxuzhonghu Ambient is all alpha/experimental so there's no expectation of full compatibility.

**Review by bleggett — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]
agreed

**Pull request merged**
