### PR TITLE
Fix racetest failures in fluentd test  [release-1.0]

### LINKED ISSUE #11612: Racetest failure: istio.io/istio/mixer/adapter/fluentd TestHandleLogEntry
https://gubernator.k8s.io/build/istio-circleci/racetest/319930
```
==================
WARNING: DATA RACE
Read at 0x00c420128148 by goroutine 90:
  istio.io/istio/mixer/adapter/fluentd.TestHandleLogEntry.func1()
      /go/src/istio.io/istio/mixer/adapter/fluentd/fluentd_test.go:357 +0x580
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d

Previous write at 0x00c420128148 by goroutine 91:
  istio.io/istio/mixer/adapter/fluentd.(*mockFluentd).PostRawData()
      /go/src/istio.io/istio/mixer/adapter/fluentd/fluentd_test.go:458 +0x73
  istio.io/istio/mixer/adapter/fluentd.(*handler).postData()
      /go/src/istio.io/istio/mixer/adapter/fluentd/fluentd.go:206 +0x3de

Goroutine 90 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:824 +0x564
  istio.io/istio/mixer/adapter/fluentd.TestHandleLogEntry()
      /go/src/istio.io/istio/mixer/adapter/fluentd/fluentd_test.go:333 +0x1eda
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d

Goroutine 91 (running) created at:
  istio.io/istio/mixer/adapter/fluentd.TestHandleLogEntry.func1()
      /go/src/istio.io/istio/mixer/adapter/fluentd/fluentd_test.go:344 +0x3e8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d
==================
env.go:117: Got a new log for fluentd, name Foo
env.go:117: Got a new log for fluentd, name Foo
testing.go:730: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by ymesika**
Fixes #11612

/assign @ozevren

### CODE REVIEW

**Comment by ymesika** [comment]
Lint fails on unrelated files

**Comment by ozevren** [comment]
@mandarjog @geeknoid PTAL

**Comment by ozevren** [comment]
@mandarjog @geeknoid PTAL and lgtm as appropriate.

**Comment by ymesika** [comment]
Not stale

**Comment by ozevren** [comment]
@ymesika Can you fix the linter issue?

**Comment by ymesika** [comment]
@ozevren lint fails on this branch on unrelated issues

**Comment by ozevren** [comment]
@mandarjog @douglas-reid Could one of you guys look/approve?
Also this is against 1.0. I am not sure what the policy is for checking against 1.0 branch.

**Pull request merged**
