### PR TITLE
istio.io is the proper place to document Helm usage

### PR DESCRIPTION
**Pull request by sdake**
This README.md doesn't have much if any useful information and is very dated.  Instead
of maintaining the Helm documentaiton in two places, lets maintain it in
one (https://istio.io).

### CODE REVIEW

**Comment by linsun** [comment]
do you think it is good to put a reference to istio.io in the readme.md, @sdake ?  else lgtm.

**Comment by sdake** [comment]
@linsun yes that is a great idea - I will push an update to this PR in the next 15 mins.

Cheers
-steve

**Comment by sdake** [comment]
@linsun I know its the weekend (so no rush) and you are probably aware of this change to how the bot works with /lgtm, but (in case you aren't) could you apply /lgtm to this patch?

See this thread:
https://groups.google.com/d/msg/istio-dev/NQlIvIcK3ao/BIuJrwtBAwAJ

**Pull request merged**
