### PR TITLE
[release-1.15] fix empty endpoints weight for AUTO_PASSTHROUGH gateway

### PR DESCRIPTION
**Pull request by bincherry**
**Please provide a description of this PR:**

Manual cherrypick of #40243

This cannot be done by a bot because there are different struct names on the two branches, according to #40226 , which changes `LocLbEndpointsAndOptions` to `LocalityEndpoints` on master branch.

### CODE REVIEW

**Comment by bincherry** [comment]
It seems that something wrong with the arm64 testing. Need some help please.

**Comment by zirain** [comment]
cc @howardjohn arm64 is supported on v1.15?

**Review by dhawton — APPROVED** [review]

**Pull request merged**
