### PR TITLE
run make gen

### PR DESCRIPTION
**Pull request by jacob-delgado**
**Please provide a description of this PR:**

Uses latest build tools

### CODE REVIEW

**Comment by jacob-delgado** [comment]
Need approvals before I can merge in https://github.com/istio/test-infra/pull/5407

**Review by howardjohn — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
```
-	file_zdsapi_zds_proto_msgTypes[7].OneofWrappers = []any{
+	file_zdsapi_zds_proto_msgTypes[7].OneofWrappers = []interface{}{
```

**Comment by hzxuzhonghu** [comment]
Does this mean the tool ci used is not updated yet

**Pull request merged**
