### PR TITLE
bookinfo: add service accounts to the default deployment.

### PR DESCRIPTION
**Pull request by yangminzhu**

### CODE REVIEW

**Comment by yangminzhu** [comment]
@fpesce @liminw We will need this for `1.2`, This is blocking istio.io PR: https://github.com/istio/istio.io/pull/4320

**Comment by yangminzhu** [comment]
@frankbu, @rshriram,  @vadimeisenbergibm, @venilnoronha, Could you take a look? Thanks.

**Comment by yangminzhu** [comment]
ping, this is needed for 1.2

**Comment by rlenglet** [comment]
This PR broke links in the docs, to https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/bookinfo-add-serviceaccount.yaml and https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/rbac/ratings-v2-add-serviceaccount.yaml.

**Comment by yangminzhu** [comment]
@rlenglet Thanks, I sent out another PR to update the link for zh: https://github.com/istio/istio.io/pull/4429

**Pull request merged**
