### PR TITLE
validation: respect unsafe regex config in regex validation

### PR DESCRIPTION
**Pull request by ramaraochavali**
This PR https://github.com/istio/istio/pull/18539 added validation for regex > 100 chars. But Pilot has env var support that can be used to turn off safe regex. For non galley use cases, this flag should be considered during validation.

### CODE REVIEW

**Comment by howardjohn** [comment]
lgtm if @istio/wg-config-maintainers confirm there aren't any subtle problems that may arise due to having the underlying validation to change as configuration is changed. Given we are already changing validating in version upgrades, I do not think this is any worse.

**Comment by ramaraochavali** [comment]
@howardjohn Can we merge this as we are blocked on upgrade because one of our important services has the regex with more than 100 bytes long?
If we need any further changes I can do as follow-up?

@istio/wg-config-maintainers  Any concerns?

**Comment by ramaraochavali** [comment]
@howardjohn  Thanks !

**Comment by ayj** [comment]
Does pilot validate configuration itself? I thought it relied on Galley to handle validation. What happens if a pilot with unsafe_regex=0 tries to process a regex with len > 100? 

Is this unsafe_regex change temporary or permanent? This isn't a pattern we want to endorse or support long term. If conditional validation is required long term we need to reflect that in a proper API and not an envvar.

> Given we are already changing validating in version upgrades, I do not think this is any worse.

Changing validation isn't great unless we're relaxing constraints. I suspect this hasn't been so much a problem because any restrictions we do add are likely fixing underlying bugs anyway.

**Comment by howardjohn** [comment]
> unsafe_regex=0 tries to process a regex with len > 100

the config is rejected by envoy 

This flag is intended for backwards compatible purposes, and is a one way migration from set to unset. The flag will be removed soon (maybe even 1.5?)

**Comment by ramaraochavali** [comment]
@howardjohn Looking at this more closely, I do not know whether we need a validation at all.  [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/type/matcher/regex.proto#type-matcher-regexmatcher-googlere2) say, either regex can be rewritten or length can be specified. The think the point in Envoy deprecation was more about `std::regex` vs google's `re2` regex - as `std::regex` is unsafe. If I read the Envoy docs, it did not occur to me length was a problem. We just have to specify the length if need more than 100 and that is supported.

So I guess, from our perspective, when using safe regex
- We should set the length of regex as `max_program_size` when building Google Re2 regex matcher here https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L591 and else where this is constructed
- Remove length validation.

WDYT? Am I missing any thing here?

**Comment by howardjohn** [comment]
Yeah I guess that works, we could just hard code it to 1024 (which was the
old max) as well if that's easier. Good catch

**Comment by ramaraochavali** [comment]
> we could just hard code it to 1024 (which was the old max) as well if that's easier

Yes. That is definitely easier. Where did we configure 1024 earlier?

**Comment by howardjohn** [comment]
The default (or only? not sure it was configurable) was 1024 for the old unsafe regex, and we have no validation before

**Pull request merged**
