### PR TITLE
fix gateway cluster race

### PR DESCRIPTION
**Pull request by ramaraochavali**
For #4 in https://github.com/istio/istio/issues/29131

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@howardjohn It may be difficult to add a test case for this. Can you Please review this?

**Comment by ramaraochavali** [comment]
re reading the thread https://github.com/istio/istio/issues/29310#issuecomment-740224564 - I doubt this will fix it. I also think this is not specific to `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` this flag. Even if we add a new cluster and VS that references that cluster we will run in to the same issue. Here in this specific test case, it working by disabling `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` is because we are sending all clusters in the beginning and nothing is added after that.

I suspect this is a race in Envoy not in Pilot because we send the clusters first and then routes.

So we should not tie that issue with this flag? @howardjohn  Since you did the original analysis  did you find that we are sending routes before clusters by any chance?

**Comment by howardjohn** [comment]
>  I also think this is not specific to PILOT_FILTER_GATEWAY_CLUSTER_CONFIG this flag. Even if we add a new cluster and VS that references that cluster we will run in to the same issue.

Yes, its technically not. However, in practice it typically is. Consider the starting state: User has Svc A and route points to A. If a user creates a service B and switches the route pointing to B *immediately*, its their fault it doesn't work - the pod's behind service B may not even be running yet so even if envoy/istio were perfect they would get downtime. They need to sequence it. If they don't have filter gw, and they wait for service B to be ready *then* update the route, it works fine. Note this is exactly what knative does extensively and what the original issue came from.

With filter gw, its worse. The user can already have svc B running, wait for it to be ready, etc. then switch the route and get 503s. That shouldn't happen. The only way a user could work around it is to create some dummy route referencing B such that the cluster is created, then switch the real route - which is bad UX and shouldn't be required.

> I suspect this is a race in Envoy not in Pilot because we send the clusters first and then routes.

Yes, I think the cluster is stuck warming and/or not processed+ACKed before we send the route. One fix may be to wait for cluster ACK before we send route, but that has its own issues

**Comment by ramaraochavali** [comment]
> I think the cluster is stuck warming

I think this is what was happening because by the time cluster warmed and thread local clusters are created on workers, routes might have updated .

**Comment by ramaraochavali** [comment]
I will close this as this is not going to solve the prolbem.

**Pull request closed without merging**
