### PR TITLE
Gateway IPv6: Third time's the charm

### PR DESCRIPTION
**Pull request by keithmattix**
**Please provide a description of this PR:**
I found the issue (for real this time); `net.SplitHostPort` if ipv6 addresses aren't enclosed in brackets: https://go.dev/play/p/8T7qP72hAlp. I wrote a fix and pointed this PR to it to confirm it works

**EDIT**: This is now ready for approval. I also kept Gateway conformance tests as part of the presubmit because I feel like they're another category of traffic tests. Happy to change it though if folks have strong opinions

### CODE REVIEW

**Comment by keithmattix** [comment]
> Hi @keithmattix, basically, `host + port` is a `socket address`, and it's different with the `ip address` itself. However, this should be an issue of `net.SplitHostPort`.

net.SplitHostPort requires brackets according to the [docs](https://pkg.go.dev/net#SplitHostPort): 
> A literal IPv6 address in hostport must be enclosed in square brackets

We should abide by it

**Comment by keithmattix** [comment]
@ericvn I don't notice a ton of difference, but I can remove the GatewayConformance from presubmit if there are concerns

**Review by ericvn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
