### PR TITLE
istioctl: add revision shortcode for analyze

### PR DESCRIPTION
**Pull request by my-git9**
**Please provide a description of this PR:**

It's good to add a shortcode for the revision of `istioctl analyze` like other place, and there are no other parameters to confuse it here.

### CODE REVIEW

**Review by hanxiaop — COMMENTED** [review]
We do have a recursive flag with `-R`, and IMO mixing lowercase and uppercase short flags can lead to confusion, although it seems other installation related commands already use `-r`.

**Review by MorrisLaw — COMMENTED** [review]
@hanxiaop do you think it makes sense to consider removing the `-R` flag for recursive and add the `-r` for revision here? It's inconsistent and confusing to not have that `-r` shorthand when it seems like all of the other `revision` commands have it. It'd be a more uniform UX to change it imo.

At the same time, I'm not sure of the precedent of removing an existing shorthand and if that is too disruptive. And if it is we should just leave it as is.

In either situation, I agree that a case sensitive short hand is bad UX and isn't really an option.

**Comment by hanxiaop** [comment]
> do you think it makes sense to consider removing the -R flag for recursive and add the -r for revision here?

@MorrisLaw This makes sense to me, as you said it provides a more consistent UX for the revision flag across commands. 

Since this flag only affects file-based recursive analysis, it shouldn’t be a big problem. I'd also prefer to change `-R` to something else as long as we cover it in the release notes, and probably add an arg validation to indicate that it has been moved to another flag instead of reporting the unknown flag error.

**Comment by bleggett** [comment]
> > do you think it makes sense to consider removing the -R flag for recursive and add the -r for revision here?
> 
> @MorrisLaw This makes sense to me, as you said it provides a more consistent UX for the revision flag across commands.
> 
> Since this flag only affects file-based recursive analysis, it shouldn’t be a big problem. I'd also prefer to change `-R` to something else as long as we cover it in the release notes, and probably add an arg validation to indicate that it has been moved to another flag instead of reporting the unknown flag error.

Should be a separate PR if we remove `-R` IMO.

Looking at the `recursive` flag, I think it should be dropped anyway, for template analysis we should mimic the UX of `helm lint` and Helm in general, which do not do this or have this flag.

(they simply lint all templates in the current chart, and there's an optional flag to lint subcharts as well, there is no other general concept of "recursion" there because it's not needed).

**Comment by MorrisLaw** [comment]
> > > do you think it makes sense to consider removing the -R flag for recursive and add the -r for revision here?
> 
> > 
> 
> > @MorrisLaw This makes sense to me, as you said it provides a more consistent UX for the revision flag across commands.
> 
> > 
> 
> > Since this flag only affects file-based recursive analysis, it shouldn’t be a big problem. I'd also prefer to change `-R` to something else as long as we cover it in the release notes, and probably add an arg validation to indicate that it has been moved to another flag instead of reporting the unknown flag error.
> 
> 
> 
> Should be a separate PR if we remove `-R` IMO.
> 
> 
> 
> Looking at the `recursive` flag, I think it should be dropped anyway, for template analysis we should mimic the UX of `helm lint` and Helm in general, which [do not do this or have this flag](https://helm.sh/docs/helm/helm_lint/).
> 
> 
> 
> (they simply lint all templates in the current chart, and there's an optional flag to lint subcharts as well, there is no other general concept of "file recursion" there because it's not needed).
> 
> 
> 
> Our templates are/should be valid Helm charts IMO, and we should operate on them as such, I don't see much point in supporting arbitrary nonstandard-Helm template nesting in `istioctl analyze`.
> 
> 
> 
> IMO we should just drop `-R` and hardcode recursion to `true`.

Yeah, that's a good point about Helm.

**Comment by my-git9** [comment]
What should I do with this PR? @hanxiaop @MorrisLaw @bleggett

**Comment by MorrisLaw** [comment]
> IMO we should just drop `-R` and hardcode recursion to `true`.

@my-git9 you dropped `-R` but did you also plan on hardcoding recursion to `true` based on Ben's suggestion?

And as far as this PR, refactoring to include the shortcode `-r` makes sense. We should probably add a release note for the addition of this shortcode. 

Also, maybe consider adding arg validation in this PR or a separate to inform ppl that `-R` is no longer a valid command per @hanxiaop's suggestion.

**Comment by my-git9** [comment]
> Thank you @my-git9 for adding the release note. Made a typo comment.
> 
> Can you address @hanxiaop's comment as well, to `add an arg validation to indicate that it has been moved to another flag instead of reporting the unknown flag error.`

Updated, PTAL, thanks

**Review by MorrisLaw — CHANGES_REQUESTED** [review]
Just update that typo in the release note. And it should be good to go.

**Review by MorrisLaw — APPROVED** [review]

**Pull request merged**
