### PR TITLE
control operator replica sets history

### PR DESCRIPTION
**Pull request by tareksha**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Can you explain why?

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by litong01 — APPROVED** [review]
Changes look good to me. The changes keep the behavior the same if not using this new configuration parameter.

**Review by jacob-delgado — APPROVED** [review]
You aren't changing defaults, but allowing users to specify. LGTM.

**Pull request merged**
