### PR TITLE
make use of go generics to remove MostSpecificHostMatch2

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@hzxuzhonghu I thought the decision was not to add any generics code in production code https://github.com/istio/istio/issues/36308#issuecomment-1190847116 (only tests should be allowed)?

**Comment by hzxuzhonghu** [comment]
Thanks for that info, so we can wait until generics is stable

**Comment by howardjohn** [comment]
:+1:, Go 1.19 is coming out in a couple weeks so we can pick this up then

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
