### PR TITLE
disable EnvoyFilter by default for telemetry

### PR DESCRIPTION
**Pull request by howardjohn**
This PR replaces EnvoyFilter with native code for Telemetry when there are no overrides.

followups: once https://github.com/istio/istio/pull/43501 merges, add warnings if overrides are used

Design https://docs.google.com/document/d/1FMvwyoooGeiACf9b7R0A6iJyB6ZuiP7hv5-XDmXtHLo/edit#

cc @zirain @kyessenov for the high level idea.

### CODE REVIEW

**Comment by zirain** [comment]
this's what I want, repalce stats EnvoyFilter with Telemetry API.
BTW, we should mention the risk about using [MetricDefinition](https://github.com/istio/api/pull/2661) with EnvoyFilter.

**Comment by zirain** [comment]
I have an immature idea in https://github.com/istio/istio/issues/39772#issuecomment-1183844295, which seems simpler?

**Comment by howardjohn** [comment]
I specifically do not want any Envoyfilters installed at all, not just not applied, for performance and confusion reasons. EnvoyFilter is considered "highly alpha and not stable" and we discourage it, yet we use it ourselves which is a bad message.

**Review by GregHanson — APPROVED** [review]
release note looks good

**Comment by kyessenov** [comment]
Can something be done about the logic in helm? That's unmaintainable, and we cannot get it to the finish line after this because we also need to convert the content from helm to Telemetry API.

**Comment by howardjohn** [comment]
@kyessenov my intention was that normal users never need to change their config (i.e. we keep the logic, but it will simplify to just prometheus.enabled instead of all the overrides), and configOverrides would be deprecated (start warning in 1.18, remove in 1.19).

For the overrides we will never automatically support them like this, users will need to manually migrate to Telemetry API. I expect (or hope?) this is a pretty uncommon field (?)

WDYT?

**Comment by kyessenov** [comment]
AFAIK Google used overrides for a long time, and users rely on them to control the size of metrics (e.g. auto trader).

Why is it hard to migrate to telemetry API? The config is the same at Envoy level.

**Comment by howardjohn** [comment]
I am not sure I understand what you are proposing. Given configOverride can configure ~anything, and we don't expose it all in Telemetry, I am not sure how we could transparently create Telemetry for users. I am also not sure we *want* to create Telemetry for users. For a past analogy, we used to have an install helm flag enableMTLS and migrated users to explicitly create PeerAuthn

**Comment by kyessenov** [comment]
@howardjohn There's a discussion here https://github.com/istio/istio/issues/37645.

I think we need to do better than handle the common case:
1. Provide a tool to convert from helm to telemetry API. This might be the first instance for a variety of API migration tasks (to Gateway, to Ambient, etc).
2. Graduate telemetry API to beta. It'd send a wrong signal to replace a stable API (EnvoyFilter) with something alpha by default.

**Comment by howardjohn** [comment]
> 1. Provide a tool to convert from helm to telemetry API. This might be the first instance for a variety of API migration tasks (to Gateway, to Ambient, etc).

My goal would be that most users (I am sure 99% do not touch the helm API) just get automatically moved to not using EnvoyFilters. I think that may be somewhat orthogonal to a conversion tool which I think would be to handle advanced cases we cannot auto-move?

> 2. Graduate telemetry API to beta. It'd send a wrong signal to replace a stable API (EnvoyFilter) with something alpha by default.

I generally agree but Envoyfilter is alpha as well. Also this PR doesn't technically use the Telemetry API

Overall sounds like we need some more discussion though, maybe be worth pulling a design doc together

**Comment by zirain** [comment]
there're features only supported by `EnvoyFilter`, what I could recall is https://github.com/istio/api/pull/2661.

**Comment by howardjohn** [comment]
> there're features only supported by `EnvoyFilter`, what I could recall is [istio/api#2661](https://github.com/istio/api/pull/2661).

They can use EnvoyFilter, this PR is to get the 99% of users that do not use those features off EnvoyFilter

**Comment by zirain** [comment]
this PR is too complex and unmaintainable.
IMO, for 99% users, a migration doc is enough.

**Comment by howardjohn** [comment]
We will never migrate all users (or even 1% of users) if we don't do it automatically IMO

**Review by jacob-delgado — APPROVED** [review]

**Comment by howardjohn** [comment]
I wrote up a small design doc: https://docs.google.com/document/d/1FMvwyoooGeiACf9b7R0A6iJyB6ZuiP7hv5-XDmXtHLo/edit#. We can discuss in the WG meeting if desired

**Comment by howardjohn** [comment]
We discussed this in the WG. The general consensus was that this was adding some complexity, but it was short term and the benefits were worth it long term: https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#bookmark=id.kek32e4qvyzy.

This is pending Environments WG but will give @zirain a chance to respond

**Comment by zirain** [comment]
> The general consensus was that this was adding some complexity.

I'm ok if this's a short term, this should be mentioned in the upgrade notes of v1.18.

**Review by zirain — APPROVED** [review]
open a ticket to track: https://github.com/istio/istio/issues/43910

**Pull request merged**
