### PR TITLE
Refactor Istio Dashboards to support larger meshes

### PR DESCRIPTION
**Pull request by douglas-reid**
The original Istio Dashboard provided a panel (and several charts) per service within the mesh, in addition to mesh-wide charts. This does not scale for meshes beyond trivial sizes.

In order to support medium-to-large meshes, this PR refactors the setup by introducing two new single service dashboards (one for TCP and one for HTTP/GRPC) and replacing the panels on the main dashboard with a table of service metrics.

To drill down to individual service dashboards, the "destination service" column in the tables provides a clickable-link for navigation purposes. The tables provides a scrollable set of 25 rows, with pagination for cases when there are more than 25 services.

A few notes:
- in preparation for the attribute update and service -> workload refactor, some of the advanced filtering features have been removed (dropdowns for source, version, etc.).
- the new service dashboards are bare-bones. follow-on PRs will be necessary to fully-flesh them out. that work is intended to be carried out in parallel to the client-side reporting and attribute change work.

Screenshots in action:

istio-mesh-dashboard
http-service-dashboard
tcp-service-dashboard

Reviewers:

- I have not verified image creation and e2e test passage yet. I wanted to put this out for comment before proceeding further.
- I am looking for feedback on overall approach and design. This was my first thought. Always open to better suggestions, etc.

### CODE REVIEW

**Comment by kyessenov** [comment]
Are there plans to change how source service is represented in the dashboards per service? Should it be using source workload?

**Comment by kyessenov** [comment]
Agree that several incremental steps are the right approach for the
dashboards work. I don't think this has any risk impact on the next release
or the other components.

**Comment by douglas-reid** [comment]
@kyessenov yes, there are plans to shift from workload to service, particularly as it relates to source.

**Comment by douglas-reid** [comment]
@geeknoid the dashboard tests all pass. Would you mind approving and merging (if there are no other objections) ?

**Pull request merged**
