### PR TITLE
fix mixed case host with tls redirect

### PR DESCRIPTION
**Pull request by ramaraochavali**
https://github.com/istio/istio/issues/49638

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### CODE REVIEW

**Review by keithmattix — APPROVED** [review]
LGTM

**Comment by briansonnenberg** [comment]
@ramaraochavali We need to add this fix to each supported version, right?

**Comment by keithmattix** [comment]
Yeah I was just about to ask; should we cherry pick this and the PR it's based on

**Comment by ramaraochavali** [comment]
yes. need to cherry pick to 1.23 and 1.24. The base fix is already in 1.22 and above

**Comment by mikemorris** [comment]
Looks like 1.22 and 1.23 will need manual cherrypicks @ramaraochavali - 1.24 has a few failing tests I'm rerunning now to see if they're just flakes or that needs additional work too.

**Comment by ramaraochavali** [comment]
1.22 is EOL. I will do manual cherry pick for 1.23

**Pull request merged**
