### PR TITLE
Update start_envoy.sh path

### PR DESCRIPTION
**Pull request by yutongz**
start_envoy.sh was moved in https://github.com/istio/proxy/pull/1140
Updating to match this changes

### CODE REVIEW

**Comment by ldemailly** [comment]
isn't this merged already in some other pr ? (by @mandarjog last night?)

/test istio-presubmit

**Comment by ldemailly** [comment]
I think the bot will repeatedly fail to update the sha so it needs to be done manually ? maybe do it in this pr ?

**Comment by mandarjog** [comment]
Make sense.

**Comment by nmittler** [comment]
@ldemailly it seems that we either need to simplify how to change the proxy image, add better docs, or both.  I'm having the same issue on https://github.com/istio/istio/pull/3690

**Comment by yutongz** [comment]
There some unit tests failing here, might be something to do with new proxy?

**Comment by mandarjog** [comment]
@qiwzhang 
0222 18:40:34.536] [2018-02-22 18:40:33.304][5502][error][config] src/envoy/utils/config.cc:61] Failed to convert mixer V2 client config, error: INVALID_ARGUMENT:transport.network_fail_policy: invalid value "FAIL_CLOSE" for type type.googleapis.com/istio.mixer.v1.config.client.NetworkFailPolicy, data: {"transport":{"networkFailPolicy":"FAIL_CLOSE"},"mixerAttributes":{"attributes":{"target.namespace":{"stringValue":"XYZ222"},"target.uid":{"stringValue":"POD222"},"mesh1.ip":{"bytesValue":"AQEBAQ=="}}}}

**Comment by yutongz** [comment]
This issue has been handled by https://github.com/istio/istio/pull/3693
/close

**Pull request closed without merging**
