### PR TITLE
Copy start_envoy and envoy.conf.template into istio/istio from proxy

### PR DESCRIPTION
**Pull request by yutongz**
fixes https://github.com/istio/istio/issues/4317

### CODE REVIEW

**Comment by ldemailly** [comment]
can you just put a header on both this file and the original one to reference each other
so someone knows to update both ?
(tricky part: what is a json comment?)

**Comment by ldemailly** [comment]
looks like you got the broken version:

```
[2018-03-20 01:16:33.796][11235][debug][main] external/envoy/source/server/server.cc:164] Unable to initialize config as v2, will retry as v1: Unable to parse JSON as proto (INVALID_ARGUMENT:cluster_manager: Cannot find field.): 
```

**Comment by yutongz** [comment]
/hold cancel 
Reviewer approved, all required tests passed.

**Pull request merged**
