### PR TITLE
Update the base image versions to latest for bookinfo sample

### PR DESCRIPTION
**Pull request by shamsher31**
Last updated year ago https://github.com/istio/istio/pull/16556.

Not upgraded python version to the latest `3.8.3` because of some dependency issues, it was failing locally.

Referenced https://github.com/istio/istio/pull/24304 for updating tag

### CODE REVIEW

**Comment by ericvn** [comment]
Looks like our base images are have vulnerabilities again. Wasn't expecting that to impact istio/istio PRs.

**Comment by shamsher31** [comment]
Thanks @ericvn , I believe this https://github.com/istio/istio/pull/24973 fixes vulnerabilities test failure. Any idea why integration test is failing ?

**Comment by ericvn** [comment]
@shamsher31 It looks to me like you've updated the yaml files to point to new images that don't exist yet. I'm not sure of the process here. Should one get the Dockerfile changes approved and merged and then a build and push of the images followed by another PR to update the yamls for the new images. @brian-avery, what did you do previously?

**Comment by brian-avery** [comment]
We don't have automated tooling for the bookinfo images. This means that the code for the bookinfo images needs to be reviewed, the images pushed to dockerhub, and then the tests ran before they will pass. @howardjohn updated the images for me.

**Comment by brian-avery** [comment]
Code changes *look* good to me, that said, there are quite a few library changes here. Can you provide a description of what testing you've done?

**Comment by ericvn** [comment]
I can push new images as well. @frankbu can as well, and mentioning here as BookInfo is used in the documentation.

**Comment by shamsher31** [comment]
I haven't performed a complete end to end test as I'm not aware how to do that, but I run `$ samples/bookinfo/src/build-services.sh docker.io 1.16.2` for the local build to make sure that it builds successfully and create tags. 

This was my assumption from @brian-avery PR
> Note that many tests expect the bookinfo images to already exist and the images do not get built in the pull request process. These tests will fail until the images exist.

Also While running `make test` I saw  `'istioctl-racetest' ` failure and couldn't figure out how to fix it. I thought might be some issue with my local builds.

**Comment by brian-avery** [comment]
What I did in my testing was: 

* Start up Istio with bookinfo
* Make sure that all three ratings pages load, this hits all services except for mongodb if I'm not mistaken. 
* Run make test which will run a lot of integration tests. 

It might also be good to run the automated istio.io tests as these will hit the documentation tests that cover Bookinfo.

**Comment by shamsher31** [comment]
@brian-avery @ericvn .
So I tried building images locally and pushed them to my [personal docker account](https://hub.docker.com/u/shamsher31) using.

```
$ ./build_push_update_images.sh 1.16.2 --prefix=shamsher31
``` 
And tried [bookinfo sample](https://istio.io/latest/docs/examples/bookinfo/) with custom pushed images.

All the pods are in running state except `producpage` which in `CrashLoopBackOff` state.
```
$ kubectl get pods
NAME                             READY   STATUS             RESTARTS   AGE
details-v1-844786c47b-fdgvv      2/2     Running            0          18m
productpage-v1-f44bfb5fd-p98lp   1/2     CrashLoopBackOff   7          18m
ratings-v1-dc5bcf7c6-fqsds       2/2     Running            0          18m
reviews-v1-7b7d4579c8-2nb69      2/2     Running            0          18m
reviews-v2-55658bfd7d-9rtpc      2/2     Running            0          18m
reviews-v3-5488b95dc4-mw9zp      2/2     Running            0          18m
```
So not able to test it further.

**Comment by shamsher31** [comment]
Pod log.

```
$ kubectl describe pod productpage-v1
Name:         productpage-v1-f44bfb5fd-vpx8h
Namespace:    default
Priority:     0
Node:         istio-testing-control-plane/172.21.0.2
Start Time:   Mon, 29 Jun 2020 17:34:20 +0530
Labels:       app=productpage
              istio.io/rev=default
              pod-template-hash=f44bfb5fd
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=productpage
              service.istio.io/canonical-revision=v1
              version=v1
Annotations:  sidecar.istio.io/status:
                {"version":"e16b88389e2d0f30d103af853bdac6a41c399031fafef687a65ce53a7ee83d33","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Running
IP:           10.244.0.13
IPs:
  IP:           10.244.0.13
Controlled By:  ReplicaSet/productpage-v1-f44bfb5fd
Init Containers:
  istio-init:
    Container ID:  containerd://39462989b30c282e38a65ee4964b1d60c95e150ad547bbb47af06a7eb51653aa
    Image:         docker.io/istio/proxyv2:1.6.3
    Image ID:      docker.io/istio/proxyv2@sha256:d082c3eea9c12e2f1bf6e4361509453a87e495d12146a1702d79e549098b8951
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 29 Jun 2020 17:34:37 +0530
      Finished:     Mon, 29 Jun 2020 17:34:37 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      DNS_AGENT:  
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-productpage-token-dmtzx (ro)
Containers:
  productpage:
    Container ID:   containerd://3417c85d0825c9ef06a9e736700785f6a1f099e3eb38e773d4a20d3a85a6430b
    Image:          shamsher31/examples-bookinfo-productpage-v1:1.16.2
    Image ID:       docker.io/shamsher31/examples-bookinfo-productpage-v1@sha256:c4c6a86c96938885393b1ba07d77e0f847d54b2df5f01c1caebfda8c43319edd
    Port:           9080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 29 Jun 2020 17:39:54 +0530
      Finished:     Mon, 29 Jun 2020 17:39:55 +0530
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-productpage-token-dmtzx (ro)
  istio-proxy:
    Container ID:  containerd://c8d6faa9205fc0574f3ca5c025eed06f1040c7e67ae3b5a9e17ac83cd260ccb2
    Image:         docker.io/istio/proxyv2:1.6.3
    Image ID:      docker.io/istio/proxyv2@sha256:d082c3eea9c12e2f1bf6e4361509453a87e495d12146a1702d79e549098b8951
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      productpage.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --trust-domain=cluster.local
      --concurrency
      2
    State:          Running
      Started:      Mon, 29 Jun 2020 17:39:14 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    first-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      productpage-v1-f44bfb5fd-vpx8h (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}
                                     
      ISTIO_META_POD_PORTS:          [
                                         {"containerPort":9080,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     [
                                         productpage
                                     ]
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      productpage-v1
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/default/deployments/productpage-v1
      ISTIO_META_MESH_ID:            cluster.local
      DNS_AGENT:                     
      ISTIO_KUBE_APP_PROBERS:        {}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from bookinfo-productpage-token-dmtzx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  bookinfo-productpage-token-dmtzx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  bookinfo-productpage-token-dmtzx
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                                  Message
  ----     ------     ----               ----                                  -------
  Normal   Pulling    5m59s              kubelet, istio-testing-control-plane  Pulling image "docker.io/istio/proxyv2:1.6.3"
  Normal   Scheduled  5m59s              default-scheduler                     Successfully assigned default/productpage-v1-f44bfb5fd-vpx8h to istio-testing-control-plane
  Normal   Pulled     5m43s              kubelet, istio-testing-control-plane  Successfully pulled image "docker.io/istio/proxyv2:1.6.3"
  Normal   Created    5m43s              kubelet, istio-testing-control-plane  Created container istio-init
  Normal   Started    5m42s              kubelet, istio-testing-control-plane  Started container istio-init
  Normal   Pulling    5m41s              kubelet, istio-testing-control-plane  Pulling image "shamsher31/examples-bookinfo-productpage-v1:1.16.2"
  Normal   Pulled     82s                kubelet, istio-testing-control-plane  Successfully pulled image "shamsher31/examples-bookinfo-productpage-v1:1.16.2"
  Normal   Pulling    81s                kubelet, istio-testing-control-plane  Pulling image "docker.io/istio/proxyv2:1.6.3"
  Normal   Pulled     66s                kubelet, istio-testing-control-plane  Successfully pulled image "docker.io/istio/proxyv2:1.6.3"
  Normal   Created    65s                kubelet, istio-testing-control-plane  Created container istio-proxy
  Normal   Started    65s                kubelet, istio-testing-control-plane  Started container istio-proxy
  Normal   Created    25s (x4 over 81s)  kubelet, istio-testing-control-plane  Created container productpage
  Normal   Started    25s (x4 over 81s)  kubelet, istio-testing-control-plane  Started container productpage
  Normal   Pulled     25s (x3 over 65s)  kubelet, istio-testing-control-plane  Container image "shamsher31/examples-bookinfo-productpage-v1:1.16.2" already present on machine
  Warning  BackOff    24s (x5 over 64s)  kubelet, istio-testing-control-plane  Back-off restarting failed container
```

**Comment by ericvn** [comment]
Looking, it seems like that could be an IPV6 related issue. Note sure if the older images work fine for you. I'm not sure if any of the requirements (in .txt) need to be updated but the python update seems to be pretty small. Maybe try backing it out and see if things improve.

**Comment by shamsher31** [comment]
Right, it is because Python does not work on an IPv6 only host https://bugs.python.org/issue10414. Using IPv4 address fix this issue.

**Comment by shamsher31** [comment]
I tried the following steps to test:

1. Build
```
$ samples/bookinfo/src/build-services.sh 1.16.2 docker.io/shamsher31
```
2. Push it to personal docker account.
```
$ ./build_push_update_images.sh 1.16.4 --prefix=shamsher31
```
Setup bookinfo sample.
```
$ kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

$ kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-7f556f5c6b-485l2       2/2     Running   0          19m
productpage-v1-84c8f95c8d-tlml2   2/2     Running   0          19m
ratings-v1-66777f856b-2ls78       2/2     Running   0          19m
reviews-v1-64c47f4f44-rx642       2/2     Running   0          19m
reviews-v2-66b6b95f44-s5nt6       2/2     Running   0          19m
reviews-v3-7f69dd7fd4-zjvc8       2/2     Running   0          19m
```

Test through cli
```
$ kubectl exec -it "$(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}')" -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"
<title>Simple Bookstore App</title>

```

Tested through the browser.
```
http://192.168.39.116:31395/productpage
```

star

**Comment by ericvn** [comment]
Images pushed and scanned. Should tweak the scrip to not push `latest`, although two slipped through.

**Pull request merged**
