### PR TITLE
add an option to disable generation of x-request-id header if tracing is off

### PR DESCRIPTION
**Pull request by darkstarmv**
1. add an option to disable generation of x-request-id header if tracing is off
1. add `enableTracing` to `meshConfig` in `global.yaml` to match value used in go code:

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
This seems fine to me but to make sure I understand, what is the motivation? performance? Or not adding an additional header?

**Comment by darkstarmv** [comment]
> This seems fine to me but to make sure I understand, what is the motivation? performance? Or not adding an additional header?

application team is using their own tracing library that generates `x-request-id` and sets its own sampling. 
Logging library is creating log entry based on presence of  `x-request-id`, which causes excessive logging if envoy passes its own headers. 
At the moment, we would like to be able to completly disable tracing in Istio.

**Review by douglas-reid — COMMENTED** [review]
Should we add tests to validate this behavior?

**Review by ramaraochavali — CHANGES_REQUESTED** [review]
One concern I have with disabling request ID generation if tracing is not enabled is, we will loose that in access logs also https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/accesslog.go#L41 if tracing is disabled.
Also I do think people use "x-request-id" to log in the application logs to correlate requests even if they are not using tracing/access logs. So this will affect them.
Either we need to drive this behaviour with new flag (I am not sure there will be many who want to disable that) or ~~you can write an Envoy filter to turn it off in your setup~~ (sorry, I missed that it is the same bool update issue)

**Comment by darkstarmv** [comment]
> One concern I have with disabling request ID generation if tracing is not enabled is, we will loose that in access logs also https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/accesslog.go#L41 if tracing is disabled.
> Also I do think people use "x-request-id" to log in the application logs to correlate requests even if they are not using tracing/access logs. So this will affect them.
> Either we need to drive this behaviour with new flag (I am not sure there will be many who want to disable that) or ~you can write an Envoy filter to turn it off in your setup~ (sorry, I missed that it is the same bool update issue)

Yes, Envoy filter is not an option at the moment. I can add a separate flag if that is a better solution.

**Comment by ramaraochavali** [comment]
Would it help if we stop setting this in the if `listenerOpts.push.Mesh.EnableTracing` - because I do not see a value in setting only when tracing is enabled - It is default in Envoy anyways

`connectionManager.GenerateRequestId = proto.BoolTrue`

Will it avoid merge issue in Envoy filter? Can you create Envoy filter to specifically add the field? I am not fully familiar with the proto merge issue. - @howardjohn would it work if that field itself does not exist?

**Comment by howardjohn** [comment]
That would work I think. Need to test it though

**Comment by ramaraochavali** [comment]
@darkstarmv do you want to try that? IMO not setting GenerateRequestId is much safer fix.

**Comment by darkstarmv** [comment]
> @darkstarmv do you want to try that? IMO not setting GenerateRequestId is much safer fix.

Ok, i can test this next week.
FYI: I've built and deployed custom image with above changes, so we are good for now, but i definitely don't want to maintain my own istio fork :)

**Comment by darkstarmv** [comment]
Tested these scenarios after code change:
1. No envoy filter, can see `x-request-id: 6f7c6425-7083-4d6f-8bae-f57ef013ddb2`:
```
curl https://myhost.mydomain | jq
{
  "Request": "GET / HTTP/1.1\nHost: myhost.mydomain\ncontent-length: 0\nx-envoy-peer-metadata: Ch......==\nuser-agent: curl/7.64.1\naccept: */*\nx-forwarded-for: 1.1.3.2,1.2.3.5\nx-forwarded-proto: http\nx-envoy-external-address: 1.2.3.5\nx-request-id: 6f7c6425-7083-4d6f-8bae-f57ef013ddb2\nx-envoy-peer-metadata-id: router~1.2.3.5~istio-ingressgateway-76588576ff-xghr2.istio-system~istio-system.svc.cluster.local"
```
2. Applied Envoy Filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio.io/rev: default
  name: configure-envoy
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          generate_request_id: false
```
Curl output has no `x-request-id` header:
```
curl https://myhost.mydomain | jq
{
  "Request": "GET / HTTP/1.1\nHost: myhost.mydomain\ncontent-length: 0\nx-envoy-peer-metadata: Ch......==\nuser-agent: curl/7.64.1\naccept: */*\nx-forwarded-for: 1.1.3.2,1.2.3.5\nx-forwarded-proto: http\nx-envoy-external-address: 1.2.3.5\nx-envoy-peer-metadata-id: router~1.2.3.5~istio-ingressgateway-76588576ff-xghr2.istio-system~istio-system.svc.cluster.local"
```

**Comment by ramaraochavali** [comment]
@darkstarmv I am sorry, I did not see the update on this PR and I have pushed a PR to remove it https://github.com/istio/istio/pull/27579 and it is merged. Sorry for that.

**Comment by darkstarmv** [comment]
> @darkstarmv I am sorry, I did not see the update on this PR and I have pushed a PR to remove it #27579 and it is merged. Sorry for that.

@ramaraochavali no worries, what about update to the helm chart to match it to the flag used in the code?

**Comment by ramaraochavali** [comment]
There is no helm change needed right - now that config is not added under any condition. Or Am I missing some thing?

**Comment by darkstarmv** [comment]
> There is no helm change needed right - now that config is not added under any condition. Or Am I missing some thing?

It is set with [this](https://github.com/istio/istio/blob/3036d1e6c5c148a4eeb24eff0700887e6e1e2a63/operator/cmd/mesh/install.go#L94) command and 
we are using helm to install `istio` and as a `helm` user it took me some time to dig in the code to find how to turn off tracing where it should be in [here]

**Comment by ramaraochavali** [comment]
I am not fully familiar with the helm change. ccing @howardjohn who might be able to help

**Review by howardjohn — CHANGES_REQUESTED** [review]
I don't think we need to set this here. We want the defaults to be configured in the code not the templates

**Comment by darkstarmv** [comment]
ok, I'm closing this pr - thanks for looking into this.

**Pull request closed without merging**
