### PR TITLE
Restructure node agent.

### PR DESCRIPTION
**Pull request by myidpt**
This copies the work from https://github.com/istio/istio/pull/5888 to master.
The purpose is to cherry pick features related to Citadel and node agent to master so that we can develop features on them while catching up with the progress on collab-gcp-identity.

### CODE REVIEW

**Comment by quanjielin** [comment]
seems https://github.com/istio/istio/pull/5888 made similar change in ```collab-gcp-identity``` 
? master should get the change after we merge back.

**Comment by myidpt** [comment]
@incfly @quanjielin 

I'm starting the work on supporting the [new CA protocol](https://github.com/istio/istio/tree/collab-gcp-identity/security/proto/ca/v1alpha1) on VM node agent and Citadel. I want to start this work now since it's not logically blocked.

About the process, there are 2 options:
1. Pick the related work (proto, VM node agent) and merge into master now. Implement the above feature on master. When we merge collab-gcp-identity back to master, the work will be relatively small. Of course, the merge process needs to be carefully done since there will be some conflicts.
2. Implement the above feature directly on collab-gcp-identity, and merge it into master. The concern is that the feature is not related to the purpose of this branch. Also, there's going to be a lot of diff between the two branches, that might make the merge task tough.

What do you think?

**Comment by incfly** [comment]
To me, merge collab-gcp-identity  back to master and then continue to develop on master is the best option if it's safe and flag guarded. (@quanjielin can commet)

If not feasible, vote for develop on collab-gcp-identity branch  and preparing mering back to master in parallel.

Merging collab-gcp-identity to master should be a trivial fast-forawrd merge since when developping collab-gcp-identity, we periodically do a commit preserved merge master into collab-gcp-identity.

Either way can avoid conflicts/extra work.

**Comment by quanjielin** [comment]
I plan to merge collab-gcp-identity back to master after next week's demo(also need wait to sync with Andy); to unblock the current work, how about checking into collab-gcp-identity for now ?

**Comment by myidpt** [comment]
I agree that the best approach is to merge `collab-gcp-identity` back to `master` and develop on `master` is the best option.
@quanjielin 
What's the earliest time this merge can be done? I heard there's also some work on the networking side for the merge.

**Comment by myidpt** [comment]
Reopen this PR due to https://github.com/istio/istio/pull/8056/files.

**Pull request merged**
