### PR TITLE
Remove ingress from Istio

### PR DESCRIPTION
**Pull request by sdake**
Remove lint error from preconfigured.yaml
Remove ingress from all values.yaml addon files
Remove preconfigured k8s ingress object
Remove k8sIngress from top level values.yaml
Initial removal of ingress charts

### CODE REVIEW

**Comment by duderino** [comment]
@philrud PTAL

**Comment by linsun** [comment]
thanks @sdake!! you saved me from working on this during lunch break :)

Q: I'd like to see the ingress config remains for some of our addons.  for example:  install/kubernetes/helm/istio/charts/kiali/templates/ingress.yaml

as this will work with k8s ingress.

**Comment by philrud** [comment]
@duderino I've provided my reasoning here: https://github.com/istio/istio/issues/12015#issuecomment-469764994
If @costinm believes we should do it for 1.1, let's do it of course, I just don't understand what are we gaining by doing this now, considering the new installer is around the corner.

**Comment by sdake** [comment]
@linsun happy to drop the addons commits from the layers - which would restore them.  I am not clear they would work as is, and they would need qualification I suspect.  Unfortunately, I am really tight on time this week to do such qualification.  Monday is open :)

Cheers
-steve

**Comment by linsun** [comment]
@sdake let's drop it. I'm chairing a doc testing day this Fri with Dan - we can ask folks to test this on that day.

**Comment by duderino** [comment]
Closing because of https://github.com/istio/istio/issues/12015#issuecomment-469911843 and comments on this PR

**Pull request closed without merging**
