### PR TITLE
Add dial timeout

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
MCP server dial should use timeout.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
>The MCP client uses non-blocking dialing. WithTimeout is only valid for blocking dials.

Thanks, I read the comments now.  Should we make this blocking with `WithBlock()` option?

```
// DialContext creates a client connection to the given target. By default, it's
// a non-blocking dial (the function won't wait for connections to be
// established, and connecting happens in the background). To make it a blocking
// dial, use WithBlock() dial option.
//
// In the non-blocking case, the ctx does not act against the connection. It
// only controls the setup steps.
//
// In the blocking case, ctx can be used to cancel or expire the pending
// connection. Once this function returns, the cancellation and expiration of
// ctx will be noop. Users should call ClientConn.Close to terminate all the
// pending operations after this function returns.
```

**Comment by ayj** [comment]
> Thanks, I read the comments now. Should we make this blocking with WithBlock() option?

No, I think we still want non-blocking operation (w/o timeout). First, blocking doesn't really buy us anything. The grpc layer will end re-dialing in the background anyway to recover the connection. Second, we don't want to block the rest of pilot startup while we wait for each MCP client to connect.

**Comment by hzxuzhonghu** [comment]
What's the behavior when send a request when the underlying connection is not available?

**Comment by ayj** [comment]
The gRPC client connection will attempt to reconnect until we explicitly close the connection. Likewise, the MCP client will (re)establish the bi-directional stream on top of that connection until we explicitly stop the client.

**Comment by hzxuzhonghu** [comment]
That's good when network is ok. But when network is not ok, the dial time maybe uncertain, maybe minutes level. Is that acceptable?

**Comment by hzxuzhonghu** [comment]
when server is not accessable. Maybe config error. The pilot will never exit. But user can not find the cause easily.

**Comment by ayj** [comment]
DialTimeout is invalid for non-blocking calls per the documentation.

The server will likely not be accessible during initial Install due to pod startup times. I believe we want Pilot and Mixer to be resilient to these startup delays and transient network issues. Making the call blocking and failing (due to timeout) after 15 seconds may likely result in pod restarts during install. And subsequent re-connections will occur in the background anyway.

**Comment by hzxuzhonghu** [comment]
Ok, I am convinced

**Pull request closed without merging**
