### PR TITLE
Add telemetry-gateway subchart to helm requirements

### PR DESCRIPTION
**Pull request by douglas-reid**
Fixes: https://github.com/istio/istio/issues/9748

### CODE REVIEW

**Comment by douglas-reid** [comment]
@sdake i tested the conditions locally. seemed to work (and matches the mixer enablement condition)

**Comment by douglas-reid** [comment]
@hklai I think in `release-1.1` a different approach was being taken.  @jmazzitelli @sdake is that correct?

**Comment by hklai** [comment]
@douglas-reid it is **bad** if release-1.1 has already diverged.

**Comment by hklai** [comment]
Looking at https://github.com/istio/istio/pull/10349/files, it looks like I can just remove  telemetry-gateway from requirements.yaml, as I am merging release-1.1 to master (https://github.com/istio/istio/pull/10843)

I will include that in the same PR.

**Pull request merged**
