### PR TITLE
WIP Refactor SDS code to use go-control-plane

### PR DESCRIPTION
**Pull request by howardjohn**
WIP. https://github.com/istio/istio/pull/28843/ investigates using
Istiod's XDS server, this looks at using go-control-plane

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by mandarjog** [comment]
@kyessenov this is using go-controlplane. @howardjohn Is this copying something from go-controlplane or 'using' it by importing?

**Comment by howardjohn** [comment]
@mandarjog this is actually using it as the control plane. I was exploring it as an option as I originally thought it would be challenging to refactor the ADS server in Istiod to be used in the agent. However, in https://github.com/istio/istio/pull/29688 I explored that option more and I think it is ideal, so I would consider this obsolete

**Pull request closed without merging**
