### PR TITLE
Refresh golden snapshot

### PR DESCRIPTION
**Pull request by carolynhu**
https://github.com/istio/istio/issues/27931

Since recently there are some dashboards being updated, operator addson testdata should in sync with those. This PR is for adding those changes in one place.

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
you should just run `./operator/scripts/run_update_golden_snapshots.sh`. This does not need to be updated on every change though, the whole point is its used to test the internal logic of the operator rendering, not to exactly look at the output

**Review by howardjohn — APPROVED** [review]

**Review by ostromart — APPROVED** [review]

**Pull request merged**
