### PR TITLE
fix routes nil

### PR DESCRIPTION
**Pull request by dsy3502**
validate: nil check routes
when i set the tcp route: []  istiod restarts

### CODE REVIEW

**Comment by dsy3502** [comment]
> How did you set routes nil?
my statement is not accurate, the length of routes is 0  when  I set the virtualservice resource tcp：route: [] by accident. Then istiod restarts

spec:
  hosts:
  - crm
  tcp:
    route: []

**Comment by zirain** [comment]
> > How did you set routes nil?
> > my statement is not accurate, the length of routes is 0  when  I set the virtualservice resource tcp：route: [] by accident. Then istiod restarts
> 
> spec: hosts:
> 
> * crm
>   tcp:
>   route: []

that passed webhook?

**Pull request closed without merging**
