### PR TITLE
Move cert generation tooling to /tools

### PR DESCRIPTION
**Pull request by myidpt**
/install isn't included in the release package. Move it to /tools.

Will cherrypick to 1.6 as well.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jacob-delgado** [comment]
This is more or less a revert of https://github.com/istio/istio/pull/23895/, right?

**Comment by myidpt** [comment]
@jacob-delgado Yes it is, but the Makfile has been changed since that PR.

**Comment by smawson** [comment]
This makefile is referenced from a number of install guides, if it is not for actual use we need to change the install guides. Please fix the install guides first and then we can move these back to samples, but for now they're what our documentation is telling users to do.

**Comment by myidpt** [comment]
Yes this Makefile is also used by VMs, and I don't think it offers best security for VMs either. The admin is able to access the private signing key and the private key for the VM.
But it is unfortunately the only way we provision certs for VMs. I think we can do is to put security caveats in the VM setup UG.

**Review by howardjohn — APPROVED** [review]
approving as Oliver said he will update docs

**Comment by sdake** [comment]
@howardjohn - Can you verify these tools will be packaged by release-builder for 1.6?

@myidpt I can take care of the doc changes now and have a cherry-pick ready to go once 1.6 is live. Please confirm if you wish me to do so, or if you plan to handle it. For the virtual machine guide, this is a 1 liner change (IIRC).

Please let me know.

CC / @frankbu / @ericvn .

Cheers,
-steve

**Comment by sdake** [comment]
> Yes I don't think this Makefile offers best security for VMs either. The admin is able to access the private signing key and the private key for the VM.
> But it is unfortunately the only way we provision certs for VMs. I think what we can do is to put security caveats in the VM setup UG.
> @liminw FYI

FWIW, there are already 3 different warnings of the same nature in the virtual machine workload integration guide. I'm not sure more warnings help :)

Cheers,
-steve

**Comment by sdake** [comment]
> @howardjohn - Can you verify these tools will be packaged by release-builder for 1.6?
> 
> @myidpt I can take care of the doc changes now and have a cherry-pick ready to go once 1.6 is live. Please confirm if you wish me to do so, or if you plan to handle it. For the virtual machine guide, this is a 1 liner change (IIRC).
> 
> Please let me know.
> 
> CC / @frankbu / @ericvn .
> 
> Cheers,
> -steve

@myidpt I just noticed you have already solved the documentation via the 1 liner. Cheers :)
-steve

**Comment by sdake** [comment]
> This makefile is referenced from a number of install guides, if it is not for actual use we need to change the install guides. Please fix the install guides first and then we can move these back to samples, but for now they're what our documentation is telling users to do.

@smawson The actions @myidpt has taken LGTM. We have only one document that references this tool, and the document has numerous warnings about the security implications of the virtual machine integration.

@rcaballeromx 's new guide for multicluster uses this same tooling, although it is not yet live, and that will need a few one liner changes here and there as well.

Cheers
-steve

**Pull request merged**
