### PR TITLE
Embed integration testdata

### LINKED ISSUE #14945: Integration test framework depends on testdata causing test failures when using go modules
**Bug description**
I will start by saying I don't have a full understanding of go modules internals as of yet so apologies if this is a non-issue or there is a simple workaround.

I am using the integration test framework in istio 1.1.7 in an OOP adapter.
However when I migrate my code to use go modules, the integration tests begin to fail.

My understanding is that go modules strips all non `.go` files from the projects dependencies. 
The integration test framework depends on yaml config here, loaded from relative path https://github.com/istio/istio/blob/1.1.7/mixer/pkg/adapter/test/integration.go#L347-L359 causing test failures.

Do you have any suggestions to workaround this or am I overlooking something/ missing an obvious workaround?

I guess we could embed the content directly in the go code but not sure this is an ideal solution.

### PR DESCRIPTION
**Pull request by PhilipGough**
This embeds test fixtures and manifests required by adapter integration test framework.

Fixes #14945

### CODE REVIEW

**Comment by PhilipGough** [comment]
@kyessenov mind taking a quick look? I haven't tested yet but should hopefully resolve the linked issue . Just let me know if you are happy with it and I'll test it out e2e

**Comment by PhilipGough** [comment]
@kyessenov yes, I've ran go generate locally and all looks good and that is included in `fixtures.gen.go`.

 I assume you mean we would want to run this on each build or future PR is it? If yes then not sure where, is there some make target I should add it too? Saying that can't imagine this will change all that often, if ever.

**Comment by kyessenov** [comment]
Sorry, I missed the large generated file (github collapsed it for me).

**Comment by PhilipGough** [comment]
@kuat I've fixed the spellcheck and rebased to fix linting. Tested this out locally and works as expected if your happy, I think it is good to go.

**Pull request merged**
