### PR TITLE
update bookinfo containers after code changes

### PR DESCRIPTION
**Pull request by rshriram**
This PR updates bookinfo docker images after recent changes in #693 to provide proper API endpoints. To maintain backward compatibility, images have been versioned.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
Versioning the images seems good but there are at least 2 unrelated changes combined here, but I suppose if it passes all tests, maybe it's ok. Or it can wait 0.3

**Comment by ldemailly** [comment]
Description is unclear by the way, please clarify

**Comment by rshriram** [comment]
auth failure.. this pr has nothing to do with pilot. whoever made auth as required, please fix.
```W0909 05:07:17.814] W0909 05:06:44.703535       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0909 05:07:17.814] I0909 05:06:44.704615       1 client.go:167] registering CRD "routerules.config.istio.io"
W0909 05:07:17.814] Error: failed to register custom resources. User "system:serviceaccount:mixer-test-8c81b9545f4a43989579b9305c:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope.: "Unknown user \"system:serviceaccount:mixer-test-8c81b9545f4a43989579b9305c:istio-pilot-service-account\"" (post customresourcedefinitions.apiextensions.k8s.io)
W0909 05:07:17.814] Usage:
W0909 05:07:17.814]   pilot discovery [flags]
W0909 05:07:17.814] 
W0909 05:07:17.815] Flags:
W0909 05:07:17.815]       --admission-registration-delay duration   Time to delay webhook registration after starting webhook server (default 5s)
W0909 05:07:17.815]       --admission-secret string                 Name of k8s secret for pilot webhook certs (default "pilot-webhook")
W0909 05:07:17.815]       --admission-service string                Service name the admission controller uses during registration (default "istio-pilot-external")
W0909 05:07:17.815]       --admission-service-port int              HTTPS port of the admission service. Must be 443 if service has more than one port  (default 443)
W0909 05:07:17.815]       --admission-webhook-name string           Webhook name for Pilot admission controller (default "pilot-webhook.istio.io")
W0909 05:07:17.815]   -a, --app namespace string                    Restrict the applications namespace the controller manages; if not set, controller watches all namespaces
W0909 05:07:17.815]       --consulconfig string                     Consul Config file for discovery
W0909 05:07:17.815]       --consulserverURL string                  URL for the Consul server
W0909 05:07:17.816]       --discovery_cache                         Enable caching discovery service responses (default true)
W0909 05:07:17.816]       --domain string                           DNS domain suffix (default "cluster.local")
W0909 05:07:17.816]       --eurekaserverURL string                  URL for the Eureka server
W0909 05:07:17.816]   -h, --help                                    help for discovery
W0909 05:07:17.816]       --kubeconfig string                       Use a Kubernetes configuration file instead of in-cluster configuration
W0909 05:07:17.816]       --meshConfig string                       File name for Istio mesh configuration (default "/etc/istio/config/mesh")
W0909 05:07:17.816]   -n, --namespace string                        Select a namespace for the controller loop. If not set, uses ${POD_NAMESPACE} environment variable
W0909 05:07:17.816]       --port int                                Discovery service port (default 8080)
W0909 05:07:17.816]       --profile                                 Enable profiling via web interface host:port/debug/pprof (default true)
W0909 05:07:17.816]       --registries stringSlice                  Comma separated list of platform service registries to read from (choose one or more from {Kubernetes, Consul, Eureka}) (default [Kubernetes])
W0909 05:07:17.817]       --resync duration                         Controller resync interval (default 1m0s)
W0909 05:07:17.817] 
W0909 05:07:17.817] Global Flags:
W0909 05:07:17.817]       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
W0909 05:07:17.817]   -v, --v Level                          log level for V logs (default 0)
W0909 05:07:17.817]       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
W0909 05:07:17.817] 
W0909 05:07:17.817] E0909 05:06:44.747213       1 main.go:279] failed to register custom resources. User "system:serviceaccount:mixer-test-8c81b9545f4a43989579b9305c:istio-pilot-service-account" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope.: "Unknown user \"system:serviceaccount:mixer-test-8c81b9545f4a43989579b9305c:istio-pilot-service-account\"" (post customresourcedefinitions.apiextensions.k8s.io)
W0909 05:07:17.817] , err: <nil>```

**Comment by ldemailly** [comment]
Auth is what we ship for 0.2, please pitch in and find what's wrong

**Comment by ldemailly** [comment]
Why was this force merged ? Please revert unless it passes all tests

**Pull request merged**
