### PR TITLE
Add @nmittler to CODEOWNERs top level

### PR DESCRIPTION
**Pull request by howardjohn**
Backfill after Shriram left to avoid bus factor of only having 3 of us

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by linsun** [comment]
I'm good with @nmittler!

@nrjpoddar do you want to be added also?

**Comment by howardjohn** [comment]
:+1: for @nrjpoddar if you are interested. Basically its just approving top level files like readme, go.mod, or files that we didn't add owners for

**Comment by nrjpoddar** [comment]
Thanks, you can leave me out for now. 4 is a good number. If you fall short then I'm happy to be included.

**Review by linsun — APPROVED** [review]
SGTM @nrjpoddar

**Pull request merged**
