### PR TITLE
Pass CompliancePolicy through to gateways as well

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by keithmattix — APPROVED** [review]

**Comment by kyessenov** [comment]
Do we need to backport this?

**Comment by kyessenov** [comment]
I think we sent the original PR to 1.17-1.20 as well (some on private forks).

**Comment by howardjohn** [comment]
Ok, I cannot backport to private forks :-) So if anyone shipped this on a
private 1.17 fork, they should backport this.

**Pull request merged**
