### PR TITLE
set citadel trust domain from global config

### PR DESCRIPTION
**Pull request by quanjielin**
https://github.com/istio/istio/issues/10283

otherwise cause inconsistent

### CODE REVIEW

**Comment by quanjielin** [comment]
close this for now, need more investigation on test failure.

**Comment by loewenstein** [comment]
@quanjielin wondering why you closed this. I suppose we should indeed take the trust domain from the same config everywhere in Istio.

/cc @axel7born @myidpt

**Comment by quanjielin** [comment]
this PR is needed, as put in earlier comments ```close this for now, need more investigation on test failure.```

**Pull request closed without merging**
