### PR TITLE
Generate collections for networking/v1beta1 apis as well

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Trying to use pilot collections in our downstream controller to watch the k8s apiserver for the istio objects. Found that collections were missing for networking/v1beta apis

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by esnible** [comment]
We need a review from @jasonwzm who is working on translation between API versions before merging.  He may have a different design in mind.

**Comment by jasonwzm** [comment]
+1 to john's point. Reading v1alpha3 should give you the same API as v1beta1 now. Adding v1beta1 collections will add the reads by pilot which is overhead for now.

**Comment by vikaschoudhary16** [comment]
thanks @esnible and @howardjohn for the comments!
Now i realize may be these changes are not required. I missed to notice automatic conversion of versions that k8s supports.

**Pull request closed without merging**
