### PR TITLE
[CherryPick]Change IP addresses to show up as strings in label maps in accesslog …

### PR DESCRIPTION
**Pull request by gargnupur**
CherryPick (#11740) from Master to release 1.1 for 1.1.1 release

Change IP addresses to show up as strings in http req  in accesslog

Fix lint errors

Fix lint errors

Use stringify function

Updated based on feedback

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Can we get this merged for the next 1.1.x release? 🙏  @douglas-reid @geeknoid

**Comment by douglas-reid** [comment]
@dwradcliffe 100% agree.

@duderino can you help us merge this please?

**Comment by kyessenov** [comment]
This is a good candidate for 1.1.2
cc @duderino

**Comment by duderino** [comment]
For 1.1.2 which should be out on 4/1 (not joking)

**Pull request merged**
