### PR TITLE
istioctl analyze: display dir or file name when it is provided

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/30865

Before:
```
$ istioctl analyze samples/bookinfo/platform/kube/

✔ No validation issues found when analyzing namespace: default.
```

After:

When filename is provided
```
$ istioctl analyze samples/bookinfo/platform/kube/bookinfo-ingress.yaml

✔ No validation issues found when analyzing samples/bookinfo/platform/kube/bookinfo-ingress.yaml.
```

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
what if we pass multiple files?

**Comment by shamsher31** [comment]
> what if we pass multiple files?

Assuming that both files are in the same directory, it falls back to displaying a directory name instead of a file name. 
```
$ istioctl analyze samples/bookinfo/platform/kube/bookinfo-ingress.yaml samples/bookinfo/platform/kube/bookinfo-db.yaml

✔ No validation issues found when analyzing samples/bookinfo/platform/kube
```

**Comment by howardjohn** [comment]
It seems misleading to only show the first one. it suggests the others are ignored

**Comment by shamsher31** [comment]
> It seems misleading to only show the first one. it suggests the others are ignored

@howardjohn Added ability to list multiple files if provided.

Single file scan
```
$ istioctl analyze samples/multicluster/expose-istiod.yaml 

✔ No validation issues found when analyzing samples/multicluster/expose-istiod.yaml.
```

Multiple files.
```
$ istioctl analyze samples/multicluster/expose-istiod.yaml samples/multicluster/expose-services.yaml 

✔ No validation issues found when analyzing samples/multicluster/expose-istiod.yaml
samples/multicluster/expose-services.yaml.
```

Scanning a directory.
```
$ istioctl analyze samples/multicluster/
Skipping file samples/multicluster/README.md, recognized file extensions are: [.json .yaml .yml]
Skipping file samples/multicluster/gen-eastwest-gateway.sh, recognized file extensions are: [.json .yaml .yml]

✔ No validation issues found when analyzing samples/multicluster/expose-istiod-https.yaml
samples/multicluster/expose-istiod.yaml
samples/multicluster/expose-services.yaml.
```

If nothing is provided.
```
$ istioctl analyze
✔ No validation issues found when analyzing namespace: default.
```

**Comment by shamsher31** [comment]
@esnible ping.

**Review by jasonwzm — APPROVED** [review]

**Pull request merged**
