### PR TITLE
revert eds cache in ads

### PR DESCRIPTION
**Pull request by ramaraochavali**
Revert as there seems to be some issues https://github.com/envoyproxy/envoy/pull/32767 in Envoy and we also dont fully utilize this as we set init_fetch_timeout to zero

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]
Test flake is not related

**Pull request merged**
