### PR TITLE
do not generate other routes when catch all route is present

### PR DESCRIPTION
**Pull request by ramaraochavali**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Closing this as there is some issue with the fix

**Review by howardjohn — COMMENTED** [review]
I recall we reverted this at some point. I forget why

**Comment by howardjohn** [comment]
I mean we did this, then reverted it later

**Comment by ramaraochavali** [comment]
ok.. did not understand what is causing it fail though. I will take a deeper look later.

**Pull request closed without merging**
