### PR TITLE
make replica for cert-manager configurable and add back pdb.

### PR DESCRIPTION
**Pull request by morvencao**
Merge https://github.com/istio/installer/pull/210 back to master and add back PDB for cert-manager.

### CODE REVIEW

**Comment by howardjohn** [comment]
@morvencao what is the impact if we don't change this? Are there any risks?

If there are any risks and this isn't fixing customer issues we may just want to hold off on this while we focus on the new installer

**Comment by linsun** [comment]
@howardjohn this change already landed in the new installer.  The impact is that cert mgr isn't configurable to be HA and won't work for PDB during update.

**Comment by morvencao** [comment]
@howardjohn Yes, this is really an important fix. Or the default PDB(minAvailable=1) and replica combination for cert-manager prevent node upgrade/maintain.

**Pull request merged**
