### PR TITLE
Revert #25965

### LINKED ISSUE #27944: Istiod crash on namespace controller
```
2020-10-14T16:20:10.883777Z     info    ads     ADS: new connection for node:sidecar~10.88.5.161~svc00-0-8-0-645d6c7dcb-q7h24.service-graph00~service-graph00.svc.cluster.local-509
2020-10-14T16:20:10.885382Z     info    ads     CDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:38
2020-10-14T16:20:10.885630Z     info    ads     NDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:1
2020-10-14T16:20:10.885779Z     info    ads     EDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:34 empty:0 cached:34/34
2020-10-14T16:20:10.887008Z     info    ads     LDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:18
2020-10-14T16:20:10.887791Z     info    ads     RDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:7
2020-10-14T16:20:10.930942Z     info    ads     ADS: "10.88.2.135:51136"  terminated rpc error: code = Canceled desc = context canceled
2020-10-14T16:20:10.981982Z     info    ads     ADS: "10.88.9.214:44208"  terminated rpc error: code = Canceled desc = context canceled
2020-10-14T16:20:11.031681Z     info    ads     ADS: "10.88.9.151:40838"  terminated rpc error: code = Canceled desc = context canceled
2020-10-14T16:20:11.082305Z     info    klog    successfully acquired lease istio-system/istio-leader
2020-10-14T16:20:11.082436Z     info    Starting ingress controller
2020-10-14T16:20:11.132149Z     info    ads     ADS: new connection for node:sidecar~10.88.2.116~svc14-0-1-668fc64696-qms9r.service-graph14~service-graph14.svc.cluster.local-510
2020-10-14T16:20:11.133761Z     info    ads     CDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:38
2020-10-14T16:20:11.133982Z     info    ads     NDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:1
2020-10-14T16:20:11.134138Z     info    ads     EDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:34 empty:0 cached:34/34
2020-10-14T16:20:11.135637Z     info    ads     LDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:18
2020-10-14T16:20:11.136513Z     info    ads     RDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:7
2020-10-14T16:20:11.183144Z     info    klog    successfully acquired lease istio-system/istio-validation-controller-election
2020-10-14T16:20:11.183292Z     info    Starting validation controller
2020-10-14T16:20:11.183364Z     info    validationController    Reconcile(enter): initial request to kickstart reconciliation
2020-10-14T16:20:11.183957Z     info    validationController    validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail, resourceVersion=11245206) is up-to-date. No change required.
2020-10-14T16:20:11.233728Z     info    ads     ADS: new connection for node:sidecar~10.88.6.224~svc03-0-4-658d4c6ffd-nslxc.service-graph03~service-graph03.svc.cluster.local-511
2020-10-14T16:20:11.235321Z     info    ads     CDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:38
2020-10-14T16:20:11.235467Z     info    ads     EDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:34 empty:0 cached:34/34
2020-10-14T16:20:11.235827Z     info    ads     NDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:1
2020-10-14T16:20:11.237191Z     info    ads     LDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:18
2020-10-14T16:20:11.237997Z     info    ads     RDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:7
2020-10-14T16:20:11.282211Z     info    klog    successfully acquired lease istio-system/istio-namespace-controller-election
2020-10-14T16:20:11.282345Z     info    Namespace controller started
panic: queue can not be run twice

goroutine 19400 [running]:
istio.io/istio/pkg/queue.(*queueImpl).Run(0xc001e0efa0, 0xc008fb9080)
        istio.io/istio/pkg/queue/instance.go:76 +0x36a
created by istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*NamespaceController).Run
        istio.io/istio/pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go:125 +0x14c

```

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
The x-controller should be started only when istiod acquires leadership. Otherwise there is potential case either lose event or introduce cpu spike.

This also fixes #27944

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Can you fix lint and ut?

**Comment by hzxuzhonghu** [comment]
Sure

**Comment by hzxuzhonghu** [comment]
@ramaraochavali @howardjohn Without this there is potential issue missing handle specific objects

**Review by ramaraochavali — APPROVED** [review]

**Comment by ramaraochavali** [comment]
@hzxuzhonghu Sorry, I thought I approved it.

**Pull request merged**
