### PR TITLE
feat(gateway): Add priority class

### PR DESCRIPTION
**Pull request by sylus**
**Please provide a description of this PR:**

Add Priority Class support to gateway chart aligning with other charts.

This issue was automatically closed so I made a new P.R.:

https://github.com/istio/istio/pull/41200

## Background

The priorityClassName option in a Helm chart is a standard addition for fine-tuning resource allocation in Kubernetes clusters. By associating pods with specific priority classes, it enables effective management of workload importance, ensuring that critical applications receive the appropriate resources and precedence, thereby enhancing overall cluster reliability and performance.

### CODE REVIEW

**Comment by zirain** [comment]
please sign CLA

/ok-to-test

**Comment by keithmattix** [comment]
Can you describe a bit the use case, how its generally applicable, and if why/if https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/ works as an alternative?

Note that #41200 had changes requested for the same reason.

**Comment by sylus** [comment]
@keithmattix this is for an Argo deployment which only has the helm provider. Adding kustomize just to have a priorityclass I would argue isn't a great solution. Particularly as priorityclass has already been added in other charts and it is considered best practice along with taints and tolerations etc.

**Comment by howardjohn** [comment]
> @keithmattix this is for an Argo deployment which only has the helm provider. Adding kustomize just to have a priorityclass I would argue isn't a great solution. Particularly as priorityclass has already been added in other charts and it is considered best practice along with taints and tolerations etc that every chart at a minimum should support natively.

Expecting every project you depend on (in most large orgs, I assume this is >20) to implement all of the >1000 kubernetes API fields in their helm charts isn't a great solution. You are suggesting adding one field, but 999 other people are suggesting adding 1 other field as well. 

The proper solution is just to post-process things.

**Comment by sylus** [comment]
Thanks for taking the time @howardjohn 

I completely understand your perspective about not wanting to support every object.

It seems that the differences between our viewpoints lie here.

In my opinion, certain fields like priorityClassName, tolerations, and nodeSelectors are of great significance. These fields, along with essential parameters like the container image, are a core requirement for the workload to function correctly. I'd argue that there's a natural expectation for these fields to be consistently present in Helm charts.

On the topic of priorityClassName, since this field has already been integrated into various charts within the istio manifests folder this would just be consistency of approach:

https://github.com/search?q=repo%3Aistio%2Fistio%20priorityClassName&type=code

However I'm happy to try to use the approach you mention if this is just not something being entertained at the moment.

Thanks again for your time :)

**Pull request closed without merging**
