### PR TITLE
Stop Pilot correctly in MCP test

### PR DESCRIPTION
**Pull request by Nino-K**
This addresses an issue where  pilot mcp integration test completed but the client (pilot) was never stopped therefore this can sometimes lead into pilot trying to reconnect to the mcp server while the mcp server is stopped.

### CODE REVIEW

**Comment by ZackButcher** [comment]
Looks good but can we use [io.Closer](https://golang.org/pkg/io/#Closer) to describe the return instead - that way our linters will make sure the function is actually closed when used, etc.

That'd require making some `CloserFunc` type like:

```go
type CloserFunc func() error

func (f CloserFunc) Close() error {
    return f()
}
```

then in `setup.go` you can:

```go
func setup(additionalArgs ...func(*bootstrap.PilotArgs)) (io.Closer, error) {
    return CloserFunc(func() error { close(stop); return nil }), err
}
```

**Comment by Nino-K** [comment]
> Looks good but can we use [io.Closer](https://golang.org/pkg/io/#Closer) to describe the return instead - that way our linters will make sure the function is actually closed when used, etc.
> 
> That'd require making some `CloserFunc` type like:
> 
> ```go
> type CloserFunc func() error
> 
> func (f CloserFunc) Close() error {
>     return f()
> }
> ```
> 
> then in `setup.go` you can:
> 
> ```go
> func setup(additionalArgs ...func(*bootstrap.PilotArgs)) (io.Closer, error) {
>     // ...
>     return CloserFunc(func() error { close(stop); return nil }), err
> }
> ```

I like the idea of describing the return function, however in case of `io.Closer` I feel as tho the returned error from `CloserFunc` is not being leveraged or used. Do you think it would be more reasonable if we have a type and use the type to describe the return func?
```go
type Close func() 

func setup(additionalArgs ...func(*bootstrap.PilotArgs)) (Close, error) {
     // ...
}
```

**Comment by rshriram** [comment]
/lgtm cancel.. 
sorry didn't see Zack's review

**Comment by Nino-K** [comment]
@rshriram I updated as per @ZackButcher 's suggestion with io.closer since it is a nicer approach because the linters specifically check that instances of that interface have the Close method called, but the same linters wouldn't work for the `type Closer func()` case.

**Comment by Nino-K** [comment]
@rshriram can we merge this?

**Pull request merged**
