### PR TITLE
Add pilot version string to prom metrics (#10027)

### PR DESCRIPTION
**Pull request by ostromart**
Cherry pick of https://github.com/istio/istio/pull/10027

### CODE REVIEW

**Comment by ostromart** [comment]
That's ok, let's still get it in since there may be other 1.0 versions.

**Comment by douglas-reid** [comment]
@hklai can you merge this PR on the release-1.0 branch, per @ostromart 's suggestion?

**Comment by hklai** [comment]
@ostromart @douglas-reid  and is this needed for 1.0.6?

**Comment by hklai** [comment]
linter had been broken in release-1.0. you can ignore that for now.

**Pull request merged**
