### PR TITLE
[release-1.9] support running integration tests against real VMs  (#30464)

### PR DESCRIPTION
**Pull request by stevenctl**

### CODE REVIEW

**Comment by stevenctl** [comment]
Want to look at https://github.com/istio/istio/issues/30572#issuecomment-771378611 a bit more, added hold.

**Comment by shamsher31** [comment]
@stevenctl The work is still going on or is it ready for merge?

**Comment by stevenctl** [comment]
Going to include https://github.com/istio/istio/pull/30584 in this PR as well.

**Comment by stevenctl** [comment]
Should be good to go. Hoping this is mergeable in the freeze since it only touches test files.

**Comment by jacob-delgado** [comment]
> Should be good to go. Hoping this is mergeable in the freeze since it only touches test files. Merging this should make future cherry-picks easier since the _test changes are so widespread. 

I'm fine with it. Unit and integrations are welcome to help promote features.

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
