### PR TITLE
[release-1.4] Cherry-picking of istio.io framework enhancements

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
/hold
the mirror test is flaking...

**Comment by howardjohn** [comment]
Thanks for picking all of this up :+1:

**Comment by howardjohn** [comment]
We may need these as well: f84039647 242880fa8 82a839967 669427a8c

**Comment by jwendell** [comment]
> We may need these as well: [f840396](https://github.com/istio/istio/commit/f84039647e16a55a4f9eb06cb14979092dd6996d) [242880f](https://github.com/istio/istio/commit/242880fa8cc8f844ba41245d6aa8f4eaf3945be1) [82a8399](https://github.com/istio/istio/commit/82a8399674312da08d8514c507c3bf54746a76b0) [669427a](https://github.com/istio/istio/commit/669427a8c82b55fd51fe77629cafe4ed6e74b575)

Thanks, will add those as well.

**Pull request merged**
