### PR TITLE
Cleanup SDSEnabled as SDS is enabled by default

### PR DESCRIPTION
**Pull request by nschhina**
Since we default to SDS now, cleaning up code and tests for ISTIO_MUTUAL common context creation. Removes a lot of dead code for TLS context creation. Updated older tests to check default SDS behaviour
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nschhina** [comment]
cc: @ramaraochavali

**Comment by nschhina** [comment]
Potential merge conflict with https://github.com/istio/istio/pull/25028

**Comment by howardjohn** [comment]
`REFRESH_GOLDEN=true go test ./pkg/bootstrap/...`

should save you some time on fixing those tests.

**Comment by nschhina** [comment]
> `REFRESH_GOLDEN=true go test ./pkg/bootstrap/...`
> 
> should save you some time on fixing those tests.

Thank you for this! I was manually updating every golden file, there's comment on TestGolden that suggests we use `cp` to copy files from /out/release/bootstrap, I think that approach is outdated so I'll update the comment with this refresh approach

**Comment by hzxuzhonghu** [comment]
Is that mean sds is the only choice now?

**Comment by ramaraochavali** [comment]
@nschhina Are you planning to create a separate PR for cleaning this stuff?

**Comment by nschhina** [comment]
@ramaraochavali this PR is blocked by the failing TestEnvoy test in xDS package. That one uses it's own bootstrap and doesn't have a SDS cluster, I don't have cycles to work on this further before 1.7 release

**Pull request closed without merging**
