### PR TITLE
Add a lint_modern target to start switchinng over to the build container

### PR DESCRIPTION
**Pull request by geeknoid**
- Fix a batch of lint warnings.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by incfly — APPROVED** [review]
/lgtm
/approve

**Comment by incfly** [comment]
Wondering, how did you do a pass to fix all those existing lints error? A one-off bash script?

**Comment by geeknoid** [comment]
@incfly No script, just a text editor and patience...

**Pull request merged**
