### PR TITLE
Cleanup unused applicationPorts and inbound port meta

### PR DESCRIPTION
**Pull request by howardjohn**
Application ports is no longer used for sidecar, we now capture all. For
gateway, we added this as a short-sighted hack to work around proxy
start up issues. These issues have been fixed in multiple ways
(initial_fetch_timeout and checking server_info) so it is no longer
required.

The INCLUDE_INBOUND_PORTS metadata is never used either, so cleaned that
up. Note: this does not remove the annotation, which applies to the
iptables, just no longer passes to pilot.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by lambdai** [comment]
@diemtvu  I am pretty sure you used applicationPorts in the past. And I do see TestAuthenticationZ test failure. Could you confirm?

**Comment by lambdai** [comment]
@howardjohn Thank you for the clean up! ISTIO_META_INCLUDE_INBOUND_PORTS can be removed as we chatted. But applicationPort is slightly out of control. It's a little more than it was designed as readiness only. I will let @diemtvu to confirm

**Comment by howardjohn** [comment]
I think the failure is just a test flake

**Review by hzxuzhonghu — APPROVED** [review]

**Review by rshriram — APPROVED** [review]

**Comment by diemtvu** [comment]
/lgtm

FYI + @yangminzhu

**Comment by howardjohn** [comment]
@istio/wg-environments-maintainers please take a look

**Review by ayj — APPROVED** [review]

**Review by lambdai — APPROVED** [review]
Thank you!

**Review by ericvn — APPROVED** [review]

**Pull request merged**
