### PR TITLE
No delta for grpc XDS, no envoy prometheus fetching.

### PR DESCRIPTION
**Pull request by costinm**
**Please provide a description of this PR:**

Fixes https://github.com/istio/istio/issues/38916 - grpc listener gets disabled by delta.

Also removes the continuous error message about pulling envoy metrics.

### CODE REVIEW

**Review by adiprerepa — APPROVED** [review]

**Review by vince-0202 — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]
LGTM. but seems we lack proxyless test

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
