### PR TITLE
update go-control-plane to 0.8.0

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by howardjohn** [comment]
/lgtm

We may add initial_fetch_timeout option which requires updating this so this will be useful for pilot. As an extra data point, I updated this locally to test out that option and things seemed to run fine

**Comment by howardjohn** [comment]
@kyessenov this has some merge conflicts

**Comment by howardjohn** [comment]
@kyessenov can you rebase this?

**Comment by kyessenov** [comment]
Done

**Pull request merged**
