### PR TITLE
move to golangci unused

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

pre-step of https://github.com/istio/common-files/pull/672

### CODE REVIEW

**Comment by ericvn** [comment]
Can we remove the `common-files` change now that we know things will pass with the forth coming change. Or is the common-files change needed to get things to pass now?

**Review by ericvn — APPROVED** [review]
Approving from a T&R perspective

**Review by howardjohn — APPROVED** [review]
nice

**Pull request merged**
