### PR TITLE
Add perfcheck.sh for running Go benchmarks with baselines.

### PR DESCRIPTION
**Pull request by ozevren**
The script has self-explanatory comments.
Also updating the il/interpreter benchmarks as an example to use the new baseline model.

### CODE REVIEW

**Comment by ozevren** [comment]
Hey @yutongz . Any feedback? I believe I need your approval/lgtm to be able to check into the /bin folder?

Thanks

**Comment by ozevren** [comment]
@ldemailly , Any feedback?

**Comment by ldemailly** [comment]
Happy to get this in and rev it up later: I do have questions:

isn't the timing info dependant on where you run the benchmark ?

can we maybe normalize the numbers based on some fix benchmark first ?

also does it work/run from a mac ? (glancing at the awk etc they seem pretty standard but did you try ?)


/hold cancel
/lgtm

**Comment by ozevren** [comment]
isn't the timing info dependant on where you run the benchmark ?
Yes, it is extremely timing dependent. That's why it needs some bake time before it can graduate to be a gate.

can we maybe normalize the numbers based on some fix benchmark first ?
That is my main plan. Implement a "standard" benchmark and use its numbers to create a time dilation factor. I am still not sure about the error margin though.

also does it work/run from a mac ? (glancing at the awk etc they seem pretty standard but did you try ?)

Yup, that is how started developing and tested with CircleCI. (I was using bc for floating point, but had to switch to awk since bc is not available on CircleCI).

**Pull request merged**
