### PR TITLE
Fix problematic `if`s and `while`s in shell scripts

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by Tahler** [comment]
Oh thanks for catching this!

I caused this issue in [this commit](https://github.com/istio/istio/commit/51e762b0c55b203e3c5855a34518522edfd6a2db#diff-71308222e525f5ff137b91be32b49db6). Notice that all the instances which previously used the `!=` operator (i.e. `if [[ $? != 0 ]]; then`) were improperly changed. I'll make a PR to fix all those issues.

**Comment by Tahler** [comment]
Actually I just added another commit to your PR. Again, thanks for catching this!

**Comment by jwendell** [comment]
@Tahler while on that I think you could also fix the duplicated `while`s, for example [here](https://github.com/istio/istio/commit/51e762b0c55b203e3c5855a34518522edfd6a2db#diff-b501389642563d61dc2cda852f357b5aR38) and [here](https://github.com/istio/istio/commit/51e762b0c55b203e3c5855a34518522edfd6a2db#diff-b501389642563d61dc2cda852f357b5aR64)

**Comment by Tahler** [comment]
@jwendell I don't think I understand what you're suggesting. Are you suggesting to extract a function and have both while loops call that function?

**Comment by jwendell** [comment]
@Tahler you replaced `while [ $? -ne 0 ]; do` with `! kubectl get pods -n kube-system | grep kube-proxy |  grep Running > /dev/null; do` but forgot to remove this `kubectl` command from within the `while` loop (last command, just before `done`).

Thus it is being executed twice.

**Pull request merged**
