### PR TITLE
Fixed stsPort naming in bootstrap files

### PR DESCRIPTION
**Pull request by gargnupur**
Signed-off-by: gargnupur <gargnupur@google.com>

Fixed stsPort naming in bootstrap files

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by mandarjog** [comment]
Thanks for this. Is there a test?

**Comment by gargnupur** [comment]
> Thanks for this. Is there a test?

Not yet.. I am working on one.. 

@howardjohn , @bianpengyuan : I don't think we enable sts in our tests by default? Because I was working on tracing e2e tests and didn't see any failure there...

**Comment by mandarjog** [comment]
sts will only be enabled in asm tests.

**Comment by gargnupur** [comment]
> sts will only be enabled in asm tests.

Okay will add tests there...

**Review by bianpengyuan — APPROVED** [review]

**Review by richardwxn — APPROVED** [review]

**Pull request merged**
