### PR TITLE
fix duplicated warning message for operator install command.

### LINKED ISSUE #28527: istioctl install: Duplicate warning: cluster does not support third party JWT authentication
May be caused by https://github.com/istio/istio/pull/28253

If you install istio, the actual message for showing which version and components are being installed is hidden between the JWT warning and is hard to read..

```
$ istioctl install --revision=1-9-0 --set hub=gcr.io/istio-testing -d manifests/
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT.
See https://istio.io/v1.9/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
This will install the Istio 1.9.0 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT.
See https://istio.io/v1.9/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                        
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod-1-9-0
```

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/28527

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by shamsher31 — APPROVED** [review]
Thanks for the quick fix. works fine now.

```
$ istioctl install --revision=1-9-0 --set hub=gcr.io/istio-testing -d manifests/
This will install the Istio 1.9.0 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/v1.9/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                                                              
✔ Istiod installed                                                                                                                                  
✔ Ingress gateways installed                                                                                                                        
✔ Installation complete    
```

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
