### PR TITLE
Minimize vmlinux.h for ebpf redirection

### PR DESCRIPTION
**Pull request by PlatformLC**
**Please provide a description of this PR:**

Part of #43525: Minimize vmlinux.h. Keep only used part. Should add cared about parts manually on demand in future.

### CODE REVIEW

**Review by kebe7jun — COMMENTED** [review]
How does this deal with the big endian and the small endian?

Although we don't seem to be using those fields for a while(like: iphdr.ihl).

**Comment by bleggett** [comment]
> Curious if it's a manual minimization process or something automatic that we can add to `make gen` for example?

It is, AFAIK, entirely manual. I would be happy with an automated process but that would  be relatively tricky to do/there are no extant tools.

**Review by howardjohn — APPROVED** [review]

**Comment by bleggett** [comment]
> How does this deal with the big endian and the small endian?
> 
> Although we don't seem to be using those fields for a while(like: iphdr.ihl).

I don't think it supports BE archs - but also Istio itself doesn't ship any artifacts for BE archs ATM, so it's not a big concern ATM IMO.

**Comment by PlatformLC** [comment]
> > How does this deal with the big endian and the small endian?
> > Although we don't seem to be using those fields for a while(like: iphdr.ihl).
> 
> I don't think the eBPF impl supports BE archs period since we aren't using the BE/LE stubs `bpf2go` generates - but also Istio itself doesn't ship any artifacts for BE archs, so it's not a big concern IMO.

Initially, I thought it could be hanlded by btf relocation such as `BPF_CORE_READ_BITFIELD` because btf makes it visible what's the compiled endian and what's the runtime endian,  but reality seems not what I thought, refer to [slack](https://cilium.slack.com/archives/C4XCTGYEM/p1678152310024069)

**Comment by PlatformLC** [comment]
> > Curious if it's a manual minimization process or something automatic that we can add to `make gen` for example?
> 
> It is, AFAIK, entirely manual. I would be happy with an automated process but that would be relatively tricky to do/there are no extant tools.

Yes, it's entirely manual, grab what is used from generated one.

**Pull request merged**
