### PR TITLE
ARM additions cleanup: removal of istioctl-linux

### PR DESCRIPTION
**Pull request by dave93cab**
@sdake @howardjohn 

Clean-up tasks from: https://github.com/istio/istio/pull/22381

Depends on: https://github.com/istio/release-builder/pull/179

### CODE REVIEW

**Comment by howardjohn** [comment]
I believe this will fail until https://github.com/istio/istio/pull/22630 merges as well

**Comment by dave93cab** [comment]
@sdake @howardjohn tests passed on this cleanup task

**Pull request merged**
