### PR TITLE
istioctl miss to append ipv6 domain when using istioctl pc route

### PR DESCRIPTION
**Pull request by zhlsunshine**
**Please provide a description of this PR:**
istioctl miss to append ipv6 domain when using istioctl pc route

IPv4 or dual-stack cluster
image

IPv6 only cluster
image

### CODE REVIEW

**Comment by zhlsunshine** [comment]
After the change, the ipv6 domain can also be displayed now:
image

**Review by liamawhite — COMMENTED** [review]
Thanks! Could you add some test cases for this?

**Comment by zhlsunshine** [comment]
> Thanks! Could you add some test cases for this?

Hi @liamawhite, I added some test cases for describeRouteDomains, thanks for your review!

**Review by liamawhite — APPROVED** [review]

**Pull request merged**
