### PR TITLE
update istio/api

### PR DESCRIPTION
**Pull request by guptasu**

### CODE REVIEW

**Comment by rshriram** [comment]
can you undo all the other unrelated changes to Gopkg.lock ? Its hard to identify what changed and what didn't

**Comment by guptasu** [comment]
@geeknoid @kyessenov re-lgtm please. Bot didn't like my chances, so I decided to re-base and try again.

**Comment by mandarjog** [comment]
@costin we need to standardize on the version of dep. this minor change ended up changing everything.

Old dep puts all sub packages on one line.

**Pull request merged**
