### PR TITLE
perf: disable endpoint UID if mixer is off

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

/assign @howardjohn

### CODE REVIEW

**Comment by howardjohn** [comment]
@kyessenov this broke multicluster test https://prow.istio.io/?type=postsubmit&job=istio-pilot-multicluster-e2e-master

**Comment by howardjohn** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1737d46]

goroutine 152 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).updateEDS(0xc0006a7600, 0xc000910000, 0x0)
	/home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:782 +0x1a6
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).AppendInstanceHandler.func1(0x1fad620, 0xc000910000, 0x0, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:772 +0x59
istio.io/istio/pilot/pkg/serviceregistry/kube.(*ChainHandler).Apply(0xc000627ec0, 0x1fad620, 0xc000910000, 0x0, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/queue.go:116 +0x82
istio.io/istio/pilot/pkg/serviceregistry/kube.(*queueImpl).Run(0xc00091af90, 0xc00061c7e0)
	/home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/queue.go:98 +0x121
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).Run.func1(0xc00061c7e0, 0xc0006a7600)
	/home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:274 +0x9d
created by istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).Run
	/home/prow/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:272 +0x61

```

**Comment by kyessenov** [comment]
Any clue why multi-cluster test depends on mixer?

**Comment by howardjohn** [comment]
I am not familiar with the test at all, but seems like maybe it doesn't have a meshconfig somehow?

**Pull request merged**
