### PR TITLE
Use StringMatch instead deprecated matcher types

### PR DESCRIPTION
**Pull request by kebe7jun**
**Please provide a description of this PR:**

`HeaderMatcher_PrefixMatch` and etc are deprecated.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by kebe7jun** [comment]
Wait for https://github.com/grpc/grpc-go/pull/6313

**Comment by wulianglongrd** [comment]
If I recall correctly, the test case here will still fail even though https://github.com/grpc/grpc-go/pull/6313 has been merged. Because grpc-go only implements StringMatch for RDS, not including RBAC's StringMatch([see here](https://github.com/grpc/grpc-go/blob/f2fbb0e07ebf3dd46aa641ee89c9f17e8083eaf6/internal/xds/rbac/matchers.go#L267)).

**Comment by howardjohn** [comment]
https://github.com/grpc/grpc-go/pull/6419 - may be ok now?

**Comment by wulianglongrd** [comment]
i think yes

**Pull request closed without merging**
