### PR TITLE
Bump jinja2 version

### PR DESCRIPTION
**Pull request by howardjohn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by craigbox** [comment]
Is this because a bot suggested it and that bot can't sign the CLA?

**Comment by howardjohn** [comment]
A bot suggested it in private since its a security update - but not one that tangibly impacts istio

**Comment by craigbox** [comment]
and in public too: https://github.com/istio/istio/pull/31591

**Comment by howardjohn** [comment]
Oops, didn't see that. It has the CLA signed so that one should work too

**Pull request closed without merging**
