### PR TITLE
<cmd/pilot-agent>: check node type

### PR DESCRIPTION
**Pull request by knightXun**
pilot-agent should check node-type,and give more accurate typo.

### CODE REVIEW

**Comment by knightXun** [comment]
@nmittler is Jenkins broken again? so sad

**Comment by nmittler** [comment]
@knightXun after you fix linter error it should be good to go.

**Comment by knightXun** [comment]
@nmittler i will wait jenkins works fine

**Comment by knightXun** [comment]
ping @nmittler

**Pull request merged**
