### PR TITLE
limit the concurrency of generating outbound clusters to avoid OOM

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### CODE REVIEW

**Comment by ymesika** [comment]
I don't think your channel size will resolve OOM problem because although you limit the rate of generating the clusters they are still added to the slice and kept in-memory.
So basically for a large number of clusters it may explode even though you add control of the rate of filling that `clustersByNamespace` slice.
Is it right?

**Comment by hzxuzhonghu** [comment]
I mean the same thing as @ymesika . We store all clusters by namespace. So i donot know how rate limit can reduce the OOM risk.

**Comment by YaoZengzeng** [comment]
@ymesika @hzxuzhonghu Agree with both of you.

I find @costinm add the TODO comment here https://github.com/istio/istio/commit/ac78a552afbb6a60a87ac66ddcfd200043a0ad86#diff-46efcd7bf16775b34a39b492c27c8f19R57
maybe he could give us an answer.

Maybe function `buildOutboundClusters` will consume a lot of temp memory?

**Pull request closed without merging**
