### PR TITLE
Add buggy bookinfo versions for demos and the tutorial

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
Add buggy versions of productpage and ratings, to demonstrate Kubernetes liveness probes, Istio retrites, timeouts, outlier detection and rate limiting, in the upcoming Istio tutorial https://github.com/istio/istio.io/pull/1035.

The following versions are added:

1. `ratings v-unhealthy`, used in [Liveness probes with Kubernetes](https://deploy-preview-1035--preliminary-istio.netlify.com/docs/tutorial/liveness-probes-with-kubernetes/)
1. `ratings v-delayed`, used in [Timeouts with Istio](https://deploy-preview-1035--preliminary-istio.netlify.com/docs/tutorial/timeouts-with-istio/)
1. `ratings v-faulty`, used in [Retries with Istio](https://deploy-preview-1035--preliminary-istio.netlify.com/docs/tutorial/retries-with-istio/)
1. `ratings  v-unavailable`, used in [Outlier detection with Istio](https://deploy-preview-1035--preliminary-istio.netlify.com/docs/tutorial/outlier-detection-with-istio/)
1.  `productpage v-flooding`, used in [Rate limiting with Istio](https://deploy-preview-1035--preliminary-istio.netlify.com/docs/tutorial/rate-limiting-with-istio/)

### CODE REVIEW

**Comment by howardjohn** [comment]
Didn't get a chance to read the doc pr, will these be installed on demand? Just wondering because adding 5 deployments to the base bookinfo wouldn't be great for people with small clusters (and makes things more complicated)

**Comment by vadimeisenbergibm** [comment]
@howardjohn These will be installed on demand only, the default deployment of bookinfo will not include these pods.

**Comment by GregHanson** [comment]
for tracking purposes, unit test failures related to https://github.com/istio/istio/issues/13668

**Comment by vadimeisenbergibm** [comment]
@howardjohn  Could you please add LGTM label?

**Pull request merged**
