### PR TITLE
Added a new install-crds flag to Pilot Discovery. 

### PR DESCRIPTION
**Pull request by kdillane**
This flag when passed enables creation of CRDs when they cannot be detected.  In the case of a failure during CRDs creation, the call to deregister CRDs has been removed.

### CODE REVIEW

**Comment by kdillane** [comment]
I've created this new PR in favor of a previous PR: https://github.com/istio/istio/pull/8691.  I'm having trouble with the Circle CI testing, but have verified that the HEAD commit for the release-1.0 branch also has failures when I execute it.  https://circleci.com/workflow-run/80b1e823-e0e3-4c9c-8c99-e44a84d66639

**Comment by kdillane** [comment]
Looking at my test runs, the failure appears to be related to Circle CI hardware.  My account does not have access to xlarge hosts to run build/test.

**Comment by ayj** [comment]
cc @costinm @rshriram - is there some limitation on non-org members running circeci tests? It looks like xlarge hosts may be required?

**Comment by rshriram** [comment]
Yes.. you have to be part of the org though. That said, a test failure can be reproduced locally as well right?

**Comment by kdillane** [comment]
No test failure is reproduced locally. I have separate issues because I’m testing on a Mac

On Sep 20, 2018, at 1:08 PM, Shriram Rajagopalan <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes.. you have to be part of the org though. That said, a test failure can be reproduced locally as well right?

**Comment by rshriram** [comment]
I think you need to rebase. These tasks don’t exist in our circleci (nightly etc)

**Comment by kdillane** [comment]
The tests all pass except 1:

--- FAIL: TestCreateSelfSignedIstioCAWithSecret (0.00s)
	ca_test.go:167: Failed to create a self-signed CA Options: failed to create CA KeyCertBundle (cannot verify the cert with the provided root chain and cert pool)

**Comment by kdillane** [comment]
It seems unlikely that it is related to my changes.

**Comment by kdillane** [comment]
Likely culprit: https://github.com/istio/istio/pull/8894

**Comment by hklai** [comment]
@kdillane   is this needed in master? If so, could you create a cherrypick PR?

**Comment by hklai** [comment]
@kdillane Thanks!

**Pull request merged**
