### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by drivebyer**
**Please provide a description of this PR:**

This PR fixed typo in comment.

### CODE REVIEW

**Review by morvencao — APPROVED** [review]

**Review by morvencao — COMMENTED** [review]
/ok-to-test

**Comment by drivebyer** [comment]
According to the [details](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38700/release-notes_istio/1521488012398039040), I think there is no user facing changes in this PR.

hi @morvencao , can you add label `release-notes-none` to this PR? I can not add label by myself, becouse I am not a Org member yet.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
