### PR TITLE
Enable gateway cluster config filtering 

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

set PILOT_FILTER_GATEWAY_CLUSTER_CONFIG=true

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@howardjohn

**Comment by howardjohn** [comment]
I think we need to fix https://github.com/istio/istio/issues/29131 first. Otherwise users will get 503s

**Comment by hzxuzhonghu** [comment]
I thought is had been fixed

**Comment by hzxuzhonghu** [comment]
Will double check

**Pull request closed without merging**
