### PR TITLE
Remove deprecated `istio_cni` values from pilot chart

### PR DESCRIPTION
**Pull request by bleggett**
The `istio_cni` values are strictly redundant with/replaced by `pilot.cni` values, and [were explicitly marked deprecated 2+ releases ago](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L513) in PR: https://github.com/istio/istio/pull/49495

See also: https://github.com/istio/istio/issues/49290

Since having multiple sets of values that do the same thing really complicates what is already our most complex chart, and generally makes it hard to see what is and is not actually needed, and we have met the 2-release requirement for removal after deprecation, removing these values that we already decided to remove.

90% of this PR is gen-churn, the relevant bits are in the `istiod` chart.

### CODE REVIEW

**Comment by howardjohn** [comment]
It would have been nice to put this in https://github.com/istio/istio/blob/d8afdb4ce6eb4df55e6e3e859c833acecc6f673e/manifests/charts/istio-control/istio-discovery/templates/NOTES.txt#L28 in retrospect

**Comment by bleggett** [comment]
> It would have been nice to put this in
> 
> https://github.com/istio/istio/blob/d8afdb4ce6eb4df55e6e3e859c833acecc6f673e/manifests/charts/istio-control/istio-discovery/templates/NOTES.txt#L28
> in retrospect

Yeah - I agree it would have been.

I didn't realize we had that actually (or you told me about it and I forgot, which is also very possible).

Maybe I should throw a note to that effect into `manifests/charts/UPDATING-CHARTS.md`

**Comment by bleggett** [comment]
@howardjohn lmk what you think about the UPDATING_CHARTS.md changes I added - if you'd prefer I can move those to a separate PR.

**Review by howardjohn — APPROVED** [review]

**Comment by diranged** [comment]
@bleggett @howardjohn,
  Just a suggestion... sometimes people miss these deprecation notices (or just don't realize we're using a deprecated setting). Silently removing the setting caused new pod launches in our [environment to fail](https://istio.slack.com/archives/C37A4KAAD/p1736972683247719). If the chart had _failed when it detected the `istio_cni` key_ though, then our deployment of the control plane would have told us right away that we had a problem. How do you feel about changing future chart deprecations so that instead of just removing the setting and changing the behavior, we do something like this:

* `v1`: has `istio_cni` setting
* `v2`: introduces `pilot.cni` setting, and a _warning_ when `istio_cni` is used
* `v3`: introduces explicit [fail](https://austindewey.com/2018/12/28/helm-tricks-input-validation-with-required-and-fail/) when `istio_cni` setting is detected
* `v4`: remove `istio_cni` setting

  Thoughts?

**Comment by bleggett** [comment]
> @bleggett @howardjohn, Just a suggestion... sometimes people miss these deprecation notices (or just don't realize we're using a deprecated setting). Silently removing the setting caused new pod launches in our [environment to fail](https://istio.slack.com/archives/C37A4KAAD/p1736972683247719). If the chart had _failed when it detected the `istio_cni` key_ though, then our deployment of the control plane would have told us right away that we had a problem. How do you feel about changing future chart deprecations so that instead of just removing the setting and changing the behavior, we do something like this:
> 
>     * `v1`: has `istio_cni` setting
> 
>     * `v2`: introduces `pilot.cni` setting, and a _warning_ when `istio_cni` is used
> 
>     * `v3`: introduces explicit [fail](https://austindewey.com/2018/12/28/helm-tricks-input-validation-with-required-and-fail/) when `istio_cni` setting is detected
> 
>     * `v4`: remove `istio_cni` setting
>       Thoughts?

I am a little leery of introducing `fail` since that creates an upgrade experience that isn't like any of other other stuff

(that is, a relnotes-based `deprecation`, wait 2 releases (during which the old way continues to work), then remove)

I do think and agree that going forward we should mention all values removes in an `upgradeNote` as well as a `releaseNote`, for the release where they are removed.

**Comment by diranged** [comment]
> I am a little leery of introducing `fail` since that creates an upgrade experience that isn't like any of our other stuff.

I posted on slack - but for consistency I will put the post here:


So I don’t love `fail()` either … but I would argue that it’s a better experience than a silent change on the backend. While release notes are great, and of course everyone should read them, that just doesn’t always happen. For example, In the [Istio 1.24.0 Change Notes page](https://istio.io/latest/news/releases/1.24.x/announcing-1.24/change-notes/) , you have to search for the word “deprecated” and it’s sprinkled across two different sections (“Installation” and “Traffic Management”.. Worse, I missed the “Deprecated” notice in 1.22 .. so in 1.24 I have to also search for “Removed”.

In our environment we rely heavily on tools like RenovateBot to provide us with automated software updates - we’re a tiny team that manages thousands of nodes and dozens of Kubernetes clusters … as I'm sure you can relate, keeping up to date on all of the different components in the cluster could be nearly a full time job on its own.

If we had received a RenovateBot PR that installed our Istio 1.24 chart … and the build failed with a big error, then it would have been an immediate pointer to a deprecation we missed. From my perspective, an immediate `fail("The .Values.istio_cni setting has been removed. See .Values.pilot.cni instead")` would have been awesome. We get these types of deprecation failures on other charts all the time and it’s always more welcome than a subtle behavior change that we aren’t expecting.

(Re: `values.schema.json` … we leverage that quite a bit as well, and a well-formed schema file would have also caught this .. but its effectively the same as the fail() call… its an immediate failure either way, which I think is the right answer.)

**Comment by bleggett** [comment]
> (Re: `values.schema.json` … we leverage that quite a bit as well, and a well-formed schema file would have also caught this .. but its effectively the same as the fail() call… its an immediate failure either way, which I think is the right answer.)

I'd love to have this for other reasons, and I think it's more generally useful than selectively peppering `fail()` in charts, so I'd welcome a PR to add this.

**Comment by howardjohn** [comment]
FWIW the schema has some problems on `.global` usage we ran into in the `gateway` chart

**Comment by bleggett** [comment]
> FWIW the schema has some problems on .global usage we ran into in the gateway chart

Oh interesting. Presumably it doesn't have problems with normal Helm globals specifically, but our unique munging of them?

**Comment by howardjohn** [comment]
Not really, its just broken IMO https://github.com/helm/helm/issues/10392

**Comment by bleggett** [comment]
> Not really, its just broken IMO [helm/helm#10392](https://github.com/helm/helm/issues/10392)

Eh, that's not a major concern if we can fix it with a oneliner like this: https://github.com/istio/istio/pull/36896

`global` is always in scope in Helm, the interaction in the composition scenario (which we don't do) is a little weird, but makes sense.

IIUC it's only a big problem if you are trying to use `values.schema.json` to _prevent_ the use of globals in subcharts (which we admittedly have a unique problem with, since we historically have made chart-local values global, and regretted it)

**Comment by howardjohn** [comment]
The fix is basically "do not validate when used as a subchart" so its not
really a fix...

**Comment by bleggett** [comment]
> The fix is basically "do not validate when used as a subchart" so its not really a fix...

You can still explicitly allowlist `globals` into subcharts via `values.schema.json`, correct? 

It's only the `null` case it doesn't cover - I have _no_ globals in my subchart (or I do, but I don't want you using them) and I want validation to `fail` if you supply them.

Either way, I think adding `values.schema.json` to the CNI chart would be generally useful even with that caveat, so I don't have a problem with it.

**Pull request merged**
