### PR TITLE
Update Proxy SHA

### PR DESCRIPTION
**Pull request by gargnupur**
Update Proxy SHA : Automated task is failing https://github.com/istio/istio/pull/28982 and I am aware of one telemetry change that needs fixing

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by richardwxn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]

**Comment by bianpengyuan** [comment]
Looks like envoy removes a command arg used by Istio:
```
2020-11-23T18:51:59.791009Z	info	Envoy command: [-c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-egressgateway --service-node router~10.244.0.9~istio-egressgateway-6cb99868c6-7dn7j.istio-system~istio-system.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3 --log-format-prefix-with-location 0 --log-format %Y-%m-%dT%T.%fZ	%l	envoy %n	%v -l warning --component-log-level misc:error]
PARSE ERROR: Argument: --log-format-prefix-with-location
             Couldn't find match for argument
```

**Comment by howardjohn** [comment]
I will take this over

**Review by lei-tang — APPROVED** [review]

**Pull request merged**
