### PR TITLE
Fix multi secret update did not handle cluster delete

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fixed a bug, when secret update, should take into consideration the clusters that are being deleted in the secret. 
For example:

Original secret:

```
data:
  cluster1: "kubeconfig1"
  cluster2: "kubeconfig2"
```
Updated secret:

```
data:
  cluster1: "kubeconfig1"
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@istio/wg-networking-maintainers This is ready to go.

**Review by stevenctl — COMMENTED** [review]
Seems ok, confused how "update" is handled now. Also the new structure makes it harder to check for duplicate clusters across multiple secrets, can we add a way to handle that before merging?

**Comment by hzxuzhonghu** [comment]
Do you mean it uses `addSecret` to handle update? I donot change that in this pr, if you feels that, i can do.

**Comment by stevenctl** [comment]
It seems your PR makes it so if we have an update, we do the following:

```
delete(cluster)
update(cluster)
```

`update` is implemented as:


https://github.com/istio/istio/blob/9a4c8ddd2bcfc4c100472c5954c38a7791b69a23/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L295-L300

So if I understand correctly, this means we'll call `delete` twice, and I'm assuming the second call will fail.

**Comment by hzxuzhonghu** [comment]
@stevenctl PTAL

```
	for clusterID, kubeConfig := range s.Data {
		action, callback := "Adding", c.addCallback
		if prev := c.cs.Get(secretKey, clusterID); prev != nil {
			action, callback = "Updating", c.updateCallback
			// clusterID must be unique even across multiple secrets
			// TODO： warning
			kubeConfigSha := sha256.Sum256(kubeConfig)
			if bytes.Equal(kubeConfigSha[:], prev.kubeConfigSha[:]) {
				log.Infof("%s cluster_id=%v from secret=%v: (kubeconfig are identical)", clusterID, secretKey)
				continue
			}
		}
```
The cluster in the secret will not be deleted above, because we only delete non existing cluster at the first step.

**Comment by hzxuzhonghu** [comment]
/test unit-tests_istio


ping @stevenctl

**Review by stevenctl — APPROVED** [review]
I see, thanks for the fix!

**Pull request merged**
