### PR TITLE
Fix envoy binary used for tests on Mac

### PR DESCRIPTION
**Pull request by holgero**
Download darwin binary when running on darwin. Since #5450 only
linux binaries were downloaded (as GOOS defaults to `LOCAL_OS`).

Co-authored-by: Jan von Loewenstein <jan.von.loewenstein@sap.com>

### CODE REVIEW

**Comment by holgero** [comment]
Hi @costinm,
We tried `export GOOS=linux ; make docker.proxy` and ran a bash via `docker run` in the container. There we executed the envoy binary successfully.

**Comment by costinm** [comment]
I think 'make docker.proxy' should work - without GOOS=linux.

But I suppose if it is documented clearly it may be ok - is there any doc for mac developers ? If not can you  maybe add one ? 

Sorry - I'm using linux laptop/desktop. 

We do mac building in CircleCI  - maybe adding a small config with just build would improve things.

**Comment by sbezverk** [comment]
@costinm before #5450  I could not build proxy linux image  from mac, even with GOOS set to linux. It was using LOCAL_OS var to to set type of envoy binary. 
I have not tested this PR, but I would appreciate some logs proving that with this PR, correct linux envoy gets added to proxy image with GOOS set to linux.

**Comment by andraxylia** [comment]
@PiotrSikora told me it is enough to cd to istio/proxy and do "bazel build //src/..."

**Comment by loewenstein** [comment]
@sbezverk Here is the log you requested (executed in the proxy container):
```bash
root@0c11775cc924:/usr/local/bin# ./envoy
[2018-05-15 08:56:28.983][15][info][main] external/envoy/source/server/server.cc:203] initializing epoch 0 (hot restart version=9.200.16384.127.options=capacity=16384, num_slots=8209 hash=228984379728933363)
```

**Comment by loewenstein** [comment]
@costinm We just checked again. Without `GOOS=linux` the pilot-agent in the proxy container appears to be a darwin executable. I.e. we get an exec format error.

As far as we see it this is not introduced by this PR, but rather the unfortunate state of release-0.8/master.

**Comment by sbezverk** [comment]
After your PR got merged, it is broken again on my mac:


GOOS=linux; make build


+ DARWIN_ENVOY_DIR=/var/folders/8r/m13mcmf15z3d0dq7d412rnph0000gn/T/tmp.vGmn3yHm

+ pushd /var/folders/8r/m13mcmf15z3d0dq7d412rnph0000gn/T/tmp.vGmn3yHm

/var/folders/8r/m13mcmf15z3d0dq7d412rnph0000gn/T/tmp.vGmn3yHm ~/go/src/istio.io/istio

+ echo 'Downloading envoy darwin binary:  https://storage.googleapis.com/istio-on-macos/releases/0.7.1/istio-proxy-0.7.1-macos.tar.gz'

Downloading envoy darwin binary:  https://storage.googleapis.com/istio-on-macos/releases/0.7.1/istio-proxy-0.7.1-macos.tar.gz

+ https://storage.googleapis.com/istio-on-macos/releases/0.7.1/istio-proxy-0.7.1-macos.tar.gz

bin/init.sh: line 151: https://storage.googleapis.com/istio-on-macos/releases/0.7.1/istio-proxy-0.7.1-macos.tar.gz: No such file or directory

+ tar xz

make: *** [/Users/sbezverk/go/out/darwin_amd64/release/istio_is_init] Error 1

As you can see instead of picking up linux binary for envoy, it tries to get Darwin’s envoy bits.

Could you explain, how your change should help here??

Serguei

**Comment by holgero** [comment]
Hi @sbezverk, 
Sorry for the inconvenience. We noticed this problem ourselves, too and fixed it in #5665. We missed that problem, as we tested the fetching of binaries only from scratch. The fact that it downloads a mac binary that is used for local tests only, even if you just run `GOOS=linux; make build` is due to the fact that all binary downloads are in one shell script (instead of having them as targets with proper dependencies).

**Pull request merged**
