### PR TITLE
Deny h2c upgrade traffic around the code base

### PR DESCRIPTION
**Pull request by howardjohn**
In the Go upstream http2 library, a DOS vector was introduced. The fix for the DOS introduces a request smuggling vulnerability. See https://github.com/golang/go/issues/56352.

All of these are related to h2c upgrades; we don't actually care about this - we only want HTTP/2 prior knowledge and HTTP/1.1.

This PR introduces a wrapper around the h2c library denying h2c upgrades. It also enforces via linting that this is used.

**Please provide a description of this PR:**

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Review by ramaraochavali — APPROVED** [review]

**Comment by howardjohn** [comment]
ill move the linter change to common-files btw, once it merges.

**Review by hzxuzhonghu — COMMENTED** [review]
great catch

**Comment by zirain** [comment]
need backport to v1.16?

**Pull request merged**
