### PR TITLE
Add injection ConfigMap watcher

### PR DESCRIPTION
**Pull request by tbarrella**
As part of #27707

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
It looks this is not complete

**Comment by tbarrella** [comment]
/retest
Integrating it is done in the next PR; I didn't want to make PRs that are too big

**Pull request merged**
