### PR TITLE
add thread safety to contextgraph cache

### PR DESCRIPTION
**Pull request by adiprerepa**
Add thread safety to a cache in contextgraph. 
In https://github.com/istio/istio/blob/master/mixer/pkg/adapter/adapter.go#L50, it is guaranteed work will be done on a separate goroutine, bringing up the issue of thread safety. This PR adds thread safety to the entitycache and edgecache.

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Thanks for the contribution! Are you currently using context graph product, or is this a change based on interest? Mixer is in deprecation mode, and we are not making change to it except critical fix. If you are using context graph product, please consider using in-proxy solution instead: https://github.com/istio/istio/wiki/Proxy-Based-Stackdriver-Telemetry

**Comment by adiprerepa** [comment]
@bianpengyuan this was out of interest, I know mixer is being deprecated but maybe people who use this might find it helpful? Idk, if it's not worth it I can close it.

**Comment by bianpengyuan** [comment]
This code path is not really used in production, so I think we should be fine without it.

**Pull request closed without merging**
