### PR TITLE
echo: add Java package name and outer class name to be used in grpc java testing

### PR DESCRIPTION
**Pull request by sanjaypujare**
**Please provide a description of this PR:**
We want to use the echo.proto in grpc java interop tests with Istio. The generated code should go into designated package and outer classname.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by sanjaypujare** [comment]
CC @costinm @stevenctl - this is for grpc-java's interop testing with Istio. Note that we import protos like this from their original source repo instead of making copies and modifying them locally. So to the extent possible we would like the original to reflect our requirements

**Comment by sanjaypujare** [comment]
Thanks @howardjohn for the approval. What else needs to happen to finish tests and then merge the PR?

**Comment by howardjohn** [comment]
/ok-to-test

forgot this

**Pull request merged**
