### PR TITLE
Update bookinfo gateway selector for Helm

### PR DESCRIPTION
**Pull request by nshankar13**
Signed-off-by: nshankar <nshankar@microsoft.ghe.com>

**Please provide a description of this PR:**

Updates the bookinfo-gateway selector with a comment on what the default ingress k8s pod selector is for Helm.

### CODE REVIEW

**Comment by nshankar13** [comment]
@kfaseela related to the previous PR: https://github.com/istio/istio.io/pull/12486

**Review by howardjohn — APPROVED** [review]

**Review by ericvn — APPROVED** [review]
Thanks.

**Pull request merged**
