### PR TITLE
Support appProtocol for iop components servicePorts

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Impl of https://github.com/istio/istio/issues/42759.
Needs to make sure only pass the pointer to the struct if `appProtocol` has a value, otherwise it will have regex errors.

### CODE REVIEW

**Comment by zirain** [comment]
is this part of v1.17?

**Comment by hanxiaop** [comment]
> is this part of v1.17?

@zirain Yes it is

**Comment by zirain** [comment]
can you add release notes?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
