### PR TITLE
Add new  helper package for `ptr`

### PR DESCRIPTION
**Pull request by howardjohn**
Port from ambient branch. This adds some simple helper functions for pointers

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
I am concerned this will cause error when misused, unlike rust generics, go does not support conditional type.

**Comment by howardjohn** [comment]
Can you explain how it can be misused?

**Comment by hzxuzhonghu** [comment]
Say there is a `type interface`, and also like you said a `cb function()`

**Comment by howardjohn** [comment]
I'm not sure I follow. This just takes a pointer to something. It's the same as 
```
x=something
&x
```
but 1 line `ptr.Of(something)`.

**Comment by hzxuzhonghu** [comment]
cannot get the address of some type

**Comment by howardjohn** [comment]
What types can you not get addresses of?

**Comment by howardjohn** [comment]
maybe a go playground example would help

**Comment by hzxuzhonghu** [comment]
https://go.dev/play/p/hCESt_aXYmm

**Comment by howardjohn** [comment]
https://go.dev/play/p/bIFWr2q_1NP

this is exact the purpose of this function, to allow us to do this in 1
line instead of 2

**Review by hzxuzhonghu — APPROVED** [review]
Make sense

**Review by hanxiaop — APPROVED** [review]
lgtm

**Pull request merged**
