### PR TITLE
Dedup envoy lbEndpoint build

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
buildEnvoyLbEndpoint and toEnvoyEndpoint are very similar, so this pr removed the latter, and also some related utils function.

### CODE REVIEW

**Comment by howardjohn** [comment]
Do you mind providing a description? Since no tests changed I am not really sure what this is about

**Comment by hzxuzhonghu** [comment]
@howardjohn Added in the pr desc, and will have a look at the ut failure.

**Comment by hzxuzhonghu** [comment]
More TestController_GetPodLocality  flakes recently, not sure why

**Pull request merged**
