### PR TITLE
Admission webhook fix

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
For admission v1 reponse, not patchtype can be set. Previously we set it to "", should be nil.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Fix: #26876

**Comment by tariq1890** [comment]
Thanks @hzxuzhonghu @howardjohn

**Comment by hzxuzhonghu** [comment]
>can we update the test to catch this type of thing maybe?

Do we want to change the order to [v1, v1beta1] in this release, then it will be covered by many cases.

**Comment by howardjohn** [comment]
if we backport this we can do that. We need to make sure N-1 version
supports v1 I think, so we can have seemless upgrade?

**Pull request merged**
