### PR TITLE
rename test file

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
As in windows, a file name is not allowed to contain `*`. So when i git pull the latest code, it failed with error.

### CODE REVIEW

**Comment by pitlv2109** [comment]
Could you also cherry pick this onto release-1.4 branch?

**Comment by pitlv2109** [comment]
I think sometimes cherry-pick bot doesn't detect command after the PR has been merged, so it's worth checking it.

**Comment by hzxuzhonghu** [comment]
opened #18686

**Pull request merged**
