### PR TITLE
add quote for node selector value.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.

resolve: https://github.com/istio/istio/issues/16661
- add quote for node selector value.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
This doesn't need to be backported?

**Comment by morvencao** [comment]
I think we need this for release 1.3

**Comment by rlenglet** [comment]
Adding the label after the PR has been merged has no effect. You need to add a comment with `/cherrypick release-1.3`.

**Pull request merged**
