### PR TITLE
Fix lint warning on unused methods. 

### PR DESCRIPTION
**Pull request by xiaolanz**
**What this PR does / why we need it**:
address #1453
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
circle ci failed so I updated the branch (which wouldn't be necessary with just prow) to see if it passes with new circleci scripts

/lgtm

**Comment by mandarjog** [comment]
@jmuk https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/1672/istio-presubmit/3244/ fails with gencode check-in checks.

**Comment by jmuk** [comment]
This is weird, I don't see `mixer/template/authz` things reported in the log. Maybe somethings are out-of-sync?  Please rebase with the master.

**Comment by jmuk** [comment]
I don't see anyone referring to `mixer/template/authz` things around this PR; so here's the theory: presubmit bot keeps `bazel-genfiles` among the builds, and `./bin/bazel_to_go.py` collects the autogen files from that directory; as the consequences, some unrelated PR can cause this problem on other PRs randomly?  cc: @yutongz 

For the meanwhile, I'll create a PR to remove the presubmit failure.

**Comment by sebastienvas** [comment]
Updating the BUILD file would have been good.

**Comment by geeknoid** [comment]
Yeah, I just saw that. I've got a PR to fix that.

**Comment by guptasu** [comment]
@geeknoid @sebastienvas QQ: without the BUILD file change (which is not fixed by @geeknoid's followup commit) any idea why this was not a build failure and the [presubmit logs didn't catch it.](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/1672/istio-presubmit/120/) . It seems such changes should have been caught easily via some simple gate keepers.

**Comment by sebastienvas** [comment]
I fixed it in my PR. @guptasu that's a good question. Do we call bazel run //:gazelle at some point in the script? That would have fixed it. I think that presubmit is very complicated, we should be calling bazel build //.. If not I have no clue.

**Comment by guptasu** [comment]
@sebastienvas Let's take this outside this PR, we can investigate this tomorrow. I do see we are running [`bazel build //...`](https://storage.googleapis.com/istio-prow/pull/istio_istio/1672/istio-presubmit/120/build-log.txt), However I am not sure why we are not failing the build.

**Pull request merged**
