### PR TITLE
Disable telemetry v2 contents for minimal profile

### PR DESCRIPTION
**Pull request by linsun**
They should not be part of the minimal profile per our doc:  https://istio.io/latest/docs/setup/additional-setup/config-profiles/

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
In my opinion the doc is wrong, not the code. @mandarjog and @costinm will probably have opinions though

**Comment by mandarjog** [comment]
Since we have already defined minimal == traffic mgt only`, I think removing it from here is fine.

Many users do consider telemetry a core part of Istio, so I would like to revisit the decision if `minimal` should exclude it.

**Comment by howardjohn** [comment]
Just because the doc says it doesn't mean its valid IMO. I think the real history is that with microservices, Pilot *was* the minimal, and then someone took pilot ---> "traffic management" and documented that.

If we revisted the decision we could just as easily declare just telemetry as "minimal" - this is in fact more minimal than traffic management as we can deploy no CRDs.

Is there any reason we do not want telemetry, other than to match with the doc?

**Comment by mandarjog** [comment]
I have assumed that `minimal` profile proposal was reviewed and telemetry excluded. If that is not the case then we should not exclude it.

**Comment by howardjohn** [comment]
Minimal has been around for a long time and has not be re-evaluated post-Istiod/telemetry v2

**Comment by linsun** [comment]
When we first introduced minimal profile in istio 1.0/1.1 timeframe, it is targeted for traffic Mgmt only.  I think telemetry v2 stuff unexpectedly got in because it is part of discovery by default now.  My minimal profile installs a lot faster without it.

**Comment by howardjohn** [comment]
I don't think "install time" is a goal of the minimal profile, rather to have minimal runtime dependencies. Is install time a concern? On my machine install completes it ~3s, with the full config

**Comment by linsun** [comment]
@howardjohn install is a side benefit... may not be a huge deal for you, but for me min profile takes 14 s without telemetry v2... with telemetry v2 sometimes takes over 1+ mins.

I think the main thing is the intention of min profile which is for Istio's traffic Mgmt only.

**Comment by howardjohn** [comment]
I don't agree with you that "the intention of min profile which is for Istio's traffic Mgmt only". I think the intention is that it is minimal, and then later someone decided to document "traffic mgmt only".

Also, it taking 1+min is a bug somewhere - its literally just `kubectl apply -f` a few objects..

**Comment by mandarjog** [comment]
The options should only add a few Envoyfilter configurations. Does this 1 minute include time needed to provision prometheus?

**Comment by linsun** [comment]
@mandarjog No, it doesn't include the prometheus deployment. Not sure why it is taking so long, sometimes are related to CRDs have to finish processing before envoy filters can be installed.

Let's put the time issue aside... I think the fundamental question is what is our min profile, which I had thought it is traffic mgmt only for knative like scenario.  Let's see what others think @costinm @rshriram @istio/technical-oversight-committee

**Comment by linsun** [comment]
discussed at env wg mtg today, the decision is to also disable webhook configs off min profile and users can choose and add what they need based on min profile.  PTAL @costinm @howardjohn

**Comment by linsun** [comment]
due to lack of consensus.

**Pull request closed without merging**
