### PR TITLE
wip: experimental with single listener for headless

### PR DESCRIPTION
**Pull request by howardjohn**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by howardjohn** [comment]
On issue is we now drain all of them even if only one changes...

**Comment by zhlsunshine** [comment]
Hi @howardjohn & @hzxuzhonghu, I think this is a great example of using multi-addresses per listener for headless service. ^_^

**Pull request closed without merging**
