### PR TITLE
add annotation and priorityClass for nodeagent.

### PR DESCRIPTION
**Pull request by morvencao**
Align `nodeagent` with other control plane component:

- add annotation to prevent istio sidecar injected 
- add priority class to  avoid pod evicted

### CODE REVIEW

**Comment by howardjohn** [comment]
@morvencao what is the impact if we don't change this? Are there any risks?

If there are any risks and this isn't fixing customer issues we may just want to hold off on this while we focus on the new installer

**Comment by linsun** [comment]
@morvencao I assume this change already landed in the new installer too?

**Comment by howardjohn** [comment]
This is a dupe of https://github.com/istio/istio/pull/14032/files so whichever one gets merged the other can be closed

**Comment by sdake** [comment]
@morvencao re auto-merging to 1.2, I was incorrect in earlier instruction.  only a few repos use mergify's auto-merge to stable, and istio/istio isn't one of them.

Cheers
-steve

**Comment by morvencao** [comment]
@linsun Yes, I have merge this before to new installer. Since we have switch to old one for 1.2 release, I think we need this.

@howardjohn Yes, but https://github.com/istio/istio/pull/14032 has been updated for long time.

**Comment by linsun** [comment]
@morvencao thank you!  I will merge #14032  assuming all tests pass since it was created first.

If you want this PR in 1.2, please create a cherry pick, thank you!

**Comment by morvencao** [comment]
@linsun OK to close this.

**Pull request closed without merging**
