### PR TITLE
Update Mixer dictionary to match proxy

### PR DESCRIPTION
**Pull request by bianpengyuan**

### CODE REVIEW

**Comment by mandarjog** [comment]
@bianpengyuan @kyessenov unit tests are failing. 
`TestAuthnCheckReportAttributesOriginJwtBoundToOrigin - istio_authn_origin_jwt_bound_origin`
which sounds like it could be affected by dictionary.

**Comment by mandarjog** [comment]
@jasminejaksic @jasmine-jaksic @rkpagadala We are waiting for this PR to resolve for 1.0.1

**Comment by bianpengyuan** [comment]
@mandarjog Yeah I need to add the attributes into mixer client test. Working on it now..

**Comment by bianpengyuan** [comment]
@mandarjog PR is ready to merge.

**Comment by hklai** [comment]
@bianpengyuan, is this needed in master as well?

**Comment by bianpengyuan** [comment]
@hklai no this is not needed. It has already be covered by other pr in master.

**Pull request merged**
