### PR TITLE
[1.3] Fix stale endpoints on scale to zero

### PR DESCRIPTION
**Pull request by howardjohn**
This is a cherrypick of #17957 and
https://github.com/istio/istio/pull/16967 to the release 1.3
branch.

Cherrypick on 1.2: https://github.com/istio/istio/pull/17958

I added to 1.3.5 release notes

### CODE REVIEW

**Comment by howardjohn** [comment]
Lint failure is due to yamllint, not my PR

**Comment by rlenglet** [comment]
Yeah, I know. I'm tracking it and will merge once I fix yamllint.
We won't ship 1.3.5 without this.

**Comment by howardjohn** [comment]
Thanks!

**Comment by rlenglet** [comment]
Legit lint failure:
```
level=info msg="[runner] worker.8 took 1m22.248562993s with stages: gofmt: 1m22.248536787s"
pilot/pkg/proxy/envoy/v2/eds.go:531: File is not `gofmt`-ed with `-s` (gofmt)
				Full:              false,
```

**Comment by howardjohn** [comment]
@googlebot I consent.

**Pull request merged**
