### PR TITLE
serve static files (sample/bookinfo/productpage)

### PR DESCRIPTION
**Pull request by tedli**
The current implementation of productpage, found that responsed 404 when retrieving static files.

Add static files serving function to fix this.

### CODE REVIEW

**Comment by frankbu** [comment]
I thought that the static pages have already been fixed by this PR: https://github.com/istio/istio/pull/13314

Is this still another problem on top of what was already fixed?

cc: @rvennam

**Comment by rvennam** [comment]
@tedli 
What static files are you referring to?
css, js and icons are currently in `/static` which is the default folder for serving static files in flask.

What is in `/opt/microservices/static` ?

**Comment by tedli** [comment]
@rvennam
Thanks for reply. Sorry, I was confused the 404 is caused because there is no route defined in VirtualSerivce, not because no route in Flask. I'm going to close this PR.

image

**Pull request closed without merging**
