### PR TITLE
update performance test with ingressgateway.

### PR DESCRIPTION
**Pull request by morvencao**
Update all performance test for istio, replace `istio ingress` and `routerule` with `ingressgateway` and `virtualservice`.
Fix: https://github.com/istio/istio/issues/6623

### CODE REVIEW

**Comment by morvencao** [comment]
@ldemailly I didn't try it on a GKE cluster for I don't have one, but I have tried the core function on a Kubernetes 1.10.x cluster with istio 0.8.0, it works fine.

**Comment by rkpagadala** [comment]
tested this with GKE and it works. Grafana is still broken. Will fix that in a different PR

**Comment by rkpagadala** [comment]
@morvencao  not sure why this PR is seeing lint failures. Can you please close this and crate a new PR.

**Comment by morvencao** [comment]
OK

**Pull request closed without merging**
