### PR TITLE
Clean code the initServiceControllers

### PR DESCRIPTION
**Pull request by ping035627**
Clean code the initServiceControllers in server.go.

### CODE REVIEW

**Comment by ping035627** [comment]
@costinm @rshriram can you help to review the lint error? thanks!

Makefile:238: recipe for target 'depend.diff' failed
make: *** [depend.diff] Error 1
Exited with code 2

**Comment by ping035627** [comment]
@ZackButcher hi, the ci/circleci failed, but the error seems to have nothing to do with my change, can you help review? Thanks very much.

**Comment by ping035627** [comment]
Hi, @geeknoid can you help to review this PR? Thanks.

**Comment by geeknoid** [comment]
CI failure seems legit...

**Pull request merged**
