### PR TITLE
Update KinD e2e test suite

### PR DESCRIPTION
**Pull request by howardjohn**
* Set imagePullPolciy=Never per KinD docs
* Fix image loading -- before it was only loading the last image not all
of them
* Set ARTIFACTS_DIR so the script can be run locally

Fixes https://github.com/istio/test-infra/issues/1403

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
Manually triggered a run of this test since it runs in postsubmit and it passes now https://gubernator.k8s.io/build/istio-prow/logs/istio-kind-simpleTest-master/379?log#log

**Comment by icygalz** [comment]
once we know that this test is passing and stable, we can delete the simpleTests using boskos and changed it with KinD version.

**Comment by howardjohn** [comment]
The test passed in postsubmit

**Pull request merged**
