### PR TITLE
Skip flaky FS tests and revert istio.io/pkg update with deadlock 

### PR DESCRIPTION
**Pull request by howardjohn**
This test has been flaky for months: https://github.com/istio/istio/issues/15987

This was attempted to be fixed in https://github.com/istio/istio/pull/16825 which introduced deadlocks

As far as I know this code is not actually used yet, so I think it is safer to disable rather than block release 1.3 critical changes

### CODE REVIEW

**Comment by howardjohn** [comment]
fyi @rlenglet

**Comment by howardjohn** [comment]
the test has always been a bit flaky (5% of tests fail maybe?) but as a
result of a PR only on master it now fails almost every time

**Comment by ozevren** [comment]
Can we wait until Martin's changes to the FSWatcher? That should land today.

**Comment by howardjohn** [comment]
If it fixes it that would be preferred. But it doesn't seem to be finished
yet (and this pr was opened before it was started)

**Comment by yangminzhu** [comment]
@ozevren 
Can we merge this first to unblock other PRs (e.g. https://github.com/istio/istio/pull/16602)? We can always fix it later.

**Comment by ozevren** [comment]
We can disable the tests, and I can take a look at them later. However, can we roll forward to Martin's latest changes in pkg? That should fix issues with the FsWatcher (and we wouldn't need to rollback the collateral changes this way).

**Comment by geeknoid** [comment]
I'm hoping that https://github.com/istio/istio/pull/16843 fixes these issues.

**Comment by howardjohn** [comment]
close for https://github.com/istio/istio/pull/16843. Thanks for the fixes!

**Pull request closed without merging**
