### PR TITLE
helm: make `defaults` user proof

### LINKED ISSUE #51458: Helm profiles confusing users to put their own config under `defaults`
See https://blog.howardjohn.info/posts/advanced-helm/

I have seen a few people putting all their config under `defaults`. This is not how its supposed to be done; defaults was meant to be internal. We may need an alternative approach to solve this, or improve docs.

### LINKED ISSUE #53018: defaults.global.hub does not affect ztunnel
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using an alternative image repo to install istio (especially now that Docker is locking down), all components except ztunnel seem to use defaults.global.hub.  

### Version

```Text
1.23
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/53018
Fixes https://github.com/istio/istio/issues/51458

Attempt to avoid the common issue of people

Previous attempt https://github.com/istio/istio/pull/51859

Hopefully no one thinks it is appropriate to set
`_internal_defaults_do_not_set`...

I think this requires release-builder changes. Ill merge those if this is approved

### CODE REVIEW

**Review by jacob-delgado — COMMENTED** [review]
Defaults was always a poor name for things we want to hide. There's no proper way to hide this, but this should be clear to the user they shouldn't change them.

I'll approve when the jobs pass. If you need release-builder changes to accompany this then I'll approve it first. LMK your intent

**Comment by howardjohn** [comment]
ok this is good to go now

**Comment by bleggett** [comment]
Honestly, I would rather use the existing `make` file-copy templating and just copy `values.yaml` to `defaults.yaml` for every chart.

That's (IMO) more obvious, more normative, and less confusing than any form of `special-do-not-use:` top-level keys in a ` values.yaml`.

`values.yaml` files are supposed to be the source of truth for valid/settable keypaths in a chart. All autodoc tools assume this. Helm assumes this. People who have Helm experience that try to use our charts assume this. We will never fix this properly unless we remove `defaults` or equivalent from the `values.yaml` files.

**Comment by howardjohn** [comment]
> Honestly, I would rather use the existing `make` file-copy templating and just copy `values.yaml` to `defaults.yaml` and slurp it with `Files` for every chart (mentioned in your blog).

I tried this technique and couldn't get it working (in the blog it was theoretical). I forget why, I think it was about being impossible to distinguish `--set foo=<default value>` vs unset (which matters, since it can overwrite the profile). Also its super hard to do the recursive diff stuff

**Comment by bleggett** [comment]
> > Honestly, I would rather use the existing `make` file-copy templating and just copy `values.yaml` to `defaults.yaml` and slurp it with `Files` for every chart (mentioned in your blog).
> 
> I tried this technique and couldn't get it working (in the blog it was theoretical). I forget why, I think it was about being impossible to distinguish `--set foo=<default value>` vs unset (which matters, since it can overwrite the profile). Also its super hard to do the recursive diff stuff

I would be fine saying that profiles will override any user-set CLI values, if the profile sets the same key path as the user via CLI.

Typically, if you are trying to override a value via the CLI that's not something we would set in a common profile anyway - all our profiles are by-definition "all these things are always on".

As for the rest, sprig `merge` templating funcs should work as well here as they do everywhere else.

**Comment by howardjohn** [comment]
> Typically, if you are trying to override a value via the CLI that's not something we would set in a common profile anyway -

One example of a thing you might want to do is `--set profile=ambient --set global.variant=debug`

**Comment by bleggett** [comment]
> > Typically, if you are trying to override a value via the CLI that's not something we would set in a common profile anyway -
> 
> One example of a thing you might want to do is `--set profile=ambient --set global.variant=debug`

Yep, which is a good argument for `variant` not being something we explicitly override in a profile - we don't/shouldn't anymore anyway IIRC, `distroless` is the implicit default.

**Comment by howardjohn** [comment]
> distroless is the implicit default,

Only because of the profile :slightly_smiling_face:. The profile logic was/is supposed to be lower precedence than values after it, so if we change that we are locking us into not being able to use it otherwise

**Comment by bleggett** [comment]
> > distroless is the implicit default,
> 
> Only because of the profile :slightly_smiling_face:. 

Yes, but we should not be setting that value in a profile. If it's the implicit default, it should be set in defaults/values. Not in the profile.

If, as in the case of the ambient profile, we had a bug where the distroless container wouldn't work for a specific container, then we could easily enough have overridden this temporary in the `istio-cni` template conditionally on `ambient.enabled` without using profiles, and dropped that when we could.

I get what you're saying but there's no reason to do something awkward and non-normative, just so we can retain the theoretical ability to do something that we can do five other ways if we need to, arguably more correctly.

> The profile logic was/is supposed to be lower precedence than values after it, so if we change that we are locking us into not being able to use it otherwise.

That's fine. Profiles are a fixed group of values that, _if_ you take the profile, you should always set and not override. Anything that doesn't fall into that definition doesn't really belong in a profile. 

If people complain about this we can point them at Helm. Profiles in Helm are buggy and lightly/not documented as a feature, so I'd rather we not lean heavily on them beyond the degree we do today anyway, and prefer more normative Helm patterns.

**Comment by bleggett** [comment]
> Its the default only for ambient, how else could we provide it?

By making it the default for all of Istio (which we probably are slightly overdue for TBH) - `distroless` versus `debug` as the default container base is not really related to ambient-or-not. Actually, it probably makes more sense as a (global) compatibility version thing than as an ambient profile thing.

**Comment by howardjohn** [comment]
> > Its the default only for ambient, how else could we provide it?
> 
> By making it the default for all of Istio (which we probably are slightly overdue for TBH) - `distroless` versus `debug` as the default container base is not really related to ambient-or-not. Actually, it probably makes more sense as a (global) compatibility version thing than as an ambient profile thing.

A global compatibility version that someone might want to override :wink: . For example, if we were to change the default to distroless globally, should I really not be able to say "I want 1.23 compatibility version, but I want to set distroless"? That seems backwards - we are actually worsening their security posture. Even more surprisingly, they will literally have `variant=distroless` in their config but won't get it!

We don't make heavy use of profiles today, but an obvious one would be to have `--profile=high-availability`. In that, we would set `replicas:3` or something. Should a user not be able to override that to 5 replicas?

**Comment by howardjohn** [comment]
>  You either want it to behave like 1.22, warts and all (use compat version) or you do not (you're free to frankenstein the values however you want).

**Comment by bleggett** [comment]
> > You either want it to behave like 1.22, warts and all (use compat version) or you do not (you're free to frankenstein the values however you want).
> 
> So in 1.22, I set `helm install --set variant=distroless`. I get distroless.
> 
> Then I upgrade to 1.23, and I set `helm install --set compatibilityVersion=1.22 --set variant=distroless`. I get debug.
> 
> That is NOT giving the 1.22 behavior

No, it's giving you 1.22 defaults, which is what you asked for when you explicitly forced a compatibility version. If that isn't what you want, do not use the compatibility version. Profiles are not a foundation for infinite combinatorics. They're an optional set of values that override everything the user sets. Their use is limited. 

The way Helm supports what you're suggesting out of the box is with CLI `-f` and `--set` flags, with rightmost positional preference. If we used that (and wrapper charts), everything we have or want to do would work with virtually no hacks. We've decided we do not want to use either of those things, and use profiles instead. Profiles break Helm behavior. So, we're stuck.

We either use the Helm approach to doing this that people expect, which works with all combinatorics, or we use `profiles`, which do not, without breaking a fundamental aspects of Helm (looking at `values.yaml` and having it make sense/produce rational documentation of all values for a chart).

It's not worth arguing about anymore, and you don't need my approval for this anyway. You want to rewrite Helm's behavior from the outside to make it work more like `istioctl`.  I don't particularly care how `istioctl` does or did work, and want to use Helm how it sits and how most Helm users would expect it to work. We just fundamentally don't agree on this, that's fine.

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
