### PR TITLE
Add an end-to-end test for Vault CA prototyping

### PR DESCRIPTION
**Pull request by lei-tang**
Add an end-to-end test for Vault CA prototyping, which:
    - Create a connection to Vault
    - Mount Vault PKI
    - Set CA signing key and cert
    - Set workload role for issuing certificates
    - Sign CSR and print the certificate signed

### CODE REVIEW

**Comment by costinm** [comment]
In release 0.8 ?? Code yelllow/red/etc ? Please read the announcement from TOC and Rel WG.

**Comment by costinm** [comment]
Unless vault is a feature planned for 0.8 - in which case it's a great PR. 

We need to stabilize the release - if something can be delayed for 0.8.1, please focus on 
going over the supported features, test, polish, document, etc.

**Comment by wattli** [comment]
Agree with Costin, 0.8 has enough test failures already, let's hold on the submission of this PR and wait after 0.8 release.

**Comment by lei-tang** [comment]
This PR is not for release 0.8.  This PR contains a flag enableForRelease = false to avoid affecting the release 0.8. As the master branch is locked, it was created on the release 0.8 branch. This PR is closed since it is not for the release 0.8.

**Pull request closed without merging**
