### PR TITLE
Support setting FAIL_OPEN for istio-policy service

### PR DESCRIPTION
**Pull request by yangminzhu**
istio/istio#9483, https://github.com/istio/istio/issues/9485

### CODE REVIEW

**Comment by mandarjog** [comment]
looks good, except why is `Owners` file changed in this PR ?

**Comment by mandarjog** [comment]
/lgtm 

@rshriram this needs an lgtm from you too.

**Comment by yangminzhu** [comment]
@mandarjog the OWNER is changed in this PR https://github.com/istio/api/pull/671, We use the master branch of Istio API so I think that's the reason why it's also changed here when I synced to the latest commit.

**Pull request merged**
