### PR TITLE
Print CLI version in bug-report/versions

### PR DESCRIPTION
**Pull request by clsacramento**
Not sure if this is the most efficient way to achieve this, but proposing a fix for https://github.com/istio/istio/issues/35097

**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by clsacramento** [comment]
Hey team, can you help me understand what is failing on the unit test? Looks like something with `racetest` but I didn't quite understand...

```
=== RUN   TestNtohs
--- PASS: TestNtohs (0.00s)
PASS
ok  	istio.io/istio/tools/istio-iptables/pkg/validation	0.067s
FAIL
make: *** [Makefile.core.mk:481: racetest] Error 1
+ cleanup
+ log 'Starting cleanup...'
++ date -u +%Y-%m-%dT%H:%M:%S.%NZ
+ echo -e '2021-09-09T18:03:25.501006852Z\tStarting cleanup...'
```

**Comment by howardjohn** [comment]
Its a bug not from this PR: https://github.com/istio/istio/issues/35079

/retest

**Pull request merged**
