### PR TITLE
Fix skywalking default port

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Which cause test failure https://github.com/istio/istio.io/pull/12962.

More details in https://github.com/istio/istio/pull/43177#issuecomment-1487894417

### CODE REVIEW

**Comment by ericvn** [comment]
We just need to decide if we want to continue to use the old 8080 port, or the new port. I already have a istio.io test PR updating the test to the new port and that passes if we want to continue with the new port.

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/44150 moves the port back so if it merges, we won't need this change.

**Review by GregHanson — APPROVED** [review]

**Pull request merged**
