### PR TITLE
Update go-control-plane

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by ldemailly** [comment]
you need to make your vendor PR first

**Comment by ldemailly** [comment]
pilot/pkg/proxy/envoy/v2/placeholder.go:37:2:error: ineffectual assignment to server (ineffassign)

**Comment by kyessenov** [comment]
This is dead code: see build !ignore flag above.

**Comment by ldemailly** [comment]
merged the vendor so please switch your vendor to head
( 1e7ee397956188785387ebce3da0e5dc1941ef5d )
before we merge this one

optional, another round with master in the toml (but that one can wait next update)

**Comment by ldemailly** [comment]
FAIL	istio.io/istio/mixer/adapter/solarwinds/internal/appoptics	0.578s

**Comment by kyessenov** [comment]
Nothing to do with this PR. Flake?

**Comment by ldemailly** [comment]
probably not because of you but...

I0227 00:40:47.469] istio-ca-9fd9f4869-tlsb8               0/1       ImagePullBackOff   0          4m

seems like something is broken - @costinm  maybe your pr ?

**Comment by ldemailly** [comment]
never mind the failure is most likely #3645

**Pull request merged**
