### PR TITLE
Return a meaningful exception if Pilot did not have data on the pod

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/13028

### CODE REVIEW

**Comment by esnible** [comment]
Marking as `WIP` so that we can first merge https://github.com/istio/istio/pull/13118/files which will ensure enough code coverage to please CircleCI.

**Comment by esnible** [comment]
Blocked until https://github.com/istio/istio/pull/13277 is merged.

**Comment by dwradcliffe** [comment]
This error message isn't a ton better, since it just outputs the pod name from the command input.
As discussed in #13028 I think there's a better way to fix this.

**Comment by esnible** [comment]
Closing in favor of https://github.com/istio/istio/pull/13724

**Pull request closed without merging**
