### PR TITLE
Add rolling update max unavailable to CNI chart to speed up deploys

### PR DESCRIPTION
**Pull request by myshkin5**
**Please provide a description of this PR:**
Updates to the CNI chart take a long time because the default is to update one node at a time. This PR allows the max unavailable to be overridden so multiple node can be updated at once.

Other charts expose a similar override. Note that I did not expose max surge as it seemed inappropriate to have more than one CNI pod per node even if just during an update.

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]

**Comment by jacob-delgado** [comment]
This was missing from this chart, but is found in other charts.

**Review by dgn — APPROVED** [review]

**Comment by dgn** [comment]
Could you add a release note?

**Review by hanxiaop — APPROVED** [review]

**Pull request merged**
