### PR TITLE
[Bug fix][Version 1.6]Fix ingress SDS not getting secret updates and create unit tests

### PR DESCRIPTION
**Pull request by williamaronli**
patch ref: https://github.com/istio/istio/issues/18912

Please provide a description for what this PR is for.
Fix ingress SDS not getting secret updates and create unit tests

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @williamaronli We are intending to get 1.6.6 out Tuesday or so. This will have to wait after.

**Comment by jacob-delgado** [comment]
cc @williamaronli @JimmyCYJ 

Jimmy, can I get an approval from you for this PR? I noticed that it is shorter than the original.

**Comment by JimmyCYJ** [comment]
Thanks @jacob-delgado, just reviewed and approved. The original PR has a test file, and the fix is the same.

**Pull request merged**
