### PR TITLE
istioctl upgrade checks differences in profiles between versions

### LINKED ISSUE #21939: istioctl upgrade should check the different defaults between minor versions
istioctl upgrade should check the different defaults between minor versions, and give users an output of the differences.

**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by elfinhe**
istioctl upgrade checks differences in profiles between versions
Fix: https://github.com/istio/istio/issues/21939

### CODE REVIEW

**Comment by elfinhe** [comment]
Here is an example output of 1.4.6 -> 1.5.0:

```
addonComponents:
  certManager: map[enabled:false] ->
  grafana:
    k8s: -> map[replicaCount:1]
  istiocoredns: -> map[enabled:false]
  kiali:
    k8s: -> map[replicaCount:1]
  prometheus:
    k8s: -> map[replicaCount:1]
components:
  base: -> map[enabled:true]
  citadel:
    enabled: true -> false
  egressGateways:
    '[#0]':
      k8s:
        hpaSpec:
          scaleTargetRef:
            name: istio-egressgateway -> istio-ingressgateway
  galley:
    enabled: true -> false
  nodeAgent: map[enabled:false] ->
  pilot:
    k8s:
      hpaSpec: map[maxReplicas:5 metrics:[map[resource:map[name:cpu targetAverageUtilization:80]
        type:Resource]] minReplicas:1 scaleTargetRef:map[apiVersion:apps/v1 kind:Deployment
        name:istio-pilot]] ->
      readinessProbe:
        periodSeconds: 30 -> 5
      resources: map[requests:map[cpu:500m memory:2048Mi]] ->
  policy:
    enabled: true -> false
  sidecarInjector: map[enabled:true k8s:map[replicaCount:1 strategy:map[rollingUpdate:map[maxSurge:100%
    maxUnavailable:25%]]]] ->
  telemetry:
    enabled: true -> false
installPackagePath: /tmp/istio-install-packages/istio-1.4.6/install/kubernetes/operator/charts
  ->
values:
  certmanager: map[hub:quay.io/jetstack image:cert-manager-controller tag:v0.6.2]
    ->
  gateways:
    istio-egressgateway:
      zvpn: map[enabled:true suffix:global] ->
    istio-ingressgateway:
      meshExpansionPorts:
        '[#2]':
          targetPort: 853 -> 8853
      ports:
        '[#1]':
          targetPort: 80 -> 8080
        '[#2]':
          targetPort: -> 8443
      sds: map[enabled:false image:node-agent-k8s resources:map[limits:map[cpu:2000m
        memory:1024Mi] requests:map[cpu:100m memory:128Mi]]] ->
      zvpn: map[enabled:true suffix:global] ->
  global:
    imagePullPolicy: IfNotPresent ->
    istioNamespace: -> istio-system
    istiod: -> map[enabled:true]
    jwtPolicy: -> third-party-jwt
    mountMtlsCerts: -> false
    mtls:
      auto: false -> true
    pilotCertProvider: -> istiod
    sds:
      enabled: false ->
    sts: -> map[servicePort:0]
    tracer:
      stackdriver: -> map[debug:false maxNumberOfAnnotations:200 maxNumberOfAttributes:200
        maxNumberOfMessageEvents:200]
    useMCP: true -> false
  grafana:
    enabled: false ->
    image:
      tag: 6.4.3 -> 6.5.2
    replicaCount: 1 ->
  istiocoredns:
    enabled: false ->
  kiali:
    dashboard:
      grafanaInClusterURL: -> http://grafana:3000
      jaegerInClusterURL: -> http://tracing/jaeger
    enabled: false ->
    replicaCount: 1 ->
    tag: v1.9 -> v1.14
  mixer:
    telemetry:
      useMCP: true ->
  nodeagent: map[image:node-agent-k8s] ->
  pilot:
    ingress:
      ingressControllerMode: OFF -> STRICT
    useMCP: true ->
  prometheus:
    enabled: true ->
    provisionPrometheusCert: -> true
    replicaCount: 1 ->
    tag: v2.12.0 -> v2.15.1
  security:
    trustDomain: cluster.local ->
  sidecarInjectorWebhook:
    image: sidecar_injector ->
    rewriteAppHTTPProbe: false -> true
    selfSigned: false ->
  telemetry:
    v1:
      enabled: true -> false
    v2:
      enabled: false -> true
  tracing:
    enabled: false ->
    jaeger:
      tag: 1.14 -> 1.16
    zipkin:
      probeStartupDelay: 200 -> 10
      resources:
        limits:
          cpu: 300m -> 1000m
          memory: 900Mi -> 2048Mi
      tag: 2.14.2 -> 2.20.0

```

**Comment by howardjohn** [comment]
```
  egressGateways:
    '[#0]':
      k8s:
        hpaSpec:
          scaleTargetRef:
            name: istio-egressgateway -> istio-ingressgateway
```

That is a bug... nice find

many are false positives though, like
```
  grafana:
    enabled: false ->
```

I can't think of any good ways to fix that though.

Also, is that really 1.5, and not master?

**Comment by elfinhe** [comment]
> ```
>   egressGateways:
>     '[#0]':
>       k8s:
>         hpaSpec:
>           scaleTargetRef:
>             name: istio-egressgateway -> istio-ingressgateway
> ```
> 
> That is a bug... nice find
> 
> many are false positives though, like
> 
> ```
>   grafana:
>     enabled: false ->
> ```
> 
> I can't think of any good ways to fix that though.
> 
> Also, is that really 1.5, and not master?

Oh, it is master.

**Review by richardwxn — COMMENTED** [review]
actually we may also change the templates between versions, not just the profiles. So it would be great that somehow we can combine them in this diff check?

**Comment by elfinhe** [comment]
```
components:
  nodeAgent: map[enabled:false] ->
  pilot:
    k8s:
      resources: map[requests:map[cpu:500m memory:2048Mi]] ->
  sidecarInjector: map[enabled:false k8s:map[replicaCount:1 strategy:map[rollingUpdate:map[maxSurge:100%
    maxUnavailable:25%]]]] ->
installPackagePath: /tmp/istio-install-packages/istio-1.5.0/install/kubernetes/operator/charts
  ->
values:
  gateways:
    istio-ingressgateway:
      meshExpansionPorts:
        '[#2]':
          targetPort: 853 -> 8853
      ports:
        '[#1]':
          targetPort: 80 -> 8080
        '[#2]':
          targetPort: -> 8443
      sds: map[enabled:false image:node-agent-k8s resources:map[limits:map[cpu:2000m
        memory:1024Mi] requests:map[cpu:100m memory:128Mi]]] ->
      zvpn: map[enabled:false suffix:global] ->
  global:
    imagePullPolicy: IfNotPresent ->
    sds:
      enabled: false ->
  nodeagent: map[image:node-agent-k8s] ->
  sidecarInjectorWebhook:
    image: sidecar_injector ->
    rewriteAppHTTPProbe: false -> true
    selfSigned: false ->
  tracing:
    zipkin:
      probeStartupDelay: 200 -> 10
      resources:
        limits:
          cpu: 300m -> 1000m
          memory: 900Mi -> 2048Mi
      tag: 2.14.2 -> 2.20.0
```
And this is the output from 1.5.0 -> 1.5-dev.

**Comment by elfinhe** [comment]
> profiles. So it would be great that somehow we can combine them in this diff check?

@richardwxn maybe we need more discussion on that. For most of our users, IstioOperator API is the place to customize their Istio. So as an end user, getting feedback on the templates will be difficult to understand what to do.

**Review by richardwxn — APPROVED** [review]
discussed offline with @elfinhe and agree that diffing IOP should be clear enough

**Pull request merged**
