### PR TITLE
Add operator options flag into integration test framework.

### PR DESCRIPTION
**Pull request by bianpengyuan**
#31765 I would like to enable a CNI test suite at postsubmit first. If that looks good and not flaky, we can make it at presubmit.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
I'm not sure we have all the flags there, but good to add to the wiki: https://github.com/istio/istio/wiki/Istio-Test-Framework

**Review by howardjohn — CHANGES_REQUESTED** [review]
Should we make this more generic? CNI is just one case, we may want to test with all sorts of different values enabled.

I believe we can provide a custom IOP file already, should we use that instead?

**Comment by bianpengyuan** [comment]
Yeah I think it is fine to use `helmValues` flag for the new suite. Custom IOP might be hard to maintain, since we need to dup content from the default IOP in it.

**Comment by howardjohn** [comment]
> Yeah I think it is fine to use helmValues flag for the new suite. Does this make sense?

Is helmValues just layered on top of the IOP? if so, I think that makes sense

**Comment by bianpengyuan** [comment]
> Is helmValues just layered on top of the IOP? if so, I think that makes sense

Yeah looks like it does not work. I added a new flag to provide operator options directly.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
