### PR TITLE
[broker] change on broker's autogen files

### PR DESCRIPTION
**Pull request by jmuk**
bin/bazel_to_go.py makes this change, and it seems similar change
happened as #1529, so I guess this change should also be accepted?

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by mandarjog** [comment]
@douglas-reid is this the same change that you checked in?

**Comment by douglas-reid** [comment]
@mandarjog yes. this is the exact same change. i'm fine with going with this version of the change.

**Comment by jmuk** [comment]
can someone in toplevel owner approve this?  (seems no OWNERS file in broker -- but why?)

**Comment by jmuk** [comment]
can someone in toplevel owner approve this?  (seems no OWNERS file in broker -- but why?)

**Comment by xiaolanz** [comment]
I will add an OWNER file to broker.

**Comment by mandarjog** [comment]
This is checking in an autogen file.

**Pull request merged**
