### PR TITLE
remove 1.3 version guards

### PR DESCRIPTION
**Pull request by ramaraochavali**
- Removes version guards for 1.3
- Simplifies some code

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@esnible Are you referring to this test `TestDescribe13` - Based on the description , I thought it is only used for 1.3 style messages. If it tests, other aspects, I can rename the test and retain the tests that are still relevant

**Comment by esnible** [comment]
@ramaraochavali I believe I wrote TestDescribe13 to distinguish between 1.2 and 1.3 behavior.

The 1.3 style data is used for 1.4 data, and we can remove it in 1.6.
The problem is the new tests I wrote for https://github.com/istio/istio/pull/22129 were removed in this PR.  Some tests using port 7080 must stay.

**Comment by ramaraochavali** [comment]
@esnible In the latest commit, I reverted the test change and brought the entire test back (Correcting the 1.3 specific check in one test case). PTAL. Is that what you are looking for? or some thing else?

**Pull request merged**
