### PR TITLE
tests: avoid ambiguity with an empty header

### PR DESCRIPTION
**Pull request by kyessenov**
This is an immediate improvement band-aid over the flaky ingress check cache. 
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
@hklai if this passes, can you please merge this? We uncovered some questionable behavior thanks to the test, but this should reliably pass I think.

**Comment by geeknoid** [comment]
/lgtm

We should also write some e2e tests to make sure mixer client & mixer see eye-to-eye on how to handle absent maps vs. absent keys in maps.

**Comment by hklai** [comment]
/test e2e-simple

I wonder why it keeps failing, as it looks pretty solidly green in other PRs.

**Comment by kyessenov** [comment]
I may have very well broke some other test if it reuses the same test rule.
I'll take a look later.

**Comment by kyessenov** [comment]
@hklai the error is:
```
container_linux.go:247: starting container process caused "exec: \"/usr/local/bin/galley\": stat /usr/local/bin/galley: no such file or directory"
```
This has nothing to do with this PR.

Did someone force merge a change? 😡

**Comment by kyessenov** [comment]
/test e2e-simple

If this keeps happening we should revert the PR that renamed gals to galley...

**Comment by hklai** [comment]
@kyessenov

I doubt it's due to a force mege, as post-submit looks mostly green.
https://prow.istio.io/?type=postsubmit&job=e2e-simpleTests

And I don't seem to find "starting container process caused" in that most recent failure.

**Comment by kyessenov** [comment]
It's galley crashing and failing the install:
`I0622 04:07:54.010] istio-galley-5f65fd95f7-xrlvl               0/1       CrashLoopBackOff   5          5m`

I have no idea why this is working for others. This PR doesn't even touch galley or build.

**Comment by kyessenov** [comment]
@hklai the line about missing binary is from the crash logs from galley pods. The build is screwed, it seems to create containers without the binary...

**Comment by hklai** [comment]
@kyessenov yeah it's weird. I think you can either send a fake commit to trigger a new build, or force merge and see if post-submit continues to stay green.

**Comment by kyessenov** [comment]
.. and the problem magically disappeared. Is there some build dependency from prow on circle? Maybe prow expected something that circle did not build (since it doesn't fast-forward).

**Comment by hklai** [comment]
/lgtm

circle does fast forward too...
https://github.com/istio/istio/pull/5957/files

**Pull request merged**
