### PR TITLE
Uniform pilot-agent and pilot-discover 's code style

### PR DESCRIPTION
**Pull request by vince-0202**
**Please provide a description of this PR:**

I noticed that pilot-agent's code style was different from pilot-discovery's,I wonder if it would be better like that.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [*] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by lei-tang** [comment]
Consider fixing it in master branch, then cherry-picking to patched release branches.

**Review by lei-tang — COMMENTED** [review]
Consider fixing it in master branch, then cherry-picking to patched release branches.

**Comment by vince-0202** [comment]
> Consider fixing it in master branch, then cherry-picking to patched release branches.

It would be better,So ,Should I resubmit this PR and fix it in master

**Pull request closed without merging**
