### PR TITLE
use ipv4 for platform discovery for dual stack

### PR DESCRIPTION
**Pull request by senior88oqz**
Follow up https://github.com/istio/istio/pull/37874, use ipv4 address to get aws metadata when dual stack is detected. This should provide better compability. For example, we have ipv6 interface available but have not enable ipv6 for our cluster, the proxy would be using the ipv6 address for AWS metadata discovery and it fails.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by senior88oqz** [comment]
hey @Chen-Xintong, it's been a while since this PR is open, can I get some feedback on this please?

**Review by Chen-Xintong — APPROVED** [review]
LGTM!

**Comment by Chen-Xintong** [comment]
@nmittler @ramaraochavali @howardjohn, PTAL!

**Comment by Chen-Xintong** [comment]
> hey @Chen-Xintong, it's been a while since this PR is open, can I get some feedback on this please?

Hi @senior88oqz , I'm not a networking WG maintainer that have merge permissions, but this PR lgtm, thanks!

**Pull request closed without merging**
