### PR TITLE
[Release-1.7] Fix eds: gateways missing endpoint instances of headless service

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

Fix: #27100

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
original issue: #27041

**Review by jwendell — COMMENTED** [review]
@hzxuzhonghu Could you please add a release note file for this fix?

**Review by jwendell — APPROVED** [review]

**Pull request merged**
