### PR TITLE
Add DNSSettings support for Tracer

### PR DESCRIPTION
**Pull request by aatarasoff**
**Please provide a description of this PR:**
A new section called `dns_settings` has been added to the Tracer Configuration. The purpose of this addition is to limit the Istio proxy's DNS queries to 10 minutes, instead of the default 30 seconds when Zipkin tracing is enabled. This can be achieved by defining the below structure in `MeshConfig` using this PR:
```yaml
dns_settings:
  refresh_rate: "600s"
  respect_ttl: false
```

Related PR: https://github.com/istio/api/pull/2934

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [*] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
Please use Telemetry API, `MeshConfig.DnsRefreshRate` may help this.

**Comment by keithmattix** [comment]
Adding DNM label pending discussion on the API PR

**Comment by aatarasoff** [comment]
> Please use Telemetry API, `MeshConfig.DnsRefreshRate` may help this.

We also need `respect_ttl` because we tried to change the refresh rate only. It didn't help

**Comment by zirain** [comment]
> > Please use Telemetry API, `MeshConfig.DnsRefreshRate` may help this.
> 
> We also need `respect_ttl` because we tried to change the refresh rate only. It didn't help

Telemetry API use standard `CDS`, I don't we need something special for tracing.

cc @howardjohn

**Comment by aatarasoff** [comment]
> Telemetry API use standard `CDS`

Don't fully understand, but let me explain the issue.

Now we have the following structure in `envoy_bootstrap.tmpl.yaml`:
```yaml
{
        "name": "zipkin",
        ...
        "respect_dns_ttl": true,
        "dns_lookup_family": "{{ .dns_lookup_family }}",
        "dns_refresh_rate": "30s",
        ...
}
```

We desire the following rendered configuration according to our tests:
```yaml
{
        "name": "zipkin",
        ...
        "respect_dns_ttl": false,
        "dns_lookup_family": "V4_ONLY",
        "dns_refresh_rate": "600s",
        ...
}
```

As you can see, we need to change `dns_refresh_rate` and `respect_dns_ttl`. We can use the `dns_refresh_rate` property to change the refresh rate, but we have nothing to change `respect_dns_ttl`. 

By the way, it is okay to add `respect_dns_ttl` or other property to the same level as `MeshConfig.DnsRefreshRate` and use it if you don't want to introduce separated section for tracer for some reasons.

**Comment by zirain** [comment]
Actually, you can achieve this with Telemetry API, then pacth Cluster with an EnvouFilter.
I have no objection to adding support for new apis in `MeshConfig`, if this's a common issue.

**Comment by aatarasoff** [comment]
> Actually, you can achieve this with Telemetry API, then pacth Cluster with an EnvouFilter. I have no objection to adding support for new apis in `MeshConfig`, if this's a common issue.

Thanks, that's interesting. Let me give it a try. 
However, for me, it doesn't seem like the most straightforward approach 😅

**Comment by hzxuzhonghu** [comment]
if `respect_dns_ttl` is true, actually dns_refresh_rate should make no sense

**Comment by hzxuzhonghu** [comment]
from https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/, it seems the default k8s dns ttl is 5s. I am sure this can be changed

**Pull request closed without merging**
