### PR TITLE
Remove vendor in favor of go modules

### PR DESCRIPTION
**Pull request by howardjohn**
This is just to get a feel for if we *could* remove vendor and if we did what impact it has on CI speed

### CODE REVIEW

**Comment by costinm** [comment]
1. Can you post a summary on the speed impact ? 
2. Offline/patche-able builds ? Isn't it still a priority ? Shouldn't we have them first (since vendor is what 
allows us to do them today, at least for the go portion ) ?

**Comment by howardjohn** [comment]
> Can you post a summary on the speed impact ?

When I first submitted this PR, there difference in speed was negligible, retesting a couple times showed the timing to be in line with the vendor speeds. We did some other changes that impact test speeds since then so let me rerun.

I think this is because the `git clone` is fast enough to offset the slow down from having to pull in the modules. At some point the dependencies need to be downloaded, from GOPROXY or vendor. The goproxy we use, https://proxy.golang.org, is the official golang proxy and will be default in go 1.13 by the way.

> Offline/patche-able builds ? Isn't it still a priority ? Shouldn't we have them first (since vendor is what allows us to do them today, at least for the go portion ) ?

As you mentioned, we cannot even do this today, as we depend on Envoy and maybe others like helm. I am not sure what makes vendor more offline -- at some point you must download the dependencies, does it matter if it is from `git clone` or `go mod download` (that is a real question, not rhetorical)?

I am not sure what you mean be patchable builds. If you mean modifying vendor directory directly, I don't think that is something we ever want to do, otherwise it gets wiped out the next time someone runs `go mod vendor`. The proper solution is doing the `replace` thing in `go.mod` and pointing to a fork I believe, which should work the same with and without vendor?


I don't want to force kill vendor if there are legitimate problems with it, but I personally do not have any objections anymore. Whatever we do, can we please do it before tomorrow so that we don't have differences between master and 1.3?

**Comment by howardjohn** [comment]
Racetest: 12:40m, 14m. Without this PR: 12:55, 13:13, 14m
Integration Test: 10:13m, 10:17m. Without this PR: 10:09m, 11:16m, 9:30m.
Lint: 9:30m, 8m. Without this pr: 9:38m, 9:13m.
Shellcheck (closest test we have to just `go build`): 1:23m 3x in a row. Without this PR, all tests between 1:10m - 1:30m

Conclusion - performance is essentially identical

**Comment by costinm** [comment]
We discussed offline: I think the main blocker is that some environments ( including our own internal systems ) have a requirement that all sources used for the build are checked in to a controlled repo,
and not downloaded from the internet ( with or without proxy)

Helm and other binaries we download are not compiled - and generally they can be checked in as well and pre-populated. 

This can probably be fixed - but there is additional work required, including finding how this is handled in other projects that use go mod. Maybe there are special proxies that satisfy the requirement, or other mechanisms.

But I don't think we can merge this PR until we test a solution - patching security and dealing
with prod requirements is tricky. 

@duderino

**Comment by howardjohn** [comment]
Created https://github.com/istio/istio/issues/16215 to track resolution of ^.

**Pull request closed without merging**
