### PR TITLE
Remove secret permission from the lesser get, list, watch group [release 1.4 branch]

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/19226

### CODE REVIEW

**Comment by howardjohn** [comment]
Please submit to master branch and cherrypick to 1.4

**Comment by lei-tang** [comment]
Per the comment, https://github.com/istio/istio/pull/19332 is created on the master branch and this PR is closed. After https://github.com/istio/istio/pull/19332 is merged, it will be cherrypicked to release 1.4 branch.

**Comment by lei-tang** [comment]
Reopen to merge this PR to the release 1.4 branch: https://github.com/istio/istio/pull/19332 on the master branch can not be cherrypicked to release 1.4 branch through adding the cherrypick/release-1.4 label. There are following merging conflicts after adding the cherrypick/release-1.4 label in https://github.com/istio/istio/pull/19332:

Applying: Fix lint error
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	pilot/pkg/model/push_context.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/model/push_context.go
CONFLICT (content): Merge conflict in pilot/pkg/model/push_context.go
Patch failed at 0002 Fix lint error

**Comment by howardjohn** [comment]
PR lgtm, won't merge until after the security patches land to keep things simpler for our private build

**Pull request merged**
