### PR TITLE
mixer: add enable l2 cache flag

### PR DESCRIPTION
**Pull request by kyessenov**
Add a flag to enable L2 cache (optionally).
Before this change, the cache was force disabled. Now it's disabled by default.
 
/assign @geeknoid 

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
Anyone?

**Comment by geeknoid** [comment]
Why does this need a flag? Isn't setting the number of cache entries to 0 sufficient?

**Comment by kyessenov** [comment]
I don't think we can change default to 0 from 1500000 for numCheckCacheEntries. With a flag, we don't have to change any defaults for any existing flags.

**Comment by kyessenov** [comment]
stale?

**Comment by douglas-reid** [comment]
@kyessenov probably?  with policy disabled by default, I don't believe this is critical.

**Comment by geeknoid** [comment]
As I stated above, I think we don't need a new flag. Let's just set the default # cache entries to 0 and remove the code in server.go that forces it to 0. I think that's good enough.

**Pull request closed without merging**
