### PR TITLE
[vendor-change, istio-api] update the istio/api sha

### PR DESCRIPTION
**Pull request by guptasu**
istio/vendor https://github.com/istio/vendor-istio/pull/48

### CODE REVIEW

**Comment by guptasu** [comment]
@rshriram any idea what might  be wrong with the pilot test here https://circleci.com/gh/istio/istio/63479

**Comment by ldemailly** [comment]
this can't work until #4668 is done

**Comment by guptasu** [comment]
@ldemailly I talked to @rshriram and he suggested to add `name` back into the Destination message. This would make the existing istio/istio repo work and we should be able to move the istio/api to latest SHA. I think what I have is the right fix, because it restores the old `name` field which is what istio/istio uses everywhere.

**Comment by ldemailly** [comment]
I didn't see you fixed it for him, thanks for doing that !

**Comment by ldemailly** [comment]
cool, I missed that kindly picked up the clean up!

**Pull request merged**
