### PR TITLE
feature: upgrading grafana dashboards to latest(38) version

### PR DESCRIPTION
**Pull request by vhbfernandes**
This upgrades all Grafana dashboards by:
- Updates .schemaVersion to latest (38) and commits all changes from grafana
- Changes deprecated angular panels to latest timeseries/tables
- Enables datasource selection (the available variable was doing nothing)

Also pushed the same updates to the samples/addons/grafana.yaml manifest

I know it's a terrible PR to review since changing dashboards will change thousands of lines 😅

### CODE REVIEW

**Comment by zirain** [comment]
`samples/addons/grafana.yaml` generated by `manifests/addons/gen.sh`, you can run `make gen` locally

**Comment by vhbfernandes** [comment]
@zirain thanks, just updated it

**Review by zirain — APPROVED** [review]

**Pull request merged**
