### PR TITLE
Update Prow job based on https://github.com/istio/test-infra/pull/306

### PR DESCRIPTION
**Pull request by sebastienvas**

### CODE REVIEW

**Comment by nlandolfi** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Comment by sebastienvas** [comment]
@istio-testing test this

**Pull request merged**
