### PR TITLE
Suggestion to improve readability.

### PR DESCRIPTION
**Pull request by cesarlbf**
Following the sample of: https://istio.io/docs/reference/config/adapters/servicecontrol.html

### CODE REVIEW

**Comment by cesarlbf** [comment]
CLA was signed.

**Comment by cesarlbf** [comment]
/assign @douglas-reid - Hi! Could you review this PR, it is just a suggestion to fix the formating issue on the adapter documentation. 
regards,

**Comment by geeknoid** [comment]
Sorry, but this is a generated file. The original content is in config.proto. You can make corrections there if you'd like, but any changes made only to the .pb.html file will be lost the next time the file is regenerated.

If you have a general suggestion to improve the appearance of our generated docs, please make suggestions in istio.github.io with specific pointers to the pages that don't look good. Maybe we can fix the generation tool to globally improve things, or perhaps put in a tactical fix for a specific issue.

Thanks.

**Comment by cesarlbf** [comment]
@geeknoid 

Thanks, I will trace back the original file.  I was just exploring how to contribute on docs,  As I was trying to learn more about adapters. :)

**Pull request closed without merging**
