### PR TITLE
Fixed "bazel run --output_groups=static .." command issue

### PR DESCRIPTION
**Pull request by mangchiandjjoe**
**What this PR does / why we need it**:

bazel build --output_groups=static ... command build the binary with the surffix ".static" under bazel-bin
But bazel run --output_groups=static ... command is looking for the binary without the surffix.

CI build ran "baze build ..." before the running of security/bin/e2e.sh. But there is no binary without the surffix when running security/bin/push-docker alone. I have to remove the optio " --output_groups=static"
to resolve the issue.

bazelbuild/rules_go#815 is the related issue.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mangchiandjjoe** [comment]
@wattli PTAL

**Comment by mattdelco** [comment]
I manually applied the change to the test repo I'm using with Cloud Builder and the builds now complete successfully so LGTM.

**Comment by mangchiandjjoe** [comment]
Thanks @mattdelco for testing this.

**Comment by myidpt** [comment]
Can you put more description to this PR? Thanks.

**Comment by mangchiandjjoe** [comment]
bazel build --output_groups=static ... command build the binary with the surffix ".static" under bazel-bin
But bazel run --output_groups=static ... command is looking for the binary without the surffix.

CI build ran "baze build ..." before the running of security/bin/e2e.sh. But there is no binary without the surffix when running security/bin/push-docker alone. I have to remove the optio " --output_groups=static" 
to resolve the issue.

https://github.com/bazelbuild/rules_go/issues/815 is the related issue.

**Comment by mattdelco** [comment]
A different commit already applied the same diff (which is why the net delta after the update merge from mail is now to apply no changes), so this PR can be closed/discarded.

**Pull request closed without merging**
