### PR TITLE
Updating Kiali to v0.5.0 on Ansible Installer

### PR DESCRIPTION
**Pull request by gbaufake**
Following https://github.com/istio/istio/pull/6930, https://github.com/istio/istio/pull/6929 and https://github.com/istio/istio/pull/7007,

Updating Kiali on Ansible Installer on release-1.0 branch

cc @gyliu513

### CODE REVIEW

**Comment by gbaufake** [comment]
@gyliu513  can we merge it?

**Comment by gyliu513** [comment]
@rshriram @sdake do you know why this PR merge blocked?

**Pull request merged**
