### PR TITLE
Add Unit tests to operator/pkg/util on helper functions

### PR DESCRIPTION
**Pull request by adiprerepa**
Added some tests to operator/pkg/util. I just wanted to get my "feet wet" with istio, i'm new to this, let me know if I did anything wrong.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release X
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by adiprerepa** [comment]
@googlebot I signed it!

**Review by morvencao — COMMENTED** [review]
Thanks
/ok-to-test

**Comment by adiprerepa** [comment]
@morvencao Do you know why its giving me linter errors? I'm not sure.

**Comment by morvencao** [comment]
@adiprerepa try to run
```
make format-go
```

**Comment by adiprerepa** [comment]
@morvencao When I run `sudo make format-go`, I get no output. I'm not sure what the linter means by this error.

**Comment by dgn** [comment]
@adiprerepa if you click on the "Details" link next to the failed CI job, you can see [the logs](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22920/lint_istio/11211). At the bottom, you can see the problem:
```
 operator/pkg/util/util_test.go:100: File is not `gofmt`-ed with `-s` (gofmt) 
```

`make format-go` should solve this; there's no output but you should see changes in the file.

**Comment by adiprerepa** [comment]
I can see changes in the file. does it just indent the struct definition? and why? Sorry, i'm new to this.

**Comment by adiprerepa** [comment]
@dgn  do I need to do more or is that it?

**Review by morvencao — APPROVED** [review]

**Comment by dgn** [comment]
> I can see changes in the file. does it just indent the struct definition? and why? Sorry, i'm new to this.

Hey- sorry, I was already gone then, I live in Europe.

The linter makes sure the code adheres to style guidelines, in this case they are the official ones (e.g. `don't use snake_case in variable names` or `keep initialisms intact, like hostIP instead hostIp` (see [common initialisms](https://github.com/golang/lint/blob/6ad27b90362c482217b8c2b555d1c24b9464fa69/lint.go#L701-L738) in go). The only thing `gofmt` does is reformat your code to match the style guidelines. We're gating the code on that to make sure it has at least some sort of coherence, it makes it easier to read.

**Comment by adiprerepa** [comment]
Ah okay that makes sense, thanks.

**Pull request merged**
