### PR TITLE
Move kube/inject out of Pilot

### PR DESCRIPTION
**Pull request by howardjohn**
kube/inject is a shared library between istioctl and sidecar-injector, but is under the pilot directory. This PR breaks it out into pkg/kube/inject, and additionally moves the (single file) sidecar-injector binary out of pilot as well.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I think this is good, but better add codeowners as well.

**Comment by incfly** [comment]
+1

This is always something looking very unnatural when browsing code dir :)

**Comment by costinm** [comment]
Wouldn't be better to just move it to a separate repo ?

It is a pretty well-contained component, without a lot of deps.

**Comment by howardjohn** [comment]
it would be one of the easiest components to break out into another repo, but until we have a way to deal with the release I don't think it's feasible right now.

With this change it will be pretty simple switch to another repo when we are ready

**Comment by costinm** [comment]
I generally don't like code moves/refactoring shortly after a freeze - we
had a big problem in 1.0 where cherry-picks stopped working.
Maybe we can hold on this for a week or 2 ?

I'm not sure what is the problem with the release - separate repo means
injector initially becomes a go mod/vendored dependency. Just
the go code.

Then we move the Dockerfile/Makefile for injector and start debating if it
really needs to be coupled with rest of Istio mega-releases, or
if instead it can be turned into a generic patch or template based
'transformation' tool that can support multiple versions of istio (and not
only)

**Comment by howardjohn** [comment]
> I'm not sure what is the problem with the release - separate repo means injector initially becomes a go mod/vendored dependency. Just the go code.

And how do we release the sidecar-injector binary? What happens when the sidecar-injector repo depends on istio/pkg (the repo, because we would need to move the common injection logic there for istioctl to work), but istio/istio depends on a different version - when we make a release what SHA do we tag?

Which of the 4 (!) different ways we handle dependencies should we use?

- Proxy reads from istio.deps
- CNI reads from istio.deps, but actually checks out the head of the branch
- Operator and Tools checks out head of the branch
- API reads from go modules (not just using standard go tooling, we parse the go.mod file, extract the SHA, and then git clone at that SHA)

These are all problems that *can* be solved, but they aren't yet. Until they are, I don't think it is feasible to break this out into another repo.

Moving to a different repo would make cherry-picks even worse

**Comment by kyessenov** [comment]
This is going to make @douglas-reid 's WIP on adding injection bits more complicated to cherry pick.
I agree, please stop moving code around before the release is finished.

**Comment by howardjohn** [comment]
When is the proper time to make improvements to the code structure? We are always supporting 2-3 Istio releases at any given time

**Comment by kyessenov** [comment]
Any time outside of 2-3 week window of a release :)
We need to move many more cherry-picks during that time than usual.

**Comment by nmittler** [comment]
I would think that a simple code move shouldn't be much of a problem for merging. Or is there something specific to Doug's PR?

@douglas-reid will this cause you problems?

**Comment by douglas-reid** [comment]
@nmittler i haven't tried a rebase yet. But I am worried about the divergence. Let me try now.

**Pull request merged**
