### PR TITLE
fix(dependencies): updated vault dependencies to only use the SDK

### PR DESCRIPTION
**Pull request by gitirabassi**
Please provide a description for what this PR is for.

Since the guys at hashicorp has moved vault to a multi module repository is possibile to only download the SDK instead of the whole repo. 

Using the whole repo creates conflic for projects who wants to import istio and also vault

People can verify I didn't touch the vendor by simply running a `go mod verify`

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
/ok-to-test

Can you run `go mod tidy`? Should clean some stuff up. See https://github.com/istio/istio/wiki/Vendor-FAQ. We should have this automated but haven't yet (:slightly_frowning_face:)

It seems like this change just adds a dependency? We still have `vendor/github.com/hashicorp/vault/api` with all the same stuff as before and git shows `+21,662 −11,390`, I would expect a lot more `-`

It seems to me that we now directly depend on the new split out sdk, but we still indirectly depend on the full repo? I could be wrong though... not a go modules expert

**Comment by gitirabassi** [comment]
Hi @howardjohn, I didn't notice the addition/deletion. usigin `git diff --numstat master` I saw there is a file `vendor/golang.org/x/net/publicsuffix/table.go` with ++9800/--9700 all alone. Most of the other additions come from `github.com/hashicorp/go-sockaddr`

**Comment by gitirabassi** [comment]
@howardjohn I tried understanding why tests are failing but I'm not sure my changes have anything to do with this because tests are failing for previous PRs too

**Comment by howardjohn** [comment]
Definitely something that sounds useful, but some things have changed in the repo so we aren't vendoring anymore. This is also a duplicate of https://github.com/istio/istio/pull/16621 I believe, which is also not yet ready to merge. I'll close this because of that, but feel free to help out on 16621 if needed or open a new PR (although it might be duplicated effort from 16621). Thanks!

And sorry we didn't get this finished review earlier so it became stale

**Pull request closed without merging**
