### PR TITLE
Revert "Run istio-init with non-root UID (#20380)"

### PR DESCRIPTION
**Pull request by dgn**
This reverts commit 0996b80fd41dc9ac92e6d2129a78a83c68aff76a.

See #20863

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Review by ericvn — COMMENTED** [review]
I did note that this PR has 125 files while the original PR had 124.

**Review by esnible — APPROVED** [review]
(Reviewed "istioctl" test data only.)

**Pull request merged**
