### PR TITLE
[security] Add yaml file for plugging in CA cert.

### PR DESCRIPTION
**Pull request by myidpt**
**What this PR does / why we need it**:
This yaml file can be used to help redeploy CA with user-provided certs/keys. The instructions will be shown in istio.io security task. It is a security feature in V0.2.

This is a cherry pick of PR #1334.

**Release note**:

```release-note
Add yaml file for plugging in existing key/cert to Istio CA.
```

### CODE REVIEW

**Comment by myidpt** [comment]
@ldemailly Yes I added it to the PR description.

**Comment by ldemailly** [comment]
I can merge this and it can make it in 0.2.12 ? @wattli  ?

**Comment by myidpt** [comment]
@ldemailly @wattli This PR is not urgent. It is OK to release next week if we have already built the release package.

**Comment by ldemailly** [comment]
given we need to redo a 0.2 might as well have it - if you want - up to you

**Comment by myidpt** [comment]
@ldemailly Of course it would be great if we can get it in this week, since the istio.io doc will be updated this week as well :)

**Comment by myidpt** [comment]
@yutongz Could you help to figure out why the tests are failing? Thanks!

**Comment by yutongz** [comment]
This is something oncall should do. It's a test failure, not infrastructure. I am willing to help, but next time try oncall first.

```
I1107 23:53:28.430] Need to update template and run install/updateVersion.sh
I1107 23:53:28.430] diff --git a/install/kubernetes/istio-ca-plugin-certs.yaml b/install/kubernetes/istio-ca-plugin-certs.yaml
I1107 23:53:28.430] index 41b3dec..7dd9160 100644
I1107 23:53:28.430] --- a/install/kubernetes/istio-ca-plugin-certs.yaml
I1107 23:53:28.430] +++ b/install/kubernetes/istio-ca-plugin-certs.yaml
I1107 23:53:28.430] @@ -27,7 +27,7 @@ spec:
I1107 23:53:28.430]        serviceAccountName: istio-ca-service-account
I1107 23:53:28.431]        containers:
I1107 23:53:28.431]        - name: istio-ca
I1107 23:53:28.431] -        image: docker.io/istio/istio-ca:0.2.10
I1107 23:53:28.431] +        image: docker.io/istio/istio-ca:0.2.12
I1107 23:53:28.431]          imagePullPolicy: IfNotPresent
I1107 23:53:28.431]          command: ["/usr/local/bin/istio_ca"]
I1107 23:53:28.431]          args:
```

https://github.com/istio/istio/blob/e3e17456d567cf0e4d329642582650cf8463eb6e/install/updateVersion.sh#L288

**Pull request merged**
