### PR TITLE
Clean up ISTIO_METAJSON_ANNOTATIONS k8s env var.

### PR DESCRIPTION
**Pull request by bianpengyuan**
I don't think this env variable is used anywhere.

### CODE REVIEW

**Comment by kyessenov** [comment]
@bianpengyuan I am not convinced it is not used anywhere. The way it works is quite convoluted but FWIW this is how I think it is passed:
1. pkg/bootstrap/config.go looks at any environment variable with ISTIO_METAJSON_ prefix.
2. it merges the JSON contents into a generic JSON
3. it converts that final JSON into bootstrap node metadata. That one has stats inclusion prefixes which I think can be annotations.

This is needlessly complex, so perhaps, it should be simplified first, and then we can remove METAJSON stuff.

**Comment by bianpengyuan** [comment]
> it converts that final JSON into bootstrap node metadata. That one has stats inclusion prefixes which I think can be annotations.

I see.. I thought annotations information is passed in through pod-info volume via downward API. Looks like these are two duplicated ways to get annotations information at agent. Let me see if I can clean up usage of this annotations json env first.

**Comment by kyessenov** [comment]
@bianpengyuan Yes it is also available from pod info file. I am not entirely sure why it's not read from there.

**Comment by mandarjog** [comment]
+1 to what Kuat said. 

right now this can be used to inject arbitrary node metadata.

**Comment by kyessenov** [comment]
@mandarjog Is the ability to override arbitrary node metadata a documented feature? It's not well-known and fairly dangerous to override arbitrary field in the bootstrap via annotations. I'd be in favor of locking it down more, to prevent tampering with it. As-is, any pod can pretend to be any other pod via an annotation, and potentially leak secrets (breaking namespace isolation).

**Comment by howardjohn** [comment]
Istiod will authenticate the namespace of the pod (and service account). So
you can impersonate other pods but only those in the same namespace.

Locking down what the agent will inject is at best a mild deterrent from a
security perspective though, as you can trivially send direct gRPC requests
with arbitrary metadata.

**Comment by kyessenov** [comment]
Thanks, @howardjohn, the auth should help with isolation. However, this feels like yet another undocumented EnvoyFilter-like mechanism, and it's not even remotely supportable.

**Comment by howardjohn** [comment]
are we removing all ISTIO_METAJSON_ or just annotation? the description and code don't seem to match.

I think removing the annotation part is no problem, but we should keep ISTIO_METAJSON_. Despite it possibly not being a good idea, I'm not convinced it wouldn't break users. We certainly use ISTIO_META_ (non json) so it seems in a similar category.

**Comment by bianpengyuan** [comment]
Looks like the `METAJSON_LABELS` is still useful for vm. I reduce this clean up to only remove `METAJSON_ANNOTATIONS` from injection template, as pod annotations information is already passed in via downward API.

**Comment by bianpengyuan** [comment]
> are we removing all ISTIO_METAJSON_ or just annotation? the description and code don't seem to match.
> 
> I think removing the annotation part is no problem, but we should keep ISTIO_METAJSON_. Despite it possibly not being a good idea, I'm not convinced it wouldn't break users. We certainly use ISTIO_META_ (non json) so it seems in a similar category.

Yeah sorry, just clean up the annotations env var.

**Comment by kyessenov** [comment]
It's fair to keep the logic, but the feature status of this bootstrap overriding mechanics should be clarified. It needs to be either fully supported or out.

**Review by howardjohn — COMMENTED** [review]
Can you remove https://github.com/istio/istio/blob/ad63263720be2de93bcea85b392c28ea554155ad/pilot/pkg/model/context.go#L481? there are still a few usages

**Comment by bianpengyuan** [comment]
> Can you remove
> 
> https://github.com/istio/istio/blob/ad63263720be2de93bcea85b392c28ea554155ad/pilot/pkg/model/context.go#L481
> 
> ? there are still a few usages

I originally removed Annotations from node metadata at https://github.com/istio/istio/pull/32331, but @kyessenov would like to preserve annotations I think to track bootstrap derivation https://github.com/istio/istio/pull/32331#discussion_r617043873.

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
ping @istio/wg-user-experience-maintainers

**Review by shamsher31 — APPROVED** [review]

**Comment by shonecyx** [comment]
We are using it and now it's broken. 
We need this annotation to apply envoyfilter to specific workloads, if this annotation is removed what's the alternative approach for that?  @bianpengyuan 
```
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      proxy:
        metadata:
          managedstack: "true"
        proxyVersion: ^1\.17.*
```

**Comment by howardjohn** [comment]
I am pretty sure ANNOTATIONS is still in the envoy node meta?

```
$ ik pc bootstrap sidecar-uncaptured-v1-6c678c444d-6nqdn | jq .bootstrap.node.metadata
{
  "ANNOTATIONS": {
    "istio.io/rev": "default",
    "kubectl.kubernetes.io/default-container": "app",
    "kubectl.kubernetes.io/default-logs-container": "app",
    "kubernetes.io/config.seen": "2024-06-07T17:28:12.635991536Z",

```

**Comment by shonecyx** [comment]
@howardjohn You are right the ANNOTATIONS is still in node meta but actually there was a breaking change.

The ` ISTIO_METAJSON_ANNOTATIONS` was actually being used https://github.com/istio/istio/blob/master/pkg/bootstrap/config.go#L606 and will be put to the `Metadata:    meta` before this change and the node meta look like below:
```
{
     "ANNOTATIONS": {
      "istio.io/rev": "default",
      "kubectl.kubernetes.io/default-container": "app",
      "kubectl.kubernetes.io/default-logs-container": "app",
      "kubernetes.io/config.seen": "2024-06-07T17:28:12.635991536Z",
	},
	.
	.
	.
    "istio.io/rev": "default",
    "kubectl.kubernetes.io/default-container": "app",
    "kubectl.kubernetes.io/default-logs-container": "app",
    "kubernetes.io/config.seen": "2024-06-07T17:28:12.635991536Z",
}
```
And the annoations can be directly used by https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ProxyMatch `metadata	map<string, string>	 Match on the node metadata` to apply the EnvoyFilter. 

However after removing `ISTIO_METAJSON_ANNOTATIONS` the node metadata look like below and those annotations can not be used any more by the proxy match.
```
{
      "ANNOTATIONS": {
        "istio.io/rev": "default",
        "kubectl.kubernetes.io/default-container": "app",
        "kubectl.kubernetes.io/default-logs-container": "app",
        "kubernetes.io/config.seen": "2024-06-07T17:28:12.635991536Z",
	},
	.
	.
	.
}
```
Shall we duplicate the key-values into the node metadata again so that they can be used by the `ProxyMatch`?

**Pull request merged**
