### PR TITLE
Add az to SDS/EDS API output

### PR DESCRIPTION
**Pull request by liamawhite**
This is part of the missing xDS API requirements for zone aware routing.

Discussion on the background of the issues can be found [here](https://groups.google.com/forum/#!topic/istio-users/y7mcC76Adyc).

### CODE REVIEW

**Comment by costinm** [comment]
To be clear: the endpoint tags are supported in which envoy version ? All ? Need new one ?

**Comment by liamawhite** [comment]
@costinm These are for the v1 APIs. Should we be upstreaming any changes to the v2 work as well?

**Pull request merged**
