### PR TITLE
remove grpc generator

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
grpc generator is nerver used, and has long been inconsistent with real Lds/rds/cds generator. 

We can implement a well consistent one if there is a use case later.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
can we keep this? I don't think it hurts anyone and we use this.

It does work - you can deploy a gRPC app today and get proper load balancing without a sidecar

**Comment by hzxuzhonghu** [comment]
You mean it is for the grpc sdk?

**Comment by hzxuzhonghu** [comment]
It looks there is no integration test for it as all the ci jobs passed

**Comment by howardjohn** [comment]
ok then feel free to assign me an issue to add e2e tests, I have been
planning to add them

**Comment by adiprerepa** [comment]
e2e tests for the gRPC generator?

**Comment by hzxuzhonghu** [comment]
I understand the real use case, this is to support grpc xds

**Pull request closed without merging**
