### PR TITLE
Add support in kubeenv adapter to generate missing pod uids

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR ensures that the `source.uid` and `destination.uid` attributes are populated when the `kubernetesenv` adapter is called with `source.ip` and `destination.ip` values. Config written using `source.uid` will be problematic in cases when the values are not populated -- leading to operator confusion and unexpected results. This scenario happens for TCP use cases, when `source.uid` in particular is not available server-side.

cc: @quentinmit

### CODE REVIEW

**Comment by kyessenov** [comment]
As long as we don't override uid, and default to using uid for the rest, LGTM.
IPs are re-used in k8s.

**Comment by douglas-reid** [comment]
@kyessenov if uids are sent in the Mixer call, they will not be overridden by the APA. i confirmed this with some local testing.

**Comment by douglas-reid** [comment]
@geeknoid may I kindly ask for your super merge powers here?

**Comment by geeknoid** [comment]
Is the lint job just kaputt these days?

**Comment by douglas-reid** [comment]
@geeknoid I think so?? The error message is: `Too long with no output (exceeded 10m0s)`.

**Comment by geeknoid** [comment]
Can you run the linters locally to make sure this isn't introducing a regression on that front?

**Comment by douglas-reid** [comment]
I will try when next at a computer

**Comment by douglas-reid** [comment]
@geeknoid i can't run the linters locally. there is a recent bug with deps in the linter and it prevents installing linters. this is what we get for always `go get -u`ing. i don't know what to say here.

Can we please merge this and I will promise to address any possible linting issues that arise?

**Comment by douglas-reid** [comment]
@geeknoid From CircleCI:

```
+ echo 'Running gometalinter ....'
Running gometalinter ....
+ /go/bin/gometalinter.v2 --config=./lintconfig_base.json ./...
+ echo 'gometalinter OK'
gometalinter OK
+ echo 'Running gometalinter on adapters ....'
Running gometalinter on adapters ....
+ pushd mixer/tools/adapterlinter
/go/src/istio.io/istio/mixer/tools/adapterlinter /go/src/istio.io/istio
+ go install .
+ popd
/go/src/istio.io/istio
+ /go/bin/gometalinter.v2 --config=./mixer/tools/adapterlinter/gometalinter.json ./mixer/adapter/...
+ echo 'gometalinter on adapters OK'
gometalinter on adapters OK
+ echo 'Running helm lint on istio & istio-remote ....'
Running helm lint on istio & istio-remote ....
+ helm lint ./install/kubernetes/helm/istio ./install/kubernetes/helm/istio-remote
==> Linting ./install/kubernetes/helm/istio
Lint OK

==> Linting ./install/kubernetes/helm/istio-remote
Lint OK

2 chart(s) linted, no failures
+ echo 'helm lint on istio & istio-remote OK'
helm lint on istio & istio-remote OK
+ echo 'Checking Grafana dashboards'
Checking Grafana dashboards
+ bin/check_dashboards.sh
/go/src/istio.io/istio /go/src/istio.io/istio
/go/src/istio.io/istio
+ echo 'dashboards OK'
dashboards OK
```

The task fails when trying to do some sort of dep ensure diff. Nothing in this PR touches any deps. We are safe.

**Pull request merged**
