### PR TITLE
Correctly assign conntrack zone to return packets from upstream DNS resolvers.

### PR DESCRIPTION
**Pull request by nberkley-gp**
**Please provide a description of this PR:**

Fixes https://github.com/istio/istio/issues/46935. Also cleaned up a couple places where comments did not match code that I saw when trying to track this down originally.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Nice debugging! 

This seems probably correct but also very subtle so want to ping some other people to look

@bleggett @yuval-k @nmittler perhaps one of you?

**Review by bleggett — APPROVED** [review]
LGTM pending test twiddles, ty!

**Comment by yuval-k** [comment]
looks right to me as well

**Comment by nberkley-gp** [comment]
Sorry it's taking a bit to get the CLA stuff sorted out. Thought we had this ironed out before opening this but for some reason our org isn't showing up.

**Comment by nberkley-gp** [comment]
CLA is finally sorted out. Could one of the network maintainers give it an approval?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
