### PR TITLE
move to drain listeners admin endpoint

### PR DESCRIPTION
**Pull request by ramaraochavali**
Moves to drain_listeners admin endpoint instead of custom draining with restart.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@howardjohn 
> if not I can throw it in a cluster
That would be great. I have not done any manual tests. Please throw it in a cluster

**Comment by howardjohn** [comment]
Forgot to try this out today.. will hopefully tomorrow

**Comment by ramaraochavali** [comment]
Sure. no problem

**Comment by howardjohn** [comment]
Getting some 503 UCs on server side when shutting down with this change. Need to try again without to compare though.

**Comment by howardjohn** [comment]
looks like lint failed - not sure why it fails now but not before

**Comment by ramaraochavali** [comment]
> looks like lint failed - not sure why it fails now but not before

I found that lint is little erratic some times. I will take a look

**Comment by ramaraochavali** [comment]
@linsun @rshriram @geeknoid can you PTAL?

**Pull request merged**
