### PR TITLE
Update Proxy SHA and go-control-plane

### PR DESCRIPTION
**Pull request by JimmyCYJ**

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
> FYI, there has been a bug reported regarding duplicate B3 headers that would be bought in with this PR: [envoyproxy/envoy#5017](https://github.com/envoyproxy/envoy/issues/5017)
> 
> It hasn't been investigated yet, so not clear what the impact would be - may only affect applications that use the newer single B3 header.

Thanks @objectiser! I notice that some tests complain "Duplicate subset v2 found while merging destination rules for c-weighted.extsvc.com", "Duplicate cluster outbound|443||www.wikipedia.org found while pushing CDS". Probably they are caused by this bug.

**Comment by JimmyCYJ** [comment]
Rerun e2e-pilot-auth-v1alpha3-v2 in circleci with ssh, both test app proxy and egressgateway shows this message.

[2018-11-21 00:59:50.475][000059][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:51] Unable to establish new stream
[2018-11-21 00:59:50.476][000059][critical][main] [external/envoy/source/server/server.cc:84] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': Proto constraint validation failed (ZipkinConfigValidationError.CollectorEndpoint: ["value length must be at least " '\x01' " bytes"]): collector_cluster: "zipkin"

**Comment by JimmyCYJ** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
It sounds like istio is using invalid bootstrap. Can you try setting this setting:
https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/trace/v2/trace.proto#L71

The proto constraint requires it to be set.

**Comment by JimmyCYJ** [comment]
> It sounds like istio is using invalid bootstrap. Can you try setting this setting:
> https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/trace/v2/trace.proto#L71
> 
> The proto constraint requires it to be set.

Thanks, Kuat. I have added it into bootstrap config and golden files.

**Pull request merged**
