### PR TITLE
WIP [Generate clusters for destination rules + 503s] 

### LINKED ISSUE #3781: Alpha2 clusters should be created even if no route points to the cluster
This is very important to allow warming and separate the creation of clusters from routing changes.
Currently it is the backup plan, in case the Envoy changes don't make it for 0.7 - I consider it a blocker
and P0 for 0.7.

I would appreciate if the change doesn't refactor or change alpha1 code - instead just constructs
clusters based on alpha2 DestinationRules, and merges the result with what the existing code generates ( replacing any cluster with the same name that may be created by alpha1 rules ). In general we agreed
for Gateway and other things that if a user defines an alpha2 setting it can take priority. 
Once CDS v2 is implemented, it could only use alpha2 cluster creation ( if we drop alpha1 ), and 
can further optimize by not watching/invalidating or pushing on routing rule changes.

Example yaml file:

```
# Service with traffic split.
apiVersion: v1
kind: Service
metadata:
  name: split-noroute
  labels:
    app: c
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 7070
    targetPort: 7070
    name: grpc
  selector:
    app: c


---

apiVersion: config.istio.io/v1alpha2
kind: DestinationRule
metadata:
  name: split-no-route
spec:
  name: split-no-route
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
           simple: LEAST_CONN
    - name: v2
      labels:
        version: v2
      trafficPolicy:
        loadBalancer:
           simple: ROUND_ROBIN
```

### PR DESCRIPTION
**Pull request by andraxylia**
Fixes #3781 

Needed for 503s, since we need the warm the clusters.

Includes tests for 503s.

### CODE REVIEW

**Comment by andraxylia** [comment]
@rshriram #3781 was assigned to me, I would have appreciated some communication related to this.

other than that, I see the code is very similar, though #4403 misses any test. Do you have CDS golden files or tests to prove it works, and is it something that can be exercised now to further investigate 503? How can code be committed without any test? I do not mind merging my stuff on top of something that is proven to work, there are multiple part in this PR.

**Comment by costinm** [comment]
@rshriram  this is important for avoiding 503 in v1 - and I think it's valuable to have it fixed for v1 in 0.8 even if the code will go away after.

As we agreed some people will waste a bit of time in v1 on a case-by-case basis.

Of course ideally the work will be done in both v1 and v2 and we keep it consistent.

**Comment by costinm** [comment]
On the issue of testing: this kind of PR must have e2e/integration test, AFAIK Andra has been using the 
'dynamic' test (apply routes and verify no traffic is lost), and it absolutely must be migrated and used with v2 and alpha3.

**Comment by rshriram** [comment]
Sorry about the conflict. I didn't know that particular issue even existed until I saw this PR.

My concern with this PR is that the fix you have applies only to v1alpha3, whose support is incomplete in proxy/envoy-v1. Users do not see see envoy v1 or v2. They only see Istio v1alpha1 or istio v1alpha3. 

If we go down the path proposed by this PR, we have to fully support v1alpha3 in v1 (external services, gateways, allowing all virtual hosts in the route rule, and other syntactic sugar in VirtualService) so that people can do the routing stuff properly. None of that is scheduled to be done in v1. As of now, nothing in v1alpha3 is exposed to public.

With regard to tests, unlike the old code, this is bootstrapping from scratch. Each component is dependent on the other. Can't test CDSv2 without a dummy or mocked LDS/RDS. Hence the decision was to get the bare minimal code in place so that we can start writing the test suites for all xDS.

With regard to goldens, if someone can wire up the go test with gRPC and other frills, I can happily punch in the goldens.

**Comment by andraxylia** [comment]
@rshriram I have to go ahead with what it is available, which is v1, so we can uncover all the things that can go wrong and cause 503s when config is changed, especially with Envoy - so far we have found 3 issues that need to be fixed in Envoy. The incomplete alpha3 support with v1 has worked for my tests, so no issue here. When we switch to Envoy v2, the tests will have to keep working.

**Comment by rshriram** [comment]
closing this as we now have proper cluster generation and tests for 503 in pilot (see gateway tests)

**Pull request closed without merging**
