### PR TITLE
NormalizePath: more error handling and whether it is directory judgment

### PR DESCRIPTION
**Pull request by helen-frank**
**Please provide a description of this PR:**
more error handling and whether it is directory judgment

### CODE REVIEW

**Comment by bleggett** [comment]
Can you please add more context around what specific problem you are trying to solve with this PR?

**Comment by helen-frank** [comment]
> Can you please add more context around what specific problem you are trying to solve with this PR?

Handle errors other than NotExist as well, and determine if path is a folder

**Comment by dhawton** [comment]
> > Can you please add more context around what specific problem you are trying to solve with this PR?
> 
> Handle errors other than NotExist as well, and determine if path is a folder

Is there an instance where it would be a directory or would encounter another type of error? I don't feel like this change really adds anything. I'd recommend looking at the outstanding issues, especially ones labeled "Good first issue".

**Comment by helen-frank** [comment]
> > > Can you please add more context around what specific problem you are trying to solve with this PR?
> 
> > 
> 
> > Handle errors other than NotExist as well, and determine if path is a folder
> 
> 
> 
> Is there an instance where it would be a directory or would encounter another type of error? I don't feel like this change really adds anything. I'd recommend looking at the outstanding issues, especially ones labeled "Good first issue".

got it

**Pull request closed without merging**
