### PR TITLE
WORKSPACE fix to build with bazel 0.6.1

### PR DESCRIPTION
**Pull request by lizan**
**What this PR does / why we need it**:
https://github.com/istio/mixer/pull/1423

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by mandarjog** [comment]
/lgtm

This is needed for https://github.com/istio/mixer/pull/1423 to pass.

**Comment by ldemailly** [comment]
this seems to break my 0.5.3 - are we forcing the upgrade to 0.6 ?
does everything works with 0.6 ?

this kind of change may need more than 1 reviewer

**Comment by ldemailly** [comment]
also seems to reference some very slow
INFO: Downloading https://codeload.github.com/golang/tools/zip/3d92dd60033c312e3ae7cac319c792271cf67e37: 1,637,844 bytes

**Comment by mandarjog** [comment]
I have tested it on 0.5.4 - 0.6.1

**Comment by mandarjog** [comment]
It looks like build machines have already upgraded to 0.6.1 so the code is just catching up now.

**Comment by mandarjog** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_mixer/1402/mixer-presubmit/1220/

**Comment by ldemailly** [comment]
0.5.3 didn't work for me after pull (in this repo) so I brew updated and got 0.6.1
not super fun to do that while also trying to get 0.2 branch going

**Pull request merged**
