### PR TITLE
Bag conversion to proto missing parent attributes

### PR DESCRIPTION
**Pull request by elevran**
See https://github.com/istio/issues/issues/258

### CODE REVIEW

**Comment by elevran** [comment]
@geeknoid qq: who can set the `cla` label? Upon rebase, pulled it a bunch of other commits from other authors which seem to have had the cla manually set.
Other option is to close this and redo the PR off `master` again, losing the rebase/merge commits.

**Comment by geeknoid** [comment]
I've seen the CLA get stuck, we can just ignore it.

If you can get a run where all the tests pass, except cla/google, then I'll push in your change.

Thanks.

**Comment by elevran** [comment]
@geeknoid the failure is in mockapi tests where `got` and `want` check responses differ:
```
got:  
&v1.CheckResponse{ ...
    Attributes:v1.CompressedAttributes{
        Words:[]string{"test.attribute", "test.value"},
        Strings:map[int32]int32{-1:-2}, 
        Int64S:map[int32]int64(nil), 
        Doubles:map[int32]float64(nil), 
        ...
    },  ...
}, 

want: 
&v1.CheckResponse{ ...
    Attributes:v1.CompressedAttributes{
         Words:[]string(nil), 
         Strings:map[int32]int32(nil), 
         Int64S:map[int32]int64(nil), 
         ...
    }, ...
}
```

The reference attributes in the response proto are all nil, where as the actual contains the attributes.
While I think the correct and expected behavior is copy the parent bag's attributes when converting to proto (which is what this PR does), I'm not sure if the test logic/set up is amiss or the mockapi handler is accounting for this. 
I think the `wantBag` is not initialized correctly in the test (since the compressed attributes are all nil). It would seem that the mockapi handler returns the attributes passed to it (assuming that's normal operation) and before the PR the parent attributes were not copied and hence they return was empty as well.
Would appreciate some help with fixing my code, the test case or the mockapi. 
Thanks!

**Comment by geeknoid** [comment]
I think the semantic change you're trying to make is correct. ToProto should consider the parents when generating the proto. I just surveyed all uses of ToProto in the source base and they're almost entirely in tests, except for one use in the mixc command.

The solution is to just hack the mockapi code to deal with your changes semantics. Probably, al you need to is change it so that when it creates the response bag, it doesn't use the request bag as parent. Just use nil instead.

**Comment by elevran** [comment]
thanks @geeknoid for the advice - wanted to make sure the semantic change was correct before changing test or mockapi code.
mockapi changed per suggesting and previously failing tests now pass

**Pull request merged**
