### PR TITLE
Handle envoy RDS protocol error response - 1.0

### PR DESCRIPTION
**Pull request by knrc**
istio-10105 for branch 1.0

### CODE REVIEW

**Comment by knrc** [comment]
It looks as if lint is failing on code completely unrelated to this commit

**Comment by costinm** [comment]
Doesn't seem critical for 1.0 - can you move it to 1.1 ?

**Comment by knrc** [comment]
The issue causes a sidecar to lose its routes and prevents it from talking to the mesh, we discovered this during one of our tests as it hit the ingressgateway and prevented all external access into the cluster.  I do have an update for it however, we hit a second race where a proxy requesting updates was not being handled.  I'll update the PR tomorrow.

**Comment by knrc** [comment]
@costinm The PR has now been updated for 1.0, I'm about to update the other PRs

**Comment by knrc** [comment]
lint seems to be complaining about files not included in this PR

**Comment by knrc** [comment]
Galley failures also appear to be unrelated to this PR

**Comment by knrc** [comment]
The race also appears to be unrelated, it seems to be associated with the metrics refresh.

**Comment by GregHanson** [comment]
not sure what happened with circleci jobs, closing and re-opening this PR to try and re-kick them

**Pull request closed without merging**
