### PR TITLE
backport various WorkloadEntry auto-registration fixes

### PR DESCRIPTION
**Pull request by stevenctl**
Requires several PRs (listed from newest to oldest):

- [x] #29691
- [x] #29793
- [x] #29685
- [x] #29604
- [x] #29554 (only parts relating to workloadentry controller, none of the other internalgen changes)
- [X] #28968

### CODE REVIEW

**Comment by stevenctl** [comment]
cc @hzxuzhonghu and @howardjohn who authored some of the PRs.

**Comment by howardjohn** [comment]
@googlebot I consent

**Review by howardjohn — COMMENTED** [review]
LGTM, all the code is pretty isolated

**Review by bianpengyuan — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
@googlebot I consent

**Pull request merged**
