### PR TITLE
[release-1.7] remove cni initContainers and volumes in remove-from-mesh (#26812)

### PR DESCRIPTION
**Pull request by tariq1890**
(cherry picked from commit 707b28d8b8e6dac582f55fe40403109f4d3cbb4e)

Manual cherry pick of PR #26812 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by tariq1890** [comment]
@JimmyCYJ @jwendell Requesting your review

**Comment by jwendell** [comment]
@tariq1890 Could you please add a release note entry?

**Comment by tariq1890** [comment]
@jwendell Done

**Pull request merged**
