### PR TITLE
prioritize using istio-ca-secret even if USE_CACERTS_FOR_SELF_SIGNED_…

### PR DESCRIPTION
**Pull request by Xieql**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
LGTM. I think this should be backported to 1.20. 
And in 1.21, we can turn on the flag, and copy istio-ca-secret to cacerts if exist.  In a future release maybe 1.24, we can completely remove ` istio-ca-secret ` secret support.

**Comment by keithmattix** [comment]
@hzxuzhonghu that plan sounds really similar to the design doc that @jaellio circulated around the community. I'm sure she'd appreciate prompt reviews and support in implementing her design!

**Comment by jaellio** [comment]
@hzxuzhonghu @costinm @Xieql To the best of my knowledge this PR is the same as #47654. We were still having an ongoing discussion on that PR on whether this change should be included in v1.20 and why I had removed similar logic that I had already implemented in a previous PR when adding the feature flag. I was at KubeCon this past week and did not have time to review this PR. I would appreciate in the future if we could reach consensus on an issue before an identical PR is opened and merged.

I have documented my plan for adding this feature flag in multiple issues and I would have appreciated that if there were concerns surrounding the feature flag, those conversations could have continued on those issues.

>> And in 1.21, we can turn on the flag, and copy istio-ca-secret to cacerts if exist. In a future release maybe 1.24, we can completely remove istio-ca-secret secret support.

I have documented the plan for the cacert merging work in multiple locations and I have documented and had an open conversation surrounding the feature flag addition.

**Pull request merged**
