### PR TITLE
only call edsUpdate when svc not changed

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

fixes: #17814

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by Nino-K** [comment]
@hzxuzhonghu can we hold off on this one, the `newEpVersion != ""` was a temprorary fix for a flaky test and I don't think it's a right thing to do anymore. The reason it was being added was galley sometimes drops the endpoint(s) intermittenly (still not sure why) and I'm currently investigating why is that happening. The reason `newEpVersion != ""` doesn't seem right is  because there might be legitimate cases where galley wants to drop the endpiont and `newEPVersion` will be nil for the right reasons.

**Comment by hzxuzhonghu** [comment]
Feel free to do that

>The reason it was being added was galley sometimes drops the endpoint(s) intermittently (still not sure why)

Is that because the k8s service occurs early than endpoints?

**Comment by Nino-K** [comment]
> Feel free to do that
> 
> > The reason it was being added was galley sometimes drops the endpoint(s) intermittently (still not sure why)
> 
> Is that because the k8s service occurs early than endpoints?

That could potentially be the cause, but why is it intermitten? is the k8s service happening before endpoints and vice versa expected/known behaviour? Reason asking is because test is pretty determenistic in the way it updates the service and the endpoint(s). It does the service and endpoint updates always in the same order.

**Comment by hzxuzhonghu** [comment]
Yes, k8s service is created by user, and endpoints is created by kube-controller-manager after it has watched the service. But i donot know why is it intermitten as i have not looked into the galley side code

**Comment by hzxuzhonghu** [comment]
close as @Nino-K is working on SSE

**Pull request closed without merging**
