### PR TITLE
Fix compilation issue caused by bad merge

### PR DESCRIPTION
**Pull request by rshriram**
Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by linsun** [comment]
validated the latest 1.1 has a different signature on DestinationRule() https://github.com/istio/istio/blob/release-1.1/pilot/pkg/model/push_context.go#L509

/lgtm

**Comment by linsun** [comment]
@wenchenglu @duderino can we get this in asap?

**Comment by rshriram** [comment]
force merging so as to unblock other PRs, as this is purely a compilation fix. no functional changes..

**Pull request merged**
