### PR TITLE
Update issue_template.md

### PR DESCRIPTION
**Pull request by sakshigoel12**
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
for the cla go/github
/approve

**Comment by ldemailly** [comment]
@sebastienvas new tests seem broken... can't merge

**Comment by sebastienvas** [comment]
I changed it back to the other one. @yutongz let s understand why this is failing and re-enable it back when they are passing.

**Comment by sakshigoel12** [comment]
I signed it!

**Pull request merged**
