### PR TITLE
Rename v1alpha3.ExternalSerivce to v1alpha3.ServiceEntry

### PR DESCRIPTION
**Pull request by GregHanson**
updating istio master to a newer istio/api commit appears to have picked up some changes to mixer in istio/api that are not implemented in master:

```
# istio.io/istio/mixer/test/client/env
../../../../../mixer/test/client/env/mixer_filter_config.go:167:47: undefined: client.JWT
../../../../../mixer/test/client/env/mixer_filter_config.go:168:21: mfConf.PerRouteConf.EndUserAuthnSpec undefined (type *client.ServiceConfig has no field or method EndUserAuthnSpec)
../../../../../mixer/test/client/env/mixer_filter_config.go:168:42: undefined: client.EndUserAuthenticationPolicySpec
../../../../../mixer/test/client/env/mixer_filter_config.go:169:21: mfConf.PerRouteConf.EndUserAuthnSpec undefined (type *client.ServiceConfig has no field or method EndUserAuthnSpec)
```

until mixer code is updated, PR is blocked

### CODE REVIEW

**Comment by GregHanson** [comment]
cc @diemtvu

**Comment by GregHanson** [comment]
related Mixer PR to resolve:
https://github.com/istio/istio/pull/5194

**Comment by rshriram** [comment]
force merging due ot stuck CLA bot.

**Pull request merged**
