### PR TITLE
fix multicluster leader election regression

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

fix https://github.com/istio/istio/issues/47901

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
regression from #44746

**Comment by zirain** [comment]
need backport？

**Review by howardjohn — APPROVED** [review]
cc @frankbu

**Comment by ericvn** [comment]
If this is a regression and we are back porting the fix, it would be good to have a release-note.

**Pull request merged**
