### PR TITLE
trustbundle: refactoring code that fetches CA roots when CA is not ru…

### PR DESCRIPTION
**Pull request by shankgan**
refactoring code that fetches CA roots when CA is not running.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Not sure I understand - this looks more like a revert than refactor?

**Comment by shankgan** [comment]
> Not sure I understand - this looks more like a revert than refactor?

Not completely a revert - but seeing some startup issues in setups when CA is disabled. Will re-add this capability when I have greater confidence with more tests.

**Review by myidpt — APPROVED** [review]

**Review by ramaraochavali — APPROVED** [review]

**Comment by ramaraochavali** [comment]
@shankgan This looks good. Can I remove hold or did you put it for any other purpose?

**Comment by ramaraochavali** [comment]
@shankgan I am removing hold so that we can test in our env while do a followup PR to fix it correctly with more tests.

**Comment by shankgan** [comment]
> @shankgan This looks good. Can I remove hold or did you put it for any other purpose?

no reason. thanks for taking care of the merge

**Pull request merged**
