### PR TITLE
Cherrypick change from master to release 1.1 (#13733)

### PR DESCRIPTION
**Pull request by lsjostro**
Cherrypick change from master to release 1.1 (#13733)  ping @quanjielin

### CODE REVIEW

**Comment by lsjostro** [comment]
Something wrong with e2e test. Temporary hick up? ;)
Seems to be the same problem here #13807.

**Comment by lsjostro** [comment]
@quanjielin what is the status of this getting into 1.1 release?

**Comment by quanjielin** [comment]
Is fix in master ok for your use, or do you have use case that needs this fix to be 1.1 ?

**Comment by lsjostro** [comment]
I would be lovely to have the fix in the next 1.1 release as well. Don't know when you plan to cut of a release from master?

**Comment by wenchenglu** [comment]
@duderino 
lgtm to cherrypick, as this is a fix to the existing feature.

**Comment by lsjostro** [comment]
Any news on getting this into next release 1.1? As currently this prevent us for using our own root ca. Ping @duderino @wencheglu

**Comment by lsjostro** [comment]
can we have this merged?

**Comment by duderino** [comment]
Sorry this didn't make it into 1.1.  It should go out in 1.2 with an ETA of 3 weeks

**Pull request closed without merging**
