### PR TITLE
Create default Mixer config YAMLs

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR moves the "default" configs for mixer from the `samples/app/bookinfo/rules` dir to the main `install/kubernetes/**` tree.

This PR is needed because, without it, the install of mixer will be missing many important configs for basic operation, including:
- attribute manifests
- default metrics
- configuration of `prometheus` and `stdio` adapters

To make use of the new location for the Mixer configs, the e2e framework code was updated to replace the `istio-config-default` namespace with the namespace of the test. The various, now unnecessary YAML files in the `samples` directory were deleted.

cc: @debianmaster, @karmab

Related issue: https://github.com/istio/issues/issues/59

**Release note**:

```release-note
Provide default Mixer configuration for prometheus metrics and stdio logs.
```

### CODE REVIEW

**Comment by douglas-reid** [comment]
@rshriram I don't want to bundle logs with any of the metrics stuff. It arguably could be two files itself (one for the adapter config, one for the logentry). But it is distinct, in the Mixer sense, from the metrics stuff.

The metrics stuff *can* be used separately from `prometheus` adapter (if you wanted to use `stdio` metrics handler or stackdriver, for instance). But maybe that is a detail we worry about later.

@mandarjog thoughts on the `addons` config organization?  should we bundle `metrics.yaml` and `prometheus.yaml` ?  which is easier for users (to understand AND to use)?

**Comment by mandarjog** [comment]
We should bundle prometheus with related metrics. 
Prometheus adapter is built-in so it is safe to do so.
 
Regarding using fully qualified instance and handler names inside actions, namespace can be elided from those names. We do this is configs checked into Mixer repo.

Let us get some feedback from users if short names are desirable over fully qualified names while operating within a namespace.
https://github.com/istio/mixer/issues/1323

**Comment by douglas-reid** [comment]
PTAL. I moved the "default" Mixer YAMLs for metrics and logs into the template for mixer itself. This simplifies the number of files, etc. I also stripped some of the explicit namespacing.

**Comment by mandarjog** [comment]
I don't fully like the idea of installing config resources in a namespace of our choice - `istio-config-default`.  It does create a good out of the box experience, but I don't see a way for a user to specify a different namespace, unless I have missed something.

That said, this does get us back to parity with 0.1.

**Comment by douglas-reid** [comment]
@mandarjog Filed https://github.com/istio/istio/issues/878

**Comment by douglas-reid** [comment]
Merging, in advance of internal testing to allow for proper out-of-the-box Mixer experience.

**Pull request merged**
