### PR TITLE
removed apps/ and moved subdirs up one level

### PR DESCRIPTION
**Pull request by GregHanson**
**Release note**:

```release-note
<PLEASE PUT RELEASE-NOTE HERE, PUT NONE if NO RELEASE-NOTE>
NONE
```

### CODE REVIEW

**Comment by GregHanson** [comment]
folder re-org changes of PR #893

**Comment by ZackButcher** [comment]
/lgtm

poking the bot.

**Comment by ldemailly** [comment]
Reviewers: it's part of your job to check for release notes, proper description of risk/benefits and not rush changes in 1h unless there is a huge fire

**Comment by ZackButcher** [comment]
This is a simple reshuffling of code to get rid of an annoying extra directory. I don't think it warrants release notes.

**Comment by ldemailly** [comment]
no it also change the optics, making "istio rules" now appear like "kube/" rules just because the consul implementation doesn't understand or is unable to normalize some parts of them

the reference platform should still be k8s in 0.2 and the others can be deltas/on the side

this was rushed and should not have been

cc @smawson

**Comment by rshriram** [comment]
the optics have already changed because you approved the PR that first introduced Consul rules https://github.com/istio/istio/pull/681. [Not sure if you paid any attention to "optics" there].

If you by chance take a look at the design and docs. Namespace field is a clear kubernetes hack. Also, consul has its own DNS domain, which necessitates different rules with just minor changes between them. 

In my opinion, this PR was merely adding the missing rules and reorganizing the clutter.

**Pull request merged**
