### PR TITLE
Bump addon versions

### PR DESCRIPTION
**Pull request by howardjohn**
For https://github.com/istio/istio/issues/30822
I did some brief manual testing and didn't see any issues

### CODE REVIEW

**Review by douglas-reid — APPROVED** [review]

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
Something looks wrong. The ConfigMap has this still:

```
      image_version: v1.29
```

and the Deployment:
```
      - image: "quay.io/kiali/kiali:v1.29"
```

Something happened when helm was run - it didn't seem to update things correctly. This shows that its at 1.31 but the container image is still 1.29

**Comment by howardjohn** [comment]
Good catch! will look into it

**Comment by jmazzitelli** [comment]
Just a side note - the reason why we override image_version is this is how we allow users to pick up latest Z-stream releases of  Kiali without having to update these Istio addon yamls. We ensure the quay.io image label "vX.Y" always point to the latest vX.Y.Z image.

**Review by jmazzitelli — APPROVED** [review]
looks good now

**Review by morvencao — APPROVED** [review]

**Pull request merged**
