### PR TITLE
[not for 1.2] mixer: enable CEL for httpaccesslog

### PR DESCRIPTION
**Pull request by kyessenov**
Enable CEL runtime for HTTP access log.
Given that HTTP access log is not recommended for high performance set-up, this should not have impact on performance configurations.
The benefit is continuous integration with CEL in end-to-end tests.

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
Hey, can we merge this? This is intended not to be released, but we need to analyze the behavior continuously using the test infra.

**Comment by douglas-reid** [comment]
This seems fine, especially given the deprecation path for Mixer instances in general. Should this be in the new installer, however?

**Comment by kyessenov** [comment]
I just used whichever installer is being used today. If we switch the tests to use another installer, I can make changes there too.

**Comment by douglas-reid** [comment]
@kyessenov what should be done with this PR now?

**Comment by kyessenov** [comment]
We can park it. I'm not sure if the installation change is even picked up by CI at the moment.

**Pull request closed without merging**
