### PR TITLE
Add mixer tests for the Istio authn filter

### PR DESCRIPTION
**Pull request by lei-tang**
Add the following Mixer tests for Istio authn filter

- Test when requiring JWT for peer and binding to peer, the authn attributes in the actual check and report calls match those in the expected check call
- Test when requiring JWT for peer and binding to origin, but no method specified in origin policy, the request will be rejected by Istio authn filter.
- Test when when requiring JWT for origin and binding to origin, the authn attributes in the actual check and report calls match those in the expected check call.
- Test when requiring JWT for origin and no binding to origin, the authn attributes in the actual check and report calls match those in the expected check call.
- Test when the HTTP request is rejected by the Istio authn filter for peer JWT authentication, the response code and the response message is as expected.
- Test when the HTTP request is rejected by the Istio authn filter for origin JWT authentication, the response code and the response message is as expected.
- Test when the Istio authn filter requires mTLS for peer connection, the non mTLS connection is rejected and the response code and the response message are as expected.
- Test when the Istio authn filter requires TLS for peer connection, the non TLS connection is rejected and the response code and the response message are as expected.

### CODE REVIEW

**Comment by hklai** [comment]
Doh this should not have been merged when istio-unit-tests failed.

**Comment by lei-tang** [comment]
With https://github.com/istio/istio/pull/5430, the istio-unit-tests passed.

**Comment by lei-tang** [comment]
#5430

**Comment by lei-tang** [comment]
The result of running #5443 shows that the mixer tests in prow/istio-unit-tests still fail with tcp_filter_v1_config_test duplicated and #5267 reverted.

**Pull request merged**
