### PR TITLE
Fix jwksURI base64 encoding

### PR DESCRIPTION
**Pull request by hexiaodai**
The JWKS structure consists of an array of JWK entries named "keys".
| Key | Contents |
| :-- | :-- |
| n | The modulus (2048 bit) of the key - Base64URL encoded. |

Whenever our authn authentication server fails and after restarting istio-ingressgateway, the following failures occur:
1. Istiod error log:
ADS:LDS: ACK ERROR istio-ingressgateway-8654477747-dzkmm.istio-system-1 Internal:Error adding/updating listener(s) 0.0.0.0_8080: Provider 'origins-0' in jwt_authn config has invalid local jwks: Jwks RSA [n] or [e] field is missing or has a parse error
2. Istio-ingressgateway error log(restart istio-ingressgateway):
2022-06-08T13:20:27.514937Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected

This bug causes envoy to fail to parse local_jwks properly, because the n dynamically generated by jwks before this is not base64 encoded.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by howardjohn** [comment]
what changed? was it always broken? envoy became more strict?

**Comment by hzxuzhonghu** [comment]
The branch has no chance to run in normal case, we need an integration test to cover it

**Comment by aryan16** [comment]
Why is it not failing in the first push before ingress restart?

**Comment by hzxuzhonghu** [comment]
I guess during this time, there is no xds push

**Comment by hexiaodai** [comment]
> what changed? was it always broken? envoy became more strict?

```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
...
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: http://ip:port/auth
    jwksUri: http://ip:port/auth/xxx/certs
```
1. Whenever my jwksuri fails, restarting istio ingressgateway will fail to start normally.
2. yes.
3. The JWKS structure consists of an array of JWK entries named "keys". Previously, the N dynamically generated by jwks was not Base64 encoded.
| Key | Contents |
| :-- | :-- |
| n | The modulus (2048 bit) of the key - Base64URL encoded. |

**Comment by hexiaodai** [comment]
> Why is it not failing in the first push before ingress restart?

Because my authn authentication server works normally during the first push

**Review by aryan16 — APPROVED** [review]

**Comment by hexiaodai** [comment]
> @[hexiaodai](https://github.com/hexiaodai) Can you add a release note, we need to backport this fix

@hzxuzhonghu How do I add a release note? I'm not familiar with the operation of github. 😂

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/tree/master/releasenotes

**Comment by hexiaodai** [comment]
> @[hexiaodai](https://github.com/hexiaodai) Can you add a release note, we need to backport this fix

@hzxuzhonghu a release note has been added😂

**Comment by kebe7jun** [comment]
auto cherry-pick seems not work...

/cherry-pick release-1.14
/cherry-pick release-1.13

**Pull request merged**
