### PR TITLE
retry remote clusters that fail to init

### PR DESCRIPTION
**Pull request by stevenctl**
https://github.com/istio/istio/issues/38440

This should help these clusters recover.

### CODE REVIEW

**Comment by stevenctl** [comment]
One worry I had is will this treat all the retries as "update" instead of "add". But after inspecting the code it seems like we will always treat things as add. @hzxuzhonghu 

We delete here

https://github.com/istio/istio/blob/53ae9db2d3595aa31d170d134701f6a05319fc3a/pkg/kube/multicluster/secretcontroller.go#L328-L334

then the check here never passes:

https://github.com/istio/istio/blob/8da4506000e267f80ddd926efa771c4bd7b0a8a0/pkg/kube/multicluster/secretcontroller.go#L343

**Comment by hzxuzhonghu** [comment]
Should be very careful to be idempotent

**Comment by hzxuzhonghu** [comment]
@stevenctl 

The delete only happens on those that exist in secret before, but after secret updated, the items are not there

**Comment by Minh-Ng** [comment]
@stevenctl @hzxuzhonghu is this still relevant? seem like https://github.com/istio/istio/pull/40542 helped with retries but for extended periods of time Istiod will still never recover to the desired state without being restarted

**Pull request closed without merging**
