### PR TITLE
Add headersToDownstreamOnAllow for ext authz

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/36950

### CODE REVIEW

**Comment by hanxiaop** [comment]
@yangminzhu PTAL. Thanks!

**Review by yangminzhu — COMMENTED** [review]
looks good, could you also add an e2e test for the new field in `TestAuthorization_Custom()` (tests/integration/security/authorization_test.go)

**Comment by hanxiaop** [comment]
@yangminzhu I tried, however it looks like envoy doesn't return the additional headers to me in `headersToDownstreamOnAllow` case. It looks like the test patched the `extensionProviders` config to the latest istio testing image, which doesn't contain the feature i wrote. Please correct me if I'm wrong, thanks! Or if it is, I'll update the e2e test once this PR get merged.

**Comment by hanxiaop** [comment]
@yangminzhu PTAL. Thanks!

**Comment by jitendra-fareye** [comment]
We need this feature in Istio.
@hanxiaop Thanks for creating this PR. 
@yangminzhu Please help getting this PR into Istio.

**Review by yangminzhu — APPROVED** [review]

**Review by ramanujadasu — COMMENTED** [review]
Could you please review and approve: @howardjohn

**Review by GregHanson — APPROVED** [review]

**Pull request merged**
