### PR TITLE
Optimize yamllint to run in one process

### PR DESCRIPTION
**Pull request by howardjohn**
Previously we ran a new process for every yaml file. yamllint can just
take in a list of files to run, and handles this much more efficiently.
On my machine, this broguht runtime from 75s to 15s.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
/lgtm

not sure why the label didn't get added

**Comment by irisdingbj** [comment]
> /lgtm
> 
> not sure why the label didn't get added

because I am not an `OWNER` of `test`.  you may need an OWNER's lgtm

**Pull request merged**
