### PR TITLE
create namespace before applying manifests in operator

### LINKED ISSUE #24037: istio control plane only installs in istio-system namespace using istio-operator
**Bug description**
When trying to create the IstioOperator CR in a different namespace than istio-system, the operator does not create the control plane resources. Neither creating a component in a specific namespace described here https://istio.io/docs/setup/install/istioctl/#configure-component-settings does not work.

**Expected behavior**
Istio control plane or components should install in any system using the IstioOperator CRD.

**Steps to reproduce the bug**
```
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ istioctl version
no running Istio pods in "istio-system"
1.6.0
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get ns
NAME              STATUS   AGE
default           Active   10d
kube-node-lease   Active   10d
kube-public       Active   10d
kube-system       Active   10d
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ istioctl operator init
Using operator Deployment image: docker.io/istio/operator:1.6.0
- Processing resources for Istio operator.
- Processing resources for Istio operator.
- Processing resources for Istio operator.
  Processing resources for Istio operator.
- Processing resources for Istio operator.
- Processing resources for Istio operator.
- Processing resources for Istio operator.
  Processing resources for Istio operator. Waiting for Deployment/istio-operator/istio-operator
- Processing resources for Istio operator. Waiting for Deployment/istio-operator/istio-operator
- Processing resources for Istio operator. Waiting for Deployment/istio-operator/istio-operator
✔ Istio operator installed

✔ Installation complete
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get ns
NAME              STATUS   AGE
default           Active   10d
istio-operator    Active   11s
kube-node-lease   Active   10d
kube-public       Active   10d
kube-system       Active   10d
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pod -n istio-operator
NAME                              READY   STATUS    RESTARTS   AGE
istio-operator-58f98cd489-29clx   1/1     Running   0          24s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ cat istiooperator1.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  profile: default
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl create ns test
namespace/test created
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl apply -f istiooperator1.yaml -n test
istiooperator.install.istio.io/istiocontrolplane created
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A
NAMESPACE   NAME                AGE
test        istiocontrolplane   6s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A -o yaml
apiVersion: v1
items:
- apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"test"},"spec":{"profile":"default"}}
    creationTimestamp: "2020-05-22T12:11:31Z"
    generation: 1
    name: istiocontrolplane
    namespace: test
    resourceVersion: "1045202"
    selfLink: /apis/install.istio.io/v1alpha1/namespaces/test/istiooperators/istiocontrolplane
    uid: 9a28cdb1-677a-4edc-a265-bda0be6d6d60
  spec:
    profile: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n test -w
╚[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A
NAMESPACE   NAME                AGE
test        istiocontrolplane   2m43s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A -o yaml
apiVersion: v1
items:
- apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"test"},"spec":{"profile":"default"}}
    creationTimestamp: "2020-05-22T12:11:31Z"
    generation: 1
    name: istiocontrolplane
    namespace: test
    resourceVersion: "1045202"
    selfLink: /apis/install.istio.io/v1alpha1/namespaces/test/istiooperators/istiocontrolplane
    uid: 9a28cdb1-677a-4edc-a265-bda0be6d6d60
  spec:
    profile: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n test -w
╚[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl create ns istio-system
namespace/istio-system created
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl apply -f istiooperator1.yaml -n istio-system
istiooperator.install.istio.io/istiocontrolplane created
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A
NAMESPACE      NAME                AGE
istio-system   istiocontrolplane   5s
test           istiocontrolplane   3m9s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator istiocontrolplane -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"istio-system"},"spec":{"profile":"default"}}
  creationTimestamp: "2020-05-22T12:14:35Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 1
  name: istiocontrolplane
  namespace: istio-system
  resourceVersion: "1045523"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istiocontrolplane
  uid: e95e203f-7abe-417d-ae45-1928f56a2e46
spec:
  profile: default
status:
  status: RECONCILING
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n istio-system -w
NAME                      READY   STATUS    RESTARTS   AGE
istiod-788cf6c878-ggj57   0/1     Running   0          5s
istiod-788cf6c878-ggj57   1/1     Running   0          5s
istio-ingressgateway-569669bb67-th45v   0/1     Pending   0          0s
istio-ingressgateway-569669bb67-th45v   0/1     Pending   0          0s
istio-ingressgateway-569669bb67-th45v   0/1     ContainerCreating   0          0s
prometheus-79878ff5fd-4bkhl             0/2     Pending             0          0s
prometheus-79878ff5fd-4bkhl             0/2     Pending             0          0s
prometheus-79878ff5fd-4bkhl             0/2     ContainerCreating   0          0s
istio-ingressgateway-569669bb67-th45v   0/1     Running             0          8s
istio-ingressgateway-569669bb67-th45v   1/1     Running             0          11s
prometheus-79878ff5fd-4bkhl             0/2     Running             0          11s
prometheus-79878ff5fd-4bkhl             1/2     Running             0          13s
prometheus-79878ff5fd-4bkhl             2/2     Running             0          13s
╚[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator istiocontrolplane -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"istio-system"},"spec":{"profile":"default"}}
  creationTimestamp: "2020-05-22T12:14:35Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 1
  name: istiocontrolplane
  namespace: istio-system
  resourceVersion: "1045824"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istiocontrolplane
  uid: e95e203f-7abe-417d-ae45-1928f56a2e46
spec:
  profile: default
status:
  componentStatus:
    AddonComponents:
      status: HEALTHY
    Base:
      status: HEALTHY
    IngressGateways:
      status: HEALTHY
    Pilot:
      status: HEALTHY
  status: HEALTHY
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ cat istiooperator2.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  profile: default
  components:
    citadel:
      enabled: true
      namespace: test-citadel
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl create ns test-citadel
namespace/test-citadel created
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl apply -f istiooperator2.yaml -n istio-system
istiooperator.install.istio.io/istiocontrolplane configured
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A
NAMESPACE      NAME                REVISION   AGE
istio-system   istiocontrolplane              97s
test           istiocontrolplane              4m41s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator istiocontrolplane -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"istio-system"},"spec":{"components":{"citadel":{"enabled":true,"namespace":"test-citadel"}},"profile":"default"}}
  creationTimestamp: "2020-05-22T12:14:35Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 2
  name: istiocontrolplane
  namespace: istio-system
  resourceVersion: "1045952"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istiocontrolplane
  uid: e95e203f-7abe-417d-ae45-1928f56a2e46
spec:
  components:
    citadel:
      enabled: true
      namespace: test-citadel
  profile: default
status:
  componentStatus:
    AddonComponents:
      status: RECONCILING
    Base:
      status: RECONCILING
    IngressGateways:
      status: RECONCILING
    Pilot:
      status: RECONCILING
  status: RECONCILING
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n test-citadel -w
╚[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A
NAMESPACE      NAME                REVISION   AGE
istio-system   istiocontrolplane              2m40s
test           istiocontrolplane              5m44s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator istiocontrolplane -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"istio-system"},"spec":{"components":{"citadel":{"enabled":true,"namespace":"test-citadel"}},"profile":"default"}}
  creationTimestamp: "2020-05-22T12:14:35Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 2
  name: istiocontrolplane
  namespace: istio-system
  resourceVersion: "1046011"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istiocontrolplane
  uid: e95e203f-7abe-417d-ae45-1928f56a2e46
spec:
  components:
    citadel:
      enabled: true
      namespace: test-citadel
  profile: default
status:
  componentStatus:
    Pilot:
      status: HEALTHY
  status: HEALTHY
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator -A
NAMESPACE      NAME                REVISION   AGE
istio-system   istiocontrolplane              2m44s
test           istiocontrolplane              5m48s
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n test-citadel -w
╚[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ cat istiooperator3.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  profile: default
  components:
    citadel:
      enabled: true
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl apply -f istiooperator3.yaml -n istio-system
istiooperator.install.istio.io/istiocontrolplane configured
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator istiocontrolplane -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"istio-system"},"spec":{"components":{"citadel":{"enabled":true}},"profile":"default"}}
  creationTimestamp: "2020-05-22T12:14:35Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 3
  name: istiocontrolplane
  namespace: istio-system
  resourceVersion: "1046160"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istiocontrolplane
  uid: e95e203f-7abe-417d-ae45-1928f56a2e46
spec:
  components:
    citadel:
      enabled: true
  profile: default
status:
  componentStatus:
    Pilot:
      status: RECONCILING
  status: RECONCILING
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n istio-system -w
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-569669bb67-th45v   1/1     Running   0          3m8s
istiod-788cf6c878-ggj57                 1/1     Running   0          3m14s
prometheus-79878ff5fd-4bkhl             2/2     Running   0          3m8s

╚[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get istiooperator istiocontrolplane -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"istiocontrolplane","namespace":"istio-system"},"spec":{"components":{"citadel":{"enabled":true}},"profile":"default"}}
  creationTimestamp: "2020-05-22T12:14:35Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 3
  name: istiocontrolplane
  namespace: istio-system
  resourceVersion: "1046225"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istiocontrolplane
  uid: e95e203f-7abe-417d-ae45-1928f56a2e46
spec:
  components:
    citadel:
      enabled: true
  profile: default
status:
  componentStatus:
    Pilot:
      status: HEALTHY
  status: HEALTHY
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl get pods -n istio-system -w
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-569669bb67-th45v   1/1     Running   0          3m45s
istiod-788cf6c878-ggj57                 1/1     Running   0          3m51s
prometheus-79878ff5fd-4bkhl             2/2     Running   0          3m45s
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ istioctl version --remote
no running Istio pods in "istio-system"
1.6.0
[cloud-user@nci-service-mesh-performance-benchmark-1 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
IstioOperator

**Environment where bug was observed (cloud vendor, OS, etc)**
vanilla Kubernetes 1.16.6, Rhel 7.8, Openstack VM

### PR DESCRIPTION
**Pull request by erdun**
Create namespace before applying manifests in operator

FIx #24037

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I am a bit confused. The operator is installing in the namespace that the IOP exists in. So how can the namespace not exist?

**Comment by erdun** [comment]
`WATCH_NAMESPACE` default value is `istio-system`, but you can set other namespaces to watch the IOP

**Comment by howardjohn** [comment]
@erdun are you saying that I create an IOP in namespace `foo` and then the operator is modifying resources in `istio-system`? That seems wrong

**Comment by erdun** [comment]
But the cli tell the user can do this

```
istioctl operator init -h                                                                                                                                                                  !10006
The init subcommand installs the Istio operator controller in the cluster.

Usage:
  istioctl operator init [flags]

Flags:
  -d, --charts string              Specify a path to a directory of charts and profiles
                                   (e.g. ~/Downloads/istio-1.5.0/install/kubernetes/operator)
                                   or release tar URL (e.g. https://github.com/istio/istio/releases/download/1.5.1/istio-1.5.1-linux.tar.gz).

      --dry-run                    Console/log output only, make no changes.
  -f, --filename string            Path to file containing IstioOperator custom resource
  -h, --help                       help for init
      --hub string                 The hub for the operator controller image (default "docker.io/istio")
      --operatorNamespace string   The namespace the operator controller is installed into (default "istio-operator")
      --tag string                 The tag for the operator controller image (default "1.6.0")

Global Flags:
      --context string          The name of the kubeconfig context to use
  -i, --istioNamespace string   Istio system namespace (default "istio-system")
  -c, --kubeconfig string       Kubernetes configuration file
  -n, --namespace string        Config namespace
```


`--operatorNamespace` which namespace the operator run
`--istioNamespace`  watch namespace that IOP in
`IOP: .spec.values.globa.istioNamespace` which namespace istio to install

**Comment by dgn** [comment]
That's not really how this works... `global.istioNamespace` is largely a relict of istio/installer times

**Comment by dgn** [comment]
As @howardjohn said, if you want the control plane to be installed somewhere else, you have to create the IOP resource there

**Comment by erdun** [comment]
The operator can watch the namespace IOP in by env `WATCH_NAMESPACE`, but the namespace   that control plane installed in is decided by `global.istioNamespace`, they can be different

**Pull request closed without merging**
