### PR TITLE
Delete redundant service handler

### PR DESCRIPTION
**Pull request by dddddai**
Signed-off-by: dddddai <dddwq@foxmail.com>

**Please provide a description of this PR:**
It seems redundant to append service handler in `ClusterAdded`, because the handler has already been appended in `initRegistryEventHandlers`

This patch would reduce unnecessary push requests

related snippet:
https://github.com/istio/istio/blob/fe652368feb59068c6693452deaf5f6d8664c205/pilot/pkg/bootstrap/server.go#L861-L877
https://github.com/istio/istio/blob/fe652368feb59068c6693452deaf5f6d8664c205/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L208
https://github.com/istio/istio/blob/fe652368feb59068c6693452deaf5f6d8664c205/pilot/pkg/serviceregistry/aggregate/controller.go#L71-L80

### CODE REVIEW

**Comment by stevenctl** [comment]
I think this patch would make it so we only fire the push for service updates in the "main" cluster this istiod is watching. 

Instead we could either:
1. Remove the handler we setup in `initRegistryEventHandlers`, since we do it in `multicluster.go`
2. Gate the `AppendServiceHandler` call in `multicluster.go` with `if localCluster`

**Comment by dddddai** [comment]
@stevenctl Thanks for your review :)
> I think this patch would make it so we only fire the push for service updates in the "main" cluster this istiod is watching.

Why? When a "remote" cluster added, it would callback `ClusterAdded` and call `AddRegistryAndRun` to append the service handler to remote registry.

So it should fire the push for remote services, shouldn't it? Please correct me if I'm wrong

**Comment by stevenctl** [comment]
Yes it should fire the push

**Comment by hzxuzhonghu** [comment]
/ok-to-test

seems good

**Review by stevenctl — APPROVED** [review]

**Comment by stevenctl** [comment]
misunderstood at first pass – this looks good

**Pull request merged**
