### PR TITLE
Prow postsubmit runs unit tests sequentially

### PR DESCRIPTION
**Pull request by chxchx**
Mitigates https://github.com/istio/istio/issues/4230

### CODE REVIEW

**Comment by chxchx** [comment]
I have tested the postsubmit script by running through presubmit unit tests jobs and it passes.

**Comment by mattdelco** [comment]
You mentioned that postsubmit passes, but did all the instances of pause/cont also disappear?  I figure that's a straightforward way to get a clue about whether the parallelism did get appropriately suppressed.

**Comment by chxchx** [comment]
@mattdelco Oh yeah, checking for pause/cont would be a good test. According to this, my previous fix still allows in-package parallelism (based on the [log](https://00e9e64bac834d1b817f856ce83ae1ab4442a7d431e890b3b6-apidata.googleusercontent.com/download/storage/v1/b/istio-prow/o/pull%2Fistio_istio%2F4242%2Fistio-unit-tests%2F2242%2Fbuild-log.txt?qk=AD5uMEvt5RKBtKTyMFvBBiOpu8UqdsMDjGqEU6Ev_7Ap_ca3oQ2lQIMopjPmlL5jeOxpRfUIxMeXufX8pjeUg8YtgML_rAOUVjvVEyo6Mt_0v7SZLImax7p6FO7Jv1VY_boalThBWOeTO4bQTvleV8Ze7qG8MqWdvHzy6MnxGQRIjtIc73oWdd-kqaMHoI51KnUmyuFa4Ua2_269qbVNQFxtJcdZqpaP7xYz1sP4xMjS7SF89XGlXOhN4npI3Z54sw1LzVWw2s-6aNCMQR34ZOJfl6dQTgFymZzRCHlW_vt-Lt5zj21SFrmwElDZfTKl45_HxjxAnZ5g7N-yLhT_Ys-5oL2kbgTx6uC-zvcm6xKbC2UOdIEOtbg4h9jS42ql0JAdaMWDBxA738eLgeMFcyvGtDPvgaoGCKNvSX1BrE62vCXSq5KSAfTLpe98YHw4n7nBwUYEhRB069zcip5MvRbZY-QUpuU7_ek0W3EoTL-O8SGChgo3CQF9TjJ0vEMvq4wQ4XxxK3zpJHyAdZS50EnKL1kWmbQ8v_2ysIb9wSdtuPPcJxxJ5NKEBImX-1kJoNV9ywPBik1Ks8GtqyEICrHcx1hHPSsHKSviNOXwb2-lolWCyZfzDAh6Oox-XpSHP1APW8ah0GZ0YO-eCQli7DYyD5fKQ6WQHvE8fec-e77fFni_lqxwie6L8YVwrot7oJ5vrRRWOFdYRvXMDvFivPFGj5r2iMnaDjEhAe6a6xPjXY7T5-ZtOQ4dvKCft0O-h8R_RB4YVtanzX3upflRYLqVdsvJ3xt8nJvhUtqzhHaUOQlPryx6RXk)), since `-p 1` and `-parallel 1` had different meaning. I added this in the latest commit and hopefully that does the trick.

**Comment by chxchx** [comment]
If a test case calls `t.Parallel()` I don't think it is possible to completely remove the PAUSE/CONT logging based on go testing source code https://go-review.googlesource.com/c/go/+/49430/3/src/testing/testing.go#663. This PR is be best we can do to retrain parallelism using only flags.

The false positives reported by go-junit-report is due to parallel execution of test cases with the same name from different packages and one of them panic-ed. I believe removing package parallelism should be fine.

**Pull request merged**
