### PR TITLE
Exclude Prometheus traffic in rule so that Kiali does not show it.

### PR DESCRIPTION
**Pull request by pilhuhn**
Cherry pick of #12251

### CODE REVIEW

**Comment by pilhuhn** [comment]
@douglas-reid This replaces #13711, which I foo-bar'd

**Comment by douglas-reid** [comment]
@pilhuhn you may want to send this to `master` and then cherry-pick it back, but I'll let the release managers help with sorting that out: @duderino @fpesce

**Comment by pilhuhn** [comment]
@douglas-reid Not sure I get it - that is a cherry-pick from master, where it was merged as #12251

**Comment by douglas-reid** [comment]
@pilhuhn ah, ok. i've lost track. nevermind.

**Comment by pilhuhn** [comment]
Ping @mandarjog - could you please have a look?

**Comment by sdake** [comment]
> @douglas-reid Not sure I get it - that is a cherry-pick from master, where it was merged as #12251 It unfortunately did not make the cut-off for 1.1, which is why I submitted this one.

@phil9909 you can always use the -x option to git to produce output that the reviewers will know is a pure cherrypick.  Another option is to use the mergify annotations on a PR to automate the cherrypick process, although that wouldn't have worked in this case.

Cheers
-steve

**Comment by pilhuhn** [comment]
@sdake How can we progress this? Shall I close and resubmit as cp -x (which I think does not add additional information to solve this)? I am open to all suggestions that help here :)

**Comment by sdake** [comment]
@pilhuhn no sense creating extra work.  In the future, if you could use cherrypick `-x` that helps reviews know its a cherrypick, if there were merge collisions, etc.

This PR looks ready to go - minus the gate failure.  That will need to be rectified prior to merging.  The next step is the release manager must manually merge it.  I've assigned to the relmgr for 1.1 for this purpose.

Cheers
-steve

**Comment by sdake** [comment]
This is a fatal flake ```2019-05-28T21:54:04.863904Z	info	Command output: 
Error: error validating "": error validating data: field spec.volumeClaimTemplates[0].spec.dataSource for v1.PersistentVolumeClaimSpec is required
2019-05-28T21:54:04.864007Z	info	Command error: exit status 1
2019-05-28T21:54:04.864038Z	error	Failed to complete Init. Error helm install stable/redis failed, setValue=--set usePassword=false,persistence.enabled=false
2019-05-28T21:54:04.864046Z	info	Saving logs```

I'm not sure how consistently this problem occurs, however, if it happens often it is something T&R should look into.

Cheers
-steve

**Comment by duderino** [comment]
I'm in super risk averse mode right now with the 1.1 branch.  What are the implications of not merging this?   If not super severe, I'd like to ship this in 1.2 which is only ~3 weeks away

**Comment by pilhuhn** [comment]
@duderino Not merging results in "a bit bogus" telemetry in case Prometheus is told to scrape metrics from the users containers. 
Certainly far from a security fix. 
While I'd like to see it merged, I can understand that you are reluctant.

**Comment by duderino** [comment]
@pilhuhn thanks for the assessment.  I'm rejecting this for 1.1 branch for now, but if you get a lot of user complaints please point me to them and I'll reconsider.

Also, please send to master and release-1.2 if you haven't already.  @fpesce and @linsun are the release manager for the 1.2 branch so they will have their own opinions ;)

**Comment by pilhuhn** [comment]
Looks like this is already in release-1.2, so I guess we are good there.

**Pull request closed without merging**
