### PR TITLE
revert fault filter change

### PR DESCRIPTION
**Pull request by ramaraochavali**
As being discussed https://github.com/istio/istio/pull/36259#issuecomment-982286784 and below, I think we do not need to add filter at top level and per route config will take care of it.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM, give a chance to @howardjohn to take a look

**Comment by ramaraochavali** [comment]
Looked at Envoy code again, the original filter chain is built based on the filters defined in HCM and when the filter is executed it resolves the most specific config. So adding it to http filters is needed. Not sure how csrf test passed for me yesterday.

**Comment by ramaraochavali** [comment]
@howardjohn @hzxuzhonghu can PTAL? Any concerns with this?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
