### PR TITLE
istiod: merge iptables binaries into pilot-agent

### LINKED ISSUE #20038: iptables: subcommand under pilot-agent
istio-init is already using the proxyv2 docker image, with two (maybe 3, not sure if we have the "clean" binary as well) binaries for init and proxying. We should just merge the two into a single binary with multiple cobra commands. This makes operation simpler since there is a single binary and makes the build, image pull, etc faster since the image is smaller.

cc @lambdai @rlenglet @abhide

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/20038

This drops the proxyv2 image about 25mb, and adds 0.5mb to the
pilot-agent binary.

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]
Nice!

**Comment by howardjohn** [comment]
Unit tests are blocked by https://github.com/istio/istio/pull/21881

**Comment by howardjohn** [comment]
/retest

dependent PR merged

**Review by nmittler — APPROVED** [review]

**Pull request merged**
