### PR TITLE
[Release-1.6] Change to comma separated value for app_container (#25441)

### PR DESCRIPTION
**Pull request by gargnupur**
* Change to comma separated value for app_container

Signed-off-by: gargnupur <gargnupur@google.com>

Run make gen

Signed-off-by: gargnupur <gargnupur@google.com>

Add test for container  name

Signed-off-by: gargnupur <gargnupur@google.com>

Update VM test files

Signed-off-by: gargnupur <gargnupur@google.com>

Change to comma separated value for app_container

Signed-off-by: gargnupur <gargnupur@google.com>

Run make gen

Signed-off-by: gargnupur <gargnupur@google.com>

Add test for container  name

Signed-off-by: gargnupur <gargnupur@google.com>

* Fix vm test

Signed-off-by: gargnupur <gargnupur@google.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by gargnupur** [comment]
@jacob-delgado : can you please take a look at this?

**Comment by gargnupur** [comment]
@jacob-delgado : Can you please help merge this?

**Comment by jacob-delgado** [comment]
cc @gargnupur We are in a code freeze until August 11th due to a CVE. I will put on a do-not-merge and approve it. I will remove it after we ship 1.6.8.

**Comment by jacob-delgado** [comment]
## DO NOT MERGE UNTIL 1.6.8 HAS BEEN RELEASED

**Pull request merged**
