### PR TITLE
Generalize default webhook message

### LINKED ISSUE #50687: don't talk about injection if the install profile is ambient
```
$ istioctl install --set profile=ambient --skip-confirmation
✔ Istio core installed                                                                                                                                             
✔ Istiod installed                                                                                                                                                 
✔ CNI installed                                                                                                                                                    
✔ Ztunnel installed                                                                                                                                                
✔ Installation complete                                                                                                                                            
Made this installation the default for injection and validation.
```

That last line is confusing to someone who is only installing ambient.

### PR DESCRIPTION
**Pull request by leosarra**
**Please provide a description of this PR:**

Fixes #50687

### CODE REVIEW

**Comment by leosarra** [comment]
@craigbox

**Review by howardjohn — COMMENTED** [review]
It still impacts ambient. Gateways, for example, are injected.

There is also leader election, etc impacted. Probably even the "before" state was not great.

I am not sure a good way to word it though :slightly_smiling_face:

**Review by linsun — COMMENTED** [review]
I also share the concern of @leosarra and wanted to change the msg every time I install istio :)

How about just printing out:
if ambient:
  The ambient profile has been installed successfully, enjoy Istio without sidecars!
else:
  same msg as today?

**Comment by howardjohn** [comment]
We could also generally say "Set as the default for cluster-wide operations"

**Comment by craigbox** [comment]
> The ambient profile has been installed successfully, enjoy Istio without sidecars!

You're really leaning into the cutesy lately there Lin :)

**Comment by linsun** [comment]
> > The ambient profile has been installed successfully, enjoy Istio without sidecars!
> 
> You're really leaning into the cutesy lately there Lin :)

Mainly to emphasize the message `without sidecars` :)

**Comment by leosarra** [comment]
Sorry for the delay, I had some days off.

> We could also generally say "Set as the default for cluster-wide operations"

I like the idea of making the msg more general. Updated to "Made this installation the default for cluster-wide operations.".

I have also added a post-install msg specific to ambient based on @linsun proposal.

**Review by linsun — APPROVED** [review]

**Pull request merged**
