### PR TITLE
Support customization of Envoy bootstrap config (#11559)

### PR DESCRIPTION
**Pull request by howardjohn**
Already merged into master: https://github.com/istio/istio/pull/11559#issuecomment-462656579

* Support customization of Envoy bootstrap config

This change allows override the default Envoy bootstrap configuration
for a resource. A sample is included to show how it can be used.

* Format code

* Fix tests

### CODE REVIEW

**Comment by duderino** [comment]
Saw a 

```
*** Test killed with quit: ran too long (26m0s).
FAIL	istio.io/istio/tests/e2e/tests/galley	1560.005s
make: *** [test/local/e2e_galley] Error 1
```

in the galley e2e tests.  https://circleci.com/gh/istio/istio/324127?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@ozevren @ayj FYI

/retest

**Comment by howardjohn** [comment]
I think the circleci tests need to be restarted from circleci (not `/retest`)? Which I cannot do since I do not have permissions. But both the e2e-galley and lint fail look unrelated to my change

**Comment by ozevren** [comment]
```

* command failed: "Error from server (BadRequest): container \"prometheus\" in pod \"prometheus-646dbcbbbf-wfjh5\" is waiting to start: PodInitializing\n" exit status 1
namespace "istio-system" deleted
```

It looks like this is a setup issue with the test. @ayj had a PR that helped identify such issues more clearly.

**Comment by ozevren** [comment]
I've restarted the test

**Comment by duderino** [comment]
istio-integ-k8s-test usually fails:  https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/istio-integ-k8s-tests
istio-pilot-multicluster-e2e almost always fails:  https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/istio-pilot-multicluster-e2e

I'll merge this as soon as I see a looks good to me

**Comment by costinm** [comment]
Also: circle is not restarted by retest, you need to go to the circle page, click on the workflow and 
hit 'rerun failed'.

They have an API and could be integrated in retest - but nobody had time to do it.

**Pull request merged**
