### PR TITLE
Fix potential fd leak

### PR DESCRIPTION
**Pull request by zrss**
fixes: #9760

### CODE REVIEW

**Comment by ymesika** [comment]
Not stale. Can you please re-open this one with `release-1.1` branch?

**Comment by zrss** [comment]
@ymesika  .. er what a long time and it is still not be fixed

**Comment by ymesika** [comment]
> @ymesika .. er what a long time and it is still not be fixed

Right, sorry about that. Sometimes prow is stuck and valid PRs are just becoming stale.
Thank you for re-opening.

**Pull request closed without merging**
