### PR TITLE
Fix two integration tests when jwtPolicy=first-party-jwt

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/20178

    - Fix two integration tests when jwtPolicy=first-party-jwt
    - Fix a wrong log of Pilot grpc server

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
the unit test failures are from a new test I added, and is not a bug, just need to update the golden files - but since we are not merging this everything looks good

**Comment by lei-tang** [comment]
@howardjohn Thank you for explaining why unit-tests_istio fails! This PR contains a fix (i.e., set global.controlPlaneSecurityEnabled=false) for two tests when jwtPolicy=first-party-jwt. So I think it should be merged. Is there a command for updating the golden files?

**Comment by howardjohn** [comment]
REFRESH_GOLDEN=true go test ./pkg/kube/...

we merge but should keep 3p as default

**Comment by lei-tang** [comment]
@howardjohn Thanks! After this PR is merged, I will create a follow up PR to test and set the third-party-jwt as default. Thus, we have integration-tested both first-party-jwt and third-party-jwt.

**Comment by howardjohn** [comment]
lei, this pr already tested with 1p jwt, we do not need to merge it in order to test it? should we just keep only the test changes and merge now?

**Comment by lei-tang** [comment]
@howardjohn the PR has been revised based on your suggestion. Please take a look.

**Review by howardjohn — APPROVED** [review]

**Review by myidpt — APPROVED** [review]

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/19918

**Pull request merged**
