### PR TITLE
remove deprecated outboundTrafficPolicy from global values.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.
resolve: https://github.com/istio/istio/issues/27494 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by richardwxn — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
What happens to the in cluster operator if someone bumps a patch release and this is now rejected?

**Comment by morvencao** [comment]
@howardjohn there will be error message in the logs of in-cluster operator.

**Comment by jwendell** [comment]
@morvencao Is there any corresponding pr in master (or this is not a cherry-pick?).
Also, can you fix the conflicts?

**Comment by morvencao** [comment]
@jwendell The PR: https://github.com/istio/istio/pull/25778/files#diff-856492d2c49d39f2a9362307746c1174 contains this change to master.

**Review by JimmyCYJ — APPROVED** [review]

**Pull request merged**
