### PR TITLE
[kiali] upgrade to 1.38

### PR DESCRIPTION
**Pull request by jmazzitelli**
This should be applied to the 1.11 branch also.

cc @howardjohn

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I did not apply this on Istio 1.11 - someone should sanity check this.

**Review by howardjohn — APPROVED** [review]
LGTM. I didn't manually test this though, I am assuming the Kiali team has?

Thanks for the fixes :slightly_smiling_face:

**Review by douglas-reid — APPROVED** [review]

**Comment by jmazzitelli** [comment]
> LGTM. I didn't manually test this though, I am assuming the Kiali team has?

We are going to grab the latest 1.11 beta and apply this. I have not personally done so yet.

**Review by morvencao — APPROVED** [review]

**Pull request merged**
