### PR TITLE
[release-1.17] Break system namespace and ingressgateway assumptions

### LINKED ISSUE #43864: [release-1.17] Break system namespace and ingressgateway assumptions
Manual cherrypick required.

#43809 failed to apply on top of branch "release-1.17":
```
Applying: Custom ingress field and templatize certain tests for systemNamespace
Using index info to reconstruct a base tree...
M	pkg/test/framework/components/istio/kube.go
M	tests/integration/pilot/common/traffic.go
Falling back to patching base and 3-way merge...
Auto-merging tests/integration/pilot/common/traffic.go
CONFLICT (content): Merge conflict in tests/integration/pilot/common/traffic.go
Auto-merging pkg/test/framework/components/istio/kube.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Custom ingress field and templatize certain tests for systemNamespace
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by keithmattix**
Cherry-pick of #43809 due to merge conflicts. Fixes #43864

### CODE REVIEW

**Comment by johnma14** [comment]
@keithmattix is there any reason why we want to back port this to 1.17? Thanks.

**Comment by keithmattix** [comment]
@johnma14 Sure, happy to provide context! Without this change, the istio.deploy test flag is basically useless (if your preinstalled istio is in a different namespace) because several tests assume that the systemNamespace is istio-system. Because this change fixes a bug in the integration test suite, I categorized it as a bug fix and backported it

**Review by johnma14 — APPROVED** [review]
Thanks Keith.

**Pull request merged**
