### PR TITLE
Recompute service account at endpoint shard when all endpoints are removed

### PR DESCRIPTION
**Pull request by bianpengyuan**
fix https://github.com/istio/istio/issues/36465 and https://github.com/istio/istio/issues/31534.

The sequence to trigger the issue:

1. Scale down a service's workloads to zero, either manually, or some upgrade or reschedule event. This will trigger an EDS push, which does not update Cluster / push CDS.
2. Update any istio config or any service, which will trigger a Cluster update and CDS push for all services (Note CDS cache is invalidated at step 1, which means Cluster for this service will be recomputed), and for this service, since there is no endpoint, the default validation context / SAN match will be empty `"default_validation_context": {}`.
3. Now scale up the workloads, this will trigger another EDS push, and we have the logic to check if the service accounts have any update (https://github.com/istio/istio/blob/4dea7d99eba0ab42e84056d50e1a96151f301887/pilot/pkg/xds/eds.go#L150). if there is, a CDS update will also be triggered. However, whether the service account change is checked against the EndpointShards cache, which is not cleaned up when all endpoints get removed at step 1, so no CDS update will happen.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Nice, LGTM but will let @ramaraochavali or @hzxuzhonghu take a look since I think they are familiar with this code deeply.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@howardjohn ping for release notes approval. thanks!

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
