### PR TITLE
Update operator SHA

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by tmshort** [comment]
Is this the right version? when I do a `go mod vendor` it seems to pull down operator 1.4.4?

**Comment by howardjohn** [comment]
> Is this the right version? when I do a go mod vendor it seems to pull down operator 1.4.4?

Not sure why it would do that. Its pointing to https://github.com/istio/operator/commit/291f72e5ff741a331fedc8dff0e623f4b578b578 which is the head of the branch?

**Comment by tmshort** [comment]
Yes, looks to be the case; but even there on release-1.4, pkg/vfs/assets.gen.go  lists up to 1.4.4 in the `_versionsYaml` array. Unfortunately, I can't give a line number link due to file-size, but if one searches for "1.4.4", you'll see the list.. and it doesn't include 1.4.5, 1.4.6 nor 1.4.7. So, I could be misunderstanding, especially if the operator doesn't follow the same version numbers as istio/istio

**Comment by howardjohn** [comment]
@elfinhe ^

**Comment by elfinhe** [comment]
now we range express to represent supported versions.

**Pull request merged**
