### PR TITLE
hpa support for memory

### PR DESCRIPTION
**Pull request by AdheipSingh**
Adding support for memory in hpa, with autoscaling/v2beta2 api version.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is not supported on GKE, which a large number of Istio users run on

**Comment by AdheipSingh** [comment]
@howardjohn agreed as v2beta2 still not for GKE, here have hpa added for v2beta1

**Comment by zehuaiWANG** [comment]
agree with @howardjohn , I don't think it should be added before the supporting of GKE.

**Comment by AdheipSingh** [comment]
@zehuaiWANG v2beta1 is supported in GKE, have changed to v2beta1

**Comment by hobbytp** [comment]
@AdheipSingh why use targetAverageValue instead of targetAverageUtilization for memory? user need to change the value for different deployments. Thanks for clarification.

**Comment by AdheipSingh** [comment]
@hobbytp in this case both values should be configurable, make sense.

**Pull request closed without merging**
