### PR TITLE
Add env var GLIBC_PATH to enable mix build test on CentOS

### PR DESCRIPTION
**Pull request by dove-young**
Fix issue https://github.com/istio/istio/issues/9358

CentOS 7.x incorporate with GLIBC 2.17 instead of 2.18 which requires by Envoy.  So that `mix` build testing will fail because Envoy cannot start on CentOS 7.x by default.  

Here is a solution to let user build a separate `glibc-2.18` on CentOS 7 and tell Istio build process to use it. 

- Let user to build a separate `glibc-2.18` on CentOS 7

```
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar zxvf glibc-2.18.tar.gz
cd glibc-2.18
mkdir build
cd build
../configure --prefix=/opt/glibc-2.18
make -j4
make install
```

- Specify customized `glibc-2.18` path to environment variable `GLIBC_PATH`
  - `export GLIBC_PATH=/opt/glibc-2.18/lib`
- With this patch,  `mixer/test/client/env/envoy.go` will know where GLIBC 2.18 is by  environment variable `GLIBC_PATH` 
- Then build will go smoothly by start Envoy with GLIBC 2.18

If user build Istio on an environment in which glibc-2.18 is incorporated, then environment variable `GLIBC_PATH` is not necessary to set

### CODE REVIEW

**Comment by sdake** [comment]
@dove-young I think a better approach may be to use the native CentOS built glibc/toolchains that are modernized.  Reference the SCL devtoolset 7.  IIRC this has a more modern glibc in addition to the rest of the toolchains:

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

**Comment by lizan** [comment]
@dove-young Can you elaborate a bit more about the glibc dependency? I don't think Envoy has hard glibc dependency to be >= 2.18, it might be just a build problem of Envoy / Istio proxy.

**Comment by sdake** [comment]
@dove-young I am not certain why envoy requires glibc2.18 - perhaps because it is compiled against a glibc 2.18 implementation.  I have asked for further guidance on this thread:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/envoy-users/XK9M-RhWrxg/ttrLobxgAgAJ

**Comment by lizan** [comment]
Looks like the glibc 2.18 dependency is introduced by linking libstdc++ with glibc >= 2.18.

Reference link: https://bugs.chromium.org/p/chromium/issues/detail?id=749077

I think we can either take approache described in the link above (which is pretty ugly solution though), or just build istio proxy / envoy on CentOS 7.

**Comment by dove-young** [comment]
Since envoy is used in running test code for mix, it would be much easier to give developer/contributor an option to provide qualified GLIBC to get ride of it.

**Comment by dove-young** [comment]
Apply same change to `pkg/test/envoy/envoy.go` to align to current master head

**Comment by sdake** [comment]
@dove-young thank you for the contribution.  I really do feel this approach isn't quite right.  I know folks want CentOS base images, and the way to make that happen is to work with the Envoy community to build a CentOS based Envoy.  In that case, Envoy would link against 2.17 of gibc, Istio would download the CentOS specific image if a centos build was desired, and tagging would be used to ensure folks knew if they were getting an ubuntu or centos variant of Istio.  Containers are not always portable between Linux distros, despite what people may claim.

If you want to tackle this work, I'd suggest reaching out to @knrc as I believe he has an interest in solving this problem from a Red Hat perspective.

Cheers
-steve

**Comment by knrc** [comment]
@dove-young @sdake Apologies for the delay in responding.  FYI we create CentOS/RHEL images as part of our release and currently use glibc-2.17-260.el7.x86_64 in the CentOS container.

**Pull request closed without merging**
