### PR TITLE
Remove unused scripts

### PR DESCRIPTION
**Pull request by rshriram**
Removing stale scripts, and artifacts. Updating docs.

### CODE REVIEW

**Comment by linsun** [comment]
can we move git work flow to an individual page?   I think that page is useful.  else LGTM.

**Comment by geeknoid** [comment]
Please bring back the GitHub workflow stuff. There is no reason to delete this and it is useful, no everyone is a GitHub wizard.

**Comment by kyessenov** [comment]
Please also update testing doc in pilot. There are useful instructions to
set up RBAC and golden files.

**Comment by ldemailly** [comment]
$ curl -L https://git.io/getIstio
404: Not Found

**Comment by rshriram** [comment]
Well, you forced all docs to use getLatestIstio (https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps) and thanks to you, all release scripts have started using this. So I don't see why its getting ridiculous :). Besides, this file was not updated for three months.

**Comment by rshriram** [comment]
and @kyessenov those RBAC instructions belong in istio.github.io setup, as they are applicable to general istio users as well.

**Pull request merged**
