### PR TITLE
mixer: update test certificates

### LINKED ISSUE #16184: Unit test failure - re-enable pilotplugin_mtls test
Certs are expired: https://github.com/istio/istio/tree/2bfefe78b746c4f0c2b23e3bc2605492c2ab74a8/mixer/test/client/pilotplugin_mtls/testdata

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Fixes #16184

/assign @howardjohn 
/assign @PiotrSikora

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Could you please extend them by more than a year? Otherwise, we're going to run into the same issue a year from now.

**Comment by kyessenov** [comment]
This code won't exist in a year or so we thought :)

**Comment by howardjohn** [comment]
> This code won't exist in a year or so we thought :)

People can still checkout the code though, and now tests will fail. Especially if we continue supporting istio 1.3 for 6 more months, I could see the test being around longer than a year

**Comment by kyessenov** [comment]
Changed it to 5 years.

**Comment by howardjohn** [comment]
@geeknoid @JimmyCYJ @douglas-reid can you take a look?

**Pull request merged**
