### PR TITLE
update multicluster kind image

### PR DESCRIPTION
**Pull request by stevenctl**
Part one for https://github.com/istio/istio/issues/29025 to sync KinD versions

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by stevenctl** [comment]
fixes https://github.com/istio/istio/issues/29025

**Comment by stevenctl** [comment]
@howardjohn added a hold so you can have a chance to check the second commit in the PR

This is a temp fix – the default should be in the common-files repo so we can change for istio and istio.io

**Comment by howardjohn** [comment]
LGTM again

**Comment by howardjohn** [comment]
Thanks for the fix

**Pull request merged**
