### PR TITLE
WIP envoy2envoy

### PR DESCRIPTION
**Pull request by lambdai**
With the ::6 or 127.0.0.6 trick we have better solution of intercept local traffic.

Will enable the future local to local mtls traffic. 

Signed-off-by: Yuchen Dai <silentdai@gmail.com>

### CODE REVIEW

**Comment by lambdai** [comment]
Running e2e test and gather failed cases

**Comment by hzxuzhonghu** [comment]
I will try this in https://github.com/istio/istio/pull/19496

**Comment by lambdai** [comment]
e2e passes. 
Update golden file

**Comment by hzxuzhonghu** [comment]
please check failure in https://github.com/istio/istio/pull/19496

**Comment by hzxuzhonghu** [comment]
It still cannot resolve pod access itself under mtls

**Comment by lambdai** [comment]
There are 3 OUTPUT cases:
1) envoyinbound: dont redirect
2) envoyoutbound: dont redirect
3) appoutbound: redirect

(1) could be identified by source ip 127.0.0.6
(2) could be identified by uid/gid 1337
(3) is the rest

However, the below rule b eager redirect 2). 
```
a iptables -t nat -A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
b ptables -t nat -A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -j ISTIO_REDIRECT
c iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 0 -j RETURN
```

will try swap b and c

**Comment by lambdai** [comment]
> please check failure in #19496

@hzxuzhonghu will check tmr using your branch. My brain stop working now :)

**Comment by hzxuzhonghu** [comment]
>will try swap b and c

@lambdai Will this also disable the traffic to itself goes through envoy?

**Comment by lambdai** [comment]
lots of failures
will investigate today

**Pull request closed without merging**
