### PR TITLE
simplify codecov test

### PR DESCRIPTION
**Pull request by mandarjog**
**What this PR does / why we need it**:
Replace multi process codecov by a single process codecov.
It is a bit slower but more reliable.

```release-note
NONE
```

### CODE REVIEW

**Comment by mandarjog** [comment]
This is failing because API repo is not up to date. 
@ayj  `pilot/proxy/envoy/policy.go:53:61: mesh.MtlsExcludedServices undefined (type *istio_proxy_v1_config.MeshConfig has no field or method MtlsExcludedServices)` Is this related to the changes you made? Is the sha updated in istio/istio ?

**Comment by GregHanson** [comment]
@mandarjog the circleci test uses `dep ensure` and not bazel build.  Test was originally broken here:
https://github.com/istio/istio/pull/1718

**Comment by ayj** [comment]
>  Is this related to the changes you made? Is the sha updated in istio/istio ?

ISTIO_API_SHA points to a previous version of proxy mesh config without the mtls field. This isn't an issue bazel (official build system) since it still auto-generates *.pb.go from *.proto, only the experimental "go dep".

**Pull request merged**
