### PR TITLE
set GOGC on golangci-linter

### PR DESCRIPTION
**Pull request by kyessenov**
/assign @howardjohn 

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by howardjohn** [comment]
Restarted circle to see if it passing lnit was a flake

**Comment by kyessenov** [comment]
/assign @geeknoid 
for approval

**Comment by howardjohn** [comment]
Doesn't seem to fix https://circleci.com/gh/istio/istio/397319?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link maybe need to revert 1.16 update. What was the update for?

**Comment by kyessenov** [comment]
Why is it so random on circle? I cannot reproduce it locally (and I have 16GB), and both my PRs passed the checks.
Let's try to push GC aggressiveness even higher then?

**Comment by howardjohn** [comment]
We can try that. Does this definitely indicate OOM? `bin/linters.sh: line 69: 21146 Killed                  golangci-lint run -j 1 -v ./...`

**Comment by kyessenov** [comment]
Yes, it's OOMing mostlikely. Golang has a notoriously bad GC so it permits out of memory condition for the sake of performance. Although, I'm not sure why there is this much variance in the outcome.

**Comment by kyessenov** [comment]
We do need to keep updating since we need to pick up the fixes in golang toolchain (e.g. the segfault that happens for a number of people is a bug in golang, not the linter).

**Pull request merged**
