### PR TITLE
Use go 1.22

### PR DESCRIPTION
**Pull request by jacob-delgado**
**Please provide a description of this PR:**

Go 1.22 includes changes to the language (see https://tip.golang.org/doc/go1.22#language). It's possible that some unit tests may break or bugs appear. Let's start testing this early before 1.22.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Should we wait a bit for this? I think this will require everyone to upgrade to 1.22 right now I think

**Comment by jacob-delgado** [comment]
We can hold off for now. Still need to fix any linting issues. Let's see if anything breaks. I don't intend to change api as that may break other users.

**Comment by keithmattix** [comment]
Should we wait until quic-go has support for 1.22?

**Comment by jacob-delgado** [comment]
Do you think now would be a good time to get this merged?

**Pull request merged**
