### PR TITLE
test: a flake fix

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by mandarjog** [comment]
@kyessenov did you remove a flaky test here?
Not sure how are you testing this...

**Comment by kyessenov** [comment]
@mandarjog I commented all but one test that flakes. There might be some interference between test cases.

**Comment by kyessenov** [comment]
No idea how it passed the first time, but the envoyfilter had an indentation problem.

**Comment by kyessenov** [comment]
Fixes #31677

**Review by howardjohn — APPROVED** [review]
did you figure out why it ever worked?

**Comment by kyessenov** [comment]
> did you figure out why it ever worked?

nope. best guess is test interference.

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
