### PR TITLE
Support CliContext for all install commands

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by GregHanson — APPROVED** [review]

**Comment by ericvn** [comment]
I suspect this is a big big regression as it broke commands like `istioctl uninstall --revision=default --context=kind-doc-cluster1`.

Investigating now.

**Comment by frankbu** [comment]
> I suspect this is a big big regression as it broke commands like istioctl uninstall --revision=default --context=kind-doc-cluster1.

Maybe the regression has to do with running two istioctl uninstall commands at the same time?
https://github.com/istio/istio.io/blob/d843c65402fa3ba4cb44ca3e989f5cfbb6e7d21d/content/en/docs/setup/install/multicluster/common.sh#L80

**Comment by ericvn** [comment]
See discussion in https://github.com/istio/istio.io/pull/13819, but the istio.io tests that install istio into multiple clusters and then try to uninstall istio from those clusters fails as the --context from the uninstall is ignored.

**Comment by ericvn** [comment]
> Maybe the regression has to do with running two istioctl uninstall commands at the same time? https://github.com/istio/istio.io/blob/d843c65402fa3ba4cb44ca3e989f5cfbb6e7d21d/content/en/docs/setup/install/multicluster/common.sh#L80

I tried removing the & in the uninstalls in a commit, and that test still failed..

**Comment by ericvn** [comment]
See https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/13819/doc.test.multicluster_istio.io/1699476474538496000/artifacts/tests-setup-multicluster-63d9b8/TestDocs/setup/install/multicluster/multi-primary/test.sh/cleanup.sh/_test_context/cleanup.sh_output.txt for output.

**Pull request merged**
