### PR TITLE
mixer: remove xDS struct

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

/assign @howardjohn

### CODE REVIEW

**Comment by mandarjog** [comment]
@kyessenov is this safe now? We do not need struct again?

**Comment by kyessenov** [comment]
The code has been ripped off envoy. It will just reject config with struct I think. I've tried removing it from all of istio, but it's impossible to get everyone's approval, so let's just do mixer.

**Comment by howardjohn** [comment]
@kyessenov was the issue approval or failing tests?

**Comment by kyessenov** [comment]
@howardjohn Probably both. I was not able to get feedback on why some tests were failing, and I'm not familiar with those parts of istio.

**Comment by howardjohn** [comment]
If I remember right it was just the security stuff? We should try to clean everything up soon, it doesn't make sense to have an option that doesn't work + makes our code more complicated

**Comment by kyessenov** [comment]
I think so. There was some weird change in meaning whether you use struct vs any because of some embedded messages being set/unset. Our APIs assign semantics to empty protos (e.g. x: { y : {}} is not the same as x: {}), so I didn't want get to deep into those details.

**Pull request merged**
