### PR TITLE
Add function to create kubeClient for istio CRDs by passing in a restconfig

### PR DESCRIPTION
**Pull request by angelachin**
We are using a Istio client for a custom Kubernetes controller.

We noticed that in other projects in which there is a client for a CRD, the client can be instantiated by passing in a restConfig. This PR provides the same capability for initializing the Istio client.

In particular, we wanted this use case to be able to specify our master server address without having to set an environment variable (which is currently the case).

Ideally, to be most in line with other controllers we've seen, we would also like to remove `domainSuffix` from the `NewForConfig` function, but do not entirely understand the repercussions of doing so.

Please let us know thoughts and feedback. Thanks!

Co-authored-by: Jeff Pak <jeffrey.pak@dell.com>

### CODE REVIEW

**Comment by angelachin** [comment]
I signed the CLA.

**Comment by hzxuzhonghu** [comment]
> having to set an environment variable (which is currently the case).
What's env?

**Comment by angelachin** [comment]
> > having to set an environment variable (which is currently the case).
> 
> What's env?

I'm not sure what you mean by this. When I say environment variable, I'm specifically referring to `KUBERNETES_MASTER`, which is used to specify the address of the cluster master I wish to target. Right now, if that is not set it defaults to `localhost:8080`. I'm targeting a separate kubernetes cluster that lives outside where my binary is being run.

**Comment by jeffpak** [comment]
I signed it!

**Comment by hzxuzhonghu** [comment]
`KUBERNETES_MASTER` is the env k8s.io/client-go using.

**Comment by hzxuzhonghu** [comment]
This is kind of code enhancement.

/lgtm

**Comment by hklai** [comment]
@angelachin @rshriram @hzxuzhonghu 
it looks like this commit was merged to master but is missing from release-1.1. Is this needed in release-1.1?

**Comment by hzxuzhonghu** [comment]
It is a refactor, it doesn't matter whether it is in or not.

**Pull request merged**
