### PR TITLE
kube-inject: hide namespace flag in favour of istioNamespace

### PR DESCRIPTION
**Pull request by shamsher31**
Attempt to fix https://github.com/istio/istio/issues/28005

Based on @linsun comments

> I recommend us enhance it to search for sidecar innjector cm in the -n ns.

### CODE REVIEW

**Comment by shamsher31** [comment]
@esnible PTAL.

**Review by esnible — DISMISSED** [review]
Perhaps instead of treating `--namespace` as a second `--istioNamespace` we should just disable inheriting `--namespace` from the root command?

**Comment by shamsher31** [comment]
@esnible Is it ok to keep also fallback in case someone made a mistake?

This is done.
```
Global Flags:
      --context string          The name of the kubeconfig context to use
  -i, --istioNamespace string   Istio system namespace (default "istio-system")
  -c, --kubeconfig string       Kubernetes configuration file
```

**Comment by esnible** [comment]
If it ever had an effect, it hasn't had an effect in a long time.

I don't believe any scripts use it.  If you are concerned about breaking scripts, hide `--namespace` and print a message to stdout if `--namespace` has a value saying that `--namespace` is deprecated.

**Comment by shamsher31** [comment]
No problem, only hiding `namespace`.

**Comment by shamsher31** [comment]
@esnible PTAL.

**Review by irisdingbj — APPROVED** [review]
LGTM

**Pull request merged**
