### PR TITLE
Use global imagePullPolicy

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by howardjohn** [comment]
Can you make this to https://github.com/istio/installer?

**Comment by clyang82** [comment]
> Can you make this to https://github.com/istio/installer?

Sure. I saw there is a branch `release-1.2` in https://github.com/istio/installer. The new installer is available for `release-1.2`. right?

**Comment by howardjohn** [comment]
@clyang82 yes, for 1.2 we will offer both. istio/installer will be as an alpha, in 1.3 we are targeting it as the only installer

**Comment by howardjohn** [comment]
@clyang82 to clarify, just submit it to master and we will backport it to 1.2 for you, we have a bot that cherry-picks

**Comment by clyang82** [comment]
> @clyang82 yes, for 1.2 we will offer both. istio/installer will be as an alpha, in 1.3 we are targeting it as the only installer

Thanks for your information. so I think this PR should go into istio (stable) and istio/installer (alpha). WDYT?

**Comment by morvencao** [comment]
I think this should go to release branch(release-1.2), too.

**Pull request merged**
