### PR TITLE
Adapter CloudwatchLogs support in the existing Mixer Cloudwatch adapter

### PR DESCRIPTION
**Pull request by karanvasnani**
Adding support in the existing Mixer CloudWatch adapter to also send LogEntries to AWS CloudWatchLogs platform. It is an extension to the existing adapter which only sends metrics to AWS CloudWatch.

### CODE REVIEW

**Comment by douglas-reid** [comment]
Looks like some conflicts and failed tests.  Once those are resolved I'll take a look.  I believe this was an lgtm in the previous PR, so this shouldn't be a lengthy review.

**Comment by karanvasnani** [comment]
@douglas-reid The tests which failing are because of changes in the vendor directory resulted by running `dep ensure`. 
For example: 
`# istio.io/istio/pilot/pkg/kube/inject
pilot/pkg/kube/inject/initializer.go:56:4: undefined: "istio.io/istio/vendor/github.com/openshift/api/apps/v1".LegacySchemeGroupVersion`
Is occurring because running dep ensure has removed the file with field LegacySchemeGroupVersion.

Am I doing something wrong with respect to handling vendor dependency changes?

**Comment by karanvasnani** [comment]
@douglas-reid This is what I see when I run `dep version`:
`dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.10
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false`

Yeah I can wait for a while till the vendor changes are stable. Just let me know when it happens. Thanks :)

**Comment by douglas-reid** [comment]
@karanvasnani I apologize for losing track of this PR. What can we do to get this unblocked and merged ?

**Comment by karanvasnani** [comment]
Yeah I checked that it's going to take a lot of effort to rebase this over other commits and then check if it passes all the tests. I'll do that mostly this weekend. Although I'm not sure if dep ensure will work as expected.

**Comment by karanvasnani** [comment]
@douglas-reid I tried to fix the issues with this pr but it was too much effort because I had before merged in changes from upstream instead of doing rebase. Closing this pr and creating simplified PR with just two commits one for code changes and another for gopkg.lock and vendor changes here https://github.com/istio/istio/pull/10366. Closing this PR. Thanks..

**Comment by douglas-reid** [comment]
OK. I'll keep trying to track this. let's get this in this next week (🤞)

**Pull request closed without merging**
