### PR TITLE
[1.4] Update CODEOWNERS and master references

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by geeknoid — APPROVED** [review]
Is this strictly necessary? I thought branch protection would automatically prevent random people from approving changes to the branch.

**Comment by howardjohn** [comment]
> Is this strictly necessary? I thought branch protection would automatically prevent random people from approving changes to the branch.

The goal here was to avoid release managers needing admin privileges to force merge every PR, which breaks tide and is not good from a security standpoint (more admins) and safety standpoint (breaking tide == worse testing)

**Comment by howardjohn** [comment]
This is the model we followed in 1.3 as well and it worked very well. I think you can remove our admin access

**Comment by rlenglet** [comment]
+1 setting maintainers as owners of the release branch worked great for 1.3.

**Review by jwendell — APPROVED** [review]

**Comment by howardjohn** [comment]
Force merging to change owners file

**Pull request merged**
