### PR TITLE
Fuzzing: Add parse k8s object fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
Adds a fuzzer for `object.ParseK8sObjectsFromYAMLManifest`

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by AdamKorcz** [comment]
The failed test looks like a flaky to me. I will wait a bit with retesting.

**Comment by howardjohn** [comment]
Yeah there was a bad PR merged, revert should land soon

**Pull request closed without merging**
