### PR TITLE
Fix prometheus and citadel connection tests (#12747)

### PR DESCRIPTION
**Pull request by phil9909**
Cherrypicked as requested in https://github.com/istio/istio/pull/12747#issuecomment-477800936

* Fix test-prometheus-connection.yaml: test never failed

Co-authored-by: Ralf Pannemans <ralf.pannemans@sap.com>

* Fix test-citadel-connection.yaml: test never failed

Co-authored-by: Ralf Pannemans <ralf.pannemans@sap.com>

### CODE REVIEW

**Comment by jsPlachetka** [comment]
@costinm @mandarjog Could you have a look at this please?

**Comment by sdake** [comment]
@jsPlachetka this PR is ready for merge - awaiting review by the release managers now.

Cheers
-steve

**Comment by duderino** [comment]
LOL I had an extremely perverse thought while reviewing this:  "if I merge this won't it be more likely to see test failures"

Must not be evil....

Merging....

**Pull request merged**
