### PR TITLE
[release-1.9] Fix sidecar injector default template config option. (#30353)

### PR DESCRIPTION
**Pull request by bianpengyuan**
cherry-pick to fix https://github.com/istio/istio/issues/30402. Also update operator test snapshot and regenerate test golden files.

* Fix sidecar injector default template options.

* add a test for sidecar template

* add test files

* update data snapshot and gen golden file

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by shamsher31** [comment]
The original PR https://github.com/istio/istio/pull/30353 have `14` file changes where as this cherry-pick have `46`. Can you please make sure that the cherry-pick should only match the files which got merged in `master`?

**Review by shamsher31 — CHANGES_REQUESTED** [review]
The original PR https://github.com/istio/istio/pull/30353 have `14` file changes where as this cherry-pick have `46`. Can you please make sure that the cherry-pick should only match the files which got merged in `master`?

**Comment by bianpengyuan** [comment]
After cherry-pick, I ran `./operator/scripts/run_update_golden_snapshots.sh` and then `make gen`, which is needed for the newly added test. Even at head of 1.9, after running these two command, there are ton of diff. To make it easy, I made a separated PR https://github.com/istio/istio/pull/30427 which bring test data up to date. After merging that, diff in this PR should be reasonable.

**Comment by shamsher31** [comment]
Can you just run `make refresh-goldens` and then `make gen` and update this PR?

**Comment by bianpengyuan** [comment]
The test output generated by running only `make refresh-goldens` and `make gen` wont reflect the latest change in the helm charts. They are still based on old charts.

This is the diff of doing only`make refresh-goldens` and `make gen` after cherry-pick: https://github.com/istio/istio/compare/release-1.9...bianpengyuan:injector-v2/default-templates-fix-19-new?expand=1#diff-6b0c583ea048fdce001ad0a0ef77a75ee80d2e4b2a87b45bf09e2cd8640f8e6fR165 and if you look at the new test output file `operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml, it still has the configuration removed by this PR:
```
...
    # NOTE: this currently only allows a single element
    defaultTemplates: [sidecar]
...
```

> Ideally, it is required when make gen fails.

Do you mean the test charts snapshot should not be updated? I update the test data snapshot here since I want to make sure the test output could reflect this fix. Not sure what is appropriate.

**Comment by bianpengyuan** [comment]
Now the other change #30427 has been merged and this change is much smaller. Please take another look, thanks!

**Review by jacob-delgado — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]

**Comment by shamsher31** [comment]
Thanks @bianpengyuan

**Pull request merged**
