### PR TITLE
Create container containing helm manifests

### PR DESCRIPTION
**Pull request by jacob-delgado**
Issue: Upgrade testing for helm requires access to each of the manifest
charts for each potentially each version of istio (e.g. 1.8.0, 1.8.1,
etc...). However, checking in these charts is problematic as they are
10k+ lines with few changes per patch release and potentially a lot of
change for minor versions.

Solution: Create a docker image that contains the helm charts
for each version post 1.8.0. The integration testing framework will have
to be extended to call this docker file similar to the following

docker run -v KUBEPATH:/kubeconfig/kube.config gcr.io/istio:manifests \
    install istio -n istio-system /manifests/1.8.0/base \
    --kubeconfig /kubeconfig/kube.config

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by jacob-delgado** [comment]
We could also put this in `istio/tools` if that is a better location, but first I'd like to get feedback on this approach before we proceed.

**Comment by ericvn** [comment]
I don't think the mount command is quite correct, but this is indeed what I had planned in my comment in #29697.

**Review by howardjohn — COMMENTED** [review]
I am not sure I understand why a docker image is better than checking in the files. If it's just to not store it in the repo, then why are we using docker instead of something like GCS?

**Comment by howardjohn** [comment]
Also I think helm can install from a remote gcs and/or GitHub repo? That may be another path instead of copying it then using helm with local files

**Comment by howardjohn** [comment]
Despite alternatives mentioned above, my initial preference would be to check them in, but I may he missing context on why this is any issue. This is a tried-and-true approach used by other projects to do the same thing. Git can easily handle 10k lines of yaml, and we will only ever have a few copies (if you have more than a few the limit is going to be our testing times)

**Comment by jacob-delgado** [comment]
> Also I think helm can install from a remote gcs and/or GitHub repo? That may be another path instead of copying it then using helm with local files

Long-term that may be the path as we may publish the helm charts in a repo for others to consume. We can change the way we use the charts if that's the case.

> I am not sure I understand why a docker image is better than checking in the files. If it's just to not store it in the repo, then why are we using docker instead of something like GCS?

> Despite alternatives mentioned above, my initial preference would be to check them in, but I may he missing context on why this is any issue. This is a tried-and-true approach used by other projects to do the same thing. Git can easily handle 10k lines of yaml, and we will only ever have a few copies (if you have more than a few the limit is going to be our testing times)

In the PR for a simple helm upgrade test https://github.com/istio/istio/pull/29697 the checked in files for the manifests (1.8.1) were over 16k lines. Git can easily handle this, but I was exploring if there was a way to do it without checking in so many files. It can be error prone to do that, so there may be alternatives ways to do it instead of manually. I'm fine with closing this PR and re-evaluating it if it becomes untenable. We are probably thinking too far ahead as we intend to test skip-level upgrades.

**Comment by jacob-delgado** [comment]
Closing as we will check-in manifests for a releases.

**Pull request closed without merging**
