### PR TITLE
WIP: Templatize sidecar injection template

### PR DESCRIPTION
**Pull request by cmluciano**
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/istio/istio/issues/1624

**Special notes for your reviewer**:
- [ ] should all options have the if/else logic within the[ template](https://github.com/cmluciano/istio/blob/6dc3b1eacd4c10223cd37c1ee7c5f9b34089c1c6/pilot/platform/kube/inject/inject.go#L119-L123) and create a similar function to  [injectIntoSpec](https://github.com/cmluciano/istio/blob/6dc3b1eacd4c10223cd37c1ee7c5f9b34089c1c6/pilot/platform/kube/inject/inject.go#L411) (The if/else logic for every option does not read well to me when shown in a Go template)
- [x] Or should we just unmarshal the template (w/o if related logic)passed in and follow defaulting logic in 
[injectIntoSpec](https://github.com/cmluciano/istio/blob/6dc3b1eacd4c10223cd37c1ee7c5f9b34089c1c6/pilot/platform/kube/inject/inject.go#L411)

**Release note**:
```
support passing a file to kube-inject for configuring a sidecar proxy
```

### CODE REVIEW

**Comment by cmluciano** [comment]
@ayj I added notes/questions in the PR description for feedback

**Comment by ayj** [comment]
Putting aside how a template is generated from existing flags for a moment, I think we can just read template from ConfigMap, execute template over the pod spec, and unmarshal the result as a list of containers/volumes. The only variables that would be templated in this context would be values that depend on the content of the pod spec itself, e.g. `secretName`, `serviceCluster`. Things like `image` would have a set value, e.g. `istio.io/proxy:0.2.12`.

Now, coming back to how the template itself is created, either by kube-inject flags or as part of release process, it seems we need a template of templates. This outer template would never be exposed directly to the end-user but instead exist to create the user-facing template from flags.

**Comment by rshriram** [comment]
sync with master

**Comment by linsun** [comment]
Would this help if user wants to deploy app with helm without using the initializer?  trying to understand the user value for this.

**Comment by ayj** [comment]
Helm users would use kube-inject, either as part of creating their own helm files, as after-the-fact when deploying vanilla k8s resources into a cluster.

Also, see https://github.com/kelseyhightower/konfd for an example that leverages go templates for config mgmt. Our implementation wouldn't look exactly like this, but it does demonstrate precedence for this approach.

**Comment by cmluciano** [comment]
@ayj ack

Do we need if/else to preserve templated initializer configuration [as it is today](https://github.com/istio/istio/blob/master/pilot/platform/kube/inject/inject.go#L205-L227)

**Comment by cmluciano** [comment]
closing in favor of #1895

**Pull request closed without merging**
