### PR TITLE
Set HTTP connection manager to normalize path. (#14191)

### PR DESCRIPTION
**Pull request by yangminzhu**
Cherry-pick the change from `master` to `1.2`, the change didn't make to 1.2 branch as it's merged a few hours after the 1.2 cut.

/cc @liminw

### CODE REVIEW

**Comment by howardjohn** [comment]
/lgtm
@fpesce this is P0 for 1.2 -- without this we will have a security regression as we are back on upstream Envoy without this change on by default

**Comment by rshriram** [comment]
is this available in Envoy from Istio 1.1 ? If not, then this is a breaking change..

**Comment by rshriram** [comment]
and if its a breaking change, then master needs to be fixed

**Comment by yangminzhu** [comment]
@rshriram I don't think this is available in 1.1, but I assume Envoy will just ignore it as we start Envoy with option `--allow-unknown-fields`?

**Comment by rshriram** [comment]
if it works then great

**Pull request merged**
