### PR TITLE
[Release 1.11]  Fix misue service's pointer address in map 

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Manually cherry-pick #34898

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
@hzxuzhonghu is this an user-visible change? If so it needs a release note entry

**Comment by hzxuzhonghu** [comment]
This is a bug which can happend in very rare case, so i guess this is not user-visible.  WDYT?

**Comment by jwendell** [comment]
Hard to say, reading https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes maybe it fits in the `Fixes of bugs that have not been released.` category?

**Comment by hzxuzhonghu** [comment]
@jwendell kindly ping

**Review by jwendell — APPROVED** [review]

**Pull request merged**
