### PR TITLE
Add mesh id cluster scoped webhookconfig

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

This is to support multi control plane deployments. RFC is [here](https://docs.google.com/document/d/1y4liRJbQW0NCMeQtqMma46flVqs-izV1/edit) 

We need to distinguish cluster scoped resources `mutatingWebhookConfiguration` and `validatingWebhookConfiguration`

This patch added mesh ID label to the configs, so istiod can only handle configs which belong to it.

TODO: apply discoverySelector to the configs.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
cc @kfaseela

**Comment by ramaraochavali** [comment]
Is webhook supporting different meshids sufficient for multi tenancy? What about about other configuration? is it based on DiscoverySelectors and tenancy is based on namespace? If yes, why not label namespace with meshid and configure selectors for webhooks accordingly?

**Review by howardjohn — COMMENTED** [review]
Why not use revision?

Without using revision or modifying the selectors on the webhook, this will mean that each pod calls each mesh's injector service which is not going to lead to good behavior.

The RFC linked does not describe the behavior in the PR as far as I can tell

**Comment by howardjohn** [comment]
It would be useful to have a full example of how this is expected to work in a real cluster

**Comment by kfaseela** [comment]
> Why not use revision?
> 
> Without using revision or modifying the selectors on the webhook, this will mean that each pod calls each mesh's injector service which is not going to lead to good behavior.
> 
> The RFC linked does not describe the behavior in the PR as far as I can tell

The RFC had the below suggestion:

**Webhook Patching**

- Use namespace label to restrict the namespace selectors (filter) of both k8s mutating and validating webhooks only to events from matching namespaces.

- Update the [istiod webhook cert patcher](https://github.com/istio/istio/blob/master/pkg/webhooks/webhookpatch.go#L65) to only monitor webhook resources matching namespace selector.

**Comment by hzxuzhonghu** [comment]
> Why not use revision?

This is because in case user want to isolate test and production mesh. Actually they would use istio with same revision, only reside in different namespaces. So I proposed using meshID to distinguish.

**Comment by hzxuzhonghu** [comment]
>Is webhook supporting different meshids sufficient for multi tenancy?

@ramaraochavali We have done many work to isolate by namespaces for CRD, for namespace level  CA root cert.  This is the left work  to isolate sidecar injectors and validators. Without this, it is not complete.

**Comment by ramaraochavali** [comment]
Why not use the same label selector approach that I mentioned above for webhook config also? Why we need separate mesh id?

**Comment by hzxuzhonghu** [comment]
> Why not use the same label selector approach that I mentioned above for webhook config also? Why we need separate mesh id?

This is automatically labeling

**Review by howardjohn — CHANGES_REQUESTED** [review]
Please expand a bit on how this will work. This code is extremely nuanced, and needs thorough review to ensure each webhook will select the appropriate workloads.

The linked RFC doesn't correlate to the PR.

**Comment by irisdingbj** [comment]
Since each webhookconfig has namespace as suffix already, can we leverage it for scoping directly?

**Comment by hzxuzhonghu** [comment]
> Since each webhookconfig has namespace as suffix already, can we leverage it for scoping directly?

@irisdingbj There is also a default validator, default sidecar injector config, so not viable unless we change the default name.

>Please expand a bit on how this will work. This code is extremely nuanced, and needs thorough review to ensure each webhook will select the appropriate workloads.

Yes, we will prepare a design for what should be done to supplement the original RFC

**Comment by kfaseela** [comment]
> > Since each webhookconfig has namespace as suffix already, can we leverage it for scoping directly?
> 
> @irisdingbj There is also a default validator, default sidecar injector config, so not viable unless we change the default name.
> 
> EDIT: this looks good, I do take a quick look again, and we did add a namespace suffix
> 
> https://github.com/istio/istio/blob/c76b484e2398829febc5182c4bc6ac4984cfd2e5/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml#L36-L40
> 
> only `istiod-default-validator` is a const,
> 
> https://github.com/istio/istio/blob/c76b484e2398829febc5182c4bc6ac4984cfd2e5/manifests/charts/default/templates/validatingwebhook.yaml#L4
> 
> > Please expand a bit on how this will work. This code is extremely nuanced, and needs thorough review to ensure each webhook will select the appropriate workloads.
> 
> Yes, we will prepare a design for what should be done to supplement the original RFC

@hzxuzhonghu Iris's suggestion will work with minimal changes right? Also that can be behind the new feature flag as well so that there are no other compatibility issues.

**Comment by hzxuzhonghu** [comment]
Yes

**Comment by hzxuzhonghu** [comment]
close this one with above comment

**Pull request closed without merging**
