### PR TITLE
(Done) Fix failed mixer tests

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is to fix the mixer test problems mentioned in https://github.com/istio/istio/pull/5426.

Diagnosis of the problems: 
1. when more than two of the following mixer tests are enabled, the test in mixer/test/client/tcp_filter_v1_config/tcp_filter_v1_config_test.go fails (the failure seems to be caused by the crash of Envoy). When no more than two of the following mixer tests are enabled, the test in mixer/test/client/tcp_filter_v1_config/tcp_filter_v1_config_test.go passes.
- mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go
- mixer/test/client/istio_authn_origin_jwt_bound_peer/authn_report_test.go
- mixer/test/client/istio_authn_origin_reject_no_jwt/authn_origin_reject_no_jwt_test.go
- mixer/test/client/istio_authn_peer_jwt_bound_origin/authn_report_test.go
- mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go
- mixer/test/client/istio_authn_peer_reject_no_jwt/authn_peer_reject_no_jwt_test.go
- mixer/test/client/istio_authn_peer_reject_no_mtls/authn_peer_reject_no_mtls_test.go
- mixer/test/client/istio_authn_peer_reject_no_tls/authn_peer_reject_no_tls_test.go

2. The result of running #5443 shows that the mixer tests in prow/istio-unit-tests still fail with tcp_filter_v1_config_test duplicated and #5267 reverted, which indicates that the existing mixer tests have problems.

### CODE REVIEW

**Comment by lei-tang** [comment]
The PRs/issues related to this PR are: https://github.com/istio/istio/pull/5426 and https://github.com/istio/istio/pull/5267. The PR has been updated to use os.Getenv() to enable/disable flaky mixer tests.

**Comment by hklai** [comment]
I think these tests failed fairly consistently after your other PR. I would not call them flaky and this PR effectively just disabled them in presubmit tests. I doubt this is the right way to go.

**Comment by lei-tang** [comment]
The PR has been updated to re-enable the disabled mixer tests. To fix the mixer test problems, the PR revises the code of adding the authn config in the tests.

**Comment by lei-tang** [comment]
The PR #5443 removes the newly added authn mixer tests in #5267 and duplicates tcp_filter_v1_config_test to debug whether the mixer test problem is caused by #5267.

**Comment by lei-tang** [comment]
#5443

**Comment by lei-tang** [comment]
The result of running #5443 shows that the mixer tests in prow/istio-unit-tests still fail with tcp_filter_v1_config_test duplicated and #5267 reverted.

**Comment by lei-tang** [comment]
The mixer test problem has been fixed by the PR https://github.com/istio/istio/pull/5458

**Pull request closed without merging**
