### PR TITLE
Close valiation readiness goroutine once it is ready

### PR DESCRIPTION
**Pull request by clyang82**
when the server is actually ready to serve, we should close the goroutine.

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by clyang82** [comment]
@ayj Thanks for your comments. I think Readiness probe is designed to let Kubernetes know when your app is ready to serve traffic. it is not designed to remove pod by k8s. it should be the responsible for Liveness probe. I do think we should add this health check in Liveness probe. What do you think?

**Comment by ayj** [comment]
Removed "from the service load balancer", i.e. the galley pod's IP is no longer included in the k8s endpoint ready list. This would handle transient failures. As you suggested, permanent failures should be still be handled by the liveliness probes.

**Comment by clyang82** [comment]
Do you think we should add permanent failures in liveness probe? if so, how to check the permanent failure? I think to have a real call to `/admitpilot` or `/admitmixer` in 1 second loop is a little overkill.
if you think it is unnecessary to add permanent failures check, let me just close this PR. Thanks.

**Pull request closed without merging**
