### PR TITLE
mixer: add grpc message counter test

### PR DESCRIPTION
**Pull request by kyessenov**
Requires https://github.com/istio/proxy/pull/2137

Adds a test to validate gRPC message counting telemetry.
I run this up to 100,000 variable-sized message but that takes 30s, so I reduced it to 1000 in the submitted test.

/assign @douglas-reid 
/assign @mandarjog 
/assign @geeknoid 

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
wakawakawaka

**Comment by douglas-reid** [comment]
@kyessenov this seems code mauve applicable. what's needed to complete this PR?

**Comment by kyessenov** [comment]
@douglas-reid The test assumes https://github.com/istio/proxy/pull/2137 which did not get merged. So we cannot really move forward without the proxy change.

**Comment by douglas-reid** [comment]
Whenever we get consensus around the proxy PR, I'm OK with this going in.

**Pull request closed without merging**
