### PR TITLE
Push some local test cleanups

### PR DESCRIPTION
**Pull request by bleggett**
**Please provide a description of this PR:**

Follow-on fixes from https://github.com/istio/istio/pull/50572

- use label suffixes
- drop weird `Annotation` indirection/aliasing used in test code that actually made refactoring + discovery harder, in favor of ye olde `map[string]string`

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Comment by bleggett** [comment]
> /test integ-security-multicluster

I don't think it's a flake, I just dorked something. Fixing.

**Review by hanxiaop — APPROVED** [review]
/retest

**Pull request merged**
