### PR TITLE
Update release to 0.2.11

### PR DESCRIPTION
**Pull request by wattli**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
0.2.11
```

### CODE REVIEW

**Comment by ldemailly** [comment]
change it to 0.2.12 ?

**Comment by ldemailly** [comment]
what's the replacement? we should move to 0.2.12 for download latest

**Comment by rkpagadala** [comment]
https://github.com/istio/istio/pull/1586

**Pull request closed without merging**
