### PR TITLE
Update istio/api dependency

### PR DESCRIPTION
**Pull request by jacob-delgado**
There have been 4 commits to istio/api for release-1.6 branch, but it doesn't appear that the automator auto merges updates (which can sometimes break).

### CODE REVIEW

**Comment by jacob-delgado** [comment]
@howardjohn I was testing the annotation `proxy.istio.io/config` and it wasn't working. I think this may be the issue why it wasn't as istio/api had your change. I'll test it after this makes it.

**Comment by howardjohn** [comment]
Missed cherrypick :confused:

**Comment by jacob-delgado** [comment]
@clarketm Is the automator setup to to update istio/istio@release-1.6 branch for changes to istio/api@release-1.6 branch?

**Comment by jacob-delgado** [comment]
Both @ericvn and @jasonwzm contributed to istio/api.

**Comment by jasonwzm** [comment]
I think tests will fail the same way as https://github.com/istio/istio/pull/23559. Creating PR in /api to fix the issue.

**Comment by clarketm** [comment]
> @clarketm Is the automator setup to to update istio/istio@release-1.6 branch for changes to istio/api@release-1.6 branch?

The [job](https://github.com/istio/test-infra/blob/936b24d31ae6c811968abe4cc0e4953acfc0b3b9/prow/config/jobs/api-1.6.yaml#L22) exists but it looks misconfigured. I will PR a fix. 
https://prow.istio.io/view/gcs/istio-prow/logs/update_api_dep_api_release-1.6_postsubmit/6

**Pull request closed without merging**
