### PR TITLE
optimize memory usage (#25531)

### PR DESCRIPTION
**Pull request by dozer47528**
Use ConfigKey for map keys will waste too much memory.

Before Optimize:

image

After Optimize

image

[x] Performance and Scalability

### CODE REVIEW

**Comment by ramaraochavali** [comment]
lgtm. Will leave it open for others review

**Comment by knight42** [comment]
I am a bit concerned that what if the hash code of two `ConfigKey`s happended to be the same? would `SidecarScope. DependsOnConfig()` report false positive?

**Comment by howardjohn** [comment]
If there is a false positive it will just result in an additional push. I
think the chance of collision is very small

**Pull request merged**
