### PR TITLE
Add lifecycle + terminationgracepriod to GW Chart

### PR DESCRIPTION
**Pull request by iainbowman**
**Please provide a description of this PR:**

The intention of this PR is to provide support for lifecycle (preStop hooks) and terminationGracePeriodSeconds to the Gateway deployment Helm chart.

### CODE REVIEW

**Comment by zirain** [comment]
see https://github.com/istio/istio/issues/38912#issuecomment-1126512011

**Comment by iainbowman** [comment]
Thanks, I wasn't aware of https://github.com/istio/istio/issues/38912#issuecomment-1126512011 and I understand your position on not adding lots of new fields. Would love to give this a try but unfortunately as we are using ArgoCD to deploy and it currently does not support helm post-render this solution will not work for my use case.

**Comment by howardjohn** [comment]
Seems it could be done via https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts

**Comment by iainbowman** [comment]
> Seems it could be done via https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts

Thanks I'll look into this 👍

**Pull request closed without merging**
