### PR TITLE
fix trivial style correction

### PR DESCRIPTION
**Pull request by jmuk**
These changes are done by bin/fmt.sh (i.e. gofmt / gosimple /
goimports / buildifier).

bin/fmt.sh has a new exclude pattern `*mock*.go`, which aims to
exclude auto-generated broker/pkg/model/config/mock_store.go.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by yutongz** [comment]
/lgtm
Thanks! 
BTW, you need extra approvers from either top level or from someone under mixer & security folders.  :)

**Comment by jmuk** [comment]
/assign @ldemailly 

@ldemailly, can you make the approval?

**Pull request merged**
