### PR TITLE
Add label test

### PR DESCRIPTION
**Pull request by adrianwg23**
Small test to get my first PR in and to get my feet wet in contributing to Istio! 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by adrianwg23** [comment]
@googlebot I signed it!

**Review by adiprerepa — APPROVED** [review]
LGTM, but you need a maintainer to approve.

Looks like lint is failing because the line is too long. You can split the conditional up to fix this.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
