### PR TITLE
Add requested server name attribute to release 1 0

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
Checked according to https://istio.io/docs/examples/advanced-egress/egress-gateway/#direct-https-traffic-through-an-egress-gateway.
 
`kubectl -n istio-system logs $(kubectl -n istio-system get pods -l istio-mixer-type=telemetry -o jsonpath='{.items[0].metadata.name}') mixer | grep tcpaccesslog.logentry.istio-system | grep '"connectionEvent":"open"'`

```
{"level":"info","time":"2018-08-17T02:30:32.692709Z","instance":"tcpaccesslog.logentry.istio-system","connectionDuration":"0s","connectionEvent":"open","connection_security_policy":"unknown","destinationApp":"istio-egressgateway","destinationIp":"172.30.146.115","destinationName":"istio-egressgateway-7fb9959565-6pdxk","destinationNamespace":"istio-system","destinationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-egressgateway","destinationPrincipal":"","destinationServiceHost":"edition.cnn.com","destinationWorkload":"istio-egressgateway","protocol":"tcp","receivedBytes":0,"reporter":"source","requestedServerName":"edition.cnn.com","sentBytes":0,"sourceApp":"sleep","sourceIp":"172.30.109.111","sourceName":"sleep-776b7bcdcd-f2dsb","sourceNamespace":"default","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/default/deployments/sleep","sourcePrincipal":"","sourceWorkload":"sleep","totalReceivedBytes":0,"totalSentBytes":0}
{"level":"info","time":"2018-08-17T02:30:32.696204Z","instance":"tcpaccesslog.logentry.istio-system","connectionDuration":"0s","connectionEvent":"open","connection_security_policy":"unknown","destinationApp":"","destinationIp":"151.101.1.67","destinationName":"unknown","destinationNamespace":"default","destinationOwner":"unknown","destinationPrincipal":"cluster.local/ns/istio-system/sa/istio-egressgateway-service-account","destinationServiceHost":"","destinationWorkload":"unknown","protocol":"tcp","receivedBytes":297,"reporter":"source","requestedServerName":"edition.cnn.com","sentBytes":0,"sourceApp":"istio-egressgateway","sourceIp":"172.30.109.111","sourceName":"istio-egressgateway-7fb9959565-6pdxk","sourceNamespace":"istio-system","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-egressgateway","sourcePrincipal":"cluster.local/ns/default/sa/default","sourceWorkload":"istio-egressgateway","totalReceivedBytes":297,"totalSentBytes":0}
```

### CODE REVIEW

**Comment by kyessenov** [comment]
we may need to bump the proxy to pick up https://github.com/istio/proxy/pull/1909

**Comment by vadimeisenbergibm** [comment]
@kyessenov Would it be OK to merge this one without https://github.com/istio/proxy/pull/1924? Now this one passes the tests, so https://github.com/istio/proxy/pull/1924 could be merged later to 1.1 or 1.0.2. If yes, could you please approve this PR?

**Comment by vadimeisenbergibm** [comment]
@kyessenov 
https://github.com/istio/proxy/pull/1924 has been merged, I have updated this PR. Waiting for https://storage.googleapis.com/istio-build/proxy/envoy-debug-cc83ed8fe87d854f6a3f14a06d874879a78076d1.tar.gz to be uploaded.

**Comment by kyessenov** [comment]
/retest
/lgtm
/approve

Thanks for doing this @vadimeisenbergibm . Changes look good to me.

**Comment by vadimeisenbergibm** [comment]
Thanks @kyessenov, sorry I missed additional changes, hope the tests will pass now.

**Comment by vadimeisenbergibm** [comment]
@costinm @rkpagadala Could you please merge  this one? It is a PR that depends on  
https://github.com/istio/proxy/pull/1924. The PR is a minor one - adds a Mixer attribute to two log entries, updates istio/proxy according to https://github.com/istio/proxy/pull/1924 and fixes the tests accordingly. It is a customer issue, I would like to have it in 1.0.1.

**Comment by vadimeisenbergibm** [comment]
Thanks, @costinm ! This is SNI reporting to Mixer, BTW.

**Pull request merged**
