### PR TITLE
Istio demo for Kubernetes deployment

### PR DESCRIPTION
**Pull request by andraxylia**
This change is [Reviewable](https://reviewable.io/reviews/istio/istio/26)

### CODE REVIEW

**Comment by mandarjog** [comment]
@andraxylia Can we add grafana pod to this as well? We are already collecting prometheus metrics that are compatible with our grafana build. @douglas-reid are there any issues with using our grafana image with your latest dashboard? separate PR is ok.

**Comment by douglas-reid** [comment]
we should probably update our currently published grafana image (grab the latest ENV settings), but otherwise, there should be no issues with using it.

**Comment by andraxylia** [comment]
I will add prometheus, grafana and service graph.

**Comment by andraxylia** [comment]
Who updates the grafana image, can please also move the "demo" tag? Thanks!

**Pull request merged**
