### PR TITLE
Allow user to override manifest entries with dotted keys

### LINKED ISSUE #19196: istioctl --set doesn't support escaping strings
Background: https://github.com/istio/istio/pull/17334

> I can't for the life of me figure out the syntax for passing in values to the sidecarInjectorWebhook.injectedAnnotations parameter, to set the apparmor annotation slightly_smiling_faceMy issue is that the "key" part contains dot-notation so it attempts to split it up no matter how I try to encapsulate it
> 
> Using Helm I think the proper way is to encapsulate it in quotes and escape dots
> ```
> istioctl manifest generate \
>     --set cni.enabled=true \
>     --set values.sidecarInjectorWebhook.injectedAnnotations."container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy"=runtime/default \
>     --output ./generated
> ```
> However this results in a mess in the actual manifest
> ```
> injectedAnnotations:
>   "container\": "map[apparmor\:map[security\:map[beta\:map[kubernetes\:map[io/istio-proxy:runtime/default]]]]]"
> Doesn't matter if I try to escape the dots or not
> ```
> Thanks!

> 
> adding complex stuff like this is really painful with helm --set and may not even be possible with istioctl.. I am not sure. What I would recommend is just to use a file. This will work:
> ```
> ik manifest generate -f <(echo 'apiVersion: install.istio.io/v1alpha2
> kind: IstioControlPlane
> spec:
>   values:
>     sidecarInjectorWebhook:
>       injectedAnnotations:
>         container.apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default')
> ```

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/19196

The syntax ***from bash*** is `istioctl manifest generate --set "values.sidecarInjectorWebhook.injectedAnnotations.container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy=runtime/default"`

The quotes are necessary because Bash will eat the `\` without them.

Although the generated output is seems correct I noticed that setting the injectedAnnotations this way causes `proto: tag has too few fields: "-"` to be written to stdout.  I believe this is not a new bug, but another example of https://github.com/kubernetes/kubernetes/issues/86739

### CODE REVIEW

**Review by richardwxn — COMMENTED** [review]
Can you also add this example to README?

**Comment by esnible** [comment]
@richardwxn Which README?

I will also add an example of `\.` to the examples in _operator/cmd/mesh/manifest-apply.go_ and friends so that the CLI help text shows it.

**Comment by richardwxn** [comment]
@esnible thx, I think that would be great

**Review by ostromart — APPROVED** [review]

**Pull request merged**
