### PR TITLE
Switch back to scratch for Galley

### PR DESCRIPTION
**Pull request by clyang82**
it was changed in this PR - #11065
I think we should switch back right now.

### CODE REVIEW

**Comment by sdake** [comment]
@clyang82 I think the general decision was to base every container from base_debug - and then permit people to roll their own base_debug with distro of their choice for compliance purposes.  SInce base_debug is in every image, the cost of the docker cache storage doesn't increase by simply adding yet another image with the same debug.

If you did want to proceed down this path, I can't help but wonder why we would use scratch when the distroless containers are much better structured for go binaries (including all of the stuff generally needed for a go binary).

Cheers
-steve

**Comment by clyang82** [comment]
@sdake Hi Steve, Thanks for your explanation. I considered the galley is stable so that we should switch back to `scratch`. if we go with `base_debug` for every image,  I am OK with that. Thanks.

**Comment by ayj** [comment]
Are Pilot, Mixer, etc.  using debug base?

**Comment by clyang82** [comment]
> Are Pilot, Mixer, etc. using debug base?

@ayj Pilot is using debug base while Mixer/Citadel are not using debug base.

**Pull request closed without merging**
