### PR TITLE
Merge release-1.1 to master 

### PR DESCRIPTION
**Pull request by rshriram**

### CODE REVIEW

**Comment by hklai** [comment]
/hold
Will do a manual commit merge after all tests have passed.

**Comment by venilnoronha** [comment]
I suggest that we wait until istio/proxy#2031 is merged and both `master` and `release-1.1` are in sync on `istio/proxy`. Once that's done, we can update the `PROXY_SHA` on `release-1.1` on this repo and then include that in this merge PR.

**Pull request merged**
