### PR TITLE
Update istio based on latest from auth, pilot and mixer

### PR DESCRIPTION
**Pull request by sebastienvas**
Using the sha from the repos that passed their own postsubmit from https://prow.istio.io/?type=postsubmit
Updated the yaml files with install/updateVersion.sh

```release-note
NONE
```

### CODE REVIEW

**Comment by sebastienvas** [comment]
cc @rvkubiak. Updating manually istio to the last version of repos.

**Comment by sebastienvas** [comment]
@kyessenov I am assuming that our kube inject templates are not compatible with 1.6 clusters anymore.

**Comment by ldemailly** [comment]
can you put in the description how you got the SHAs ? (running updateVersion or some other script ? manually ? if manually how to automate?)

(also doesn't seem like it works)

**Comment by sebastienvas** [comment]
I need to do start a release at 1pm. The automation of this is coming, but until then this is a manual step.

**Comment by ldemailly** [comment]
understood but how did you get the sha? looking at some build log ? latest in gcr ?

**Comment by sebastienvas** [comment]
I updated the PR description. It is all in there.

**Pull request merged**
