### PR TITLE
Tidying up the root directory.

### PR DESCRIPTION
**Pull request by geeknoid**
Removing a couple dead things and moving envsetup.sh to the proper place.

Costin: envsetup.sh is not documented anywhere. If we expect people to use it, we should mention it in the dev guide.

### CODE REVIEW

**Comment by ldemailly** [comment]
you can not remove nor move dowload istio as it’s used by the git.io immutable url

**Comment by geeknoid** [comment]
OK, I removed downloadIstio.sh from the commit.

So how is this file used? The fact that it points to Istio 0.2.12 tells me this is not that useful of a thing...

**Comment by ldemailly** [comment]
> So how is this file used? The fact that it points to Istio 0.2.12 tells me this is not that useful of a thing...

it's used in our installation steps for stable releases for instance
https://archive.istio.io/v0.1/docs/tasks/installing-istio#installation-steps
```
curl -L https://git.io/getIstio | sh -
```

and sadly 0.2.12 is the 'best' stable release so far, for instance it's the last one for which the vm mesh expansion just works out of the box. it also lags by design - it would probably be pointing to our "quarterly" supported releases and not each monthly - for which again 0.2.12 is the one for now (though you could argue 0.1.6 should be the one given the basic 404/503 regression in 0.2-0.5..)

after 0.5.0 bakes for a while, or maybe 0.6.2, we can bump it up

**Comment by ldemailly** [comment]
also:
https://www.google.com/search?q=https%3A%2F%2Fgit.io%2FgetIstio
(ie a bunch of blogs etc reference that script)

**Pull request merged**
