### PR TITLE
[Galley] configure logging at process startup

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
The logging should be configured at process start up.

fixes: #9265

ref: https://github.com/istio/istio/pull/9298#issuecomment-429683394

### CODE REVIEW

**Comment by ozevren** [comment]
Given that there was a previous fix, this PR is pure refactoring right?

If so, can we make it so that we have a single "server" package that can start multiple independent subsystems?

Having setup code hidden in cmd package is not healthy. We have the server package for this, which captures the entry-point/start/stop operations. We should expand it, put validation startup here and wire up logging options as the first thing.

**Comment by hzxuzhonghu** [comment]
@ozevren No, this is also a bug fix. And  the `put validation startup here and wire up logging options` seems not feasible. Because it may not run server when server node is not enabled.

**Comment by ozevren** [comment]
I am not sure which bug this is fixing? #9298 seems to already have fixed a bug in this area.

There should be one package that encompasses starting of all subsystems. It should be responsible for starting the rest of the subsystems as needed. Log configuration should be done there as well. Moving such logic into the cmd folder makes things meatier in those packages, and makes the overall thing harder to follow and reason about.

My previous suggestion was to use the server package for this purpose (and perhaps move the MCP server related code to another package). This aligns the code structure better with other components such as Mixer. Alternatively, we can keep the server package just for the MCP service, but create another package (i.e. bootstrap perhaps?) to encapsulate sub-system logic. That package needs to be able to start/stop things in a tractable way, similar to how the current service package works.

**Comment by hzxuzhonghu** [comment]
>I am not sure which bug this is fixing?

There is potential data race when print log and Configure concurrently.

**Pull request closed without merging**
