### PR TITLE
feat(gateways): don't set spec.replicas unless user supplies a real number

### PR DESCRIPTION
**Pull request by diranged**
**Please provide a description of this PR:**

Many users will need to manage their own `HorizontalPodAutoscaler` configurations for the Gateways to control scale-up and scale-down behaviors. To do this, users have to set `.Values.autoscaling.enabled: false`.

In the current chart setting `.Values.autoscaling.enabled: false` implicitly means setting `spec.replicas: 1` in the Deployment. For most users though who use something like ArgoCD to do deployments, this causes conflicts because their `HorizontalPodAutoscaler` will make changes to the `.spec.replicas` setting ... causing ArgoCD to report a delta between the desired and actual configs.

Given that the default behavior in Kubernetes Deplouyments is that `spec.replicas` defaults to `1` if not supplied ... it seems reasonable to simply not set this default at all unless the user actually specifies a hard-coded `.Values.replicaCount` setting.

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Review by hanxiaop — APPROVED** [review]
Seems reasonable to me

**Comment by zirain** [comment]
@diranged can you add release-notes?

**Comment by diranged** [comment]
@zirain Thanks, I just updated the PR with a changelog (https://github.com/istio/istio/pull/46121/files#diff-0cd703a3e390607f965c77bb4ddd798d6220d6642079410ca6ec56009ac693c6

**Pull request merged**
