### PR TITLE
[release-1.9] Backport destination rule does not trigger LDS 1.9

### PR DESCRIPTION
**Pull request by EItanya**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by linsun** [comment]
@stevenctl also need your help to make google cla bot happy here.

**Comment by linsun** [comment]
cc @jacob-delgado would love to get this cherrypick PR in 1.9 once test passes.

**Review by jacob-delgado — APPROVED** [review]

**Comment by EItanya** [comment]
@googlebot I consent.

**Comment by stevenctl** [comment]
@EItanya thanks for backporting!

**Pull request merged**
