### PR TITLE
support install gateway helm chart as daemonset

### LINKED ISSUE #37610: Helm charts: gateways: provide a daemonset chart
**Describe the feature request**
Could you provide a daemonset type for gateways ?
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml
or:
https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml

**Describe alternatives you've considered**
We're migrating from istioctl installation back to helm, where we could "easily" set the ingress to run as daemonset with:
```
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      namespace: istio-system
      k8s:
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
              - path: spec.strategy
```
But there's no "daemonset" yet in helm

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

fixed: https://github.com/istio/istio/issues/37610

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]

**Comment by jgournet** [comment]
Thank you for this PR
=> Any chance this PR could be merged ?
it would be really appreciated ;)

**Comment by zirain** [comment]
kindly ping @Monkeyanator @istio/wg-environments-maintainers

**Review by irisdingbj — APPROVED** [review]
Thanks for this fix!

**Comment by yann-soubeyrand** [comment]
I may be wrong, but I think HPA doesn’t work with DaemonSet. If kind is DaemonSet, the HPA shouldn’t be deployed.

**Pull request merged**
