### PR TITLE
Skip/reject k8s jwt authentication if SDS is disabled (#15445)

### PR DESCRIPTION
**Pull request by pitlv2109**
Cherry-pick from #15445 for `release-1.1`.

https://github.com/istio/istio/issues/15269

### CODE REVIEW

**Comment by pitlv2109** [comment]
codecov failed because code coverage for `kube_jwt.go` dropped from 100% to ~94-95%. The file is really small and what I added is very trivial. `master` and `1.2` didn't have this problem, so I'm not sure why the codecov req for `1.1` is different? Can we merge this in manually? If not, I can add some code to master first then cherry pick with one altogether. 
@myidpt @howardjohn @fpesce

**Comment by myidpt** [comment]
Please try to add a unit test to https://github.com/istio/istio/blob/master/security/pkg/server/ca/authenticate/kube_jwt_test.go#L103
Let's keep the code coverage up.

**Comment by fpesce** [comment]
Also @duderino is the 1.1 Release Manager.

**Comment by pitlv2109** [comment]
Added a test in master here https://github.com/istio/istio/pull/15599

**Pull request merged**
