### PR TITLE
Added externalTrafficPolicy to istio-ingressgateway, to keep X-Forwar…

### PR DESCRIPTION
**Pull request by Modulus**
Added externalTrafficPolicy to istio-ingressgateway, to keep X-Forwarded-For header. This is needed for a client, connected to issue 7328.

Usage of the parameter is in install/kubernertes/helm/chats/gateways/service.yaml

### CODE REVIEW

**Comment by Modulus** [comment]
I signed it!

**Comment by Modulus** [comment]
The failing tests are not connected to the change as far as I can see.

**Comment by rshriram** [comment]
@PiotrSikora also had a similar PR.. we dont need a new values.yaml for this.. we could simply have this in the main values.yaml and probably set it to something else?

**Comment by Modulus** [comment]
I added the externallTrafficPolicy to the values file, and left it commented out with what this setting means. I also removed the extra values file that was added in the previous commit.

**Pull request merged**
