### PR TITLE
Adding galley test for sidecar config validation

### PR DESCRIPTION
**Pull request by mbanikazemi**
Test cases related to PR #12233

### CODE REVIEW

**Comment by ozevren** [comment]
@duderino Can you merge this in? It is a test only PR.

**Comment by ozevren** [comment]
Hey @mbanikazemi, it looks like this won't make it into 1.1. Could you check this in to master?

Thanks

**Comment by mbanikazemi** [comment]
I think some of the changes to release-1.1 have not found their way to master yet. Hence the test failing.

**Comment by ozevren** [comment]
I am cherry-picking your change from release-1.1 to master: 
https://github.com/istio/istio/pull/12643/files
This should help.

**Comment by ozevren** [comment]
Your PR against 1.1 is in master now. If you merge/rebase with master, then the tests should start passing.

**Pull request merged**
