### PR TITLE
ca: fix TestCreateSelfSignedIstioCAWithSecret caused by expired cert.

### PR DESCRIPTION
**Pull request by yangminzhu**
The old cert expired at `Sep 20 23:18:40 2018 GMT`, the new cert is generated with the following command, this should fix the immediate test failure.

```
$ cat req.conf 
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
O = k8s.cluster.local
[v3_req]
keyUsage = critical,keyCertSign
basicConstraints = critical,CA:true
$ openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout key.pem -out cert.crt -config req.conf -extensions 'v3_req' 
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Can you regenerate with a longer expiration time, 10 years is not long enough.

**Comment by hzxuzhonghu** [comment]
/lgtm
since this is a blocker, any one can approve?

**Comment by mandarjog** [comment]
Can we have a better solution that this going forward?

**Comment by mabushey** [comment]
I'm running into this problem. Do I regenerate the cert on each master node?

**Pull request merged**
