### PR TITLE
Rolling back #5071

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by costinm** [comment]
Let me confirm with the people who had conflicts, if they updated their PRs we'll break it more.

I don't mind the cleanup - the problem is 0.8 and priorities.

**Comment by sbezverk** [comment]
@costinm +1 to go ahead with revert.

**Comment by costinm** [comment]
/lgtm
/approve

Let's re-do this after 0.8 is out - very likely the cluster initialization will be refactored anyways.

Thanks for the quick revert and sorry for the churn !

**Comment by rshriram** [comment]
some explanation please..

**Comment by sdake** [comment]
@rshriram summary is there are no moves/renames/deletion of software during rc0.  The original PR that this is a revert of touched a lot of code that is being refactored in other ways.  The goal of this work is to enable automatic addition/removal of cluster secrets here: https://github.com/istio/istio/pull/5017

**Comment by costinm** [comment]
Seems to no longer be needed.

**Pull request closed without merging**
