### PR TITLE
Bookinfo changes for 0.8

### PR DESCRIPTION
**Pull request by zachgersh**
modified bookinfo docker images. Wanted to run samples against 0.8

### CODE REVIEW

**Comment by zachgersh** [comment]
@rshriram These test failures feel like they are unrelated to the docker image changes made. I see other PRs with failures to connect to the database (that was my primary concern). Should I dig into this any more?

**Comment by rshriram** [comment]
Let’s wait for those tests to be fixed. There is no baseline for the newer version of bookinfo images

**Comment by mandarjog** [comment]
@zachgersh @rshriram  `e2e-bookInfo`, Do we want to get this PR into 0.8?

**Comment by zachgersh** [comment]
@mandarjog - I'd like to get this in if we can but I'd need some help determining if these tests are failing for the right reasons.

**Comment by zachgersh** [comment]
@sdake - I don't quite understand (apologies). It seems like bookinfo still failed on that branch. I've also seen a lot of chatter in the istio slack about bookinfo. I'd be glad to fix the docker images but I don't suspect they are the problem 💃

**Comment by rshriram** [comment]
This time it fails for sure? TestDBRoutingMySql?

**Comment by ijsnellf** [comment]
@GregHanson PTAL since this changes some files in Consul.

**Comment by zachgersh** [comment]
This is incorporated into #6842

**Pull request closed without merging**
