### PR TITLE
Drop support for 1.9 proxies

### PR DESCRIPTION
**Pull request by howardjohn**
We do not support Istiod 1.11 and 1.9 proxy, so clean this up a bit

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
We donot support every release version in production, we support every other version currently. Like 1.9->1.11, with this it is hard to do graceful upgrade.

**Comment by howardjohn** [comment]
You have Istiod 1.11 connecting to 1.9 proxies? Or 1.9 proxies connecting
to 1.11 proxies?

I don't know how the first one would ever work. We break it in almost every
version, such as the xds v3 migration?

**Comment by hzxuzhonghu** [comment]
We want this: Istiod 1.11 connecting to 1.9 proxies
We did not do graceful upgrade before, as community does not support it.  If we keeps the compatibility, surely users can do upgrade according to their business.  For example, users are reluctant to upgrade their DB unless they must do.

**Comment by howardjohn** [comment]
I would recommend you follow this approach: https://istio.io/latest/blog/2021/revision-tags/

Then there is no cross-version traffic but you can still skip versions. Otherwise it's not safe nor is it something we have ever even attempted to support

**Comment by hzxuzhonghu** [comment]
IC, looks super good feature. Thanks！

**Review by hzxuzhonghu — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Comment by lei-tang** [comment]
Quoted from the PR description "We do not support Istiod 1.11 and 1.9 proxy", which version(s) of proxies are supported by istiod 1.11?

**Comment by howardjohn** [comment]
1.11 and 1.10

**Pull request merged**
