### PR TITLE
Update Jaeger to version 1.8

### PR DESCRIPTION
**Pull request by aljesusg**
Update to Jaeger 1.8 

cc @objectiser

### CODE REVIEW

**Comment by douglas-reid** [comment]
Nothing here should impact codecov. We should just merge.

**Comment by sdake** [comment]
@douglas-reid sadly the dashboard job is failing as well, which is required.

Also master is frozen.  I am not sure what version of jaeger is in release-1.1 of istio, but if its newer than this version, can the author close this PR?

Cheers
-steve

**Comment by sdake** [comment]
Can you close this PR against master?  IThe plan is to forward port all 1.1 PRs to master once we ship 1.1.  If the forward port doesn't happen, I'd ask you to submit again.

Cheerfs
-steve

**Comment by aljesusg** [comment]
Closed. Thanks

**Pull request closed without merging**
