### PR TITLE
Fix Inconsistent Capitalization in the Command Reference

### LINKED ISSUE #6359: Inconsistent Capitalization in the Command Reference
Looking at: https://preliminary.istio.io/docs/reference/commands/istioctl/
the capitalization of sentences is very inconsistent. Some sentences start with a capital letter, but there are many that do not. 

Examples: 
`istioctl experimental add-to-mesh external-service create a ServiceEntry and\ a Service without selector for the specified external service in Istio service mesh. The typical usage scenario is Mesh Expansion on VMs. THIS COMMAND IS STILL UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.`

`istioctl experimental add-to-mesh service restarts pods with the Istio sidecar. Use 'add-to-mesh' to test deployments for compatibility with Istio. If your service does not function after using 'add-to-mesh' you must re-deploy it and troubleshoot it for Istio compatibility. See https://istio.io/docs/setup/kubernetes/additional-setup/requirements/ THIS COMMAND IS STILL UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.`

`(convert-ingress has graduated. Use `istioctl convert-ingress`)`

`webhook command to manage webhook configurations`

There are quite a few other instances as well.

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio.io/issues/6359

### CODE REVIEW

**Review by esnible — COMMENTED** [review]
You might want to fix the inconsistent sentence endings, with and without `.`, as part of this PR.

**Comment by shamsher31** [comment]
> You might want to fix the inconsistent sentence endings, with and without ., as part of this PR.

You mean all the sentences should end with `.` ?

**Comment by esnible** [comment]
> You mean all the sentences should end with `.` ?

I don't know.  Long ago someone requested consistent endings.  I couldn't decide which looked nicer.  I compared with `kubectl` which is inconsistent!

**Comment by brian-avery** [comment]
The capitalization looks good to me. My thought it consistent punctuation (either present or not) is probably better for more polished docs as well, but I'll leave that up to Frank.

**Review by esnible — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Pull request merged**
