### PR TITLE
Allow --concurrency to be explicitly 0

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/30618

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Not sure I understand the use case to set --concurrency=0. It does the same as ` --concurrency=1`, whereas unset does something distinct (all available threads)

**Comment by howardjohn** [comment]
```
2021-02-05T19:42:42.002606Z     info    Apply proxy config from env {"concurrency":0}

2021-02-05T19:42:42.003239Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
```

I think the problem is the `0` setting in mesh configmap doesn't propogate

**Comment by esnible** [comment]
> I think the problem is the `0` setting in mesh configmap doesn't propogate

See https://github.com/istio/istio/issues/30618#issuecomment-774906027 .  User set concurrency to 0, was surprised that currency became 2, expected it to become 1!

I would be happy to close this PR unmerged.  Yet it makes sense that if the meshConfig specifies concurrency=0, we should pass it along to Envoy.

**Comment by howardjohn** [comment]
I don't think this actually solves that issue though. Here is an example of me setting `--concurrency 0`:
```
$ proxy-local --concurrency=0 | h concurrency
2021-02-08T16:18:28.658655Z     info    FLAG: --concurrency="0"
2021-02-08T16:18:28.658669Z     info    FLAG: --domain=""
2021-02-08T16:18:28.658673Z     info    FLAG: --help="false"
2021-02-08T16:18:28.658675Z     info    FLAG: --log_as_json="false"
2021-02-08T16:18:28.658677Z     info    FLAG: --log_caller=""
2021-02-08T16:18:28.658678Z     info    FLAG: --log_output_level="default:info"
2021-02-08T16:18:28.658680Z     info    FLAG: --log_rotate=""
2021-02-08T16:18:28.658682Z     info    FLAG: --log_rotate_max_age="30"
2021-02-08T16:18:28.658684Z     info    FLAG: --log_rotate_max_backups="1000"
2021-02-08T16:18:28.658686Z     info    FLAG: --log_rotate_max_size="104857600"
2021-02-08T16:18:28.658689Z     info    FLAG: --log_stacktrace_level="default:none"
2021-02-08T16:18:28.658693Z     info    FLAG: --log_target="[stdout]"
2021-02-08T16:18:28.658695Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2021-02-08T16:18:28.658697Z     info    FLAG: --outlierLogPath=""
2021-02-08T16:18:28.658699Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2021-02-08T16:18:28.658701Z     info    FLAG: --proxyLogLevel="warning"
2021-02-08T16:18:28.658703Z     info    FLAG: --serviceCluster="istio-proxy"
2021-02-08T16:18:28.658706Z     info    FLAG: --stsPort="0"
2021-02-08T16:18:28.658707Z     info    FLAG: --templateFile=""
2021-02-08T16:18:28.658710Z     info    FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2021-02-08T16:18:28.658712Z     info    Version unknown-unknown-unknown
2021-02-08T16:18:28.659080Z     info    Apply proxy config from env binaryPath: /home/howardjohn/go/src/istio.io/istio/out/linux_amd64/envoy
configPath: /home/howardjohn/kube/local/proxy
proxyBootstrapTemplatePath: /home/howardjohn/go/src/istio.io/istio/tools/packaging/common/envoy_bootstrap.json
discoveryAddress: localhost:15012
statusPort: 15020
terminationDrainDuration: 0s
tracing: {}
2021-02-08T16:18:28.659603Z     info    Effective config: binaryPath: /home/howardjohn/go/src/istio.io/istio/out/linux_amd64/envoy
concurrency: 2
configPath: /home/howardjohn/kube/local/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: localhost:15012
drainDuration: 45s
parentShutdownDuration: 60s
proxyAdminPort: 15000
proxyBootstrapTemplatePath: /home/howardjohn/go/src/istio.io/istio/tools/packaging/common/envoy_bootstrap.json
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 0s
tracing: {}

2021-02-08T16:18:28.659617Z     info    Proxy role      ips=[10.0.0.14 2601:646:8a01:dc30::da24 2601:646:8a01:dc30:d870:60d6:b123:a0e5 2601:646:8a01:dc30:9de3:71d9:fd87:dc6d fe80::79ae:8863:632:79f0 172.17.0.1 fc00:f853:ccd:e793::1 fe80::42:5dff:fedc:3666 fe80::1 192.168.9.1 fe80::42:f8ff:fe29:82b8 fe80::4023:feff:fe56:588 fe80::14de:f7ff:fe0f:cb1 fe80::6c7b:22ff:fe39:9e6d] type=sidecar id=. domain=.svc.cluster.local
2021-02-08T16:18:28.659621Z     info    JWT policy is third-party-jwt
2021-02-08T16:18:28.659626Z     info    Pilot SAN: [istiod.istio-system.svc]
2021-02-08T16:18:28.659629Z     info    CA Endpoint localhost:15012, provider Citadel
2021-02-08T16:18:28.659650Z     info    Using CA localhost:15012 cert with certs: var/run/secrets/istio/root-cert.pem
2021-02-08T16:18:28.659712Z     info    citadelclient   Citadel client using custom root cert: localhost:15012
2021-02-08T16:18:28.683306Z     info    ads     All caches have been synced up in 25.192775ms, marking server ready
2021-02-08T16:18:28.683563Z     info    sds     SDS server for workload certificates started, listening on "./etc/istio/proxy/SDS"
2021-02-08T16:18:28.683576Z     info    xdsproxy        Initializing with upstream address "localhost:15012" and cluster ""
2021-02-08T16:18:28.683715Z     info    Starting proxy agent
2021-02-08T16:18:28.683781Z     info    Received new config, creating new Envoy epoch 0
2021-02-08T16:18:28.683908Z     info    Opening status port 15020
2021-02-08T16:18:28.683917Z     info    Epoch 0 starting
2021-02-08T16:18:28.683916Z     info    sds     Start SDS grpc server
2021-02-08T16:18:28.686900Z     info    Envoy command: [-c /home/howardjohn/kube/local/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-proxy --service-node sidecar~10.0.0.14~.~.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3 --log-format %Y-%m-%dT%T.%fZ     %l      envoy %n     %v -l warning --component-log-level misc:error --concurrency 2]
```

Also, we do not want to pass `--concurrency=0` to envoy - there is no point, user should set it to `1`.

**Comment by howardjohn** [comment]
I opened https://github.com/istio/istio/pull/30750 to do something similar but different. PTAL and let me know what you think

**Pull request closed without merging**
