### PR TITLE
Replace "MaxMsgSize" with "MaxRecvMsgSize" in grpc server

### PR DESCRIPTION
**Pull request by lichuqiang**
As "MaxMsgSize" is now deprecated, use MaxRecvMsgSize instead in grpc server,

### CODE REVIEW

**Comment by lichuqiang** [comment]
@ozevren Anything else I need to do to get the PR merged?
What does it mean by "At least 1 approving review is required to merge this pull request"?
Seems the lgtm and approve labels are already there.

**Comment by ozevren** [comment]
The main message to look for is the tide check. That is the merge robot that will apply you patch.
There is a failing required test.

**Pull request merged**
