### PR TITLE
revert https://github.com/istio/istio/pull/43560

### PR DESCRIPTION
**Pull request by kyessenov**
cc @ramaraochavali

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@kyessenov Thanks for identifying this problem. Just put a hold to fix the issue instead of reverting. https://github.com/istio/istio/pull/44473 - fix. PTAL

**Comment by kyessenov** [comment]
Hey Rama,
Can we proceed with the revert so that we can properly add tests to the PR you are adding? It looks like it should be easy to revert with no conflicts. The bug is blocking our build pipeline as tests crash.

**Comment by ramaraochavali** [comment]
Sure. Please free to remove the DNM

**Pull request merged**
