### PR TITLE
refresh the look of Bookinfo sample app

### PR DESCRIPTION
**Pull request by peterj**
Refreshing the look of Bookinfo sample application. The functionality of the sample app is the same, I replaced Bootstrap with Tailwind, refreshed the design a bit, added the Izzy and Istio logo and links to istio.io in a couple of places.

Screenshots of the new look. If people agree on this change, I'll go through the rest of the docs to update any outdated screenshots (there are probably some). 

errors
index
main
signedin
signin

### CODE REVIEW

**Comment by peterj** [comment]
Not sure if this change would require release notes (or not). Potentially.

**Comment by craigbox** [comment]
Release notes: yes please. "Refreshed look and feel of Bookinfo".

My gut reaction to hearing about logos: other projects use this (largely for testing against us though I think!) and maybe they wouldn't if it was too overtly Istio branded?

(I think what i see in the screenshots is fine.)

**Comment by howardjohn** [comment]
End of an era

LGTM generally but some of our tests/docs grep against the html (to detect which version of reviews generally I think) so we will want to keep compat there?

**Comment by peterj** [comment]
@craigbox Istio logo is only on the sign-in dialog and since this is Istio's sample app, it should be fine (I can also easily remove the logo from there).

@howardjohn good point! I'll check the docs and make sure the HTML is similar so those instructions still work fine.

**Comment by peterj** [comment]
There was a change to the requirements.txt and dockerfile in the same exact folder like 10 min ago .. :|

**Comment by peterj** [comment]
I think I messed up something here, because it's seems like it's reverting the changed that came in from https://github.com/istio/istio/commit/9a9671d05670b78d08248576510c599482490922

**Comment by peterj** [comment]
should be good now 🤞🏼

**Comment by kfaseela** [comment]
This looks cool 🙂

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
I'm not sure of the pipeline to getting new containers built, and the impact of doing so; I don't think they are in any way versioned to Istio releases.  When they are built, they'll apply to examples in all released versions of Istio.  Which is good, but means we will want to update screenshots in at least `master` and `release-1.22`.

**Comment by ericvn** [comment]
> I'm not sure of the pipeline to getting new containers built, and the impact of doing so; I don't think they are in any way versioned to Istio releases. When they are built, they'll apply to examples in all released versions of Istio. Which is good, but means we will want to update screenshots in at least `master` and `release-1.22`.

I think @howardjohn and @frankbu are two of the people that can run a build of the new images and then update the yamls to call out the new images (instructions in the README). Then we can update the docs in `master` and if we want to cherry-pick the yaml changes to 1.22, we can update there as well.

**Comment by peterj** [comment]
@howardjohn let me know once you've built the images and I can go and update the screenshots in the docs after that.

**Comment by howardjohn** [comment]
Having some issues with my machine, hopefully will be soon

**Pull request merged**
