### PR TITLE
Fix service address misuse

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Fix: #34807 get the service address for the cluster

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by nmittler** [comment]
@hzxuzhonghu I don't think this quite fixes the underlying cause of the issue. The field is named poorly or simply shouldn't be publicly accessible. This PR fixes the call sites for now, but new ones might very well crop up because it's not immediately clear what the field represents or how it should be used.

**Comment by howardjohn** [comment]
I agree we should make it private or rename it

**Comment by hzxuzhonghu** [comment]
I agree, will try to make it private. I was seeing some tests use this field directly.

**Comment by hzxuzhonghu** [comment]
Make it private seems not viable.

**Review by adiprerepa — APPROVED** [review]

**Pull request merged**
