### PR TITLE
Allow json maps as strings in istioctl

### LINKED ISSUE #24318: meshConfig.accessLogFormat doesn't work
**Bug description**

setting meshConfig.accessLogFormat has no effect. had to fallback to global.proxy.accessLogFormat

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Setting meshConfig.accessLogFormat should change the log format

**Steps to reproduce the bug**

This configuration doesn't change log format:
```
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: "/dev/stdout"
    accessLogFormat: |
      {
        "log_type": "access_log",
        "start_time": "%START_TIME%",
        "route_name": "%ROUTE_NAME%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "duration": "%DURATION%",
        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "user_agent": "%REQ(USER-AGENT)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "authority": "%REQ(:AUTHORITY)%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
      }
```
This works:
```
  meshConfig:
    enablePrometheusMerge: false
    accessLogEncoding: JSON
    accessLogFile: "/dev/stdout"

  values:
    global:
      proxy:
        accessLogFormat: |
          {
            "log_type": "access_log",
            "start_time": "%START_TIME%",
            "route_name": "%ROUTE_NAME%",
            "method": "%REQ(:METHOD)%",
            "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
            "protocol": "%PROTOCOL%",
            "response_code": "%RESPONSE_CODE%",
            "response_flags": "%RESPONSE_FLAGS%",
            "bytes_received": "%BYTES_RECEIVED%",
            "bytes_sent": "%BYTES_SENT%",
            "duration": "%DURATION%",
            "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
            "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
            "user_agent": "%REQ(USER-AGENT)%",
            "request_id": "%REQ(X-REQUEST-ID)%",
            "authority": "%REQ(:AUTHORITY)%",
            "upstream_host": "%UPSTREAM_HOST%",
            "upstream_cluster": "%UPSTREAM_CLUSTER%",
            "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
            "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
            "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
            "requested_server_name": "%REQUESTED_SERVER_NAME%",
            "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
            "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
          }
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (9 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Not using helm

**How was Istio installed?**
I've tried this on three different clusters.
Two were installed with istioctl and the third with istio-operator controller

**Environment where bug was observed (cloud vendor, OS, etc)**
aws kops 1.16.2 - ubuntu 20.04

### PR DESCRIPTION
**Pull request by howardjohn**
https://github.com/istio/istio/pull/23596 added some logic to allow
strings as objects. This caused a regression in setting fields that are
expected to be maps encoded as strings.

Fixes https://github.com/istio/istio/issues/24318

This *is* a breaking change as the case seen in
pilot_override_kubernetes now changes from taking a map as input instead
of string. However, I think this is better behavior anyways.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
@ostromart I am not sure how to fix the test failures.. I probably fixed one issue and created 2 new ones

**Review by howardjohn — COMMENTED** [review]
@ostromart I will need help with ModifyMapEntryMapValue. The current behavior seems wrong, but I may be missing something. I don't see how if we set the path `a.b` to be some struct, we get rid of the `b` field? When for AddMapEntryMapValue we have path a.new_key and it adds new_key. The behavior doesn't seem very consistent, but I may be having a hard time mapping the low level unit test to high level user config

**Review by ostromart — APPROVED** [review]

**Comment by jdomag** [comment]
@howardjohn 
Any progress on that? Is this fixed in any istio version higher than 1.6.5?

**Comment by howardjohn** [comment]
No, I could not get this working. Maybe @ostromart or @richardwxn could carry this forward

**Pull request closed without merging**
