### PR TITLE
[release-1.12] Fix mutatingwebhook analysis

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**Please provide a description of this PR:**
fixes: #36114

This is a manual change instead of clean cherry-pick because this is a fix in the galley code which got removed with the[ removal of legacy galley code in 1.13](https://github.com/istio/istio/commit/d0748d7c46c02e1fddf77d7a38f90cb3620e4358)

- Reconcile invokes [analyzeWebhooks](https://github.com/istio/istio/blob/1.12.6/operator/pkg/helmreconciler/reconciler.go#L168) 
- analyzeWebhooks creates an instance of source analyzer, `sa`, with config schema, resources read from[ `metadata.yaml`](https://github.com/istio/istio/blob/a0c7a3355331ef20354e3e1682dc13b7e6bcf4c1/pkg/config/schema/metadata.yaml#L276-L281). In this file, webhooks are not mentioned as `clusterScoped: true` and this is the cause of the issue. 
- [`sa.AddReaderKubeSource()`](https://github.com/istio/istio/blob/a0c7a3355331ef20354e3e1682dc13b7e6bcf4c1/operator/pkg/helmreconciler/reconciler.go#L591) then  tries to add config sources based on metadata file. In this call flow eventually from [here](https://github.com/istio/istio/blob/1.12.6/galley/pkg/config/source/kube/inmemory/kubesource.go#L306-L310), it ended up prefixing `istio-system` in the webhook name. IOW, in the analyzer's snapshot, webhook gets stored by key `istio-system/<webhook-name>`
-  analyzer also runs a k8s watcher. In the initial cache sync itself, this watcher inserts, along with other resources, webhook as well into the buffer queue. [But here `istio-system` is not added as the prefix.](https://github.com/istio/istio/blob/1.12.6/galley/pkg/config/source/kube/apiserver/watcher.go#L72) Eventually, analyzer's snapshot is having two entries for the same webhook, `webhook-name` and `istio-system/<webhook-name>`. Naturally, it then fails with `Webhook overlaps with others` 
**log from analyzer's [`Snapshotter.publish`]**(https://github.com/istio/istio/blob/1.12.6/galley/pkg/config/processing/snapshotter/snapshotter.go#L224):
```
2022-04-12T08:23:07.254608Z	debug	processing	InmemoryDistributor.Distribute: localAnalysis: [0] istio/mesh/v1alpha1/MeshConfig (@istio/mesh/v1alpha1/MeshConfig/1)
  ......
[10] k8s/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations (@k8s/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/8)
  [0] istio-system/istio-sidecar-injector-stable <-----  SEE THIS
  [1] istio-sidecar-injector-stable                      <---- AND THIS
  [2] onboarding-operator
  

```

### CODE REVIEW

**Comment by dgn** [comment]
hi @vikaschoudhary16, could you add a release note?

**Comment by dgn** [comment]
Also, I don't see how setting CRDs to clusterScoped will do anything? In your original comment you mention setting clusterScoped to `true` on MutatingWebhooks, not CRDs

**Comment by vikaschoudhary16** [comment]
> Also, I don't see how setting CRDs to clusterScoped will do anything? In your original comment you mention setting clusterScoped to `true` on MutatingWebhooks, not CRDs

my fatty fingers mistake, thanks for catching!! 
PTAL now!

**Review by dgn — APPROVED** [review]

**Pull request merged**
