### PR TITLE
operator init: make replicas configurable

### LINKED ISSUE #32214: Istio Operator Init repliaCount flag to run operator server in HA
**Describe the feature request**
Currently the istio operator init command only creates a deployment with a single replica. We would like to at least run the operator in a HA manner (N+1). Could a flag be added to template the replicaCount for the operator deployment?

**Describe alternatives you've considered**
Patch the deployment after init is ran.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/32214

You can use helm to configure replicaCount or override values using -f in operator int.
```
$ helm install istio-operator manifests/charts/istio-operator --set replicaCount=3
```

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
What is the use case for multiple replicas? AFAIK only one can run at a time and the others crashloop if they don't get the leader election client?

**Comment by shamsher31** [comment]
> What is the use case for multiple replicas?

Currently, only 1 replica is running and elected as leader. Running multiple replicas will be useful if the current leader fails for some reason.

> AFAIK only one can run at a time and the others crashloop if they don't get the leader election client?

I have tried running 3 replicas and one of them became leader and the other tries to acquire leader lock. The other two pods are in a `running` state instead of `crashloop`. I think if the main leader dies for some reason (pod gets deleted) the other two replicas will try to acquire the leader lock. Isn't that expected behavior?
 
```
$ k get pod -n istio-operator
NAME                              READY   STATUS    RESTARTS   AGE
istio-operator-775b889cc6-fsdq6   1/1     Running   0          2m13s
istio-operator-775b889cc6-rdfsg   1/1     Running   0          2m13s
istio-operator-775b889cc6-xq29v   1/1     Running   0          2m13s
```

The first pod acquires a leader lock
```
$ k logs istio-operator-775b889cc6-fsdq6 -n istio-operator
2021-04-19T06:44:35.581886Z     info    ControlZ available at 127.0.0.1:9876
2021-04-19T06:44:35.581993Z     info    leader election cm: istio-operator-lock
...
2021-04-19T06:44:35.487368Z     info    klog    attempting to acquire leader lease istio-operator/istio-operator-lock...
2021-04-19T06:44:35.494565Z     info    klog    successfully acquired lease istio-operator/istio-operator-lock
```

The other two pods were trying to acquire leader lock.
```
$ k logs istio-operator-775b889cc6-rdfsg -n istio-operator
2021-04-19T06:44:35.581886Z     info    ControlZ available at 127.0.0.1:9876
2021-04-19T06:44:35.581993Z     info    leader election cm: istio-operator-lock
...
2021-04-19T06:44:36.087561Z     info    klog    attempting to acquire leader lease istio-operator/istio-operator-lock...
```
```
$ k logs istio-operator-775b889cc6-xq29v -n istio-operator
2021-04-19T06:44:35.581886Z     info    ControlZ available at 127.0.0.1:9876
2021-04-19T06:44:35.581993Z     info    leader election cm: istio-operator-lock
...
2021-04-19T06:45:06.488129Z     info    klog    attempting to acquire leader lease istio-operator/istio-operator-lock...
```

**Comment by howardjohn** [comment]
How is that any better than one pod?

* Scenario 1: I have a multiple replicas. It crashes. 60s later (perhaps 30s, not sure the default), the leader election lock is lost, and one of the other pods becomes the leader. Total downtime: 60s.
* Scenario 2: I have one replica. It crashes. A new pod comes up ~10s later. 50s later, the leader election lock is lost, so my new pod becomes the leader. Total downtime: 60s.

**Comment by shamsher31** [comment]
When the leader crashes, considering the default _grace period_ for Pod is `30s`, as the other replicas are already up and running, even if the next leader lock is acquired in `10s` (30s + 10s = 40s), Not a big difference but it's still better than re-creating another replica and performing leader election again (60s).

**Comment by howardjohn** [comment]
I feel like it can only make a difference if the new pod comes up slower
than the leader timeout, which seems unlikely.

**Comment by nitinatgh** [comment]
Hi,

Can this be reopened please and have the replica count configurable? 
I have seen the reasons above for not doing so, but as stated there can be other scenarios where it can be beneficial e.g.:
- pod creation issues (if they had to get recreated from a failed node)
   -- CrashLoopBackOff issues i.e. failed to get docker image
   -- cluster resourcing issues
   -- etc...
And these could happen for various reasons.

Thanks

Nitin

**Pull request closed without merging**
