### PR TITLE
Use values-e2e.yaml for integration2 tests

### PR DESCRIPTION
**Pull request by howardjohn**
Should fix test.integration.kube, which was not using e2e test values file leading to failures like https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12257/istio-integ-k8s-tests/4617?log#log, where all pods are stuck pending.

https://github.com/istio/istio/issues/12267

### CODE REVIEW

**Comment by howardjohn** [comment]
Looks like this doesn't actually fix prow/istio-integ-k8s-tests.sh, but it does improve it. Before tests were failing due to all pods pending, now it fails for other reasons.

**Comment by ozevren** [comment]
Shouldn't this be a change to the default values file? Will passing multiple values file work in this instance?

**Comment by howardjohn** [comment]
> Shouldn't this be a change to the default values file? Will passing multiple values file work in this instance?

We could make a new values file for these tests which would effectively just be values-mcp + values-e2e, but passing multiple values files does work.

**Comment by incfly** [comment]
Thanks for the fix!

Agree with @ozevren  I feel inline values in a single file is easier to understand and follow. And there seems no other use cases requring more than one value file?

Off the topic, one of things I'm working on is to allow test specify per-test suite values overrides, https://github.com/istio/istio/pull/11531 I need this for health check prober rewrite. That might cover the needs?

wdty?

**Comment by howardjohn** [comment]
> Thanks for the fix!
> 
> Agree with @ozevren I feel inline values in a single file is easier to understand and follow. And there seems no other use cases requring more than one value file?
> 
> Off the topic, one of things I'm working on is to allow test specify per-test suite values overrides, #11531 I need this for health check prober rewrite. That might cover the needs?
> 
> wdty?


If we allow test suites to override values, we still need them to use the `values-e2e.yaml`. Every test must have these values applied or it will fail, as our E2E clusters are not large enough and pods get stuck pending. We could copy these values into the default file for these tests, and that would simplify things, but that won't work when we can provide helm value overrides. I don't think its a good idea to require every test to make sure they set the right resource requests - I doubt it will happen, and then we will get vague errors and another flaky test.

I don't think it is that weird/complex to have multiple value files applied. The values-e2e one is applied first, so if a test needs to change any values that will work (helm merges them, in order).

**Comment by ozevren** [comment]
I think we should follow suit on whatever the current e2e tests does. It looks like some of them use e2e values, in addition to another file. However, I think this needs to be very explicit, silently injecting e2e_values will be counter intuitive.

Also, I think the 1.1 branch bar is quite high at the moment. This PR would be much more valuable in master (or collab-test-framework, where I started an important refactoring of the framework).

**Comment by incfly** [comment]
I totally understand that we need values-e2e settings to be set for all tests. I'm not suggesting that we do that at each individual test level.

Maybe I miss something, but it's not obvious to me that why we need to support multiple values files.

Will anything break or not working if we merge "test-values/values-istio-mcp.yaml" and "test-values/values-e2e.yaml"  into single file and then we don't need to support multiple values files.

The harm about multiple configuration overlay is hard to reason about by human. You can't explain what settings will eventually be by looking at individual files. This is an example of some of our own Istio configuration, for example, Authentication Policy. @ozevren can comment on this more...

So the values config overlay if really needed, I hope it's specific and occasional, and avoid when possible.

**Comment by howardjohn** [comment]
I have no problem with merging "test-values/values-istio-mcp.yaml" and "test-values/values-e2e.yaml" into a new file that is the default values file for the integration test framework. I think with the state of the tests now, this will work 100% fine. The issue I am concerned about is when, with your change, tests override the values file, say to `test-values/values-istio-non-mcp.yaml`, but now they don't apply the `values-e2e.yaml` file, and there tests have resource issues. And if we add 10 new tests, we now have to add 10 new values files, which get out of sync, etc.

The other E2E tests don't have this issue, since they don't use Helm, and the generated yaml files that are made apply both values files.

One possible solution would be to have a make target to generate the merged values files for these tests, but that adds complexity in a different area.

I guess the main decision is do we want to add complexity to:
* The tests, by allowing multiple values files
* The values files, by making a new values file for each test, just for the framework tests
* The makefile, by generating the merged values

**Comment by howardjohn** [comment]
After some discussion I realized I misunderstood the changes that would be made to the testing; the default values file is still always applied, so we can just make a new file with values-e2e merged with the current default, which should be a lot simpler.

**Comment by incfly** [comment]
@ozevren can you grant lgtm and approve?

@sdake @costinm can you grant `install/OWNERS`?

**Comment by howardjohn** [comment]
@ozevren can you grant lgtm and approve?

@sdake @costinm can you grant install/OWNERS?

This is a low/no risk change that impacts tests only and will reduce test failures

**Comment by mandarjog** [comment]
Is values-integration same as values-e2e?

The more copies we have, more difficult to keep them is sync.

**Comment by howardjohn** [comment]
> Is values-integration same as values-e2e?
> 
> The more copies we have, more difficult to keep them is sync.

It currently is, but with mcp on and mtls off (not sure what values-e2e has for these).

I agree its not great - any alternative ideas? 

1. Apply 2 files in the tests - complicates the code and is confusing for testers/debugging
1. This change - simple, but duplicates values
1. Make target that generates values-integration.yaml - no duplication at the cost of some more complexity, can no longer run `go test ...` which I believe is one of the goals of the new framework.

**Comment by ozevren** [comment]
Sorry, just getting back to this. 
The E2E tests should have MCP on by default. So we should be able to use e2e-values for that purpose.

Re: mtls off, it is worth checking the output of e2e yaml output. I suspect we will have tests using/having both, so this can be either handled as an override to e2e, or following the patterns we already for such tests.

So, using just e2e values should work?

**Comment by howardjohn** [comment]
The only differences between values-e2e is:
```yaml

 global:
  controlPlaneSecurityEnabled: false
  mtls:
    enabled: false
  useMCP: true
```

These are all defaults, and values-e2e doesn't override, so we could just use values-e2e

**Comment by howardjohn** [comment]
Closing this as it is already fixed in master

**Pull request closed without merging**
