### PR TITLE
Add Authz test for JWT aud claim

### PR DESCRIPTION
**Pull request by jaellio**
**Please provide a description of this PR:**

Test aud matching a list or a value
Related to #50843

### CODE REVIEW

**Comment by jaellio** [comment]
@kyessenov I believe this tests a similar scenario to the one fixed in #50843. Tried to leverage existing `gen-jwt.py` to generate token with aud list.

**Review by kyessenov — APPROVED** [review]
Thank you, this test looks right I think.

**Review by howardjohn — APPROVED** [review]
thanks!

**Pull request merged**
