### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brian-avery**
This PR cleans up spacing and adds quotes around the docs entries such that the content from the example can literally be copied and used.

### CODE REVIEW

**Review by carolynhu — APPROVED** [review]

**Comment by carolynhu** [comment]
@brian-avery I made a small typo fix for this `This field describes the are of Istio that the note affects.` line, which should be `area`. let's see, which PR gets merged first, then might need a rebase.

**Review by sdake — APPROVED** [review]
LGTM.

**Review by dgn — APPROVED** [review]
/retest

**Pull request merged**
