### PR TITLE
rename istio.io/istio/pilot/pkg/networking/core/v1alpha3 to istio.io/istio/pilot/pkg/networking/core

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by keithmattix** [comment]
+1 to this change assuming istio/api#3111 gets merged

**Comment by hzxuzhonghu** [comment]
TBH before moving to v1 i have such thought

**Comment by hzxuzhonghu** [comment]
/test release-notes


@keithmattix @howardjohn ready to go

**Review by hanxiaop — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by zirain** [comment]
ping @istio/wg-networking-maintainers-pilot

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
