### PR TITLE
Integration tests for ingress SDS when the control plane certificate provider is k8s CA

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: integration tests for ingress SDS when the control plane certificate provider is k8s CA.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
We need a more sustainable model for these test then having the same test duplicated into 10+ different test suites

**Comment by howardjohn** [comment]
ref https://github.com/istio/istio/issues/17512

**Comment by lei-tang** [comment]
Per offline discussion, to reduce the test running time, for the existing 7 tests in tests/integration/security/sds_ingress, 5 of them are moved to postsubmit. 
For the new tests, only add two new tests while sharing the test functions with exisiting ones.

@howardjohn please take another look.

**Comment by howardjohn** [comment]
> Per offline discussion, to reduce the test running time, for the existing 7 tests in tests/integration/security/sds_ingress, 5 of them are moved to postsubmit.
> For the new tests, only add two new tests while sharing the test functions with exisiting ones.

My understanding is that this is not the case from this PR. There are 7 existing postsubmit tests, and you added 2. None of the existing ones changed. Is that correct?

**Comment by lei-tang** [comment]
@howardjohn Correct, the existing ones are not changed as you mentioned that flakey and postsubmit labels are identical. Can you remove the "change requested" label on this PR so it can be merged?

**Pull request merged**
