### PR TITLE
Remove unused stats

### PR DESCRIPTION
**Pull request by SpecialYang**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by SpecialYang** [comment]
The annotation `sidecar.istio.io/statsInclusionPrefixes` is not recommended. Should we use the following annotation instead it?
```
proxy.istio.io/config: |-
  proxyStatsMatcher:
    inclusionPrefixes:
    - "cluster.outbound"
    - "cluster_manager"
    - "listener_manager"
    - "server"
    - "cluster.xds-grpc"
```

**Comment by bianpengyuan** [comment]
> The annotation `sidecar.istio.io/statsInclusionPrefixes` is not recommended. Should we use the following annotation instead it?
> 
> ```
> proxy.istio.io/config: |-
>   proxyStatsMatcher:
>     inclusionPrefixes:
>     - "cluster.outbound"
>     - "cluster_manager"
>     - "listener_manager"
>     - "server"
>     - "cluster.xds-grpc"
> ```

Yeah that would be ideal. Thanks!

**Comment by SpecialYang** [comment]
@bianpengyuan I have updated it. PTAL.

**Review by bianpengyuan — APPROVED** [review]

**Review by kebe7jun — APPROVED** [review]

**Pull request merged**
