### PR TITLE
Updating istiod helm chart to allow the use of host networking for pilot pods in istiod

### LINKED ISSUE #45761: Professionally let's unit and solve it out .  Let's stand as one
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by geoffo-dev**
**Please provide a description of this PR:**

This PR will add the option to use host networking on the pilot primarily to support the use of custom CNIs whilst using cloud based k8s distros

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
please start working after make an agreement: https://github.com/istio/istio/issues/45738#issuecomment-1613775893

**Comment by geoffo-dev** [comment]
> please start working after make an agreement: [#45738 (comment)](https://github.com/istio/istio/issues/45738#issuecomment-1613775893)

Sorry - thought I would just have it ready to go

**Comment by zirain** [comment]
IMO, this should be introuded as standard practice, you can achieve that with https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by geoffo-dev** [comment]
I dont disagree @zirain that it can be - however, from an automation perspective, particularly using tools such as argocd, it is a bit of a nightmare and kinda (IMO) defeats the point of a helm chart.

**Comment by zirain** [comment]
IIRC, argocd can work with helm + kustomize, correct me if I'm wrong.

**Comment by geoffo-dev** [comment]
To be honest, I thought it could only work with one or the other and not do the post render, looks like there is an option to! I didn't realise - thanks!

Although would that still stop this change from being valid? If other people have this issue, then it would be much easier to implement.

**Comment by howardjohn** [comment]
I specifically do not want to make bad ideas easier to implement

**Comment by geoffo-dev** [comment]
So out of all the projects I implemented today, all of them had the option to change this, istio has been the exception. 

I know this is not the fault of Istio, but to work with any cloud provider k8s offering, this change will need to be made. Whilst I appreciate most will chain, I think this is still a valid use case and not the fault of the user.

I appreciate you don’t want to make this easier, but the default would be off and a conscious decision would need to be made to turn it on - I am sure people would only need to do that for this use case…

Sorry be a pain, I have a solution, I just want to make it a bit easier for the next person.

**Comment by howardjohn** [comment]
FWIW it's not "any cloud provider". Plenty of providers like GKE support
this fine - to be honest, I am surprised the ones that do not pass
conformance tests.

**Pull request closed without merging**
