### PR TITLE
basic istio ascii art

### PR DESCRIPTION
**Pull request by ilrudie**
**Please provide a description of this PR:**

location still TBD, suggestions please

the intent would be to use this in istioctl. potentially components might embed and print during startup

### CODE REVIEW

**Comment by ilrudie** [comment]
https://pkg.go.dev/github.com/fatih/color may be an option for adding colored output

**Comment by linsun** [comment]
Would love to preview the result in istioctl before approval - is it possible?

**Comment by ilrudie** [comment]
Yeah, I think that would be possible.

**Comment by ilrudie** [comment]
image

**Comment by ilrudie** [comment]
example colored ascii art

image

**Review by linsun — APPROVED** [review]
LGTM, thanks Ian!

**Pull request merged**
