### PR TITLE
fix vulnerability in istio proxy_init image.

### PR DESCRIPTION
**Pull request by morvencao**
Similar to https://github.com/istio/istio/pull/8494

Fix vulnerability issues in istio proxy_init image:
image

### CODE REVIEW

**Comment by sdake** [comment]
@GregHanson can you give this an /approve?

Cheers
-steve

**Comment by linsun** [comment]
@morvencao should we create a PR for this in 1.0 too?

**Comment by gyliu513** [comment]
@linsun +1 to cherry-pick this to 1.0, but one question is if we chery-pick some fixes to 1.0, do we need to increase the chart version? Based on helm chart policy, the chart version should be updated if there are new changes to a released chart.

@sdake @costinm for more comments for how to maintain the chart version.

**Comment by linsun** [comment]
what is the issue of getting this in 1.0.3 and use 1.0.3 as the chart version?  Sorry I'm not understanding your concern.

**Pull request merged**
