### PR TITLE
Add analyzers for Sidecar workload selectors

### PR DESCRIPTION
**Pull request by sushicw**
Adds analyzers that cover the following:
* Per namespace, there should be at most one Sidecar resource without a workload selector
* For Sidecars with a workload selector, it should map to at least one pod in its namespace
* Multiple Sidecars in the same namespace should not select the same pod

See https://github.com/istio/istio/issues/18468

### CODE REVIEW

**Comment by howardjohn** [comment]
I didn't get a chance to look at the code in detail, we should make sure this is abstracted so it can apply to other CRDs if possible. The workload selector in Sidecar is shared between other CRDs as well, and will be shared more in the future, and I think the same rules apply to all of these. At  the very least the new Policy does, I think?

**Comment by sushicw** [comment]
> I didn't get a chance to look at the code in detail, we should make sure this is abstracted so it can apply to other CRDs if possible. The workload selector in Sidecar is shared between other CRDs as well, and will be shared more in the future, and I think the same rules apply to all of these. At the very least the new Policy does, I think?

Yes. I didn't try to make it generic here because I'm not familiar enough with the other usages to be sure what would overlap and what wouldn't, but I expect there will be something worth refactoring out eventually.

**Pull request merged**
