### PR TITLE
remove cni initContainers and volumes in remove-from-mesh

### PR DESCRIPTION
**Pull request by tariq1890**
Committing files which I had forgotten to push in my earlier PRs. I was wondering why my master builds were working and not the release ones *facepalm*

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by tariq1890** [comment]
@esnible Requesting your review on this

**Comment by esnible** [comment]
@tariq1890 This PR targets Master.I approved this but removed the `cherrypick-1.7`.  Instead of using the auto-cherry pick, I would like to see all of your remove-from-mesh merged PRs get cherry-picked manually to 1.7 branch.

Do you know how to check out the release-1.7 branch, cherry-pick, and create PR?  If so, do that and in the comments link to the merged Master PRs.

**Comment by tariq1890** [comment]
Yes i do. I can get around to doing that later in the day

**Comment by tariq1890** [comment]
@esnible Done!

**Pull request merged**
