### PR TITLE
istioctl: add confirmation for istioctl operator remove

### LINKED ISSUE #41244: `istio operator remove` should confirm
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
`istio operator remove`  may need a confirmation  like `istio uninstall`

**Describe alternatives you've considered**
Show results:
```
$./istioclt operator remove -h
The remove subcommand removes the Istio operator controller from the cluster.

Usage:
  istioctl operator remove [flags]

Flags:
      --dry-run                    Console/log output only, make no changes.
      --force                      Proceed even with validation errors.
  -h, --help                       help for remove
      --operatorNamespace string   The namespace the operator controller is installed into. (default "istio-operator")
  -r, --revision string            Target revision for the operator.
  -y, --skip-confirmation          The skipConfirmation determines whether the user is prompted for confirmation.
                                   If set to true, the user is not prompted and a Yes response is assumed in all cases.

Global Flags:
      --context string      The name of the kubeconfig context to use
  -c, --kubeconfig string   Kubernetes configuration file
      --vklog Level         number for the log level verbosity. Like -v flag. ex: --vklog=9
$
$
$ ./istioctl operator remove -y
Removing Istio operator...
  Removed Deployment:istio-operator:istio-operator.
  Removed Service:istio-operator:istio-operator.
  Removed ServiceAccount:istio-operator:istio-operator.
  Removed ClusterRole::istio-operator.
  Removed ClusterRoleBinding::istio-operator.
✔ Removal complete
$
$  ./istioctl operator remove
Istio operator will be removed from cluster, Proceed? (y/N) n
Cancelled.
$
$ ./istioctl operator remove
Istio operator will be removed from cluster, Proceed? (y/N) y
Removing Istio operator...
  Removed Deployment:istio-operator:istio-operator.
  Removed Service:istio-operator:istio-operator.
  Removed ServiceAccount:istio-operator:istio-operator.
  Removed ClusterRole::istio-operator.
  Removed ClusterRoleBinding::istio-operator.
✔ Removal complete
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by my-git9**
**Please provide a description of this PR:**
add confirmation for istio operator remove

Fix https://github.com/istio/istio/issues/41244

### CODE REVIEW

**Comment by my-git9** [comment]
Hi @howardjohn, can you review this PR? Thanks a lot!

**Review by GregHanson — APPROVED** [review]
release note looks good

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by morvencao — APPROVED** [review]

**Review by richardwxn — APPROVED** [review]

**Pull request merged**
