### PR TITLE
Fix pilot race errors

### PR DESCRIPTION
**Pull request by howardjohn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
blocked by https://github.com/istio/istio/pull/26078

/retest

**Comment by ramaraochavali** [comment]
@howardjohn Could you please create a manual cherry pick for 1.7?

**Pull request merged**
