### PR TITLE
Fix: correct error format after json marshal

### PR DESCRIPTION
**Pull request by whalecold**
**Please provide a description of this PR:**
ref: https://github.com/istio/istio/issues/36358

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by whalecold** [comment]
> /ok-to-test

Hi, could you please add the release-notes-none label to the pull request ?

**Review by jacob-delgado — APPROVED** [review]

**Comment by whalecold** [comment]
@hzxuzhonghu hi, can you help merge this pull request

**Comment by kevinnoel-be** [comment]
We're having the same issue, could this fix be pushed through?

**Review by esnible — APPROVED** [review]
LGTM

**Pull request merged**
