### PR TITLE
Revert "Istioctl - Revision centric view"

### PR DESCRIPTION
**Pull request by howardjohn**
Reverts istio/istio#29713

This broke our tests: https://github.com/istio/istio/issues/30401

### CODE REVIEW

**Review by GregHanson — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Comment by su225** [comment]
Can we just remove the integration tests as it causing trouble? The command is experimental anyways.

**Comment by howardjohn** [comment]
sure, if you send a pr I can approve it. Thanks!

**Comment by su225** [comment]
https://github.com/istio/istio/pull/30424 - PR for fixing flake. It seems that another test messed with the environment removing mutating webhook configurations. After moving to separate suite it seems to be fine. If it takes time then we can move it to post-submit.

**Comment by howardjohn** [comment]
seems that was not enough to fix it

**Comment by su225** [comment]
So. I'm removing it now - https://github.com/istio/istio/pull/30426

**Comment by howardjohn** [comment]
thanks!

**Review by shamsher31 — APPROVED** [review]

**Comment by su225** [comment]
@shamsher31 - I don't think we need to revert the entire PR. I have already removed integration tests in  #30426

**Pull request closed without merging**
