### PR TITLE
ambient: dynamically determine dstport for geneve link

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

This small change fixes one of the issues of ambient on OpenShift with ovn-kubernetes CNI.

By default, ovn-kubernetes creates an external geneve link named "ovn_sys_6081", and therefore istio-cni fails to create links for geneve tunnels `istioin` and `istioout`, because "**There already exists an externally controlled device on this destination port**" - this is the error message from `ip link add` command. The port conflict occurs, because istio-cni does not specify destination ports for created links and therefore it uses the same port - 6081.

I also noticed that similar error may occur when a node has a geneve link with the same VNI and remote IP as `istioin` and `istioout`. This is probably unlikely to happen, but it's at least theoretically possible.

I added a function to find first available destination port if there is a conflict.

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
LGTM. Thanks!

**Comment by jewertow** [comment]
Thanks, I added a release note.

**Review by howardjohn — COMMENTED** [review]
Do we need to update here?

```
cni/pkg/ambient/net_linux.go
490:            // Don't set anything on the tunnel (geneve port is 6081), as the tunnel copies
497:                    "--dport", "6081",
```

**Comment by jewertow** [comment]
Oh, I missed that... Thanks for vigilance.

**Comment by jewertow** [comment]
Previously, I tested only the installation and therefore I didn't notice that I have to set determined port for geneve links in ztunnel network namespace.

To make sure that network traffic will work when an external geneve link exists on the default port, I tested all samples from the docs https://istio.io/latest/docs/ops/ambient/getting-started/, but after creating kind cluster and before installing Istio, I created a conflicting link with the following command:
```
kubectl apply -n default -f - <<EOF
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: external-geneve
spec:
  selector:
    matchLabels:
      k8s-app: external-geneve
  template:
    metadata:
      labels:
        k8s-app: external-geneve
    spec:
      tolerations:
      - operator: "Exists"
      hostNetwork: true
      containers:
      - name: iproute
        image: redhat/ubi8:8.6
        command:
        - "/bin/sh"
        - "-c"
        - |
          dnf install -y iproute
          echo "ip addr:"
          ip addr
          ip link add ovn_sys_6081 type geneve external
          echo "ip link:"
          ip link
          sleep 60
        securityContext:
          runAsGroup: 0
          runAsUser: 0
          runAsNonRoot: false
          privileged: true
EOF
```
CNI didn't log any error and network traffic was as expected in the docs.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
