### PR TITLE
Fix lint error underscore in package name sds_ingress

### PR DESCRIPTION
**Pull request by nak3**
This patch fixes lint error underscore in package name sds_ingress.
Please refer to the error in https://github.com/istio/istio/pull/19261

/cc @pitlv2109 @myidpt

### CODE REVIEW

**Comment by nak3** [comment]
Umm.. cherry pick PR has this fix https://github.com/istio/istio/pull/19275 even though master PR https://github.com/istio/istio/pull/19270 has this error.  

Anyway new PR like https://github.com/istio/istio/pull/19261 does not pass lint check without this fix.

**Comment by pitlv2109** [comment]
@howardjohn mentioned there might be a bug in the master linter. There are some other places where we have underscored package names (e.g. https://github.com/istio/istio/blob/master/tests/integration/security/sds_citadel_flow/main_test.go#L15), so you might need to change those as well.

**Comment by nak3** [comment]
I have checked other underscored package names and there are two patterns:

a. package name has `_test` which is test packages literally like [main_test.go](https://github.com/istio/istio/blob/master/tests/integration/security/sds_citadel_flow/main_test.go).
b. package name has `_` because of auto generated code like [template_handler.gen.go](https://github.com/istio/istio/blob/master/mixer/adapter/kubernetesenv/template/template_handler.gen.go).

When we fixed them, a) needs to solve cyclic import errors, b) needs to have filename changes. So, it would be a huge change (and I think it should be done by another PR.)

**Comment by nak3** [comment]
Closing as it was fixed by https://github.com/istio/istio/pull/18991

**Pull request closed without merging**
