### PR TITLE
Add custom address support for LocalDNSServer

### PR DESCRIPTION
**Pull request by kebe7jun**
Add custom address support for LocalDNSServer and fix https://github.com/istio/istio/issues/30131

[X] Networking
[X] Test and Release

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
Seems reasonable, but what is the motivation for custom address? I don't think the iptables will work if you change it

**Comment by kebe7jun** [comment]
> Seems reasonable, but what is the motivation for custom address? I don't think the iptables will work if you change it

I didn't change it, its default value is localhost:5353, mainly because I need it when writing unit tests.

**Review by adiprerepa — APPROVED** [review]

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
It looks confusing to me. Neither there is a flag nor an env to set the address.

**Pull request closed without merging**
