### PR TITLE
Add cluster filtering based on exposed services via VS in case of AUTO_PASSTHROUGH gw

### PR DESCRIPTION
**Pull request by shivanshu1333**
**Please provide a description of this PR:**
Issue ref: https://github.com/istio/istio/issues/42304
This PR provides one of the possible implementation to avoid generation of massive envoy cluster configs when gw is set to 
`AUTO_PASSTHROUGH` mode.

Currently, there's no filtering mechanism to filter the creation of envoy cluster configs only for exposed services when using `AUTO_PASSTHROUGH` as tls mode in the gateway.

This PR adds this feature by enabling a filtering mechanism using an additional virtual service.
The user needs to create a virtual service having all the exposed services, 
and enable `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`

Now, envoy cluster configs will be generated for only those services which are mentioned in VS will be created.

For eg, if I need to expose only hello world service,
without this feature the config generated will have
```bash
SERVICE FQDN                                                                   	PORT 	SUBSET 	DIRECTION 	TYPE       	DESTINATION RULE
BlackHoleCluster                                                               	-    	-      	-         	STATIC
agent                                                                          	-    	-      	-         	STATIC
outbound_.15010_._.istiod-stable.istio-system.svc.cluster.local                	-    	-      	-         	EDS
outbound_.15012_._.istiod-stable.istio-system.svc.cluster.local                	-    	-      	-         	EDS
outbound_.15014_._.istiod-stable.istio-system.svc.cluster.local                	-    	-      	-         	EDS
outbound_.15021_._.echo-gateway.echo-7-79306.svc.cluster.local                 	-    	-      	-         	EDS
outbound_.15021_._.httpbin-gateway.httpbin-gateway-2-22729.svc.cluster.local   	-    	-      	-         	EDS
outbound_.15443_._.echo-gateway.echo-7-79306.svc.cluster.local                 	-    	-      	-         	EDS
outbound_.15443_._.httpbin-gateway.httpbin-gateway-2-22729.svc.cluster.local   	-    	-      	-         	EDS
                               ...
                               ...
                               ...
outbound_.18080_._.external-ratelimit-server.default.svc.cluster.local         	-    	-      	-         	EDS
outbound_.18443_._.echo-gateway.echo-7-79306.svc.cluster.local                 	-    	-      	-         	EDS
outbound_.18443_._.external-ratelimit-server.default.svc.cluster.local         	-    	-      	-         	EDS
outbound_.443_._.echo-gateway.echo-7-79306.svc.cluster.local                   	-    	-      	-         	EDS
outbound_.443_._.httpbin-gateway.httpbin-gateway-2-22729.svc.cluster.local     	-    	-      	-         	EDS
outbound_.443_._.istiod-stable.istio-system.svc.cluster.local                  	-    	-      	-         	EDS
outbound_.443_._.kubernetes.default.svc.cluster.local                          	-    	-      	-         	EDS
outbound_.5000_._.helloworld.echo-7-79306.svc.cluster.local                    	-    	-      	-         	EDS        	dr-ew-helloworld-echo-7-79306-svc-cluster-local.echo-7-79306
prometheus_stats                                                               	-    	-      	-         	STATIC
sds-grpc                                                                       	-    	-      	-         	STATIC
xds-grpc                                                                       	-    	-      	-         	STATIC
zipkin                                                                         	-    	-      	-              STRICT_DNS
```

**with this feature user can add a VS to expose hello world and then the generated envoy cluster configs will be**
```bash
$ i pc c echo-eastwestgateway-7b9d5455cf-rpf84.echo-7-93033

SERVICE FQDN                                                    PORT     SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                -        -          -             STATIC
agent                                                           -        -          -             STATIC
helloworld.echo-7-93033.svc.cluster.local                       5000     -          outbound      EDS            dr-ew-helloworld-echo-7-93033-svc-cluster-local.echo-7-93033
outbound_.5000_._.helloworld.echo-7-93033.svc.cluster.local     -        -          -             EDS            dr-ew-helloworld-echo-7-93033-svc-cluster-local.echo-7-93033
prometheus_stats                                                -        -          -             STATIC
sds-grpc                                                        -        -          -             STATIC
xds-grpc                                                        -        -          -             STATIC
zipkin
```

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [x] Configuration Infrastructure
- [x] Docs
- [x] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [x] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

Contains user facing changes.

### CODE REVIEW

**Comment by howardjohn** [comment]
Isn't it still broken? Sidecars will send all domains through the GW, and they will be missing the config?

**Comment by shivanshu1333** [comment]
This will only happen when the feature `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` is enabled. Why would it break anything?

**Comment by shivanshu1333** [comment]
when the feature is disabled, there's no need of creating VS. When feature is enabled, user can create VS to control envoy cluster config creation.

**Comment by howardjohn** [comment]
AUTO_PASSTHROUGH scope is based on the `host` field of Gateway. I am not
sure how you can have that without a VS?

**Comment by shivanshu1333** [comment]
Umm, ok, Can you point to me a UT/e2e which would fail?
Thanks!

**Comment by howardjohn** [comment]
Any usage of multicluster that also configured a virtual service. Its not
common to use a VS with AUTO_PASSTHROUGH since they usually use a dedicated
gateway.

**Comment by shivanshu1333** [comment]
Also, if you think there's something broken, can you help in proposing a solution (similar to this maybe, or some enhance on top of it). Going through some UT/e2e tests will help me understand it better.
Thanks

**Comment by howardjohn** [comment]
I don't think there is an easy solution. AUTO_PASSTHROUGH fundamentally
needs all of the clusters. There could be broad refactoring of the entire
XDS to make it not require so many, maybe, but just filtering will never
work.

**Comment by shivanshu1333** [comment]
I don't think we'd have an e2e with this...
> Any usage of multicluster that also configured a virtual service

where VS to attached to an AUTO_PASSTHROUGH gw

**Comment by shivanshu1333** [comment]
I'm still not very clear, what will happen if I want my GW (for some reason configured as an AUTO_PASSTHROUGH) to create enovy cluster configs for specific services which are exposed to GW via VS...

> I don't think there is an easy solution. AUTO_PASSTHROUGH fundamentally
> needs all of the clusters. There could be broad refactoring of the entire
> XDS to make it not require so many, maybe, but just filtering will never
> work.

I'd think more about this and come back...
Thanks!

**Pull request closed without merging**
