### PR TITLE
Skip test/try to diagnose test flakes

### PR DESCRIPTION
**Pull request by bleggett**
**Please provide a description of this PR:**
Trying a few things  to understand how/why https://github.com/istio/istio/issues/54303 can happen,  since it's still non-obvious to me how it could and I cannot coerce local repros.

There are, as far as I can see, only 2 possibilities here.

1. The `kubeclient` we use on shutdown is reporting stale data - the DS has been deleted, our pods get a SIGTERM, we `GET` the DS from inside the pod, and it's still there, even though our pod has been told to terminate _because_ it was deleted - e.g. racy/stale reads from the K8S API server. I haven't been able to repro this with `helm` or `istioctl` or plain old manifest deletion.  It is _very_ unlikely that this is the case.

2. `TestCNIMisconfigHealsOnRestart` is putting the installer into a bad state  because of it's net dir  munging, and this was made more manifest when we initialized the installer earlier in https://github.com/istio/istio/pull/54180.

This PR assumes No. 2, I want to see if it impacts the flakes. If it does not, then No. 1 is what we are left with.

### CODE REVIEW

**Comment by howardjohn** [comment]
> The kubeclient we use on shutdown is reporting stale data - the DS has been deleted, our pods get a SIGTERM, we GET the DS from inside the pod, and it's still there, even though our pod has been told to terminate because it was deleted - e.g. racy/stale reads from the K8S API server. I haven't been able to repro this with helm or istioctl or plain old manifest deletion. It is very unlikely that this is the case.

This would violate Kubernetes API guarantees -- we are using a direct GET.

One thing I did notice though:

`log.Debugf("Daemonset %s has deletion timestamp?: %+v", dsName, cniDS.DeletionTimestamp)` - this log line will panic when cniDS == nil, which will happen when its deleted. That means if it is a delete, we panic, and therefor don't clean up?

**Comment by bleggett** [comment]
> 
> One thing I did notice though:
> 
> `log.Debugf("Daemonset %s has deletion timestamp?: %+v", dsName, cniDS.DeletionTimestamp)` - this log line will panic when cniDS == nil, which will happen when its deleted. That means if it is a delete, we panic, and therefor don't clean up?

Yep, that was my first thought - but in that case it should be trivial to reproduce the panic (it doesn't panic) and it should panic every time we uninstall and we log that the DS is gone (it doesn't).

**Comment by howardjohn** [comment]
ah, k8s returns an empty object when not found (ref https://github.com/kubernetes/kubernetes/issues/126664)

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
