### PR TITLE
Adds Gateway API Weighted Routing Bookinfo Example

### PR DESCRIPTION
**Pull request by danehans**
**Please provide a description of this PR:**
Adds sample manifest for Gateway API weight-based routing for the bookinfo reviews v1/v2 service.

In support of https://github.com/istio/istio.io/issues/12803.

### CODE REVIEW

**Review by frankbu — APPROVED** [review]

**Comment by danehans** [comment]
CI is failing due to:

```
Missing "release-notes-none" label
```

**Review by linsun — APPROVED** [review]
/retest

**Pull request merged**
