### PR TITLE
Make sure all the events in the eventCh been processed

### PR DESCRIPTION
**Pull request by whalecold**
**Please provide a description of this PR:**

https://github.com/istio/istio/pull/42914

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by whalecold** [comment]
@hzxuzhonghu Hi,  I have a new idea about the old [pr](https://github.com/istio/istio/pull/42914) , could you take a look ?

**Comment by howardjohn** [comment]
I think I left this comment on the original PR, I still don't understand *why* we need this. Even Kubernetes informer doesn't provide this guarantee. if we are closing the configstore why do we care about its events?

**Comment by hzxuzhonghu** [comment]
Fair point from John

**Comment by whalecold** [comment]
> I think I left this comment on the original PR, I still don't understand _why_ we need this. Even Kubernetes informer doesn't provide this guarantee. if we are closing the configstore why do we care about its events?

The lifecycle of a Kubernetes informer is typically the same as a process, and the process will process all the events again when it restarts, so there is no need to take the guarantee and it's the same way with "configstore".  In our team, we support multiple [ADSC](https://github.com/istio/istio/blob/c37f54c11d3ee71e829727564a769a276195a347/pkg/adsc/adsc.go#L144) and store the data with the configstore, it can configure the registry dynamically. It must therefore guarantee to process all events when a registry is erased, otherwise there will be dirty data in memory.

**Comment by howardjohn** [comment]
Why? once we remove the registry we should remove all resources. Why does it matter if we miss the last few "add" if we are going to remove them anyways?

BTW, informer != process, we have dynamic with multi-cluster as well

**Comment by whalecold** [comment]
> BTW, informer != process, we have dynamic with multi-cluster as well

I'm sorry, i forget it. 

> Why? once we remove the registry we should remove all resources. Why does it matter if we miss the last few "add" if we are going to remove them anyways?
>

The k8s resources(such as service pod) reside in the informer, and it will be clean when the infomer removed. But the istio crd (such as serviceentry, workloadentry) reside in the [serviceentryStore](https://github.com/istio/istio/blob/c37f54c11d3ee71e829727564a769a276195a347/pilot/pkg/serviceregistry/serviceentry/controller.go#L99), it use [callback hander](https://github.com/istio/istio/blob/c37f54c11d3ee71e829727564a769a276195a347/pilot/pkg/serviceregistry/serviceentry/controller.go#L210) to manage the serviceInstance. If the events are lost, the data in the serviceentryStore  may be not right.

**Comment by howardjohn** [comment]
We should be issuing Delete events when we tear down the store then probably?

**Comment by whalecold** [comment]
> We should be issuing Delete events when we tear down the store then probably?

I think so.

**Comment by hzxuzhonghu** [comment]
close since we donot need this feature atm

**Pull request closed without merging**
