### PR TITLE
[release-1.9] Fix probe header

### PR DESCRIPTION
**Pull request by wzshiming**
This is an cherry-pick of #31981
Fixes #32105

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by shamsher31** [comment]
@wzshiming can you also cherry-pick tests? Looks like test is missing.

**Comment by wzshiming** [comment]
The test commit conflicts with this version
#32105 
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32105/lint_istio_release-1.9/1381458583647948800/build-log.txt

**Comment by shamsher31** [comment]
The cherry-pick should match exactly the same PR merged in master. This way we don't face conflicts for the future PR's. Please also add https://github.com/istio/istio/pull/31981/files#diff-1e904fe2f4270621c37137d26d788dadfc65300f4b589eb71ffd2df108c0696eR40 in this PR.

**Comment by wzshiming** [comment]
> The cherry-pick should match exactly the same PR merged in master. This way we don't face conflicts for the future PR's. Please also add https://github.com/istio/istio/pull/31981/files#diff-1e904fe2f4270621c37137d26d788dadfc65300f4b589eb71ffd2df108c0696eR40 in this PR.


https://github.com/istio/istio/pull/32108/commits/42ad20650243e69d3ed33029da14b88cb4f7a7da
Because this was renamed , In 1.10 is `Options`,  In 1.9 is `Config`

**Comment by shamsher31** [comment]
@wzshiming Sorry, I mean can you add the following line in `pkg/kube/apimirror/probe.go` file as in the original PR.

> // Custom headers to set in the request. HTTP allows repeated headers.

Other things LGTM.

**Comment by wzshiming** [comment]
> I mean can you add the following line in `pkg/kube/apimirror/probe.go` file as in the original PR.

https://github.com/istio/istio/blob/80052f5a21deeb5fb19b23bb8a051884e267c295/pkg/kube/apimirror/probe.go#L40

This line already exists in 1.9,.

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
