### PR TITLE
Moving API repo into istio/istio/api

### PR DESCRIPTION
**Pull request by rshriram**
Used git subtree to pull all commits from API into istio/istio
thereby preserving commit histories.

Fixed up references throughout code base to use istio/api
instead of importing from vendor (istio.io/api). Had to regenerate
mixer stuff due to this change.

Added top level Makefile targets. Any uncommitted changes to
API will be caught by the depend.diff target (circleci) as
well as prow (make build->depend->api.generate).

Still need to figure out a bot to mirror changes from this
folder to istio.io/api.

Had to revert https://github.com/istio/api/pull/594 as it
caused compilation errors. The PR is also something that should
not have been approved as it creates a new top level directory
as a library of commonly used stuff. This is not something we
want end users to see.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
We need a mechanism to sync to istio/api repo.
Unless you are proposing to introduce a dependency from istio/proxy on istio/istio, which is a circular dependency.

**Comment by kyessenov** [comment]
/hold
Please remove python code.

**Comment by rshriram** [comment]
I am going to mirror the api folder to istio.io/api

**Comment by kyessenov** [comment]
Let's get the whole setup ready before committing changes. Otherwise, we are stuck in semi-broken state. If you can setup scripts for mirroring (and code generation), and hook it in prow/circle, then we're good.

**Comment by yangminzhu** [comment]
@rshriram Could you clarify how did istio/api#594 cause compilation errors? It's merged automatically as it passed all required tests.

There are actually [multiple duplicate](https://github.com/istio/api/search?q=StringMatch+extension%3Aproto&unscoped_q=StringMatch+extension%3Aproto) `StringMatcher` definitions in the code, isn't it better to use a single definition across the code? or if you think it's okay to define a third `StringMatch` in `policy.proto`?

/cc @diemtvu

**Comment by rshriram** [comment]
Api doesn’t test with istio/istio. So the sha you had was never used with istio until my pr. Doug said it had something to do with gogo

**Comment by ldemailly** [comment]
closed?

**Pull request closed without merging**
