### PR TITLE
Fix healthcheck test not cleaning up properly

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/20686

### CODE REVIEW

**Comment by incfly** [comment]
changing this make the health check ns deletion completed? how will this help with the issue your linked? that tls secret test check some stats metrics which can be polluted by heath check test?

could you elaborate a bit?

**Comment by howardjohn** [comment]
the old pods from this test that try to talk to the pilot later in other tests get tls handshake errors. there are some more info on the issue

**Comment by howardjohn** [comment]
the test failing was unrelated to the tls handshake errors but I have no clue how to debug it further

**Pull request merged**
