### PR TITLE
authn: enable sharing for tunnel

### PR DESCRIPTION
**Pull request by kyessenov**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by ramaraochavali** [comment]
curious, what does this "shared" flag do for authn filter?

**Comment by kyessenov** [comment]
@ramaraochavali See https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/internal_listener#internal-upstream-transport, the flag enables sharing.

**Comment by hzxuzhonghu** [comment]
@kyessenov is this related?

**Comment by kyessenov** [comment]
@hzxuzhonghu related to what?

**Comment by hzxuzhonghu** [comment]
I mean this flag is setting istio proxy not envoy while you linked envoy doc

**Comment by kyessenov** [comment]
Ah, the corresponding proxy PR is https://github.com/istio/proxy/pull/4443

**Comment by hzxuzhonghu** [comment]
Thanks this much clearer

**Pull request merged**
