### PR TITLE
Fix mixer source namespace attribute when dot in pod name

### PR DESCRIPTION
**Pull request by chaudyg**
Relates to https://github.com/istio/istio/issues/19015

Mixer `source.namespace` attribute missconfigured on the envoy sidecar when the pod name includes a dot. `.` .

For example, if the pod name is 'foo.bar-1234-5678' in the namespace 'demo', the `source.namespace` mixer attribute inside the sidecar proxy will be set to 'bar-1234-5678' instead of 'demo'.

Proxy.Id format is `<pod_name>.<namespace>` in kubernetes
https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L82-L84

### CODE REVIEW

**Comment by chaudyg** [comment]
Question for the reviewer:   Do you think I should add a test for the case 'pod-name.with.dot'? The happy path (pod without dot) is already covered by the entire codebase. I would gladly add one if you think it's relevant.

Also, do you think this fix could be cherry-picked into 1.4/1.3?

Cheers

**Comment by douglas-reid** [comment]
/ok-to-test

Please add a test, and reference the bug. We should cherry-pick to the releases.

**Comment by chaudyg** [comment]
@douglas-reid I've added a test. Let me know if that works for you! Also, what do you mean by "reference the bug"?

Thx

**Comment by chaudyg** [comment]
@douglas-reid @howardjohn
Thanks for approving/ merging. Would it be possible to cherry-picked into previous releases?

**Comment by chaudyg** [comment]
Out of curiosity do you think this could go on release 1.3 as well 🙏 ?

**Comment by chaudyg** [comment]
Created another PR to cherry-pick into release 1.3
https://github.com/istio/istio/pull/19223

**Pull request merged**
