### PR TITLE
istiod use cert-chain to verify cert

### PR DESCRIPTION
**Pull request by irisdingbj**
Take over from https://github.com/istio/istio/pull/34486 to fix https://github.com/istio/istio/issues/34218
Enhance integration test to sign cert with intermediate cert to cover this case.

### CODE REVIEW

**Comment by irisdingbj** [comment]
@shankgan @howardjohn A ping on this. Thanks.

**Comment by shankgan** [comment]
> @shankgan @howardjohn A ping on this. Thanks.

Looks great. Thanks for taking care of this!

**Review by shankgan — APPROVED** [review]

**Comment by jacob-delgado** [comment]
Can we add some test cases for this?

**Comment by irisdingbj** [comment]
> Can we add some test cases for this?

 Hi Jacob, test cases are ready under tests/integration/security/external_ca

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
