### PR TITLE
fix: helm values-istio-gateways.yaml miss cpu.targetAverageUtilization

### PR DESCRIPTION
**Pull request by HYmian**

### CODE REVIEW

**Comment by rshriram** [comment]
Is this critical to 1.0? Why not master ?

**Comment by gyliu513** [comment]
+1 to @rshriram , we should fix this in master.

**Comment by HYmian** [comment]
@gyliu513 should I make a new PR to master？

**Comment by gyliu513** [comment]
yes, close this and create a new pr.

**Pull request closed without merging**
