### PR TITLE
cherry-pick Remove SDS Timeout for default and root case for 1.6

### PR DESCRIPTION
**Pull request by williamaronli**
Please provide a description for what this PR is for.

cherry-pick for release 1.7 https://github.com/istio/istio/pull/26001/

solve this issue: https://github.com/istio/istio/issues/26136
And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by williamaronli** [comment]
@jacob-delgado could you take a look?

**Comment by williamaronli** [comment]
@irisdingbj @jacob-delgado could you take a look and merge it into 1.6 branch thanks

**Comment by irisdingbj** [comment]
https://github.com/istio/istio/pull/26001 . - master PR is  merged

**Review by irisdingbj — APPROVED** [review]
Thanks for this!

**Pull request merged**
