### PR TITLE
Upgrade CA root cert to 10 years

### PR DESCRIPTION
**Pull request by wattli**

### CODE REVIEW

**Comment by linsun** [comment]
@duderino ping for merging

**Comment by wattli** [comment]
non of the above errors seem related @duderino anything we can do here?

**Comment by pitlv2109** [comment]
Boskos resource was overloaded, that's why the prow test failed. I think it should be good now.

/test e2e-mixer-no_auth

**Comment by duderino** [comment]
I'm merging this but will get all the required tests fixed on the 1.0 branch asap

**Pull request merged**
