### PR TITLE
disable format check on 1.0, fix linting violations, update dep to 0.5.0

### PR DESCRIPTION
**Pull request by kyessenov**
There is a little impact of mal-formatted code in 1.0 branch since we don't forward-port changes.
The problem is using goimports at HEAD which is known to break from time-to-time.

/assign @duderino

### CODE REVIEW

**Comment by kyessenov** [comment]
Please retest whenever boskos recovers.

**Comment by duderino** [comment]
This failed with one error that was most likely fixed by https://github.com/istio/istio/pull/13456

```
TestTLS - v2
Failed
ads_test.go:109: Stream resources failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"
```

**Pull request merged**
