### PR TITLE
Fix the body is not closed when the response failure

### PR DESCRIPTION
**Pull request by wzshiming**
[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Comment by wzshiming** [comment]
@morvencao  Hi, this PR needs release-notes-none

**Comment by wzshiming** [comment]
Rebase to fix test failed https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/31798/release-notes_istio/1377107914166112256/build-log.txt

reference #31804

**Pull request merged**
