### PR TITLE
Update proxy sha

### PR DESCRIPTION
**Pull request by mandarjog**
Uses the proxy with ratelimit / status code fix.

### CODE REVIEW

**Comment by ldemailly** [comment]
what's the error ? it's hard to see error in circleci

**Comment by ldemailly** [comment]
--- FAIL: TestStoreWatchMultiple (0.01s)
	store_test.go:138: Got watch already exists, Want nil

**Comment by mandarjog** [comment]
@jmuk can you take a look at the failed test?

**Comment by jmuk** [comment]
Where's the error?

**Comment by mandarjog** [comment]
Looks like it was a flake. Larent but ```store_test.go:138: Got watch already exists, Want nil``` this was the error.

**Pull request merged**
