### PR TITLE
fix a typo to get familiar with the PR process

### PR DESCRIPTION
**Pull request by YaoZengzeng**
The Pull Request processing in istio community seems a bit complicated.

So I try to get familiar with it with this PR 😄

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
/assign @hzxuzhonghu 

PTAL

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu then this PR will be automatically merged by istio-bot sometime?

Or another `/approve` is needed?

**Comment by hzxuzhonghu** [comment]
No, the LGTM also labels approve . Once the ci passes, it can be merged by bot.

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu @geeknoid Why this simple PR has not been merged automatically ? :)

**Comment by hzxuzhonghu** [comment]
The circle ci fails, should retrigger.

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu I don't seem to have the permission to trigger the failed CI case

Would you please to help me rerun it? Thanks!

**Comment by hzxuzhonghu** [comment]
I did, seems flake.

**Pull request merged**
