### PR TITLE
Enable basic presubmit

### PR DESCRIPTION
**Pull request by mandarjog**
**What this PR does / why we need it**:
Enables basic presubmit
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rshriram** [comment]
Sorry. I meant just remove pilot from the WD. Keep rest.

**Comment by rshriram** [comment]
Typing from mobile. Apologies for terse comments

**Comment by rshriram** [comment]
@mandarjog tests failing because of some bazel stuff
```
ERROR: error loading package 'docker': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/docker:docker.bzl': BUILD file not found on package path

Loading: 18 packages loaded

    currently loading: mixer/adapter/noop ... (7 packages)


ERROR: error loading package 'docker': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/docker:docker.bzl': BUILD file not found on package path

Loading: 18 packages loaded

    currently loading: mixer/adapter/noop ... (7 packages)


INFO: Elapsed time: 16.289s

Loading: 18 packages loaded

    currently loading: mixer/adapter/noop ... (7 packages)


FAILED: Build did NOT complete successfully (18 packages loaded)

    currently loading: mixer/adapter/noop ... (7 packages)

Exited with code 1
```

Possibly related to @jmuk 's PR?

**Comment by mandarjog** [comment]
@rshriram can we let this PR thru with a prow presubmit success? 
You can fix the circli presubmit in a separate PR.

Some other PRs can start flowing thru behind this.

**Comment by rshriram** [comment]
Yep.

**Pull request merged**
