### PR TITLE
fix race cluster vip mutex in service (#31204)"

### LINKED ISSUE #31247: concurrent map read and map write in GetServiceAddressForProxy
https://storage.googleapis.com/istio-prow/logs/integ-pilot-multicluster-tests_istio_postsubmit/1367553922817855488/artifacts/pilot-26c62a9f7f924718bb0375036/_suite_context/istio-state-831956234/primary/istiod-85d7db58dc-gtbxr_discovery.previous.log

Broken by https://github.com/istio/istio/commit/a0b66178103fd0fd114d81ddec37905a12db0d5d and/or https://github.com/istio/istio/commit/6c9315b1c58a8310ea7a8a681c3424a619e62f19 I assume

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fix #31247

### CODE REVIEW

**Comment by ramaraochavali** [comment]
I do not mind reverting - but why do we have to revert entire logic?

**Comment by hzxuzhonghu** [comment]
I missed there are some other parts

**Review by ramaraochavali — APPROVED** [review]

**Comment by ramaraochavali** [comment]
just updated the title to reflect the change for future reference

**Pull request merged**
