### PR TITLE
envoy: update set_filter_state config for ambient

### PR DESCRIPTION
**Pull request by kyessenov**
Fixes https://github.com/istio/istio/pull/48759

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
can you share more details about this changes, upstream link or something else.

**Comment by kyessenov** [comment]
Follow-up to https://github.com/envoyproxy/envoy/pull/31594, so that we can remove a custom filter state object.

**Review by ericvn — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
/hold 
Is the new istiod compatible with older proxies? I think you should check the proxy versions, and add the key as needed

**Comment by kyessenov** [comment]
/retest

@hzxuzhonghu This only affects ambient which is alpha and not expected to work with older proxies.

**Comment by hzxuzhonghu** [comment]
make sense, it is only on `ConnectAuthorityFilter`

**Pull request merged**
