### PR TITLE
CNI: refactor and fix memory leak/infinite loops

### PR DESCRIPTION
**Pull request by howardjohn**
# Problem

Since the PR https://github.com/istio/istio/pull/39801 (1.15), there is a bug only when CNI_ENABLE_INSTALL is set. Actually there is a few bugs working together.

First, we enter a loop that is basically for { sleepCheckInstall }: https://github.com/istio/istio/blob/b7ffd8eae26583f234a8113412db8a1c1aa5022d/cni/pkg/install/install.go#L91-L105

We see sleepCheckInstall always returning quickly, causing the loop to spin.

Inside sleepCheckInstall, watchSAToken spawns a goroutine which only exits once the entire process shuts down. This is bug #1 and why this is presented as a memory leak.

In sleepCheckInstall we have another loop: https://github.com/istio/istio/blob/b7ffd8eae26583f234a8113412db8a1c1aa5022d/cni/pkg/install/install.go#L200-L221. This will exit immediately due to the watchSAToken function call above. This calls readServiceAccountToken and checks curToken != token. Token comes from reading a file (which should always be there). curToken is set during the install call: https://github.com/istio/istio/blob/b7ffd8eae26583f234a8113412db8a1c1aa5022d/cni/pkg/install/install.go#L61 which is skipped due to CNI_ENABLE_INSTALL=false. This is bug #2.

The end result is we have an infinite loop executing very often (basically as fast as we can read a file), each time spawning a goroutine.

# Fix

Drop variables to disable install/re-install, as they are broken and not useful. they were originally added by Google for, IMO, not great reasons. Remove these entirely.
Also removed two other variables that added complexity for no gain; they were only there because we copy+pasted them from Calico 5 years ago.

Fix the watching logic for SA. Just merge it into the main watcher, no need for 2 codepaths to just watch the same files.

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]
This seems like an important bug. Let me know if you'd like any info and I get try this out on an OCP cluster. Any graphs or cpu usage before and after?

**Comment by howardjohn** [comment]
I guess the k8s watcher leak was impacting everyone but that was 1
goroutine per install loop, which is likely 1hr,so not terrible

**Comment by howardjohn** [comment]
cc @jwendell

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
