### PR TITLE
Fix missing gateway services

### PR DESCRIPTION
**Pull request by dddddai**
**Please provide a description of this PR:**
Fixes https://github.com/istio/istio/issues/44439
This bug also impacts ambient mode

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
Please add your analysis.

And one question is it a regression?

**Comment by dddddai** [comment]
If a VS has `exportTo`, we will [skip building the rest of `virtualServiceIndex`](https://github.com/istio/istio/pull/44443/files#diff-a8e332e06b003dfbf58c29f37de893fbb0e45f642200ea3ea2faa9847fc7e1e0L1529)
That code is much older than the indexes I think

Yes it's a regression

**Comment by hzxuzhonghu** [comment]
Since the code is committed in 2020,  why below 1.16 it works

**Comment by dddddai** [comment]
Because we didn't have/use the index to generate gateway services before 1.16

**Comment by hzxuzhonghu** [comment]
Isn't it here
https://github.com/istio/istio/blob/e6124efb9305932433789887c2333a958f5b1ed1/pilot/pkg/model/push_context.go#L748-L791

**Comment by dddddai** [comment]
There's no `destinationsByGateway`

**Comment by hzxuzhonghu** [comment]
please do some more deeper ananlysis, https://github.com/istio/istio/blob/e6124efb9305932433789887c2333a958f5b1ed1/pilot/pkg/networking/core/v1alpha3/cluster.go#L74-L82

It was calling GatewayServices to get services for agateway and then build clusters. So in 1.15, it should be missing clusters as well

**Comment by dddddai** [comment]
> It was calling GatewayServices to get services for agateway and then build clusters. So in 1.15, it should be missing clusters as well

Sorry I don't get it, why would it miss clusters in 1.15? 
In 1.15 `GatewayServices` get services from `VirtualServicesForGateway` and everything works fine
In 1.16+ it gets services from `destinationsByGateway` which may be broken as I [said above](https://github.com/istio/istio/pull/44443#issuecomment-1515639042)

**Comment by hzxuzhonghu** [comment]
>In 1.15 GatewayServices gets services from VirtualServicesForGateway. 

donot we miss vs here?

**Comment by dddddai** [comment]
> > In 1.15 GatewayServices gets services from VirtualServicesForGateway.
> 
> donot we miss vs here?

Could you please explain why? I don't think so

**Comment by hzxuzhonghu** [comment]
1.15, VirtualServicesForGateway aggregate the vses from virtualServiceIndex, and it is set up by the function you are fixing. So i think it skipped other VSes if a exportTo public is set for a VS
```
func (ps *PushContext) VirtualServicesForGateway(proxyNamespace, gateway string) []config.Config {
	res := make([]config.Config, 0, len(ps.virtualServiceIndex.privateByNamespaceAndGateway[proxyNamespace][gateway])+
		len(ps.virtualServiceIndex.exportedToNamespaceByGateway[proxyNamespace][gateway])+
		len(ps.virtualServiceIndex.publicByGateway[gateway]))
	res = append(res, ps.virtualServiceIndex.privateByNamespaceAndGateway[proxyNamespace][gateway]...)
	res = append(res, ps.virtualServiceIndex.exportedToNamespaceByGateway[proxyNamespace][gateway]...)
	res = append(res, ps.virtualServiceIndex.publicByGateway[gateway]...)

	return res
}
```

**Comment by dddddai** [comment]
> So i think it skipped other VSes if a exportTo public is set for a VS

It does not skip anything in 1.15

**Comment by hzxuzhonghu** [comment]
Can we directly talke about this via slack? I donot want to waste more round trips. I could not find you in slack, can you reach to me

**Review by hzxuzhonghu — APPROVED** [review]
Understood, lgtm

**Comment by dddddai** [comment]
..Why is this merged without an approval from release-note maintainers?

**Pull request merged**
