### PR TITLE
Lazy evaluation of `controlPlane` to allow the lazy POD_NAME env var setting

### PR DESCRIPTION
**Pull request by ingwonsong**
This PR proposes the lazy evaluation of `controlPlane`.
By this way, "POD_NAME" being set after the process start can be properly used for "ID" of the control plane.

Change-Id: I31adfcb808d04aef51c42ddaed5b3473db2397a5

### CODE REVIEW

**Comment by ingwonsong** [comment]
Please note that this is a part of efforts for solving the issue in https://github.com/istio/istio/pull/42835 with alternative way.

**Comment by hzxuzhonghu** [comment]
>"POD_NAME" being set after the process start 

What's this case?

**Comment by ingwonsong** [comment]
> > "POD_NAME" being set after the process start
> 
> What's this case?

We are now using a customized entry point instead of `pilot/cmd/pilot-discovery/app/cmd.go` in order to initialize the pilot process externally. In there, POD_NAME need to be generated dynamically because the pilot process is not running in the Kubernetes Cluster. So, we need to set "POD_NAME" after the start of the process, but before the first xDS response.

I understand that it could be seen as too much specialized needs.
But, I think just lazy evaluation of `contronlPlane` is not a big deal.

Can you imagine any issue? or cons?

**Review by hzxuzhonghu — APPROVED** [review]
No cons, just want to know the case clearly. For the case, maybe use ip as an identifier is more appropriate.

**Comment by howardjohn** [comment]
This is not really a reliable change. There is no way to know that you will
actually set POD_NAME before you evaluate the control plane. A refactor can
**easily** break this again.

**Pull request merged**
