### PR TITLE
[Auto Release] Update istio.Version

### PR DESCRIPTION
**Pull request by sebastienvas**
Update istio.Version

### CODE REVIEW

**Comment by sebastienvas** [comment]
@linsun I am not sure I understand this failure from IBM tests. Did you guys updated bazel to be 0.5.3 ?

**Comment by gyliu513** [comment]
@sebastienvas is there a CHANGELOG for this?

**Comment by sebastienvas** [comment]
@yutongz do you have the release note generation working ? Otherwise we might have to ask for the team to come up with one.

**Comment by sebastienvas** [comment]
@gyliu513 are you volunteering to gather release note from people ?

**Comment by gyliu513** [comment]
@sebastienvas I'd love to be the volunteer, but I found that the istio have no CHANGELOG since day one...

Like Kubenretes, we should have the CHANGELOG for each release. For Kubenretes, it has a repo https://github.com/kubernetes/features which will define tasks for each release cycle and release note, perhaps we can follow that way?

How about create a new repo named as `istio/features`, and draft the release note there, everyone can add his own projects there, then we can publish it at https://github.com/istio/istio/CHANGELOG , comments?

BTW: This is kubernetes draft 1.8 release note: https://github.com/kubernetes/features/blob/master/release-1.8/release_notes_draft.md , we can follow this.

**Comment by sebastienvas** [comment]
Thanks for volunteering. I am just noticing that k8s started this process for 1.2. We need a formal process before 1.0, for sure but I believe that using github pages for release, and generated (or manual) release notes would be sufficient for now. Do you know who put this process in place for k8s, such that we understand the requirement behind it and why it was done that way ?

**Comment by gyliu513** [comment]
@sebastienvas please checkout here for detail https://github.com/kubernetes/community/issues/484

Congrats to 0.2.1, but for the release here https://github.com/istio/istio/releases/tag/0.2.1 , I found that we only list features, but did not mention who introduced this and what is the issue number of this feature, it would be great if we also have such info.

**Comment by gyliu513** [comment]
@sebastienvas when we will have official 0.2 release? I was planning to update the istio chart here https://github.com/kubernetes/charts/issues/1909

**Comment by sebastienvas** [comment]
I don't think we know that yet. Not all the features are in, and we still need to run some stabilization phase. Maybe @sakshigoel12 can give you an approximation.

**Comment by ldemailly** [comment]
the release notes have been hastily put together and 0.2.1 isn't an official release yet.
hopefully we will have a real release with more complete notes in a couple of weeks

this being said you can get all the changes using links like:
https://github.com/istio/pilot/compare/0.1.6...0.2.1
https://github.com/istio/mixer/compare/0.1.6...0.2.1
https://github.com/istio/istio/compare/0.1.6...0.2.1
etc

**Comment by gyliu513** [comment]
@sebastienvas @sakshigoel12 @ldemailly thanks all for the comments here, one comment for release, I do hope that we can release agilely with some significant features, such as the transparent injection here https://github.com/istio/pilot/issues/335 , this will impact some other projects, such as helm charts https://github.com/kubernetes/charts/issues/1909 etc, I do hope that we can have a official release which can support this feature soon.

**Pull request merged**
