### PR TITLE
Cherry pick root cert auto rotation

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Introduce a root cert rotator into Citadel that periodically checks root certificate expiration time and rotates expiry root certificate. Root cert rotation uses old root private key.
Support Citadel to sync root cert in local key cert bundle with root cert in istio-ca-secret, which is needed when multiple Citadels are deployed.

#17059

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
It seems that the lint_istio_release-1.3 job is broken.

**Comment by rlenglet** [comment]
Yes the lint test is broken because of `yamllint` in `release-1.3`. I'll merge this PR when it's fixed.

**Comment by JimmyCYJ** [comment]
> I assume this is close to the `release-1.1` fix.
> Please add an item for this PR into the [1.3.5 release note draft](https://github.com/istio/istio/wiki/Release-Note-1.3.5-Draft).

I have updated the release note now. Thanks!
I need to update this PR as there are differences between 1.2 and 1.3, and the current PR is based on cherry-pick PR for release 1.2.
I will remove the hold label once the PR is ready.

**Comment by rlenglet** [comment]
Legit lint failures:
```
security/pkg/k8s/controller/workloadsecret_test.go:354:3: U1000: field `rootCertMatchBundle` is unused (unused)
		rootCertMatchBundle bool
		^
```
```
security/pkg/pki/ca/selfsignedcarootcertrotator.go:152:11: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
level=info msg="[runner] Issues before processing: 9455, after processing: 2"
			} else {
			       ^
```

**Pull request merged**
