### PR TITLE
install: add envoyfilter to prune list

### LINKED ISSUE #48126: Upgrade with spec.values.telemetry.enabled = false will not delete EnvoyFilter stats-filter-xxx
First time, I install with default profile.
Istio add EnvoyFilter `stats-filter-xxx` for me.

Second time, I upgrade with default profile and set values.telemetry.enabled to false.
EnvoyFilter `stats-filter-xxx` has not be deleted.

Do I have to delete it manually? Why is this?

**Affected product area (please put an X in all that apply)**
[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/48126

### CODE REVIEW

**Comment by zirain** [comment]
can we add a test?

**Comment by hanxiaop** [comment]
> can we add a test?

@zirain Added a test for resource pruning.

**Comment by zirain** [comment]
is 1.19 EOL?

**Comment by hanxiaop** [comment]
> is 1.19 EOL?

@zirain Not yet, I think there will be a final patch release.

**Comment by j2gg0s** [comment]
This feature might not be entirely compatible with historical actions.
Somebody may depend on the envoyfilter that hasn't beed deleted?

**Comment by jacob-delgado** [comment]
@keithmattix not familiar with this but I saw you commented on the PR. If you approve then I will. Don't have time to investigate it any further.

**Comment by hanxiaop** [comment]
> This feature might not be entirely compatible with historical actions. Somebody may depend on the envoyfilter that hasn't beed deleted?

@j2gg0s Do you have any specific cases to share? I think we have not depended on envoy filters for some releases, so it would be good to prune them. In the opposite, I think pruning would be better, since it could result in double metrics if switching some configurations to telemetry while the envoy filters are not removed.

**Comment by j2gg0s** [comment]
> > This feature might not be entirely compatible with historical actions. Somebody may depend on the envoyfilter that hasn't beed deleted?
> 
> @j2gg0s Do you have any specific cases to share? I think we have not depended on envoy filters for some releases, so it would be good to prune them. In the opposite, I think pruning would be better, since it could result in double metrics if switching some configurations to telemetry while the envoy filters are not removed.

No, I am just afraid that others might have.
I am also a victim of double metrics.

**Comment by hanxiaop** [comment]
> > > This feature might not be entirely compatible with historical actions. Somebody may depend on the envoyfilter that hasn't beed deleted?
> > 
> > 
> > @j2gg0s Do you have any specific cases to share? I think we have not depended on envoy filters for some releases, so it would be good to prune them. In the opposite, I think pruning would be better, since it could result in double metrics if switching some configurations to telemetry while the envoy filters are not removed.
> 
> No, I am just afraid that others might have. I am also a victim of double metrics.

I think the old installation method may have been deprecated for some releases but not quite sure about the details. @zirain may know more about this.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
