### PR TITLE
A couple cherry-picks from master

### PR DESCRIPTION
**Pull request by hklai**

### CODE REVIEW

**Comment by hklai** [comment]
@douglas-reid simpleTest failed consistently few times in a row (not the same reasons however). Do you see how this PR might have broken it?

**Comment by douglas-reid** [comment]
@hklai i'll take a look now.

**Comment by douglas-reid** [comment]
@hklai I don't believe that this PR could be the cause of those failures. They (mostly) are init errors (with one prometheus test error -- which I think someone sent a PR to fix last week). Is it possible that something on Prow has changed ?

**Comment by hklai** [comment]
@douglas-reid i think i found the culprit and reverted it. https://github.com/istio/istio/pull/11331#issuecomment-458319644

Rerunning the test now.

**Comment by hklai** [comment]
All required tests have passed. Merging.

**Pull request merged**
