### PR TITLE
Add go native race testing for goroutines

### PR DESCRIPTION
**Pull request by sdake**
The race testing currently fails in several places.  I'm not sure
if these races are legitimate, or if the implementation of this
make target is missing something mandatory.

Note I ran make kubelink + deployed Kubernetes with kubeadm prior
to testing.

### CODE REVIEW

**Comment by sdake** [comment]
@ldemailly mind taking a look at this and telling me if I'm doing it wrong?

I get all kinds of positive failures out of this make target - although it seems super trivial from a Makefile perspective.

Cheers
-steve

**Comment by rshriram** [comment]
add a circleci target please..

**Comment by sdake** [comment]
@rshriram sure thing in the morning - headed to family time atm :)

Cheers
-steve

**Comment by sdake** [comment]
related PR that fixes pilot races: https://github.com/istio/istio/pull/2439

**Comment by sdake** [comment]
The failing circle CI test (racetest) is expected and triggered by either bugs in the implementation or test cases.  I think the most reasonable plan forward with this as this is a new test is to merge the test case and distribute the racetest failures among the community so that this CI check can be made functional.

Cheers
-steve

**Comment by sdake** [comment]
@kyessenov why revert #2479?  No explanation was given.

**Comment by kyessenov** [comment]
Just fat fingers I think :) I was asked to revert Gautam PR.

**Comment by sdake** [comment]
@kyessenov fair enough.  This revert isn't currently in master - if it hits master, I'll resubmit.

Cheers
-steve

**Pull request merged**
