### PR TITLE
add ambient test framework flag

### PR DESCRIPTION
**Pull request by pegasas**
**Please provide a description of this PR:**

fixes https://github.com/istio/istio/issues/43508
add ambient test framework flag for quick running integration test.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**
 
* [ ]  Ambient
* [ ]  Configuration Infrastructure
* [x]  Docs
* [ ]  Installation
* [ ]  Networking
* [ ]  Performance and Scalability
* [ ]  Policies and Telemetry
* [ ]  Security
* [ ]  Test and Release
* [x]  User Experience
* [ ]  Developer Infrastructure

### CODE REVIEW

**Comment by pegasas** [comment]
try to resolve https://github.com/istio/istio/issues/43508.
It takes me some time to run integration tests towards k8s.
I think may add here to let people test ambient

**Comment by pegasas** [comment]
try to resolve https://github.com/istio/istio/issues/43508.
It takes me some time to run integration tests towards k8s.
I think may add here to let people test ambient

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
