### PR TITLE
Remove cloudfoundry config controller

### PR DESCRIPTION
**Pull request by Nino-K**
We no longer need to ingest istio configurations through CF config controller since we fully integrated MCP into copilot

### CODE REVIEW

**Comment by Nino-K** [comment]
@rshriram can we merge this?

**Comment by rshriram** [comment]
lint and shellcheck?

**Comment by tangiel** [comment]
I think this PR broke lint: https://circleci.com/gh/istio/istio/202189 as it removes the validator.v2 dep while still being in Gopkg.toml (maybe I'm wrong, I'm new here)

**Comment by rshriram** [comment]
I am not sure if thats the lint error.. the lint error I saw in this PR and I saw it in other PRs as well was
```Solving failure: Could not introduce go.opencensus.io@v0.14.0, as it has a dependency on github.com/prometheus/client_golang with constraint >=0.8.0, which does not allow the currently selected version of v0.9.0-pre1```

**Pull request merged**
