### PR TITLE
Improve xDS logging consistency

### PR DESCRIPTION
**Pull request by howardjohn**
Slightly inconsistencies in the logs make it hard to debug issues

### CODE REVIEW

**Comment by howardjohn** [comment]
@rshriram @duderino ready to merge

**Comment by duderino** [comment]
I have a concern with this one.   Users may have tools/processes that grep through logs looking for certain patterns.  Technically this is a backwards incompatible change.

**Comment by howardjohn** [comment]
Fair point, and this change will help them with doing that in the future. I can move this over to master if we don't want to push to 1.1 @duderino @costinm

**Comment by howardjohn** [comment]
@costinm @duderino want me to move this over to master and close this?

**Comment by howardjohn** [comment]
@duderino general consensus seemed to me that this change ok to make?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/13948 closing this and moving to master

**Pull request closed without merging**
