### PR TITLE
Revert "add ratelimit configmap (#31734)"

### PR DESCRIPTION
**Pull request by zackzhangkai**
This reverts commit 8f1518137d981aa54acfa268be8c5fbfdc60ebd5.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

Should not push to release branch. Fisrtly should push to master, then cherry-pick to release.

### CODE REVIEW

**Comment by zackzhangkai** [comment]
https://github.com/istio/istio/issues/31731

**Review by shamsher31 — APPROVED** [review]

**Comment by zackzhangkai** [comment]
Can anybody do this please? Thanks a lot.

**Pull request merged**
