### PR TITLE
Do not count typeConfigs if it is error.

### PR DESCRIPTION
**Pull request by gyliu513**
This is a follow up PR for https://github.com/istio/istio/pull/6424#r197377947

/cc @esnible @liamawhite

### CODE REVIEW

**Comment by esnible** [comment]
All current implementations of List() return empty []model.Config if they return an err.  It does not hurt to append an empty list.

If someone implemented a List() that returned >0 elements AND an error I believe _istioctl_ should display it.

**Comment by gyliu513** [comment]
Thanks @esnible , got the List() here https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/client.go#L469-L470 , but I still prefer that we should add the check even the List() return empty []model.Config if they return an err , this can make the code more readable.

**Pull request merged**
