### PR TITLE
More fix: only select wles from config cluster

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

follow up #46734

### CODE REVIEW

**Comment by stevenctl** [comment]
Should it be config cluster, or _same_ cluster? 

https://github.com/istio/istio/blob/326ac2e28c9608792a686404d2e09458aaf2db6e/pilot/pkg/features/pilot.go#L502-L503

**Comment by hzxuzhonghu** [comment]
@stevenctl You have a good point, we donot handle any workloadEntry from remote clusters before and after.  I am planing to file an issue to track it.

**Comment by hzxuzhonghu** [comment]
Filed https://github.com/istio/istio/issues/46779, will resolve it later

**Comment by hzxuzhonghu** [comment]
ping @stevenctl another look

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
