### PR TITLE
Add do-not-edit banner to snippets files.

### PR DESCRIPTION
**Pull request by nmittler**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by geeknoid** [comment]
Is there an easy way to inject source information in the banner?

# Created based on test tests/security/tls_test.go in the istio repo

**Comment by howardjohn** [comment]
@nmittler this has lint errors

**Pull request merged**
