### PR TITLE
Update Proxy SHA to latest.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Ping.

**Comment by fpesce** [comment]
@PiotrSikora ping me on hangout/chat next time ;-) I'm more responsive over there, got too many notification on GH. Also there was a merge conflict, I seem to have fixed it.

**Comment by PiotrSikora** [comment]
@fpesce it wasn't *that* urgent to escalate to IM. Regarding the merge conflict - it wasn't there at the time of submission / my ping, so clearly you approved some PRs in the wrong order ;)

**Pull request merged**
