### PR TITLE
WIP: refactoring

### PR DESCRIPTION
**Pull request by ozevren**

### CODE REVIEW

**Comment by ozevren** [comment]
/test e2e-smoke
--

**Comment by douglas-reid** [comment]
whoa. this PR is massive.

14000 new lines of code is too much for any sort of decent review, even if most of it is testing code.

This is fine for a WIP, but I think we have to think about how to stage this across a set of PRs, such that review can be effective (which may be your intent?). See: https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/

**Comment by ozevren** [comment]
This PR is not meant to be reviewed. I don't intend to check all of this at
once. I am planning at least 6-7 separate PRs in there, if not more.

However, I'd like to develop and test all of them together before even
sending out for a review. I assume that is fine?

**Comment by ozevren** [comment]
If this is causing heart palpitations :), I can remove the PR after every
test submit. I was keeping it around as a convenience.

**Pull request closed without merging**
