### PR TITLE
Added identity path prefix variable to meshconfig 

### PR DESCRIPTION
**Pull request by nmnellis**
**Please provide a description of this PR:**

Complies with the Spiffe spec and allows for a path prefix to be prepended to the identity but after the trust domain.

Setting the below meshConfig will yield identites with the format `<trust_domain>/<identity_path_prefix>/sa/<service_account>/ns/<namespace>`

* Example output Spiffe ID
```
URI:spiffe://cluster1.solo.io/development/ns/istio-system/sa/istio-ingressgateway-service-account
```

Mesh config
```yaml
  meshConfig:
    trustDomain: cluster1.solo.io
    identityPathPrefix: development
```

### CODE REVIEW

**Comment by nmnellis** [comment]
This is still a draft because a formal PR needs to be submitted to istio/api for adding the `identityPathPrefix` variable

**Comment by bleggett** [comment]
This would effectively resolve https://github.com/istio/istio/issues/43105

**Comment by nmnellis** [comment]
Depends on https://github.com/istio/api/pull/2830

**Comment by elinesterov** [comment]
@nmnellis did you get any feedback on this? It seems it is just auto-closed :(

**Pull request closed without merging**
