### PR TITLE
Fix waypoint listener order

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
This seems to be a regression introduced by the ambient krt PR. Originally, the workloads were sorted by creation time, but after the rewrite, `SortWorkloadsByCreationTime` has become an unused function.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
Thank you

**Review by howardjohn — COMMENTED** [review]
Why does the order matter here?

**Review by howardjohn — COMMENTED** [review]
I guess from https://github.com/istio/istio/pull/48601 it is so the listener config is deterministic

**Comment by hzxuzhonghu** [comment]
If the order is undetermined, the listener will be reloaded, causing connection drain

**Comment by hanxiaop** [comment]
> I guess from #48601 it is so the listener config is deterministic

Yes, if it's not deterministic, the configs may sometimes be the same and sometimes not when we compare them, for example comparing in proxy-status. All other configs are in a deterministic order.

**Pull request merged**
