### PR TITLE
Fix #22804

### LINKED ISSUE #22804: istioctl 1.5.1 can't create correct pilot plugins configuration
**Bug description**
I used following configure to configure install istio with additional pilot plugins, pass the plugins as slice(list)
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - aa
      - bb
 ```
but always get error when generating manifest 
```
istioctl manifest  generate --verbose --log_output_level=default:debug    -f istioctl-values.yaml 
json: cannot unmarshal string into Go value of type map[string]json.RawMessage
Error: generated config failed semantic validation: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```
seems ask me to pass a map into it, so if I set the the plugins as maps, manifest will be genterated without errors.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - 0: aa
      - 1: bb
 ```
and ther result deployment of istiod is :
```
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --secureGrpcAddr=:15011
        - --trust-domain=cluster.local
        - --plugins=[map[0:aa] map[1:bb]]
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --disable-install-crds=true
```
which is incorrect,  according to [discovery document](https://istio.io/docs/reference/commands/pilot-discovery/)  only accept `<stringSlice> , [authn,authz,health,mixer]`  but not map list  `[map[0:aa] map[1:bb]]`

**Expected behavior**

istioctl generate correct conf

**Steps to reproduce the bug**

```
istioctl manifest  generate --verbose --log_output_level=default:debug    -f istioctl-values.yaml 
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl: 1.5.1

**How was Istio installed?**
not installed yet 

**Environment where bug was observed (cloud vendor, OS, etc)**
runing istioctl on CentOS 7

### PR DESCRIPTION
**Pull request by adiprerepa**
[X] Configuration Infrastructure
I know this was opened previously, but I messed up my git and now no longer have a copy of it. Re-open discussion & clarify here?

Description edit:

This is a fix for #22804 
Previously, you could not pass in a list of plugins as specified in the spec, but you were required to pass in a map: https://istio.io/docs/reference/commands/pilot-discovery/.

This adds the repeated slice type to the value_types proto and makes that the plugins type, hence fixing the bug.

I added some unit tests on the validation of the plugins, verifying that you can actually pass in a list of plugins, and verifies that passing in a map fails.

### CODE REVIEW

**Review by costinm — COMMENTED** [review]
Please add some more text to the description - the bug number should be in the description. 

And few words in the description would help too.

**Comment by adiprerepa** [comment]
@costinm Wrote the description, sorry about that, re-requesting review.

**Comment by sdake** [comment]
@ostromart this PR LGTM. Any objections?

Cheers,
-steve

**Review by richardwxn — APPROVED** [review]

**Comment by richardwxn** [comment]
LGTM, the plugin should be a list

**Pull request merged**
