### PR TITLE
Revert name change of kubernetesenv template

### PR DESCRIPTION
**Pull request by douglas-reid**
Changing the kubernetes env template name broke e2e tests (among other things), as configuration for the kubernetes-related rules are now purged from Mixer (as they no longer validate). This change was originally done as part of a larger set of changes, and its impact was missed.

This PR restores all kubernetes adapter related configuration to a working state. With any luck, it also will fix the e2e tests.

### CODE REVIEW

**Comment by mandarjog** [comment]
@douglas-reid Can add to the PR why this renaming is necessary :-)

**Comment by douglas-reid** [comment]
@mandarjog done.

**Comment by mandarjog** [comment]
I am going to run e2es tests on this before merge. Until then
/hold

**Comment by douglas-reid** [comment]
sgtm. thanks.

**Comment by mandarjog** [comment]
My e2e test failed, investigating.
@douglas-reid can you run one too?

Just export TAG=your sha
And make e2e

**Comment by douglas-reid** [comment]
@mandarjog when i'm next on a linux box, I will try running the e2e. It is possible that TestRateLimit is broken for other reasons.

This change is definitely needed to make the `kubenetesenv` adapter work again with the existing configs, however.

**Pull request merged**
