### PR TITLE
pilot-agent: add a flag to disable internal telemetry

### PR DESCRIPTION
**Pull request by kyessenov**
Enabled by default, but allows to turn off telemetry.

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by douglas-reid** [comment]
/lgtm

Thanks for tackling this so quickly!

**Comment by costinm** [comment]
Can we have it off by default ?

**Comment by kyessenov** [comment]
Yes, if there is a reason for that. So far I have not heard about control plane load exceeding the load of the data plane.

**Comment by douglas-reid** [comment]
@costinm i'm inclined to leave it on by default (given a number of use cases) unless/until it proves to be entirely detrimental.

**Comment by costinm** [comment]
Can you at least make this configurable in the helm template - so users can
easily turn it off.
We no longer expect them to edit templates.

**Comment by costinm** [comment]
Also: a-la-carte usually means opt-in - if user doesn't select graphana or
prometheus - or telemetry - what is the value of having this on.

**Comment by kyessenov** [comment]
There is a difference between application opt in and control plane opt in
options. We use mTLS between istio components even if the application does
not. Same applies to telemetry. It's fine to have telemetry always on since
Prometheus is almost always there.

**Comment by douglas-reid** [comment]
@costinm Mixer is on by default.

**Pull request merged**
