### PR TITLE
fix mtls dest rule namespace when config root namespace is enabled

### PR DESCRIPTION
**Pull request by rshriram**
cc @uk000

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by rshriram** [comment]
@morvencao / @sdake how do I fix this error:
```error: the namespace from the provided object "default" does not match the namespace "istio-system". You must pass '--namespace=default' to perform this operation.
uration\" created\nconfigmap \"prometheus\" created\nconfigmap \"istio\" created\nconfigmap \"istio-sidecar-injector\" created\nserviceaccount \"istio-galley-service-account\" created\nserviceaccount \"istio-egressgateway-service-account\" created\nserviceaccount \"istio-ingressgateway-service-account\" created\nserviceaccount \"istio-mixer-service-account\" created\nserviceaccount \"istio-pilot-service-account\" created\nserviceaccount \"prometheus\" created\nserviceaccount \"istio-cleanup-secrets-service-account\" created\nclusterrole \"istio-cleanup-secrets-istio-system\" created\nclusterrolebinding \"istio-cleanup-secrets-istio-system\" created\njob \"istio-cleanup-secrets-7d0396dd4a64f2189722574ffc5c9a75\" created\nserviceaccount \"istio-citadel-service-account\" created\nserviceaccount \"istio-sidecar-injector-service-account\" created\nserviceaccount \"istio-multi\" created\nclusterrole \"istio-galley-istio-system\" created\nclusterrole \"istio-egressgateway-istio-system\" created\nclusterrole \"istio-ingressgateway-istio-system\" created\nclusterrole \"istio-mixer-istio-system\" created\nclusterrole \"istio-pilot-istio-system\" created\nclusterrole \"prometheus-istio-system\" created\nclusterrole \"istio-citadel-istio-system\" created\nclusterrole \"istio-sidecar-injector-istio-system\" created\nclusterrole \"istio-reader\" created\nclusterrolebinding \"istio-galley-admin-role-binding-istio-system\" created\nclusterrolebinding \"istio-egressgateway-istio-system\" created\nclusterrolebinding \"istio-ingressgateway-istio-system\" created\nclusterrolebinding \"istio-mixer-admin-role-binding-istio-system\" created\nclusterrolebinding \"istio-pilot-istio-system\" created\nclusterrolebinding \"prometheus-istio-system\" created\nclusterrolebinding \"istio-citadel-istio-system\" created\nclusterrolebinding \"istio-sidecar-injector-admin-role-binding-istio-system\" created\nclusterrolebinding \"istio-multi\" created\nrole \"istio-ingressgateway-sds\" created\nrolebinding \"istio-ingressgateway-sds\" created\nservice \"istio-galley\" created\nservice \"istio-egressgateway\" created\nservice \"istio-ingressgateway\" created\nservice \"istio-policy\" created\nservice \"istio-telemetry\" created\nservice \"istio-pilot\" created\nservice \"prometheus\" created\nservice \"istio-citadel\" created\nservice \"istio-sidecar-injector\" created\ndeployment \"istio-galley\" created\ndeployment \"istio-egressgateway\" created\ndeployment \"istio-ingressgateway\" created\ndeployment \"istio-policy\" created\ndeployment \"istio-telemetry\" created\ndeployment \"istio-pilot\" created\ndeployment \"prometheus\" created\ndeployment \"istio-citadel\" created\ndeployment \"istio-sidecar-injector\" created\nmeshpolicy \"default\" created\ndestinationrule \"default\" created\nhorizontalpodautoscaler \"istio-egressgateway\" created\nhorizontalpodautoscaler \"istio-ingressgateway\" created\nhorizontalpodautoscaler \"istio-telemetry\" created\nhorizontalpodautoscaler \"istio-pilot\" created\nmutatingwebhookconfiguration \"istio-sidecar-injector\" created\npoddisruptionbudget \"istio-galley\" created\npoddisruptionbudget \"istio-egressgateway\" created\npoddisruptionbudget \"istio-ingressgateway\" created\npoddisruptionbudget \"istio-policy\" created\npoddisruptionbudget \"istio-telemetry\" created\npoddisruptionbudget \"istio-pilot\" created\nattributemanifest \"istioproxy\" created\nattributemanifest \"kubernetes\" created\nhandler \"stdio\" created\nlogentry \"accesslog\" created\nlogentry \"tcpaccesslog\" created\nrule \"stdio\" created\nrule \"stdiotcp\" created\nmetric \"requestcount\" created\nmetric \"requestduration\" created\nmetric \"requestsize\" created\nmetric \"responsesize\" created\nmetric \"tcpbytesent\" created\nmetric \"tcpbytereceived\" created\nmetric \"tcpconnectionsopened\" created\nmetric \"tcpconnectionsclosed\" created\nhandler \"prometheus\" created\nrule \"promhttp\" created\nrule \"promtcp\" created\nrule \"promtcpconnectionopen\" created\nrule \"promtcpconnectionclosed\" created\nhandler \"kubernetesenv\" created\nrul
e \"kubeattrgenrulerule\" created\nrule \"tcpkubeattrgenrulerule\" created\nkubernetes \"attributes\" created\ndestinationrule \"istio-policy\" created\ndestinationrule \"istio-telemetry\" created\nerror: the namespace from the provided object \"default\" does not match the namespace \"istio-system\". You must pass '--namespace=default' to perform this operation.\n" exit status 1```

This Pr is important. If people enable the config root namespace, lots of things will break in helm install or in istio as such.. So lets get this in ASAP, with whatever fixes needed. 

cc @duderino

**Comment by morvencao** [comment]
@rshriram It should caused by that the `destinationrule` namespace is hard coded as `default`, while the chart is deployed  with `--namespace=istio-system`

**Comment by rshriram** [comment]
Yes but this rule needs to be in default namespace..

**Comment by sdake** [comment]
An unmanaged object is the only answer I can think of.  @morvencao is doing work in this area around upgrade and MTLS at the moment.

Cheers
-steve

**Pull request closed without merging**
