### PR TITLE
ServiceEntries with non FQDN hosts were silently failing, 

### PR DESCRIPTION
**Pull request by GregHanson**
rules accepted by validation, ignored by pilot

Resolves: https://github.com/istio/istio/issues/13436

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
But we do not enforce hostname must contains `.` for ServiceEntry.

**Comment by GregHanson** [comment]
@hzxuzhonghu, yes the current validation logic allows shortnames through for ServiceEntries, but pilot is currently not pushing any configs for ServiceEntries with a shortname in `hosts` - and is barely acknowledging that it was performing any such filtering

**Comment by hzxuzhonghu** [comment]
Have a look at #13447, which allows short hostname, like google, github.

**Comment by GregHanson** [comment]
closing in favor of #13447 as the ServiceEntry now appears in config_dump's of sidecar

**Pull request closed without merging**
