### PR TITLE
[1.3]Add perf benchmark script entry

### PR DESCRIPTION
**Pull request by richardwxn**
Cherry pick for https://github.com/istio/istio/pull/17007. Need it for performance benchmark for different releases.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by richardwxn** [comment]
@mandarjog

**Comment by mandarjog** [comment]
@rlenglet this is a cherry pick to start perf testing 1.3 continuously.
Does not touch product code.

**Comment by rlenglet** [comment]
We'll get this into 1.3.3.

**Comment by rlenglet** [comment]
@richardwxn Please an item for this PR into the [1.3.3 release note draft](https://github.com/istio/istio/wiki/Release-Note-1.3.3-Draft).

**Comment by richardwxn** [comment]
@rlenglet done

**Pull request merged**
