### PR TITLE
Fix deployment on liveness sample

### PR DESCRIPTION
**Pull request by howardjohn**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rcaballeromx** [comment]
@howardjohn What documents in istio.io are impacted by this change?

**Comment by howardjohn** [comment]
@rcaballeromx https://preliminary.istio.io/docs/ops/app-health-check/. It looks like on the page we inline one of the `Deployment`s and it is outdated as well

**Comment by fpesce** [comment]
@rcaballeromx / @geeknoid can we get an approval on this one ?

**Comment by howardjohn** [comment]
@istio/wg-docs-maintainers ping

**Pull request merged**
