### PR TITLE
Fix markdown files to pass linter (single empty line) at tail

### PR DESCRIPTION
**Pull request by ericvn**
**Please provide a description of this PR:**

A newer version of the markdown linter checks for a single empty line at the end of markdown files.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by frankbu — APPROVED** [review]

**Comment by kyessenov** [comment]
Needs cherry pick to experimental branches.

**Comment by ericvn** [comment]
I'll check, but right now the experimental branches don't move up to the new build-images so might not be needed right away. Although, at one time I did want them to move up as the other branches.

**Comment by howardjohn** [comment]
I think ambient is on same image as master

**Comment by ericvn** [comment]
ie. if I run `make lint-markdown` on the `experimental-ambient` branch is uses a older build-image so the test won't fail like it does on `master`. Same as the older release-branches. When we move an experimental branch to the current common-files, it is not uncommon for there to be a number of cherry-picks required to make things work.

**Comment by ericvn** [comment]
> I think ambient is on same image as master

It's not since I just ran the command locally (after pulling the latest) and it required an older build image. I will create a PR to move up to the latest build image and update the various md files.

**Comment by howardjohn** [comment]
the CI does though

**Comment by ericvn** [comment]
OK. Why I had opened a PR earlier to try and keep those branches up to date so local builds and pipeline jobs would stay in sync. Didn't merge and I ended up closing. 

I did create and have merged the PR for the `experimental-ambient` branch. The `experimental-dual-stack` branch hasn't had a commit since last September and needs a lot more than these lint fixes to make in pass the current CI. A bunch of linter changes across the board as well, Go 1.20 changes, etc. As there hasn't been a commit in a while, I'm not sure of the necessity to try and get it all back up to date.

**Pull request merged**
