### PR TITLE
mixer: switch to simplified config model

### PR DESCRIPTION
**Pull request by kyessenov**
Change tests and sample configs to use simplified config model.
Will follow up with removal of 50 CRDs later.

- update runtime config processor to load static instances
- remove deprecated `mixs crd` command

/assign @douglas-reid 
/assign @geeknoid 

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
It should be noted that 1.1 did not ship with a capability to use Instance CR for static templates.
Therefore, we cannot immediately remove support for old style CRDs. We can switch the default and installation options but the config pipeline for the old style must stay for one release.

**Comment by kyessenov** [comment]
Gentle ping :)

**Comment by douglas-reid** [comment]
/lgtm

Keep in mind, that with this change, we will need to update all the website docs, including: https://istio.io/help/ops/telemetry/missing-metrics/#verify-mixer-metric-instances-configuration-exists.

**Comment by kyessenov** [comment]
Sure, I'll file an issue to keep track of documentation changes.

**Comment by geeknoid** [comment]
Per TOC, we decided we want this in for 1.2

I opened https://github.com/istio/istio.io/issues/3851 to track doc update.

/approve

**Pull request merged**
