### PR TITLE
Move this as per TOC

### PR DESCRIPTION
**Pull request by bleggett**
**Please provide a description of this PR:**

This originally lived in `charts` with the other charts (and would be published to the same registry path as the other charts), as [per TOC](https://github.com/istio/istio.io/pull/15279#issuecomment-2220493410) we want to create a `samples` subpath for this.

`sample-charts` in the repo seems obvious enough given we have an existing `manifests/charts` split.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
interesting, I had initially thought under the top level samples/ but now I see the appeal of this as well. 

If we are going to have a bunch of samples for various gitops deployment models, under samples/ makes sense. If it's just this, lumping it with the rest of helm charts probably makes sense. 

I suppose we can just move it later if needed

**Comment by bleggett** [comment]
> interesting, I had initially thought under the top level samples/ but now I see the appeal of this as well.

Mostly, it's from a perspective of "release builder just publishes all the charts in $DIR" - which is a nice simple pattern I'd rather retain, and for that to work, you have to have the same kind of thing (chart) in the $DIR.

I am open to the name being different, just need a way to clearly indicate via path that it's sample _charts_ versus sample something-else.

**Comment by bleggett** [comment]
Interesting. I am not sure why simply moving this chart _out_ would affect RB.

**Comment by bleggett** [comment]
Needs https://github.com/istio/release-builder/pull/1899

**Pull request merged**
