### PR TITLE
cherrypick 29752 for the istio operator permissions.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.

cherrypick istio-operator permission of https://github.com/istio/istio/pull/29752 to release-1.8
resolve: https://github.com/istio/istio/issues/30106

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by morvencao** [comment]
kindly ping @GregHanson @bianpengyuan

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
