### PR TITLE
Disable istio-ingressgateway in ambient profile

### LINKED ISSUE #44030: Remove Istio Ingress Gateway from Ambient Profile
**Describe the feature request**
Since Istio intends on making [Kubernetes Gateway API](https://gateway-api.sigs.k8s.io/) the default API for traffic management in the [future](https://istio.io/latest/blog/2022/gateway-api-beta/), the ambient profile should use a [Kubernetes Gateway](https://gateway-api.sigs.k8s.io/api-types/gateway/) instead of Istio ingress gateways. A Kubernetes Gateway can be created by the ambient profile that exposes the same protocols and ports as an Istio ingress gateway. Users would then create an HTTPRoute to route traffic through the Gateway to one or more Ambient mesh services.
 
**Describe alternatives you've considered**
- Continue using Istio classic APIs for the ambient profile. Since Ambient is experimental, this is a great time to promote the use of Kubernetes Gateway API for traffic management.
- Have the ambient profile create both an Istio ingress gateway and a Kubernetes Gateway. Having two different Gateways may cause confusion with users. Additionally, most users will continue to use the Istio ingress gateway due to familiarity.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Current profile:
```
istioctl install --set profile=ambient
This will install the Istio 1.18.0 ambient profile with ["Istio core" "Istiod" "CNI" "Ztunnel" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
...
```

Proposed profile:
```
istioctl install --set profile=ambient
This will install the Istio 1.18.0 ambient profile with ["Istio core" "Istiod" "CNI" "Ztunnel" "Kubernetes gateway"] components into the cluster. Proceed? (y/N) y
...
```

A new type, i.e. KubeGatewaySpec, will need to be defined similar to [GatewaySpec](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec) and added as field `kubernetesGateways` to [IstioComponentSetSpec](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioComponentSetSpec) .

### PR DESCRIPTION
**Pull request by frankbu**
**Please provide a description of this PR:**

Fixes: #44030

Adding DNM until the getting started with ambient doc is updated.

### CODE REVIEW

**Review by danehans — APPROVED** [review]
/lgtm

**Review by ericvn — APPROVED** [review]
LGTM

**Review by linsun — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
