### PR TITLE
Update proxy's SHA to latest.

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Fixes https://github.com/istio/proxy/issues/1190#event-1510612332

### CODE REVIEW

**Comment by nmittler** [comment]
I think this is right now.  @mandarjog do you want to take a look as well?

**Comment by ldemailly** [comment]
the failures are interesting... any idea?

**Comment by JimmyCYJ** [comment]
For the istio-presubmit.sh failures, by reading the error logs 
"error when do request: Post http://localhost:9090/echo: dial tcp [::1]:9090: connect: connection refused"

I suspect when the test begins, the port 9090 at Envoy is not ready for new TCP connections yet.
cc: @qiwzhang

**Comment by qiwzhang** [comment]
I think https://github.com/istio/istio/pull/4292 is newer than this one. 

If so, do we still need this PR?

**Comment by ldemailly** [comment]
#4292 is newer, it's interesting though that neither are passing any tests ?

**Comment by JimmyCYJ** [comment]
I will close this one, thanks. The sample1 test still fails, I will take a look.

**Pull request closed without merging**
