### PR TITLE
Added zipkin endpoint to istio remote chart.

### PR DESCRIPTION
**Pull request by gyliu513**
This can make sure Jaeger can also trace services in remote cluster.

/cc @sdake @sbezverk @costinm

### CODE REVIEW

**Comment by gyliu513** [comment]
This can make sure the remote service can be traced by Jaeger.

image

**Comment by costinm** [comment]
Note that zipkin is not protected by TLS - it is ok to expose pilot for example in a gateway/load balancer, because we do use MTLS. Until zipkin is secured in a similar way - I don't think this is a viable prod deployment.

**Comment by gyliu513** [comment]
@costinm zipin exposed here is not lb, but kubernetes endpoint of the service.

**Comment by morvencao** [comment]
@gyliu513 If this gets merged, we also need to update doc: https://istio.io/docs/setup/kubernetes/multicluster-install/

**Comment by hklai** [comment]
Why this is going to release-0.8 instead of master?

**Comment by gyliu513** [comment]
@hklai done at https://github.com/istio/istio/pull/6127

**Pull request closed without merging**
