### PR TITLE
fix pilot ads goroutine leak and memory leak

### PR DESCRIPTION
**Pull request by pxzero**
fix pilot ads goroutine leak and memory  leak

### CODE REVIEW

**Comment by pxzero** [comment]
> I signed it!

**Comment by hzxuzhonghu** [comment]
@pxzero We canot stop the receive routine,  which is based on a long-running grpc connection.

**Comment by hzxuzhonghu** [comment]
Oh, I see. This is reasonable.  But should do this when `StreamAggregatedResources` exit.
Not only here https://github.com/istio/istio/pull/10823/files#diff-14f4a8a239bf5ba82053cf6606daace5R622
So a  `defer close(channel)`  can improve this. 

BTW should make this for release-1.1 branch.

**Comment by hzxuzhonghu** [comment]
I am not expert on gRPC, so I have a question what's the behavior when `StreamAggregatedResources` returns with error or nil?
I look into gRPC code, I think the grpc connection will not be influenced. 

Will

**Comment by hzxuzhonghu** [comment]
cc @costinm you must be familiar with gRPC.

**Comment by pxzero** [comment]
thanks for reply. I have show some detail of goroutine pprof file in the refer issue . 
In our case , when StreamAggregatedResources exit , the receive thread still block at 
`
reqChannel <- req
`
so what we do is to make sure receive thread exit before StreamAggregatedResources exit . 
Yes you are right , defer close is a better way

**Comment by hzxuzhonghu** [comment]
@pxzero  Would you open a new pr to release-1.1 branch?

**Comment by pxzero** [comment]
> @pxzero Would you open a new pr to release-1.1 branch?

OK , will

**Comment by pxzero** [comment]
I have commit a new PR to release-1.1 , this PR should be closed
please check the new PR : https://github.com/istio/istio/pull/10862#event-2065514453
thanks

**Pull request closed without merging**
