### PR TITLE
add ratings service unavailable message to bookinfo app

### PR DESCRIPTION
**Pull request by jasonwzm**
as a fix of issue https://github.com/istio/istio/issues/1034

showing rating service unavailable when rating service is being blocked, rate limited, etc.
screen shot 2017-12-30 at 4 51 10 pm

### CODE REVIEW

**Comment by ldemailly** [comment]
/lgtm
thx!

**Comment by rshriram** [comment]
@jasonwzm did you update the official bookinfo images? Any update to the HTML files requires an update to the official bookinfo images. They are not build automatically (as we update them very rarely).

If you update the official bookinfo images (bumping up the versions), you have to update all the example files to use the newer docker images as well.

**Comment by jasonwzm** [comment]
@rshriram Thanks for the reminder. I will do that today.

**Comment by jasonwzm** [comment]
@rshriram can I get write access to istio dockerhub? jasonwzm is the username

**Pull request merged**
