### PR TITLE
fix operator resources prune issue.

### LINKED ISSUE #23280: in-cluster doesn't prune all resources after iop instance is deleted
**Bug description**

This is different from https://github.com/istio/istio/issues/23141

After iop instance is deleted, the istio resources created by in-cluster controller are just clean the **istiod**, others are still there:

```
# kubectl -n istio-system delete iop example-istiocontrolplane
istiooperator.install.istio.io "example-istiocontrolplane" deleted
# kubectl -n istio-system get pod
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-74dc798895-dd57k                1/1     Running   0          12m
istio-egressgateway-6c86b9948f-45qps    1/1     Running   0          12m
istio-ingressgateway-7dbdd7d5c5-bs2xw   1/1     Running   0          12m
istio-tracing-8584b4d7f9-zkf8z          1/1     Running   0          12m
kiali-696bb665-cfcfz                    1/1     Running   0          12m
prometheus-7b9bb5f758-v4nkr             2/2     Running   0          12m
```
After checking the code, I found that the prune cycle is using iop without merged with profile.
See: https://github.com/istio/istio/blob/master/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L190

The iop spec should be merged with profile before create the helm reconciler.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/23280

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ostromart** [comment]
there was a considerable cleanup here - could you please merge master?

**Comment by morvencao** [comment]
Still see this in master, all other components are not pruned except istiod:
```
# kubectl -n istio-system get pod
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-74dc798895-qlzgc                1/1     Running   0          6m30s
istio-egressgateway-b879d4d6b-wr5pv     1/1     Running   0          6m36s
istio-ingressgateway-5df97bd48d-bmzzm   1/1     Running   0          6m36s
istio-tracing-8584b4d7f9-j4lwz          1/1     Running   0          6m30s
kiali-696bb665-5wvgb                    1/1     Running   0          6m30s
prometheus-7967495d45-v4kht             2/2     Running   0          6m30s
```

**Review by sdake — APPROVED** [review]
LGTM for master - unclear if this should be backported for 1.6.

@morvencao if you believe a backport is necessary, please explain why in a comment for the release managers and set the backport flag.

Cheers
-steve

**Comment by morvencao** [comment]
@sdake I believe this should be backported for 1.6, because the resources can't cleaned up after iop instance is deleted.

**Comment by jacob-delgado** [comment]
cc @brian-avery @irisdingbj @morvencao 

The cherry-pick failed and does not have a manual cherry picked PR for 1.6.

**Pull request merged**
