### PR TITLE
remove dead non functional code from pilot/pkg/networking

### PR DESCRIPTION
**Pull request by rshriram**
This code was used to aid V2 transition.. its no longer needed. This is not used by any test. Its not functional either.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by rshriram** [comment]
lets wait until other PRs get in. The code here is no longer functional.

**Comment by kyessenov** [comment]
Asking again: have the tests been updated to v2?

**Comment by kyessenov** [comment]
this is blocking PRs -- the removed code is not linter-correct!

**Pull request merged**
