### PR TITLE
Remove unnecessary webhook script

### PR DESCRIPTION
**Pull request by idoshamun**
This script fails in the last line due to the following validation error:
`error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`
I changed it to instantly create the secret in the given namespace instead of piping the result of the `dry-run`.

Follow up of #5473 

**Update:**
It turns out that this script is irrelevant in 0.8, so it needs to be deleted

### CODE REVIEW

**Comment by yusuoh** [comment]
This script is no longer in use. We should try to delete it.

**Comment by idoshamun** [comment]
@yusuoh documentation states to use this script to install the webhook for the sidecar injection. I couldn't follow it, this is why I suggests this fix

**Comment by yusuoh** [comment]
@andraxylia doshamun The documentation for webhook installation is already updated for 0.8.  See

https://preliminary.istio.io/docs/setup/kubernetes/sidecar-injection.html#installing-the-webhook

**Comment by hklai** [comment]
@yusuoh If the script does not work as expected, we should fix it (i.e. merge this since @andraxylia 
 already approved) ASAP.

If the script is indeed no longer needed, we should delete it and clean up the doc on istio.io.

**Comment by hklai** [comment]
SGTM

@idoshamun are you going to update this PR and delete the script instead?

**Comment by idoshamun** [comment]
Yap, as soon as I can

**Comment by andraxylia** [comment]
sounds good to me.

**Comment by idoshamun** [comment]
@hklai @andraxylia PR is ready :)

**Pull request merged**
