### PR TITLE
Get rid of demo-auth

### LINKED ISSUE #16774: Helm file values-istio-demo.yaml is wrong
**Bug description**

The `install/kubernetes/helm/istio/values-istio-demo.yaml` available in the released package defines the "global" key twice. There is one definition at the top:

```yaml
global:
  proxy:
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false
```

and one at the bottom:

```yaml
# @include <values-istio-demo-common.yaml>
#
global:
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false
```

When rendering with:

`helm template install/kubernetes/helm/istio --name istio --namespace istio-system -f install/kubernetes/helm/istio/values-istio-demo.yaml`

definitions are not merged, but the second one completely overwrites the first one. So, the rendered template is not suitable for small envs.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Perhaps, the `values-istio-demo.yaml` file provided in the released package should define `global` only once, with merged values.

**Steps to reproduce the bug**
It's all in the bug description :)

FYI: I discovered this because I was trying to setup a multi-cluster env using instructions in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/. But I wanted a _demo_ profile _plus_ multi-cluster. So, I was trying:

```bash
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
    -f install/kubernetes/helm/istio/values-istio-demo.yaml \
    -f install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml
```

which was generating a yaml not suitable for small envs (thus pods not starting because insufficient cpu).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.2.4
Helm: 2.14.3

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

Fixed https://github.com/istio/istio/issues/16774

I have tested this case, if in a yaml file with duplicated key, the keys that appears later overrides the keys that have appeared before. you can take the `accessLogFile: "/dev/stdout"` in `values-istio-demo.yaml` in release package as an example, it will not take effect by running 
```
helm template . -f values-istio-demo.yaml | grep accessLogFile -A 1 -m 2
    # Set accessLogFile to empty string to disable access log.
    accessLogFile: ""
```

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
would it be easier just to have one values-demo.yaml and then for the auth one do `--set global.controlPlaneSecurityEnabled=true --set global.mtls.enabled=true`? Its only two values anyways

Seems a bit simpler and then we don't need to randomly pull in a dependency in the middle of the release process

**Comment by clyang82** [comment]
> would it be easier just to have one values-demo.yaml and then for the auth one do `--set global.controlPlaneSecurityEnabled=true --set global.mtls.enabled=true`? Its only two values anyways
> 
> Seems a bit simpler and then we don't need to randomly pull in a dependency in the middle of the release process

I am OK with your suggestion that it is easier to maintain by developer. but consider how easy to use it, I think have 2 files with different name is more intuitive. And there are many places reference it in document. WDYT?

**Comment by howardjohn** [comment]
We don't ship the demo values we just ship the rendered demo yamls, right? So how we generate them is an implementation detail? That's what I thought anyways

**Comment by clyang82** [comment]
> We don't ship the demo values we just ship the rendered demo yamls, right? So how we generate them is an implementation detail? That's what I thought anyways

we shipped the demo values
```
chunlins-mbp:istio clyang$ ll
total 136
-rw-r--r--   1 clyang  wheel   346B Sep 10 10:13 Chart.yaml
-rw-r--r--   1 clyang  wheel   4.5K Sep 10 10:13 README.md
drwxr-xr-x  15 clyang  wheel   480B Sep 10 09:44 charts
drwxr-xr-x   8 clyang  wheel   256B Sep 10 10:13 example-values
drwxr-xr-x   3 clyang  wheel    96B Sep 10 10:13 files
-rw-r--r--   1 clyang  wheel   1.0K Sep 10 10:13 requirements.yaml
drwxr-xr-x  14 clyang  wheel   448B Sep 10 10:13 templates
-rw-r--r--   1 clyang  wheel   2.0K Sep 10 10:13 values-istio-demo-auth.yaml
-rw-r--r--   1 clyang  wheel   2.0K Sep 12 14:13 values-istio-demo.yaml
-rw-r--r--   1 clyang  wheel   904B Sep 10 10:13 values-istio-minimal.yaml
-rw-r--r--   1 clyang  wheel   702B Sep 10 10:13 values-istio-remote.yaml
-rw-r--r--   1 clyang  wheel   442B Sep 10 10:13 values-istio-sds-auth-control-plane-auth-disabled.yaml
-rw-r--r--   1 clyang  wheel   440B Sep 10 10:13 values-istio-sds-auth.yaml
-rw-r--r--   1 clyang  wheel   149B Sep 12 13:54 values-istio-test.yaml
-rw-r--r--   1 clyang  wheel    21K Sep 10 10:13 values.yaml
chunlins-mbp:istio clyang$ pwd
/tmp/istio-1.3.0-rc.3/install/kubernetes/helm/istio
```

**Comment by howardjohn** [comment]
it's not documented though so I don't think we need to https://istio.io/docs/setup/additional-setup/config-profiles/ - we only have the demo one which I think is good

The only reason I am pushing back is I don't want to add another dependency (yq) to our release process. I would rather just have some duplication or remove the values auth file. What do you think?

**Comment by clyang82** [comment]
> it's not documented though so I don't think we need to https://istio.io/docs/setup/additional-setup/config-profiles/ - we only have the demo one which I think is good
> 
> The only reason I am pushing back is I don't want to add another dependency (yq) to our release process. I would rather just have some duplication or remove the values auth file. What do you think?

the demo and demo-auth are using in https://istio.io/docs/setup/install/helm/ so that it seems we cannot remove the file.
The demo-common file is identified by @linsun `please only put common configuration for the demo profiles here.` @linsun Any comments here? Thanks.

**Comment by howardjohn** [comment]
hmm.. the profiles on that page should match up with the ones on the page I
linked, as a follow-up we should probably reconcile that

**Comment by linsun** [comment]
My personal preference is to get rid of demo-auth because it can be easily generated using a few params `--set global.controlPlaneSecurityEnabled=true --set global.mtls.enabled=true`.  Having an additional profile for auth is confusing imho.   It confused users a lot when we have a profile for non-auth and another profile for auth, and we do that for each set of our profiles except we only generate yaml files for demo profile.  I think we have agreed either in environment WG or TOC that for new installer we would only ship demo profile for non-auth.

**Comment by clyang82** [comment]
Thanks @howardjohn & @linsun for your comments. Let me use this PR to address remove demo-auth and have another document PR to reconcile it.

**Comment by howardjohn** [comment]
Thanks! I think that will be a big improvement

**Comment by clyang82** [comment]
@howardjohn @linsun I have removed the demo-auth and just keep demo profile. when I did update the document, I found that security part  strongly depends on the demo-auth. e.g.: https://istio.io/docs/tasks/security/health-check/  `strict mutual TLS mode`. if we remove the demo-auth, we have to rely on the `helm template or helm install` to install with mtls enabled. is it acceptable?

**Review by howardjohn — APPROVED** [review]

**Comment by rlenglet** [comment]
This PR shouldn't have been merged before fixing all the references to the deleted files in the docs.

**Comment by pitlv2109** [comment]
Second to @rlenglet's comment. Can you also update relevant docs and files, such as this one https://preliminary.istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template?

**Pull request merged**
