### PR TITLE
Adding Cloudwatchlogs support in Mixer Cloudwatch adapter

### PR DESCRIPTION
**Pull request by karanvasnani**
Adding support in the existing Mixer CloudWatch adapter to also send LogEntries to AWS CloudWatchLogs platform. It is an extension to the existing adapter which only sends metrics to AWS CloudWatch.

### CODE REVIEW

**Comment by douglas-reid** [comment]
I think I've reviewed this PR in all of its various previous forms.

@karanvasnani can you kick the circleci test ?

/lgtm

**Comment by karanvasnani** [comment]
@douglas-reid So looks like the build is failing because of this change https://github.com/istio/istio/commit/f883fbf8e01db4767bfaeab128b87976123b1df6#diff-5ba6e3676f5209259a1addc23e3617a6R12 where `destination_service: destination.labels["service"] | "unknown"` was changed to `destination_service: destination.service.host | "unknown"` in `cloudwatch.yaml` but the corresponding attribute `destination.service.host` doesn't exist in `attribute.yaml`

**Comment by douglas-reid** [comment]
I'm a little confused, as that change was made months ago and builds have been passing since then. I also see `destination.service.host` in the testconfig [attributes.yaml](https://github.com/istio/istio/blob/master/mixer/testdata/config/attributes.yaml#L160). What am I missing?

**Comment by karanvasnani** [comment]
@douglas-reid The [attributes.yaml](https://github.com/istio/istio/blob/master/mixer/adapter/cloudwatch/operatorconfig/attributes.yaml#L115) in the cloudwatch operator config has `destination.service` as attribute which looks to have been deprecated and doesn't have all the attributes that are there in the `testdata/attributes.yaml`.

**Pull request closed without merging**
