### PR TITLE
Embed integration testdata

### PR DESCRIPTION
**Pull request by PhilipGough**
* Add go generate command to embed test fixures required for adapter integration test framework
* Update adapter integration test framework to use embedded assets

@kyessenov - cherry pick of #14990 and re-generate for 1.1.x

### CODE REVIEW

**Comment by duderino** [comment]
@PhilipGough @kyessenov 1.1 is a venerable branch that likes to yell at kids and tell them to get off its lawn.  Why do you want this in 1.1?

**Comment by kyessenov** [comment]
This doesn't need to be in 1.1. I think 1.2 is mostly interface-compatible, so the adapters can point to 1.2 instead.

**Comment by PhilipGough** [comment]
@kyessenov, @duderino - it doesnt need to be, but our adapter will depend on 1.1 for GA and we would *like* to use go modules. However its not a blocker or anything so feel free to close it if required.

**Pull request closed without merging**
