### PR TITLE
Make use istio sets in all places

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Fix https://github.com/istio/istio/issues/45537

### CODE REVIEW

**Review by hanxiaop — APPROVED** [review]

**Review by ramaraochavali — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
ping @istio/wg-test-and-release-maintainers

**Comment by ramaraochavali** [comment]
Should we add lint to this ?

**Comment by ramaraochavali** [comment]
> how to achieve it with a linter?

TBH, I do not know exactly. I was just asking if it is possible

**Review by ericvn — APPROVED** [review]

**Pull request merged**
