### PR TITLE
chore: adds vanity import to code.

### PR DESCRIPTION
**Pull request by jcchavezs**
**Please provide a description of this PR:**

This PR adds vanity import to all the exported code in this repository by using the tool `porto`. Vanity imports are very helpful when it comes to working with 
- libraries with many packages (and long import names) 
- libraries with non CVS's domain (e.g. istio.io instead of github.com/istio) 
as it tells the user what is the import to use for a package without the need of copying the fullpath and guessing the domain of the module. For example, imagine checking the code of this file and having to resolve the import:

https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go

Files like proto generated, tests files, testdata and internal packages are ignored.

Other CNCF projects like [opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go/pull/2255) and [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/pull/4180) uses it.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by howardjohn** [comment]
No thanks

**Comment by jcchavezs** [comment]
Do you mind elaborating the reason? This come from my time working with
istio apis lately and struggling finding the import paths.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/37277#pullrequestreview-879543256

**Comment by jcchavezs** [comment]
Thanks for the response. With all respect, resolving the import from a file (e.g. the posted on the issue) is really a terrible experience, you need to figure out the path and then go to the go.mod to obtain the domain, so this is more a user experience thing. I encourage you to stumble upon that file and sort out the import and then think of that on daily basis work.

**Comment by howardjohn** [comment]
I wish you luck on your plan to convince every Go project in the ecosystem to adopt this pattern.

**Pull request closed without merging**
