### PR TITLE
[release-1.4] pilot: add alpn HTTP filter (#17821)

### PR DESCRIPTION
**Pull request by yxue**
* add alpn HTTP filter

* address comment

* renaming

* nit

* fix test

* fix test

* format?

* lint

* nit

* guard

* nit

* fix

* add istio in the alpn filter

* update alpn filter

* enable inbound protocol sniffing

* fix unit test

* unit test

* conflict

* security test

* lint

* turn off protocol sniffing

* address comment

### CODE REVIEW

**Comment by ericvn** [comment]
I don't see anything in the _master_ pr that makes this something we need to pull into 1.4 post the testing events. Maybe I'm missing something.

**Comment by rshriram** [comment]
> This should have a feature flag.

> AFAIK this has no benefit to the user without inbound sniffing, so this is purely introducing risk to the user

This doesn't require a feature flag. If inbound sniffing is disabled, then the ports will not be treated as auto so the code wont kick in at all. If you introduce feature flag, then the code is going to get very very complicated [and more bugs!].

**Comment by rshriram** [comment]
Also remember if the ALPN thing doesn't go into 1.4 now, we will have same upgrade issues in 1.5 and worse.

**Comment by rshriram** [comment]
@googlebot I fixed it.

**Comment by howardjohn** [comment]
> Also remember if the ALPN thing doesn't go into 1.4 now, we will have same upgrade issues in 1.5 and worse.

Have we done the testing for introducing this change now? I would rather push upgrade issues to 1.5 than make it impossible to upgrade from 1.3 to 1.4

**Pull request closed without merging**
