### PR TITLE
pilot/xds: replace mutex with atomic.Bool when accessing cache sync

### PR DESCRIPTION
**Pull request by panjf2000**
It seems to me that the synchronization for `serverReady` could be atomic.Bool instead of two mutexs, unless the `IsServerReady()` should be blocked during the `EndpointShardsByService` is being updated.

Please correct me if I misunderstood anything here.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by panjf2000** [comment]
Makefile.core.mk:290: recipe for target 'build' failed
make: *** [build] Error 2
++ docker ps -q
+ docker kill
"docker kill" requires at least 1 argument.
See 'docker kill --help'.

**Comment by panjf2000** [comment]
This seems not a source code issue?

**Comment by panjf2000** [comment]
image

It seems like a temporary failure? or it is caused by my code changes?

**Comment by hzxuzhonghu** [comment]
maybe a flake

**Comment by panjf2000** [comment]
Well, the unit-tests_istio failed again, maybe it is caused by my code changes, but I don't get the causes, and this failure is  different from the last one:
image
Any clue about it?

**Comment by panjf2000** [comment]
The last failed test now pass:
image

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by duderino** [comment]
@hzxuzhonghu @panjf2000 what is the benefit of this change?  If it improves performance by reducing lock contention, I'd expect there to be a comparison of performance results before and after the change

**Comment by duderino** [comment]
@panjf2000 could you do the performance comparison and attach the results here?  

My concern is that if you introduced a race condition with this change, the tests that ran against your PR might not catch it, and I'd at least like to understand the benefits of this change.

If there are no detectable benefits, then I think we should revert it.  There's no reason to risk introducing a race condition if we can't demonstrate a performance improvement.

**Comment by panjf2000** [comment]
Although the performance improvement is pretty intuitive (the atomic operation is faster than lock and the `DiscoveryServer.IsServerReady()` will be blocked if it happens to be in the middle of `DiscoveryServer.EndpointShardsByService` being updated cuz they share the same mutex, which makes it even slower), I can still submit a benchmark for this latter if you insist.

**Comment by duderino** [comment]
@panjf2000 Amdahl's Law applies here.  Your change may have improved performance in an area that the program spends little time in.   In such a case, we would end up taking the risk of introducing a race condition for an insignificant benefit.

**Comment by hzxuzhonghu** [comment]
Yeah, i understand your concern. Since this is a minor improvement, so i approved

**Pull request merged**
