### PR TITLE
Helm chart: Custom proxy image for ingress, gateways, pilot and mixer

### PR DESCRIPTION
**Pull request by ewbankkit**
Fixes https://github.com/istio/istio/issues/7782.

### CODE REVIEW

**Comment by rshriram** [comment]
if you wnat this in 1.0.1, please send same Pr to release-1.0 branch

**Comment by ewbankkit** [comment]
@rshriram Yes, `1.0.1` would be ideal. Shall I close this PR and submit the same changes against `release-1.0`?

**Comment by sdake** [comment]
@ewbankkit my suggestion is to wait for this to merge, and then cherrypick to the release-1.0 branch.  This master-first approach for backports is generally always best practice.

In any regard, @linsun approved, so you will have do that work anyway.

This PR begs the question, if in addition, we want a custom hub for proxyv2.  I don''t quite understand how the proxyv2 image is built to understand well enough if someone would want to customize that and run that separately from the control plane hubs.

Cheers
-steve

**Comment by ewbankkit** [comment]
@sdake Given that this is now merged to `master` and I can do my own work off `master` I won't bother doing a `release-1.0` PR. Thanks.

**Pull request merged**
