### PR TITLE
revert API sha

### PR DESCRIPTION
**Pull request by rshriram**
Move SHA to state before subsets were introduced, to allow #1925 to move ahead.

### CODE REVIEW

**Comment by rkpagadala** [comment]
@rshriram we have bots updating api sha, so devs don't need to do it. How long do you want to keep API frozen?

**Comment by rkpagadala** [comment]
Also why not revert the original commit in api?

**Comment by rshriram** [comment]
API needs to be frozen as long as it needs to be, until implementation can catch up. The reason for having small commits in the API is so that we can keep the corresponding implementation small as well, finishing up each milestone step by step. Else, we would have a giant PR, that will never get done.

**Comment by rkpagadala** [comment]
Adding @hklai 
/lgtm

**Comment by rkpagadala** [comment]
Thanks for doing the changes to istio.deps
I don't feel comfortable with this change, could the development be done on a different branch?
I don't think it is my call to make. This has impact on istio releases (we release only when api/istio/mixerclient/proxy) has consistent shas.

**Pull request closed without merging**
