### PR TITLE
use EndpointSlice v1 in Kubernetes 1.21+

### PR DESCRIPTION
**Pull request by stevenctl**
The EndpointSlice controller will read using the new v1 if the server is running 1.21 or newer. 

fixes https://github.com/istio/istio/issues/32056

### CODE REVIEW

**Comment by stevenctl** [comment]
still need to update the usage of v1beta1 structs... trying to avoid a full fork.

**Comment by stevenctl** [comment]
From https://kubernetes.io/docs/reference/using-api/deprecation-guide/

> All existing persisted objects are accessible via the new API

It seems that at they very least the fake k8s client doesn't exhibit this behavior, or that I don't understand this statement. Does "existing" mean, things that already existed before an upgrade? 

> make sure all of our unit tests exercise both paths

Thinking about the best way to go about this. A lot of tests call `.DiscoveryV1Beta1()` directly. Wondering if I should just add something that mirrors between the old/new versions to the fake kube client code.

**Comment by howardjohn** [comment]
If it was easy, I think ideally we would actually do the version mirror for
*all* types. Its pretty annoying writing a test and accidentally using
v1beta1 istio API and it does nothing. Super low priority if its not easy.

Mirror looks good assuming its just for tests. As i am sure you
know, convertRes may not exactly meet api-server behavior (at least
generically - maybe in ES case its ok), but seems good enough for our tests

**Comment by stevenctl** [comment]
Added the mirror for tests.. didn't make it two way, so test writers will have to use v1, but we can trigger the v1beta1 compat path by overriding the k8s version in the client... This means I need to update several tests to check the backwards compat.

**Pull request merged**
