### PR TITLE
Added headers to propagate for token data

### PR DESCRIPTION
**Pull request by willowmck**
**Please provide a description of this PR:**
This PR enhances the bookinfo sample application to propagate three headers containing potential token data:

- cookie
- jwt
- authorization

This was done to enable testing of more complex RequestAuthentication and AuthorizationPolicy logic with the sample apps.

In addition, I made a change to the productpage requirements for gevent (from 1.4.0 to 1.5.0) and greenlet (from 0.4.15 to 0.4.17).  This was to accommodate the latest version of Python (3.9) on Mac OSX 11.5.  

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by craigbox** [comment]
/ok-to-test

Thanks Will!

**Comment by willowmck** [comment]
> /ok-to-test
> 
> Thanks Will!
> 
> (You'll need to sign the CLA too)

Thanks @craigbox - I just signed the CLA.

**Comment by ericvn** [comment]
I believe at this point, we need verification that the PR originator has built and tested the images with these changes as documented in https://github.com/istio/istio/tree/master/samples/bookinfo#readme. At that point, someone who has the ability to push images to `docker hub` will need to create and push a new set of official images based on those changes, and finally we need to test again with the official image before updating the yamls with the new version number.

**Comment by willowmck** [comment]
Hi Eric,

Yes, I tested my changes in order to write this blog post -
https://www.solo.io/blog/how-to-configure-zero-trust-authn-authz-with-istio/
.

Let me know if you have any questions.

**Comment by craigbox** [comment]
@rvennam @frankbu FYI

**Review by linsun — APPROVED** [review]

**Review by ericvn — APPROVED** [review]
I will let someone with authority work on creating new images and getting them updated in the various yamls.

**Pull request merged**
