### PR TITLE
remove deprecated mcpServerAddrs flag

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
/assign @rshriram

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
This also fix a bug: when configSource.Address is of type ip+port, pilot can not run up.

**Comment by hzxuzhonghu** [comment]
re-apply labels

**Comment by irisdingbj** [comment]
@hzxuzhonghu Can we have this fix go to 1.1 branch as well? Otherwise, pilot will fail when we define one external mcp server.

**Pull request merged**
