### PR TITLE
Update deps before creating 1.2 branch

### PR DESCRIPTION
**Pull request by duderino**

### CODE REVIEW

**Comment by howardjohn** [comment]
@duderino needs rebase

**Comment by duderino** [comment]
Damn, I had just updated too

**Comment by duderino** [comment]
@howardjohn @liamawhite quite possibly the release-1.2 branch will be created off of this PR after it's merged.   Looks like one of the non-required locality weighted load balancing tests has failed.  Please tell me if this indicates something deeply messed up or is merely a flake or garden variety bugfix.

```
failover_test.go:138: a->fake-eds-external-service-7812454174515070270.com total requests to unexpected service=49/100
info	CI	=== FAILED: Test Run: 'locality_prioritized_failover_loadbalancing' (exitCode: 1) ===
info	CI	=== Suite "locality_prioritized_failover_loadbalancing" run time: 2m56.655629178s ===
error	CI	=== Dumping Istio Deployment State...
info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
error	error closing listener: close tcp4 127.0.0.1:46451: use of closed network connection
error	error closing listener: close tcp6 [::1]:46451: use of closed network connection
```

**Comment by howardjohn** [comment]
@duderino https://github.com/istio/istio/issues/13812 known flake. I have been working on getting it stable but haven't yet

**Pull request merged**
