### PR TITLE
feat(gateway-api): customize gateway deployments via class annotations

### LINKED ISSUE #46594: Support customization for Kubernetes Gateway API automated deployments
**Describe the feature request**

I am looking for a way to configure `nodeSelector`, `tolerations` and `affinity` for automatic `Gateway` deployments in the multi-tenant Kubernetes cluster.

[Documentation](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment) references [Custom templates](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental) section, which introduces `inject.istio.io/templates` annotation to provide custom patches on top of the default `sidecar` and `gateway` templates. This doesn't really work after https://github.com/istio/istio/pull/43369 got merged.

As I understand the actual `kube-gateway` template is hardcoded for `gateway.networking.k8s.io/v1beta1/Gateway` here in https://github.com/istio/istio/blob/d400ed59d02763bd6323a942f9b8bf9a6693b646/pilot/pkg/config/kube/gateway/deploymentcontroller.go#L135 and the only way to customize default template is to copy it from [kube-gateway.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml), add patches on top and supply a patched template via Helm values. This is complicated to maintain and probably not safe to keep between version upgrades.

I see following options:
* Supporting `inject.istio.io/templates` or new annotation on `GatewayClass`, so `Gateway` inherits a common template. 
* Extend `ProxyConfig` to support extra pod fields like tolerations and affinity.

For example
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: istio-custom
  annotations:
    inject.istio.io/templates: custom
spec:
  controllerName: istio.io/gateway-controller
```

or

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: my-gateway-affinity
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: my-gateway
  nodeSelector: {}
  affinity: {}
  tolerations: []
```

I can also contribute, but I see there is some active refactoring happening atm.

**Describe alternatives you've considered**

Providing complete custom template.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### PR DESCRIPTION
**Pull request by svrakitin**
Closes #46594

This PR enhances custom `GatewayClass`'es and allows a per-class customization. Currently we have templates and service types hardcoded for each controller type instead.

* Support `inject.istio.io/templates` annotation on `GatewayClass` to pick a custom template from the istiod ConfigMap.
  * Uses controller's default if unset.
  * Supports just a single template for now. No template chaining like for sidecars.
* Support `networking.istio.io/service-type` annotation on `GatewayClass` to override controller's default. This annotation is already supported for `Gateway` to perform a per-gateway override.
  * Uses controller's default if unset.

### CODE REVIEW

**Comment by keithmattix** [comment]
This looks reasonable to me
/ok-to-test

**Comment by howardjohn** [comment]
sorry I didn't notice this until now, will take a look soon

**Comment by howardjohn** [comment]
So I like the idea, I have some concerns on the implementation.

First is GatewayClass in general. I *personally* don't like the idea of GatewayClass at all and have pushed in the API to remove it and/or move things way from it. But its still there and going GA so my opinion there probably doesn't matter much. In particular, I hate `parametersRef` - but, again, its there and going GA. `parametersRef` is the "right" way to do this in the API. But I have some cognitive dissonance here, as the API is bad IMO... not sure how to rationalize those

On the injection template: if we allow it in the class, we should probably allow it per-Gateway as well. Should be easy to add that.

However, I am more concerned about the idea of providing arbitrary templates. Unlike classic sidecar pod injection, this form of templating has a subtle but critical security risk I call "YAML injection". Basically, if you write a template like `type: {{ index .Annotations "networking.istio.io/service-type" }}` (obviously as part of a large template), this may look innocent and fine. But if a user makes the annotation something like

```yaml
networking.istio.io/service-type: |
  ClusterIP
  ---
  kind: ClusterRole
  name: give-everyone-admin-permission
  ---
```

You are going to have a bad time. Sidecar injection mitigates this since its always generating a Patch on a Pod object, so its impossible to create new objects. Technically, this is the template-writers' (who is the mesh admin) fault -- but its really easy to make the mistake, and the results are pretty bad.
Perhaps we add some mitigation that it can only create certain objects or something?
This is why we have `quote` everywhere, by the way.

The other concern is around stability. There is (slow) progress to make some of this upstream (https://github.com/kubernetes-sigs/gateway-api/pull/1757), and the API for templates may change over time (for example, `.DeploymentName` -- we could decide it needs to be removed for some reason or other, or changed, etc). If we do this I would want to add some caveat that it is experimental.

WDYT?

**Comment by svrakitin** [comment]
Thanks for the detailed explanation @howardjohn

Sounds good, you definitely have much more context than I do! 😄 

We can avoid touching `GatewayClass` at all and support override per-gateway only.

Do we want to introduce something like `gateway.istio.io/pod-template` instead, which would be applied on top of the `Deployment`'s existing `spec.template`. This should be safer and cover most of the use cases?

**Comment by howardjohn** [comment]
pod-template is kind of nice since then you could also use the same templates for sidecars. `GatewayConfig` is nice but will be a big effort to get in - the project is very conservative around adding new resources.

Let me solicit some feedback from others and get back to you

**Comment by svrakitin** [comment]
@howardjohn Thank you!

**Comment by ofirshaya** [comment]
any progress on this? related to [this](https://github.com/istio/istio/issues/48151)
it is impossible for us to use istio-gateway-api, we are using a global template that injects `.Values.global.proxy.lifecycle` and we get `field not declared in schema`
I thought about using a custom template but as it is stated in this issue- not possible because of the nature of the kube-gateway file.
@svrakitin @howardjohn

**Pull request closed without merging**
