### PR TITLE
make QPS and Burst values configurable via pilot features

### PR DESCRIPTION
**Pull request by nirvanagit**
Make QPS and Burst values configurable via pilot features

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Reference 
- [1.6 port](https://github.com/istio/istio/pull/25661)
- [master](https://github.com/istio/istio/pull/25662)

### CODE REVIEW

**Comment by fpesce** [comment]
@nirvanagit please ahave a look at the details of your failing tests

**Comment by howardjohn** [comment]
Please submit to master and cheryypick, following https://github.com/istio/istio/wiki/Istio-Release-1.7#how-do-i-get-my-changes-into-the-release. Thanks!

**Pull request closed without merging**
