### PR TITLE
bump k8s version when setup minikube

### PR DESCRIPTION
**Pull request by richardwxn**

### CODE REVIEW

**Comment by howardjohn** [comment]
/ok-to-test
you should join the org in istio/community

**Comment by richardwxn** [comment]
/assign @gargnupur

Can you help approve the change

**Comment by richardwxn** [comment]
@howardjohn Can you help merge it or it is an automated process here?

**Comment by howardjohn** [comment]
@gargnupur needs to `/aprove` the change otherwise the bot won't notice it I think. Also the test are failing so it won't merge. The tests fail because they are running under your account on circleci. I forget the exact steps, but you need to go into circleci and change the settings to not watch `richardwxn/istio`, then it will run under Istios account (which has more resources)

**Comment by richardwxn** [comment]
@howardjohn Thanks for the explanation. I tried updating the setting of circleci but it looks like I need to close and reopen a new pr for the updated setting to work, simply retest won't work. Do you know is there an easier way to enforce updated settings and rerun

**Comment by howardjohn** [comment]
@richardwxn maybe just force push (maybe just change commit message)

**Comment by richardwxn** [comment]
@gargnupur Can you help give lgtm label again since I push updated commit to trigger retest

**Pull request merged**
