### PR TITLE
[release-1.5] Update istio/proxy sha for release-1.5 branch

### PR DESCRIPTION
**Pull request by jacob-delgado**
Update istio/proxy after merged in security fix

Based on https://github.com/istio/istio/compare/release-1.5...release-1.5.7-patch

### CODE REVIEW

**Comment by gargnupur** [comment]
/cc @PiotrSikora , @jplevyak , @mandarjog , @bianpengyuan 
@jacob-delgado : Telemetry WASM tests are failing with following error:
[Envoy (Epoch 0)] [2020-07-06 18:10:50.601][30][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: WASM missing Proxy-Wasm ABI version or requires an unsupported version.

we think could be because of your changes to generate-wasm script: https://github.com/istio/proxy/pull/2892/files#diff-e67ce387bec7e0d09f32b7683edfce61...
Do you need these changes in release 1.5 branch?

**Comment by jacob-delgado** [comment]
> /cc @PiotrSikora , @jplevyak , @mandarjog , @bianpengyuan
> @jacob-delgado : Telemetry WASM tests are failing with following error:
> [Envoy (Epoch 0)] [2020-07-06 18:10:50.601][30][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: WASM missing Proxy-Wasm ABI version or requires an unsupported version.
> 
> we think could be because of your changes to generate-wasm script: [#2892 (files)](https://github.com/istio/proxy/pull/2892/files#diff-e67ce387bec7e0d09f32b7683edfce61)...
> Do you need these changes in release 1.5 branch?

There were changes in the `1.5.7-patch` that included changes to the `generate-wasm.sh` script that caused failures (see https://github.com/istio/proxy/pull/2889/files). It was my attempt to fix them, but I guess I didn't do it correctly. I can bring back the old scripts and just try and update the sha.

**Comment by jacob-delgado** [comment]
This will fail until the prow post-submit jobs are finished. I will retest it once they are complete.

**Pull request merged**
