### PR TITLE
cherry-pick of 14448 HTTP1.0 support for gateway

### PR DESCRIPTION
**Pull request by GregHanson**
cherry pick of https://github.com/istio/istio/pull/14448

### CODE REVIEW

**Comment by GregHanson** [comment]
cc @Demonsthere 
@howardjohn @fpesce can you add the `cla: yes`?  we have both signed the CLA (see #14448)

**Comment by Demonsthere** [comment]
@googlebot I confirm

**Comment by fpesce** [comment]
CLA was signed-off in original PR.

**Pull request merged**
