### PR TITLE
Fix URLFetch does not support folders

### PR DESCRIPTION
**Pull request by wzshiming**
Fix URLFetch does not support folders

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by wzshiming** [comment]
@howardjohn  Hi, Coud you have time to take a look.

**Review by morvencao — COMMENTED** [review]
> Fix URLFetch does not support folders

When you say the URLFetcher doesn't support folder, you mean the folder in the URL or folder in the download destination directory?

From the test cases you added, it should be the former, but I didn't see the directory in the URL is actually used.

**Comment by wzshiming** [comment]
@morvencao
This URL can be configured, especially in the environment where some intranets cannot be connected to the Internet

**Review by morvencao — APPROVED** [review]

**Comment by wzshiming** [comment]
@morvencao 
Hi, Needs `release-notes-istio` label.

**Review by shamsher31 — APPROVED** [review]

**Comment by shamsher31** [comment]
> Parsing release notes
> Unable to read release notes: unable to open file releasenotes/notes/gateway-target-port.yaml: open releasenotes/notes/gateway-target-port.yaml: no such file or directory

@brian-avery can you PTAL. looks like an unrelated failure for release notes.

**Comment by wzshiming** [comment]
Rebase to fix test failed

reference #31804

**Pull request merged**
