### PR TITLE
[DO NOT MERGE] - Add rate limiting for API methods.

### PR DESCRIPTION
**Pull request by apicl**
This CL is intended for discussion purpose. Please don't submit.

**Release note**:

```release-note
<PLEASE PUT RELEASE-NOTE HERE, PUT NONE if NO RELEASE-NOTE>
```

### CODE REVIEW

**Comment by rshriram** [comment]
Some explanation would be helpful

**Comment by ayj** [comment]
Updated the title, priority, and milestone to reflect that this PR is intended for discussion at the moment.

@rshriram, okay to leave this PR open for discussion? I was originally going to close to avoid confusion with on going 0.2 release and consuming test resources. I updated title, etc. and its still marked "needs-ok-to-test" so maybe that's not a problem? Otherwise we can create on a separate branch.

**Comment by rshriram** [comment]
We can leave it open. Also, whats all the X-Google stuff ? Can we keep this vendor neutral? Else we are going to have a bunch of people come in and plug their vendor specific stuff in the swagger. The Host in Swagger was omitted explicitly because people can run up their bookinfo anywhere, and plug the swagger.yaml in a swagger UI, point to the bookinfo ingress and try the API calls.

cc @ErikWittern any thoughts?

**Comment by apicl** [comment]
Currently OpenAPI does not support rate limiting features, so we have to
use some kind of extension. The X-Google is Google extensions.

Will follow up about the vendor neutral solution during the design phase.



Thanks
Chengliang

**Pull request closed without merging**
