### PR TITLE
Changing the logic to check if default namespace already exits.

### LINKED ISSUE #27063: Installation fails - incorrect check for whether istio-system namespace already exists
Encountered with Istio 1.6.8.

Scenario:

1. OPA gatekeeper admission controller requires certain labels on every namespace.
2. Manually create istio-system namespace and add required labels.
3. Run `istioctl install`.
4. [createNamespace](https://github.com/istio/istio/blob/f23bb221697effd3506bc8f46e8ffa5e125504f4/operator/cmd/mesh/shared.go#L253) function returns an error because instead of being an "isAlreadyExists" error it is an admission control related error.

The namespace does already exist and Istio should simply be installed into it. Instead there is a misleading error message. For example:
```
Error: failed to apply manifests: failed to create namespace istio-system: admission webhook
"validation.gatekeeper.sh" denied the request: [denied by ns-must-have-labels] All namespaces
must have a `xxxx` and `yyyy` annotation
```

### PR DESCRIPTION
**Pull request by luckoseabraham**
Currently the check for namespace depends on error message from create activity. This has problems when there are other admission hooks which blocks simple namespace creations.
Fixes https://github.com/istio/istio/issues/27063

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
/ok-to-test

thanks!

**Comment by luckoseabraham** [comment]
hey @howardjohn  - I am not really familiar with the release note test. I forgot to check the "Does not have any changes that may affect Istio users." section in the description. Would you be able to add the label release-notes-none to this PR ?

**Review by Rayow-13 — COMMENTED** [review]
![Uploading 93547773...]

**Pull request merged**
