### PR TITLE
Fix listener parsing with ipv6 addresses

### PR DESCRIPTION
**Pull request by sbezverk**
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

Closes: #11867

### CODE REVIEW

**Comment by sbezverk** [comment]
On ipv6 only pod side car reports:
```
2019-02-19T22:17:53.594255Z     info    Envoy proxy is ready
```

**Comment by costinm** [comment]
/approve
/lgtm

Note that ipv6 was broken in 1.0 - this will enable it in some parts of the system ( when using whitebox mode for example ).

There is a risk that clusters have ipv6 enabled - and would break even if Istio only uses the ipv4 addresses.

**Comment by costinm** [comment]
Sorry - meant to 
/lgtm 
/approve

not close.

**Comment by sbezverk** [comment]
@costinm it looks it is missing an extra label to get merged.. Could you please fix it? Thanks a lot..

**Comment by costinm** [comment]
@duderino 
@wenchenglu

**Comment by duderino** [comment]
This will go into Istio 1.1 RC1

**Comment by JamazRuan** [comment]
after support ipv6 address parse, it cannot parse the "virtual" listener
because "virtual" listener cannot skip by the isLocalListener function as before
the error logs is:
```
Envoy proxy is NOT ready: failed parsing Envoy listener: virtual
```

**Comment by sbezverk** [comment]
@JamazRuan since this changes passes all CI tests, there must be some special about your configuration then. Please make sure you use the latest images, there were more ipv6 related changes merged into master. Also share pilot's discovery log and istio-proxy log of a side car of application. If you are confident, it is a bug, please file an issue.

**Pull request merged**
