### PR TITLE
use read only stop channel

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
pass read only stop channel

### CODE REVIEW

**Comment by rshriram** [comment]
wrong branch

**Comment by zachgersh** [comment]
@hzxuzhonghu can you please repoint this PR to release-1.0 instead?

**Comment by hzxuzhonghu** [comment]
>@hzxuzhonghu can you please repoint this PR to release-1.0 instead?

Yes, I can. And I am new contributor to sitio. Where can I find which branch to point to?

**Comment by costinm** [comment]
Still lint errors, please fix (and move to master if not ready by Fri, hope to cut an almost final build)

**Comment by hzxuzhonghu** [comment]
@costinm 
This is the lint error, I do not think my modification can introduce dep issue. (without new import)
```
#!/bin/bash -eo pipefail
make depend.diff ISTIO_OUT=/go/out
go get -u github.com/golang/dep/cmd/dep
dep ensure
git diff HEAD --exit-code -- Gopkg.lock vendor > /go/out/dep.diff
Makefile:245: recipe for target 'depend.diff' failed
make: *** [depend.diff] Error 1
Exited with code 2
```

**Comment by hzxuzhonghu** [comment]
BTW, it's odd for newers like me to see this kind of error. And I run `dep ensure` in my local host, it actually bring some updates. But that has nothing to do with this pr.

**Pull request merged**
