### PR TITLE
Run bin/update_deps.sh

### PR DESCRIPTION
**Pull request by jacob-delgado**
**Please provide a description of this PR:**

Various fixes to distroless images were made, including a CVE fix.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
@jacob-delgado Note that pulling thew latest proxy version will cause all tests to fail. See the automated job. I've asked for the network team about it.

**Comment by jacob-delgado** [comment]
> 

I'm going to revert the deps change, except for distroless

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
