### PR TITLE
Added yaml templates for rate limiting.

### PR DESCRIPTION
**Pull request by gyliu513**
**Release note**:

```release-note
None
```

In https://github.com/istio/istio.github.io/blob/master/_docs/tasks/policy-enforcement/rate-limiting.md , there are two files for rate limiting need to be created by end user, it is better to put those two files in source code and end user can use those files directly when doing test.

### CODE REVIEW

**Comment by gyliu513** [comment]
@rshriram what do you think of adding those yaml files to the source code?

**Comment by rshriram** [comment]
Yes, thats a good idea!

**Comment by rshriram** [comment]
@gyliu513 I checked the code.. WE have this file in the repo.. mixer-rule-ratings-ratelimit.yaml..

**Comment by gyliu513** [comment]
Thanks @rshriram , then I think that the document needs to be updated a bit to enable end user use the template in the source code, but not re-create, will update the PR later.

**Pull request closed without merging**
