### PR TITLE
refactor gen identities

### PR DESCRIPTION
**Pull request by wulianglongrd**
**Please provide a description of this PR:**
Use `spiffe.MustGenSpiffeURI` func instead of `fmt.Sprintf` to generate identity, delete unnecessary `TrustDomain` parameter.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
For refactor pr, it's better to describe what you do in detail. Otherwise it is hard to review

**Comment by wulianglongrd** [comment]
@hzxuzhonghu thanks. I updated the PR description.

**Review by hzxuzhonghu — APPROVED** [review]
Thanks, LGTM

**Comment by howardjohn** [comment]
This seems to be moving us towards using *more* global variables which is a bit backwards of where I would hope we go.

**Comment by wulianglongrd** [comment]
In fact, the use of global variables is reduced, because this pr deletes a global variable `IdentityTemplate`.

**Comment by howardjohn** [comment]
A global const is not a global variable. We are now using more GenSpiffe which relies on a global variable that changes at runtime

**Pull request merged**
