### PR TITLE
Remove the Envoy v1 implementation

### PR DESCRIPTION
**Pull request by ijsnellf**
Removes unused files.

https://github.com/istio/istio/issues/6049

### CODE REVIEW

**Comment by costinm** [comment]
/lgtm
/approve

Not sure if this needs to be backported to release-1.0 - and it may be good to stop making changes to master for next 2 weeks, to have a smooth merge back fro rel1.0

**Comment by rshriram** [comment]
Please backport to 1.0.. Else, we will have a painful merge

**Pull request merged**
