### PR TITLE
Add az cache support

### PR DESCRIPTION
**Pull request by zhuguihua**
This PR is to add az cache support, and rename function AvailabilityZone to RetrieveAvailabilityZone.

### CODE REVIEW

**Comment by rshriram** [comment]
Does it make sense to add webhooks for this as well?
If so, could you please copy the code from ListClusters and follow the same pattern?

**Comment by liamawhite** [comment]
Looks fine to me. 

Not really sure there is much benefit to caching the AZ though. The AZ will only be looked up once per IP so we should never hit the cache.

Is there a chance a kube pod could have the same IP as a pod that has previously been terminated but be on different worker? I would guess so? If that is true this could potentially be dangerous,

**Comment by zhuguihua** [comment]
When the containers not the pod restarted, for example, docker restart, kubelet eviction casued containers restart, these will hit the az cache.

**Comment by liamawhite** [comment]
@zhuguihua How long does the lookup persist in the cache?

**Comment by zhuguihua** [comment]
@liamawhite The cache would be persisted until the service node was deleted.

**Comment by liamawhite** [comment]
So there's no expiry on the cache?

**Comment by zhuguihua** [comment]
Currently it is. Your suggestion?

**Comment by liamawhite** [comment]
Im happy to approve then. Even if we will only see it on edge cases like proxy container reload.

**Comment by zhuguihua** [comment]
@liamawhite I'm so glad you approved this, thanks for your work.

**Comment by costinm** [comment]
v1 is obsolete, we have new model of tracking clients in v2. If you want caching, please add it to the v2 
config, and start moving the AZ handler to the v2 package, since v1 is scheduled for removal post 0.8

**Pull request closed without merging**
