### PR TITLE
fix(helm/sidecar-injector-configmap): run as root

### LINKED ISSUE #10358: Istio sidecar init-container requires to run as `root`, specify it explicitly in the ConfigMap
**Describe the bug**
Istio sidecar init-container requires to run as `root` because of `iptables`. It does not specify it explicitly in the sidecar injector ConfigMap. In our environment, Pods by default run as a non-root user. So, the init-container inherits:
```
  securityContext:
    fsGroup: <int>
    runAsNonRoot: true
    runAsUser: <int>
```
We need to explicitly override the init-container as:
```
  securityContext:
    runAsNonRoot: true
    runAsUser: 0
```

**Expected behavior**
The `runAsUser: 0` configuration is currently not present in the istio-sidecar-configmap by default. Would expect this to be present by default since it's required to run `iptables`

**Steps to reproduce the bug**
1. Set [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#podsecuritypolicyspec-v1beta1-extensions) with `runAsUser` different than root.
1. Try the sidecar auto-injection. The auto-injected init-container fails to start with error:
```
+ iptables -t nat -N ISTIO_REDIRECT
iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
+ dump
+ iptables-save
iptables-save v1.6.0: Cannot initialize: Permission denied (you must be root)
```

Even if `privileged=true` is set at container level SecurityContext, the issue is reproducible.

**Version**
```
$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Installation**
[Istio Minimal Installation steps were followed](https://istio.io/docs/setup/kubernetes/minimal-install/)

**Environment**
Own k8s cluster.

### PR DESCRIPTION
**Pull request by jaredallard**
**What this PR does**: Fixes the init container to be able to properly apply iptables rules when the parent pod has a securityContext set

Fixes #10358

### CODE REVIEW

**Comment by gyliu513** [comment]
@jaredallard , sorry for late response (just come back from vacation), master is frozen, can you please create this PR against the branch of `release-1.1`?

**Comment by linsun** [comment]
/hold

need to understand which k8s platform is used

**Comment by jaredallard** [comment]
@gyliu513 Will do.

@linsun This is not platform specific, since the parent securityContext is modifying the initContainers securityContext.

**Comment by jaredallard** [comment]
@Bessonov I'll try to get this rebased onto release-1.1 by this weekend, apologies for the delay everyone.

**Comment by jaredallard** [comment]
@gyliu513 based on `release-1.1` let me know if you need anything else from me.

**Comment by jaredallard** [comment]
@gyliu513 Can we get some movement on this? Need to stop modifying this myself asap!

**Comment by Bessonov** [comment]
@mandarjog @gyliu513 c'mon guys, this one is pending since 2 months. It's frustrate a ton of people or at least everyone, who want to use non-root images. Every bitnami image for helm (stable/mariadb, stable/mongodb, stable/redisdb, ...) is a non-root image. It costs me a lot of time to figure out why charts are failing with istio.

To hold this PR you produce not only work for you, but for your users and maintainers of non-root images.

**Comment by jaredallard** [comment]
/cc greghanson

Adding another reviewer, would be nice to get some movement on this.

**Comment by Bessonov** [comment]
@mandarjog @gyliu513 @GregHanson more activity, please.

**Comment by translucens** [comment]
There is a workaround like #10358, however, this PR is essential for GKE Istio addon users because GKE Istio addon does not allow modifying sidecar-injector-configmap manifest by cluster user and they cannot apply its workaround.

**Comment by chrisz100** [comment]
Same for us, this needs to stop. And it's been months!

**Comment by duderino** [comment]
/retest

@ostromart @costinm PTAL

**Comment by duderino** [comment]
This definitely should not have been left sitting for so long.  Sorry.  Getting more eyes on it now.

However, the circleci test failures look like they are due to this change.  We can't merge a PR that breaks tests

**Comment by costinm** [comment]
Sorry for the delay - the PR looks good, if we can get the tests to pass we should get it in.

/lgtm
/approve

**Comment by howardjohn** [comment]
To fix the tests, you need to update the expected files. in pilot/pkg/kube/inject/testdata.

And probably rebase your changes since this is from a while ago

**Comment by duderino** [comment]
@howardjohn can you take this one?  I think it's an important fix, I worry we've stretched everyone's patience too far already, and I bet you could fix the test failures in far less time

**Comment by sdake** [comment]
@jaredallard apologies for the long lag in your PR review.  This issue is in the process of being solved, and I want to thank you for hunting down the correct solution.

Most Istio contributors that can approve PRs are a little overloaded.  One thing that helps when your PR is submitted is to use the `/assign` feature so the reviewer knows your work is ready.  If you feel the current reviewer is slacking (Costin is super overloaded;) you can always do a second assign.

This shows up in a dashboard under https://github.com/pulls/assigned and is the primary mechanism by which many PRs are reviewed.

Cheers
-steve

**Pull request closed without merging**
