### PR TITLE
Add XDS address to ztunnel

### PR DESCRIPTION
**Pull request by costinm**
Updated some of the comments to be more clear on what is used as well.

### CODE REVIEW

**Comment by costinm** [comment]
As a follow-up - we may want to allow users to customize where the roots are loaded from ( for 443 with system roots case )

**Review by howardjohn — APPROVED** [review]
Root is XDS_ROOT_CA and CA_ROOT_CA, so it can be set already, maybe just not easily via helm fwiw

**Comment by costinm** [comment]
Yes, I saw that - can follow up with a helm option to set either the XDS_ROOT_CA or to use a custom configmap (or both).

**Pull request merged**
