### PR TITLE
[WIP] Add test case for accessing external service with sni

### PR DESCRIPTION
**Pull request by ronenschafferibm**
This PR adds a test case to pilot's e2e tests that checks the access of an application to an external service using sni.

### CODE REVIEW

**Comment by rshriram** [comment]
We already have a test for SNI via egress gateway. Check egressgateway_test.go

**Comment by ronenschafferibm** [comment]
@rshriram Don't you think we should have a test for a case that doesn't go through the egressgateway?

**Comment by rshriram** [comment]
They are both the same. SNI routing is happening at sidecar and then at egress gateway. It cannot work with just egress gateway.

**Comment by ronenschafferibm** [comment]
Although testing only the case with egressgateway might include the case without it, 
I think we should have this additional test since it's a use case the users might use and it can help us identify problems when the implementation of the gateway changes.

**Pull request closed without merging**
