### PR TITLE
Test framework: remove "Static VM" concept

### PR DESCRIPTION
**Pull request by howardjohn**
This is part of an overall goal to reduce the complexity of the test framework, to ease debugging, test writing, and improving the framework in other ways.

This removes the concept of non-Kubernetes clusters. These were used to build out real VM instances, rather than the in-pod simulation ones. However, I don't think anyone uses this.

### CODE REVIEW

**Comment by bleggett** [comment]
Okay I didn't realize this would kill about 1K LOC. +1 then.

**Review by bleggett — APPROVED** [review]
As per 5/15 WG consensus.

**Review by ilrudie — COMMENTED** [review]
👍 LGTM, thanks John!

**Comment by howardjohn** [comment]
> does the readme need to be updated?

I don't know any readme that references this?

**Comment by howardjohn** [comment]
@istio/wg-test-and-release-maintainers LFR

**Review by ericvn — APPROVED** [review]

**Pull request merged**
