### PR TITLE
remove unneeded service instance guard for gateway

### PR DESCRIPTION
**Pull request by jeffpak**
Please provide a description for what this PR is for.

This guard breaks Cloud Foundry, because CF does not need a
service instance attached to the gateway.
This guard should not be needed by Galley; Galley should only be
sending config when it is updated.
Tests have been doctored to address removal of guard.
The mock copilot has been removed, since it is unused.
This PR effectively reverts #11905. cc @rshriram

And to help us figure out who should review this PR, please
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Regards,
The Cloud Foundry Networking Team

### CODE REVIEW

**Comment by rshriram** [comment]
I just remembered why we put this in.. See these (k8s) issues:
https://github.com/istio/istio/issues/10904
https://github.com/istio/istio/issues/11039
https://github.com/istio/istio/issues/11520

In our internal setup, when we tried to deploy Istio purely on VMs [no k8s], with a gateway on VMs, we hit the same issue [gateway being disconnected due to no service instances] even though we had explicitly added service entries with the gateway IP as the endpoint IP.  [cc @saigs]  So my PR (https://github.com/istio/istio/pull/11905) seems to fix k8s while breaking cloudfoundry and the vm-only istio where both cf/vm use service entries for service registry.

Could it be that the issue lies in the way the service instances are populated for service entries and not in the actual check for number of instances? It could also be that you are supplying the wrong endpoint IP from the one that pilot has for the service instance. This can only happen if getproxyServiceInstances is not using the IP you use in the service node (x~y~IP~..).

cc @hzxuzhonghu / @howardjohn - thoughts?

**Comment by hzxuzhonghu** [comment]
As #13229 was in,  i think we can remove this check https://github.com/istio/istio/pull/15473/files#diff-14f4a8a239bf5ba82053cf6606daace5L529

**Pull request merged**
