### PR TITLE
quick fix for flaky TestMixerReportingToMixer

### PR DESCRIPTION
**Pull request by ayj**
TestMixerReportingToMixer searches pod logs to verify mixer is
reporting on itself. The current code checks the last 100 lines of
logs which may not be sufficient to capture enough report
history. Increase the search to the last 1000 lines as a quick fix for
postsubmit failures.

fixes https://github.com/istio/istio/issues/4858

### CODE REVIEW

**Comment by ayj** [comment]
fyi @hklai

**Comment by hklai** [comment]
/lgtm

Thanks Jason!

**Pull request merged**
