### PR TITLE
remove deprecated service graph off demo profile

### PR DESCRIPTION
**Pull request by linsun**
This is something we discussed for a long time but was not implemented.

### CODE REVIEW

**Comment by linsun** [comment]
cc @duderino @utka if there is another 1.1 build, would like to get this in.  If not, 1.1.1 is fine.

**Comment by linsun** [comment]
some discussion on slack:

```Lin Sun [2:32 PM]
folks, our demo profile still has service graph enabled, should i change that to disabled in favor of kiali?  @costin @Joshua Blatt @sdake and others

Steve Dake [2:32 PM]
i’m going to bed
i’ll be back tomorrow
i’m in no shape to make any decisions
(too tired)
although from my understanding wervice graph is depreciated- try @dougreid

Douglas Reid [3:10 PM]
@linsun yes. servicegraph was deprecated. i don't believe anyone has even tried it with 1.1 (to my knowledge)
```

**Comment by utka** [comment]
I am pretty sure there will be rc4 next week. I jsut created rc3 this morning

**Pull request merged**
