### PR TITLE
channel should be closed before deleting

### PR DESCRIPTION
**Pull request by Penguin-zlh**
**Please provide a description of this PR:**
channel should be closed before deleting

### CODE REVIEW

**Comment by jiuker** [comment]
@kebe7jun /cc

**Review by kebe7jun — APPROVED** [review]

**Comment by Penguin-zlh** [comment]
@howardjohn This processing method can maintain consistent style, just like this
```go
func (w *FakeWatcher) Close() error {
	w.Lock()
	for path, ch := range w.events {
		close(ch)
		delete(w.events, path)
	}
	for path, ch := range w.errors {
		close(ch)
		delete(w.errors, path)
	}
	defer w.Unlock()
	return nil
}
```

**Comment by howardjohn** [comment]
There is no need to close channels in most cases, and I don't think this is
a case where we need one.

**Comment by Penguin-zlh** [comment]
thanks for your reply

**Pull request closed without merging**
