### PR TITLE
support dualstack in bookinfo sample

### PR DESCRIPTION
**Pull request by sstoner**
update `bookinfo/details` and `bookinfo/productpage` to listen on dualstack(support ipv6)

### CODE REVIEW

**Comment by sstoner** [comment]
@googlebot I signed it!

**Comment by sstoner** [comment]
@googlebot I signed it!

**Comment by sstoner** [comment]
@googlebot I signed it!

**Comment by sstoner** [comment]
@googlebot I fixed it.

**Comment by sstoner** [comment]
@googlebot I signed it!

**Comment by howardjohn** [comment]
@istio/wg-docs-maintainers please review this

**Comment by sstoner** [comment]
@istio/wg-docs-maintainers please review this.  Bookinfo applications will support ipv6 completely

**Pull request merged**
