### PR TITLE
Remove obsolete mixer deployment files.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Up to date deployment files are under install/kubernetes. These are
out of date and cause confusion.

### CODE REVIEW

**Comment by douglas-reid** [comment]
Thanks for handling this cleanup!

**Comment by jeffmendoza** [comment]
@douglas-reid Can you trigger a retest when you have a chance? Thanks.

**Comment by jeffmendoza** [comment]
@douglas-reid rebased

**Pull request merged**
