### PR TITLE
set node on first message only (#30390)

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/30461

I think this should be in 1.9 because I am a bit worried about the upgrade implications of setting this on existing new proxies for in place upgrade. If we merge it in 1.9, this will never happen, as 1.8 proxies will be unchanged.

If we do not merge this here, I strongly recommend we change the proxy version check to be GE110 instead of GE19.

However, I do think we should merge here, as it results in 50% CPU usage in istiod.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Just to make sure, this fix https://github.com/envoyproxy/envoy/pull/14080 is in 1.9 proxy right? If yes, merging it to 1.9 makes sense to me.

**Comment by howardjohn** [comment]
I assumed so since your pr checks for proxy > 1.9. If not, we should change the check to 1.10?

**Comment by howardjohn** [comment]
yep it's there https://github.com/istio/envoy/commit/9340c2cbfba31e7b2fb17c810f27781ba9d6d411

**Comment by ramaraochavali** [comment]
Thanks for confirming.

**Review by ramaraochavali — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]
im fine with it, looking for feedback from the other RMs

**Review by shamsher31 — APPROVED** [review]
LGTM.

**Pull request merged**
