### PR TITLE
Use external service controller for Synthetic Service Entries

### PR DESCRIPTION
**Pull request by nmittler**
While debugging #19973, I discovered that SSEs use a different type/kind than standard ServiceEntries. This is not correct - they shoul be the same kind but from different collections.

Changing this, however, is problematic because the SSE logic implements both ConfigStore and ServiceDiscovery. The external controller uses the ConfigStore as it's source for events. Since it also implements ServiceDiscovery, the XDS updater ends up seeing the same ServiceEntry in both controllers.

I think that we never should have implemented a ServiceDiscovery controller for SSEs, but instead let the external service controller do its job. That is the change here.

### CODE REVIEW

**Comment by Nino-K** [comment]
lgtm

**Comment by hzxuzhonghu** [comment]
/hold
just give some others a chance to have a look since it is a huge change.

cc @ramaraochavali @rshriram

**Comment by nmittler** [comment]
@hzxuzhonghu this is not a large change ... it only affects synthetic service entries. Please remove your hold.

**Pull request merged**
