### PR TITLE
[release-1.3]Remove outdated time diff info for istioctl ps command. (#16477)

### PR DESCRIPTION
**Pull request by AsCat**
* Remove outdated time diff info for istioctl proxy-status command.

* goimports format fix

* Display 'STALE (Never Acknowledged)' when there is never acknowledged

(cherry picked from commit cdb896e3e81ec5db64ee702f1fd2e9d2daede3d2)

Please provide a description for what this PR is for.

Fixes https://github.com/istio/istio/issues/16071

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by AsCat** [comment]
This is a manually created fix for release-1.3 [PR](https://github.com/istio/istio/pull/16477)

**Comment by clyang82** [comment]
@sdake @howardjohn I saw we just had 1.3.0-rc.3 package. I am not sure if we can have this PR in or not. I think that is serious usability gap for istioctl. What do you think?

**Comment by rlenglet** [comment]
> I saw we just had 1.3.0-rc.3 package. I am not sure if we can have this PR in or not. I think that is serious usability gap for istioctl. What do you think?

This PR came in late. We'll likely pick it for 1.3.1.

**Comment by howardjohn** [comment]
Fixes https://github.com/istio/istio/issues/16071

**Comment by AsCat** [comment]
> @AsCat Please add an entry into the [1.3.1 release note draft](https://github.com/istio/istio/wiki/Release-Note-1.3.1-Draft).

It seems that i have no permission to edit this wiki page. 
Can anyone help add a permission or update the wiki directly?
Entry may like below:
**Removed**  time diff info in proxy-status command

**Comment by rlenglet** [comment]
I updated the wiki. Thanks!

**Pull request merged**
