### PR TITLE
Attempt to fix race in destination rule

### PR DESCRIPTION
**Pull request by howardjohn**
This mirrors what we do for virtual service

Fixes failures like
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20524/unit-tests_istio/7352

### CODE REVIEW

**Comment by rshriram** [comment]
How come we never saw this in last 6 months ?

**Comment by howardjohn** [comment]
That is a good question... I am not sure. I think the way we handle this type of modification to the config is not correct, and this is more of a hack than a proper fix. If we do integrate the galley config pipeline this would fit pretty natively into the model they have there of transformations

**Comment by rshriram** [comment]
I want to know if this is going to cause any adverse impact (I don’t think so), but check just in case. Otherwise I am okay.

**Pull request merged**
