### PR TITLE
[DO NOT MERGE] a dummy change to test a PR

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**

### CODE REVIEW

**Comment by sdake** [comment]
@vadimeisenbergibm would you mind closing this (working to clean up the PR backlog)

Cheers
-steve

**Comment by vadimeisenbergibm** [comment]
@sdake I have opened this PR to test if an empty PR (a line in README) can pass the tests. Basically it means that the master passes the tests. The tests are currently failing. I would like to make this PR pass the tests and then close it. Otherwise, how can I know that the current master passes?

**Comment by vadimeisenbergibm** [comment]
@sdake the PR is still failing.

**Comment by vadimeisenbergibm** [comment]
@ldemailly @costinm Could someone explain me why this PR (a change in README) fails the circle ci race test? Or is this race test not required for merging?

**Comment by ldemailly** [comment]
race test is not marked "required" because it hasn't been passing yet (@xiaolanz is working on getting it green)

**Comment by ldemailly** [comment]
?

**Comment by vadimeisenbergibm** [comment]
@ldemailly I use this PR occasionally as a sanity check that a smallest possible change (test in README) passes all the tests. I hope it does not create too much noise. If you think it interferes with the work of others, I will stop this practice. Right now, ci/circleci: e2e-pilot-noauth-v1alpha3-v2 fails on this PR.

In general, I think it could be a nice test to perform automatically, "to test the tests"  - the whole PR cycle, that the tests run as expected and pass.

**Comment by ldemailly** [comment]
test grid and post submit tests should give that few of the state of master but it's fine - I was just curious about the reopen, reopen without tickling by merging isn't too useful

**Comment by vadimeisenbergibm** [comment]
Reopening to test prow/e2e-bookInfoTests-v1alpha3.sh.

**Comment by ldemailly** [comment]
out of curiosity, do you rebase when you reopen/update ?

**Comment by vadimeisenbergibm** [comment]
no, I just add a new dummy commit

**Comment by ldemailly** [comment]
ic so you rely on auto merge to latest to work correctly, hopefully that does work

**Comment by vadimeisenbergibm** [comment]
@ldemailly ah, you mean for general PRs? This one is just a dummy PR to test the CI tests.

In general, I usually merge from master. If my commits digress from master and cannot be merged, i.e. have conflicts, I just open another branch/PR, and cherry-pick the commits to it from the original PR or just manually copy all the changes as one big new commit. Then I close the original PR and reference the original PR from the new one (put a link to it).

Please let know if you think this mode is OK and if you have better ideas for working with PRs/branches.

**Comment by ldemailly** [comment]
I think costin did add auto merge to circleci, it used to be that only prow did that so it's fine
but for a test you could also rebase and push -f

For real PRs my take is that it is best to not move to new PRs once someone started reviewing them (and just merge/update the PR with a merge from master, and not a rewriting history rebase)

**Comment by vadimeisenbergibm** [comment]
@ldemailly so to merge even if there are conflicts in the merge? I mean to merge and to fix the conflicts during the merge.

**Pull request closed without merging**
