### PR TITLE
fix: helmchart istiod - add ports defined on service to deployment

### PR DESCRIPTION
**Pull request by bryankaraffa**
This adds the missing ports that the istiod Service expects on the pods to the Deployment spec.  

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by bryankaraffa** [comment]
@googlebot I signed it!

**Review by howardjohn — COMMENTED** [review]
Can you indicate what this fixes? `containerPort` is not a required field

**Comment by bryankaraffa** [comment]
This is intended to address [POP-1106 - No target ports match service port](https://github.com/derailed/popeye/blob/master/docs/codes.md#service).  

The `Service` is [expecting the selected pods to have ports 15010, 15012, 15014, 15017](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/service.yaml#L14-L27) and this adds the missing ports to the `Deployment` spec so that all ports defined on the Service have an equivalent containerPort in the Pod/Depoyment it's selecting

**Comment by howardjohn** [comment]
I am not sure I agree with that linter rule, especially the "error" severity. The containerPort is not required unless you used named service ports, which we are not.

**Comment by bryankaraffa** [comment]
The istiod Service exposes 15010, 15012, 15014, 15017 and the Deployment/Pods expose only 15010 and 15017.  I guess I am not clear why it is OK to have the Deployment/Pods not exposing everything that is defined in the Service; or why the "extra" ports on the Service [15012, 15014] that not exposed via Deployment/Pods should not removed

**Comment by howardjohn** [comment]
From the spec:

```
     List of ports to expose from the container. Exposing a port here gives
the
     system additional information about the network connections a container
     uses, but is primarily informational. Not specifying a port here DOES
NOT
     prevent that port from being exposed.
```

It is more or less just documentation

**Comment by bryankaraffa** [comment]
Gotcha.. well thank you for the time and additional clarify.  I'll close this PR out

**Pull request closed without merging**
