### PR TITLE
Reenable TestStressEnvoy race test.

### PR DESCRIPTION
**Pull request by xiaolanz**
Looks like it doesn't fail anymore. address #3210

### CODE REVIEW

**Comment by ldemailly** [comment]
can we see #3780 pass first ?
/hold

**Comment by xiaolanz** [comment]
No. We cannot wait for the other one. because there are a few other racetests to be fixed before I can enable for presubmits.

**Comment by ldemailly** [comment]
this PR didn't fix anything, it just made the test enabled... I hope it does pass

**Comment by xiaolanz** [comment]
We tested locally. Neither Wayne nor me found it fail though.

**Pull request merged**
