### PR TITLE
'istioctl kube-inject' warnings output to stderr AFTER yaml output to stdout

### PR DESCRIPTION
**Pull request by esnible**
Resolve https://github.com/istio/istio/issues/23717 by failing kube-inject if a pod is already injected or has host networking.

### CODE REVIEW

**Comment by esnible** [comment]
> What if you have a big yaml of all your deployments? Now a single one will cause it to fail - may cause some issues in ci pipelines

Fair enough.  How would you feel if the IntoResourceFile yaml reader accumulated the errors in a multi-error instead of bailing on the first one?  Then `stdout` would include injected yaml.  I could code it to keep or reject the unchanged failures.

I created this because @GregHanson reported users missing the output.  Any thoughts?

Other possibilities considered
- Output processing errors to stdout at the end, surrounded by lines of asterisks, but keep current $? results.
- Keep processing, skipping invalid injections
- Keep processing, pass invalid injections through
- A `--force` option, or guidance in the long description to use `| true` in scripts to avoid bombing out.

**Comment by GregHanson** [comment]
@esnible for #23717 my main comment was the one line error message is very easy to miss since there are no newlines between the error message and the rejected yaml.  I don't know if in cases like this it would be better to put the error message at the end of the yaml output?  Or maybe some additional formatting around the error message to call better attention to it in this case?

**Comment by esnible** [comment]
@GregHanson This keeps the $? behavior the same.

Instead of stderr messages appearing at the beginning they are held until the end.  There is a `\n` dividing them from the YAML and `===>` before each one:

```

===> Skipping injection because "hello-host-network" has host networking enabled
```

**Comment by esnible** [comment]
@GregHanson Can you review?

**Pull request merged**
