### PR TITLE
Determine delta eds regardless of full push or not

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

I donot remember why needed to check this

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
What is the difference? Seems like it would be identical , is there a case it behaves different?

**Comment by ramaraochavali** [comment]
For eds, I do not think it behaves differently?

**Comment by hzxuzhonghu** [comment]
With the check, it means never do delta eds when full push. What we need is to make delta work even for full push.

**Comment by howardjohn** [comment]
> With the check, it means never do delta eds when full push. What we need is to make delta work even for full push.

Isn't it "never do delta eds when *incremental* push."? And incremental is identical to delta

**Comment by ramaraochavali** [comment]
I am confused why do we need "delta" for eds - Is n't it same as what we do now for non full push?

**Comment by hzxuzhonghu** [comment]
Delta eds and incremental eds is not equal.

Say if service is created, we need to do full push. And In Stow, we need to push all the eds of all services.

But for delta, we only need to push eds for the single service.

**Comment by howardjohn** [comment]
but this change only impacts  !full I thought

**Comment by hzxuzhonghu** [comment]
Ok, to align with delta semantics, we also need to notify the removed resources

**Comment by howardjohn** [comment]
But for `!full` there is no removed?

**Comment by hzxuzhonghu** [comment]
I was confused by the double negative check.

**Pull request closed without merging**
