### PR TITLE
Fix bug in slice size

### PR DESCRIPTION
**Pull request by bvwells**
Fix bug in array sizing and relevant test.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by bvwells** [comment]
@kyessenov thanks for the review. I came across this issue a bit randomly while just looking through some of the codebase. Doing a quick search through the code I couldn't convince myself that this code is actually used so might be zero impact...

Might be worth removing if this is the case and it's not work in progress.

**Comment by kyessenov** [comment]
Sounds good. I am not aware of a place we rely on `Names` correctness either. Should be fixed anyways.

**Pull request merged**
