### PR TITLE
[WIP] refactor bookinfo to use different gateway definitions for envoy v1/routing v1alpha1 and envoy v2/routing v1alpha3 

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
Two issues:
1. @frankbu @ZackButcher I did not manage to make `ingressgateway` to work neither on minikube nor on IBM cloud. Could you please try the gateway definition https://github.com/vadimeisenbergibm/istio/blob/01644127058b0e17dd15755916dbc4ae3642d400/samples/bookinfo/routing/bookinfo-gateway.yaml  for bookinfo on some environment and let me know if it works?

2. @rshriram we would have to know how to get the public IP of a worker node of the prow cluster for the NodePort of `ingressgateway`. For reference, this is a list of various ways to get the public IPs of the worker nodes - https://istio.io/docs/guides/bookinfo.html#determining-the-ingress-ip-and-port

**Comment by vadimeisenbergibm** [comment]
@frankbu @ZackButcher @rshriram - good news! @ronenschafferibm found the problem in my Virtual Service - an incorrectly specified destination port. The correct VirtualService is here https://github.com/vadimeisenbergibm/istio/blob/extract_ingress_definition/samples/bookinfo/routing/bookinfo-gateway.yaml, and it works for me.

**Comment by vadimeisenbergibm** [comment]
@rshriram could you please LGTM this PR? The ingress issue was resolved, two tests fail, which should resolved by other PRs.

**Comment by hklai** [comment]
This might have caused the TestUpgrade failure #4937 and possibly TestIngressMetric failure #5270.

Please help fix it or I may have to revert this to unblock daily releases in the 0.8 branch.

**Comment by vadimeisenbergibm** [comment]
@hklai I am sorry, but #4937 is open for 17 days. How could the refactoring in this PR, committed four days ago, have caused this flakiness for 17 days? In my opinion, this flakiness is a general issue related to getting ingress IP in the prow environment. I would consider to increase timeouts/retries, check the issues with LoadBalancer/public IP allocation of the prow cluster. A possible issue could be conflicts on getting a public IP between different tests running on the same prow cluster. These are just my guesses, I am not familiar with the prow environment.

You can revert this PR and check if the flakiness still happens.

Regarding #5270 let me check this. `istio-ingressgateway` was introduced together with v1alpha3 rules and is the recommended way to direct the ingress traffic with v1alpha3. The tests should be updated to reflect this. I will check them and will update #5210 accordingly.

**Comment by vadimeisenbergibm** [comment]
@hklai  Note that the test of #5270 passes currently - https://prow.istio.io/log?job=e2e-suite-rbac-auth&id=1567 .

**Comment by hklai** [comment]
@vadimeisenbergibm sorry it's a bit confusing.

#4937 was opened for a long time as TestUpgrade was flaky. However, it had been failing consistency for a few days, and it had not passed once since 25th. 

See https://prow.istio.io/?type=postsubmit&job=e2e-suite-rbac-auth

/cc @yusuoh who thought deleting the ingress from bookinfo.yaml was the root case of the consistent failure (not flakiness).

**Comment by vadimeisenbergibm** [comment]
@hklai Sorry, my bad, I was distracted by the flakiness issue. Indeed, ingress was moved from bookinfo.yaml to bookinfo-gateway.yaml, and bookinfo-gateway.yaml should be applied in addition to bookinfo.yaml.

@yusuoh You are right, the change in bookinfo.yaml caused the consistent failure.

**Pull request merged**
