### PR TITLE
Helm: Use --set-string instead of --set when applicable

### PR DESCRIPTION
**Pull request by jwendell**
To avoid helm interpreting a tag like `20190806` as float `2.0190806e+07`.

Please provide a description for what this PR is for.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by sdake** [comment]
from the gate:
```
helm template --values /home/prow/go/src/istio.io/istio/charts/istio-cni/values.yaml --name=istio-cni --namespace=kube-system --set 'excludeNamespaces={}' --set cniBinDir=/home/kubernetes/bin --set-string hub=gcr.io/istio-release --set-string tag=master-latest-daily --set-string pullPolicy=IfNotPresent --set logLevel=debug /home/prow/go/src/istio.io/istio/charts/istio-cni
Error: unknown flag: --set-string
```

It appears the test images need a new revision of helm, and a new bottom pin for helm must be determined and added to this release notes prior to this pr merging.

**Comment by howardjohn** [comment]
Looks like introduced in 2.9. Prow uses helm 2.7. I am planning to upgrade helm so hopefully this can just sit here and will magically be fixed soon

**Comment by howardjohn** [comment]
Upgrade to 2.10, as documented as the minimum on istio.io, so this change is safe to make

**Comment by jwendell** [comment]
@howardjohn Created https://github.com/istio/test-infra/pull/1617 - not sure if that's enough for tests.

**Pull request merged**
