### PR TITLE
Decouple upstream connection lifecycle with per stream error

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is after #27881

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
https://github.com/istio/istio/pull/27923#discussion_r505745040 for details

**Comment by hzxuzhonghu** [comment]
@howardjohn This is ready to review.
The healthcheck request process maybe not quit appropriate.

**Comment by hzxuzhonghu** [comment]
@howardjohn Please take a look when you have bandwidth

**Comment by howardjohn** [comment]
I do not think this is the right direction to move in. We are changing the proxy to be a "dumb" proxy that forwards XDS messages, to a "smart" proxy that is initiating the XDS sequence. I am confident this will lead to hard to track down bugs as Envoy and control plane state fall out of sync. One example of a bug caused by this I have noticed is the XDS initialization sequencing is different; with old code, we follow the standard XDS protocol https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol sequence. With new code, we send out 4 requests for CDS, LDS, EDS, RDS immediately.

If we are going to take on this complexity burden, it must be for a huge benefit - and I am not seeing any here. The primary change here is the Envoy<->Agent XDS connection will now "never" close - however, I consider this a bug, not a feature, that will lead to unexpected Envoy behavior.

Its possible there are other benefits I missed, let me know if that is the case!

cc @ramaraochavali @lambdai 

Additionally, if we do move forward with this, we will need to properly attribute the code to xds-relay as I don't want us to be accused of plagarism

**Comment by ramaraochavali** [comment]
+1 to what @howardjohn said - I prefer xds proxy to be dumb rather than smart :-)

**Comment by hzxuzhonghu** [comment]
1. There are some cases that envoy may establish multiple streams with xds-proxy, for example:  envoy upgrade hot restart(someone has implemented this), envoy terminated unexpectedly, it should be restarted.   It will cause a churn to istiod during the upgrade time.

2. To multiplexing one connection for all xds types, in future we may want to change CSR through the same grpc stream as well.

**Comment by howardjohn** [comment]
Envoy termination causes the whole pod to restart and hot restart is no
longer used

**Comment by hzxuzhonghu** [comment]
What i mean is that  some vendor has customized envoy hot restart

**Pull request closed without merging**
