### PR TITLE
Remove broken cluster for pilot dashboard

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR attempts to fix the `e2e_dashboard` broken by a recent PR and changes to envoy->Pilot comm protocol.

I have not tested this locally.

### CODE REVIEW

**Comment by douglas-reid** [comment]
in first test, Mixer never initialized. this could indicate a failure in setup -- possibly `galley` related.

**Comment by douglas-reid** [comment]
Other tests are failing with errors like:
```
Helm install istio install failed install/kubernetes/helm/istio, setValue=--set global.mtls.enabled=true --set global.hub=gcr.io/istio-testing --set global.tag=c0217f559843b8e42a54f0a19ab58ca66aabc094
I0627 19:08:24.169] 2018-06-27T19:08:24.167762Z	error	Failed to deploy Istio with helm.
```

**Comment by hklai** [comment]
Unbelievable timing.
I just sent https://github.com/istio/istio/pull/6677 to revert. Could you rebase and try again?

**Comment by douglas-reid** [comment]
@hklai will do. i need to wait until my local e2e finishes for another PR, and then I'll rebase.

**Comment by douglas-reid** [comment]
trying a concurrent local run. if that passes, i'll ping for an lgtm.

**Comment by douglas-reid** [comment]
Local testing:

```
=== RUN   TestDashboards
=== RUN   TestDashboards/Istio
=== RUN   TestDashboards/HTTP_Service
=== RUN   TestDashboards/TCP_Service
=== RUN   TestDashboards/Mixer
=== RUN   TestDashboards/Pilot
--- PASS: TestDashboards (0.26s)
	dashboard_test.go:78: Validating prometheus in ready-state...
	dashboard_test.go:478: Waiting for prometheus metrics: 0s
	dashboard_test.go:485: Value found for: 'round(sum(irate(istio_request_count[1m])), 0.001)'
	dashboard_test.go:485: Value found for: 'sum(irate(istio_request_count{response_code=~"4.*"}[1m]))'
	dashboard_test.go:485: Value found for: 'sum(irate(istio_request_count{response_code=~"5.*"}[1m]))'
	dashboard_test.go:83: Sentinel metrics found in prometheus.
    --- PASS: TestDashboards/Istio (0.04s)
    	dashboard_test.go:108: For Istio, checking 20 queries.
    --- PASS: TestDashboards/HTTP_Service (0.04s)
    	dashboard_test.go:108: For HTTP Service, checking 14 queries.
    --- PASS: TestDashboards/TCP_Service (0.09s)
    	dashboard_test.go:108: For TCP Service, checking 14 queries.
    --- PASS: TestDashboards/Mixer (0.06s)
    	dashboard_test.go:108: For Mixer, checking 35 queries.
    --- PASS: TestDashboards/Pilot (0.03s)
    	dashboard_test.go:108: For Pilot, checking 18 queries.
```

**Comment by douglas-reid** [comment]
w00t:  `prow/e2e-dashboard.sh — Job succeeded.`

**Pull request merged**
