### PR TITLE
[test-framework] Merging several changes from master

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by ozevren** [comment]
@hklai Could you PTAL? It would be great to land this, so that we can add more testing.

**Comment by hklai** [comment]
@ozevren @nmittler please fix lint errors. =)

The codecov failures were due to refactoring. I can manual merge this after linter errors are fixed.

**Comment by nmittler** [comment]
@hklai I ran `make lint` manually and it passes.  Can you explain why CI is different?

**Comment by nmittler** [comment]
@hklai nm ... I see them locally too.  False alarm ... will fix.

**Comment by nmittler** [comment]
should be fixed now ... we'll see what the CI gods think.

**Comment by hklai** [comment]
Manually merging since prod related tests are passing.

The codecov failures had been fixed by https://github.com/istio/istio/pull/10436

**Pull request merged**
