### PR TITLE
Change messages about failed config map parsing to errors

### PR DESCRIPTION
**Pull request by ymesika**
**Please provide a description of this PR:**

As described in https://github.com/istio/istio/issues/48991 when configmap can't be parsed there is a warning message about it which is easy to miss.
Changing those to errors.

Fixes https://github.com/istio/istio/issues/48991

### CODE REVIEW

**Comment by krisztianfekete** [comment]
Thanks for picking this up!

Can we maybe provide more details on which part of the config caused the failure, so users can mitigate it easier?

**Review by krisztianfekete — COMMENTED** [review]
Thanks for picking this up!

Can we maybe provide more details on which part of the config caused the failure, so users can mitigate it easier?

**Comment by ymesika** [comment]
We can't control the error description generated by the parser.
But I saw in your issue description that it printed only the problematic portion of the yaml. Or did you trim it yourself?

**Comment by krisztianfekete** [comment]
> We can't control the error description generated by the parser. But I saw in your issue description that it printed only the problematic portion of the yaml. Or did you trim it yourself?

Yes, this is the full log entry:
```console
2024-01-25T16:56:50.147366Z	warn	failed to read mesh config from ConfigMap: failed reading MeshConfig config: failed to convert to proto. json: cannot unmarshal bool into Go value of type string. YAML:
accessLogFile: /dev/stdout
accessLogFormat: |
  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)% "%REQ(END-USER)%"
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata:
    ISTIO_META_DNS_CAPTURE: true
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
defaultProviders:
  metrics:
  - prometheus
enablePrometheusMerge: true
extensionProviders:
- envoyOtelAls:
    logFormat:
      labels:
        authority: '%REQ(:AUTHORITY)%'
        host: '%UPSTREAM_HOST%'
        instance: '%ENVIRONMENT(POD_NAME)%'
        istio_client_type: envoyOtelAls
        method: '%REQ(:METHOD)%'
        namespace: '%ENVIRONMENT(POD_NAMESPACE)%'
        path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
        protocol: '%PROTOCOL%'
        reponseCode: '%RESPONSE_CODE%'
        startTime: '[%START_TIME%]'
        traceparent: '%REQ(traceparent)%'
        xForwardedClientCert: '%REQ(x-forwarded-client-cert)%'
      text: |
        [ACCESS LOGS OTEL] [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% "traceparent": "%REQ(traceparent)%" "enduser": "%REQ(END-USER)%"
    port: 4317
    service: opentelemetry-collector.otel.svc.cluster.local
  name: opentelemetry-logging
rootNamespace: istio-system
trustDomain: cluster.local
```

So basically the full config.

**Review by ilrudie — APPROVED** [review]
This seems reasonable to me.

**Review by howardjohn — APPROVED** [review]

**Review by linsun — APPROVED** [review]
Thanks Yossi!

**Pull request merged**
