### PR TITLE
> fix service list concurrent read and write

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix https://github.com/istio/istio/issues/36448

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Do we need to deepcopy in the prod code? That will be costly. Maybe just in registryz you can copy it only

**Comment by kebe7jun** [comment]
> Do we need to deepcopy in the prod code? That will be costly. Maybe just in registryz you can copy it only

DeepCopy does lose performance, but without DeepCopy, concurrent reads and writes to objects do cause problems, and we can't just do DeepCopy inside `registryz`, because it's not fundamentally different from calling writeJSON directly, they all go to read the contents inside the object..

PS: ServiceEntry  https://github.com/istio/istio/blob/9f449d325e325d4b0e3f281586ca988c404d273f/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L511-L514
also do DeepCopy, if we don't use DeepCopy, we may have to make some bigger changes to possibly solve this problem.

**Comment by howardjohn** [comment]
Where are we writing to the map after creation?

**Comment by kebe7jun** [comment]
Service.Attributes.Labels ExportTo LabelSelectors ClusterExternalPorts.

https://github.com/istio/istio/blob/9f449d325e325d4b0e3f281586ca988c404d273f/pilot/pkg/model/service.go#L508-L541

**Comment by kebe7jun** [comment]
Good question, I'll try to find it out later.

**Comment by zijianz** [comment]
@kebe7jun Does it mean that at this time, `registryz` can not be called in an intensive manner? Thanks!

**Comment by rcernich** [comment]
I think the issue here is that we're simply serializing these objects, but the objects themselves are being modified in another thread.  I suspect the code that is doing the modification is most likely holding a lock (e.g. the kube registry), but the code doing the reading (json serializer) is not.  I think the solution would be to lock the object before serializing it to json (`Service` has a publicly accessible mutex).

**Pull request closed without merging**
