### PR TITLE
operator: fix typos in comments and tests

### PR DESCRIPTION
**Pull request by alexandear**
This PR fixes spelling and grammar issues in the `operator` folder.

- [ ] Ambient
- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by ymesika** [comment]
Suggestion - If it's some grammar checking linter/tool you use to find those typos I think a much more beneficial PR would be to add it to the set of CI linters checks we run to future avoid these kinds and fix all current typos in one shot (PR).

**Comment by alexandear** [comment]
@ymesika In general, I agree with the suggestion.

I'm using different tools and self-reading to find typos. Some of them are proprietary and can't be integrated into CI/CD. Also, all spell-checker tools have false positives, so I always re-check their results before creating PR.

istio repo is too big to fix all lint issues in one shot. So, to simplify the review I'm creating medium-large size PRs. 

In the next PRs, I'll choose the most appropriate Open Source spell checker and integrate it into the CI/CD process. Anyway, the tool's configuration sometimes needs to be extended with new "false positive" words.

**Review by hanxiaop — APPROVED** [review]

**Pull request merged**
