### PR TITLE
Remove  normalization for LoadBalancingWeight

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
## 
Since envoy 1.11 https://www.envoyproxy.io/docs/envoy/v1.11.0/intro/version_history

`eds: removed max limit for load_balancing_weight.`

## And to help us figure out who should review this PR, please put an X in all the areas that this PR affects.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I have the same doubt, actually there isn't any.

**Comment by hzxuzhonghu** [comment]
ping @howardjohn

**Comment by rshriram** [comment]
Is 1.11 in istio 1.3?

**Comment by hzxuzhonghu** [comment]
Yes, 1.11 is released in 7.11 

https://github.com/istio/proxy/blob/d78a39943d19ff06a770718a3a20da73d9676548/WORKSPACE#L37-L40

```
# When updating envoy sha manually please update the sha in istio.deps file also
#
# Determine SHA256 `wget https://github.com/istio/envoy/archive/$COMMIT.tar.gz && sha256sum $COMMIT.tar.gz`
# envoy commit date: 09/10/2019
# bazel version: 0.28.1
ENVOY_SHA = "d24427d43edfb1bd722aa781e22f87a11ec51e8d"
```

**Comment by hzxuzhonghu** [comment]
>Do we have any unit test/integration test/even manual testing of this?

Actually no i think

> I am not sure I fully understand the implication of this change.. how did the weight go above 128 before, isn't the weight limited to [0, 100] for ServiceEntry?

Think of one service with >128 endpoints, previously we could not set the weight to the number of the endpoints. ServiceEntry is another case.

**Pull request merged**
