### PR TITLE
control service and policy tracing tags based on api

### PR DESCRIPTION
**Pull request by ramaraochavali**
Currently we add service and policy tags even if some one does not want them. It has couple of problems
- XDS overhead as we add it for every http_connection_manager where tracing is enabled
- Unnecessary tags populated to backends if it is not used

Implements https://github.com/istio/api/pull/3322

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### CODE REVIEW

**Comment by zirain** [comment]
is there a flag similar to this in the past?

**Comment by ramaraochavali** [comment]
> is there a flag similar to this in the past?

I do not remember seeing that.

**Comment by zirain** [comment]
https://github.com/istio/istio/blob/55f2059ce13723b6c40ac73cc085680e90c33adf/pilot/pkg/networking/core/v1alpha3/tracing.go#L603

@ramaraochavali seems removed since v1.19.

**Comment by ramaraochavali** [comment]
hmm.. interesting. Don't understand why they should be on always - we do not use them for example. Are you OK to add a telemetry API change for this or proxyConfig to disable them?

**Comment by zirain** [comment]
that sounds good to me.

**Comment by ramaraochavali** [comment]
are you ok to add `enable_istio_standard_tags`  under https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.proto#L43 - It would be defaulted to true(current behaviour) and folks who do not want can disable it?

**Comment by zirain** [comment]
what about add it into telemetry api?

**Comment by ramaraochavali** [comment]
Same flag under https://github.com/istio/api/blob/master/telemetry/v1alpha1/telemetry.proto#L313? 

Folks we rely on just proxyConfig and not telemetry API - how will it work?

**Comment by zirain** [comment]
> Same flag under https://github.com/istio/api/blob/master/telemetry/v1alpha1/telemetry.proto#L313?
> 
> Folks we rely on just proxyConfig and not telemetry API - how will it work?

If we add it in ProxyConfig, will restart/rollout a must after you change it?

**Comment by zirain** [comment]
> > If we add it in ProxyConfig, will restart/rollout a must after you change it?
> 
> Yes. But the user who is using it in ProxyConfig is already aware of that. May be we should add at both places?

sgtm

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
