### PR TITLE
Move admission configs to v1

### PR DESCRIPTION
**Pull request by howardjohn**
For https://github.com/istio/istio/issues/30822

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
might need https://github.com/helm/helm/issues/7697#issuecomment-613535044 or manual steps for helm

**Comment by costinm** [comment]
Could you throw another value.yaml setting with v1 as default value ? Is it worth it ?

**Review by costinm — APPROVED** [review]

**Comment by howardjohn** [comment]
> Could you throw another value.yaml setting with v1 as default value ? Is it worth it ?

If it was just these 7 lines yes. But this is one of many PRs, and its 10k++ lines (and not just simple ifs). K8s 1.15 usage is near 0 at this point, so that is why we decided to drop support. I think 1.15 support is the only motivation for dual-support, is that accurate?

**Pull request merged**
