### PR TITLE
[WIP] Mixer: Make runtime2 default

### PR DESCRIPTION
**Pull request by ozevren**
Work in progress, not ready for review/checkin

### CODE REVIEW

**Comment by geeknoid** [comment]
So much green!

/lgtm

**Comment by ldemailly** [comment]
/hold

can you measure with on and off using 
https://github.com/istio/istio/tree/master/tools#istio-load-testing-user-guide
before changing the default

we also need to check memory footprint in light of recent reports

**Comment by mandarjog** [comment]
I think this should go ahead now.
We have evidence that runtime2 has ~30% lower over all latency and can drive 33% more throughput in IBM's setup, all other things being equal.

/lgtm

**Comment by mandarjog** [comment]
| runtime | clients | p50 client latency| TPS |
|---------|--------|------------------|------|
| runtime1 | 60 | 51 ms | 1125 |
| runtime1 | 5 | 7 ms | 598 |
| runtime2 | 60 | 36 ms | 1599 |
| runtime2 | 5 | 5 ms | 841 |

@ldemailly we should switch to runtime2.

**Comment by ozevren** [comment]
I have one more fix to push before flipping this bit. I'll do that
tomorrow. Until then, please do not remove /hold on this.

**Pull request merged**
