### PR TITLE
update log scope

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Please provide a description for what this PR is for.
Use scoped log for debugging server.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

https://github.com/istio/istio/issues/13439
https://github.com/istio/istio/issues/15416

### CODE REVIEW

**Comment by Monkeyanator** [comment]
Might be dup of [https://github.com/istio/istio/pull/15547#issuecomment-511885275](https://github.com/istio/istio/pull/15547#issuecomment-511885275)

**Comment by JimmyCYJ** [comment]
> Might be dup of #15547.
> 
> Edit: looks like this is in merge pool, so I'll go ahead and close the other PR.

Sorry, I didn't notice that you already have a PR for the change.

**Pull request merged**
