### PR TITLE
refactor bootstrap_config

### PR DESCRIPTION
**Pull request by knightXun**

### CODE REVIEW

**Comment by knightXun** [comment]
@ozevren I think this pr can be merge before we fix the lint test

**Comment by knightXun** [comment]
@ozevren hi, the e2e-pilot-auth-v1alpha3-v2 failed, how can i retigger it again?

**Comment by ozevren** [comment]
You need to go to the CircleCI UI and click on "Rerun workflow" (or something similarly named) and select "rerun with ssh". You may need to do that after signing-in to CircleCI via your GitHub account.

**Comment by knightXun** [comment]
@ozevren oh,thank you. I see the test is passed.

**Comment by knightXun** [comment]
@ozevren hi, can this pr be merged? thank you.

**Comment by knightXun** [comment]
@ozevren I alse found i have no authority to press `Rerun workflow`, maybe that's the members' right.

**Pull request merged**
