### PR TITLE
support multiple custom hosts

### PR DESCRIPTION
**Pull request by shirleyyLi**
**Please provide a description of this PR:**

We have a requirement in grayscale release. The control plane needs to support multiple custom hosts. And we can separate multiple values ​​with commas. Of course it is still compatible with only one custom host.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
What is the use case?

**Comment by shirleyyLi** [comment]
@hzxuzhonghu 
In grayscale release，we want to only change service's selector without restarting istiod pod.

For example，when we want to release a new version of istiod, if istiod pod supports multiple custom hosts which are `Service Stable` and `Service Canary`. At first, only Service Canary selects the new version. we can use Service Canary and releted envoys to test the new version of istiod pod. And then, the tests are successful, we can make the Service Stable select the new version. Then gradually scale up the new version pod and finally replace the old version.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by hzxuzhonghu** [comment]
Not clear to me, the recommended way is https://istio.io/latest/docs/setup/upgrade/canary/.

**Comment by shirleyyLi** [comment]
@hzxuzhonghu
Your recommended way needs to migrate all of the traffic to the new version, which means the configuration of envoys should be updated and they will be restarted. But we do not want to have impact on the existing sidecar proxies or istio gateways. So using service selector and multiple custom hosts to control direction of the traffic is a better way to us.

**Review by costinm — APPROVED** [review]
Lgtm

**Comment by hzxuzhonghu** [comment]
> which means the configuration of envoys should be updated and they will be restarted. 

Yes, but older envoy connects to new istiod could introduce unexpected error.  Though we always consider the version mismatch, be careful.

**Review by hzxuzhonghu — COMMENTED** [review]
I will approve if you update the `ISTIOD_CUSTOM_HOST` help message as well

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
