### PR TITLE
Avoid that people end up using month' old stale tags from istio.VERSION

### PR DESCRIPTION
**Pull request by ldemailly**
istio.VERSION is a template/placeholder at this point, for almost all of the tags

### CODE REVIEW

**Comment by ldemailly** [comment]
cc @mattdelco I assume the release will still work with this change - is there a way /test that would confirm ?

**Comment by mattdelco** [comment]
Offhand I don't think the release build itself would have a problem with the change, assuming updateVersion.sh is okay with it (and more specifically that "make istio-archive" runs okay.

Having said that, I'm not sure it's appropriate to apply the same treatment to PROXY_TAG.  Regardless, I think the update bot (which runs independently of the release build) might throw a fit.  I haven't looked at the update script recently, but I think part of the reason that istio.deps tracks "lastStableSHA" is because it expects the existing sha in the target file (in this case istio.VERSION) to match "lastStableSHA" before it does the update.  So, worst case is the update bot stops updating the file, and in the best case the bot updates this file and this proposed change to PROXY_TAG be irrelevant the next time the bot runs.

The "replace-by-actual-tag" might be more helpful to people if it was something like "need-to-run-updateVersion-sh" (or whatever the process for helm will be if/when it supersedes the script).

**Comment by douglas-reid** [comment]
/lgtm

We should also update docs related to this generation, I imagine.

**Comment by mattdelco** [comment]
/lgtm

Offhand the only thing I can see that might break is the VM-related tests, but those are still be worked on and updated and if they do break it's probably because they weren't doing something right.

**Comment by ldemailly** [comment]
/test istio-pilot-e2e

can I get a github approve ?

**Pull request merged**
