### PR TITLE
add back semantic validation for iop

### PR DESCRIPTION
**Pull request by richardwxn**
We have schematic validation now, this PR is to add back the semantic validations(including feature validation and type check for specific fields).

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by richardwxn** [comment]
There is a feature validation to check whether automtls and controlplanesecurityenabled is enabled together. So after enabling the validation in this PR some tests failed because of breaking this requirement. And I changed  controlplanesecurityenabled to true during the test setup, but then some tests related to galley would fail, but I don't want to add back those certs removed in https://github.com/istio/istio/pull/20883. So I did some override to disable the controlplanesecurity in some related tests.

Please advise whether it is a correct way to go? @incfly @howardjohn

**Comment by howardjohn** [comment]
controlplanesecurityenabled is legacy anyways, I don't think it applies now. Except maybe if you have galley/mixer running

**Pull request merged**
