### PR TITLE
Use latest 'stable' istio and 'getLatestIstio' script when installing

### PR DESCRIPTION
**Pull request by selmanj**
**What this PR does / why we need it**:
Istio 0.3.0 was released, but is not currently the 'stable' version (according to `downloadIstioCandidate.sh`). This change moves the default back to 0.2.12, and also uses the recommended method of installation rather than attempting to clone the repo.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Small changes to startup-script. Should have no impact on any e2e tests (as it's not covered in any way).

**Release note**:

```NONE
```

/cc @salrashid123 @costinm

### CODE REVIEW

**Comment by mattdelco** [comment]
https://github.com/istio/istio/pull/1940 will address the oversight on downloadIstioCandidate.sh and I wouldn't read into that file too much on indicating stable vs. not.

**Comment by salrashid123** [comment]
since we're enumerating the version number now anyway on selection, maybe just wget the tar.gz direct?
eg:
  - https://github.com/istio/istio/releases/download/0.2.12/istio-0.2.12-linux.tar.gz
  - https://github.com/istio/istio/releases/download/0.3.0/istio-0.3.0-linux.tar.gz

**Comment by selmanj** [comment]
@salrashid123 I initially considered that until I found the `getLatestIstio` script, which seems to be the recommended way to obtain an arbitrary version of istio. While it doesn't too much more than download from the releases page, you could imagine in the future that istio releases might be hosted elsewhere or packaged differently. In that case, it seems reasonable that the script would continue to operate the same.

I don't feel that strongly about this so if you disagree let me know.

**Comment by salrashid123** [comment]
SGTM as-is (i was just offering an alternative)

**Comment by costinm** [comment]
Well, 0.3.0 was released - but there is a bug, so stick with 0.2 for now.

We're also discussing using a :latest_stable label in docker.

**Pull request merged**
