### PR TITLE
Multi inbound cluster route

### PR DESCRIPTION
**Pull request by dozer47528**
Implement of #30951

[x] Networking

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

Based on the example in issue, the envoy clusters and configs looks like this:

```
inbound|80||nginx.default.svc.cluster.local::default_priority::max_connections::4294967295
inbound|80||nginx.default.svc.cluster.local::default_priority::max_pending_requests::4294967295
inbound|80||nginx.default.svc.cluster.local::default_priority::max_requests::4294967295
inbound|80||nginx.default.svc.cluster.local::default_priority::max_retries::4294967295
inbound|80||nginx.default.svc.cluster.local::high_priority::max_connections::1024
inbound|80||nginx.default.svc.cluster.local::high_priority::max_pending_requests::1024
inbound|80||nginx.default.svc.cluster.local::high_priority::max_requests::1024
inbound|80||nginx.default.svc.cluster.local::high_priority::max_retries::3
inbound|80||nginx.default.svc.cluster.local::added_via_api::true
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::cx_active::0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::cx_connect_fail::0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::cx_total::3
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::rq_active::0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::rq_error::0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::rq_success::4
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::rq_timeout::0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::rq_total::4
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::hostname::
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::health_flags::healthy
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::weight::1
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::region::
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::zone::
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::sub_zone::
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::canary::false
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::priority::0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::success_rate::-1.0
inbound|80||nginx.default.svc.cluster.local::127.0.0.1:80::local_origin_success_rate::-1.0
inbound|80||nginx2.default.svc.cluster.local::default_priority::max_connections::4294967295
inbound|80||nginx2.default.svc.cluster.local::default_priority::max_pending_requests::4294967295
inbound|80||nginx2.default.svc.cluster.local::default_priority::max_requests::4294967295
inbound|80||nginx2.default.svc.cluster.local::default_priority::max_retries::4294967295
inbound|80||nginx2.default.svc.cluster.local::high_priority::max_connections::1024
inbound|80||nginx2.default.svc.cluster.local::high_priority::max_pending_requests::1024
inbound|80||nginx2.default.svc.cluster.local::high_priority::max_requests::1024
inbound|80||nginx2.default.svc.cluster.local::high_priority::max_retries::3
inbound|80||nginx2.default.svc.cluster.local::added_via_api::true
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::cx_active::0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::cx_connect_fail::0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::cx_total::3
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::rq_active::0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::rq_error::0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::rq_success::4
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::rq_timeout::0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::rq_total::4
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::hostname::
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::health_flags::healthy
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::weight::1
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::region::
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::zone::
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::sub_zone::
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::canary::false
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::priority::0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::success_rate::-1.0
inbound|80||nginx2.default.svc.cluster.local::127.0.0.1:80::local_origin_success_rate::-1.0
```

```json
{
    "virtual_hosts": [
        {
            "name": "inbound|http|nginx.default.svc.cluster.local|80",
            "domains": [
                "nginx.default.svc.cluster.local",
                "nginx.default.svc.cluster.local:80",
                "nginx",
                "nginx:80",
                "nginx.default.svc",
                "nginx.default.svc:80",
                "nginx.default",
                "nginx.default:80"
            ],
            "routes": [
                {
                    "match": {
                        "prefix": "/"
                    },
                    "route": {
                        "cluster": "inbound|80||nginx.default.svc.cluster.local",
                        "timeout": "0s",
                        "max_stream_duration": {
                            "max_stream_duration": "0s"
                        }
                    },
                    "decorator": {
                        "operation": "nginx.default.svc.cluster.local:80/*"
                    },
                    "name": "default"
                }
            ]
        },
        {
            "name": "inbound|http|nginx2.default.svc.cluster.local|80",
            "domains": [
                "nginx2.default.svc.cluster.local",
                "nginx2.default.svc.cluster.local:80",
                "nginx2",
                "nginx2:80",
                "nginx2.default.svc",
                "nginx2.default.svc:80",
                "nginx2.default",
                "nginx2.default:80"
            ],
            "routes": [
                {
                    "match": {
                        "prefix": "/"
                    },
                    "route": {
                        "cluster": "inbound|80||nginx2.default.svc.cluster.local",
                        "timeout": "0s",
                        "max_stream_duration": {
                            "max_stream_duration": "0s"
                        }
                    },
                    "decorator": {
                        "operation": "nginx2.default.svc.cluster.local:80/*"
                    },
                    "name": "default"
                }
            ]
        },
        {
            "name": "inbound|http|80",
            "domains": [
                "*"
            ],
            "routes": [
                {
                    "match": {
                        "prefix": "/"
                    },
                    "route": {
                        "cluster": "inbound|80||nginx.default.svc.cluster.local",
                        "timeout": "0s",
                        "max_stream_duration": {
                            "max_stream_duration": "0s"
                        }
                    },
                    "decorator": {
                        "operation": "nginx.default.svc.cluster.local:80/*"
                    },
                    "name": "default"
                }
            ]
        }
    ]
}
```

after query with different service name, the final stats will be like this:

```
cluster.inbound|80||nginx.default.svc.cluster.local.upstream_rq_total: 4
cluster.inbound|80||nginx2.default.svc.cluster.local.upstream_rq_total: 4
```

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Doing this routing on the inbound has me a bit concerned. WDYT @bianpengyuan @ramaraochavali @lambdai ?

**Comment by lambdai** [comment]
Two potential issues here
1. istio metric. @bianpengyuan  Please verify.
2. The high level design is that we don't want to couple inbound sidecar with k8s "service" spec. Ideally inbound sidecar is associated with "deployment" because we cannot assume all the inbound requests are all from an existing service.

**Comment by howardjohn** [comment]
Oh thanks @lambdai , I forgot part of the issue we originally changed things. We were seeing 503s when service association was changing.

I agree that inbound should not really be service oriented. We have moved almost everything (expect DR connectionPool settings, which has a design) to be workload oriented already

**Comment by dozer47528** [comment]
@howardjohn @lambdai 
Understand the consider of the high level design.

We can try to resolve this issue by other way.

**Pull request closed without merging**
