### PR TITLE
allow :authority host rewrite

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Allow weighted cluster host rewrite from both `:authority` and `host`

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
LGTM, thanks! Can you add a test case in https://github.com/istio/istio/blob/88dffed9afcb19e789cb31ea0c532cdc2a14b9fc/tests/integration/pilot/common/routing.go#L265 though

**Comment by hzxuzhonghu** [comment]
Make sense

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
