### PR TITLE
Fix duplicates in HTTP domains

### PR DESCRIPTION
**Pull request by howardjohn**
if we have domains like {foo, foo.local}, the order we build matters. If
foo is first, we will build the foo virtual host, then the foo.local.
But if foo.local is first, we build a single virtual host with both
domains, and then a second one with empty domain.

This is broken for three reasons
1. Empty domain list is rejected by envoy
2. The behavior is nondeterministic. Should have stable Service ordering
3. You may explicitly want the non-expanded versions

### CODE REVIEW

**Comment by howardjohn** [comment]
```
name                               old time/op        new time/op        delta
RouteGeneration/gateways-6               44.3ms ± 1%        44.7ms ± 1%   ~     (p=0.667 n=2+2)
RouteGeneration/gateways-shared-6         177ms ± 4%         179ms ± 4%   ~     (p=0.667 n=2+2)
RouteGeneration/empty-6                   760µs ± 1%        1357µs ± 0%   ~     (p=0.333 n=2+2)
RouteGeneration/tls-6                     768µs ± 2%        1379µs ± 1%   ~     (p=0.333 n=2+2)
RouteGeneration/telemetry-6               791µs ± 1%        1426µs ± 0%   ~     (p=0.333 n=2+2)
RouteGeneration/virtualservice-6         1.70ms ± 1%        1.73ms ± 2%   ~     (p=0.667 n=2+2)
```

benchmark shows pretty major increase, but for these cases the numbers in microseconds so its pretty much negligible?

**Comment by howardjohn** [comment]
/hold

think there is a bug

**Review by hzxuzhonghu — COMMENTED** [review]
Just one doubt: why donot we merge the virtualhosts of `test.local:80` and `test.80`, they both has the same fields except the domains

**Comment by howardjohn** [comment]
> Just one doubt: why donot we merge the virtualhosts of test.local:80 and test.80, they both has the same fields except the domains
 
Maybe we can, but it will be tricky since I don't think we have readily accessible info to know they can be collapsed. Its possibly theoretically but would be tricky

**Comment by hzxuzhonghu** [comment]
Maybe I can try to address it later.

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
