### PR TITLE
xds: ensure CDS and EDS filters are the same

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/28402

Related to https://github.com/istio/istio/issues/38709 but probably not
fixing it

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I am not sure if this is the right approach, I am still not sure why no eds request comes after the CDS updated.

**Comment by howardjohn** [comment]
That is just how Envoy works for some reason :shrug: .

Even if they did send a request, it would be indistinguishable from an ACK with our current code.

**Comment by hzxuzhonghu** [comment]
That's bad, envoy / xds should mark ACK explicitly rather than depending on the version_info

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Should backport, it is a bug fix

**Comment by hzxuzhonghu** [comment]
@howardjohn I tested with debug logs open, seems this handle is enopugh.
Here the nonce not equal when a request come. 
https://github.com/istio/istio/blob/dde2015562d8bf0216237322a15dd4625b3530c2/pilot/pkg/xds/ads.go#L383-L390

**Comment by hzxuzhonghu** [comment]
If you think there is still other uncovered cases, feel free to remove the hold

**Comment by howardjohn** [comment]
Sorry not sure I 100% follow https://github.com/istio/istio/pull/39120#issuecomment-1138079606. What is the issue/what should we do instead?

This is based on the XDS doc "The management server should not send a [DiscoveryResponse](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/discovery/v3/discovery.proto#envoy-v3-api-msg-service-discovery-v3-discoveryresponse) for any [DiscoveryRequest](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/discovery/v3/discovery.proto#envoy-v3-api-msg-service-discovery-v3-discoveryrequest) that has a stale nonce. A nonce becomes stale following a newer nonce being presented to Envoy in a [DiscoveryResponse](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/discovery/v3/discovery.proto#envoy-v3-api-msg-service-discovery-v3-discoveryresponse)." (https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol)

**Comment by hzxuzhonghu** [comment]
I misread the code, and thought it return true.


But our judgment seems not right,  a request can have different nonce with previous sent nonce.  should take a look at how envoy

**Comment by howardjohn** [comment]
Right in that case we are supposed to ignore it? I think I am not following
you since I am not sure the connection for this PR and nonce?

**Comment by hzxuzhonghu** [comment]
If we can distinguish a request from ACK, then we no need the update in this pr.

**Comment by hzxuzhonghu** [comment]
@howardjohn After investigating a bit more, i could not find how vs update will lead to a existing cluster update, it can lead to add/remove a cluster.  
In both case, eds push is redundant, including stale cluster endpoints for remove.   


For both, eds requests will come later, and istiod will send the up-to-date eds at once.

**Comment by howardjohn** [comment]
To distinguish things, I think we would need to become stateful. See https://github.com/istio/istio/issues/38709#issuecomment-1136137121, we get 2 requests identical requests (one ACK one request):

```
ClusterLoadAssignment, res=[my-cluster], ver=v2, nonce=nonce-eds-1
ClusterLoadAssignment, res=[my-cluster], ver=v2, nonce=nonce-eds-1
```

However from the Envoy issue (https://github.com/envoyproxy/envoy/issues/13009) it seemed like there was no request at all.. so I am a bit confused.

Either way, good point about VS. Perhaps we don't need this at all. This was mostly something I noticed when debugging https://github.com/istio/istio/issues/38709, but it does *not* fix that issue, and I don't have any concrete examples this fixes

**Pull request closed without merging**
