### PR TITLE
Remove implicit usage of 'busybox:latest'

### PR DESCRIPTION
**Pull request by loewenstein**

### CODE REVIEW

**Comment by sdake** [comment]
@wenchenglu @duderino - Using :latest tags is a security concern.  This should probably be merged into 1.1.

Cheers
-steve

**Comment by sdake** [comment]
@loewenstein woudl you mind rebasing?  We recently had a gate breaking change that merged which is why the gate is red.

Cheers
-steve

**Comment by loewenstein** [comment]
@sdake done

**Comment by loewenstein** [comment]
@sdake could you please retrigger the failing circleci job

**Comment by loewenstein** [comment]
@wenchenglu @duderino all required checks are good now. Only merges-blocked-needs-admin is left.

**Pull request merged**
