### PR TITLE
Treat thrift as a kind of tcp

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
The second commit is cleanups during the investigation.

**Comment by howardjohn** [comment]
@pnovotnak

**Comment by hzxuzhonghu** [comment]
This is to make it work when thrift is specified in portname but thrift feature is not enabled. In this case, it is treated as pure tcp protocol.

**Comment by hzxuzhonghu** [comment]
ping @howardjohn rebased, ptal

**Pull request merged**
