### PR TITLE
Fixed versioning information in the helm chart

### PR DESCRIPTION
**Pull request by scaratec**
Issue: All values is helm have been updated
but 'helm ls' is still showing version 1.1.0
allthough all the images are version 1.1.1.

### CODE REVIEW

**Comment by sdake** [comment]
@scaratec for master, we should be using 1.2.  We have automated tooling to change the versions field, and it looks like the automation in 1.1 wasn't quite working correctly.

@utka ^^

/assign utka

**Comment by utka** [comment]
If the version 1.2, will the install from head just fail?

**Comment by howardjohn** [comment]
We need this type of change to be automated/fix the existing automation we have. Currently this change won't actually do anything since 1.1.x releases are from the release-1.1 branch.

**Pull request closed without merging**
