### PR TITLE
Mac / other make tweaks e2e

### PR DESCRIPTION
**Pull request by ldemailly**
Makefile tweak: don't hide slow commands

Common-tests should be the first to be tested not last
pilot should be last as it is the only ones that have envoy
dependencies (which fail on Mac)

### CODE REVIEW

**Comment by mattdelco** [comment]
I don't have any objection to the change.

Having said that, I had wondered whether init.sh should be the one that's more verbose (in general or perhaps by having it respect the VERBOSE flag in the top-level Makefile [possibly by "porting" init.sh into the Makefile]).  In any case, it would be good for someone to eventually go through the Makefiles and increase the use of $(Q) so that we can have things be relatively quiet for dev but also still have a stream-of-consciousness logged during the builds.

For pilot-test, if it really will only work on Mac then this might be a more elegant option:
<pre>
- test: pilot-test mixer-test security-test broker-test galley-test common-test
+ test: mixer-test security-test broker-test galley-test common-test
+ # pilot tests have dependencies on proxy, which is only available for Linux
+ ifeq ($(GOOS),linux)
+   test: pilot-test 
+ endif
</pre>

**Comment by ldemailly** [comment]
/hold

I am sort of trying to get `make docker` to work too

**Comment by mattdelco** [comment]
I'm guessing that the "FROM scratch" images are relatively trivial but I didn't try.  If you do end up making changes to istio-docker.mk then please consider fixing my typo in "copied form go/out".

**Comment by douglas-reid** [comment]
@ldemailly still working on the docker mac ?

**Comment by ldemailly** [comment]
yes as soon as I get around back to it

**Pull request merged**
