### PR TITLE
make redis op timeout configurable

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

fix: https://github.com/istio/istio/issues/38500

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Comment by diranged** [comment]
@zirain Just so I understand the PR - this allows us to set the `REDIS_OP_TIMEOUT` environment variable on the pilot containers, to override the default of `5s` and instead lower it to something else. Right?

**Comment by howardjohn** [comment]
IMO we shouldn't add so many special cases for these super super obscure cases. You can always just set it to 1s to workaround the merge issues:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-patch-op-timeout
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.redis_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.redis_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          settings:
            op_timeout: 1.0s
```

**Comment by diranged** [comment]
Wait .. really? That's crazy. Unfortunately that is still too high for us - we have done extensive testing, and in our environments we need it set to 0.5s or even lower.  Good to know though.. really strange merge behavior!

**Pull request merged**
