### PR TITLE
Fix the `cni-test` target

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
It seems we don't have a job that runs just `make test`

**Comment by howardjohn** [comment]
I think it runs "racetest".We should actually merge the two targets
probably, we always want to run with race detection

**Comment by ericvn** [comment]
https://github.com/istio/test-infra/blob/master/prow/config/jobs/istio.yaml#L9 as noted by @howardjohn. And the *-test targets are just calling the *-racetest targets anyway.

**Comment by jwendell** [comment]
Yeah, I had noticed that.
What happened is that `make test` is failing for me locally then I realize we don't have a job that runs `make test`. As John mentioned, we should probably merge those targets so that those failures (if they exist at all) are exposed.

**Pull request merged**
