### PR TITLE
Add local minikube test job in circleci

### PR DESCRIPTION
**Pull request by m1093782566**
Per #8598 

This PR add tests for scripts in `test/e2e/local` so that they would be easily broken.

PS. How to make the test job non-required for now?

/assign @hklai @rshriram

### CODE REVIEW

**Comment by m1093782566** [comment]
I am wondering if there is a way to run the test job locally?

**Comment by GregHanson** [comment]
@m1093782566 are you just looking for a way to run e2e tests locally on minikube?  There is not a way to use a job defined in .circleci/config.yaml and run it locally. However, you can run any integration test against minikube using make commands.

```
$ minikube version
minikube version: v0.28.2
```

```
minikube start --kubernetes-version=v1.10.0 --memory 4096 \
    --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
    --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key"
eval $(minikube docker-env)
```
NOTE: you can adjust the `--memory` setting based on what you have available on your machine

Now you can run `make build test-bins docker TAG=XXX HUB=XXXX` to build all the images locally.  HUB and TAG can be set to arbitrary values since none of the images are pushed.  Then you can grab the `make` command from the corresponding circleci test you want to run.  For example: https://github.com/istio/istio/blob/master/.circleci/config.yml#L270
and run `make test/local/noauth/e2e_pilotv2 HUB=XXXX TAG=XXXX`

**Comment by rshriram** [comment]
what I meant was to replace the test setup in existing jobs to use this new thing

**Comment by m1093782566** [comment]
Thanks @GregHanson 

@rshriram I think it's a good idea. I will update this PR soon.

**Pull request closed without merging**
