### PR TITLE
allow node selection parameters in operator chart

### PR DESCRIPTION
**Pull request by jonkerj**
All credits go to @matheusfm. This is a rebase of #31262, since this was closed before anyone took a chance to look at it.

**Please provide a description of this PR:**

Allow kubernetes parameters for node selection in istio-operator helm chart: `nodeSelector`, `tolerations` and `affinity`.
Users can constrain the Istio Operator pod(s) to only be able to run on particular node(s). The new parameters have default values that does not affect the users.

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @jonkerj this looks good to me. Trying typing

```
@googlebot I signed it!
```

**Comment by jonkerj** [comment]
@googlebot I signed it!

**Comment by jonkerj** [comment]
Hmm, I signed using my private email (which is on Google). I'll have to sign from my work address, which isn't a google-associated account. Let me check and re-trigger the bot after that.

**Comment by jacob-delgado** [comment]
> Hmm, I signed using my private email (which is on Google). I'll have to sign from my work address, which isn't a google-associated account. Let me check and re-trigger the bot after that.
> 
> Edit: my GH username was included in my CLA, which should be OK, according to [google](https://cla.developers.google.com/about). Still no cookie 😢

I've had the same happen before. GH usernames aren't sufficient. You can always rewrite your git commit history to change the author.

**Comment by jonkerj** [comment]
I changed the author of my commit, should be OK now. 

I'd look into that bot in the long run if I were you, as not everybody likes to get a Google address in order to be able to contribute, but that's something for a different time I guess 😉

**Comment by jacob-delgado** [comment]
> I changed the author of my commit, should be OK now.
> 
> I'd look into that bot in the long run if I were you, as not everybody likes to get a Google address in order to be able to contribute, but that's something for a different time I guess 😉

There's plenty of people that have a non-google address, myself included.

**Review by jacob-delgado — APPROVED** [review]

**Comment by jonkerj** [comment]
In the meanwhile, is there anything else I can do to keep this moving?

**Comment by jonkerj** [comment]
Hi there, anything I can do?

**Comment by zirain** [comment]
@istio/wg-environments-maintainers need a approval, ptal.

**Review by Monkeyanator — APPROVED** [review]

**Pull request merged**
