### PR TITLE
move ingress controller test to e2e

### PR DESCRIPTION
**Pull request by xiaolanz**
CRD tests against real apis should be in e2e tests. 

address #4319, #4235

### CODE REVIEW

**Comment by nmittler** [comment]
@xiaolanz I'd rather not move this into `/tests/e2e/tests/pilot` until it can be made to use the testing framework under `tests/e2e/framework`.

**Comment by nmittler** [comment]
My main concern is incompatibility with the TestMain in https://github.com/istio/istio/pull/4510.  I've done enough merging over the past 2 weeks that I've been working on the PR ... I'd rather avoid this if possible.  Perhaps move this to another package?

**Comment by kyessenov** [comment]
Moving is fine, but you would need to figure out how exactly these tests
are invoked from the script soup.

**Pull request merged**
