### PR TITLE
get latest GitTag

### PR DESCRIPTION
**Pull request by waret**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
doesn't the command already do this? what is different now?

**Comment by duderino** [comment]
Yes, a link to a bug would be very helpful, but at a minimum we need some sort of description for why this is necessary

**Comment by waret** [comment]
When clone istio/istio repo from scratch and execute these commands, we can see the outputs are different as follows:

```
# git clone https://github.com/istio/istio.git
Cloning into 'istio'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 154379 (delta 22), reused 8 (delta 2), pack-reused 154302
Receiving objects: 100% (154379/154379), 98.02 MiB | 513.00 KiB/s, done.
Resolving deltas: 100% (98373/98373), done.
Checking out files: 100% (3780/3780), done.
# cd istio
# git describe --tags
1.2.0-rc.3-643-g2532d2de4
# git describe --tags "$(git rev-list --tags --max-count=1)"
1.3.0-rc.2
# git describe --long --tags "$(git rev-list --tags --max-count=1)"
1.3.0-rc.2-0-g8710d0006
```

**Comment by howardjohn** [comment]
`1.3.0-rc.2` is not the right tag when on the master branch. I think your change just always gets the latest tag which is not what we want

**Comment by waret** [comment]
Sorry for my misunderstanding

**Pull request closed without merging**
