### PR TITLE
R0.8: Update proxy sha to 38353474

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by rshriram** [comment]
Please grab the latest envoy update as well.

**Comment by qiwzhang** [comment]
Sure,  waiting for proxy-postsubmit job to be done in order to generate proxy artifacts

**Comment by hklai** [comment]
The test failures look concerning, as it is pretty green in postsubmit.
https://k8s-testgrid.appspot.com/istio-postsubmits#circleci-e2e-pilot-noauth-v1alpha3-v2

Could you take a look?

**Comment by qiwzhang** [comment]
replaced with https://github.com/istio/istio/pull/5807

**Pull request closed without merging**
