### PR TITLE
Fix dry-run deactivating default webhook

### LINKED ISSUE #48241: mutatingWebhookConfiguration no-opted when using `istoctl ... --dry-run`
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

running certain `istioctl ... --dry-run` commands basically disable the mutating webhook (`istio-sidecar-injector`) by adding the following
```
    matchLabels:
      istio.io/deactivated: never-match
```
e.g.
```
istioctl install --set values.global.proxy.privileged=true --dry-run
```

### Version

```Text
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.3 (5 proxies)
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/48241.

See:

https://github.com/istio/istio/blob/ed790066c418cda0f9a258af2981dffeba0a6546/istioctl/pkg/tag/generate.go#L77-L79

And:

https://github.com/istio/istio/blob/ed790066c418cda0f9a258af2981dffeba0a6546/istioctl/pkg/tag/generate.go#L133-L144

### CODE REVIEW

**Comment by zirain** [comment]
possiable to add a test?

**Comment by hanxiaop** [comment]
> possiable to add a test?

Sounds good, we can add one to avoid future unexpected changes

**Comment by hanxiaop** [comment]
@zirain I've added a test for the option, but it's a bit tricky to add a test for `istioctl install --dry-run`. This is because the *activated* `istio-sidecar-injector` should not exist in the default installation if the installation is successful. If we were to add a test, the flow would be:

clean environment -> installation failed (we will have a activated istio-sidecar-injector) -> run install in dry-run mode -> check if dry-run failed

which may be too complicated for such a minor option. Instead, in the long term it might be better to consider adding an integration test to verify that the dry-run doesn't actually change anything during installation.

**Review by zirain — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Review by GregHanson — APPROVED** [review]

**Pull request merged**
