### PR TITLE
Cherry-Pick to 1.0: update certificates in tests with expiration time 100 years (#13233)

### PR DESCRIPTION
**Pull request by howardjohn**
This is causing failures of the release tests https://testgrid.k8s.io/istio-release#unit-tests&width=20

### CODE REVIEW

**Comment by howardjohn** [comment]
Lint is not something we can easily fix, its related to not pinning the linter version. Not worth the effort to fix for 1.0

**Comment by hzxuzhonghu** [comment]
Agreed
/lgtm

**Comment by howardjohn** [comment]
/assign @costinm 
I think you are the only owner active

**Comment by howardjohn** [comment]
Not stale

**Pull request merged**
