### PR TITLE
Proxy sha in istio. Api sha is already correct

### PR DESCRIPTION
**Pull request by utka**

### CODE REVIEW

**Comment by duderino** [comment]
@utka I see this sometimes, does this mean we aren't waiting long enough for the proxy image to be created?

```
Downloading envoy debug artifact: curl -fLSs https://storage.googleapis.com/istio-build/proxy/envoy-debug-9d0bda2f5771ebd5733b8492f5aa1c62ba548aa3.tar.gz
curl: (22) The requested URL returned error: 404 
```

**Comment by duderino** [comment]
I will reinvoke the circleci workflow until the proxy image can be fetch then will lgtm and merge this

**Comment by duderino** [comment]
grumble

/retest

**Comment by utka** [comment]
I think it's good to go

**Pull request merged**
