### PR TITLE
manifests: fix gateways.securityContext not work

### PR DESCRIPTION
**Pull request by timonwong**
PR #51234 allows us to configure securityContext for gateways but it does not work for injected gateways and `IstioOperator` resources (failed during merging).

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by hanxiaop — APPROVED** [review]

**Comment by timonwong** [comment]
@hanxiaop thanks! Should we cherry-pick release-1.20 ~ release-1.22? In case of auto cherry-pick failure in older branches (likely release-1.20 to release-1.21), I'd like to send manual cherry-pick then.

**Comment by hanxiaop** [comment]
@timonwong I think so, since https://github.com/istio/istio/pull/51234 was backported to those branches. Thanks for doing this!

**Comment by timonwong** [comment]
@hanxiaop I've send manual PR for release-1.20 & release-1.21 here: #51674 #51675

Can you help me issuing prow commands cherry-picking release-1.22? I think it there is no conflicts

**Pull request merged**
