### PR TITLE
server: split monitoring and readiness mux

### PR DESCRIPTION
**Pull request by ramaraochavali**
Currently debug/monitoring and readiness share the same mux. As a result of that the debug and monitoring handlers are also available on `8080` port. We have a requirement to not expose these debug endpoints outside of pod - So we configured monitoringAddr accodinlgy. But we can not configure httpAddr like that because it exposes readiness probe. This PR splits the mux such that debug/monitoring has one mux used by monitoring server and httpServer has a separate readinessMux.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Don't you want to expose monitoring?

**Comment by ramaraochavali** [comment]
> Don't you want to expose monitoring?

We do not use prometheus directly. We use a local scraper sidecar that runs in the same pod, scrapes that endpoint, converts monitoring stats and pushes it our stats backend in the format needed.

**Comment by hzxuzhonghu** [comment]
Yeah, there is a TODO to remove one server.

**Comment by ramaraochavali** [comment]
Yes.  /version is on 15014 https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/monitoring.go#L48

**Comment by jmazzitelli** [comment]
Kiali Operator will attempt to auto-detect the port (it looks for the new istiod endpoint, otherwise uses the old pilot endpoint):

https://github.com/kiali/kiali-operator/blob/v1.22.0/deploy/kiali/kiali_cr.yaml#L498-L504
https://github.com/kiali/kiali-operator/blob/v1.22.0/roles/default/kiali-deploy/tasks/main.yml#L236

The kiali server helm chart will install a Kiali Server that assumes the default of istiod port 15014: https://github.com/kiali/kiali/blob/master/config/config.go#L388

So if you use the operator, or if you install the server via the server helm chart, you are good.

Note that if all these auto-detections or defaults fail, you can always set the `external_services.istio.url_service_version` to the version URL endpoint.

**Comment by costinm** [comment]
Also based on your use case description, you only need to disable debug and monitoring - no need to move them to a separate port ? We still want to have debug on 8080 with ability to control the bind address ( 127.0.0.1) and have monitoring/readiness on 0.0.0.0 ports.

**Comment by ramaraochavali** [comment]
I have thought about a release notes but we have not documented that `8080` is the debug port. Our documentation refers to `15014` as the debug port https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/. That is why I have not added a release notes.

>  I think this is the PR that caused debug to move.

No. that is not correct. The debug was exposed on both `8080` and `15014` -  This PR just stopped exposing on `8080` - I have not moved the debug port. 

Do you prefer to retain the debug port on both `8080`  and `15014`?

I certainly do not want to create BC issue - But if you want to conditionally add via flag to both - I am fine with that. I can add that env var  default to  true  i.e. add to both in `1.8` and we can remove it in `1.9`.  Please let me know what you prefer.

**Comment by costinm** [comment]
My preference is to keep the debug on 8080 for 1.8, deprecated - because scripts and tools may still use it. That was the original port for debug - 15014 was added later for metrics. 

Technically this didn't cause debug to move - but to stop working the way it did in the past. 

It would be great to add env variable to turn off metrics - if you have this use case. 
Also add an env variable for /debug - to bind it to localhost or disable it. Unfortunately to bind it to localhost we would need readiness to move, and I think having readiness and monitoring on the same port would be better than monitoring and debug, because monitoring clearly can't be localhost only. 

My new PR is doing the opposite of your - allowing everything (including gRPC) to use a single port. That's for a different use
case, and even if they share a port it should still be possible to selectively disable different features. 

Re. release notes - all my debug scripts use 8080, it looks John also was used with it. We should document if debug moves, and we should also document we are planning to bind it to localhost and gradually replace it with the new 'XDS' based debug, which will require authentication. No doubt that unauthenticated and exposed /debug must go away - just need to do it carefully.

BTW - does anyone know if Prometheus requires the monitoring port to be declared as part of the Service ? I thought they look at container port directly ( so they can scan client-only workloads ).

**Comment by costinm** [comment]
Re. release notes - we clearly need to announce the deprecation and how to turn off or do localhost-only debug, and probably update some of the docs.

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/26536 adds env var for `8080` and release notes.

I agree monitoring and readiness should be together because they can not be localhost only.  But as you said that needs readiness port to change. Let us do it little later.

**Pull request merged**
