### PR TITLE
Fix istioctl analyze docs url version error

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix https://github.com/istio/istio/issues/30515

[X] Installation
[X] User Experience

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by adiprerepa — APPROVED** [review]
LGTM

**Comment by kebe7jun** [comment]
@howardjohn  hello, it seems that I can not add `release-note-none` label for this pr, would you plz help me?

**Review by shamsher31 — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
