### PR TITLE
Remove lists from jaeger services template

### LINKED ISSUE #12662: Remove unneeded lists from jaeger templates
**Describe the bug**
Embedded lists in the jaeger template can cause issues with automation tools like kustomize.  The list are not really needed and would be nice if they could be removed.
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml

**Expected behavior**
No Lists in the resource templates.

**Steps to reproduce the bug**

**Version**
1.1.0

**Installation**
helm template, then kubectl apply

**Environment**

**Cluster state**

### PR DESCRIPTION
**Pull request by objectiser**
@kramvan1 Could you please test to confirm this fixes the problem.

Fixes #12662

### CODE REVIEW

**Comment by objectiser** [comment]
@kramvan1 Could you please verify that this fixes your problem.

@ostromart @mandarjog Would you be able to review. Thanks.

**Comment by kramvan1** [comment]
@objectiser yes, this fixes the problem.

**Comment by howardjohn** [comment]
Sorry this slipped through somehow. Is there any compelling reason that this should go into 1.1 (upgrade issues, etc)? If not maybe we can move it into istio/installer for 1.2. We are trying to limit the changes to 1.1 as 1.2 is going to be starting the release process pretty soon.

Thanks for fixing this, sorry again that we missed it

**Comment by objectiser** [comment]
I'm fine with it being moved to 1.2 installer if ok with @kramvan1

**Comment by kramvan1** [comment]
@objectiser @howardjohn thx for fixing, fine with 1.2.

**Comment by douglas-reid** [comment]
Did this make it in the istio/installer ?  I saw some PRs related to tracing go in there recently.  @richardwxn can we close this?

**Comment by richardwxn** [comment]
Related change to remove lists was made in [installer](https://github.com/istio/installer/pull/132)

**Comment by douglas-reid** [comment]
@howardjohn do the backport PRs you have been creating include this change?

**Comment by howardjohn** [comment]
@douglas-reid this did not make it in, I think it slipped through because it was bundled in the big "import tracing" one. We still have the List on 1.2.

**Comment by duderino** [comment]
@objectiser @kramvan1 @ostromart @douglas-reid @howardjohn can someone send this to master and then attempt a cherry pick into release-1.2?

**Comment by howardjohn** [comment]
I don't think we need this in 1.2, this change was made to support Kustomize which is the point of Istio/installer and is already fixed in that repo. We want to minimize changed to the existing installer as much as possible (only bug fixes, which this isn't really or not that ciritical)

**Pull request closed without merging**
