### PR TITLE
Delete reference to old ISTIO_META_PROXY_XDS_VIA_AGENT

### PR DESCRIPTION
**Pull request by linsun**
In discussion with @howardjohn - this flag has been renamed:  PROXY_XDS_VIA_AGENT.  Also no need to enable it in preview any more as it is enabled by default.

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by linsun** [comment]
| /test integ-pilot-k8s-tests_istio
-- | --

**Pull request merged**
