### PR TITLE
ambient upstream: make gateway-api deployment no longer use injection

### PR DESCRIPTION
**Pull request by howardjohn**
For https://github.com/istio/istio/issues/40879

Unlike most PRs as part of upstreaming ambient, this PR involves almost no code specific to ambient. Ambient introduces a new Waypoint concept, which takes a Gateway and runs a deployment, service, etc for it. We already have almost the same config for deploying Gateways (https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment).

When we introduced that feature, we had used injection as a short term mechanism until we solved how upgrades would work (because injection has "solved" upgrades, to some extent). Because we absolutely do not want injection in ambient, this wasn't viable, and pushed us to replace the injection mechanism.

This PR does a few things:
* Remove injection and replace with a Deployment. The resulting pod is equivilent, but the upgrade mechanism is different.
* Move templates from hardcoded in binary to configmap. Watch configmap; on change update deployment/service/etc as needed
* Makes the gatewayclass and deploymentcontroller code support multiple classes which have different config. Today we just have 1 config, but in the ambient branch we have one for waypoints as well. I split that out to keep the PR small though

There is a lot of generated code. This is split into its own commit, so I would recommend just reviewing the first commit

### CODE REVIEW

**Review by costinm — APPROVED** [review]
Not sure I found the code  but I assume we are still compatible with injection based ? 

Should we add a way to turn it off ?

**Comment by ericvn** [comment]
Not sure if there are changes needed in https://raw.githubusercontent.com/istio/istio/release-1.17/samples/helloworld/gateway-api/helloworld-gateway.yaml for this as well, as the external control plane gateway test is now failing.

**Pull request merged**
