### PR TITLE
Update to latest istio/api SHA and delete associated dead Mixer code.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by guptasu** [comment]
In case you are making another iteration on this PR, can you update the SHA to "a924e58fe691274257e2e81d666fb67a4cc67993". Not essential though.

**Comment by geeknoid** [comment]
Yep, I'll grab your latest change in this PR.

**Comment by geeknoid** [comment]
@ozevren Please see the changes to pkg/il tests to accommodate the death of the GlobalConfig type.

**Pull request merged**
