### PR TITLE
Added missing affinity section in istio-discovery helm chart

### PR DESCRIPTION
**Pull request by SandeepVaman**
- Added affinity and tolerations in the deployment manifest of the discovery helm chart
- Added affinity template file for istio discovery helm chart

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by SandeepVaman** [comment]
I have raised a PR for the change required.
Please check and review.
https://github.com/istio/istio/issues/24854

**Review by morvencao — COMMENTED** [review]
/ok-to-test

I believe this can be achieved by k8s overlay, see: https://github.com/istio/istio/tree/master/operator#new-api-customization

**Comment by howardjohn** [comment]
Can you use the k8s overlay?

**Comment by Eslam-mohammed-anwar** [comment]
I am planning to use helm chart to deploy istio without using istioOperator , and helm lack of affinity rules. can we please consider merging this PR

**Pull request closed without merging**
