### PR TITLE
Points deps update to release 0.2

### PR DESCRIPTION
**Pull request by yutongz**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by ldemailly** [comment]
is the same needed every other repo ?

can the tool know which branch it's running from so we don't have to change N files for each branch?

**Comment by yutongz** [comment]
Totally agree.

**Comment by yutongz** [comment]
/test istio-presubmit

Test are not properly triggered.

**Comment by ldemailly** [comment]
I just protected the branch when I saw this PR showing mergeable so maybe that's why the bot wasn't auto testing it

**Comment by yutongz** [comment]
Thanks! And it's running tests now. I don't know, it shouldn't be. I looked at PRs merged to this branch, they all got triggered. Hmm, wired. And there is nothing wrong with Prow.

**Pull request merged**
