### PR TITLE
Use latest labels for identifying IngressGateway workload

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/18773 by using labels that are valid in 1.4 beta.

### CODE REVIEW

**Comment by howardjohn** [comment]
should probably sync the operator add the same labels instead of this change?

**Comment by esnible** [comment]
@howardjohn The operator creates these labels for the Ingress Pod:

```
  labels:
    app: istio-ingressgateway
    operator.istio.io/component: IngressGateway
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.4.0
    release: istio
```

The helm deployment of Istio 1.4 alpha I installed last week used
```
  labels:
    app: istio-ingressgateway
    chart: gateways
    heritage: Tiller
    istio: ingressgateway
    release: istio
```

I don't object to the new labels from the operator.  I was not surprised to lose `chart` and `heritage`.  I was surprised to lose `istio: ingressgateway` and if you agree can you create an Issue for the operator to also include that label?

I will put a hold on this PR to await your decision.

**Comment by howardjohn** [comment]
we should get rid of chart and heritage (like we have) but I think app,
istio, and release should be consistent with the helm charts to avoid
breaking things like istioctl, tests, users tooling, and to be more
consistent, etc. It was not an intentional design decision as far as I know

**Comment by howardjohn** [comment]
If ingress doesn't have `istio: ingressgateway` it will break 99% of users Gateway objects and docs. Proper fix is in operator

**Pull request closed without merging**
