### PR TITLE
fix prom image can not set hub error

### PR DESCRIPTION
**Pull request by zgfh**
when offline install ,I can not change image "busybox",so replace it by promethues image

### CODE REVIEW

**Comment by zgfh** [comment]
I signed it!

**Comment by ostromart** [comment]
I'm confused by what you're trying to do. Why replace a shell command that waits for certs with a prometheus image? What is the problem you're facing?

**Comment by zgfh** [comment]
@ostromart Sorry about not explain clearly,My English is pool. 
when I install istio without internet,I have to change image of "busybox" to "my_registry/busybox" by edit yaml . I cann't change image with this:
`--set prometheus.hub=my_registry/prom `
I think change image of "busybox" to "prometheus" may fix it

**Comment by ostromart** [comment]
The change is not going to give you what you want. We currently don't support changing the busybox image through helm so your only option is to edit the manifest, or fork the istio helm charts and add a template parameter there. If you want to propose an ability to set busybox image path, please open an issue which will allow the Istio community to discuss the proposal.

**Pull request closed without merging**
