### PR TITLE
[release-1.6] cherry pick update cluster info based on injection url #23942

### PR DESCRIPTION
**Pull request by linsun**
fixes: https://github.com/istio/istio/issues/23976

### CODE REVIEW

**Comment by linsun** [comment]
@irisdingbj could you approve this?  (assume test passes)

**Comment by jacob-delgado** [comment]
@linsun can this wait until 1.6.1 or do you consider it a release blocker for 1.6.0? We are trying not to merge anything until the release.

**Comment by linsun** [comment]
hmm I think our 1.6 branch is broken?  The errors don't seem to be related to my change. I'll look at it tmr.

**Comment by linsun** [comment]
@jacob-delgado 1.6.1 is fine.  Thanks.

**Comment by linsun** [comment]
@irisdingbj @jacob-delgado this is ready for approval for 1.6.1

**Pull request merged**
