### PR TITLE
Manually update istio.VERSION for pilot(60e6ed1)

### PR DESCRIPTION
**Pull request by yutongz**
**Release note**:

```release-note
None
```
Let's try one more time, but might fail as well.

### CODE REVIEW

**Comment by sebastienvas** [comment]
Can we use @chxchx framework instead ?

**Comment by yutongz** [comment]
@sebastienvas Yes, we should. It just my personal token is not power enough to create a branch in istio/istio, must be a old token or some reason.

**Comment by ldemailly** [comment]
there is a mesh config change needed first (in shriram's pr)

**Comment by yutongz** [comment]
OK, need for shriram's pr it is.

**Pull request closed without merging**
