### PR TITLE
add ratelimit configmap

### PR DESCRIPTION
**Pull request by zackzhangkai**
Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by zackzhangkai** [comment]
https://github.com/istio/istio/issues/31731

**Review by shamsher31 — APPROVED** [review]

**Comment by bianpengyuan** [comment]
Changes under `sample/bookinfo` does not seem to be related..

**Comment by bianpengyuan** [comment]
Can we please revert those two bookinfo changes? @zackzhangkai if those change are desired, please do them on master first then cherry-pick to 1.9.

**Comment by zackzhangkai** [comment]
@bianpengyuan OK, I will revert this.

**Pull request merged**
