### PR TITLE
Skip broken gateway API test

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by keithmattix — APPROVED** [review]
We should really fix that at some point. Good to skip for now though

**Review by ramaraochavali — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
There are still many cases failure

**Comment by hzxuzhonghu** [comment]
Do we still need this @ericvn

**Comment by howardjohn** [comment]
The ambient issue was unrelated to this PR

**Pull request merged**
