### PR TITLE
Adapt permissions to make productpage microservice work as non-root.

### LINKED ISSUE #14667: Bookinfo productpage microservice crashes when run as non-root userid
**Bug description**

This is a bug related to the productpage microservice of the Istio Bookinfo example.  When run as a non-root userid, the container crashes because it attempts to write log information into a directory/file owned by the root uid.

Note that the bug can be reproduced without Istio being installed, it is a problem with the productpage cointainer. 

**Affected product area (please put an X in all that apply)**

Bookinfo examples

**Steps to reproduce the bug**

```
$ docker run  --user 1001 istio/examples-bookinfo-productpage-v1:1.14.0
touch: cannot touch '/opt/microservices/microservice.log': Permission denied
Traceback (most recent call last):
  File "productpage.py", line 47, in <module>
    logging.basicConfig(filename='microservice.log',filemode='w',level=logging.DEBUG)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/opt/microservices/microservice.log'

```

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
Minimal change to demo microservice to make the image also runnable for different users.

See #14667, the new image must still be consumed.

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
@esnible How to get a new version of this image tagged, so that it can be used in the demo? Currently istio/examples-bookinfo-productpage-v1:1.14.0

**Comment by esnible** [comment]
@frankbu Do you know the answer to https://github.com/istio/istio/pull/14943#issuecomment-503021908 ?

**Comment by c0d1ngm0nk3y** [comment]
> @c0d1ngm0nk3y do we want this to be `istio/examples-bookinfo-productpage-v1:1.15.0`?

I don't know about the versioning, but the issue is not solved until this is actually consumed. For me, this sounds like a minor adjustment. 1.14.X? If it is available, we can use it in the productpage deployment of the bookinfo.

**Comment by frankbu** [comment]
We always update the version of all bookinfo images together, and we've tend to only update the minor version number, so this should be 1.15.0.

The images need to be built and pushed to dockerhub using this script: https://github.com/istio/istio/blob/master/samples/bookinfo/build_push_update_images.sh

**Comment by venilnoronha** [comment]
@c0d1ngm0nk3y can you create a separate PR to update the YAMLs once we merge this? I can push the new images once this PR has been merged.

**Comment by c0d1ngm0nk3y** [comment]
> @c0d1ngm0nk3y can you create a separate PR to update the YAMLs once we merge this?

Just let me know...

**Pull request merged**
