### PR TITLE
attempt to update golangci-lint

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
@geeknoid Setting CPU_NUM to 1 seems to resolve OOM problem.

**Comment by howardjohn** [comment]
@kyessenov lint seems to flake after this change
https://circleci.com/gh/istio/istio/396902?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/istio/istio/396236?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kyessenov** [comment]
Ugh, so I guess it's OOMing again on circle. Should we roll it back? WDYT?

**Comment by howardjohn** [comment]
We could try this https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint maybe?

Its crazy it OOMs when we give it 16gb... I can't repro locally though as it segfaults for me

**Comment by nmittler** [comment]
my PR (#13586) is blocked by this ... can we fix quickly or rollback?

**Comment by kyessenov** [comment]
fix hopefully in #13587

**Comment by nmittler** [comment]
@kyessenov I'm still seeing it happen: https://circleci.com/gh/istio/istio/397680?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kyessenov** [comment]
@nmittler rebase or merge manually. Circle doesn't do that for you automatically.

**Pull request merged**
