### PR TITLE
Create prometheus service account in istio ns

### PR DESCRIPTION
**Pull request by nmnellis**

### CODE REVIEW

**Comment by ldemailly** [comment]
fixes https://github.com/istio/issues/issues/204 ?

**Comment by sdake** [comment]
dup of PR https://github.com/istio/istio/pull/3440

**Comment by linsun** [comment]
While it is a dup, this is a better fix, thank you @nmnellis

**Comment by Nopik** [comment]
Since we are using `{ISTIO_NAMESPACE}`, it makes no sense to mix `{ISTIO_NAMESPACE}` with `istio-system` in the same file. I'd suggest replacing all instantations of `istio-system` in this file to the `{ISTIO_NAMESPACE}`.

**Comment by ldemailly** [comment]
@Nopik you are right, send a PR?

**Comment by jeffmendoza** [comment]
@Nopik That is correct, I put this in #3492, can you check? Thanks.

**Pull request merged**
