### PR TITLE
Derive proxy image from values.global if it exist

### PR DESCRIPTION
**Pull request by deveshkandpal24121990**
**Please provide a description of this PR:**
- `imageName` is hardcoded to "proxyv2" as introduced in this PR -> https://github.com/istio/istio/pull/35996
- This PR fixes the bug and derives `imageName` from `values.global.proxy.image` if it exist
- Added unit test to verify the same

### CODE REVIEW

**Review by ramaraochavali — COMMENTED** [review]
LGTM. @mandarjog @howardjohn can you PTAL?

**Comment by mandarjog** [comment]
we had left out image name ( and proxy init image name) because it has not been used in a long time.
Do we have  evidence that this is still used ?

**Comment by ramaraochavali** [comment]
Yes. We use it

**Review by mandarjog — APPROVED** [review]
Lgtm

**Review by howardjohn — APPROVED** [review]
ty!

**Pull request merged**
