### PR TITLE
Example DNS certificate configuration for istio.io user guide

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: this PR adds an example DNS certificate configuration for the istio.io user guide in https://github.com/istio/istio.io/pull/5152.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
lgtm, you can remove hold once the docs PR lands

**Comment by lei-tang** [comment]
Since https://github.com/istio/istio.io/pull/5152 depends on this PR, this PR should be merged before https://github.com/istio/istio.io/pull/5152. Without this PR, the PR 5152 will fail at link check:
* External link https://raw.githubusercontent.com/istio/istio/master/install/kubernetes/helm/istio/example-values/values-istio-dns-cert.yaml failed: 404 No error

So the hold on this PR is removed.

**Pull request merged**
