### PR TITLE
Update Grafana to 5.0.2

### PR DESCRIPTION
**Pull request by jeffmendoza**
Updating from beta 5.0 to released 5.0. Also update provisioning config to v1 spec.

See http://docs.grafana.org/administration/provisioning for docs on latest provisioning config spec. There should be no noticeable changes in Grafana.

### CODE REVIEW

**Comment by douglas-reid** [comment]
cc: @ldemailly 

@jeffmendoza should we bump this to the latest (5.0.4?) and then submit?

**Comment by jeffmendoza** [comment]
@douglas-reid Yep, done. Thanks for following up on this, I've been meaning to ping it.

**Pull request merged**
