### PR TITLE
Fix delay queue retry

### LINKED ISSUE #46070: delayQueue will loop forever if task function return error
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

i wrote test using delayqueue and found this problem
in pkg/queue/delay.go  work function of struct delayQueue

```
// work takes a channel that signals to stop, and returns a channel that signals the worker has fully stopped
func (d *delayQueue) work(stop <-chan struct{}) (stopped chan struct{}) {
	stopped = make(chan struct{})
	go func() {
		defer close(stopped)
		for {
			select {
			case t := <-d.execute:
				if err := t.do(); err != nil {
					if t.retries < maxTaskRetry {
                                               // below 2 lines will cause problem 
						d.Push(t.do)
						t.retries++
						log.Warnf("Work item handle failed: %v %d times, retry it", err, t.retries)
						continue
					}
					log.Errorf("Work item handle failed: %v, reaching the maximum retry times: %d, drop it", err, maxTaskRetry)
				}
			case <-stop:
				return
			}
		}
	}()
	return
}
```

there's a field called retires , obviously ,the logic should drop the task if it fails for maxTaskRetry+1 times
but the problem is that task recommiting part  d.Push(t.do)

it will call PushDelayed ,and create a new instance task := &delayTask{do: t, runAt: time.Now().Add(delay)}
you see,the retires field will be reset to 0,so the retries field will never get to maxTaskRetry
if this task keeps failing,then it will be pushed to queue and rerun forever

### Version

```Text
the current master branch at least Istio 1.18.1 ,no relation with k8s
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

fix https://github.com/istio/istio/issues/46070

previously it will always retrying if an error returned

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Comment by ramaraochavali** [comment]
Changes Look Good. Test needs to be fixed I think

**Comment by hzxuzhonghu** [comment]
ah, i rebased. will take a look

**Pull request merged**
