### PR TITLE
Bump istio/vendor-istio

### PR DESCRIPTION
**Pull request by loewenstein**
Should go in together with https://github.com/istio/vendor-istio/pull/39

/cc @kyessenov

### CODE REVIEW

**Comment by kyessenov** [comment]
Make sure to update vendor .gitsubmodule with the SHA from master on vendor-istio, after you merge it there. Merge after this PR passes the tests.

**Comment by loewenstein** [comment]
@kyessenov When no change is needed for https://github.com/istio/vendor-istio/pull/39 this PR should  point to a valid git ref in https://github.com/istio/vendor-istio or do we have a rebase-always policy for PR merges? In the latter case I indeed shouldn't have opened this PR already...

**Comment by kyessenov** [comment]
The first PR with a sha from a branch is needed to confirm the update is
possible (e.g. no breakages due to the new versions of the dependency
repos). The same PR is then modified with a sha from the master, since the
branch may get lost.

**Comment by ldemailly** [comment]
hey can you update this asap (to the head of master in vendor)

we should not have the 2 repo get out of sync and @rshriram merged the vendor pr

if this can't go in quickly I'll need to revert the vendor part

**Comment by ldemailly** [comment]
never mind, you did already, thanks

**Pull request merged**
