### PR TITLE
Changed the bug/feature issue template description font to small font

### PR DESCRIPTION
**Pull request by ymesika**
When reading bug/feature reports that were created from the templates I always find it difficult to focus on the user input vs. template description text.
This change will just make the description text smaller to make our life easier.
Other alternatives (such as italic) can be used too.

/assign @geeknoid

### CODE REVIEW

**Comment by geeknoid** [comment]
Hmmm. I bet bug reports will come in where the whole bug report is written in small font.

Let's try and see what happens.

**Comment by geeknoid** [comment]
I think we should revert this change. When you open a bug now, the bug template that shows up for you to edit contains these <sup> sequences which looks terrible and detracts from the text.

**Comment by ymesika** [comment]
_Italic_ ?

**Comment by geeknoid** [comment]
The problem is that what is shown to the user that's editing the bug is raw markdown and not a WYSIWYG view. So any type of annotations, where `<sup>` or `<i>` is still muddying up the 'form' that the user is being asked to fill in.

**Comment by ymesika** [comment]
I meant underscore for italic which isn't that muddying.
Anyway feel free to revert.

**Pull request merged**
