### PR TITLE
enable status flag is not fully honoured

### PR DESCRIPTION
**Pull request by ramaraochavali**
Even though  `PILOT_ENABLE_STATUS` is set to false, we create status reporter and status is published because most of the code checks if `StatusReporter != nil ` and pushes the status. This PR creates status reporter only when it is enabled.
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@howardjohn  Couple of tests in Istoctl `TestWait` and TestVersion` assume that status tracking is on. How do we set the flag to true, specifically for those tests?

**Comment by howardjohn** [comment]
Are we really actually writing the status? Wouldn't it fail with lack of rbac?

The intent here was we need this part of it running for the config tracking mechanism (istioctl wait) and just disable actually writing that to status. Is that not happening?

**Comment by ramaraochavali** [comment]
We may be not actually writing to the CRD. I have n't verified that part. But the entire flow is going through which results in lot of errors like 

```
error	status	Distribution Event Queue overwhelmed, status will be invalid.
```
I did not know about the intent that it needs to be used for `istio ctl wait`. 

What are our options to eliminate that log line? I

**Comment by howardjohn** [comment]
@ramaraochavali are you running before or after https://github.com/istio/istio/commit/23081b9df812b73bad327449b1085a574e98aa09?

**Comment by ramaraochavali** [comment]
@howardjohn we are running before that . I see. I was looking at the code and got confused - why we are running in to this with 100,000. Now it makes sense. :-)

**Pull request closed without merging**
