### PR TITLE
Add all securityContext fields in injected containers

### LINKED ISSUE #17318: Include all securityContext fields in injection template
**Bug description**

Istio's sidecar injection webhook rewrites the pod spec to inject the Istio containers, _after_ the pod spec has been rewritten by the PodSecurityPolicy admission controller to match the applied PSP, but also _before_ the PSP validation (see https://github.com/istio/istio/issues/12231 for more details). In the case the spec injected by Istio would need to be mutated by the PSP admission controller, esp. if the Istio container specs are missing some fields in their `securityContext` which would be injected by the PSP admission controller, the PSP validation would reject the resulting pod spec, and the pods couldn't be created. In the case of a `Deployment`, the `ReplicaSet` description would show an error like:

```
Error creating: pods "httpgo-796d5fdfbf-xhz2x" is forbidden: unable to validate against any pod security policy: []
```

This problem concerns only automatic sidecar injection. Manual injection doesn't have this problem, because in this case the `istioctl kube-inject` is executed before the deployment is created, and therefore before the PSP admission controller mutates the pod spec.

To observe the mutations done by the PSP admission controller (and other controllers):

1. Enable pod security policy in the cluster, and configure a PSP to be applied on your `Deployment`.
1. Inject the `Deployment` manually with `istioctl kube-inject` and create it.
1. Observe the diff between the pod specs of the `Deployment` and the created `Pod`.

For instance for an injected `istio-proxy` container, the diff may look like:
```
       - args:
         - proxy
         - sidecar
...
         - name: POD_NAME
           valueFrom:
             fieldRef:
+              apiVersion: v1
               fieldPath: metadata.name
         - name: POD_NAMESPACE
           valueFrom:
             fieldRef:
+              apiVersion: v1
               fieldPath: metadata.namespace
         - name: INSTANCE_IP
           valueFrom:
             fieldRef:
+              apiVersion: v1
               fieldPath: status.podIP
         - name: ISTIO_META_POD_NAME
           valueFrom:
             fieldRef:
+              apiVersion: v1
               fieldPath: metadata.name
         - name: ISTIO_META_CONFIG_NAMESPACE
           valueFrom:
             fieldRef:
+              apiVersion: v1
               fieldPath: metadata.namespace
         - name: ISTIO_META_INTERCEPTION_MODE
           value: REDIRECT
...
           httpGet:
             path: /healthz/ready
             port: 15020
+            scheme: HTTP
           initialDelaySeconds: 1
           periodSeconds: 2
+          successThreshold: 1
+          timeoutSeconds: 1
         resources:
           limits:
             cpu: "2"
...
             cpu: 100m
             memory: 128Mi
         securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+            - ALL
           readOnlyRootFilesystem: true
           runAsUser: 1337
+        terminationMessagePath: /dev/termination-log
+        terminationMessagePolicy: File
         volumeMounts:
         - mountPath: /etc/istio/proxy
           name: istio-envoy
         - mountPath: /etc/certs/
           name: istio-certs
           readOnly: true
+        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
+          name: testuser-token-lsxfd
+          readOnly: true
+      dnsPolicy: ClusterFirst
+      enableServiceLinks: true
+      nodeName: ...
+      priority: 0
+      restartPolicy: Always
+      schedulerName: default-scheduler
       securityContext:
         fsGroup: 10001
         runAsGroup: 10001
         runAsUser: 10000
+        supplementalGroups:
+        - 1
+      serviceAccount: testuser
       serviceAccountName: testuser
+      terminationGracePeriodSeconds: 30
+      tolerations:
+      - effect: NoExecute
+        key: node.kubernetes.io/not-ready
+        operator: Exists
+        tolerationSeconds: 300
+      - effect: NoExecute
+        key: node.kubernetes.io/unreachable
+        operator: Exists
+        tolerationSeconds: 300
       volumes:
       - emptyDir:
           medium: Memory
         name: istio-envoy
       - name: istio-certs
         secret:
+          defaultMode: 420
           optional: true
           secretName: istio.testuser
```

The relevant mutations are in the `securityContext` of the injected containers, and some annotations:
```
       annotations:
+        container.apparmor.security.beta.kubernetes.io/httpgo: runtime/default
+        container.apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default
+        kubernetes.io/psp: unprivileged
         readiness.status.sidecar.istio.io/applicationPorts: ""
+        seccomp.security.alpha.kubernetes.io/pod: docker/default
         sidecar.istio.io/status: '{"version":"7b4662597b3e803e9e0c812acba79e8dfca00ce0f570cbae5a5cc18940e19ce2","initContainers":null,"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
...
         securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+            - ALL
           readOnlyRootFilesystem: true
           runAsUser: 1337
```

What annotations and fields are injected depends on which PSP the PSP admission controller matched with the pod spec.

Both the security annotations and the fields in `securityContext` need to be injected by Istio's injection webhook in order for the resulting pod spec to pass PSP validation.

This issue tracks **updating Istio's default injection template to include all the `securityContext` fields in injected containers**, even if to set them to default values, so that the PSP admission controller wouldn't need to add / mutate them.

Injecting custom annotations is tracked in https://github.com/istio/istio/issues/17331.

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

All Istio versions.

**Environment where bug was observed (cloud vendor, OS, etc)**

Any cluster with pod security policy enabled.

### PR DESCRIPTION
**Pull request by rlenglet**
Fixes https://github.com/istio/istio/issues/17318

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jammerful** [comment]
@rlenglet I'm interested in seeing this PR merged, as right now istio doesn't work with Pod Security Policy even with the istio cni installed. Do you have a sense of when this might be merged and when this might make it into a release?

**Comment by rlenglet** [comment]
@jammerful you can apply a similar change into your deployment's injection template. You don't have to wait for a new release to apply this change locally. I'm expecting to ship this in 1.3.3, around mid-October.

**Comment by jammerful** [comment]
@rlenglet I was trying to avoid having to change the config map for the side car injector, though I will test that this changed does allow my pod security policy to be used.
On a side note, I stumbled upon [re-invocation of mutating admission controllers](https://github.com/kubernetes/kubernetes/pull/78080), is it correct if the pod security policy's mutating admission controller is marked a `reinvocationPolicy: "IfNeeded"` the istio side car injector's and the pod security policy's mutating admission controllers will work together allowing, technically not requiring setting the fields in this PR explicitly? That being said I still like the fields being set explicitly as it is deterministic.

**Comment by rlenglet** [comment]
> On a side note, I stumbled upon re-invocation of mutating admission controllers, is it correct if the pod security policy's mutating admission controller is marked a reinvocationPolicy: "IfNeeded" the istio side car injector's and the pod security policy's mutating admission controllers will work together allowing, technically not requiring setting the fields in this PR explicitly?

That is very interesting, thanks. However, users may have other admission controllers that could trigger a re-invocation, so I think we can't avoid setting the fields.

**Comment by jammerful** [comment]
> That is very interesting, thanks. However, users may have other admission controllers that could trigger a re-invocation, so I think we can't avoid setting the fields.

Yup this is still needed, as I noted this ensures that istio always runs with the minimal set of permissions (principle of least privilege) no matter what the users kubernetes configuration is (that is what I meant by "deterministic"). In any case, please let me know if you need any help with this, I would be happy to help out to get this over the line.

**Comment by howardjohn** [comment]
lgtm, mention me once its not WIP if you need an approval

**Comment by ericvn** [comment]
Note that this PR is missing the cherrypick label for 1.4. I assume it should be added there as well.

**Comment by thecodejunkie** [comment]
Running into this issue as well, in a PSP enabled cluster with automatic sidecar injection. Unable to validate against any PSP -> ReplicaSet fails to create pods. Will this be fixed for 1.4?

**Comment by howardjohn** [comment]
@rlenglet are you still working on this?

**Comment by rlenglet** [comment]
> @rlenglet are you still working on this?

Yes, I should.

**Comment by btoonk** [comment]
Does this also work for the istioctl installation method or does this require a change in install/kubernetes/operator/charts/istio-control/istio-autoinject/files/injection-template.yaml ?

**Comment by rlenglet** [comment]
@btoonk Do you mean https://github.com/istio/installer/blob/master/istio-control/istio-autoinject/files/injection-template.yaml? Yes, that will need to be updated as well.

**Comment by michaelbannister** [comment]
My colleague and I have spent hours today fighting this before finding the various issues here - without deep knowledge of how the PSP admission controller works it was extremely puzzling! We thought we'd pinned it down to injectedAnnotations for apparmor profiles but looks like we're falling foul of the securityContext as well.

It'd be great to know whether this is likely to be merged soon or whether we have to resort to hacking the configmap!

Given the appeal of Istio from a security perspective it's a great shame not to have it working neatly with pod security policies. (We've also had to overlay all the control plane components to set runAsUser > 0, but that's a separate issue which I think I'll raise tomorrow...)

**Comment by myidpt** [comment]
Ping. It would be great to get this into V1.5 :)

**Comment by rlenglet** [comment]
All test fail because `istio-init` containers are crashing. It seems like it doesn't get `CAP_NET_ADMIN` when using those capabilities:
```
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            drop:
            - ALL
```
The `drop` field seems to have precedence over the `add` field.

**Comment by rlenglet** [comment]
Just found out that iptables requires the `CAP_NET_RAW` capability in addition to `CAP_NET_ADMIN`. `CAP_NET_RAW` is given by default by Docker. I'll fix the PR to not drop it for `istio-init`.

**Comment by rlenglet** [comment]
The automated tests are passing.
And I manually tested that this PR allows running pods with automatic injection and Istio CNI enabled with a very restrictive PodSecurityPolicy.

**Comment by rlenglet** [comment]
Will try this combination to simplify the templates:
```
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
```

**Comment by rlenglet** [comment]
@howardjohn @istio/wg-environments-maintainers @istio/wg-user-experience-maintainers This is ready for review. I am still working on the matching `istio/installer` PR. Thanks!

**Review by liamawhite — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
