### PR TITLE
Update statsd host address in template

### PR DESCRIPTION
**Pull request by tak2siva**

### CODE REVIEW

**Comment by ymesika** [comment]
Can you explain please what issue it solves? Seems like having the namespace suffix was fine.

**Comment by tak2siva** [comment]
@ymesika Looks like in built statsd-exporter has been deprecated. So I configured custom statsd-exporter in [values.yaml](https://github.com/istio/istio/blob/d93e9eb86a104c77275e84077fd20435ab1c9cfa/install/kubernetes/helm/istio/values.yaml#L201) like
```
envoyStatsd:
      enabled: true
      host: statsd.statsd-exporter
      port: 9125
```

But the template appends `.istio-system` and renders envoy configmap like `statsd.statsd-exporter.istio-system`

This makes all the sidecar's to throw `unable to resolve domain` exception.

**Comment by ymesika** [comment]
@tak2siva Makes sense. Can you also add a comment to the `values.yaml` that (if necessary) the host should include the namespace suffix?

**Comment by tak2siva** [comment]
@ymesika Done

**Comment by ymesika** [comment]
Can you please search for other files with `host: # example: statsd-svc` and update all values file?
I personally think just changing to `host: # example: statsd-svc.istio-system` is enough to explain that namespace can be specified.

**Comment by tak2siva** [comment]
@ymesika Updated all values files

**Pull request merged**
