### PR TITLE
fixed bug for port forward to support ipv4 and ipv6

### PR DESCRIPTION
**Pull request by zhlsunshine**
**Please provide a description of this PR:**
fixed bug for port forward to support ipv4 and ipv6
may be related to [issue#40605](https://github.com/istio/istio/issues/40605)

### CODE REVIEW

**Review by GregHanson — COMMENTED** [review]
can you add a [release note](https://github.com/istio/istio/tree/master/releasenotes) for this and include issue linked in the description?

**Review by howardjohn — APPROVED** [review]

**Comment by zhlsunshine** [comment]
> can you add a [release note](https://github.com/istio/istio/tree/master/releasenotes) for this and include the issue linked in the description?

Hi @GregHanson , sure, I will add the release note. Thanks for your commment!

**Comment by zhlsunshine** [comment]
Hi @GregHanson the release note has been added

**Comment by zhlsunshine** [comment]
!Hi @istio/wg-policies-and-telemetry-maintainers  & @istio/release-managers, PTAL for this PR. thanks!

**Review by zirain — APPROVED** [review]

**Comment by GregHanson** [comment]
removing `do-not-merge` after verifying with @zhlsunshine

**Pull request merged**
