### PR TITLE
[release-1.5] feat(injection): add app container name to envoy metadata

### PR DESCRIPTION
**Pull request by douglas-reid**
Manual cherry-pick of: https://github.com/istio/istio/pull/22721

### CODE REVIEW

**Comment by mandarjog** [comment]
@fpesce this contains only 24 lines of code change, everything else is generated.

ISTIO_META_APP_CONTAINERS adds names of containers in the pod as a list.

**Comment by mandarjog** [comment]
/test integ-mixer-k8s-tests_istio_release-1.5
flake

**Comment by mandarjog** [comment]
gentle ping! @fpesce this is ready to go.

**Comment by johnma14** [comment]
@douglas-reid does this need to be added to the release-notes for 1.5.2?

**Comment by douglas-reid** [comment]
@johnma14 It shouldn't impact users directly -- this should mostly be hidden. It matters for extension developers.

If we do want to add it given that, I would suggest something like: "Added application container information to Envoy node metadata."

**Pull request merged**
