### PR TITLE
telemetry: replace wasm stats with native stats for telemetry API

### PR DESCRIPTION
**Pull request by kyessenov**
The new stats extension is only used for telemetry APIs (although it's capable of replacing the default, EnvoyFilter-based one, which can be done manually).
This solves the problem of dynamically adding tags without proxy restarts, and reduces the overall cost of the extension by removing Wasm dependency. 
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
LGTM but we should probably add a feature flag given the (potential) risk?

Is this 100% transparent to users currently (aside from performance) or are there functional differences?

**Comment by kyessenov** [comment]
@howardjohn It's a very experimental feature that was written less than 10 days ago. So yes, it'll be under a flag.

**Comment by kyessenov** [comment]
CI apparently can't parse regular dockerfile???
```2022-10-17T20:46:12.036002Z	warn	dockerfile	Skipping RUN: [set -eux;         apt-get update;     apt-get install -qqy --no-install-recommends         libc++-dev;]```

**Comment by howardjohn** [comment]
You can remove this line:

prow/integ-suite-kind.sh
45:export ISTIO_DOCKER_BUILDER=crane

**Comment by kyessenov** [comment]
CC @zirain 
I think this is a good trafe-off - telemetry API will use native stats while existing EnvoyFilter users can choose to apply https://github.com/istio/istio/pull/41441/commits/a5d49887d4393c86f5a4332c45bc0f9e9df3e0f6 to get native stats. They are functionally almost identical.

**Comment by zirain** [comment]
> CC @zirain I think this is a good trafe-off - telemetry API will use native stats while existing EnvoyFilter users can choose to apply [a5d4988](https://github.com/istio/istio/commit/a5d49887d4393c86f5a4332c45bc0f9e9df3e0f6) to get native stats. They are functionally almost identical.

yes, I think most of the users try `Telemetry` with logging and tracing
but we should mention this in release-notes for v1.16

**Comment by kyessenov** [comment]
@zirain I added a release note describing the change.

**Comment by zirain** [comment]
> @zirain I added a release note describing the change.

I think this maybe a major change, users care about performance will be interest in.
we should point this change out something like https://istio.io/latest/news/releases/1.15.x/announcing-1.15/, WDYT?

I'm not sure of the workflow, maybe need talk to release manger group?

**Comment by kyessenov** [comment]
@zirain I don't want to make strong claims without performance testing, and we lost some of our continuous profiling at the moment. I'll follow up in the release notes, haven't seen the draft yet.

**Comment by zirain** [comment]
> @zirain I don't want to make strong claims without performance testing, and we lost some of our continuous profiling at the moment. I'll follow up in the release notes, haven't seen the draft yet.

we'd better make strong claims as change of default behavior, which I think it's better to end-user.

**Comment by kyessenov** [comment]
@zirain Sure, we will announce the change. I haven't seen the compiled notes yet, but I'll make sure it's visible there.

**Review by zirain — APPROVED** [review]
this's a good start for improving metric performance, thanks @kyessenov

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by howardjohn** [comment]
> @howardjohn It's a very experimental feature that was written less than 10 days ago. So yes, it'll be under a flag.

@kyessenov it doesn't look like its under a flag. Thats fine with me if its for master since we will have ~3 months of soak time. If we are going to cherrypick we should add the flag though

**Review by howardjohn — APPROVED** [review]

**Comment by kyessenov** [comment]
Since we don't have automatic long-running tests, I ran a manual 24h bookinfo test at 100qps. Everything seems to behave as expected, memory and CPU is stable and is slightly better than Wasm version.

24h native stats dashboard:
Screenshot 2022-11-11 10 39 27 AM


Switch to wasm stats:
Screenshot 2022-11-11 12 45 17 PM


FYI @zirain

**Comment by kyessenov** [comment]
There's something unexpected with `istio_response_bytes` metric, will take a look at that later.

**Comment by kyessenov** [comment]
I validated that response bytes difference is probably an artifact of histograms. Curl and envoy agree on bytes sent/received.

**Pull request merged**
