### PR TITLE
format code

### PR DESCRIPTION
**Pull request by IanCao**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by IanCao** [comment]
I signed it!

**Comment by sdake** [comment]
Looks like a legimiate test failure: 

```
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"authentication.istio.io/v1alpha1","kind":"MeshPolicy","metadata":{"annotations":{},"labels":{"app":"security","chart":"security","heritage":"Tiller","release":"istio"},"name":"default","namespace":""},"spec":{"peers":[{"mtls":{"mode":"PERMISSIVE"}}]}}
  generation: 1
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
  name: default
  selfLink: /apis/authentication.istio.io/v1alpha1/meshpolicies/default
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
error: error parsing /tmp/kubedelete515603622.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
authn_policy_test.go:49: command failed: "error: error parsing /tmp/kubedelete515603622.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context\n" exit status 1
```

**Comment by howardjohn** [comment]
failure was fixed in another PR, was not related to this one

/test istio-pilot-e2e-envoyv2-v1alpha3-master

**Pull request merged**
