### PR TITLE
Set `destination_service` to `destination.service.host`

### LINKED ISSUE #17234: The destination service label for tcp connection opened/closed metrics are inconsistent
**Bug description**
Metrics `istio_tcp_connections_closed_total` and `istio_tcp_connections_opened_total` have `destination_service` label set to the `destination.service.name` attribute where as this label should be set to the `destination.service.host` as is done for all other metrics.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`destination_service` label is set to the `destination.service.host` attribute

**Steps to reproduce the bug**
Install Istio and run TCP traffic through the merge, query `istio_tcp_connections_closed_total` and `istio_tcp_connections_opened_total` metric. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3, 1.2, 1.1

### PR DESCRIPTION
**Pull request by nrjpoddar**
Fixes: #17234

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]
/lgtm

Thanks!

**Review by morvencao — APPROVED** [review]

**Comment by nrjpoddar** [comment]
@bianpengyuan I'm guessing we should cherry-pick this in release-1.1, release-1.2 & release-1.3?

@rlenglet would appreciate your input too.

**Comment by bianpengyuan** [comment]
Not sure about release-1.1, but yeah cherry-pick to release-1.2 and release-1.3 sgtm.

**Comment by rlenglet** [comment]
Backporting to 1.3 sgtm.

**Comment by rlenglet** [comment]
@bianpengyuan Adding the labels after the PR has been merged has no effect. You need to comment with e.g. `/cherrypick release-1.3`. Then the bot will react and create the backport.

**Comment by bianpengyuan** [comment]
Hmm @rlenglet  looks like the command does not work for release-1.2?

**Comment by howardjohn** [comment]
Maybe it can't do 2 at once

**Comment by douglas-reid** [comment]
So, i have a concern that by using `destination.service.host` we've introduced an issue in telemetry.

At ingress, spammy XSS attacks may end up setting bad values for `request.host`, which result in NR 404s at ingress.

I _think_ with this change, we are now going to see metrics like the following:

`istio_response_bytes_sum{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="%22%3E%3Cscript%3Ealert('Qualys_XSS_Joomla_2.5.3')%3C%2Fscript%3E",destination_service_name="unknown",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",endpoint="prometheus",instance="10.60.4.57:42422",job="istio-telemetry",namespace="istio-system",permissive_response_code="none",permissive_response_policyid="none",pod="istio-telemetry-7fcb6f85f8-6rz7v",reporter="source",request_protocol="http",response_code="404",response_flags="NR",service="istio-telemetry",source_app="istio-ingressgateway",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"}`

Note the `destination_service` of:

```
"%22%3E%3Cscript%3Ealert('Qualys_XSS_Joomla_2.5.3')%3C%2Fscript%3E"
```

**Comment by douglas-reid** [comment]
Should we have used `destination_service: destination.service.name | destination.service.host | "unknown"` instead?

**Comment by douglas-reid** [comment]
wait, this only updated a few TCP metrics... sigh, i'll keep digging.

**Pull request merged**
