### PR TITLE
Skip export to

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Fix https://github.com/istio/istio/issues/54077

Not sure when exportTo `~` are unfiltered

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@howardjohn Anything wrong?

**Comment by ramaraochavali** [comment]
hmm.. As I said [here](https://github.com/istio/istio/issues/54077#issuecomment-2503556868) - I am working on fix for it. Let me push a [draft PR](https://github.com/istio/istio/pull/54120) ( Haven't tested it for all conditions yet - but basic flows are working). But couple of things missing here I think
- It does not handle update of service with exportTo None
- It does not handle endpoint updates
We can see which of our PR's work better and can decide accordingly

**Comment by hzxuzhonghu** [comment]
> It does not handle update of service with exportTo None

It does, cheked exportTo = `~`

> It does not handle endpoint updates

That's true at some point, endpoint event we do not look up service.

**Comment by hzxuzhonghu** [comment]
>>It does not handle endpoint updates

>That's true at some point, endpoint event we do not look up service.

When looking https://github.com/istio/istio/pull/54101/files, checked the endpointslice event handler,  i think we already did it right.

**Comment by ramaraochavali** [comment]
> It does, cheked exportTo = ~

This is the case I am talking about - Deploy service without exportTo and update it with exportTo: `~` - Then it should trigger a push and remove right? I am not sure if this PR handles that

**Comment by hzxuzhonghu** [comment]
Yes, this case is not handled. 


I will close this, and move discuss to https://github.com/istio/istio/pull/54101.

**Pull request closed without merging**
