### PR TITLE
Enable tests on CentOS Stream 8

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>

**Please provide a description of this PR:**

Issue: #38224

### CODE REVIEW

**Comment by jewertow** [comment]
@howardjohn are you able to load modules `nft_compat` and `nft_chain_nat` on the CI host?

I think that these modules are necessary to run tests on RHEL-based containers, because I analyzed loaded `nf*` modules and if I correctly understood what they do, they are required for current iptables rules to be applied successfully.
```
nft_chain_nat          16384  3
nf_nat                 49152  5 ip6table_nat,nft_chain_nat,iptable_nat,xt_MASQUERADE,xt_REDIRECT
nf_conntrack_netlink    49152  0
nf_conntrack          172032  6 xt_conntrack,nf_nat,nf_conntrack_netlink,xt_connmark,xt_MASQUERADE,xt_REDIRECT
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
nft_counter            16384  15
nft_compat             20480  4
nf_tables             249856  43 nft_compat,nft_counter,nft_chain_nat
nfnetlink              20480  4 nft_compat,nf_conntrack_netlink,nf_tables
```

Below are the dependencies of `nft_compat` and `nft_chain_nat`, which will have to be loaded as well.
```
vagrant@ubuntu-jammy:~/istio$ modprobe --show-depends nft_compat
...
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/x_tables.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nfnetlink.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nf_tables.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nft_compat.ko 
vagrant@ubuntu-jammy:~/istio$ modprobe --show-depends nft_chain_nat
...
insmod /lib/modules/5.15.0-67-generic/kernel/net/ipv4/netfilter/nf_defrag_ipv4.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/ipv6/netfilter/nf_defrag_ipv6.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nf_conntrack.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nf_nat.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nfnetlink.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nf_tables.ko 
insmod /lib/modules/5.15.0-67-generic/kernel/net/netfilter/nft_chain_nat.ko
```
Unfortunately, I cannot be 100% sure that I'm right, because I couldn't reproduce a VM with the kernel modules currently loaded on the CI host, but I was testing these modules on [this VM](https://github.com/jewertow/istio-playground/tree/kernel-modules-for-rhel/kernel-modules-for-rhel-8).

**Comment by howardjohn** [comment]
As far as I can tell those modules are not available on the OS we use (COS)

**Pull request closed without merging**
