### PR TITLE
Prevent Externalname service dns floods

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

This help when the referenced service has an address, 
like it is a k8s service with clusterIP, to it is a ServiceEntry with address previously allocated by istio

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Can you add a test case? What exactly do you mean by "DNS flood" here? Can you give an example?

**Comment by hzxuzhonghu** [comment]
The dns flood is because for a strict-dns cluster, envoy would resolve it periodically. That in knative use case, knative can create many external name service.

**Comment by hzxuzhonghu** [comment]
Yes, i will add unit test if it makes sense to us

**Review by howardjohn — CHANGES_REQUESTED** [review]
The issue is we are creating a STRICT_DNS cluster in Envoy. This queries from every proxy (in sidecar scope) every ~30s (typically -- varies by TTL). This adds up quickly since its N^2.

Envoy proxy DNS requests do not go through NDS, so I don't think this helps resolve the issues we are seeing there. Meanwhile, https://github.com/istio/istio/pull/46332 resolves the issue by removing the STRICT_DNS cluster

**Comment by hzxuzhonghu** [comment]
You are right, just realized envoy dns request is not intercepted. So if we allow envoy DNS resolve request intercepted by iptables,  then we can prevent the DNS floods cause by all kind of strict DNS cluster

**Comment by howardjohn** [comment]
If we already known the answer to the DNS response then  there is no point
telling envoy to do DNS - we can just do eds. Actually that is exactly what
my ExternalName PR does basically

**Comment by hzxuzhonghu** [comment]
This way it has another benefit for those static dns cluster in bootstrap, it will also prevent DNS floods.

The main concern about your patch is its complexity and perf maybe.

**Pull request closed without merging**
