### PR TITLE
[release-1.9] add timeout for remote clusters to become ready (#31876)

### PR DESCRIPTION
**Pull request by stevenctl**
Fixes a single point of failure in multicluster where failure to reach/authenticate/sync with a remote cluster's API server blocks istiod  readiness

### CODE REVIEW

**Comment by stevenctl** [comment]
@jtrbs do you have any idea why the passthroughfilterchain test is so flaky on 1.9? This PR shouldn't really affect it.

**Comment by jtrbs** [comment]
Hi @stevenctl, yeah looks like the "naked" related test cases are flaky after the previous refactors on passthroughfilterchain. Also some VM related. Maybe adding a check for every policy deployment  with https://github.com/istio/istio/blob/50a75bd511a5fdcc6395a2e521e6ad9dcadac944/tests/integration/security/util/framework.go#L279 can improve/give more info? cc @JimmyCYJ

**Comment by stevenctl** [comment]
Yeah, I've seen several PRs land despite those flakes, but maybe I'm especially unlucky with this PR? 

Different tests are failing in each of the jobs, always from primary 2 (cross network primary)

I see the same failures in https://github.com/istio/istio/pull/32345

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
