### PR TITLE
Update Proxy SHA to latest (release-1.0).

### PR DESCRIPTION
**Pull request by PiotrSikora**

### CODE REVIEW

**Comment by kyessenov** [comment]
You think you can just update the SHA ;)
There's @bianpengyuan 's change that was not pulled in and requires changes to tests.

**Comment by PiotrSikora** [comment]
Sigh, the new proxy is crashing at startup due to a bug in Envoy (I believe it's the same issue as: https://github.com/envoyproxy/envoy/pull/3856), which blocks the update until it's fixed upstream.

cc @jasmine-jaksic @costinm @rshriram

**Comment by PiotrSikora** [comment]
Actually, that might be a different issue.

**Comment by kyessenov** [comment]
@hklai this needs to go in first before I pull latest proxy SHA...

**Comment by rshriram** [comment]
closing due to memory leaks in proxy

**Pull request closed without merging**
