### PR TITLE
WIP - SPIRE integration with ambient mesh

### PR DESCRIPTION
**Pull request by shubham-bansal96**
Signed-off-by: Shubham Bansal <shubhambansaliimtgn@gmail.com>

Issue https://github.com/istio/istio/issues/42339

**Please provide a description of this PR:**
This PR includes changes to integrate SPIRE with ambient mesh.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [X] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Any design doc? I don't see how this can work

**Comment by howardjohn** [comment]
ztunnel is fundamentally different than ztunnel wrt to SPIRE/certificates. I would recommend a design doc before spending time on impl to make sure time isn't wasted.

**Comment by howardjohn** [comment]
How does it request? What is in the request?

> Basically once ztunnel receive the workload request with identity,

Ztunnel sends the req, it doesn't get one

BTW, just to be upfront - per https://github.com/istio/ztunnel/issues/251, I am currently a "no" to this proposal, so there will need to be some efforts to convince that this is a desired method

**Comment by shubham-bansal96** [comment]
> How does it request? What is in the request?
> 
> > Basically once ztunnel receive the workload request with identity,
> 
> Ztunnel sends the req, it doesn't get one
> 
> BTW, just to be upfront - per [istio/ztunnel#251](https://github.com/istio/ztunnel/issues/251), I am currently a "no" to this proposal, so there will need to be some efforts to convince that this is a desired method

I tried to make some improvement in this architecture , please take a look and share your thoughts on the same.

Ztunnel new

# Explanation
Here’s how the Ambient Mesh will handle it with SPIRE Integration. The flow will largely remain the same irrespective of whether the pods are on the same node or different.

1. Suppose, App A wants to send a request to App B.Traffic will originate from App A and be tunneled through the Ztunnel. 
2. Ztunnel will detect the location of socket on a fixed path and request a spire agent for SVID via spire delegated API by providing SPIFFE id.
3. Now the spire agent will do all the process related to verification of workload through the spire server and return the SVID to Ztunnel.
4. Once Ztunnel receives the SVID successfully then the request will continue to the destination IP(App B).

# Workflow
Ztunnnel Workflow

If the Ztunnel detects the Admin agent socket, it’ll use that to talk to SPIRE. Else it’ll continue with the current functionality to get the certificate from Istio control-plane.
The proposed architecture/Workflow for SPIRE integration with ambient mesh includes changes only in Ztunnel.

Whenever the request is being made from one workload to another workload, Ztunnel would first check the existence of Admin Agent Socket (SPIRE) on a fixed location.
1. If found then Ztunnel will try to get SVID from spire agent via spire delegated API.
2. If not found then Ztunnel will work with the existing behavior, that is to sign CSR and send it to Istio CA to get a certificate.

Once Ztunnel gets a certificate/SVID successfully, then the request will continue to the destination IP.

**Comment by howardjohn** [comment]
Does SPIRE support the ztunnel pod requesting a cert for `spiffe://NOT-ZTUNNEL-IDENTITY`?

**Comment by linsun** [comment]
> Does SPIRE support the ztunnel pod requesting a cert for `spiffe://NOT-ZTUNNEL-IDENTITY`?

Good q - or does the req cert have to be done by the spire agent?

**Comment by shubham-bansal96** [comment]
> Does SPIRE support the ztunnel pod requesting a cert for `spiffe://NOT-ZTUNNEL-IDENTITY`?

Yes spire support requesting a cert on behalf of another pod using their delegated APIs.
Here is the reference for the same.

https://spiffe.io/docs/latest/deploying/spire_agent/#:~:text=Delegated%20Identity%20API,-SPIRE%20agent%20has&text=This%20API%20is%20intended%20for,are%20defined%20for%20this%20purpose.

**Comment by shubham-bansal96** [comment]
> > Does SPIRE support the ztunnel pod requesting a cert for `spiffe://NOT-ZTUNNEL-IDENTITY`?
> 
> Good q - or does the req cert have to be done by the spire agent?

No. Ztunnel itself can request for cert with the help of Delegated APIs of spire exposed by spire agent.

**Comment by shubham-bansal96** [comment]
> > > Does SPIRE support the ztunnel pod requesting a cert for `spiffe://NOT-ZTUNNEL-IDENTITY`?
> > 
> > 
> > Yes spire support requesting a cert on behalf of another pod using their delegated APIs. Here is the reference for the same.
> > https://spiffe.io/docs/latest/deploying/spire_agent/#:~:text=Delegated%20Identity%20API,-SPIRE%20agent%20has&text=This%20API%20is%20intended%20for,are%20defined%20for%20this%20purpose.
> 
> Thanks for the link. Its not clear to me what this means:
> 
> ```
>     authorized_delegates = [
>         "spiffe://example.org/authorized_client1",
>         "spiffe://example.org/authorized_client2",
>     ]
> ```
> 
> Does this mean ` "spiffe://example.org/authorized_client1"` can get ANY cert?
> 
> What we need is ` "spiffe://example.org/ztunnel"` can get only certificates for workloads on its node. Otherwise it turns each ztunnel into cluster root and the security is out the window

Yes.  "spiffe://example.org/authorized_client1" this means ztunnel can get cert of any workload(attested by Spire) that is running on any node.

You are right, this might cause the security issue. But at this moment i am not sure how we can restrict this with the help of delegated API's or something else.
I am trying to figure it out the same and if i find anything then will share with you.

**Comment by howardjohn** [comment]
I would not feel comfortable exposing an integration that is insecure like this. Also not our initial plans for CA integrations was to support only K8s CSR API (https://github.com/istio/ztunnel/issues/251), not SDS

**Comment by bleggett** [comment]
> > > Does SPIRE support the ztunnel pod requesting a cert for `spiffe://NOT-ZTUNNEL-IDENTITY`?
> > 
> > 
> > Yes spire support requesting a cert on behalf of another pod using their delegated APIs. Here is the reference for the same.
> > https://spiffe.io/docs/latest/deploying/spire_agent/#:~:text=Delegated%20Identity%20API,-SPIRE%20agent%20has&text=This%20API%20is%20intended%20for,are%20defined%20for%20this%20purpose.
> 
> Thanks for the link. Its not clear to me what this means:
> 
> ```
>     authorized_delegates = [
>         "spiffe://example.org/authorized_client1",
>         "spiffe://example.org/authorized_client2",
>     ]
> ```
> 
> Does this mean ` "spiffe://example.org/authorized_client1"` can get ANY cert?
> 
> What we need is ` "spiffe://example.org/ztunnel"` can get only certificates for workloads on its node. Otherwise it turns each ztunnel into cluster root and the security is out the window


SPIRE has the SPIRE agent, but effectively we have to allow `ztunnel` to act as the agent - it has to be able to impersonate workloads, and to some degree we have to trust it not to lie about the workloads it's impersonating.

In terms of trust, there's no security difference between allowing `ztunnel` to have access to workload certs and allowing it to mint workload certs, other than that the latter is more obvious. Kube/Istio CAs and SPIRE CAs both have this problem.

SPIRE's DelegatedIdentityAPI is essentially punting workload attestation to some unknown workload with a SPIFFEID instead of the trust `spire-agent`. The trust domain is the boundary and trust root, which makes perfect sense from an x509 perspective. They don't want to get into the problem of "authorized" cert _use_ because authZ is something they want to keep out of scope. We unfortunately use a global trust domain for the entire cluster (not per node, which is what we should do if we care about that), so this is partially on us.

In CA-land you'd solve this blast-radius problem by using different intermediate certs. 

My understanding is that CSR essentially lets ztunnel mint certs on-behalf-of workloads, and SPIRE can be set up to allow ztunnel to do the same - ztunnel can essentially act as a `spire-agent` and freely mint workload certs (using an intermediate CA it is granted by either the SPIRE server directly, or better yet a SPIRE agent on the node).
 
 I think that's the proper approach for this - ztunnel should be trusted to mint certs for the workloads its impersonating. Letting something else attest workloads and mint workload certs, and then figure out how to safely convey those to a (potentially compromised) ztunnel is both architecturally more complex, and practically slightly worse in terms of security IMO.

**Comment by howardjohn** [comment]
Ztunnel cannot be broadly trusted -- it must only have access to mint certificates _for workloads on its own node_. Otherwise if you take over a node, you get mesh-wide access which is broken. Its trust is scoped to its node.

This aligns with how kubelet works.

I feel like spire-agent must not allow this or it would be pretty terrible for a security POV...?

**Comment by bleggett** [comment]
> Ztunnel cannot be broadly trusted -- it must only have access to mint certificates _for workloads on its own node_. Otherwise if you take over a node, you get mesh-wide access which is broken. Its trust is scoped to its node.
> 
> This aligns with how kubelet works.
> 
> I feel like spire-agent must not allow this or it would be pretty terrible for a security POV...?

I agree - I'm saying the only way to actually prove that this is true/enforce this is have unique intermediate CAs per node that ztunnel mints from.

**Comment by howardjohn** [comment]
> I agree - I'm saying the only way to actually prove that this is true/enforce this is have unique intermediate CAs per node that ztunnel mints from.

Why do you need a unique CA per node? You can just have one CA verify ztunnel lives on the node.

Any CA is going to verify attributes of the peer requesting the cert, it shouldn't need a unique intermediate for each unique attribute.

This is not NIH Istio security btw, its based on Kubernetes own node authz (https://kubernetes.io/docs/reference/access-authn-authz/node/)

> (Or do out-of-band double-checking from the node CA to make sure what ztunnel is asking for is legit - and whatever does that checking and whatever rules it uses have to be trusted)

Yes, this is what we do basically. The CA (Istiod) verifies the requester. CA is trusted

**Comment by bleggett** [comment]
> Why do you need a unique CA per node? You can just have one CA verify ztunnel lives on the node.

You can have a CA verify the impersonator lives on the node, and you also need that CA to verify that the thing the impersonator is requesting a cert for lives on the same node. You need to trust the thing doing both levels of this verification, and if you are using the same CA for that thing across multiple nodes with no node-specific intermediates, that trust getting compromised has a blast radius across all nodes.

If every node has an intermediate CA _and_ that multilevel attestation is tiered between a cross-node CA and node-level intermediate CAs, it mitigates that to a large degree (how SPIRE does it)

> Any CA is going to verify attributes of the peer requesting the cert, it shouldn't need a unique intermediate for each unique attribute.

It doesn't - but if you want to use SPIRE to scope trust domains and do "soft authz" (cluster versus node versus what node A workload B is allowed to do with node A workload C) you need an intermediate for scope. 

_Or_, you need a component that you implicitly trust on top of the CA to enforce authZ. Which is what Kube does. Which works great if you're in Kube, and doesn't work at all outside of it (see VM integ).

> Yes, this is what we do basically. The CA (Istiod) verifies the requester. CA is trusted.

And I'm guessing `istiod` verifies/attests both the requestor and what the requestor is requesting on-behalf-of? 

If so, it's basically a CA, authenticator _and_ a trusted, K8S-specific authorizer collapsed into one. That works in Kube (if you trust the API server) and won't work outside of it, which is why SPIRE doesn't do that.

All this is to say that SPIRE is capable of more than K8S CAs are and so has different design constraints/makes fewer environmental assumptions. Which means I don't believe they can ever give us a `spire-agent` API that will serve our needs 

 - because any API we'd need would break their security model (we'd be asking for non-attestable identity impersonation fenced with environment-specific authz components)
 - and any API they'd give us wouldn't fit nicely into the CSR model (unless we wrote+self-trusted our own authorizer component).
 
One way forward here might be to actually grant ztunnel itself (as attested by SPIRE) multiple SVID identities. SPIRE would go "I know you're ztunnel, and you have 10 registered SVIDs, here they are" and let ztunnel select which one to use. But that would require some prototyping since that's rather unconventional.

**Comment by bleggett** [comment]
The other way forward might be to support one trust domain per node, and then anything upstream of a compromised ztunnel could see that ztunnel belonged to trust domain A, and is trying to impersonate with a cert from trust domain B, and flag that.

**Comment by bleggett** [comment]
> Ztunnel cannot be broadly trusted -- it must only have access to mint certificates _for workloads on its own node_. Otherwise if you take over a node, you get mesh-wide access which is broken. Its trust is scoped to its node.
> 
> This aligns with how kubelet works.
> 
> I feel like spire-agent must not allow this or it would be pretty terrible for a security POV...?

Okay - (and I should have recognized this) actually `Yes. "spiffe://example.org/ztunnel" this means ztunnel can get cert of any workload(attested by Spire) that is running on any node.` is not correct.

DelegatedIdentity API will give the delegatee (`ztunnel` in this case) access to every identity bound to that node's SPIRE Agent via explicit registration.

So, the answer to the question of "what identities can ztunnel impersonate" is "only the identities that have been explicitly tied to _this node's_ SPIRE agent identity". So that should be fine.

**Comment by howardjohn** [comment]
does spire handle that tying automatically or would that be something we
configure?

**Comment by bleggett** [comment]
> does spire handle that tying automatically or would that be something we configure?

Today this is something we tell you to configure correctly out-of-band - it essentially becomes a property of how you declare workload identities, not something Istio cares about or controls.

You can do it manually or automatically, but consumers of this delegation API will effectively only see identities you have explicitly mapped to this node's Agent via declarative SPIRE registrations: https://github.com/spiffe/spire-api-sdk/pull/8#discussion_r678765416

**Pull request closed without merging**
