### PR TITLE
Set envoy's server_name to istio-envoy for inbound listeners

### PR DESCRIPTION
**Pull request by shakti-das**
For issue #5043

### CODE REVIEW

**Comment by shakti-das** [comment]
I signed the CLA

**Comment by shakti-das** [comment]
There is code duplication in listener_test.go, I am not sure whether that test is required for the simple change. Based on reviewers comments, will either modularize the methods or revert the test.

**Comment by rshriram** [comment]
can you please send this to release-1.1 branch?

**Comment by shakti-das** [comment]
> can you please send this to release-1.1 branch?

Sure, I can port this to release-1.1 branch once merged in master.

**Comment by rshriram** [comment]
closing as we will merge release-1.1 to master soon.

**Pull request closed without merging**
