### PR TITLE
Added support for istioctl kube-inject into a Pod

### LINKED ISSUE #6731: istioctl kube-inject does not inject where kind: Pod
**Describe the bug**
Given YAML where kind: Pod, istioctl kube-inject outputs the same input, with no Istio injected.
The injector works where kind is ReplicaSet or Deployment.

**Expected behavior**
Istio configuration injected into my solo Pod

**Steps to reproduce the bug**
Istio 0.8 installed on a new cluster with the helm template method.

`istioctl kube-inject`

Paste in bold:

<pre><b>apiVersion: v1
kind: Pod</b>
apiVersion: v1
kind: Pod
</pre>

<pre><b>apiVersion: v1
kind: Deployment</b>
apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
spec:
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: '{"version":"55c9e544b52e1d4e45d18a58d0b34ba4b72531e45fb6d1572c77191422556ffc","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
    spec:
      containers:
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - istio-proxy
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 10s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-statsd-prom-bridge.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        image: docker.io/istio/proxyv2:0.8.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - ""
        - -d
        - ""
        image: docker.io/istio/proxy_init:0.8.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
</pre>

When running with --log_output_level debug I can see my configmap being returned form the server, and you can see that the correct values are injected where kind is Deployment.

**Version**
```
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No

**Environment**
Client on Mac, Istio on GKE

### PR DESCRIPTION
**Pull request by ymesika**
Currently `istioctl kube-inject` won't inject the sidecar into a Pod object.
However, when enabling the sidecar injector webhook and deploying a Pod object the webhook will inject the sidecar. This PR matches the behaviour.

Fixes #6731

### CODE REVIEW

**Comment by nmittler** [comment]
@ostromart since this is attempting to match the behavior of webhook, want to have a look?

**Comment by ymesika** [comment]
@nmittler @ostromart I was wondering whether this is a valid use case?
If it isn't then we may want to match the other way around - don't inject with webhook.
Please let me know.

**Comment by costinm** [comment]
Do we need this in 1.0 ? If so, please rebase. Seems a safe change.

**Comment by ymesika** [comment]
Replaced by #6903

**Pull request closed without merging**
