### PR TITLE
istioctl: promote envoy-stats command

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

promote `istioctl x es` to `istioctl es`

### CODE REVIEW

**Review by hanxiaop — COMMENTED** [review]
Was this discussed in the WG meeting? I think in the past, we graduated commands after approval in the WG meeting.

**Comment by bleggett** [comment]
Discussed in Nov. 29th WG meeting -> https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#heading=h.3lzzxgz0kjhk

Decision was to _not_ promote `istioctl x es` for the following reasons:
 - Envoy stats are not an Istio API and the current `istioctl` command doesn't value-add anything to the Envoy raw stats output.
 - All Envoy instances Istio ships expose the same `stats` endpoint which can be `curl`ed with a GET -> this is the same as what `istioctl x es` does
 - As `istioctl x es` simply dumps [Envoy's raw, non-human-readable stats endpoint](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--stats), it can be replaced pretty easily with a generic `curl` GET against any Envoy instance's stats endpoint e.g.
 
 ```
k port-forward <envoy_container> 15000:15000
curl localhost:15000/stats > statsdump.json
```` 

To promote experimental `istioctl` commands from experimental, the consensus is they should have more significant value-add than the equivalent `curl GET` command, at least.

**Comment by hanxiaop** [comment]
> To promote experimental istioctl commands from experimental, the consensus is they should have more significant value-add than the equivalent curl GET command, at least.

Makes sense.

**Pull request closed without merging**
