### PR TITLE
Adapt to new service entry port

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

For https://github.com/istio/api/pull/2626

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Sorry I missed https://github.com/istio/api/pull/2626#discussion_r1069641126 on the initial review...

**Comment by hzxuzhonghu** [comment]
This does not even use that field, so i think can be resolved separately

**Review by howardjohn — APPROVED** [review]
Good point

**Comment by ericvn** [comment]
I did do the `make gen` and added a commit, as it would be nice to get this change in so we can have a consistent istio/api and istio/istio before the branch cut happens (should be real soon).

**Review by nmittler — APPROVED** [review]

**Pull request merged**
