### PR TITLE
[1.3] DONT MERGE run another test

### PR DESCRIPTION
**Pull request by lambdai**
Test if we have regression.

Signed-off-by: Yuchen Dai <silentdai@gmail.com>

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
@lambdai I am missing the context of this PR.
Can you add more to the description?
Is this just a WIP PR, not intended to be merged?
What is the corresponding master PR that is cherry-picked here?

**Comment by lambdai** [comment]
@rlenglet This is PR is modifying test case. It is used to detect if we were doing anything wrong in 1.3. 
I don't think we need to merge it as long as all the tests pass.
Alternatively I can run tests on local but my machine is overloaded.
Let's see.

**Comment by lambdai** [comment]
@rlenglet Add DONT MERGE in title. Make my intention clear

**Comment by lambdai** [comment]
Tests are passing. Great! 
I am closing this PR because this PR doesn't introduce bug fix. 
Feel free to loop this PR in if we are fixing anything related to mtls or headless.

**Pull request closed without merging**
