### PR TITLE
Moved subcharts into the istio chart

### PR DESCRIPTION
**Pull request by ymesika**
After #11307 there is no longer need for the subcharts to be shared with others.
Therefore, to better organize the structure moving those into `istio` chart.

In addition, there is no longer a need for `helm dep update`.

Docs will also be updated.

Part of #11306

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Is there a related "master" PR for this change too?

**Comment by morvencao** [comment]
@ymesika So we still need `istio-cni` subchart tar package in `istio/charts` directory? I think I need close https://github.com/istio/istio/pull/11230

**Comment by ymesika** [comment]
> Is there a related "master" PR for this change too?

@jmazzitelli I'm sorry but I'm not familiar with the term master PR and what you mean by that.
Like mentioned in the description this PR is the 2nd phase of an opened issue for getting rid of the `istio-remote` (Issue and 1st phase PR are mentioned there).

> So we still need `istio-cni` subchart tar package in `istio/charts` directory?

@morvencao That's a good question. I think that for the sake of UX we should include the subchart package rather than asking users to run `help dep update` every time. Unless the `istio-cni` stuff isn't static and changes frequently?

**Comment by linsun** [comment]
I think this is a great move, reduced the install steps for istio - thank you @ymesika

**Comment by linsun** [comment]
@wenchenglu can we get this in for 1.1?

cc @costinm @sdake

**Comment by sdake** [comment]
as mentioned in the env wg meeting, this breaks helm package -u.  Also this PR has imploded the release-1.1 gate, causing a complete blockage of all work in release-1.1.  recommend a revert at this point.

**Comment by sdake** [comment]
@wenchenglu please revert this PR.  It is blocking the gate and is incorrect.

Here are the reasons:

`helm package -u` does not work with requirements in the istio helm chart dir
we need `requirements.yaml` for the purposes of conditionalizing the inclusion of subdirs
As `helm package -u` does not work, this breaks daily chart building
helm dep  update is still required even after this pr (or alternately and the recommended path is `helm package -u`

Thanks
-steve

**Comment by jmazzitelli** [comment]
> I'm sorry but I'm not familiar with the term master PR and what you mean by that.

This PR is based on the release-1.1 branch. I don't think we are cherry picking things from release-1.1 to master anymore. So I was asking if you created a second PR that is rebased on master branch so this change can also go into the master branch.

But, now that I explained that - never mind :) From what @sdake said, this needs to be reverted, so don't put this in master :)

**Comment by linsun** [comment]
created a PR for revert - https://github.com/istio/istio/pull/11597

**Comment by linsun** [comment]
@sdake this is breaking because another PR got merged right before this which removed the cni binary (#11230).

**Pull request merged**
