### PR TITLE
fix multiple egress hosts select same service error

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix: https://github.com/istio/istio/issues/33765

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Looks good, wondering if this conflict can be validated

**Comment by kebe7jun** [comment]
why the tests always Expected...

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Yeah, i mean if we can prevent this in galley. Which will be once for all.

**Comment by kebe7jun** [comment]
> Yeah, i mean if we can prevent this in galley. Which will be once for all.

sounds good, I will create another PR to do that.

**Pull request merged**
