### PR TITLE
Disable route timeout for passthrough cluster

### PR DESCRIPTION
**Pull request by chaudyg**
Disable timeout for passthrough cluster, which currently defaults to 15 seconds timeout ([see envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction))

see https://github.com/istio/istio/issues/6861

### CODE REVIEW

**Comment by chaudyg** [comment]
@rshriram @howardjohn do you think this should be backported to previous releases ?

**Comment by chaudyg** [comment]
For anyone needing this before 1.15 is released, the following EnvoyFilter can be used:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-passthrough-timeout
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND # will match outbound listeners in all sidecars
      routeConfiguration:
        portNumber: 80
        vhost:
          name: "allow_any" # match the passthrough route
    patch:
      operation: MERGE
      value:
        route:
          timeout: 0s
```

**Comment by Tharun-Sabbu** [comment]
@chaudyg, thanks for the solution. I'm using istio 1.4.3, will this configuration works for that and what is the timeout 0s means and the port number in the router configuration. Can you please explain

**Pull request merged**
