### PR TITLE
update istio/proxy

### PR DESCRIPTION
**Pull request by JimmyCYJ**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by JimmyCYJ** [comment]
Thanks @howardjohn

**Comment by bianpengyuan** [comment]
@JimmyCYJ I think you need to add port into bootstrap stats_tag like @yxue did in proxy repo: https://github.com/istio/proxy/commit/39398c218d6d7376c71a2d634f319a71155c09bc#diff-b0b4ca38b1b2857af55d520a6489ec4dR52

**Comment by howardjohn** [comment]
/retest

@bianpengyuan may be an issue with stats filter

**Comment by bianpengyuan** [comment]
Yeah, Jimmy is working on updating the tag list in bootstrap.

**Pull request merged**
