### PR TITLE
[release-1.12] Drop packets in INVALID state to avoid intermittent connection reset from sidecar

### PR DESCRIPTION
**Pull request by shonecyx**
Manual cherry-pick of #36566 and #36667

### CODE REVIEW

**Comment by zirain** [comment]
> /test all

I'm not sure this is a correct way to cherry-pick to release-1.12, you'd better ask release-manager in the original PR first.

**Comment by Kmoneal** [comment]
@shonecyx I'm going to try to do a cherry-pick so we have distinct ones. If that doesn't work I am happy to go with this

**Comment by shonecyx** [comment]
> @shonecyx I'm going to try to do a cherry-pick so we have distinct ones. If that doesn't work I am happy to go with this

@Kmoneal  Please go ahead to cherry-pick, thanks.  BTW I see there is UT failure, probably need to fix the UT after the cherry-pick.

**Comment by shonecyx** [comment]
> > /test all
> 
> I'm not sure this is a correct way to cherry-pick to release-1.12, you'd better ask release-manager in the original PR first.

Ack, let me check with release-manager.

**Comment by dgn** [comment]
there's also https://github.com/istio/istio/pull/36752 - why the manual cherry-pick?

**Review by dgn — APPROVED** [review]

**Pull request merged**
