### PR TITLE
DNM Revert "Re-enable stdout logging for e2e (#2593)"

### PR DESCRIPTION
**Pull request by sdake**
This simply tests if the above chagne is responsible for the wedged check.

DO NOT MERGE

This reverts commit 80967e68954f06d5a5987d6dd88d63d92cdba4ba.

### CODE REVIEW

**Comment by sdake** [comment]
@ldemailly apologies for not adding enough detail - have to sleep sometime :)  Several recent PRs are failing on e2e-smoke.sh consistently.

The failure looks like: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2634/e2e-smoke/1445/

**Comment by sdake** [comment]
More details: https://github.com/istio/istio/pull/2634

**Comment by sdake** [comment]
Looks like a transitory issue with e2e-smoke (or someone fixed it last night).

Abandoning this test PR.

**Comment by ldemailly** [comment]
ah ic. there were 2 bugs with rate limit that are now fixed

**Pull request closed without merging**
