### PR TITLE
Cherry-pick OOP adapter fixes to release-1.0

### LINKED ISSUE #8363: Error in translating google.protobuf.Duration in mixer adapter config
**Describe the bug**
When deploying an out-of-process adapter, the following log is observed for a `google.protobuf.Duration` field when it's specified in yaml in the string format.
```
2018-08-30T04:04:19.837110Z	error	field 'flushInterval' is of type 'string' instead of expected type 'google.protobuf.Duration'
```

**Expected behavior**
As per the protobuf [documentation](https://github.com/protocolbuffers/protobuf/blob/d36c0c538a545fac5d9db6ba65c525246d4efa95/src/google/protobuf/duration.proto#L92-L100), it should be possible to translate the field from a string.

**Steps to reproduce the bug**
Follow the out-of-process [adapter guide](https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough) and include a `google.protobuf.Duration` field in the configuration.

The proto definition for the field is as follows.
```proto
google.protobuf.Duration flush_interval = 2 [(gogoproto.nullable) = false, (gogoproto.stdduration) = true];
```

In the failure scenario, the yaml configuration for the field was as follows.
```yaml
  params:
    flushInterval: 5s
```

It worked, however, when the field was expanded to match the `google.protobuf.Duration` type:
```yaml
  params:
    flushInterval:
      seconds: 5
```

**Version**
Istio:
```
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No

**Environment**
Minikube 0.28 (macOS)

**Note**
The same issue was observed when trying to write a test as described in the [guide](https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough#step-6-write-test-and-validate-your-adapter).

### LINKED ISSUE #8379: DURATION is not supported by metric template
**Describe the bug**
The following error is observed in the mixer when trying to apply a metric configuration having an instance for `request.duration` with an out-of-process Istio adapter.

```
2018-08-30T16:53:30.104396Z	error	config does not conforms to schema of template 'metric': unable to build message field: value, unsupported type: DURATION
```

**Expected behavior**
Metrics depending on `request.duration` should work like any other metrics.

**Steps to reproduce the bug**
Use the following instance configuration.

```yaml
apiVersion: "config.istio.io/v1alpha2"
  kind: instance
  metadata:
    name: requestduration
    namespace: istio-system
  spec:
    template: metric
    params:
      value: response.duration | "0ms"
      dimensions:
        source_service: source.service | "unknown"
        source_version: source.labels["version"] | "unknown"
        destination_service: destination.service | "unknown"
        destination_version: destination.labels["version"] | "unknown"
        response_code: response.code | 200
      monitored_resource_type: '"UNSPECIFIED"'
```

**Version**
Istio:
```
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No

**Environment**
Minikube 0.28 (macOS)

### PR DESCRIPTION
**Pull request by venilnoronha**
This PR cherry-picks #7924, #8028 and #8172 on `release-1.0`.

Fixes #8363.
Fixes #8379.

/cc @mandarjog

### CODE REVIEW

**Comment by venilnoronha** [comment]
Thanks for merging this!

**Comment by mandarjog** [comment]
@venilnoronha can you pickup the release-1.0 daily build from tomorrow and ensure it works?

We don't have integration test coverage there.

**Comment by venilnoronha** [comment]
@mandarjog sure, I'll send an update tomorrow.

**Comment by venilnoronha** [comment]
I see the `Duration` and other metrics fine; however, here's the initial log I observe with the nightly build:

```
2018-10-10T18:25:13.849952Z	info	Publishing 15 events
2018-10-10T18:25:13.850345Z	error	failed to evaluate expression for field 'Dimensions[destination_workload_namespace]'; unknown attribute destination.workload.namespace
2018-10-10T18:25:13.850494Z	error	failed to evaluate expression for field 'Value'; unknown attribute request.size
2018-10-10T18:25:13.850538Z	error	failed to evaluate expression for field 'Variables[sourceOwner]'; unknown attribute source.owner
2018-10-10T18:25:13.850557Z	error	failed to evaluate expression for field 'Value'; unknown attribute connection.received.bytes
2018-10-10T18:25:13.850570Z	error	failed to evaluate expression for field 'Value'; unknown attribute connection.sent.bytes
2018-10-10T18:25:13.850584Z	error	failed to evaluate expression for field 'Value'; unknown attribute response.duration
2018-10-10T18:25:13.850655Z	error	error evaluating AttributeBinding expression for attribute key 'source.labels': unknown attribute source.labels
2018-10-10T18:25:13.850725Z	error	failed to evaluate expression for field 'Value'; unknown attribute response.size
2018-10-10T18:25:13.850744Z	error	failed to evaluate expression for field 'Variables[connectionEvent]'; unknown attribute connection.event
2018-10-10T18:25:13.850785Z	error	unknown attribute context.protocol
2018-10-10T18:25:13.850798Z	error	Handler not found: handler='handler.stdio'
2018-10-10T18:25:13.850818Z	error	No valid actions found in rule
2018-10-10T18:25:13.850937Z	error	unknown attribute context.protocol
2018-10-10T18:25:13.850969Z	error	Handler not found: handler='handler.prometheus'
2018-10-10T18:25:13.850974Z	error	No valid actions found in rule
2018-10-10T18:25:13.850992Z	error	unknown attribute context.protocol
2018-10-10T18:25:13.851000Z	error	Handler not found: handler='handler.kubernetesenv'
2018-10-10T18:25:13.851005Z	error	No valid actions found in rule
2018-10-10T18:25:13.851012Z	error	Handler not found: handler='handler.kubernetesenv'
2018-10-10T18:25:13.851016Z	error	No valid actions found in rule
2018-10-10T18:25:13.851030Z	error	unknown attribute context.protocol
2018-10-10T18:25:13.851071Z	error	Handler not found: handler='handler.stdio'
2018-10-10T18:25:13.851078Z	error	No valid actions found in rule
2018-10-10T18:25:13.851092Z	error	unknown attribute context.protocol
2018-10-10T18:25:13.851100Z	error	Handler not found: handler='handler.prometheus'
2018-10-10T18:25:13.851104Z	error	No valid actions found in rule
2018-10-10T18:25:13.851109Z	info	Built new config.Snapshot: id='2'
2018-10-10T18:25:13.851156Z	info	Cleaning up handler table, with config ID:1
2018-10-10T18:25:15.421138Z	info	Publishing 2 events
2018-10-10T18:25:15.421357Z	error	error evaluating AttributeBinding expression for attribute key 'destination.workload.uid': unknown attribute destination.workload.uid
2018-10-10T18:25:15.421415Z	error	failed to evaluate expression for field 'Value'; unknown attribute response.size
2018-10-10T18:25:15.421446Z	error	failed to evaluate expression for field 'Value'; unknown attribute connection.sent.bytes
2018-10-10T18:25:15.421461Z	error	failed to evaluate expression for field 'Value'; unknown attribute response.duration
2018-10-10T18:25:15.421550Z	error	failed to evaluate expression for field 'Variables[sentBytes]'; unknown attribute connection.sent.bytes
2018-10-10T18:25:15.421586Z	error	failed to evaluate expression for field 'Variables[sourceApp]'; unknown attribute source.labels
2018-10-10T18:25:15.421616Z	error	failed to evaluate expression for field 'Value'; unknown attribute connection.received.bytes
2018-10-10T18:25:15.421636Z	error	failed to evaluate expression for field 'Dimensions[source_workload_namespace]'; unknown attribute source.workload.namespace
2018-10-10T18:25:15.421649Z	error	failed to evaluate expression for field 'Value'; unknown attribute request.size
2018-10-10T18:25:15.421673Z	error	unknown attribute context.protocol
2018-10-10T18:25:15.421685Z	error	Instance not found: instance='accesslog.logentry'
2018-10-10T18:25:15.421689Z	error	No valid instances found
2018-10-10T18:25:15.421693Z	error	No valid actions found in rule
2018-10-10T18:25:15.421706Z	error	unknown attribute context.protocol
2018-10-10T18:25:15.421719Z	error	Handler not found: handler='handler.prometheus'
2018-10-10T18:25:15.421722Z	error	No valid actions found in rule
2018-10-10T18:25:15.421841Z	error	unknown attribute context.protocol
2018-10-10T18:25:15.421854Z	error	Instance not found: instance='attributes.kubernetes'
2018-10-10T18:25:15.421856Z	error	No valid instances found
2018-10-10T18:25:15.421858Z	error	No valid actions found in rule
2018-10-10T18:25:15.421865Z	error	unknown attribute context.protocol
2018-10-10T18:25:15.421869Z	error	Handler not found: handler='handler.prometheus'
2018-10-10T18:25:15.421871Z	error	No valid actions found in rule
2018-10-10T18:25:15.421875Z	error	Instance not found: instance='attributes.kubernetes'
2018-10-10T18:25:15.421877Z	error	No valid instances found
2018-10-10T18:25:15.421881Z	error	No valid actions found in rule
2018-10-10T18:25:15.421886Z	error	unknown attribute context.protocol
2018-10-10T18:25:15.421891Z	error	Instance not found: instance='tcpaccesslog.logentry'
2018-10-10T18:25:15.421893Z	error	No valid instances found
2018-10-10T18:25:15.421894Z	error	No valid actions found in rule
2018-10-10T18:25:15.421899Z	info	Built new config.Snapshot: id='3'
2018-10-10T18:25:15.422011Z	info	Cleaning up handler table, with config ID:2
2018-10-10T18:25:16.430489Z	info	Publishing 2 events
2018-10-10T18:25:16.434446Z	error	Handler not found: handler='handler.prometheus'
2018-10-10T18:25:16.434471Z	error	No valid actions found in rule
2018-10-10T18:25:16.434498Z	error	Handler not found: handler='handler.prometheus'
2018-10-10T18:25:16.434502Z	error	No valid actions found in rule
```

**Comment by mandarjog** [comment]
Do these errors ever resolve ?

**Comment by venilnoronha** [comment]
Yup, I don't see them after a few seconds.

**Pull request merged**
