### PR TITLE
[kiali] update to kiali 1.72.0

### PR DESCRIPTION
**Pull request by jmazzitelli**
**Please provide a description of this PR:**

Updates the Kiali addon to the latest 1.72 release for use with Istio 1.19.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
testing looks good:

```
$ kubectl apply -f kiali.yaml 
serviceaccount/kiali created
configmap/kiali created
clusterrole.rbac.authorization.k8s.io/kiali-viewer created
clusterrole.rbac.authorization.k8s.io/kiali created
clusterrolebinding.rbac.authorization.k8s.io/kiali created
role.rbac.authorization.k8s.io/kiali-controlplane created
rolebinding.rbac.authorization.k8s.io/kiali-controlplane created
service/kiali created
deployment.apps/kiali created
```

```
$ kubectl get pods -n istio-system -l app.kubernetes.io/name=kiali
NAME                     READY   STATUS    RESTARTS   AGE
kiali-7c9d5f9f96-rlr85   1/1     Running   0          50s
```

```
$ kubectl logs -n istio-system -l app.kubernetes.io/name=kiali --tail=-1
{"level":"info","time":"2023-08-08T11:56:20Z","message":"Adding a RegistryRefreshHandler"}
2023-08-08T11:56:20Z INF Kiali: Version: v1.72.0, Commit: 7208cd1767e8347b00bff10391130d7bcc824548, Go: 1.20.5
2023-08-08T11:56:20Z INF Using authentication strategy [anonymous]
2023-08-08T11:56:20Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2023-08-08T11:56:20Z INF Some validation errors will be ignored [KIA1301]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2023-08-08T11:56:20Z INF Initializing Kiali Cache
2023-08-08T11:56:20Z INF Adding a RegistryRefreshHandler
2023-08-08T11:56:20Z INF [Kiali Cache] Waiting for cluster-scoped cache to sync
2023-08-08T11:56:20Z INF [Kiali Cache] Started
2023-08-08T11:56:20Z INF [Kiali Cache] Kube cache is active for cluster: [Kubernetes]
2023-08-08T11:56:20Z INF Server endpoint will start at [:20001/kiali]
2023-08-08T11:56:20Z INF Server endpoint will serve static content from [/opt/kiali/console]
2023-08-08T11:56:20Z INF Starting Metrics Server on [:9090]
```

**Comment by jmazzitelli** [comment]
With today's 1.9 dev build and bookinfo installed with ambient enabled, the Kiali graph looks like this with the new Kiali 1.72 addon:

image

**Review by howardjohn — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Comment by jmazzitelli** [comment]
> Just double checking -- is this showing it looks as expected? Or that it does _not_ look as expected?
> 
> I assume its good, just I don't normally see both workloads+services visualized at once?

This normal. I just turned off the "services node" setting. The graph has a Display dropdown with a bunch of options - one of them is to either hide or show the triangles (services nodes) - in my first screenshot it was enabled (so you see apps+services - that's what the rectangles and triangles represent in that graph), in the second, service nodes were turned off so you just see the app rectangles.

**Comment by jmazzitelli** [comment]
The one thing that DOES look odd to me is the telemetry that shows this:
image
Maybe that is what you were asking about @howardjohn ? Notice the dual edges here - there looks to be some telemetry that looks strange to me, but I haven't investigated that as to what it should be and if it is correct.

**Pull request merged**
