### PR TITLE
istioctl: allow setting remote istiod port

### PR DESCRIPTION
**Pull request by stevenctl**
When running in KinD, istiod is exposed via NodePort rather than a LoadBalancer. For remote clusters to connect to this for configuration, they need to be able to change or map the port envoys use to get configuration from Pilot. 

When `values.global.remotePilotAddress` is set, we create a Service/Endpoint `istiod-remote` with port 15012. This change adds to that with `values.global.remoteIstiodPort`. When that flag is set:
- give the istiod-remote service a clusterIP so that it can perform port mapping
- targetPort is set on the istiod-remote Service
- istiod-remote endpoint uses the correct port

Example output:

<details>
<summary>With the new flag</summary>

```
landow@Stevens-MacBook-Pro:istioctl (master) $ ./istioctl manifest generate --set profile=remote --set values.global.remotePilotAddress=1.1.1.1 --set values.global.remoteIstiodPort=32345 | grep "name: istiod-remote" --context=7
    namespace: istio-system
---


apiVersion: v1
kind: Endpoints
metadata:
  name: istiod-remote
  namespace: istio-system
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - port: 32345
    name: tcp-istiod
--
--
    release: istio
---


apiVersion: v1
kind: Service
metadata:
  name: istiod-remote
  namespace: istio-system
spec:
  ports:
  - port: 15012
    name: tcp-istiod
    targetPort: 32345
```

</details>

<details>
<summary>Without the new setting</summary>

```
landow@Stevens-MacBook-Pro:istioctl (remote-istiod-port) $ ./istioctl manifest generate --set profile=remote --set values.global.remotePilotAddress=1.1.1.1 | grep "name: istiod-remote" --context=7
    namespace: istio-system
---


apiVersion: v1
kind: Endpoints
metadata:
  name: istiod-remote
  namespace: istio-system
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - port: 15012
    name: tcp-istiod
--
--
    release: istio
---


apiVersion: v1
kind: Service
metadata:
  name: istiod-remote
  namespace: istio-system
spec:
  ports:
  - port: 15012
    name: tcp-istiod
  clusterIP: None
---
```
</details>

### CODE REVIEW

**Comment by sdake** [comment]
@stevenctl I strongly recommend against nodeport for any Istio use case. If you are running kind, I'd recommend using metallb. If our documentation is broken in some way, can you point it out, so we can remove any recommendations for nodeport.

There are many blogs on this topic - the first one that comes up in my google search is: https://mauilion.dev/posts/kind-metallb/

**Comment by stevenctl** [comment]
> @stevenctl I strongly recommend against nodeport for any Istio use case. If you are running kind, I'd recommend using metallb. If our documentation is broken in some way, can you point it out, so we can remove any recommendations for nodeport.
> 
> There are many blogs on this topic - the first one that comes up in my google search is: https://mauilion.dev/posts/kind-metallb/

I've run through the MetalLB and it works fine. Right now in Prow, the kind clusters run with `NodePort` exposing tcp-istiod. As part of setting up multicluster (shared control plane) integration tests, we need to enable remote clusters to access the istiod/Pilot running in another cluster to get configs. Would you recommend setting up MetalLB as part of our [KinD setup](https://github.com/istio/istio/blob/master/prow/lib.sh#L188) rather than providing this configuration override?

**Comment by howardjohn** [comment]
If no one is using nodeports for multicluster in prod and it is feasible to setup metallb in  our CI that option sounds good to me

**Comment by sdake** [comment]
Some prior work in this area: https://github.com/istio/operator/pull/379

Part of this work was removed at my suggestion because, at that time, the work occurred last minute (sort of like now ;) and I didn't have time to obtain an IP address range in the prow infrastructure.

See this removal PR for more context: https://github.com/istio/operator/pull/456

Cheers
-steve

**Comment by stevenctl** [comment]
Closing in favor of https://github.com/istio/istio/pull/23363

**Pull request closed without merging**
