### PR TITLE
Fix a linter warning.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by howardjohn** [comment]
@geeknoid failing linter

**Comment by ericvn** [comment]
I will mention that at least the removal of the warning line has been attempted in another PR, but looks like there are a bunch of shadow warnings now that that was enabled. Maybe two different PRs next time to at least get one change in. although maybe that is more difficult having to get the required approvers, etc.

**Comment by geeknoid** [comment]
@ericvn Argh. I made this change locally and tested it, and no warnings came out. Now in CircleCi, tons of shadow errors are being produced. I'll revert that change.

Why is it so difficult to get these darn linters to produce systematically consistent results. Seems we are constantly getting into situations where the results reported are inconsistent.

**Comment by kyessenov** [comment]
There is some sensitivity to the version of go SDK I think.

**Pull request merged**
