### PR TITLE
Add labels to support kubectl --prune with Helm

### PR DESCRIPTION
**Pull request by ostromart**
This is required to be able to use helm template with kubectl apply --prune in a multi-revision case where gateways are managed separately.

### CODE REVIEW

**Review by morvencao — APPROVED** [review]

**Comment by sdake** [comment]
@ostromart @nrjpoddar I am really wishing we had upgrade tests for the helm workflows before introducing irrevocable changes such as labels.

Cheers,
-steve

**Review by howardjohn — COMMENTED** [review]
I think changing labels is fine. the main issue is changing selectors, which this is not

**Comment by nrjpoddar** [comment]
> @ostromart @nrjpoddar I am really wishing we had upgrade tests for the helm workflows before introducing irrevocable changes such as labels.
> 
> Cheers,
> -steve

Agree about testing.

I chatted with @ostromart and confirmed that Helm based canary upgrades would only need the "istio.io/revision" label as Helm performs pruning via its own mechanism. The new ownership label is needed for "kubectl" pruning afaict.

**Review by sdake — APPROVED** [review]

**Comment by ostromart** [comment]
Fixed https://github.com/istio/istio/pull/28039.

**Pull request merged**
