### PR TITLE
 Refresh secret when failed to parse certificates in it

### PR DESCRIPTION
**Pull request by lichuqiang**
Should refresh secret when failed to parse certificates in the secret

### CODE REVIEW

**Comment by lichuqiang** [comment]
@myidpt Thanks! but seems the `approve` did not take effect.
And if no other opinions, can you give it a lgtm?

**Comment by lichuqiang** [comment]
PR in active state

**Comment by myidpt** [comment]
Sorry for the delay. Please resolve the conflicts and I will approve.

**Comment by sdake** [comment]
if e2e-simple continues to fail, I recommend a rebase.

**Comment by lichuqiang** [comment]
@sdake Thanks for reminding!
@myidpt Code rebased, PTAL :)

**Pull request merged**
