### PR TITLE
[pilot] Moving clusterregistry to kube

### PR DESCRIPTION
**Pull request by nmittler**
This is just a bit of cleanup to clarify that the clusterregistry
is really a k8s-specific component.

### CODE REVIEW

**Comment by nmittler** [comment]
@sdake mind taking a look as well, since it involves moving the cluster registry code a bit?

**Comment by sbezverk** [comment]
@nmittler I really do not think it is good timing to move cluster registry stuff at this point. There are several efforts changing exactly the code you try to move. @costinm  WDYT
/cc @john-a-joyce

**Comment by nmittler** [comment]
@sbezverk That's fine, I can raise a bug to move the code if you prefer?

**Comment by sdake** [comment]
@nmittler goal sound good.  Very bad timing.  I think shortly after 0.8 is released, the entire cluster registry code will be need removal.  The reason we are leaving it in as is is to enable both a better user experience while not disrupting the CI work taking place.

The people in the CC and review list intend to remove the registry entirely.  We may revive it post 1.0 when the upstream project is more mature so that we can deliver a true multicloud experience.  I personally feel good when I remove code rather than add code.  Moving/reorging code makes sense if the dependency is a long term dependency.

Cheers
-steve

**Comment by costinm** [comment]
Please reopen after 0.8 and few weeks have passed.

**Comment by nmittler** [comment]
@sdake SGTM ... thanks!

**Pull request closed without merging**
