### PR TITLE
Update golangci-lint

### PR DESCRIPTION
**Pull request by kyessenov**
There are new restrictions on import naming introduced in the upstream goimports.
This PR fixes the existing code to satisfy the linter.

/assign @douglas-reid 
/assign @geeknoid

### CODE REVIEW

**Comment by nmittler** [comment]
@kyessenov it would seem that the new restrictions are overly strict, no? The one that sticks out is that it now requires a redundant package alias if the package name differs from the directory. This has been a periodic problem with our linters. Is there any way to adjust the linter to ignore this?

**Comment by kyessenov** [comment]
This is something that was debated by the golang team (I think Brad made
the change). It is intentional since it dramatically speeds up static
analysis from what I understand. Plus the modules make imports more
complicated.

**Comment by nmittler** [comment]
@kyessenov ok thanks for clarifying. I suspect that we'll just have to wait for other tools (e.g. IDEs) to catch up.

**Pull request merged**
