### PR TITLE
Using switch-case instead of multiple if-else

### PR DESCRIPTION
**Pull request by ChenglongGao327**
Increase code readability，using switch-case instead of multiple if-else

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
/ok-to-test

**Comment by kebe7jun** [comment]
Thanks!

**Review by howardjohn — COMMENTED** [review]
lgtm

**Pull request merged**
