### PR TITLE
cherry-pick #31663

### LINKED ISSUE #31733: [release-1.9] Extend pass through filter chain security integration tests to cover vm as client and to become workload agnostic
Manual cherrypick required.

#31663 failed to apply on top of branch "release-1.9":
```
Applying: templatize policy
Using index info to reconstruct a base tree...
M	tests/integration/security/pass_through_filter_chain_test.go
Falling back to patching base and 3-way merge...
Auto-merging tests/integration/security/pass_through_filter_chain_test.go
Applying: extend test to cover vm workload
Using index info to reconstruct a base tree...
M	tests/integration/security/pass_through_filter_chain_test.go
Falling back to patching base and 3-way merge...
Auto-merging tests/integration/security/pass_through_filter_chain_test.go
CONFLICT (content): Merge conflict in tests/integration/security/pass_through_filter_chain_test.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0002 extend test to cover vm workload
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Manually cherry-pick https://github.com/istio/istio/pull/31663

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Fixes #31733 

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
The failed test cases in `integ-security-multicluster-tests_istio_release-1.9` are irrelevant to this PR.
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31742/integ-security-multicluster-tests_istio_release-1.9/1376241106060054528

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
