### PR TITLE
dashboard: switch sent/received for outbound TCP connections

### LINKED ISSUE #32399: istio_tcp_sent_bytes_total and istio_tcp_received_bytes_total are swapped
**Bug description**
TCP bytes sent on outgoing connection and received are reversed

This is a screen shot of sending request at 50 qps and receiving 2k responses: (mislabelling a fortio http echo as tcp on purpose to demonstrate the issue:)

image

It's not just Grafana but the actual prometheus metrics istio_tcp_sent_bytes_total and istio_tcp_received_bytes_total are swapped

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Bytes sent to be sent and received to be received (from the perspective of the pod; seems to be maybe from perspective of envoy)

**Steps to reproduce the bug**

See description

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.5

**How was Istio installed?**

helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Fixes #32399

### CODE REVIEW

**Review by douglas-reid — COMMENTED** [review]
This looks OK to me. Is there any other dash using these metrics (mesh or service) ?

**Comment by kyessenov** [comment]
@douglas-reid I scanned through and looks like mesh dashboard has it already correctly flipped.

**Review by douglas-reid — APPROVED** [review]

**Comment by kyessenov** [comment]
Gentle ping.

**Comment by kyessenov** [comment]
Gentle ping @howardjohn .

**Review by howardjohn — APPROVED** [review]
Sorry lost track of this. If it looks good to you and Doug LGTM

**Comment by ldemailly** [comment]
While this fixes the grafana dashboard I don't think it fixes the confusing /inconsistent name of the metric - it also won't fix Kiali etc

But I suppose it's better than without it and maybe "safer"

**Comment by jshaughn** [comment]
I just stumbled over this.  Perhaps Kiali still has a problem here, given that the fix affects only the grafana dashboard.  @ldemailly, do you know if Kiali needs to make a change to accommodate?

**Pull request merged**
