### PR TITLE
Buffer xds requests in istiod

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This introduces a fixed capacity with 10 to handle requests burst.

Replace #31167

### CODE REVIEW

**Comment by ramaraochavali** [comment]
LGTM. Leave it open for @howardjohn to take a look because he has an opinion on introducing buffering at Istiod.

**Review by howardjohn — COMMENTED** [review]
I am really not sure this is a good idea. I haven't seen any examples looking around at grpc streaming servers of doing this. Generally it looks like a desired back-pressure mechanism. As a concrete example, go-control-plane doesn't do this https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L400 nor does xds-relay https://github.com/envoyproxy/xds-relay/blob/345df46f133e063cba18050932ba7dfeda297639/internal/app/upstream/client.go#L357.

Without some concrete data on prior art of why this helps I am not sure its the right idea

**Comment by kyessenov** [comment]
xDS is not edge triggered. It's level triggered, so using the latest in the
queue is usually fine. There are odd back where edge triggered behavior
needs to happen, but those are bugs.

**Comment by howardjohn** [comment]
I am not sure this is about edge vs level triggered, unless I misunderstand. Rather do we stop Recv'ing if we are busy and let it back up in the agent/envoy, or slurp up any discovery request in istiod and enqueue it. Either way we should get the same requests in the same order

**Comment by hzxuzhonghu** [comment]
As we have extended the xds, like healthcheck,  i donot think we can discard this kind of request. In this pr it is not to use unlimited buffer which is unsafe, with a warning we can check the burden the system faces.

**Comment by cocotyty** [comment]
In fact, this problem is caused by a variety of reasons.
At the beginning, the istiod pushed more than 40,000 clusters to gateway,  and gateway threads number was more than 200.
I think that the problem occurs in envoy's XDS processing performance.

**Comment by hzxuzhonghu** [comment]
@cocotyty absolutely this could not reduce push time. This can only buffer xds requests and prevent xds connection reestablish when it is in a burst.

**Pull request closed without merging**
