### PR TITLE
Clean up duplicated/legacy iptables tests

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/20313

I am fairly certain these are all covered by
https://github.com/istio/istio/blob/master/tools/istio-iptables/pkg/cmd/run_test.go,
these test were originally a test for compatibility between golang and
shell. Now there is just golang, which has much more testing, so this is
no longer needed.

### CODE REVIEW

**Comment by howardjohn** [comment]
@abhide @rlenglet I think these are redundant but please keep me honest here. I was going to convert these to golang tests but realized that probably isn't needed

**Comment by howardjohn** [comment]
I found one case that was not covered, added it to the golang tests

**Comment by abhide** [comment]
LGTM! Thanks for adding this.

**Pull request merged**
