### PR TITLE
Move ci2gubernator to circle ci base image

### PR DESCRIPTION
**Pull request by chxchx**

### CODE REVIEW

**Comment by chxchx** [comment]
Ping @costinm

**Comment by chxchx** [comment]
@rshriram Perhaps you can do me the favor of creating and pushing a new base image to circleci hub, assuming you are an admin too? I am not sure if using images from a personal docker hub is a good practice (aside from testing the change of course)

**Comment by rshriram** [comment]
Hi, sorry, I totally missed this. I can definitely push

**Pull request closed without merging**
