### PR TITLE
remove bin/perftest.sh

### LINKED ISSUE #3869: bin/perftest.sh out of date
istio/bin/perftest.sh references bazel. Should this be fixed, or the script deleted?

### PR DESCRIPTION
**Pull request by jmuk**
This is not used, and bin/perfcheck.sh seems more preferable.
This PR also adds some baselines for benchmark tests.

Fixes #3869

### CODE REVIEW

**Comment by ozevren** [comment]
Hey Jun,

Where did you collect the baseline numbers from? It looks like they are lower than what I generally expect to see.

**Comment by jmuk** [comment]
@ozevren I got them on my local machine (z620) with GOMAXPROCS=8, go 1.10. What's the best way to collect the numbers?

**Comment by ozevren** [comment]
There is no best way at this point i am afraid. Every machine inherently gives different numbers. I am trying to get a better understanding of the variances. The numbers in the baselines seemed lower across the board and I was curious.

**Pull request merged**
