### PR TITLE
set default priorityClass for istiod

### PR DESCRIPTION
**Pull request by tariq1890**
Raising this PR after discussing with @morvencao on this. Since `istiod` acts as as a SPOF of sorts, it's important that we set a high priority class to it by default

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by tariq1890** [comment]
See [here](https://github.com/istio/istio/issues/12786).

cc @linsun @hzxuzhonghu

**Review by howardjohn — COMMENTED** [review]
are there other projects that are setting this? It seems like the kind of thing that may cause some subtle breaking behavior.

It seems like a good idea, just curious if there is prior art to give us more confidence

**Comment by tariq1890** [comment]
> are there other projects that are setting this? It seems like the kind of thing that may cause some subtle breaking behavior.

I do not know of other projects. Then again there aren't many applications that play a critical role in the functioning of a cluster like `istiod`

**Comment by tariq1890** [comment]
The setting works pretty well for our Istio clusters however

**Review by hzxuzhonghu — APPROVED** [review]
I remember we did this before

**Comment by dntosas** [comment]
we apply this setting to all our clusters also ^^ set as the default behavior seems a good idea

**Comment by tariq1890** [comment]
Yes, this comes out of the box with Kubernetes clusters that support the priorityClass API

**Review by ostromart — APPROVED** [review]

**Pull request merged**
