### PR TITLE
add missing root certificate to cert-chain.pem

### PR DESCRIPTION
**Pull request by elevran**
cert-chain.pem contained only (intermediate) Citadel CA certificate, concatenate root-cert.pem into the chain. 

Tests and samples for multicluster worked since the instructions resulted in the same intermediate certificate imported into multiple citadels. Ideally, we should be using different intermediate CA for each Citadel but still share a common root-CA.

### CODE REVIEW

**Comment by elevran** [comment]
@wattli I'm trying to understand the comment in https://istio.io/docs/tasks/security/plugin-ca-cert/:
> In the following example, Citadel’s signing (CA) certificate (ca-cert.pem) is different from root certificate (root-cert.pem), so the workload cannot validate the workload certificates directly from the root certificate. The workload needs a cert-chain.pem file to specify the chain of trust, which should include the certificates of all the intermediate CAs between the workloads and the root CA. 
>
> In our example, it contains Citadel’s signing certificate, so cert-chain.pem is the same as ca-cert.pem. Note that if your ca-cert.pem is the same as root-cert.pem, the cert-chain.pem file should be empty.

My understanding is the the cert-chain file should include the entire chain from current certificate all the way to the root-ca certificate. That is, I would expect to see `cert-chain.pem` include:
```pem
-----BEGIN CERTIFICATE-----
ca-cert
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
root-cert
-----END CERTIFICATE-----
```

How would a workload access the root-ca to verify Citadel's if it is not part of the Citadel chain?

**Comment by elevran** [comment]
@myidpt - can you please take a look? I believe chains need to include all certs, all the way up to the root.

**Comment by wattli** [comment]
@myidpt , what do you think?

**Comment by linsun** [comment]
ping @myidpt

**Pull request closed without merging**
