### PR TITLE
istioctl x metrice support custom duration

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

istioctl x metrice support custom duration

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Comment by zirain** [comment]
ping @istio/wg-user-experience-maintainers

**Comment by zirain** [comment]
@irisdingbj can you take a look, need a approve from UX part.

**Review by irisdingbj — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
