### PR TITLE
Use latest stable from manager, mixer and auth

### PR DESCRIPTION
**Pull request by sebastienvas**

### CODE REVIEW

**Comment by sebastienvas** [comment]
@douglas-reid the current SHA used in istio.VERSION for mixer is not in mixer.

**Comment by andraxylia** [comment]
We need the manager image from this PR, which now building:
https://github.com/istio/manager/pull/803

**Comment by sebastienvas** [comment]
We can create another PR for istio/manager#803

**Comment by sebastienvas** [comment]
rebuild istio/presubmit

**Pull request merged**
