### PR TITLE
Add support for k8s.v1.cni.cncf.io/networks annotation

### PR DESCRIPTION
**Pull request by knrc**
Pull Request for https://github.com/istio/istio/issues/24425

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
This looks good to me but I'd like to give some people more familiar with CNI a chance to look before approving immediately. @lambdai @stewartbutler

**Comment by stewartbutler** [comment]
Technically it looks fine to me, I'd just like more information on the motivation for it.

Can we get some context on what this annotation is used for?

**Comment by knrc** [comment]
@stewartbutler The annotation is used to define the list of network attachment definitions which are to be attached to the pod, it's used by multus CNI

**Comment by nrjpoddar** [comment]
This should be cherry-picked into 1.5/1.6, @knrc is that correct?

**Comment by knrc** [comment]
@nrjpoddar I can certainly work on that, I've only tested against master so far but can look at 1.5/1.6.  I have a different solution for 1.4.

**Comment by stewartbutler** [comment]
OK, LGTM. I'd leave it a bit longer to give Yuchen a chance to take a look.

@knrc we can try an automated cherrypick. Only do it manually if that fails.

**Review by lambdai — CHANGES_REQUESTED** [review]
Generally LGTM

Can you add the documentation or the link regarding `k8s.v1.cni.cncf.io/networks` 
1. What is the consumer of this annotation?
2. When can we delete it?

I don't think istio-cni is idempotent and we cannot control the user input of annotation.
Could you add the validation, or blindly strip istio-cni if `isti-cni` is already in the annotation? 
Unless the consumer would dedup the cnis

**Comment by knrc** [comment]
@lambdai I wouldn't expect the consumer to have specified istio-cni but I can take a look at deduping

**Comment by lambdai** [comment]
> @lambdai I wouldn't expect the consumer to have specified istio-cni but I can take a look at deduping

Agree. it's nice to have. It's not the hard block for this PR.

**Comment by sdake** [comment]
I would recommend against backporting to 1.5, unless there is very strong motivation for such.

**Review by howardjohn — APPROVED** [review]

**Review by lambdai — APPROVED** [review]

**Comment by sdake** [comment]
> I would recommend against backporting to 1.5, unless there is very strong motivation for such.

This is fine to backport. Please ignore my knee-jerk anti-backport stance in this case 👍 
Cheers,
-steve

**Pull request merged**
