### PR TITLE
fix typo and do some refactoring work

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

**Please provide a description of this PR:**
When reading source code, found some typo and did some refactoring works by the way.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by kerthcet** [comment]
Maybe label `ok-to-test` is needed, since I'm not trusted now. @howardjohn

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by kerthcet** [comment]
This pr is approved by @howardjohn  but may need another lgtm from a reviewer.

**Comment by kerthcet** [comment]
cc @therealmitchconnors, as I found you are the leader in User Experience WG from here: https://github.com/istio/community/blob/master/WORKING-GROUPS.md#working-group-leads

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by kerthcet** [comment]
Sorry to disturb you @hzxuzhonghu , is this pr needs approval from `User Experience WG` side? I found two approvals already but still pending.

**Review by hanxiaop — APPROVED** [review]

**Pull request merged**
