### PR TITLE
remove redundant code

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by douglas-reid** [comment]
Did you just self-apply the LGTM label and then merge to master without a review?

**Comment by mandarjog** [comment]
Yes it looks like that :-(

**Comment by jmazzitelli** [comment]
> Did you just self-apply the LGTM label and then merge to master without a review?

@douglas-reid @mandarjog -- How is that even possible when @hzxuzhonghu isn't in the [OWNERS](https://github.com/istio/istio/blob/master/mixer/OWNERS) file??

**Comment by kyessenov** [comment]
It's a hack around our bot system. It was discussed a few months ago in TOC.

**Comment by hzxuzhonghu** [comment]
Sorry, I thought no one would review such a small pr.

**Comment by duderino** [comment]
@hzxuzhonghu there is a reason why we always require code reviews.  This change ended up creating a P0 for the 1.2 release and caused a production incident for Autotrader UK.

https://github.com/istio/istio/issues/15029

**Comment by hzxuzhonghu** [comment]
Agreed, but i can not see how this cause crash.

**Comment by mandarjog** [comment]
res.Group = ConfigAPIGroup
res.Version = ConfigAPIVersion

In absence of these 2 lines, the group and version were left unset.
This means that the client was created for an incomplete resource.
Version=“” group=“” kind=“handler”

Mixer could not find or watch any resource

**Comment by hzxuzhonghu** [comment]
IC, thanks @mandarjog ， I can fix it if no pr is opened ?

**Comment by mandarjog** [comment]
There is a cherry pick. Let’s be careful next time. Unfortunately there was no test that continued to test this configuration.

**Comment by louiscryan** [comment]
@geeknoid this is an example of tide allowing a merge when it should not, violating the no-self dealing principle. Where are we with cutting over to Mergify

**Comment by geeknoid** [comment]
I've got on my short list to disable tide. We've got mergify on the smaller repos already, and I'll do istio/api and then istio/istio RSN.

**Pull request merged**
