### PR TITLE
[Cherrypick-release-1.1] Dedupe Redis tests in e2e tests and new integration test framework (#…

### PR DESCRIPTION
**Pull request by gargnupur**
…14192)

https://github.com/istio/istio/issues/14424

### CODE REVIEW

**Comment by duderino** [comment]
@gargnupur why do we need this in the 1.1 branch?

**Comment by kyessenov** [comment]
@duderino The test that is removed no longer works on any branch. At some point `helm install stable/redis` stopped working, and we've since started using the new integration framework on 1.2 and master as a replacement. We're hoping that once the framework is moved away from istio, we could use it to test 1.1.

**Comment by duderino** [comment]
@gargnupur @kyessenov if I merge this, which test failure/flake will start passing?

@gargnupur there's also a linter issue that must be fixed

```
tests/e2e/tests/mixer/mixer_test.go:54:2: `mixerTestDataDir` is unused (varcheck)
	mixerTestDataDir      = "tests/e2e/tests/mixer/testdata"
	^
WARN [runner/nolint] Found unknown linters in //nolint directives: vet, vetshadow 
Makefile:306: recipe for target 'lint' failed
```

**Comment by gargnupur** [comment]
@duderino : Yes, it will fix prow/e2e-mixer-no_auth.sh. Fixing linter error..

**Pull request merged**
