### PR TITLE
run dep ensure

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
run dep ensure with 

```
# dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false

```

### CODE REVIEW

**Comment by rshriram** [comment]
We don't run dep ensure usually, unless we want to update a specific dependency

**Comment by ayj** [comment]
/lgtm

@rshriram, vendor and Gopkg.toml are currently [out-of-sync on master](https://github.com/istio/istio/pull/7799#issuecomment-413618138) after running `dep prune` with an older version of dep. This PR re-adds the missing files that were removed in https://github.com/istio/istio/pull/7799.

**Comment by douglas-reid** [comment]
I've run `dep ensure` with the latest dep (`go get -u`) in #8036. It'd be nice if we agreed on version (and `dep` behavior) somehow.

**Comment by zachgersh** [comment]
@douglas-reid - I think we have agreed on a version, its marked as the latest stable in our makefile (0.5.0). Unfortunately, I can't think of a good way for us to enforce someone not doing `go get -u` for dep and then saying ensure on the project (sadly, I've even done this myself).

**Comment by ldemailly** [comment]
like linters a good way to have a reliable/consistent tool version is to use a docker image or add it to our existing build image ?

**Comment by hzxuzhonghu** [comment]
Since @#8036 merged, close this.

**Comment by douglas-reid** [comment]
@zachgersh maybe our solution is to migrate away from `dep`? always having to have the latest version of the tool is a real thorn.

**Comment by zachgersh** [comment]
@douglas-reid agreed and yes I think that is the solution. We just need to wait for 1.11 to ship and then modules will be the way (I hope). I am going to attempt to switch istio as soon as the official release is out (they see like they are close since the rc just came out).

**Comment by kyessenov** [comment]
Wait for a couple of weeks after the release, so that the most pressing
bugs are fixed. Otherwise, modules do seem like the right long term
solution.

**Pull request closed without merging**
