### PR TITLE
Add cluster labels to all prom metrics for all topologies

### PR DESCRIPTION
**Pull request by douglas-reid**
Part of the plan for 1.9 release was to make all prometheus metrics include source/destination cluster labels (not just for multicluster scenarios). This PR is meant to accomplish that goal by removing the conditional logic in the manifests.

For 1.10+, we should absorb this logic into the istio/proxy extension code itself (or similar).

[ X ] Policies and Telemetry

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
lgtm

**Review by nmittler — APPROVED** [review]

**Review by mandarjog — APPROVED** [review]
Lgtm

**Review by morvencao — APPROVED** [review]

**Review by nrjpoddar — COMMENTED** [review]
@douglas-reid I'm assuming we would need to update the istio.io docs to reflect the new set of default labels?

**Comment by douglas-reid** [comment]
> @douglas-reid I'm assuming we would need to update the istio.io docs to reflect the new set of default labels?

Yes. There will need to be a follow-on PR after this is cherry-picked.

**Pull request merged**
