### PR TITLE
Prepare deployment before writing golden file.

### PR DESCRIPTION
**Pull request by axel7born**
The function `compareDeployments` removes some fields that start with `ISTIO_META_*` . These fields have to be removed when we write the golden files.

Co-authored-by: Julia Plachetka <julia.plachetka@sap.com>

### CODE REVIEW

**Comment by axel7born** [comment]
/cc @costinm 
/cc @ayj 
/cc @hzxuzhonghu
Someone interested in reviewing this change?

**Comment by jkbschmid** [comment]
Not stale

**Pull request closed without merging**
