### PR TITLE
injection: drop legacy ISTIO_META_APP_CONTAINERS

### PR DESCRIPTION
**Pull request by howardjohn**
This was only used for stackdriver which has since been removed

### CODE REVIEW

**Comment by howardjohn** [comment]
Put a hold to let @lei-tang or @kyessenov approve specifically rather than anyone else

**Comment by kyessenov** [comment]
I'm pretty sure this is needed to attach to k8s container monitored resource in GCP.

**Comment by kyessenov** [comment]
Correct, but SD filter can't function without all the data in the injection template. Where else would it get the container name?

**Comment by kyessenov** [comment]
I would love to remove this field as well - @lei-tang the code does a fallback to "istio-proxy" as k8s_container name when it can't find APP_CONTAINERS. Can we simply hard code it to "istio-proxy" since you can't generally tell which container originates the request anyways?

**Pull request closed without merging**
