### PR TITLE
eds: Hold lock for iterating on EDS clusters for logging

### PR DESCRIPTION
**Pull request by rlenglet**
Fixes: https://github.com/istio/istio/issues/4903
Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
cc @kyessenov @costinm

**Comment by rshriram** [comment]
can you point your PR to release-0.8 branch?

**Comment by rlenglet** [comment]
@rshriram done!

**Pull request merged**
