### PR TITLE
Allow creation of gateways for prometheus and grafana addons

### PR DESCRIPTION
**Pull request by cezarsa**
This change adds new config options for both prometheus and grafana addons: `prometheus.gateway.enabled` and `grafana.gateway.enabled`. By setting these to true the helm chart will create a Gateway a DestinationRule and a VirtualService to allow exposing the addon in the default ingress gateway.

This functionality replaces the old telemetry-gateway addon which was removed in this PR.

cc @sdake

### CODE REVIEW

**Comment by linsun** [comment]
Thanks @cezarsa  what about update to requirements.yaml?

**Comment by cezarsa** [comment]
@linsun The requirements.yaml does not reference the telemetry-gateway on master yet, the PR to add it is #9606 but I think it can be closed without merging if this was is approved instead.

**Comment by linsun** [comment]
ok thanks @cezarsa, I lost track of which PR is in :)

**Comment by sdake** [comment]
@costinm I agree- I had suggested this PR to the author before I learned that all of our telemetry lacks https protocols.  That problem needs to be fixed first.

**Comment by jmazzitelli** [comment]
I wrote a PR that fixes this up with no conflicts, is based on release-1.1 branch, and adds changes for kiali:

https://github.com/istio/istio/pull/10349

We can close this PR out since that new PR supercedes this one.

**Comment by jmazzitelli** [comment]
/hold

I'm putting a hold on this PR, since I believe https://github.com/istio/istio/pull/10349 supercedes this one.

**Comment by sdake** [comment]
@cezarsa I really want to thank you for your work here.  It is the basis of @jmazzitelli 's pr here: https://github.com/istio/istio/pull/10349.  He should probably add you as a co-author.  @jmazzitelli is in the process of adding HTTPS at the edge, and possibly internally in the mesh, which is the reason @costinm placed a hold on this PR here:

https://github.com/istio/istio/pull/9640#pullrequestreview-170478135

@cezarsa Hope to see more good work from you in the future :)  One thing that would rock is internal mesh https for the addons.  Perhaps you and @jmazzitelli can collaborate on that work?

Cheers
-steve

**Comment by cezarsa** [comment]
I'm sorry for not tackling this at the time, thank you @jmazzitelli for continuing this work. I ended up busy on other stuff and wasn't able to finish this. I'm surely looking forward to contributing more with Istio in the future. Closing this in favor of #10349.

**Pull request closed without merging**
