### PR TITLE
Update installation yaml to include CRD for templates

### PR DESCRIPTION
**Pull request by manlinl**
**What this PR does / why we need it**:
Add CRD for apikey and servicecontrolreport templates.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by manlinl** [comment]
@mandarjog @douglas-reid Hey guys, could you take a look?

**Comment by manlinl** [comment]
@suguru could you help review my change for template CRD?

**Comment by geeknoid** [comment]
@mandarjog @douglas-reid 

Do either of you guys want to take this PR over and see it gets committed? If not, we should close this PR.

Thanks.

**Comment by GregHanson** [comment]
resolved by other PR, closing for now

**Pull request closed without merging**
