### PR TITLE
proxy: update tests

### PR DESCRIPTION
**Pull request by kyessenov**
For some weird reasons, tests are here instead of the proxy repo.

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
Can something be done about circleci consistently failing?
I have already clicked the button three times and nothing helps.
@wattli @hklai

**Comment by hklai** [comment]
Did you rebase to include https://github.com/istio/istio/pull/5961?

Circle does not do it automatically (until https://github.com/istio/istio/pull/5957 gets back in master)

**Comment by kyessenov** [comment]
@qiwzhang  can you please re-approve again. I rebased to get a fix for circle CI.

**Comment by kyessenov** [comment]
@mandarjog @douglas-reid need a top-level owner approval

**Comment by kyessenov** [comment]
@geeknoid could you please merge this. Need top-level owner to update the proxy.

**Pull request merged**
