### PR TITLE
Fix a few doc issues in quota adapters.

### PR DESCRIPTION
**Pull request by caohe**
- Update the links of docs in quota adapters.
- Update the years of copyright to 2019.

### CODE REVIEW

**Comment by geeknoid** [comment]
Hi there,

We generally don't update copyrights, they should just reflect the year of the file's creation.

And the updates for the front-matter stuff aren't correct or necessary. This is how they're supposed to be, like in all the other adapters.

Since this doesn't leave anything in this PR, I'm closing it. 

Thanks.

**Comment by caohe** [comment]
ok. thx.

**Pull request closed without merging**
