### PR TITLE
Move Muticluster/VM cert setup tool to install/ dir.

### PR DESCRIPTION
**Pull request by myidpt**
Move the cert management tool to install/tools/certs since it's the tool (not samples) for users to set up their clusters.

### CODE REVIEW

**Review by nmittler — APPROVED** [review]

**Review by rcaballeromx — APPROVED** [review]

**Comment by rcaballeromx** [comment]
Please address linter errors.

**Review by rcaballeromx — CHANGES_REQUESTED** [review]
Fix linter errors

**Review by rcaballeromx — APPROVED** [review]
Thanks!

**Comment by sdake** [comment]
One has to appreciate the irony of this PR being open for 1 hour and merged.

Gotta love open source!

**Comment by sdake** [comment]
@myidpt Please change release-builder accordingly. By making this change, this code will be excluded from the release tarball.

Cheers
-steve

**Pull request merged**
