### PR TITLE
fix: high priority threshold in circuit breaker configruation is missing

### PR DESCRIPTION
**Pull request by zhaohuabing**
Signed-off-by: zhaohuabing <huabingzhao@tencent.com>

fix https://github.com/istio/istio/issues/41882

**Please provide a description of this PR:**

fix missing high priority threshold in circuit breaker configruation

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Why does it matter? We don't use priorities? This seems to just bloat the Cluster definition further.

**Comment by zhaohuabing** [comment]
> Why does it matter? We don't use priorities? This seems to just bloat the Cluster definition further.

We encountered a 429 Too Many Requests error response from a pod with a large amout of inbound traffice. The config_dump of clusters shows that the ciruit_breaker for that service in envoy is the below. I thought this problem may be caused by the second threshold not being set to appropriate values. 

kubectl exec xxxxxx-67bd94f7f8-4lzh6 -c istio-proxy curl 127.0.0.1:15000/clusters?format=json

```yaml
      "circuit_breakers": {
        "thresholds": [
          {
            "max_connections": 4294967295,
            "max_pending_requests": 4294967295,
            "max_requests": 4294967295,
            "max_retries": 4294967295
          },
          {  
            "priority": "HIGH",
            "max_connections": 1024,
            "max_pending_requests": 1024,
            "max_requests": 1024,
            "max_retries": 3
          }
        ]
      },
   ```

**Comment by howardjohn** [comment]
When/why is HIGH priority used? AFAIK it is not?

**Comment by hzxuzhonghu** [comment]
We have set just one threshold

**Comment by zhaohuabing** [comment]
> When/why is HIGH priority used? AFAIK it is not?

I have the same question. Looked into the Envoy documentation and there's not much information. I suggest we hold this until we understand how priority is used. I will also check whether this change works or not in my test environment.

**Pull request closed without merging**
