### PR TITLE
Invert namespace injection selection criteria

### PR DESCRIPTION
**Pull request by ostromart**
Addresses https://github.com/istio/istio/issues/5576.

### CODE REVIEW

**Comment by ayj** [comment]
Does this need to be configurable defaulting to the opt-in behavior? Otherwise user's upgrading from 0.8 to 1.0 will be surprised.

**Comment by ostromart** [comment]
Yes, that's a good point. What mechanism do you suggest to opt-in? A flag that defaults to false?
Do you know if install/kubernetes/templates/istio-ns.yaml.tmpl will still be used or is it all helm going forward?

**Comment by ayj** [comment]
> Yes, that's a good point. What mechanism do you suggest to opt-in? A flag that defaults to false?

Yes, something like the following that defaults to the existing behavior,

```diff
diff --git a/install/kubernetes/helm/istio/values.yaml b/install/kubernetes/helm/istio/values.yaml
index 373c5c9cd..e487ef763 100644
--- a/install/kubernetes/helm/istio/values.yaml
+++ b/install/kubernetes/helm/istio/values.yaml
@@ -203,6 +203,7 @@ gateways:
 #
 sidecarInjectorWebhook:
   enabled: true
+  namespaceSelectorOptOut: false
   replicaCount: 1
   image: sidecar_injector
   resources: {}
```

> Do you know if install/kubernetes/templates/istio-ns.yaml.tmpl will still be used or is it all helm going forward?

Not sure.

**Comment by ayj** [comment]
cc @tcnghia

**Pull request closed without merging**
