### PR TITLE
Bump istio/api

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by jasonwzm — APPROVED** [review]

**Comment by howardjohn** [comment]
@jasonwzm somehow the preserveUnknownFields=false breaks Envoyfilter. It doesn;t handle the generic part.

apply:
```
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.metadata_exchange
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            value:
              config:
                configuration: |
                  {}
                vm_config:
                  {{- if .Values.telemetry.v2.metadataExchange.wasmEnabled }}
                  runtime: envoy.wasm.runtime.v8
                  code:
                    local:
                      filename: /etc/istio/extensions/metadata-exchange-filter.wasm
                  {{- else }}
                  runtime: envoy.wasm.runtime.null
                  code:
                    local:
                      inline_string: envoy.wasm.metadata_exchange
                  {{- end }}
```

and we end up with 

```
    patch:
      operation: INSERT_BEFORE
      value: {}
```

**Comment by jasonwzm** [comment]
@howardjohn i will send a PR to remove `preserveUnknownFields` in EnvoyFilter and I will work on getting including `x-kubernetes-preserve-unknown-fields` in the gen tool.

**Comment by jasonwzm** [comment]
@howardjohn can you update api again? The CRD file does not seem to be updated.

**Comment by jasonwzm** [comment]
@howardjohn can you update api again?

**Comment by jasonwzm** [comment]
crds need to be updated as well.

**Review by linsun — APPROVED** [review]

**Pull request merged**
