### PR TITLE
Convert validation error for ServiceEntry having multiple hosts with TCP port to warning

### PR DESCRIPTION
**Pull request by l8huang**
When DNS_AUTO_ALLOCATE is enabled, sidecar egress listener can use private IP 240.240.x.x to multiplex TCP traffic.

Current validation is quite weak because it can be workaround by creating multiple ServiceEntry objects each has 1 host with same TCP port. This change converts the error to a warning.

### CODE REVIEW

**Comment by l8huang** [comment]
This PR is related to Allow ServiceEntry to have multiple hosts for same TCP port #42522

**Comment by l8huang** [comment]
@hzxuzhonghu thanks, changed error to warning.

**Review by howardjohn — COMMENTED** [review]
I would prefer to not merge this PR for the reasons mentioned in the issue.

**Pull request closed without merging**
