### PR TITLE
Fix stats tags for http_conn_manager

### PR DESCRIPTION
**Pull request by keithmattix**
**Please provide a description of this PR:**
This was a bug in the original implementation; the regex didn't take into account the fact that the first dot was already excluded, leading to a double dot.

### CODE REVIEW

**Comment by psaia** [comment]
@keithmattix Do you believe that this will resolve the issue outlined here? https://github.com/istio/istio/issues/41206

At the surface it looks like it does.

**Comment by keithmattix** [comment]
@psaia yes it should!

**Pull request merged**
