### PR TITLE
update certs

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Fix security integrate CI failure, now updated the cert expire time to 10 years, same as root cert

### CODE REVIEW

**Review by ymesika — APPROVED** [review]
Thanks. All recent PRs failed security tests because of that.

**Comment by hzxuzhonghu** [comment]
@howardjohn

**Review by zirain — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Review by johnma14 — APPROVED** [review]

**Pull request merged**
