### PR TITLE
fix docker tag names for pushing

### PR DESCRIPTION
**Pull request by jmuk**
I've found that mixer/docker/gcloud_build.sh fails, and the tag
name for the generated docker image has changed slightly,
from istio/docker:mixer to istio/mixer/docker:mixer.

This PR fixes the mixer script, and also does the same thing
for other scripts.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by rshriram** [comment]
aren't you missing istio/security/docker ?

**Comment by jmuk** [comment]
I couldn't find scripts doing this thing in security. Could you point which file I should change?
BTW I've found yet another file, `mixer/docker/cloudbuild.yaml` needs something similar. PTAL.

**Comment by rshriram** [comment]
If its not there, then fine..

**Pull request merged**
