### PR TITLE
Remove defunct VM sample

### PR DESCRIPTION
**Pull request by howardjohn**
This is for Istio 0.2

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ericvn** [comment]
I do see this sample pointed at by the current documentation, although there is a PR to remove that reference going forward. The older archives still have a reference. I'm not sure how this would impact builds of older branches (not typically done), but the release current istio.io release 1.8 branch may have issues.

**Comment by howardjohn** [comment]
Current 1.8 branch of docs should point to the old release branch, not
master. Also, I am removing the doc that refers to this - I already have an
open PR.

**Comment by ericvn** [comment]
Verified that preliminary.istio.io did point to the release 1.9 branch. The only other thing that might be could would be to update the sample shortcode on istio.io/istio.io/content/en/about/contribute/shortcodes/index.md. It won't fail, but good to point to something that exists.

I'll wait to approve until https://github.com/istio/istio.io/pull/8892 is merged.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
