### PR TITLE
add FatalLevel for package log

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Add a FatalLevel in `istio.io/istio/pkg/log`

### CODE REVIEW

**Comment by geeknoid** [comment]
Please add unit tests to cover all new functionality. pkg/log is at 100% coverage, we should keep it that way.

Thanks.

**Comment by hzxuzhonghu** [comment]
@geeknoid added ut , ptal

**Comment by geeknoid** [comment]
Hi, thanks for the added test. The code coverage report still shows a drop of 10% coverage in scope.go and 20% in default.go. Is this a tooling problem, or are there still uncovered new lines?

Thanks.

**Comment by hzxuzhonghu** [comment]
@geeknoid Sorry， now I add a new test for scope.go. And run `go test -v -cover istio.io/istio/pkg/log/` in my local env, got the result:

```
PASS
coverage: 100.0% of statements
ok  	istio.io/istio/pkg/log	0.188s	coverage: 100.0% of statements

```

**Pull request merged**
