### PR TITLE
Recreate PR for merge of 1.1 to master

### PR DESCRIPTION
**Pull request by louiscryan**
This is a clone of https://github.com/istio/istio/pull/11722 which @duderino committed but unintentionally squashed the merges.

### CODE REVIEW

**Comment by duderino** [comment]
Approved by admin.  Louis is going to try to push directly to master from the git cli to preserve commit history

**Comment by pitlv2109** [comment]
Wrong reference?

**Comment by louiscryan** [comment]
CLA evaluation was done in previously committed PR, no delta in commits

**Comment by louiscryan** [comment]
@pitlv2109 yup, fixed

**Comment by louiscryan** [comment]
Closing in favor of https://github.com/istio/istio/pull/11911

**Pull request closed without merging**
