### PR TITLE
update deployment and services requirements url for istioctl add-to-mesh

### PR DESCRIPTION
**Pull request by shamsher31**

### CODE REVIEW

**Comment by tanjunchen** [comment]
i think it is better than now.

**Comment by shamsher31** [comment]
> i think it is better than now.

Thanks. Sometimes the URLs moved into different sections in istio.io docs, other times it breaks because it gets removed from docs. I'm thinking to create commonplace to update these URL's so that we don't have to keep refactoring a lot of files.

**Pull request merged**
