### PR TITLE
[DO-NOT-MERGE] test update to latest proxy SHA.

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by qiwzhang** [comment]
DO NOT SUBMIT. Just for testing

**Comment by qiwzhang** [comment]
prow/e2e-smoke.sh FAILED == first time.  It doesn't seem related to Envoy.

=== RUN   TestSvc2Svc
I0126 00:02:10.645] 2018-01-26T00:02:10.642615Z	info	Running command kubectl get pods -n simple-auth-test-a995363db2b94d58b41f -l app=echosrv -o jsonpath={.items[*].metadata.name}
I0126 00:02:11.116] 2018-01-26T00:02:11.116605Z	info	Command output: 
I0126 00:02:11.117]  echosrv-deployment-1077105825-8z19r echosrv-deployment-1077105825-9vr82, err: <nil>
I0126 00:02:11.117] 2018-01-26T00:02:11.116674Z	info	From pod "echosrv-deployment-1077105825-8z19r"
I0126 00:02:11.117] 2018-01-26T00:02:11.116693Z	info	Running command kubectl exec -n simple-auth-test-a995363db2b94d58b41f echosrv-deployment-1077105825-8z19r -c echosrv -- /usr/local/bin/fortio load -qps 0 -t 10s http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo
I0126 00:02:12.286] 2018-01-26T00:02:12.286594Z	info	Command output: 
I0126 00:02:12.287]  Fortio 0.6.6 running at 0 queries per second, 4->4 procs, for 10s: http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo
I0126 00:02:12.287] 00:02:12 I httprunner.go:72> Starting http test for http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo with 4 threads at -1.0 qps
I0126 00:02:12.287] 00:02:12 E http.go:513> Unable to connect to {10.67.254.169 8080 } : dial tcp 10.67.254.169:8080: getsockopt: connection refused
I0126 00:02:12.287] Aborting because error -1 for http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo: ""
I0126 00:02:12.287] command terminated with exit code 1
I0126 00:02:12.288] , err: exit status 1
I0126 00:02:12.288] --- FAIL: TestSvc2Svc (1.64s)
I0126 00:02:12.288] 	simple1_test.go:119: kubectl failure to run fortio command failed: "Fortio 0.6.6 running at 0 queries per second, 4->4 procs, for 10s: http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo\n00:02:12 I httprunner.go:72> Starting http test for http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo with 4 threads at -1.0 qps\n00:02:12 E http.go:513> Unable to connect to {10.67.254.169 8080 } : dial tcp 10.67.254.169:8080: getsockopt: connection refused\nAborting because error -1 for http://echosrv.simple-auth-test-a995363db2b94d58b41f:8080/echo: \"\"\ncommand terminated with exit code 1\n" exit status 1

==

**Comment by qiwzhang** [comment]
====ALL TESTS PASSED 2nd time

**Comment by qiwzhang** [comment]
====ALL TESTS PASSED 3rd time

**Comment by qiwzhang** [comment]
====ALL TESTS PASSED 4th time

**Comment by qiwzhang** [comment]
@rshriram @hklai @costinm @lizan @kyessenov 

* istio-pilot-e2e test has been passed in prow for this PR 4, 5 times.
* In my local,  I tested it 20 times, all passed

Any more tests do you want to do?

Can we trust the latest Proxy/Envoy and merge this PR?

**Comment by hklai** [comment]
Probably want to retest in circle CI as well. /retest only triggers prow tests I think.

**Comment by costinm** [comment]
https://github.com/istio/istio/pull/2865 has a recent failure - but it's
with the old envoy.

So likely it's not a regression - I'm +1 to move it to current envoy, but
it's still P0 to reproduce it and fix it.
(really P0)

**Comment by kyessenov** [comment]
The original segfault I noticed happened in circleci, for which we do not
collect logs.
I haven't filed an issue since there were no logs available, and all I know
it's a segfault.

**Comment by qiwzhang** [comment]
From this PR UI, /retest cause all circleci tests to re-run too (turn yellow).  

How do I re-run circleci tests  if /retest doesn't work?

**Comment by lizan** [comment]
Click CircleCI and login with your GitHub, you should see Rerun button.

I tried rerun with SSH, but couldn't reproduce segfault.

**Comment by costinm** [comment]
Segfault was observed in both prow and CI - since it's also happening in the old envoy I think 
we can move ahead, and Andra's PR should collect the full log when it happens. AFAIK there are no
logs in either - the code is just printing that line and doesn't seem to save the log anywhere.

Note that Andra's PR also moves envoy forward, so watch for failures in regular prow/CI builds.

**Comment by rshriram** [comment]
@qiwzhang https://github.com/istio/istio/wiki/Working-with-CircleCI has the screenshots/tutorial for circleci one time setup. and as @lizan pointed out, you can ssh into the VM and debug the segfault if you can reproduce it. 

btw, @kyessenov circleci does have logs.. in the artifacts section. But since we are dumping all logs to console, nothing is stored in log file. you can download the entire console log.

**Comment by hklai** [comment]
AFAICT the test failure rate was much higher before envoy version was
rolled back, and people had problem merging last week. Do we have any
explanation?

**Comment by ldemailly** [comment]
we are loosing stderr from envoy containers somehow - specifically envoy's stderr upon failure

we can't see "initializing epoch 0" anywhere in the build output, which is the first thing envoy prints on stderr or  "starting main dispatch loop" which it prints a bit later

So we just need to gather stderr in the pilot tests on circleci ? How are we starting envoy exactly in the pods - is there an issue with pilot-agent's file descriptor handling when it spawns envoy ?

**Pull request closed without merging**
