### PR TITLE
[Kiali][release-1.0] updating cluster roles necessary for the kiali v0.12.0

### PR DESCRIPTION
**Pull request by jmazzitelli**
in case istio 1.0.x has another release, this PR will be needed.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
tests are failing due to this issue: #10706

**Comment by jmazzitelli** [comment]
re-run tests after this is merged: https://github.com/istio/istio/pull/10708

**Comment by jmazzitelli** [comment]
I rebased on the new release-1.0 branch with the new cert fixes. let's see how that goes

**Comment by jmazzitelli** [comment]
@linsun @gyliu513 who has merge-permission to merge this in? I have a feeling there will be another 1.0.x release now that it seems 1.1 is going to be delayed a little while longer.

**Comment by gyliu513** [comment]
@jmazzitelli , I think @linsun should have the permission.

**Pull request merged**
