### PR TITLE
Enable service-apis by default

### PR DESCRIPTION
**Pull request by howardjohn**
This has been around for ~3 releases now and been tested during this
time. This is pretty low risk since unless the user actually has the
CRDs in their cluster, this does absolutely nothing. If they do have the
CRDs, we still exit early if none of them reference the Istio
controller.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Review by costinm — APPROVED** [review]
User will also need to create the istio class I believe - so super safe.

**Comment by hzxuzhonghu** [comment]
Will istiod print spammy error logs if service-apis crds are not installed?

**Comment by howardjohn** [comment]
No, it will log a single time at start up. The same applies to any CRD
actually; you can run with none installed

**Comment by hzxuzhonghu** [comment]
Let me have a test

**Comment by hzxuzhonghu** [comment]
@howardjohn Verified, the logs is always printed 
```
2021-01-18T01:34:50.196922Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)
2021-01-18T01:34:51.132319Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: failed to list *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)
2021-01-18T01:34:54.078537Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: failed to list *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)
2021-01-18T01:34:58.867291Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: failed to list *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)
2021-01-18T01:35:08.435149Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: failed to list *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)
2021-01-18T01:35:29.235954Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: failed to list *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)
2021-01-18T01:36:03.023648Z	error	klog	k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1alpha3.Gateway: failed to list *v1alpha3.Gateway: the server could not find the requested resource (get gateways.networking.istio.io)

```

**Comment by howardjohn** [comment]
I don't see how that would be caused by this? the error is for Istio's gateway, not service-apis.

If a crd is present, we ignore it in crdclient and never attempt to create a watch

**Comment by hzxuzhonghu** [comment]
I deleted the istio gateway crd

**Pull request merged**
