### PR TITLE
gateway-api: reconcile grpc routes

### PR DESCRIPTION
**Pull request by dddddai**
**Please provide a description of this PR:**
Fixes https://github.com/istio/istio/issues/49373

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
How can we prevent missing update these places when we add a new API support

**Comment by eguzki** [comment]
Great!  Looking forward for an Istio release with this feature. 

BTW, is there a way I can test this? Maybe setting some specific istio image version?

Currently we are deploying Istio with 

```
ISTIOVERSION = 1.20.0 
curl -sSL https://istio.io/downloadIstio | ISTIO_VERSION=$(ISTIOVERSION) sh -
```
```
istioctl operator init
```

```
kubectl apply -f - <<EOF
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        env:
          - name: PILOT_ENABLE_ALPHA_GATEWAY_API
            value: "true"
        resources:
          requests:
            cpu: "0"
  values:
    pilot:
      autoscaleEnabled: false
    global:
      istioNamespace: istio-system
EOF
```

**Comment by dddddai** [comment]
> BTW, is there a way I can test this? Maybe setting some specific istio image version?

Yes you can change the istiod image to `gcr.io/istio-testing/pilot:1.22-alpha.459fb2e507d0e217d767e8b679e9895d3800bf5f` and test it out

**Comment by dddddai** [comment]
> How can we prevent missing update these places when we add a new API support

Yeah I have the same concern..

**Comment by spacewander** [comment]
Will this fix backport to Istio 1.21.2?

GRPCRoute is going to be graduated to GA in the coming Gateway API 1.1, people will investigate the usability of GRPCRoute. Waiting for 1.22 would be too long.

**Comment by howardjohn** [comment]
> Will this fix backport to Istio 1.21.2?
> 
> GRPCRoute is going to be graduated to GA in the coming Gateway API 1.1, people will investigate the usability of GRPCRoute. Waiting for 1.22 would be too long.

Istio generally doesn't back port features. Istio 1.22 and Gateway 1.1 will release at about the same time

**Pull request merged**
