### PR TITLE
[cherrypick] [vendor change] Add B3 codec to Jaeger tracer to enable mixer trace to be included in the application trace - and extended zipkin test to check for the mixer span

### PR DESCRIPTION
**Pull request by objectiser**
Cherry picked from #5116 as suggested by @douglas-reid [here](https://github.com/istio/istio/pull/5116#issuecomment-383967174).

Note: the vendor change from `dep ensure` has resulted in more than just the jaeger/zipkin dependency being added, it has resulted in a number of unused (I assume) dependencies being removed.

### CODE REVIEW

**Comment by objectiser** [comment]
@douglas-reid All the required tests seem to have passed, but the Submit Queue seems dependent upon the circleci/racetest passing - which it doesn't seem to be doing on most recent PRs - so would you be able to manually merge this?

**Comment by rshriram** [comment]
closing this PR as we are merging master into 0.8

**Pull request closed without merging**
