### PR TITLE
Add the new CNI field "chained"

### PR DESCRIPTION
**Pull request by jwendell**
Addresses https://github.com/istio/istio/issues/20202

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
@jwendell Is istio-cni working as standalone plugin instead of chained plugin? I have tried that for istio-1.1 release, but it did't work at that time.

/cc @clyang82

**Review by rlenglet — APPROVED** [review]

**Comment by jwendell** [comment]
> @jwendell Is istio-cni working as standalone plugin instead of chained plugin? I have tried that for istio-1.1 release, but it did't work at that time.
> 
> /cc @clyang82

Yes, depending on the environment. That's exactly what this PR enables. Once this gets in I'll update the docs instructing users on how to make use of it.

**Review by morvencao — APPROVED** [review]

**Pull request merged**
