### PR TITLE
Rollout Status timeout during e2e tests

### PR DESCRIPTION
**Pull request by mbanikazemi**
Addresses issue #9685

### CODE REVIEW

**Comment by mbanikazemi** [comment]
Looking at the failures, there are a few where some Istio pods did not get up and running on time, say `pilot` keeps crashing or `istio-security-post-install` gets stuck in pulling the image but the majority of failures are related to `rollout status` timing out in 8 minutes. One possible solution is to merge this PR and see if doubling the timeout will reduce the number of failures.

**Comment by linsun** [comment]
@mbanikazemi can you fix all the required tests?

Once that is done, ping release czar (Josh or Wencheng) for merge into 1.1.

**Comment by mbanikazemi** [comment]
@wenchenglu Could you please have a look and see if can merge.

**Pull request merged**
