### PR TITLE
Remove hardcoded sidecar template for istioctl kube-inject

### PR DESCRIPTION
**Pull request by mathspanda**
Fix issue #10380 

1. Remove hardcoded sidecar template in `kube-inject`.
2. Modify some tests to read sidecar template from `install/kubernetes/helm`.
3. Remove some meaningless tests for injecting.

Signed-off-by: mathspanda <mathspanda826@gmail.com>

### CODE REVIEW

**Comment by incfly** [comment]
Thanks for this work!

I'm currently out of office till 1/9. @mandarjog, @nmittler maybe you can provide some initial feedback?

**Comment by mathspanda** [comment]
The merge branch is wrong. Will pull another request. Just close it.

**Pull request closed without merging**
