### PR TITLE
unify cobra args validation.

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

/kind cleanup

Let cobra args unify, for the validation logic.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
this seems like a regression as we loose helpful error messages

**Comment by yanggangtony** [comment]
> this seems like a regression as we loose helpful error messages

Hi, just close the pr , is that ok?

**Comment by zhlsunshine** [comment]
Hi @yanggangtony,  why this unify args validation?

**Comment by yanggangtony** [comment]
> Hi @yanggangtony, why this unify args validation?

@zhlsunshine 
because i think it is can be done well by cobra .
And there are some place use cobra args validation , and some places not..
What's your point about these and do you think it is necesary?

**Comment by zhlsunshine** [comment]
> > Hi @yanggangtony, why this unify args validation?
> 
> @zhlsunshine because i think it is can be done well by cobra . And there are some place use cobra args validation , and some places not.. What's your point about these and do you think it is necesary?

Hi @yanggangtony, IMO, it's unnecessary to do this kind of verification

**Pull request closed without merging**
