### PR TITLE
pilot/pkg/xds: optimize the push queue using linked list

### PR DESCRIPTION
**Pull request by panjf2000**
The push queue buffer is currently based on slice which may grow its size redundantly:
```go
	newcap := old.cap
	doublecap := newcap + newcap
	if cap > doublecap {
		newcap = cap
	} else {
		if old.cap < 1024 {
			newcap = doublecap
		} else {
			// Check 0 < newcap to detect overflow
			// and prevent an infinite loop.
			for 0 < newcap && newcap < cap {
				newcap += newcap / 4
			}
			// Set newcap to the requested cap when
			// the newcap calculation overflowed.
			if newcap <= 0 {
				newcap = cap
			}
		}
	}
```
Either it doubling up the capacity (when less than 1024) or growing by a factor of 1.25 (when greater than 1024).

Since the push queue is not accessed by index, I suggest that we replace the slice with a linked list which only takes up space when it's needed, and release the element when it has been popped up.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Did you observe memory growth with this?  What are the typical queue sizes? Wondering, is there a real problem here?

**Comment by panjf2000** [comment]
> Did you observe memory growth with this? What are the typical queue sizes? Wondering, is there a real problem here?

I believe that it's not a fatal issue, just a little concern here, and try to make a tiny improvement.

**Review by howardjohn — CHANGES_REQUESTED** [review]
Any change should either be fixing a bug, or of it's an optimization it should be clear it's an improvement (typically by benchmarks). This changes doesn't appear to be either. See https://github.com/istio/istio/wiki/Development-Conventions#superfluous-changes

I appreciate the effort you have put into this but I am not sure this change is improving the code and I am worried about destabilizing a critical part of our code base.

**Comment by hzxuzhonghu** [comment]
I would expect a benchmark comparison between slice and linked list.

**Pull request closed without merging**
