### PR TITLE
Removing Lua as one of the languages istio uses ;-)

### PR DESCRIPTION
**Pull request by ldemailly**
Scripts not used (no hits from git grep; and compilation/tests should confirm)

Also anything that wrk does fortio can do better

istio languages

### CODE REVIEW

**Comment by ldemailly** [comment]
btw @yutongz can we change the text of the bot message to say "/lgtm" instead of "/approve" as it's "/lgtm" that is needed for merging ? (or change /approve to put lgtm label?)

**Comment by sebastienvas** [comment]
Thanks for doing this ! 
/lgtm

**Comment by ldemailly** [comment]
it passed the tests the first time and failed on unrelated 

I0120 01:12:56.282] istio.io/istio/mixer/pkg/perf.(*ClientServer).initializeRPCServer.func1(0xc4202360c0)
I0120 01:12:56.282] FAIL    istio.io/istio/mixer/pkg/perf 

on the second pass so I merged

**Pull request merged**
