### PR TITLE
set imagePullSecrets with values.yaml

### PR DESCRIPTION
**Pull request by abrahamjoc**
**Please provide a description of this PR:**
This PR is for allowing to pull image from different registry

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ x] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Why is this under global.imagePullSecrets? Its already there in `imagePullSecrets`?

**Comment by abrahamjoc** [comment]
oh sorry that's true but the other charts are with global.imagePullSecrets and I just left it the same

**Comment by howardjohn** [comment]
That is intended. The other charts are all nested under `global.xyz.bar` which is due to legacy reasons. This chart was explicitly intended to do things the right way.

**Comment by howardjohn** [comment]
Ah yeah I see that is accidentally forgotten. Thanks

**Pull request closed without merging**
