### PR TITLE
Add upgrade test to post-submit test suite.

### PR DESCRIPTION
**Pull request by yusuoh**

### CODE REVIEW

**Comment by yusuoh** [comment]
The tests seem to be failing on some missing files.

I0320 05:04:00.733] 2018-03-20T05:04:00.726603Z	error	Cannot read original yaml file /home/bootstrap/go/src/istio.io/istio/_artifacts/upgrade-test-b9c4c47d821540c9a1142761/istio-0.6.0/install/kubernetes/istio-mixer-validator.yaml
I0320 05:04:00.733] 2018-03-20T05:04:00.726728Z	error	Generating yaml /home/bootstrap/go/src/istio.io/istio/_artifacts/upgrade-test-b9c4c47d821540c9a1142761/yaml/istio-mixer-validator.yaml failed
I0320 05:04:00.734] 2018-03-20T05:04:00.726783Z	error	Failed to deploy Istio.
I0320 05:04:00.734] 2018-03-20T05:04:00.726946Z	error	Failed to complete Init. Error open /home/bootstrap/go/src/istio.io/istio/_artifacts/upgrade-test-b9c4c47d821540c9a1142761/istio-0.6.0/install/kubernetes/istio-mixer-validator.yaml: no such file or directory

**Comment by chxchx** [comment]
@costinm The tests are added to e2e_all make target so they are available to all CI and developers.

**Comment by chxchx** [comment]
@yusuoh do we know why the files are missing? It does not seem to be the case for other runs of the same jobs.

**Comment by yusuoh** [comment]
e2e-cluster_wide-auth failed because it has with_mixer_validator enabled. We added a new yaml file (istio-mixer-validator.yaml) recently while it does not exist in 0.6. This is cause upgrade test fail when deploying Istio.

The other one (e2e-suite-rbac-auth.sh) seems to be failing on Mixer tests. The upgrade test is actually passing.

**Comment by yusuoh** [comment]
@chxchx I have fixed the upgrade test. It passed locally with with_mixer_validator enabled. However, I don't know why the post-submit is still failing. Does it require the code to be checked in?

**Comment by chxchx** [comment]
/hold
Could you also add a skew test target using your upgrade framework (using different flags)? The current skew test is actually not the best reflection of what customers will do. See https://github.com/istio/istio/issues/4398.

**Comment by yusuoh** [comment]
I already sent out a PR to fix it. See #4472

**Pull request merged**
