### PR TITLE
Integration test for Prometheus certificate provisioning

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: Integration test for Prometheus certificate provisioning.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by lei-tang** [comment]
@mandarjog @kyessenov Can you review the PR?

**Comment by lei-tang** [comment]
@istio/wg-policies-and-telemetry-maintainers Can you review the PR?

**Comment by bianpengyuan** [comment]
Does this test needs to be under `telemetry` folder? It does not actually verify any telemetry feature. `security` folder seems to be a better place for it.

I think the desired test to add under `telemetry` is to verify that prometheus could scrape app metrics when SDS is turned on.

**Comment by lei-tang** [comment]
The reasons to organize this test under telemetry are:
- This test is to verify the certificate provisioning for Prometheus, which is a telemetry component.
- This test runs as a subtest within the telemetry test suite, instead of duplicating the telemetry suite under the security folder and running this test in a new telemetry deployment.

**Comment by bianpengyuan** [comment]
The test does not verify anything related to prometheus or telemetry. It verifies the sidecar inside prometheus pod is generating cert. e2e test is feature oriented and the feature to verify here is about certificate provision.

This test does not need any telemetry set up. The only option needed is `cfg.Values["prometheus.enabled"] = "true"`

**Comment by lei-tang** [comment]
The certificate provisioning feature tested here is specific to Prometheus and no other component uses the same feature. The certificate provisioning feature for Prometheus is related to the functioning of Prometheus and should be integration tested as part of the Prometheus integration test. 
Running this test under security using a new test suite instead of a subtest under telemetry also prolongs the total test running time.

**Comment by lei-tang** [comment]
Meanwhile, this test does need telemetry setup, e.g.,
	cfg.Values["telemetry.enabled"] = "true"
	cfg.Values["telemetry.v1.enabled"] = "false"
	cfg.Values["telemetry.v2.enabled"] = "true"
	cfg.Values["prometheus.enabled"] = "true"

**Comment by bianpengyuan** [comment]
Why does it need telemetry options? It just need prometheus to be enabled... (cfg.Values["prometheus.enabled"] = "true")

**Comment by lei-tang** [comment]
cfg.Values["prometheus.enabled"] = "true" is a telemetry option, no?

**Comment by bianpengyuan** [comment]
I think the proper test we should add is to verify prometheus could scrape app metrics when mtls is turned on, which should cover what being tested here. wdyt? Feel free to open an issue and assign it to me.

**Comment by lei-tang** [comment]
An integrationt test that verifies Prometheus can scrape app metrics when mTLS is turned on will be useful and can be added in a separate PR. The integration test in this PR tests the foundation of the Prometheus mTLS since the Prometheus certificate provisioning is the foundation of Prometheus mTLS. So both integration tests are useful and they are different, e.g., when Prometheus mTLS fails, the Prometheus certificate provisioning may work correctly.

**Comment by lei-tang** [comment]
@istio/wg-policies-and-telemetry-maintainers Can you review the PR?

**Comment by bianpengyuan** [comment]
hmm I don't understand why they are different. Scraping with mTLS essentially covers certificate provisioning, and this is the actual feature we are shipping.

**Comment by lei-tang** [comment]
mTLS and certificate provisioning are different, e.g., certificate provisioning may succeed while mTLS may fail. mTLS is mutual TLS and certificate provisioning is to generate a certificate.

**Comment by bianpengyuan** [comment]
Isn't this certificate used to scrape application metrics from a port with mTLS enabled? Otherwise what is the usage of this cert?

**Comment by lei-tang** [comment]
Yes, the certificate provisioned is used by mTLS. But it does not mean certificate provisioning and mTLS are the same.

**Comment by bianpengyuan** [comment]
Ok then if prometheus could scrape metrics from a mTLS secured port, does it mean certificate is provisioned successfully in prometheus? Doesn't that cover what you are testing here? Isn't user visible behavior (metrics show in prometheus) what we really want to verify in e2e test, not detailed set up (prometheus has certs)?

Also the mechanism for prometheus scraping mTLS port is changing, I don't think the behavior you tested here is going to exist for long term. I don't think it should be in telemetry test suite.

**Comment by lei-tang** [comment]
Based on the review comments, the test is moved to the security folder.

**Comment by howardjohn** [comment]
Strongly agree with @bianpengyuan comments, we should be testing mtls scraping works not looking for the cert

**Pull request merged**
