### PR TITLE
Fix webhook issues in installation process

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
1. In dry-run mode, the webhook is still being modified.
2. The creation of the webhook used a fixed system namespace "istio-system", which should use the actual system namespace.

### CODE REVIEW

**Review by ymesika — APPROVED** [review]
lgtm

**Review by howardjohn — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Comment by hanxiaop** [comment]
@istio/wg-user-experience-maintainers PTAL, thanks

**Comment by hanxiaop** [comment]
After merging with the master, the changes made in https://github.com/istio/istio/pull/44410 have already addressed the fixed namespace issue. The only thing left is to handle the dry run option.

**Pull request merged**
