### PR TITLE
[release 1-.5] Remove multicluster zvpn from ingress/egress default

### PR DESCRIPTION
**Pull request by sdake**
Multicluster is alpha as per preliminary feature pages. As
such, demoting this zvpn default of true to false.

Manually ran:
```
BUILD_WITH_CONTAINER=1 make update-charts
BUILD_WITH_CONTAINER=1 make update-goldens
```
Fixes: https://github.com/istio/istio/issues/21440
(cherry picked from commit 0b82ab666670d262ee7cf3e095f00369651a1c35)

 Conflicts:
	operator/data/profiles/default.yaml
	operator/pkg/vfs/assets.gen.go

### CODE REVIEW

**Comment by sdake** [comment]
@ostromart this PR had merge conflicts. I executed the above steps to remove the merge conflicts. can you please provide a review of this PR ahead of the T&R team?

It appears `make update-goldens` was not run by prior cherrypicks. This step seems necessary to me.

**Comment by ostromart** [comment]
@sdake sometimes merges cause assets to have conflicts, and sometimes auto merges are not correct (wrt how go-bindata would write the file) so that's where the conflicts come from. We do have gencheck to prevent conflicts being merged though.

**Comment by sdake** [comment]
@johnma14 @ostromart already gave a review above.

Cheers
-steve

**Pull request merged**
