### PR TITLE
Bugfix for race conditions

### PR DESCRIPTION
**Pull request by girishranganathan**

### CODE REVIEW

**Comment by douglas-reid** [comment]
@girishranganathan is this PR still in development? Is there any way we can rebase ?

**Comment by girishranganathan** [comment]
Hello @douglas-reid, technically no. I had finished the work almost a month back. @geeknoid had approved the code. I think e2e tests were failing and they were being fixed. When I checked a few weeks back, @xiaolanz had made some changes attempting to fix the issues. Now I am kind of confused/concerned that if I try to bring my changes in, it will overwrite @xiaolanz.
Please advise.

**Pull request closed without merging**
