### PR TITLE
[WIP] Add contextpath kiali and jaeger ui

### PR DESCRIPTION
**Pull request by clyang82**
1. add contextpath for jaeger and kiali
https://github.com/kiali/kiali/issues/526
https://github.com/jaegertracing/jaeger-ui/issues/258
2. if there is no ingress host defined, should allow to expose the service for all hosts.

### CODE REVIEW

**Comment by clyang82** [comment]
I signed it!

**Comment by sdake** [comment]
@linsun we have implementations of GW/VS/DR for both kiali and jaeger in the repository.  Sounds like they need a little more attention for the condition of control plane security enabled.

If I parsed your statement correctly, we also need to add ingress to prometheus and grafana - is that correct?

Cheers
-steve

**Comment by linsun** [comment]
@sdake yes for consistency, if we are adding it for kiali but not for other telemetry related services.

**Comment by gyliu513** [comment]
@sdake @linsun As Jaeger and Kiali are Istio add-on components, and there maybe cases that the end user want to use their own ingress controller as proxy to access those services, so I think we still need to support Kiali and Jaeger running with ingress services for integration with 3rd party ingress controller.

@clyang82 your PR needs rebase.

**Comment by clyang82** [comment]
@sdake @linsun @gyliu513 Thanks for your comments. I will handle adding ingress to prometheus and grafana in another PR.

**Comment by douglas-reid** [comment]
@linsun @sdake i'm fine with supporting both ingress and ingressgateway, but I had been previously advised that we were not going to support ingress moving forward, and so I shouldn't bother with adding stuff for `prometheus` and `grafana`. I would like us to adopt some understandable and universal posture around these decisions, as they seem to change with the wind ;).

**Comment by sdake** [comment]
@douglas-reid Roger.  The struggle we have documenting and communicating fairly big decisions like this are real as the size of our developer community grows.  With success comes harder problems to solve :).  Some type of decision log may be helpful for the project, although that seems the WG leads decision to implement or the TOC to coordinate.  IOW not sure who is responsible for communicating these fundamental decisions.

As for this specific thing changing, I think recently we (not sure who? :) have decided kubernetes ingress is something we want to enable for the transitory case of people moving to Istio incrementally (e.g. step 1 = current ingress + mesh, step 2 = ingressgateway + mesh).  I think we were hopeful that operators would just be satisfied to deploy Istio's ingress, but it appears we (may?) have data indicating this isn't always the case.

**Comment by gyliu513** [comment]
Good to see we have a conclusion here 👍 

@clyang82 please rebase and then we can merge this.

**Pull request closed without merging**
