### PR TITLE
fix inconsistent cr hash.

### LINKED ISSUE #27355: Istio Operator should revive the Istio deployments once they are deleted
**Bug description**
Using the latest code base or any version of istio operator to install istio, three deployments, istio-egressgateway, istio-ingressgateway and istiod are launched.

If we delete any of these deployments, they cannot be revived by the istio operator. Istio operator still indicate the deployment is in health status with CR status info.

[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Install Istio with Istio Operator.
After all the deployments are launched by creating the CR, delete any one deployment resource of istio.
The deleted deployment should be restored by the istio operator.

**Steps to reproduce the bug**
Install Istio with Istio Operator.
After all the deployments are launched by creating the CR, delete any one deployment resource of istio.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Latest, every istio operator version

**How was Istio installed?**
Via operator

**Environment where bug was observed (cloud vendor, OS, etc)**
All environments

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/27355
Will add test for https://github.com/istio/istio/issues/27355 in followup PR.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by richardwxn — APPROVED** [review]

**Comment by houshengbo** [comment]
I confirm that this PR resolve the issue #27355.

**Pull request merged**
