### PR TITLE
Added authorization template

### PR DESCRIPTION
**Pull request by mangchiandjjoe**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Authorization adapter template.
Any authorization module needs to answer the question: Is a “subject” allowed to do an “action”. 
```

### CODE REVIEW

**Comment by geeknoid** [comment]
This looks fine as a temporary state. We're just about to check in support for submessages in Mixer, and we should update this template when that happens.

@guptasu is working on submessage support, he can comment on when he thinks the functionality will land.

**Comment by guptasu** [comment]
Hi @mangchiandjjoe I am hopeful that by end of next week, the sub messages will be done and documented.

**Comment by mangchiandjjoe** [comment]
Thank you for your update.

**Comment by mangchiandjjoe** [comment]
Are we going to merge this change now or wait for the sub messages update?

**Comment by mangchiandjjoe** [comment]
@geeknoid @guptasu @liminw Any idea when do we want to merge this change?

**Comment by guptasu** [comment]
@mangchiandjjoe good news. I just submitted a PR that supports generation of code with submessages. That should make your PR work with submessages, except the change in the template/BUILD file that you have. So, if you remove the `template/BUILD` file and leave the other 2 files and modify the template definition to use submessages, you should be fine.

Also, I am about to send out the last PR that finishes the submessage work. After that you can even include the changes in template/BUILD and should be able to build the Mixer with your template.

**Comment by mangchiandjjoe** [comment]
@guptasu Great news!! Thank you for the quick update. :)

**Comment by mangchiandjjoe** [comment]
I am closing the pr for now

**Pull request closed without merging**
