### PR TITLE
It seems prune resolves the depupdate issues

### PR DESCRIPTION
**Pull request by costinm**
Also removed tools - it's not a direct dep and master doesn't have to be listed, it's the default.

### CODE REVIEW

**Comment by costinm** [comment]
Consider this as submitting a small (and non-controversial) part of #3348 :-)

**Comment by ldemailly** [comment]
you also need the rest of my fixes for this to pass... let's not waste time duplicating effort and get the right fix in (you can improve caching too if you want, after)

**Comment by ldemailly** [comment]
I think tools is needed somewhere in the build too @geeknoid 
(but again we don't need this)

**Comment by ldemailly** [comment]
/hold
until tomorrow 1pm

**Pull request closed without merging**
