### PR TITLE
Remove istioctl manifest migrate command

### LINKED ISSUE #22716: Remove manifest migrate
John Howard  4 minutes ago
can we remove the code to convert ICP -> IOP now? Seems like a user can follow the 1.4 -> 1.5 -> 1.6 upgrade path so in 1.6 we don't need to support it any longer. Same applies for manifest migrate (in 1.7, though)?

Martin Ostrowski  2 minutes ago
i think icp to iop we can probably remove. manifest migrate we should keep for another release i think

John Howard  2 minutes ago
Agreed, since folks upgrading to 1.6 will need it

John Howard  2 minutes ago
But for 1.7 upgrade they won't, so we can kill it then

Martin Ostrowski  2 minutes ago
sure, sg

### PR DESCRIPTION
**Pull request by howardjohn**
fixes https://github.com/istio/istio/issues/22716

### CODE REVIEW

**Review by richardwxn — COMMENTED** [review]
I thought we are removing migrating part for icp->iop not the whole cmd?

**Comment by howardjohn** [comment]
@richardwxn if a user wants to translate they can use the old 1.6 istioctl. There will be no users migrating from 1.6 helm -> 1.7 iop, as 1.6 helm does not exist. We cannot feasibly maintain a helm -> iop migration path anymore, the entire architecture has changed. well over 50% of the values no longer have a logical equivalent anymore

**Review by sdake — APPROVED** [review]
this should not be backported to 1.6 AFIACT based upon @ostromart 's comments in the linked issue.

**Comment by howardjohn** [comment]
yes for master only

**Review by elfinhe — APPROVED** [review]

**Pull request merged**
