### PR TITLE
Remove busybox

### PR DESCRIPTION
**Pull request by ostromart**
A step towards being completely GPL free.
I believe we don't need this now since we have pretty good debug tool coverage and all essential core utils are in the distro.

### CODE REVIEW

**Comment by costinm** [comment]
I would also suggest swapping the base to "FROM debian:9-slim" and replacing dnsutils with knot-dnsutils.

**Comment by sdake** [comment]
@ostromart can you hold off on going to debain:9-slim?  I'd like to see if we can find an approach that nets us debian:9-slim like characteristics, with a xenial base.

Cheers
-steve

**Comment by sdake** [comment]
I gave a try to `docker --squash` after removing the delta above.  The squashed image ends with two layers.  There is no way to further reduce the layering that I see without creating a custom FROM...

Reading the docker documentation, it appears the ability to squash into one layer is not possible.  Kind of a bummer.

**Pull request merged**
