### PR TITLE
Decouple golden outputs from live manifests

### PR DESCRIPTION
**Pull request by ostromart**
Even with golden changes now being rolled up in review, there's no need to change all goldens for every PR. One is enough - and that one is all_on, which enables everything. This means that any change in the template will lead to usually a small diff in one output file, which should still be part of a PR changing the templates.
Tested with a change in istiod deployment template, only all_on golden output yaml is affected as expected.

### CODE REVIEW

**Review by sdake — COMMENTED** [review]
I took a look at the PR. What generates the data-snapshot directory? Should there be a make target for it?

This long list of files may lead to merge conflicts during backports.

I'd like to see the operator get to the point that `make gen` or `make update-goldens` doesn't result in a massive churn for maintainers doing backport work.

I am curious if further improvements could be made here to just remove the data-snapshot directory, and not check this directory in, but instead generate on-demand prior to testing.

**Comment by howardjohn** [comment]
So I think there are two things we want to test:

1) The template in our manifests is correct. Helm is fairly complicated, otherwise this would not be needed (plain yamls would not need tests, for example)
2) Our logic in `manifest generate`/other commands is correct

Currently we test these together, resulting in a change to manifests being propagated to many places.

This PR decouples these, which I think is good, but it does so in a way that I am not sure makes the most sense.

my understanding is that to test (2) we are now going against a complete copy of the manifests, snapshotted at some point in time. Instead, it seems like we can test completely decoupled from the manifests at all, and operating completely independent from the "real" manifests. For example, rough pseudocode:

```
TestOverlay() {
  charts := hello-world-deployment.yaml # 10 line yaml deployment.
  overlay := "... some overlay from hello deployment"
  expected := hello-world-deployment-overlayed.yaml
  assert generate(charts, overlay) == expected
}
```

Does that make sense? In theory I think it would, but not sure if it does in practice.

The concern I would have with this is that it falls out of sync, is sort of pretending to tests the real manifests when it is not actually testing these, maybe add some confusion about everything being copied, and it may cause issues when we make changes to the manifests and now certain values do or do not exist any longer, but they do/do not exist in the copied charts. I am not sure how valid these concerns are though

**Comment by ostromart** [comment]
I get your point and it makes sense but the type of testing you're describing (manifest generate internal logic against a completely fake yaml) is already covered in package level unit tests. At least it should be - there's still work to do to improve that coverage. Those tests mostly avoid assumptions about the inputs being realistic and rather test the API state space. 
The purpose of the goldens is more integration-level testing, meaning that apart from the API tests, any changes in the code should behave sensibly against realistic and more complex inputs. I think this is also useful to provide defense in depth against regression when devs make changes in the manifest/operator code. 
The concern about the manifests drifting is valid but these tests can tolerate a lot of drift before gaps start to appear. We still have the system tests against real manifests and this PR leaves behind one golden file against real manifests (all_on).

**Comment by mandarjog** [comment]
In order for us to verify that “manifest generate” logic  is correct @ostromart you believe  that unit tests are not enough and we *do* need to also test of a snapshot.

If by valid we are *only* testing that the resources are well formed yaml, then It can be done in other ways. What else is being tested in snapshot beyond unit tests ?

**Comment by ostromart** [comment]
Unit tests are not enough to test the logic, integration tests are also needed. To put it in common terminology, here's how I see the various tests:
- unit tests -> mostly package level, isolated tests of function APIs. Charts are not involved.
- integration tests -> the snapshots are part of the integration tests. To me it makes sense to use realistic inputs at this level rather than completely abstract test data.
- e2e/system tests -> checking that Istio was correctly installed, these are the prow tests that use istioctl manifest apply et al.

The one golden file linked to the live manifests is not in any of these three. It is just a means for the person making the change to a template to check that the rendered manifest is what they expect. Ideally this would be covered in some e2e test but often it isn't so this is another line of defense against bad changes going in that pass all existing tests.

**Comment by mandarjog** [comment]
Ok. what you are calling `integration tests` is what I would call `unit tests` with complex inputs.
The fact that the complex / realistic input was generated by say `make snapshot` is an implementation detail.  
I am ok with that.

That just leaves the `all_on.golden` file which will continue to have merge conflicts on template change. Golden files also serve as real examples of rendered output, but that can be separated.

This improves the current state, so I think we should proceed with the PR. We can discuss removing the last golden file as a separate change.

**Comment by howardjohn** [comment]
How often is there a merge conflict in a golden file, but NOT a merge conflict in all_on.yaml? I haven't looked closely enough, but I would expect all_on.yaml to have the most conflicts by nature of it being "all on", and having 1 merge conflict vs 10 merge conflicts doesn't really matter.

**Comment by ostromart** [comment]
all_on will have the most merge conflicts for sure but I think this PR is still worthwhile as a first step. It just addresses the fact that most of the complex input tests among those goldens are testing the generate logic, not the charts. 
As a follow-on I'd like to tackle either some way to reduce conflicts, or discuss removing this remaining "live" golden, possibly by making it also point to the snapshot charts. I have this as a point for discussion in the weekly tomorrow.

**Comment by mandarjog** [comment]
@ostromart if you are talking this tomorrow, we can just hold off.

After this golden file is removed, are any other golden files left in pilot? @howardjohn ?

**Comment by howardjohn** [comment]
There are some for the injection template as well, under pkg/kube/inject

**Comment by kyessenov** [comment]
IMHO we should get rid of all goldens committed to the repository (that applies to all generated artifacts). We think we should add a step in CI that prints the generated file differences, so that they can be manually inspected/compared before/after. I do get the point that it's impossible to understand the code changes without looking at the outputs in pilot/helm, but there's no need to commit them just to see the diffs.

**Comment by kyessenov** [comment]
Another 2c: collecting coverage by producing goldens is not a good indicator that the logic is correct. We should write deliberate unit tests for coverage that verify the output.

**Comment by howardjohn** [comment]
We might even be able to get it set up such that on postsubmit we generate
all the Golden's. Then each pr will generate them as well, compare them,
and leave a comment in the pr of the diff if there is a change. It would
involve some test infra work of course but would give the same level of
visibility.

**Comment by mandarjog** [comment]
1. let’s add a “make gen-diff” target which will output a diff of old vs new. This is what we do inside google for config files.
2. We can do one better, ci/cd will run this target and post the diff results back to the PR for people to inspect.
3. The only other reason why I like golden files is that you can read configuration on GitHub without running any code. We can generate that as post submit build artifacts so you can look at it .

@ostromart ?

**Comment by ostromart** [comment]
All that sounds good to me. To summarize also the offline discussion:
- for now we will have just one file (the kustomize manifest) show up rendered changes when templates change. We will work towards moving this one file to be.emitted by make gen-diff. 
- we will keep the snapshot goldens and charts for the time being. These do not change when the real charts change. Over time, we will work towards refactoring these into more focused tests with programmatically defined expectations on the outputs.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
