### PR TITLE
slow down retries to allow for delayed_close_timeout

### PR DESCRIPTION
**Pull request by stevenctl**
The only consistent pattern in the sniffing test flakes is that we see:

- 0-2 successful "calls" (really it's a burst of 5 * nUpstreams)
- A context based timeout inside the echo forwarders expires. (cx_connect_fail increments, rq_error and rq_total do not)
- We see 1 or more failures due to connection resets. (these show up as rq_error, rq_total does not increment)

--- 

We might be trying to re-use some unhealthy/invalid connection.

[This article](https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/) is sort of interesting. It should mean we don't have to worry about this.. but the TLDR is that kube-proxy does translation between service and pod IPs before they go back to the application. Sometimes conntrack loses track, and things blow up. Do our IP tables rules circumvent this? Do we need an equiv rule to drop these bad packets? 

For now, I want to see if increasing our retry back-off to the same as the default [delayed_close_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto) makes it so the retries do their job.

### CODE REVIEW

**Comment by stevenctl** [comment]
Going to hold this for now and retest the multicluster-pilot job a few times.

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
Ah actually - we have Converge(3). this means all tests will take, at minimum, 3s I think?

**Comment by stevenctl** [comment]
Hm... maybe I'll add an option to retry for backoff which overrides delay and only applies after a failure.

**Comment by stevenctl** [comment]
Actually looks like the run had things finish sub 1s so we're probably fine.

**Comment by howardjohn** [comment]
I see, maybe I already made converge not wait for the delay

**Pull request merged**
