### PR TITLE
Expose RENEW_DEADLINE env variable in operator

### PR DESCRIPTION
**Pull request by nielsole**
**Please provide a description of this PR:**
Exposes RENEW_DEADLINE  env variable for configuration https://github.com/istio/istio/pull/28085
This is useful if one hits: https://github.com/istio/istio/issues/27509

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by nielsole** [comment]
I now see this was already attempted to merge once: https://github.com/istio/istio/pull/28085/commits/4a6fe73842689c8128736e1569d9eea8e135540e
From: https://github.com/istio/istio/pull/28085#discussion_r508796737:
> is this really needed? we don't want to introduce new values.yaml stuff
we could also wrap the env variable in an if statement, so that we don't need to change values.yaml. lmk what you prefer.

**Comment by jacob-delgado** [comment]
cc @litong01 can you take a look at this?

**Comment by litong01** [comment]
> I now see this was already attempted to merge once: [4a6fe73](https://github.com/istio/istio/commit/4a6fe73842689c8128736e1569d9eea8e135540e) From: [#28085 (comment)](https://github.com/istio/istio/pull/28085#discussion_r508796737):
> 
> > is this really needed? we don't want to introduce new values.yaml stuff
> 
> we could also wrap the env variable in an if statement, so that we don't need to change values.yaml. lmk what you prefer.

I think that the general consensus is to use the environment without changing the deployment template and values file. I also think changes to these files requires running `make gen`

**Comment by nielsole** [comment]
> the general consensus is to use the environment without changing the deployment template and values file

How does one go about that? There is no `{{- toYaml .extraEnvs | nindent 12 }}` or similar. 
I would be open to changing the PR towards supporting changing env variables without changing the deployment template or values file.

**Comment by nielsole** [comment]
sorry, to bump this. It would seem counterintuitive to me why the operator would have configuration options that are not exposed via the chart. Otherwise every configuration change requires a fork of the chart. 
I just took a look and it seems that `RENEW_DEADLINE` [is the only env variable that is not exposed in the chart](https://github.com/istio/istio/search?q=os.LookupEnv). `LEADER_ELECTION_NAMESPACE` and `WATCH_NAMESPACE` are exposed. Why would `RENEW_DEADLINE` be different?

I see three options going forward:
* refactor all three env variables into `{{- toYaml .extraEnvs | nindent 12 }}`
* Use the approach I chose currently.
* Close this ticket and keep `RENEW_DEADLINE` not exposed to users and require a fork of the chart.

Please let me know which approach you prefer and I will put the PR into good shape.

**Comment by SebTardif** [comment]
Today, what's the faster way to change the value of RENEW_DEADLINE?
I have Image:docker.io/istio/operator:1.13.2

**Comment by nielsole** [comment]
If you want to use the chart, you will have to maintain your own fork unfortunately.

**Comment by howardjohn** [comment]
https://preliminary.istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Pull request closed without merging**
