### PR TITLE
Implement the two-way merging mechanism to update the object

### PR DESCRIPTION
**Pull request by houshengbo**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
It would be great if we had a test case that fails without this change and passes with it so we can fully understand the difference.

**Comment by howardjohn** [comment]
What are the benefits of 2 way merge vs kubectl's 3 way merge? https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/apply/patcher.go#L144

**Comment by houshengbo** [comment]
I have asked @ostromart if we need 3-way before.
However, it seems we only expect changes by istio, so 2-way is enough?

**Comment by ostromart** [comment]
on reflection i'm not sure how a merge operation can be made to work correctly. let's say that we start by installing some customization object (tree) at path X in the IOP and apply it. now it's reflected in the cluster. then, we remove the customization in the IOP - how would it be deleted from the cluster?

**Comment by houshengbo** [comment]
@ostromart For the scenario you just mentioned, Knative operator has met something similar. Knative operator runs a comparison between the old and the new manifests, to find out the delta, to decide what resources to be deleted, what resources to be created and what resources to be updated.

The merging mechanism is only applicable to the `resources to update`.

**Comment by ostromart** [comment]
then i think we are sort of back to the original solution i proposed, where we selectively merge just the few fields that we know are set for us by the k8s server?

**Comment by houshengbo** [comment]
@ostromart If we still want to use the approach that kube does with 2-way merging, the only thing we need to change is to make sure the `current` is what we have now. Do a deep clone of the `current` into `new`, set what we need to set in `new`, making it become `overlay`. Then run applyObject(current, overlay).

**Review by morvencao — COMMENTED** [review]
The 2-way merge will keep values for all fields in current object, unless any field is override in overlay object, right?

**Comment by sdake** [comment]
There is this server-side apply issue that is being tracked for master. Is this PR specific to release-1.7 branch as server side apply does not work correctly on older versions of K8s in the support window for 1.7?

Cheers,
-steve

**Comment by houshengbo** [comment]
For 2-way merging, we have original, which is available in the annotation `kubectl.kubernetes.io/last-applied-configuration`, current, which is what in the cluster, and the overlay, which is what we expect. 

We do a comparison between original and overlay, to generate a PATCH, and use this PATCH to merge the current. Then update current with the cluster.

Fields, like clusterip, ports, which are filled in by the cluster automatically, the PATCH actually bypass them, because neither original or overlay sets any of them. After PATCH is merged into current, we still keep these fields the generated values.

**Pull request closed without merging**
