### PR TITLE
move MCP settings to meshConfig

### PR DESCRIPTION
**Pull request by rshriram**
pilot's --mcp-server-addr flag was deprecated several months ago in favor of specifying
a list of MCP server addresses in the config map (allows adding/removing mcp servers dynamically).
This PR fixes the helm templates to add MCP info into config map instead of using the deprecated
CLI option in pilot.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by ymesika** [comment]
/lgtm

cc @wenchenglu

**Comment by irisdingbj** [comment]
@rshriram you can pull changes in https://github.com/istio/istio/pull/11805 to get the circleci passed.

**Comment by ymesika** [comment]
@irisdingbj All required tests are passing on this one.
The CLA isn't because @hzxuzhonghu pushed to @rshriram's branch and the bot doesn't like it.

**Pull request merged**
