### PR TITLE
Always add prometheus annotations to istiod.

### LINKED ISSUE #33280: Istiod does not have prometheus scraping annotations when metrics merging is disabled
**Bug description**
Currently, the metrics merging configuration (`meshConfig.enablePrometheusMerge`) controls whether the Prometheus scraping annotations are placed on istiod pods. This makes it impossible to monitor istiod with Prometheus when metrics merging is disabled.

[Metrics merging](https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging) controls whether application metrics should be merged with istio's metrics. Metrics merging is a data plane concern and should not affect the prometheus-related annotations on control plane pods.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Prometheus annotations can be added to the istio control plane Pods regardless of whether metrics merging is enabled or disabled.

**Steps to reproduce the bug**
1. Install istio with `meshConfig.enablePrometheusMerge` set to `false`
2. See missing prometheus annotations on control plane Pods (e.g. istiod)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.5

### PR DESCRIPTION
**Pull request by bianpengyuan**
fix https://github.com/istio/istio/issues/33280

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
I could be wrong but I think the motivation was that if they didn't have metrics merging then they probably had a job for pilot specifically. So we may end up double scraping?

**Comment by alexbrand** [comment]
Should this cover other components, such as ingress gateway, egress gateway, etc?

**Comment by bianpengyuan** [comment]
> I could be wrong but I think the motivation was that if they didn't have metrics merging then they probably had a job for pilot specifically. So we may end up double scraping?

Good point, @Stono might be affected by this. Do you have any input?

**Comment by alexbrand** [comment]
It seems like this could be configurable if we want to maintain that behavior, but it should be configurable with another helm value.

**Comment by bianpengyuan** [comment]
@alexbrand Are you able to add those annotations via istioctl k8s overlay during installation?

**Comment by alexbrand** [comment]
Good call! Yes, we can. Thanks!

**Comment by bianpengyuan** [comment]
Close due to the potential side effect + a workaround exists.

**Pull request closed without merging**
