### PR TITLE
reenable cacert rotation test

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

fix: #47829

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by howardjohn — CHANGES_REQUESTED** [review]
This test is still taking >5min which is unacceptably long for a single test

**Comment by zirain** [comment]
> This test is still taking >5min which is unacceptably long for a single test

```console
ok  	istio.io/istio/tests/integration/security/cacert_rotation	38.696s
```

it's better now.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
