### PR TITLE
add newrelic gRPC adapter

### PR DESCRIPTION
**Pull request by wentao-zh**
Add a gRPC mode mixer adapter for New Relic backend.

### CODE REVIEW

**Comment by linsun** [comment]
cc @geeknoid for input.  Do we have guidance published for mixer adapter developer on what adapters should istio repo accept with the new gRPC adapter model?

**Comment by geeknoid** [comment]
@linsun 

We haven't established specific rules about what should and should not be in the Istio repo. 

We have a good idea of what should be built in to the Mixer binary. We'll only include the simple adapters like list checker in the binary. All adapters for independent backends will eventually be packaged as external gRPC adapters.

Once we have gRPC adapters, there is very narrow coupling between the adapters and the rest of the Istio project; they can be developed completely independently in separate repos. So where we put the code is no longer a technical issue, it's more about perception/responsibility kind of thing. My inclination is to put all gRPC-based adapters in the contrib repo and allow non-Istio folks to add their own adapters there as well. Each adapter would carry its own license within the repo. Since gRPC adapters can be written in any language, we wouldn't be able to have a standard build process for all these adapters, so we'd need to settle on sharing containers I suppose.

Then there's the issue of which adapters are included in the standard Istio installation files. I don't know how we decide that.

There's how we advertise adapters & templates on istio.io. Do we make a difference between adapters written by the Istio team vs. others?

And finally there's the issue of certification. I really don't know what that means in this context. Given the backends are all different, I'm not clear what we could certify in a systematic way.

The point here is that there is a lot of stuff to figure out to get and end-to-end story worked out.

**Comment by linsun** [comment]
Agreed, lots of stuff to figure out. Thank you for opening https://github.com/istio/istio/issues/8620.

@geeknoid - I like the idea of having it in istio/contrib repo for gRPC adapters.   It would be great if the istio team can give out guidance on how each adapter in the contrib repo should be built and tested as part of the process of contributing an adapter to the contrib repo.

**Comment by mandarjog** [comment]
@linsun my consistent advise to all new adapter authors is, We don’t want any new adapters in the istio repo. New tenmplates are ok, since it is not new code. I do not like the idea of contrib for vendor adapters either, who is going to code review those PRs, what about it rot there, What about CI?

We can already include documentation about these adapters at istio.io.
Grpc adapters enable decoupling and it is best that authors host their own repos.

Even the adapters that are already checked in will move out in due course of time.

There are a few things that need to be clarified, for example some adapters that istio considers part of the core like Prometheus will remain in an istio repo.

Certification process is TBD.

**Comment by mandarjog** [comment]
It was decided in the last TOC meeting that vendor adapters should be held externally in vendor repositories. You may use the existing mechanism to include your documentation at isio.io.

Closing this PR.

**Comment by linsun** [comment]
@mandarjog thanks!  Could you link the existing mechanism here if it exists?  I don't see it in @geeknoid 's proposal either:  https://docs.google.com/document/d/1V5NQ2juGnBS7dNACU6M5VUGSqkItf23P3m8KVBvGnBs/edit

I was under the impression it is not avail yet.

**Comment by mandarjog** [comment]
At present you have to open a PR against the istio.io repo and update this line. 
https://github.com/istio/istio.io/blob/master/scripts/grab_reference_docs.sh#L19 

mtail is working on a better version for import.

**Pull request closed without merging**
