### PR TITLE
Revert "Update Grafana to 4.6.3"

### PR DESCRIPTION
**Pull request by jeffmendoza**
Revert #2320

This reverts commit 2d894071482faaf40e0043d1bf1f0844d6668b99.
The new version has some sort of default smoothing that creates
terrible graphs compared to the old version. Not sure what causes
this, reverting until I can get the new version to look as good as the
old one.

### CODE REVIEW

**Comment by douglas-reid** [comment]
@jeffmendoza this seems fine to me.  should we open an issue to track the debugging of the display issues ?

/lgtm

**Comment by jeffmendoza** [comment]
@douglas-reid Opened #2676 to track.

**Comment by jeffmendoza** [comment]
@douglas-reid Looks like all the tests finally passed after the last rebase, can I get an lgtm? Thanks.

**Pull request merged**
