### PR TITLE
Fix analyze file resource not working when same resource exists in cluster

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/44844

### CODE REVIEW

**Comment by hanxiaop** [comment]
This is also consistent with what the analyze was done before 1.13, the file resource was being analyzed when the same resource existed in the cluster.

**Comment by hanxiaop** [comment]
This breaks `istioctl install` when doing the re-install when previous control plane was installed, with the following message:

```
This will install the Istio 1.19.0 "ambient" profile (with components: Istio core, Istiod, CNI, and Ztunnel) into the cluster. Proceed? (y/N) y
Error: failed to install manifests: errors occurred during operation: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector ) Webhook overlaps with others: [istio-revision-tag-default/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector ) Webhook overlaps with others: [istio-revision-tag-default/object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector ) Webhook overlaps with others: [istio-revision-tag-default/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector ) Webhook overlaps with others: [istio-revision-tag-default/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
```

This feature was introduced in https://github.com/istio/istio/pull/33644 to analyze webhooks before installation. However, I don't think it's performing the correct webhook analysis, as the MutatingWebhookConfiguration being analyzed will be revised (deactivated) after the installation.

Before this change, it actually didn't function properly because only in-cluster configurations were covered, which meant the webhook configuration analysis was always valid.

Additionally, throughout all installation methods (istioctl, helm, operator), the webhook was handled differently. My suggestion is to temporarily disable this webhook analysis since it's not working as expected at all, and then rework it to correctly handle the conflicting MutatingWebhookConfiguration. @howardjohn, do you have any thoughts on this?

**Comment by howardjohn** [comment]
I don't think it *never* worked properly - there are webhooks that may be completely user made that would not be de-activated. But agreed this check is not properly functioning in many cases now, unfortunately...

**Comment by hanxiaop** [comment]
> I don't think it _never_ worked properly - there are webhooks that may be completely user made that would not be de-activated. But agreed this check is not properly functioning in many cases now, unfortunately...

I'm going to try to refactor the check first before moving this PR forward, as this PR should not break anything.

**Pull request closed without merging**
