### PR TITLE
Fixing race test failure in TestAdsEds

### PR DESCRIPTION
**Pull request by xiaolanz**
introduced by https://github.com/istio/istio/pull/4694
addresses #4235

### CODE REVIEW

**Comment by baodongli** [comment]
Thanks for fixing the race issue. 
Unfortunately, I failed to see how the original code would introduce a race condition, since the variables are local and objects created in the same function. Can anyone explain?

I also think that the fix is tricky and the code becomes hard to understand. It's also error-prone for future changes. For example, If we'd introduce a new field such as the length of the Addresses: NumOfAddresses, then in the returned services, this field in the returned objects would have been completely wrong since it will be always zero. The following code snippet added one line in the function after the fix in this PR, to explain the above point:

```
func (c *Controller) Services() ([]*model.Service, error) {
	smap := make(map[string]model.Service)
	services := make([]*model.Service, 0)
	var errs error
	for _, r := range c.registries {
		svcs, err := r.Services()
		if err != nil {
			errs = multierror.Append(errs, err)
			continue
		}
		for _, s := range svcs {
			sp, ok := smap[s.Hostname]
			if !ok {
				sp = *s
				smap[s.Hostname] = sp
				services = append(services, &sp)
			}

			if r.ClusterID != "" {
				if sp.Addresses == nil {
					sp.Addresses = make(map[string]string)
				}
				sp.Addresses[r.ClusterID] = s.Address
                                sp.NumOfAddresses = len(sp.Addresses) // this is just to explain the point in the comments.
				smap[s.Hostname] = sp
			}
		}
	}
	return services, errs
}
```

**Comment by xiaolanz** [comment]
The problem with original code is that smaps gets a pointer to a model.service and it's being modified concurrently when multiple Services() is being called.

The fix is for smap to hold a copy of model.service and the modification of the object (adding clusterID/address mapping) stays local.

The real design issue is that Services() suppose to be an immutable operation to service objects. But the previous PR make it having side effects. The side effect should be documented in comments, and causes racing condition.

**Comment by baodongli** [comment]
Thanks for your explanation. Just for my personal understanding, I Looked at the calling chain: BuildClusters() calls aggregate.Services(), followed by calls to kube.Services(). kube.Services() creates a list of *model.Service, which is created in kube.convertService(). In each of the call to kube.Services(), a new list of model.Service() instances will be created and returned. This is why I'm still puzzling at why multiple go routines, each of which calls BuildClusters(), would end up writing to the same model.Service() instance.

**Pull request merged**
