### PR TITLE
add nil check to authz builder

### PR DESCRIPTION
**Pull request by ramaraochavali**
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by lei-tang — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
when is it nil?

**Comment by howardjohn** [comment]
Should we be using the NewListenerBuilder that handles that though?

I don't mind this either but seems if we run into this case we. may be doing something wrong

**Comment by ramaraochavali** [comment]
> Should we be using the NewListenerBuilder that handles that though?

Yes we can. Some tests are still using &ListenerBuilder and we can certainly move to NewListenerBuilder.

One of the builders(auth) already handles this. So thought it is better to be consistent and handle these as well.

**Pull request merged**
