### PR TITLE
remove envoy filter from isitod-remote

### PR DESCRIPTION
**Pull request by irisdingbj**
suppose these envoy filters can only work  together with istiod.  Based on this, we can remove them from istiod-remote.

### CODE REVIEW

**Comment by linsun** [comment]
Hi @irisdingbj - I am a little confused why this should be removed.  envoy filter should be installed on the config cluster, similar like any other istio networking resources.

**Comment by linsun** [comment]
discussed with @irisdingbj offline - remove envoy filter could be an issue for external istiod unless we have a way to properly indicate CRD is enabled or not.  e.g. for external istiod, we want crd and envoy filters on config cluster.  for MC remote cluster, we don't want crd or envoy filters.

cc @nmittler @stevenctl

**Comment by irisdingbj** [comment]
> discussed with @irisdingbj offline - remove envoy filter could be an issue for external istiod unless we have a way to properly indicate CRD is enabled or not. e.g. for external istiod, we want crd and envoy filters on config cluster. for MC remote only cluster, we don't want crd or envoy filters.
> 
> cc @nmittler @stevenctl

@linsun  Thanks! https://github.com/istio/istio/pull/28346 -- adding a flag into base to let us disable/enable crds. Also when crds are disabled, we will not install these envoy filters.  So Let me close this PR.

**Pull request closed without merging**
