### PR TITLE
stop the presubmit failure of uncommitted autogen files

### PR DESCRIPTION
**Pull request by jmuk**
See #1689 for the details.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mandarjog** [comment]
@yutongz Like Jun says, since workspace is being shared across PRs, a previous PR may have created these files in the workspace that `bazel_to_go.py` picks up.
Perhaps clean gen files before running tests?

**Comment by yutongz** [comment]
/lgtm
Is there is a way to only clean bazel-genfiles instead of `bazel clean` cleans everything?

**Pull request merged**
