### PR TITLE
Add support for reset as a retryable policy

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by howardjohn** [comment]
Fixes https://github.com/istio/istio/issues/18515

**Comment by rshriram** [comment]
We shouldn’t be having this policy list in validation. It will get out of date with envoy and force people to use EnvoyFilter when pilot goes out of date.

**Comment by kyessenov** [comment]
Agree. It's a lot of work to keep in sync with xDS, and is rather unnecessary this is just a mirror.

**Comment by maksim-azhgirei** [comment]
Release Istio 1.4.2 doesn't includes istio#18537. Will it appear in the next release istio?

**Pull request merged**
