### PR TITLE
ep builder: check invidual proxy has hbone

### PR DESCRIPTION
**Pull request by stevenctl**
Right now we're doing tunnel for proxies that don't have this enabled, disallowing opt-out AFAICT.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by shashankram** [comment]
I confirmed this fixes the bug I observed in https://github.com/istio/istio/issues/41375#issuecomment-1353520581 when HBONE is disabled on the client sidecar. Thanks @stevenctl

**Comment by shashankram** [comment]
> I confirmed this fixes the bug I observed in [#41375 (comment)](https://github.com/istio/istio/issues/41375#issuecomment-1353520581) when HBONE is disabled on the client sidecar. Thanks @stevenctl

I tested this again with the latest branch, and it doesn't work as expected for the multi-network scenario. The endpoint still refers to the pod IP instead of the E/W Gw IP. Ignore my earlier update as it seems it might have run against outdated builds.

**Comment by shashankram** [comment]
> @shashankram in your case, do you have HBONE enabled for the envoy on the VM? I am not exactly sure how to double check on that on the vm, i think it would should have this metadata (perhaps as the metadata you copied to VM?): `node.Metadata.EnableHBONE`. in k8s pod, you can review the env variable of the pod.

Both with and without HBONE, I was not seeing the E/W Gw IP in the client config. This change does fix the the part where when HBONE is disabled, the client config does not attempt to tunnel traffic to upstream over HBONE.

**Pull request merged**
