### PR TITLE
Update min k8s version to 1.26

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
This will be needed once we transition to the new supported window for the next release.

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by ymesika** [comment]
Do we have documentation of this min requirement that needs to be updated as well?

**Comment by hanxiaop** [comment]
> Do we have documentation of this min requirement that needs to be updated as well?

We do have this listed in the release preparation doc. I just try to update it advancely, and RMs do not need to update it again.

**Review by jacob-delgado — COMMENTED** [review]
https://istio.io/latest/docs/releases/supported-releases/ still shows master supporting 1.25

This should be updated as well

**Comment by hanxiaop** [comment]
> https://istio.io/latest/docs/releases/supported-releases/ still shows master supporting 1.25
> 
> This should be updated as well.
> 
> We officially support supported versions of K8s at release date. See https://endoflife.date/kubernetes

Thanks for the info. I would like this to be merged after https://istio.io/latest/docs/releases/supported-releases/ is updated, which should be close to the release date. In the past, it wasn't updated on time, and I did cherry-pick several times. I'll just add a DNM label for now.

**Review by irisdingbj — APPROVED** [review]

**Review by GregHanson — APPROVED** [review]

**Comment by hanxiaop** [comment]
This can be merged once https://github.com/istio/istio.io/pull/14486 is declared.

**Pull request merged**
