### PR TITLE
Introduce pkg/version and use it throughout the system.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by kyessenov** [comment]
Maybe provision something in version package to allow independent
versioning of components? We'll probably need to release things
independently in a few months.

**Comment by kyessenov** [comment]
/lgtm

I think independent versioning can be solved with more bash ni gobuild.

**Comment by mattdelco** [comment]
If the pkg/version is used through them some corresponding cleanup can be done in bin/get_workspace_status (e.g., delete the mixer/broker section [except for moving the buildStatus line into the pilot/istioctl/security section], and then remove the label on the pilot/istioctl/security section.

**Comment by ldemailly** [comment]
this appears to have created #2869

**Pull request merged**
