### PR TITLE
Update API sha

### PR DESCRIPTION
**Pull request by hklai**

### CODE REVIEW

**Comment by duderino** [comment]
istio-integ-k8s-test usually fails:  https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/istio-integ-k8s-tests

istio-pilot-multicluster-e2e almost always fails:  https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/istio-pilot-multicluster-e2e

but e2e-pilot-noauth-v1alpha3-v2 looks real:

From https://circleci.com/gh/istio/istio/324437?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link :

```
TestIngressGateway503DuringRuleChange - pilot
Failed
gateway "istio-ingressgateway" created
destinationrule "destination-rule-c" created
virtualservice "gateway-bound-route" created
destinationrule "destination-rule-c" configured
virtualservice "gateway-bound-route" configured
destinationrule "destination-rule-c" configured
virtualservice "gateway-bound-route" deleted
destinationrule "destination-rule-c" deleted
gateway "istio-ingressgateway" deleted
ingressgateway_test.go:258: Got non 200 status code while changing rules: map[503:1 200:499]
```

**Comment by gargnupur** [comment]
@duderino : looks like e2e-pilot-noauth-v1alpha3-v2 passed with retest... 
rerunning e2e-simple as that looks like infrastructure error

**Comment by duderino** [comment]
@costinm thought the e2e-pilot-noauth-v1alpha3-v2 failure is not due to this PR

The e2e-dashboard failure also looks like an infrastructure problem

```
Sending build context to Docker daemon   43.5MB


Step 1/5 : FROM ubuntu:16.04
Get https://registry-1.docker.io/v2/: EOF

real	0m0.459s
user	0m0.036s
sys	0m0.060s
make: *** [docker.node-agent-k8s] Error 1
Exited with code 2
```

**Comment by duderino** [comment]
@mandarjog is worried that the e2e-simple failure indicates galley isn't getting the resources its requesting.   @gargnupur will retest it and if it fails again ssh in to investigate before the workspace is destroyed.

```
2019-02-12T23:02:46.185393Z	info	Running command kubectl -n istio-system get deployment -o name --kubeconfig=
2019-02-12T23:02:46.355417Z	info	Command output: 
deployments/istio-citadel
deployments/istio-egressgateway
deployments/istio-galley
deployments/istio-ingressgateway
deployments/istio-pilot
deployments/istio-policy
deployments/istio-sidecar-injector
deployments/istio-telemetry
deployments/prometheus
2019-02-12T23:02:46.355569Z	info	Running command kubectl -n istio-system rollout status deployments/prometheus --kubeconfig=
2019-02-12T23:02:46.355648Z	info	Running command kubectl -n istio-system rollout status deployments/istio-ingressgateway --kubeconfig=
2019-02-12T23:02:46.355818Z	info	Running command kubectl -n istio-system rollout status deployments/istio-citadel --kubeconfig=
2019-02-12T23:02:46.356143Z	info	Running command kubectl -n istio-system rollout status deployments/istio-pilot --kubeconfig=
2019-02-12T23:02:46.356324Z	info	Running command kubectl -n istio-system rollout status deployments/istio-policy --kubeconfig=
2019-02-12T23:02:46.356468Z	info	Running command kubectl -n istio-system rollout status deployments/istio-telemetry --kubeconfig=
2019-02-12T23:02:46.356647Z	info	Running command kubectl -n istio-system rollout status deployments/istio-egressgateway --kubeconfig=
2019-02-12T23:02:46.356791Z	info	Running command kubectl -n istio-system rollout status deployments/istio-galley --kubeconfig=
make: *** [test/local/auth/e2e_simple] Terminated
Too long with no output (exceeded 10m0s)
```

**Pull request merged**
