### PR TITLE
Cleaned up edge service

### PR DESCRIPTION
**Pull request by jkohen**
Proposing changes suggested in external review:
- Remove `_name` suffix from fields that have it.
- Remove unused (and not well defined) field `api_protocol`.
- Some extra documentation.

### CODE REVIEW

**Comment by geeknoid** [comment]
Note that for this and related changes, we will need a migration story to ensure that 1.0 and 1.1 deployments of Istio don't get borked when upgrading to 1.2.

We don't have versioning on templates at the moment. Either we'll need to do this for 1.2 and mark your updates as being new versions, and still support the old. Or we'll need some mechanism to migrate user config forward.

**Comment by jkohen** [comment]
What do you suggest? 1.2 sounds fine if we can count on on-the-wire
compatibility.

The other changes are just documentation. Do we need a migration story for
that?

**Comment by geeknoid** [comment]
Doc changes don't need migration, that's fine.

If the actual config format changes, we need to make sure customer's setups continue to work as they upgrade to a new version of Istio. This particular change you're making will be part of 1.2 (as 1.1 is just about done). So before 1.2 comes out officially, we need to have a strategy in place. I think it's fine to file a bug stating that "Implement approach to migrate customers to new config format" or whatever, so long as we keep track.

What we likely need to do is in 1.2 is:

- Introduce support for multiple concurrent versions of a given template or config.

- Support both formats in the code.

- Provide a migration tool that converts a deployed config from the old format to the new format.

- Publish a warning indicating the old format will be deprecated.

- In 1.3, we remove support for the old format,

**Comment by jkohen** [comment]
As discussed with Doug, I'm going to drop this change in favor of a Stackdriver-specific template.

**Pull request closed without merging**
