### PR TITLE
Default proxyv2 image

### PR DESCRIPTION
**Pull request by GregHanson**
remove references to `proxy` image

looking for feedback on the Dockerfile.proxy_debug file.  The dockerfile has some difference between proxy and proxyv2 dockerfile

### CODE REVIEW

**Comment by GregHanson** [comment]
@costinm do you know why there are subtle difference between the proxy_debug and proxyv2 dockerfiles?
https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxy_debug#L16
and
https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxyv2#L16

**Comment by ZackButcher** [comment]
Ug, the merge beat me to it. Is there a reason we renamed to `proxyv2` rather than just updating the image of the `proxy` container to use the v2 APIs (i.e. kill the `proxyv2` image and just make it `proxy`)? That should not break any other users of the proxy image since all Istio YAMLs pin the image to a specific tag.

**Comment by hklai** [comment]
@GregHanson 
This have broken all prow tests apparently...
https://prow.istio.io/?repo=istio%2Fistio&type=postsubmit

https://storage.googleapis.com/istio-prow/e2e-dashboard/298/build-log.txt

Could you take a look?

**Comment by hklai** [comment]
Sorry it think it might be noise.
The error was W0626 22:18:14.568] package istio.io/test-infra/boskos/cmd/mason_client: unrecognized import path "istio.io/test-infra/boskos/cmd/mason_client" (https fetch: Get https://istio.io/test-infra/boskos/cmd/mason_client?go-get=1: EOF)

which may be a timing issue with https://github.com/istio/istio.github.io/pull/1594

Will monitor for subsequent post submit runs.

**Pull request merged**
