### PR TITLE
Correct spelling mistakes

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

Improve document quality.

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
@jasonwzm Thanks.

**Comment by yuxiaobo96** [comment]
@geeknoid 
If you have time, please check it out for me.

**Review by howardjohn — APPROVED** [review]

**Review by esnible — APPROVED** [review]
(For istioctl/* test only.  I did not review the other files.)

**Review by geeknoid — APPROVED** [review]

**Comment by yuxiaobo96** [comment]
Thank you all.
Does this pr still need review by others?

**Review by incfly — APPROVED** [review]
Waiting on code owner review from istio/wg-policies-and-telemetry-maintainers and/or istio/wg-security-maintainers

you need polici and telemetry maintainers

**Review by bianpengyuan — APPROVED** [review]

**Comment by yuxiaobo96** [comment]
Thanks.

**Pull request merged**
