### PR TITLE
Update the gen_istio_image_list script to reflect updates

### PR DESCRIPTION
**Pull request by johnma14**
Made changes to the script file so that it reflects the changes to the DOCKER_TARGETS
target from `DOCKER_TARGETS:=` to `DOCKER_TARGETS ?= ` in 1.5.

Fixes: #21356

### CODE REVIEW

**Comment by linsun** [comment]
@johnma14 Thanks for the PR!  is this still using the old install/k8s/helm dir or the new operator dir?

@kramvan1 can you give a quick test of the PR?

**Comment by johnma14** [comment]
@linsun this script uses the helm charts to get the list of images. I am working on this issue to do this from operator: #18789

**Comment by kramvan1** [comment]
@linsun @johnma14   using the latest master I get this:
```
$ ./tools/gen_istio_image_list.sh -v 1.5.0-beta.5
docker.io/istio/pilot:1.5.0-beta.5
docker.io/istio/proxytproxy:1.5.0-beta.5
docker.io/istio/proxyv2:1.5.0-beta.5
docker.io/istio/app:1.5.0-beta.5
docker.io/istio/app_sidecar:1.5.0-beta.5
docker.io/istio/test_policybackend:1.5.0-beta.5
docker.io/istio/mixer:1.5.0-beta.5
docker.io/istio/mixer_codegen:1.5.0-beta.5
docker.io/istio/citadel:1.5.0-beta.5
docker.io/istio/galley:1.5.0-beta.5
docker.io/istio/sidecar_injector:1.5.0-beta.5
docker.io/istio/kubectl:1.5.0-beta.5
docker.io/istio/node-agent-k8s:1.5.0-beta.5
docker.io/istio/istioctl:1.5.0-beta.5
docker.io/istio/operator:1.5.0-beta.5
```
istiod is missing from the 1.5.0list along with the addons which I believe is covered under that other issue.

**Comment by howardjohn** [comment]
There is no istiod image, its pilot

**Comment by kramvan1** [comment]
@howardjohn yup, my mistake.

**Pull request merged**
