### PR TITLE
Fix destination rule issue when no sidecar resources are defined.

### PR DESCRIPTION
**Pull request by yangminzhu**
This is a workaround to solve the problem without changing the
semantic of how does Pilot pick up the destination rule in legacy
mode.

Workaround for https://github.com/istio/istio/issues/12000, a more proper fix might be needed when the default Sidecar resource is generated in Pilot.

### CODE REVIEW

**Comment by howardjohn** [comment]
If I am understanding this right, right now we search through all of the destination rules and pick the first match. istio-system's default one happens to come before the default namespace productpage one we actually want, so this just moves istio-system's to the end. But what happens when we have another namespace? Won't that one override the default namespaces productpage destination rule as well?

**Comment by yangminzhu** [comment]
@howardjohn Yes, the one from other namespace might still override the one in default. I think this had long been a problem in the old model where a dest rule taking effect beyond the namespace boundary. But the dest rule in other namespace (other than istio-system) is likely to be created by the customer and the customer should be aware of this override logic when they're creating it in the first place.

**Comment by howardjohn** [comment]
> @howardjohn Yes, the one from other namespace might still override the one in default. I think this had long been a problem in the old model where a dest rule taking effect beyond the namespace boundary. But the dest rule in other namespace (other than istio-system) is likely to be created by the customer and the customer should be aware of this override logic when they're creating it in the first place.

Ok I think that makes sense. So if we have two dest rules, both for host `*.local` either one can be chosen arbitrarily, and that is expected behavior.

Right now we iterate over all the namespaces and try to match. Instead of putting istio-system at the end of the namespaces list, would it be better to just flatten this, so it is not namespace scoped? We can sort it again (probably want to precompute it, just like all of the other `namespaceLocalDestRules`, etc) which gives us the Hostname ordering so wildcards like `*.local` appear last.

I tested this and it seems to work. I this would also fix the issue of having:

* Namespace a with destination rule `*.local`
* Namespace b with destination rule `something.local`

and namespace A's destination rule being arbitrarily picked for `something.local`, since the sorted list will match namespace b first, as expected. 

Another reason I like this is that it doesn't depend on "istio-system" being the namespace for Istio, which I don't think is guaranteed.

**Comment by howardjohn** [comment]
Actually, it could be a lot simpler. `allExportedDestRules` already is the flattened version. I think we can just skip the first check and use the check that uses allExportedDestRules as the default

**Comment by yangminzhu** [comment]
@howardjohn If we could remove that logic completely, that would be much better! I don't know why Pilot doesn't do this before, as long as the change doesn't break anything existing, we should go for it.

**Comment by yangminzhu** [comment]
Closing this one in favor of @howardjohn's PR.

**Pull request closed without merging**
