### PR TITLE
make use of unbounded channel to store xds response, in case forward …

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
…to envoy is slower than pilot sender

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
can you take a look @howardjohn

**Review by howardjohn — CHANGES_REQUESTED** [review]
So the origin of unbounded was https://github.com/istio/istio/pull/39310. In this case, we had a well established, reproducible deadlock issue.

In that PR, we actually moved responsesChan from 10 capacity to 1. This PR is doing basically the opposite, and moving it to infinite.

If you read the commentary on L306 and original issue, it seems we only need one part of the chain to be unbounded. Keeping the other bounded provides us with important backpressure to avoid infinite backup.

Based on this past analysis, at first glance this change seems to make the system less reliable. However, there is no commentary provided in the PR about *why* the change is needed, so maybe I am missing context. Is there additional information about why this is desirable?

**Comment by hzxuzhonghu** [comment]
This is based on the envoy is slow processing the xds response  reported from https://github.com/istio/istio/issues/48517, see my analysis https://github.com/istio/istio/issues/48517#issuecomment-1869858439

We simply make istiod not affected by one particular client pressure, leaves the backpressure all to client side. In other words this is to make the system control plane more reliable, rather than less

**Comment by howardjohn** [comment]
What data do we have to suggest this is an improvement?

For example, if we used envoy directly without xds proxy it would behave like the proxy without this PR.

It's not clear why we should remove back pressure which can lead to unbounded memory usage and OOM

**Comment by hzxuzhonghu** [comment]
>What data do we have to suggest this is an improvement?

istiod can never block sending, and bo goroutine leak.

I can understand your theory is based on that `you prefer blocking from the source rather than client message accumulation`.  My view is based on that source here istiod is a shared component, while the client is per workload, a slow client should not consume server resources.

**Comment by howardjohn** [comment]
> > What data do we have to suggest this is an improvement?
> 
> istiod can never block sending, and bo goroutine leak.
> 
> I can understand your theory is based on that `you prefer blocking from the source rather than client message accumulation`. My view is based on that source here istiod is a shared component, while the client is per workload, a slow client should not consume server resources.

I don't think it's a good practice to entirely remove back pressure. Under high load, istiod can push repeatedly and accumulate GBs of unprocessed data which will trigger OOM. Clients must protect themselves.

I agree the server side is not ideal, but we should discuss proposals on how to better handle that IMO - I've thought about it before and don't have any great ideas, but I am sure there are some improvements we could make.

**Comment by hzxuzhonghu** [comment]
Isn't what we do here just like istio dataplane for workload's requests? We can apply ratelimit for traffic between C/S, or set buffer limit for them. And even set timeout, actually these three ways are all open to users.

Here we are merely normal users, we face the same situation as users of istio.

**Comment by howardjohn** [comment]
Envoy sidecar proxy is not indefinitely buffering up requests without sending them (I don't think ever, but certainly not in Istio's configuration).

**Comment by hzxuzhonghu** [comment]
This is a good reason, make sense

**Pull request closed without merging**
