### PR TITLE
Add a integration test for tracing header in mixer report

### PR DESCRIPTION
**Pull request by bianpengyuan**
#13391

test should pass once https://github.com/istio/proxy/pull/2182 ready in main repo.

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@kyessenov Would you mind to unhold this PR? Thanks!

**Comment by kyessenov** [comment]
Can you cherry-pick this PR and the proxy one  to master branches as well?
I think there is no more batch fast-forward offered.

**Comment by bianpengyuan** [comment]
@kyessenov sounds good. will do.

@duderino Could you please merge this PR? It picks the fix in proxy that is recently merged: istio/proxy#2182

**Comment by bianpengyuan** [comment]
The fix is in 1.2. It might not worth it to release 1.1.8 for this bug, so closing this pr.

**Pull request closed without merging**
