### PR TITLE
Update e2e test to be less flaky

### PR DESCRIPTION
**Pull request by sebastienvas**
```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
which linter complains about string([]bytes) I'm curious ? (also i don't see those)

**Comment by sebastienvas** [comment]
@ldemailly I just ran go get -u on gometalinter and megacheck

**Comment by ldemailly** [comment]
it's odd because I don't see those lints even after -u (/running mixer's bin/install_linter.sh)
what are your exact command line/steps?

**Comment by sebastienvas** [comment]
@ldemailly go get -u github.com/alecthomas/gometalinter && go get -u honnef.co/go/tools/cmd/megacheck

**Comment by ldemailly** [comment]
somehow got it to work after doing install -f -u

**Comment by douglas-reid** [comment]
so, we've increased our backoffs... but can we figure out what exactly is happening?

**Comment by sebastienvas** [comment]
There might be an underlying performance issue (Istio feature or k8s 1.7). I hate those blind retries, and sleep. I think the right way to do that would have to query istio and check if a rule has been applied or not and check under  30 s timeout or something that make sense.

**Comment by ldemailly** [comment]
it should only take seconds for a pod to come up - we should find out why it takes more so often

**Pull request merged**
