### PR TITLE
Fix typo 'proxywhen'

### PR DESCRIPTION
**Pull request by JinVei**
**Please provide a description of this PR:**
Fix typo 'proxywhen'

Related: https://github.com/istio/istio.io/pull/14089

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Review by ericvn — COMMENTED** [review]
LGTM. It may take a bit to flow through to the docs now that we've hit code freeze for 1.20.

**Review by GregHanson — APPROVED** [review]

**Pull request merged**
