### PR TITLE
Purge bazel files from the mixer tree.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by geeknoid** [comment]
Another /lgtm please? I had to rebase...

**Comment by ldemailly** [comment]
> Another /lgtm please? I had to rebase...

Already did/it's there and going (https://github.com/istio/istio/pull/2589#issuecomment-357412848 and https://github.com/istio/istio/pull/2589#issuecomment-357412874)

**Comment by ldemailly** [comment]
looks like
```
I0113 06:42:03.382] --- FAIL: TestNodeAgentTest (514.36s)
I0113 06:42:03.382] 	node_agent_test.go:150: failed to check certificate update and validate after 10 retry
I0113 06:42:03.383] FAIL
```
is back, I think that got fixed somehow as part of what was since reverted... the plot thickens...

**Comment by kyessenov** [comment]
my revert only touched proxy SHA update, nothing to do with node agent.
another flake?

**Comment by rshriram** [comment]
btw guys.. the bot does not trigger circleci tests. Please use the UI to rebuild circleci tests. Or rerun the entire workflow. https://github.com/istio/istio/wiki/Working-with-CircleCI

**Comment by rshriram** [comment]
can you nuke other bazel files as well?

**Comment by ldemailly** [comment]
/lgtm

that test seems to fail a lot (saw it on multiple PRs:)

I0117 20:37:17.384] FAIL	istio.io/istio/mixer/test/client/quota_cache	1.145s

**Comment by ldemailly** [comment]
you don't need to rebase for prow to test against master

/lgtm

**Pull request merged**
