### PR TITLE
Add rbac.istio.io permissions back to ClusterRoles

### LINKED ISSUE #29364: Cannot restart 1.6 Istio revision after installing 1.7 revision
**Bug description**

After installing revision of Istio 1.7.5 I cannot restart Istio 1.6.13 revision, because `discovery` container ends up in non ready state. It produces lots of log about syncing CRDs removed in 1.7.5:
```
2020-12-03T10:11:48.889099Z    error    k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *crd.IstioRbacV1Alpha1Servicerolebindings: servicerolebindings.rbac.istio.io is forbidden: User "system:serviceaccount:istio-system:istiod-service-account" cannot list resource "servicerolebindings" in API group "rbac.istio.io" at the cluster scope
2020-12-03T10:11:48.975299Z    info    controller "rbac.istio.io/v1alpha1/ServiceRoleBinding" is syncing...
2020-12-03T10:11:48.987164Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:48.987203Z    info    controller "rbac.istio.io/v1alpha1/ClusterRbacConfig" is syncing...
2020-12-03T10:11:49.075297Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:49.087164Z    info    controller "rbac.istio.io/v1alpha1/RbacConfig" is syncing...
2020-12-03T10:11:49.087200Z    info    controller "rbac.istio.io/v1alpha1/ServiceRoleBinding" is syncing...
2020-12-03T10:11:49.175292Z    info    controller "rbac.istio.io/v1alpha1/ClusterRbacConfig" is syncing...
2020-12-03T10:11:49.187163Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:49.187186Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:49.275297Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:49.287154Z    info    controller "rbac.istio.io/v1alpha1/ClusterRbacConfig" is syncing...
2020-12-03T10:11:49.287186Z    info    controller "rbac.istio.io/v1alpha1/ServiceRoleBinding" is syncing...
2020-12-03T10:11:49.375283Z    info    controller "rbac.istio.io/v1alpha1/ServiceRoleBinding" is syncing...
2020-12-03T10:11:49.387154Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:49.387172Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
2020-12-03T10:11:49.475296Z    info    controller "rbac.istio.io/v1alpha1/ServiceRoleBinding" is syncing...
2020-12-03T10:11:49.487169Z    info    controller "rbac.istio.io/v1alpha1/ServiceRole" is syncing...
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**

Old Istio revision works without problems.

**Steps to reproduce the bug**

1. Install revision of 1.6
2. Install revision of 1.7
3. Rollout restart 1.6 istiod
4. Observe logs and new pods status

**Version**

```bash
❯ kubectl version --short
Client Version: v1.19.3
Server Version: v1.17.12
```

For 1.6:
```bash
❯ istioctl1.6 version --remote
client version: 1.6.13
istiod version: 1.6.13
istiod version: 1.6.13
istiod version: 1.6.13
istiod version: 1.6.13
istiod version: 1.6.13
istiod version: 1.6.13
istiod version: 1.7.5
istiod version: 1.7.5
istiod version: 1.7.5
pilot version: 1.5.7
pilot version: 1.5.7
pilot version: 1.5.7
data plane version: 1.7.5 (3 proxies), 1.6.13 (14 proxies)
```

For 1.7 `istioctl1.7 version --remote` is stuck and does not return anything, but it should say `1.7.5`, because I am using this version.

**How was Istio installed?**

Istio 1.6 was installed using canary upgrade from 1.5. Istio 1.7 was installed using canary upgrade from 1.6.

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS, k8s installed using Gardener, os is Garden Linux 184.0

### PR DESCRIPTION
**Pull request by Monkeyanator**
Fixes #29364.

The `rbac.istio.io` ClusterRole permission was removed at some point in 1.7 resulting in <=1.6 `istiod` to hang forever on restart when a newer revision is installed in the same cluster (because ClusterRole is shared across all installations we overwrite old permissions during installation of new version). This change just adds the permission back to keep restarts on old versions from hanging after installing newer revisions.

Long-term solution to this (that would let us drop permissions for deprecated CRDs in new versions) could be having multiple ClusterRole resources each scoped to their respective revisions (requires different service accounts for different `istiod`, I think).

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
cc @yangminzhu

**Review by howardjohn — COMMENTED** [review]
LGTM

our coupling between revisions is concerning here. I wonder if there are any other bugs... at the very least this means our RBAC list can only grow in the future - any shrinking will break old revisions

**Review by yangminzhu — COMMENTED** [review]
LGTM, should this be cherry-picked to 1.7 release?

**Comment by yangminzhu** [comment]
> LGTM
> 
> our coupling between revisions is concerning here. I wonder if there are any other bugs... at the very least this means our RBAC list can only grow in the future - any shrinking will break old revisions

It looks like the the service account and cluster role should also be revision based if the revision installation is used.

**Comment by Monkeyanator** [comment]
> LGTM, should this be cherry-picked to 1.7 release?

Should be cherry-picked to 1.7 and 1.8 releases. I'll make an issue for revisioning the service account and cluster role

**Comment by howardjohn** [comment]
My only concern with SA is it is part of the identity. Maybe it doesn't
matter since istiod isn't doing mTLS anyways though

**Comment by dgn** [comment]
> our coupling between revisions is concerning here. I wonder if there are any other bugs... at the very least this means our RBAC list can only grow in the future - any shrinking will break old revisions

^^ this is important. we should at least add a note in the ClusterRole so we don't have regressions everytime we remove a CRD.

It doesn't have to be quite as strict though.. afaik we only support single step releases, right? so next release we can remove the permissions?

**Comment by Monkeyanator** [comment]
> > our coupling between revisions is concerning here. I wonder if there are any other bugs... at the very least this means our RBAC list can only grow in the future - any shrinking will break old revisions
> 
> ^^ this is important. we should at least add a note in the ClusterRole so we don't have regressions everytime we remove a CRD.
> 
> It doesn't have to be quite as strict though.. afaik we only support single step releases, right? so next release we can remove the permissions?

Added a note to the `ClusterRole` warning about this. Will remove it along with the `rbac.istio.io` permission when permanent fix lands (i.e. revisioning `ClusterRole` and `ServiceAccount`, letting us remove CRD perms without regression)

**Comment by Monkeyanator** [comment]
> It doesn't have to be quite as strict though.. afaik we only support single step releases, right? so next release we can remove the permissions?

since we're shooting to support skip-level upgrades in the nebulous future, if we remove a CRD (without a better fix), I think we'd have to keep the permissions around for quite a few releases

**Comment by Monkeyanator** [comment]
Another option without changing ServiceAccount for istiod: just revision the `ClusterRole` and `ClusterRoleBinding`. These permissions are additive (two ClusterRoles bound to the istiod ServiceAccount gives union of permissions), so things would keep working on old control plane, and then when you removed the old revision (along with its ClusterRole and ClusterRoleBinding), the new `istiod` would have just the permissions it needs.

**Comment by Monkeyanator** [comment]
Bumping this for review

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
