### PR TITLE
Add empty regex validator

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix https://github.com/istio/istio/issues/34065

### CODE REVIEW

**Comment by kebe7jun** [comment]
Similar to https://github.com/istio/istio/pull/33786, should I use warnings instead?

**Review by howardjohn — APPROVED** [review]
I think this case of adding validation is ok because the previous configuration was 100% invalid and resulted in a broken cluster. It is in the case where a configuration is not recommended/ineffective or other non-critical issues where we should not add validation I think.

Thanks for the PR!

**Review by costinm — APPROVED** [review]

**Pull request merged**
