### PR TITLE
Fix request/response header validation

### PR DESCRIPTION
**Pull request by itaysk**
fix https://github.com/istio/istio/issues/10118

### CODE REVIEW

**Comment by ymesika** [comment]
Can you pleasse re-open it with `release-1.1` as the target branch?

**Comment by ymesika** [comment]
@itaysk Yeah, we usually get those kind of errors when just switching branch.
I usually close and open new one but it seems fine now except that `needs-rebase` label.

**Comment by itaysk** [comment]
not sure why it needs rebase, the prev commit is `cdeb2771969ce3baff9d60bfc0cd315282015f81` which is the tip of `release-1.1`. If you think it's better to open a new PR I don't mind

**Comment by itaysk** [comment]
closing this so I can open a new one for `release-1.1`

**Pull request closed without merging**
