### PR TITLE
[release-1.6]fix controller test and add back resource status check

### PR DESCRIPTION
**Pull request by richardwxn**
would try to get the 1.6 done first and then come back to the master one

now it is passing for consecutive runs

### CODE REVIEW

**Comment by jacob-delgado** [comment]
> [Testing]
> 
> would try to get the 1.6 done first and then come back to the master one

It makes it easier for the release managers if this is cherry-picked from master to release-1.6. For this to get my approval it would have to be reviewed and approved by a SME who is familiar with the operator code. Thoughts @brian-avery?

**Comment by richardwxn** [comment]
@jacob-delgado yep I am still testing it and once it is done I will ask environment wg folks to approve it here

**Comment by howardjohn** [comment]
Why on 1.6 first? We should develop on master and cherrypick to 1.6 unless there is a compelling reason to do otherwise - it does not seem to be the case here?

**Comment by richardwxn** [comment]
The master one is merged: https://github.com/istio/istio/pull/23099, and I just updated this PR to just cherry-pick the commit, can you help approve it? @jacob-delgado

**Comment by jacob-delgado** [comment]
> The master one is merged: #23099, and I just updated this PR to just cherry-pick the commit, can you help approve it? @jacob-delgado

It's an easier workflow to do what John was suggesting and work in master and have a comment saying `/cherry-pick release-1.6`. That way an automated PR will be put up once it merges into master if you aren't too familiar

**Comment by richardwxn** [comment]
@jacob-delgado yep I am pretty familiar with this process, previously I created this one first because master was flaky so the test I added would not be able to pass, that's why I wanted to make it in to 1.6 first and spend more time to debug the master one, but later issue of master is fixed

**Pull request merged**
