### PR TITLE
fix: remove .svc: in some services

### PR DESCRIPTION
**Pull request by eminaktas**
**Please provide a description of this PR:**

Changes the services ending with `<service-name>.<service-namespace>.svc:<port>` to `<service-name>.<service-namespace>:<port>`

#41396

Signed-off-by: eminaktas <eminaktas34@gmail.com>

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
I don't think this is a good idea. Istio relies on core Kubernetes components to work - DNS among them. You can do all sorts of things like denying pods with <X property>, changing DNS semantics, etc to break Istio - all the power to you if you want to do this. But if you do and want to use Istio, the burden should be on you to customize things, not changing things for all users.

This is almost certain to break something (even if we fix the find+replace that already missed some places and incorrectly updated others). There is a bunch of things like certificates, etc that already encode this information that makes this a breaking change.

**Comment by eminaktas** [comment]
> I don't think this is a good idea. Istio relies on core Kubernetes components to work - DNS among them. You can do all sorts of things like denying pods with , changing DNS semantics, etc to break Istio - all the power to you if you want to do this. But if you do and want to use Istio, the burden should be on you to customize things, not changing things for all users.
> 
> This is almost certain to break something (even if we fix the find+replace that already missed some places and incorrectly updated others). There is a bunch of things like certificates, etc that already encode this information that makes this a breaking change.

Thanks for the reply. I understand your thoughts. I was checking again the changes. It won't be easy to change it as you say.

I already fix the problem by changing the installation files for our environment however, this should be changed in Istio if possible.

https://github.com/istio/istio/issues/41396#issuecomment-1277357788

**Comment by eminaktas** [comment]
I'm closing this PR for now since I just only wanted to add some functionality to remove `svc` which is hardcoded in yamls.

**Pull request closed without merging**
