### PR TITLE
update go version for linters

### PR DESCRIPTION
**Pull request by jmuk**
updates #1779.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by jmuk** [comment]
`gcloud docker -- push` seems failing on my environment, maybe I don't have the authority of doing so? @kyessenov can you do that?

**Comment by kyessenov** [comment]
Just push to any other hub and update the docker run command.

**Comment by jmuk** [comment]
Done. PTAL.

**Comment by kyessenov** [comment]
Thanks for doing the work.
/lgtm
/approve

**Pull request merged**
