### PR TITLE
Repair cni resources

### PR DESCRIPTION
**Pull request by prary**
PR lets user to set cpu and memory for cni daemon pods.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[  ] Does not have any changes that may affect Istio users. 
* Yes

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
@prary Thanks for the PR.
But we recommend to set resources/affinity/annotation... with k8s settings, see: https://github.com/istio/istio/tree/master/operator#new-api-customization
We don't want to add helm parameters for each option in the values.yaml any more, it's hard to maintain so many options in the helm values.

**Comment by noah8713** [comment]
@morvencao  Using cni.k8s.resources with over-ride only adds for first container and doesn't work for other container. e,g only install-cni gets updated and repair-cni still uses default bigger resources. 

Seems this needs to be fixed in k8s to iterate to n number of containers in the daemonset spec and update same resources for all containers. However, this PR is also valid if different containers need different resources for over-ride till the other fix is in place

Also linking the issue https://github.com/istio/istio/issues/30570 
cc @howardjohn

**Comment by noah8713** [comment]
Double checked the k8s overlay code and its possible to leverage the same instead of this code change in istio. 

e.g. use below in operator spec to set custom resources for install/repair cni.
```
+              - path: spec.template.spec.containers[name:install-cni].resources.limits.cpu
+                value: "400m"
+              - path: spec.template.spec.containers[name:install-cni].resources.limits.memory
+                value: "1Gi"
+              - path: spec.template.spec.containers[name:install-cni].resources.requests.cpu
+                value: "100m"
+              - path: spec.template.spec.containers[name:install-cni].resources.requests.memory
+                value: "100Mi"
+              - path: spec.template.spec.containers[name:repair-cni].resources.limits.cpu
+                value: "400m"
+              - path: spec.template.spec.containers[name:repair-cni].resources.limits.memory
+                value: "1Gi"
+              - path: spec.template.spec.containers[name:repair-cni].resources.requests.cpu
+                value: "100m"
+              - path: spec.template.spec.containers[name:repair-cni].resources.requests.memory
```

Hence, +1 this PR can be skipped.

Closing issue https://github.com/istio/istio/issues/30570

**Comment by morvencao** [comment]
@noah8713 Yes, the k8s overlay can be used to customize the settings for `repair-cni` container.

**Comment by prary** [comment]
@morvencao @noah8713 , for security reason we are not using operators. Can we add above capability to helm?

**Pull request closed without merging**
