### PR TITLE
Fix local connection over port 22 error PR #10462

### PR DESCRIPTION
**Pull request by gekart**
Fixes Issue #10462 to use local connection without resorting to ssh-ing into localhost, as recommended in 

https://docs.ansible.com/ansible/2.6/user_guide/playbooks_delegation.html#local-playbooks

### CODE REVIEW

**Comment by gekart** [comment]
I signed it! "Thanks, your CLA has been submitted."

**Comment by gbaufake** [comment]
@gekart 
Can you cherry-pick this commit and submit a PR to istio-release-1.1 branch?
Regards,
Guilherme Baufaker Rêgo

**Comment by gbaufake** [comment]
assing @sdake

**Comment by gbaufake** [comment]
@gekart  can you rebase this PR?
Istio 1-1 branch is closed now.

**Comment by gbaufake** [comment]
/assign @sdake 
Can we merge this PR?

**Comment by sdake** [comment]
@gbaufake I don't have permissions to force merge.  IMO this PR should have merged long ago.  Once the gate is passing, the PR will merge automatically with current github labels.  Try rebasing.

**Comment by gbaufake** [comment]
@sdake 
can we merge this PR?

**Pull request closed without merging**
