### PR TITLE
Stop using deprecated filters naming/config

### PR DESCRIPTION
**Pull request by howardjohn**
For https://github.com/istio/istio/issues/21183

See
https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated#april-8-2020

This has an unfortunate impact on perfomance due to the extra overhead for proto marshalling, despite sharing the same filter object, since the marshalling still happens each time:
```
name                                 old time/op    new time/op    delta
ListenerGeneration/empty-6             5.02ms ± 1%    5.28ms ± 2%   +5.15%  (p=0.008 n=5+5)
ListenerGeneration/telemetry-6         5.93ms ± 2%    6.57ms ± 1%  +10.92%  (p=0.008 n=5+5)
ListenerGeneration/virtualservice-6    4.94ms ± 2%    5.24ms ± 2%   +6.05%  (p=0.008 n=5+5)

name                                 old alloc/op   new alloc/op   delta
ListenerGeneration/empty-6             2.35MB ± 0%    2.37MB ± 0%   +0.58%  (p=0.008 n=5+5)
ListenerGeneration/telemetry-6         2.75MB ± 0%    2.84MB ± 0%   +3.19%  (p=0.008 n=5+5)
ListenerGeneration/virtualservice-6    2.35MB ± 0%    2.37MB ± 0%   +0.58%  (p=0.008 n=5+5)

name                                 old allocs/op  new allocs/op  delta
ListenerGeneration/empty-6              27.8k ± 0%     27.6k ± 0%   -0.71%  (p=0.008 n=5+5)
ListenerGeneration/telemetry-6          32.8k ± 0%     33.8k ± 0%   +3.09%  (p=0.029 n=4+4)
ListenerGeneration/virtualservice-6     27.8k ± 0%     27.6k ± 0%   -0.71%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Comment by howardjohn** [comment]
thanks @kyessenov  for the help!

**Comment by ramaraochavali** [comment]
Does this change need a version guard? ? I read in Envoy issues, some folks have complained about old vs new names causing issues depending on the version (Sha) of Envoy used.

**Comment by howardjohn** [comment]
I don't think so? I didn't change the name even, just added the (empty) typed config

**Comment by ramaraochavali** [comment]
Ah. I thought based on PR description, the `wellknown.*` points to the new names.  if names are not changed, we are good.

**Comment by howardjohn** [comment]
It's not required yet but our current use is deprecated so it may be
required in the future. Basically it's shifting to identifying by name to
identifying by type

**Pull request merged**
