### PR TITLE
Remove protobuf dependency for config objects

### PR DESCRIPTION
**Pull request by howardjohn**
The problem we face is the current Config object requires the spec to be a (gogo) protobuf. This is problematic for a number of reasons:
* We may change our protos to golang protobuf
* Projects we want to import do not have any protos
* Incorrect abstraction

We don't actually *need* protobuf - what we need is a way to marshal, unmarshal, and deepcopy any type we want to reference in `Config`.

### CODE REVIEW

**Comment by kyessenov** [comment]
Are you trying to use k8s go structs instead for istio APIs? I think that would help avoid protobuf roundtrip.

**Comment by howardjohn** [comment]
@kyessenov hadn't written the PR description yet, it may answer that question now. If not I am not sure what you mean

**Pull request closed without merging**
