### PR TITLE
Update Vendor Files to match go.mod

### PR DESCRIPTION
**Pull request by therealmitchconnors**
The vendor directory was out of sync, likely due to someone not running `go mod vendor` before committing.  See https://github.com/istio/istio/wiki/Vendor-FAQ#how-do-i-add--change-a-dependency

### CODE REVIEW

**Comment by kyessenov** [comment]
This is strange.
Last change to `go.mod` was by me at c2d324a2e7f430b4d002acbf17ac06127c6be741.
```
git checkout c2d324a2e7f430b4d002acbf17ac06127c6be741
go mod vendor
```
leaves everything tidy.

However:
```sh
git checkout a122dc94700bb8cd514b4d8ae17f2308f044b5c3
go mod vendor
```
changes vendor...

**Comment by kyessenov** [comment]
The first change after mine that changed vendor is aa554e793a6d7ed5b2857db79c87624ccefd07e9.

**Comment by ericvn** [comment]
Do we need a `go mod tidy` run?

**Comment by geeknoid** [comment]
If we continue to use the vendor directory, we're going to need to have a gate to ensure "go mod vendor" was run.

We probably should ensure "go mod tidy" was run too.

**Comment by therealmitchconnors** [comment]
This commit was generated by running:
```
git clone https://github.com/istio/istio
go mod tidy
go mod vendor
git add vendor go.mod go.sum
git commit
```
Is there a step I missed?

**Comment by ericvn** [comment]
@therealmitchconnors That looks correct to me, although at some point we should be able to remove the vendor (I recall it mentioned on a call why that's to possible yet, but don't remember the specifics (CircleCI downlevel?)).

**Comment by geeknoid** [comment]
Those are the right steps. I just want to have a gate to make sure our go.mod file and the vendor dir are always up to date so folks don't forget.

As far as keeping vendor around, it's mostly about reproducibility. If a dependency we have disappears (someone deletes the repo), then we always have a copy around we can depend on before finding an alternate solution.

**Comment by kyessenov** [comment]
I have experimented with `go mod verify` and it doesn't behave as expected.

I think it would be more productive to move CI to _not use vendor_. For that, we need to update build docker images (which we have many and they are inconsistent) to upgrade go SDK.

We have many other options to preserve vendor. 
- `go mod download` as a separate job
- `go mod download` as part of Docker build
- `GOPROXY=file://` to move vendor out of git tree
- etc.

**Pull request merged**
