### PR TITLE
fix nodeagent priorityClass problem

### PR DESCRIPTION
**Pull request by paassdc**
fix nodeagent priorityClass can't take effect problem

### CODE REVIEW

**Comment by howardjohn** [comment]
We are doing all work on https://github.com/istio/installer for 1.2 release, as per the readme (sorry it isn't super visable), and changes on the installer here are frozen until then. Looks like a good change to get in there (although I am not sure why you had to add the do not inject annotation)

**Comment by morvencao** [comment]
@paassdc Would you please raise PR here: https://github.com/istio/installer

**Comment by morvencao** [comment]
@paassdc Would you please ry to rebase your code to pass the tests?

**Pull request merged**
