### PR TITLE
Added nodeSelector on discovery/gateways deployment templates

### PR DESCRIPTION
**Pull request by Smeedy**
From an OPA rule we have the internal requirement to have nodeselector on deployments. I've added them on the Pilot and Ingress/Egress deployment templates and added them into values as well. Since they will not do anything disrupting in the charts I decided to add them and use this PR so we can have a clean upstream on our clusters.  

[X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
It is recommended to use k8s settings to apply the **nodeSelector**, **tolerations**... see: https://github.com/istio/istio/blob/master/operator/samples/pilot-k8s.yaml

**Comment by Smeedy** [comment]
Hi @morvencao. I will have a look here. This will though break our take on this on the enterprise clusters since we are only working through Helm and not using the operator since that's the one off.

**Comment by howardjohn** [comment]
I am not sure its reasonable to expect every helm chart to have every single option. Maybe I just don't like helm, but k8s exposes 100s of options for each resource - I would think an overlay system (possible kustomize + helm, which I have seen before) is the only viable option for bespoke configurations.

**Comment by andreamaruccia** [comment]
> It is recommended to use k8s settings to apply the **nodeSelector**, **tolerations**... see: https://github.com/istio/istio/blob/master/operator/samples/pilot-k8s.yaml

@morvencao I'm confused. Why would this be not valid? If you see the resource limits for instance (https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-egress/templates/deployment.yaml#L152) you can see that it follows the same logic: params are provided for the respective helm charts.

In the case of @Smeedy even if the operator is used, I believe that the request will be rejected by OPA since it will not allow a request to be done without the nodeSelector being provided or am I missing something?

**Comment by andreamaruccia** [comment]
hey guys sorry to bother you is there a way to review this? the MR is stale now.
cc: @costinm @ostromart @sdake

**Comment by ericvn** [comment]
Reopening.

**Comment by Smeedy** [comment]
@googlebot I signed it!

**Comment by Smeedy** [comment]
@howardjohn In reply on your question. We are only interested in just an explicit NodeSelector since we are running hybrid clusters so the NodeSelector needs to be there all the time since we cannot rely on some default. This nodeSelector being present is vital for the workloads in the cluster (and that's why this is OPA enforced on our side).

Transforming or local forking of the Helm is an option but we really prefer to have the upstream holding the definition. And Helm being the de facto standard for the configs and 3rd party opt-ins we need to stick with it.

I could even pin the nodeSelector to a fixed Linux in the istiod/gateway upstream deployment Helm files as this needs to be run a Linux node anyway and makes the change a bit more condensed. Let me know if this makes any sense.

Thx, Martijn

**Comment by andreamaruccia** [comment]
@ericvn is something blocking this PR for any valid reason? I think the PR is valid

**Comment by ericvn** [comment]
@andreamaruccia If you look in the box at the bottom, there is a Code owner reviewed required section which highlights the approvals required. The @istio/wg-environments-maintainers is the main reviewer. I also added a label to draw their attention.

**Comment by ericvn** [comment]
@andreamaruccia And some test failures will need fixing.

**Pull request closed without merging**
