### PR TITLE
Use pods in docker compose

### PR DESCRIPTION
**Pull request by rshriram**
**What this PR does / why we need it**:
Simple bookinfo (same with or without istio) and a separate set of containers hosting the sidecars. Overtime, these containers can be generated using istioctl docker-inject style commands programmatically. Tested with Consul, and assuming it works similarly in Eureka.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
POD style construct in docker compose
```

### CODE REVIEW

**Comment by rshriram** [comment]
We can do that in follow up PR as well.

**Comment by ijsnellf** [comment]
we will need to update the docs as well after this is merged

**Comment by ijsnellf** [comment]
We can do that in a follow up PR. I volunteer @GregHanson.

**Comment by costinm** [comment]
Super cool !  I missed the 'istioctl docker-inject' review, excited to see it !

**Pull request merged**
