### PR TITLE
feat:fix bug add-to-mesh service productpage can't add or remove sidecar Error

### PR DESCRIPTION
**Pull request by tanjunchen**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

### CODE REVIEW

**Comment by tanjunchen** [comment]
ref:https://github.com/istio/istio/issues/25877

**Comment by tanjunchen** [comment]
> LGTM.
> 
> @tanjunchen can you also update the test.

ok . thanks . btw, https://github.com/istio/istio/issues/25830 could u review this problems. Thanks

**Comment by shamsher31** [comment]
> btw, #25830 could u review this problems. Thanks

I believe @esnible is looking into it. He already fixed one of the related issue https://github.com/istio/istio/pull/25452 .

**Comment by tanjunchen** [comment]
> > btw, #25830 could u review this problems. Thanks
> 
> I believe @esnible is looking into it. He already fixed one of the related issue #25452 .

right. It seems that this problem still exists.

**Pull request closed without merging**
