### PR TITLE
Upgrade istio-builder image to 0.4.6

### PR DESCRIPTION
**Pull request by chxchx**
See discussion in https://github.com/istio/istio/pull/3279

/assgin @mattdelco @sebastienvas @rkpagadala

### CODE REVIEW

**Comment by ldemailly** [comment]
what is new in 0.4.6 ?

**Comment by mattdelco** [comment]
This change is great for updating the release builds, though it'd be more proper/complete to also remove the following from release/cloud_builder.sh:

<pre>apt-get -qqy install ruby ruby-dev rubygems build-essential
gem install --no-ri --no-rdoc fpm
</pre>

I think your motivation is to update what's run by prow for pre/post-submit, and that's probably controlled elsewhere, but I'm not sure where.  E.g., prow/config.yaml is one possible lead, at least for green-builds.

**Comment by chxchx** [comment]
0.4.6 comes with fpm installed

**Comment by mattdelco** [comment]
/lgtm

The file linux-install-bazel seems to have BAZEL_VERSION='0.6.1' in it, so I'm not clear on how a newer 0.7 got into the older image that's being replaced.  I don't know what istio/proxy expects these days, but I suppose it's a net win for the release builds that this image is usually used for.

It looks like linux-install-golang is using 1.9, though 1.9.3 would be more ideal.  I don't know which specific version is in the builder 0.4.5 image so I don't know if this is getting older or staying the same.

**Comment by chxchx** [comment]
Thank you @mattdelco for spotting the versioning discrepancy. Perhaps the previous 0.4.5 image was created with bazel 0.7 and pushed, but such version change remained local and was not merged into test infra. I am not sure if 0.6.1 bazel will break anything. Should we make a new image with the 0.7 bazel and 1.9.3 go as suggested?

/cc @sebastienvas

**Comment by mattdelco** [comment]
Afaik istio-builder is only used for release builds in cloud builder, and it's currently not using bazel so the downgrade to 0.6.1 should break anything (except possibly me when I try to experiment with building everything from local source).  Prow-builder might be a different story.  There is the update bot that builds proxy artifacts in post-submit but I don't know if that uses prow-builder or something else.  As for go, it looks like 1.10 is expected soon so regardless of whether we do 1.9 or 1.9.3 it's likely that it'll be reved again soon for 1.10 (1.10 has some caching features that can improve build performance so devs will likely be eager to adopt 1.10).

**Pull request merged**
