### PR TITLE
Fix #14235

### LINKED ISSUE #14235: Mixer container crashes with 'invalid memory address or nil pointer dereference' after upgrading to 1.1.6
**Bug description**
After upgrading istio from 1.0.6 to 1.1.6 mixer is crashing in both `istio-policy` and `istio-telemetry` pods.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1784e3f]

goroutine 1 [running]:
istio.io/istio/mixer/pkg/runtime/routing.(*builder).addRuleOperations(0xc420ec74c0, 0xc4203412c0, 0xc, 0x0, 0x0, 0xc42000dcb0, 0x1, 0x1)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/routing/builder.go:728 +0x12f
istio.io/istio/mixer/pkg/runtime/routing.(*builder).build(0xc420ec74c0, 0xc420036000)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/routing/builder.go:234 +0x1011
istio.io/istio/mixer/pkg/runtime/routing.BuildTable(0xc420af9b00, 0xc420036000, 0x7ffecb65593b, 0xc, 0xc420c0f500, 0x4625be)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/routing/builder.go:137 +0x286
istio.io/istio/mixer/pkg/runtime.(*Runtime).processNewConfig(0xc42027a070)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/runtime.go:159 +0x10b
istio.io/istio/mixer/pkg/runtime.(*Runtime).StartListening(0xc42027a070, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/runtime.go:117 +0x15f
istio.io/istio/mixer/pkg/server.newPatchTable.func1(0xc42027a070, 0xc420531a70, 0xc420531aa0)
	/workspace/go/src/istio.io/istio/mixer/pkg/server/server.go:105 +0x2b
istio.io/istio/mixer/pkg/server.newServer(0xc420334600, 0xc420534190, 0x6977206465747261, 0xa73250a6874, 0xc42054a480)
	/workspace/go/src/istio.io/istio/mixer/pkg/server/server.go:219 +0x926
istio.io/istio/mixer/pkg/server.New(0xc420334600, 0x15, 0xc42054a480, 0x1)
	/workspace/go/src/istio.io/istio/mixer/pkg/server/server.go:95 +0x39
istio.io/istio/mixer/cmd/mixs/cmd.runServer(0xc420334600, 0x20f2c60, 0x20f2c58)
	/workspace/go/src/istio.io/istio/mixer/cmd/mixs/cmd/server.go:93 +0x9e
istio.io/istio/mixer/cmd/mixs/cmd.serverCmd.func1(0xc420279680, 0xc420037980, 0x0, 0x8)
	/workspace/go/src/istio.io/istio/mixer/cmd/mixs/cmd/server.go:37 +0x3c
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0xc420279680, 0xc420037880, 0x8, 0x8, 0xc420279680, 0xc420037880)
	/workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420279400, 0x0, 0x2031de8, 0x12)
	/workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:846 +0x30a
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420279400, 0x9, 0x9)
	/workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/workspace/go/src/istio.io/istio/mixer/cmd/mixs/main.go:39 +0x293
```

**Expected behavior**
Mixer was able to start up.

**Steps to reproduce the bug**
Currently unclear.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio is version 1.1.6 inside the cluster, but as mixer is not running --remote will not report it:
```
$ istioctl version --remote
version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"brew", Host:"Mojave-2.local", GolangVersion:"go1.12.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4"}
Error: error execing into istio-policy-65d47566cd-zfrzb mixer container: unable to upgrade connection: container not found ("mixer")
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
1.0.6 was installed using helm with helmsman describing the desired state.
Upgrade was also done using helm, by following the upgrade steps for helm.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS, worker nodes running kubernetes v1.12.7

Mixer and pilot logs:
[mixer_mixer.log](https://github.com/istio/istio/files/3196670/mixer_mixer.log)
[pilot_discovery.log](https://github.com/istio/istio/files/3196671/pilot_discovery.log)
[pilot_istio_proxy.log](https://github.com/istio/istio/files/3196672/pilot_istio_proxy.log)
 
replicaset definitions:

[replicaset_policy.yml.txt](https://github.com/istio/istio/files/3196673/replicaset_policy.yml.txt)
[replicaset_telemetry.yml.txt](https://github.com/istio/istio/files/3196674/replicaset_telemetry.yml.txt)

### PR DESCRIPTION
**Pull request by kyessenov**
Fixes #14235 
Cherry-pick of https://github.com/istio/istio/pull/14256

/assign @douglas-reid

### CODE REVIEW

**Comment by Multiply** [comment]
@kyessenov We can run this in our test-cluster to verify it's fixed, if you want.

**Comment by kyessenov** [comment]
Thanks! That would be great if you can confirm this fix works.
The image is gcr.io/istio-testing/mixer:f85fb7d434d62f4f286b9b5de975549056b4c8b8

The test failure here is known and due to problems with helm install for redis.

**Comment by Multiply** [comment]
> gcr.io/istio-testing/mixer:f85fb7d434d62f4f286b9b5de975549056b4c8b8

Can confirm that istio-policy and istio-telemetry is no longer crashing when using the above image.

**Comment by kyessenov** [comment]
Thanks @Multiply !
@duderino can you please merge this backport into 1.1? The test flake is known and due to `helm install redis/stable` failing for unknown reasons.

**Pull request merged**
