### PR TITLE
filter multi-network gateway services by revision label

### PR DESCRIPTION
**Pull request by stevenctl**
Necessary for upgrades in multi-network configurations. Without this, Gateways configured by an old control plane may be part of the multi-network loadbalancing rotation. 

cc @nmittler @howardjohn

### CODE REVIEW

**Review by nmittler — APPROVED** [review]
Good catch! LGTM

**Comment by stevenctl** [comment]
One problem we could still have with upgrades: 

We hardcode the name of the gateway here:
https://github.com/istio/istio/blob/a43810c5326adce8c1910224a5aaa235d9e5b8b5/samples/multicluster/gen-eastwest-gateway.sh#L74

And unlike istiod, the ingressgateway template doesn't append `-{.Revision}` to the Service name, so we'll end up replacing the old gateway service.

**Comment by stevenctl** [comment]
https://istio.io/latest/docs/setup/upgrade/gateways

I don't fully understand how revisioned gateways are supposed to work? Even this guide seems to have you completely overwrite your old gateway.

**Comment by stevenctl** [comment]
cc @howardjohn @Monkeyanator

**Review by howardjohn — COMMENTED** [review]
Does this mean I must have 1:1 gateway with istiod? And cannot just add istiod use existing gateways? I am not certain that matches the users expectations today. Is this required since the gateway may have different configs that are only valid for the associated revision?

cc @costinm

**Comment by stevenctl** [comment]
> the gateway may have different configs that are only valid for the associated revision

This is my assumption, but I'm not certain it's actually true.

**Pull request closed without merging**
