### PR TITLE
move up kiali and grafana

### PR DESCRIPTION
**Pull request by linsun**
to address some vulnerability issue found during our image scan for older images we use in 1.1

### CODE REVIEW

**Comment by linsun** [comment]
@jmazzitelli i noticed you had a bunch of other changes... https://github.com/istio/istio/pull/11823

Can we just update the version in 1.1 but not picking up the other changes to minimize risk or we need to bring them together in?  thoughts?

**Comment by howardjohn** [comment]
I think youll need to rebase to fix test failures

**Comment by jmazzitelli** [comment]
You are going to need to cherry-pick over the kiali yaml for this. Do not just move up the version without pulling in the new yaml... some things have changed between 0.14 and 0.16 such as the location of the secret (now mounted on the file system, not via env vars). See the master PR that bumped kiali from 0.14 to 0.16: https://github.com/istio/istio/pull/11823

FWIW: we have a kiali e2e test to check at least the basic install works - but that istio PR has been stagnate and not merged due to lack of review/approvate. See: https://github.com/istio/istio/pull/11448

**Comment by jmazzitelli** [comment]
BTW: as a side note: Kiali is going to soon release a Kubernetes Operator that will be used for installing Kiali in the future. At some point after that, we will want to have the istio pull in Kiali using its operator

**Comment by linsun** [comment]
Thanks for the feedback, I'll rework this into 2 PRs, including 1 kiali cherrypick from master to 1.1

**Pull request closed without merging**
