### PR TITLE
Add HPA and PDB for Istiocoredns manifests

### PR DESCRIPTION
**Pull request by zufardhiyaulhaq**
Enable user to setup HorizontalPodAutoscaler and PodDistruptionBudget for istiocoredns component when using multicluster that need istiocoredns to resolv .global FQDN.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

related issue: https://github.com/istio/istio/issues/24769

### CODE REVIEW

**Comment by zufardhiyaulhaq** [comment]
@googlebot I signed it!

**Review by morvencao — COMMENTED** [review]
/ok-to-test

**Comment by zufardhiyaulhaq** [comment]
@morvencao can you review & merge?

**Review by morvencao — COMMENTED** [review]
Please also add condition check for https://github.com/istio/istio/blob/master/manifests/charts/istiocoredns/templates/deployment.yaml#L10

**Comment by zufardhiyaulhaq** [comment]
> Please also add condition check for https://github.com/istio/istio/blob/master/manifests/charts/istiocoredns/templates/deployment.yaml#L10

It is something similar like https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L15 right?

**Comment by zufardhiyaulhaq** [comment]
@morvencao please review

**Review by morvencao — APPROVED** [review]

**Comment by zufardhiyaulhaq** [comment]
@morvencao please merge, thank you

**Pull request merged**
