### PR TITLE
Move golden output files to test_mode specific directories

### PR DESCRIPTION
**Pull request by abhide**
istio-iptables golang implementation will cause changes to the output format.
Moving these expected test output under testmode specific directories;
to keep test compatible with the current istio-iptables script.

### CODE REVIEW

**Comment by abhide** [comment]
@rlenglet @mandarjog @duderino @howardjohn 

Can one of you take a look? Thanks!

**Comment by rlenglet** [comment]
Can someone from @istio/wg-test-and-release-maintainers take a look? This is mostly a mechanical change, which is required to match the optimizations @abhide is doing in the Golang implementation.

**Pull request merged**
