### PR TITLE
remove unused glog dependency

### PR DESCRIPTION
**Pull request by leizhiyuan**
I noticed there are so many unused glog import, and It make "real TODO" is difficult to find. So I just remove them with replace function.

### CODE REVIEW

**Comment by ZackButcher** [comment]
/lgtm
Thanks! I'll let Nathan give the final approval, I'm not sure if there was anything else blocking removing those imports.

**Comment by ldemailly** [comment]
@nmittler can you remind us what the todo was about ?
I _think_ we have istio/glog as a bridge from glog to istio logger but not sure it's all in place already - @geeknoid 

/hold

**Comment by leizhiyuan** [comment]
sorry. I get something wrong..

**Comment by nmittler** [comment]
@leizhiyuan mind rebasing? Then we can look into the failing tests.

**Comment by leizhiyuan** [comment]
@nmittler I solved the conflict in Github.  Tests is running again.

**Comment by ldemailly** [comment]
^

**Comment by ldemailly** [comment]
I believe this is done already now - please reopen if I'm mistaken

**Pull request closed without merging**
