### PR TITLE
[1.5] Fix PDB selector for istiod (#22273)

### PR DESCRIPTION
**Pull request by howardjohn**
(cherry picked from commit fd0591e2364d8600c47a67b55516252bbfa3903b)

### CODE REVIEW

**Comment by howardjohn** [comment]
@ostromart any idea what is up with

```
./operator/cmd/mesh/testdata/manifest-generate/output/component_hub_tag.golden.yaml
  133:17    error    too many spaces after colon  (colons)
  136:17    error    too many spaces after colon  (colons)
  139:17    error    too many spaces after colon  (colons)
  142:17    error    too many spaces after colon  (colons)
  145:17    error    too many spaces after colon  (colons)
  148:17    error    too many spaces after colon  (colons)
  151:17    error    too many spaces after colon  (colons)
  154:17    error    too many spaces after colon  (colons)
```

**Comment by howardjohn** [comment]
@ostromart I don't understand why this is failing, any ideas?

**Comment by ostromart** [comment]
sorry i missed this earlier... lint is correctly reporting bad yaml:
133:          name:<2 spaces>istio
Looking at manifests/istio-telemetry/grafana/templates/deployment.yaml there are indeed two spaces in the template.
it looks like that line has been there for over a year so i'm not sure why it's been passing all this time. probably we haven't run a linter on any manifest generated with this in it before.

**Comment by howardjohn** [comment]
/retest

Retrying one more time to see if its magically fixed. If not Ill fix the template I guess

**Comment by howardjohn** [comment]
figured out the problem... the cherrypick copied some new golden files that were not needed. I removed those now

**Pull request merged**
