### PR TITLE
Revert driver to old version

### PR DESCRIPTION
**Pull request by wattli**
The current one does not work in GKE, I tried to fix but seems there are many incompatible issues. Revert it and work on a fix in the meantime.

### CODE REVIEW

**Comment by wattli** [comment]
@incfly , this will unblock you from the development work.

**Comment by wattli** [comment]
Saurabh, here are the ones I found: 

1) the driver needs to be initialized with https://github.com/istio/istio/blob/master/security/cmd/flexvolume/driver/driver.go#L66

2) the mgmt.sock and workload.sock paths in the driver changed, but the node agent code does not

3) I tried to fix 2) but looks like /var/run path has some permission issues, this part I was not sure.

**Comment by saumoh** [comment]
@wattli let me take a look at 1 and 2.

**Comment by wattli** [comment]
Thanks

**Pull request merged**
