### PR TITLE
Change doc about e2e presubmit status

### PR DESCRIPTION
**Pull request by yutongz**
Matches https://github.com/istio/istio/issues/3509

### CODE REVIEW

**Comment by yutongz** [comment]
BTW, I don't know why we moved pilot e2e/integration tests under this dir, they don't even use this framework. It's confusing to me it lives under `istio/tests/e2e/tests`

**Comment by ldemailly** [comment]
> BTW, I don't know why we moved pilot e2e/integration tests under this dir, they don't even use this framework. It's confusing to me it lives under istio/tests/e2e/tests

I agree

/lgtm

**Pull request merged**
