### PR TITLE
Remove default --skip_cleanup in test makefile.

### PR DESCRIPTION
**Pull request by hklai**

### CODE REVIEW

**Comment by sebastienvas** [comment]
this makes me laugh. That means that test relies on the fact that clean up is skipped. OMG.

**Comment by hklai** [comment]
The fact that the tests are still passing (and the nodeport problem disappeared) seem to imply the tests do not depend on cleanup being skipped.

Instead, I suspect it was there for this only.
https://github.com/hklai/istio/blob/78c04617aafd8c0c86323bdb740bcf80e77aaf47/tests/istio.mk#L229

which is probably a wrong thing to do (i.e. not cleaning up for everything).

**Comment by sebastienvas** [comment]
I just looked at prow/istio-pilot-e2e.sh failures. I guess this test was already failing.

**Comment by costinm** [comment]
On Thu, Jun 14, 2018, 08:26 Andy Lai <notifications@github.com> wrote:

> Getting the cluster dump and debug info on circleci depends on this
>
> It should not be needed for all tests. We should just need a way to enable
> it for targeted test runs, which we apparently already have.
>
Why not ? We want to know what happened and inspect for all tests. Even if
test passes.


Can you include before/after execution time on circleci ? There is no point
> in spending time clening up in circle - the entire environment is going
> away.
>
> With this 9mins6secs.
> https://circleci.com/gh/istio/istio/114150
> Around 30 seconds more than other runs.
> https://circleci.com/gh/istio/istio/114198
>
30 second wasted for nothing seems a long time. The entire env is
ephemeral.





It is related to the nodeport problem as discussed on the test/release
> channel on slack. See below.
> We need either this or fixing that or both to restore daily releases
> (hence monthly RC) tomorrow. Not cleaning up is problematic in Prow and we
> cannot optimize only circle.
>
Prow can override and add the flag.

Or even better - split the cleanup to separate target ( for parallel
running, etc).

No need to slow down and break circle just to pass an extra prow-specific
flag


===========================================================

**Comment by costinm** [comment]
What do you mean we can't optimize only circle ? Add a 30 second sleep just
to be as bad as prow ??

**Comment by costinm** [comment]
Sorry, but this is crazy: if nodeports should not be created in prow, just
add an option to helm to not create them in prow.

Why would a fix for nodeport config involve breaking and slowing circle ?

**Comment by hklai** [comment]
If it is meant for circle optimization, add the extra argument to circle
config.

It should not be in the makefile which also affects running these tests
locally as Doug mentioned. I hit the same problem yesterday as well.

Also, considering some prow job is required, the 30s saving in circle jobs
is not material.

**Pull request merged**
