### PR TITLE
enable mixer alpha3_v2 tests

### PR DESCRIPTION
**Pull request by mandarjog**

### CODE REVIEW

**Comment by mandarjog** [comment]
@ostromart looks like the new test failed :-(

**Comment by costinm** [comment]
Can we get this in master sooner ?

**Comment by rshriram** [comment]
FYI: ci/circleci: e2e-mixer-noauth-v1alpha3-v2 passes. The error is from the dumpsys stage in circleci config. Not fixing it in this PR.

**Pull request merged**
