### PR TITLE
Update distroless, with ztunnel support and debian12

### LINKED ISSUE #43243: ambient: support and default to distroless
We currently need ubuntu due to ztunnel init container using shell.

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/43243

### CODE REVIEW

**Comment by keithmattix** [comment]
How did we fix libgcc linking in https://github.com/istio/istio/issues/43243?

**Comment by howardjohn** [comment]
Added libgcc as well, forgot to mention that

**Comment by keithmattix** [comment]
> Added libgcc as well, forgot to mention that

That got added in the iptables base image?

**Comment by howardjohn** [comment]
> That got added in the iptables base image?

Yes. Its already in the standard base images distroless publishes for non-static images, we had just elided it from our custom images until now. Its quite small (100kb) so seems pretty low risk to include, and virtually impossible to remove from rust binaries it seems. All rust projects using distroless, as far as I found, include this

**Review by keithmattix — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
