### PR TITLE
Cleanup manifest samples

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Samples in manifest directory don't provide much value, can be deleted or moved to `operator/samples`.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
I believe you need to do an update_deps or at least update https://github.com/istio/istio/blob/master/prow/release-commit.sh#L39C13-L39C53 to be the new release-builder SHA.

**Comment by hanxiaop** [comment]
The ambient test failure seems to occur when I update the ztunnel commit to 71ef8eb9a71bb5b5450866dd9f6da5e1527751e6; it appears that recent changes have broken the test. I'll revert the ztunnel commit change and record this in the issue.

**Pull request merged**
