### PR TITLE
Change the default for UseOldProcessor flag.

### PR DESCRIPTION
**Pull request by ozevren**
Not ready for check-in yet. Using this PR to run some tests continuously.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nmittler** [comment]
@ozevren am I missing something? The description doesn't seem to match the changes.

**Comment by ozevren** [comment]
It does. Or, will be when https://github.com/istio/istio/pull/17120 is checked in. This PR contains some of the fixes that go in there (plus some other changes that I'll split off to another PR).

**Review by geeknoid — APPROVED** [review]

**Pull request merged**
