### PR TITLE
Added documentation for message code for istioctl analyze

### PR DESCRIPTION
**Pull request by my-git9**
**Please provide a description of this PR:**

The message code is not a piece of information that is easy for users to remember and understand. Adding relevant documentation will help improve the user experience.

### CODE REVIEW

**Review by hanxiaop — COMMENTED** [review]
The message is already too long and why do you think we need to add the link here? We do have several places to inform users with the doc link. See the usage of 
https://github.com/istio/istio/blob/9d5a361d030fdab10c529aef596e521bb8d8f89b/pkg/url/url.go#L66-L68

**Comment by my-git9** [comment]
> The message is already too long and why do you think we need to add the link here? We do have several places to inform users with the doc link. See the usage of
> 
> https://github.com/istio/istio/blob/9d5a361d030fdab10c529aef596e521bb8d8f89b/pkg/url/url.go#L66-L68

The information here seems to be displayed to the user only when the command reports an error. I think that it would be more user-friendly if it could be displayed directly in the normal help command.

**Comment by hanxiaop** [comment]
If so, it would be better to place the link in a more obvious location, like in the command description since this doc isn't only for the suppress flag.

**Comment by my-git9** [comment]
> If so, it would be better to place the link in a more obvious location, like in the command description since this doc isn't only for the suppress flag.

Updated, PTAL, thanks

**Review by hanxiaop — APPROVED** [review]

**Pull request merged**
