### PR TITLE
Make jaeger installation the same as other addons in Ansible playbook

### PR DESCRIPTION
**Pull request by geoand**
This PR removed the `istio.jaeger` flag and simply makes `jaeger` one of the options in `istio.addon`

### CODE REVIEW

**Comment by geoand** [comment]
@costinm As far I can see, Helm does not provide the ability to install Jaeger instead of Zipkin (although I might be wrong since I have never used Helm)

**Comment by costinm** [comment]
You are right, helm and regular templates only have zipkin.

But I think I am right too :-) - we should be consistent and add jaeger to
helm as well.

We are planning to deprecate the install/kubernetes/templates - and replace
them with
'helm template' or 'istioctl gen-template' - so probably no need to update
that.

**Comment by geoand** [comment]
I totally agree that consistency is desirable across the different installation methods :)

**Comment by ldemailly** [comment]
Mick Jagger installation...

**Pull request merged**
