### PR TITLE
fix typo.

### PR DESCRIPTION
**Pull request by morvencao**
Fix typo in `ingress` cluserrolebinding
Moved from https://github.com/istio/istio/pull/7475

### CODE REVIEW

**Comment by gyliu513** [comment]
/cc @costinm 

Any comments for this? You mentioned some upgrade issues here https://github.com/istio/istio/pull/7475#pullrequestreview-141333835

**Comment by morvencao** [comment]
@costinm I think this will not break Istio upgrade, since we just change the reference name of `clusterrole`, instead of `clusterrole` itself.

**Comment by morvencao** [comment]
@ymesika If you mean test upgrade from 0.8.0 
Helm upgrading for istio currently broken because of an helm issue: helm/helm#1193
So I think helm upgrade from 0.8.0 to 1.0+ will be broken for other reasons.
But upgrading Istio with kubectl apply ... should be OK.

**Comment by morvencao** [comment]
@sdake Thanks OK to close this.

**Comment by sdake** [comment]
@morvencao I wouldn't give up all hope - maybe someday kubernetes will permit the modification of the name field there.  There are several bugs of this type in Kubernetes and they receive alot of traffic and complaints.

Cheers
-steve

**Comment by ymesika** [comment]
Maybe add a comment there to avoid the 6th?

**Pull request closed without merging**
