### PR TITLE
Fix loadBalancerSourceRanges default value in the helm chart

### LINKED ISSUE #9725: loadBalancerSourceRanges in helm chart does not work
**Describe the bug**
`loadBalancerSourceRanges` capability has been added by #7740. But when using it with helm version 2.10, helm install complains with this: 
```
2018/10/29 16:28:10 warning: cannot overwrite table with non table for loadBalancerSourceRanges (map[])
Release "istio" has been upgraded. Happy Helming!
```

Looking at the service for ingressgateway, we can confirm that it DOES NOT have `loadBalancerSourceRanges` configured: 
> kubectl get svc/istio-ingressgateway --namespace istio-system -o yaml 

**Expected behavior**
no warning from helm, and `kubectl get svc/istio-ingressgateway --namespace istio-system -o yaml ` containing configured `loadBalancerSourceRanges`

**Steps to reproduce the bug**
```
wget https://github.com/istio/istio/releases/download/$(ISTIO_VERSION)/istio-$(ISTIO_VERSION)-linux.tar.gz
tar zxf istio-$(ISTIO_VERSION)-linux.tar.gz
cd istio-$(ISTIO_VERSION)
wget https://patch-diff.githubusercontent.com/raw/istio/istio/pull/7744.patch;
patch -p1 --no-backup-if-mismatch < 7744.patch;
```
Then configure loadBalancerSourceRanges in a custom `values.yaml` for ingressgateway, and install istio. 

**Version**
istio version: 1.0.3

```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.6", GitCommit:"06898a4d0f2b96f82b43d9e59fa2825bd3d616a2", GitTreeState:"clean", BuildDate:"2018-10-02T17:32:01Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

helm version
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```
**Installation**
helm install

**Environment**
GKE

**Cluster state**
Without loadBalancerSourceRanges working, ingress endpoint is not protected with firewall rules.

### PR DESCRIPTION
**Pull request by enis**
Fixes #9725.

### CODE REVIEW

**Comment by enis** [comment]
/assign @gyliu513 
cc @rshriram , @ ijsnellf

**Comment by linsun** [comment]
can you submit this for release 1.1 also?  There is also a reference to this in values-istio-gateways.yaml file.

**Comment by enis** [comment]
Thanks, created https://github.com/istio/istio/pull/9727.

**Comment by ymesika** [comment]
+1 for empty to keep it consistent with other places (e.g. Grafana and Servicegraph)

**Comment by linsun** [comment]
@enis could you test if setting it as `loadBalancerSourceRanges:` will solve your prob?

/hold

**Comment by ymesika** [comment]
@enis And please keep only your `release-1.1` #9727 open. It will be eventually merged to `master`.

**Comment by linsun** [comment]
close this PR as changes from 1.1 (#9727) will be batch merged to master.

**Pull request closed without merging**
