### PR TITLE
[Kiali][master] things needed for next version of Kiali

### PR DESCRIPTION
**Pull request by jmazzitelli**
I'm going to play with the new github feature of a draft pull request here :)

This is going to be a PR I will build up as things are needed to upgrade Istio master branch to the next Kiali release. ~~Do not merge - it is a WIP~~

### CODE REVIEW

**Comment by xeviknal** [comment]
@jmazzitelli we need this too: https://issues.jboss.org/browse/KIALI-2417

**Comment by xeviknal** [comment]
@jmazzitelli we have this[1] also for updating kiali. Thanks.
[1] https://issues.jboss.org/browse/KIALI-2564

**Comment by jmazzitelli** [comment]
@xeviknal done: https://github.com/istio/istio/pull/11823/commits/40782ff5ae13980b26427072e651bffbf99ff51c

**Comment by jmazzitelli** [comment]
Kiali v0.16 was just released. This pulls in the necessary changes into master to get that version of Kiali into Istio. This PR now needs review, plus also need to find out why I'm seeing unrelated tests fail.

**Comment by jmazzitelli** [comment]
/assign @linsun 

Lin - please try this out - this should bring in the new Kiali v0.16 to master

**Comment by jmazzitelli** [comment]
Found a [problem](https://github.com/kiali/kiali/issues/927) in v0.16 - gonna release a new patch version. Then we can merge this.

**Comment by jmazzitelli** [comment]
Taking off the hold - the problem was fixed. We can merge this.

**Pull request merged**
