### PR TITLE
Fix istio/operator tagging

### PR DESCRIPTION
**Pull request by clarketm**
Fix `istio/operator` tagging.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
Ha. I can't force-merge any more. Release managers are not admins anymore. :/

**Comment by clarketm** [comment]
Based on the lint errors (https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/18587/lint_istio_release-1.3/122/build-log.txt) I presume this specific job will not pass. Is this because of the builder-tools image version?

**Comment by rlenglet** [comment]
Yes, none of the PRs against `release-1.3` are merging because of the builder image has an updated `yamllint`.

**Comment by clarketm** [comment]
@rlenglet - who should I reach out to to force push this through (if that is the *best* option here)?

**Comment by rlenglet** [comment]
> @rlenglet - who should I reach out to to force push this through (if that is the best option here)?

Honestly I don't know who has admin rights these days. Release managers aren't admin anymore.

> Alternatively, should I lint the yaml and file a follow-up PR? Will that fix the failures?

Yes, that would be great!

**Comment by clarketm** [comment]
> Honestly I don't know who has admin rights these days. Release managers aren't admin anymore.

No problem. I will reach out on slack at a reasonable hour to solicit assistance. 

> Yes, that would be great!

👍 . I will tackle this and file a PR.

**Comment by howardjohn** [comment]
why don't we just remove the yamllint?

**Comment by clarketm** [comment]
> why don't we just remove the yamllint?
Does this require some form of modification to the `Makefile` in this repo on branch `release-1.3`?

**Pull request merged**
