### PR TITLE
Update CODEOWNERS to add some UX maintainers for helm chart values files

### PR DESCRIPTION
**Pull request by jacob-delgado**
**Please provide a description of this PR:**

It's best to leave manifests to the wg-environments-maintainers instead of a few people

### CODE REVIEW

**Comment by jacob-delgado** [comment]
It's sometimes hard to get a hold of people when one of the few people on this list need to push a change. See https://github.com/istio/istio/pull/45207

**Review by howardjohn — COMMENTED** [review]
I am fine with this but we should be cautious to avoid merging junk into the values - the intent of the small list was to avoid this

**Comment by howardjohn** [comment]
I like not being one, it gives me an excuse to say No without being the bad
guy :-)

**Comment by zirain** [comment]
what about add @istio/wg-user-experience-maintainers ? helm chart always cause UX problem.

**Comment by hanxiaop** [comment]
> what about add @istio/wg-user-experience-maintainers ? helm chart always cause UX problem.

I'm not sure if @istio/wg-user-experience-maintainers have ever maintained this part. Sometimes, it's not very clear for a single person to determine whether things need to be merged. Is it possible to limit the number of approvals required from ENV maintainers to two?

**Comment by bleggett** [comment]
> > what about add @istio/wg-user-experience-maintainers ? helm chart always cause UX problem.
> 
> I'm not sure if @istio/wg-user-experience-maintainers have ever maintained this part. Sometimes, it's not very clear for a single person to determine whether things need to be merged. Is it possible to limit the number of approvals required from ENV maintainers to two?

Or require 1 from UX and 1 from ENV, if it's a crosscutting concern (it is IMO).

**Comment by zirain** [comment]
> > > what about add @istio/wg-user-experience-maintainers ? helm chart always cause UX problem.
> > 
> > 
> > I'm not sure if @istio/wg-user-experience-maintainers have ever maintained this part. Sometimes, it's not very clear for a single person to determine whether things need to be merged. Is it possible to limit the number of approvals required from ENV maintainers to two?
> 
> Or require 1 from UX and 1 from ENV as a merge gate, if it's a crosscutting concern (it is IMO).

that's what i'm thinking

**Comment by howardjohn** [comment]
I don't think we have the ability to require 1 of each. Can just do OR
I don't think we can even do 2 approvals needed on a per-directory basis

**Comment by bleggett** [comment]
> I don't think we have the ability to require 1 of each. Can just do OR I don't think we can even do 2 approvals needed on a per-directory basis


Is that a limitation with our tooling we could fix? Or is that something we explicitly (have, want to continue) avoid doing?

**Comment by howardjohn** [comment]
Limit on GitHub tooling afaik.

**Comment by jacob-delgado** [comment]
I added @GregHanson and @hanxiaop as representatives from the UX maintainers group given that both are fairly involved with the community. Concerns? Thoughts?

**Comment by howardjohn** [comment]
Yeah that is per repo. It's also not great since it's "1 TOC member + 1 of
anyone" when we really would prefer it to be 2 TOC members

**Comment by bleggett** [comment]
We could just create `helm-approvers` if it becomes a maintenance problem - but I'm good with what's here for now.

**Comment by ericvn** [comment]
This LGTM.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
