### PR TITLE
Label proxy images

### LINKED ISSUE #6572: Provide an easy way to trace which envoy version is being used in the proxy_debug and release docker images
@mdhume commented on [Tue Jan 30 2018](https://github.com/istio/old_issues_repo/issues/176)

**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Feature Request:**
Y

**Describe the feature:**

Currently to figure out which envoy version is being used, one would need to trace back by using the docker SHA specified in the pilot repo to the git SHA in the proxy repo, to get the git SHA of the envoy repo.
Even in the docker container version command returns `/usr/local/bin/envoy  version: 0//DEBUG`

Would it be possible to expose this more explicitly as part of the docker or part of the github repo itself?

### PR DESCRIPTION
**Pull request by elevran**
Label istio-proxy images with SHA of dependencies

Fixes #6572

After this PR is merged, documentation should be added to inform users how to get the versions from the images.
(replaces #11375)

### CODE REVIEW

**Comment by elevran** [comment]
example:
```sh
$ docker inspect -f '{{json .Config.Labels}}' istio/proxyv2:2638f9d34f13e67a331fcc01ddaf4e03b0b26fa7

{"envoy-vcs-ref":"b3be5713f2100ab5c40316e73ce34581245bd26a","istio-api-vcs-ref":"825044c7e15f6723d558b7b878855670663c2e1e"}
```

**Comment by ricochet** [comment]
The changes to `bin/init.sh` are not macOS friendly.

`sed: 1: "/name/,/lastStableSHA/{ ...": extra characters at the end of p command`

**Comment by elevran** [comment]
@ricochet will submit a cross platform fix tomorrow. Thank you for your patience.

**Comment by stormasm** [comment]
@linsun @elevran Is there any way in the future we can put a testing procedure in place so that it doesn't break the build for everyone developing on a mac ?  Just curious... Seems like there should be some type of a bot where the build can get checked for mac development environments ?

**Pull request merged**
