### PR TITLE
fix flaky race condition in TestCrdsRetryMakeSucceed

### PR DESCRIPTION
**Pull request by xiaolanz**
addresses #4486 

All tests in this file set retryInterval=0 in  getTempClient()  that causes a race condition when tests are running in parallel.  

Also exclude a api server test from racetest.

### CODE REVIEW

**Comment by geeknoid** [comment]
I don't understand what this change impacts. Can you describe what's the specific problem & fix?

**Comment by xiaolanz** [comment]
PTAL  yes. init() was a bad choice so changed to once. for some reason, i thought it was file scope init.

**Comment by geeknoid** [comment]
I don't believe the diagnostic is correct.

Writing retryInterval to 0 over and over again will not cause a race condition.

**Comment by xiaolanz** [comment]
retryInterval is *read* in the production code. This causes racing condition. Hmmm, using once still doesn't fix the problem completely. It just races less. Are you ok if i change the type into atomic? Although I feel it's a bit overkill.

**Comment by geeknoid** [comment]
I don't believe that any of this will solve the race.

The value is written once as a static var initializer, and the test writes
it down to 0. You even had it as an init function and that didn't help.
There is simply no race there.

**Comment by xiaolanz** [comment]
PTAL.

**Comment by xiaolanz** [comment]
PTAL

**Pull request merged**
