### PR TITLE
set Http2 max outbound stream to connectionPool settings.Http2MaxRequests

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Currently in istio we use Http2MaxRequests to limit the circuit breaker threshold., which means max number of parallel requests envoy makes to upstream cluster.

### CODE REVIEW

**Review by ramaraochavali — COMMENTED** [review]
This does not solve the problem. We will have to set at HCM at inbound listener as well otherwise HCM level flow control breaks

**Comment by hzxuzhonghu** [comment]
We couldn't set inbound like timeout, because inbound could be shared by multi service

**Comment by hzxuzhonghu** [comment]
FYI https://github.com/istio/istio/issues/40619#issuecomment-1227206403

**Comment by ramaraochavali** [comment]
Sorry I meant outbound. Otherwise the flow control between client (downstream client) and Envoy (HCM) breaks before it sends to upstream cluster.

**Comment by hzxuzhonghu** [comment]
Really similar as idle timeout

**Comment by ramaraochavali** [comment]
> Really similar as idle timeout

Yes

**Comment by ramaraochavali** [comment]
Thinking about this more, I think we should not do this as it can add more confusion and the solution is only partial.

**Comment by hzxuzhonghu** [comment]
I also think this is not a complete solution, this is to prove that purely adding a field in DR does not solve anything

**Comment by ramaraochavali** [comment]
I will think about it and come up with a better proposal to address this.

**Pull request closed without merging**
