### PR TITLE
[WIP] Add gRPC healthcheck service at SDS server and ensure SDS server is ready during bootstrap

### PR DESCRIPTION
**Pull request by JimmyCYJ**
fixes: https://github.com/istio/istio/issues/22443

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
cc @myidpt @howardjohn Please take a look and let me know if this is the right approach. Thanks.

**Comment by howardjohn** [comment]
@JimmyCYJ I think you mentioned you added a sleep somewhere and reproduced the problem? Where was that?  I tried adding sleep to https://github.com/istio/istio/blob/0026a93bc914056c69dd0fa3573651f041a406e1/security/pkg/nodeagent/sds/server.go#L259, and after 10s delay the connections are fine

**Comment by howardjohn** [comment]
@JimmyCYJ can you let me know how you reproduced this? I would like to verify this and try out alternative idea. I think this solution is very heavyweight so if we can do something lighter it would be prefered

**Comment by JimmyCYJ** [comment]
@howardjohn I could not reproduce it by adding a sleep before starting workload SDS server either.
I have added 10 seconds sleep and tried to reproduce using both the local integration test and deploying Istio in my GKE cluster. Originally I added a much longer sleep and didn't check if the SDS channel is back to live after the sleep. During the sleep, the symptom looks similar. 

Please feel free to try alternative ideas.

**Comment by howardjohn** [comment]
@JimmyCYJ if a sleep does not reproduce the problem, then this indicates to me that we have miss-diagnosed the problem, and that this won't fix it. Why do you think this is the problem if a sleep does not reproduce?

**Comment by howardjohn** [comment]
Because originally we said the issue was envoy starts before we listen on the UDS socket, but if we add a sleep we force this to happen and there are no issues?

**Comment by JimmyCYJ** [comment]
I think the issue is with the UDS socket, we can add more logs in bootstrap and find out other approaches that can reproduce the issues. Closing this PR now.

**Comment by myidpt** [comment]
Thanks for digging into this, Jimmy.

**Pull request closed without merging**
