### PR TITLE
skip empty value for reverse translation to k8s settings.

### LINKED ISSUE #29944: Using `istioctl profile dump` with config generated from `istioctl profile dump` changes values
**Bug description**

Using `istioctl profile dump` with config generated from `istioctl profile dump` changes values.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

If I generate config with the CLI tool, it should be respected if I pass it to the same tool.

**Steps to reproduce the bug**

```
#!/bin/bash

# make a new temporary directory with some sample yaml
pushd $(mktemp -d)
cat <<EOF >operator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  components:
    pilot:
      k8s:
        env:
        - name: SPIFFE_BUNDLE_ENDPOINTS
          value: "SPIFFE_BUNDLE_ENDPOINT"
EOF

# use the current 1.8 release
curl -L https://github.com/istio/istio/releases/download/1.8.1/istio-1.8.1-linux-amd64.tar.gz | tar xz

# generate config from the sample yaml above
./istio-1.8.1/bin/istioctl profile dump -f operator.yaml > ./profile_dump.yaml

# generate config from generated config
./istio-1.8.1/bin/istioctl profile dump -f profile_dump.yaml > ./second_profile_dump.yaml

# they're not the same config
diff profile_dump.yaml second_profile_dump.yaml
```

This generates

```
108,110c108,109
<         env:
<         - name: SPIFFE_BUNDLE_ENDPOINTS
<           value: SPIFFE_BUNDLE_ENDPOINT
---
>         env: []
>         nodeSelector: {}
117a117
>         replicaCount: 1
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.1 release

**How was Istio installed?**
n/a

**Environment where the bug was observed (cloud vendor, OS, etc)**
Linux (Debian)

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/29944

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Can you add a test covering this?

**Review by richardwxn — APPROVED** [review]
lgtm, feel free to remove the hold once test added

**Pull request merged**
