### PR TITLE
istioctl ztunnel: add connections command

### PR DESCRIPTION
**Pull request by howardjohn**
Depends on https://github.com/istio/ztunnel/pull/939

Ultimately this enables istioctl to give us:

```
WORKLOAD                                      DIRECTION LOCAL                                              REMOTE                                             REMOTE TARGET
cartservice-bffc98bf4-bmqsg.anthos            Inbound   cartservice-bffc98bf4-bmqsg.anthos:7070            checkoutservice-c58746cd5-prxg9.anthos:41903
cartservice-bffc98bf4-bmqsg.anthos            Inbound   cartservice-bffc98bf4-bmqsg.anthos:7070            frontend-86c4744d65-f6xwb.anthos:50955
cartservice-bffc98bf4-bmqsg.anthos            Outbound  cartservice-bffc98bf4-bmqsg.anthos:50320           redis-cart-7ff8f4d6ff-lmlwg.anthos:6379            redis-cart.anthos.svc.cluster.local:6379
cartservice-bffc98bf4-bmqsg.anthos            Outbound  cartservice-bffc98bf4-bmqsg.anthos:50330           redis-cart-7ff8f4d6ff-lmlwg.anthos:6379            redis-cart.anthos.svc.cluster.local:6379
productcatalogservice-64898b8c5f-pqx6h.anthos Inbound   productcatalogservice-64898b8c5f-pqx6h.anthos:3550 recommendationservice-85846457-79l2f.anthos:58205
productcatalogservice-64898b8c5f-pqx6h.anthos Inbound   productcatalogservice-64898b8c5f-pqx6h.anthos:3550 checkoutservice-c58746cd5-prxg9.anthos:46941
productcatalogservice-64898b8c5f-pqx6h.anthos Inbound   productcatalogservice-64898b8c5f-pqx6h.anthos:3550 frontend-86c4744d65-f6xwb.anthos:39685
frontend-86c4744d65-f6xwb.anthos              Inbound   frontend-86c4744d65-f6xwb.anthos:8080              loadgenerator-866ccfdfc9-9mhz7.anthos:48071
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:44436             checkoutservice-c58746cd5-prxg9.anthos:5050        checkoutservice.anthos.svc.cluster.local:5050
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:40386             cartservice-bffc98bf4-bmqsg.anthos:7070            cartservice.anthos.svc.cluster.local:7070
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:50976             productcatalogservice-64898b8c5f-pqx6h.anthos:3550 productcatalogservice.anthos.svc.cluster.local:3550
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:37700             recommendationservice-85846457-79l2f.anthos:8080   recommendationservice.anthos.svc.cluster.local:8080
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:40528             adservice-684fbd8977-r6vsh.anthos:9555             adservice.anthos.svc.cluster.local:9555
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:41618             shippingservice-77d6cdd487-v4fj6.anthos:50051      shippingservice.anthos.svc.cluster.local:50051
frontend-86c4744d65-f6xwb.anthos              Outbound  frontend-86c4744d65-f6xwb.anthos:48212             currencyservice-5495597f5-nwnd5.anthos:7000        currencyservice.anthos.svc.cluster.local:7000
emailservice-d74c4c797-xpkp2.anthos           Inbound   emailservice-d74c4c797-xpkp2.anthos:8080           checkoutservice-c58746cd5-prxg9.anthos:54561
recommendationservice-85846457-79l2f.anthos   Inbound   recommendationservice-85846457-79l2f.anthos:8080   frontend-86c4744d65-f6xwb.anthos:54843
recommendationservice-85846457-79l2f.anthos   Outbound  recommendationservice-85846457-79l2f.anthos:36164  productcatalogservice-64898b8c5f-pqx6h.anthos:3550 productcatalogservice.anthos.svc.cluster.local:3550
checkoutservice-c58746cd5-prxg9.anthos        Inbound   checkoutservice-c58746cd5-prxg9.anthos:5050        frontend-86c4744d65-f6xwb.anthos:40593
checkoutservice-c58746cd5-prxg9.anthos        Outbound  checkoutservice-c58746cd5-prxg9.anthos:39576       cartservice-bffc98bf4-bmqsg.anthos:7070            cartservice.anthos.svc.cluster.local:7070
checkoutservice-c58746cd5-prxg9.anthos        Outbound  checkoutservice-c58746cd5-prxg9.anthos:59008       emailservice-d74c4c797-xpkp2.anthos:8080           emailservice.anthos.svc.cluster.local:5000
checkoutservice-c58746cd5-prxg9.anthos        Outbound  checkoutservice-c58746cd5-prxg9.anthos:56736       currencyservice-5495597f5-nwnd5.anthos:7000        currencyservice.anthos.svc.cluster.local:7000
checkoutservice-c58746cd5-prxg9.anthos        Outbound  checkoutservice-c58746cd5-prxg9.anthos:57080       productcatalogservice-64898b8c5f-pqx6h.anthos:3550 productcatalogservice.anthos.svc.cluster.local:3550
checkoutservice-c58746cd5-prxg9.anthos        Outbound  checkoutservice-c58746cd5-prxg9.anthos:41766       paymentservice-5dd485cf9c-ks47b.anthos:50051       paymentservice.anthos.svc.cluster.local:50051
checkoutservice-c58746cd5-prxg9.anthos        Outbound  checkoutservice-c58746cd5-prxg9.anthos:39090       shippingservice-77d6cdd487-v4fj6.anthos:50051      shippingservice.anthos.svc.cluster.local:50051
redis-cart-7ff8f4d6ff-lmlwg.anthos            Inbound   redis-cart-7ff8f4d6ff-lmlwg.anthos:6379            cartservice-bffc98bf4-bmqsg.anthos:41363
currencyservice-5495597f5-nwnd5.anthos        Inbound   currencyservice-5495597f5-nwnd5.anthos:7000        frontend-86c4744d65-f6xwb.anthos:43913
currencyservice-5495597f5-nwnd5.anthos        Inbound   currencyservice-5495597f5-nwnd5.anthos:7000        checkoutservice-c58746cd5-prxg9.anthos:41455
adservice-684fbd8977-r6vsh.anthos             Inbound   adservice-684fbd8977-r6vsh.anthos:9555             frontend-86c4744d65-f6xwb.anthos:59253
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60636        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60638        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60586        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:40164        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:40178        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60628        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60594        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60608        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60612        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
loadgenerator-866ccfdfc9-9mhz7.anthos         Outbound  loadgenerator-866ccfdfc9-9mhz7.anthos:60630        frontend-86c4744d65-f6xwb.anthos:8080              frontend.anthos.svc.cluster.local:80
paymentservice-5dd485cf9c-ks47b.anthos        Inbound   paymentservice-5dd485cf9c-ks47b.anthos:50051       checkoutservice-c58746cd5-prxg9.anthos:41735
shippingservice-77d6cdd487-v4fj6.anthos       Inbound   shippingservice-77d6cdd487-v4fj6.anthos:50051      checkoutservice-c58746cd5-prxg9.anthos:35323
shippingservice-77d6cdd487-v4fj6.anthos       Inbound   shippingservice-77d6cdd487-v4fj6.anthos:50051      frontend-86c4744d65-f6xwb.anthos:51271
```

Or waypoints:
```
WORKLOAD                       DIRECTION LOCAL                                REMOTE                                  REMOTE TARGET
echo-66d88ff694-tf8bm.default  Inbound   echo-66d88ff694-tf8bm.default:80     waypoint-654dccf598-229fx.default:50712
shell-56bd5dbdbf-24v42.default Outbound  shell-56bd5dbdbf-24v42.default:46034 waypoint-654dccf598-229fx.default:15008 echo.default.svc.cluster.local:80
```

### CODE REVIEW

**Review by bleggett — APPROVED** [review]

**Review by hanxiaop — COMMENTED** [review]
The output looks good; needs some tests before the merge.

**Comment by costinm** [comment]
On Fri, Apr 19, 2024 at 7:37 AM John Howard ***@***.***>
wrote:

> Change is very useful, approve - but I'm concerned with few things ( that
> are already problems - not new in this PR).
>
>    1. A lot of what started as 'internal debug' code has become 'feature'
>    with expectation of stability. Yet it was never reviewed or designed as
>    such - just json
>    encoding slapped on internal structures. This is another path (along
>    with 'experimental' env variables and annotations and MeshConfig) on adding
>    a huge
>    API surface with no versioning or API review.
>
> This is explicitly under istioctl experimental to designate its
> unstability. Do you have suggestions on how we can do things better?
>

Of course - everything is under experimental and becomes v1 since it can't
be changed after :-)
As long as production users are allowed to use it ( and we have to because
otherwise we can't get feedback ) - we can do things
better by having a design, consider security/scalability ( is cardinality
too high to just use metrics?, does it need chunking ? Streaming ? ),
and not play more games with experimental ( not specific to this PR, of
course ).




>
>    2. More important, we seem to continue down the path of expecting
>    tooling to do
>    kubectl exec - which also happened mostly accidentally and pretty sure
>    without security reviews. Too late to do much about Istio v1, but in
>    ztunnel we should take some time and fix this ( not now - but before we are
>    stuck ). An endpoint with auth would work for example - and may be extended
>    to allow namespace owners to see only their own data for example. A metrics
>    endpoint may work too - not sure why we don't expose stats about all
>    connections already, is it because of size ?
>
> This does not require exec, nor does any (IIRC - there might be some
> obscure one I have missed) istioctl command anymore.
>
Confused - isn't this a command in ztunnel ? How does it get run ?



>
>    3. For a lot of debug stuff we are using 'over XDS' - I wonder if we
>    want to do this for ztunnel ( and waypoints ) too - with Istiod acting as a
>    dispatcher and doing access control / filtering.
>
> I don't see any benefit to doing this. Maybe I don't understand it.
>

The benefit is that a ztunnel may have a lot of connections - and a
streaming model where you don't have to poll sending the entire set
may be more efficient for tools. Using the metrics infra ( delta ) would
also achieve that.


>
>    4. For alternative L4 implementations - do we want to set any
>    (optional) expectations for reporting this ?
>
> I would imagine alternative implementations have alternative debugging
> tools. If they take inspiration from the 1P one, great... but its pretty
> standard for different implementations to have different debugging.
>
If it's only debugging - i.e. not allowed in prod, since
security/scalability/general design are missing - I agree. But that's not
what we've been
doing.

If it's something we want in production - including for operations, etc -
defining some protocol ( like we did for WDS, or like semantic conventions
if we can expose this as metrics) may be useful.

I don't believe this feature is 'debugging only' - seems pretty important
for operations.

**Comment by costinm** [comment]
An option would be to only include this in the debug builds - while release
builds can have the 'debug' features disabled ? My real concern is to stop
things that don't have security/scale/api/protocol review from becoming
'production' via backdoor, at least in ambient/Gateway world.

**Comment by costinm** [comment]
So the security model is "allow port forward RBAC" - and ztunnel doesn't
have any admin port like envoy, and all info exposed this way is not
sensitive ? And no way a port forward could be used to forward or originate
requests that would appear to be from (trusted) ztunnel ?

I'm not saying the feature is bad - I think it is super useful to have
visibility into active connections, not only for debug.
My concern is that we follow the same exact pattern we did for Istiod and
istio v1 - implement 'debug' or 'experimental' features
without considering the security implications or what would be the right
design, and 6 month later they are either 'feature that
 everyone uses and can no longer be changed' or CVEs.

With sidecars - there was the 'owner' or namespace level access that
provided some protection, for ztunnel - am I the only
one that doesn't understand the security model for debug tools ?

**Comment by hzxuzhonghu** [comment]
If the remote is waypoint, will it shows it or the actual workload?

**Pull request merged**
