### PR TITLE
[release-1.23] `istio-cni` - stop writing `kubeconfig` to shared CNI netdir (#52323)

### PR DESCRIPTION
**Pull request by bleggett**
Manual backport of #52323, fixes https://github.com/istio/istio/issues/52470

This DOES need a 1.23 backport, because 1.23 will be broken without it

- https://github.com/istio/istio/pull/52173 introduced a bug this fixes properly.
- Somehow it seems the revert  of the above @fjglira did here https://github.com/istio/istio/pull/52276 did _not_ get cherried to 1.23 by the automator, AFAICT (despite being labeled for it).

So might as well backport the whole fix.

### CODE REVIEW

**Comment by thedebugger** [comment]
Discussed w/ Ben on slack. We are holding off the fix since we are close to code freeze. Instead we will cherry pick the [revert](https://github.com/istio/istio/pull/52276)

**Comment by bleggett** [comment]
@thedebugger https://github.com/istio/istio/pull/52499 - ty!

**Comment by mikemorris** [comment]
Closing as the cherry-picked revert in #52499 has been merged

**Comment by bleggett** [comment]
@mikemorris I do intend to backport this  post-freeze, can we reopen this and just leave it?

**Comment by mikemorris** [comment]
Sure, sounds good!

**Review by thedebugger — APPROVED** [review]

**Pull request merged**
