### PR TITLE
Adds support for envoy filter for grpc proxyless

### PR DESCRIPTION
**Pull request by anuragagarwal561994**
Closes https://github.com/istio/istio/issues/47927

### CODE REVIEW

**Comment by howardjohn** [comment]
I am a bit concerned with this. In general, there has been a lot of effort around the project about reducing and removing use cases for EnvoyFilter.

To add a huge new usage seems controversial at least.

cc @keithmattix @kyessenov @whitneygriffith

**Comment by kyessenov** [comment]
Please don't add EnvoyFilter to gRPC. The extensibility use cases from EnvoyFilter do not work on gRPC since they have different extensions. So you're mostly likely looking at the core xDS (LB?) and that deserves a first class API.

**Comment by anuragagarwal561994** [comment]
@howardjohn @kyessenov we did a long discussion over https://github.com/istio/istio/issues/47927 for the usecase and the idea of why it is controversial but needed for some usecase.

I am okay to not add EnvoyFilter for grpc proxyless scenarios, although that would require us to add few proper support for grpc proxyless in istio.

As of now, our team needs to experiment and use the outlier_detection functionality. What would you suggest, should I instead go about adding it properly as part of the destination rule and contribute further for any other appearing use cases. 

The issue which I wanted to avoid is that there are going to few more experiments on different features we may have to do with grpc proxyless support and istio, but upgrading istio in production infra everytime doesn't make sense because it may impact all the associated services and hence thought EnvoyFilter as an alternative for now and later can be implemented as a feature from DestinationRule.

Also as you mention that extensibility use-cases doesn't work with grpc-xds, I am not 100% sure will it be possible for you to share some examples, because grpc-xds is compliant with `go-control-plane` and Envoy API as far as I understand there should be no issues, the grpc clients and servers will itself handle what they want to read and avoid.

**Comment by kyessenov** [comment]
I don't think EnvoyFilter will help you in terms of production stability. It'll help you get something working but when it comes to upgrades or support, it's by far the worst option. gRPC shares xDS with Envoy for the core data plane APIs, and it's not fully complete. Are you saying some core Envoy xDS is not applying to gRPC? There's probably some deeper issue going on if a core xDS API behaves differently on gRPC vs Envoy. Patching it up for gRPC is a band-aid solution.

**Comment by keithmattix** [comment]
-1 on increasing surface area of EnvoyFilter; it's giant as it is.

> hence thought EnvoyFilter as an alternative for now and **later can be implemented as a feature from DestinationRule.**

(emphasis mine) Why not start here? Is the underlying grpc outlier detection incompatible with DestinationRule? Some other reason?

**Comment by anuragagarwal561994** [comment]
@kyessenov no I think you have understood the problem incorrectly here.

So grpc-xds understands core Envoy XDS APIs

Envoy proxy understands core Envoy XDS APIs

Istio acts as a control plane here makes it easier for the user to create kubernetes resources like DestinationRule / VirtualService and it translates it to Envoy XDS API format which is then forwarded to the respective proxy to consume.

But there comes a limitation here for the cases where istio doesn't have the translations implemented, to get that configuration working one has to use EnvoyFilter.

Taking an example here:
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#failure-percentage

This is one of the outlier detection algorithms which is not part of istio
https://istio.io/latest/docs/reference/config/networking/destination-rule/#OutlierDetection

The comment in a similar issue suggests to use an EnvoyFilter for this use case:
https://github.com/istio/istio/issues/40785#issuecomment-1236047788

Although there are alternative algorithms that istio supports for Envoy which can at least do some good in production traffic. But for `grpc-xds` proxyless setup the only supported alorithms https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md#xds-integration include: 
* Success Rate
* Failure Percentage

Istio on translates:
* Traffic LB Policy
* Subsets

from the DestinationRule for grpc-proxyless usecase.

https://github.com/istio/istio/blob/d4d1475976444f1c5ddbb21d5ef0073c5dc9a7ff/pilot/pkg/networking/grpcgen/cds.go#L153C1-L166C2

The remain configurations like outlier detection, circuit breaker etc. are currently not implemented properly and hence not forwarded to the grpc clients and grpc client doesn't get the configured outlier detection information.

So there are 2 approaches: 

Proper Way:
* Implement success rate and failure percentage in destination rule
* Implement validating and forwarding outlier detection configurations for grpc-proxyless from FR
* Implement enovy support for success rate and failure percentage

I can implement it this way and contribute to the repo as well, if that is desired but this will solve just one problem. Both grpc-xds and istio are developing at rapid phase and have their own unrelated development lifecycle.

Simpler / Extensible Way:
* Add EnvoyFilter for patching what istio doesn't understand for `grpc-proxyless`

This is something which is not encouraged in general but will unblock the users of the setup unitl proper support is being catching up and the responsibility of what applies is left for the user to configure properly.

I hope I am able to clearly state the problem statemenet and the solution suggested, did a lot of research last week to understand this whole web of interelated changes #:smile: 

Let me know if there are still some gaps left or any suggestions.

**Comment by kyessenov** [comment]
> I can implement it this way and contribute to the repo as well, if that is desired but this will solve just one problem. Both grpc-xds and istio are developing at rapid pace and have their own unrelated development lifecycle.

Their development is very much coordinated since xDS additions are coordinated with Envoy, and Istio as well since it is a consumer of Envoy. The root of the problem is that there are varying levels of capabilities between Envoy and gRPC, and some xDS algorithms work on one but not the other. My claim is that it's unlikely to be intentional, and there was some discussion in the past to bring them on parity. If you want some feature from xDS that's only implemented on gRPC we have to expose it in Istio as a first-class API, since it must support the super-set of both Envoy and gRPC. Separately, we should investigate why Envoy didn't implement it, and we can potentially gate some Istio API additions based on the client capabilities.

**Comment by anuragagarwal561994** [comment]
So what I mean by development coordination here is not between the xDS API and Envoy, but between `grpc-xds` https://grpc.github.io/grpc/core/md_doc_grpc_xds_features.html and Envoy.

With respect to the disparity between the two, actually these are 2 different implementations and `grpc-xds` can choose which features to implement which not because on one hand, envoy can act as gateways, sidecars and provide much wider capabilities, grpc-xds is mostly used for inter service communication and may limit some of the algorithms because they may either not fit the usecase or might not have higher user traction.

`grpc-xds` need not comply with everything xDS API provides but as far as I understands, it will keep all of its features under the umbrella of the standard xDS API (which means lesser scope of extensions and moving away from standards).

The outlier detection algorithms I am talking about are actually implemented in Envoy as well, it is just not implemented in Istio currently.

**Comment by kyessenov** [comment]
> The outlier detection algorithms I am talking about is actually implemented in Envoy as well, it is just not implemented in Istio currently.

Let's just add them to Istio then, and it'll work on both?

**Comment by anuragagarwal561994** [comment]
@kyessenov sure let me open a new issue and start working on the same, will need some help since this is my first time contributing to istio. Thanks for discussion

**Pull request closed without merging**
