### PR TITLE
iptable just "return" by uid as the parameter u indicates

### PR DESCRIPTION
**Pull request by rokii**
resolve this https://github.com/istio/istio/issues/6557

### CODE REVIEW

**Comment by hklai** [comment]
@nmittler should be a better person to review this.

**Comment by nmittler** [comment]
@costinm should take a look as well

**Comment by nmittler** [comment]
@costinm I'm not sure the original intent of matching on the group.  Is this something that we can safely remove?

**Comment by rokii** [comment]
If group has to be an option,it is better to provide   -g param separately

**Pull request merged**
