### PR TITLE
Added nodeagent to requirements.yaml.

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @wattli @quanjielin 

This is a follow up PR for https://github.com/istio/istio/pull/7875

### CODE REVIEW

**Comment by quanjielin** [comment]
thanks ! btw https://github.com/istio/istio/pull/7875 was made in ```collab-gcp-identity```; also just curious, is there any side effect without updating this yaml file ?

**Comment by gyliu513** [comment]
@quanjielin this is an optional file and mainly used to define the dependency, and it will not impact your previous PR, please refer to https://github.com/helm/helm/blob/master/docs/charts.md for detail.

**Comment by quanjielin** [comment]
thanks, I think this PR needs to be checked into collab-gcp-identity branch ?

**Comment by gyliu513** [comment]
Thanks @quanjielin , a new PR at https://github.com/istio/istio/pull/7895

**Pull request closed without merging**
