### PR TITLE
Remove CircleCI gates for aggregated integration tests.

### PR DESCRIPTION
**Pull request by ozevren**

### CODE REVIEW

**Comment by howardjohn** [comment]
Just to clarify: is the end goal to have everything split, and running only on prow not circleci?
So prow/istio-integ-k8s-tests.sh  will go away in the future as well?

**Comment by ozevren** [comment]
> Just to clarify: is the end goal to have everything split, and running only on prow not circleci?
> So prow/istio-integ-k8s-tests.sh will go away in the future as well?

Yes, maybe, yes. 

The intent was to have a similar setup to e2e tests all along. Having a single gate made development easier. It is now time to split things up. Once the gates are gone, there is no need keep the shell scripts.

Prow v.s. CircleCI is a separate discussion. I picked Prow v.s. CircleCI as CI only has minikube, and we also had resourcing problems before (which seems to be happening now as well).

Whatever the "right" CI system, we should settle on it and run the tests  on that. Until then Prow seems to be the better choice.

**Comment by costinm** [comment]
Note that there is an effort to switch Prow to a new version, which will
require migrating all tests - including
migration to Kind.

Both Minikube mode in Circle and the current Boskos in Prow should be
replaced by KIND, and
MUST run locally (using a standard make test).

We are likely going to replace CircleCI as well at some point - but Prow is
likely to be the first
to be revamped, and either way - it'll go to Kind-based testing that can be
reproduced locally.

If any test can't run in Kind or can't run locally - please file a bug and
make sure everyone
is aware of it.

Also please make sure any new test you review is using the new installer....

**Comment by costinm** [comment]
Also the current agreement is that we want all possible tests to run:
- locally
- in whatever 'official' CI we'll have - current candidates are the new
Prow or BuildKite
- in any other CI that community or orgs maintains and is compatible with
Kind.

The gates should be only on the 'official' CI - but the tests must run in
all supported CIs.

The only exception for now are tests that can't be converted to Kind ( and
of course the
stability/perf tests ).

**Comment by ozevren** [comment]
Can you explain why you're putting hold?

**Comment by howardjohn** [comment]
@costinm I understand what you said but don't see how it relates to not mreging in this PR. We had a monolithic integration test target that we split into multiple smaller targets. This PR just deletes the old monolithic target

**Comment by ozevren** [comment]
> Note that there is an effort to switch Prow to a new version, which will require migrating all tests - including migration to Kind. Both Minikube mode in Circle and the current Boskos in Prow should be replaced by KIND, and MUST run locally (using a standard make test). We are likely going to replace CircleCI as well at some point - but Prow is likely to be the first to be revamped, and either way - it'll go to Kind-based testing that can be reproduced locally. If any test can't run in Kind or can't run locally - please file a bug and make sure everyone is aware of it. Also please make sure any new test you review is using the new installer....

First, this is just a final PR in a series of PRs for splitting a monolithic gate into multiple gates, and removing the monolithic gate. 

Also, the tests already run using standard "make test". There is nothing here that is Prow specific, *except* for integration glue that is needed to run on Prow. 

Re: New Installer: I don't have the bandwidth to do the migration of the test framework to the new installer model. Given the framework is meant to be a common dev-owned component, I expect people working on the installer to pitch in and implement the necessary things as appropriate, given they have the best domain knowledge to do so.

**Comment by hzxuzhonghu** [comment]
@ozevren 
Is this error related?
```
Build-agent version 1.0.11043-90328079 (2019-05-08T08:08:06+0000)
Configuration errors: 1 error occurred:

* Cannot find a job named `test-integration-local` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
```

```
Build-agent version 1.0.11043-90328079 (2019-05-08T08:08:06+0000)
Configuration errors: 1 error occurred:

* Cannot find a job named `test-integration-kubernetes` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
```

**Pull request merged**
