### PR TITLE
Cherry-pick pull/32970 to release-1.8 (#32970)

### PR DESCRIPTION
**Pull request by sergii-ssh**
* Replace eastwest with ingress gateway

* Patch replace eastwest with ingress gateway

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
/ok-to-test

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
