### PR TITLE
Use platform profile for GKE as well, and drop the K8S version detect

### LINKED ISSUE #39534: CNI chart GKE check using deprecated Helm .Capabilities.KubeVersion.GitVersion object
### Bug Description

In this PR https://github.com/istio/istio/pull/37872 the check for using HPA v2 was updated to:

```
{{- if (semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion)}}
```

The `GitVersion` parameter is part of Helm2 built-in objects (https://v2.helm.sh/docs/chart_template_guide/#built-in-objects) and no longer supported in Helm3 (https://helm.sh/docs/chart_template_guide/builtin_objects/). The check should be rewritten to use `KubeVersion.Minor` instead.

### Version

```prose
Chart versions 1.14.1

helm version --short                                                                   │
v3.8.2+g6e3701e
```

### Additional Information

See also https://pkg.go.dev/helm.sh/helm/v3/pkg/chartutil#KubeVersion.GitVersion

Workflows using helm template or kustomize with helmChartInflationGenerator will be hit by this since only KubeVersion can be specified to the template operation.

### PR DESCRIPTION
**Pull request by bleggett**
**Please provide a description of this PR:**

Fixes: https://github.com/istio/istio/issues/39534

and closes out: https://github.com/istio/istio/issues/51121

Since we have had platform profiles for some time and people generally are OK with them, this removes the (one) instance of K8S version autodetection we were doing in the `istio-cni` chart and just creates a platform profile for GKE like the others we already have for other platforms.

3 problems with autodetection in the Helm template:

1. It's fragile
2. It's not obvious/discoverable
3. It doesn't work if you template the charts ahead-of-time and install them with a different tool(Argo, kubectl) unless you use the correct option flag when templating (`--current-cluster` for istioctl/`--kube-version` for helm)

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
I am fine to have the `platform` but I don't want to remove the auto setting. It seems strictly a regression for users.

There are a few cases:

1. `helm install` / `istioctl install`. Before it detects, now it does not. **regression**
2. `helm template` / `manifest generate`. Before/after it does not detect **no change**
3. `helm template --kube-version` / `manifest generate --cluster-specific` and install to the same cluster. Before it detects, now it does not. **regression**
4. `helm template --kube-version` / `manifest generate --cluster-specific` and install to a different cluster. Before it detects incorrectly, now it does. *Technically* this is an improvement, but this is not a valid installation pattern. I have never ever heard of someone making this mistake (especially with `--cluster-specific`, you have to try pretty hard to mess up here).

So overall I think we are going to harm GKE users by this change

**Comment by bleggett** [comment]
> I am fine to have the `platform` but I don't want to remove the auto setting.

Okay, fair enough. I'll put it back in and indicate that the preferred approach is to use the platform profile (generally, since we often need to override other things at the platform level we cannot easily autodetect inline)

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
> Okay, fair enough. I'll put it back in and indicate that the preferred approach is to use the platform profile (generally, since we often need to override other things at the platform level we cannot easily autodetect inline)

should we just detect the platform instead of detecting the cniBinDir? 

Not a functional change just might be more clean, I don't have a strong preference; it may be slightly more complex

**Comment by bleggett** [comment]
> > Okay, fair enough. I'll put it back in and indicate that the preferred approach is to use the platform profile (generally, since we often need to override other things at the platform level we cannot easily autodetect inline)
> 
> should we just detect the platform instead of detecting the cniBinDir?
> 
> Not a functional change just might be more clean, I don't have a strong preference; it may be slightly more complex

if you mean autodetecting and autoapplying the `gke` platform profile if we get `gke` in the K8S GitVersion, I'd rather not (not because it wouldn't work, but because I don't want to encourage that as a pattern, and there are pathologies/corner cases to individual charts self-overriding wholesale like that).

I do think `istioctl` probably should have platform detection + pick the right profile for all charts, that's a good value add for it and it's better equipped to make that decision across all charts anyway.

**Comment by bleggett** [comment]
(opened https://github.com/istio/istio/issues/51121 since we had already mentioned that as a possibility anyway)

**Pull request merged**
