### PR TITLE
Update bookinfo

### PR DESCRIPTION
**Pull request by howardjohn**
This updates bookinfo. I thought it would be easy but the python ecosystem is.. interesting, and it felt easier to switch to OTEL than make it work with deprecated packages.

Once this PR is approved, I will push to the real repos and update the yamls

Fixes https://github.com/istio/istio/issues/49205

### CODE REVIEW

**Comment by zirain** [comment]
> This updates bookinfo. I thought it would be easy but the python ecosystem is.. interesting, and it felt easier to switch to OTEL than make it work with deprecated packages.
> 
> Once this PR is approved, I will push to the real repos and update the yamls
> 
> Fixes #49205

Just want to know, which images(except bookinfo and distroless) are to be manually built and pushed, who can do that?

**Comment by howardjohn** [comment]
> > This updates bookinfo. I thought it would be easy but the python ecosystem is.. interesting, and it felt easier to switch to OTEL than make it work with deprecated packages.
> > Once this PR is approved, I will push to the real repos and update the yamls
> > Fixes #49205
> 
> Just want to know, which images(except bookinfo and distroless) are to be manually built and pushed, who can do that?

Only frank I can. It's everything under samples/book info/platform

**Comment by zirain** [comment]
> > > This updates bookinfo. I thought it would be easy but the python ecosystem is.. interesting, and it felt easier to switch to OTEL than make it work with deprecated packages.
> > > Once this PR is approved, I will push to the real repos and update the yamls
> > > Fixes #49205
> > 
> > 
> > Just want to know, which images(except bookinfo and distroless) are to be manually built and pushed, who can do that?
> 
> Only frank I can. It's everything under samples/book info/platform

does [header_injector](https://github.com/istio/istio/blob/c34ccc8963ad9cae80e884f54505a29d94827834/samples/wasm_modules/header_injector) build/push manually?

**Comment by zirain** [comment]
> > does [header_injector](https://github.com/istio/istio/blob/c34ccc8963ad9cae80e884f54505a29d94827834/samples/wasm_modules/header_injector) build/push manually?
> 
> Bookinfo is done manually by https://github.com/istio/istio/blob/master/samples/bookinfo/src/build-services.sh. Looks like header_injector has its own makefile that can be run manually.

and push manually

**Comment by howardjohn** [comment]
@ericvn lmk if this looks good and I will build+push+update the pr

**Comment by ericvn** [comment]
@howardjohn Sorry it took so long to verify things. Not everything went smoothly, but I was able to build, and run bookinfo with the new-images and verify things worked OK. I think this is good to go.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
