### PR TITLE
clean up gateways not used

### PR DESCRIPTION
**Pull request by DreamRivulet**
clean up gateways not used in bookinfo sample.

### CODE REVIEW

**Comment by DreamRivulet** [comment]
I don't think the test failure was caused by by my change, any way to rerun the test ?

**Comment by idouba** [comment]
The following error seems have nothing to do with this commit.
Creating vendor diff03:22
```
Exit code: 2
#!/bin/bash -eo pipefail
make depend.diff ISTIO_OUT=/go/out
go get -u github.com/golang/dep/cmd/dep
dep ensure
git diff HEAD --exit-code -- Gopkg.lock vendor > /go/out/dep.diff
Makefile:245: recipe for target 'depend.diff' failed
make: *** [depend.diff] Error 1
Exited with code 2
```

**Comment by frankbu** [comment]
@DreamRivulet your PR is for the wrong branch ... it needs to be for the release-0.1 branch

**Comment by frankbu** [comment]
I mean release-1.0 branch

**Comment by DreamRivulet** [comment]
oh, i thought it should go to the master branch...
I will move it to the release-1.0  branch, thanks for your help.
BTW:  why the PR should go to the release branch instead of master ?

**Comment by frankbu** [comment]
Thanks @DreamRivulet. Changes that are targetted for 1.0 need to go into the release-1.0 branch and they will be merged into master later. Only post-1.0 future work should go to master now.

**Pull request closed without merging**
