### PR TITLE
Fix #2389 add missing jinja files to install folder

### LINKED ISSUE #2389: `install` folder in releases contains only part of the files
When I download an istio release, I expect the `install` folder to contain all the files required to install istio on a given platform. Up until `0.4.0`, only part of the files are packaged.

For eg. the `install/gcp` should contain the GCP deployment manager scripts to deploy a k8s cluster with istio pre-installed. Those scripts are in the codebase but some are missing from the release packages. 

It seems that only `yaml` and `markdown` files are included.

### PR DESCRIPTION
**Pull request by dgageot**
This includes all the files but `BUILD` files in `install` folder when creating the release packages.

### CODE REVIEW

**Comment by rshriram** [comment]
This would add the template files as well, which we do not want.

**Comment by dgageot** [comment]
@rshriram Oh yes, I see the templates now. I was so focused on the `install/gcp` where there qre no template that I missed them. I'll fix the PR tomorrow.

**Comment by mattdelco** [comment]
It seems like it'd be more conservative to basically add "install/gcp" to the existing find for "install/tools".   The other option is to place gcp/ under tools/ but I don't have a good sense of the mindset behind the install/ directory layout to know which (if any) is more appropriate.

**Comment by dgageot** [comment]
@mattdelco `gcp/` folder is not the only folder impacted. There are files missing from other folders. I pushed a new version that filters the templates out. wdyt?

**Comment by mattdelco** [comment]
It's help to mention what else was missing.  The only thing I spotted was generate-webhook-cert.sh .  A problem with excluding */templates/* is that there's 4 different "templates" directories under install/kubernetes/helm that apparently need to be shipped (I haven't ever installed nor used istio so I'm just stating based based on it being previously shipped). Offhand possible options would be to use "*/kubernetes/templates/*", or move generate-webhook-cert.sh under tools/, or whitelist *.sh (the last would probably require filtering out updateVersion.sh, either by a separate delete or just ignore the issue for now with the expectation that the file will get removed within a month or two when its replacement arrives).

**Comment by dgageot** [comment]
@mattdelco I rebased and added the list of the missing files to the commit. Here it is for reference:

```
install/gcp/deployment_manager/istio-cluster.jinja
install/gcp/deployment_manager/istio-cluster.jinja.display
install/gcp/deployment_manager/istio-cluster.jinja.schema
install/kubernetes/generate-webhook-cert.sh
install/kubernetes/templates/addons/grafana-config/istio-dashboard.json
install/kubernetes/templates/addons/grafana-config/custom.ini
install/kubernetes/helm/deployIstioHelmCharts.sh
```

Instead of filtering out `*/templates/*`, I filtered out `*.tmpl`. That should be much better!

Thank you for your patience.

**Comment by mattdelco** [comment]
I had considered excluding the .yaml.tmpl or .tmpl but that would have not excluded the istio-dashboard.json and custom.ini that are processed by updateVersion.sh and thus I presume intentionally excluded from the tar (though I don't understand the point of simply running "sed" with 's/^/    /' on these two files).

**Comment by dgageot** [comment]
Bummer. Can you annotate files in my list? Those that should be included,
those that shouldn’t.

**Comment by mattdelco** [comment]
I'm not sure I correctly understand the annotation request, but with the list you provided the main inappropriate files are the inclusion of:

install/kubernetes/templates/addons/grafana-config/istio-dashboard.json
install/kubernetes/templates/addons/grafana-config/custom.ini

A tempting option is to also exclude .json and .ini files (since these seems to be the only instances of this type), but offhand I'm not sure if this will also exclude the generated versions of these files (it would have been less of an issue if the .json and .ini files had a .tmpl suffix like the yaml files).

**Comment by dgageot** [comment]
@mattdelco OK. Let me change my mind and treat the `install/gcp` folder differently. I feel that I don't understand all the side effects of trying to package the right files. I'm going to update the PR.

**Pull request merged**
