### PR TITLE
Revert "add support for preserving header key case"

### PR DESCRIPTION
**Pull request by howardjohn**
Reverts istio/istio#33030

This is causing NACKs and has some TOC concerns. It can also be addressed by envoyfilter in the short term

This is breaking all VM tests in istio.io as well as our internal tests

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Review by stevenctl — APPROVED** [review]

**Comment by ningyougang** [comment]
My istio version is: `1.13.2`, envoy version: 15cc87023540f5f81331c11ef9010784f7ef2460 (e.g. when build istio image, we downloaded the envoy from: https://storage.googleapis.com/istio-build/proxy/envoy-alpha-15cc87023540f5f81331c11ef9010784f7ef2460.tar.gz)

I added envoyfilter like below
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: preserve-case-filter
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_protocol_options:
            header_key_format:
              stateful_formatter:
                name: preserve_case
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
```
But does work.(When access curl -H "custom_HEADERA: custom_HEADERA_value" http://xxx.xxx.xxx.xxx:10000, the header key is onverted to lower case letters)

@howardjohn Has any idea?

**Pull request merged**
