### PR TITLE
Make it work with devel version of Go.

### PR DESCRIPTION
**Pull request by PiotrSikora**

### CODE REVIEW

**Comment by mattdelco** [comment]
Afaict the script doesn't work with any version of go, devel or otherwise.  It's already pending deletion in https://github.com/istio/istio/pull/2831 , which does't have explicit support for devel but it's possible to touch a file to disable the check.

**Comment by PiotrSikora** [comment]
@mattdelco thanks, I'll drop it once #2831 is merged.

**Comment by mattdelco** [comment]
You're welcome to try a subsequent change to handle devel differently.  I did get burned by IT swapping my release go for a devel, and I wasn't sure if such a change was intentional or accidental.  For now I opted to err on the concervative side, which means that make will complain the first time about not seeing 1.9, but if you then do "touch ../../../bin/have_go_1.9" then you'll bypass the check (at least until the requirement is bumped to 1.10 or higher.  The error msg and file location that make produces about the failed recipe provides enough info to be a good reminder about the name and location on where to create the file.

**Comment by PiotrSikora** [comment]
This file was removed in #2831, so I'm going to drop this PR.

**Pull request closed without merging**
