### PR TITLE
add -fS to curl so it fails clearly

### PR DESCRIPTION
**Pull request by ldemailly**
missing part of #3231

### CODE REVIEW

**Comment by mattdelco** [comment]
How quiet was it before, and how much messaging would you like to see?  I'm partly asking as part of the review, but also considering how much messaging I should put in if go is just used to perform the download (the very tail part of https://github.com/istio/istio/compare/master...mattdelco:master20?expand=1 where the go implementation in the last diff is shorter than the bin/init.sh script to use curl or wget).

**Comment by ldemailly** [comment]
ty!

**Comment by mattdelco** [comment]
I don't know what's wrong with curl other than it looks to me like someone felt the need to enhance bin/init.sh to try to cope with cases where only curl is installed (or where curl lacks https support) or only wget is installed.  So, rather than pick favorites or debate on which one of the two should be supported it seemed like an option was to not rely on either and just leverage another existing build requirement (i.e., golang).

**Comment by ldemailly** [comment]
I objected to that change (curl vs wget etc...) too :-)
but if we want to use something in go, let's use
```
fortio curl --stdclient https://storage.googleapis.com/istio-build/proxy/envoy-debug-54077a0c8486b6db7b2fc5d10619b6813bb40767.tar.gz | ...
```

**Comment by ldemailly** [comment]
/retest
it seems we have ingress delays on prow at the moment (takes more than 70s for the ingress to showup)

**Comment by mattdelco** [comment]
Where does fortio come from?  I'm not a fan of home brewing an app but it does take less than a second to compile (assuming 1.10's caching isn't exaggerating) and there's be something ironic about downloading a binary to download a binary.

**Comment by ldemailly** [comment]
fortio is in vendor/ already and comes from me (istio/fortio)

**Comment by ldemailly** [comment]
@mattdelco btw fortio takes less than 4s to compile the first time and is used by some test [script](https://github.com/istio/istio/blob/e6d05c5c24433a597c478a3ba80eae3b6d6b20f2/tests/integration/example/integration.sh#L49) so needed anyway later:
```
ldemailly-macbookpro:istio ldemailly$ cd vendor/istio.io/fortio/
ldemailly-macbookpro:fortio ldemailly$ rm  ~/go/bin/fortio
ldemailly-macbookpro:fortio ldemailly$ time go install .

real	0m3.918s
user	0m7.364s
sys	0m2.198s
ldemailly-macbookpro:fortio ldemailly$ time go install .

real	0m0.286s
user	0m0.273s
sys	0m0.276s
```

**Pull request merged**
