### PR TITLE
Remove citadel deployment

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by howardjohn** [comment]
/retest

inrfa issue, I have a pr to fix

**Comment by howardjohn** [comment]
As a side benefit, security tests are no longer the slowest test

**Comment by myidpt** [comment]
Generally LGTM.
We still have customers that ONLY uses Citadel. I think we need to make sure istiod + node agent can cover their use cases (including istio-agent delivers the key and cert via files). If important customers are blocked by this, we may need to have Citadel in a separate repo for their use cases. In general this is the right move.

**Review by myidpt — APPROVED** [review]

**Comment by howardjohn** [comment]
> We still have customers that ONLY uses Citadel. I think we need to make sure istiod + node agent can cover their use cases (including istio-agent delivers the key and cert via files). If important customers are blocked by this, we may need to have Citadel in a separate repo for their use cases. In general this is the right move.

Do we know of any cases we are not supporting today?

**Review by richardwxn — APPROVED** [review]

**Comment by howardjohn** [comment]
@istio/wg-test-and-release-maintainers please take a look. Thanks!

**Review by fpesce — APPROVED** [review]

**Pull request merged**
