### PR TITLE
Fix subscribedResources in install/helm

### PR DESCRIPTION
**Pull request by Nino-K**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by Nino-K** [comment]
@howardjohn PTAL

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
