### PR TITLE
Update to latest go 1.11 to avoid security vulnerability

### PR DESCRIPTION
**Pull request by linsun**
recent golang updates to fix 3 security vulnerabilities:
https://groups.google.com/forum/#!topic/golang-announce/Kw31K8G7Fi0

pls let me know if there are other spots I missed in the istio repo.

### CODE REVIEW

**Comment by hklai** [comment]
Had that documented in wiki before.
https://github.com/istio/istio/wiki/Circle:codecov-(Code-Coverage)-FAQ/_compare/6cba4bbcf3abb5fc61c7de50cc0289dcb303e798...d66df7621bde9f63f223d06c699af49e6e70802e

**Comment by GregHanson** [comment]
@linsun I know there was some discussion of moving to go1.12 . . .  @rshriram @costinm was there a final decision made regarding this?

**Comment by linsun** [comment]
@hklai that is so odd.  I see what you are saying.  I went ahead and merged the latest from release-1.1 upstream and the issue seems resolved now.

**Comment by linsun** [comment]
@hklai  no, I have never seen this before...

**Pull request closed without merging**
