### PR TITLE
put back bookinfo-v1.yaml used by blog

### PR DESCRIPTION
**Pull request by frankbu**
This yaml file is referenced by a kubernetes blog article. It is otherwise unused and requires no testing.

### CODE REVIEW

**Comment by rshriram** [comment]
can we move this to a different folder though ?
So that it doesn't get packaged with the release.. Perhaps under the root itself.. Like blog/ where we can put all these files and then fix the links in the kubernetes blog
Ideally, I would even say we put these files in istio.github.io under a ping back blog article

**Comment by frankbu** [comment]
I agree moving it somewhere better, would be best. I can change the references, but there are 3 of them used in the article, so we should move all 3 to the same place - although I'm not sure if the other 2 are used for anything else (e.g. tasks, tests) as well. If not we would need to keep copies in both dirs. 

The 3 yaml files needed by the blog are:
```
bookinfo-v1.yaml
bookinfo-review-v2.yaml
bookinfo-ratings.yaml
```

**Comment by frankbu** [comment]
@rshriram I moved `bookinfo-v1.yaml` to `/blog` and also made a copy of the other two files (`bookinfo-ratings.yaml` and `bookinfo-reviews-v2.yaml`) in `/blog` as well. If the 2 files are not needed for anything else, we can remove them from the bookinfo sample dir, but we can do that cleanup after the 0.2 release.

**Pull request merged**
