### PR TITLE
use edsCliet instead of adsClient building the StreamEndpoints

### PR DESCRIPTION
**Pull request by idouba**
use edsCliet instead of adsClient building the StreamEndpoints.

### CODE REVIEW

**Comment by ymesika** [comment]
Typo.
/lgtm

**Comment by ymesika** [comment]
You need to remove the project from your personal CircleCI account as the tests are currently running there instead of within the Istio workspace.

**Comment by ymesika** [comment]
CircleCI tests are not following the /retest commands.
Can you merge master and push just to trigger CircleCI retest in Istio's workspace this time?

**Comment by idouba** [comment]
racetest  failed again, after I trigger another CI by another merge. 
I cannot understand why renaming a variable cause such CI problem. @ymesika

**Comment by ymesika** [comment]
You can ignore the racetest failure.

/lgtm

**Comment by idouba** [comment]
And multicluster e2e also failed..

**Pull request merged**
