### PR TITLE
Cleanup sleep files

### PR DESCRIPTION
**Pull request by jwendell**
- There is no such sleep service actually
- Remove vault files, they are not used anywhere

### CODE REVIEW

**Comment by frankbu** [comment]
@jwendell Are you sure these vault deployments aren't used anywhere? Maybe in some task? I wonder who added them. Seems it's just the service account that is special?

**Comment by jwendell** [comment]
> @jwendell Are you sure these vault deployments aren't used anywhere? Maybe in some task? I wonder who added them. Seems it's just the service account that is special?

A task was added and then removed a while back.
Added by https://github.com/istio/istio/pull/12917 and https://github.com/istio/istio.io/pull/3886
Removed by https://github.com/istio/istio.io/pull/4904

**Comment by frankbu** [comment]
I'm not sure what's going on with them, but it looks like there's a PR in the works to put back a task uses the vault deployments. https://github.com/istio/istio.io/pull/4432

**Comment by jwendell** [comment]
AFAICT that PR does not reference those two files (httpbin-vault.yaml and sleep-vault.yaml)

**Comment by frankbu** [comment]
> AFAICT that PR does not reference those two files (httpbin-vault.yaml and sleep-vault.yaml)

https://deploy-preview-4432--preliminary-istio.netlify.com/docs/tasks/security/vault-ca/#deploy-workloads-for-testing

**Comment by jwendell** [comment]
@frankbu ok, those files (from the preview link) are deleted in master.

Anyway, I changed the PR to keep -vault files around, just touched the service definitions.

**Pull request closed without merging**
