### PR TITLE
Add support for adapter name aliases.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by guptasu** [comment]
Sorry, missed one point.. in CRDs we are using raw adapter.Info objects and I think even that needs to be updated with aliases.

https://github.com/istio/istio/blob/master/mixer/cmd/mixs/cmd/crd.go#L72

**Comment by guptasu** [comment]
Also, adapter.md https://github.com/istio/istio/blob/master/mixer/doc/adapters.md#initialization-time

**Comment by andraxylia** [comment]
please rebase

**Comment by ldemailly** [comment]
ping. update or close?

**Comment by geeknoid** [comment]
I know it's getting old, but the work on that had just been a bit lower on
my todo list. It's bubbling up again soon...

**Comment by douglas-reid** [comment]
@geeknoid still bubbling?

**Comment by geeknoid** [comment]
Yeah, I'll get off me keester soon or close this...

**Comment by geeknoid** [comment]
Punt for now, we may come back to this later.

**Pull request closed without merging**
