### PR TITLE
move port label to api repo

### PR DESCRIPTION
**Pull request by xichengliudui**
**Please provide a description of this PR:**
ref: https://github.com/istio/api/pull/2193

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by zirain** [comment]
run `make lint` and `make gen` locally

**Comment by zirain** [comment]
@xichengliudui please run `make lint`  `make gen` at root of istio repo and fix all error.

**Pull request closed without merging**
