### PR TITLE
Temporarily remove eBPF impl pending CNCF guidance

### PR DESCRIPTION
**Pull request by bleggett**
eBPF support is temporarily disabled pending CNCF establishing guidance around dual-licensed eBPF bytecode 

https://github.com/cncf/toc/pull/1000#issuecomment-1564289871

See also Istio slack convo: https://istio.slack.com/archives/C041EQL1XMY/p1685101763149379

cc @irisdingbj @PlatformLC 

- [x] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by craigbox — APPROVED** [review]
LGTM, thank you

**Comment by kfaseela** [comment]
thanks @bleggett

**Comment by irisdingbj** [comment]
Thanks @bleggett

**Pull request merged**
