### PR TITLE
SignalFx Adapter Doc Fixes and Update

### PR DESCRIPTION
**Pull request by keitwb**
This was rendering incorrectly in HTML

### CODE REVIEW

**Comment by ozevren** [comment]
Core changes themselves looks good to me, but you have conflicting files that needs resolving. Also please revert the vendor changes, you shouldn't be needing thouse.

**Comment by keitwb** [comment]
The vendor changes are to get the latest version of our tracing client that includes faster JSON encoding of spans.

**Comment by ozevren** [comment]
Removed myself from the review as I don't have approve on Mixer stuff anymore.

**Comment by douglas-reid** [comment]
This seems reasonable.

/ok-to-test
/lgtm

**Comment by linsun** [comment]
/approve

can you pls get the shell check pass?  may need rerun it.

**Pull request closed without merging**
