### PR TITLE
Support setting FAIL_OPEN for istio-policy service

### PR DESCRIPTION
**Pull request by yangminzhu**
Cherrypick https://github.com/istio/istio/pull/9489 to 1.0 branch
#9483, #9485

### CODE REVIEW

**Comment by yangminzhu** [comment]
@rshriram we probably need to ignore the lint fail as it seems not working correctly in 1.0 branch. The lint is complaining format error in a unrelated file: `/mixer/adapter/rbac/rbac.go`.

**Comment by jsw** [comment]
After `helm upgrade...` does anything need to be restarted to propagate this change?

**Comment by yangminzhu** [comment]
@jsw I haven't tried `helm upgrade ...` with this but I think as long as you can set the `policyCheckFailOpen` flag to true without any error from pilot, then it's good and you don't need to restart to propagate it.

**Pull request merged**
