### PR TITLE
Remove long-time-experimental "Config distribution feature"

### PR DESCRIPTION
**Pull request by howardjohn**
Closes https://github.com/istio/istio/issues/30511

This feature has been experimental and off by default for ~4 years due to a variety of issues (https://github.com/istio/istio/issues/30179). Unfortunately, we have been unable to get investment to bring this feature up to a quality that supports enabling it by default/promoting it. As a result, after discussion with @therealmitchconnors who was one of the primary drivers for this feature, I feel its best to remove this feature.

This removes `PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING` and `istioctl x wait`, along with code supporting that. Primarily, this is the `pkg/ledger` and `pilot/pkg/status/distribution` packages, but there is a lot of cleaned up code in XDS as well.

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
`This feature has been experimental and off by default for ~4 years due to a variety of issues`

image


:+1:

**Review by MorrisLaw — APPROVED** [review]
🔥

**Comment by zirain** [comment]
I've heard some feedback from users in the past(most are complaints about high resource usage), it's worth to provide feature like this in a more efficient way.

**Comment by howardjohn** [comment]
> I've heard some feedback from users in the past(most are complaints about high resource usage), it's worth to provide feature like this in a more efficient way.

I agree the feature is useful in abstract, which is why it wasn't removed for many years despite not being usable. However, given we have no credible path to making it usable, keeping this code around isn't really helping IMO

**Comment by zirain** [comment]
> > I've heard some feedback from users in the past(most are complaints about high resource usage), it's worth to provide feature like this in a more efficient way.
> 
> I agree the feature is useful in abstract, which is why it wasn't removed for many years despite not being usable. However, given we have no credible path to making it usable, keeping this code around isn't really helping IMO

+1 on removing this, let's open a discussion about how to implement this in the future?

**Review by hanxiaop — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]
Awesome

**Comment by nrjpoddar** [comment]
Makes sense to remove this and cleanup the codebase.

LGTM

**Review by dhawton — APPROVED** [review]

**Comment by glasser** [comment]
https://istio.io/latest/docs/reference/config/config-status/ still says you need to enable config distribution to enable status tracking — is that outdated?

**Comment by glasser** [comment]
Or is the entire linked feature itself removed?

**Comment by glasser** [comment]
https://github.com/istio/istio.io/issues/17036

**Pull request merged**
