### PR TITLE
Exclude capture inbound on prometheus port 15090

### PR DESCRIPTION
**Pull request by diemtvu**
Port 15090 is used by prometheus with static config, and shouldn't be captured. If so, traffic will go through virtualInbound / passthrough listener, which will have mTLS enforced with the new mTLS API.

### CODE REVIEW

**Review by liamawhite — APPROVED** [review]

**Comment by howardjohn** [comment]
nit - can you remove the space between the two?

I'll wait for mandar to review

**Comment by mandarjog** [comment]
This is compatible behavior. This port was never captured before.
We have a FR to support secure scraping of Istio metrics. @douglas-reid ?

**Comment by hzxuzhonghu** [comment]
It is, we can see from the access log. 

GET /stats/prometheus HTTP/1.1" 200 - "-" "-" 0 37503 2 2 "-" "Prometheus/2.12.0" "bba03237-4ee8-9448-b580-592648923eac" "10.244.0.34:15090" "10.244.0.34:15090" InboundPassthroughClusterIpv4 - 10.244.0.34:15090 10.244.0.52:60808 - default
[2020-02-25T03:11:16.988Z] "GET /stats/prometheus HTTP/1.1" 200 - "-" "-" 0 37503 2 2 "-" "Prometheus/2.12.0" "40b94985-ee77-9b6a-ae84-59dcc52d2107" "10.244.0.34:15090" "10.244.0.34:15090" InboundPassthroughClusterIpv4 - 10.244.0.34:15090 10.244.0.52:60808 - default

**Comment by douglas-reid** [comment]
Seems fine to me. Would be good to understand how we can protect this port in the future.

**Comment by howardjohn** [comment]
Prior to 1.3 it was not captured.

If we do want to provide authentication here in the future, maybe it makes more sense to add an explicit inbound filter chain for this rather than bypassing envoy? Does that not solve the problem though since the authz policy will still apply?

**Comment by diemtvu** [comment]
> Prior to 1.3 it was not captured.
> 
> If we do want to provide authentication here in the future, maybe it makes more sense to add an explicit inbound filter chain for this rather than bypassing envoy? Does that not solve the problem though since the authz policy will still apply?

It's more code change at this point. And if you want the filter chain to honor authN/authZ, it needs proper design to make sure to outbound from prometheus match the application side (that also mean prometheus envoy should also capture traffic). We can address this post 1.5, but at the moment, this is the simplest fix.

**Review by rlenglet — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
