### PR TITLE
Make image pull policy configurable in Makefile

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by linsun** [comment]
/lgtm

agreed on removing using `istioctl gen-deploy`

**Comment by nmittler** [comment]
@sdake PTAL. I've re-based this PR and it looks like the generate_yaml target was already removed. I've reduced this PR to just adding a configuration option for PULL_POLICY.

**Comment by nmittler** [comment]
@wenchenglu this is minor, but it would be nice to get it in.  Should be zero risk.

**Pull request merged**
