### PR TITLE
Use standard meshconfig defaults in galley

### PR DESCRIPTION
**Pull request by howardjohn**
For some reason galley is using its own special MeshConfig, that is
different than Helm/what pilot uses, leading to inconsistent config.
This changes it to use the standard defaults in pkg/config/mesh.

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by crazyxy** [comment]
Do you need to delete galley/pkg/config/meshcfg/defaults.go?

**Comment by howardjohn** [comment]
> Do you need to delete galley/pkg/config/meshcfg/defaults.go?

what... why does galley have two different mesh config defaults?? and they are both wrong?

**Comment by ozevren** [comment]
Galley had its own defaults because, the alternative was to create yet another dependency on Pilot from Galley. It is used mostly for Ingress handling. It looks like Nathan's refactoring changes allows Galley to depend on the common mesh code now, so removing the defaults now makes sense. Thanks for taking care of this.

**Comment by ozevren** [comment]
Please also update the one in galley/pkg/config as well. That is an off-by-default config processing pipeline.

Thanks

**Comment by howardjohn** [comment]
> Galley had its own defaults because, the alternative was to create yet another dependency on Pilot from Galley. It is used mostly for Ingress handling. It looks like Nathan's refactoring changes allows Galley to depend on the common mesh code now, so removing the defaults now makes sense. Thanks for taking care of this.

Makes sense, glad we moved it out then! I just updated the other one. Not sure if it is correct with changes to ingressClass/ingressControllerMode?

**Pull request merged**
