### PR TITLE
Do not use Envoy deprecated CLI flag '--allow-unknown-fields'

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
@nmittler I thought you already did this?

Anyways we probably want to reject unknown static fields, I think the correct behavior now is to just remove the flag -- this means reject unknown static fields, but allow unknown XDS responses

**Comment by jwendell** [comment]
> Anyways we probably want to reject unknown static fields, I think the correct behavior now is to just remove the flag -- this means reject unknown static fields, but allow unknown XDS responses

@howardjohn removed.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
