### PR TITLE
use custom merge logic for ProxyConfig

### PR DESCRIPTION
**Pull request by fatedier**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/41046

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by GregHanson** [comment]
@fatedier @hzxuzhonghu should this be cherry-picked?

**Comment by fatedier** [comment]
> @fatedier @hzxuzhonghu should this be cherry-picked?

I think it can be cherry-picked to 1.14. It relies on this PR https://github.com/istio/istio/pull/38617 .

**Pull request merged**
