### PR TITLE
[release-1.6] Support k8s version less than 1.15

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
manually cherry-pick #24228 
fix: #24233

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @sdake @irisdingbj @brian-avery 

I do not plan on merging this as 1.15 is the minimum supported version. I will wait until Iris and/or Brian confirm the same to close this PR.

See https://github.com/istio/istio/pull/24228#issuecomment-636318648

**Comment by hzxuzhonghu** [comment]
Feel free to close it if we come to an agreement.

**Comment by sdake** [comment]
@jacob-delgado i have already (attempted) to revert this PR in master. The work was well done, and there is nothing technically wrong with it, however, it is as you point out outside of the K8s support matrix.

See: https://github.com/istio/istio/pull/24238#issuecomment-636384636

**Comment by brian-avery** [comment]
Unfortunately, I don't think we can accept this. We support 1.16-1.18 and we can't expand that window anymore than we already have for 1.6. This has already been discussed with TOC/the test and release group. Adding additional supported Kubernetes versions would cause quite a bit more work for us. We also know that in 1.17, additional features in Kubernetes 1.19 will cause 1.15 to no longer work, so this issue would resurface in 1.7.

**Comment by brian-avery** [comment]
Closing this as discussed above.

**Comment by hzxuzhonghu** [comment]
sounds good

**Pull request closed without merging**
