### PR TITLE
update addons manifest with explicit image path

### PR DESCRIPTION
**Pull request by AliRezaTaleghani**
none-docker-engine CRI env expect an explicit image path contains registry as well

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is generated from `./manifests/addons/gen.sh`, we need to update the inputs there then re-run the script.

That being said - these are basically generated by `helm template prometheus`, grafana, etc. Given all of these extremely popular charts are not putting docker.io, are we really expected to? It feels a bit like you need to boil the entire ocean to get this working...

**Comment by howardjohn** [comment]
I am not against it, just a bit suspicious that its actually viable to run a kubernetes cluster that doesn't resolve this to docker.io already. Seems like a lot of applications would break

**Comment by AliRezaTaleghani** [comment]
@howardjohn 
I see, if they are all just generation by `helm template` then really make sense to push them via original charts repo.

**Comment by AliRezaTaleghani** [comment]
and that is very true! if you move away from Docker engine into any other CRI (ex: cotainerd / cri-o) then there is no magic auto registry definition under the hood and we need to explicitly say where should it pull from...

**Comment by howardjohn** [comment]
Are you sure? I regularly run kind and GKE with containerd and it resolves
to docker.io. Not an expert here though, just seems to work for me

**Comment by AliRezaTaleghani** [comment]
Regarding **cri-o**, yes as it's my current deployment mode...
Also, I can pretty sure about **containerd** there we have global config with specific directly:
- [[unqualified-search-registries]]
- [[registry]]

but this sounds to be a more broad case:
lets say we have containerd and array of trusted registries (ex: docker.io / quay.io)
sadly image called:  _proxy-xyz/v-1.2.3_ is available on both, but not maintained by the say team/co...

**Pull request closed without merging**
