### PR TITLE
Fix prometheus yaml.

### PR DESCRIPTION
**Pull request by wangfakang**
Unexpected results after executing `istioctl manifest generate  --set .values.global.proxy.image="mosnio/proxyv2:1.4.6-mosn" `.

## got 
```
       image: gcr.io/istio-testing/mosnio/proxyv2:1.4.6-mosn:latest
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
```
## want 
```
       image: mosnio/proxyv2:1.4.6-mosn:latest
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
```

## fix 

```
diff --git a/manifests/istio-telemetry/prometheus/templates/deployment.yaml b/manifests/istio-telemetry/prometheus/templates/deployment.yaml
index a7fc0e9..37a6c22 100644
--- a/manifests/istio-telemetry/prometheus/templates/deployment.yaml
+++ b/manifests/istio-telemetry/prometheus/templates/deployment.yaml
@@ -61,7 +61,11 @@ spec:
 
 {{- if .Values.prometheus.provisionPrometheusCert }}
         - name: istio-proxy
-          image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
+{{- if contains "/" .Values.global.proxy.image }}
+          image: "{{ .Values.global.proxy.image }}"
+{{- else }}
+          image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image | default "proxyv2" }}:{{ .Values.global.tag }}"
+{{- end }}


diff --git a/operator/pkg/vfs/assets.gen.go b/operator/pkg/vfs/assets.gen.go
index 07d3bc7..2699e7f 100644
--- a/operator/pkg/vfs/assets.gen.go
+++ b/operator/pkg/vfs/assets.gen.go
 {{- if .Values.prometheus.provisionPrometheusCert }}
         - name: istio-proxy
-          image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
+{{- if contains "/" .Values.global.proxy.image }}
+          image: "{{ .Values.global.proxy.image }}"
+{{- else }}
+          image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image | default "proxyv2" }}:{{ .Values.global.tag }}"
+{{- end }}

```

## env
go version go1.13.7 linux/amd64

### CODE REVIEW

**Comment by dgn** [comment]
Hi @wangfakang, you'll have to run `make gen-charts` to make sure your changes will be compiled into istioctl, see also: https://github.com/istio/istio/blob/master/manifests/UPDATING-CHARTS.md

**Review by dgn — APPROVED** [review]

**Comment by wangfakang** [comment]
> Hi @wangfakang, you'll have to run `make gen-charts` to make sure your changes will be compiled into istioctl, see also: https://github.com/istio/istio/blob/master/manifests/UPDATING-CHARTS.md

@dgn I have verified that it is as expected, thx.

**Comment by tanjunchen** [comment]
It seems that istio 1.5.2 still has same problems.

**Pull request merged**
