### PR TITLE
Remove old envoyfilters

### PR DESCRIPTION
**Pull request by howardjohn**
We do not support 1.7 Pilot talking to 1.4 or 1.5 proxy

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by kyessenov — APPROVED** [review]

**Review by douglas-reid — APPROVED** [review]
These are definitely ugly and confusing. Thanks for clearing these out.

**Comment by nrjpoddar** [comment]
@howardjohn what's the new location for EnvoyFilter resources related to telemetry v2?

**Comment by howardjohn** [comment]
It hasn't changed, this is just the 1.4/1.5 ones. We still have 1.6/1.7
files

**Review by dgn — APPROVED** [review]

**Pull request merged**
