### PR TITLE
Monorepo: commit generated api go files..

### PR DESCRIPTION
**Pull request by rshriram**
Currently under vendor/istio.io/api until we figure out how to do the bazel fu to get it to be generated under istio.io/istio/api [this would need fixing all paths as well]
```release-note
NONE
```

### CODE REVIEW

**Comment by kyessenov** [comment]
I think putting things into vendor is not a good practice. Are you planning to move them to top-level api directory eventually?

**Comment by rshriram** [comment]
I want to .. but i think it requires that bazel hack you did in Envoy. Alternatively, mandar has a nice idea. That we just commit these go files into istio/api and import it as a standard dependency

**Comment by kyessenov** [comment]
Committing to istio/api is the best option for istio. As long as mixerfilter is happy with go files in that repo.

**Comment by kyessenov** [comment]
Btw, we have to do something about dependencies of istio/api. Last time I tried it, I had difficulty reconciling gogoproto and goproto versions of them. Which ones are we going with?

**Comment by rshriram** [comment]
oh I got no idea about that vodoo.. I am just going to commit the pb.go files there and let @mandarjog / you do the bazel fu

**Comment by mandarjog** [comment]
This is now being added to istio.io/api repo.

**Pull request closed without merging**
