### PR TITLE
use Gateway and VirtualService for bookinfo

### PR DESCRIPTION
**Pull request by tomkukral**
I was testing **bookinfo** application on my cluster and seems like `Ingress` resources are not working anymore. Switching to `v1alpha3` routing API makes the app working.

### CODE REVIEW

**Comment by rshriram** [comment]
We already have gateway and virtualservice. Its in a different folder..

**Comment by frankbu** [comment]
For `v1alpha3` you should be using `samples/bookinfo/routing/bookinfo-gateway.yaml`, instead of `samples/bookinfo/kube/bookinfo-gateway.yaml`. See docs [here](https://istio.io/docs/guides/bookinfo/).

`samples/bookinfo/kube/bookinfo-gateway.yaml` is only there for v1alpha1 users backward compatibility and will be removed in istio 1.0.

**Comment by tomkukral** [comment]
Ok, thanks for explanation. Should I update documentation? https://istio.io/docs/guides/bookinfo/ is refering to v1aplha3 but then using Ingress.

**Comment by tomkukral** [comment]
Oh, my fault, sorry. I have overlooked `/routing/` directory in step 3. I'm sorry for making this PR and wasting your time.

**Pull request closed without merging**
