### PR TITLE
tests: add `--scheme` argument to registry-redirector to allow HTTP requests

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

This change is needed to allow HTTP requests to kind-registry. Read #51778 and #35915 for more context.

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]

**Comment by jewertow** [comment]
Please do not merge this PR until all tests pass in #51778.

**Comment by jewertow** [comment]
Ok, now all telemetry tests pass. Could you review again @MorrisLaw @zirain? Do you have permissions to build and push `gcr.io/istio-testing/fake-registry:1.4`?

**Review by howardjohn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
can you update pkg/test/fakes/imageregistry/Makefile to 1.4

**Comment by howardjohn** [comment]
Pushing the image now

**Comment by howardjohn** [comment]
gcr.io/istio-testing/fake-registry:1.4 pushed

**Pull request merged**
