### PR TITLE
support distribute flag

### PR DESCRIPTION
**Pull request by irisdingbj**
For FS source, we need to set the distribute flag as true in the beginning.

### CODE REVIEW

**Comment by ayj** [comment]
Alternatively, would sending `resource.FullSync` after the initial process work?

```diff
diff --git a/galley/pkg/fs/fssource.go b/galley/pkg/fs/fssource.go
index d5c9be13c..517a99ed4 100644
--- a/galley/pkg/fs/fssource.go
+++ b/galley/pkg/fs/fssource.go
@@ -203,6 +201,7 @@ func (s *fsSource) initialCheck() {
                s.process(resource.Added, k, "", r)
                s.shas[k] = r.sha
        }
+       s.ch <- resource.Event{Kind: resource.FullSync}
 }
 
 // Stop implements runtime.Source
```

**Comment by irisdingbj** [comment]
@ayj @ozevren I suggest this go into 1.1.  If no objection, I will resubmit against 1.1.

**Comment by ozevren** [comment]
Is this PR still needed? I believe you have one going for 1.1 branch, right? Can we cherry-pick that?

**Comment by irisdingbj** [comment]
close this one as the PR has been in 1.1 already

**Pull request closed without merging**
