### PR TITLE
improve kube service registry queue performance

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is cherry-pick of #8162

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
There is a `dep ensure` error, I have to run this command.

**Comment by hzxuzhonghu** [comment]
run `dep ensure` , re tag lgtm

**Comment by hzxuzhonghu** [comment]
@costinm @rshriram just update Gopkg.lock , ptal

**Comment by hzxuzhonghu** [comment]
ping @rshriram

**Comment by hklai** [comment]
@hzxuzhonghu  @rshriram is this needed in master? I tried cherrypicking but there is a conflict. Could you do that if this is indeed needed for 1.1.

**Comment by rshriram** [comment]
This is already a cherry pick from master

**Pull request merged**
