### PR TITLE
Updating the sample helloworld python base image

### PR DESCRIPTION
**Pull request by abasitt**
The current helloworld app images are 6 years old. The previous base image is old and was throwing a lot of errors so I am updating the python base image.
The reason for this update so that helloworld sample app can work with IPv6 and dual stack. Currently all our multi-cluster verification is based on helloworld sample app and it doesn't work in IPv6/dual stack environment.

I build the images and tested these images in both IPv4 and IPv6 environment. The images are available in my repo. I wasn't sure about what tags to use so I am using latest tag.

abasitt/examples-helloworld-v1:latest
abasitt/examples-helloworld-v2:latest

This will fix the issue [here ](https://github.com/istio/istio/issues/42855)

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
@abasitt Because this PR only changes a sample, you can add the `release-notes-none` label to fix the release-notes_istio build job failure. You also need to fix the lint error it's complaining about (add `--no-cache-dir`).

Otherwise, LGTM.

**Comment by abasitt** [comment]
@frankbu and @ericvn thank you. I updated the images based on the updated --no-cache-dir if you want to try my images and push it to Istio hub.

**Review by bleggett — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
@frankbu has permission to upload new images. I do not unfortunately.

**Comment by abasitt** [comment]
Thank you @ericvn

**Pull request merged**
