### PR TITLE
Cherry pick envoy control plane api update, #5889 from master into release-0.8

### PR DESCRIPTION
**Pull request by incfly**
Original PR in master, #5889 

- Specifically this is to include "TransportProtocol" field in `FilterChainMatch`. The current API version in release-0.8 does is outdated and does not have it.
- Envoy TLS requires `FilterChainMatch.TransportProtocol`.

#5059

### CODE REVIEW

**Comment by hklai** [comment]
Why is this needed? the release-0.8 branch is closed, now that 0.8.0 is released.

**Comment by incfly** [comment]
Okay, I'll move this into 0.8.0.

**Comment by incfly** [comment]
@hklai Sorry I misunderstand your post. I thought there's a new 0.8.0 branch for 0.8.1 development, but I didn't find such one. So where can I make changes for 0.8.1 change?

**Comment by hklai** [comment]
There is no plan for 0.8.1, unless we are sure that it is needed.

Please make a case in https://github.com/istio/istio/issues/5982.

**Comment by yangminzhu** [comment]
@incfly Do we still need this?

**Comment by incfly** [comment]
@yangminzhu we still need this if we want to ship multiplexing/incremental mTLS before 1.0.

**Comment by yangminzhu** [comment]
if it's targeting 1.0, why put it to 0.8 instead of master?

**Comment by hklai** [comment]
incremental mTLS is expected in the Jun 1.0 snapshot release, which will be cut from master.
Please just close this.

**Pull request closed without merging**
