### PR TITLE
Fix for #22804

### LINKED ISSUE #22804: istioctl 1.5.1 can't create correct pilot plugins configuration
**Bug description**
I used following configure to configure install istio with additional pilot plugins, pass the plugins as slice(list)
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - aa
      - bb
 ```
but always get error when generating manifest 
```
istioctl manifest  generate --verbose --log_output_level=default:debug    -f istioctl-values.yaml 
json: cannot unmarshal string into Go value of type map[string]json.RawMessage
Error: generated config failed semantic validation: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```
seems ask me to pass a map into it, so if I set the the plugins as maps, manifest will be genterated without errors.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - 0: aa
      - 1: bb
 ```
and ther result deployment of istiod is :
```
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --secureGrpcAddr=:15011
        - --trust-domain=cluster.local
        - --plugins=[map[0:aa] map[1:bb]]
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --disable-install-crds=true
```
which is incorrect,  according to [discovery document](https://istio.io/docs/reference/commands/pilot-discovery/)  only accept `<stringSlice> , [authn,authz,health,mixer]`  but not map list  `[map[0:aa] map[1:bb]]`

**Expected behavior**

istioctl generate correct conf

**Steps to reproduce the bug**

```
istioctl manifest  generate --verbose --log_output_level=default:debug    -f istioctl-values.yaml 
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl: 1.5.1

**How was Istio installed?**
not installed yet 

**Environment where bug was observed (cloud vendor, OS, etc)**
runing istioctl on CentOS 7

### PR DESCRIPTION
**Pull request by adiprerepa**
This PR fixes #22804, and adds unit tests for this case.

### CODE REVIEW

**Comment by adiprerepa** [comment]
it seems that only by altering one field in the proto, I have changed a log of the generated code. Why is this happening? To generate the protobuf, I used:
```
bin/protoc.sh operator/pkg/apis/istio/v1alpha1/values_types.proto --proto_path operator/pkg/apis/istio/v1alpha1/  --go_out operator/pkg/apis/istio/v1alpha1
```
Is there another way to generate the protobuf? could someone point me to the place where that setup is documented?

**Comment by dgn** [comment]
Try running `make operator-proto`

**Review by howardjohn — COMMENTED** [review]
Thanks!

I think we could use a test actually generating the output though. In the original issue, they end up with `        - --plugins=[map[0:aa] map[1:bb]]` being rendered. Just dumping the profile only validates that you can pass in a list as the input, not that the output is correct

**Comment by adiprerepa** [comment]
@howardjohn thanks for the review. I'm a newbie, so I apologize for my naivete, but isn't the output being generated in `parseYAMLFiles`? I added a unit test that takes in the file `testdata/profile-dump/input/pilot_plugin.yaml` and verifies that the plugins are correct.

**Comment by sdake** [comment]
@adiprerepa yes output is being dumped, but the content of the output is not validated. This must also be done in a proper test case, else why generate the output at all?

Cheers
-steve

**Comment by adiprerepa** [comment]
@howardjohn I added a new test case that confirms that you can only pass a list in, and that a map will fail. Is that what you were saying?

**Review by richardwxn — COMMENTED** [review]
I think you need to check the output as well? i.e. the generated istiod deployment object manifest

**Comment by adiprerepa** [comment]
@richardwxn sorry, but do you mean another unit test, or in the existing one? From what I understand, `parseYAMLFiles` does not produce an istiod deployment object manifest, but `GenerateConfig` does? Do you mean add a test for that code?

**Comment by adiprerepa** [comment]
Am I mistaken, or does this not fix the issue?

**Comment by adiprerepa** [comment]
I messed up my git fork, so The new PR is in #24231

**Pull request closed without merging**
