### PR TITLE
Enable rewriteAppHTTPProbe by default for better UX

### LINKED ISSUE #10357: Evaluate the risk and benefits of liveness probe rewrite on by default
**Describe the feature request**
Istio currently supports to rewrite the kubernetes liveness probe rewrite during `kube-inject` time. This improves user experience who used have to rewrite their PodSpec with `curl` for liveness probe under mTLS. We currently disable this feature by default for risk consideration.

**Describe alternatives you've considered**
Turn on by default when we believe the benefits are larger than risks. This needs user feedback. Please consider answering following questions

- If you have tried this feature, how long and how large deployments you enabled the feature? In terms of number of the pods and different readiness/liveness probers?
- The feature is not needed if you can use other options, `curl cmd` probe in app container or use different ports for the health check, and configure authentication policy differently for different ports. Can you explain why you can't use those two approach?

**Additional context**
https://github.com/istio/istio/issues/9150

### PR DESCRIPTION
**Pull request by johnma14**
Fixes: https://github.com/istio/istio/issues/10357

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I don't think automtls is enabled by default

**Comment by rvennam** [comment]
Regardless of if auto-mTLS is enabled by default, this PR helps users by improving the default and out of the box compatibility - allow app health checks to work when mutual TLS is enabled without having to modify istio config map or pod annotations. 

https://istio.io/docs/ops/app-health-check/#liveness-and-readiness-probes-with-http-request-option


```
sidecarInjectorWebhook.rewriteAppHTTPProbe
If  true, webhook or istioctl injector will rewrite PodSpec for liveness  health check to redirect request to sidecar. 
This makes liveness check  work even when mTLS is enabled.
```

**Comment by linsun** [comment]
@johnma14 can you look into the required tests failure?  Also, can you check if there is sufficient tests to cover this?  You will also need changes in the new installer/operator repo when this is merged to istio/istio.

@howardjohn I believe the team is planning to enable auto MTLS by default for 1.4... regardless of whether it will be enabled, this feature is useful for users to enable.  We have multiple customers enabled this already and it is a big surprise when folks turn on mTLS and found out their service health check stops working.

cc @sdake @ostromart

**Comment by incfly** [comment]
Thanks @pitlv2109 for routing this PR to me!

/cc @diemtvu 

- I agree this should not be coupled with auto mTLS. They are orthogonal UX improvements for users to configure server side in STRICT mode. I edit the PR title to avoid confusion
- I agree enable this on by default can improve much user experience.
- Note, we might further simplify our mTLS policy, make it a deployment time thing, to specify STRICT, by then we can have even better probe rewriter targetting, we know which workloads will be in STRICT mode and only rewrite http probers for those workloads. PERMISSIVE/Plaintext won't be touched to minimize the change.

Having said that, if we really want to get better out of box UX, while considering the **risk** of doing so for mesh wide, I'm fine with that. Release upgrade notes definitely need to be updated for this behavior change.

**Comment by incfly** [comment]
@linsun test coverage should be good enough... I recently added positive/negative integration test, injection unit test is covered as well.

Also this is an environment changes (helm stuff), but can we make sure the original feature developers are on the reviewer list? It'll be better to provide review feedback, status of the feature, as well as avoiding the duplicate work ( I was thinking to do this in 1.5). Thanks!

**Comment by linsun** [comment]
@incfly apologies for leaving out reviews unintentionally.  Glad to hear this is well tested.  Would be interested in hearing your perspective of risks associated with enabling this mesh wide.

**Comment by incfly** [comment]
No worries! :)

Yeah I think it's worth giving a try for the UX improvements. If we wait
for future authn/mtls policy API change, that might be safer, but I think
it's okay to do it in 1.4

**Comment by incfly** [comment]
https://github.com/istio/istio/issues/18311 fyi...

**Comment by linsun** [comment]
@johnma14 looking at the test failures in unit-tests_istio... I think you need to update the injected file (e.g. hello-probes.yaml.injected) to reflect the update with httpprobe enabled by default.

**Comment by incfly** [comment]
/hold
@johnma14 @linsun there's a known issue for the health check prober. I think we should fix that before making it on by default.

Original prober is Kubelet -> App; now it's Kubelet -> pilot agent -> app. Customers can configure timeout in the prober config, but we don't propogate this information to pilot agent, rather than using a hardcoded timeout. This can cause the problem where customer specified timeout is larger than the hardcoded value we're using.

See https://github.com/istio/istio/issues/18242 for more details.

**Comment by incfly** [comment]
Do you mind fixing that? I can provide more details & help on that if needed.

**Comment by incfly** [comment]
Do you plan to fix the time out in spearate PR?

**Comment by johnma14** [comment]
yes @incfly. That is the intent.

**Comment by howardjohn** [comment]
Is this still desired?

**Comment by incfly** [comment]
Enable on by default is still desired, we see many customers giving +1 on the issue. https://github.com/istio/istio/issues/10357  We just need to fix one issue of this feature.

**Comment by incfly** [comment]
I saw knative turned on their config map for this field specifically. can we continue the venue to fix the timeout issue and turn it on by default then?

**Comment by howardjohn** [comment]
My understanding is that right now with this enabled if they have a timeout set we don't respect it, so sometimes the probe fails because the timeout isn't high enough. But without this, it ALWAYS fails. So isn't it a strict improvement ?

**Comment by incfly** [comment]
It only fails when you turn on strict mtls

**Comment by howardjohn** [comment]
if we set this default the time problem impacts permissive mode as well
though?

**Review by hzxuzhonghu — APPROVED** [review]
nit: It's better not set the env when it is `{}`

**Comment by howardjohn** [comment]
I will approve if @incfly approves

**Comment by incfly** [comment]
I don't think there're known issues for the feature. 

there's one limitation of enabling this though, unlike other meshconfig field that can affect xDS, which can be rolled out with double-control planes, gradually. This only affects during sidecar injection time, only kick in effect when customer are deployed. something nice to have though.

**Review by incfly — COMMENTED** [review]
agree with @hzxuzhonghu that we should  avoid empty `{}` if no prober

**Comment by johnma14** [comment]
@incfly those injected files where you see the empty value field {} are generated files. Do you still want to fix that here?

**Comment by incfly** [comment]
I see. You are saying it's two separate things that enable this by default
vs the implementation itself does not introduce new empty {} when no
probers defined.

Make sense, we can do it separately. It'll be a good starter issue.

**Review by incfly — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
