### PR TITLE
specify name of invalid sidecar resource during validation

### PR DESCRIPTION
**Pull request by tariq1890**
We deploy a helm chart which contains the sidecar resources for all our namespaces. Currently, we receive an error message like this: 

```
admission webhook "validation.istio.io" denied the request: configuration is invalid: sidecar: the egress listener with empty port should be the last listener in the list
```
Adding the name of the offending resource would make developer's lives a lot easier as opposed to sifting through a large list of sidecar YAML files.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Doesn't the error show up like:
```
Error from server: error when creating "galley/testdatasets/validation/dataset/networking-v1alpha3-EnvoyFilter-invalid.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: missing patch operation
```
?

If we do need this, maybe it would be good to have consistency across all validators not just sidecar? But we should get agreement we do actually need this so we don't waste time changing a bunch of error strings first

**Comment by tariq1890** [comment]
I think this part is dependent on the implementor

```
Error from server: error when creating "galley/testdatasets/validation/dataset/networking-v1alpha3-EnvoyFilter-invalid.yaml": 
```

Including the resource name in the validation message at least makes it client-agnostic

**Comment by howardjohn** [comment]
Validation errors from Kubernetes do not do this, making me think the client should be including the resource, not the warning. For example:
```
error validating data: ValidationError(EnvoyFilter.spec): unknown field "baz" in io.istio.networking.v1alpha3.EnvoyFilter.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

That error is from k8s, not Istio's webhook

**Comment by tariq1890** [comment]
Also, we render all of our Sidecar APIs into a single YAML file. Even if we printed the name of the file that failed to render, we would still end up having to go through tons of YAML to pinpoint the issue

**Comment by tariq1890** [comment]
I am not sure why Kubernetes doesn't add the resource name. But I don't see how adding the resource name would cause an issue. If anything, it's only helpful for users. 

`.metadata.name` is a standard field and I think it should be okay to highlight that in an error message.

**Pull request closed without merging**
