### PR TITLE
Enable ratelimit config reload automatically when the configMap has been updated

### PR DESCRIPTION
**Pull request by devincd**
Enable ratelimit config reload automatically when the configMap has been updated.

How to do this?
- Set the RUNTIME_WATCH_ROOT environment variable to false, and let ratelimit update the contents inside RUNTIME_ROOT/RUNTIME_SUBDIRECTORY/config/ directly.
- Delete the subPath, because a container using a ConfigMap as a subPath volume mount will not receive ConfigMaps updates.

Related issue: https://github.com/istio/istio/issues/34890

Signed-off-by: devincd <505259926@qq.com>

**Please provide a description of this PR:**

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
Would it work if we only remove subPath and keep `RUNTIME_WATCH_ROOT` as true?

**Comment by devincd** [comment]
> Would it work if we only remove subPath and keep `RUNTIME_WATCH_ROOT` as true?

It does'n work, because a container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates.

> https://kubernetes.io/docs/concepts/storage/volumes/#configmap

**Comment by bianpengyuan** [comment]
> > Would it work if we only remove subPath and keep `RUNTIME_WATCH_ROOT` as true?
> 
> It does'n work, because a container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates.
> 
> > https://kubernetes.io/docs/concepts/storage/volumes/#configmap

Yeah I mean if we only remove subPath like what you did, and do not specify `RUNTIME_WATCH_ROOT` and `RUNTIME_IGNOREDOTFILES`, will it work? Trying to figure out if it is necessary to set those two env variables, seems unnecessary to me.

**Comment by devincd** [comment]
> > > Would it work if we only remove subPath and keep `RUNTIME_WATCH_ROOT` as true?
> > 
> > 
> > It does'n work, because a container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates.
> > > https://kubernetes.io/docs/concepts/storage/volumes/#configmap
> 
> Yeah I mean if we only remove subPath like what you did, and do not specify `RUNTIME_WATCH_ROOT` and `RUNTIME_IGNOREDOTFILES`, will it work? Trying to figure out if it is necessary to set those two env variables, seems unnecessary to me.

oh, my fault.  It is necessary to set the `RUNTIME_WATCH_ROOT ` and `RUNTIME_IGNOREDOTFILES `.

- `RUNTIME_WATCH_ROOT`: because configuration files are loaded from RUNTIME_ROOT/RUNTIME_SUBDIRECTORY/config/*.yaml

There are two methods for triggering a configuration reload:
1.Symlink RUNTIME_ROOT to a different directory.
2.Update the contents inside RUNTIME_ROOT/RUNTIME_SUBDIRECTORY/config/ directly.
The ratelimit is the default behavior. To use the latter method, set the RUNTIME_WATCH_ROOT environment variable to false.

- `RUNTIME_IGNOREDOTFILES`: If we don't set the env to true, we get the following error log when the ratelimit reload the config
```
time="2021-09-01T03:39:40Z" level=warning msg="statsd is not in use"
time="2021-09-01T03:39:40Z" level=debug msg="runtime changed. loading new snapshot at /data/ratelimit/config"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: processing /data/ratelimit/config"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: processing /data/ratelimit/config/..2021_09_01_03_39_38.115520831"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: processing /data/ratelimit/config/..2021_09_01_03_39_38.115520831/config.yaml"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: adding key=..2021_09_01_03_39_38.115520831.config.yaml value=domain: productpage-ratelimit\ndescriptors:\n  - key: PATH\n    value: \"/productpage\"\n    rate_limit:\n      unit: minute\n      requests_per_unit: 1\n  - key: PATH\n    rate_limit:\n      unit: minute\n      requests_per_unit: 101\n uint=false"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: processing /data/ratelimit/config/..data"
time="2021-09-01T03:39:40Z" level=warning msg="runtime: error reading /data/ratelimit/config/..data: read /data/ratelimit/config/..data: is a directory"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: processing /data/ratelimit/config/config.yaml"
time="2021-09-01T03:39:40Z" level=debug msg="runtime: adding key=config.yaml value=domain: productpage-ratelimit\ndescriptors:\n  - key: PATH\n    value: \"/productpage\"\n    rate_limit:\n      unit: minute\n      requests_per_unit: 1\n  - key: PATH\n    rate_limit:\n      unit: minute\n      requests_per_unit: 101\n uint=false"
time="2021-09-01T03:39:40Z" level=warning msg="connecting to redis on redis:6379 with pool size 10"
time="2021-09-01T03:39:40Z" level=debug msg="Implicit pipelining enabled: false"
time="2021-09-01T03:39:40Z" level=debug msg="loading domain: productpage-ratelimit"
time="2021-09-01T03:39:40Z" level=debug msg="loading descriptor: key=productpage-ratelimit.PATH_/productpage ratelimit={requests_per_unit=1, unit=MINUTE}"
time="2021-09-01T03:39:40Z" level=debug msg="loading descriptor: key=productpage-ratelimit.PATH ratelimit={requests_per_unit=101, unit=MINUTE}"
time="2021-09-01T03:39:40Z" level=error msg="error loading new configuration from runtime: config.yaml: duplicate domain 'productpage-ratelimit' in config file"
time="2021-09-01T03:39:40Z" level=warning msg="Listening for HTTP on ':8080'"
time="2021-09-01T03:39:40Z" level=debug msg="waiting for runtime update"
time="2021-09-01T03:39:40Z" level=warning msg="Listening for debug on ':6070'"
time="2021-09-01T03:39:40Z" level=warning msg="Listening for gRPC on ':8081'"
```
and the configuration fails to be loaded.

**Review by bianpengyuan — COMMENTED** [review]
Thanks for the detailed explanation!

**Review by bianpengyuan — APPROVED** [review]

**Review by craigbox — APPROVED** [review]

**Pull request merged**
