### PR TITLE
debug: sync failure

### PR DESCRIPTION
**Pull request by kyessenov**
Change-Id: Idc0e1c884e67906690666dca733d59725119fc8c

**Please provide a description of this PR:**

### CODE REVIEW

**Review by hanxiaop — APPROVED** [review]

**Comment by zirain** [comment]
@hanxiaop this's just for verify.

**Comment by hanxiaop** [comment]
> @hanxiaop this's just for verify.

I see, thanks

**Comment by kyessenov** [comment]
A huge sleep does not help DNS propagation. Something else is going down with the test environment, which I can't replicate locally.

**Comment by zirain** [comment]
> A huge sleep does not help DNS propagation. Something else is going down with the test environment, which I can't replicate locally.

why always `fails on remote`?

**Comment by kyessenov** [comment]
It's only remote because it fails in DNS when resolving gRPC DNS names. I don't know enough about multi-cluster DNS to triage this.

**Pull request closed without merging**
