### PR TITLE
[Very WIP] Refactor ADS handling to make it re-usable for ECDS and SDS

### PR DESCRIPTION
**Pull request by howardjohn**
Way to early for review

### CODE REVIEW

**Comment by howardjohn** [comment]
@ramaraochavali @hzxuzhonghu I have been looking into the workload SDS code. I think we have three options
1. Keep custom SDS code which is not properly handling all the XDS edge cases and is complex
2. Refactor our pilot XDS code to be re-usable. That is what this PR attempts
3. Use go-control-plane for the workload SDS since its so simple anyways

Thoughts? I am on the fence that this may make the pilot XDS code more confusing

**Comment by ramaraochavali** [comment]
If 3 solves the problem better, I lean towards #3 rather than attempting #2. Would there be any more use cases that can benefit from refactor other than SDS?

**Comment by howardjohn** [comment]
> Would there be any more use cases that can benefit from refactor other than SDS?

I think the only benefit is if we plan to serve XDS from something other than Istiod and want to re-use the same XDS logic. For the ECDS case, they may want to serve ECDS directly (instead of ADS). If they want to do that, its literally a 2 line change, just abstract StreamADS to take in the generic DiscoveryStream interface shared by both ADS and the individual XDS types.

So tl;dr no

**Comment by hzxuzhonghu** [comment]
It seems 2 is better to reuse the current arch and makes ads have a better extension, but in another way, it is more error prone. 
#3 is more independent, but need to implement a separate but similar framework.

**Comment by ramaraochavali** [comment]
> but in another way, it is more error prone.

This is the part I am worried about

**Pull request closed without merging**
