### PR TITLE
revise admin log to be more formatted like other commands

### PR DESCRIPTION
**Pull request by monsteredc**
Currently, the `admin log` command will output something like:
```
➜  istio-1.11.1 istioctl admin log
active_scopes:
  ads:info
  adsc:info
  analysis:info
  authn:info
```

This PR is to revise the first line of the ouput, to be the format like below:
```
Active scopes:
  ads:info
  adsc:info
  analysis:info
  authn:info
```

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by monsteredc** [comment]
The release-notes test failed with the log below:
```
REPO_PATH not specified. Using current working directory.
~/prow/go/src/istio.io/tools/cmd/schema-validator ~/prow/go/src/istio.io/istio
~/prow/go/src/istio.io/istio
~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio
Executing ../tools/cmd/schema-validator/schema-validator  --schemaPath ../tools/cmd/gen-release-notes/release_notes_schema.json --documentPath ./releasenotes/notes/34982.yaml
~/prow/go/src/istio.io/istio
Checking files from pull request istio/istio#34982
~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio
~/prow/go/src/istio.io/tools/cmd/gen-release-notes ~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio
~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio ~/prow/go/src/istio.io/istio
Looking for release notes in ..
Executing: cd .; gh pr view https://github.com/istio/istio/pull/34982 --json files
{"files":[{"path":"istioctl/cmd/istiodconfig.go","additions":1,"deletions":1},{"path":"istioctl/cmd/istiodconfig_test.go","additions":1,"deletions":1},{"path":"releasenotes/notes/34982.yaml","additions":6,"deletions":0}]}
Found 1 files.
Parsing release notes
Unable to read release notes: unable to open file releasenotes/notes/releasenotes/notes/34982.yaml: open releasenotes/notes/releasenotes/notes/34982.yaml: no such file or directory
```
The file path generated has the duplicated `releasenotes/notes` directory. I think the same situation was happended before when I tried to merge to the release-1.10 branch. Seems like there is a test flake.
Since the releasenote `releasenotes/notes/34982.yaml` is already present, I'm going to add the `release-note-none` label to pass the release-notes test.

**Pull request merged**
