### PR TITLE
Do not expose username and password in grafana and kiali.

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @sdake @morvencao

### CODE REVIEW

**Comment by gyliu513** [comment]
This is a back merge of https://github.com/istio/istio/pull/7967 and https://github.com/istio/istio/pull/7719

**Comment by sdake** [comment]
@linsun this is already in 1.1 from what I can tell.  Did you mean to assign to the 1.0 delivery?

Cheers
-steve

**Comment by linsun** [comment]
@sdake my bad, corrected.

**Pull request merged**
