### PR TITLE
Add enabled switch to security section in values.yaml

### PR DESCRIPTION
**Pull request by shenxg13**
Add enabled switch to security section in values.yaml for requirements dependencies of security chart.

### CODE REVIEW

**Comment by shenxg13** [comment]
I signed it!

**Comment by sebastien-prudhomme** [comment]
@shenxg13 Have you made a test with enabled to false? Last time it tries, there were some problems with Istio installation.

**Comment by linsun** [comment]
@sebastien-prudhomme I think that could happen when you run side car with pilot.  But this should work, see https://istio.io/docs/setup/kubernetes/minimal-install/

/lgtm

**Comment by sebastien-prudhomme** [comment]
@linsun perhaps pilot sidecar should be disabled if security is disabled in Helm chart

**Pull request merged**
