### PR TITLE
solving #16784 in accordance with https://istio.io/docs/tasks/traffic…

### PR DESCRIPTION
**Pull request by zeph**
…-management/ingress/secure-ingress-mount/

just trying to align pregenerated paths related to certs

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
/ok-to-test

lgtm, I'll see if I can ask some others like @rshriram if they know why it was this way to begin with - it seems like a simple mistake but maybe not

**Review by howardjohn — APPROVED** [review]
thank you!

**Comment by zeph** [comment]
@howardjohn u r welcome... 

btw, I just signed the Google CLA, shall it automatically go fwd?

**Comment by howardjohn** [comment]
@googlebot I signed it!

**Pull request merged**
