### PR TITLE
remove xds send timeouts from istiod

### PR DESCRIPTION
**Pull request by ramaraochavali**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
What's this for? send timeout was introduced to prevent blocking forever. And can also prevent go routines leaks.

**Comment by ramaraochavali** [comment]
See this discussion https://github.com/istio/istio/issues/31943

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
https://github.com/istio/istio/issues/31943#issuecomment-816537546

**Review by howardjohn — COMMENTED** [review]
If we are concerned about blocking forever one compromise is a really high timeout (1min+)?

I think that if there is connectivity issues the whole connection will drop so we won't block forever, but it is theoretically possible that envoy has a deadlock that dropping might unblock?

**Comment by ramaraochavali** [comment]
> If we are concerned about blocking forever one compromise is a really high timeout (1min+)?

I was thinking about this option. But want to better understand when will it block though? If there is a possibility then we can go down that path.

**Comment by howardjohn** [comment]
The only case I can think of is if envoy has a deadlock? This is assuming
that grpc will always close the connection if the network is blocked, envoy
terminates, etc - I am not certain that is true

**Comment by ramaraochavali** [comment]
If Envoy is deadlocked, even if we timeout and close the stream - not sure if it is going to reconnect. Also I did not understand how go routine leak will be prevented with timeout - I do not think this https://github.com/istio/istio/blob/master/pilot/pkg/xds/ads.go#L910 will ever comeback if send is blocked @hzxuzhonghu Am I understanding this correctly?

**Comment by ramaraochavali** [comment]
I am closing this infavor of https://github.com/istio/istio/pull/32075 where I unified the send logic to be used across proxy and isitod.

**Pull request closed without merging**
