### PR TITLE
[release-1.12] Fix stale svc clusterVIP fo multicluster

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

manually cherry-pick of https://github.com/istio/istio/pull/39058

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
The failure are based on master branch, can be ignored I think.

**Comment by hzxuzhonghu** [comment]
Because at first i put the pr to master, and then updated to 1.12. I am not sure why the ci jobs are still there

**Comment by hzxuzhonghu** [comment]
close in favor of #39114

**Comment by Minh-Ng** [comment]
39187

**Pull request closed without merging**
