### PR TITLE
add istioctl build for ARMv7 and ARM64

### PR DESCRIPTION
**Pull request by dave93cab**

### CODE REVIEW

**Comment by dave93cab** [comment]
@googlebot I signed it!

**Comment by dave93cab** [comment]
I did a make istioctl-all and ARMv7 binary appears to work

**Comment by dave93cab** [comment]
@howardjohn I found this in the release-builder, bolded where it could be changed to linux-amd64 as I named it in this PR. Or I can revert to amd64 build just being called 'linux' which I think will pass the test. Let me know what makes sense and I can update.
```

// We build archives for each arch. These contain the same thing except arch specific istioctl
	for _, arch := range []string{"**linux-amd64**", "osx", "win"} {
```

**Comment by howardjohn** [comment]
Do you think it makes sense to have istioctl-linux just build all 3
targets? So you can build individual architectures or run istioctl-linux
and it builds them all

**Comment by dave93cab** [comment]
```
// Copy the istioctl binary over
istioctlBinary := fmt.Sprintf("istioctl-%s", arch)
```
and (where standalone istioctls are released) 
```
if err := createStandaloneIstioctl(arch, manifest, out); err != nil {
    return err
}
```
both take place in a loop over those arches in my previous comment and expect the -<arch> suffix.

It wouldn't take much to move the standalone generation out of that loop to create them from their own set of arches, and leave the amd64 arch named as it is

How do you sync up changes to the release builder and the istio repo if changes to both are required?

**Comment by howardjohn** [comment]
It's a bit of pain unfortunately. I think you would need to make a
backwards compatible change to istio, update release-builder, then you can
update istio to use the new release builder and remove the backwards
compatibility bit (if needed)

**Comment by dave93cab** [comment]
@howardjohn wondering your thoughts on the following:

1. [istio] add istioctl-linux and istio-linux-amd64 to build (using same arch)
2. [release-builder] update arch linux -> linux-amd64
3. [release-builder] add istioctl standalone generator loop (linux-armv7, linux-arm64)
4. [istio] remove istioctl-linux build

I guess this comes down to whether you want the release package to change from istio-linux to istio-linux-amd64 which may be useful if somebody manages to get the entire istio to build for arm in future

**Comment by howardjohn** [comment]
We package istio-X and istioctl-X, but in reality the only difference
between istio-linux and istio-mac is istioctl itself. Everything else is
pretty much just yamls. So we probably want to release an istio-arm and
istioctl-arm for consistency?

**Comment by dave93cab** [comment]
Oh I see. So can just modify the arches to include the arm builds then. A modified plan:

1. [istio] duplicate istioctl-linux with new istioctl-linux-amd64 in build (using same arch)
2. [release-builder] update arch linux -> linux-amd64
3. [release-builder] add arches linux-armv7, linux-arm64
4. [istio] remove istioctl-linux from build

This will result in following linux arches in release:

1. istio-linux-amd64 (was istio-linux)
2. istio-linux-armv7
3. istio-linux-arm64

**Comment by dave93cab** [comment]
hi @howardjohn, any thoughts on that plan? I can modify this PR and do the required PR on the release builder if it's a go. Thanks

**Comment by howardjohn** [comment]
SGTM, should have another release owner give this a quick look though

@ericvn @sdake @brian-avery @esnible

**Comment by sdake** [comment]
@howardjohn LGTM. `armv7` is a bit off from standards set by other T&R teams within the cloud-native ecosystem. Perhaps just `arm` would do, although I don't know enough about armv7 to make the qualified judgment.

We also don't need a duplicate `istioctl-linux` - perhaps that could just be removed later as a followup.

The code itself and plan looks good.

**Comment by dave93cab** [comment]
@sdake see this in the go docs regarding arm / armv7 [https://github.com/golang/go/wiki/GoArm#supported-architectures](https://github.com/golang/go/wiki/GoArm#supported-architectures)

> Starting from Go 1.1, the appropriate GOARM value will be chosen if you compile the program from source on the target machine. In cross compilation situations, it is recommended that you always set an appropriate GOARM value along with GOARCH.

and yes the duplication would only be temporary to not break the builder before changing it

**Comment by dave93cab** [comment]
@howardjohn @sdake Added PR to release-builder:
[https://github.com/istio/release-builder/pull/179](https://github.com/istio/release-builder/pull/179)

**Comment by BlackMix** [comment]
waiting this release 🙏
good work.

**Comment by sdake** [comment]
> https://github.com/golang/go/wiki/GoArm#supported-architectures

As part of the review, I found this link via google already. It still didn't really answer my statement as to whether arm or arm7 is more appropriate for the binary name.

To dig into the question a little more, is `arm` sufficient to run on all 32-bit arm architectures, and `arm64` sufficient to run on all arm64 architectures, or, do we need:

- `arm`
- `arm7`
- `arm64`

**Comment by sdake** [comment]
@dave93cab for now, we can punt on the v7 vs not v7 question and handle in a followup.

**Pull request merged**
