### PR TITLE
switch the sleep image to governmentpaas/curl-ssl

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
since it has both curl and openssl, required for testing SNI connectivity
for example, see step 3 in https://istio.io/docs/examples/advanced-gateways/egress-gateway/#troubleshooting

### CODE REVIEW

**Comment by douglas-reid** [comment]
@vadimeisenbergibm do we still want this?  if so, can we rebase and push to fix the tests?

**Comment by vadimeisenbergibm** [comment]
@douglas-reid I am afraid something in the images causes the tests to fail, I can't figure out what it is. Let me rebase and try again.

**Comment by vadimeisenbergibm** [comment]
@douglas-reid I found the problem, something in the new image does not let it resolve `<service>.<namespace>` to `<service>.<namespace>.svc.cluster.local`.

**Comment by vadimeisenbergibm** [comment]
@douglas-reid Found the problem, governmentpaas/curl-ssl uses alpine 3.3 which has some DNS problems with Kubernetes. A related issue https://github.com/gliderlabs/docker-alpine/issues/255.

I will wait until they switch to alpine 3.8 like pstauffer/curl. Closing the PR until then.

**Comment by vadimeisenbergibm** [comment]
Created an issue https://github.com/alphagov/paas-docker-cloudfoundry-tools/issues/153.

**Comment by vadimeisenbergibm** [comment]
governmentpaas/curl-ssl bumped their version of Alpine, reopening this PR.

**Comment by vadimeisenbergibm** [comment]
@duderino Could you please merge this one? The rationale is in the first comment https://github.com/istio/istio/pull/12871#issue-265228384.

**Comment by duderino** [comment]
@vadimeisenbergibm also on this one, what are the implications of not merging this?   I'm trying to raise the bar on 1.1 merges and move attention to master and subsequently 1.2

**Comment by vadimeisenbergibm** [comment]
@duderino The implication is that istio.io documentation's steps will not work, this one for example  https://istio.io/docs/examples/advanced-gateways/egress-gateway/#troubleshooting uses `openssl`.

**Comment by vadimeisenbergibm** [comment]
@douglas-reid Could you please add LGTM label again? At some point I closed this PR and your LGTM label was removed.

**Pull request merged**
