### PR TITLE
Fix potential memory leak in slice when using FilterInPlace

### PR DESCRIPTION
**Pull request by SpecialYang**
When we move right elements to left, we should assgin emtpy value to useless elements for gc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Nice. A good test for this:

```go
func TestFilterInPlace2(t *testing.T) {
	type s struct {
		Junk string
	}
	var input []*s
	var output []*s
	t.Run("inner", func(t *testing.T) {
		a := &s{"a"}
		b := &s{"b"}
		// Check that we can garbage collect elements when we delete them.
		leak.MustGarbageCollect(t, b)
		input = []*s{a, b}
		output = FilterInPlace(input, func(s *s) bool {
			return s.Junk == "a"
		})
	})
	assert.Equal(t, output, []*s{{"a"}})
	assert.Equal(t, input, []*s{{"a"}, nil})
}
```

similar to the Delete test we have.

I put a hold in case you want to add this

**Comment by SpecialYang** [comment]
Done. @howardjohn

**Pull request merged**
