### PR TITLE
[Release-1.5] Update proxy/release1.5 sha in istio/release1.5

### PR DESCRIPTION
**Pull request by gargnupur**

### CODE REVIEW

**Comment by dgn** [comment]
Hi @gargnupur, since merging this the TestTcpMetric test has been broken in postsubmit (see https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/123). Could you take a look? Thank you

**Comment by gargnupur** [comment]
@dgn: sure, taking a look.. although it's weird given it passed in presubmit...

**Comment by gargnupur** [comment]
@dgn: Talked with @howardjohn  about this and integ_k8s-115 use helm for install. I will disable this test when istioctl is not used..
I have to make an update to istio/istio proxy sha and will make fix to this test in that PR. Will update this once I have that fix.

**Pull request merged**
