### PR TITLE
 Use strict version for zipkin

### PR DESCRIPTION
**Pull request by clyang82**
refer to this PR https://github.com/istio/installer/pull/241 for more detailed information.

Signed-off-by: clyang82 <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by clyang82** [comment]
@duderino I need to have this PR into 1.1.x as well. How to do it? Create another PR against release 1.1 branch? Thanks.

**Comment by howardjohn** [comment]
/lgtm

Not sure we need this in 1.1 though. Up to @duderino though

**Comment by fpesce** [comment]
This ended up being mergified to 1.2, seeing the discussion, it doesn't look like it's intended.

**Comment by clyang82** [comment]
@fpesce this PR should be merged into 1.2.

**Pull request merged**
