### PR TITLE
concatenate cert-chain using correct order

### PR DESCRIPTION
**Pull request by irisdingbj**
concatenate the cert-chain for workload certs with right order: workload cert->intermediate ca cert ->root cert

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
How come no tests fail from this?

**Comment by irisdingbj** [comment]
> How come no tests fail from this?

Test currently only call  `xx-cacerts`   This is to fix `xxx-certs` which generate certs for workload.

**Comment by irisdingbj** [comment]
@nmittler PTAL , Thanks!

**Review by nmittler — APPROVED** [review]

**Pull request merged**
