### PR TITLE
add tests for istio.io tutorial version routing

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
add a test for directing the traffic to _reviews v2_ for both normal and test users, and also a test for traffic shadowing

### CODE REVIEW

**Comment by rshriram** [comment]
Please add tests in new v1alpha3 format. Otherwise, this entire code will rot in a month. cc @frankbu

**Comment by vadimeisenbergibm** [comment]
@rshriram @frankbu  I personally would not mix the formats of the tests. Note that all other bookinfo tests use the old format. I would proceed to add the tests in the old format until the new format is fully functional. Once the new format is fully functional - all its e2e tests pass, I would switch the format for all the rules in all the sample repositories, bookinfo and others.

You decide, I will follow the decision.

**Comment by vadimeisenbergibm** [comment]
Closing meanwhile, until https://github.com/istio/istio/pull/4042 is merged.

**Pull request closed without merging**
