### PR TITLE
[WIP] RBAC Discovery Service

### PR DESCRIPTION
**Pull request by ymesika**
**Please provide a description of this PR:**

Work in progress.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Can you please provide context of this change?

**Comment by howardjohn** [comment]
I think there may have been some miscommunication as I thought I was taking this over and submitted https://github.com/istio/istio/pull/42531. I'll be back tomorrow and can look this over and can maybe pull in bits of this into my PR as needed? Sorry for the confusion..

**Comment by ymesika** [comment]
@ramaraochavali The related issue for this is https://github.com/istio/ztunnel/issues/259 and it is about adding the new XDS for the RBAC used by the new ztunnel (see the internally linked design issue as well). It was discussed in recent Ambient meetings.
Sorry for the blank description for the PR as I meant it to be a WIP PR to be shared with others.

**Comment by ramaraochavali** [comment]
@ymesika No problem. Thanks for the context. I was able to get the additional context from @howardjohn 's :PR.

**Pull request closed without merging**
