### PR TITLE
galley: discard the sync.Pool in api server status

### PR DESCRIPTION
**Pull request by panjf2000**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by panjf2000** [comment]
Hi @howardjohn, since you stop by, could you take a look at this?

**Comment by panjf2000** [comment]
Hi @hzxuzhonghu, since you stop by, could you take a look at this? this is a tiny but vital fix, it would be totally meaningless to use a sync.Pool if you don't put the object back into the pool after it's released, thanks!

**Comment by hzxuzhonghu** [comment]
Actually, i could not understand why the sync.Pool is necessary here.

**Comment by panjf2000** [comment]
> Actually, i could not understand why the sync.Pool is necessary here.

For reusing the `status` struct when it is being created and released in high frequency?

But the `status` really doesn't seem like a struct big enough or being created so often to use a sync.Pool. 
This is introduced by @ozevren in #17360, anyway, we ought to either add an action of putting objects back into the pool or just remove the sync.Pool directly.

**Comment by hzxuzhonghu** [comment]
>  or just remove the sync.Pool directly.

This is what i mean

**Comment by panjf2000** [comment]
Currently, the `statusPool` is nothing but a liability, so I suggest that we just throw it away? 
If it is okay with you, I will start working on it in this PR. @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Agree with that

**Review by hzxuzhonghu — COMMENTED** [review]
/ok-to-test

**Comment by panjf2000** [comment]
image

Is there something wrong with the test environment? The `integ-security-multicluster-tests_istio` seemed to fail for some uncorrelated causes with this PR.

@hzxuzhonghu Any clues about that?

**Review by howardjohn — CHANGES_REQUESTED** [review]
Sorry to comment this on every one of your PRs, but please describe what issues this is fixing or we cannot review it appropriately.

Historically, these types of PRs often look innocent then months down the line lead to outages or security regressions.

**Comment by panjf2000** [comment]
> Sorry to comment this on every one of your PRs, but please describe what issues this is fixing or we cannot review it appropriately.
> 
> Historically, these types of PRs often look innocent then months down the line lead to outages or security regressions.

In the first place, I notice there is missing a pool.Put action for a sync.Pool containing `status` struct, so I opened a PR adding this action, see [here](https://github.com/istio/istio/pull/29240/commits/6d3855d9d4708f45a5846e69079cca0c6ec496cb).

However, after discussing with @hzxuzhonghu , we all agree to discard the sync.Pool cuz it doesn't seem to be worth.

**Comment by panjf2000** [comment]
Shall we continue this PR? @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@howardjohn This is kind of clean up

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by panjf2000** [comment]
Have a look at this?

**Comment by panjf2000** [comment]
PTAL @howardjohn

**Comment by panjf2000** [comment]
PTAL @howardjohn

**Comment by panjf2000** [comment]
It's been more than a week, so how should we treat this change? any definite decisions?

**Comment by panjf2000** [comment]
PTAL @howardjohn

**Review by howardjohn — COMMENTED** [review]
Sorry for the delay - I don't think we should making changes to code that does not have bugs and is going to be removed in the near future. there is no benefits and it introduces risk

**Comment by panjf2000** [comment]
The current code with the sync.Pool is totally bootless and even drags down this part for not putting objects back into pool, if you are not happy with this ultimate change, I think at least we should return to this commit: https://github.com/istio/istio/pull/29240/commits/6d3855d9d4708f45a5846e69079cca0c6ec496cb

**Comment by howardjohn** [comment]
> The current code with the sync.Pool is totally bootless and even drags down this part for not putting objects back into pool, if you are not happy with this ultimate change, I think at least we should return to this commit: 6d3855d

If there is no user facing bugs as a result of this code, I see no reason to change this. We are planning to completely remove this code in 1.9 (https://github.com/istio/istio/issues/23943)

**Pull request closed without merging**
