### PR TITLE
[Auto Release] Update istio.Version

### PR DESCRIPTION
**Pull request by linsun**
Update istio.Version

**Release note**:
None

### CODE REVIEW

**Comment by rshriram** [comment]
if possible, switch to proxy:0.2.7 instead of proxy_debug.. much lighter and faster

**Comment by ldemailly** [comment]
the way you switch to non debug image is to use --debug=false in kube-inject

and as we discussed earlier it's too early to change the default

**Comment by ldemailly** [comment]
@sebastienvas this auto pr still doesn't have the no rel note needed label

**Pull request merged**
