### PR TITLE
Updates to accommodate move of api/config/mcp to api/mcp.

### PR DESCRIPTION
**Pull request by ozevren**
- Since this is the release branch, and the corresponding changes are in api/release-1.0 branch, I've updated Gokg.toml file to point istio.io/api dependency to api/release-1.0. This needs to be reverted back once 1.0 ships and changes get merged back into master.

### CODE REVIEW

**Comment by rshriram** [comment]
you have to update the dependencies (vendor stuff).

**Comment by ozevren** [comment]
Yes, I am aware. I created this PR early since you asked for it in the previous one.

**Comment by ozevren** [comment]
Updated with dependencies. I've also updated the PR description to reflect what is going on.
@hklai I've opened https://github.com/istio/istio/issues/6849, to track a work that needs to be done to revert some changes back and assigned to you.

**Comment by ozevren** [comment]
Removed the comment about cobra/legal dependencies from PR description. After the linter has failed in the checkin gate, I ran depend.diff again, (which seems to have updated my local dep). Rerunning dep ensured pruned those dependencies again.

**Pull request merged**
