### PR TITLE
Allow the gateways controller to be changed

### PR DESCRIPTION
**Pull request by nalbam**
**Please provide a description of this PR:**

This change makes the controller changeable.
Default is Deployment, but can be changed to DaemonSet.

re PR : https://github.com/istio/istio/pull/35660

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by morvencao — COMMENTED** [review]
you may need to run `make gen` to fix test failing tests.
BTW, if you're using operator to deploy gateway, you can following https://github.com/istio/istio/issues/31303#issuecomment-814576305 without changing charts.

**Comment by nalbam** [comment]
The `release-notes-none` label should be added here.

**Comment by calebfornari** [comment]
@Arhell @morvencao Any plans to look at this one again? We need to run our ingress as a Deamonset and this is really messing up our transition to using Helm to manage our Istio installs.

**Pull request closed without merging**
