### PR TITLE
We should not set container/use_client_certificate if we disable legacy authorization

### PR DESCRIPTION
**Pull request by panywei**
If set this field to true, you may get some error like this:
Error from server (Forbidden): pods is forbidden: User "client" cannot list pods at the cluster scope: Unknown user "client"

More explanation at https://stackoverflow.com/questions/49075723/what-does-unknown-user-client-mean?answertab=votes#tab-top

### CODE REVIEW

**Comment by costinm** [comment]
Seb, do you remember if this is required ?

**Comment by sebastienvas** [comment]
Yes this is right. We should not be using this !

**Comment by sebastienvas** [comment]
proof
https://github.com/istio/test-infra/blob/master/scripts/update-e2e-cluster.sh#L80

**Pull request merged**
