### PR TITLE
Invert namespace injection selection criteria

### PR DESCRIPTION
**Pull request by ayj**
Fixes https://github.com/istio/istio/issues/5576

Copy of https://github.com/istio/istio/pull/6439

### CODE REVIEW

**Comment by ayj** [comment]
The new opt-out behavior is off by default to match existing install configuration.

Namespace labeled is required to avoid bootstrap problems. Annotating the pods alone (w/o namespace labels) won't work. The api-server will still invoke the webhook for properly annotated pods, including the injector pod itself. And the injector pod can inject into itself before it's running.

Any suggestions for labeling namespaces automatically in the install processes? If helm isn't sufficient, do we need a real installer/upgrader (e.g. operator pattern)?

**Comment by costinm** [comment]
+Andy - we may need to revert this for the RC1.

**Comment by costinm** [comment]
Never mind - the values.yaml doesn't set this option, so no need to revert. Still won't work if someone
sets it explicitly - but it's not documented.

**Comment by ayj** [comment]
This option is disabled by default (see https://github.com/istio/istio/pull/6704#issuecomment-401573433). We should document this prerequiste requirement in the setup instructions (or hide it from docs entirely for 1.0).  

To handle this automatically with helm we'll likely need an install job (see https://github.com/istio/istio/pull/6823) unless helm gets native support for namespace labeling.

**Pull request merged**
