### PR TITLE
Use zipkin 2.6.0 in istio.

### PR DESCRIPTION
**Pull request by gyliu513**
We should use a stable release for zipkin.

/cc @linsun

### CODE REVIEW

**Comment by gyliu513** [comment]
Fixed https://github.com/istio/istio/issues/4725

**Comment by gyliu513** [comment]
Can I got another approve?

**Comment by gyliu513** [comment]
Any feedback from approvers...

**Comment by gyliu513** [comment]
@sdake sure, I will try to keep this up to date.

BTW, how about follow Kubernetes guidance? Currently, Kubernetes is always using stable release for its dependent components, such as etcd, calico etc, and it will be upgraded once the related components has  a new stable release, thoughts?

**Comment by gyliu513** [comment]
@sdake not sure why `ci/circleci: lint` failed, I run `bin/fmt.sh -c` locally with this PR, it works fine.

**Comment by sdake** [comment]
@gyliu513 not sure what the precise error is.  I have seen this in the past.  It was related to a mispelling in a comment.

One solution is to run the linters in the circleci containers.  Obviously not a great solution as it slows down workflow, but it should help you get moving on this problem.

@hklai any ideas here?

**Comment by linsun** [comment]
@gyliu513 have you tried to rerun the lint job in circle?

**Comment by gyliu513** [comment]
Seems I do not have permission to rerun the lint job in circle. @sdake @linsun

**Comment by linsun** [comment]
@gyliu513  Did you check this?  https://github.com/istio/istio/wiki/Working-with-CircleCI

**Comment by costinm** [comment]
Lint failure has nothing to do with code change - merging.

**Comment by ldemailly** [comment]
why 2.6.0 vs 2.7.1 ? (or 2.6.1... usually .0 is not a great choice)

looks like they have moving tags so we should used 2.6 or 2.7 without .x

https://hub.docker.com/r/openzipkin/zipkin/tags/

**Comment by gyliu513** [comment]
@ldemailly 2.7 was not released yet when I create this PR.

Also for open source version, I'd prefer that we do not use the latest stable version but use a old stable version, so with 2.7 as latest stable version, using 2.6 maybe better.

Also I found that https://hub.docker.com/r/openzipkin/zipkin/tags/ also include tags such as 2.6.1, 2.6.2 etc, what is the advantage of using 2.6?

**Comment by ldemailly** [comment]
if we use 2.6 or 2.7 we don’t have to change our files eaxh time they release a bug fix or patch. let’s change it to 2.7 ?

**Comment by gyliu513** [comment]
@ldemailly done at https://github.com/istio/istio/pull/5155

**Pull request merged**
