### PR TITLE
Update kiali to v1.4.0

### PR DESCRIPTION
**Pull request by howardjohn**
Tested this manually, everything seems to function fine

### CODE REVIEW

**Comment by clyang82** [comment]
@howardjohn could you please review this PR - https://github.com/istio/istio/pull/16848

**Review by sdake — APPROVED** [review]

**Comment by linsun** [comment]
I’m using 1.14.6 K8s in IBM Cloud.  Tried this twice but getting blank page with kiali icon in the title/tab after `istioctl dashboard kiali`:

```
kubectl -n istio-system set image deployment/kiali kiali=quay.io/kiali/kiali:v1.4.0 --record
```

Not recommend to update for 1.3

**Comment by linsun** [comment]
Upon further debugging with kiali team, it turned out to be a kiali 1.4 issue with firefox: https://github.com/kiali/kiali/issues/1631

**Pull request merged**
