### PR TITLE
fix race detector goroutine limit

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
fixes: #8424

### CODE REVIEW

**Comment by ozevren** [comment]
I don't think this is the right fix. I suspect whatever test is failing, it is failing to properly close the mixer server instance. Ensuring the server object is closed properly should fix this issue.

**Comment by hzxuzhonghu** [comment]
> Ensuring the server object is closed properly

@ozevren All the sub-cases are run concurrently in `TestErrors`,, We can not close it.

**Comment by ozevren** [comment]
"s" in line 308 (and at the top of the function) are not Close'd. s in line 308 is allocated within the sub-tests, so it should be close-able within the same sub-test as well.

**Comment by ozevren** [comment]
Sorry, I misread the code, you're right.

The right fix seems to be in somewhere in server then. If we fail to properly initialize the object, then the API pools should be cleaned up properly before returning control.

**Comment by hzxuzhonghu** [comment]
> The right fix seems to be in somewhere in server then. If we fail to properly initialize the object, then the API pools should be cleaned up properly before returning control.

Sorry, the `newServer` does not return an error in this case. It it a system panic.

**Comment by ozevren** [comment]
The panic is because we're leaking resources in case of a failed initialization.

I think the problem is with some of the returns not Close'ing the object:
https://github.com/istio/istio/blob/ce140478a652d34e7d1f2659eda12bec7e8a623e/mixer/pkg/server/server.go#L227

like this:
https://github.com/istio/istio/blob/ce140478a652d34e7d1f2659eda12bec7e8a623e/mixer/pkg/server/server.go#L212

**Comment by hzxuzhonghu** [comment]
@ozevren We already process all errors, please check `mixer/pkg/server/server.go`

**Comment by hzxuzhonghu** [comment]
@ymesika any comments

**Comment by ozevren** [comment]
I don't understand what you mean. There are error return paths in code that doesn't call close before returning an error. Are you suggesting that making them close before returning error is not fixing the problem?

**Comment by hzxuzhonghu** [comment]
@ozevren The root cause is race detector is 8192 limit. But our goroutine pool size default is 1024 +1024.

How can wen guarantee not exceed 8192 when many cases concurrently run?

**Comment by ozevren** [comment]
I don't think they run concurrently. We are not specifying t.Parallel(). The test framework should not be running go-routines in parallel unless that is specified.

This test used to pass race test. I suspect the reason it is failing now is because of the naked returns that were introduced recently. Fixing that should fix the issue. In fact, it would be great if we add a test to go through the declared cases 5 times for each case, back-to-back. This should ensure that this category of problems won't be introduced again.

**Comment by hzxuzhonghu** [comment]
Thanks @ozevren . I misunderstand t.Run() for long time. You are right, thanks.

**Comment by ozevren** [comment]
You still are limiting the worker pool sizes in the PR. What happens when you remove them? Does the test pass?

**Comment by hzxuzhonghu** [comment]
>You still are limiting the worker pool sizes in the PR. What happens when you remove them? Does the test pass?

Yes, I have tested. It still passed.  Updated now

**Pull request merged**
