### PR TITLE
Update proxy SHA to 08d535

### PR DESCRIPTION
**Pull request by nrjpoddar**
SHA: 08d53544b4465545e095b1446ef8cc58471115e6

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@kyessenov fyi

**Comment by nrjpoddar** [comment]
@howardjohn how do I get this merged? It has another 7 people added to the reviewers list.

**Comment by howardjohn** [comment]
@nrjpoddar you don't need all of them, see the bottom of the page

```
Changes approved
1 approving review by reviewers with write access.
```

Our merging system, tide, will retest PRs to make sure they work with the latest changes that have been merged since the PR was submitted, see the status at https://prow.istio.io/tide

**Pull request merged**
