### PR TITLE
Scrape internal Grafana metrics

### LINKED ISSUE #12438: Internal Grafana metrics aren't collected
**Describe the bug**
[The internal metrics that Grafana exposes](http://docs.grafana.org/administration/metrics/) aren't configured in Prometheus when installing Grafana and Prometheus using the Helm chart. 

**Expected behavior**
Internal Grafana metrics are scraped by Prometheus.

**Steps to reproduce the bug**
1. Install Istio using Helm chart with `grafana.enabled=true`
2. Go to Prometheus targets list
3. Observe that Grafana container is not in the list

**Version**
Istio 1.0.5, Kubernetes 1.11.6

**Installation**
Helm chart with `grafana.enabled=true`

**Environment**
AWS, Kubernetes installed with kops

**Cluster state**
Can provide if required.

### PR DESCRIPTION
**Pull request by charleskorn**
This resolves #12438.

### CODE REVIEW

**Comment by charleskorn** [comment]
I will need a day or two to get approval for the CLA, I will post back here when this is approved.

**Comment by jmazzitelli** [comment]
this is good for Kiali. Just a heads up - in the next release of Kiali, it will expose its metrics on a different port (currently, it is exposed on the same IP:port as the /console and /api endpoints). So in the future, we'll need to specify another annotation "prometheus.io/port" for the kiali scrape to work. See: https://github.com/kiali/kiali/pull/900/files#diff-cbe6b632ae0a7103625b8e51b8757e7fR27

**Comment by charleskorn** [comment]
@jmazzitelli thanks for the heads up. Do you want me to amend my PR to include that? When will the Istio Helm charts install the next release of Kiali?

@douglas-reid / @jmazzitelli (not sure who is best to ask sorry): I can't see how those test failures are related to the change I've made - am I missing something?

**Comment by jmazzitelli** [comment]
> When will the Istio Helm charts install the next release of Kiali?

Kiali v0.16 was just released today. I have a [PR 11823](https://github.com/istio/istio/pull/11823) that I will try to merge in soon that will pull in the next release... once I get the tests to pass! In that PR, I have the annotations, also. But I also am getting odd test failures in my PR that look unrelated.

**Comment by jmazzitelli** [comment]
@charleskorn within this PR, you can remove the changes to the kiali deployment yaml - Kiali has been upgraded in Istio master and the scrape annotations are now in master.

**Comment by charleskorn** [comment]
I've finally been able to sign the CLA - sorry for the delay.

**Pull request merged**
