### PR TITLE
Fix some delta xds proxy logics

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
This is to sync logics with xds proxy. Found the inconsistencies when I was debugging.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
Is this kind of code refactor and no other change? I will take a closer look then

**Comment by hanxiaop** [comment]
> Is this kind of code refactor and no other change? I will take a closer look then

@hzxuzhonghu Not a refactor, but it only involves changes that are already in the xds proxy logic, many of which I noticed were made by you, and have not been added in delta xds.

**Review by hzxuzhonghu — APPROVED** [review]
lgtm

**Comment by hanxiaop** [comment]
try again /test integ-security-istiodremote

**Pull request merged**
