### PR TITLE
Add more log to sd integration test.

### PR DESCRIPTION
**Pull request by bianpengyuan**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@istio/wg-policies-and-telemetry-maintainers ptal, thanks!

**Comment by bianpengyuan** [comment]
@istio/wg-policies-and-telemetry-maintainers ptal, thanks!

**Comment by bianpengyuan** [comment]
@istio/wg-policies-and-telemetry-maintainers ptal, thanks!

**Comment by bianpengyuan** [comment]
Ping @istio/wg-policies-and-telemetry-maintainers ptal thanks!

**Review by kyessenov — APPROVED** [review]

**Pull request merged**
