### PR TITLE
Switch prometheus operator to scrape agent instead of envoy

### PR DESCRIPTION
**Pull request by howardjohn**
This matches the non prometheus operator and allows us to get
istio-agent metrics

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by douglas-reid** [comment]
Did you compare this with approaches like: https://github.com/istio/istio/issues/27328#issuecomment-698020196

I'm concerned about backwards compatibility for current releases.

**Comment by howardjohn** [comment]
@douglas-reid I think I was attempting to avoid and issue with that approach, which I have now realized probably applies to both.

if a user just uses Prom op objects directly, with nothing looking at prometheus.io/scrape labels, I think both approaches should work equally well (?)

However, if they are scraping prometheus.io labels (similar to your example, or through other means), they are now going to get double scraping. So really these configs should only be applied if they are not scraping based on prometheus.io labels?

**Comment by douglas-reid** [comment]
> @douglas-reid I think I was attempting to avoid and issue with that approach, which I have now realized probably applies to both.
> 
> if a user just uses Prom op objects directly, with nothing looking at prometheus.io/scrape labels, I think both approaches should work equally well (?)
> 
> However, if they are scraping prometheus.io labels (similar to your example, or through other means), they are now going to get double scraping. So really these configs should only be applied if they are not scraping based on prometheus.io labels?

i think Prom de-dupes targets. Adding the port to all deploys will certainly help alleviate the issue here (and in the linked comment).

**Comment by howardjohn** [comment]
> i think Prom de-dupes targets.

It might in some cases, but in the case of PodMonitor and ServiceMonitor it did not. Maybe within a single job it does

**Review by douglas-reid — APPROVED** [review]
Thanks for pushing this to completion.

**Pull request merged**
