### PR TITLE
move certmanager configs from bookinfo/routing to bookinfo/networking

### PR DESCRIPTION
**Pull request by yacut**
related to https://github.com/istio/istio/pull/6660

Cc @frankbu

### CODE REVIEW

**Comment by rshriram** [comment]
also @yacut please add a task or guide in Istio.github,io

**Comment by rshriram** [comment]
and rename egress rule to destination rule.

**Comment by rshriram** [comment]
Why do you need the destinationRule? I think auth already installs these rules.

**Comment by yacut** [comment]
OK. I removed the DestinationRule and will tomorrow add a task or guide in Istio.github.io

**Pull request merged**
