### PR TITLE
[experimental-dual-stack]fix bug:istiod will crash dual to the service with ExternalName type in k8s cluster

### PR DESCRIPTION
**Pull request by zhanghw0354**
**Please provide a description of this PR:**
Istiod will crash dual to the service with ExternalName type in k8s cluster
image
The error logs of istiod show below:
image

### CODE REVIEW

**Comment by zhlsunshine** [comment]
Hi @jacob-delgado, could this integration test can be ignored? Thanks!

**Comment by jacob-delgado** [comment]
I'll have to change this tomorrow. It'll require a change in istio/test-infra

**Comment by zhanghw0354** [comment]
> I'll have to change this tomorrow. It'll require a change in istio/test-infra

**Comment by zhanghw0354** [comment]
Hi @jacob-delgado ,can you ignore the integration test when you are not busy? Thanks

**Pull request closed without merging**
