### PR TITLE
Adding the build&test logic to release-1.2

### PR DESCRIPTION
**Pull request by icygalz**
/hold

### CODE REVIEW

**Comment by fpesce** [comment]
@icygalz I'm starting considering to land this change + istio/test-infra#1367 istio/test-infra#1351
If it can help pass Continuous Integration, we're stuck in a very unpredictable state for testing right now.

**Comment by howardjohn** [comment]
@fpesce @icygalz ready to merge?

**Comment by icygalz** [comment]
/hold cancel

This PR can be merge anytime

**Pull request merged**
