### PR TITLE
More output columns for 'istioctl pc routes' and 'clusters'

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/23987 by providing one line per virtual-host-route instead of one line per-overall route.  New columns DOMAINS, MATCH, CONFIG, and VS (virtual service) supply information.

The previous output is still available if `--verbose=false` is specified.

The previous version shows
```
NAME        VIRTUAL HOSTS
http.80     1
            1
            1
```

The new version shows

```
NAME                                  DOMAINS     MATCH                  VIRTUAL SERVICE
http.80                               *           /productpage           bookinfo.default
http.80                               *           /static*               bookinfo.default
http.80                               *           /login                 bookinfo.default
http.80                               *           /logout                bookinfo.default
http.80                               *           /api/v1/products*      bookinfo.default
https.443.https.mygateway.default     *           /*                     
                                      *           /healthz/ready*        
                                      *           /stats/prometheus*     
```

The 'CONFIG' column is empty here but indicates non-vanilla situations with values like `envoy.fault`.

The output is a bit wide for pods within the mesh:

```
NAME                                                                                 DOMAINS                                                        MATCH                  VIRTUAL SERVICE
istio-ingressgateway.istio-system.svc.cluster.local:15021                            istio-ingressgateway.istio-system                              /*                     
15014                                                                                istiod.istio-system                                            /*                     
kube-dns.kube-system.svc.cluster.local:9153                                          kube-dns.kube-system                                           /*                     
public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system.svc.cluster.local:80      public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system     /*                     
dashboard-metrics-scraper.kube-system.svc.cluster.local:8000                         dashboard-metrics-scraper.kube-system                          /*                     
9080                                                                                 details                                                        /*                     details.default
9080                                                                                 productpage                                                    /*                     productpage.default
9080                                                                                 ratings                                                        /*                     ratings.default
9080                                                                                 reviews                                                        /*                     reviews.default
metrics-server.kube-system.svc.cluster.local:443                                     metrics-server.kube-system                                     /*                     
public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system.svc.cluster.local:443     public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system     /*                     
istiod.istio-system.svc.cluster.local:853                                            istiod.istio-system                                            /*                     
tiller-deploy.kube-system.svc.cluster.local:44134                                    tiller-deploy.kube-system                                      /*                     
9090                                                                                 prometheus.istio-system                                        /*                     
15010                                                                                istiod.istio-system                                            /*                     
kubernetes-dashboard.kube-system.svc.cluster.local:443                               kubernetes-dashboard.kube-system                               /*                     
50051                                                                                addon-catalog-source.ibm-system                                /*                     
8000                                                                                 dashboard-metrics-scraper.kube-system                          /*                     
8000                                                                                 httpbin                                                        /                      httpbin.default
8000                                                                                 httpbin                                                        /*                     httpbin.default
80                                                                                   details.default.svc.cluster.local                              /*                     details.default
80                                                                                   httpbin.default.svc.cluster.local                              /                      httpbin.default
80                                                                                   httpbin.default.svc.cluster.local                              /*                     httpbin.default
80                                                                                   ibm-k8s-controller-default-backend.kube-system                 /*                     
80                                                                                   istio-ingressgateway.istio-system                              /*                     
80                                                                                   productpage.default.svc.cluster.local                          /*                     productpage.default
80                                                                                   public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system     /*                     
80                                                                                   ratings.default.svc.cluster.local                              /*                     ratings.default
80                                                                                   reviews.default.svc.cluster.local                              /*                     reviews.default
8081                                                                                 olm-operator-metrics.ibm-system                                /*                     
inbound|8000|http|httpbin.default.svc.cluster.local                                  *                                                              /*                     
inbound|8000|http|httpbin.default.svc.cluster.local                                  *                                                              /*                     
                                                                                     *                                                              /stats/prometheus*     
InboundPassthroughClusterIpv6                                                        *                                                              /*                     
inbound|8000|http|httpbin.default.svc.cluster.local                                  *                                                              /*                     
inbound|8000|http|httpbin.default.svc.cluster.local                                  *                                                              /*                     
InboundPassthroughClusterIpv6                                                        *                                                              /*                     
InboundPassthroughClusterIpv4                                                        *                                                              /*                     
InboundPassthroughClusterIpv4                                                        *                                                              /*                     
                                                                                     *                                                              /healthz/ready*        
```

An earlier version included information about the cluster, with a CLUSTER column and values such as "=> details.bookinfo.svc.cluster.local:9080" and "balance 20%/80%".  This made the output too wide for pods on the mesh although it looked nice on the ingress.

See comment below for the new output of `pc clusters`.

### CODE REVIEW

**Comment by esnible** [comment]
/retest
flake

**Comment by howardjohn** [comment]
`80                                                               *                                                  /*                                     `
These are on every single one. Should filter them or identify them in some way? Its basically a final fall through to pass through cluster (or 502, is passthrough disabled)

**Comment by esnible** [comment]
@howardjohn Good idea.  I wrote code to filter if it is passthrough.  I have not used passthrough disabled; remind me how to turn it on?  I am not sure if a 502 should be filtered or not.

I also added a `DR` DestinationRule column to `pc clusters` because if we display the VS on routes we should display the PC on clusters.  While I was implementing it a user pinged me to ask why his DR wasn't working.  (He didn't realize a DR did nothing without a ServiceEntry).  I believe showing the VS and DR names here will help people understand their rules better.

**Comment by esnible** [comment]
Holding while I diagnose https://github.com/istio/istio/issues/24925

**Comment by esnible** [comment]
/retest
flake

**Comment by rvennam** [comment]
Tested the latest:
image

This is great and will prove to be extremely valuable for debugging quickly.

Minor feedback/thoughts:
- The NAME column seems useless at first, but protocol and port are important. Maybe a column for port and protocol instead of NAME?
- I would like to see the MATCH column first
- What does the CONFIG column show? It's blank for me
- Expand VS -> Virtual Service

**Comment by esnible** [comment]
/retest
flake

**Comment by ayj** [comment]
@esnible, can you update the PR description with the latest sample usage?

**Comment by esnible** [comment]
> can you update the PR description with the latest sample usage?

@ayj Done

**Comment by ayj** [comment]
> * What does the CONFIG column show? It's blank for me

I had the same question. It looks like it is showing EnvoyFilter's that apply to the route? It would be worth spelling that out. 

Also, are there any other columns you foresee adding in the future? 

> * Expand VS -> Virtual Service

This makes sense to me.

**Comment by esnible** [comment]
I forgot to mention this PR also gives new output for `pc clusters`:

```
SERVICE FQDN                                                                     PORT      SUBSET         DIRECTION     TYPE             DESTINATION RULE
BlackHoleCluster                                                                 -         -              -             STATIC           
InboundPassthroughClusterIpv4                                                    -         -              -             ORIGINAL_DST     
InboundPassthroughClusterIpv6                                                    -         -              -             ORIGINAL_DST     
PassthroughCluster                                                               -         -              -             ORIGINAL_DST     
addon-catalog-source.ibm-system.svc.cluster.local                                50051     -              outbound      EDS              
agent                                                                            -         -              -             STATIC           
catalog-operator-metrics.ibm-system.svc.cluster.local                            8081      -              outbound      EDS              
dashboard-metrics-scraper.kube-system.svc.cluster.local                          8000      -              outbound      EDS              
details.default.svc.cluster.local                                                9080      -              outbound      EDS              
httpbin.default.svc.cluster.local                                                8000      -              outbound      EDS              
httpbin.default.svc.cluster.local                                                8000      http           inbound       STATIC           
ibm-k8s-controller-default-backend.kube-system.svc.cluster.local                 80        -              outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local                              80        -              outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local                              443       -              outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local                              15021     -              outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local                              15443     -              outbound      EDS              
istiod.istio-system.svc.cluster.local                                            443       -              outbound      EDS              
istiod.istio-system.svc.cluster.local                                            853       -              outbound      EDS              
istiod.istio-system.svc.cluster.local                                            15010     -              outbound      EDS              
istiod.istio-system.svc.cluster.local                                            15012     -              outbound      EDS              
istiod.istio-system.svc.cluster.local                                            15014     -              outbound      EDS              
kube-dns.kube-system.svc.cluster.local                                           53        -              outbound      EDS              
kube-dns.kube-system.svc.cluster.local                                           9153      -              outbound      EDS              
kubernetes-dashboard.kube-system.svc.cluster.local                               443       -              outbound      EDS              
kubernetes.default.svc.cluster.local                                             443       -              outbound      EDS              
metrics-server.kube-system.svc.cluster.local                                     443       -              outbound      EDS              
mgmtCluster                                                                      15021     mgmt-15021     inbound       STATIC           
node-local-dns.kube-system.svc.cluster.local                                     53        -              outbound      EDS              
olm-operator-metrics.ibm-system.svc.cluster.local                                8081      -              outbound      EDS              
productpage.default.svc.cluster.local                                            9080      -              outbound      EDS              
prometheus.istio-system.svc.cluster.local                                        9090      -              outbound      EDS              
prometheus_stats                                                                 -         -              -             STATIC           
public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system.svc.cluster.local     80        -              outbound      EDS              
public-crf2795d8b4d834ee593f06f52f2289261-alb1.kube-system.svc.cluster.local     443       -              outbound      EDS              
ratings.default.svc.cluster.local                                                9080      -              outbound      EDS              
reviews.default.svc.cluster.local                                                9080      -              outbound      EDS              
sds-grpc                                                                         -         -              -             STATIC           
tiller-deploy.kube-system.svc.cluster.local                                      44134     -              outbound      EDS              
xds-grpc                                                                         -         -              -             STRICT_DNS       
zipkin                                                                           -         -              -             STRICT_DNS       
```

**Comment by esnible** [comment]
> What does the CONFIG column show? It's blank for me

@rvennam @ayj In this PR the CONFIG column was intended to show `envoy.fault` if there is a synthetic "fault" (40x, 50x) on the route.  However, it is perhaps too rare, so I will remove it.

**Pull request merged**
