### PR TITLE
Remove proxy via agent option

### PR DESCRIPTION
**Pull request by howardjohn**
This has been stable for a number of releases now

I put a bunch of assignees since I am not sure if there is some usage of this I wasn't aware of

### CODE REVIEW

**Review by adiprerepa — COMMENTED** [review]
so after this, there is no way to connect to envoy directly? are we sure we want to do this?

It seems like a good "backup" option for if istio-agent fails

**Comment by howardjohn** [comment]
> It seems like a good "backup" option for if istio-agent fails

At this I think we are confident in the stability, I hope. We have had it for quite a few releases, and for the most part its not even a good backup at this point. We have no tests and a large amount of functionality depends on the agent

**Comment by adiprerepa** [comment]
> > It seems like a good "backup" option for if istio-agent fails
> 
> At this I think we are confident in the stability, I hope. We have had it for quite a few releases, and for the most part its not even a good backup at this point. We have no tests and a large amount of functionality depends on the agent

yeah, fair enough. I remember it being useful for initial delta stuff, but thats already pretty niche.

**Review by hzxuzhonghu — COMMENTED** [review]
lgtm

**Comment by ramaraochavali** [comment]
lgtm

**Review by lei-tang — COMMENTED** [review]
lgtm

**Comment by howardjohn** [comment]
Not stale @istio/wg-networking-maintainers

**Review by ramaraochavali — APPROVED** [review]

**Pull request merged**
