### PR TITLE
enable multiple Set-Cookie headers

### LINKED ISSUE #14240: Allow DirectHttpResponses to return multiple keys of the same name.
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Allow *DirectHttpResponse* to return multiple header key/value pairs with the same key.

```
e.g.

Set-Cookie: <cookie-name-1>=<cookie-value-1>
Set-Cookie: <cookie-name-2>=<cookie-value-2> 
```

**Describe alternatives you've considered**

1. Tried folding multiple cookies into the same header. Firefox and chrome ignored all except the first declared.

2. Attempted to combine `DirectHttpResponse` and `RouteDirectives`. However, `DirectHttpResponse` is only applied on a non-OK response https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#DirectHttpResponse, while `RouteDirectives` are only applied on OK responses https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Rule

**Additional context**

*DirectHttpResponse* currently allows Mixer adapters to send a custom HTTP status code and map of headers after a 401 response. This enables adapters to do things like initiate redirects or set cookies.

Unfortunately, some default HTTP headers do not support multiple being folded into the same header field, but instead require two separate headers of the same name. 

See `Set-Cookie` and its accompanying [RFC6265](https://tools.ietf.org/html/rfc6265#section-3).
```
Excerpt from RFC6265:
An origin server can include multiple Set-Cookie header fields in a single response.

Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.  The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616]) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.
```

### PR DESCRIPTION
**Pull request by elevran**
This is an alternative to [PR #2308 in istio/proxy](https://github.com/istio/proxy/pull/2308), localizing the change to the mixer code base.

**What this PR does / why we need it**:
This PR allows setting multiple `Set-Cookie` headers from a mixer response.
Per the RFC, Set-Cookie headers should be sent on separate lines. However, the DirectHttpResponse object encodes headers as a map<key,value> which prevents multiple headers from being specified.
This PR's treats the returned value as a comma separated list. While incomplete in handling all possible cookie variants and attributes (e.g., `Expires` attribute may contain a comma in the date), it handles the common case of session based cookies and allows future extension based on customer feedback.

Full discussion is on [#14240](https://github.com/istio/istio/issues/14240)

- split DirectHttpResponse handling to its own function (ease testing, will be added)
- split Set-Cookie header to multiple APPEND directives

**Which issue this PR fixes**:
fixes #14240

**Special notes for your reviewer**:
This is an alternative to [PR #2308 in istio/proxy](https://github.com/istio/proxy/pull/2308), localizing the change to the mixer code base.

`Set-Cookie` is not an Envoy inline header so will not get folded by the proxy if multiple headers are added. The current "cookie cutter" is simple and works for a subset of the cookies. This is noted in the code documentation.

**Release note**:
```release-note
FIX: mixer direct response may now include multiple Set-Cookie values, by specifying a comma separated list of cookies to send. The cookies must not include other commas (e.g., in Expire attribute) 
```

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by kyessenov** [comment]
I'm in favor of this approach. I think it makes sense to keep the proxy functions less smart, and instead handle edge cases like `set-cookie` during processing in Mixer. The effort to ensure correctness of parsing in C++ is much greater than golang IMHO.

WDYT @mandarjog @geeknoid ?

**Comment by kyessenov** [comment]
LGTM pending an integration test for route directive (see mixer/test/client/route_directive/)

**Comment by elevran** [comment]
@kyessenov PTAL - test for multiple `Set-Cookie` header added to directive.

**Comment by mandarjog** [comment]
We discussed this at the wg meeting yesterday and adding this intelligence in go code is preferred, so this PR should go Thru.

**Comment by elevran** [comment]
@kyessenov thanks for the approval. Bot seems to want an LGTM label - is that automatic or manually added?
I'll add the test for coverage separately

**Pull request merged**
