### PR TITLE
Fix issue #13287. Change RLock to Lock

### PR DESCRIPTION
**Pull request by crazyxy**
Issue #13287

### CODE REVIEW

**Comment by crazyxy** [comment]
> Did you attempt to reproduce this and see this fixed it? Logically I think the fix seems good, but would be great to have more confidence.

I didn't reproduce this. I have another simple code which reproduce the problem and using `Lock` can fix the problem.

```go
package main

import (
	"sync"
)

func main() {
	lock := sync.RWMutex{}
	wg := sync.WaitGroup{}
	x := -1
	for i := 1; i <= 100; i++ {
		go func(y int) {
			wg.Add(1)
			defer wg.Done()
			lock.RLock()
			if x != y {
				x = y
			}
			lock.RUnlock()
		}(i)
	}

	wg.Wait()
}

**Comment by kramerul** [comment]
There is also another usage of `RLock` in `updateClusterInc`, which is not correct, because the endpoints are modified within the section. 
In my point of view, `RWMutex` should be replaced by `Mutex` in this file to avoid the incorrect usage of `RWMutex`.

**Comment by howardjohn** [comment]
I confirmed this fixes the race manually. Not as good as a regression test but better than nothing

**Comment by howardjohn** [comment]
This got merged in with another PR it looks like: https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L922

Thanks for the change

**Comment by fpesce** [comment]
> This got merged in with another PR it looks like: https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L922

Yes the PR that changed it was #14254 and on a related note: I'm pretty sure eds.go diverged from 1.0 on the mutex strategy c.f. #14339 :P

**Pull request closed without merging**
