### PR TITLE
Enable STS tests

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Enable all the STS integration tests.

https://github.com/istio/istio/issues/20133

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
Need to update proxy SHA when this PR is merged.
https://github.com/istio/proxy/pull/2700

**Comment by howardjohn** [comment]
```
--- FAIL: TestTokenFetchFailureTwo (1.05s)
    mockserver.go:203: Registered handler for endpoints:
        /v1/projects/-/serviceAccounts/service-1234567@gcp-sa-meshdataplane.iam.gserviceaccount.com:generateAccessToken
        /v1/identitybindingtoken
    setup.go:200: 2020-02-21 10:56:39.459970039 -0800 PST m=+12.337127383 check if all servers in the STS flow are up and ready
    setup.go:206: set up server address to dial 127.0.0.1:20711
    setup.go:218: 2020-02-21 10:56:39.462870844 -0800 PST m=+12.340028110 all servers in the STS flow are up and ready
    token_failure_test.go:76:
        Expected
            <int>: 1
        to be >
            <int>: 1
FAIL
[2020-02-21 10:56:39.489][168113][warning][main] [external/envoy/source/server/server.cc:489] caught SIGTERM
[2020-02-21 10:56:39.489][168113][info][main] [external/envoy/source/server/server.cc:602] shutting down server instance
[2020-02-21 10:56:39.489][168113][info][main] [external/envoy/source/server/server.cc:556] main dispatch loop exited
[2020-02-21 10:56:39.489][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0
[2020-02-21 10:56:39.489][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-02-21 10:56:39.489][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 1d997c17e2321d43565c80eb828f7bdcb78de7e2/1.13.0/Clean/RELEASE/BoringSSL
[2020-02-21 10:56:39.489][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7fbcca095520]
[2020-02-21 10:56:39.498][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Server::ConnectionHandlerImpl::ActiveTcpListener::~ActiveTcpListener() [0x55b39c77f76e]
[2020-02-21 10:56:39.506][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Server::ConnectionHandlerImpl::ActiveTcpListener::~ActiveTcpListener() [0x55b39c77f915]
[2020-02-21 10:56:39.514][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: Envoy::Server::ConnectionHandlerImpl::~ConnectionHandlerImpl() [0x55b39c78162b]
[2020-02-21 10:56:39.522][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Server::InstanceImpl::terminate() [0x55b39c7225b8]
[2020-02-21 10:56:39.530][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: Envoy::Server::InstanceImpl::run() [0x55b39c7260eb]
[2020-02-21 10:56:39.538][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::MainCommonBase::run() [0x55b39b484a38]
[2020-02-21 10:56:39.546][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: main [0x55b39b483952]
[2020-02-21 10:56:39.546][168113][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: __libc_start_main [0x7fbcc9ee8bbb]
FAIL    istio.io/istio/security/pkg/stsservice/test/failure_sts_token_fetch     12.604s

```

**Comment by howardjohn** [comment]
I think its an issue locally

**Comment by JimmyCYJ** [comment]
> These tests do not seem to run locally, I get errors like `E0221 10:56:28.942559587 168113 oauth2_credentials.cc:220] oauth_fetch: {"created":"@1582311388.942539213","description":"Failed to load file","file":"external/com_github_grpc_grpc/src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"","referenced_errors":[{"created":"@1582311388.942538001","description":"No such file or directory","errno":2,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}`

It seems that gRPC library fail to open files, the test sets up two files, one for initial JWT token and one for CA cert. Perhaps your Istio ROOT PATH is not equal to istioEnv.IstioSrc used in the test.
The tests pass in prow:
 https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/21334/unit-tests_istio/8974/build-log.txt

**Comment by howardjohn** [comment]
Looks like the failing test is an STS one, are we enabling a flaky test?

**Comment by JimmyCYJ** [comment]
> Looks like the failing test is an STS one, are we enabling a flaky test?

It is a known flaky test, I am going to fix it. https://github.com/istio/istio/issues/19918

**Pull request merged**
