### PR TITLE
pkg/queue: optimize the delay queue and resolve some TODOs

### PR DESCRIPTION
**Pull request by panjf2000**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
/ok-to-test

**Comment by stevenctl** [comment]
Looks nice! Could you make sure we have test coverage that covers the capacity shrinking case?

**Comment by panjf2000** [comment]
> Looks nice! Could you make sure we have test coverage that covers the capacity shrinking case?

I'll add the tests for it.

**Comment by panjf2000** [comment]
Please take a look at the latest code.@stevenctl

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
