### PR TITLE
fix accessLogFormat with req_without_query and JSON encoding

### PR DESCRIPTION
**Pull request by lavoiedn**
**Please provide a description of this PR:**

Fixing a small issue when configuring access logs in JSON format.

### CODE REVIEW

**Comment by lavoiedn** [comment]
Relates to: https://github.com/istio/istio/issues/39271

**Review by ramaraochavali — APPROVED** [review]

**Comment by ramaraochavali** [comment]
@lavoiedn Thank you. Can you please add a test for this?

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/blob/master/tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go - You can try an integration test similar to this.

If it is taking too much time for you, please let me know - we can merge this and do a follow-up

**Comment by lavoiedn** [comment]
I tried to get something done, but unfortunately it seems like my current setup (`podman` on WSL2 Ubuntu 20.04) cannot run the integration tests successfully 😞

Here is what I had so far, but I didn't get to test them, only ensure that `go build` ran without issues: https://github.com/istio/istio/compare/master...lavoiedn:access-log-json-req-wo-query-error-test

I was running `go test -tags=integ ./tests/integration/pilot/networking/accesslog_test.go`, istiod and the gateways were starting in `minikube` but then the sidecars where erroring out with an error similar to this one:

```
Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1641705239788335054.txt1249728033, exit status 2
```

It's strange because I managed to reproduce this issue with an istio sidecar using the 1.13.4 helm charts just yesterday, but the integration tests deployments were failing 🤔

I may have to call it quits on writing the integration tests and take you up on the offer to merge and do a follow-up.

**Comment by ramaraochavali** [comment]
Ok. Can you please add a release notes?

**Comment by ramaraochavali** [comment]
@lavoiedn Thank you

**Comment by lavoiedn** [comment]
Thank you for reviewing and helping me get the PR ready! Next time I contribute, I'll try to get the tests running for real

**Review by GregHanson — APPROVED** [review]

**Comment by jpbelangerupgrade** [comment]
@ramaraochavali I see the 1.14 cherrypick label added on June 4th, but latest 1.14 release still doesn't include this change. Is something missing to get it in 1.14?

**Comment by ericvn** [comment]
Sometimes the labels don't work (certainly if added after PR was closed (wasn't the case here)). Attempted a manual cherry pick. Will see if the 1.14 RMs approve.

**Comment by jpbelangerupgrade** [comment]
Thanks @ericvn appreciate the quick response.

**Pull request merged**
