### PR TITLE
[Kiali][release 1.2] update kiali version

### PR DESCRIPTION
**Pull request by jmazzitelli**
(cherry picked from commit 85a6e6a79beae252b11a61674d46804b554d9ecd)

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Obviously, will need someone to test this prior to merge just to verify.. don't want to screw up 1.2 release due to some unforeseen issue with this kiali PR

**Comment by sdake** [comment]
@jmazzitelli can you close this PR, then wait for the master PR to merge, then cherrypick?  If you don't do this, the commit ids produced by `cherry-pick -x` point to the wrong place.

I know the boskos resource problem has been a problem today; hopefully, that starts to sort itself out over the next few days.

Cheers
-steve

**Comment by sdake** [comment]
Also @jmazzitelli typically the PR submitter tests their own work.  Do you mean testing this work on K8s (instead of OpenShift)?

Cheers
-steve

**Pull request closed without merging**
