### PR TITLE
Bump gateway api to 0.8.0

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
:thinking: I thought we need https://github.com/kubernetes-sigs/controller-runtime/pull/2460.

Nice work if you found a way around it!

**Review by howardjohn — APPROVED** [review]
Nice! TBH I don't get how it works but awesome

**Review by ericvn — APPROVED** [review]

**Comment by keithmattix** [comment]
Do we need to cherry-pick this?

**Comment by howardjohn** [comment]
If feasible it would be nice so we are not on an RC release.

**Comment by ericvn** [comment]
> Do we need to cherry-pick this?

I have a PR that already was doing rc2 so updating with these changes: https://github.com/istio/istio/pull/46677

**Pull request merged**
