### PR TITLE
Fix #2150 istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml

### LINKED ISSUE #2150: Failed istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml
```
# istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml

Error: configuration is invalid: 1 error occurred:

* name or service is mandatory for a service reference
```
I think it was cased by this line.
https://github.com/istio/istio/blob/d1c939b5d6a23c496e0c1a9a1a02419b3837c93d/pilot/model/validation.go#L256
```
func ValidateIstioService(svc *routing.IstioService) (errs error) {
	if svc.Name == "" && svc.Service == "" {
		errs = multierror.Append(errs, errors.New("name or service is mandatory for a service reference"))
	}
```
in route-rule-all-v1.yaml:
```
match:
    source:
      labels:
        istio: ingress

source is a type of IstioService, but has no name or service. 
```
add service name will be ok.
before: https://github.com/istio/istio/blob/master/samples/bookinfo/kube/route-rule-all-v1.yaml
after:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: productpage-default
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: productpage
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-deny-all
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
  precedence: 2
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-products-api
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          prefix: /api/v1/products
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-logout
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /logout
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-login
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /login
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-landing
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /productpage
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default
spec:
  destination:
    name: reviews
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-default
spec:
  destination:
    name: ratings
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: details-default
spec:
  destination:
    name: details
  precedence: 1
  route:
  - labels:
      version: v1

```

### PR DESCRIPTION
**Pull request by yaoguais**
….yaml

**What this PR does / why we need it**:

fix the sample that can not run.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes #2150

**Special notes for your reviewer**:

it may be caused by the validation.

https://github.com/istio/istio/blob/d1c939b5d6a23c496e0c1a9a1a02419b3837c93d/pilot/model/validation.go#L256
```
func ValidateIstioService(svc *routing.IstioService) (errs error) {
	if svc.Name == "" && svc.Service == "" {
		errs = multierror.Append(errs, errors.New("name or service is mandatory for a service reference"))
	}
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by linsun** [comment]
Thanks for the PR, i believe someone at IBM hit this also recently.  You may also want to update these 2 files:

./samples/bookinfo/consul/route-rule-all-v1.yaml
./samples/bookinfo/eureka/route-rule-all-v1.yaml

**Comment by yaoguais** [comment]
I don't have consul or eureka environment, and I can't test this locally.

**Comment by linsun** [comment]
ok understood, please make sure your CLA is signed.

**Comment by yaoguais** [comment]
I signed it!

**Comment by yaoguais** [comment]
Yes, it should be istio-ingress. I will check it.

**Comment by James-Dao** [comment]
It seems not to be work, such as deny ingress, after creating routerrule successfully, it still can access destination from ingress, why?

**Comment by rshriram** [comment]
I am fixing it in another PR

**Comment by rshriram** [comment]
sync your branch with istio/istio master please. Else, circleci tests will fail.

**Comment by rshriram** [comment]
https://github.com/istio/istio/pull/2155 for ingress fix

**Comment by rshriram** [comment]
Sorry for the confusion. I suggest you close this PR, because the one I just sent is removing all ingress based routing from route-rule-all-v1.yaml. The reason for doing so is because deny-all does not work in ingress (using fault injection - omitting a lengthy technical explanation aka implementation mess). This should be addressed in @ZackButcher 's Gateway PR series #2106  and more..

**Pull request closed without merging**
