### PR TITLE
Add tests to verify TCP filter sends connection.id in Check() and Rep…

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Add tests to verify TCP filter sends connection.id in Check() and Report() calls.

### CODE REVIEW

**Comment by douglas-reid** [comment]
For the dep ensure bits, do we need to update the istio-contrib repo?  @ldemailly can you advise?

**Comment by ldemailly** [comment]
you can't change Gopkg.lock without following the steps in
https://github.com/istio/istio/wiki/Vendor-FAQ#how-do-i-add--change-a-dependency

**Comment by JimmyCYJ** [comment]
I am not sure if I need to change .lock file.
In istio.deps, istio.io/api is using SHA [9d978d](9d978d76653da8b7b4bd6421b7e8f9925d8c79ea), which includes istio/api@[ec13aa](ec13aab7d0788f57693f4697a0f1185dd54bce32) that defines message NetworkFailPolicy in api/mixer/v1/config/client/client_config.proto.

When I update proxy SHA in istio.deps, I break test istio.io/istio/mixer/test/client/network_policy/network_policy_test.go, because it does not use the new NetworkFailPolicy config. 

I modified mixer/test/client/env/v2_config.go in this PR to use NetworkFailPolicy, but I got compile failure.
"env/v2_config.go:109:36: undefined: client.NetworkFailPolicy
env/v2_config.go:111:33: v2.Transport.NetworkFailPolicy.Policy undefined (type client.TransportConfig_NetworkFailPolicy has no field or method Policy)
env/v2_config.go:113:33: v2.Transport.NetworkFailPolicy.Policy undefined (type client.TransportConfig_NetworkFailPolicy has no field or method Policy)
"
Seems that I need to update istio.io/istio/vendor/istio.io/api/mixer/v1/config/client/client_config.pb.go

**Comment by ldemailly** [comment]
can you follow
https://github.com/istio/istio/wiki/Vendor-FAQ#how-do-i-add--change-a-dependency
and let me know if you encounter any issue

**Comment by ldemailly** [comment]
this PR isn't using your vendor PR

**Comment by ldemailly** [comment]
build+tests are green, merging https://github.com/istio/vendor-istio/pull/15

**Comment by ldemailly** [comment]
last update: can you cd vendor; git checkout master; git pull
and then cd ..; git diff vendor

should point to new head/master sha: 1c8002038e1782d4a38e22f8e3c328b51b764664

git add vendor; update the PR

and we can merge this :-)

**Comment by JimmyCYJ** [comment]
@ldemailly  Thanks a lot for helping me waling through this vendor update. 
git diff vendor points to new commit 1c8002038e1782d4a38e22f8e3c328b51b764664.
I have added vendor into this PR.

**Comment by ldemailly** [comment]
filled #3810 for the weird test failure

**Pull request merged**
