### PR TITLE
Initial implementation of Telemetry for prometheus metrics and stackdriver metrics

### PR DESCRIPTION
**Pull request by howardjohn**
This provides an initial implementation of the metrics portion of the Telemetry API.

This does *not* yet remove the envoyfilters and switch to native code by default. We may get to that in 1.12, but will be a split PR to reduce complexity. For now, a user should delete the envoyfilters then apply a Telemetry (or set default provider).

Initial benchmarks show a small performance improvement, mostly in Listener:
```
BenchmarkInitPushContext/telemetry-6              641355              1567 ns/op             664 B/op         17 allocs/op
BenchmarkInitPushContext/telemetry-native-6       783992              1528 ns/op             664 B/op         17 allocs/op

BenchmarkRouteGeneration/telemetry-6                1257            901918 ns/op                32.14 kb/msg             2.000 resources/msg      644173 B/op       6347 allocs/op
BenchmarkRouteGeneration/telemetry-native-6         1309            856273 ns/op                32.14 kb/msg             2.000 resources/msg      643276 B/op       6325 allocs/op

BenchmarkClusterGeneration/telemetry-6               241           4750415 ns/op               188.4 kb/msg            410.0 resources/msg       2395737 B/op      37259 allocs/op
BenchmarkClusterGeneration/telemetry-native-6                254           4758618 ns/op               188.4 kb/msg            410.0 resources/msg       2394857 B/op      37238 allocs/op

BenchmarkListenerGeneration/telemetry-6                      699           1715602 ns/op                31.06 kb/msg             6.000 resources/msg      936320 B/op      16604 allocs/op
BenchmarkListenerGeneration/telemetry-native-6               771           1514333 ns/op                23.43 kb/msg             6.000 resources/msg      859686 B/op      16224 allocs/op

BenchmarkNameTableGeneration/telemetry-6                  354374              2880 ns/op                 0 kb/msg                1.000 resources/msg         456 B/op          7 allocs/op
BenchmarkNameTableGeneration/telemetry-native-6           377917              2759 ns/op                 0 kb/msg                1.000 resources/msg         456 B/op          7 allocs/op

```

### CODE REVIEW

**Review by douglas-reid — COMMENTED** [review]
Thanks for tackling!  Quick first pass looks reasonable. I got lost a bit when trying to plow through some of the looping, so my initial comments are mostly about clarifying the context and expected behaviors.

**Review by bianpengyuan — APPROVED** [review]
Looks good to me. Thanks a lot!

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
