### PR TITLE
Remove ClusterLocal structure from Service

### PR DESCRIPTION
**Pull request by nmittler**
This was originally added to support a second set of host/vips for Kubernetes Multi-Cluster Services (MCS). We've since gone with a different approach and this is no longer needed.

Moving the hostname and cluster VIPs to the top-level in Service.

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@nmittler what's the different approach?

**Comment by nmittler** [comment]
@hzxuzhonghu  we're now using a separate (synthetic) service to represent the MCS `clusterset.local` host. So many of the previous changes are effectively now reverted.

**Comment by hzxuzhonghu** [comment]
Seems just one change: svc hostname revert. LGTM

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
