### PR TITLE
cluster: cleanup ServiceInstances usage

### PR DESCRIPTION
**Pull request by howardjohn**
We had a bit of a code smell earlier, where we create a fake struct because the function signature expects it -- but we don't actually use the data. This has led to bugs in the past.

I think its best to pass in only what we need. Here I make a new type that is just a Service+Port+TargetPort, without the endpoint information.

Part of https://github.com/istio/istio/issues/45241

lmk what you think @ramaraochavali @hzxuzhonghu

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Idea makes sense to me. Will leave it for @hzxuzhonghu's opinion otherwise I will approve

**Comment by hzxuzhonghu** [comment]
LGTM, ServiceEndpoint name is a little large, usually we would think an endpoint must have an associated address

**Comment by ramaraochavali** [comment]
> LGTM, ServiceEndpoint name is a little large, usually we would think an endpoint must have an associated address

I agree that Endpoint is little confusing in the name. Should we call `TargetInstance` or `ServiceTarget`?

**Comment by howardjohn** [comment]
Updated then name

**Review by ramaraochavali — APPROVED** [review]

**Pull request merged**
