### PR TITLE
Make prow e2e test failure actually fail

### PR DESCRIPTION
**Pull request by sebastienvas**
Fixes issue introduced by istio/istio#3542, which returns the exit code of tee instead of the exit code of make.

### CODE REVIEW

**Comment by mattdelco** [comment]
I'm doubtful that this will fix the issue.  Each line in a makefile recipe normally executes in a different shell invocation so I wouldn't expect the state set by the first line to carry over to the second.  You might have to combine the lines together (possibly easier said than done).

**Comment by sebastienvas** [comment]
@mattdelco Thanks!

**Comment by ldemailly** [comment]
wow thx for finding and fixing this!

**Pull request merged**
