### PR TITLE
Update Jaeger to 1.9

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by douglas-reid** [comment]
Should this be against `master` now, or is this needed for 1.1 ?

**Comment by objectiser** [comment]
@aljesusg Is Jaeger 1.9 required for Kiali in 1.1? If not, then I will move the change to master.

**Comment by objectiser** [comment]
@douglas-reid I have opened #11185 against master, so will close this one.

**Comment by objectiser** [comment]
Sorry closed by mistake - kiali does need updated version in 1.1.

**Comment by linsun** [comment]
@wenchenglu @duderino can we get this approved for 1.1?

**Pull request merged**
