### PR TITLE
Adding codecov threshold file

### PR DESCRIPTION
**Pull request by hklai**

### CODE REVIEW

**Comment by kyessenov** [comment]
@hklai Have you tried the new codecov feature of defining multiple threshold by paths:
https://docs.codecov.io/docs/commit-status

**Comment by hklai** [comment]
@kyessenov I am close to ditching codecov.io for now. Their reports look noisy, and they PR gating check does not always show up. For now it seems to show up in PRs merging to master only, but not the others.

With all these changes at least I managed to get some primitive html UI to see the coverage.
e.g. https://252272-74175805-gh.circle-artifacts.com/0/go/out/codecov/baseline/coverage.html#file0

**Pull request merged**
