### PR TITLE
Run updateVersion.sh

### PR DESCRIPTION
**Pull request by andraxylia**
Was missing from #696
```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
we should really do something about those generated files
/lgtm

**Comment by ldemailly** [comment]
sadly it's not passing - with 
W0908 05:35:54.585] [libprotobuf ERROR external/mixerclient_git/src/report_batch.cc:78] Mixer Report failed with: UNAVAILABLE

**Comment by ldemailly** [comment]
the rbac-auth almost passed minus the TestDbRouting failure
and the one failing isn't using the files that are changed
so merging

**Comment by rshriram** [comment]
Why did you merge this ? RBAC no auth was failing.

**Comment by rshriram** [comment]
Why was this merged despite failing the only passing test? (RBAC no auth)?
Pilot is back to red.

**Comment by rshriram** [comment]
As of PR (https://github.com/istio/istio/pull/634) we finally managed to get the basic stuff back to green. This PR however breaks everything due to force merging despite failing tests.

**Comment by ldemailly** [comment]
the failure is unrelated as mentionned and this pr does make auth work for all but tcp test

**Pull request merged**
