### PR TITLE
Merge branch 'release-1.1' into master

### PR DESCRIPTION
**Pull request by howardjohn**
Do not merge label is added since I think we need to do something extra to ensure we don't squash the commits

This change needs to be manually merged and NOT SQUASHED by an admin. We should probably squash all of my commits into one prior to merging, as they won't get squashed

### CODE REVIEW

**Comment by ozevren** [comment]
There is a legitimate lint problem in the PR. The codecov failure seems benign.

**Comment by ozevren** [comment]
circle:test failure is a known flake:
TestProcessor_EventAccumulation_WithFullSync

**Comment by howardjohn** [comment]
> circle:test failure is a known flake:
> TestProcessor_EventAccumulation_WithFullSync

Thanks, I was wondering about that one.

I have a fix for the lint and integ tests, but I want to let the other tests finish first so I can fix all the issues in one go

**Comment by ozevren** [comment]
The istio-integ-k8s-tests failure is legitimate:
 /home/prow/go/src/istio.io/istio/install/kubernetes/helm/istio/values-e2e.yaml: no such file or directory

This needs to be fixed.

**Comment by howardjohn** [comment]
This is a merge PR from commits to repo that require CLA. Setting CLA to yes

**Comment by rshriram** [comment]
fix tests please

**Comment by howardjohn** [comment]
istio-pilot-multicluster-e2e is failing already in release-1.1. All the other failures are the same (a real failure) working on now

**Comment by yangminzhu** [comment]
The `TestRBACForEgressGateway` failed probably due to some code change in release-1.1 that is not compatible with the master branch.

If you look at the diff in `pilot/pkg/networking/plugin/authn/authentication.go`, add the similar changes in in `pilot/pkg/networking/plugin/authz/rbac.go` might fix the test. Most likely related to https://github.com/istio/istio/pull/12071

@rshriram

**Comment by duderino** [comment]
Thank you @howardjohn for hammering away at this

**Comment by howardjohn** [comment]
I think we have everything passing as expected now...

multicluster e2e is a known failure

**Pull request merged**
