### PR TITLE
Adding sidecar annotations to configure iptables.

### PR DESCRIPTION
**Pull request by nmittler**
Also had to change the default istioctl flag defaults for
includeInboundPorts/includeIPRanges to be "*", since "" is a valid
value (meaning re-direct nothing) and can't be considered the same
as "*".

Fixes: #4703

### CODE REVIEW

**Comment by nmittler** [comment]
@ayj I didn't see a way to test the configmap changes ... any ideas?

**Comment by nmittler** [comment]
@costinm, mind taking a look at the new annotations?

**Comment by ayj** [comment]
> @ayj I didn't see a way to test the configmap changes ... any ideas?

We don't have great e2e test coverage for all of the end-user sidecar injection config maps variants. You could copy the idea behind `inject_test.go` but applied at the webhook `inject` function using the configmap as configuration input. This could also help increase test coverage of the config reload watcher as well. cc @yusuoh

**Comment by nmittler** [comment]
@sebastienvas looks like prow is having trouble creating the clusters ... any ideas?

**Comment by ayj** [comment]
Opened https://github.com/istio/istio/issues/4862 to track "failed to acquire resource" issue.

**Comment by stephen-dahl** [comment]
is using this documented somewhere?

**Comment by nmittler** [comment]
I don't believe it is currently.  I had created https://github.com/istio/istio/issues/4920 a while back as a tracking issue for documenting all annotations.

**Pull request merged**
