### PR TITLE
[WIP] add inbound listeners to the gateways

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
to enforce policies and collect telemetry on the inbound
traffic (into the listeners)

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
@rshriram Note that the outbound and inbound listeners are built differently. For an egress gateway, an outbound listener is built, as follows, with address 0.0.0.0.

```
[
    {
        "name": "0.0.0.0_443",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 443
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.http_connection_manager",
                        "config": {
                            "access_log": [
                                {
                                    "config": {
                                        "path": "/dev/stdout"
                                    },
                                    "name": "envoy.file_access_log"
                                }
                            ],
                            "generate_request_id": true,
                            "http_filters": [
                                {
                                    "config": {
                                        "forward_attributes": {
                                            "attributes": {
                                                "source.uid": {
                                                    "string_value": "kubernetes://istio-egressgateway-5855864c44-gxnkc.istio-system"
                                                }
                                            }
                                        },
                                        "mixer_attributes": {
                                            "attributes": {
                                                "context.reporter.kind": {
                                                    "string_value": "outbound"
                                                },
                                                "context.reporter.uid": {
                                                    "string_value": "kubernetes://istio-egressgateway-5855864c44-gxnkc.istio-system"
                                                },
                                                "source.namespace": {
                                                    "string_value": "istio-system"
                                                },
                                                "source.uid": {
                                                    "string_value": "kubernetes://istio-egressgateway-5855864c44-gxnkc.istio-system"
                                                }
                                            }
                                        },
                                        "transport": {
                                            "attributes_for_mixer_proxy": {
                                                "attributes": {
                                                    "source.uid": {
                                                        "string_value": "kubernetes://istio-egressgateway-5855864c44-gxnkc.istio-system"
                                                    }
                                                }
                                            },
                                            "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                                            "network_fail_policy": {
                                                "policy": "FAIL_CLOSE"
                                            },
                                            "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
                                        }
                                    },
                                    "name": "mixer"
                                },
                                {
                                    "name": "envoy.cors"
                                },
                                {
                                    "name": "envoy.fault"
                                },
                                {
                                    "name": "envoy.router"
                                }
                            ],
                            "rds": {
                                "config_source": {
                                    "ads": {}
                                },
                                "route_config_name": "http.443"
                            },
                            "stat_prefix": "0.0.0.0_443",
                            "tracing": {
                                "operation_name": "EGRESS"
                            },
                            "use_remote_address": true
                        }
                    }
                ]
            }
        ]
    }
]
```

Compare it with an inbound listener on one of the application nodes. The address is the IP of the pod.
```
[
    {
        "name": "172.30.146.104_80",
        "address": {
            "socketAddress": {
                "address": "172.30.146.104",
                "portValue": 80
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.http_connection_manager",
                        "config": {
                            "access_log": [
                                {
                                    "config": {
                                        "path": "/dev/stdout"
                                    },
                                    "name": "envoy.file_access_log"
                                }
                            ],
                            "generate_request_id": true,
                            "http_filters": [
                                {
                                    "config": {
                                        "default_destination_service": "ingress",
                                        "mixer_attributes": {
                                            "attributes": {
                                                "context.reporter.kind": {
                                                    "string_value": "inbound"
                                                },
                                                "context.reporter.uid": {
                                                    "string_value": "kubernetes://sleep-776b7bcdcd-b22tx.default"
                                                },
                                                "destination.ip": {
                                                    "bytes_value": "AAAAAAAAAAAAAP//rB6SaA=="
                                                },
                                                "destination.namespace": {
                                                    "string_value": "default"
                                                },
                                                "destination.port": {
                                                    "int64_value": "80"
                                                },
                                                "destination.uid": {
                                                    "string_value": "kubernetes://sleep-776b7bcdcd-b22tx.default"
                                                }
                                            }
                                        },
                                        "service_configs": {
                                            "ingress": {}
                                        },
                                        "transport": {
                                            "attributes_for_mixer_proxy": {
                                                "attributes": {
                                                    "source.uid": {
                                                        "string_value": "kubernetes://sleep-776b7bcdcd-b22tx.default"
                                                    }
                                                }
                                            },
                                            "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                                            "network_fail_policy": {
                                                "policy": "FAIL_CLOSE"
                                            },
                                            "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
                                        }
                                    },
                                    "name": "mixer"
                                },
                                {
                                    "name": "envoy.cors"
                                },
                                {
                                    "name": "envoy.fault"
                                },
                                {
                                    "name": "envoy.router"
                                }
                            ],
```

**Comment by rshriram** [comment]
Yes I know. Inbound applies only if you are using IP tables to trap traffic. Gateway is a single ton envoy with no iptables business. So, listening on 0.0.0.0:443 is fine. The idea is to be able to deply the gateway outside of Kubernetes.

**Comment by rshriram** [comment]
@kyessenov / @douglas-reid who will know more about the mixer configuration

**Comment by kyessenov** [comment]
@vadimeisenbergibm My understanding was that there are no "inbound" listeners on gateways. Gateway outbound and sidecar outbound listeners are almost identical, and receive identical mixer configuration for the plugin. So you could apply policies on the gateway, but you would have to treat them as client-side. Adding server-side checks to gateway has a cost of two RPCs to mixer, so we'd be interested to hear when it's useful.

**Comment by vadimeisenbergibm** [comment]
@kyessenov The use case - I want the following policy: only `serviceA` is allowed to access _www.google.com_. I direct the traffic thru the `egressgateway`, see https://istio.io/docs/tasks/traffic-management/egress-gateway/ and want to apply the policy: I will use the source identity `spiffe://serviceA` and the requested SNI `www.google.com` - this one will be allowed, all other source identities/requested SNI will be denied. I would propose to cancel the outbound checks on mixer, and to enable inbound instead, if we want to save two calls to mixer.

**Comment by kyessenov** [comment]
@vadimeisenbergibm The problem is that for ingress, the inbound checks are not very useful. They basically have the port, and that's it. Outbound checks contains routing information for the destination service.

Have you looked at attribute `source.principal` in egress gateway? AFAIK `connection` attributes are actually always downstream attributes, and principals are derived from there.

**Comment by kyessenov** [comment]
We can always add an attribute (`origin.principal`?) to capture more information.

**Comment by mandarjog** [comment]
server side (inbound) checks make sense in his case.
The full information we want to convey to Mixer is: A is accessing google.com via G

G is the most appropriate place to enforce this, though same information can be conveyed on inbound and outbound listeners on G.

**Comment by kyessenov** [comment]
The issue is how we move policies between sidecars and egress. It's more natural to model egress as client-side behavior (it is the mesh as the client), and make it easy to switch between sidecars and egress. Once we choose egress as destination, then it becomes a service (gateways are not true services at the moment, they are global). FWIW pilot chose to model gateways as clients.

**Comment by vadimeisenbergibm** [comment]
@kyessenov My understanding of the policy enforcement is as follows:
when A calls B, an inbound listener of B performs a check if A is allowed to call B.
when A calls www.google.com, we do not have a sidecar proxy at www.google.com. So we put a gateway G to represent www.google.com for the mesh. So the inbound listener of G performs the check if A is allowed to call G (which represents www.google.com). To show the symmetry:

when A calls B, an inbound listener of B performs a check if A is allowed to call B.
when A calls G, an inbound listener of G performs a check if A is allowed to call G (which represents www.google.com).

We have symmetry and the code should be the same for the two cases, no need to introduce additional attributes.

**Comment by rshriram** [comment]
In that case, you can change the mixer plugin to treat all gateways as inbound servers instead of treating them as outbound entities. You don't have to tinker with the listeners on the gateway. This would apply equally well for ingress gateway as well.

**Comment by kyessenov** [comment]
I think this boils down to what gateway really is. When you say a gateway represents a service, then I agree, it should be modeled as a server. Currently, telemetry and policy model gateways as transparent proxies, that do not propagate their own identity except at ingress. 

There is another symmetry, which is that both ingress and egress gateways are the same thing except for a name. We don't have capability to have two mixer filters on the same listener AFAIK. That would be the appropriate way to solve this problem.

**Comment by kyessenov** [comment]
@vadimeisenbergibm what about the following rule on sidecars:
`context.reporter.kind == "outbound" && connection.requested_server_name == "google.com"`

My concern is that changing how mixer models gateways this late in the release cycle is going to have some unintended consequences.

**Comment by vadimeisenbergibm** [comment]
@kyessenov 
> what about the following rule on sidecars:

That's the whole point of having an egress gateway for enforcing policies, see https://goo.gl/eYY7na. In short, you cannot trust the source, only the destination (the gateway represents the destination in the case of the egress traffic).

Suppose we want to enforce: A is not allowed to call B and is not allowed to call www.google.com.

If A is compromised, it will not perform the check and will just access B and www.google.com. You need another proxy to check what A is allowed to call, the proxy of B and the proxy of the Gateway that represents www.google.com.

**Comment by vadimeisenbergibm** [comment]
@kyessenov see also the proposal of @mandarjog https://goo.gl/s7fSqM .

**Comment by kyessenov** [comment]
@vadimeisenbergibm How do ensure that network is captured by egress gateway is source sidecar is compromised? The mechanism for capturing the traffic and applying check is shared, so if you compromise one, you compromise both. The trust for sidecar client-side checks is the same as the trust for egress inbound checks, right?

**Comment by kyessenov** [comment]
I remember that proposal. There were a lot of unexpected changes when gateways landed, and I think this is another case when things did not go as planned. Have you considered modeling egress gateway as a service? It sounds like you really want it to be an actual service alias for some external service, in which case it's not really a gateway, but another service with its inbound checks.

**Comment by vadimeisenbergibm** [comment]
@kyessenov The assumptions are as follows:
1. The Istio control plane components and the gateways run on dedicated nodes, with special security measures, in a separate namespace, and cannot be attacked (are much harder to attack than the application pods). There is only a dozen of Istio components that can be properly secured by the cluster provider.
2. On the other hand, there are thousands of application pods, that have lower security requirements than the Istio components. They application pods can be accessed by multiple dev ops people, some of them could be malicious. The application pods can even run user code in some scenarios. You cannot trust the application pods.
3. To prevent egress traffic to bypass the egress gateway, you define a Kubernetes network policy or a firewall rule to prevent any egress access except from the egress gateway.

So, any compromised application pod will direct the traffic thru the egress gateway, where the policy check will be performed.

**Comment by kyessenov** [comment]
@vadimeisenbergibm Thanks, that makes sense. Have you tried using `source.principal == A && connection.requested_server_name == "google.com"` rule? I think that might work as a workaround while we figure out how to get inbound checks on gateways.

**Comment by vadimeisenbergibm** [comment]
@kyessenov 
> It sounds like you really want it to be an actual service alias for some external service, in which case it's not really a gateway, but another service with its inbound checks

But how can I define such a service? I need some pod with envoy to serve as a proxy to www.google.com, this is exactly what gateway is for.

**Comment by vadimeisenbergibm** [comment]
@kyessenov I can try to work with outbound listeners, that would be less natural and not symmetrical with the policies for destinations inside the mesh. BTW, what is wrong with the code of this PR - looks pretty simple for me.

**Comment by kyessenov** [comment]
@vadimeisenbergibm adding two listeners that just ping-pong to each other works (which is what I think you propose). It has performance costs (double proxy processing). I am also not an owner for this code, and @rshriram has some concerns. Ideally, we could make mixerfilter call out once/twice with both inbound and outbound context bags, but that's just something we don't support (although we talked about that).

**Comment by kyessenov** [comment]
@vadimeisenbergibm if we keep the rule general enough, then it doesn't matter whether it's inbound or outbound or done by egress/sidecar. I just want to make sure we can express this policy at all.

**Comment by vadimeisenbergibm** [comment]
@kyessenov Checking the access log of istio-egressgateway, it seems outbound listeners of the egress gateway should work for my use case.

The mixer check is performed by the egressgateway:
```
{"level":"info","time":"2018-07-16T16:26:39.784642Z","instance":"accesslog.logentry.istio-system","apiClaims":"","ap\
iKey":"","apiName":"","apiVersion":"","clientTraceId":"","connectionMtls":false,"destinationApp":"policy","destinati\
onIp":"172.30.146.73","destinationName":"istio-policy-8867896bf-66nsc","destinationNamespace":"istio-system","destin\
ationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-policy","destinationPrin\
cipal":"","destinationServiceHost":"istio-policy.istio-system.svc.cluster.local","destinationWorkload":"istio-policy\
","latency":"3.658686ms","method":"POST","protocol":"http","receivedBytes":1332,"referer":"","reporterKind":"inbound\
","requestHost":"mixer","requestId":"3d7d2d82-8f6f-9ecd-9d1c-fb7a8d15ac59","requestOperation":"","requestSize":830,"\
requestedServerName":"","responseCode":200,"responseSize":69,"responseTimestamp":"2018-07-16T16:26:39.786979Z","sent\
Bytes":237,"sourceApp":"istio-egressgateway","sourceIp":"172.30.146.78","sourceName":"istio-egressgateway-646c54cc7c\
-qfgpg","sourceNamespace":"istio-system","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system\
/deployments/istio-egressgateway","sourcePrincipal":"","sourceWorkload":"istio-egressgateway","url":"/istio.mixer.v1\
.Mixer/Check","userAgent":"","xForwardedFor":"172.30.146.78"}
```

The reported access entry by the egress gateway, `source.principal` seems to be OK:
```
{"level":"info","time":"2018-07-16T16:26:39.782583Z","instance":"accesslog.logentry.istio-system","apiClaims":"","ap\
iKey":"","apiName":"","apiVersion":"","clientTraceId":"","connectionMtls":true,"destinationApp":"","destinationIp":"\
151.101.1.67","destinationName":"unknown","destinationNamespace":"default","destinationOwner":"unknown","destination\
Principal":"","destinationServiceHost":"istio-egressgateway.istio-system.svc.cluster.local","destinationWorkload":"u\
nknown","latency":"432.759984ms","method":"GET","protocol":"http","receivedBytes":916,"referer":"","reporterKind":"o\
utbound","requestHost":"edition.cnn.com","requestId":"a4ac12c5-69cb-9c59-8507-384efa6137bc","requestOperation":"","r\
equestSize":0,"requestedServerName":"","responseCode":200,"responseSize":1997289,"responseTimestamp":"2018-07-16T16:\
26:40.215354Z","sentBytes":1998731,"sourceApp":"sleep","sourceIp":"172.30.146.120","sourceName":"sleep-776b7bcdcd-cc\
jbh","sourceNamespace":"istio-system","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/default/deploym\
ents/sleep","sourcePrincipal":"cluster.local/ns/default/sa/default","sourceWorkload":"sleep","url":"/politics","user\
Agent":"curl/7.35.0","xForwardedFor":"172.30.146.120"}
```

**Comment by vadimeisenbergibm** [comment]
For TCP:

The mixer check by the egress gateway:
```
{"level":"info","time":"2018-07-16T16:40:50.179187Z","instance":"accesslog.logentry.istio-system","apiClaims":"","ap\
iKey":"","apiName":"","apiVersion":"","clientTraceId":"","connectionMtls":false,"destinationApp":"policy","destinati\
onIp":"172.30.146.73","destinationName":"istio-policy-8867896bf-66nsc","destinationNamespace":"istio-system","destin\
ationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-policy","destinationPrin\
cipal":"","destinationServiceHost":"istio-policy.istio-system.svc.cluster.local","destinationWorkload":"istio-policy\
","latency":"2.058491ms","method":"POST","protocol":"http","receivedBytes":828,"referer":"","reporterKind":"inbound"\
,"requestHost":"mixer","requestId":"7574c409-5621-9add-a056-889ec4032365","requestOperation":"","requestSize":359,"r\
equestedServerName":"","responseCode":200,"responseSize":69,"responseTimestamp":"2018-07-16T16:40:50.181112Z","sentB\
ytes":237,"sourceApp":"istio-egressgateway","sourceIp":"172.30.146.78","sourceName":"istio-egressgateway-646c54cc7c-\
qfgpg","sourceNamespace":"istio-system","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system/\
deployments/istio-egressgateway","sourcePrincipal":"","sourceWorkload":"istio-egressgateway","url":"/istio.mixer.v1.\
Mixer/Check","userAgent":"","xForwardedFor":"172.30.146.78"}
```

The tcp access entry, with the correct source.principle
```
{"level":"info","time":"2018-07-16T16:40:50.208489Z","instance":"tcpaccesslog.logentry.istio-system","connctionDurat\
ion":"37.144943ms","connectionEvent":"close","connectionMtls":true,"destinationApp":"","destinationIp":"151.101.193.\
67","destinationName":"unknown","destinationNamespace":"default","destinationOwner":"unknown","destinationPrincipal"\
:"","destinationServiceHost":"","destinationWorkload":"unknown","protocol":"tcp","receivedBytes":570,"reporterKind":\
"outbound","requestedServerName":"","sentBytes":2007497,"sourceApp":"istio-egressgateway","sourceIp":"172.30.146.120\
","sourceName":"istio-egressgateway-646c54cc7c-qfgpg","sourceNamespace":"istio-system","sourceOwner":"kubernetes://a\
pis/extensions/v1beta1/namespaces/istio-system/deployments/istio-egressgateway","sourcePrincipal":"cluster.local/ns/\
default/sa/default","sourceWorkload":"istio-egressgateway","totalReceivedBytes":570,"totalSentBytes":2007497}
```

**Comment by vadimeisenbergibm** [comment]
Closing, telemetry and policy checks for gateways will be performed by outbound listeners.

**Pull request closed without merging**
