### PR TITLE
remove redundant whitespace

### PR DESCRIPTION
**Pull request by irisdingbj**

### CODE REVIEW

**Comment by irisdingbj** [comment]
https://github.com/istio/istio/issues/7383

**Comment by costinm** [comment]
Interesting - circle seems to run the test under a different org ( in the branch ) and doesn't have enough CPU/memory, so build fails. I've seen this before - not related with the change. Merging, we need to eventually investigate.

**Comment by ymesika** [comment]
@costinm happens when the forked repo is linked to CircleCI

**Pull request merged**
