### PR TITLE
[Ansible Installer] Upgrading to Kiali v0.7

### PR DESCRIPTION
**Pull request by gbaufake**
Hello Everyone, 
This pull request intends to update the Kiali Version to v0.7

I will have another PR to update it on Helm as well.

Best Regards,
Guilherme Baufaker Rêgo

### CODE REVIEW

**Comment by gbaufake** [comment]
cc sdake

**Comment by sdake** [comment]
Can you please rebase your PR.  This should hopefully fix the circleci gates failing.

**Comment by gbaufake** [comment]
@sdake  Can we merge this one?

**Pull request merged**
