### PR TITLE
Revert #6308 until #6346 is resolved

### PR DESCRIPTION
**Pull request by hklai**
revert #6308 until #6346  in order to restore post-submit runs.

### CODE REVIEW

**Comment by douglas-reid** [comment]
I can't repro the source issue locally. Is there a way to confirm that is won't cause other issues?

**Comment by kyessenov** [comment]
@hklai I strongly suggest we fix the underlying prow issue instead of turning off the test. The test runs fine on circle and locally.

**Comment by kyessenov** [comment]
The log I looked at shows gateway returning 503s consistently. I think that might be a release blocking... Let's not turn it off until we know more.

**Comment by hklai** [comment]
> @hklai I strongly suggest we fix the underlying prow issue instead of turning off the test. The test runs fine on circle and locally.

@kyessenov its a good practice to revert any "breaking" change, so other potential breakages don't go undetected. But if the problem can be fixed ASAP like today, yeah I think we can wait a bit.

**Comment by kyessenov** [comment]
There was no breaking change. All we did was to uncover a behavior that was there for awhile.

**Comment by hklai** [comment]
Anything breaking pre/post submit is breaking. =)
Let's try to get the fix in today however.

**Comment by douglas-reid** [comment]
I haven't been following this closely. Is this still needed? Where are we on figuring out the 503s?

**Comment by hklai** [comment]
@ostromart has kindly sent https://github.com/istio/istio/pull/6378 to fix but there appears to be some remaining problems.

**Comment by hklai** [comment]
No longer needed

**Pull request closed without merging**
