### PR TITLE
xds: enable skip node ID

### PR DESCRIPTION
**Pull request by kyessenov**
Enable xDS node ID perf optimization. This optimization amounts to sending node metadata exactly once per gRPC stream.

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
`REFRESH_GOLDEN=true go test ./pkg/kube/inject/...` will be useful if you don't like manually updating golden files

**Comment by douglas-reid** [comment]
@kyessenov would you mind adding a brief description of the why for this PR? it will be important to document for later.

**Comment by kyessenov** [comment]
Pilot crash detected:
```
2019-09-24T22:27:02.090483Z	info	ads	Push debounce stable[3] 1: 100.20837ms since last change, 100.208147ms since last push, full=true
2019-09-24T22:27:02.091977Z	info	ads	XDS: Pushing:2019-09-24T22:27:02Z/2 Services:19 ConnectedEndpoints:0
2019-09-24T22:27:02.092337Z	info	ads	Cluster init time 505ns 2019-09-24T22:27:02Z/2
2019-09-24T22:27:04.686602Z	info	ads	ADS:CDS: REQ 10.244.0.21:56674  330.169µs version:2019-09-24T22:18:41Z/21
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x160c88f]

goroutine 322 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters(0xc000289f60, 0xc0004a4880, 0x0, 0xc00093e200, 0x1f6f500, 0xc000229500, 0x10)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/cluster.go:95 +0x5f
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawClusters(0xc0002d8900, 0x0, 0xc00093e200, 0x2f24640, 0x1cbd541, 0x3)
	istio.io/istio@/pilot/pkg/proxy/envoy/v2/cds.go:73 +0x6b
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds(0xc0002d8900, 0xc0008bdc80, 0xc00093e200, 0xc000a1c180, 0x16, 0x4, 0xc00065b810)
	istio.io/istio@/pilot/pkg/proxy/envoy/v2/cds.go:51 +0x80
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc0002d8900, 0x1fcecc0, 0xc000a91180, 0x0, 0x0)
	istio.io/istio@/pilot/pkg/proxy/envoy/v2/ads.go:317 +0x12c4
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1cadd80, 0xc0002d8900, 0x1fc3c20, 0xc000796540, 0x2f42560, 0xc000745400)
	github.com/envoyproxy/go-control-plane@v0.9.0/envoy/service/discovery/v2/ads.pb.go:181 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000119600, 0x1fd3ca0, 0xc0008cdb00, 0xc000745400, 0xc0005dc3c0, 0x2f08ac0, 0xc00088bc40, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1199 +0xb2e
google.golang.org/grpc.(*Server).handleStream(0xc000119600, 0x1fd3ca0, 0xc0008cdb00, 0xc000745400, 0xc00088bc40)
	google.golang.org/grpc@v1.23.0/server.go:1279 +0xd30
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000a38a90, 0xc000119600, 0x1fd3ca0, 0xc0008cdb00, 0xc000745400)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

**Comment by howardjohn** [comment]
> pilot/pkg/networking/core/v1alpha3/cluster.go:95

Looks like a crash from `proxy` being nil.. which could be caused by this? but I would expect it to crash long before this if that was the case

**Comment by howardjohn** [comment]
Actually looks like we set `node := &core.Node{}` but don't really ever use it

**Comment by kyessenov** [comment]
Looks like some data race to me. I don't know how nil could have made it that far...

**Review by douglas-reid — APPROVED** [review]
lgtm.

**Comment by howardjohn** [comment]
@geeknoid the bot should probably recognize approval as activity

**Comment by howardjohn** [comment]
Superseded by https://github.com/istio/istio/pull/19266

**Pull request closed without merging**
