### PR TITLE
Fix KinD installation as it needs gomodule on

### PR DESCRIPTION
**Pull request by icygalz**
Current KinD installation needs to have Go111Module turned on. Fixing the test and setup script to use KinD.

### CODE REVIEW

**Comment by ericvn** [comment]
My first thought reading this was that the `kind` requirement had been removed and the only thing needed was `Docker`. That said, I haven't tried running the tests without having `kind` installed to know if that statement is true.

**Comment by icygalz** [comment]
@ericvn  This is the issue https://github.com/kubernetes-sigs/kind/issues/509 saying that we need to have gomodule on.

**Comment by ericvn** [comment]
@icygalz I agree it needs to be on if we do a `go get`. I'm just wondering if we even need the `go get` anymore.

**Comment by icygalz** [comment]
@ericvn I think we still need it for testing using KinD. KinD is not installed by default. Unless we are not planning to use KinD for testing anymore?

This test has been enabled ONLY as postsubmit test and the test is failing with:
https://k8s-gubernator.appspot.com/build/istio-prow/logs/istio-kind-simpleTest-master/12

""""
+ kind --help
/home/prow/go/src/istio.io/istio/prow/lib.sh: line 118: kind: command not found
+ go get sigs.k8s.io/kind
# sigs.k8s.io/kind/pkg/kustomize
../../sigs.k8s.io/kind/pkg/kustomize/kustomize.go:108:7: undefined: k8sdeps.NewFactory
../../sigs.k8s.io/kind/pkg/kustomize/kustomize.go:109:26: not enough arguments in call to build.NewCmdBuild
+ echo 'Looks like KinD installation failed.'
Looks like KinD installation failed.
+ exit 1
""""

**Comment by ericvn** [comment]
Kind is installed in the test image that is mounted back to the local Docker and then they run docker exec into the container to call Kind. At least that's how I saw things being setup.

**Comment by howardjohn** [comment]
Why are the go modules changes needed here? (likely answer is I don't understand go modules very well :slightly_smiling_face: )

**Comment by ericvn** [comment]
@howardjohn I assume it's the new packages that are required to build the `kind` binary. I suspect there may be more direction on adding _vendored_ packages using `go mod` vs `dep` (I see our wiki wasn't updated) forthcoming.

**Pull request closed without merging**
