### PR TITLE
Push back invalid secret to prevent sds fetching timeout

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

fix https://github.com/istio/istio/issues/46868

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Are we just now incrementing the metric for invalid certs but still continue to push to Envoy?

**Comment by hzxuzhonghu** [comment]
failure maybe related to https://github.com/istio/istio/pull/46957

**Comment by hzxuzhonghu** [comment]
>Are we just now incrementing the metric for invalid certs but still continue to push to Envoy?

Yes, and also a warning log printed

**Comment by ramaraochavali** [comment]
I agree NACK is more obvious. Then there is no point in validating the certs on Istiod side. Let us just rely on Envoy to validate and reject if it is invalid.

**Comment by howardjohn** [comment]
can we double check the startup behavior if we nack in envoy?

Best: it starts up and listener denies traffic
Ok: timeout (current state)
Bad: it hangs forever

**Comment by hzxuzhonghu** [comment]
I donot remember clearly what we get from the log. Does the NACK contains enough info that indicate which cert is invalid or expired

**Comment by howardjohn** [comment]
expired is not a nack, its perfectly valid to serve an expired cert (just
not recommended)

**Comment by howardjohn** [comment]
expired cert works fine if client doesn't care (curl -k etc)

**Comment by hzxuzhonghu** [comment]
hmm, doesnot server validate it?
 And what if the cert is set for client with destination rule?

**Comment by howardjohn** [comment]
it's up to the other end to decide to validate it. Not Istio. In the
original issue the user reported their client doesn't validate. That was
aws LB.. GCP is the same so it's pretty common

**Comment by ramaraochavali** [comment]
And even with in Envoy there is an option to allow expired certs where it is acting as server for non mesh clients

**Comment by hzxuzhonghu** [comment]
> can we double check the startup behavior if we nack in envoy?
> 
> Best: it starts up and listener denies traffic
> Ok: timeout (current state)
> Bad: it hangs forever


From envoy https://github.com/envoyproxy/envoy/blob/ca8003deb338a00ff335774d515650a697e68d57/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc#L133-L140

It will disableInitFetchTimeoutTimer, and listener can warm up, and yes it denies all traffic

**Comment by hzxuzhonghu** [comment]
So i believe we send both malformed and expired cert is ok

**Comment by ramaraochavali** [comment]
It would be good if we can validate it locally once

**Comment by hzxuzhonghu** [comment]
@howardjohn @ramaraochavali What else should we do to continue?

**Review by howardjohn — APPROVED** [review]
I tested this. Before, expired and invalid will wait 15s. Now they will send. 

Expired will serve ok (if client is insecure), invalid will break that filter chain.

One minor downside is if you go from valid -> invalid, before it works until the pod restarts. Now it breaks instantly.

**Comment by hzxuzhonghu** [comment]
Good test, it works as expected

**Pull request merged**
