### PR TITLE
add cert to xfcc header for sidecar

### PR DESCRIPTION
**Pull request by ramaraochavali**
Implements [#istio/api](https://github.com/istio/api/pull/3323)

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I think the idea was this is huge and not needed often. mTLS at gateway is rare and means someone explicitly opted in.

We already have ProxyConfig_ProxyHeaders.ForwardedClientCert, maybe we want to allow customization there..?

**Comment by ramaraochavali** [comment]
> I think the idea was this is huge and not needed often

Possible - but not 100% if it would be more than 6k?

> We already have ProxyConfig_ProxyHeaders.ForwardedClientCert, maybe we want to allow customization there..?

Yeah. That was one of the points I was considering. Are you suggesting to deprecate ForwardClientCertDetails and add a composite message to allow that customization or add additional field like "allow_cert_in_xfcc_header" ?

**Comment by howardjohn** [comment]
> Yeah. That was one of the points I was considering. Are you suggesting to deprecate ForwardClientCertDetails and add a composite message to allow that customization or add additional field like "allow_cert_in_xfcc_header" ?

I guess so, kind of annoying we didn't do that original.

Maybe something like
```
forwardedCert:
  cert: true/false
  san: true/false
  mode: SET/SANITIZE/...
```

?

**Comment by ramaraochavali** [comment]
I realized Envoy also two different fields to configure this. I thought it is just easier to go down that path instead of going down the deprecation dance. See https://github.com/istio/api/pull/3323. Let me know if you see any concerns with this

**Comment by hzxuzhonghu** [comment]
Not sure i quite understand this, according to envoy doc

```
APPEND_FORWARD
⁣When the client connection is mTLS, append the client certificate information to the request’s XFCC header and forward it.

SANITIZE_SET
⁣When the client connection is mTLS, reset the XFCC header with the client certificate information and send it to the next hop.
```

When the traffic is mtls, this is istio mtls, should application itself depend on underlying istio to get  {subject , uri, dns rtc }? I think it is not a good pattern for app developer to depend on istio implement details.

**Comment by ramaraochavali** [comment]
> When the traffic is mtls, this is istio mtls, should application itself depend on underlying istio to get {subject , uri, dns rtc }? I think it is not a good pattern for app developer to depend on istio implement details.

It could be Istio mTLS or regular mTLS (especially for traffic coming from non mesh clients or people with metadata certs) and in that case knowing the details is needed to enforce additional authz

**Comment by hzxuzhonghu** [comment]
You mean the hybrid sidecar, got it. Make sense to me

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
