### PR TITLE
operator: add resourcequotas in clusterrole

### LINKED ISSUE #41159: Operator doesn't create correct webhooks for sidecar injection & missing RBAC for `resourcequotas`
### Bug Description

- Istio Operator manifests are missing RBAC for resourcequotas. This is needed when installing Istio CNI. On that note, it is not clearly documented how to do this. Only clues were https://github.com/istio/istio/pull/34673 and https://github.com/istio/istio/blob/master/operator/pkg/apis/istio/v1alpha1/values_types.pb.go

```
2022-09-24T23:13:25.930917Z	info	installer	using server side apply to update obj: ConfigMap/istio-system/istio-cni-config
2022-09-24T23:13:25.976025Z	info	installer	using server side apply to update obj: ResourceQuota/istio-system/istio-cni-resource-quota
2022-09-24T23:13:25.979868Z	error	installer	failed to update resource with server-side apply for obj ResourceQuota/istio-system/istio-cni-resource-quota: resourcequotas "istio-cni-resource-quota" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot patch resource "resourcequotas" in API group "" in the namespace "istio-system"
2022-09-24T23:13:25.980028Z	info	installer	using server side apply to update obj: DaemonSet/istio-system/istio-cni-node
2022-09-24T23:13:25.981081Z	info	installer	using server side apply to update obj: Deployment/istio-system/istio-ingressgateway
2022-09-24T23:13:26.061788Z	info	installer	using server side apply to update obj: PodDisruptionBudget/istio-system/cluster-local-gateway
- Processing resources for CNI, Ingress gateways.
✘ CNI encountered an error: failed to update resource with server-side apply for obj ResourceQuota/istio-system/istio-cni-resource-quota: resourcequotas "istio-cni-resource-quota" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot patch resource "resourcequotas" in API group "" in the namespace "istio-system"
2022-09-24T23:13:26.091938Z	info	installer	using server side apply to update obj: PodDisruptionBudget/istio-system/istio-eastwestgateway
```
- MutatingWebhookConfigurations are broken when installed via the Operator.

```
2022-09-25T11:12:40.698110Z	info	kube	Pilot K8S CRD controller synced 147.17µs
2022-09-25T11:12:40.701171Z	error	installer	Error during reconcile: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-default) Webhook overlaps with others: [istio-system/istio-sidecar-injector-default/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-default) Webhook overlaps with others: [istio-system/istio-sidecar-injector-default/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-system/istio-sidecar-injector-default ) Webhook overlaps with others: [istio-sidecar-injector-default/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-system/istio-sidecar-injector-default ) Webhook overlaps with others: [istio-sidecar-injector-default/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
2022-09-25T11:17:09.301839Z	info	installer	Reconciling IstioOperator
2022-09-25T11:17:09.402120Z	info	installer	Updating IstioOperator
2022-09-25T11:17:09.402199Z	info	installer	Detecting third-party JWT support
```
Previous reports:
- https://github.com/istio/istio/issues/39573
- https://github.com/istio/istio/issues/40876

```
# istioctl installation
 REDACTED  MCW0CDP3YY  ~  $  kg mutatingwebhookconfiguration --context gke_coen-mahamed-ali_europe-west4_dev
W0925 16:44:55.088590   27264 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME                                                      WEBHOOKS   AGE
istio-revision-tag-default                                4          4h16m
istio-sidecar-injector                                    4          4h17m
neg-annotation.config.common-webhooks.networking.gke.io   1          24d
pod-ready.config.common-webhooks.networking.gke.io        1          24d
# istiooperator installation
 REDACTED  MCW0CDP3YY  ~  $  kg mutatingwebhookconfiguration --context gke_coen-mahamed-ali_us-central1-c_istio
W0925 16:45:10.288240   27339 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME                                                      WEBHOOKS   AGE
istio-sidecar-injector                                    4          2m
neg-annotation.config.common-webhooks.networking.gke.io   1          3h57m
pod-ready.config.common-webhooks.networking.gke.io        1          3h57m
```

```
# difference between mutatingwebhookconfiguration/istio-sidecar-injector on the clusters
  name: object.sidecar-injector.istio.io
   namespaceSelector:
-    matchExpressions:
-    - key: istio-injection
-      operator: DoesNotExist
-    - key: istio.io/rev
-      operator: DoesNotExist
+    matchLabels:
+      istio.io/deactivated: never-match
   objectSelector:
-    matchExpressions:
-    - key: sidecar.istio.io/inject
-      operator: In
-      values:
-      - "true"
-    - key: istio.io/rev
-      operator: DoesNotExist
+    matchLabels:
+      istio.io/deactivated: never-match
   reinvocationPolicy: Never
```

How to reproduce the bug:
- Deploy the operator: https://github.com/borg-land/k8s-demo/blob/dev/istio/operator.yaml
- Deploy the istiooperator: https://github.com/borg-land/k8s-demo/blob/dev/istio/mesh.yaml
- Patch any value in the istiooperator CRD and look at the pods + the mutatingwebhookconfigurations
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: controlplane
  namespace: istio-system
spec:
  components:
    ingressGateways:
      - enabled: true
        k8s:
          service:
            externalTrafficPolicy: Local
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: tcp-istiod
                port: 15012
                protocol: TCP
                targetPort: 15012
              - name: tls
                port: 15443
                protocol: TCP
                targetPort: 15443
        name: istio-ingressgateway
    pilot:
      k8s:
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
  hub: gcr.io/istio-release
  meshConfig:
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
    protocolDetectionTimeout: 5s
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2  
  namespace: istio-system
  profile: default
  tag: 1.15.0
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
      resourceQuotas:
        enabled: true

```

@howardjohn 

### Version

```prose
REDACTED  MCW0CDP3YY  ~  Desktop  Git  k8s-demo  istio   dev  1✎  10+  $   k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
W0925 16:48:59.088301   27642 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.8-gke.1900
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  k8s-demo  istio   dev  1✎  10+  $   ./istio-1.15.0/bin/istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (5 proxies)
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

part of fixes: https://github.com/istio/istio/issues/41159

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by upodroid** [comment]
Can you edit the body of your PR? This is a partial fix. Change it from fixes to part of

**Review by howardjohn — COMMENTED** [review]
Not sure this is super safe... resourceQuota is a SUPER high privilege. Can we really just force all users into using this?

**Comment by upodroid** [comment]
> Not sure this is super safe... resourceQuota is a SUPER high privilege. Can we really just force all users into using this?

The operator is already highly privileged. https://kubernetes.io/docs/concepts/policy/resource-quotas/ Looks safe to me

**Comment by zirain** [comment]
> Not sure this is super safe... resourceQuota is a SUPER high privilege. Can we really just force all users into using this?

what about remove this, users should configure this manual?

**Comment by howardjohn** [comment]
I'd like someone that has an interest in the operator to review this. It doesn't seem great from a security perspective to me, but I think the whole operator is flawed from a security perspective so maybe I am biased :-)

**Comment by zirain** [comment]
> I'd like someone that has an interest in the operator to review this. It doesn't seem great from a security perspective to me, but I think the whole operator is flawed from a security perspective so maybe I am biased :-)

I agree with the point about security perspective.
IMO, something not working is worser.

**Comment by litong01** [comment]
> > I'd like someone that has an interest in the operator to review this. It doesn't seem great from a security perspective to me, but I think the whole operator is flawed from a security perspective so maybe I am biased :-)
> 
> I agree with the point about security perspective. IMO, something not working is worser.



> > Not sure this is super safe... resourceQuota is a SUPER high privilege. Can we really just force all users into using this?
> 
> what about remove this, users should configure this manual?

I do not feel grant operator controller resourcequota is no worse than the current permissions. If you all agree with that, I think I am ok with this permission addition.

**Comment by howardjohn** [comment]
> I do not feel grant operator controller resourcequota is no worse than the current permissions. If you all agree with that, I think I am ok with this permission addition

Fair enough

**Comment by litong01** [comment]
> > I do not feel grant operator controller resourcequota is no worse than the current permissions. If you all agree with that, I think I am ok with this permission addition
> 
> Fair enough

Thanks john.

**Review by litong01 — APPROVED** [review]
Thanks very much for your contribution.

**Pull request merged**
