### PR TITLE
Fix typos that do not affect logical with crate-ci/typos.

### PR DESCRIPTION
**Pull request by j2gg0s**
**Please provide a description of this PR:**

Find and fix typos via github.com/crate-ci/typos.

I limited the scope of influence to avoid any modifications that might affect the logic of the code
The configuration I use locally:
```toml
[default]
extend-ignore-identifiers-re = [
    "ANDed",
    "O_WRONLY",
    "Failer",
    "failer",
    "IST",
    "ist",
    "ba",
    "ALS",
    "Als",
    "als",
    "Octect",
    "clik",
    "mis",
    "Ser",
    "unmarshaling",
    "wil",
    "Syncronization",
]

[default.extend-words]
wil = "will"
lsit = "list"
rebuilts = "rebuilt"

[type.log]
extend-glob = ["*.log"]
check-file = false

[type.gotest]
extend-glob = ["*_test.go"]
check-file = false

[type.svg]
extend-glob = ["*.svg"]
check-file = false

[files]
extend-exclude = [
  "go.mod",
  "licenses/**",
  "security/**",
  "tests/**",
  "pkg/test/**",
  "pkg/testcerts/**",
  "pkg/ctrlz/assets/static/**",
  "releasenotes/**",
  "samples/**",
  "pkg/config/analysis/analyzers/testdata/**",
  "pilot/pkg/config/kube/gateway/testdata/**",
]

```

### CODE REVIEW

**Comment by sword-jin** [comment]
Looks we could use this action in our CI PIPELINE?

**Comment by zirain** [comment]
> Looks we could use this action in our CI PIPELINE?

can this be part of https://github.com/golangci/golangci-lint?

**Comment by j2gg0s** [comment]
> Looks we could use this action in our CI PIPELINE?

There are some negative case:

- with cert/base64/binary
```
error: `TEH` should be `THE`
  --> ./pilot/pkg/model/jwks_resolver.go:316:174
    |
316 |       "p": "7EK8xaN7qCdWCeQ1ptXWvuc6qotZc6oD-j1ecgel9FqmfkmaioVEbEAfP_N73QAjw-sU60sK3XK8LV4fkGUoJV-MDvmiCzy3wUPe-adSaTCxFykgOm6SPA9NKCqAh8lUm6GUm9RZkjwkv4xzZ8pJjng3d74WXx7zhTEH6yi4E00",
    |                                                                                                                                                                              ^^^
    |
```
- with abbrev in code
```
error: `WRONLY` should be `WRONGLY`
  --> ./pkg/file/file.go:59:73
   |
59 |  out, err := os.OpenFile(filepath.Join(targetDir, targetFilename), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm.Mode())
   |                                                                         ^^^^^^
   |
```

I think this check can not be MUST, and add to CI

**Comment by zirain** [comment]
> > Looks we could use this action in our CI PIPELINE?
> 
> There are some negative case:
> 
> * with cert/base64/binary
> 
> ```
> error: `TEH` should be `THE`
>   --> ./pilot/pkg/model/jwks_resolver.go:316:174
>     |
> 316 |       "p": "7EK8xaN7qCdWCeQ1ptXWvuc6qotZc6oD-j1ecgel9FqmfkmaioVEbEAfP_N73QAjw-sU60sK3XK8LV4fkGUoJV-MDvmiCzy3wUPe-adSaTCxFykgOm6SPA9NKCqAh8lUm6GUm9RZkjwkv4xzZ8pJjng3d74WXx7zhTEH6yi4E00",
>     |                                                                                                                                                                              ^^^
>     |
> ```
> 
> * with abbrev in code
> 
> ```
> error: `WRONLY` should be `WRONGLY`
>   --> ./pkg/file/file.go:59:73
>    |
> 59 |  out, err := os.OpenFile(filepath.Join(targetDir, targetFilename), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm.Mode())
>    |                                                                         ^^^^^^
>    |
> ```
> 
> I think this check can not be MUST, and add to CI

can not skip with something like `//nolint: typos`

**Comment by j2gg0s** [comment]
> > > Looks we could use this action in our CI PIPELINE?
> > 
> > 
> > There are some negative case:
> > 
> > * with cert/base64/binary
> > 
> > ```
> > error: `TEH` should be `THE`
> >   --> ./pilot/pkg/model/jwks_resolver.go:316:174
> >     |
> > 316 |       "p": "7EK8xaN7qCdWCeQ1ptXWvuc6qotZc6oD-j1ecgel9FqmfkmaioVEbEAfP_N73QAjw-sU60sK3XK8LV4fkGUoJV-MDvmiCzy3wUPe-adSaTCxFykgOm6SPA9NKCqAh8lUm6GUm9RZkjwkv4xzZ8pJjng3d74WXx7zhTEH6yi4E00",
> >     |                                                                                                                                                                              ^^^
> >     |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * with abbrev in code
> > 
> > ```
> > error: `WRONLY` should be `WRONGLY`
> >   --> ./pkg/file/file.go:59:73
> >    |
> > 59 |  out, err := os.OpenFile(filepath.Join(targetDir, targetFilename), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm.Mode())
> >    |                                                                         ^^^^^^
> >    |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think this check can not be MUST, and add to CI
> 
> can not skip with something like `//nolint: typos`

With config
- extend-ignore-identifiers-re, you can ignore word by regex
- check-file, you can ignore by file type
- extend-exclude, you can ignore by path, support regex

However, I didn't find a way to config it via comments.
I'm guessing it's not using syntax parsing.

Adding typos check to golangci-lint is very attractive, but difficult

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
We already have typo checks, its just not as sensitive

**Comment by j2gg0s** [comment]
> We already have typo checks, its just not as sensitive

Do you mean https://github.com/golangci/misspell ?

**Review by hanxiaop — APPROVED** [review]

**Pull request merged**
