### PR TITLE
Replace MaxClusterNameLength with MeshConfig.StatNameLength

### PR DESCRIPTION
**Pull request by lichuqiang**
Replace hard code MaxClusterNameLength with field StatNameLength of ProxyConfig.

TODO: consider making the field configurable to users

### CODE REVIEW

**Comment by lichuqiang** [comment]
Seems some of the circleci tasks are flaky.
@rshriram Do you know how to trigger them again? Seems command "/retest" won't take effect on the circleci ones.

**Comment by lichuqiang** [comment]
@rshriram I rebased it with newest code.
Can you give it a lgtm?

**Comment by hzxuzhonghu** [comment]
re-tag 
/lgtm

**Pull request merged**
