### PR TITLE
init Labels map

### LINKED ISSUE #30725: NPE in reconciler
install istio via below iop:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "cluster1"
      network: "kube-network"
```
fails with `panic: assignment to entry in nil map`

### PR DESCRIPTION
**Pull request by irisdingbj**
fix #30725

### CODE REVIEW

**Review by esnible — APPROVED** [review]
My review carries no weight in _operator_ directory, but I believe this is an important fix!

**Review by howardjohn — APPROVED** [review]
maybe we need a test?

**Comment by irisdingbj** [comment]
> maybe we need a test?

Sure, Let me add a integration test to this later.

**Pull request merged**
