### PR TITLE
Update to latest istio.io/pkg in order to get updated doc generation.

### PR DESCRIPTION
**Pull request by geeknoid**
- Brings with it OpenCensus support for ControlZ and support for the "all" scope
when specifying log output level on the command-line.

### CODE REVIEW

**Comment by fpesce** [comment]
@geeknoid What happened with integration tests here? Is CI suffering from an update of type "go mod" ?

**Comment by geeknoid** [comment]
Seems like we're still building with Go 1.12 and the code coming from istio/pkg depends on Go 1.12

:-(

**Comment by sdake** [comment]
> Seems like we're still building with Go 1.11 and the code coming from istio/pkg depends on Go 1.12
> 
> :-(
Building with which repo with Go 1.11?   istio/pkg depends on go 1.12 (this seems right).

**Comment by geeknoid** [comment]
If you look at some of the failed jobs, the failure is because the symbol strings.ReplaceAll doesn't exist. This symbol was added in Go 1.12 and istio/pkg/ctrlz has a dependency on this symbol.

**Comment by geeknoid** [comment]
I changed a bit of code in the pkg repo to remove the dependency on Go 1.12, so hopefully this will all build and pass tests now.

**Comment by geeknoid** [comment]
@fpesce Can we still get this in the release?

**Comment by fpesce** [comment]
> @fpesce Can we still get this in the release?

Now that all the red disappeared, no problem!

**Pull request merged**
