### PR TITLE
Use distro provided ca-certificates

### PR DESCRIPTION
**Pull request by howardjohn**
Currently our docker files manually copy ca-certificates into the
images. This means they are pretty outdated, and it is just extra
complexity we don't need. Both ubuntu and distroless handle this for us,
so just use those.

Fixes https://github.com/istio/istio/issues/17286

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by kyessenov** [comment]
Please make sure it's possible to audit root CAs. These are sometimes revoked.

**Comment by tallclair** [comment]
@kyessenov you may be interested in https://github.com/kubernetes/kubernetes/issues/63726

**Pull request merged**
