### PR TITLE
fix(tests): remove empty integ-telemetry-local-presubmit test

### PR DESCRIPTION
**Pull request by douglas-reid**
Removes empty integration test. All telemetry integration tests require k8s at the moment.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
this is one of the reasons we made the change to rename the tests, they usually don't even correspond to the test being run

**Comment by douglas-reid** [comment]
@howardjohn yeah, i was just cleaning out everything I could find.

**Comment by howardjohn** [comment]
/assign @utka 

Sorry I assign everything to you but you are the only prow owner

**Pull request merged**
