### PR TITLE
[WIP] Change the iptables script not to clean the previous chains

### LINKED ISSUE #16768: Make Istio-init resilient to erroneous init-containers restarts
**Describe the feature request**
There could be buggy situations in some Kubernetes environments where init containers run multiple times, see https://github.com/kubernetes/kubernetes/issues/67261, https://github.com/istio/istio/issues/16473, https://stackoverflow.com/questions/49247931/kubernetes-init-containers-run-every-hour.

While these situations represent bugs/misconfigurations in Kubernetes environments, it could be nice if Istio init would be resilient to these situations. Currently, as far as I can see in https://github.com/istio/istio/blob/master/tools/packaging/common/istio-iptables.sh#L262 istio-init deletes the Istio chains and recreates them. During the window between deletion and recreation, Istio traffic control for the pod is broken since there is no redirection to Envoy.

The solutions seems to be simple:
1. remove deletion of Istio chains from https://github.com/istio/istio/blob/master/tools/packaging/common/istio-iptables.sh
1. add a check if `ISTIO_REDIRECT` exists, and if it exists, exit.

Based on https://stackoverflow.com/a/10784612/553720:

```bash
iptables -t nat --list ISTIO_REDIRECT
if [[ $? -eq 0 ]]; then exit 0; fi
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
if cleaning is not required, check if ISTIO_REDIRECT already exists
if it exists, exit

resolves #16768

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by lambdai** [comment]
kubernetes/kubernetes#67261 is closed
Do we really need to make our code more complex to guard the events should not happen?
I believe there is more than this PR if we concede istio should be working well on restarting completed container. 
Meanwhile the PR itself is good to go if we decide to cope with this unexpected restart

**Comment by howardjohn** [comment]
What version is kubernetes/kubernetes#67261 in? Seems like its fixed since a year ago so should be in 1.12+. We only support 1.13+, and this is master so by the time this is released only 1.14+

Given that bug is fixed do we need this?

**Comment by vadimeisenbergibm** [comment]
@lambdai @howardjohn Note that #16473 is experienced right now on OpenShift. This shows that restarting init containers is a recurring bug that can happen in different environments from time to time. On our part the fix is simple - just check if an Istio chain is there and exit in case it is.

Let me ask you if the cleanup of the previous Istio chains is needed if not part of tests. Is there a requirement for the init container to clean the previous Istio chains?

**Comment by howardjohn** [comment]
I think I read it wrong, I thought if the chains existed it just exited, not clean them.

Does this mean we will have a period of time where iptables rules are not set? allowing bypass of polices, etc

**Comment by vadimeisenbergibm** [comment]
@howardjohn @lambdai Let me clarify my intent.

1. I renamed #16768 to be "Make Istio-init resilient to erroneous init-containers restarts". I think the feature is not "idempotent" , the feature is resiliency to external errors which is important in general.
2. The simplicity/maintenance of resiliency. Of course resiliency comes with price - complexity of code and maintenance of it. So there is a trade-off between the complexity of code and resiliency, we should weigh the probability of an external error vs. complexity of the code to handle it.
3. In our case, the external error is "restart of init-container" without restart of the pod, which should not happen according to [Kubernetes docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#understanding-init-containers): `If a Pod’s init container fails, Kubernetes repeatedly restarts the Pod until the init container succeeds.` In the both documented cases in #16768, the init container restarted without any reason, and without restarting the pod. The probability of such an error is not small since we had such case documented in the past, and we have it now happening as well.
4. Handling of this error is simple - just check that an istio chain exists and exit. It is several lines of code.
5. Regarding maintenance - let me ask why the cleaning code is there in the first place. Is it for tests only? As far as I understand init-container runs always on a fresh pod, so there should be no previous Istio chains there. So if we care about code complexity and performance, maybe we should remove the cleaning code alltogether, and put it in a separate script, and use that script for cleaning Istio chains during the tests.

**Comment by vadimeisenbergibm** [comment]
@howardjohn 
> I thought if the chains existed it just exited, not clean them.

This is what this PR is doing. The existing code cleans the iptables and recreates them again.

> Does this mean we will have a period of time where iptables rules are not set? allowing bypass of polices, etc

This is what the user in #16473 is experiencing due to some in OpenShift. The Istio-init container runs multiple times, cleans iptables and recreates them. During that period of time, between the clean and recreation, some requests are not routed correctly and fail.

**Comment by vadimeisenbergibm** [comment]
@rlenglet Thank you for your review. It seems it would be simpler just to remove the cleaning code from `istio-iptables.sh`. Then move the cleaning code into a separate script, used for tests only.

cc @lambdai @howardjohn Can someone confirm that the cleaning code is for tests only? Is there a situation that `istio-iptables.sh` runs in an environment where Istio chains are already set and istio-iptables.sh must clean them, except in Istio tests?

**Comment by rlenglet** [comment]
> It seems it would be simpler just to remove the cleaning code from istio-iptables.sh. Then move the cleaning code into a separate script, used for tests only.

Always happy to remove dead code.

**Comment by howardjohn** [comment]
Is it possibly used on VMs? how else would you upgrade on a VM for example?
(note - just a guess)

**Comment by lambdai** [comment]
so 
1. iptables.sh: do  add rules 
2. iptables.sh clean: do clean up, not add
you are adding 
3. iptables.sh -c: do clean up then add rule
Correct?

**Comment by vadimeisenbergibm** [comment]
@lambdai 
_iptables.sh: do clean up then add rules
iptables.sh clean: do clean up, do not add rules_

After my change (iptables.sh clean remains the same)
_iptables.sh: do add rules
iptables.sh clean: do clean up, do not add rules
iptables.sh -c: do clean up then add rules_

We can discuss other interface options, any ideas are welcome.

**Comment by vadimeisenbergibm** [comment]
@lambdai Following https://github.com/istio/istio/pull/16810#issuecomment-528747675, alternatively, we can just replace `iptables.sh -c` with `iptables.sh clean; iptables.sh`. Or we can move it into a separate script, to be `iptables-clean.sh; iptables.sh`. Let's decide. cc @rlenglet @howardjohn

**Comment by rlenglet** [comment]
> Or we can move it into a separate script, to be iptables-clean.sh; iptables.sh.

I like that idea. It would make `istio-iptables.sh` smaller, and therefore reduce the amount of code that has to be reimplemented in Go and the amount of code shipped in `istio-init`.

**Comment by vadimeisenbergibm** [comment]
@lambdai @howardjohn @rlenglet So can we agree on the implementation?
Two options:
1. Move the cleaning code into a separate script, e.g. clean-ip-tables.sh
2. Add -c flag, and do not perform cleaning by default.

@rlenglet and I are in favour of the first option. This PR originally represents the second option, I am ready to rewrite it.

**Comment by rlenglet** [comment]
cc @abhide

**Comment by lambdai** [comment]
> @lambdai
> _iptables.sh: do clean up then add rules iptables.sh clean: do clean up, do not add rules_
> 
> After my change (iptables.sh clean remains the same)
> _iptables.sh: do add rules iptables.sh clean: do clean up, do not add rules iptables.sh -c: do clean up then add rules_
> 
> We can discuss other interface options, any ideas are welcome.

Thank you for the clarify!

**Comment by lambdai** [comment]
Both option looks good. I wrongly interpreted the `idempotent` before. I don't have strong opinion on any option

**Pull request closed without merging**
