### PR TITLE
add bin/xds.py

### PR DESCRIPTION
**Pull request by mandarjog**
Produces a single yaml file with all xds configuration.
1. Requires direct access to pilot:15003
2. Needs kubectl access unless pod is fully specified as `pod_name,pod_namespace, pod_ip`

example:
```
mjog-macbookpro:bin mjog$ ./xds.py http://localhost:15003 ingress
/listeners/istio-proxy/ingress~10.4.1.7~istio-system~istio-ingress-c5f98cb78-8zljl.svc.cluster.local
/routes/80/istio-proxy/ingress~10.4.1.7~istio-system~istio-ingress-c5f98cb78-8zljl.svc.cluster.local
/clusters/istio-proxy/ingress~10.4.1.7~istio-system~istio-ingress-c5f98cb78-8zljl.svc.cluster.local
/registration/prometheus.istio-system.svc.cluster.local|http-prometheus
/registration/istio-mixer.istio-system.svc.cluster.local|http-prometheus
/registration/httpbin.default.svc.cluster.local|http|version=v50
/registration/istio-pilot.istio-system.svc.cluster.local|http-discovery
Wrote  istio-ingress-c5f98cb78-8zljl_xds.yaml
```

### CODE REVIEW

**Comment by mandarjog** [comment]
```yaml
listeners:
- address: tcp://0.0.0.0:80
  bind_to_port: true
  filters:
  - config:
      access_log:
      - path: /dev/stdout
      codec_type: auto
      filters:
      - config:
          forward_attributes:
            source.ip: 10.4.1.7
            source.uid: kubernetes://istio-system
          mixer_attributes:
            destination.ip: 10.4.1.7
            destination.service: istio-ingress.istio-system.svc.cluster.local
            destination.uid: kubernetes://istio-system
          quota_name: RequestCount
          v2:
            defaultDestinationService: istio-ingress.istio-system.svc.cluster.local
            forwardAttributes:
              attributes:
                source.ip:
                  bytesValue: AAAAAAAAAAAAAP//CgQBBw==
                source.uid:
                  stringValue: kubernetes://istio-system
            mixerAttributes:
              attributes:
                destination.ip:
                  bytesValue: AAAAAAAAAAAAAP//CgQBBw==
                destination.uid:
                  stringValue: kubernetes://istio-system
            serviceConfigs:
              istio-ingress.istio-system.svc.cluster.local:
                mixerAttributes:
                  attributes:
                    destination.service:
                      stringValue: istio-ingress.istio-system.svc.cluster.local
        name: mixer
        type: decoder
      - config: {}
        name: cors
        type: ''
      - config: {}
        name: router
        type: decoder
      generate_request_id: true
      rds:
        cluster: rds
        refresh_delay_ms: 1000
        route_config_name: '80'
      route_config:
        route_config_name: '80'
        virtual_hosts:
        - domains:
          - httpbin
          - httpbin:80
          name: httpbin
          routes:
          - cluster:
              connect_timeout_ms: 1000
              endpoints:
                hosts:
                - ip_address: 10.4.2.14
                  port: 8000
              lb_type: round_robin
              name: out.httpbin.default.svc.cluster.local|http|version=v50
              service_name: httpbin.default.svc.cluster.local|http|version=v50
              type: sds
            decorator:
              operation: details-default
            opaque_config:
              destination.service: httpbin.default.svc.cluster.local
              mixer_check: 'on'
              mixer_forward: 'on'
              mixer_report: 'on'
            prefix: /
            timeout_ms: 0
        - domains:
          - istio-mixer
          - istio-mixer:80
          name: istio-mixer
          routes:
          - cluster:
              connect_timeout_ms: 1000
              endpoints:
                hosts:
                - ip_address: 10.4.0.5
                  port: 42422
              lb_type: round_robin
              name: out.istio-mixer.istio-system.svc.cluster.local|http-prometheus
              service_name: istio-mixer.istio-system.svc.cluster.local|http-prometheus
              type: sds
            decorator:
              operation: default-route
            opaque_config:
              destination.service: istio-mixer.istio-system.svc.cluster.local
              mixer_check: 'on'
              mixer_forward: 'on'
              mixer_report: 'on'
            prefix: /
            timeout_ms: 0
        - domains:
          - istio-pilot
          - istio-pilot:80
          name: istio-pilot
          routes:
          - cluster:
              connect_timeout_ms: 1000
              endpoints:
                hosts:
                - ip_address: 10.4.2.13
                  port: 15003
              lb_type: round_robin
              name: out.istio-pilot.istio-system.svc.cluster.local|http-discovery
              service_name: istio-pilot.istio-system.svc.cluster.local|http-discovery
              type: sds
            decorator:
              operation: default-route
            opaque_config:
              destination.service: istio-pilot.istio-system.svc.cluster.local
              mixer_check: 'on'
              mixer_forward: 'on'
              mixer_report: 'on'
            prefix: /
            timeout_ms: 0
        - domains:
          - prometheus
          - prometheus:80
          name: prometheus
          routes:
          - cluster:
              connect_timeout_ms: 1000
              endpoints:
                hosts:
                - ip_address: 10.4.2.12
                  port: 9090
              lb_type: round_robin
              name: out.prometheus.istio-system.svc.cluster.local|http-prometheus
              service_name: prometheus.istio-system.svc.cluster.local|http-prometheus
              type: sds
            decorator:
              operation: default-route
            opaque_config:
              destination.service: prometheus.istio-system.svc.cluster.local
              mixer_check: 'on'
              mixer_forward: 'on'
              mixer_report: 'on'
            prefix: /
            timeout_ms: 0
      stat_prefix: http
      tracing:
        operation_name: egress
      use_remote_address: true
    name: http_connection_manager
    type: read
  name: http_0.0.0.0_80
```

**Comment by kyessenov** [comment]
see also https://github.com/istio/istio/blob/master/bin/istio-proxy-cfg
Maybe merge the two?

**Comment by rshriram** [comment]
This is very timely. @liamawhite was writing an istioctl plugin to actually do this entire thing.

**Comment by davidshepard989** [comment]
If anyone (like myself) wants a 1-liner to forward istio pilot's port to localhost:15003

`kubectl --namespace=istio-system port-forward $(kubectl --namespace=istio-system get -l istio=pilot pod -o=jsonpath='{.items[0].metadata.name})` 15003:15003`

**Pull request merged**
