### PR TITLE
Support impersonate flags in istioctl

### PR DESCRIPTION
**Pull request by edieYoung**
**Please provide a description of this PR:**
This PR adds support for the impersonate flags used in kube client in the istioctl. 
Related issue https://github.com/istio/istio/issues/52285

### CODE REVIEW

**Review by MorrisLaw — CHANGES_REQUESTED** [review]
Blocking this to ensure more discussion is had, specifically because this seems to have been addressed in the past and it was determined that we didn't need to add to istioctl for this to work. See [here](https://github.com/istio/istio/issues/22365). Also left a related comment on the issue for this PR.

**Comment by edieYoung** [comment]
> Blocking this to ensure more discussion is had, specifically because this seems to have been addressed in the past and it was determined that we didn't need to add to istioctl for this to work. See [here](https://github.com/istio/istio/issues/22365). Also left a related comment on the issue for this PR.

thanks for the pointer, will take a look in that thread.

**Comment by MorrisLaw** [comment]
> > Blocking this to ensure more discussion is had, specifically because this seems to have been addressed in the past and it was determined that we didn't need to add to istioctl for this to work. See [here](https://github.com/istio/istio/issues/22365). Also left a related comment on the issue for this PR.
> 
> thanks for the pointer, will take a look in that thread.

np! Thanks for the issue and PR. Let me know if those suggestions in the thread are able to unblock you.

**Comment by edieYoung** [comment]
As per [discussion](https://github.com/istio/istio/issues/52285#issuecomment-2315834461), we made consensus to add these flags.
Shall we continue the review, thanks!

**Comment by MorrisLaw** [comment]
> As per [discussion](https://github.com/istio/istio/issues/52285#issuecomment-2315834461), we made consensus to add these flags.
> 
> Shall we continue the review, thanks! cc @MorrisLaw @Stevenjin8 

Saw the consensus, thanks for getting that ironed out. I can review this Monday when I'm back from vacation.

**Review by MorrisLaw — COMMENTED** [review]
Did you test/verify that this works as expected manually or did you consider adding an [integration test](https://github.com/istio/istio/blob/master/tests/integration/pilot/istioctl_test.go)?

**Review by howardjohn — APPROVED** [review]

**Comment by edieYoung** [comment]
**Local test results:**
command flags output:
```
./istioctl -h
Istio configuration command line utility for service operators to
debug and diagnose their Istio mesh.

Usage:
  istioctl [command]

Available Commands:
  admin                Manage control plane (istiod) configuration
  analyze              Analyze Istio configuration and print validation messages
  authz                (authz is experimental. Use `istioctl experimental authz`)
  bug-report           Cluster information and log capture support tool.
  completion           Generate the autocompletion script for the specified shell
  create-remote-secret Create a secret with credentials to allow Istio to access remote Kubernetes apiservers
  dashboard            Access to Istio web UIs
  experimental         Experimental commands that may be modified or deprecated
  help                 Help about any command
  install              Applies an Istio manifest, installing or reconfiguring Istio on a cluster.
  kube-inject          Inject Istio sidecar into Kubernetes pod resources
  manifest             Commands related to Istio manifests
  proxy-config         Retrieve information about proxy configuration from Envoy [kube only]
  proxy-status         Retrieves the synchronization status of each Envoy in the mesh
  remote-clusters      Lists the remote clusters each istiod instance is connected to.
  tag                  Command group used to interact with revision tags
  uninstall            Uninstall Istio from a cluster
  upgrade              Upgrade Istio control plane in-place
  validate             Validate Istio policy and rules files
  version              Prints out build version information
  waypoint             Manage waypoint configuration
  ztunnel-config       Update or retrieve current Ztunnel configuration.

Flags:
      --as string               Username to impersonate for the operation. User could be a regular user or a service account in a namespace
      --as-group stringArray    Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --as-uid string           UID to impersonate for the operation.
      --context string          Kubernetes configuration context
  -h, --help                    help for istioctl
  -i, --istioNamespace string   Istio system namespace (default "istio-system")
  -c, --kubeconfig string       Kubernetes configuration file
  -n, --namespace string        Kubernetes namespace
      --vklog Level             number for the log level verbosity. Like -v flag. ex: --vklog=9

Additional help topics:
  istioctl options              Displays istioctl global options

Use "istioctl [command] --help" for more information about a command.
```

without `--as` flag in command:
```
  ./istioctl proxy-config cluster xxx-7ccc68d947-mzlwt 
2024-08-29T18:01:25.110857Z     error   port forward failed: error upgrading connection: pods "xxx-7ccc68d947-mzlwt" is forbidden: User "xxx" cannot create resource "pods/portforward" in API group "" in the namespace "pod-test"
Error: failed to execute command on [xxxx]: failure running port forward process: failure running port forward process: port forward: error upgrading connection: pods "" is forbidden: User "xxx" cannot create resource "pods/portforward" in API group "" in the namespace "xxx"
```
Add `--as` flag in command:
```
  ./istioctl proxy-config cluster xxx-7ccc68d947-mzlwt --as=xxx
SERVICE FQDN                                                    PORT     SUBSET     DIRECTION     TYPE       DESTINATION RULE
BlackHoleCluster                                                -        -          -             STATIC     
agent                                                           -        -          -             STATIC     
dynamic_forward_proxy_cluster                                   -        -          -             STATIC     
prometheus_stats                                                -        -          -             STATIC     
sds-grpc                                                        -        -          -             STATIC     
sni_cluster                                                     -        -          -             STATIC     
xds-grpc                                                        -        -          -             STATIC     

```

**Review by MorrisLaw — APPROVED** [review]
Great work! Thanks again for adding this feature, LGTM

**Pull request merged**
