### PR TITLE
remove Reporter's *dirty* field

### PR DESCRIPTION
**Pull request by cocotyty**
Reporter's `dirty` field is not necessary ,  no code read this field.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[*] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[*] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by cocotyty** [comment]
@therealmitchconnors

**Comment by howardjohn** [comment]
LGTM - @therealmitchconnors can you confirm?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
