### PR TITLE
Revert "[release-1.10] istio-agent csr flow: add api for caClient plugins to explicitly provide CA TrustAnchors if available"

### PR DESCRIPTION
**Pull request by sergii-ssh**
Reverts istio/istio#34226

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
This PR is co-dependant on https://github.com/istio/istio/pull/34255/files, which is likely not being backported (unless it goes through exception process). So revert the backport of this one

**Review by Monkeyanator — APPROVED** [review]

**Pull request merged**
