### PR TITLE
Add list object path dump for profile dump

### LINKED ISSUE #35865: profile dump not support list object path
### Bug Description

```
[root@kebe-iog-11 ~]# istioctl profile dump demo -o json -p values.gateways.istio-egressgateway.secretVolumes
Error: json: cannot unmarshal array into Go value of type map[string]interface {}
```

### Version

```prose
master branch
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by kebe7jun**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/35865

```console
$ istioctl profile dump demo -o json -p values.gateways.istio-egressgateway.secretVolumes
[
    {
        "mountPath": "/etc/istio/egressgateway-certs",
        "name": "egressgateway-certs",
        "secretName": "istio-egressgateway-certs"
    },
    {
        "mountPath": "/etc/istio/egressgateway-ca-certs",
        "name": "egressgateway-ca-certs",
        "secretName": "istio-egressgateway-ca-certs"
    }
]

```

### CODE REVIEW

**Comment by kebe7jun** [comment]
@istio/wg-environments-maintainers PTAL.

**Comment by kebe7jun** [comment]
not stale

**Comment by kebe7jun** [comment]
@morvencao Can you please take a look here?

**Review by morvencao — COMMENTED** [review]
looks good.
can you add testing for this?

**Review by morvencao — APPROVED** [review]
thanks!

**Pull request merged**
