### PR TITLE
Change initializer defaults to match `kube-inject` defaults

### PR DESCRIPTION
**Pull request by ayj**
**What this PR does / why we need it**:

Change initializer defaults to match `kube-inject` defaults. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
/lgtm
I'm not sure when there will be a 0.2.8

**Comment by linsun** [comment]
haha, for all the times, i'm using non-debug proxy :)

**Comment by linsun** [comment]
@ayj do you think we should merge this fix to branch 0.2?  I hit an issue that the proxy (non-debug) didn't have curl thus I can't do this task:  https://istio.io/docs/tasks/security/mutual-tls.html#testing-the-authentication-setup

Installing curl on proxy (non-debug) isn't simple as I can't run apt-get install cmd as the user (it is a non-root user for that image).

**Comment by ayj** [comment]
SGTM

**Pull request merged**
