### PR TITLE
Use http_destination in HTTP Service Panel for success rate denominator

### PR DESCRIPTION
**Pull request by mhamrah**
The current Grafana dashboard template for Success Rate By Source And Version mixes $http_destination in the numerator and $destination in the denominator. This creates a mismatch in the query making the success rate appear lower than it should be depending on your mix of http or tcp based services. This PR makes both use http_destination which aligns with the HTTP Metric section of the dashboard and accurately reporting the success rate.

### CODE REVIEW

**Comment by ijsnellf** [comment]
I'm not qualified to review this. @jeffmendoza: you created the original file, would you like to weigh in?

**Comment by ijsnellf** [comment]
@douglas-reid: Do you have any idea who should review this PR?

**Comment by douglas-reid** [comment]
This PR LG. Can we also remove the unneeded `$destination` template altogether? (i was fixing this in a separate PR).

**Comment by mhamrah** [comment]
$destination isn't needed for the tcp panels? Would it be better to rename?

**Comment by mhamrah** [comment]
Removed $destination in favor of $tcp_destination for bytes sent

**Comment by mhamrah** [comment]
I also upgraded to the release version of Grafana. This works well on our istio/k8s cluster.

**Comment by mhamrah** [comment]
Anything I can do to get this landed? /cc @douglas-reid @jeffmendoza 

Thanks

**Comment by mhamrah** [comment]
blurp

**Pull request closed without merging**
