### PR TITLE
rename EnvoyXdsServer to XDSServer

### PR DESCRIPTION
**Pull request by ramaraochavali**
Rename `EnvoyXdsServer` -> 'DiscoveryServer` as it is not just for Envoy now.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ Z] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
How about `XDSServer`?

**Comment by ramaraochavali** [comment]
> How about XDSServer? Envoy docs saying so

I am fine with that. I was going back and forth between XDSServer and DiscoveryServer. Initially changed to XDSServer and then to DiscoveryServer. I will change to XDSServer

**Pull request merged**
