### PR TITLE
Add IO shortname for istio operator

### PR DESCRIPTION
**Pull request by linsun**
so that users can do

```
$ k get io -n istio-system                   
NAME                            REVISION   STATUS    AGE
example-custom-ingressgateway   custom     HEALTHY   9m15s
example-istiocontrolplane                  HEALTHY   15m
```

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
why do we need io when we have iop?

**Comment by linsun** [comment]
Because IstioOperator translates more intuitively to io, similar as all other shortnames we have like VirtualService to vs, DestinationRule to dr.

**Comment by sdake** [comment]
@linsun seems reasonable to me. As this is a user-facing change, can you add a release note?

Cheers,
-steve

**Review by sdake — APPROVED** [review]
lgtm - feel free to release the hold when the release note is added.

**Review by bianpengyuan — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
