### PR TITLE
[wip] [release-1.11] backport misc proxyless grpc fixes

### PR DESCRIPTION
**Pull request by stevenctl**

### CODE REVIEW

**Comment by jwendell** [comment]
@stevenctl unit tests are failing

**Comment by stevenctl** [comment]
yeah this isn't done.

**Comment by jwendell** [comment]
@stevenctl we are planning to release 1.11.5 this week. Do you think this PR will make it until tomorrow?

**Comment by stevenctl** [comment]
No, unfortunately I don't think it will.

**Comment by stevenctl** [comment]
I think there may be some incompatibility between different versions of gRPC.

**Pull request closed without merging**
