### PR TITLE
Revert changes to always notify XdsUpdater in mem discovery

### PR DESCRIPTION
**Pull request by howardjohn**
This impacts tests only.
In https://github.com/istio/istio/pull/39133 we changed to notify on
writes; this ended up triggering a ton of test flake. Instead, just add
explicit functions to notify (new test needs them) and revert the other changes

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by nmittler** [comment]
@howardjohn do we understand the cause of the flakes? Is this something we'll want to fix and roll-forward later?

**Comment by howardjohn** [comment]
basically tests do "apply some changes, trigger push, wait for push". But
with my change to always trigger push when there are changes , depending on
debounce they may get a different number of pushes.

It's possible to make the tests more robust but there are a lot like this
and they are somewhat complex to fix so I at least don't have bandwidth to
fix in the short term

**Comment by howardjohn** [comment]
depending on the test it's also reasonable to want to explicitly control
the push to test certain things

**Review by hzxuzhonghu — APPROVED** [review]

**Review by adiprerepa — APPROVED** [review]

**Pull request merged**
