### PR TITLE
fix(injection template): correct owner string format

### PR DESCRIPTION
**Pull request by douglas-reid**
The ISTIO_META_OWNER field is improperly specified in the injection template. This PR fixes it.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
What is the right format here? I have seen other similar PRs before, not sure what format this actually expects?

**Comment by douglas-reid** [comment]
@howardjohn i too get a bit lost. i'm going off of the URLS in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#-strong-read-operations-deployment-v1-apps-strong-

**Comment by douglas-reid** [comment]
@howardjohn did this get CP'd correctly? i don't see the bot info here.

**Comment by bianpengyuan** [comment]
That label does not quite seem to work now. The command could make it do the work.

**Comment by bianpengyuan** [comment]
But seems like we need a manual cherry-pick...

**Pull request merged**
