### PR TITLE
Update Istio api SHA

### LINKED ISSUE #7934: Mixer Report: attribute index not defined error
Mixer: `gcr.io/istio-release/mixer:release-1.0-20180810-09-15`
Proxy: `gcr.io/istio-release/proxyv2:release-1.0-20180810-09-15`
The following error was observed while using `release-1.0-20180810-09-15`

```
4050 [libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNKNOWN:1 error occurred:%0A%0A* request could not be processed due to invalid attributes: 1 error occurred:%0A%0A* attribute index 202 is not defined in the available dictionaries
```

The global wordlist compiled with Mixer is older and shorter than the one used by mixer client.
Mixerclient is built with a more recent version of istio/api than Mixer.

### PR DESCRIPTION
**Pull request by bianpengyuan**
fix #7934

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@kyessenov word list in mixer is updated. Thanks!

**Comment by kyessenov** [comment]
The tests are working! Please update the tests to reflect the new attributes.

**Comment by bianpengyuan** [comment]
Close for now. Will update the SHA with a integration test.

**Pull request closed without merging**
