### PR TITLE
set proxy 100 continue to true by default, so that envoy will not str…

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
…ip Expect: 100-continue header

**Please provide a description of this PR:**

Fix: #36278 #21382

Will add ut if this is the right direction.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
will this have negative impact on any users?

**Comment by hzxuzhonghu** [comment]
From api doc, there is no influence. cc @lambdai

**Comment by hzxuzhonghu** [comment]
@lambdai WDYT?

**Comment by hzxuzhonghu** [comment]
ping @lambdai

**Pull request closed without merging**
