### PR TITLE
Envoy: improve logging format configuration

### PR DESCRIPTION
**Pull request by howardjohn**
Before/After JSON:
```
{"level":"debug","time":"2024-03-04T12:11:46.931655Z","scope":"envoy connection","msg":"[Tags: \"ConnectionId\":\"2\"] closing socket: 1","caller":"external/envoy/source/common/network/connection_impl.cc:281","thread":947194}
{"time":"2024-03-04T12:15:57.204132Z","level":"debug","scope":"envoy connection","msg":"closing socket: 0","caller":"connection_impl.cc:281 closeSocket","thread":"956652","ConnectionId":"2"}
```

Before/After plain:
```
2024-03-04T12:21:24.654824Z     debug   envoy connection external/envoy/source/common/network/connection_impl.cc:281    [Tags: "ConnectionId":"2"] closing socket: 0    thread=963777
2024-03-04T12:21:00.256847Z     debug   envoy connection connection_impl.cc:281 closeSocket     [Tags: "ConnectionId":"2"] closing socket: 0    thread=962566
```

Primary benefit is to put envoys structured logs (`[Tags: "ConnectionId":"2"])` into proper top level json keys. We also improve the source file format

### CODE REVIEW

**Comment by kyessenov** [comment]
I disagree that the file name change is an improvement. Please don't force foreign logging templates, it doesn't help debugging.

**Comment by howardjohn** [comment]
What is a 'foreign logging template'?

**Comment by kyessenov** [comment]
Using just file names is a glog pattern. I don't think it's a good one.

**Comment by zirain** [comment]
i recall there's performance issue withjson?

**Comment by howardjohn** [comment]
> i recall there's performance issue withjson?

Any more info on this? We already have a 'json' format, its just partially broken

**Comment by howardjohn** [comment]
> Using just file names is a glog pattern. I don't think it's a good one.

Reverted

> i recall there's performance issue withjson?

This is only for debug logs, mostly, so I don't think performance is important here (there are some warn/error logs in envoy, but its extremely small volume). This is not impacting access logs

**Review by zirain — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
