### PR TITLE
Remove unused attributes of WatchedResource to reduce memory

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Remove `VersionSent NonceNacked LastSent`

### CODE REVIEW

**Comment by howardjohn** [comment]
> In the case 10000 (res)* 1000(proxy), suppose the attributes cost 100Byte, the total mem is: 1GB

Isn't their typically 4-7 resources? Or is this for non-envoy clients?

**Comment by hzxuzhonghu** [comment]
Sorry, mis reading it. Will change the description

**Comment by hzxuzhonghu** [comment]
@ramaraochavali

**Comment by hzxuzhonghu** [comment]
ping @howardjohn @costinm

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
