### PR TITLE
Uniform pilot-agent and pilot-discover 's code style

### PR DESCRIPTION
**Pull request by vince-0202**
**Please provide a description of this PR:**

In this PR,#38542,I shouldn't have submitted go.mod file.

### CODE REVIEW

**Comment by zirain** [comment]
you do not need re-open PR, add more commit then push them.

**Comment by zirain** [comment]
before you submit a PR, please run `make build` to make sure the code is OK.
run `make lint` to lint your changes.

**Comment by vince-0202** [comment]
> before you submit a PR, please run `make build` to make sure the code is OK. run `make lint` to lint your changes.

I really want to run **make build**  , But i can't pull the image 'gcr.io/istio-testing/build-tools:master-2022-04-22T17-24-18' in china.
If VPN connection is used,My pull image request was not allowed.
image
How can I solve this problem.

**Comment by zirain** [comment]
> > before you submit a PR, please run `make build` to make sure the code is OK. run `make lint` to lint your changes.
> 
> @zirain I really want to run **make build** , But i can't pull the image 'gcr.io/istio-testing/build-tools:master-2022-04-22T17-24-18' in China. If VPN connection is used,My pull image request was not allowed. image How can I solve this problem.

can you access docker hub?

**Comment by vince-0202** [comment]
@zirain thanks,It works, I'm already fixed my fault

**Review by howardjohn — CHANGES_REQUESTED** [review]
A number of unexpected changes here. Maybe a git issue.

**Review by vince-0202 — COMMENTED** [review]
I think i should fix it in a new branch,To many unexpected changed here,

**Pull request closed without merging**
