### PR TITLE
Enhance validation for mixer args

### PR DESCRIPTION
**Pull request by supereagle**

### CODE REVIEW

**Comment by supereagle** [comment]
I find this comments, not sure whether need to allow these ports to be `0`. 
Could you give some suggestion?  @douglas-reid  @kyessenov 

> 	// Setting zero will make Mixer pick any available port.
	args.APIPort = 0
	args.MonitoringPort = 0

**Comment by douglas-reid** [comment]
/ok-to-test

I believe that comment is referencing the capability of Mixer to pick an open port if no port is provided (value is 0).

cc: @geeknoid

**Comment by geeknoid** [comment]
Yes, it is important to support letting the port be selected automatically. Otherwise, hardcoding ports will lead to failures in unit tests as there will be attempts to reuse the same port.

**Comment by supereagle** [comment]
@douglas-reid  Need your approval, thx

**Comment by supereagle** [comment]
@kyessenov  @douglas-reid  Could you help to approve?

**Pull request merged**
