### PR TITLE
add outlier log path configuration in mesh proxy config

### PR DESCRIPTION
**Pull request by JingmingGuo**
**Please provide a description of this PR:**
OutlierLogPath is already added in envoy proxy config: https://github.com/istio/istio/blob/91868f70ae0ce459300cbca68f60705ccc45153c/pkg/envoy/proxy.go#L46 but missing the configuration pass from istio operator.

Add the outlier log path configuration to mesh proxy config. After this change, users can add in the desired outlier log path to expose envoy outlier logging properly.

### CODE REVIEW

**Comment by bleggett** [comment]
@JingmingGuo please add release notes - thanks.

This makes sense to me (and the TODO clearly implies a gap), but I don't have a ton of context.

**Comment by ramaraochavali** [comment]
Currently how are users configuring outlier detection path? I see it was added https://github.com/istio/istio/pull/19117 - not sure how it is removed again. @howardjohn do you remember the history?

**Comment by JingmingGuo** [comment]
> Currently how are users configuring outlier detection path? I see it was added #19117 - not sure how it is removed again. @howardjohn do you remember the history?

I don't see there is a way that user can config it ATM. The outlier_log_path is passed to envoy outlier_detection event_log_path: https://github.com/istio/istio/blob/e8cddfb585338ce36676f36d3e49f0981e0089b9/tools/packaging/common/envoy_bootstrap.json#L828 but there is no way to pass the config from Istio operator.

The context and history will be very helpful here.

**Comment by MorrisLaw** [comment]
> > Currently how are users configuring outlier detection path? I see it was added #19117 - not sure how it is removed again. @howardjohn do you remember the history?
> 
> I don't see there is a way that user can config it ATM. The outlier_log_path is passed to envoy outlier_detection event_log_path:
> 
> https://github.com/istio/istio/blob/e8cddfb585338ce36676f36d3e49f0981e0089b9/tools/packaging/common/envoy_bootstrap.json#L828
> 
> but there is no way to pass the config from Istio configuration.
> The context and history will be very helpful here.

[Support outlierDetection logging PR #19117](https://github.com/istio/istio/pull/19117)

This seems to be the PR in which ` "event_log_path": "{{ .outlier_log_path }}" ` this was added. I don't have the context, but maybe this might be helpful? Here is the corresponding issue as well "[Enable outlierDetection logging](https://github.com/istio/istio/issues/18555)". Unfortunately the envoy documentation linked in that issue, just points to a 404 😅

**Comment by JingmingGuo** [comment]
Looks like the request on https://github.com/istio/istio/issues/39635

> > > Currently how are users configuring outlier detection path? I see it was added #19117 - not sure how it is removed again. @howardjohn do you remember the history?
> > 
> > 
> > I don't see there is a way that user can config it ATM. The outlier_log_path is passed to envoy outlier_detection event_log_path:
> > https://github.com/istio/istio/blob/e8cddfb585338ce36676f36d3e49f0981e0089b9/tools/packaging/common/envoy_bootstrap.json#L828
> > 
> > but there is no way to pass the config from Istio configuration.
> > The context and history will be very helpful here.
> 
> [Support outlierDetection logging PR #19117](https://github.com/istio/istio/pull/19117)
> 
> This seems to be the PR in which `"event_log_path": "{{ .outlier_log_path }}"` was added. I don't have the context, but maybe the corresponding issue might be helpful? "[Enable outlierDetection logging](https://github.com/istio/istio/issues/18555)". Unfortunately the envoy documentation linked in that issue, just points to a 404 😅

Thanks for linking the related issues! I see this PR implements the second option provided here: https://github.com/istio/istio/issues/39635#issuecomment-1225385143

@zirain @howardjohn Could you mind having a look?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
