### PR TITLE
fix typo in default envoy JSON log format

### PR DESCRIPTION
**Pull request by dwradcliffe**
Fixes https://github.com/istio/istio/issues/12232

### CODE REVIEW

**Comment by esnible** [comment]
The code coverage failure is

```
    main_test.go:216: Coverage dropped:
        istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:-12.200000% (73.200000% to 61.000000%)
```

This is caused by https://github.com/istio/istio/issues/12316 and is not the fault of this PR.  It is a random failure.  I will attempt to re-run it.

**Comment by GregHanson** [comment]
@wenchenglu can we get this one merged?  Minor bug fix and the circleci failure is unrelated

**Comment by linsun** [comment]
good catch!  cc @duderino

**Comment by wenchenglu** [comment]
lgtm on my side. This is a nice fix, and I don't see risk merging this to 1.1 if the new release hasn't been cut yet. But if the new release has already been cut, I think this can wait til 1.1.1
@duderino what do you think?

**Comment by dwradcliffe** [comment]
_bump_

**Comment by GregHanson** [comment]
@wenchenglu can we get this one merged to 1.1?

**Pull request merged**
