### PR TITLE
Correctly supporting auth modes in pilot e2e tests

### PR DESCRIPTION
**Pull request by nmittler**
Introduced by abcd9d417b51a1a4cc4a1827654b062f7a38bda6

### CODE REVIEW

**Comment by nmittler** [comment]
@ldemailly this will certainly add logging in cases where authmode is configured as `both`, since we'll now properly run the tests twice (with and without auth)

**Comment by ldemailly** [comment]
filled #3518 for the prow error

/test istio-pilot-e2e

**Comment by ldemailly** [comment]
/lgtm

I'm a bit worried about not running the prow test though

**Comment by ldemailly** [comment]
@chxchx can you look at #3518 asap please?

**Pull request merged**
