### PR TITLE
Fix lint failure in circleci

### PR DESCRIPTION
**Pull request by sdake**
A for loop over the main dir would use far less memory.  Will
see if we can get this stable first as we are not in a big
rush to move to 1.17 as it is a little more noisy with the linting.

### CODE REVIEW

**Comment by sdake** [comment]
in-gate memory usage seems to work with this PR (from logs):
```
INFO Memory: 248 samples, avg is 8933.0MB, max is 15623.7MB 
```

Matches my bare metal run.

**Comment by sdake** [comment]
https://github.com/istio/pkg/pull/25

**Comment by sdake** [comment]
@howardjohn I did a binary search of the best gogc value in the issue tracker.  Might be worth a look.

Cheers
-steve

**Comment by geeknoid** [comment]
Closing, replacing with https://github.com/istio/common-files/pull/11 instead.

**Pull request closed without merging**
