### PR TITLE
Extend istioctl mocking library to allow mocking of authn etc

### PR DESCRIPTION
**Pull request by esnible**
Implements https://github.com/istio/istio/issues/13116

### CODE REVIEW

**Comment by esnible** [comment]
@nmittler @ozevren My PR is failing lint for _galley/pkg/runtime/projections/serviceentry/handler.go_:135

```
S1031: unnecessary nil check around range
```

due to a change made yesterday.  https://github.com/istio/istio/pull/12890

Please advise.

**Comment by esnible** [comment]
@liamawhite @ayj This is mostly just more tests; it should be easy to review.

**Comment by esnible** [comment]
@nmittler @liamawhite @ayj This is mostly just more tests; it should be easy to review.

**Comment by esnible** [comment]
My hope is to do more work on _istioctl_ unit tests, mocking, and e2e tests.  Please review this PR, which just adds mocking and testing, so that I know if I am on the right track for adding tests for 1.2.  @nmittler @liamawhite @ayj

**Comment by ozevren** [comment]
/lgtm
The linter issues seem to be gone.

**Comment by esnible** [comment]
/test istio-pilot-e2e-envoyv2-v1alpha3
Rerunning because the previous test "failed to get a Boskos resource".

**Pull request merged**
