### PR TITLE
fix empty endpoints weight for AUTO_PASSTHROUGH gateway

### PR DESCRIPTION
**Pull request by bincherry**
**Please provide a description of this PR:**

For AUTO_PASSTHROUGH gateway, typically istio-eastwestgateway, the endpoints of SNI-dnat cluster will be filtered by mtls checker. Yet the filtered `LocalityLbEndpoints` results have empty `LoadBalancingWeight`, that would cause LB error in sidecar.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you give more details? How to replicate? What error? And we need tests covering this

**Comment by tedli** [comment]
The case is that, service call cross clusters through eastwest gateway with lb policy of consistency hash, result no healthy upstream. Because the locality weight in cluster load assignment is 0.

Ring hash logic in envoy code, read the locality weight:

https://github.com/envoyproxy/envoy/blob/652a89b6a76e6a59521a46d764b2bd52317421a0/source/common/upstream/thread_aware_lb_impl.cc#L54

https://github.com/envoyproxy/envoy/blob/652a89b6a76e6a59521a46d764b2bd52317421a0/source/common/upstream/ring_hash_lb.cc#L54

**Comment by bincherry** [comment]
> Thanks for the PR! Can you give more details? How to replicate? What error? And we need tests covering this

Errors would happen in sidecar because of the empty load_balancing_weight of endpoints, which should be as least 1. For exmaple as described by tedli.

For now the empty load_balancing_weight will happen on every eastwestgateway, and we could get config_dump and check endpoints of SNI DNAT clusters to find it.

```

    {
     "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "outbound_.8081_._.web.sky.svc.cluster.local",
      "endpoints": [
       {
        "locality": {},
        "lb_endpoints": [
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "172.30.40.144",
             "port_value": 8081
            }
           },
           "health_check_config": {}
          },
          "health_status": "HEALTHY",
          "metadata": {
           "filter_metadata": {
            "envoy.transport_socket_match": {
             "tlsMode": "istio"
            },
            "istio": {
             "workload": "web;sky;web;latest;cid-5a3b17793356"
            }
           }
          },
          "load_balancing_weight": 1
         }
        ],
        "load_balancing_weight": 0             ### HERE
       }
      ],
      "policy": {
       "overprovisioning_factor": 140
      }
     }
    },
```

**Comment by hzxuzhonghu** [comment]
cc @stevenctl 

/ok-to-test

**Review by stevenctl — APPROVED** [review]

**Comment by stevenctl** [comment]
Good catch, probably part of the fix for https://github.com/istio/istio/issues/38704

**Comment by stevenctl** [comment]
cc @howardjohn if you want to drop the change request

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by tedli** [comment]
Hi all,

During we debug with this pr, we also found another issue https://github.com/istio/istio.io/pull/11680, which was not documented. Then we give a pr to the doc repo.

Could someone help to assign reviewers to take a look?

**Pull request merged**
