### PR TITLE
Bump envoy api to 3a04e5314385acb275da35cedb3c088c1e90dd50

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is to fix: #21982

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Currently, we have no mechanism to make sure upgrading envoy api along with proxy. @howardjohn 

For release-1.4 the proxy is bumped to almost the latest. But the api is relatively very old.

**Comment by hzxuzhonghu** [comment]
We have to cherry-pick #20564 as well. I want to know if it is worth it before i do.

**Comment by howardjohn** [comment]
We should not be changing the Envoy version here. Why do we need to change that in order to update go-control-plane?

**Comment by hzxuzhonghu** [comment]
There are many mismatch types

**Comment by hzxuzhonghu** [comment]
It is not safe to backport so many codes, i think.

**Comment by hzxuzhonghu** [comment]
To reduce the risk as much as possible, only update to commit including the common_http_options

**Pull request closed without merging**
