### PR TITLE
use the default namespace based on what the current kubectl context i…

### PR DESCRIPTION
**Pull request by christian-posta**
…s. fix https://github.com/istio/istio/issues/2486

### CODE REVIEW

**Comment by christian-posta** [comment]
Is this failure one of those intermittent ones that can be run again and crossing fingers?

**Comment by sdake** [comment]
@christian-posta I've noticed that test fails often - not sure if it fails 100% of the time or not.

**Comment by christian-posta** [comment]
Thx for kicking it for me @sdake 
Do I have karma/auth to kick the tests myself?

**Comment by rshriram** [comment]
@christian-posta for future reference, if you authorize circleci for your GH account, you can easily go and rebuild the failing tests/ssh into the container/vm and debug, etc.. But I think the failing test in this case was from prow?

**Comment by christian-posta** [comment]
@rshriram yah was prow; but that's good to know for future about circleci

**Comment by sdake** [comment]
@christian-posta No I'm pretty sure member is required; although you can run the circleci tests as @rshriram points out.

Cheers,
-steve

**Pull request merged**
