### PR TITLE
Use Kubernetes 1.19 in CI

### PR DESCRIPTION
**Pull request by howardjohn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by brian-avery** [comment]
@howardjohn I think this one needs release notes/upgrade notes.

**Comment by howardjohn** [comment]
Why? its not user facing

**Comment by howardjohn** [comment]
/retest

I think its a flake in ubuntu  not related

**Comment by brian-avery** [comment]
Oh wait. Nevermind. Read it, reviewed it in terms of CI, and then was thinking of supporting 1.19.

**Comment by howardjohn** [comment]
/retest

same ubuntu flake

**Comment by howardjohn** [comment]
Ipv6 has legit failures - researching

**Comment by howardjohn** [comment]
Blocked by 4d901a84e5907fba9d50825c8acab14794254a9d in kind. Will wait a ~week for release with that sha.

**Review by ericvn — APPROVED** [review]

**Pull request closed without merging**
