### PR TITLE
Turn auto mTLS on by default for 1.4

### PR DESCRIPTION
**Pull request by incfly**
Turn this feature on by default and see what happens.

Mixer label is no longer needed. Control plane mTLS with Mixer always have a DestinationRule

- If control plane auth is enabled, DR.ISTIO_MUTUAL override the auto mTLS feature, so we don't care
- If control plane auth is disabled, we have DR.TLS.DISABLE, auto mTLS is also disabled.

Previous this is an issue because we make it wrong that default cluster has transport_socket matches. This is now fixed.

Some rbac test makes incorrect mTLS settings due to this change, fixed that via creating explicit destination rule or update the expectations (in new test framework)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
for 1.4 or 1.5? I thought you mentioned this wouldn't be on for 1.4

**Comment by incfly** [comment]
@howardjohn that's what I planned before. But on Thursday's data plane WG meeting, we think it's worth to aim at 1.4 default on so that having more exposure in release process testing.

Similar to protocol sniffing what we did in 1.3.

**Comment by howardjohn** [comment]
Ok of that's the case we should get this in ASAP. Is this ready to be merged?

**Comment by incfly** [comment]
Need to fight with failing CI test failures. Some tests assume the mTLS enabling is determined in the old fashion (global mTLS policy and DR), which cause some issue since we change the default expectation...

New installer also introduce some failures, is the procedure update the new installer in advance and then sync this PR to master again? after we're confident the rest issues are addressed? @diemtvu similar to what you did in the PR to add this `mtls.auto` flag?

---

Aside from that, dashboard test seems tricky... It seems to introduce some route delay on ingress gateway after enabling the feature, -- my explanation of `e2e_dashboard` failure

- fortio request to ingress getting `503 NR`, (used to be response cod 200/418)
- Wait for extra time, then it's fine.
- I confirmed the ingress cluster and destination service/echosrv listeners config are expected)...

Can't think why the feature has anything to do with route propagation delay, @rshriram @GregHanson any thoughts?

---

**Comment by incfly** [comment]
I think I discover the root cause of (at least one category of the) test failure... Filed https://github.com/istio/istio/issues/18106

**Review by rshriram — APPROVED** [review]

**Comment by incfly** [comment]
/test integ-pilot-k8s-tests_istio

(The run passed but github reports as failure...)

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
