### PR TITLE
add error line for destination rule's ca-cert analyzer

### PR DESCRIPTION
**Pull request by monsteredc**
add error line number for destination rule ca certificate analyzer. Later will try to reopen this issue #26696, to add a kind of method like `GetJSONPath` for structs to be more developer-friendly.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by shamsher31 — APPROVED** [review]

**Comment by shamsher31** [comment]
@esnible PTAL.

**Comment by shamsher31** [comment]
@esnible can you please provide your feedback?

**Comment by monsteredc** [comment]
@istio/wg-test-and-release-maintainers PTAL. Thanks!

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
