### PR TITLE
Removed flag multicluster.enabled from values.yaml.

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @sdake @costinm @baodongli

### CODE REVIEW

**Comment by tiswanso** [comment]
This change breaks using the helm charts for multicluster with the control plane in any namespace other than istio-system.  The controller for the secrets for the remotes' kubeconfigs relies on the `--ClusterRegistriesNamespace` pilot discovery arg.

**Comment by tiswanso** [comment]
@sdake  Found this with the e2e tests.  They always create random-ish namespaces to install the Istio control-plane.

**Comment by andraxylia** [comment]
The design always allowed istio to be run in any namespace, not only istio-system. This got lost somewhere.

As of last year, e2e tests for multiple users were run in a shared cluster, but restricted to a single namespace created with a random name. Now, each run has the entire cluster, so it's ok to istio-system, but there should not be any implicit assumption about the name.

**Comment by sdake** [comment]
@gyliu513 that sounds good to me.  The primary goal here is to enable the e2e  tests that already implement multicluster with a secondary goal of removing the configmap for good.

**Comment by sdake** [comment]
@andraxylia thanks for the correction.  Hard to keep up with all of the policy changes wrt Istio :)  Seems like @gyliu513 offers a simple approach to solving this problem with an optional `--multiclusterSecretsNamespace` that defaults to `istio-system`.

**Comment by gyliu513** [comment]
@sdake @tiswanso @andraxylia I posted a PR at here https://github.com/istio/istio/pull/6459

**Pull request merged**
