### PR TITLE
[release-1.22] monitoring: move to OTEL sync gauge

### PR DESCRIPTION
**Pull request by sschepens**
**Please provide a description of this PR:**
Backport #52826 to Istio 1.22, update otel dependencies.

Fixes https://github.com/istio/istio/issues/53289

### CODE REVIEW

**Comment by sschepens** [comment]
@howardjohn dependencies have to be updated to be able to backport this, I don't know if that's desired, if not I could just have a go at fixing the crash instead of backporting

**Comment by hzxuzhonghu** [comment]
Not sure why we cherrypick a feature back when we actually need to fix a panic.

**Comment by howardjohn** [comment]
The old code has the panic and new code does not. Plausibly it could be
fixed in the old code to not panic though, I did not investigate.

**Comment by howardjohn** [comment]
I wouldn't really call it a new feature though, there is no user facing
change - just new implementation

**Comment by hzxuzhonghu** [comment]
I donot feel strongly, absolutely it is better if this panic can be fixed without much change.

**Pull request closed without merging**
