### PR TITLE
Support comma seperated list of HUBS for build-base-images.sh

### PR DESCRIPTION
**Pull request by ericvn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Would be better to make `make dockerx` support this natively. Then we just build once and push in parallel. Right now its slower and may actually build two different images

**Comment by ericvn** [comment]
@howardjohn I'll look into that Makefile change as well. That might be a little harder more places look at HUB.

**Pull request merged**
