### PR TITLE
change env ISTIO_VERSION , match the latest.

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

/kind cleanup

Fix ```export ISTIO_VERSION``` , for the latest version.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by howardjohn — COMMENTED** [review]
We aren't going to update this every release so I am not sure the benefit of this? If anything it may be better to set it to 1.0.0 or something to make it clear it is a placeholder?

Or 0.0.0 so its not a real version...

**Comment by yanggangtony** [comment]
> We aren't going to update this every release so I am not sure the benefit of this? If anything it may be better to set it to 1.0.0 or something to make it clear it is a placeholder?
> 
> Or 0.0.0 so its not a real version...

yes.. thanks for the advice.
its hard to define the version number..
So just close the pr , is that ok?

**Comment by ymesika** [comment]
Closing per @yanggangtony request

**Pull request closed without merging**
