### PR TITLE
proxy hub and tag should be fetching from pilot

### PR DESCRIPTION
**Pull request by linsun**
in values.yaml.tmpl, as that is what we do in the update_istio_install() around line 256 for non helm scenario.

cc @luisyonaldo thank you for the https://github.com/istio/istio/pull/2557#pullrequestreview-91229751

### CODE REVIEW

**Comment by luisyonaldo** [comment]
that fixes the bug but my point was more about why does `PROXY_HUB` exist in the first place. Each time is used on `updateVersion.sh` is being replace with `PILOT_HUB` value, which mean that it's just not needed. Unless I'm missing something.

**Comment by linsun** [comment]
@luisyonaldo I think @ZackButcher answered your question in the other PR, which I agree with Zack.  This is something confusing and took me quite a while to find out myself.   We should be producing/putting proxy images into proxy_hub, it is just we are not there yet today.

**Comment by costinm** [comment]
/lgtm

I think we have too much confusion on allowing each component to have a custom tag and repository. 
For 99% of cases we should have 'istio_hub' and 'istio_tag'. 
Advanced users who want to download each component from a different hub or use a mix of builds can edit the yaml file. 

In particular the tag should be a single setting, and accept an TAG or ISTIO_TAG environment override
( as used in the makefile for example).

**Comment by costinm** [comment]
/retest
/lgtm
(to clear the bot after the rebase that affected everyone)

**Comment by linsun** [comment]
Thank you @costinm!

**Pull request merged**
