### PR TITLE
Remove chmod from pilot dockerfile

### PR DESCRIPTION
**Pull request by phil9909**
As proposed in https://github.com/istio/istio/pull/12741#discussion_r268611724

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
The racetest seems to fail in many unrelated PRs, what is the test worth if it is ignored anyhow?

**Comment by sdake** [comment]
Docker inherits the permissions of the file on the filesystem.  Hence this line is redundant and was asked to be broken out from another review.

/lgtm

**Comment by sdake** [comment]
> The racetest seems to fail in many unrelated PRs, what is the test worth if it is ignored anyhow?

racetest is probably something that needs to be hardened for the code muave..

**Comment by jsPlachetka** [comment]
Got merged into #13579.

**Pull request closed without merging**
