### PR TITLE
Revert "update MutatingWebhook apiVersion to v1 and other minor fixes"

### LINKED ISSUE #26280: In-place/canary upgrade 1.6->1.7 failure on k8s 1.16
**Bug description**
On k8s 1.16, Install Istio 1.6 first, then install Istio 1.7 for in-place upgrade. The 1.6 webhook will have a similar issue like: https://github.com/istio/istio/issues/26186. seems like we need to apply https://github.com/istio/istio/pull/26187 to release 1.6 as well to support inplace upgrade.

Background: https://github.com/kubernetes/kubernetes/issues/85681
Webhook v1beta1 -> v1 PR: https://github.com/istio/istio/pull/24723

```
$ ./istioctl install -f my-istio-operator.yaml
✔ Istio core installed                                        
2020-08-07T17:33:53.283001Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T17:33:53.476295Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T17:33:53.683472Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T17:33:53.890488Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T17:33:54.127200Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T17:33:54.320725Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
```
Same for canary upgrade:
```
$ ./istioctl install  -f my-istio-operator.yaml  --set revision=canary
✔ Istio core installed                                                                                                                                                 
2020-08-07T18:42:14.472831Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.6-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T18:42:14.595879Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.7-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T18:42:14.730029Z     error   installer       failed to create "EnvoyFilter/istio-system/stackdriver-filter-1.6-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T18:42:14.861414Z     error   installer       failed to create "EnvoyFilter/istio-system/stackdriver-filter-1.7-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T18:42:14.987809Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.6-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
2020-08-07T18:42:15.116263Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.7-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
✘ Istiod encountered an error: failed to create "EnvoyFilter/istio-system/metadata-exchange-1.6-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
failed to create "EnvoyFilter/istio-system/metadata-exchange-1.7-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
failed to create "EnvoyFilter/istio-system/stackdriver-filter-1.6-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
failed to create "EnvoyFilter/istio-system/stackdriver-filter-1.7-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.6-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.7-canary": Internal error occurred: failed calling webhook "validation.istio.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by tariq1890**
Revert "update MutatingWebhook apiVersion to v1 and other minor fixe (#24723)"

Retain "add mwc v1beta1 api to runtime scheme (#26187)"

This reverts commit 1772c281

Fixes #26280

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
Is #26187 the only future proofing we need to allow us to upgrade in 1.8?

**Comment by tariq1890** [comment]
@howardjohn I believe so yes. Given that #26187 solved @nmittler 's issue #26186

**Comment by tariq1890** [comment]
Also. I am fairly certain the cherrypick to 1.7 will be manual

**Comment by elfinhe** [comment]
> @howardjohn I believe so yes. Given that #26187 solved @nmittler 's issue #26186

I can do one more verify after this revert is merged and the new build is ready, i.e., install the build after revert, in-place update to the build before the revert.

**Review by howardjohn — APPROVED** [review]

**Review by elfinhe — APPROVED** [review]

**Review by JimmyCYJ — APPROVED** [review]

**Comment by tariq1890** [comment]
@elfinhe Please let me know once you get the results of your testing. After that, I can do the cherrypick to release-1.7

**Review by jasonwzm — APPROVED** [review]

**Comment by tariq1890** [comment]
Appeasing the prow gods should be a full-time job

**Comment by elfinhe** [comment]
@tariq1890 we need to keep `admissionReviewVersions: ["v1", "v1beta1"]` but still use v1beta1 api to support upgrade from 1.7 -> 1.8. See more in https://github.com/istio/istio/issues/26280.

**Comment by tariq1890** [comment]
In the yaml manifests you mean?

**Comment by tariq1890** [comment]
I can do that in a separate PR. And we can cherry pick that to 1.7 too

**Pull request merged**
