### PR TITLE
Update GCP DM template for 0.8

### PR DESCRIPTION
**Pull request by salrashid123**
* Update GCP DM template for ```0.8.0``` as well as -2 releases 
* Update GKE ```initialClusterVersion: 1.9.7-gke.1```  (we have to keep specifying it in the template until default clusterVersion is > 1.9
* separate PR to update docs

* staged tempalte is hosted on my personal git page here:
  - [https://console.cloud.google.com/launcher/config?templateurl=https://raw.githubusercontent.com/salrashid123/deploymentmanager-samples/master/istio_dm/istio-cluster.jinja](https://console.cloud.google.com/launcher/config?templateurl=https://raw.githubusercontent.com/salrashid123/deploymentmanager-samples/master/istio_dm/istio-cluster.jinja)

### CODE REVIEW

**Comment by andraxylia** [comment]
cc @hklai

**Comment by hklai** [comment]
@salrashid123 These files are referenced and inked from the doc only, and are not packaged in the 0.8.0 artifacts, correct?

**Comment by salrashid123** [comment]
@hklai The changes need to apply to the ```release-0.8.0``` artifacts.   When a user clicks on the gke-dm quickstart docs, it spins up a DM template but the source for the template (which includes the release install instructions), specified a path back to ```github.istio/istio/...```.

(we could change the location where the raw template is read from but see its better if its back somwhere under istio's github)

**Comment by hklai** [comment]
@salrashid123 
If the file is needed on https://github.com/istio/istio only, why is it needed in the 0.8.0 artifacts (that we built and released last week).

And is it your intention to make these files available in the corresponding release branches going forward?

**Comment by salrashid123** [comment]
The change doens't _haveto_ get attached to ```release-0.8``` specifically, it just need to be available via a url here at the end:
- [https://raw.githubusercontent.com/istio/istio/master/install/gcp/deployment_manager/istio-cluster.jinja](https://raw.githubusercontent.com/istio/istio/master/install/gcp/deployment_manager/istio-cluster.jinja)


I can file a PR like this one that i cancelled like this if cherrypick back to ```release-0.8``` isn't in play.
* https://github.com/istio/istio/pull/5990

LMK where 
@geeknoid 
@selmanj

**Comment by hklai** [comment]
@salrashid123 actually that is exactly my question. =)
Are you going to have different versions of DM files for different istio versions?

E.g.
https://raw.githubusercontent.com/istio/istio/release-0.8/install/gcp/deployment_manager/istio-cluster.jinja
https://raw.githubusercontent.com/istio/istio/release-1.0/install/gcp/deployment_manager/istio-cluster.jinja

If so, this should go to the release branch (release-0.8), and I can help merge it. Otherwise, this should go to master where different versions of docs point to the same set of DM files.

**Comment by geeknoid** [comment]
I'm going to be adding a mechanism in the docs to easily reference
per-branch files from GitHub.

So in the 0.8 docs, it will reference the 0.8 files in GitHub, in the 1.0
docs it will reference the 1.0 files in GitHub, etc. I was planning on
getting this in tonight since I need it for some other stuff I'm working on.

**Comment by salrashid123** [comment]
I like the idea of 'if you clicked the quickstart from 1.0, you get 1.0, .8 gives you a .8 cluster' and no option to deviate from there...(is there a compelling reason to do that in a 'quickstart`?  i'd say only more advanced users would entertain that in which case the dm-quickstart isn't the place).   We can add a line in the ```.8``` DM quickstart docs stating this.

at the moment, its just one big file which allows to pick the version itself fom the UI.

```
if [ "{{ properties['installIstioRelease'] }}" == "0.8.0" ]; then
...
if [ "{{ properties['installIstioRelease'] }}" == "0.7.1" ]  || [ "{{ properties['installIstioRelease'] }}" == "0.6.0" ]; then
```

if you're all ok w/ this, then i'll just remove the second ```if``` statement block and also remove the option in the DM ui dropdown where users can select the version (even if they came from the .8 docs).

and keep this PR as-is  targeted towards  ```release-0.8```

**Comment by selmanj** [comment]
@salrashid123 Sounds like a good idea to me!

**Comment by hklai** [comment]
@salrashid123 SGTM

And since this is going to release-0.8, does it still need the following check?
if [ "{{ properties['installIstioRelease'] }}" == "0.8.0" ];

**Comment by salrashid123** [comment]
ok, I removed the conditional for the different versions; its locked to ```0.8``` which is still read in from the template parameters (vs hardcoding into the install).  I also added in a minor statement into the docs PR to state we're installing the current rease thats in context

**Comment by hklai** [comment]
/test e2e-simple
/test e2e-bookInfo
/test e2e-bookInfo-envoyv2-v1alpha3
/test istio-pilot-e2e-envoyv2-v1alpha3
/test istio-pilot-e2e

(The change should not have broken any of these tests. Rerunning tests just for sanity. )

**Comment by salrashid123** [comment]
hi  @hklai -  i can execute ```/retest``` for this but it shoudn't matter;  as you mentioned, the test failures don't apply to this specific PR.  Its fine to merge the specific changes as-is

**Pull request merged**
