### PR TITLE
Cherry-pick #9559: Rename identity-domain to trust-domain.

### PR DESCRIPTION
**Pull request by axel7born**
Trust domain seems to be the correct term for spiffe:
https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#21-trust-domain

Co-authored-by: Ralf Pannemans <ralf.pannemans@sap.com>

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
Hi @hzxuzhonghu, could you please help us? Seems we cant trigger a retest.

**Comment by hzxuzhonghu** [comment]
OK. Have you read the wiki? https://github.com/istio/istio/wiki/Working-with-CircleCI

**Comment by axel7born** [comment]
> OK. Have you read the wiki? https://github.com/istio/istio/wiki/Working-with-CircleCI

The wiki is only about CircleCI. 
But we have prow tests, that prevent this change from being merged.

**Comment by hzxuzhonghu** [comment]
Sorry, my mistake. The bot tells us. https://github.com/istio/istio/pull/9740#issuecomment-436898504

Have a try.

**Comment by myidpt** [comment]
Thanks for the work!

**Pull request merged**
