### PR TITLE
Refactor pilot dashboard to improve key metric visibility

### PR DESCRIPTION
**Pull request by howardjohn**
This is built on https://github.com/istio/istio/pull/15476 but extended a bit as doug is out of office.

See the dashboard at https://snapshot.raintank.io/dashboard/snapshot/cKhmOMMH83eEb2oKYr9VLJNsKEv1afQl?orgId=2

Improvements

- consistent use of irate in CPU chart
- consolidation of errors to single chart (and away from push chart, where they were being hidden)
- simplification of the ADS Monitoring panel
- addition of a proxy_convergence_time panel
- redesign of EDS Instances to instead only show clusters with no endpoints
- clarification of envoy provenance for some metrics
- Add more envoy stats

### CODE REVIEW

**Comment by mandarjog** [comment]
John, the dashboard test failure is genuine.
1. Check if the data your are showing is always collected.
2. If not, queries can be excluded from dash tests.

**Comment by howardjohn** [comment]
yeah I need to exclude some of the error ones which never happen. Thanks!

**Comment by howardjohn** [comment]
@mandarjog I got the test passing

**Pull request merged**
