### PR TITLE
Fix the db auth test

### PR DESCRIPTION
**Pull request by ldemailly**
No idea why it was setup without kube inject

```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
On my own machine and cluster:

before
```
DbTest fails and :

#mongodb pod:
2017-09-09T00:31:18.185+0000 I NETWORK  [thread1] connection accepted from 10.24.2.13:55676 #12 (1 connection now open)
2017-09-09T00:31:18.186+0000 I -        [conn12] AssertionException handling request, closing client connection: 17132 SSL handshake received but server is started without SSL support
2017-09-09T00:31:18.186+0000 I -        [conn12] end connection 10.24.2.13:55676 (1 connection now open)
```

after:
```
=== RUN   TestDbRouting
I0908 17:54:28.647539   81635 commonUtils.go:73] Running command kubectl apply -n demo-test-9843206c5012405eb4601b78974 -f /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/demo_test859916522/route-rule-ratings-db.yaml
I0908 17:54:33.643864   81635 commonUtils.go:76] Command output: 
 routerule "ratings-test-v2" created
routerule "reviews-test-ratings-v2" created
, err: <nil>
I0908 17:54:33.643899   81635 demo_test.go:258] Waiting for rules to propagate...
I0908 17:55:03.854038   81635 demo_test.go:205] Get from page: 200
I0908 17:55:03.854983   81635 demo_test.go:133] Success! Response matches with expected! glyphicon-star
I0908 17:55:03.855003   81635 commonUtils.go:73] Running command kubectl delete -n demo-test-9843206c5012405eb4601b78974 -f /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/demo_test859916522/route-rule-ratings-db.yaml
I0908 17:55:04.148781   81635 commonUtils.go:76] Command output: 
 routerule "ratings-test-v2" deleted
routerule "reviews-test-ratings-v2" deleted
, err: <nil>
I0908 17:55:04.148805   81635 demo_test.go:245] Waiting for rule to be cleaned up...
--- PASS: TestDbRouting (65.50s)
PASS

# mongodb
2017-09-09T00:55:03.802+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:39326 #1 (1 connection now open)
2017-09-09T00:55:03.803+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:39326 conn1: { driver: { name: "nodejs", version: "2.2.31" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.64+" }, platform: "Node.js v4.8.4, LE, mongodb-core: 2.1.15" }
2017-09-09T00:55:03.830+0000 I -        [conn1] end connection 127.0.0.1:39326 (1 connection now open)
```

**Comment by ldemailly** [comment]
@rshriram this test has been failing forever and just finally after we spent many hours debugging it is finally working - what is your objection ? this is going in as it finally gets us where we want to be which is "rbac + auth" passing and we can make that the mandatory test which is what we need for a release.

**Comment by rshriram** [comment]
Sorry this is the test. Let's not touch docs.

**Comment by andraxylia** [comment]
@rshriram how can auth and non-auth talk mTLS? This has to be kube-injected.

**Comment by andraxylia** [comment]
/lgtm
@ldemailly thanks for fixing this.

**Comment by ldemailly** [comment]
merging as it passed for the test that matters 

--- PASS: TestDbRouting 
I0909 01:27:27.766] PASSED: //tests/e2e/tests/bookinfo:go_default_test

**Comment by lookuptable** [comment]
@ldemailly thanks a lot for digging this out!

**Pull request merged**
