### PR TITLE
populate accurate version into xds response

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by fpesce** [comment]
Please make sure to land yhour changes to master first.
c.f. point 5 [1.2 Release branch cut](https://discuss.istio.io/t/1-2-release-branch-cut/2372)

**Comment by sdake** [comment]
I see @fpesce already left a similar review.

Cheers
-steve

**Comment by hzxuzhonghu** [comment]
ping @fpesce #14415 already in

**Pull request merged**
