### PR TITLE
Mixer adapter for appoptics and papertrail

### PR DESCRIPTION
**Pull request by girishranganathan**
The feature is a new mixer adapter for sending metrics and access logs collected by istio to Appoptics (https://www.appoptics.com) and Papertrail (https://papertrailapp.com) respectively.

### CODE REVIEW

**Comment by girishranganathan** [comment]
I signed it!

**Comment by girishranganathan** [comment]
I signed it!

**Comment by girishranganathan** [comment]
These are the lint errors in CircleCI:

mixer/template/doc.go:45::error: line is 216 characters (lll)
mixer/template/sample/doc.go:30::error: line is 230 characters (lll)
mixer/test/spyAdapter/template/doc.go:16::error: line is 248 characters (lll)
pkg/log/options_test.go:1::error: file is not gofmted with -s (gofmt)
pkg/log/options_test.go:1::error: file is not goimported (goimports)


None of these are my files. I am help fix them as well. Please confirm.

**Comment by girishranganathan** [comment]
I don't really understand the e2e tests. It would be nice if someone can help explain it to me.

**Comment by mandarjog** [comment]
We are fixing the linter issues, don’t worry about that for now, just rebase once those fixes are made.

**Pull request closed without merging**
