### PR TITLE
Adjust Wasm VMs charts order and Add release note

### PR DESCRIPTION
**Pull request by carolynhu**
Please provide a description for what this PR is for.

Follow up PR for this https://github.com/istio/istio/pull/28209

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by mandarjog** [comment]
Raintank ?

Also was a release note attached to the previous one ?

**Comment by carolynhu** [comment]
https://snapshot.raintank.io/dashboard/snapshot/GpJF3QPW3WXVl6k2gkZoMh6AaYlpyLXB

**Comment by carolynhu** [comment]
> Raintank ?
> 
> Also was a release note attached to the previous one ?

here it is: https://snapshot.raintank.io/dashboard/snapshot/GpJF3QPW3WXVl6k2gkZoMh6AaYlpyLXB

We did not add a release notes for this (in last PR), do we need a release notes? If yes, we can add it in this PR.

**Comment by mandarjog** [comment]
Yes, please add a release note.

**Review by mandarjog — APPROVED** [review]
Lgtm

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
It seems like adding a dashboard also needs to be reflected in the release-builder repo. Adding this dashboard in https://github.com/istio/release-builder/pull/454

**Pull request merged**
