### PR TITLE
Add auth context to readme

### PR DESCRIPTION
**Pull request by wattli**
**What this PR does / why we need it**:

Add auth context / it is not there

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by wattli** [comment]
@ldemailly , can you help to merge? Thanks.

**Comment by ldemailly** [comment]
the bot will

**Comment by ldemailly** [comment]
you have to keep the 3 backticks like a code block


```
  ```release-note
  NONE
```

**Comment by yutongz** [comment]
The pr is good to good, the robot is queued this pr: http://35.197.104.17:8080/#/queue. Will verify it after https://github.com/istio/istio/pull/1001

**Pull request merged**
