### PR TITLE
[release-1.5] update go-control-plane and proxy sha

### PR DESCRIPTION
**Pull request by yangminzhu**
The latest go-control-plane and proxy for release 1.5 is needed for fixing the path field in the authZ policy for 1.5: https://github.com/istio/istio/pull/21132

### CODE REVIEW

**Comment by yangminzhu** [comment]
The test `TestStatsFilter` and `TestTcpMetric` failed with the new proxy sha in release 1.5:
```
--- FAIL: TestStatsFilter (146.43s)
    util.go:138: Sending traffic
    util_prometheus.go:25: query prometheus with: istio_requests_total{reporter="source",destination_service_name="reviews",source_workload="productpage-v1",destination_workload_namespace="istio-bookinfo-1-75589",source_workload_namespace="istio-bookinfo-1-75589",request_protocol="http",response_code="200",destination_app="reviews",destination_service="reviews.istio-bookinfo-1-75589.svc.cluster.local",destination_service_namespace="istio-bookinfo-1-75589",destination_version="v1",source_app="productpage",source_version="v1",}
    util_prometheus.go:32: value: 
    stats_filter_test.go:77: prometheus values for istio_requests_total: 
    util.go:138: Sending traffic
    util_prometheus.go:25: query prometheus with: istio_requests_total{reporter="source",destination_service_name="reviews",source_workload="productpage-v1",destination_workload_namespace="istio-bookinfo-1-75589",source_workload_namespace="istio-bookinfo-1-75589",request_protocol="http",response_code="200",destination_app="reviews",destination_service="reviews.istio-bookinfo-1-75589.svc.cluster.local",destination_service_namespace="istio-bookinfo-1-75589",destination_version="v1",source_app="productpage",source_version="v1",}
    util_prometheus.go:32: value: 
    stats_filter_test.go:77: prometheus values for istio_requests_total: 
    stats_filter_test.go:73: retry.UntilSuccessOrFail: timeout while waiting (last error: could not find metric value: value not found for map[string]string(nil))
```

@bianpengyuan @mandarjog  Could you take a look? Thanks.

**Comment by bianpengyuan** [comment]
You will need to update bootstrap config stats config (https://github.com/istio/istio/blob/release-1.5/tools/packaging/common/envoy_bootstrap_v2.json#L133) 
like https://github.com/istio/proxy/commit/dc79048b1b91116040bfaeec8967cf38a1e4abf3#diff-433c4773bcfcd8bf4579fd17adc9b11b. Specifically you will need to remove the two permission labels I think.

**Comment by yangminzhu** [comment]
> You will need to update bootstrap config stats config (https://github.com/istio/istio/blob/release-1.5/tools/packaging/common/envoy_bootstrap_v2.json#L133)
> like [istio/proxy@dc79048#diff-433c4773bcfcd8bf4579fd17adc9b11b](https://github.com/istio/proxy/commit/dc79048b1b91116040bfaeec8967cf38a1e4abf3#diff-433c4773bcfcd8bf4579fd17adc9b11b). Specifically you will need to remove the two permission labels I think.

@bianpengyuan I removed the two "permissive" attribute in [this commit](https://github.com/istio/istio/pull/21131/commits/da8a150a4fd155858f3e3d26e8c5f360c0fc98ec) but it doesn't fix the test. 

Looking at the error message again, it seems related to the "istio_requests_total" attribute, could you suggest how to fix it? I have no idea why it failed with the new proxy. cc @kyessenov @douglas-reid

**Pull request closed without merging**
