### PR TITLE
increase the maxAttempts for checking namespace deleted.

### LINKED ISSUE #2157: e2e-cluster_wide-auth flake on cleaning up?
I see 2 same errors on `e2e-cluster_wide-auth` out of 9 runs. The real cause is, timeout happened on removing `istio-system` namespace at the end for mixer's e2e test, and the next test case tries to make instances on the terminating namespaces, which caused unexpected behaviors (see https://k8s-gubernator.appspot.com/build/istio-prow/e2e-cluster_wide-auth/217/ for example).

If this keeps happening at this rate, maybe we should consider increasing the timeout of the cleanup.

### PR DESCRIPTION
**Pull request by jmuk**
**What this PR does / why we need it**:

I see multiple times for failure of namespace deletion even with this number of attempts, for mixer e2e. This causes a failure of another test for cluster-wide tests, since multiple tests are sharing the same 'istio-system' namespace.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2157

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by yutongz** [comment]
I think you need to push another commit to trigger tests in circle-CI :)

**Comment by jmuk** [comment]
@yutongz PTAL

**Pull request merged**
