### PR TITLE
Removing Galley pod and node datasets from tests

### LINKED ISSUE #10947: Galley integration test failures
Error log
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10888/istio-integ-local-tests/3370

Note that due to bugs in the test job, tests were NOT run, so it is not easy to figure out if any PR broke this or if the test really ran correctly before.

https://github.com/istio/istio/pull/10888 has uncovered this.

### PR DESCRIPTION
**Pull request by nmittler**
Fixes #10947

### CODE REVIEW

**Comment by hklai** [comment]
/hold

@nmittler  Please wait and rebase after https://github.com/istio/istio/pull/10888 is merged so that CI actually kick off these tests.

Also, please add "galley/pkg/testing/testdata=100" to https://github.com/istio/istio/blob/master/codecov.threshold to address the coedcov problem.

**Comment by hklai** [comment]
@nmittler Yup this fixes the galley tests as shown by https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10953/istio-integ-local-tests/3403

Thanks!

Please still rebase to take the latest codecov.threshold which should fix your codecov job failure.

**Comment by nmittler** [comment]
@hklai done

**Comment by hklai** [comment]
The galley tests are failing in k8s tests

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10953/istio-integ-k8s-tests/1698

**Comment by incfly** [comment]
I add `TestAuthnPermissive` as integration2 native environment. So right now seems some tests are failing, and we can't turn on those tests as required. How can I ensure my tests are required then? Can I skip the failing test for now and change test suite to required?

**Comment by hklai** [comment]
Nupur is fixing the remaining failing mixer tests. Once the job is
restored, I will make it required again.

**Comment by incfly** [comment]
Great, thanks!

**Pull request merged**
