### PR TITLE
Add mention of our team drive.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by ldemailly** [comment]
Why do we have the drive link here when an access request is needed to read it ?
previous version (share the link to the mailing list) seems better ?

screen shot 2017-06-08 at 2 54 58 pm

edit: didn't see the pr earlier

**Comment by geeknoid** [comment]
So what's the issue?

Unfortunately, Team Drive doesn't have any notion of "World access", otherwise I would've made it so you don't need to request read access. As it is, we will grant read access to anyone that asks, and only selectively grant write access.

**Comment by ldemailly** [comment]
@geeknoid 

can we checkin in istio/docs or turn into web site pages the past design docs (for world readability)

and collaborate on 1 by 1 basis for future/current designs (links to the dev mailing list) ?

that seems more scalable / correct rather than manually adding a bunch of people to a huge shared drive

also I think we're likely to make mistakes giving write access (for instance I got write access using my personal email - could have been anyone)

**Comment by geeknoid** [comment]
We can certainly consider these changes.

But for now, we've settled on Google Docs for design documents and having people be able to read those docs. The idea solution would be to project a view of the Team Drive into istio.io (like we do internally in Google at go/istio). I don't think there's a way to do this on public sites at this point.

We didn't have a clear policy on what access to grant to incoming requests, so some people got write access that shouldn't have. These have been cleaned up now. Moving forward, requests will always get read access, and write access will be granted only when the need is proven.

**Pull request merged**
