### PR TITLE
add support for proxying 100 continue headers

### PR DESCRIPTION
**Pull request by ramaraochavali**
Fixes https://github.com/istio/istio/issues/21382 and https://github.com/istio/istio/issues/36278

Added a feature flag that can be removed later.

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
AFAIK, it does not have any negative impacts on any routes.  https://github.com/istio/istio/issues/21382#issuecomment-669525370 also confirms the same

**Comment by bleggett** [comment]
If we don't think it will break anything and should be the new default, but it is a behavioral change, do we want this to be affected by compatibility version?

**Comment by ramaraochavali** [comment]
> If we don't think it will break anything and should be the new default, but it is a behavioral change, do we want this to be affected by compatibility version?

It should be compatible with all versions and I do not think this change should impact any one negatively. That is why I defaulted it to true and if there are any cases that need it to be false for some reason, they can turn it off. My plan is to remove this env var after couple of releases.

Other option is an API in VS but that IMO that is an overkill here.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by nmische** [comment]
@ramaraochavali: We found this to be a breaking change in a recent upgrade from 1.22 -> 1.23. We use AWS ALBs in front of Istio Ingress. ALBs are http2 on the downstream side (client facing) but http1.1 on the upstream side (Istio facing). (See HTTP connections [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html#:~:text=and%20HTTPS%20listeners-,HTTP%20connections,-Classic%20Load%20Balancers).) With this setup we found that some service will return 100-continue header for http1.1 requests, and now that this is being proxied by Istio, the 100-continue header makes it back to the http2 client, causing errors.

Given the above, I think we would need the ability to disable 100-continue proxying to support similar setups.

**Comment by ramaraochavali** [comment]
What errors are you seeing? Also you can disable it via flag right?

**Comment by nmische** [comment]
In one case the upstream is a GraphQL server. For http1.1 requests this server implementation will respond with a 100-continue header, but for http2 requests it will not. We saw the following error with `curl` when making an http2 request to this server through our ingress (which downgrades http2 to http1.1 at the ALB):

```curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)```

We were able to disable 100-continue proxying with the flag and the errors went away. 

Given this, I think we would need the ability to disable 100-continue proxying as long as the connection is being "downgraded" at the ALB.

**Comment by nmische** [comment]
And to clarify, I think proxying this header is probably the correct default behavior for Istio, but I want to ensure that we continue to have the ability to override as needed. I brought this up because I saw you mention:

> My plan is to remove this env var after couple of releases.

**Comment by ramaraochavali** [comment]
Ok. Thank you.

**Comment by leosarra** [comment]
@ramaraochavali I see that the flag has run its course in the compatibility charts.
Do you think it makes sense to keep it as an ENV flag, or should we opt for a more permanent place for it (given that it seems there’s still a need to keep it toggleable)?

**Comment by ramaraochavali** [comment]
ENV flag seems fine

**Pull request merged**
