### PR TITLE
Remove mixer client stress test.

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by qiwzhang** [comment]
https://github.com/istio/istio/issues/4281

**Comment by ldemailly** [comment]
is this test going to come back ? or moved to a different suite ? if it was testing something like it appeared to be, it's a bit sad it's just deleted ?

**Comment by qiwzhang** [comment]
It was not very useful stress test.  It just launches 10 threads with a lot of requests.  At the end, count number of failed requests.  So far, it did not catch anything.  Sometime it introduced false alarm due to late started Envoy or Mixer.

**Comment by ldemailly** [comment]
ok I guess it'll get covered by perf tests then! thanks

**Pull request merged**
