### PR TITLE
TestTraffic for ambient

### PR DESCRIPTION
**Pull request by stevenctl**
This tests "ambient L7" and adds a fair bit of coverage. 
While a lot of things are skipped in this mode, I still think it's super valuable to know that those things need looking at.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Comment by jacob-delgado** [comment]
Holding for https://github.com/cncf/toc/pull/1000

**Comment by stevenctl** [comment]
Go ahead an leave the hold there. I'd like @howardjohn  to take a look. 

* The flake was on the boookinfo test, seems unrelated. 
* I don't think it adds much time. The most recent run took 16 mins, but I see a handful of runs on PRs that don't affect this suite to take that long. It's completed with the full set of new tests in as little as 8 mins.

**Comment by howardjohn** [comment]
Why does this relate to the CNCF thing? that is only blocking eBPF, not ambient

**Comment by linsun** [comment]
Agreed, this should not be related to CNCF, unless there is ebpf based stuff.

**Pull request merged**
