### PR TITLE
Support short names for Istio resources

### LINKED ISSUE #9729: Proposal: Support short names for Istio resources
**Describe the feature request**

There are many resources defined in Istio such as VirtualService, ServiceEntry, DestinationRule and so on. 
They don't have short names, so it is not convenient to operate them through kubectl.

**Describe alternatives you've considered**

I think it is necessary to support short names for frequently used resources.

**Additional context**

xref: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-dev/_OX4WW_KzM4/c7mR8ixpCwAJ

### PR DESCRIPTION
**Pull request by supereagle**
Fix #9729

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
/ok-to-test

LGTM

**Comment by ozevren** [comment]
We should add short names for all of the Istio resources as well (except for old style handler CRDs) and ensure that there is no conflict there.

Once that is done, we can send it for a broader code-review for WG leads.

**Comment by supereagle** [comment]
@ozevren  I have add short names for all Pilot CRDs. 

Mix CRDs' short names are not added as they are not always used, and the number of these CRDs is a little large. Is it OK?

**Comment by ozevren** [comment]
Can you please add them for standard Mixer types?
rule, instance, handler, template, adapter,

**Comment by supereagle** [comment]
@ozevren   Short names are convenient for long resource names, the names of these standard Mixer types are short and easy enough. So I think it it not necessary for them, otherwise users have to remember their short names.

If you think it is necessary, I'm ok to add them.

**Comment by ayj** [comment]
Note that Galley doesn't register CRDs. Adding short names to the metadata file won't have an affect on the CRD in the cluster. Of course, that might change in the future if we decide to use Galley to create CRDs.

**Comment by supereagle** [comment]
@ayj   I have added short names in [crds.yaml](https://github.com/istio/istio/pull/9731/files#diff-30d13d1e7cdc6d8c82ff518b58f0849a), so they can work on the CRDs. If these CRDs already exists in k8s, can apply the crds.yaml to take effect.

**Comment by ozevren** [comment]
@geeknoid any thoughts on the lack of short names for Mixer CRDs? Are you ok with that?

**Comment by ozevren** [comment]
Sent the PR for a broader review for WG leads & TOC. After review I can place comments or lgtm.

**Comment by geeknoid** [comment]
I'd rather have short names for the canonical Mixer resource types too.

mr - rules
mh - handler
mi - instance
mt - template
ma - adapter

Conveniently, the long names all start with different letters.

**Comment by ozevren** [comment]
Would it make more sense to have a different start letter, to represent the
domain, rather than the component? (e.g. policy)

pr - rules (policy rule)
ph - handler (policy handler)
pi - instance (policy instance)
pt - template (policy template)
pa - adapter (policy adapter)

**Comment by ayj** [comment]
CRD short names are globally scoped and may conflict with other k8s resources -- CRD or built-in types (see below). Not all resources need short names if the full name is short itself, e.g. rule. 

We should also consider frequency of use common initialisms and idioms, e.g. customresourcedefinition is frequently referred to as `crd` in docs vs. no one talks about `pr` with a dependent `ph` and `pi`.

```bash
  * certificatesigningrequests (aka 'csr')  
  * clusterrolebindings  
  * clusterroles  
  * componentstatuses (aka 'cs')  
  * configmaps (aka 'cm')  
  * controllerrevisions  
  * cronjobs  
  * customresourcedefinition (aka 'crd')  
  * daemonsets (aka 'ds')  
  * deployments (aka 'deploy')  
  * endpoints (aka 'ep')  
  * events (aka 'ev')  
  * horizontalpodautoscalers (aka 'hpa')  
  * ingresses (aka 'ing')  
  * jobs  
  * limitranges (aka 'limits')  
  * namespaces (aka 'ns')  
  * networkpolicies (aka 'netpol')  
  * nodes (aka 'no')  
  * persistentvolumeclaims (aka 'pvc')  
  * persistentvolumes (aka 'pv')  
  * poddisruptionbudgets (aka 'pdb')  
  * podpreset  
  * pods (aka 'po')  
  * podsecuritypolicies (aka 'psp')  
  * podtemplates  
  * replicasets (aka 'rs')  
  * replicationcontrollers (aka 'rc')  
  * resourcequotas (aka 'quota')  
  * rolebindings  
  * roles  
  * secrets  
  * serviceaccounts (aka 'sa')  
  * services (aka 'svc')  
  * statefulsets (aka 'sts')  
  * storageclasses (aka 'sc')
```

**Comment by kyessenov** [comment]
Mixer rules and etc. are used for both policy and telemetry. I think it's
fair to call them mr, mi, etc. instead of pr, pi.

**Comment by geeknoid** [comment]
All right, Jason's arguments convinced me. Mixer names are short enough as it is, so let's leave things as is.

**Comment by supereagle** [comment]
I agree with Jason.   @ozevren  Please help to review this PR.

**Comment by ozevren** [comment]
I've sent the PR for WG lead/TOC review. Please hold until we have enough time to garner feedback. If there is no feedback by Friday, I'll LGTM it.

**Comment by supereagle** [comment]
@mandarjog PTAL, thx

/assign @mandarjog

**Comment by supereagle** [comment]
@mandarjog Please help to review the change for installation.

**Comment by supereagle** [comment]
Have replaced html template with text template for simpleness. 

/cc @ozevren @mandarjog

**Comment by supereagle** [comment]
@ozevren @mandarjog   PTAL

**Comment by ozevren** [comment]
Have you checked whether these shortnames conflict with existing ones? We had a similar issue reported recently with the full names.

Also, you don't need to update the Galley metadata model. Galley does not make use of this at this point. Updating CRD yaml files should be enough.

**Comment by ayj** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/59812

**Comment by sdake** [comment]
/hold

See https://github.com/istio/istio/pull/10296#issuecomment-444871336

**Comment by supereagle** [comment]
Only need #10296 currently, temporarily close this PR.

/close

**Pull request closed without merging**
