### PR TITLE
Remove unused fields from operator API

### PR DESCRIPTION
**Pull request by nrfox**
**Please provide a description of this PR:**

Removes both `GlobalConfig.ConfigRootNamespace` and `GlobalConfig.DefaultConfigVisibilitySettings` from the operator API. Both are unused in the manifests.

Part of: https://github.com/istio/istio/issues/51987

### CODE REVIEW

**Comment by MorrisLaw** [comment]
@whitneygriffith @howardjohn ; would removing these fields require some type of deprecation process?

**Comment by jacob-delgado** [comment]
The gateways charts are considered deprecated at this point and have been for over a year. Users should be pushed to use the gateway chart.

**Comment by dgn** [comment]
> @whitneygriffith @howardjohn ; would removing these fields require some type of deprecation process?

Usually they would. in this case however they have long been removed from the charts and what @nrfox is removing are only some references to those former fields

**Review by dgn — APPROVED** [review]

**Comment by whitneygriffith** [comment]
> > @whitneygriffith @howardjohn ; would removing these fields require some type of deprecation process?
> Usually they would. in this case however they have long been removed from the charts and what @nrfox is removing are only some references to (and default values for) those former fields

I agree the fields addressed in this PR are only references and wouldn't typically need a deprecation process. 

However, I am confused on the deprecation of the Operator API itself. Did we have any official announcements or documentation around the deprecation of the Operator API and guidance to use Gateway Charts instead? And is the Operator API related to the [In Cluster Operator](https://github.com/istio/enhancements/issues/166) that we are currently in the process of deprecating?

**Comment by dgn** [comment]
> > > @whitneygriffith @howardjohn ; would removing these fields require some type of deprecation process?
> > > Usually they would. in this case however they have long been removed from the charts and what @nrfox is removing are only some references to (and default values for) those former fields
> 
> I agree the fields addressed in this PR are only references and wouldn't typically need a deprecation process.
> 
> However, I am confused on the deprecation of the Operator API itself. Did we have any official announcements or documentation around the deprecation of the Operator API and guidance to use Gateway Charts instead? And is the Operator API related to the [In Cluster Operator](https://github.com/istio/enhancements/issues/166) that we are currently in the process of deprecating?

This "operator API" here is what's used by istioctl (and formerly the operator) to do type-checking of inputs. The user-visible result of this PR is that the user will see an error when trying to use these fields in istioctl, as they don't exist, whereas before they would have simply been ignored.

This is part of a larger cleanup (see https://github.com/istio/istio/issues/51987) and there will be a release note covering all the removed fields.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
