### PR TITLE
remove redundant whitespace

### PR DESCRIPTION
**Pull request by irisdingbj**
https://github.com/istio/istio/issues/7383

### CODE REVIEW

**Comment by ymesika** [comment]
Thanks.

/ok-to-test

**Comment by ymesika** [comment]
@irisdingbj Can you please choose `release-1.0` as the target?
I believe it's important fix for the release.

**Comment by irisdingbj** [comment]
@ymesika PR for release-1.0 is https://github.com/istio/istio/pull/7385

**Comment by gyliu513** [comment]
master is frozen and all the PRs should goto 1.0 branch.

**Pull request closed without merging**
