### PR TITLE
use only ipv4 for pilot and zipkin

### PR DESCRIPTION
**Pull request by rshriram**
Signed-off-by: Shriram Rajagopalan <rshriram@gmail.com>

### CODE REVIEW

**Comment by Stono** [comment]
Cross linking https://github.com/istio/istio/issues/12968

**Comment by linsun** [comment]
/lgtm
if we need to support ipv6, we need to make this configurable.  I double checked we don't have statement in the features list in istio.io for ipv6 today.

**Comment by GregHanson** [comment]
@linsun we explicitly set it to V4 only everywhere else: https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L1001
Otherwise default is AUTO, which tries V6 first and then V4

**Comment by GregHanson** [comment]
should also be address the few clusters in the yaml bootstrap files as well:
```
$ grep -rIin "_DNS" ./pilot/docker/ 
./pilot/docker//envoy_pilot.yaml.tmpl:61:    type: STRICT_DNS
./pilot/docker//envoy_policy.yaml.tmpl:74:    type: STRICT_DNS
```

**Comment by Stono** [comment]
What are the chances of this being squeezed into `1.0.2`?

**Comment by sbezverk** [comment]
@rshriram any chance to make this option as a variable which would be rendered depending on a flag? It is fine if it is defaulted to IPv4 but imho it should be configurable.

**Comment by Stono** [comment]
Can we please do configuration of ipv4+ipv6 as a separate piece of work?  We've already identified that in many other areas of the code, ipv4 is enforced, this just brings it all in line.

I really don't want to bloat out this piece of work into a feature, because it is currently a customer impacting bug

**Comment by sbezverk** [comment]
@Stono sure thing, it will be addressed later.

**Pull request merged**
