### PR TITLE
Make metrics experimental again

### PR DESCRIPTION
**Pull request by esnible**
Some folks felt `istioctl experimental metrics` is not ready to graduate.

If you like this PR remove `do-not-merge` and also cherry-pick for release-1.3.
This should go into master and release-1.3, or neither.

### CODE REVIEW

**Comment by rlenglet** [comment]
Someone please comment `/cherrypick release-1.3`

**Comment by sdake** [comment]
there is doc and release note impact.  Is there going to be a 1.3.0 rebulid?

**Comment by rlenglet** [comment]
> there is doc and release note impact. Is there going to be a 1.3.0 rebulid?

If we want this in 1.3.0, we'll need to rebuild. But we need to rebuild the 1.3.0 official release anyway.

**Comment by sdake** [comment]
@esnible do you know how the istioctl reference documentation is generated?  I am unclear how to regenerate it.

**Comment by rlenglet** [comment]
The `release-1.3` backport will also require changing the release notes?

**Pull request merged**
