### PR TITLE
remove seconds from daily build name

### LINKED ISSUE #4194: daily builds: confusing timestamps (still)
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/

last release dir is 0.7.0-pre20180309-09-15-15/

can we
a) drop the last -15 (assuming this is seconds ?) we aren't going to make more than 1 daily per minute (would be less confusing as 0.7.0-pre20180309-0915 )
b) when I click; https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/0.7.0-pre20180309-09-15-15/
all the timestamps are
09 Mar 2018 10:06:18

yet when I look inside the tar:

-rw-r--r--  0 releng releng      739 Mar  9 01:19 istio-0.7.0-pre20180309-09-15-15/istio.VERSION

what happened between 1:19 and 9:15 ? and what happened between 9:15 and 10:06 ?

Can we please make sure the daily show up as we talked about before 9a PST (ideally at 8a pst)

### PR DESCRIPTION
**Pull request by rkpagadala**
fixes #4194

### CODE REVIEW

**Comment by hklai** [comment]
Shall we add the timezone as well? =)

**Comment by ldemailly** [comment]
nah I understand for the filename using UTC is fairly standard

I just got tripped by gcsweb UI expecting it to be in my timezone

**Comment by ldemailly** [comment]
unless you meant that the code doesn't force the TZ to be UTC ? (does it ? I'm not that familiar with python)

**Pull request merged**
