### PR TITLE
Update zipkin deployment.

### PR DESCRIPTION
**Pull request by morvencao**
Update `zipkin` deployment to include `priorityClassName`, `imagePullSecrets` and `nodeAffinity`.

### CODE REVIEW

**Comment by morvencao** [comment]
@wenchenglu Can we merge this to release-1.1?

**Comment by morvencao** [comment]
Maybe we can fix this in post 1.1.

**Comment by douglas-reid** [comment]
@morvencao should we target this to the istio/installer artifacts instead now?

**Comment by morvencao** [comment]
@douglas-reid Oh, yes, thanks for reminder, i think this has been fixed in new installer , see: https://github.com/istio/installer/pull/132

Closing this.

**Pull request closed without merging**
