### PR TITLE
[ci skip] [pilot] Fix links in init.sh

### PR DESCRIPTION
**Pull request by andraxylia**
Fix links in init.sh

```release-note
NONE
```

### CODE REVIEW

**Comment by andraxylia** [comment]
@kyessenov this script is not supposed to be used anymore, can we remove it completely?

**Comment by mandarjog** [comment]
@andraxylia this script should be removed.
Only top level scripts are / will be used now.

**Comment by mandarjog** [comment]
@andraxylia can you close this PR. There are too many PRs in the queue, and we don't need this fix anymore.

**Comment by ldemailly** [comment]
can this branch be deleted ? (the feature has moved to istio/bin ?)

ps: there is no cost of an open PR so there should be no need to close a PR that isn't being modified

**Comment by andraxylia** [comment]
Please hold off from deleting, the PR has not been merged and it is not clear if @kyessenov still needs init.sh.

**Pull request closed without merging**
