### PR TITLE
Support ip:port format configSource

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Without this pr

specify the below configSource will fail pilot.

```
   – address: istio-galley.istio-system.svc:9901

   – address: 9.119.56.229:9902
```

### CODE REVIEW

**Comment by irisdingbj** [comment]
Thanks for fixing this. With this fix we can include external MCP server with pilot.

**Comment by irisdingbj** [comment]
@linsun This fix problems in istio 1.1 when we want to integrate external mcp servers. can we get this PR in 1.1.x?  The fix has already been merged in master branch.

**Comment by howardjohn** [comment]
@hzxuzhonghu @irisdingbj can we move this to master so it get can into 1.2?

**Comment by hzxuzhonghu** [comment]
@howardjohn It is already in 1.2

**Comment by duderino** [comment]
Given the proximity of 1.2 I'd like to keep this out of 1.1.  If the issue becomes severe for a user, please let me know and I'll reconsider

**Pull request closed without merging**
