### PR TITLE
Pilot debug/authenticationz API improvements 

### PR DESCRIPTION
**Pull request by GregHanson**
Distinguish difference between no rule defined and auto mtls enabled for pilot debug api.  These changes are just for the pilot debug API, separate PR will handle the istioctl interpretation of the output. 
related issue: https://github.com/istio/istio/issues/18988

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by GregHanson** [comment]
How the output looks in istioctl with these changes:

No DestinationRule and `--set values.global.mtls.enabled=false     --set values.global.mtls.auto=false`

```
istioctl authn tls-check productpage-v1-85b9bf9cd7-52p95 reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER         CLIENT     AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     OK         PERMISSIVE     None       /default         None
```
With DestinationRule
```
$ istioctl authn tls-check productpage-v1-85b9bf9cd7-52p95 reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER         CLIENT           AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     OK         PERMISSIVE     ISTIO_MUTUAL     /default         default/reviews
```

No DestinationRule and `--set values.global.mtls.enabled=true     --set values.global.mtls.auto=true`
```
$ istioctl authn tls-check productpage-v1-85b9bf9cd7-sng4d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     AUTO       STRICT     -          /default         -
```
With DestinationRule
```
$ istioctl authn tls-check productpage-v1-85b9bf9cd7-sng4d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER     CLIENT           AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     OK         STRICT     ISTIO_MUTUAL     /default         default/reviews
```

No DestinationRule and `--set values.global.mtls.enabled=false     --set values.global.mtls.auto=true`
```
$ istioctl authn tls-check productpage-v1-85b9bf9cd7-sng4d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER         CLIENT     AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     AUTO       PERMISSIVE     -          /default         -
```
With DestinationRule
```
$ istioctl authn tls-check productpage-v1-85b9bf9cd7-sng4d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER         CLIENT           AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     OK         PERMISSIVE     ISTIO_MUTUAL     /default         default/reviews
```

**Comment by GregHanson** [comment]
Changes existing logic around `"-"` currently returned by debug API.  `"-"` is now returned when autoMTLS=true and no rules exist.  New keyword `None` is returned when no rules exist and behavior is NOT modified by autoMTLS.  This change does NOT break existing `istioctl` commands AFAIK

**Comment by GregHanson** [comment]
@diemtvu do you mean the `authn tls-check` command is getting removed?  These changes can also be used to improve the `istioctl describe` command as well.  See https://github.com/istio/istio/issues/18988

**Comment by diemtvu** [comment]
I see. Thanks.

/lgtm

**Comment by linsun** [comment]
@diemtvu why is this tool being deprecated?  This is one of the most useful tools from istioctl imho.

**Comment by diemtvu** [comment]
Good to know :). However, it doesn't work in the same way with new mTLS API
( workload selector). Also, with auto mTLS, it may not have the same value.

We will try to provide the tool in different way, and possible to merge
with other analyze tools.

Thanks.

**Comment by esnible** [comment]
Before I approve this, does "None" always mean unspecified?

Are these the the possible client side output for /debug/authenticationz and their meanings?

"DISABLE" (no TLS)
"SIMPLE" (?)
"MUTUAL" (mTLS with other certificate?)
"ISTIO_MUTUAL" (Istio mTLS)
"-" (auto-mTLS)
"None" (neither a specific policy for a service nor a generic policy for *, so we do the default, which is no mTLS?)

**Comment by linsun** [comment]
@howardjohn can you help approve this?

**Pull request merged**
