### PR TITLE
authz: clean namespaceMatch

### PR DESCRIPTION
**Pull request by dvrkps**
[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by esnible — COMMENTED** [review]
Is this code-cleanup, with no issue or change in behavior?

**Comment by dvrkps** [comment]
Hi @esnible. No issues and behavior changes there. Basic code cleanup.

**Review by esnible — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by dvrkps** [comment]
@howardjohn can you check release-notes_istio failing test. thx.

**Pull request merged**
