### PR TITLE
Remove cds cache completely 

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is a cleanup after #13737

### CODE REVIEW

**Comment by howardjohn** [comment]
Can you submit to master though? https://discuss.istio.io/t/1-2-release-branch-cut/2372

**Comment by hzxuzhonghu** [comment]
ok, i missed many important notification

**Comment by fpesce** [comment]
> Can you submit to master though? https://discuss.istio.io/t/1-2-release-branch-cut/2372

Thanks for reminding that @howardjohn 
Once merged into master, just link the PR here @hzxuzhonghu and assign it to me.

**Comment by hzxuzhonghu** [comment]
ping @fpesce cherry-pick #14416

**Pull request merged**
