### PR TITLE
Change update_deps.sh to use docker (default) or crane

### PR DESCRIPTION
**Pull request by ericvn**
**Please provide a description of this PR:**

This change is to better support developers on MacOS on silicon devices.

On Apple devices, commands like `sed` and `grep` behave differently. Some of the Istio scripts, like update_deps.sh, use these commands and fail when run on the MacOS. One can install software to make the commands work as they do on Linux. Another option is to simply to do `make shell`  to get a Linux command line. From this Linux command line, the scripts can be run.

One issue right now is that the `crane` command segfaults when run in the `make shell` container. An issue with qemu? 

This PR reverts a change that solely uses `crane` in `update_deps.sh`, instead allowing the developer to export `ISTIO_DOCKER_BUILDER=crane` to use `crane`. I made `docker` the default to mimic the behavior in `docker-builder`.

### CODE REVIEW

**Comment by ericvn** [comment]
Adding a DNM to allow @GregHanson to test this on his Apple Silicon computer.

**Comment by howardjohn** [comment]
This feels a bit wrong to me... do we expect arm machines to be able to run the build container successfully? I cannot imagine it works (or works well, at least) in many other places.

At the very least we should continue to use the proper way (crane) instead of hacking around it just for ARM.

Maybe its time to get multiarch build-tools

**Comment by ericvn** [comment]
With qemu, there is a possibility of running intel/amd containers on arm machines. This works for Docker Desktop and podman. While I agree this isn't ideal and we should have arm versions of the build-tools and build arm images, that will be a longer process.

**Comment by ericvn** [comment]
I'd like to leave this one set a little longer.

**Comment by ericvn** [comment]
Closing this PR for now. Will reopen if the users are still seeing issues with crane on MacOS Silicon devices.

**Pull request closed without merging**
