### PR TITLE
Fix the deployment error of sleep-vault.yaml

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is to fix the issue: https://github.com/istio/istio/issues/16604

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
@lei-tang It looks like this needs to be backported. Please comment `/cherrypick release-1.3`.

**Comment by lei-tang** [comment]
@rlenglet Done: I have commented "/cherrypick release-1.3".

**Comment by howardjohn** [comment]
ping @istio/wg-docs-maintainers this is a blocker

**Pull request merged**
