### PR TITLE
istio-cni - privilege container

### PR DESCRIPTION
**Pull request by ajohnstone**
istio-cni - add privilege to allow for selinux with istio-cni.

The istio-cni provider will fail to write to `/host/etc/cni/net.d/10-aws.conflist.tmp: Permission denied`.

```
k -n kube-system logs istio-cni-node-hlzzd -c install-cni
/host/opt/cni/bin is non-writable, skipping
/host/secondary-bin-dir is non-writable, skipping
/install-cni.sh: line 185: /host/etc/cni/net.d/istio-cni.conf.tmp: Permission denied
Cleaning up and exiting.
Removing istio-cni config from CNI chain config in /host/etc/cni/net.d/10-aws.conflist
/install-cni.sh: line 110: /host/etc/cni/net.d/10-aws.conflist.tmp: Permission denied

# ---

k -n kube-system logs istio-cni-node-hlzzd -c repair-cni
{"level":"info","time":"2021-04-21T15:26:09.172568Z","msg":"Controller Option: Running as a Daemon."}
{"level":"info","time":"2021-04-21T15:26:09.172613Z","msg":"Controller Option: Deleting broken pods. Pod Labeling deactivated."}
{"level":"info","time":"2021-04-21T15:26:09.172620Z","msg":"Filter option: Only managing pods with an annotation with key sidecar.istio.io/status"}
{"level":"info","time":"2021-04-21T15:26:09.172625Z","msg":"Filter option: Only managing pods with field selector spec.nodeName=ip-10-0-49-241.eu-west-1.compute.internal,"}
{"level":"info","time":"2021-04-21T15:26:09.172629Z","msg":"Filter option: Only managing pods where init container is named istio-validation"}
{"level":"info","time":"2021-04-21T15:26:09.172633Z","msg":"Filter option: Only managing pods where init container exit status is 126"}
```

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Can you add some more information about why this is needed?

**Comment by ajohnstone** [comment]
@howardjohn thanks updated the description with the details.

```
k -n kube-system logs istio-cni-node-hlzzd -c install-cni
/host/opt/cni/bin is non-writable, skipping
/host/secondary-bin-dir is non-writable, skipping
/install-cni.sh: line 185: /host/etc/cni/net.d/istio-cni.conf.tmp: Permission denied
Cleaning up and exiting.
Removing istio-cni config from CNI chain config in /host/etc/cni/net.d/10-aws.conflist
/install-cni.sh: line 110: /host/etc/cni/net.d/10-aws.conflist.tmp: Permission denied
```

**Review by bianpengyuan — COMMENTED** [review]
The following istioctl k8s overlay will also work:
```
   components:
    cni:
      namespace: kube-system
      enabled: true
      k8s:
        overlays:
        - kind: DaemonSet
          name: istio-cni-node
          patches:
            - path: spec.securityContext.privileged
              value: true
```

Could you specify that instead? I think in general we want to avoid adding any new value option now..

**Comment by zioproto** [comment]
@bianpengyuan would it make sense to integrate that overlay here: https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/istio/options/cni-gcp.yaml

??

I also wanted to ask, is there any case where it would make sense to configure in the values `privileged: false` in this proposed patch? 

I would rather suggest to patch the `DaemonSet` with a default value for `securityContext` that does not need a new value option.

The `securityContext` we had in the `istio-init` container when not using istio-cni was like this:

```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
```

Would this be enough to write those files that fail now with permissions errors ?

**Comment by ajohnstone** [comment]
@bianpengyuan Unfortunately using istio asm 1.6. That works great in 1.9 and will be upgrading to soon. Wasn't aware of overlays in istio :)

@zioproto 
To get it to work with selinux need to modify the securityOptions.
1. Make privileged by default without it being an option
2. Can instruct users in docs to patch as per @bianpengyuan advice, no change.
3. Unsure how https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/istio/options/cni-gcp.yaml or where this fits into istio asm?

I solely made an option if people needed to disable, let me know either way and happy to update.

**Comment by bianpengyuan** [comment]
Since it works within most environment as unprivileged container, I would prefer to keep CNI default configuration as is, treat SELinux as a special case, and document how to run CNI on it with overlays configuration (we are working on CNI beta graduation at Istio 1.11 release and one of the major tasks is better document).

**Comment by howardjohn** [comment]
> Since it works within most environment as unprivileged container, I would prefer to keep CNI default configuration as is, treat SELinux as a special case, and document how to run CNI on it with overlays configuration (we are working on CNI beta graduation at Istio 1.11 release and one of the major tasks is better document).

I just wanted to clarify:
* SELinux requires privileged
* Everything else does not

is that accurate? If so, +1 to what you suggested

**Comment by bianpengyuan** [comment]
> > Since it works within most environment as unprivileged container, I would prefer to keep CNI default configuration as is, treat SELinux as a special case, and document how to run CNI on it with overlays configuration (we are working on CNI beta graduation at Istio 1.11 release and one of the major tasks is better document).
> 
> I just wanted to clarify:
> 
> * SELinux requires privileged
> * Everything else does not
> 
> is that accurate? If so, +1 to what you suggested

Yeah that is what I am thinking, since so far people only request for this when running on SELinux. I can do a bit more research on this but at least for now I don't think this worth a value option.

**Comment by ajohnstone** [comment]
The following patch resolves the issue with a overlay working in istio 1.6 and greater.

```
  components:
    cni:
      enabled: true
      namespace: kube-system
      k8s:
        overlays:
        - kind: DaemonSet
          name: istio-cni-node
          patches:
            - path: spec.template.spec.containers.[name:install-cni].securityContext
              value: {"privileged": true}
```

**Pull request closed without merging**
