### PR TITLE
No need to cache when the token is equal to the cached one

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

This may occur when multi goroutines building same xds (like clusterXXX) for different proxy.

1. all go routines get() returns nil
2. one goroutine build its own and add().
3. another goroutinebuild its own and add()

the above two tokens are the same, so we can break fast instead of updating indexes

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@howardjohn @ramaraochavali Is there any caveat

**Comment by ramaraochavali** [comment]
I have not looked at it in detail but test failure seems legit. @howardjohn may know it already

**Comment by hzxuzhonghu** [comment]
This could reduce Lock conflict in some degree, the lock conflict reported by @yingzhuivy

**Comment by hzxuzhonghu** [comment]
@howardjohn

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
