### PR TITLE
Revert "add PROXY_REPO_SHA removing overloaded meaning of PROXY_TAG"

### PR DESCRIPTION
**Pull request by sebastienvas**
Reverts istio/istio#4158

### CODE REVIEW

**Comment by ldemailly** [comment]
why? what is broken/the problem?

**Comment by sebastienvas** [comment]
I0310 07:22:52.161] error when retrieving current configuration of:
I0310 07:22:52.161] &{0xc420ad1200 0xc420221420   /home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml 0xc420f900f8 0xc420f900f8  false}
I0310 07:22:52.161] from server for: "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": resource name may not be empty
I0310 07:22:52.161] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-pilot-admin-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.161] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-sidecar-injector-admin-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.162] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-ca-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.162] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-ingress-admin-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.162] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-sidecar-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.162] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-mixer-admin-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.163] Error from server (Invalid): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-mixer-validator-admin-role-binding-" is invalid: subjects[0].namespace: Required value
I0310 07:22:52.163] Error from server (NotFound): error when creating "/home/bootstrap/go/src/istio.io/istio/_artifacts/simple-auth-test-3c8cd21a6a0a4b08ab98/yaml/istio-one-namespace-auth.yaml": namespaces "simple-auth-test-

**Comment by sebastienvas** [comment]
namespace is not set the generated yaml file

**Comment by sebastienvas** [comment]
/hold 
I want to make sure this is the right PR

**Comment by rkpagadala** [comment]
Thanks Seb. I merged the other pr from Mandar

**Pull request closed without merging**
