### PR TITLE
iptables: add first tests utilizing `unshare` to run without root

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by costinm** [comment]
Context ? Is it for the test infra or what is the end goal here ?

**Comment by bleggett** [comment]
> Context ? Is it for the test infra or what is the end goal here ?

Test infra, to prove we can (cleanly) sandbox iptables in test suite.

**Review by bleggett — APPROVED** [review]
LGTM, not sure about multicluster test tho, I wouldn't expect that to be relevant to this.

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
