### PR TITLE
code cleanup: use cobra.Args to check command line arguments

### PR DESCRIPTION
**Pull request by BinacsLee**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

## Clarification

We should check the `args` just like this:

https://github.com/istio/istio/blob/master/istioctl/cmd/tag.go#L101-L110

```go
		Args: func(cmd *cobra.Command, args []string) error {
			if len(args) != 0 {
				return fmt.Errorf("unknown subcommand %q", args[0])
			}
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			cmd.HelpFunc()(cmd, args)
			return nil
		},
```

Thanks for review!

### CODE REVIEW

**Comment by BinacsLee** [comment]
@googlebot I signed it!

**Comment by BinacsLee** [comment]
/assign @liamawhite 

Thanks a lot!

**Comment by BinacsLee** [comment]
Hi @shamsher31 , could you please review this PR?

I will be very grateful if we can finish it. ^-^

**Review by shamsher31 — APPROVED** [review]
Thanks

**Pull request merged**
