### PR TITLE
Fix synthetic-service-entry push context init

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

This is to fix incremental SyntheticSE update. Without this, the push context is not right.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
lgtm @Nino-K

**Comment by hzxuzhonghu** [comment]
It seems there is no bot cherry-pick it to 1.4 automatically.

**Comment by howardjohn** [comment]
hmm there should be.. it's worked for other prs

**Pull request merged**
