### PR TITLE
iptables - fix redirection for UDP calls

### PR DESCRIPTION
**Pull request by deveshkandpal1224**
**Please provide a description of this PR:**
- After running latest master in our dev envs we noticed that cross cluster calls to resolve `svc.cluster.local` addresses are returning `NXDOMAIN` since the call is not being forwarded to DNS proxy.
- It seems the simplification done in [this](https://github.com/istio/istio/pull/50915) PR to manage UDP traffic on `ISTIO_OUTPUT` chain breaks because of below generated rules :

```
-A ISTIO_OUTPUT -j RETURN
-A ISTIO_OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 172.20.0.10/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 15053

```
- `-A ISTIO_OUTPUT -j RETURN` rule is coming from within `handleOutboundIncludeRules`, while UDP calls are added to `ISTIO_OUTPUT` after that. This PR moves it to the bottom of `Run()` function so that it gets added as the last rule to `ISTIO_OUTPUT` chain. Thinking about this a bit more, would it make sense to completely eliminate that rule since it will anyways be a no-op in the ISTIO_OUTPUT chain or is there a reason where this will continue to make sense ?

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by deveshkandpal1224** [comment]
@bleggett @eoinfennessy - when you have a moment, could you please take a look at this ? Appreciate your time! Thanks.

**Comment by howardjohn** [comment]
how is this not caught by our e2e tests...? we have a lot of rest coverage if DNS capture

**Comment by bleggett** [comment]
> would it make sense to completely eliminate that rule since it will anyways be a no-op in the ISTIO_OUTPUT chain or is there a reason where this will continue to make sense

Yeah we should drop it  - we no longer need an unconditional RETURN because we're not in the main table.

We should always jump to a chain for any sort of conditional logic block like this.

**Review by bleggett — COMMENTED** [review]
Can you add a test in `plugin_dryrun_test.go` that actually populates `OutboundIPRangesInclude` and tests the resulting generated iptables rules?

Clearly we didn't have a test that exercised this `else if` block, which is why none of the `.golden`'s had this (obviously wrong) RETURN in the middle of the emitted ruleset, which is why none of us noticed.

**Comment by deveshkandpal1224** [comment]
thanks for the feedback folks. I'll work on the test.  We do add `OutboundIPRangesInclude` in our env :)

**Comment by deveshkandpal1224** [comment]
@bleggett - I think the test you are referring to where outbound ranges need to be defined as a CIDR ( `else if` ) is covered in this test file [here](https://github.com/istio/istio/pull/51352/files#diff-87a900c4d51e14af35efdb90715580482ee91c076fe4f8fd01570fce75602af2L27), or were you suggesting having an isolated test only for `outboundIpRanges` ?

**Comment by bleggett** [comment]
> @bleggett - I think the test you are referring to where outbound ranges need to be defined as a CIDR ( `else if` ) is covered in this test file [here](https://github.com/istio/istio/pull/51352/files#diff-87a900c4d51e14af35efdb90715580482ee91c076fe4f8fd01570fce75602af2L27), or were you suggesting having an isolated test only for `outboundIpRanges` ?

Okay so we do have at least one test covering it. That's fine. Just missed it then.

**Comment by deveshkandpal1224** [comment]
@bleggett - added release notes. You PTAL when you have a moment ? Thanks!

**Review by bleggett — APPROVED** [review]
LGTM, ty for triaging!

**Pull request merged**
