### PR TITLE
[release-1.20] manifests: fix gateways.securityContext not work

### PR DESCRIPTION
**Pull request by timonwong**
**Please provide a description of this PR:**

Manual cherry-pick of #51654

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
this's more like a new feature rather than bug-fix(and without release-notes).

**Comment by hanxiaop** [comment]
> this's more like a new feature rather than bug-fix(and without release-notes).

@zirain This is not a new feature; it’s a supplement to the one that adds the configurable field, which was to fix an issue where users with old OS versions could not deploy the gateway.

**Review by zirain — APPROVED** [review]

**Pull request merged**
