### PR TITLE
dns: don't generate alt-hosts for FQDN

### LINKED ISSUE #47340: Incorrect values in NDS
Pilot nds looks good, but agent has weird values:

```yaml
vm.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
vm.echo.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
vm.echo.svc.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
vm.echo.svc.cluster.local:
  ips:
  - fd00:10:96::f006
  namespace: echo
  registry: Kubernetes
  shortname: vm
vm.echo.svc.cluster.local.:
  ips:
  - fd00:10:96::f006
  registry: Kubernetes
```

You can see the FQDN is duplicated

```yaml
istio-egressgateway.istio-system.:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system..:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc.:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc..:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc.cluster.local:
  ips:
  - fd00:10:96::47f3
  namespace: istio-system
  registry: Kubernetes
  shortname: istio-egressgateway
istio-egressgateway.istio-system.svc.cluster.local.:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
istio-egressgateway.istio-system.svc.cluster.local..:
  ips:
  - fd00:10:96::47f3
  registry: Kubernetes
```

double `..` seems broken

### PR DESCRIPTION
**Pull request by leosarra**
**Please provide a description of this PR:**

Fixes #47340

If we already have an unambigous name, don't generate additional alternatives hosts.
Otherwise we will end up with something like istio-egressgateway.istio-system.svc..

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
LGTM
/assign  @howardjohn

**Review by howardjohn — COMMENTED** [review]
can we add some tests coverage?

**Comment by leosarra** [comment]
> can we add some tests coverage?

Sure, tomorrow I will work on that

**Comment by zirain** [comment]
what about 1.19 ?

**Comment by hzxuzhonghu** [comment]
1.19 is EoL

**Comment by zirain** [comment]
> 1.19 is EoL

not now, https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases

**Comment by hzxuzhonghu** [comment]
ah, IC

**Comment by leosarra** [comment]
Existing tests are checking that specific names can be resolved via the DNS protocol and to which address they are resolved to.
The new tests are checking which alt hosts are generated, test will fail if we have more or less addresses than expected.

I did not check the whole DNS table (e.g: I do not check entry related to ipv4/6.localhost name). Let me know if you prefer me to check also the remaining ones or if you wish me to go for a different approach regarding the verification.

**Review by howardjohn — APPROVED** [review]

**Comment by leosarra** [comment]
@howardjohn I realized that the test case was flaky due to a race condition in how the start/cleanup of the DNS server is handled.
It can happen that the cleanup of the tests is performed before the start of the DNS server has concluded.
This only became apparent in my test because, unlike the other ones, I'm not running real DNS queries via a DNS client (which may have a timeout/retry logic) but I'm simply checking how the local tables were filled -> test terminates in a short time.

I tried to update the initDNS() test function to wait for a "IsReady()" condition before returning but it does us no good as IsReady does not check if the underlying server has started. The underlying mikieg's DNS library has a "isStarted" method which would come in handy if only it was not a private one.

For the time being I handled the issue as such:
- updated my test to create a DNS server without starting it as verifying the building of the alternate hosts does not require a running DNS server.
- Keep the rest unchanged as I don't think the existing tests will encounter the issue due to the retry/timeout logic. I will still keep an eye on it going forward.

Considering that I have changed the tests considerably since your last approval I have added a do-not-merge label, if things still looks good to you I will remove it.

**Comment by leosarra** [comment]
Thank you @howardjohn for the review :)

**Pull request merged**
