### PR TITLE
add install/kubernetes/istio-customresources.yaml 

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
**What this PR does / why we need it**:
There is an issue with the current istio deployment: CustomResourceDefinitions and their instances (custom resources) are defined in the same file, e.g. istio.yaml. There is a race condition - the resources could be added before CustomResourceDefinitions are known to Kubernetes (the definitions  are being added at the same time as the resources they define).

It can cause errors "unable to recognize matches... no matches for" that could confuse the users. I experience these errors  on minikube. Probably, the race condition happens on slow clusters with limited resources. 

When this condition happens, the `kubectl apply -f  install/kubernetes/istio.yaml` command must run several times before the errors disappear. During each run, the errors about deployments already defined appear, causing additional confusion.

Kubernetes instructions regarding adding CRDs and custom resources https://github.com/kubernetes/kubernetes/issues/57042

The proposed Kubernetes documentation wording https://github.com/kubernetes/website/pull/6660:

> Please note that it might take a few seconds for the endpoint to be created. You can watch the `Established` condition of your CustomResourceDefinition to be true or watch the discovery information of the API server for your resource to show up.

The proposed Istio flow will be as follows:

1. Optimistically try to deploy CRDs and the resources. 
`kubectl apply -f  install/kubernetes/istio.yaml`

If no errors appear, stop.

In rare cases, the errors "unable to recognize matches... no matches for"  appear, wait for several seconds.

2. Run `kubectl get crd`

If invalid age of CRDs is displayed, wait more, and then rerun `kubectl get crd` again, until valid age of CRDs is displayed. See example outputs below.

CRDs are not yet ready. Wait and rerun `kubectl get crd` again

```
$ kubectl get crd
NAME                                  AGE
attributemanifests.config.istio.io    <invalid>
checknothings.config.istio.io         <invalid>
...
```

CRDs are ready. Proceed to the next step.
```
$ kubectl get crd
NAME                                  AGE
attributemanifests.config.istio.io    7s
checknothings.config.istio.io         7s
...
```
3. `kubectl apply -f  install/kubernetes/istio-customresources.yaml`

https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps will have to be updated accordingly.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/istio/issues/issues/123

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
has someone else reproduced this issue (and not on minikube)?
I thought on the contrary having crd and cr in same file is what makes it work

cc @andraxylia

**Comment by vadimeisenbergibm** [comment]
In minikube you can deploy istio.yaml, run `kubectl get crd`. Once the CRD resources with the names *config.istio.io appear with valid age, istio-crd-instances.yaml can be applied.

```
$ kubectl get crd
NAME                                  AGE
attributemanifests.config.istio.io    4s
checknothings.config.istio.io         4s
deniers.config.istio.io               4s
destinationpolicies.config.istio.io   3s
egressrules.config.istio.io           3s
listcheckers.config.istio.io          4s
listentries.config.istio.io           4s
logentries.config.istio.io            4s
memquotas.config.istio.io             4s
metrics.config.istio.io               4s
noops.config.istio.io                 4s
prometheuses.config.istio.io          4s
quotas.config.istio.io                4s
reportnothings.config.istio.io        4s
routerules.config.istio.io            3s
rules.config.istio.io                 4s
stackdrivers.config.istio.io          4s
statsds.config.istio.io               4s
stdios.config.istio.io                4s
svcctrls.config.istio.io              4s
```

**Comment by vadimeisenbergibm** [comment]
After deploying istio.yaml on minikube, `kubectl get crd` returns:
```
$ kubectl get crd
NAME                                  AGE
attributemanifests.config.istio.io    <invalid>
checknothings.config.istio.io         <invalid>
deniers.config.istio.io               <invalid>
destinationpolicies.config.istio.io   <invalid>
egressrules.config.istio.io           <invalid>
listcheckers.config.istio.io          <invalid>
listentries.config.istio.io           <invalid>
logentries.config.istio.io            <invalid>
memquotas.config.istio.io             <invalid>
metrics.config.istio.io               <invalid>
noops.config.istio.io                 <invalid>
prometheuses.config.istio.io          <invalid>
quotas.config.istio.io                <invalid>
reportnothings.config.istio.io        <invalid>
routerules.config.istio.io            <invalid>
rules.config.istio.io                 <invalid>
stackdrivers.config.istio.io          <invalid>
statsds.config.istio.io               <invalid>
stdios.config.istio.io                <invalid>
svcctrls.config.istio.io              <invalid>
```

In this state, deploying CRD instances is not possible, errors appear.

Deploying CRD instances is possible only once `kubectl get crd` returns valid age.

**Comment by douglas-reid** [comment]
In general, I'm not opposed to moving the resources out into their own file. However, if we do this, we also need to make sure update the docs that reference the existing files too. I worry that some of the documented Tasks (etc.) will fall out of sync.

General comments:
- Should we rename the new file to be `istio-mixer-customresources.yaml.tmpl` instead ?
Reasoning: CRD instances are CustomResources. We should probably strive for consistent terminology.
- I would expect to see updates to the `*.yaml` files that should be generated with this new template file. Why are they not included in this PR?

**Comment by douglas-reid** [comment]
cc: @mandarjog

**Comment by ldemailly** [comment]
again, have we at least tested this doesn't make things worse for real clusters and is actually necessary/required/correct ? any link from k8s doc indicating so ?

**Comment by vadimeisenbergibm** [comment]
@douglas-reid 

> CRD instances are CustomResources

Agreed, renamed.

> If we do this, we also need to make sure update the docs that reference the existing files too.

I will update the documentation in https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps. Hope we will catch all other cases.

> I would expect to see updates to the *.yaml files that should be generated with this new template file. Why are they not included in this PR?

Note that istio-testing automatically updates istio.Version without updating the generated *.yaml files - for example by this PR https://github.com/istio/istio/pull/2014 as part of _Auto PR to update dependencies of istio_. Should _Auto PR to update dependencies of istio_ update the generated files as well?

I did not want to mix updating SHAs of the images and changing the content of the yaml files in the same PR.

**Comment by vadimeisenbergibm** [comment]
@ldemailly let me check what happens on a real cluster. 

The only reference I found in kubernetes documentation is this: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/ 

> After the CustomResourceDefinition object has been created, you can create custom objects.

The question is what "after" means here. I would guess it means after CRDs are initialized and `kubectl get crds` returns their valid age, starting with 0s.

**Comment by ldemailly** [comment]
I'm pretty sure kubectl ensure it works if it's in the same file (or at least I remember asking @andraxylia about it)

**Comment by ldemailly** [comment]
I also don't want to change the istio installation from 1 step to 2 steps with undetermined wait in the middle just because of 1 single unconfirmed user report and unclear root cause

**Comment by ayj** [comment]
Server-side configuration validation and automatic proxy injection webhooks requires cert provisioning. The install needs to be multiple step or we need to introduce an installer script regardless of this PR.

ref https://github.com/istio/istio/issues/1894, https://github.com/istio/istio/blob/master/install/kubernetes/generate-webhook-cert.sh

**Comment by ldemailly** [comment]
The base installation is still 1 step + kube-inject and my other point (is this really fixing something) stay irrespective of what we do with webhooks

**Comment by sdake** [comment]
@ldemailly I run istio.yaml on Kubernetes latest release (which was 1.8.4 prior to kubecon) on bare metal deployed via kubeadm 20+ times a day.  I run with and without initializer in many cases.

This results in: https://github.com/istio/istio/issues/1954

Unclear if they are related.  I have never thought to obtain the age of CRDs.  I'll give that a spin now.  Would love to have a solution to 1954 and perhaps this could be it.

**Comment by sdake** [comment]
@ldemailly reading that thread, the user reported that upgrading to kubernetes 1.8.4 resolves the problem for them (as of ~24 hours ago).  The root of the problem they suffered was running kubernetes 1.6.4 which has no CRD resources.

**Comment by sdake** [comment]
WIth http://github.com/sdake/istio-tools I receive the following output:


```VERTICAL
sdake@falkor-05:~/istio-tools$ kubectl get crd
NAME                                  AGE
attributemanifests.config.istio.io    2s
checknothings.config.istio.io         2s
deniers.config.istio.io               2s
destinationpolicies.config.istio.io   1s
egressrules.config.istio.io           1s
listcheckers.config.istio.io          2s
listentries.config.istio.io           2s
logentries.config.istio.io            2s
memquotas.config.istio.io             2s
metrics.config.istio.io               1s
noops.config.istio.io                 2s
prometheuses.config.istio.io          2s
quotas.config.istio.io                1s
reportnothings.config.istio.io        1s
routerules.config.istio.io            1s
rules.config.istio.io                 2s
stackdrivers.config.istio.io          2s
statsds.config.istio.io               2s
stdios.config.istio.io                2s
svcctrls.config.istio.io              2s```

Note, my bare metal is very speedy.

This may just be limited to minikube not waiting for kubelet to become active or (in the case of the reported issue) an incorrect version of Kubernetes under use (1.6.z was reported to fail, 1.8.4 was reported to work).

Cheers
-steve

**Comment by ldemailly** [comment]
> The root of the problem they suffered was running kubernetes 1.6.4 which has no CRD resources.

!

so I'm closing this for now

**Comment by sdake** [comment]
Note there was another issue hidden in this PR related to invalid CRDs when launching with minikube.  This is reproducible with this script:
https://github.com/sdake/istio-tools/blob/master/deploy-mk.sh

```NAME                                  AGE
attributemanifests.config.istio.io    5s
checknothings.config.istio.io         4s
deniers.config.istio.io               5s
destinationpolicies.config.istio.io   0s
egressrules.config.istio.io           <invalid>
listcheckers.config.istio.io          4s
listentries.config.istio.io           4s
logentries.config.istio.io            3s
memquotas.config.istio.io             4s
metrics.config.istio.io               3s
noops.config.istio.io                 4s
prometheuses.config.istio.io          4s
quotas.config.istio.io                3s
reportnothings.config.istio.io        3s
routerules.config.istio.io            <invalid>
rules.config.istio.io                 5s
stackdrivers.config.istio.io          4s
statsds.config.istio.io               4s
stdios.config.istio.io                4s
svcctrls.config.istio.io              4s
```

after 30-40 seconds, the invalid CRDs become valid.

**Comment by ldemailly** [comment]
that's quite odd (going from invalid to valid, any idea why ?)

**Comment by sdake** [comment]
There are a few deltas, but not clear on the root cause:
* Deploying with minikube launches in a VM versus https://github.com/sdake/istio-tools/blob/master/deploy.sh which launches on bare metal.
* the minikube launch script does not use calico as a CNI.

I placed a 30 second sleep after the launch of Kubernetes via minikube prior to starting istio.yaml, and the problem does not exhibit.  There are a variety of reasons that could resolve the problem.  My speculation is that Kubernetes in a VM is exhibiting a race condition.  Bare metal is too fast to see such race.

Cheers
-steve

**Comment by vadimeisenbergibm** [comment]
Created an issue for Kubernetes https://github.com/kubernetes/kubernetes/issues/57042.

**Comment by vadimeisenbergibm** [comment]
@ldemailly @andraxylia @sdake @ayj I removed from the PR the description the cases of kubernetes not supporting CRDs. The issue still exists, as @sdake pointed out - https://github.com/istio/istio/pull/2017#issuecomment-350597567. The issue https://github.com/istio/issues/issues/123 is still relevant.

Now we have feedback from Kubernetes on kubernetes/kubernetes#57042. I rewrote the PR description - please take a look.

I propose to optimistically deploy `install/kubernetes/istio.yaml`, as it is today. Only if errors appear, in rare cases, rerun deployment of custom resources in a separate step: `install/kubernetes/istio-customresources.yaml`

**Comment by vadimeisenbergibm** [comment]
@ldemailly could you please approve the new version of this PR and remove do-not-merge label? I addresses your concerns.

**Comment by ldemailly** [comment]
thanks for the updates. I still think this doesn't add much of anything vs `kubectl apply -f istio-auth.yaml` and that the priority would be to unify installs but if you feel strongly this is useful, go for it

**Comment by vadimeisenbergibm** [comment]
Closing, submitted a rebased PR #2250 .

**Pull request closed without merging**
