### PR TITLE
add listener tcp metadata exchange filter only when enabled

### PR DESCRIPTION
**Pull request by ramaraochavali**
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
I think this will not remove mx from alpn, which will cause issue? Also probably should also control the cluster network filter and alpn at upstream context.

**Comment by ramaraochavali** [comment]
> I think this will not remove mx from alpn, which will cause issue

I think cluster has same alpns but we control with flag. It does not create issue. So should be fine

> Also probably should also control the cluster network filter and alpn at upstream context.

This is already controlled

**Comment by bianpengyuan** [comment]
> I think cluster has same alpns but we control with flag. It does not create issue. So should be fine

But still it is incorrect config. The listener will claim something that it is not capable of. I can think of cases where someone switch this env var from true to false, and in the transition state, some cluster might still have mx in alpn, and connect with listeners which has mx in alpn but no mx filter. Request / TCP connection will fail during that brief period.

**Comment by ramaraochavali** [comment]
> But still it is incorrect config. The listener will claim something that it is not capable of. I can think of cases where someone switch this env var from true to false, and in the transition state, some cluster might still have mx in alpn, and connect with listeners which has mx in alpn but no mx filter. Request / TCP connection will fail during that brief period.

Is n't that the case already? This PR is trying to fix that inconsistency.

**Comment by bianpengyuan** [comment]
I don't think `features.MetadataExchange` controls listener alpn, so this PR actually make the filter chain and its alpn claim inconsistent? (i.e. alpn has `istio-peer-exchange` but no network mx filter in the chain). And looking at the code, it seems the same problem already exists at cluster, that `istio-peer-exchange` is always added to the alpn but client side tcp mx is controlled by `features.MetadataExchange`.

**Comment by ramaraochavali** [comment]
> And looking at the code, it seems the same problem already exists at cluster, that istio-peer-exchange is always added to the alpn but client side tcp mx is controlled by features.MetadataExchange.

This is what I meant. If this is a problem, I think we should control ALPNs also with this flag?

**Comment by bianpengyuan** [comment]
> This is what I meant. If this is a problem, I think we should control ALPNs also with this flag?

Yeah I think we should fix that instead of deepening the inconsistency.

**Comment by ramaraochavali** [comment]
@bianpengyuan Fixed  - ALPN is also controlled by that flag. PTAL.

**Comment by ramaraochavali** [comment]
@bianpengyuan Can you PTAL when you get chance?

**Review by bianpengyuan — APPROVED** [review]
LGTM, Sorry for the delay.

**Comment by ramaraochavali** [comment]
@bianpengyuan Np

@howardjohn Can you please review this as well?

**Review by hzxuzhonghu — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by ramaraochavali** [comment]
/ test integ-pilot-k8s-tests_istio

**Pull request merged**
