### PR TITLE
adjust galley dashboard time range

### PR DESCRIPTION
**Pull request by ayj**
fixes https://github.com/istio/istio/issues/11626

### CODE REVIEW

**Comment by mandarjog** [comment]
Thanks for the quick turn around.
Can you check if any other dashboard suffers from the same problem?

**Comment by ayj** [comment]
```
$ grep -rn '"from"' install/kubernetes/helm/subcharts/
install/kubernetes/helm/subcharts/grafana/dashboards/mixer-dashboard.json:1777:    "from": "now-5m",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-workload-dashboard.json:126:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-workload-dashboard.json:209:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-workload-dashboard.json:391:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-workload-dashboard.json:474:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-workload-dashboard.json:2271:    "from": "now-5m",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json:135:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json:216:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json:298:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json:380:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-mesh-dashboard.json:922:    "from": "now-5m",
install/kubernetes/helm/subcharts/grafana/dashboards/galley-dashboard.json:1777:    "from": "now-5m",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:83:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:166:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:352:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:435:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:518:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:704:          "from": "null",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-service-dashboard.json:2569:    "from": "now-5m",
install/kubernetes/helm/subcharts/grafana/dashboards/pilot-dashboard.json:1564:    "from": "now-5m",
install/kubernetes/helm/subcharts/grafana/dashboards/istio-performance-dashboard.json:566:    "from": "now-5m",
```

**Comment by ayj** [comment]
@wenchenglu, can you please merge into 1.1?

**Pull request merged**
