### PR TITLE
Disable Ingress for kiali

### LINKED ISSUE #26038: samples/addons kiali creates Ingress object
I feel like we probably don't want this. On my cluster it actually fails with  `error while evaluating the ingress spec: service "istio-system/kiali" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`. Istio users should probably use https://preliminary.istio.io/docs/tasks/observability/gateways/#configuring-remote-access not Ingress. Need to see if we can disable, probably just need to pass a flag.

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/26038

### CODE REVIEW

**Comment by jmazzitelli** [comment]
/lgtm

@howardjohn just a heads up. Clearly, operators are creating grief for some people, especially for simple demo applications like what we are doing here in the samples/addons stuff. So, most likely within the next 24 to 48 hours (once I get buy-in from the Kiali team that the additional maintenance burden this will create is acceptable), I'm going to propose we change the gen.sh to use the new-new Kiali Server Helm chart that we just merged (only a SNAPSHOT is published so far - we may be releasing an official release in a day or two). See: https://github.com/kiali/kiali-operator/pull/105

I will try to get this in quick so 1.7 can use it.

**Comment by howardjohn** [comment]
@jmazzitelli thanks! I think that will be really useful for the demo stuff!

**Review by douglas-reid — APPROVED** [review]

**Review by elfinhe — APPROVED** [review]

**Review by jmazzitelli — APPROVED** [review]
/lgtm

**Pull request merged**
