### PR TITLE
fix dr ca-cert analyzer reporting error when serviceentry is external

### PR DESCRIPTION
**Pull request by hanxiaop**
Originally when the analyzer analyzes the ca certificates for destination rules, even when the service entry is external, if the certs are missing, the analyzer will report the error IST0128. This PR is to fix the issue #32936.

[ ] Configuration Infrastructure
[ ] Docs
[] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by shamsher31 — COMMENTED** [review]
@monsteredc Thanks for the fix, please add release notes for the same.

**Comment by monsteredc** [comment]
@shamsher31 Thanks for the reminder! I've added the release note.

**Review by howardjohn — CHANGES_REQUESTED** [review]
Thanks for the PR!

> But if it is external, no caCertificates have to be specified as default public CA trusts are, presumably, used.

This assumption is not accurate, which is the reason the analyzer is in used. See https://github.com/istio/istio/issues/25652

**Comment by arcivanov** [comment]
@howardjohn So all of the examples in the docs concerning external HTTP/TLS ServiceEntry with DR are broken then when dealing with exposing public external websites, such as would the case be here: 

image

What is the point of requiring supplying a *publicly trusted CA* to the mesh for ALL such CAs? The overhead for every user of maintaining and supplying a public trust CA repository for each such DR is enormous as well as tracking *which* certificates belong to which CAs.

This is only in re MESH_EXTERNAL SE with DR TLS SIMPLE for publicly verifiable certificates:
1. Use public trust CAs if none specified.
2. Use specified CAs otherwise.

This is the only way it makes any practical sense for external service entry uses IMO.

**Comment by arcivanov** [comment]
Furthermore, imagine, as the docs suggest, I'm using an external service. I supply a CA but the external service gets a new certificate in a different chain under the same CA (changes validation depth).

Furthermore, what IS the validation depth in the SIMPLE configuration? Are we required to supply ALL the certificates in the chain up to and including the actual server certificate? What happens in validation depth is 3 and 2nd intermediary is missing?

This is an important security concern that has basically no documentation of the feature set.

**Pull request closed without merging**
