### PR TITLE
EDS metadata: fix ClusterID of network gateways

### PR DESCRIPTION
**Pull request by dddddai**
**Please provide a description of this PR:**
It's incorrect to set the ClusterID of network gateways to the proxy's ClusterID, which can generate wrong stas

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by stevenctl — COMMENTED** [review]
Can you add a release note?

**Review by hzxuzhonghu — APPROVED** [review]
lgtm

**Comment by howardjohn** [comment]
I am not sure I get it.

Say I have 3 clusters: source-cluster, dest-cluster, and gateway-cluster.

The metrics should be `src_cluster=source-cluster,dest_cluster=dest-cluster`. Not `src_cluster=source-cluster,dest_cluster=gateway-cluster`.

IIUC this PR is doing the opposite?

**Comment by hzxuzhonghu** [comment]
Without this, you could get `src_cluster=source-cluster,dest_cluster=source-cluster`

**Comment by howardjohn** [comment]
oh I get it now. thanks

**Pull request merged**
