### PR TITLE
Adding sidecars to validating webhook configuration

### PR DESCRIPTION
**Pull request by mbanikazemi**
Addresses issue #12193

### CODE REVIEW

**Comment by ozevren** [comment]
Does the backing validation code working in Pilot?

Can you please add a test to e2e-galley?
https://github.com/istio/istio/tree/master/tests/e2e/tests/galley/testdata
https://github.com/istio/istio/blob/5ecaf7557d1b3c7448db25d82313a8744f9df2e7/tests/e2e/tests/galley/galley_test.go#L104

**Comment by ymesika** [comment]
@wenchenglu Can we get this fix in?

**Comment by mbanikazemi** [comment]
@ozevren  yes, the validation code in Pilot works. Will add the tests you have requested tomorrow.

**Pull request merged**
