### PR TITLE
fix iop with custom hpa failed

### LINKED ISSUE #41011: Istio installation using IOP failed when hpaSpec for cpu utilization configured  for components
Installing istio with IOP(default profile) failed when hpaSpec for cpu utilization configured.

Error message - 
```
- Processing resources for Istio core.
   ✔ Istio core installed
   - Processing resources for Istiod.2022-08-30T23:43:32.119129Z        error   installer       failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: failed to create typed patch object (istio-system/istiod; autoscaling/v2beta1, Kind=HorizontalPodAutoscaler): .spec.metrics[0].resource.target: field not declared in schema
   
   ✘ Istiod encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: failed to create typed patch object (istio-system/istiod; autoscaling/v2beta1, Kind=HorizontalPodAutoscaler): .spec.metrics[0].resource.target: field not declared in schema
```

**Istio version** - 1.14.3
**Kubernetes version** - 1.24.3

**Attachments**: Istio IOP file generated using `istioctl profile dump`
[istio_1.14.3_default_profile.txt](https://github.com/istio/istio/files/9577498/istio_1.14.3_default_profile.txt)

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

fix: https://github.com/istio/istio/issues/41011

if you install an iop like following:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
      name: istio-ingressgateway
  values:
    pilot:
      cpu:
        targetAverageUtilization: 80
```

`translateDeprecatedAutoscalingFields` will change `global.autoscalingv2API` to `false`, and then `translateHPASpec` override hpa metirc to somehting like following, which is invalid for v1beta1.
```yaml
- type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: %f`
```

`translateHPASpec` should not translate configuration if `global.autoscalingv2API` is `false`.

### CODE REVIEW

**Comment by richardwxn** [comment]
This may only work if users explicitly define autoscalingv2: false in the IOP spec, which might not be the case most of the time since it servers as an internal settings only. I created: https://github.com/istio/istio/pull/41079 for a fix. PTAL

**Review by richardwxn — CHANGES_REQUESTED** [review]
See the comment above.

**Comment by zirain** [comment]
user can not set `autoscalingv2API` via IOP, it's an internal setting

**Comment by zirain** [comment]
replaced by https://github.com/istio/istio/pull/41079

**Pull request closed without merging**
