### PR TITLE
Replace the hard-coded proxy image for chart.

### PR DESCRIPTION
**Pull request by morvencao**
As we switch proxy to proxyv2 in https://github.com/istio/istio/pull/5741, we still have a strong desire to customized proxy image name, hopefully the hardcoded proxy image name can be replaced.

/cc @linsun @gyliu513

### CODE REVIEW

**Comment by ldemailly** [comment]
thank you, that was my comment/feedback in Lin’s pr

**Comment by ldemailly** [comment]
0.8 will have more fixes, I doubt it's "closed" - now maybe we can say this particular fix isn't critical enough to be put in, but this is an LTS branch so I would think it makes sense.

Maybe the variable should be `.Values.global.control-plane-proxy.image`

**Comment by gyliu513** [comment]
> Maybe the variable should be .Values.global.control-plane-proxy.image

@ldemailly +1 to update `values.yaml` to rename to `control-plane-proxy`

@costinm , also +1 to @ldemailly , considering 0.8 is LTS, it is better merge this to 0.8 as well.

**Comment by ldemailly** [comment]
ps: I don't know the rules about helm variable naming, maybe `-` is not legal and it would need to be `controlPlaneProxy` (camelCase) instead ?

**Comment by costinm** [comment]
This PR would break igressgateway in the upgrade - it can't work with v1.

Please do not merge in 0.8. 

And probably do not merge in master - since v1 should no longer be supported there.

**Comment by linsun** [comment]
agreed with @costinm 's comment above.

**Comment by gyliu513** [comment]
@costinm why this change will break ingressgateway in the upgrade? Can you please show more detail for this? As I can see, we only do not want to hardcode the proxy image name in the chart.

**Comment by linsun** [comment]
@gyliu513 because you'd be configure ingress gateway to use v1 proxy which is recommended proxy per our install doc till you fully move all your apps to the new network API.

**Comment by ldemailly** [comment]
there should be a variable, controlPlaneProxy would work and not conflict with user choice of v1/v2 for their app proxies

**Comment by gyliu513** [comment]
@ldemailly you mean add a new parameter in `values.yaml` for proxy v2?

**Comment by linsun** [comment]
we don't intend to expose control plane proxy as a configuration option for our users thus we didn't make it a param in values.yaml.  We should review all params exposed by helm in one of the few upcoming env WG meetings as we should be exposing only the params that we want users to config in values.yaml.

**Comment by gyliu513** [comment]
@linsun for some offline install, some customer may want to pull all of the images from dockerhub and push it to their private registry with re-tag, and for this case, it is better to enable customer customized the control panel image.

**Comment by costinm** [comment]
For sidecars - users may want to use a different build (with their own
envoy plugins), base image ( fedora, etc), etc.
For control plane - we do not allow users to customize.

We already have far too many options that need to be sanitized.

Re. breakage: as Lin said, ingress gateway does not support v1. Just like
old ingress does not support v2.
Because v1 does not implement the Gateway and new alpha3, and the v2 does
not implement RouteRules and alpha1.

**Pull request closed without merging**
