### PR TITLE
Update istio.io/api dependency in vendor.

### PR DESCRIPTION
**Pull request by incfly**
Run `dep ensure -v -update istio.io/api` to generate this PR.

#5059

### CODE REVIEW

**Comment by incfly** [comment]
@diemtvu I found the https://github.com/istio/api/pull/456 removes some types like `EndUserAuthnSpec` but they are still used in the mixer's code. This is why some tests failing above. Would you continue to remove istio/istio reference of those fields? Or any other suggestion to proceed?

**Comment by yangminzhu** [comment]
@incfly Thanks for syncing the API repo.
I think you have to either wait for the cleaning of istio/api#456 is done or sync this PR to an earlier commit in istio/api. The latter doesn't make sense for your purpose of this PR, so probably just wait for some time.

**Comment by rshriram** [comment]
You might have to wait until the mixer change that's breaking in istio/api is reverted..

**Comment by rshriram** [comment]
api updated to master commit.

**Pull request closed without merging**
