### PR TITLE
Remove dead code for codecov and bookinfo output

### PR DESCRIPTION
**Pull request by howardjohn**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Comment by howardjohn** [comment]
@linsun can you take a look?

**Review by elfinhe — APPROVED** [review]

**Review by linsun — APPROVED** [review]

**Pull request merged**
