### PR TITLE
Prevent generation of filter chains with identical CIDR matches

### PR DESCRIPTION
**Pull request by mbanikazemi**
Fixes: issue #14334

Needs unit tests.

### CODE REVIEW

**Comment by howardjohn** [comment]
Thank you for the quick fix! I manually confirmed this fix works, would be great to have unit tests for preventing regressions

**Comment by mbanikazemi** [comment]
should get the unit tests done tomorrow.

**Comment by mbanikazemi** [comment]
@howardjohn cherry-picking this for release-1.2 will require cherry-picking #14134 as well, it seems. I think you had asked for a cherrypick but now I am not sure if I am confusing this PR with something else. Either way feel free to proceed yourself or let me know.

**Comment by howardjohn** [comment]
what does this have to do with the access log PR? we want this into 1.2 as it is a bug fix for a critical but

**Pull request merged**
