### PR TITLE
feat(helm): add settings to stabilize gateways for high traffic

### PR DESCRIPTION
**Pull request by diranged**
**Please provide a description of this PR:**

Re-opening https://github.com/istio/istio/pull/45914/files and hoping to get it pushed through this time. 

We operate our IngressGateways at fairly high traffic volumes - frequently exceeding 50,000 QPS of inbound traffic with a _wide_ range of traffic shapes. We've found that in order to safely replace pods at this scale, we need to make tweaks to the Deployment rollout process. These three settings (`spec.strategy`, `spec.minReadySeconds` and `spec.template.spec.terminationGracePeriodSeconds`) are critical to tuning the rollout process to be stable and smooth no matter the traffic load.

### CODE REVIEW

**Comment by diranged** [comment]
@zirain - could you re-evaluate this PR again? I know that I let the ball drop on https://github.com/istio/istio/pull/45914 .. but I'd like to get this in officially. I'm hoping this time around the tests pass. I think I had a typo in the helm templating on the previous PR.

**Comment by zirain** [comment]
/ok-to-test

please add release notes

**Comment by diranged** [comment]
@zirain I've updated the PR and all the builds are passing

**Review by zirain — APPROVED** [review]

**Comment by diranged** [comment]
Thank you!! ;)

**Comment by indranilvyasFlipp** [comment]
Following chart still doesn't reflect this change:  https://istio-release.storage.googleapis.com/charts/gateway-1.23.1.tgz

**Comment by zirain** [comment]
this's a new feature, will land in v1.24.0 hopfully.

**Pull request merged**
