### PR TITLE
Revert "Add support for Mapkey caching"

### PR DESCRIPTION
**Pull request by hklai**
Reverts istio/istio#1828

This broke e2e tests. 
e2e-suite-rbac-auth failed: https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/76

e2e-suite-rbac-no_auth failed: https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/76

We need to green postsubmit run as we can cutting 0.3.0 today.

### CODE REVIEW

**Comment by mandarjog** [comment]
@rkpagadala this also reverts your proxy sha update. Is that ok ?

**Comment by rkpagadala** [comment]
@mandarjog its alright, I will add it again

**Comment by ldemailly** [comment]
did we know for sure the reverted PR broke the test / is related ?

I need to look at the fortio failure - it may be a different issue - is there instructions on how to run tests against one's cluster post merge ?

**Comment by hklai** [comment]
The failure was FAILED: //tests/e2e/tests/mixer:go_default_test so this was the most likely culprit.
And I believe Seb saw the failure started with https://github.com/istio/istio/pull/1828

**Comment by mandarjog** [comment]
Yes, indeed. It was caused by #1828

**Comment by ldemailly** [comment]
I was a bit anxious when I saw in the logs it was using the latest fortio I had just released, glad that’s not the issue. thanks!

**Pull request merged**
