### PR TITLE
Drain listeners gracefully

### PR DESCRIPTION
**Pull request by howardjohn**
See https://github.com/envoyproxy/envoy/pull/11639/files

The old draining behavior: GOAWAY/connection: close all existing
connections, reject all new connections. This means if a connection is
established (because of slow propogationo of endpoint updates or similar
issues), it will be closed. This connection actually has a chance to
succeed, if the app has not shut down yet, or for ingress its very
likely to be ok as we know envoy is still running.

The new behavior will still goaway existing connections, but new
connections are accepted

Along with bumping up the drain to 10s, I have gotten 100% success with https://github.com/istio/istio/issues/26524; prior to this it fails every rollout

### CODE REVIEW

**Comment by howardjohn** [comment]
Hold for wider review.

cc @hzxuzhonghu @ramaraochavali @lambdai @liamawhite @XanderStrike

**Comment by linsun** [comment]
@howardjohn nice found - good job!  Any objection for cherry pick to 1.7?

**Comment by howardjohn** [comment]
It's not in Envoy in 1.7

**Comment by linsun** [comment]
oh i see :-(

**Pull request merged**
