### PR TITLE
Disable MCP when installing Istio minimal

### PR DESCRIPTION
**Pull request by ymesika**
Added a flag that disables the MCP flag when installing with the Istio minimal values.

### CODE REVIEW

**Comment by ymesika** [comment]
Fixes #11110

/assign @linsun

**Comment by ymesika** [comment]
@itaysk there is actually an open PR with this change: https://github.com/istio/istio.io/pull/3101
@morvencao please consider suggestion above for using the values in the doc.

**Comment by ymesika** [comment]
@morvencao The suggestion is to use the command `helm install install/kubernetes/helm/istio --name istio-minimal --namespace istio-system --values install/kubernetes/helm/istio/values-istio-minimal.yam` instead of the flags. What do you think?

**Comment by morvencao** [comment]
@ymesika All right, let me update it.

**Pull request merged**
