### PR TITLE
Revert "multi-cluster panic fix"

### PR DESCRIPTION
**Pull request by kyessenov**
Reverts istio/istio#15700

Please follow the conventions of our project when submitting a PR:
- need an explanation what the issue is and what the fix is;
- need a test exercising the change in the behavior
- need an approval from a component OWNER

/assign @mandarjog

### CODE REVIEW

**Comment by nicktrav** [comment]
@kyessenov - we hit the same crash in 1.2.5 that the original patch was intended to fix. Is there any indication that mixer is still vulnerable to this crash in 1.3.x?

i.e. was this reverted due to a lack of tests on the original patch? Or is there functionality elsewhere that prevents this crash from happening?

**Comment by kyessenov** [comment]
I don't fully recall all the details now, but the revert was due to lack of tests and lack of explanation of the intent of the PR. There were a few changes after this. If you think there is a bug, please explain how to reproduce it and we can address it.

**Pull request merged**
