### PR TITLE
Remove PILOT_ENABLE_FLOW_CONTROL flag

### PR DESCRIPTION
**Pull request by howardjohn**
This was added like 2 years ago and has no known usage and adds a lot of complexity to our core codepaths. I think its best to remove; if we want to re-vist we can always add it back

### CODE REVIEW

**Review by stevenctl — APPROVED** [review]
code LGTM, deferring to others on the intent

**Review by lei-tang — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
It is to fix https://github.com/istio/istio/issues/25685

@[ZhuangYuZY](https://github.com/ZhuangYuZY) From IBM could use it.

**Comment by howardjohn** [comment]
I checked that Knative, who the fix was originally developed for, does not actually use this flag. I am pretty sure it doesn't actually work. Can I remove the hold?

**Comment by hzxuzhonghu** [comment]
LGTM

**Pull request merged**
