### PR TITLE
Automatically config the ClusterRole based on certificates setting

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/19226

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by howardjohn — CHANGES_REQUESTED** [review]
should make sure this doesn't break istiod

**Comment by howardjohn** [comment]
Specifically worried about conflicts with https://github.com/istio/istio/pull/19107

**Comment by lei-tang** [comment]
This PR configures the clusterrole for Pilot and does not affect istiod.

**Comment by howardjohn** [comment]
@lei-tang the PR linked is changing Pilot. We are deleting the standalone istiod

**Comment by lei-tang** [comment]
@howardjohn https://github.com/istio/istio/pull/19107 has been merged. Can you take another look of this PR?

**Comment by howardjohn** [comment]
#19107 is making CSRs even without certificates field in mesh config set

**Pull request closed without merging**
