### PR TITLE
Fix istioctl wait and add integ test

### PR DESCRIPTION
**Pull request by therealmitchconnors**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by therealmitchconnors** [comment]
This is effectively a cherry-pick of #23999, made manually because of the significant differences in the two codebases.

**Comment by therealmitchconnors** [comment]
I agree that lack of testing in 1.5 was an oversight on my part.  The tests were implemented in istio.io, but unfortunately they were rolled back when this functionality was broken, instead of investigating the root cause.  

While there is risk around this change, a similar cherry-pick has been made to 1.6.1 to fix the same issue in that release, and the code has been in master for around a month with no notable problems.  Additionally, we have a large user whose 1.5 upgrade is potentially blocked by this feature being broken.  Workarounds are expensive, flakey, and, in the words of this user, 'a huge hack.'

**Comment by esnible** [comment]
@therealmitchconnors Can you triage this / give it a priority?

**Comment by therealmitchconnors** [comment]
Closing as 1.5 is EOL in 10 days...

**Pull request closed without merging**
