### PR TITLE
Bump go-control-plane

### PR DESCRIPTION
**Pull request by howardjohn**
```
name                         old time/op        new time/op        delta
EndpointGeneration/1/100-8          825µs ±11%         451µs ± 5%  -45.31%  (p=0.100 n=3+3)
EndpointGeneration/10/10-8          514µs ± 4%         250µs ± 7%  -51.28%  (p=0.100 n=3+3)
EndpointGeneration/100/10-8        4.72ms ± 2%        2.04ms ± 0%  -56.79%  (p=0.100 n=3+3)
EndpointGeneration/1000/1-8        4.74ms ± 2%        2.10ms ± 2%  -55.67%  (p=0.100 n=3+3)

name                         old kb/msg         new kb/msg         delta
EndpointGeneration/1/100-8           16.2 ± 0%          16.2 ± 0%     ~     (all equal)
EndpointGeneration/10/10-8           13.0 ± 0%          13.0 ± 0%     ~     (all equal)
EndpointGeneration/100/10-8           128 ± 0%           128 ± 0%     ~     (all equal)
EndpointGeneration/1000/1-8           129 ± 0%           129 ± 0%     ~     (all equal)

name                         old resources/msg  new resources/msg  delta
EndpointGeneration/1/100-8            100 ± 0%           100 ± 0%     ~     (all equal)
EndpointGeneration/10/10-8           10.0 ± 0%          10.0 ± 0%     ~     (all equal)
EndpointGeneration/100/10-8          10.0 ± 0%          10.0 ± 0%     ~     (all equal)
EndpointGeneration/1000/1-8          1.00 ± 0%          1.00 ± 0%     ~     (all equal)

name                         old alloc/op       new alloc/op       delta
EndpointGeneration/1/100-8          409kB ± 0%         372kB ± 0%   -9.01%  (p=0.100 n=3+3)
EndpointGeneration/10/10-8          249kB ± 0%         212kB ± 0%  -14.79%  (p=0.100 n=3+3)
EndpointGeneration/100/10-8        2.30MB ± 0%        1.93MB ± 0%  -15.99%  (p=0.100 n=3+3)
EndpointGeneration/1000/1-8        2.30MB ± 0%        1.93MB ± 0%  -16.02%  (p=0.100 n=3+3)

name                         old allocs/op      new allocs/op      delta
EndpointGeneration/1/100-8          7.62k ± 0%         6.02k ± 0%  -21.00%  (p=0.100 n=3+3)
EndpointGeneration/10/10-8          4.98k ± 0%         3.38k ± 0%  -32.11%  (p=0.100 n=3+3)
EndpointGeneration/100/10-8         45.6k ± 0%         29.6k ± 0%  -35.09%  (p=0.100 n=3+3)
EndpointGeneration/1000/1-8         45.1k ± 0%         29.1k ± 0%  -35.49%  (p=0.100 n=3+3)
```

Not shabby :slightly_smiling_face:

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
These are microbenchmarks AFAICT.

**Comment by howardjohn** [comment]
> These are microbenchmarks AFAICT.

The ones I showed are, yes since they take a long time to run so I only showed a few. https://github.com/envoyproxy/go-control-plane/issues/824 shows all of them, and they are not really microbenchmarks -- they cover ~90% of Pilot CPU usage in typical real world scenarios and are fairly high level

**Comment by sschepens** [comment]
Nice! Can we get this into 1.22?

**Comment by howardjohn** [comment]
> Nice! Can we get this into 1.22?

Plan is 1.21 assuming this merges

**Comment by sschepens** [comment]
> > Nice! Can we get this into 1.22?
> 
> 
> 
> Plan is 1.21 assuming this merges

Yeah, I meant 1.21 lol. Excellent!

**Comment by sschepens** [comment]
@howardjohn shouldn't we implement something like: https://github.com/vitessio/vitess/blob/main/go/vt/servenv/grpc_codec.go ? To allow for grpc framework to use vtprotobuf's methods on messages sent/received through grpc?

**Comment by howardjohn** [comment]
I added a feature flag on this for now so we can do some more testing and validation before pushing it out to everyone (off by default)

**Review by hzxuzhonghu — COMMENTED** [review]
Good to add a feature flag, could you enable it for tests

**Review by jacob-delgado — APPROVED** [review]

**Comment by ericvn** [comment]
/retest


https://github.com/istio/istio/issues/48872

**Review by zirain — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
