### PR TITLE
Disable EnableAutomTLSCheckPolicies due to race condition

### PR DESCRIPTION
**Pull request by howardjohn**
See https://github.com/istio/istio/issues/34227

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by incfly — APPROVED** [review]
might need to add this ENABLE_AUTO_MTLS_CHECK_PICKES: true to the integration tests main_test.go.

**Comment by howardjohn** [comment]
I do not think we want it running in tests, it has a race condition that will crash the istiod and make tests flake (which is how I found it)

**Comment by howardjohn** [comment]
Ah... but I need to disable the test that depends on it

**Comment by incfly** [comment]
sure. then you can comment out the `automtls-*-workload.yaml` test introduced in the original PR.

**Review by incfly — APPROVED** [review]

**Review by adiprerepa — APPROVED** [review]

**Pull request merged**
