### PR TITLE
Switch default LB algorithm to LEAST_REQUEST

### PR DESCRIPTION
**Pull request by nmittler**
Also adding an environment variable to revert the default globally.

**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
lgtm but will others review since it is changing something prettty core

**Comment by ramaraochavali** [comment]
LGTM as well

**Review by howardjohn — APPROVED** [review]

**Review by douglas-reid — APPROVED** [review]
p&t owned changes seem fine. i'm not sure that increasing request counts will ultimately ensure full cross-cluster traffic, but maybe 20 reqs is enough?

**Comment by nmittler** [comment]
> p&t owned changes seem fine. i'm not sure that increasing request counts will ultimately ensure full cross-cluster traffic, but maybe 20 reqs is enough?

@douglas-reid It's actually 20 * number of clusters, so in our case we have 3 clusters = 60 requests.

**Pull request merged**
