### PR TITLE
fix path separator in revision.

### LINKED ISSUE #26095: bug: istio-operator throws an error when an `IstioOperator` resource is created with a `revision` element that contains a period
**Bug description**

istio-operator throws an error when an `IstioOperator` resource is created with a `revision` element that contains a period. It cannot reconcile and create the control plane canary revision.

```
2020-08-03T23:56:33.226327Z     info    Reconciling IstioOperator
2020-08-03T23:56:33.227122Z     info    Updating IstioOperator
2020-08-03T23:56:33.227192Z     info    installer       ReadProfileYAML for profile name: default
2020-08-03T23:56:33.227219Z     info    installer       Loading values from compiled in VFS at path profiles/default.yaml
2020-08-03T23:56:33.787130Z     info    Detecting third-party JWT support
2020-08-03T23:56:34.389078Z     info    Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/
security/#configure-third-party-service-account-tokens for details.
2020-08-03T23:56:37.988682Z     error   reconciling err: path [Deployment:istiod-1.6.7].spec.strategy has an unexpected first element [Deployment:istiod-1 in OverlayK8sSettings
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I expect to be able to use periods in the revision name.

**Steps to reproduce the bug**

```
$ istioctl operator init

$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: broken-control-plane
spec:
  profile: default
  revision: 1.6.7
EOF
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ kubectl get deployment istio-operator --namespace istio-operator -o jsonpath='{..operator\.istio\.io/version}'
1.6.7

$ istioctl version --remote
client version: 1.6.7
control plane version: 1.5.7
data plane version: 1.5.7 (2 proxies)
```

**How was Istio installed?**

`istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**

`kind` cluster on mac os.

### PR DESCRIPTION
**Pull request by morvencao**
Resolve: https://github.com/istio/istio/issues/26095

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Shouldwe just reject `.` in the revision?

**Comment by morvencao** [comment]
emm, I just recalled that k8s resource name doesn't allow `.`, we should add validation for `revision`, right? @howardjohn

**Comment by morvencao** [comment]
Looks like the k8s name allows `.` in resource name from https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by howardjohn** [comment]
Yeah it is supported - but we don't need to allow it for revision if its going to cause issues. I don't feel strongly either way, as long as we can ensure it actually does work with `.`

**Comment by morvencao** [comment]
Close this as `.` is not allowed in revision, need to replace it with `-`.

**Pull request closed without merging**
