### PR TITLE
Add envFrom values to Gateway helm chart

### PR DESCRIPTION
**Pull request by cnvergence**
**Please provide a description of this PR:**
Adds an optional field to support loading all required envs directly from Kubernetes secrets or configmaps
See also: 
- https://github.com/istio/istio/issues/42860

### CODE REVIEW

**Comment by howardjohn** [comment]
What is the usecase? This seems fairly niche, may be suited for https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by cnvergence** [comment]
> What is the usecase? This seems fairly niche, may be suited for https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

I agree it is niche, but the main use case reported in the issue was to safely pass env vars from Kubernetes secret.
Let me get back to the reporter, if the advanced helm chart configuration will also solve this issue.

**Comment by howardjohn** [comment]
It would be useful to know what env var they are trying to set

**Comment by kstasik** [comment]
`WasmPlugin` gives you the option to set configuration using `pluginConfig` and `vmConfig`. If you want to pass on secrets 
 (like JWT keys) you have to use environment variables from the host. We need to pass env variables from Kubernetes secrets generated by the secret manager.

**Comment by howardjohn** [comment]
@kyessenov @ingwonsong are there better approaches to secrets for WASM?

**Comment by ingwonsong** [comment]
> @kyessenov @ingwonsong are there better approaches to secrets for WASM?

one of the approaches would be to extend Wasm API for supporting `Secret` from https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#EnvVar

**Comment by kyessenov** [comment]
There's nothing specific to secrets in Wasm. Using env variables seems reasonable to establish workload identity.

**Comment by cnvergence** [comment]
@howardjohn I think for this use case, this is still valid
PTAL: https://github.com/istio/istio/issues/42860#issuecomment-1404979716

**Comment by kstasik** [comment]
No-one needs injecting secrets on a gateway level (or WasmPlugins)? Isn't moving authorization/authentication layer to the gateway a common use case? How people are managing secrets needed by WasmPlugin, using kustomize as post processing tool? Actually I think it feels like a common use case - one of the best use cases if you don't want to manage additional api gateways like kong, tyk or krakend.

**Pull request closed without merging**
