### PR TITLE
check if virtual service destinations has matching ports

### PR DESCRIPTION
**Pull request by ramaraochavali**
https://github.com/istio/istio/pull/20408 we added support for adding additional virtual host destinations. But it does not check if the matching destination has the matching ports when egress listener has ports. This PR fixes. Please see the test case added for the problem.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by howardjohn** [comment]
Is this a performance optimization or fixing behavior?

**Comment by ramaraochavali** [comment]
bug fix. Not a perf optimization. It is  not honouring port for the virtual service destinations. This PR fixes it.

**Review by howardjohn — COMMENTED** [review]
I am a bit confused. We have the selectServices call matchingService which has almost identical logic. Can we not just do the same in selectVirtualServices?

**Comment by ramaraochavali** [comment]
> I am a bit confused. We have the selectServices call matchingService which has almost identical logic. Can we not just do the same in selectVirtualServices?

We can not do there because selectVirtualServices selects by matching hosts. but this problem is about destination hosts  that we select here https://github.com/istio/istio/blob/master/pilot/pkg/model/sidecar.go#L337 and we add those services which may not have those ports defined for egress listener.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
