### PR TITLE
Use apiVersion without deprecation warnings for Ingress resources

### PR DESCRIPTION
**Pull request by dieterdemeyer**
This change will remove deprecation warnings for the `Ingress` resources in the helm chart.

### CODE REVIEW

**Comment by clyang82** [comment]
Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. but Istio 1.5 has been tested with Kubernetes releases 1.13, 1.14, 1.15. The 1.13 is still supported.

**Review by howardjohn — CHANGES_REQUESTED** [review]
extensions/v1beta1 is around until 1.20, lets wait a bit rather than breaking users on 1.13?

**Review by howardjohn — CHANGES_REQUESTED** [review]
Actually, this whole folder is deprecated and will be removed anyways in about a week

**Comment by dieterdemeyer** [comment]
Alright, perhaps you are in favor of closing this issue ? I can always create a new PR when Kubernetes 1.13 is no longer supported.

**Comment by howardjohn** [comment]
I think in master we can drop support for 1.13, but these files have been removed in favor of the `manifests/` folder. I think a similar change to that folder would be useful

**Comment by dieterdemeyer** [comment]
I would be more than happy to change this in the manifests folder but after checking all files in that folder, I'm unable to find the yaml files where the Ingress resources are defined for those that were originally in my PR...
Are Ingress resources managed in a different way here ?

**Review by richardwxn — COMMENTED** [review]
I think we only have prometheus ingress for the new charts under manfiests/

**Pull request closed without merging**
