### PR TITLE
Fix nil pointer dereference in initSidecarInjector of Pilot

### PR DESCRIPTION
**Pull request by SpecialYang**
When the Pilot is deployed in a non-K8s environment, the process of initializing the server will cause the program to panic. In order to reproduce this issue, as in the following example, set the service registry of the Pilot to Mock registry,  build and run discovery cmd.
```
./pilot-discovery discovery --registries=mock --configDir=/tmp
```
Then, I got the nil pointer dereference error.
```
panic: runtime error: invalid memory address or nil pointer dereference
```
I find the reason. When the local injection config is not exist in the path `./var/lib/istio/inject` specified in initial `serverArgs`, the  server will find the remote injection config by accessing ConfigMap with KubeClient. Our Pilot is deployed in a non-K8s environment and the KubeClient will not be created, so we get the nil pointer dereference.

I improve the code of this method `initSidecarInjector ` to avoid the above issue. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by SpecialYang** [comment]
@googlebot I signed it!

**Review by howardjohn — APPROVED** [review]

**Comment by SpecialYang** [comment]
@howardjohn Can you add the label `release-notes-none` for this pr? Thanks.

**Pull request merged**
