### PR TITLE
fix: added uuid_extension_test.go test cases

### PR DESCRIPTION
**Pull request by ramanujadasu**
**Please provide a description of this PR:**
Fix: Added uuid_extension_test.go test cases
(Ref: https://github.com/istio/istio/issues/37354)

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@[ramanujadasu](https://github.com/ramanujadasu) please add some more valuable tests.

**Comment by hzxuzhonghu** [comment]
FYI https://github.com/istio/istio/issues?q=is%3Aopen+is%3Aissue+label%3A%22community%2Fhelp+wanted%22+

**Comment by ramanujadasu** [comment]
Could you please add [release-notes-none] label

**Pull request closed without merging**
