### PR TITLE
The output of "istioctl ps" cmd show the cluster(k8s) name which a pod belongs

### LINKED ISSUE #36290: The output of "istioctl ps" cmd should include the  cluster(k8s) name which a pod belongs
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In a multi-cluster scenario, we execute `istioctl ps`, output the following content:
```bash
$istioctl ps
NAME                                                     CDS        LDS        EDS        RDS          ISTIOD                             VERSION
istio-egressgateway-d7dd9b576-rp6m8.istio-system         SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
istio-ingressgateway-1-7ccb8dfc57-rj7hm.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
istio-ingressgateway-2-5fddcd5f97-f9fsn.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
istio-ingressgateway-5cf945c645-p25xl.istio-system       SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
productpage-v1-69d58d775f-6qbgc.default                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-1-10-3-845cddf779-67wx9     1.10.3
reviews-v1-769b6ccbcf-mvkd5.default                      SYNCED     SYNCED     SYNCED     SYNCED       istiod-1-10-3-845cddf779-67wx9     1.10.3

```
However, sometimes we expect to see the cluster name of a pod in multi-cluster mesh

**Describe alternatives you've considered**
We can add the `CLUSTER` column in the output of `istioctl ps` command , like:
```
$ istioctl ps
NAME                                                     CLUSTER     CDS        LDS        EDS        RDS          ISTIOD                             VERSION
istio-egressgateway-d7dd9b576-rp6m8.istio-system         cluster1    SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
istio-ingressgateway-1-7ccb8dfc57-rj7hm.istio-system     cluster1    SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
istio-ingressgateway-2-5fddcd5f97-f9fsn.istio-system     cluster1    SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
istio-ingressgateway-5cf945c645-p25xl.istio-system       cluster2    SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-10-3-845cddf779-67wx9     1.10.3
productpage-v1-69d58d775f-6qbgc.default                  cluster2    SYNCED     SYNCED     SYNCED     SYNCED       istiod-1-10-3-845cddf779-67wx9     1.10.3
reviews-v1-769b6ccbcf-mvkd5.default                      cluster2    SYNCED     SYNCED     SYNCED     SYNCED       istiod-1-10-3-845cddf779-67wx9     1.10.3
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by miaoyq**
**Please provide a description of this PR:**
fix #36290

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
lgtm, i think it's worth a release note

**Comment by miaoyq** [comment]
@hzxuzhonghu Thanks for review :-).

**Comment by miaoyq** [comment]
/cc @istio/wg-user-experience-maintainers
istio/wg-user-experience-maintainers

**Comment by miaoyq** [comment]
@howardjohn Could you take a look the PR  :-)

**Review by howardjohn — APPROVED** [review]
LGTM from T&R perspective

**Comment by miaoyq** [comment]
cc  @therealmitchconnors  :-)

**Comment by miaoyq** [comment]
@esnible Could you please take a look at the PR, Thx :-)

**Comment by ericvn** [comment]
Looking at istio.io, I don't see any of the places where `istioctl ps` is used with example output that is tested. Thus, I don't think any istio.io tests will fail once this is merged, but several pages will have old output without the CLUSTER name.

**Pull request merged**
