### PR TITLE
lookup test only features in test code

### PR DESCRIPTION
**Pull request by ramaraochavali**
This PR tries to lookup test "only" features in test code only so that it is not enabled accidentally in production.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Still working on it.

**Review by howardjohn — COMMENTED** [review]
I don't think these are test only like `go test` only. I am deploying runtime assertion to my live cluster

**Comment by howardjohn** [comment]
we could do a build tag but its a bit annoying since you need to rebuild

**Comment by ramaraochavali** [comment]
> we could do a build tag but its a bit annoying since you need to rebuild

Yeah. I looked t that option but it is annoying to rebuild.

**Comment by ramaraochavali** [comment]
I will close this. I am looking at another solution. I will open a fresh PR when it is ready.

**Pull request closed without merging**
