### PR TITLE
remove unused post-install hook.

### PR DESCRIPTION
**Pull request by morvencao**
Merge https://github.com/istio/istio/pull/7717

### CODE REVIEW

**Comment by costinm** [comment]
Could you rebase ?

**Comment by sdake** [comment]
/lgtm
@costinm can approve as he was first to review - or if he doesn't lmk and I'll approve.

fairly certain this will break `helm upgrade` although kubectl apply should work in an upgrade.  This may reduce the future upgrade pain as @Stono has indicated Helm triggers the Helm 1131 bug most often when resources are unmanaged by Helm (as was done in 0.8.0 with post install hooks).

Cheers
-steve

**Comment by sdake** [comment]
@costinm error in install in circleci?  From circleci: ```error: unable to recognize "/tmp/istio.e2e.321623740/yaml/istio-auth.yaml": no matches for authentication.istio.io/, Kind=MeshPolicy```

Perhaps crds are not being installed ahead of istio.yaml or there isn't a sufficient wait time?

**Comment by sdake** [comment]
@morvencao can you rebase - circleci was a little sickly during the PR submission time.

**Comment by morvencao** [comment]
@sdake It seems that failed tests are caused by the order of CRD and CR creation, since we use `helm template` instead of `tiller` to generate the manifest files.

**Comment by sdake** [comment]
@morvencao can you rebase this pr?  I think alot has changed in master since it was submitted.  I see 3 post install jobs in use, and they do specific things.  It would be nice to get rid of the post install jobs that install unmanaged helm resources, however, I don't think that is viable.

Cheers
-steve

**Comment by mandarjog** [comment]
The question with this PR is if it will make 1.0.3 to 1.1 upgrade better ?
What would happen to 1.0.2 upgrades to 1.1 will `helm upgrade` work?

@morvencao @sdake we need to make a call on this tomorrow.
I would like to have most / all 1.0.3 PRs in by Thursday.

**Pull request closed without merging**
