### PR TITLE
validate gateway name.

### LINKED ISSUE #22137: Gateway name requirement should be validated
Gateway customizations should require a name. Since previously the GW name was incorrectly always set to a hard coded value, it was possible to omit a name and it would be routed to the default GW name.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.
resolve: https://github.com/istio/istio/issues/22137 and https://github.com/istio/istio/issues/22207

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by morvencao** [comment]
@ostromart PTAL

**Review by elfinhe — COMMENTED** [review]
generally LGTM, but do we have a long term plan for validation?

maybe introducing CUE (https://cue.googlesource.com/cue/), I don't think we can manually validate everything in our API.

**Comment by morvencao** [comment]
Just looking into CUE project, not sure if it can accomplish all our requirements. Currently operator introduce slice and map data type, before that we'll only validate the value of leaf, now we have to validate the item if slice and key of map.

**Review by elfinhe — APPROVED** [review]

**Pull request merged**
