### PR TITLE
Add a wait condition as an attempt to fix #18490

### LINKED ISSUE #18490: New istio.io test, TestBookinfo is flaky
See https://prow.istio.io/view/gcs/istio-prow/logs/integ-istioio-k8s-tests_istio_postsubmit/101 and https://prow.istio.io/view/gcs/istio-prow/logs/integ-istioio-k8s-tests_istio_postsubmit/102 for example failures

### PR DESCRIPTION
**Pull request by fpesce**

### CODE REVIEW

**Comment by fpesce** [comment]
> I was suggesting replacing the command, but more waits never hurt 
> 
> Can we make the test framework include the output of the scripts being run for debugging/logging?

It is already provided in the artifacts, e.g.:
https://gcsweb.k8s.io/gcs/istio-prow/logs/integ-istioio-k8s-tests_istio_postsubmit/101/artifacts/
in https://gcsweb.k8s.io/gcs/istio-prow/logs/integ-istioio-k8s-tests_istio_postsubmit/101/artifacts/examples-fb022d5f57f94f70a605d0/TestBookinfo/

**Comment by howardjohn** [comment]
Thanks! you can see in those logs it doesn't wait for the pods that were
left initializing, so I think the deploymentment wait will fix this

**Comment by howardjohn** [comment]
/retest

https://github.com/istio/istio/issues/18401

**Pull request merged**
