### PR TITLE
Automatically detect ROUTER_MODE

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/33127

### CODE REVIEW

**Review by stevenctl — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
/hold for a while

Just give @costinm @ramaraochavali @mandarjog a chance to take a look, in case this causes some unexpected behavior

**Comment by howardjohn** [comment]
SGTM. The main concern I have is that when we add or remove the AUTO_PASSTHROUGH we add/remove a bunch of clusters.. but that seems fine. Generally its a one time action

**Comment by hzxuzhonghu** [comment]
I thought the time sequence of gateway creation, but could not think of any caveats. 

LGTM

**Review by ramaraochavali — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
unhold

**Pull request merged**
