### PR TITLE
service dashboard add cluster dropdown

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**
part of https://github.com/istio/istio/issues/38525

open to hear more voice

image

image

image

### CODE REVIEW

**Comment by douglas-reid** [comment]
Can you drop a screenshot (or, even better a working sample dash link) that shows the impact of this change?

**Comment by zirain** [comment]
> Can you drop a screenshot (or, even better a working sample dash link) that shows the impact of this change?

update some screenshots

**Comment by douglas-reid** [comment]
Thanks!  Looks good. WDYT about `Workload Cluster` vs. `Service Cluster` ?  My concern is that services can be multi-cluster, and that the `source_cluster` and `destination_cluster` labels are supposed to be pulled from the workload instances.

**Comment by zirain** [comment]
> Thanks! Looks good. WDYT about `Workload Cluster` vs. `Service Cluster` ? My concern is that services can be multi-cluster, and that the `source_cluster` and `destination_cluster` labels are supposed to be pulled from the workload instances.

My thought is very simple, `Cluster` is one of filter to get workload, just like `Namespace` do. for me, it's enough, glad to here others' voice, can you share more about you concern?

**Comment by douglas-reid** [comment]
> My thought is very simple, `Cluster` is one of filter to get workload, just like `Namespace` do. for me, it's enough, glad to here others' voice, can you share more about you concern?

My concern is that `source_cluster` and `destination_cluster` are taken from workload instance attributes, and not from service attributes. If you had a service that was provided by workloads in two different clusters, it _feels_ like it could be confusing to just call the dropdown `Service Cluster`. A display name like `Service Workload Cluster` seems a bit more precise, but is certainly more unwieldy.

**Comment by zirain** [comment]
Metrics are scraped from workload/pods by prometheus. 
In my understanding, `service` (in this dashboard) is endpoint which handle the request, not a k8s service.

**Comment by douglas-reid** [comment]
> Metrics are scraped from workload/pods by prometheus. In my understanding, `service` (in this dashboard) is endpoint which handle the request, not a k8s service.

The `service` is not an endpoint; it is a collection of endpoints (the implementing workloads). That's why there is a dropdown for `Service Workload`.

The other dropdown is `Service Workload Namespace`.  We should either name them both `Service Workload (Namespace|Cluster)` or both `Service (Namespace|Cluster)` to keep it consistent.

**Comment by zirain** [comment]
>  name them both Service Workload (Namespace|Cluster)

this's a good idea

**Comment by zirain** [comment]
ping @douglas-reid

**Review by douglas-reid — APPROVED** [review]

**Comment by zirain** [comment]
ping @istio/wg-environments-maintainers

**Comment by irisdingbj** [comment]
Can you drop an updated screenshot here? Thanks!

**Review by irisdingbj — COMMENTED** [review]
Can you drop an updated screenshot here? Thanks!

**Comment by zirain** [comment]
@irisdingbj updated with new screenshots

**Review by irisdingbj — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
