### PR TITLE
Add flag job to tell this is master to auto-merge

### PR DESCRIPTION
**Pull request by yutongz**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

We need auto-merge only takes effect on master but not release-branches since we are not done migrating. Since mungegithub is not able to tell branches, this test works as a flag, showing this is master and pass check, but not for other branches.

### CODE REVIEW

**Comment by rshriram** [comment]
@geeknoid / @costinm are you guys okay with re enabling the bot? We had discussed disabling the bot now that we don’t have dependency issues. Pr authors can easily merge themselves after tests pass.

**Comment by ldemailly** [comment]
we still, and more than ever as the repo is bigger, need the autorebase and submit and merge queue
that’s one condition to make this work with more developers contending for 1 repo

**Pull request merged**
