### PR TITLE
[Cherry-pick] Merge release-1.1 fixes into master: load-shedding, test enhancements

### PR DESCRIPTION
**Pull request by douglas-reid**
Two PRs:
1. #9146 (Add load-shedding package to Mixer...)
1. #9857 (Reduce prom scrape interval for and address stability of e2e_mixer...)

### CODE REVIEW

**Comment by kyessenov** [comment]
/lgtm

A merge commit would be better, but you are the author of both PRs so up to you.

**Comment by douglas-reid** [comment]
@kyessenov i'm happy to wait for full merge commit. are they regularly scheduled?

**Comment by kyessenov** [comment]
@douglas-reid They are not AFAIK. The difficulty is that it requires a temporary change of github admin settings to allow merge commit. So @hklai or someone, needs to allow merge commits for a few minutes to perform the proper cherry-pick.

**Comment by hklai** [comment]
@rshriram and @costinm do periodic bulk merge from release-1.1 to master.

Can this wait for that?

**Pull request closed without merging**
