### PR TITLE
Cherrypick [1.2]: Send partial update on scale to zero endpoints

### PR DESCRIPTION
**Pull request by howardjohn**
This is a cherrypick of https://github.com/istio/istio/pull/17957 and
https://github.com/istio/istio/pull/16967/files to the release 1.2
branch.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by duderino** [comment]
@fpesce would be great to get this into 1.2.9

**Comment by howardjohn** [comment]
I need to fix the tests, working on it

**Comment by fpesce** [comment]
@howardjohn is it ready to go ?

**Comment by howardjohn** [comment]
Yes

**Pull request merged**
