### PR TITLE
Update branch dependencies

### PR DESCRIPTION
**Pull request by jacob-delgado**
```UPDATE_BRANCH=release-1.7 ./bin/update_deps.sh; make gen```

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by jwendell** [comment]
hmm, this same test failed for the proxy update: https://github.com/istio/istio/pull/28591
let's give it another try

**Review by jwendell — APPROVED** [review]

**Comment by jacob-delgado** [comment]
cc @gargnupur This is related to https://github.com/istio/istio/pull/28500 (and same for 1.6 and I'm imaging 1.8)

I will retest this once changes have pushed into the releases.

**Comment by jwendell** [comment]
@jacob-delgado Do you want to update this PR? Proxy SHA was updated in https://github.com/istio/istio/pull/28767

**Pull request merged**
