### PR TITLE
security/pkg/stsservice/tokenmanager/google: Fix the last connection was not closed when retrying

### PR DESCRIPTION
**Pull request by wzshiming**
Fix the last connection was not closed when retrying

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I am a bit confused by the logic. It seems weird to close the body at the start of the loop and then do a defer as well..

I think it probably works, but its not very clear without a lot of studying. Can we simplify?

**Comment by wzshiming** [comment]
I move the Close to the caller to do it, It looks simple now.

**Comment by wzshiming** [comment]
@howardjohn Could you have time to take a look

**Pull request closed without merging**
