### PR TITLE
Revert "remove feature flags for se selecting pods (#37374)"

### PR DESCRIPTION
**Pull request by GregHanson**
This reverts commit 2ffbf677e1b0bd202dfaa44783494279848fda5e.

**Please provide a description of this PR:**

feature flags `PILOT_ENABLE_SERVICEENTRY_SELECT_PODS` and `PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES` were removed in https://github.com/istio/istio/pull/37374.  `PILOT_ENABLE_SERVICEENTRY_SELECT_PODS` was re-added in https://github.com/istio/istio/pull/37407.  This PR re-adds `PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES`

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ X ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by linsun — APPROVED** [review]
based on today's WG mtg, okay to restore this for now before we come up with a plan to support this officially. Notes:

OK to restore this function for now
Need a design doc to capture user case and have further discussion

@ramaraochavali can you approve?

**Comment by howardjohn** [comment]
Ca nyou make sure you don't depend on other flags as well?

**Comment by GregHanson** [comment]
test for verifying the fix:
```
cat <<\EOF > ./my-config.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: $HUB
  tag: $TAG
  components:
    pilot:
      k8s:
        env:
        - name: PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES
          value: "false"
EOF
istioctl install -f my-config.yaml

# deploy helloworld-v1 inside of mesh and helloworld-v2 outside mesh
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/sleep/sleep.yaml
kubectl apply -f samples/helloworld/helloworld.yaml
kubectl create ns external
kubectl apply -f samples/helloworld/helloworld.yaml -n external
kubectl delete deploy helloworld-v2
kubectl delete deploy helloworld-v1 -n external

# add the v2 version
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: hello-svc
spec:
  address: 10.244.1.6
  labels:
    app: helloworld
    instance-id: vm1
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: hello-svc
spec:
  hosts:
  - gihanson.hello.com
  location: MESH_INTERNAL
  ports:
  - number: 5000
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: helloworld
EOF
```
Performing curls from the sleep pod to `gihanson.hello.com:5000/hello` loadbalances between v1 and v2 versions of the service.  Calling `helloworld.default.svc.cluster.local:5000/hello` goes to only v1 when `PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES=false` and both versions when `PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES=true`

**Review by ramaraochavali — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Review by linsun — APPROVED** [review]

**Comment by ericvn** [comment]
Does this PR need to be cherry-picked to 1.15?

**Comment by GregHanson** [comment]
Should be set to cherry-pick to 1.15 due to comments above.  A 1.14 cherry-pick exists already [here](https://github.com/istio/istio/pull/40712), but I will delete that one if the auto cherrypick created from this PR merges OK

**Pull request merged**
