### PR TITLE
clarified mesh connect timeout fields based on code impl

### PR DESCRIPTION
**Pull request by GregHanson**
resolves https://github.com/istio/istio/issues/11319

- comments in configmap.yaml to clarify difference between mesh.connectTimeout and mesh.defaultConfig.connectTimeout
- added field for mesh.connectTimeout to the configmap to expose to users

### CODE REVIEW

**Comment by GregHanson** [comment]
NOTE: open to suggestions on what the default value should be for `mesh.connectTimeout` in the configmap.  Previously XDS assigned all clusters `1s` since that is what is currently defined in the code: https://github.com/istio/istio/blob/release-1.1/pilot/pkg/model/context.go#L408
Similarly, `mesh.defaultConfig.connectTimeout` is defaulted to `1s` in code, but the value provided in the mesh configmap is default `10s`
@jnativio @mandarjog  possible performance concern?

**Comment by linsun** [comment]
@wenchenglu can we get this low risk item in 1.1 if there is another build?

**Comment by linsun** [comment]
consideration for 1.1 or 1.1.1

cc @duderino

**Comment by GregHanson** [comment]
@wenchenglu can we get this one in?

**Pull request merged**
