### PR TITLE
plug in the external service registry by default to the aggregator

### PR DESCRIPTION
**Pull request by GregHanson**

### CODE REVIEW

**Comment by costinm** [comment]
To clarify: EDS v2 is not currently handling external endpoints, CDS is sending them as static, and this is fine for 0.8. 

Once we do more advanced load reporting/scale -  it will make sense to push External changes via EDS. We are planning to move the 'mesh expansion' to use the externalservice as well.

**Comment by costinm** [comment]
I was thinking about the external services having a list of endpoints and
labels.

Yes, LDS and RDS also need to be generated, you're right, and maybe this
layer of
abstraction is simpler there.

But I still think long term code will be cleaner if each service would use
directly the
ExternalService data and event - as received from the config - instead of
translating it
and going over another layer.

**Comment by xiaolanz** [comment]
Can you use this order:


import (
	"fmt"
	"net"
	"net/http"
	"os"
	"path"
	"strconv"
	"time"

	"code.cloudfoundry.org/copilot"
	"github.com/davecgh/go-spew/spew"
	durpb "github.com/golang/protobuf/ptypes/duration"
	middleware "github.com/grpc-ecosystem/go-grpc-middleware"
	prometheus "github.com/grpc-ecosystem/go-grpc-prometheus"
	multierror "github.com/hashicorp/go-multierror"
	"google.golang.org/grpc"
	meshconfig "istio.io/api/mesh/v1alpha1"
	"istio.io/istio/pilot/cmd"
	configaggregate "istio.io/istio/pilot/pkg/config/aggregate"
	"istio.io/istio/pilot/pkg/config/clusterregistry"
	"istio.io/istio/pilot/pkg/config/kube/crd"
	"istio.io/istio/pilot/pkg/config/kube/ingress"
	"istio.io/istio/pilot/pkg/config/memory"
	configmonitor "istio.io/istio/pilot/pkg/config/monitor"
	"istio.io/istio/pilot/pkg/kube/admit"
	"istio.io/istio/pilot/pkg/model"
	envoy "istio.io/istio/pilot/pkg/proxy/envoy/v1"
	"istio.io/istio/pilot/pkg/proxy/envoy/v1/mock"
	envoyv2 "istio.io/istio/pilot/pkg/proxy/envoy/v2"
	"istio.io/istio/pilot/pkg/serviceregistry"
	"istio.io/istio/pilot/pkg/serviceregistry/aggregate"
	"istio.io/istio/pilot/pkg/serviceregistry/cloudfoundry"
	"istio.io/istio/pilot/pkg/serviceregistry/consul"
	"istio.io/istio/pilot/pkg/serviceregistry/eureka"
	"istio.io/istio/pilot/pkg/serviceregistry/external"
	"istio.io/istio/pilot/pkg/serviceregistry/kube"
	"istio.io/istio/pkg/log"
	"istio.io/istio/pkg/version"
	"k8s.io/api/core/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

**Comment by rshriram** [comment]
cla bot stuck.

**Pull request merged**
