### PR TITLE
Fix updateVersion to function with helm charts

### PR DESCRIPTION
**Pull request by sdake**
**What this PR does / why we need it**:
A regression in updateVersion.sh was spotted

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by sbezverk** [comment]
@sdake good catch +1

**Comment by linsun** [comment]
nice catch!

**Pull request merged**
