### PR TITLE
Run bin/update_deps.sh in preparation for second build for 1.17

### PR DESCRIPTION
**Pull request by johnma14**
**Please provide a description of this PR:**

In preparation for a new build for 1.17 release.

### CODE REVIEW

**Comment by ericvn** [comment]
Did your script run to completion? Did you run it in a shell? I expect there to be more changes.

**Comment by ericvn** [comment]
I believe the `sed` commands fail, and maybe other items, if you try to run this an MacOS terminal.

**Comment by ericvn** [comment]
```
	modified:   docker/Dockerfile.distroless
	modified:   go.mod
	modified:   go.sum
	modified:   istio.deps
	modified:   prow/release-commit.sh
```

**Comment by johnma14** [comment]
I forgot to run the make gen command. Ran it and updated the PR, will see.

**Comment by ericvn** [comment]
You shouldn't need the `make gen` for this. You are still missing a number of files. You should have 5, and only have 2.

**Comment by johnma14** [comment]
Ran it in `make shell` and has 5 files you mentioned. Thanks Eric.

**Comment by ericvn** [comment]
I suspect you should have seen a message about the script falling when run directly in the terminal.

**Review by pmerrison — APPROVED** [review]

**Pull request merged**
