### PR TITLE
Don't allow Destination port selector {}

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/19271

### CODE REVIEW

**Comment by esnible** [comment]
@linsun @rshriram @geeknoid The validation code is in istio/istio's `/pkg` directory, which has no owners.  Thus this needs a top-level approval.

Perhaps we should give /pkg some owners, seeded from the other owners who have commits here.  I wrote a lot of the initial webhook validation but I can't nominate myself as a maintainer for /pkg.

**Comment by howardjohn** [comment]
@esnible this PR is approved already

**Pull request merged**
