### PR TITLE
Always copy envoy binary to avoid a stale dependency.

### PR DESCRIPTION
**Pull request by yusuoh**

### CODE REVIEW

**Comment by mattdelco** [comment]
I think you might be going after the symptom rather than the problem.  The tail end of bin/init.sh only does the copy based on "if [ ! -f ${ISTIO_OUT}/envoy ]".  I'm not sure for the motivation for this but I suppose it's to avoid doing copies when someone runs init.sh a bunch of times.  I'd be for making the copies unconditional (the top-level Makefile already has protection for multiple executions of "make depend" or "make init" [and any direct callers of bin/init.sh should call via make, IMO]), or adjusting this line:

<pre>
- rm -f ${ISTIO_OUT}/envoy ${ROOT}/pilot/pkg/proxy/envoy/envoy
+ rm -f ${ISTIO_OUT}/envoy ${ISTIO_OUT}/bin ${ROOT}/pilot/pkg/proxy/envoy/envoy
</pre>

Though IMO the use of envoy in bin/ should go away.

**Comment by yusuoh** [comment]
@mattdelco You are right. I also noticed that line and wondered why it is not copying binary forcefully. Change the PR as suggested. PTAL

**Comment by mattdelco** [comment]
Thanks for being willing to change the approach.  I think this change will be less controversial if you use the approach of just modifying line ~104 so that ${ISTIO_BIN}/envoy is added to the rm statement, e.g.:

<pre>rm -f ${ISTIO_OUT}/envoy ${ISTIO_BIN}/envoy ${ROOT}/pilot/pkg/proxy/envoy/envoy</pre>

This will help keep the behaviors of ${ISTIO_OUT}/envoy and ${ISTIO_BIN}/envoy consistent and mean that init.sh will only do a copy when it's the 1st execution, or when the commit sha in the DockerFile changes, rather than for every execution of init.sh.

**Comment by yusuoh** [comment]
Sounds good. Done

**Pull request merged**
