### PR TITLE
[pilot] Moving mock discovery to cmd package

### PR DESCRIPTION
**Pull request by nmittler**
Having it in the same directory with pilot/test/mock/config.go was
causing it to bring in the pilot/testing package, which causes the
list of default flags to explode (testing.*).

### CODE REVIEW

**Comment by kyessenov** [comment]
I think the actual issue is that the native "testing" package is imported which causes the flag import. Can you validate that "pilot-discovery -h" has no "test." flags after this change?

**Comment by nmittler** [comment]
> I think the actual issue is that the native "testing" package is imported which causes the flag import. Can you validate that "pilot-discovery -h" has no "test." flags after this change?

@kyessenov yeah you're right ... native "testing", not Istio "testing" was the problem.  And yes, I've already confirmed that this PR fixes the problem.

**Comment by kyessenov** [comment]
Looks fine, although I don't like re-usable pieces placed into `cmd`.

**Comment by costinm** [comment]
Please don't put it in cmd/...

**Comment by nmittler** [comment]
> Looks fine, although I don't like re-usable pieces placed into cmd.
> Please don't put it in cmd/...

@kuat @costinm I don't disagree ... ideally it should be somewhere at the top-level, as should what is currently in `pilot/cmd/pilot-discovery/server'.  For now, keeping them together at least makes them consistent and solves the immediate problem.  The overall package structure of pilot should be addressed separately.

**Pull request merged**
