### PR TITLE
set discoveryAddress to be cluster-local by default (#23625)

### PR DESCRIPTION
**Pull request by stevenctl**
Cherry picking #23625 into release 1.6 to fix shared control plane multicluster

### CODE REVIEW

**Comment by costinm** [comment]
Wait, this is a pretty big change in behavior. 
The original PR claims there are only 2 ways - is there a RFC or decision to drop all other ways ? 

It has impact on scale and failure modes. 

Please don't merge into 1.6 without further discussion - not clear if master will keep this either.

**Comment by jacob-delgado** [comment]
cc @stevenctl @costinm With the code freeze on Wednesday the release managers @brian-avery and @irisdingbj would like some resolution to this. If not this may have to wait until 1.6.1.

**Comment by nmittler** [comment]
@brian-avery would you mind cherry-picking? We've discussed offline and agreed that this is the right change for 1.6. Multicluster with remote clusters is effectively broken without it.

**Comment by linsun** [comment]
I tried test a bit on central istiod, no impact here.  I'm good to cherry pick this in 1.6

**Comment by nmittler** [comment]
@brian-avery also we'll need to add a blurb about this to the upgrade notes. Something like:

This release makes the istiod host cluster-local by default. This means that the Istio control plane is not accessible to workloads that reside outside the cluster. It is now recommended that external workloads access istiod via the ingress gateway. This change was needed in order to support multicluster master/remote configurations. Future releases will remove this limitation.

Users may override this behavior in MeshConfig:

```yaml
values:
  meshConfig:
    serviceSettings: 
      - settings:
          clusterLocal: false
        hosts:
          - "istiod.istio-system.svc.cluster.local"
```

@costinm @smawson look good?

**Pull request merged**
