### PR TITLE
Skip stackdriver vm test in istiodremote topology

### PR DESCRIPTION
**Pull request by frankbu**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
Can we add a bit more context in the description about why it does not work?

**Comment by frankbu** [comment]
> Can we add a bit more context in the description about why it does not work?

@bianpengyuan I think the VM tests could be made to work, but currently the way the echo services are set up, it doesn't work quite right when there are multiple clusters. Rather than fixing the setup, we decided to not run any of the VM pilot or security tests in MC or external control plane. This test is already disabled for MC (`RequireSingleCluster`), but the extra check `RequireLocalControlPlane` is also needed to make sure there's also no external control plane cluster in the test topology.

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
