### PR TITLE
Fix  compatability when `USE_CACERTS_FOR_SELF_SIGNED_CA = true`

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
For  #47650

**Comment by jaellio** [comment]
Could you please clarify the fixes this PR addresses?

We do not make the claim to support a smooth, automatic transition when enabling the cacerts feature flag. See https://github.com/istio/istio/issues/47650#issuecomment-1789753240 for more info.

**Comment by hzxuzhonghu** [comment]
We do need a smooth migration even the flag is turned true one day

**Comment by hzxuzhonghu** [comment]
@istio/wg-security-maintainers

**Comment by jaellio** [comment]
I totally agree we eventually need a smooth migration, but I don't think that is a blocker for v1.20.

**Comment by hzxuzhonghu** [comment]
It is better to ship with the feature flag, otherwise may cause compatibility when user enabled the feature flag

**Comment by jaellio** [comment]
@costinm curious about your thoughts on this change

I explicitly removed this logic when I created the feature flag for `cacerts` to simplify the changes. I am concerned about adding these changes right before release unless they fix a bug when the feature flag is disabled. If we add the migration logic for the next release (v1.21) I don't believe this will cause any compatability issues. I believe you can just enable the flag for specific control plane versions.

**Comment by hzxuzhonghu** [comment]
It will cause issue if in 1.20, one turns on the flag, but then after a upgrade or downgrade, he turns down the flag, see the issue https://github.com/istio/istio/issues/47650

**Comment by hzxuzhonghu** [comment]
It is not a risky patch, it is fixing some issues, Keep in mind this is also protected with the feature flag. Nothing else different with the previous code

**Comment by hzxuzhonghu** [comment]
Any other could take it over

**Comment by jaellio** [comment]
> It will cause issue if in 1.20, one turns on the flag, but then after a upgrade or downgrade, he turns down the flag, see the issue #47650

I don't think a feature flag is required to support compatibility after it is disabled. Enabling a feature flag moves you into an experimental/unsupported status. I don't think it is a requirement for v1.20 to support enabling and then disabling the feature flag. the user is knowingly enabling an experimental feature.

**Pull request closed without merging**
