### PR TITLE
added mapping for envoy statsd to prometheus

### PR DESCRIPTION
**Pull request by nmnellis**
#3984 #4854

### CODE REVIEW

**Comment by ijsnellf** [comment]
@douglas-reid ^^^

**Comment by douglas-reid** [comment]
@nmnellis list of changes needed in dashboards:

```
Expected a metric value for 'rate(envoy_cluster_mixer_check_server_upstream_rq_total[1m])', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'rate(envoy_cluster_mixer_report_server_upstream_rq_total[1m])', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_check_server_upstream_rq_time', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_report_server_upstream_rq_time', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_check_server_upstream_cx_active', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_report_server_upstream_cx_active', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_check_server_membership_healthy', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_check_server_membership_total', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_report_server_membership_healthy', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'envoy_cluster_mixer_report_server_membership_total', found no samples: model.Vector{}
```

```
dashboard_test.go:131: Expected a metric value for 'sum(envoy_cluster_rds_upstream_rq_time) by (quantile)', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_cluster_manager_cds_update_attempt[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_cluster_manager_cds_update_success[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_listener_manager_lds_update_attempt[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_listener_manager_lds_update_success[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_cluster_rds_update_attempt[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_cluster_rds_update_success[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(irate(envoy_cluster_rds_update_attempt[1m])) - sum(irate(envoy_cluster_rds_update_success[1m]))', found no samples: model.Vector{}
dashboard_test.go:131: Expected a metric value for 'sum(envoy_cluster_rds_upstream_cx_active)', found no samples: model.Vector{}
```

**Comment by kyessenov** [comment]
How did this pass dashboard test @douglas-reid ?

**Pull request closed without merging**
