### PR TITLE
use errors.Is to check for a specific error

### PR DESCRIPTION
**Pull request by my-git9**
**Please provide a description of this PR:**
Comparing with` == `will fail on wrapped errors. Use errors.Is to check for a specific error is better.

### CODE REVIEW

**Comment by kfaseela** [comment]
tests are fixed by https://github.com/istio/istio/pull/43461

**Review by howardjohn — CHANGES_REQUESTED** [review]
How are you sure we WANT to check for wrapped errors?

This feels wrong, IMO. We are making some assumptions that the old code is "wrong" without any (presented) evidence, which introduces risk. This is a risky refactor with no documented benefits

**Comment by my-git9** [comment]
> How are you sure we WANT to check for wrapped errors?
> 
> This feels wrong, IMO. We are making some assumptions that the old code is "wrong" without any (presented) evidence, which introduces risk. This is a risky refactor with no documented benefits

Understood, thank you

**Pull request closed without merging**
