### PR TITLE
Add serviceCluster to pilot-agent flag

### PR DESCRIPTION
**Pull request by kebe7jun**
Fix https://github.com/istio/istio/issues/33635

[X] Installation

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by howardjohn** [comment]
@kyessenov IIRC you made some changes here recently?

**Review by adiprerepa — COMMENTED** [review]
lgtm but yielding

**Comment by howardjohn** [comment]
This is reverting https://github.com/istio/istio/pull/32826 more or less I think, so adding @kyessenov as approver

**Comment by kyessenov** [comment]
/approve
It's not reverting, the referenced PR is focused on k8s while this is for VMs. There is no injection template for VMs so it's fine to do whatever.

**Comment by howardjohn** [comment]
Where is sidecar getting service cluster? If its proxy config, then that is also available for VMs. It feels a bit off to use flag for VM and not for sidecar, especially since the flag is marked as deprecated

**Pull request closed without merging**
