### PR TITLE
istio-agent/health: reuse the HTTP client of prober

### PR DESCRIPTION
**Pull request by panjf2000**
Reuse the HTTP client for each prober to benefit from cached TCP connections inside the `http.Transport`.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Can you verify if kubelet does this? It actually may impact the user, as their app may behave different if we reuse connections or not

**Comment by panjf2000** [comment]
> Can you verify if kubelet does this? It actually may impact the user, as their app may behave different if we reuse connections or not

I just went through the source code of k8s prober and it turns out the HTTP prober in k8s also reuse the HTTP client for the same purpose, see [here](https://github.com/kubernetes/kubernetes/blob/v1.19.4/pkg/probe/http/http.go#L50-L79).

Besides, I don't think reusing connections would pollute the HTTP data as the `persistConn` in Go `net/http` won't store any user-related state info, only the TCP connection which is idle.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
