### PR TITLE
Add revision logic from install to upgrade command

### PR DESCRIPTION
**Pull request by cnvergence**
**Please provide a description of this PR:**
Fixes the issue https://github.com/istio/istio/issues/37908, logic from https://github.com/istio/istio/pull/33773 should be also included in the upgrade command.

### CODE REVIEW

**Review by litong01 — APPROVED** [review]
I pulled it down and built and tested, worked as expected. Thanks very much for your contributions.

**Review by litong01 — APPROVED** [review]

**Comment by cnvergence** [comment]
Thanks @dgn, I have added the release notes

**Review by dgn — APPROVED** [review]

**Pull request merged**
