### PR TITLE
Use ServiceMeta to convey the protocol and other service properties

### LINKED ISSUE #9653: ServiceMeta should be used instead of NodeMeta for Consul registry
**Describe the bug**
Currently, Consul registry is using NodeMeta to convey the service protocol, which is not appropriate in my opinion. 

Protocol is a property of the service itself, so it should not be bound to the node on which the service is located.  This assumes all the services reside on the same node must expose endpoints with the same single protocol, which is obviously not true in most cases.

https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/consul/conversion.go

**Expected behavior**
Use ServiceMeta instead of NodeMeta to convey the protocol and other service properties.

ServiceMeta has been supported by Consul at this commit: https://github.com/hashicorp/consul/commit/80dde5465b0d3b002b15703be6e378279fac6a4c#diff-163a936a979ac3cd7afdf129ac40c944

**Steps to reproduce the bug**
When Istio work with Consul, we just can't register multiple services of different protocols in the same node.

**Version**
1.0.0
the latest master branch has the same issue.

**Installation**
Consul

**Environment**
Ubuntu 16.04

**Cluster state**
Not running on kubernetes.

### PR DESCRIPTION
**Pull request by zhaohuabing**
Protocol is a property of the service itself, so it should not be bound
to the node on which the service is located. This assumes all the services
reside on the same node must expose endpoints with the same single protocol,
which is obviously not true in most cases. Instead, we should use Service Meta to 
convey protocol and other service properties.

Fixes #9653

Signed-off-by: Huabing Zhao <zhaohuabing@gmail.com>

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@rshriram Thanks for the review.
Lots of tests failed, but it seems that they're not related to this change. 
Is there anything else I need to do to merge this PR?

**Comment by zhaohuabing** [comment]
> @zhaohuabing: The following test **failed**, say `/retest` to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> prow/istio-integ-k8s-tests.sh	[aa6aa71](https://github.com/istio/istio/commit/aa6aa71426f2208d3709e2c2ca244ab38d0cb943)	[link](https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/9713/istio-integ-k8s-tests/359)	`/test istio-integ-k8s-tests`

@rshriram Should I look into this test?  It seems not related to my PR.

**Comment by rshriram** [comment]
ignore that please.. only look at required tests

**Comment by zhaohuabing** [comment]
@rshriram
This required test failed: ci/circleci: e2e-simple — Your tests failed on CircleCI

details:
Error: Looks like "https://raw.githubusercontent.com/istio/istio.io/master/static/charts" is not a valid chart repository or cannot be reached: Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/index.yaml : 404 Not Found

It seems not relevant to this PR, could you please help me on how to solve it?

Thanks

**Pull request merged**
