### PR TITLE
update convert interface to float64 function

### PR DESCRIPTION
**Pull request by realgeorgewu**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ x] Developer Infrastructure

consider more type of converting interface to float64 function

### CODE REVIEW

**Comment by zehuaiWANG** [comment]
please sign your cla

**Comment by realgeorgewu** [comment]
@googlebot I signed it!

**Comment by zehuaiWANG** [comment]
@bianpengyuan hi~ from [https://github.com/istio/api/blob/cc9d61a1c5dfb95d5b5b64f57fba58aa40f067a5/policy/v1beta1/value_type.proto#L25](https://github.com/istio/api/blob/cc9d61a1c5dfb95d5b5b64f57fba58aa40f067a5/policy/v1beta1/value_type.proto#L25)
`ValueType describes the types that values in the Istio system can take.`  I think getnumericvalue function can be a more general method. Adding more case types can make the extension of ValueType no problem later. Of course, duration type should be added back.

**Comment by bianpengyuan** [comment]
It is unlikely that new attributes or new value types are going to be added. Mixer is in maintenance mode. We are avoiding changes to it, only bug fixes are wanted. So let's make this change when it turns out to be really necessary?

**Comment by zehuaiWANG** [comment]
Okay, I agree with you, @bianpengyuan. @realgeorgewu , please close this pr if you have nothing else to add.

**Comment by bianpengyuan** [comment]
Thanks!

**Pull request closed without merging**
