### PR TITLE
Fix current ShellCheck violations

### PR DESCRIPTION
**Pull request by Tahler**
#7886 Re-enabled ShellCheck as an optional job, but in a currently failing state. This PR fixes the current violations and puts it in a passing state.

/cc @mandarjog @gargnupur

### CODE REVIEW

**Comment by Tahler** [comment]
/hold

Going to layer on these commits to bisect the issue.

**Comment by mandarjog** [comment]
@tahler can you ensure that codegen script produces no diffs when run with same proto files and diffs when proto filed change?

I am not confident that tets are guaranteeing that scripts are functionally identical.

**Pull request merged**
