### PR TITLE
iptables inbound capture port: cli flag and always enable

### PR DESCRIPTION
**Pull request by rshriram**
Currently, the inbound capture port is derived from an obscure undocumented environment variable 
that end users have no idea how to enable/use. This PR adds an explicit
[documented] cli switch that allows users to specify the inbound capture port.

In addition, this PR also always enables two separate ports for traffic capture (outbound on 15001 and inbound on 15006) instead of leaving it as an easter egg hunt for the end user to enable. Note that this
will not cause any backward compatibility issues as this flag is optional. Even if this flag was not supplied, older sidecars with newer pilot will work smoothly because all traffic will continue to go into the existing virtual listener and be forwarded into the appropriate physical listener.

Signed-off-by: Shriram Rajagopalan <rshriram@tetrate.io>

### CODE REVIEW

**Comment by rshriram** [comment]
this should go in after #15585

**Comment by rshriram** [comment]
@silentdai this enables inbound always in iptables

**Comment by howardjohn** [comment]
/assign @silentdai 

lgtm but haven't been keeping up too much with the work here

**Comment by silentdai** [comment]
@rshriram  Did you split #15585? I am pretty sure some pieces I have seen in #15585

**Comment by silentdai** [comment]
/lgtm
Thanks!

**Pull request merged**
