### PR TITLE
add additional logging for termination drain logic

### PR DESCRIPTION
**Pull request by ramaraochavali**
Minor log additions
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
LGTM. One question:  we only drain inbound listeners for sidecar, if there is connection pool for outbound without idle timeout, it should never becomes 0.

**Comment by ramaraochavali** [comment]
> One question: we only drain inbound listeners for sidecar, if there is connection pool for outbound without idle timeout, it should never becomes 0.

Yes.

**Pull request merged**
