### PR TITLE
[vendor-change, istio-api] update the istio/api sha

### PR DESCRIPTION
**Pull request by yangminzhu**
istio/vendor istio/vendor-istio#60

### CODE REVIEW

**Comment by yangminzhu** [comment]
It seems the build error `pilot/pkg/model/validation.go:1985:17: cannot convert nil to type uint32` is caused by this commit https://github.com/istio/api/commit/6236f62006b304f999e4647cc302eaa575d852d3 by this line of change: https://github.com/istio/api/commit/6236f62006b304f999e4647cc302eaa575d852d3#diff-0820bb0406265ba9b9a9e11dcec06601R496.

@rshriram Could you take a look at this? Thanks!

**Comment by rshriram** [comment]
How do I fix without the vendor update? I need the vendor sha update to fix this in istio/istio

**Comment by sbezverk** [comment]
@yangminzhu why not to switch to a pointer, in this case validating against nil makes perfect sense.

```
type HTTPMatchRequest struct {
...
Port *uint32
... 
```

**Comment by sbezverk** [comment]
@yangminzhu We just need to change it in protobuf and describe it as optional.

An 'optional' protobuf field is expressed as a pointer field in Go. Encode() will transmit the field only if the pointer is non-nil. Decode() will instantiate the pointed-to type and fill in the pointer if the field is present in the message being decoded, leaving the pointer unmodified (usually nil) if the field is not present.

```
message HTTPMatchRequest {
...
optional uint32 port = 6;
...
}
```

**Comment by sbezverk** [comment]
@yangminzhu Just realized it is proto3.  Since protobuf guarantees this value will always be set if m.GetPort() method is used, then validation should check application related limits. Example that the port values are from 0 to 65545 and not some large number since it is uint32.

**Comment by ldemailly** [comment]
this doesn't seem to build ?
can you make the code changes to match ?

**Comment by yangminzhu** [comment]
@ldemailly Please see the comments above in the PR, I was discussing with @rshriram to try to figure out a fix, I originally thought we might be able to fix it with a single line change but it now turns out it's not that simple. 
We do have a incompatible change in the API repo, though it's on v1alpha3 but it break the build of Istio. We have to solve this otherwise all other changes in the API repo will be blocked by this.

The Port field is used in multiple places, and the code is using the old PortSelector struct to do some match stuff:
https://github.com/istio/istio/blob/6f673115ed0cfc7479985b20bcbc34ebfc461e21/pilot/pkg/model/validation.go#L1985
https://github.com/istio/istio/blob/71c016568f78407b2aa5dd8f110d1d35cba31413/pilot/pkg/networking/core/v1alpha3/gateway.go#L311
https://github.com/istio/istio/blob/71c016568f78407b2aa5dd8f110d1d35cba31413/pilot/pkg/networking/core/v1alpha3/route/route.go#L263 

@rshriram, If we still want to fix this in this PR, we have to do 2 things:
1) Instead of using the `Port != nil` to check if the Port is set, we have to change to use `Port > 0` to check if it's being set  or not;
2) Drop the support of matching by port name (see the 3rd code snippet above) due to the new API changed the Port field to unint32 which we have no ways to specify the port name;

Otherwise we'll have to revert that API change.

**Comment by yangminzhu** [comment]
@ldemailly has another PR to update this to a previous commit in istio.io/api repot (#4987), so I'll close this for now.

**Comment by rshriram** [comment]
will fix tomorrow.. There is no other change in istio/api after this commit. So, nothing is lost.

**Pull request closed without merging**
