### PR TITLE
Inject: Encode labels as json similar to annotations

### LINKED ISSUE #9605: Sidecar injection not working with 1.0.3
**Describe the bug**
Sidecar injection does not work with 1.0.3 when the pods have labels with '/' inside name (for exemple, "app.kubernetes.io/name" or "app.kubernetes.io/version").
The error is : 
```
Error creating: Pod "default-apigateway-5756bb6557-64csm" is invalid: [spec.containers[2].env[7].name: Invalid value: "ISTIO_META_app.kubernetes.io/instance": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.containers[2].env[8].name: Invalid value: "ISTIO_META_app.kubernetes.io/name": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.containers[2].env[9].name: Invalid value: "ISTIO_META_app.kubernetes.io/version": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')] 
```

Note that this error appears after moving from istio 1.0.2 to istio 1.0.3.

**Steps to reproduce the bug**
Deploy a pod with standard label (see https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

**Version**
```
$ istioctl version
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Istio has been deployed with helm

### PR DESCRIPTION
**Pull request by mandarjog**
Fixes #9605

### CODE REVIEW

**Comment by jmazzitelli** [comment]
> /test e2e-mixer-no_auth

@mandarjog see https://github.com/istio/istio/issues/9635 - all PRs are blocked until this test is fixed.

**Comment by douglas-reid** [comment]
@mandarjog as part of this PR, can you use the change from https://github.com/istio/istio/pull/9637 (which I hope will fix this issue)? that would save a cherry-pick.

**Comment by mandarjog** [comment]
If pod labels change
1. In a subsequent PR, we can update metadata / restart envoy if bootstrap changes
2. Pilot can access all this metadata based on endpoint registry information it already has.
3. Label change on deployment.spec will redeploy the pod.

**Comment by mandarjog** [comment]
env vars that are explicitly passed in as ISTIO_META_xx will continue to work. Since they are passed in explicitly the user is in control, so did not need to modify bootstrap.go.

**Comment by tcnghia** [comment]
Thanks for fixing @mandarjog

**Pull request merged**
