### PR TITLE
update proxy sha to latest

### PR DESCRIPTION
**Pull request by GregHanson**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]

**Comment by bianpengyuan** [comment]
Why this PR is not merging..

**Comment by GregHanson** [comment]
@bianpengyuan in the `tide` link it shows https://github.com/istio/istio/pull/28366 in front of this one (and tests are still running for it)

**Comment by bianpengyuan** [comment]
@GregHanson Ok, thanks! Not sure why tide was not showing that when I checked. It seems a bit slower than normal merging, not sure if it is because of the flake.

**Comment by GregHanson** [comment]
Automator beat us to it:
https://github.com/istio/istio/pull/28358

**Pull request closed without merging**
