### PR TITLE
uninject missing volumes for remove-from-mesh.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.
resolve: https://github.com/istio/istio/issues/25877

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by shamsher31** [comment]
Similar PR https://github.com/istio/istio/pull/25879 but without test.

**Comment by tanjunchen** [comment]
@shamsher31 
Use this pr to modify issue.
@morvencao 
Thanks for your job!

**Comment by morvencao** [comment]
> This makes sense.
> 
> There is another small PR, one of mine, to deal with users who try to use `remove-from-mesh` against pods in `istio-system`. Would it make sense to combine with that PR?

which PR do you mean?

**Comment by esnible** [comment]
> which PR do you mean? @esnible

This one: https://github.com/istio/istio/pull/25887

**Review by tanjunchen — COMMENTED** [review]
any updates?

**Review by tanjunchen — COMMENTED** [review]
It seems that these modifications have been implemented now .

**Comment by morvencao** [comment]
Closing this as it was fixed in https://github.com/istio/istio/pull/26782

**Pull request closed without merging**
