### PR TITLE
authz: add e2e tests for workload selector

### PR DESCRIPTION
**Pull request by yangminzhu**
Please provide a description for what this PR is for.

Add e2e tests for the workload selector in authorization policy.

For #12394 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by liminw — COMMENTED** [review]
Looks good to me. Can we also add tests for root namespace?

**Comment by yangminzhu** [comment]
> Looks good to me. Can we also add tests for root namespace?

Added, PTAL.

**Review by liminw — APPROVED** [review]
/lgtm

**Comment by yangminzhu** [comment]
@istio/wg-environments-maintainers Could anyone from the environments group review this PR? thanks.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
