### PR TITLE
Partial revert of #53348 to fix race

### PR DESCRIPTION
**Pull request by howardjohn**
example https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52985/unit-tests_istio/1840809938268459008

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
I looked at that exact change and went `hmm` and almost left a comment, but figured since it was only a readlock it would probably be OK. 

TY!

**Review by keithmattix — APPROVED** [review]

**Comment by wulianglongrd** [comment]
Sorry, thanks for reviewing and fixing this.

**Comment by wulianglongrd** [comment]
There's one thing I find strange: Why didn't the race test panic when I submitted that PR? Shouldn't it always occur?

**Comment by howardjohn** [comment]
I think even with the race detector it will not always find the race since
it's timing dependant

**Review by ramaraochavali — APPROVED** [review]

**Comment by ramaraochavali** [comment]
> I looked at that exact change and went hmm and almost left a comment, but figured since it was only a readlock it would probably be OK.

Same here :-)

**Pull request merged**
