### PR TITLE
Don't call DumpResponse when res is nil

### PR DESCRIPTION
**Pull request by holgero**
Instead end the test after the first error

### CODE REVIEW

**Comment by costinm** [comment]
Please move to release 0.8

**Comment by holgero** [comment]
Should I create a new pull request based on release-0.8 or should I recycle this one?

**Comment by holgero** [comment]
I may have confused the bots by changing the base of the commit... Should I rather close this PR and create a fresh one?

**Comment by costinm** [comment]
Close and reopen usually does the trick.

**Pull request merged**
