### PR TITLE
Fix ingress test

### PR DESCRIPTION
**Pull request by zerobfd**
Right now running unit tests causes a change to the repo, it seems like
the golden file was updated in 997c137d68ef0907eebc51d295d3eff2929d1545
but this file wasn't. This prevents `go test` from changing the repo and
diffing the yaml with the .golden version shows no changes.

### CODE REVIEW

**Comment by zerobfd** [comment]
I believe the test is to 1) mutate the file and 2) check it against the "golden" file. When the test changes the file it's the right content, but it's not what's checked in.

TBH I'm not sure why they didn't just remove the file after checking it, but I'm assuming the original author had a reason for checking in both yaml files so I'm just blindly fixing the yaml.

**Comment by therealmitchconnors** [comment]
LGTM

**Pull request merged**
