### PR TITLE
enable custom proxy template file

### PR DESCRIPTION
**Pull request by kidiyoor**
wrt https://github.com/istio/istio/issues/3745 
ref: https://github.com/istio/api/pull/387

enable custom path to template file.

### CODE REVIEW

**Comment by mandarjog** [comment]
Can you not use `--custom_config_file`

**Comment by kidiyoor** [comment]
@costinm I am not sure kube-inject is involved ?

I tested it in VMs(running pilot-agent, envoy in VM). It works fine. I have raised PR for changing 'config proto' in api repo.

**Comment by kidiyoor** [comment]
Yes! You are right - this won't work for k8s since mesh file is not directly read by pilot-agent. The mesh configuration is parsed during kube-inject and passed to `istio-proxy` container as `args:` 

I'll add a cmd line parameter for `proxyBootstrapTemplatePath` in pilot-agent.

**Comment by kidiyoor** [comment]
Arguably it can be made ENV variable too. I prefer it to be cmd parameter since we already have customConfigFile, configPath, binaryPath as cmd line parameters.

**Comment by costinm** [comment]
Please fix the failures - or close the PR if no longer needed.

**Comment by kidiyoor** [comment]
closing this PR. I shall get back to this when it is required.

**Pull request closed without merging**
