### PR TITLE
Remove redundant VirtualService from helm char test.

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @costinm

### CODE REVIEW

**Comment by costinm** [comment]
Why ? 

I exposed it so it's easy to get debug info from pilot ( i.e. don't need to do all kubectl port forward or worry about current IP ) - using the DNS name is much easier.

**Comment by costinm** [comment]
Ah, got it.

/lgtm
/approve

**Comment by rshriram** [comment]
mixer failure is flake..

**Pull request merged**
