### PR TITLE
Update proxy sha to include mixerless telemetry fixes

### PR DESCRIPTION
**Pull request by mandarjog**

### CODE REVIEW

**Review by rshriram — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
@mandarjog @bianpengyuan stats filter test is failing: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17925/integ-telemetry-k8s-tests_istio/2329

**Review by bianpengyuan — APPROVED** [review]
/lgtm

**Review by howardjohn — COMMENTED** [review]
testgateway looks broken

**Comment by bianpengyuan** [comment]
TestGateway is failing because of behavior change introduced by https://github.com/istio/proxy/pull/2462, which makes gateway ignore forwarded attributes. The current test logic verifies that gateway respects forwarded attribute, we should just update it to verify the opposite:
https://github.com/istio/istio/blob/a2d3ed38343b4fa8183669969ef19c25a9b93788/mixer/test/client/gateway/gateway_test.go#L225-L227

**Comment by mandarjog** [comment]
@yangminzhu is this a flake?
```
=== RUN   TestJwtPubKeyEvictionForNotUsed
2019-10-17T12:04:59.629999Z	info	Successfully serving on http://localhost:41107
2019-10-17T12:04:59.794234Z	info	model	Removed cached JWT public key (lastRefreshed: 2019-10-17 12:04:59.630100402 +0000 UTC m=+2.935219143, lastUsed: 2019-10-17 12:04:59.630100402 +0000 UTC m=+2.935219143) from "http://localhost:41107/oauth2/v3/certs"
--- FAIL: TestJwtPubKeyEvictionForNotUsed (20.47s)
```

**Comment by douglas-reid** [comment]
> TestGateway is failing because of behavior change introduced by [istio/proxy#2462](https://github.com/istio/proxy/pull/2462), which makes gateway ignore forwarded attributes. The current test logic verifies that gateway respects forwarded attribute, we should just update it to verify the opposite.

@bianpengyuan if no one owns this yet, I will do it.

**Comment by douglas-reid** [comment]
> > TestGateway is failing because of behavior change introduced by [istio/proxy#2462](https://github.com/istio/proxy/pull/2462), which makes gateway ignore forwarded attributes. The current test logic verifies that gateway respects forwarded attribute, we should just update it to verify the opposite.
> 
> @bianpengyuan if no one owns this yet, I will do it.

Nevermind. that's what you get for not finishing reading your email chain.

**Pull request merged**
