### PR TITLE
add helm value for custom bootstrap

### PR DESCRIPTION
**Pull request by ramaraochavali**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@howardjohn as discusse din #16929 , this PR adds helm value for custom bootstrap. PTAL.

**Review by costinm — COMMENTED** [review]
I am not sure having a global bootstrap file makes sense. That would mean this config map will need to exist in each namespace, or things will break. There is no mechanism in place to make it work. 
So at least it should be able to detect if the file exists, and fallback to the bootstrap ( in pilot-agent ).

I think the usability is pretty bad, we already have too many configs and this is a global. 

How about:
- add a config with a 'well known' name ( say istio.config or istio ). We can add complicated ways to override this, but users should be able to do it the easy way and just use the default name.
- add a mount for istio.config, with optional=true 
- add code to pilot-agent to detect if a bootstrap override is present.

The UX will be: 
- no values.yaml changes or extra options, user will not need to redeploy
- if user wants to override, will create/update a configmap with a well-known name 
- namespaces that don't need custom bootstrap will not use them
- if user wants to customize the bootstrap per pod - the annotation we have will continue to work.

On the extra config map: 
We already have the 'userVolumes' annotation, we can add a similar 'global' setting, I don't think we need to have one setting for each feature. A 'default' plus userVolumes should cover all needs without complicating the installer further.

**Comment by costinm** [comment]
Also: please make the equivalent changes to new installer, and it would be best if they are first approved/merged/tested into new installer before backporting to old installer.

**Comment by ramaraochavali** [comment]
@costinm Thanks. Looks like this needs a broader discussion on UX on how to make this more usable. I am going to close this PR for now.

**Comment by ramaraochavali** [comment]
@costinm I do like the idea of well known config name - but tying that to namespace seems too restrictive to apply at a global mesh level, I am trying to think what could be alternative? Ideally we would like entire mesh have same config except few outliers who can override. Will give a thought and comeback.

**Pull request closed without merging**
