### PR TITLE
remove unuse file

### PR DESCRIPTION
**Pull request by rokkiter**
**Please provide a description of this PR:**

the files is unuse, Because this pr removes the using these two files
https://github.com/istio/istio/pull/37871  file path: pkg/test/envoy/setup.go

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
seems not (entirely) unused

**Comment by rokkiter** [comment]
i find pkg/istio-agent/agent_test.go use env.httpGet, bug i think, it can be replaced by http.DoHTTPGet

**Review by howardjohn — APPROVED** [review]
thanks

**Review by ericvn — APPROVED** [review]

**Pull request merged**
