### PR TITLE
Add viper config processing to all Istio cobra commands.

### PR DESCRIPTION
**Pull request by therealmitchconnors**
This PR executes the design approved here: https://docs.google.com/document/d/1M-qqBMNbhbAxl3S_8qQfaeOLAiRqSBpSgfWebFBRuu8/edit.

### CODE REVIEW

**Comment by howardjohn** [comment]
What is the status of this? Seems there are lots of test fialures

**Comment by ozevren** [comment]
Any updates? There seems to be both conflicts and failures.

**Comment by esnible** [comment]
I see files in the `vendor` directory, but we are now using Go Modules.

Can you write add a test that incorporates Viper?  Something as simple as taking the _istioctl/cmd/version_test.go_ mock version tests but using config files or environment variables for the test cases instead of command-line arguments?

**Comment by howardjohn** [comment]
feel free to reopen once conflicts resolved

**Pull request closed without merging**
