### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by zhaoyuguang**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by fisherxu** [comment]
@zhaoyuguang Thanks for contribution :) need to sign the cla first.

**Comment by zhaoyuguang** [comment]
I signed it!

**Pull request merged**
