### PR TITLE
Fix a bad call inside bazel_to_go.py

### PR DESCRIPTION
**Pull request by guptasu**
**What this PR does / why we need it**:
we no longer need read() on just a plain string. This was caused because of a bad change in change
https://github.com/istio/istio/commit/d075c930abff0e7a96ecc7dd4f1958e8e02cfa60

This bug was causing ./bin/bazel_to_go.py to not work.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by yutongz** [comment]
In a good chance the presubmit won't work, maybe we can force it?

**Comment by guptasu** [comment]
Can someone please force this change ?

**Pull request merged**
