### PR TITLE
Allow unknown fields in the old-ver IstioOperator during istioctl upgrade

### LINKED ISSUE #26475: In place upgrade doesn't work
I used 1.6.x's `istioctl install` to install istio.

Then 1.7.0 rc's istioctl to do in place upgrade but failed due to old citadel field:
```
$ istioctl upgrade                                   
Control Plane - ingressgateway pod - istio-ingressgateway-74d4d8d459-g67zg - version: 1.6.1
Control Plane - pilot pod - istiod-5c99cfc846-nl7rl - version: 1.6.1
2020-08-13T20:22:15.427471Z	warn	found 4 CRD of unsupported v1alpha1 security policy: [clusterrbacconfigs.rbac.istio.io rbacconfigs.rbac.istio.io servicerolebindings.rbac.istio.io serviceroles.rbac.istio.io]. The v1alpha1 security policy is no longer supported starting 1.6. It's strongly recommended to delete the CRD of the v1alpha1 security policy to avoid applying any of the v1alpha1 security policy in the unsupported version
Upgrade version check passed: 1.6.1 -> 1.7.0.
2020-08-13T20:22:21.519984Z	info	Error: failed to generate Istio configs from file [] for the current version: 1.6.1, error: could not unmarshal merged YAML: unknown field "citadel" in v1alpha1.IstioComponentSetSpec
YAML:
addonComponents:
  grafana:
    enabled: false
    k8s:
      replicaCount: 1
  istiocoredns:
    enabled: false
  kiali:
    enabled: false
    k8s:
      replicaCount: 1
  prometheus:
    enabled: true
    k8s:
      replicaCount: 1
  tracing:
    enabled: false
components:
  base:
    enabled: true
  citadel:
    enabled: false
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by elfinhe**
Fix: #26475

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by elfinhe** [comment]
Below is the output:

```
$ istioctldev upgrade --set tag=1.7.0-rc.1 --set hub=docker.io/istio
Control Plane - ingressgateway pod - istio-ingressgateway-f9c86f54c-jfhrh - version: 1.6.5
Control Plane - pilot pod - istiod-7697c784c4-s48c6 - version: 1.6.5

2020-08-14T04:11:21.224503Z	warn	found 4 CRD of unsupported v1alpha1 security policy: [clusterrbacconfigs.rbac.istio.io rbacconfigs.rbac.istio.io servicerolebindings.rbac.istio.io serviceroles.rbac.istio.io]. The v1alpha1 security policy is no longer supported starting 1.6. It's strongly recommended to delete the CRD of the v1alpha1 security policy to avoid applying any of the v1alpha1 security policy in the unsupported version
Upgrade version check passed: 1.6.5 -> 1.7.0.

Upgrade check: Warning!!! The following IOPS will be changed as part of upgrade. Please double check they are correct:
addonComponents:
  grafana: map[enabled:false k8s:map[replicaCount:1]] ->
  kiali: map[enabled:false k8s:map[replicaCount:1]] ->
  prometheus: map[enabled:true k8s:map[replicaCount:1]] ->
  tracing: map[enabled:false] ->
components:
  egressGateways:
    '[#0]':
      k8s:
        service:
          ports:
            '[#0]':
              targetPort: -> 8080
            '[#1]':
              targetPort: -> 8443
installPackagePath: /tmp/istio-install-packages/istio-1.6.5/manifests ->
meshConfig:
  enablePrometheusMerge: false -> true
values:
  base:
    enableCRDTemplates: -> false
  gateways:
    istio-ingressgateway:
      meshExpansionPorts:
        '[0->?]': map[name:tcp-pilot-grpc-tls port:15011 targetPort:15011] ->
        '[2->?]': map[name:tcp-citadel-grpc-tls port:8060 targetPort:8060] ->
  global:
    istiod:
      enabled: true ->
    proxy:
      envoyStatsd: map[enabled:false host:<nil> port:<nil>] ->
    proxy_init:
      resources:
        limits:
          cpu: 100m -> 2000m
          memory: 50Mi -> 1024Mi
  grafana:
    image:
      tag: 6.7.4 -> 7.0.5
  kiali:
    tag: v1.18 -> v1.22
  prometheus:
    tag: v2.15.1 -> v2.19.2
  telemetry:
    v2:
      metadataExchange:
        wasmEnabled: -> false
      prometheus:
        wasmEnabled: -> false
  tracing:
    jaeger:
      tag: 1.16 -> 1.18

Confirm to proceed [y/N]? y
2020-08-14T04:11:28.648111Z	info	proto: tag has too few fields: "-"
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                                                                                                                                                                                                           ..........
Control Plane - ingressgateway pod - istio-ingressgateway-f9c86f54c-jfhrh - version: 1.6.5 does not match the target version 1.7.0
..........
Upgrade rollout completed. All Istio control plane pods are running on the target version.


Control Plane - ingressgateway pod - istio-ingressgateway-56f4746747-4pgb2 - version: 1.7.0
Control Plane - ingressgateway pod - istio-ingressgateway-56f4746747-hnhdq - version: 1.7.0
Control Plane - pilot pod - istiod-ddffdc7d7-jt9lx - version: 1.7.0

Success. Now the Istio control plane is running at version 1.7.0.

To upgrade the Istio data plane, you will need to re-inject it.
If you’re using automatic sidecar injection, you can upgrade the sidecar by doing a rolling update for all the pods:
    kubectl rollout restart deployment --namespace <namespace with auto injection>
If you’re using manual injection, you can upgrade the sidecar by executing:
    kubectl apply -f < (istioctl kube-inject -f <original application deployment yaml>)
```

**Comment by richardwxn** [comment]
I think it would be better to include the removed fields in the output warning as well, not just values update. But approve it now as it solves the unmarshal issue and unblocks the release

**Review by richardwxn — APPROVED** [review]
Can you create an issue later for that?

**Comment by linsun** [comment]
Agreed on @richardwxn 's comment.  I assume this would ignore if someone uses `citadel:enabled:true` without warning.

**Comment by elfinhe** [comment]
I hear 2 questions here.

1. If users explicitly specify `citadel:enabled:true`, will istioctl ignore it without warning?
- The answer is no, because allowUnknownFields only applies to the version before upgrade, i.e., 1.6.x. When processing 1.7.x upgrade/install, unknownFields is not allowed, and an error will show up.

2. Can we include warning for removed fields?
- I digged into the code, found this [deprecation messages](https://github.com/istio/istio/blob/b82d3961b4d8fdce3a50728d2338c528738015fe/operator/pkg/apis/istio/v1alpha1/validation/validation.go#L80-L105), then I thought we can Citadel here as well.
- However, that is not feasible, because Citadel's protobuf is already deleted from the protobuf in 1.7. The deprecation message mechanism will not be able to find Citadel in v1alpha1.IstioOperatorSpec. 

Today when users enter `citadel:enabled:true`, istioctl will return this error:
```
Error: failed to generate Istio configs from file [], error: could not unmarshal merged YAML: unknown field "citadel" in v1alpha1.IstioComponentSetSpec
```

**Pull request merged**
