### PR TITLE
istiod-remote chart should not rely on global.yaml

### PR DESCRIPTION
**Pull request by jacob-delgado**
Task for https://github.com/istio/istio/issues/25184

Find all occurrences of .Values.global in istio-discovery chart
  `rg -o -e ".Values.global(\.\w+)*" | awk -F\: '{print $2}' | sort -u`

Take values from global.yaml into values.yaml

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by costinm — COMMENTED** [review]
This is for 'istiod injector deployed in remote' ? Not central istiod with run-nothing in remote ?
Because most of the options seem to apply only for first.

It may be worth having a cleaner chart for run-nothing - effectively just the URL of the central

**Comment by linsun** [comment]
@jacob-delgado maybe I'm missing the purpose of your PR, could you elaborate on what prob it solves?

Note the istiod-remote is used when you don't run istiod on the cluster but points to an istiod outside of the cluster (that runs istiod-remote)

**Comment by jacob-delgado** [comment]
cc @linsun The purpose of the PR (and other ones similar to it) are to remove the dependency on `global.yaml` which lives outside of any chart. When users install istio using helm they must pass in `-f global.yaml`. The goal of the work I'm doing is to create independence for all charts. Users will still need to pass in arguments to customize istio, but on an as needed basis for each chart.

Reasonable defaults for people using the helm charts will have to be a work in progress done for 1.8. Installing and getting it up and running is the first stage. I will mention this in the environments meeting this week.

**Comment by jacob-delgado** [comment]
It is worth noting that I did not change any values brought over from `global.yaml` over. It is possible, and even likely, that the values may not make sense or be reasonable.

**Comment by linsun** [comment]
@jacob-delgado thanks, I'll defer to @costinm and others on this.  I just feel it is odd as some of these global params I don't ever expect users to configure them.

**Comment by jacob-delgado** [comment]
Agreed @linsun, but the charts as they are written today depend on them. I didn't just copy `global.yaml` over, but went value by value (with the aid of grep).

**Comment by jacob-delgado** [comment]
Given the breadth of this. I'm not going to try and do this for 1.7. Will try and do this in a future release.

**Pull request closed without merging**
