### PR TITLE
Enable default hosts for kiali ingress

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Comment by knrc** [comment]
Issue is https://github.com/istio/istio/issues/8860

**Comment by knrc** [comment]
@sdake I've looked at the failures and I'm not sure how they would relate to the changes, do you know if these failures are known to be transient?

**Comment by knrc** [comment]
@sdake Thanks, I'll rebase and push again

**Comment by knrc** [comment]
@sdake It looks as if there are still transient failures not connected to this PR, any further suggestions?

**Comment by sdake** [comment]
@knc prow does rebase automatically.  I've retriggered the required tests.

**Comment by knrc** [comment]
@sdake No worries, I had already rebased and pushed it but I'll remember that for next time.

**Pull request merged**
