### PR TITLE
Mc install - enable secrets consumption

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by sbezverk** [comment]
@sdake I do not think this change is that simple. Here we change a behaviour of pilot bootup process. `Before` pilot would not come up and stay in Pending state if the configuration map would not exist, so it ran it meant the required config files were mounted.  `Now` pilot will start even if the configmap does not exist, but what then? The code has not been changed to address the change in behaviour. I think we need to run this test and make sure it is successful:
1. Start pilot with a reference to non existing configmap (check its behavior, most likely it will go into a crash loop)
2. Create that configmap and see if pilot will recover on its own.

As an alternative to crash loop on the absense of configmap, we could make Pilot stay in the bootstrap sequence and check periodically for the configmap, when it appears, it will continue bootstrap process.
@costinm @john-a-joyce  WDYT the right behaviour should be?

**Comment by sdake** [comment]
@sbezverk I've tested this patch, and it works in either order of creating the map (prior to or after pilot starts).  The crashloopbackoff does happen, however, with the proposal you have made in https://groups.google.com/forum/#!topic/istio-environments/q7rb65EXgl0, this patch will be made irrelevant.  Hence the #TODO in the change.

This change is simply to enable CI to unblock other folks that are working on CI - IOW it is meant to match master.

**Pull request merged**
