### PR TITLE
Update to latest ztunnel

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
There are several changes after https://github.com/istio/istio/pull/43571. I think making this automated will be much better.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [x] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
We should add this to the bin/update_deps.sh.

**Comment by ericvn** [comment]
We can also add a job to do this with each ztunnel commit or some other timeframe like daily.

**Comment by ericvn** [comment]
There have been approximately 35 commits over the last 20 days so about ~2 commits per day.

**Comment by costinm** [comment]
Would it be possible to just build ztunnel images from ztunnel repo ( as is
normally done - each repo building images for it's own code) ?

I would add ztunnel to proxyv2 - now that it supports a 'dedicated' mode it
will need the agent and simplify the install.

**Pull request merged**
