### PR TITLE
Added metrics port to kube-gateway.yaml manifest

### PR DESCRIPTION
**Pull request by m3nax**
**Please provide a description of this PR:**

Added the metric port definition to the kube-gateway manifest used during the gateway provisioning when defined via Gateway Api to allow prometheus metrics scrapping with a `PodMonitor`.

The metrics port (**15020**) is defined with the `prometheus.io/***` annotations but isn't declared in the `port` section of pod template. 
https://github.com/istio/istio/blob/0e221eb0811559cf64392b2cd5a8a0d212a58fb9/manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml#L46-L57

https://github.com/istio/istio/blob/0e221eb0811559cf64392b2cd5a8a0d212a58fb9/manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml#L105-L112

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by m3nax** [comment]
@howardjohn 

I am trying to fix the `gencheck_istio` check following the instructions written at the end of check but the command `make gen` still fail.  Does it require any parameters? Is there any documentation I can follow?

[image](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/53351/gencheck_istio/1841047169876889600#)

Command output:
``` BASH
ERROR: exit status 1: manifests/manifest.go:25:12: pattern all:charts/*: cannot embed directory charts/istio-operator: contains no embeddable files
```

**Comment by m3nax** [comment]
I found the guide under **manifests/charts/UPDATING-CHARTS.md**

**Pull request merged**
