### PR TITLE
Remove RequireSingleCluster from Telemetry Tests

### PR DESCRIPTION
**Pull request by gargnupur**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by stevenctl** [comment]
I think it would be easier to do the conversion one test at a time – first step is to create the prow job similar to:

https://github.com/istio/test-infra/blob/516353ff5c6b10766247b4fce2116421ee56b758/prow/config/jobs/istio.yaml#L55-L66

**Comment by gargnupur** [comment]
@nmittler , @stevenctl : https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27491/integ-telemetry-multicluster-k8s-tests_istio/3 tests are passing on multicluster topology too.

PR is ready to be submitted

**Review by bianpengyuan — APPROVED** [review]

**Review by morvencao — COMMENTED** [review]
/test release-notes_istio

**Pull request merged**
