### PR TITLE
start unprivileged ports in ingress

### PR DESCRIPTION
**Pull request by hemendrateli**
**Please provide a description of this PR:**

xref: https://github.com/istio/istio/issues/48364

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [X ] Installation
- [ X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
any context?

**Comment by zirain** [comment]
I think release note is required.

**Review by hzxuzhonghu — COMMENTED** [review]
This feature is useful in some case.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hanxiaop** [comment]
> > I think release note is required.
> 
> This is not a new feature, due to this [change](https://github.com/istio/istio/commit/e4ae5de66f21cfc645e5744300e58bd2ea53d22c#diff-34a675f455a18d4c77afb1cb2bc877a0a77315b3f8dfb8920ddf2f5af96cecb0) we can't bind port < 1024 to ingress. This PR is to fix that to retain previous behaviour.

I think if you want to cherry-pick this for release-1.20, you will need to include a release note about the bug fix for this regression. It's better to include info rather than silently releasing fixes.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
