### PR TITLE
Fix backoff max limit

### PR DESCRIPTION
**Pull request by wzshiming**
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Can you please add some context on the change? The current code looks correct to me and there is no description about what is being changed

**Comment by wzshiming** [comment]
According to my understanding, this logic is to backoff every time it fails and double the time.
But when the maximum value is reached, it will be reset to the initial time, which does not seem to fit the backoff scenario.

**Comment by adiprerepa** [comment]
is the expected behavior that after max backoff is reached, it stays there?

That seems correct: https://cloud.google.com/iot/docs/how-tos/exponential-backoff

@howardjohn wdyt?

**Comment by hzxuzhonghu** [comment]
r.refreshIntervalOnFailure is set equals to the MAX backoff

**Comment by adiprerepa** [comment]
> r.refreshIntervalOnFailure is set equals to the MAX backoff

is it changed anywhere? I think the point is to have a constant

**Review by howardjohn — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
It is not changed anywhere. It is just a passed in param

**Pull request merged**
