### PR TITLE
Adding Cloudwatchlogs support in Mixer Cloudwatch adapter

### PR DESCRIPTION
**Pull request by karanvasnani**
Adding support in the existing Mixer CloudWatch adapter to also send LogEntries to AWS CloudWatchLogs platform. It is an extension to the existing adapter which only sends metrics to AWS CloudWatch.

### CODE REVIEW

**Comment by douglas-reid** [comment]
@karanvasnani would you mind addressing the comments from the golangcibot ?  Then I think we can go ahead and merge this.

**Comment by karanvasnani** [comment]
@douglas-reid I have already resolved the two comments by golangcibot.

**Comment by douglas-reid** [comment]
@karanvasnani thanks! any chance you can restart the circleci tests?

**Comment by karanvasnani** [comment]
@douglas-reid I have restarted the tests.

**Comment by karanvasnani** [comment]
@douglas-reid I am unable to identify the error from this log for failing tests https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10366/e2e-simpleTests/14304. Can you please help me identify the issue.

**Comment by douglas-reid** [comment]
Failure with the test infrastructure:

```
2018-12-10T19:47:49.735173Z	error	Failed to deploy Istio with helm.
2018-12-10T19:47:49.735184Z	error	Failed to complete Init. Error command failed: "Error: timed out waiting for the condition\n" exit status 1
```

But it looks like it passed now?  In any case, the `lint` failure and the unit test failure on Circle look like the only blockers.

**Comment by douglas-reid** [comment]
@karanvasnani ah! I think I see one issue. This PR should be against `release-1.1` instead of `master`. `master` was locked recently... and I don't know the status of the `lint` test on it.

**Comment by karanvasnani** [comment]
@douglas-reid Created new PR https://github.com/istio/istio/pull/10400 from `release-1.1` instead of `master`.

**Pull request closed without merging**
