### PR TITLE
Restore registry order: the main k8s registry at first

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is the right order we have been using for long. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
just curious,  where does it make a difference?

**Comment by hzxuzhonghu** [comment]
The ci failure proves it has big difference. @stevenctl What might cause this?

**Comment by stevenctl** [comment]
This shouldn't make a difference in the aggregate registry search unless there are a very large number of clusters, in which case Get service would waste some iterations merging a service when we just want the service registry one.

In that case, there's already some redundant overlapping in the users config between vanilla k8s and se.


The cause of this failure is that we need the se registry created before creating the multicluster registry controller, so that it can wire up handlers.

**Comment by hzxuzhonghu** [comment]
Fixed

**Comment by hzxuzhonghu** [comment]
@ramaraochavali Take GetService as an example, the order matters.

https://github.com/istio/istio/blob/8933f4546e206a3788e923b863ed2f24c586c1e6/pilot/pkg/serviceregistry/aggregate/controller.go#L147-L170

**Comment by hzxuzhonghu** [comment]
@stevenctl Not sure how we can test it

**Pull request closed without merging**
