### PR TITLE
Fix grafana workload dashboard mismatched quantiles query

### PR DESCRIPTION
**Pull request by AEGQ**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by carolynhu** [comment]
@AEGQ could you please run ` ./manifests/addons/gen.sh` from the istio/istio root dir to update the grafana.yaml file as well.

**Review by carolynhu — CHANGES_REQUESTED** [review]
@AEGQ could you please run ./manifests/addons/gen.sh from the istio/istio root dir to update the grafana.yaml file as well. And, since you find this issue, could you please check about other places if we did not set to the correct corresponding quantile query. Thanks!

**Comment by AEGQ** [comment]
@carolynhu I have submitted an update to grafana.yaml and no other problems have been found so far.

But I encountered an error when executing ./manifests/addons/gen.sh, and fixed by change client to true.

image

https://github.com/istio/istio/blob/e2da6e166f44541c1a0316c587e151db61b67191/manifests/addons/gen.sh#L71
https://github.com/istio/istio/blob/e2da6e166f44541c1a0316c587e151db61b67191/manifests/addons/gen.sh#L77

**Comment by carolynhu** [comment]
@AEGQ 
--dry-run support for kubectl 1.15 only have bool option
ref: https://v1-15.docs.kubernetes.io/docs/reference/kubectl/overview/#

**Review by carolynhu — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]

**Pull request merged**
