### PR TITLE
remove duplicate istio ca certs

### PR DESCRIPTION
**Pull request by irisdingbj**
current flow is istiod will push root cert from istiod ca first and update trustbundle with root certs from all supported sources.  So it will added another duplicate root cert from istioca whenenver meshconfig is updated.  

Below is just one example: 

```
-----BEGIN CERTIFICATE-----
MIIC/TCCAeWgAwIBAgIRAIHUi1/bDcT9LuwkPqKyeZ8wDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMTA0MDgwNjE5MTVaFw0zMTA0
MDYwNjE5MTVaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDM4i0zM0BdL2ygyTH1GN8PA/84H78VtLsa3jqQ
xOGhATV2WKWSVChxTGvTE0eybrYWlvscLFGi/YIg5VbcH0bXSheUmy5+JK3mkg0w
eiVoWGolfwB9xB/QXebC3bwR2lpxIy9NuKTegrDiExjTzy8GNhR7GTA1glqNQ6pB
yGZ2QSPTXhhWEQHION7tpohk4T5M0xSFFpxwT/8Al9g0TQOyF0hKuKlqoj07KAXf
0unoGZaL9+8gYBJv0sZofMOV/WU36VVy2B79NArn+k1+dUxZIiVWSE7dEQYUxrae
XNw2nSJ5BdTNvYnRFp8T41Hzs7NZXLSgfdwqnACQqsQZmXZ1AgMBAAGjQjBAMA4G
A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS0pf6sS+fh
UX9sfhKXUZ4QZbeePTANBgkqhkiG9w0BAQsFAAOCAQEAb0qX6nauM4EIrpmE52ab
OC/DsSd8JQW8gw6ZBP1OtJFnpZjjkt7WwXbx/XuKMIQVytHVT4uu/UGPk3LpTVfv
DImCfCXsm3AGGbEtmyTyrD5/coMhY81ukQGzrzc5mfJiibsrP8C6r54jAQaa8iqQ
sRoo9fk9MHYiUw7fWQm+RZk52WgOWp4hdYwfHYc1uW6HFmfIU4otzpQEOzfjN7+i
OXmtGSQYPpJbh2GDehHJsD1e/JT61uKydCZuf4SdvphPU1E9ZyaF/zlBRe0lLd9l
EOyKBlU8frlN9ODJGJdnwJ2ONvAxPoGttNRh6n/2WQsFvzTJWcMkevno1tiF993b
Qw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIC/TCCAeWgAwIBAgIRAIHUi1/bDcT9LuwkPqKyeZ8wDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMTA0MDgwNjE5MTVaFw0zMTA0
MDYwNjE5MTVaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDM4i0zM0BdL2ygyTH1GN8PA/84H78VtLsa3jqQ
xOGhATV2WKWSVChxTGvTE0eybrYWlvscLFGi/YIg5VbcH0bXSheUmy5+JK3mkg0w
eiVoWGolfwB9xB/QXebC3bwR2lpxIy9NuKTegrDiExjTzy8GNhR7GTA1glqNQ6pB
yGZ2QSPTXhhWEQHION7tpohk4T5M0xSFFpxwT/8Al9g0TQOyF0hKuKlqoj07KAXf
0unoGZaL9+8gYBJv0sZofMOV/WU36VVy2B79NArn+k1+dUxZIiVWSE7dEQYUxrae
XNw2nSJ5BdTNvYnRFp8T41Hzs7NZXLSgfdwqnACQqsQZmXZ1AgMBAAGjQjBAMA4G
A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS0pf6sS+fh
UX9sfhKXUZ4QZbeePTANBgkqhkiG9w0BAQsFAAOCAQEAb0qX6nauM4EIrpmE52ab
OC/DsSd8JQW8gw6ZBP1OtJFnpZjjkt7WwXbx/XuKMIQVytHVT4uu/UGPk3LpTVfv
DImCfCXsm3AGGbEtmyTyrD5/coMhY81ukQGzrzc5mfJiibsrP8C6r54jAQaa8iqQ
sRoo9fk9MHYiUw7fWQm+RZk52WgOWp4hdYwfHYc1uW6HFmfIU4otzpQEOzfjN7+i
OXmtGSQYPpJbh2GDehHJsD1e/JT61uKydCZuf4SdvphPU1E9ZyaF/zlBRe0lLd9l
EOyKBlU8frlN9ODJGJdnwJ2ONvAxPoGttNRh6n/2WQsFvzTJWcMkevno1tiF993b
Qw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFCTCCAvGgAwIBAgIJAL4uxHfykeWSMA0GCSqGSIb3DQEBBQUAMCIxDjAMBgNV
BAoMBUlzdGlvMRAwDgYDVQQDDAdSb290IENBMB4XDTIxMDIxNzIyNDA1N1oXDTMx
MDIxNTIyNDA1N1owIjEOMAwGA1UECgwFSXN0aW8xEDAOBgNVBAMMB1Jvb3QgQ0Ew
ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCkESA1E1psP/v9wkdimcqZ
X832eMRKomDxFFwbk9ayMF/XrGMAUmsvqeN9a73m5UD3MpArBiRc97XXzW1K1hnW
sCtcN42C25NDXgHGjzyhplNogR6/SsKYg2oZx2iBRJUxwroi3/iTv7KPousQwGpF
a/leoNxfr0+twbA5Y9nS17zO8CfJLlJz+c8MIbSdCTckcRxvVSXWsUlH1BJS/Bfh
TnlaVqk/YGWBxhtm8BowB0hzaxFrQnwuxsRXgnFmlAV0iZ35jvrhM6vmU2RqvUUo
BEgTTPuToC/2VRmyhFw/9cWcjzxgkvkjLsmVg5icuNvKQ4PgJL07zguRjk0XFchz
SZuqimjDYSRQv3I0TOn+eT0b2KX8neg1pqh7w81YotyqFcJ7SdpQaau7CeMbus92
P7XsCpCSVe82Y8BRcdtPgDEzn7AOA2IlgxDC1hex80+10aL8naWGdxxUEom8wQwS
gvRHrdDsRigVvcygvVhfcoMak4RUxFeaQK5c1ruMlNvuuwZ20C4mUvZTvlaz7RmN
yazzjqQYT4GHbR2e1kwBqe6YtlOrHY1Fpg5V6+S1rQkbbZrfQVQOXz7VQ7jOsmEr
kNkrtgS8ZjAwgnOrf878Rr1g8Ac+I4q7Mpei2humdAydO3cEaGskcoozsxjPAKvd
8be76nUjjkBv6eURp1ziEQIDAQABo0IwQDAdBgNVHQ4EFgQUPyNoAnWNHwP+2NFi
zWLW0hz3Cw0wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAuQwDQYJKoZI
hvcNAQEFBQADggIBAIQx3aCt5GFuWxLLYlL2wbrO8tFoQnN4Poa/uli65YF47abb
zZkDm6OomYIsWVce4tdoJZy1TLlyKZPb+MDDnelOzNhpljjpw2ZdhEtnv703513q
o1zCgVrO1YWvk6Xv1gt3wVhQvJhq87BqrYFcCo899k09haXU4ddtP+YMPjyIngVb
ucxML2xqjzS1Cfs+CD/OpwntISzWOEi5r/3IkbPlMT15hFa2oAVKBhOkyk0QQP8t
bV9i4AC32gvshwIiGjbXUmnlRwBxUi8GBq5ZyR66nqoV9wBHPoqJZ3z+j6DNZSYm
QGaO0wwWgSePRNPodzPAw6vofDjBe/hcyCk2d2uRrOLJICWbAdx76+j6h3zX2sPS
FVSK1eVZaPUylL9rE+AyVGgl8/FqLNTwOHdSSovgIVVID7eXSpebnFtQEtlCSnik
naaVSrG+sTH77WD9mQO9LmYS8JVceLE+ErSEAXkFKim131317sS5Z310U/L021M4
xGH6zZHK9W9dx1X4gZKfoqGwSAHhs4rjEZCU7CKR1ouJBPWQ/cGrrk8n8ZdmKxmz
OHNB4GteIEKJKrJTKQil8hsdSIqSUX4H4tw4GXlpyBSmZNt9iOjo4tWUGoUlQRIp
QDpfEx1ep9pVDwQNGXVf+m9iqbc3DAiSN+1CGSZI5Kv0RzZSih5zIaxB2gJ7
-----END CERTIFICATE-----


```

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
Right, I noticed this too.

**Review by howardjohn — COMMENTED** [review]
Can we add a test that would have covered this?

**Comment by shankgan** [comment]
@irisdingbj - I don't think we need this additional logic IMO. Envoy has no issues with having multiple copies of the same ca Cert as part of the ROOTCA Cert Chain.

**Comment by shankgan** [comment]
@irisdingbj - If we do want to implement this - note that when submitting the ROOTCA bundle to envoy, we merge this with the root-cert of the CA cert-chain. The removal of redundant certs has to happen there as well.

**Comment by irisdingbj** [comment]
> @irisdingbj - If we do want to implement this - note that when submitting the ROOTCA bundle to envoy, we merge this with the root-cert of the CA cert-chain. The removal of duplicate certs has to happen there as well

Thanks. But we have already removed the root cert from istioca in this PR (`UpdateConfigTrustBundle`) , so the merge logic when we submitting to envoy do not need any change.

**Comment by irisdingbj** [comment]
> @irisdingbj - I don't think we need this additional logic IMO. Envoy has no issues with having multiple copies of the same ca Cert as part of the ROOTCA Cert Chain.

THe issue is the ROOTCA will be increased every time when you update meshconfig with an additional rootca from istio ca. It means it will be increased for ever..

**Pull request closed without merging**
