### PR TITLE
Move some special injection logic into the templates

### PR DESCRIPTION
**Pull request by howardjohn**
Depends on https://github.com/istio/istio/pull/29105

    When the logic is hard coded in the go code, its misleading to users and
    doesn't allow customization. this will be critical to allow gateway
    injection

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]

**Review by dgn — COMMENTED** [review]
What problem does this solve exactly? Could you add some more information?

I'm worried because it changes the default values for `securityContext.fsGroup` and apparently also revision?

**Comment by howardjohn** [comment]
@dgn it does not change anything for users today. The problem with hard coded logic in the code is there is no way to opt out. Moving more logic info the templates means that users can look at the template and fully understand what is being injected (security Context one surprised many people!) and so when custom injection templates are supported it's possible to exclude these parts.

The change to revision in the test cases is only because the test was previously not accurate, in reality the default injection result should be unchanged by this pr.

**Comment by dgn** [comment]
Okay, sorry- I was a bit confused by the amount of changes to the .patch files. Could you add your template directives for the labels and the fsGroup into the `pkg/kube/inject/testdata/webhook/TestWebhookInject_template.yaml` file? That way you don't need all those changes to the golden outputs

**Review by nmittler — APPROVED** [review]

**Pull request merged**
