### PR TITLE
allow pilot to run by itself

### PR DESCRIPTION
**Pull request by linsun**
using cmd:

helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set security.enabled=false \
  --set ingress.enabled=false \
  --set gateways.istio-ingressgateway.enabled=false \
  --set gateways.istio-egressgateway.enabled=false \
  --set galley.enabled=false \
  --set sidecarInjectorWebhook.enabled=false \
  --set mixer.enabled=false \
  --set prometheus.enabled=false \
  --set global.proxy.envoyStatsd.enabled=false \
  --set pilot.sidecar=false

### CODE REVIEW

**Comment by rshriram** [comment]
Please doc this and may be make this whole thing super prominent as a "Incremental Istio Install" section instead of tucking it away in some helm install page, as its now.

**Comment by rshriram** [comment]
Also please send same Pr to master

**Comment by kyessenov** [comment]
Just curious: what use is pilot standalone? Should it be at least
injector + gateway?

**Comment by linsun** [comment]
@rshriram will do!

@kyessenov it is useful when folks start with nginx and then move to istio ingress gateway.

@ymesika I found out sidecar injector pod/deployment isn't really needed for this pilot only mode... only the injector config.  FYI.

**Pull request merged**
