### PR TITLE
rbac: update envoy sha to support connection.sni as service role constraint

### PR DESCRIPTION
**Pull request by yangminzhu**
Also updated Envoy with following changes:
```
ea9e05a Update dependencies and fix compile errors. (#1993)
98ba490 Update bazel for circleCI (#1997)
d94f3e4 Fix attribute constant (#1996)
fdffa13 Update software in the build image used by CircleCI. (#1994)
```
/cc @rshriram @venilnoronha

### CODE REVIEW

**Comment by rshriram** [comment]
Please update the tag to 0.6.1

**Comment by yangminzhu** [comment]
@venilnoronha @rshriram Updated to use `0.6.1` for go-control-plane. I think it should be okay to merge this first and then update the Envoy sha in another PR once istio/proxy#1993 is merged.

**Comment by venilnoronha** [comment]
@yangminzhu istio/proxy#1993 is merged. Can you update this PR?

**Comment by yangminzhu** [comment]
@venilnoronha We need to wait until the proxy image is also updated with that commit, and then we can update it in Istio.

**Pull request merged**
