### PR TITLE
fix bug: allow specify cpu/memory resource requests separately

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
fixes: #12249

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@duderino

**Comment by hzxuzhonghu** [comment]
ping @duderino this is a bug absolutely

**Comment by duderino** [comment]
@linsun @geeknoid @wenchenglu @utka 

Greetings fellow admins.  @rshriram couldn't get in touch with me (my fault) so he made a call and merged this.   I think he made the right call so giving it a post-merge /lgtm.

**Pull request merged**
