### PR TITLE
Keep service instances sorted by creation/hostname

### PR DESCRIPTION
**Pull request by sergii-koshel-exa**
Fixes: https://github.com/istio/istio/issues/19234

### CODE REVIEW

**Comment by howardjohn** [comment]
Thanks for the fix! Looks good. As the bot said, just need CLA signed then this should be good to go

**Comment by sergii-koshel-exa** [comment]
@googlebot I signed it!

**Comment by nicktrav** [comment]
@howardjohn - reckon we could get this cherry-picked into 1.4.x?

**Pull request merged**
