### PR TITLE
Adding ability to disable Istiod CA server from Istioctl

### PR DESCRIPTION
**Pull request by shankgan**
Several deployments of Istiod do not require the CA server to be running. Currently, an environment variable controls that. This PR provides the ability for istioctl to configure that environment variable, thus allowing this option to be explicitly configured, if needed,  for e2e testing.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
I don't think we want to add another option to values.yaml, which we have been trying to reduce usage of, for something that is already configurable. Maybe we should push for putting this in mesh config if we want a more first class API?

**Comment by shankgan** [comment]
Marking as hold...tests pending...Created PR just to check if e2e tests run successfully

**Comment by shankgan** [comment]
@howardjohn - The reason I added this to values.yaml was because this was a pre-existing environment variable configuration (which couldn't be configured through istioctl). I think adding another configurable option to meshConfig could create some confusion? For instance, users configure ENABLE_CA_SERVER through some mechanism, but meshConfig says otherwise?

**Comment by howardjohn** [comment]
You can configure env var through istioctl. `--set values.pilot.env.FOO=bar`

**Comment by shankgan** [comment]
@howardjohn - ignore previous comment. got a little confused regarding how meshConfig can also be used to set environment variables today (for instance trustDomain). SGTM, if this is really needed, will add to meshConfig

**Pull request closed without merging**
