### PR TITLE
Add version info in citadel and agent

### PR DESCRIPTION
**Pull request by wattli**

### CODE REVIEW

**Comment by wattli** [comment]
To address https://github.com/istio/istio/issues/13937

**Comment by wattli** [comment]
@duderino

**Comment by howardjohn** [comment]
Can you backport this to master as well @wattli

**Comment by howardjohn** [comment]
Looks like a bunch of changes got added to this

**Comment by duderino** [comment]
@wattli I can't tell what this PR was supposed to fix because it inadvertently picked up a ton of other commits from master.  Please reopen if you want to try again, but also please describe why we need to get this into 1.1 instead of 1.2 which is only about 3 weeks away

**Pull request closed without merging**
