### PR TITLE
istioctl analyze: skip if namespace does not exists

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/30804

Before:
```
$ istioctl analyze -n bookinfo

✔ No validation issues found when analyzing namespace: bookinfo.
```

After:
```
$ istioctl analyze -n bookinfo
namespace "bookinfo" not found
```

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
isn't `--use-kube=false` supposed to only look at local files? I think with this change that will no longer work

**Comment by shamsher31** [comment]
> isn't --use-kube=false supposed to only look at local files? I think with this change that will no longer work

Right. I think when the user provides a filename, they don't need to add a namespace flag (which is checked in this PR) as it will be local files. But adding an extra check for `--use-kube=false` will be good to add.

```
$ istioctl analyze --use-kube=false -n bookinfo 

✔ No validation issues found when analyzing namespace: bookinfo.
```

```
$ istioctl analyze --use-kube=true -n bookinfo 
namespace "bookinfo" not found
```

**Comment by shamsher31** [comment]
@esnible PTAL.

**Comment by shamsher31** [comment]
cc: @istio/wg-user-experience-maintainers

**Comment by shamsher31** [comment]
@esnible ping.

**Review by jasonwzm — APPROVED** [review]
Thank you!

**Pull request merged**
