### PR TITLE
Remove Galley's support for legacy mixer types

### PR DESCRIPTION
**Pull request by ayj**
Remove Galley's support for legacy mixer types now that the CRDs are no longer installed.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
I approved t&r changes but put a hold since this should be reviewed by mixer owners

**Review by mandarjog — APPROVED** [review]
/lgtm

**Review by liamawhite — APPROVED** [review]

**Review by kyessenov — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Comment by ayj** [comment]
> --- FAIL: TestQuotaCache (2.57s)
>     quota_cache_test.go:97: OKGet quota called count 7 should not be more than 5

/test unit-tests_istio

**Pull request merged**
