### PR TITLE
Ansible playbooks updated to use istio-demo*.yaml instead of istio*.yaml

### PR DESCRIPTION
**Pull request by ymesika**
Istio files in `v0.8.0` are now called `istio-demo.yaml` and `istio-auth-demo.yaml`.
This is a quick fix for issue: #5985 however, as mentioned there, for future releases we might want to install using helm.

### CODE REVIEW

**Comment by gbaufake** [comment]
@ymesika 
I'm not a formal reviewer, but I can confirm this fixes #5985.

When you say using helm for future releases, is it deprecate Ansible installer in favor of helm ... or is it using helm commands on ansible playbooks?

**Comment by ymesika** [comment]
@gbaufake I thought about the second option - use helm command within the playbooks.
Does it make sense?

**Comment by gbaufake** [comment]
@ymesika 
it does.
Thanks for the clarification!

**Comment by ymesika** [comment]
Closing this one for a cleaner PR and will re-open a new one with `master` as the base.

**Pull request closed without merging**
