### PR TITLE
Restructuring pilot packages

### PR DESCRIPTION
**Pull request by nmittler**
The purpose of this change is:

- consistency with other modules (e.g. mixer)
- better separation of library code from other directories
- more clearly indicating the points of extension
- more clearly indicating those things that are k8s-specific

Overview of the changes:

- Adding `pkg` at the top-level to house all library code.
- Removed `adapter` and moved `config` and `serviceregistry` to the top level under `pkg`
- Moved all service registry implementations under `serviceregistry` (kube, consul, eureka, cloudfoundry)
- Removed `platform` and moved up the remaining `kube` package to the top level under `pkg`
- Moved cmd/pilot-discovery/server to the top-level under `pkg` and renamed to `bootstrap`
- Moved cmd/pilot-discovery/mock to `pkg/proxy/envoy`

The resulting layout for pilot is:

- bin
- cmd
- doc
- docker
- pkg
  - bootstrap
  - config
    - aggregate
    - memory
    - kube
      - crd
        - file
      - ingress
  - dataplane
  - kube
  - model
  - proxy
    - envoy
      - mock
  - serviceregistry
    - aggregate
    - kube
    - consul
    - eureka
    - cloudfoundry
- test
- tools

### CODE REVIEW

**Comment by kyessenov** [comment]
`model` package is not just config, it contains service registry APIs.
So I don't think it's appropriate to house it under config package.

**Comment by kyessenov** [comment]
Can you please ensure the following constraints hold:
- platform (service registry) depends only on the model
- config implementation only depends only the config definitions and backend platform
- proxy only depends on the model
- no dependency on the command packages

**Comment by kyessenov** [comment]
Shouldn't we move `pkg` to top-level anyways if we're going to do this?
Also please remove bin/docker/doc since it's mostly shared between all projects.

**Comment by kyessenov** [comment]
Did you forget to add code?
Also please use `git mv` so git keeps track of the history.

**Comment by nmittler** [comment]
@kyessenov 

> model package is not just config, it contains service registry APIs.
So I don't think it's appropriate to house it under config package.

I'm fine with promoting `api` to just under `pkg` ... wdyt?

> Shouldn't we move pkg to top-level anyways if we're going to do this?

Not sure I follow.  pkg is a new package ... are you suggesting there is another `pkg` package somewhere under pilot?

> Also please remove bin/docker/doc since it's mostly shared between all projects.

I don't see this directory.  Has it already been deleted by a previous PR?

> Did you forget to add code?

Are you referring to a package that I missed?

> Also please use `git mv` so git keeps track of the history.

It's unfortunate that goland isn't doing this automatically - it really seems like a bug. I don't feel comfortable doing all of this from the command line. That being said, I'm just shuffling code around here ... there are no changes to any logic.

**Comment by ldemailly** [comment]
> It's unfortunate that goland isn't doing this automatically - it really seems like a bug. I don't feel comfortable doing all of this from the command line. That being said, I'm just shuffling code around here ... there are no changes to any logic.

you need to use a better ide (you can try atom) or do it by hand + ide after git mv

keeping the history isn't an optional part of the process

**Comment by kyessenov** [comment]
Please preserve the history using git or whatever other tool you're
comfortable with. Removing and then adding files will lose all history.

**Comment by kyessenov** [comment]
By the way,`pkg` root is not an official taxonomy. Correct me if I'm wrong,
but no tool actually makes use of it, and it's simply used to demarcate go
sources from the rest. Since pilot is now just go sources, I don't see the
point of creating another indirection within `pilot`. My suggestion was to
elevate pilot to root `istio/pkg`, which is more in line with the practice.

I was suggesting to remove unused files from `bin`, `doc`, and `docker`
directories. They are there because noone had the will to purge them after
mono-repo move, and you seem enthusiastic about shuffling :)

**Comment by nmittler** [comment]
@kyessenov 
> Please preserve the history using git or whatever other tool you're
comfortable with. Removing and then adding files will lose all history.

Looking through the files in this PR, it appears that everything is viewed as a move, rather than new/deleted files. Or am I missing something?

>  By the way,`pkg` root is not an official taxonomy. Correct me if I'm wrong, but no tool actually makes use of it, and it's simply used to demarcate go sources from the rest. Since pilot is now just go sources, I don't see the point of creating another indirection within `pilot`. My suggestion was to elevate pilot to root `istio/pkg`, which is more in line with the practice.

Ah ok, I think that makes sense.  @ZackButcher does that sound reasonable?

**Comment by kyessenov** [comment]
The danger of elevating to top level is of course implicit coupling and
birth of monolith ;)

**Comment by nmittler** [comment]
> The danger of elevating to top level is of course implicit coupling and
birth of monolith ;)

That's fair. And TBH having `pilot/pkg` is consistent with what mixer is doing today.

**Comment by ZackButcher** [comment]
I don't think we want to push stuff up to the top level yet (the other parts of Istio haven't done this yet other than shared lib code coming out of Mixer). I want a `pkg` dir in Pilot so it mirrors our other components (mixer, security). After all of our major components have the same structure, we can talk about refactoring all three to push everything up to the top dir (if that's even desirable; I think ultimately we only want shared code in the root).

**Comment by kyessenov** [comment]
Why is it a good practice?
I can ask @dfc whether this has benefits, but from my experience, it would make sense to have istio/pkg but not istio/blah/blah/blah/pkg.

**Comment by ZackButcher** [comment]
It is a good practice to have a consistent directory structure across all components of our project. If we don't want `pkg` in all of our component's directories then remove it in `mixer` and `security`. I don't really care which way we go (add pkg to pilot, remove from others) so long as all Istio components are consistent.

**Comment by kyessenov** [comment]
The choice of having top-level pkg in mixer was prior to mono-repo merging.
I think we should re-consider it to avoid introducing nested `pkg` like
what happened in k8s.

**Comment by geeknoid** [comment]
I like the separation of concern that having a mixer-private pkg directory
provides. It's a valuable indication to the user which components is using
the given package.

**Comment by kyessenov** [comment]
I get that but think of pilot directory as that place for PKG in pilot.
They should be no more non go sources in pilot now that we share
infrastructure, and we should consider moving cmd up one level.

**Comment by kyessenov** [comment]
I'm not comfortable with 390 file moved. It's going to break lots of folks. Let's come up with the end goal of what you are trying to achieve across istio, and discuss that first.

**Comment by nmittler** [comment]
> I'm not comfortable with 370 file moved. It's going to break lots of folks. 

It's not clear to me why this will break anyone.  And if we're unable to restructure our codebase because of that concern in a pre-1.0 build, that seems like a much more fundamental problem that needs to be addressed.

**Comment by kyessenov** [comment]
@ijsnellf @GregHanson @rosenhouse your input in re-structing packages is very much appreciated here :)

**Comment by ijsnellf** [comment]
wrt breakage: I'll have to see how well git handles all the renaming for my upcoming external service PR. As long as git understands what is going on, it should be at least be manageable.

**Comment by ijsnellf** [comment]
> I was suggesting to remove unused files from `bin`, `doc`, and `docker` directories. They are there because noone had the will to purge them after mono-repo move, and you seem enthusiastic about shuffling :)

I think there are still references to these files in the Makefiles. Removing the files should be done with care.

**Comment by costinm** [comment]
While I don't like much the old layout, I don't think the new one is so much better to justify all the pain for people who are already familiar with the current one, nor do I think it's a P0 to move files around - or that the new layout will make it easier to find or understand the code. 

I would rather see an incremental set of changes ( and they have been happening), where it is a clear explanation for the new name/location. In particular moving the cmds to the top level ( from all components) would be good, and then the extra pkg/ will not be that useful. 

I know code layout can be a bit of bikesheding - but I don't see a good enough justification for this particular layout.

**Comment by nmittler** [comment]
@costinm 

> While I don't like much the old layout, I don't think the new one is so much better ..

Do you have suggestions for how the new layout might be improved? It would be good to hear what exactly you don't like and how to fix it.

> ...  to justify all the pain for people who are already familiar with the current one,

This change makes the pilot code more consistent with mixer. I don't see this change as causing anyone much pain. After a time, consistency will likely improve the overall code navigation experience.

> nor do I think it's a P0 to move files around

Agreed, but if we can improve the consistency and navigability of the code base before 1.0, I think it's something we should do.  Especially since moving files isn't very hard.

> I would rather see an incremental set of changes ( and they have been happening), where it is a clear explanation for the new name/location. In particular moving the cmds to the top level ( from all components) would be good, and then the extra pkg/ will not be that useful.

This is overkill for a simple code shuffle. We can't have that sort of bureaucracy and expect progress, especially on something this trivial. I've included a bulleted overview of the changes in the description.  If you have specific questions regarding the changes, I'd be happy to discuss.

> I know code layout can be a bit of bikesheding - but I don't see a good enough justification for this particular layout.

Again, without specifics this isn't very helpful. Parts of the changes have a very clear justification. For example, I moved `adapter/config/crd` and `adapter/config/ingress` to `platform/kube`, because they are k8s-specific, where the others in that directory are platform-agnostic. I also moved `adapter/cmd/pilot-discovery/mock` to `proxy/envoy/mock` because it really should be next to the "real" discovery service.

Surely you're not against all of these changes. If you have additional suggestions, I'm all ears.

**Comment by rosenhouse** [comment]
As an outside contributor trying to add support for a non-K8s platform, I appreciate any efforts to clarify, via name or hierarchy, what parts of the code are K8s-specific and what parts are not.

**Comment by rshriram** [comment]
Drive by nit: please keep model named as model and not api. It’s not api that we expose. It’s just an abstract model of services. And +1 to what Kuat said about the dependencies (platform depends on model only), proxy depends on model only.

**Comment by kyessenov** [comment]
Are CRDs really k8s specific? We had a long debate about that, and were trying to use CRDs outside of k8s too. I think there is a larger question that organization should reflect the architectural intent, and I don't see clarity in the end goal of this move. With galley and more platforms, we'll need subsequent refactoring after this, which is not helpful to limit the churn (and we're churning more than necessary with the build and repo moves).

**Comment by kyessenov** [comment]
One example of what is lost is clear separation between service registries and configuration. If that is the intent, that needs to be discussed. If it's just look code prettier, then it's not helpful to drive de-coupling enforcements that we relied upon strict package separation between model, proxy, and platform.

**Comment by nmittler** [comment]
> Are CRDs really k8s specific?

They are certainly k8s dependencies, so yes they are k8s-specific. If that ever changes, we can move them around accordingly.

**Comment by kyessenov** [comment]
Another comment: please avoid calling a package "server". It's not helpful. We have a lot of "servers" in pilot (per-proxy, per-deployment, agents, managements, etc). Having one "server" is not aiding in navigating the code.

**Comment by kyessenov** [comment]
Re CRDs. Yes, technically we depend on k8s library but that does not imply a dependency on k8s itself. A code dependency does not imply an architectural dependency.

**Comment by nmittler** [comment]
> One example of what is lost is clear separation between service registries and configuration. If that is the intent, that needs to be discussed. If it's just to make look code prettier, then it's not helpful to drive de-coupling enforcements that we relied upon strict package separation between model, proxy, and platform.

I don't believe this is the case. Service registries are still separate from configuration. Have you read the description?

**Comment by rshriram** [comment]
I am not too happy with the multi-level hierarchy, but I am not going to object either as I don’t follow golang hygiene.

Also, why leave cmd and have pkg/server ? Can’t we have pkg/bin or is that frowned upon?

Also, now might be a good time to refactor the Envoy folder. I added a dataplane folder. Perhaps we should have dataplane/v1, allowing us to add dataplane/v2 over time. The dataplane can be a top level directory or under pkg or config or wherever you want to keep it. Under it, we should have discovery.go, config.go, etc. watcher.go could remain under proxy/Envoy/

**Comment by kyessenov** [comment]
Then is platform/kube, which is k8s registry not under "serviceregistry"?

**Comment by rshriram** [comment]
Also the service registry/aggregate seems like loner. Can’t we put it under platform/aggregate ?

**Comment by nmittler** [comment]
@kyessenov 

> Then is platform/kube, which is k8s registry not under "serviceregistry"?

I'm not sure I understand the problem.  We have `config` and `serviceregistry` both at the top-level and both contain platform-agnostic implementations.  Then under `platform/kube` we  have k8s implementations of both. This seems consistent.

**Comment by kyessenov** [comment]
I think we should rename "platform/kube" to "serviceregistry/kube" instead of stuffing things under it. WDYT?
Also +1 for splitting envoy into two dataplanes.

**Comment by nmittler** [comment]
@rshriram 

> Also the service registry/aggregate seems like loner. Can’t we put it under platform/aggregate ?

Yes, it's an oddball ATM. I believe the plan is to solidify the service registry API and to make that more or less part of `model` (currently called `api` in this PR)

**Comment by kyessenov** [comment]
@nmittler every service registry is also a platform. That's the case for consul and cloudplatform.
If you want to group by platform, then we need platform/consul, and platform/cloudfoundry, etc directories and get rid of "config" and "serviceregistry". If you want to group by purpose then let's get rid of "platform".  The PR mixes the two.

I had trouble getting rid of "platform/kube" last time I tried for the same reason of touching too many files and getting too many negative comments. So I appreciate your effort :)

**Comment by kyessenov** [comment]
The benefit of dividing by purpose was to allow mix-match (run consul registry with k8s config or vice versa). Hence, multiple packages seemingly for the same platform (k8s).

**Comment by nmittler** [comment]
> I think we should rename "platform/kube" to "serviceregistry/kube" instead of stuffing things under it. WDYT?

Would that imply that we'd have both `serviceregistry/kube' and `config/kube`? I think having all of the platform-specific code under one tree is desirable.

**Comment by kyessenov** [comment]
Yes, it's ok to have multiple packages. We want pluggability. I want to disable istio ingress on k8s, and that's easier to achieve if it is a separate package, not a coupled kube package.

**Comment by nmittler** [comment]
> The benefit of dividing by purpose was to allow mix-match (run consul registry with k8s config or vice versa). Hence, multiple packages seemingly for the same platform (k8s).

The code structure is an orthogonal topic to usage. There is no benefit to usage one way or the other.

**Comment by nmittler** [comment]
> Yes, it's ok to have multiple packages. We want pluggability. I want to disable istio ingress on k8s, and that's easier to achieve if it is a separate package, not a coupled kube package.

That is not true. Nothing is made harder or easier by where the code is located.

**Comment by kyessenov** [comment]
It was easy to enforce package boundaries with bazel to make sure ingress does not leak anywhere. With go, we have to rely on reviews and manual inspection to make sure that does not happen. It's easy to check imports though if we have multiple packages.

**Comment by kyessenov** [comment]
And as I said earlier, we definitely want to keep CRDs separate from k8s. It's our main config backend for k8s and non-k8s alike.

**Comment by nmittler** [comment]
@kyessenov I suggest you propose an alternative layout. It's clear you have concerns with much of what's presented here, but not much has been provided toward a clear alternative.

**Comment by nmittler** [comment]
> And as I said earlier, we definitely want to keep CRDs separate from k8s. It's our main config backend for k8s and non-k8s alike.

Where is it used to configure something that is not k8s?

**Comment by kyessenov** [comment]
It's difficult to provide a solution if the goal is subjective judgement of
code clarity :) How about this:
- move dataplane to proxy/envoy/v2
- start removing bin, docker, and move doc up one level to doc/pilot
- move tools up one level
- drop "adapter" by moving adapter/config to just config/
- don't touch model
- move platform/consul to serviceregistry/consul
- move platform/cloudfoundry to serviceregistry/cloudfoundry
- move platform/eureka to serviceregistry/eureka
- move platform/kube to serviceregistry/kube
- move stuff out of kube that is not service registry (queue, admit,
inject) to kube/ directory -- these don't have cross-platform alternatives
and that needs to be made clear

**Comment by nmittler** [comment]
@kyessenov  thanks!

> - start removing bin, docker, and move doc up one level to doc/pilot

I'm hesitant to do this now based on https://github.com/istio/istio/pull/2739#issuecomment-359608520

> - move tools up one level

I'd like to hold off on changing the top-level for now. I want this PR to focus on the pilot directory only.

> - drop "adapter" by moving adapter/config to just config/

+1

> - don't touch model

+1

> - move platform/consul to serviceregistry/consul
- move platform/cloudfoundry to serviceregistry/cloudfoundry
- move platform/eureka to serviceregistry/eureka
- move platform/kube to serviceregistry/kube
- move stuff out of kube that is not service registry (queue, admit,
inject) to kube/ directory -- these don't have cross-platform alternatives
and that needs to be made clear

Given your last bullet, I think it would be better to keep `kube`, `consul`, `cloudfoundry`, and `eureka` at the top-level and have a subdirectory for `serviceregistry` in each.

**Comment by costinm** [comment]
On Tue, Jan 23, 2018 at 7:54 AM, Nathan Mittler <notifications@github.com>
wrote:

> @costinm <https://github.com/costinm>
>
> While I don't like much the old layout, I don't think the new one is so
> much better ..
>
> Do you have suggestions for how the new layout might be improved? It would
> be good to hear what exactly you don't like and how to fix it.
>

My suggestion is to focus on fixing bugs - and the new structs/code coming
in for v2 support, which will eventually replace existing code.
Given that a lot of the code will eventually be gone ( with the gRPC/v2,
and other refactoring ) - I don't think moving the half-dead code around
helps anyone long term, but it hurts everyone who is currently familiar
with the code.



> ... to justify all the pain for people who are already familiar with the
> current one,
>
> This change makes the pilot code more consistent with mixer. I don't see
> this change as causing anyone much pain. After a time, consistency will
> likely improve the overall code navigation experience.
>

Sure, we can do this after 1.0 - and maybe make the mixer more consistent
with pilot. This is something that needs to be discussed, planned -
and done in incrementally.


> nor do I think it's a P0 to move files around
>
> Agreed, but if we can improve the consistency and navigability of the code
> base before 1.0, I think it's something we should do. Especially since
> moving files isn't very hard.
>

It is not very hard to move them - it is hard to resolve conflicts and to
find them after the move, if you are used with the old layout.

I will not say no if a small move is well justified - but this move
everything around is not ok.



> I would rather see an incremental set of changes ( and they have been
> happening), where it is a clear explanation for the new name/location. In
> particular moving the cmds to the top level ( from all components) would be
> good, and then the extra pkg/ will not be that useful.
>
> This is overkill for a simple code shuffle. We can't have that sort of
> bureaucracy and expect progress, especially on something this trivial. I've
> included a bulleted overview of the changes in the description. If you have
> specific questions regarding the changes, I'd be happy to discuss.
>

We can't have each developer decide he wants a new layout - and move files
around whenever he wants.

Sure, you may like the new layout - other people may not, should they keep
moving files around ?



> I know code layout can be a bit of bikesheding - but I don't see a good
> enough justification for this particular layout.
>
> Again, without specifics this isn't very helpful. Parts of the changes
> have a very clear justification. For example, I moved adapter/config/crd
> and adapter/config/ingress to platform/kube, because they are
> k8s-specific, where the others in that directory are platform-agnostic. I
> also moved adapter/cmd/pilot-discovery/mock to proxy/envoy/mock because
> it really should be next to the "real" discovery service.
>
> Surely you're not against all of these changes. If you have additional
> suggestions, I'm all ears.
>

+1 on moving the mock.

I'm not sure about crd - need to understand more how this will fit in the
new data structures and v2 APIs, some of the
CRD stuff may need to be decoupled from K8S. It's the kind of change that
would be better reviewed by itself, and
in context.

**Comment by kyessenov** [comment]
Yeah, last point seems reasonable. The build issues with doc, bin, docker,
etc need to be solved eventually, but necessarily here. Leave them as they
are until somebody musters the will to clean those directories.

**Comment by costinm** [comment]
Well - CRD is also an Istio concept - and may need to be mapped to Istio
struct and adapted from other registries, with
the actual loading moved to platform. We are 'importing' some k8s concepts
- we may have Ingress or some CRDs in
the other registries.

**Comment by costinm** [comment]
No, I don't think we need everyone to propose an alternative layout and
randomly select one.

There is no requirement or need to reorg the code based on anyone's opinion
- if there are changes that
are clear ( like the mock move) we should make them, otherwise we should
prioritize fixing bugs and the
new code and structs getting in a good place from the start.

I suggest the current layout as an alternative until at least 1.0 and until
new code is in place.

**Comment by costinm** [comment]
It is very difficult to provide a solution when we don't have a clear
problem.

Optimizing based on individual subjective opinions about one layout or the
other - typical
bike shedding - is not a P0 or a problem we should be spending time on at
this point.

**Comment by ZackButcher** [comment]
Nathan had to move some code around as follow up cleanup from another PR. In the process, he was trying to standardize how our code base looked relative to Istio's other components. _This is so obviously a good thing I'm shocked we're even discussing it, let alone more than 50 comments in to a PR_. Kuat's proposed directory structure looks good to me (and Nathan too I think). The change is already written, I don't see any strong reasons in this thread not to merge something that makes our codebase better structured and more understandable. Code health _is_ a feature.

I really don't think the v2 xDS stuff is very relevant; it will live in `proxy/envoy/...` and only change code there. One directory changing is no reason to hold up refactoring the entire codebase.

**Comment by nmittler** [comment]
@ZackButcher @kyessenov I've updated the description based on our discussion. PTAL.  Once we get agreement on the layout, I'll reorganize.

**Comment by kyessenov** [comment]
@nmittler the layout looks good to me except for two minor names:
- "server": what do you want to put in there? we can pick a name from there. server is not a useful name (everything is a server in microservices world)
- why is "file" under "config/kube/crd"? I'd expect it to be "config/file".

**Comment by kyessenov** [comment]
Re: top-level "pkg". I have no strong preference, but if it helps with clarity, sure, why not.

**Comment by costinm** [comment]
On Tue, Jan 23, 2018 at 10:57 AM, Zack Butcher <notifications@github.com>
wrote:

> Nathan had to move some code around as follow up cleanup from another PR.
> In the process, he was trying to standardize how our code base looked
> relative to Istio's other components. *This is so obviously a good thing
> I'm shocked we're even discussing it, let alone more than 50 comments in to
> a PR*. Kuat's proposed directory structure looks good to me (and Nathan
> too I think). The change is already written, I don't see any strong reasons
> in this thread not to merge something that makes our codebase better
> structured and more understandable. Code health *is* a feature.
>
It is not obvious this organization is the best or right or it makes things
more understandable.

I understand he has a subjective opinion on this particular org - but
that's not obvious, and we can't have anyone who feels
something would look better in a different layout just do it. Otherwise
every 5 days we'll have another code move.

Code health is a feature - but not based on arbitrary subjective decisions.
Maybe the right thing is to move mixer to this
layout, or move k8s code to top level - and have that part reused in mixer.
It's a tricky decision even for one component and
package - doing it for everything at once and assuming it's the right one
is guaranteed to fail.

**Comment by nmittler** [comment]
@kyessenov 

> "server": what do you want to put in there? we can pick a name from there. server is not a useful name (everything is a server in microservices world)

Yeah I'm not crazy about `server` either. The content of this package is general bootstrapping logic for starting all of the services that collectively comprise a `pilot` instance. It doesn't really belong under `cmd` since creation is purely programmatic. In the comment I suggested `bootstrap`, but I'm not sure it's much better. It's not terribly important what we call this ... we can always change it later.

> why is "file" under "config/kube/crd"? I'd expect it to be "config/file".

It only works on CRD-based config files.

**Comment by kyessenov** [comment]
Bootstrap is not a terrible name actually. I'm OK with it.
There's a config schema in model/config.go that subsumes CRDs. Shouldn't we depend on that instead of CRD schema? If we don't, then we might have discovered some unnecessary dependency.

**Comment by costinm** [comment]
Once again - the problem is not discussing details of the PR.

It is just not right to do this kind of changes bulk and without any
discussion or design or agreement,
or to waste people's time on this problem.

We need to improve code organization, but this is not the way to do it.

**Comment by kyessenov** [comment]
It may not be ideal to design in a PR, but it's better to do it than let it stagnate. The compromise layout is not as invasive IMHO.

**Comment by costinm** [comment]
Things are not stagnating - some of the code will be gone in few months,
and we are doing improvements as we should, in small PRs that can be
reviewed
and understood and justified.

Just moving things around so we don't 'stagnate' is not really useful, and
at this point
we need to focus on 0.5 and 0.6 and actually fixing crashes - not on
finding ideal
layout and compromise, it's something that needs a lot of thinking and
attention from
many people, including in mixer and auth (since we want to move to a
consistent and
improved layout across istio, not each component doing its own layout )

**Comment by kyessenov** [comment]
I wasn't referring to stagnating code. The PR needs some resolution.
Again, the change you have in mind only affects proxy/envoy, and it's not
even moved, so I don't follow what's the big deal.

**Comment by ZackButcher** [comment]
/lgtm

No strong feelings w.r.t `server` vs `bootstrap`. Everything else looks fine to me.

**Comment by nmittler** [comment]
@kyessenov 

> Bootstrap is not a terrible name actually. I'm OK with it.

cool ... updated the description.

> There's a config schema in model/config.go that subsumes CRDs. Shouldn't we depend on that instead of CRD schema? If we don't, then we might have discovered some unnecessary dependency.

Possibly, but for now I don't want to actually change code in this PR.  It's CRD-specific, so I think I should keep it under CRD until that changes.

**Comment by kyessenov** [comment]
Cool, as long as you document the reason for placing "file" under "crd" and
adding a TODO to fix that, LGTM.

**Comment by costinm** [comment]
I think this PR needs to be broken up, discussed before hand - and should
not be submitted as is.

For the smaller changes I would want to see things prioritized and take
into account the cost on
existing developers working on 1.0 and having to spend time to merge and to
get used with
the new locations.

But since there is no P0 or clear benefit of moving files around - I would
suggest dropping this PR
and doing incremental changes ( and in general - we should document and
make it clear that
for such large changes it is not ok to start with a PR)

**Comment by kyessenov** [comment]
Is there anyone else that would like to have a formal review for the change except @costinm ?
I think most folks are OK making this change, or at least voiced recommendations that seem to be acted upon.

cc @louiscryan

**Comment by louiscryan** [comment]
Moving code around to facilitate codebase understanabilty is a feature, I'm
with Zack on that. Modern tooling makes these types of changes relatively
straightforward to produce and consume so if there's general consensus that
this change is an improvement then it should proceed.

@ijsnellf <https://github.com/ijsnellf> - Could you do a trial merge to see
how disruptive this feels before we submit ?

@costinm - I don't believe this type of change requires a heavy review
process if we have reasonable consensus here. Also if this change proves to
be easily consumed I don't think we should be too reluctant to make similar
changes in the future as we will almost certainly have to do.

**Comment by costinm** [comment]
We have been incrementally moving code around for a long time, and I'm not
opposed to that,
obviously we need to refactor and improve the code base.

My main point was that bulk move is not the best way to do it - in
particular when we're struggling to
cut a release. Incremental changes work better.

 Regarding review process - I'm not suggesting any heavy process, but code
organization should
be consistent across istio and take into account all components. For
example we need to merge the
2 agents ( pilot and security ), some code should move to top level pkg if
it can be reused
or is general purpose - and some code will simply be gone as soon as we
move to the new
data structures and we should waste time moving it before it is deleted
instead of focusing on the
new code.

Sending an email with the proposed code organization - so mixer, security,
broker can also
review and start moving into the same layout - doesn't seem  'high
process'. Breaking this
into manageable pieces will also help - for example all 'cmd' from all
components may
be better of at top level ( istio.io/istio/cmd/pilot-discovery ), with
generic code in istio/pkg - instead
of istio/pilot/pkg, istio/mixer/pkg. People already did this for log, some
of the k8s-related stuff
can go there as well.

But back to the point - it's quite reasonable to request that a large
change is broken in smaller
pieces, and avoid the critical time when we are fighting to cut a release
after another major
change moving all files around ( single-repo ) and the switch to a new
build, and a 3-month
fast-forward on envoy. People should have their attention of the crashes
and critical bugs
for the next weeks - not have to find their way around in the code base.

There is a time and a good way to do refactoring and code reorg - and there
is a time to
focus on keeping things stable and fix the bugs/ stabilize the code.

The other important aspect is that the new hybrid model (new structs) and
the new v2 APIs
will have a pretty big impact on code org, and I would like to review this
kind of PRs after.

**Comment by rshriram** [comment]
I think my comment on the dataplane got misread. What I suggested was this 
pkg/dataplane/v1,v2 and pkg/proxy/envoy/(non config specific code like watchers, may be discovery servers, etc). 

I am not opposed to this code move, but may be as a compromise (with @costinm), we wait until the 0.5 release (today/tomorrow) and Isaiah’s foreign services merges (in two to three days)? This way v1apha2 will be fully done (except for gateway).

**Comment by costinm** [comment]
As a compromise - if we must merge this PR (and repeat the pain from the
last bulk move ) - please wait at least until the new model for hybrid gets
in,
and move all agent related stuff to istio/agent - so we don't have to move
it again ( including watchers and all stuff that runs in the proxy ).

I would also like the cmd to be top level (
istio.io/istio/cmd/pilot-discovery instead of
istio.io/istio/pilot/cmd/pilot-discovery, etc)

I don't think 0.5 will happen today or tomorrow - we have crashes in envoy
that will take few days to fix, and we haven't even
started testing. Knowing the aversion to branches - and the pain to do the
fixes in branch when master just gets a massive
reorg - please wait until 0.5 is actually released..


On Jan 24, 2018 08:30, "Shriram Rajagopalan" <notifications@github.com>
wrote:

I think my comment on the dataplane got misread. What I suggested was this
pkg/dataplane/v1,v2 and pkg/proxy/envoy/(non config specific code like
watchers, may be discovery servers, etc).

I am not opposed to this code move, but may be as a compromise (with
@costinm <https://github.com/costinm>), we wait until the 0.5 release
(today/tomorrow) and Isaiah’s foreign services merges (in two to three
days)? This way v1apha2 will be fully done (except for gateway).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/istio/istio/pull/2739#issuecomment-360191733>, or mute
the thread

**Comment by nmittler** [comment]
@costinm @rshriram I'm fine with waiting a bit.  When will the other PRs land?

**Comment by costinm** [comment]
Hope model will land soon after 0.5 is cut.

Waiting will also allow more time for people working on other components to
review this and see how it fits with the broader istio organization.
It is hard to understand all the changes at once.

In particular:
- bootstrap is very confusing - agent is generating envoy bootstrap config,
while the bootstrap package seems to configure the http mapping ? What is
it bootstraping ? Should we have
each component in istio use this convention ? What does mixer/security use
?

- why do we have both kube/ and serviceregistry/kube and config/kube ?

- we eventually need to move cmd for each component to top level ( for
consistency and to avoid redundency ), and to get rid of the bin/ and old
Makefile and docker in each component,
moving them to top level. Assuming we also consolidate the integration
tests under top-level tests ( since they're supposed to test integration
across components ),
do we still need pilot/pkg ? The pkg is usually used at the top-level, to
keep things separated from cmd.

- mixer is missing support (AFAIK) for consul and other registries. Can you
confirm if they plan to reinvent and reimplement all registries - or plan
to use a pilot API, or could
reuse pilot registries ? If so, they should go under
istio.io/istio/pkg/registries..

**Comment by ZackButcher** [comment]
> - why do we have both kube/ and serviceregistry/kube and config/kube ?

Because we have kubernetes dependencies along multiple dimensions. One of the big wins of this restructuring is calling these `kube` dirs out under each place where we use k8s things.

> - we eventually need to move cmd for each component to top level ( for
consistency and to avoid redundency ), and to get rid of the bin/ and old
Makefile and docker in each component,
moving them to top level. Assuming we also consolidate the integration
tests under top-level tests ( since they're supposed to test integration
across components ),
do we still need pilot/pkg ? The pkg is usually used at the top-level, to
keep things separated from cmd.

Yup, I think we can safely dump the `pkg` dir when that happens.

> - mixer is missing support (AFAIK) for consul and other registries. Can you
confirm if they plan to reinvent and reimplement all registries - or plan
to use a pilot API, or could
reuse pilot registries ? If so, they should go under
istio.io/istio/pkg/registries..

Mixer has a different model for this; those registries will be adapters in the `istio/contrib` repo.

**Comment by kyessenov** [comment]
Sharing package is a red herring here, and we should not diverge into that
discussion.
This is pure rename of files, no code changes.

**Comment by kyessenov** [comment]
Bootstrap is envoy terminology, so it seems natural to me, and I guess
Nate, since he proposed it first.

**Comment by costinm** [comment]
If the bootstrap package is indeed generating envoy bootstrap file - sure,
it's natural.

But it seems bootstrap is doing something else - setting the REST mappings.
And somehow the name ended up in
all other packages ( mixer, broker, auth ).

We should obviously have a bootstrap package for proxy-agent generation of
the envoy bootstrap.
I don't remember seeing the package bootstrap used in any other code ( in
istio or outside) for http init.

**Comment by rosenhouse** [comment]
The rebase of #2714 will be ok, and we've got more work to do on it anyhow.  Let's merge!

**Comment by kyessenov** [comment]
/lgtm then
git stuff looks fine, just file moves, with little renaming here and there.

**Comment by ldemailly** [comment]
@kyessenov 

> /lgtm then

you need to not have the "then" if you want this to get lgtm label

**Comment by kyessenov** [comment]
/lgtm
we need to fix the regex to be a bit smarter :)

**Comment by rosenhouse** [comment]
isn't it supposed to get auto-merged now, by a robot?

**Comment by kyessenov** [comment]
Yes, it's in queue. The bot only recognizes "/lgtm" as a single-line, which we could improve to "/lgtm some-text".

**Comment by kyessenov** [comment]
This has no effect on stability. It deliberately makes no code change. git can take care of auto-merging (and besides if you do run into merge problems, chances are the changes there are more important to deserve attention). Why are you blocking the merge?

**Comment by kyessenov** [comment]
The whole point of regular releases was to avoid freezing the development and making last minute scrambling to get things in. We should follow regular processes, and release at regular intervals. I don't understand your resistance to making incremental progress, when we have 60 PRs in line waiting for some action.

**Comment by nmittler** [comment]
@costinm 

> there are quite a few changes in mixer, broker, security replacing 'server' with bootstrap that don't make any sense.

Yup, I see it ... will fix in a follow on shortly.

**Comment by costinm** [comment]
Since this PR got merged (just before 0.5) and a lot of previously approved
PRs are now blocked and un-approved by
the forced rebase/merge - it would be great if everyone involved in this PR
would spend some time approving and
unblocking other developers PRs that had been affected.

I am quite unhappy that this couldn't be delayed and split into smaller
PRs, and I hope in future people will be a bit
more careful around releases and with breaking large changes..

**Comment by kyessenov** [comment]
Examples? Jason's PR got auto-merged AFAIK.

**Pull request merged**
