### PR TITLE
Switching secretcontroller to use envoyv2

### PR DESCRIPTION
**Pull request by sbezverk**
Original secret controller was using envoy v1 api. This PR switches to envoy v2 api.
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

### CODE REVIEW

**Comment by sbezverk** [comment]
@gyliu513 If you still have your multi cluster test bed, could you please test this PR, it switches from envoyv1 to envoyv2 service discovery.

**Comment by rshriram** [comment]
Cc @GregHanson

**Comment by gyliu513** [comment]
@sbezverk  code looks good, will do a test later when my env back.

**Comment by gyliu513** [comment]
@sbezverk it works fine

**Pull request merged**
