### PR TITLE
run dep prune to cleanup unused files

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
previsou dep version introduced many unused files,eg. `LICENSE` `_test.go`

run dep prune to remove these useless files to reduce the repo capacity.

### CODE REVIEW

**Comment by ldemailly** [comment]
not sure which exact command (can you document it) you ran but there is a reason some repos had more files - for instance 
https://github.com/istio/istio/blame/master/Gopkg.toml#L332-L361

also now it seems the lock file and vendor are out of sync

cc @costinm (fyi) @ostromart  (for license file removal) @nmittler (vendor)

**Comment by ostromart** [comment]
The license files are a legal requirement and must be restored.

**Comment by ayj** [comment]
```bash
$ dep check
# vendor is out of sync:
code.cloudfoundry.org/copilot: hash of vendored tree not equal to digest in Gopkg.lock
github.com/BurntSushi/toml: hash of vendored tree not equal to digest in Gopkg.lock
github.com/apache/thrift: hash of vendored tree not equal to digest in Gopkg.lock
github.com/envoyproxy/go-control-plane: hash of vendored tree not equal to digest in Gopkg.lock
github.com/gogo/googleapis: hash of vendored tree not equal to digest in Gopkg.lock
github.com/gogo/protobuf: hash of vendored tree not equal to digest in Gopkg.lock
github.com/grpc-ecosystem/go-grpc-middleware: hash of vendored tree not equal to digest in Gopkg.lock
github.com/hashicorp/consul: hash of vendored tree not equal to digest in Gopkg.lock
github.com/hashicorp/go-rootcerts: hash of vendored tree not equal to digest in Gopkg.lock
github.com/hashicorp/serf: hash of vendored tree not equal to digest in Gopkg.lock
github.com/hashicorp/vault: hash of vendored tree not equal to digest in Gopkg.lock
github.com/imdario/mergo: hash of vendored tree not equal to digest in Gopkg.lock
github.com/onsi/ginkgo: hash of vendored tree not equal to digest in Gopkg.lock
github.com/open-policy-agent/opa: hash of vendored tree not equal to digest in Gopkg.lock
github.com/prometheus/client_model: hash of vendored tree not equal to digest in Gopkg.lock
github.com/spf13/cobra: hash of vendored tree not equal to digest in Gopkg.lock
github.com/square/certstrap: hash of vendored tree not equal to digest in Gopkg.lock
golang.org/x/tools: hash of vendored tree not equal to digest in Gopkg.lock
istio.io/api: hash of vendored tree not equal to digest in Gopkg.lock
k8s.io/cluster-registry: hash of vendored tree not equal to digest in Gopkg.lock
k8s.io/helm: hash of vendored tree not equal to digest in Gopkg.lock
k8s.io/kubernetes: hash of vendored tree not equal to digest in Gopkg.lock
```

**Comment by gyliu513** [comment]
Do we have some detailed process for this? As well as the `dep` version requirement for this? I think we should add this to dev guide as well.

**Comment by hzxuzhonghu** [comment]
@ayj @ldemailly I do not remember how to reproduce this. Seems weird, and now the right way is to re-run `dep ensure` to restore. 

But seems this global prune setting does not take effect
```
[prune]
  go-tests = true
  unused-packages = true
  non-go = true
```

**Comment by ostromart** [comment]
@gyliu513 there's no dep process specific to istio, everything is per the official dep documentation.
For adding dependencies we have: https://github.com/istio/istio/wiki/Vendor-FAQ#how-do-i-add--change-a-dependency
We don't expect people to be pruning the vendor dir manually so I don't think having a process for that would be appropriate, it should be done by editing Gopkg.toml. By all means feel free to submit PRs that edit Gopkg.toml if you feel something could be tidied up or improved. After reading the dep docs, the Gopkg.toml should be fairly easy to follow. Ping me or istio-dev if you have questions about any specific items in that file.

**Comment by gyliu513** [comment]
@ostromart Yes, this would help.

I also heard from @hzxuzhonghu , it seems using `dep` version other than `0.5.0` will cause build failed, @hzxuzhonghu can you help confirm? If so, we may need to update the wiki page a bit to highlight the `dep` version as well?

**Comment by ostromart** [comment]
fyi https://github.com/istio/istio/pull/8036 should indirectly fix this.

**Pull request merged**
