### PR TITLE
Raise default protocol detection timeout

### PR DESCRIPTION
**Pull request by bianpengyuan**
This is to accommodate slow client, fixes https://github.com/istio/istio/issues/24379

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@rshriram @howardjohn @costinm ptal, thanks!

**Comment by bianpengyuan** [comment]
I think inbound is not affected by the default here. It is overridden by a flag or env var.

**Comment by howardjohn** [comment]
good point - didn't remember that. So there is still the question of all outbound vs outbound on 0.0.0.0 HTTP only. Probably all outbound is fine...

**Comment by nrjpoddar** [comment]
This should probably be cherry-picked to release-1.5 branch too?

**Comment by bianpengyuan** [comment]
IIUC the change add http inspector to outbound listener is only in 1.6: https://github.com/istio/istio/pull/17169 so no need to cherry-pick to 1.5.

**Pull request merged**
