### PR TITLE
fix: increase 100% test coverage for find_errorline_utils_test.go

### PR DESCRIPTION
**Pull request by youhonglian**
**Please provide a description of this PR:**
Increase 100% test coverage for find_errorline_utils_test.go
Ref: https://github.com/istio/istio/issues/37354

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
if you want to increase test coverage, can you do that for some complex function

THis looks meaningless to me

**Comment by GregHanson** [comment]
might be better to move the testing to the  `pkg/config/analysis/analyzers/annotations/` where annotations.go and maturity.go both make calls to the function

**Pull request closed without merging**
