### PR TITLE
add istio proxy dependencies file to proxy images

### LINKED ISSUE #6572: Provide an easy way to trace which envoy version is being used in the proxy_debug and release docker images
@mdhume commented on [Tue Jan 30 2018](https://github.com/istio/old_issues_repo/issues/176)

**Is this a BUG or FEATURE REQUEST?:** Feature Request

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Feature Request:**
Y

**Describe the feature:**

Currently to figure out which envoy version is being used, one would need to trace back by using the docker SHA specified in the pilot repo to the git SHA in the proxy repo, to get the git SHA of the envoy repo.
Even in the docker container version command returns `/usr/local/bin/envoy  version: 0//DEBUG`

Would it be possible to expose this more explicitly as part of the docker or part of the github repo itself?

### PR DESCRIPTION
**Pull request by elevran**
Adds file with SHA of dependencies used Istio proxy to the images.

Fixes #6572 
After this PR is merged, documentation should be added to inform users how to get the versions from the images.

### CODE REVIEW

**Comment by linsun** [comment]
@elevran do we expect users to exec into the proxy container and cat this istio.deps file for envoy proxy SHA?

**Comment by elevran** [comment]
> @elevran do we expect users to exec into the proxy container and cat this istio.deps file for envoy proxy SHA?

They can either do that or run the image locally in interactive mode to get the data.

In the cases this is needed (beyond getting the official release number, such as `1.10`, from envoy's admin interface) it may be reasonable to do so. I'm open to other suggestions if there are any. The constraint is that envoy code should be treated as "sealed" at the point of building the container.
I can try to make these accessible as image labels instead. do you thin that would a be better option? We don't seem to use labels on any images (labels, not tags).

**Comment by linsun** [comment]
@elevran I think label on the image would be good because you could easily inspect an image using `docker inspect`, or we could do both so you can get it via runtime too :).

**Comment by elevran** [comment]
superseded by #11524

**Pull request closed without merging**
