### PR TITLE
add timestampNow() for mixer config

### PR DESCRIPTION
**Pull request by theganyo**

### CODE REVIEW

**Comment by mandarjog** [comment]
@theganyo can you add some description as to why this is needed?

`request.time` and `context.time` are supposed to provide specific time values.
Is there an additional use case for `time.Now()` ?

**Comment by theganyo** [comment]
My immediate use case was for testing - it's nice to have a way to have some kind of reasonable generated default for the time data type instead of just hard-coding a timestamp() value. Other use cases? I guess I could conceivably see it being used for logging or internal latency calculation.

**Comment by mandarjog** [comment]
can you use `context.time` or `request.time` ?

**Comment by douglas-reid** [comment]
@mandarjog unless i'm missing something, your solution still requires specifying `-t context.time="XXXX-XX-XXTXX:XX:XXZ"` for each `mixc` call -- which I think might be the motivation here.

Perhaps we could add logic to `mixc` to automatically generate and include `context.time` for all calls?

**Comment by mandarjog** [comment]
Yes, ‘context.time’ is not being populated per spec inside mixer. That is what this PR should do.
A soon as the call is received at Mixer context.time should be established.

**Comment by ozevren** [comment]
@mandarjog did we have this working before? I tried searching repo history (around October timeframe) and have only found references to it.

We can add one during the initial bag creation for request. Does that sound reasonable? Do we need to worry about attribute references in that case?

**Comment by douglas-reid** [comment]
@ozevren adding one at bag creation time seems reasonable. I would think that we would not track refs to `context.time`. Adding it to a cache-key seems problematic.

**Comment by ozevren** [comment]
Here is my initial stab:
https://github.com/istio/istio/pull/3567. PTAL and comment. (This should be available during preprocess and also not be refcounted)
If looks good, I can make this a full PR.

**Comment by ozevren** [comment]
@douglas-reid : Do we have a way to tag a result as "do-not-cache"?

For the general case, I think any expression/result is a bit suspect for caching, if it references highly ephemeral values, such as time.  If we don't track references to context.time (or not mark the result as do-not-cache) it would be easy to accidentally poison the cache.

Besides, do we actually need context.time? Feels like this can easily be obtained by the adapter by a time.Now() Go call. What am I missing?

**Comment by ozevren** [comment]
I don't want to leave this hanging, so just to finish this to a resolution:
Do we actually n

**Comment by mandarjog** [comment]
We do need `context.time()` so that a uniform `time.Now()` is available as an attribute during the instance generation phase.
We can/should add `context.hour` `context.minutes` etc ... as well at some point.

**Comment by douglas-reid** [comment]
@ozevren totally agree about not caching ephemeral values, like time. we've discussed a bunch of approaches to that in the past, but I don't think we ever implemented any of them completely.

**Comment by ozevren** [comment]
@douglas-reid Opened https://github.com/istio/istio/issues/3825 to track that issue.

**Comment by theganyo** [comment]
Ok, it sounds like the root reasons for this will be better handled in other ways. I'll close.

**Pull request closed without merging**
