### PR TITLE
Work around upstream chart bugs/remove `managed-by` from templates (which are never managed)

### PR DESCRIPTION
**Pull request by bleggett**
**Please provide a description of this PR:**
Also in kiali at least, fix this at the source so we don't have to mess with it again: https://github.com/kiali/helm-charts/pull/294

Also fix the genscript (use `yq`, and use `helm` as the binary, `helm2` hasn't shipped for years) and mention the existence of the genscript.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Why does this matter? Also this is all scripted in manifests/addons/gen.sh so will be reverted

If 4/4 charts we happen to sample -- which happen to include 2 of the most popular charts -- have this "bug", is it really a bug at that point...

**Comment by bleggett** [comment]
> Why does this matter? Also this is all scripted in manifests/addons/gen.sh so will be reverted

Ah, there is a gen script. I missed that. ty.

**Comment by bleggett** [comment]
> Why does this matter? 

Because it effectively marks things that were not installed by Helm as being managed by Helm, which will (potentially) confuse both Helm and other tools.

It's also just not needed.

> If 4/4 charts we happen to sample -- which happen to include 2 of the most popular charts -- have this "bug", is it really a bug at that point

A popular bug, I will grant you.

**Comment by bleggett** [comment]
@howardjohn Your call. If you don't want this we can close the PR.

**Comment by bleggett** [comment]
Closing this as 2/4 (soon 3/4) of the PRs opened in the upstream chart repos to fix this have merged, obviating this local workaround.

**Pull request closed without merging**
