### PR TITLE
Update description for istioctl main commands

### PR DESCRIPTION
**Pull request by shamsher31**
These are the main commands and not subcommands.

`istioctl install`
`istioctl manifest`
`istioctl operator`
`istioctl profile`

### CODE REVIEW

**Review by esnible — CHANGES_REQUESTED** [review]
Thanks for looking at the grammar!  I like that you are removing mentions of subcommands that are no longer present.

The word "subcommand" is used to indicate any command that isn't the name of a binary invokable from _bash_.  For example, see https://gobyexample.com/command-line-subcommands .  Perhaps we should continue using the term "subcommand" in Istio for the top-level istioctl commands?

**Comment by shamsher31** [comment]
> The word "subcommand" is used to indicate any command that isn't the name of a binary invokable from _bash_. For example, see https://gobyexample.com/command-line-subcommands . Perhaps we should continue using the term "subcommand" in Istio for the top-level istioctl commands?

I see, If I consider it from the user (DevOps, cluster-admin) point of view the `subcommands` appears to me that it is a sub-part of the main command. eg:

`profile` is a main command:
```
$ istioctl profile
```
and the following are sub-command of `profile`.
```
  diff        Diffs two Istio configuration profiles
  dump        Dumps an Istio configuration profile
  list        Lists available Istio configuration profiles
```
So I can use 
```
$ istioctl profile list
```
Technically `subcommand` looks ok, but from the user point of view I think we should at least not right subcommand for `list`, `diff` and `dump`. 

@esnible Does it make sense?

**Comment by esnible** [comment]
I will ask for opinions at tomorrow's UX meeting.

**Review by esnible — APPROVED** [review]
After talking with the UX Working group we agree it is OK to call top-level _istioctl_ items "commands".

**Comment by shamsher31** [comment]
Thanks @esnible

**Review by sdake — APPROVED** [review]

**Pull request merged**
