### PR TITLE
Sync missed changes from operator

### PR DESCRIPTION
**Pull request by ostromart**
These are from a manual diff with istio/operator master.

### CODE REVIEW

**Comment by ostromart** [comment]
This is failing because of racetest which is fixed in https://github.com/istio/istio/pull/20145/files.

**Review by morvencao — APPROVED** [review]

**Comment by howardjohn** [comment]
@ostromart this needs a rebase

**Review by richardwxn — APPROVED** [review]

**Comment by howardjohn** [comment]
@ostromart is this obsolete?

**Pull request closed without merging**
