### PR TITLE
fix for init.sh to download and install `dep` properly. fixes https:/…

### PR DESCRIPTION
**Pull request by christian-posta**
…/github.com/istio/istio/issues/2499

### CODE REVIEW

**Comment by christian-posta** [comment]
@kyessenov i've updated the PR to take into account giving priority to an already existing `dep` vs downloading one. take a look when you get a chance; thanks!

**Comment by mattdelco** [comment]
It might be worthwhile to also unset GOARCH.

I'm torn on what to what to make of allowing an outside dep and which to favor.  From a built hermetics/isolation standpoint it's generally better to favor what the build provides for itself, but we currently don't lock down the version of dep (and I'm not sure there will be a decent way to do this), so if this trend continues then the next-best seems to be to have dep be pre-installed in a system and have the build use that.

**Comment by kyessenov** [comment]
Thanks, looks good to me.

@mattdelco : we control the version of dep utilized by the build container. If for some reason, `dep` breaks between versions, we can build using the saved version of dep in the container.

**Comment by christian-posta** [comment]
any chance i can get a lgtm? @sdake @kyessenov

**Comment by rshriram** [comment]
Sorry for the delay. please fix the merge conflict @christian-posta

**Pull request merged**
