### PR TITLE
Fuzzing: Add CIFuzz

### PR DESCRIPTION
**Pull request by AdamKorcz**
**Please provide a description of this PR:**

This adds CIFuzz to Istios OSS-fuzz integration. Upon merging this PR, Istios fuzzers will run in the CI for 1200 seconds when a pull request is made. 

When https://github.com/istio/istio/pull/35727 gets merged, the 1200 seconds should be increased significantly.

Documentation for CIFuzz can be found at: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

### CODE REVIEW

**Comment by AdamKorcz** [comment]
If this PR can be rejected, feel free to close it.

**Comment by howardjohn** [comment]
I think we can close this. Having fuzzers run in our CI I think is useful, but it would need to be in prow. IMO we can wait 3 months for go 1.18 which will make it much simpler. Thanks for the PR!

**Comment by jonathanmetzman** [comment]
> I think we can close this. Having fuzzers run in our CI I think is useful, but it would need to be in prow. IMO we can wait 3 months for go 1.18 which will make it much simpler. Thanks for the PR!

We actually do support Prow. If youre interested in running CIFuzz, I can work on docs and we could even do a video meeting so I can help you set it up if needed.

**Comment by howardjohn** [comment]
Ah cool. I assume this would be https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/prow/?

Will there be support for go 1.18 fuzzing eventually? If so it may be desirable to wait for that to avoid too many changes in this area. Our core fuzzing is https://github.com/envoyproxy/envoy which is completely separate from this project (in terms of CI), so the fuzzers here are not the top priority that would make sense to invest much effort ifwe will change things in 2 months.

**Comment by AdamKorcz** [comment]
> Will there be support for go 1.18 fuzzing eventually?

Yes. This will be added in 2022.

**Comment by jonathanmetzman** [comment]
> Ah cool. I assume this would be https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/prow/?

Right. I just need to change that document to be CIFuzz specific instead of ClusterFuzzLite specific (both projects use the same code under the hood).

**Pull request closed without merging**
