### PR TITLE
Add contents of install/ansible to release script

### PR DESCRIPTION
**Pull request by geoand**
Since I am not particularly knowledgeable with Istio release scripts, this might be wrong.
However it did work for me locally and seems to be in line with the way the rest of assets are packaged

### CODE REVIEW

**Comment by geoand** [comment]
@sdake You were right, I had an old master :(. I rebased the PR on to the latest master. Can you please check?

**Comment by sdake** [comment]
I would recommend just integrating here: https://github.com/istio/istio/blob/master/release/create_release_archives.sh#L113

add *.cfg, *.yml, and *.j2.  That should get things going.

@sebastienvas may want a different approach, but I think this makes the most sense.

**Comment by geoand** [comment]
@sdake I was pondering that, but I was afraid it might add files we don't want.

Do you think it's safe?

**Comment by sdake** [comment]
@geoand I am not well-versed in the release process, however, reading that find command, it finds all files in istio/install that should go in the release tarball.  I believe is it safe to say .yml files, .cfg files, and .j2 files are always related to install and should be specified individually rather than calling out a specific directory.

Also as a further followup work, it may make sense to move the ansible dir into the install/kube directory (since the Ansible code is kubernetes specific and doesn't handle other aspects of installation on different platforms.

Cheers
-steve

**Comment by geoand** [comment]
Thanks for the comments @sdake!

I updated the script to not use the `install/ansible` directory and instead use the specific file types.
Would you like me to also move the content of the `ansible` directory into `install/kubernetes` like you mentioned?

**Comment by sdake** [comment]
@geoand yes I was thinking about the fact that the Ansible directory is in the wrong parent and why that was the case this weekend as I was reworking your Ansible documentation.  I hadn't picked up the incorrect parenting for your Istio specific deployment playbook.

@andraxylia had requested in the past an Ansible implementation that automates mesh expansion.  After seeing mesh expansion executed, I agree that needs to be done.

I'll leave the question to her to answer as the choice impacts mesh expansion.

Cheers
-steve

**Comment by sdake** [comment]
@andraxylia please weigh in on comment https://github.com/istio/istio/pull/4623#issuecomment-378294185.

Cheers
-steve

**Comment by sdake** [comment]
@geoand please ping on this PR Monday if no action has been taken.  I would like to see this merge prior to 0.8 (~5-10 days before branching) so the Ansible playbooks are not DOA.

**Comment by geoand** [comment]
Sure thing!

Thanks

**Comment by andraxylia** [comment]
I will let @sebastienvas review, he has knowledge of the release script.

**Comment by geoand** [comment]
@sdake Do we have any update on this?

Thank you very much

**Comment by sdake** [comment]
/assign @sebastienvas 

@geoand I don't have an update - I don't have ACLs to merge files in this directory.  (Check OWNERS file).

**Comment by geoand** [comment]
Thanks for the update @sdake !

**Comment by andraxylia** [comment]
@sdake @geoand I would really like to see ansible for mesh expansion, and I bet I am not the only one.

**Comment by andraxylia** [comment]
I agree the current /install directory where ansible for k8s is not under kubernetes does not make sense, and I forgot the reason why it was added there. 
We still have to decide where ansible for mesh expansion will leave, right now mesh expansion is also under kubernetes. We will need to separate it and possible re-organize the directory layout, but it does not have to be part of this PR.

**Comment by geoand** [comment]
I am not familiar with mesh expansion, but I'll have a look soon and see if I can use Ansible for it

**Comment by geoand** [comment]
@andraxylia @sdake Do this PR needs to be updated or can we merge it so the contents of the ansible playbook will be available in the next release?

**Comment by sdake** [comment]
I asked the question here: https://groups.google.com/forum/#!topic/istio-dev/grGYrymC-xc

**Comment by geoand** [comment]
Thanks @sdake

**Comment by andraxylia** [comment]
pending required test ci/circleci: e2e-pilot-auth-v1alpha3-v2

**Comment by tvieira** [comment]
I have tested this PR and it includes the additional 25 files from the install/ansible directory. It would be great to have the Ansible installer in the 1.0 release.

**Comment by geoand** [comment]
Closing in favor of #7194

**Pull request closed without merging**
