### PR TITLE
Add some missing fields in zipkin template in tracing subchart

### PR DESCRIPTION
**Pull request by mathspanda**
To be consistent with jaeger template in tracing subchart, this pr add some missing fields in zipkin template.
1. add field `priorityClassName`
2. add field `nodeAffinity`
3. add sidecar annotation

Signed-off-by: mathspanda <mathspanda826@gmail.com>

### CODE REVIEW

**Comment by ymesika** [comment]
@douglas-reid lgtm if you are ok with it too

**Comment by douglas-reid** [comment]
@ymesika lgtm

**Comment by ymesika** [comment]
@mathspanda Please rebase

**Comment by mathspanda** [comment]
Rebase down. @ymesika  Tests on branch master looks like all down.

**Pull request merged**
