### PR TITLE
Adding support for startup probe.

### PR DESCRIPTION
**Pull request by luckoseabraham**
Currently startup probes have no support with rewriteAppHTTPProbe. Adding it for [24203](https://github.com/istio/istio/issues/24203)

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jdomag** [comment]
It which istio release can we expect this feature to be included?

**Comment by ogerardin** [comment]
Has this been included in any release yet? I can't find any trace...

**Comment by howardjohn** [comment]
#26887

**Comment by ogerardin** [comment]
> #26887
> […](#)

So in summary: 1.7
Thanks.

**Pull request merged**
