### PR TITLE
Update the dependency on Istio API repo

### PR DESCRIPTION
**Pull request by lei-tang**
Update the dependency on Istio API repo

### CODE REVIEW

**Comment by hklai** [comment]
Why is this needed? The changes look a lot more than updating the dependency on Istio API repo

**Comment by lei-tang** [comment]
This PR is per the request from @rkpagadala since the last update on the api dependency was 6 days ago. The changes in the PR are the result of running: dep ensure --update istio.io/api. 
The go version is go1.10.3 linux/amd64; the dep has been updated to the latest version by running: go get -u github.com/golang/dep/cmd/dep

**Comment by lei-tang** [comment]
Close this PR because there is another PR (https://github.com/istio/istio/pull/7372) with smaller diff pending that does the same update.

**Pull request closed without merging**
