### PR TITLE
Remove RequireSingleCluster() within security integration tests

### PR DESCRIPTION
**Pull request by jtrbs**
This PR is the first step to convert security integration tests to multicluster supported. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
Perfect - i was just looking into make multicluster ingress SDS tests

**Comment by jtrbs** [comment]
@howardjohn cool I will start converting each security tests in follow up PRs.

**Comment by stevenctl** [comment]
This is good so you can see if anything fails just by allowing the tests to run in multicluster mode. I'd really advise starting with things to speed up the tests (re-using echos and consolidating suites) before getting to deep into converting the actual tests. The sooner we can mark the multicluster job required, the less likely it is you'll need to go back and fix things that break along the way.

**Comment by stevenctl** [comment]
https://prow.istio.io/?pull=27365&job=integ-security-multicluster-tests_istio

**Comment by jtrbs** [comment]
@stevenctl thanks! I will work on that in the follow up PR.

**Review by stevenctl — APPROVED** [review]

**Review by incfly — APPROVED** [review]

**Pull request merged**
