### PR TITLE
Fix setting canonical-revision in ingress and egress gateways

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

I noticed that ingress and egress gateways set `service.istio.io/canonical-revision` based on control plane revision instead of workload revision as the [doc](https://istio.io/latest/docs/reference/config/labels/) says. This is inconsistent with sidecars and injected gateways which set that label based on `app.kubernets.io/version` or `version`. Additionally, control plane revision is set in `istio.io/rev`.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
My concern here is that we don't actually *have* `version` or `app.kubernetes.io/version` set on this, so it will always default to `latest`...?

**Comment by jewertow** [comment]
Yes, both gateways don't have set versions by default, but a user can set it manually:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  revision: rev-1
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
  values:
    gateways:
      istio-ingressgateway:
        labels:
          app.kubernetes.io/version: v1
```

I don't know if users do it, but my motivation is to set `canonical-revision` consistently in all components, because it's really misleading when a user wants to scrape metrics with revision label.

**Comment by howardjohn** [comment]
> Yes, both gateways don't have set versions by default, but a user can set it manually:
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> metadata:
>   namespace: istio-system
> spec:
>   revision: rev-1
>   components:
>     ingressGateways:
>     - name: istio-ingressgateway
>       enabled: true
>   values:
>     gateways:
>       istio-ingressgateway:
>         labels:
>           app.kubernetes.io/version: v1
> ```
> 
> I don't know if users do it, but my motivation is to set `canonical-revision` consistently in all components, because it's really misleading when a user wants to scrape metrics with revision label.

I think the motivation is fair but I am a bit worried about impact on upgrade. I suspect 99% of users don't set the label like you mentioned. Maybe we can default to revision if its not set, best of both worlds?

**Comment by jewertow** [comment]
Defaulting to revision does not solve the problem of inconsistency. Currently, we have the following situation:
1. Sidecars:
`service.istio.io/canonical-revision: <app.kubernets.io/version, version or "latest">`
2. Injected gateways:
`service.istio.io/canonical-revision: <app.kubernets.io/version, version or "latest">`
`istio.io/rev=<cp-revision>`
3. Default gateways:
`service.istio.io/canonical-revision: <cp-revision or "latest">`
`istio.io/rev=<cp-revision>`

So it's really hard to draw conclusions from these labels.

**Comment by howardjohn** [comment]
Its not really the same to compare sidecars though - the labels are *their own user apps*. A gateway is an Istio app.

If we think that ~no one has a version label on gateway, then why do we want to set it to `latest` all the time when it previously was something at least somewhat useful?

Regardless of what is correct, I have seen users commonly use this as a `selector` in service with https://istio.io/latest/docs/setup/additional-setup/gateway/#canary-upgrade-advanced upgrades, so this would be a breaking change IMO. I am fine with allowing us to use version if its set, but changing the default behavior is not appropriate IMO.

**Comment by jewertow** [comment]
> I am fine with allowing us to use version if its set, but changing the default behavior is not appropriate IMO.

Ok, I understand your point of view.

**Comment by howardjohn** [comment]
Just to be clear I wasn't suggesting you close this but rather set the default if version is unset to `revision`. I am also fine with closing though.

**Comment by jewertow** [comment]
@howardjohn I still want to clean up labels, so I changed this PR as you suggested. Setting version explicitly to remove revision also works for me.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
