### PR TITLE
Add resourceFieldRef.divisor to resolve permadiff

### LINKED ISSUE #53001: Istio perpetually out of sync due to missing resourceFieldRef.divisor
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We deploy Istio via ArgoCD. We see a perpetual diff in the `istio` chart because of missing `resourceFieldRef.divisor`. This issue has also impacted other projects:
- https://github.com/crossplane/crossplane/issues/4509
- https://github.com/traefik/traefik-helm-chart/issues/1065
- https://github.com/cilium/cilium/issues/30634

### Version

```Text
Helm Version: istiod-1.23.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by DerekTBrown**
**Please provide a description of this PR:**
This resolves a perma-diff in the Helm chart, described in https://github.com/istio/istio/issues/53001.

fixes: https://github.com/istio/istio/issues/53001

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
this should *really* be fixed in argocd not here but oh well

**Comment by zirain** [comment]
a little surpise that `gen-check` passed.

**Comment by whoissteven** [comment]
I just added an ignore in ArgoCD to resolve this for my ambient chart.

`  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      name: istio-cni-node
      namespace: istio-system
      jsonPointers:
        - "/spec/template/spec/containers/0/env"
        - "/spec/template/spec/containers/0/resources"
    - group: apps
      kind: DaemonSet
      name: ztunnel
      namespace: istio-system
      jsonPointers:
        - "/metadata/annotations"
    - group: apps
      kind: Deployment
      name: istiod
      namespace: istio-system
      jsonPointers:
        - "/spec/template/spec/containers/0/env"
        - "/spec/template/spec/containers/0/resources"`

**Pull request merged**
