### PR TITLE
update book info app version

### PR DESCRIPTION
**Pull request by jasonwzm**
for issue https://github.com/istio/istio/issues/1034

### CODE REVIEW

**Comment by rshriram** [comment]
are these containers in dockerhub?

**Comment by jasonwzm** [comment]
@rshriram yes. tested pulling in a new VM and was working fine.

**Comment by rshriram** [comment]
please rebase

**Comment by mattdelco** [comment]
There seems to be something stale about how all of this operates but I can't make sense of the situation to know how things should behave (and samples/README.md points to a defunct https://istio.io/docs/samples/ ) .  Who normally builds the docker images for the demos?  I'm assuming either 1) istio builds and provides these for users to use, or 2) users build their own and push to their own repository.  If #1 then it seems like these should be built as part of a release build and the push to docker can happen as part of a monthly release (which would mean the references in these files should be handled/updated by updateVersion.sh).  If it's #2 then the tar files are already using 0.4.0 in their istio.VERSION, though this point seems moot since build-services.sh isn't included in the tar.

There's files under istio/blog that might also be stale.

**Comment by jasonwzm** [comment]
@mattdelco AFAIK, istio builds the images and pushes to istio repo whenever there is a change to the application(not very frequent recently, so it seems to be not in sync with istio version). @rshriram @ldemailly you guys have better context on this, feel free to chime in.

**Comment by ldemailly** [comment]
I don't know if the "seeing the test logs" has been fixed but try rebasing maybe ?

**Comment by jasonwzm** [comment]
rebased... let's see how it goes

**Comment by jasonwzm** [comment]
will take a look at that test and see what happened

**Comment by rshriram** [comment]
Ping. are you planning to follow this up? We have more pending changes

**Comment by jasonwzm** [comment]
@rshriram yes. rebased yesterday, but tests are still failing. Do the pending changes override this change?

**Comment by jasonwzm** [comment]
closed due to PR https://github.com/istio/istio/pull/2679

**Pull request closed without merging**
