### PR TITLE
Bugfix check port.

### PR DESCRIPTION
**Pull request by wangfakang**
The check port value should dependes on the `.Values.global.proxy.statusPort` .

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is intentionally 15090, see https://github.com/istio/istio/blob/e3fbe25e37f9d43ab5b4fa897bf1a87a1cc1ed38/tools/packaging/common/envoy_bootstrap_v2.json#L467

**Comment by wangfakang** [comment]
> This is intentionally 15090, see
> 
> https://github.com/istio/istio/blob/e3fbe25e37f9d43ab5b4fa897bf1a87a1cc1ed38/tools/packaging/common/envoy_bootstrap_v2.json#L467


Shouldn't the health check request trace be like this `health check ---> pilot-agent ----> Sidecar（Envoy/MOSN）`?

**Comment by howardjohn** [comment]
We changed to go `health check -> envoy (worker thread) -> agent -> envoy (/stats, main thread)`.  Envoy threading model means that requests to the admin interface are not representative of the requests that users are making, as they run on completely different threads/code paths. Readiness probe best practices suggest we make the probes as similar to traffic as possible, otherwise we may have false negatives. See #21488 for more info

**Comment by wangfakang** [comment]
> We changed to go `health check -> envoy (worker thread) -> agent -> envoy (/stats, main thread)`. Envoy threading model means that requests to the admin interface are not representative of the requests that users are making, as they run on completely different threads/code paths. Readiness probe best practices suggest we make the probes as similar to traffic as possible, otherwise we may have false negatives. See #21488 for more info

I have a question, How to ensure the health status of `pilot-agent` in this way?

**Comment by howardjohn** [comment]
I am not sure what you mean? The check goes to both envoy and pilot-agent

**Comment by wangfakang** [comment]
> I am not sure what you mean? The check goes to both envoy and pilot-agent

thx, I see.

**Comment by wangfakang** [comment]
> > I am not sure what you mean? The check goes to both envoy and pilot-agent
> 
> thx, I see.

Why the [ingress gateway](https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L131) doesn't use 15090?

**Comment by dex80526** [comment]
@wangfakang: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by howardjohn** [comment]
@wangfakang ingress not using 15090 was a bug that has since been fixed. thanks for pointing this out

**Pull request closed without merging**
