### PR TITLE
[bugfix] Fix restarting logic of deployment in the test framework

### PR DESCRIPTION
**Pull request by ingwonsong**
Fix the issues in https://github.com/istio/istio/pull/41416#issuecomment-1302227805

The timestamp was not correctly generated and add more checks for detecting the restart completion.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
Should we cherry-pick this to 1.14-1.16 and merge with the prior cherry-picks of #41416?

**Comment by ingwonsong** [comment]
I will manually add this to cherry pick after checking if the bug is really fixed in the postsubmit.

**Pull request merged**
