### PR TITLE
add back weight for pod antiaffnity.

### PR DESCRIPTION
**Pull request by morvencao**
Resolve: https://github.com/istio/istio/issues/14034

### CODE REVIEW

**Comment by linsun** [comment]
@morvencao is this also needed for master and release-1.2?

**Comment by morvencao** [comment]
@linsun This has been merged to new installer, not sure if we need to create a PR for `release-1.2` in main repo here.

**Comment by linsun** [comment]
@morvencao I think so.  FYI, the TOC has decided that the old installer will be the default installer for release 1.2 so that we can collect more feedback on the new installer before we promote it to stable.  (sorry if I have ever communicated that to you but it just happened a week ago).

**Comment by morvencao** [comment]
@linsun Got it. Have cherry pick the commit to release-1.2: https://github.com/istio/istio/pull/14418

**Comment by duderino** [comment]
At this point I'd like to keep all changes out of release-1.1 unless it's really clear that they address an important issue.  release-1.2 will be out in ~3 weeks so I think you should try to get this change merged into that.

Please reopen and argue if I have misunderstood the importance of this change.

**Pull request closed without merging**
