### PR TITLE
WIP: Deploy to Helm repository (on github pages)

### PR DESCRIPTION
**Pull request by aslafy-z**
Following up #6877 

Edit: This might need to be modified to work with current gh-pages

### CODE REVIEW

**Comment by aslafy-z** [comment]
I signed it!

**Comment by geeknoid** [comment]
I wonder if this would be better done as a script in the istio/istio.github.io repo?

We have a script called grab_reference_docs.sh which crawls the istio/istio and istio/api repos and extracts reference docs which are then integrated and published to istio.io. The procedure we use is branch-friendly and release-friendly.

In a similar way, we could have a script in istio/istio.github.io which extracts the charts and publishes them to istio.io/charts where they could be referenced easily.

**Comment by aslafy-z** [comment]
@geeknoid I'm working on it https://github.com/istio/istio.github.io/pull/2616

**Pull request closed without merging**
