### PR TITLE
Rename sidecar-injector subchart to sidecarinjector

### PR DESCRIPTION
**Pull request by munnerz**
This is part of a series of PRs to improve the Helm charts support for the sidecar injector & Istio 0.5.0 in general.

It appears when using a hyphen in a chart name, Helm does not properly pass values to the subchart from the top level values.yaml file. I ran into this when adding a new `caBundle` field to the Helm chart, to allow customising the webhooks ca bundle without the need for the pre-made scripts for templating manifests.

This PR renames the chart from `sidecar-injector` to simply `injector`, which resolves issues passing subchart values from the top level chart.

/cc @luisyonaldo

### CODE REVIEW

**Comment by luisyonaldo** [comment]
I can confirm the bug. Maybe `sidecarinjector` is a better name. I'm ok with `injector` but we are trying to make chart more in sync with plain manifest.

Thanks @munnerz

**Comment by luisyonaldo** [comment]
cc @linsun @sdake

**Comment by munnerz** [comment]
Let me know either way and I'll make a change! 😄 

I've managed to stand up an Istio 0.5.0 control plane with mTLS using the helm chart now after a few adjustments. I'm currently running into issues with the bookinfo application, although I'm having that same issue with a vanilla manifests deployment (using istio-auth.yaml) so starting to wonder if something more is broken here 😄

**Comment by linsun** [comment]
Thank you for raising this issue @munnerz I would prefer sidecarInjector to be somewhat consistent with other places when we call sidecar-injector.  for example, in our docs and istioctl, we call it sidecar injector or sidecar-injector.

**Comment by sdake** [comment]
@munnerz can you resolve the conflict in requirements.yaml?  A change to move ingress to its own subchart modified this file.

Cheers
-steve

**Comment by munnerz** [comment]
@sdake done

**Comment by munnerz** [comment]
@sdake resolved (another) conflict

**Comment by sdake** [comment]
@linsun did you want @mrunnerz to change this PR to %s/injector/sidecarinjector?  Unfortunately it appears a dash won't work correctly with Helm.

**Comment by munnerz** [comment]
PR rebased on latest master.

@linsun I'm happy to change this if needs be. What would be preferable? As @sdake says, we can't use a hyphen so we'll likely need to name the chart `sidecarinjector` if so 😄 

Let me know and I'll get it updated! This currently blocks using the injector at all, as the `caBundle` cannot be configured.

**Comment by linsun** [comment]
@munnerz @sdake yes, would be nice to have it changed to be consistent with other docs and cmds, if you don't mind.  Thank you!  (understood about the hyphen issue, thanks for spotting that!)

**Comment by munnerz** [comment]
@linsun I've updated to call the chart `sidecarinjector`. PTAL 😄

**Comment by linsun** [comment]
Thank you @munnerz!   Do you know how to trigger the retest on circleCI?  we need to get that test passing.

**Comment by sdake** [comment]
@linsun I've typically seen the bot spit out a list of tests that have failed after the jobs finish up - which permits a /retest or test on a specific job.

**Comment by munnerz** [comment]
Although it looks like Circle doesn't retest when a PR is re-opened 😢

**Comment by munnerz** [comment]
@sdake can you try going here: https://circleci.com/gh/istio/istio/30513?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link and hitting "Restart"? I am told I need write permission to the repo in order to restart tests 🤔

**Comment by munnerz** [comment]
Never mind, I just rebased on master in order to re-trigger everything.. 🤞

**Comment by linsun** [comment]
It failed again... I don't think I have write permission to trigger the circle CI re-build for you.  can you follow the step here to see if you can run the job since you own the job?   

https://github.com/istio/istio/wiki/Working-with-CircleCI

**Comment by ldemailly** [comment]
can you rebase and resolve conflicts ?

I pinged #3037 for the test failure

**Comment by ldemailly** [comment]
also the circleci shadow error is fixed on master sometime today so you do need to rebase if only for that (#3471 )

**Comment by luisyonaldo** [comment]
Btw, you can retest circle CI by commiting and empty commit. I allways do `git commit --allow-empty -m retest`, that should force a retest

**Comment by ldemailly** [comment]
> Btw, you can retest circle CI by commiting and empty commit. I allways do git commit --allow-empty -m retest, that should force a retest

a) that creates noise compared to clicking "retest"
b) that doesn't help with master fixes, for which pull/merge/rebase is what circleci forces you to do

**Comment by ldemailly** [comment]
> @munnerz PR needs rebase

@sdake ^

**Comment by munnerz** [comment]
@sdake @ldemailly rebased on master. :crossed_fingers: it passes now

**Comment by ldemailly** [comment]
@ajy can you "/ l g t m" if you're ok with this ?

**Comment by Rigdon** [comment]
I just opened #3536 for something else, but fixed the underlying problem here by changing the top level value name in `values.yaml.tmpl` The hyphen itself isn't a problem, but that the sidecar injector values were defined as `sidecarInjector` rather than `sidecar-injector` to match the chart name.

**Comment by ldemailly** [comment]
ping @munnerz @ayj

**Comment by sdake** [comment]
I think we can close this PR with the merging of https://github.com/istio/istio/pull/3536.

**Pull request closed without merging**
