### PR TITLE
Fix the dep, all components compile

### PR DESCRIPTION
**Pull request by costinm**
Tested with 
go build ./pilot/... ./mixer/... ./broker/... ./security/...

TODO: incorporate it in the Makefile and docs.
TODO: track each of the override, make sure we either move ahead or manually check the changes.

```release-note
- Enable (dep)[https://github.com/golang/dep] support
```

### CODE REVIEW

**Comment by mandarjog** [comment]
Can you add a test that actually tests this?
We want to make sure that this is maintained on an ongoing basis.
Right now you can add it to presubmit. Later on it should be it’s own job.

**Comment by mandarjog** [comment]
@rshriram in that case can we  just add it to circle ci in this PR and let it pass?

**Comment by costinm** [comment]
One step at a time, we'll need to add it to the prow as well, incremental is better.

Note that 'dep ensure' is pretty slow - ~10 min for the full project - and only needs to be run periodically, to pick updates ( daily for example). We may also checkin the vendor directory in a different repo ( istio-vendor ?), to speed up presubmit tests.

Caching it in circleci or prow is also desirable.

**Comment by rshriram** [comment]
I have already created a circle ci job to test the go build.. and it works.

**Comment by costinm** [comment]
'dep ensure -vendor-only' is about 3 minutes
'git clone github.com/costinm/istio-vendor' is 9 seconds
'dep ensure' ( updating the lock and computing the new versions) is 10 min.

**Comment by rshriram** [comment]
fwiw, it takes 80 seconds to pull vendor deps and build pilot, mixer, broker in circleci. So, caching seems like overkill in circleci.

**Comment by costinm** [comment]
Thanks Shriram, will merge as soon as it's green.

**Comment by rshriram** [comment]
and if we are going to have the vendor code, we should commit that to istio/istio. There is absolutely no point in having another repo for vendored code and then having to maintain the two. if we are principled about it, any PR that requires vendor update should either be separate or should have vendor code in a separate commit.

**Pull request merged**
