### PR TITLE
fix customservice regression in egressgateway config

### PR DESCRIPTION
**Pull request by timonwong**
**Please provide a description of this PR:**

#42740: 

> There was a PR #37259 that addresses #37260, however in PR #37867 it got accidentally  (maybe due to merge conflict?) removed

### CODE REVIEW

**Review by zirain — COMMENTED** [review]
LGTM, leave to @howardjohn for another look as code owner

/ok-to-test

**Review by howardjohn — COMMENTED** [review]
Can you remove the tests and release note? They are excessive for this change

**Comment by timonwong** [comment]
> Can you remove the tests and release note? They are excessive for this change

Done

**Comment by timonwong** [comment]
Should add /release-note-none

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
