### PR TITLE
[WIP] Test go mod on prow-staging branch

### PR DESCRIPTION
**Pull request by ericvn**
This is using a new Istio-builder image with GO111MODULE=on set so should be ignoring vendor and using go modules. Wondering what will break...

### CODE REVIEW

**Comment by ericvn** [comment]
Failure:
```
 make push HUB=gcr.io/istio-testing TAG=5c713e0b7af3bb37078459f7561c4788b60fece2-e2e_bookinfo_envoyv2_v1alpha3
mkdir -p /home/prow/go/out/logs
STATIC=0 GOOS=linux  LDFLAGS='-extldflags -static -s -w' bin/gobuild.sh /home/prow/go/out/linux_amd64/release/istioctl-linux ./istioctl/cmd/istioctl
go: finding github.com/Azure/go-autorest v11.1.0+incompatible
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: finding github.com/ghodss/yaml v1.0.0
....
go: finding golang.org/x/sys v0.0.0-20190129075346-302c3dd5f1cc
go: github.com/google/go-cmp@v0.2.0: unknown revision v0.2.0
go: error loading module requirements
Makefile:355: recipe for target '/home/prow/go/out/linux_amd64/release/istioctl-linux' failed
make: *** [/home/prow/go/out/linux_amd64/release/istioctl-linux] Error 1
```

**Comment by ericvn** [comment]
Failure (e2e-pilot-cloudfoundry-v1alpha3-v2):
```
+ exec prow/e2e-pilot-cloudfoundry-v1alpha3-v2.sh
/usr/local/bin/entrypoint: line 14: /home/prow/go/src/istio.io/istio/prow/e2e-pilot-cloudfoundry-v1alpha3-v2.sh: No such file or directory
```

**Comment by ericvn** [comment]
Failure(release-test.sh): Also expected to fail
```
fatal: Remote branch prow-staging not found in upstream origin
```

**Comment by ericvn** [comment]
Failure (istio-codecov):
```
bin/testEnvLocalK8S.sh ensure
Copying /home/prow/go/out/linux_amd64/debug/envoy-debug-542b4fda35046fc9dad5014dbe81f3d5969e63f7 to /home/prow/go/out/linux_amd64/release/envoy
Copying /home/prow/go/out/linux_amd64/release/envoy to /home/prow/go/bin/envoy
Downloading istio.deps from https://raw.githubusercontent.com/istio/proxy/542b4fda35046fc9dad5014dbe81f3d5969e63f7/istio.deps to /home/prow/go/out/linux_amd64/release/istio_proxy.deps
go: finding github.com/jstemmer/go-junit-report latest
go: downloading github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
go: extracting github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
Code coverage test (concurrency 6)
go: downloading fortio.org/fortio v1.3.0
go: downloading github.com/docker/docker v1.13.1
....
cover: unknown import path "istio.io/istio/pkg/features/pilot": cannot find module providing package istio.io/istio/pkg/features/pilot
make: *** No rule to make target 'localTestEnvCleanup'.  Stop.
vvv

**Comment by ericvn** [comment]
Failure(unit-tests):
```
=== RUN   TestVersion/sdsclient
--- FAIL: TestVersion (0.28s)
    --- FAIL: TestVersion/pilot-discovery (0.04s)
        version_test.go:60: Field Version was invalid. Got: unknown.
        version_test.go:61: Field GitRevision was invalid. Got: unknown.
        version_test.go:62: Field User was invalid. Got: unknown.
        version_test.go:63: Field Host was invalid. Got: unknown.
        version_test.go:65: Field DockerHub was invalid. Got: unknown.
        version_test.go:66: Field BuildStatus was invalid. Got: unknown.
        version_test.go:67: Field GitTag was invalid. Got: unknown.
   ....
 --- FAIL: TestVersion/galley (0.04s)
        version_test.go:60: Field Version was invalid. Got: unknown.
        version_test.go:61: Field GitRevision was invalid. Got: unknown.
        version_test.go:62: Field User was invalid. Got: unknown.
        version_test.go:63: Field Host was invalid. Got: unknown.
        version_test.go:65: Field DockerHub was invalid. Got: unknown.
        version_test.go:66: Field BuildStatus was invalid. Got: unknown.
        version_test.go:67: Field GitTag was invalid. Got: unknown.
    --- FAIL: TestVersion/sdsclient (0.03s)
        version_test.go:60: Field Version was invalid. Got: unknown.
        version_test.go:61: Field GitRevision was invalid. Got: unknown.
        version_test.go:62: Field User was invalid. Got: unknown.
        version_test.go:63: Field Host was invalid. Got: unknown.
        version_test.go:65: Field DockerHub was invalid. Got: unknown.
        version_test.go:66: Field BuildStatus was invalid. Got: unknown.
        version_test.go:67: Field GitTag was invalid. Got: unknown.
FAIL
FAIL	istio.io/istio/tests/version	0.291s
Makefile:408: recipe for target 'version-test' failed
```

**Comment by ericvn** [comment]
Also noted that locally, running `GOOS=linux GO111MODULE=on make clean init test-bins build docker  docker.push HUB=x TAG=y` yields an error:
```
=> cleaning...
can't load package: package istio.io/istio: unknown import path "istio.io/istio": cannot find module providing package istio.io/istio
make: *** [clean.go] Error 1
```
Turning GO111MODULE to auto before calling `go clean` in the make file prevents the error.

**Comment by ericvn** [comment]
The two `integ-*-presubmit` tests fail elsewhere.

**Comment by howardjohn** [comment]
>         version_test.go:60: Field Version was invalid. Got: unknown.
>         version_test.go:61: Field GitRevision was invalid. Got: unknown.
>         version_test.go:62: Field User was invalid. Got: unknown.
>         version_test.go:63: Field Host was invalid. Got: unknown.
>         version_test.go:65: Field DockerHub was invalid. Got: unknown.
>         version_test.go:66: Field BuildStatus was invalid. Got: unknown.
>         version_test.go:67: Field GitTag was invalid. Got: unknown.

I made this test basically to catch this when we switched to go mod :slightly_smiling_face: should be an easy fix though in `get_workspace_status.sh`

**Comment by ericvn** [comment]
Cancelling this PR for now as it's getting stale. Will come back to this.

**Pull request closed without merging**
