### PR TITLE
Update grafana to its latest version

### PR DESCRIPTION
**Pull request by lei-tang**
https://github.com/istio/istio/blob/master/addons/grafana/Dockerfile.grafana#L1 shows
that Istio currently uses the version 5.0.4 of grafana, which was released on March 27, 2018.
The latest version of grafana is 5.2.2, released on July 24, 2018. Istio should update its
grafana version to leverage the fixes included in the latest grafana version.

### CODE REVIEW

**Comment by sdake** [comment]
One general question I have is - has this version of grafana been tested with the Istio dashboard in master?

In the past, dashboard versions were not backward compatible with grafana.

**Comment by lei-tang** [comment]
@sdake can you help on checking the compatibility with the latest grafana?

**Comment by sdake** [comment]
@lei-tang I know nothing about grafana - half the time I can't get it to work with Istio :).  IOW I am not the right person for that task.  If you can verify this version works for you that is good enuf for me.

Cheers
-steve

**Comment by sdake** [comment]
@lei-tang - gate implosion.  Dockerfile contents upstream has changed in some way.  See https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/7945/istio-presubmit/15951/.

To submit a working PR, try `make docker.grafana` (iirc).

**Comment by sdake** [comment]
@lei-tang looks like the grafana files are finally versioned: see https://github.com/istio/istio/commit/972488c60de7176c28044d7d13afaae38b62b171

The gate may be failing as a result of this PR:
https://github.com/istio/istio/commit/f883fbf8e01db4767bfaeab128b87976123b1df6

I'm sure @douglas-reid had a good reason to put those chmod 777 operations in the docker build.  I think simply removing them while getting a working build will not yield a working grafana, but YMMV.

Cheers
-steve

**Comment by lei-tang** [comment]
I added [a commit](https://github.com/istio/istio/pull/7945/commits/e7202c11a5975722679df96cddaa1f78a1c4c9e9) in this PR to fix the error on "make docker.grafana", without removing the chmod operations.

**Comment by douglas-reid** [comment]
@lei-tang can you post screensnaps of the upgrade with traffic flowing through? It'd be nice to see the impact of upgrading (I have no reason to suspect anything will be funky, however).

**Comment by lei-tang** [comment]
image

**Comment by lei-tang** [comment]
image

**Comment by lei-tang** [comment]
@douglas-reid I have posted screenshots of the upgrade with traffic flowing: the first screenshot shows the upgraded grafana version 5.2.2 and the second screenshot shows the Istio service traffic in the dashboard of grafana 5.2.2.

**Pull request merged**
