### PR TITLE
remove aggregator AppendWorkloadHandler implement to prevent misuse

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by howardjohn** [comment]
I am a bit confused how this works. Is the issue we are registering things 2x or something?

**Comment by stevenctl** [comment]
I don't see where we actually append handlers at the aggregate level today, so this seems safe to me. Are you seeing an actual issue right now, or is this code cleanup?

**Comment by hzxuzhonghu** [comment]
@stevenctl You are right, there is no append now. This is to make sure no developer in the future will misuse it unless we find it is useful.

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
