### PR TITLE
Added data source for Galley dashboard

### PR DESCRIPTION
**Pull request by nrjpoddar**
Fixes: #13040

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@howardjohn & @morvencao how can I get this merged? I don't think these failures have anything to do with my changes.

**Comment by howardjohn** [comment]
Test failures are known failures. Needs to be manually merged by @rshriram or @duderino

**Comment by nrjpoddar** [comment]
@rshriram can you merge this?

**Comment by duderino** [comment]
Thank you @nrjpoddar

**Comment by duderino** [comment]
This will go into 1.1.3 which we will try to publish on 4/15

**Pull request merged**
