### PR TITLE
Fix deadlock in Syncz

### PR DESCRIPTION
**Pull request by costinm**

### CODE REVIEW

**Comment by mandarjog** [comment]
@costinm this just removes the lock. Can you 
1. document the actual dead lock
2. explain rationale behind removing this read lock, why it is no longer needed.
3. possibly a test

**Comment by costinm** [comment]
Sorry, I assumed it's obvious - the lock is acquired 2 times (and it's not re-entrant )

**Comment by costinm** [comment]
Re. test - probably we need to add something in the long running tests to call proxy-status, but it'll probably take longer and likely lower priority than fixing the immediate problem. I can file a bug - not sure who owns this feature, or even if it's something that we intend to support for production use ( as opposed to simply debugging )

**Comment by costinm** [comment]
yes. 
I suspect some merge error at some point, but not curious enough to dig the history.

1.1 is ok.

**Pull request merged**
