### PR TITLE
xds: restrict envoy filters

### PR DESCRIPTION
**Pull request by kyessenov**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Is there a design doc or some context on what a safe envoyfilter is and why we want one?

**Comment by hzxuzhonghu** [comment]
It is a very tricky issue, as envoyfilter is a black box, mostly we istiod could not be aware of it.  So is it to be able to parse and protect all the capabilities that istio-proxy supported.

**Comment by kyessenov** [comment]
@hzxuzhonghu I'll bring the PR to discussion separately, I didn't want reviews but CI wouldn't start. Istiod can be made aware of the capabilities of istio-proxy and Envoy - the purpose is to give this awareness and safe-guard against dangerous operations.

**Comment by hzxuzhonghu** [comment]
I agree the intent is useful.

**Comment by howardjohn** [comment]
You can mark it as draft and do `/test all` manually if you want fwiw

**Pull request closed without merging**
