### PR TITLE
Add RPM to cloud build.

### PR DESCRIPTION
**Pull request by incfly**

### CODE REVIEW

**Comment by incfly** [comment]
/hold
need to determine sha256 is needed and whether we can leave out unnecessary rpm (only retain proxy and node agent, to avoid confusion).

**Comment by incfly** [comment]
release-test.sh time out, probably we need to pre-build the rpm builder image.
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/13802/release-test/6819/build-log.txt

**Comment by incfly** [comment]
First rpm built by Istio pipeline, http://storage.googleapis.com/istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-proxy-1.0dev-1.el7.x86_64.rpm
:)

**Comment by incfly** [comment]
```bash
gsutil ls gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/                                   
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-citadel-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-galley-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-istioctl-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-mixc-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-mixs-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-node-agent-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-pilot-agent-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-pilot-discovery-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-proxy-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-proxy-debuginfo-1.0dev-1.el7.x86_64.rpm
gs://istio-artifacts/pilot/6c3a62b58c91f6dd15958f2f87c279f713d8dfaa/artifacts/rpms/istio-sidecar-injector-1.0dev-1.el7.x86_64.rpm
```

**Comment by incfly** [comment]
okay several remaining things before send out for review, @jwendell 

- i saw we have all binary rpm, mixer, pilot, sidecar, are they all needed? i thought we only need sidecar rpm
- builder image can be done as a periodically but we can improve it if build time really fails the test target, can be done as follow-up.
- is it a convention in redhat land to include the version in the package file name? right now everything is `1.0`, it seems like `VERSION` env var is using git sha for PR, and 1.1.2 for release cut?

**Comment by MrTrustor** [comment]
@incfly Can we merge this?

**Comment by incfly** [comment]
@MrTrustor the current problem is that the default timeout for the build is 120min. And the with this PR the release-build is timed out, can't finish after 2hours. Increasing time out may not be a good idea since this is run for every PR.

I believe the right way should be see how to reduce the amount of the build process, e.g. the builder docker image can be pre-built as nightly or something.

**Comment by MrTrustor** [comment]
Ok, what's the plan to move forward?

**Comment by PiotrSikora** [comment]
This should be done in [istio/proxy](https://github.com/istio/proxy), since that's where we build Debian packages. Ideally, this should be done using Bazel's [pkg_rpm](https://docs.bazel.build/versions/master/be/pkg.html#pkg_rpm) rule.

**Comment by incfly** [comment]
Indeed, I found the proxy RPM part is taking lots of time. Debian version istio-proxy, we download some prebuilt artifacts from istio/proxy.

I'll take a look of that.

The other thing, @MrTrustor I guess the customer don't need `make rpm/istio`? That includes mostly mixer/pilot-agent binaries, I guess what matters the most is the istio/proxy? Removing that from pipeline can also reduce the build time.

**Comment by MrTrustor** [comment]
@incfly Yes, correct. What matters is the proxy package. The control plane runs in K8s.

**Comment by incfly** [comment]
@howardjohn you're right, the PR is timeout, I'm closing this PR and updated the summary in https://github.com/istio/istio/issues/9117#issuecomment-540406472

**Pull request closed without merging**
