### PR TITLE
Update envoy_bootstrap.json

### PR DESCRIPTION
**Pull request by wzshiming**
The name here is repeated with prometheus_stats. Although it works, it's better to modify it

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
I donot think this right. We donot need to update, they should be same

**Comment by wzshiming** [comment]
The prometheus_stats target is /stats/prometheus of envoy's own admin service, and the agent target is pilot-agent, 
Why cluster_name of the agent is the prometheus_stats is right?

**Comment by wzshiming** [comment]
@hzxuzhonghu PTAL

**Comment by hzxuzhonghu** [comment]
I look wrongly, lgtm. You need to update lots of files i think

/ok-to-test

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by wzshiming** [comment]
@hzxuzhonghu 
My forked repository accidentally deleted the PR, so I couldn't update the commit. I reopened the PR #30061

**Comment by hzxuzhonghu** [comment]
Then it is safe to close this one

**Pull request closed without merging**
