### PR TITLE
[release-1.10] Fix cronjob timestamp trimming.

### PR DESCRIPTION
**Pull request by bianpengyuan**
Manual cherry-pick of https://github.com/istio/istio/pull/35655 fix https://github.com/istio/istio/issues/36146

### CODE REVIEW

**Comment by Monkeyanator** [comment]
@bianpengyuan looks like legitimate unit test failure with:

```
== RUN   TestCronJobMetadata
=== RUN   TestCronJobMetadata/cron-job-name-sec
    util_test.go:212: Object metadata got &ObjectMeta{Name:sec,GenerateName:sec-1234567890-pod,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{OwnerReference{Kind:Job,Name:sec-1234567890,UID:,APIVersion:v1,Controller:*true,BlockOwnerDeletion:nil,},},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} want {Name:sec GenerateName:sec-1234567890-pod Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]}
    util_test.go:215: Type metadata got &TypeMeta{Kind:CronJob,APIVersion:batch/v1beta1,} want {Kind:CronJob APIVersion:batch/v1beta1}
=== RUN   TestCronJobMetadata/cron-job-name-min
    util_test.go:212: Object metadata got &ObjectMeta{Name:min,GenerateName:min-12345678-pod,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{OwnerReference{Kind:Job,Name:min-12345678,UID:,APIVersion:v1,Controller:*true,BlockOwnerDeletion:nil,},},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} want {Name:min GenerateName:min-12345678-pod Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]}
    util_test.go:215: Type metadata got &TypeMeta{Kind:CronJob,APIVersion:batch/v1beta1,} want {Kind:CronJob APIVersion:batch/v1beta1}
=== RUN   TestCronJobMetadata/non-cron-job-name
    util_test.go:212: Object metadata got &ObjectMeta{Name:job-123,GenerateName:job-123-pod,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{OwnerReference{Kind:Job,Name:job-123,UID:,APIVersion:v1,Controller:*true,BlockOwnerDeletion:nil,},},Finalizers:[],ClusterName:,ManagedFields:[]ManagedFieldsEntry{},} want {Name:job-123 GenerateName:job-123-pod Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]}
    util_test.go:215: Type metadata got &TypeMeta{Kind:Job,APIVersion:v1,} want {Kind:Job APIVersion:v1}
--- FAIL: TestCronJobMetadata (0.00s)
    --- FAIL: TestCronJobMetadata/cron-job-name-sec (0.00s)
    --- FAIL: TestCronJobMetadata/cron-job-name-min (0.00s)
    --- FAIL: TestCronJobMetadata/non-cron-job-name (0.00s)
```

**Comment by bianpengyuan** [comment]
@Monkeyanator fixed. thanks!

**Review by Monkeyanator — APPROVED** [review]

**Pull request merged**
