### PR TITLE
Add tests to pilot end-to-end integration test

### PR DESCRIPTION
**Pull request by ronenschafferibm**
**What this PR does / why we need it**:
Added the following integration tests:
Egress rules:
* Egress rule to a domain containing a wildcard

Route rule to egress:
* Appending http headers in traffic to httpbin.org

Minor improvements: 

* Delete configuration after each test 

* Improved formatting of error messages 

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by nmittler** [comment]
@douglas-reid any idea what's going on with unittest-mixer?

**Comment by douglas-reid** [comment]
@nmittler something is still broken with the opa adapter. I could have sworn there was a PR out to fix it, but my brain was rebooted when the ball dropped. I'll see if I can find more info.

**Comment by douglas-reid** [comment]
@nmittler I believe https://github.com/istio/istio/pull/2315 is the fix we need.

**Comment by nmittler** [comment]
@douglas-reid ah ok perfect.  Anyway, it looks like this PR is passing everything that's "required".

@ronenschafferibm mind rebasing?

**Comment by ronenschafferibm** [comment]
@nmittler Rebased

**Comment by rshriram** [comment]
Please fix the linter.. and merge your branch with master..

**Pull request merged**
