### PR TITLE
Fixing typos in unit tests

### PR DESCRIPTION
**Pull request by mbanikazemi**

### CODE REVIEW

**Comment by ymesika** [comment]
`master` is probably better candidate.

/lgtm

**Comment by mbanikazemi** [comment]
@wenchenglu can we get this merged in 1.1? It is a trivial fix of typos.

**Comment by mbanikazemi** [comment]
@ymesika FYI, submitted to master.

**Comment by ymesika** [comment]
/lgtm

why the rebase flag?

**Comment by ymesika** [comment]
@mbanikazemi you'll need some googler's cla magic now.
Better/faster to re-open this PR.

**Comment by GregHanson** [comment]
@hzxuzhonghu can you add the CLA label and get this one in?

**Comment by hzxuzhonghu** [comment]
@GregHanson I can not do this, only google guys can I think.

**Comment by hzxuzhonghu** [comment]
I am not sure whether human-approved takes effect.

**Comment by mbanikazemi** [comment]
Closing as this got merged in PR #12661.

**Pull request closed without merging**
