### PR TITLE
fix istioctl authz check to print authz policies applied in pod

### PR DESCRIPTION
**Pull request by yangminzhu**
This should bring the command back to a minimum usable (and still quite useful) state, hope we can make it in 1.7 and iterate on the design later.

https://github.com/istio/istio/issues/23526

Example new outout:
```
➜ ./out/linux_amd64/istioctl x authz check httpbin-779c54bf49-nr58m
ACTION   AuthorizationPolicy          RULES
DENY     mes.default                  3
ALLOW    _anonymous_match_nothing_    1
ALLOW    bla.default                  1
ALLOW    productpage-viewer.default   1
```

Note the current `istioctl authz check` is nearly unusable and that's why I want to fix it quickly in this PR for 1.7, this is very low risk since it only touches the `istioctl authz check` command.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by esnible** [comment]
I had targeted fixing this for 1.8.
Please read https://github.com/istio/istio/issues/23526
I am not an expert in the use of this command.  If these changes are what the Security WG wants it seems to be low risk to put this in 1.7, given that the current implementation is nearly unusuable.

**Comment by yangminzhu** [comment]
> I had targeted fixing this for 1.8.
> Please read #23526
> I am not an expert in the use of this command. If these changes are what the Security WG wants it seems to be low risk to put this in 1.7, given that the current implementation is nearly unusuable.

yes, I think we should at least fix this command to make it usable instead of having the current nearly unusable command in 1.7, and iterate on the design for 1.8.

@liminw could you take a quick look at this PR? Hoping we could still make it to 1.7 (very low risk since it only changes the `istioctl authz check` command). Thanks

**Comment by yangminzhu** [comment]
@esnible  Updated to the following output format:
```
➜ ./out/linux_amd64/istioctl x authz check httpbin-779c54bf49-nr58m
ACTION   AuthorizationPolicy          RULES
DENY     mes.default                  3
ALLOW    _anonymous_match_nothing_    1
ALLOW    bla.default                  1
ALLOW    productpage-viewer.default   1
```

> Would it be possible to summarize the rule rather than just giving its number? Instead of rule 0 it would be nice to see 0: from principals cluster.local/ns/default/sa/sleep; to methods GET; when request.headers[version] in v1/v2?

I have replied this in the https://github.com/istio/istio/issues/23526#issuecomment-664571364, it is possible but it easily gets super complicated when the policy is more complex, for example, a policy could have a free combination of all these fields (multiple rules, multiple fields).

It also doesn't bring too much value, the user could just use the `kubectl get authorizationpolicy -o yaml` to check the contents of the policy, why do we re-implement the same output again? Note the authz policy is very different from other APIs (like Gateway, VirtualServer, etc.) where the API has some significant fields that are suitable to be always printed in the output (e.g. Host, etc.), this is not true for authz policy.

**Comment by nrjpoddar** [comment]
@yangminzhu this can wait for 1.7.1, let's reduce the stress on 1.7 release managers as they have been juggling many blockers.

**Pull request merged**
