### PR TITLE
Equip bin/istio-proxy-cfg.py script to show ssl summary for pod (listeners)

### PR DESCRIPTION
**Pull request by diemtvu**
This is to partly address https://github.com/istio/istio/issues/1456

Uses show_ssl_summary flag to see if listeners are using SSL or not (i.e whether it has ssl_context)

Example
```

bin/istio-proxy-cfg.py httpbin2-3289005631-flh44.default --skip_envoy --show_ssl_summary

Listener virtual                        : PLAINTEXT 
Listener http_0.0.0.0_15003             : PLAINTEXT 
Listener http_0.0.0.0_80                : PLAINTEXT 
Listener http_0.0.0.0_8000              : PLAINTEXT 
Listener http_0.0.0.0_8080              : PLAINTEXT 
Listener http_0.0.0.0_9093              : PLAINTEXT 
Listener tcp_10.11.240.10_53            : PLAINTEXT 
Listener tcp_10.11.240.1_443            : PLAINTEXT 
Listener tcp_10.11.243.100_80           : PLAINTEXT 
Listener tcp_10.11.244.4_80             : PLAINTEXT 
Listener tcp_10.11.248.83_443           : PLAINTEXT 
Listener tcp_10.11.249.61_443           : PLAINTEXT 
Listener tcp_10.11.255.218_15004        : PLAINTEXT 
Listener tcp_10.11.255.218_42422        : PLAINTEXT 
Listener tcp_10.11.255.218_9091         : PLAINTEXT 
Listener tcp_10.11.255.218_9094         : PLAINTEXT 
Listener tcp_10.11.255.218_9102         : PLAINTEXT 
Listener http_10.8.1.46_8000            : SSL  
```

### CODE REVIEW

**Comment by baodongli** [comment]
A lot of changes are due to formatting. Can you avoid reformatting so that changes pertaining to the issue can be clearly identified and reviewed?

**Comment by mandarjog** [comment]
Diem use autopep / autopep8 to format per python spec.

**Comment by mandarjog** [comment]
/hold 
Till it can be reviewed.

**Comment by ldemailly** [comment]
I did but ok :)

**Comment by mandarjog** [comment]
Sorry did not realize 
/lgtm

**Pull request merged**
