### PR TITLE
remove deployment sidecar disconnect Easier to understand

### PR DESCRIPTION
**Pull request by clarechu**
I think it's easier to understand
This code is not necessary
```go
			deps := []appsv1.Deployment{}
			deps = append(deps, *dep)
			return unInjectSideCarFromDeployment(client, deps, args[0], ns, writer)
```

It is easier to understand by changing it to the following way

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

### CODE REVIEW

**Comment by tanjunchen** [comment]
@googlebot I signed it!

**Review by tanjunchen — COMMENTED** [review]
/lgtm
I think it is good change.

**Review by howardjohn — APPROVED** [review]

**Pull request closed without merging**
