### PR TITLE
Fix running prow scripts locally

### PR DESCRIPTION
**Pull request by ymesika**
**Please provide a description of this PR:**

As result of #46082 running the prow scripts (e.g. integration tests) locally is failing.
Fixing for both local runs or build systems without the `otel-cli`.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
The otel-cli should be in the build-tools image.

**Comment by ymesika** [comment]
@ericvn this fix is for running locally out of prow.
E.g. `prow/integ-suite-kind.sh --kind-config prow/config/ambient-sc.yaml test.integration.ambient.kube`

**Comment by ericvn** [comment]
Noting also PULL_PULL_SHA is replaced by PULL_BASE_SHA in the integration tests.

**Review by ericvn — APPROVED** [review]
I will approve this PR as it fixes the local issue (as the PR name describes). I'll work on another PR to fix the integration test issues.

**Pull request merged**
