### PR TITLE
Fix injection in OpenShift

### PR DESCRIPTION
**Pull request by jwendell**
Fallback to single cluster client if multi cluster is not active.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
when is multicluster not active?

**Comment by jwendell** [comment]
I keep getting `unable to fetch namespace, failed to get client for ""` 

I'm guessing multicluster is false by default? https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L449

**Comment by jwendell** [comment]
I'm working on adding unit tests for this, but it might take a couple of days, can we merge this fix now and add UT later?

**Comment by howardjohn** [comment]
> I keep getting `unable to fetch namespace, failed to get client for ""`
> 
> I'm guessing multicluster is false by default? https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L449

I feel like this should work. Maybe we need to make a lookup for "" to be the config cluster.

Either this issue impacts all of the multicluster components or none of them I would think; a fix localized to injection feels likely to be wrong/incomplete

**Comment by jwendell** [comment]
@howardjohn another approach: https://github.com/istio/istio/pull/49986

I'll add unit tests for openshift in a separate PR

**Pull request closed without merging**
