### PR TITLE
Break up the helloworld sample into versions

### PR DESCRIPTION
**Pull request by ymesika**
Broke the `helloworld.yaml` into version specific (v1/v2) yamls.
The purpose of these new sample files is to simplify the instructions for setting up and example that demonstrates the Split Horizon EDS (https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/).

/assign @frankbu

### CODE REVIEW

**Comment by linsun** [comment]
@frankbu @ymesika looks good to me, i confirmed the 2 images exist in dockerhub.

@frankbu can you look at it?  We wanted to see if we can get it in today so it's part of the RC build.

**Comment by frankbu** [comment]
I think a better approach is to use labels like @vadimeisenbergibm did in https://github.com/istio/istio/pull/11503.

For the Gateway, I would suggest the article just use the `<<EOF` approach to inline the yaml, since it's specific to the multicluster approach.

**Comment by ymesika** [comment]
@frankbu Trying to use the labels approach it works but there is a confusing error:
```sh
unable to recognize "samples/helloworld/helloworld.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "samples/helloworld/helloworld.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
```
when deploying v2 on remote because we don't have CRD on Istio remote.

**Comment by frankbu** [comment]
Interesting, you get this errors even if the labels are not selecting Gateway/VS? Maybe we should put the CRDs on the remote cluster too? Maybe you are right and we should just put the Service/Deployments in helloworld.yaml, and put the gateway in a separate file (like we did with bookinfo).

**Comment by ymesika** [comment]
@frankbu PTAL

**Comment by ymesika** [comment]
cc @wenchenglu

**Comment by ymesika** [comment]
@wenchenglu Sorry for cc'ing you before all test passed.
It's fine now. Thanks.

**Comment by wenchenglu** [comment]
@ymesika thanks for pinging me. Not a problem at all.

**Pull request merged**
