### PR TITLE
WIP: Use string set for minimal memory consumption

### PR DESCRIPTION
**Pull request by supereagle**
Fix [comments](https://github.com/istio/istio/pull/9481#issuecomment-436697261) in #9481.

### CODE REVIEW

**Comment by supereagle** [comment]
@ozevren  You can refer to the context in https://github.com/istio/istio/pull/9481#issue-224990958

**Comment by ozevren** [comment]
Thanks. I think it would be more feasible to simply fix the offending cases and add a linter rule to avoid the pattern in the future. The package itself doesn't add much value beyond what the underlying map implementations do.

I am worried that /pkg is becoming a dumping ground for each and every little utility method/code-pattern we can think of. It should be more of a shared-library space for truly common idioms (i.e. command-line handling) or shared infrastructure (log), or high-value/deep-implementation libraries that needs to be shared(mcp).

**Comment by geeknoid** [comment]
I do agree that a linter rule would be nice to prevent backsliding.

However, I like the pattern of having an explicit set type, as opposed to a map[string]struct{}{}. Ans given that this utility can be used by the whole code base, it seems appropriate for the top-level plg directory, no?

**Comment by supereagle** [comment]
Have created issue alecthomas/gometalinter#560 to add a linter rule.

I think it is necessary to add an utility package for this pattern as `map[string]struct{}` is not convenient to directly use.

**Comment by nmittler** [comment]
Would it be sufficient to just define `type Empty struct{}`? I think it would be reasonable to see code using `map[string]Empty` directly, rather than relying on a string-specific set type.

**Comment by supereagle** [comment]
@nmittler  Thanks for point out this. I also notice that it is impossible to define type specific set for all types. So I think about defining a generic set `type Set map[interface{}]Empty` to cover all types, at the same time I find this method is also used in [golang-set](https://github.com/deckarep/golang-set).

**Comment by nmittler** [comment]
@supereagle should we just use [golang-set](https://github.com/deckarep/golang-set) then?

**Comment by geeknoid** [comment]
I think it you use map[interface{}], you'll end up causing boxing to happen
for any value type used in the set. So a set of ints would end up
allocating distinct objects in the heap for each int and the set would hold
pointers to those ints. In other words, it would actually substantially
increase memory use and reduce access speed.

Go doesn't have generics, except for the special-purpose built slice and
map types. As a result of this language deficiency, it's not possible to
build efficient & general-purpose collection types. You end up being
type-specific, or you end up with a lot of memory allocation for boxing.

**Comment by supereagle** [comment]
So we can define type specific sets only for built-in types, but not for customized types. 

Is it ok?  @geeknoid  @nmittler  @ozevren

**Comment by ozevren** [comment]
I think this is a case of solution growing out of proportions of the problem.

We want people to use map[<type>]struct{} pattern, instead of bool or any other value. The cure for that is the linter rule. That is the single most impactful fix to the problem. Adding new types for things that already exist in the language (albeit poorly done) will not make programmers use it. The implementation doesn't really help much with improving the client/caller code either. It just looks neater.  But it will be inconsistent unless it is migrated and enforced. I'd prefer if we simply added the linter rule. 

Now, if there is still desire to implement this, then it needs to be implemented in a type-specific manner, as mentioned above to avoid boxing. Having a generic "interface{}" version is probably a good idea for the sake of completeness, provided that it doesn't cause more allocations compared to a strongly typed version that would be implemented by devs manually otherwise. It also needs to be tested and all existing implementations should be converted, and protected by linter rule. Otherwise it will be yet another utility that we write and not really use.

**Comment by supereagle** [comment]
I think we have agreed on that a linter rule should be added for this, so I will first do this.

**Comment by ozevren** [comment]
@supereagle Thanks! It will be very useful.

**Pull request closed without merging**
