### PR TITLE
feat(charts): add volumes/volumemounts to istio gateway chart

### LINKED ISSUE #45878: Istio "Gateway" chart missing ability to inject custom volumes
**Describe the feature request**

_I am mainly wondering would a PR for this be accepted._

One of the cool features on the `IstioOperator` is the ability to use overlays to completely customize a given component. We've [done this](https://github.com/istio/istio/issues/34046) with some of our IngressGateways to inject custom Lua scripts into `/usr/local/share/lua/5.1`:

```
$ cat templates/lua-libs-configmap.yaml 
{{ $global := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $global.Release.Name }}-lua-libs
data:
  {{- range $path, $_ := .Files.Glob "lua/**.lua" }}
  {{- $file := $path | trimPrefix "lua/" | clean }}
  {{ $file }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{ end }}
---
$ find lua/*.lua
lua/base64.lua
lua/basexx.lua
lua/json.lua
```

We're working to transition away from the Operator, but we've noticed that https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml doesn't support injecting any custom volumes.

The question is whether or not a Pr would be accepted that would allow us to do this? 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by diranged**
**Please provide a description of this PR:**

Closes https://github.com/istio/istio/issues/45878 by enabling the end-user to supply custom `volumes` and `volumeMounts` parameters to each gateway.

### CODE REVIEW

**Comment by costinm** [comment]
I think it's a good and needed change, I like it. 

What I don't like is inconsistencies and hidden APIs. We have at least 4 ways to configure volumes already - each different (from the sidecar annotation, secret/config volumes in old gateway, pilot.VolumeMounts, etc). Helm values are an effective API - we have to support it for a long time. 

I think this is the cleanest and most flexible way to define the volumes and mounts - but I think we should have a high bar for API changes.

Could you write a small "Istio volumes and where to find them" doc (or a wiki page, issue), listing:
- the current volume mount config for the charts we have and sidecar
- evaluate if it is possible to backport this pattern (volumes/volumeMounts at top level in the chart) for the other templates, so users can have a consistent UX) - can happen in separate PRs

Since we are moving towards ambient, I'm not very concerned with the sidecar volumes and the annotation, but worth mentioning it for completeness.

Sorry for making it more difficult - but reviewing this I did a quick search and realized we have a mess and I doubt anyone knows all the ways we can mount volumes, and I remember I was able to configure volumes using K8S Gateway - but don't remember how or if it's a supported method...

**Comment by diranged** [comment]
@costinm I will take a stab at this over the weekend... but being this is my first contribution to the istio codebase, perhaps you can give me some shortcuts on where I'd look for existing docs and where I should potentially write this one?

**Comment by diranged** [comment]
@costinm It seems like two tests are failing in an unrelated way to my PR. What should I do about that?

**Comment by costinm** [comment]
Where to write - as long as it's on the internet we can find it, a wiki
page or issue are fine too. The goal is to have all the various volume
mounting options in one
place, and hopefully some discussion on what we can do to make things more
consistent.

I understand you're just making a small and pretty clean patch, if you
don't have time it's fine, I don't mean to block the PR and digging through
the dozen templates and options is tedious ( which is why we have a dozen
ways to do the same thing I guess...).

**Comment by diranged** [comment]
@costinm I tried to get to writing some docs this weekend - but was busy with a bunch of other PRs. Would you be willing to approve this as is for now, given that it's pretty simple overall and an improvement without any backwards breaking changes?

**Comment by diranged** [comment]
@costinm I've rebased this and pushed again... what do we need to do at this point to get this merged?

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
kindly ping on @jacob-delgado

**Review by jacob-delgado — APPROVED** [review]

**Comment by diranged** [comment]
I can’t see how my change would impact any tests like this… any thoughts?

**Comment by DavidSpek** [comment]
@zirain It looks like the PR to cherry pick this into release 1.19 wasn't created.

**Comment by zirain** [comment]
@DavidSpek 1.19 released, let's wait v1.20, it will be soon.

**Comment by DavidSpek** [comment]
@zirain https://github.com/istio/istio/pull/46683 is from a more recent PR that was also cherry picked into the current release channel. I'd be nice to have this included in the next patch release.

**Pull request merged**
