### PR TITLE
Better cert-rotation support in istio

### PR DESCRIPTION
**Pull request by rveerama1**
Certificate rotation is needed in case istiod is restarted, because a new plug-in CA might have been inserted.
This is the first step towards https://github.com/istio/istio/issues/30947 better cert-rotation support.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
I am not fully following the requirement here may @howardjohn is. But the implementation relying on getting all stats and comparing LDS version seems too fragile.

**Comment by rveerama1** [comment]
@ramaraochavali  Thanks for your comment. Please check out our intention to this changes from [here](https://github.com/istio/istio/issues/30947).
I am also pinging @shankgan (there is some feature recently pushed to upstream https://github.com/istio/istio/pull/30871) to take a look.

**Comment by howardjohn** [comment]
I agree with Rama. Does https://github.com/istio/istio/pull/30871 satisfy this completely?

**Comment by shankgan** [comment]
> I agree with Rama. Does #30871 satisfy this completely? - not completely. Have documented the pending requirements on https://github.com/istio/istio/issues/30947

**Comment by howardjohn** [comment]
Does it work with istiod restart ?

**Comment by shankgan** [comment]
I think this PR may be quite useful. My only issue with it is that it requires a restart of Istiod for proxies to get certs from the new CA. If we ever implement a fix to start using new ca certs on the fly, then requiring istiod to be restarted is unnecessary IMO.

**Comment by rveerama1** [comment]
> I think this PR may be quite useful. My only issue with it is that it requires a restart of Istiod for proxies to get certs from the new CA. If we ever implement a fix to start using new ca certs on the fly, then requiring istiod to be restarted is unnecessary IMO.

Is it Ok to continue with this PR until istio has support for restarting istiod not required to pick new CA ?

Otherwise can I take any part in the [RFC](https://docs.google.com/document/d/1EFMQZNlyImLP0k0HIyoBINntchqeUq7QQgc9O_jDwZ8/edit?ts=6034af98#) ?

**Comment by shankgan** [comment]
> > I think this PR may be quite useful. My only issue with it is that it requires a restart of Istiod for proxies to get certs from the new CA. If we ever implement a fix to start using new ca certs on the fly, then requiring istiod to be restarted is unnecessary IMO.
> 
> Is it Ok to continue with this PR until istio has support for restarting istiod not required to pick new CA ?
> 
> Otherwise can I take any part in the [RFC](https://docs.google.com/document/d/1EFMQZNlyImLP0k0HIyoBINntchqeUq7QQgc9O_jDwZ8/edit?ts=6034af98#) ?

Would it be possible for you to look into this feature (i.e not having to restart Istiod when we change the content of "cacerts")?

More specifically - In `createIstioCA`, we don't have a file-watcher over the contents of `cacerts`. This makes it difficult to do root-rotation when using plugin certs without restarting Istiod. Ideally, when we get an event-callback mentioning that contents of file/folder are changed, we need to alter the CA parameters (certificate/cert-chain). This will ensure that all new workloads are signed with the new cert parameters.  

@myidpt - What do you think?

**Comment by rveerama1** [comment]
> Would it be possible for you to look into this feature (i.e not having to restart Istiod when we change the content of "cacerts")?
Sure, I will look into this.
> 
> More specifically - In `createIstioCA`, we don't have a file-watcher over the contents of `cacerts`. This makes it difficult to do root-rotation when using plugin certs without restarting Istiod. Ideally, when we get an event-callback mentioning that contents of file/folder are changed, we need to alter the CA parameters (certificate/cert-chain). Some of that code can be borrowed from our SELF-SIGNED root-rotation library I think. This will ensure that all new workloads are signed with the new CA certs.

I think those are good pointers to start looking into this feature.

**Comment by rveerama1** [comment]
I am closing this, as we are trying to solve [this](https://github.com/istio/istio/issues/30947) with different [approach](https://github.com/istio/istio/pull/31522).

**Pull request closed without merging**
