### PR TITLE
Revert "Revert "Serviceentry handler optimization (#26405)""

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Reverts istio/istio#26480

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Please see https://github.com/istio/istio/issues/26465

**Comment by howardjohn** [comment]
Did you fix the flake? it looks identical but maybe I missed the change

**Comment by hzxuzhonghu** [comment]
The last commit

**Comment by hzxuzhonghu** [comment]
Running 100 times, without a failure

**Comment by howardjohn** [comment]
thanks!

**Pull request merged**
