### PR TITLE
Handle deactived webhook case for check-inject

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
This is used to optimize the deactived webhook case.
Before the PR, it is like:
```
WEBHOOK                     REVISION  INJECTED      REASON
istio-revision-tag-default  default   ✔             Namespace label istio-injection=enabled matches
istio-sidecar-injector      default   ✘             No matching namespace labels () or pod labels ()
```
After the PR, it is like:
```
WEBHOOK                     REVISION  INJECTED      REASON
istio-revision-tag-default  default   ✔             Namespace label istio-injection=enabled matches
istio-sidecar-injector      default   ✘             The injection webhook is deactivated, and will never match labels.
```

**Comment by hanxiaop** [comment]
@istio/wg-user-experience-maintainers PTAL thanks

**Comment by hanxiaop** [comment]
not stale

**Review by liamawhite — APPROVED** [review]
Apologies for letting this slip through the cracks. LGTM!

**Comment by hanxiaop** [comment]
not stale

**Review by howardjohn — APPROVED** [review]

**Comment by hanxiaop** [comment]
> **EasyCLA** Expected — Waiting for status to be reported

Has anyone encountered this before?

**Pull request merged**
