### PR TITLE
Fix test fail caused by #8606

### PR DESCRIPTION
**Pull request by yangminzhu**
I think #8606 gets merged by the bot without rebasing on the latest change on master. Some PR checked in after also needs to change but not included in #8606.

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Thanks for fixing this!

@hklai @sebastienvas @rkpagadala could you guys figure out why bot is merging stuff that breaks `master`?

**Comment by hklai** [comment]
@PiotrSikora all required tests passed in #8606.

I think prow always rebase before running tests. @sebastienvas can confirm and help figure out why.

**Comment by PiotrSikora** [comment]
@hklai yeah, the tests passed on the change itself, but the merge commit was failing, since there were other changes merged in the meantime that needed updating in the PR.

**Pull request merged**
