### PR TITLE
Remove standalone sidecar injector

### PR DESCRIPTION
**Pull request by howardjohn**
For https://github.com/istio/istio/issues/20441

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
running `git grep sidecar_injector` I see other references to this image. Do you also want to update those?

**Comment by howardjohn** [comment]
> running git grep sidecar_injector I see other references to this image. Do you also want to update those?

I removed some more references. There are still a couple in test/e2e but I think we can just remove all of those in another PR rather than try to dissect just the injector part

**Review by elfinhe — APPROVED** [review]

**Review by rshriram — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Pull request merged**
