### PR TITLE
Refactor ADSC

### PR DESCRIPTION
**Pull request by adiprerepa**
[ X] Networking

This refactors the ADSC package in `/pkg` into the test package. ADSC is only used by test files, therefore, should be in the test package. This was come to agreement in #24344.

### CODE REVIEW

**Comment by adiprerepa** [comment]
@hzxuzhonghu

**Comment by howardjohn** [comment]
it will definitely be used by istioctl (there is a pr doing so) but I don't think the agent should use it(?). At least not in it's current state. I would think the agent is proxying discovery requests not initiating them

**Comment by adiprerepa** [comment]
@howardjohn @costinm Thats what I was thinking. Would #24344 be valid in that case? Those are unit tests for ADSC.

**Comment by adiprerepa** [comment]
all right, closing.

**Comment by hzxuzhonghu** [comment]
Sorry, I do never know it is used by istioctl.

**Pull request closed without merging**
