### PR TITLE
Fix experimental metrics cli

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR fixes a regression with the experimental metrics CLI. It updates the queries to match recent telemetry changes and undoes some of the formatting errors that slipped through in a previous PR.

There is no risk in merging this PR.

### CODE REVIEW

**Comment by douglas-reid** [comment]
And `ImagePullBackOff` for bookinfo apps in CircleCI. Fan-tastic!

**Comment by douglas-reid** [comment]
I don't know how to address the CircleCI image issue.  The logs look like:

```
* command failed: "Error from server (BadRequest): container \"details\" in pod \"details-v1-584f6fb7cd-9xpqk\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"mongodb\" in pod \"mongodb-v1-6b566574dd-6ss52\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"productpage\" in pod \"productpage-v1-864d566c4-hxmmv\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"ratings\" in pod \"ratings-v1-65988bbd5d-c5b75\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"ratings\" in pod \"ratings-v2-7787fc67bf-qq74s\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"reviews\" in pod \"reviews-v1-574d949dbd-67z7h\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"reviews\" in pod \"reviews-v2-6dcdd44494-9cqsh\" is waiting to start: trying and failing to pull image\n" exit status 1
* command failed: "Error from server (BadRequest): container \"reviews\" in pod \"reviews-v3-69c7bdc8b8-brlql\" is waiting to start: trying and failing to pull image\n" exit status 1
```
Rerunning the test does not result in being able to pull the images. The test itself never gets to execute because of these setup issues. 

@costinm This PR does not impact any tests and cannot be causing breakages. Please advise on how to proceed.

**Comment by douglas-reid** [comment]
trying `docker pull krancour/examples-bookinfo-reviews-v1:1.9.0` returns: 
`Error response from daemon: pull access denied for krancour/examples-bookinfo-reviews-v1, repository does not exist or may require 'docker login'`

**Comment by douglas-reid** [comment]
@krancour any ideas why CircleCI can no longer access the docker images?

**Comment by krancour** [comment]
The images you referenced above were temporary, unofficial, and no longer exist.

If you're fully rebased, the official images should be in use.

**Comment by douglas-reid** [comment]
@krancour yup. thanks. i thought i had been working out of a fully-fresh branch. turns out, it was stale by several days. rebase appears to have fixed it right up. thanks again.

**Pull request merged**
