### PR TITLE
Add Affinity and Tolerations for deployment

### PR DESCRIPTION
**Pull request by ikrozhkov**
**Please provide a description of this PR:**
Add ability to configure `Affinity` and `Tolerations` for istiod deployment based on [values](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml).
Example of usage:
```yaml
pilot:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/istio
            operator: Exists
  tolerations:
  - key: "node-role.kubernetes.io/istio"
    operator: "Exists"
    effect: "NoSchedule"
```
BTW, [Gateway](https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml#L81-L83) already have ability to configure this.

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @IKRozhkov if you can sign the CLA that'd be great. This lgtm.

**Comment by IKRozhkov** [comment]
> cc @IKRozhkov if you can sign the CLA that'd be great. This lgtm. I'll sign it when you do.

I've signed it right after creating this PR. What should I do to pass the CLA checks?
image

**Comment by jacob-delgado** [comment]
> > cc @IKRozhkov if you can sign the CLA that'd be great. This lgtm. I'll sign it when you do.
> 
> I've signed it right after creating this PR. What should I do to pass the CLA checks?

Is the email you used to sign the CLA the same one that is authored for this PR?

**Comment by IKRozhkov** [comment]
> > > cc @IKRozhkov if you can sign the CLA that'd be great. This lgtm. I'll sign it when you do.
> > 
> > 
> > I've signed it right after creating this PR. What should I do to pass the CLA checks?
> 
> Is the email you used to sign the CLA the same one that is authored for this PR?

Yes. I set up the same email everywhere.

**Comment by jacob-delgado** [comment]
> > > > cc @IKRozhkov if you can sign the CLA that'd be great. This lgtm. I'll sign it when you do.
> > > 
> > > 
> > > I've signed it right after creating this PR. What should I do to pass the CLA checks?
> > 
> > 
> > Is the email you used to sign the CLA the same one that is authored for this PR?
> 
> Yes. I set up the same email everywhere.

Can I resubmit your PR under my email? I don't know much about the CLA bot to say why it is failing. You can also talk about this PR at the environments WG meeting this week if you'd like to get this merged. Thanks!

**Comment by howardjohn** [comment]
Just needed to click re-run in the CLA page. Any maintainer can do this now I think

**Review by jacob-delgado — APPROVED** [review]

**Comment by jacob-delgado** [comment]
cc @IKRozhkov get the lint/gen to pass and I'll get this merged in.

**Comment by morvencao** [comment]
The changes have been merged in another [PR](https://github.com/istio/istio/pull/37513).

**Pull request closed without merging**
