### PR TITLE
[Kiali] [release-1.0] bump up to next version

### PR DESCRIPTION
**Pull request by jmazzitelli**
@gbaufake - please review

### CODE REVIEW

**Comment by gbaufake** [comment]
@jmazzitelli 
I think https://github.com/kiali/kiali/pull/629 will impact on pre-1.1 release process.

**Comment by jmazzitelli** [comment]
> @jmazzitelli
> I think [kiali/kiali#629](https://github.com/kiali/kiali/pull/629) will impact on pre-1.1 release process.

What do you think are the issues? The helm stuff is independent of the file changes in that Kiali 629 PR... since the ansible stuff should be pointing to the v0.10 branch, it should still be able to pull in the correct (older) yaml files.

**Comment by gbaufake** [comment]
You are right! Thanks for pointing that out.

**Comment by sdake** [comment]
@jmazzitelli might try another rebase...

**Pull request merged**
