### PR TITLE
fix proxy image names in injection configmap

### PR DESCRIPTION
**Pull request by ayj**
Alternative to https://github.com/istio/istio/pull/2887

### CODE REVIEW

**Comment by ayj** [comment]
Alternatively, users can use kube-inject to generate the template and create the configmap on the fly.

```bash
kubectl create configmap istio -n istio-system \
    --from-file=template=<(istioctl kube-inject --emitTemplate) \
    --from-literal=policy=enabled
```

**Comment by ldemailly** [comment]
thx

**Pull request merged**
