### PR TITLE
Only allow one replica of Citadel

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is for the issue: https://github.com/istio/istio/issues/13383

### CODE REVIEW

**Comment by jcetkov** [comment]
@lei-tang I'm OOO this week, I can have a look next week, if it's not too late

**Comment by JimmyCYJ** [comment]
/lgtm

Could you please set up an experiment and verify that this fix prevents us from setting replica via variable?

**Comment by lei-tang** [comment]
@mandarjog https://github.com/istio-ecosystem/istio-installer/pull/45 has been created on https://github.com/istio-ecosystem/istio-installer.

**Comment by lei-tang** [comment]
#https://github.com/istio-ecosystem/istio-installer/pull/45

**Comment by duderino** [comment]
Thanks @lei-tang.  This will be in 1.1.4

**Pull request merged**
