### PR TITLE
Remove multicluster from samples

### PR DESCRIPTION
**Pull request by nschhina**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
Where were these scripts used in the past? Are we sure there are no more references to them anywhere in the docs?

**Comment by nmittler** [comment]
@frankbu I just searched istio.io for "samples/multicluster" and found nothing.

**Comment by nschhina** [comment]
> @frankbu I just searched istio.io for "samples/multicluster" and found nothing.

same

**Comment by ericvn** [comment]
I checked and the only place I found them used was in istio.io/istio.io/archive/v1.4/docs/setup/install/multicluster/simplified/index.html
istio.io/istio.io/archive/v1.4/docs/examples/bookinfo-multicluster/index.html
istio.io/istio.io/archive/v1.5/zh/docs/setup/install/multicluster/simplified/index.html
istio.io/istio.io/content/zh/docs/setup/install/multicluster/simplified/index.md

and they pointed to the specific release branch in istio/istio

**Pull request merged**
