### PR TITLE
Revert "Add mixer tests for the Istio authn filter (#5267)"

### PR DESCRIPTION
**Pull request by bianpengyuan**
Test out if this causes mixer client test failure. #5424

### CODE REVIEW

**Comment by bianpengyuan** [comment]
cc @lei-tang

**Comment by lei-tang** [comment]
#5430

**Comment by lei-tang** [comment]
With #5430, the istio-unit-tests passed.

**Comment by lei-tang** [comment]
#5443

**Comment by lei-tang** [comment]
The PR https://github.com/istio/istio/pull/5443 removes the newly added authn mixer tests in https://github.com/istio/istio/pull/5267 and duplicates tcp_filter_v1_config_test to debug whether the mixer test problem is caused by https://github.com/istio/istio/pull/5267.

**Comment by lei-tang** [comment]
With the PR #5443 removing the newly added authn mixer tests in #5267 and duplicating tcp_filter_v1_config_test,  the istio unit tests still fail with the same symptoms. This indicates that the existing mixer tests have problems.

**Comment by hklai** [comment]
Merging this to unblock other developers.

@lei-tang will try to root cause the test failures separately.

**Pull request merged**
