### PR TITLE
add PROXY_REPO_SHA removing overloaded meaning of PROXY_TAG

### LINKED ISSUE #4157: Clear up confusion around proxy tag
PROXY_TAG is being used as the tag for the docker image and also as the sha of the istio/proxy to use as base for building the docker proxy image in this repo. This dual is wrong and confusing,

### PR DESCRIPTION
**Pull request by rkpagadala**
PROXY_TAG now refers to the docker image tag build from file pilot/docker/Dockerfile.proxy or pilot/docker/Dockerfile.proxy_debug
PROXY_REPO_SHA refers to the sha of istio/proxy, and is used to download the envoy binary used to build the proxy docker image referred above. 
fixes #4157

### CODE REVIEW

**Comment by mattdelco** [comment]
Will there also be a corresponding change to the daily qualification tests, e.g. https://github.com/istio-releases/daily-release/blob/master/prow/daily-e2e-cluster_wide-auth-skew.sh#L39  ?

Otherwise, this change is a step in the right direction, though if PROXY_HUB/TAG is now for pilot's proxy then the rule for istio-archive in the Makefile probably needs to change what it passes to install/updateVersion.sh.  At a minimum -r probably needs to be changed from $(VERSION) to $(VERSION), though really this parameter should be modified to behave like the other parameters and handle the hub,tag representation (so that PROXY_HUB can be set, which I think it can't currently be set via the command-line except via ALL_HUB_TAG.  An option is to start having the Makefile use -a rather than the separate parameters for pilot, proxy, mixer, ca.

**Comment by mattdelco** [comment]
Actually, I suppose the tag value that's passed to -r is already okay (my comment on "from $(VERSION) to $(VERSION)" was sadly nonsensical), and the only issue might be that PROXY_HUB isn't explicitly set when -r (et al) is used instead of -a.  I'm not sure offhand where PROXY_HUB is set during a release build since I don't think the build sets it and a default isn't present in istio.VERSION (unless I'm overlooking on of those strange places where PROXY_HUB defaults to the value of PILOT_HUB.

**Comment by rkpagadala** [comment]
PILOT_HUB is used where PROXY_HUB should be logically. Fixed all that and got rid of istio.VERSION

**Comment by sebastienvas** [comment]
this PR got merged but it failed all e2e. Something is wrong with generated yaml

**Comment by mattdelco** [comment]
I know I'm beating a dead (or should I say reverted) horse, but on any subsequent attempt to delete istio.VERSION be sure to grep across the various for uses of the file (e.g., the releae build failed because the ${ISTIO_OUT}/archive rule in the Makefile has a dependency on the then-missing istio.VERSION).

**Comment by rkpagadala** [comment]
The most important change from the previous diff is setting the defaults copied from istio.VERSION
https://github.com/istio/istio/pull/4179/files#diff-c864be78fb30a2c170271b1b64576a9dR52

**Pull request merged**
