### PR TITLE
Fix dead link

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This file is autogenerated from ./operator/scripts/run_update_golden_snapshots.sh

**Comment by daixiang0** [comment]
@howardjohn could remove this doc? It would lead to misunderstand.

**Comment by howardjohn** [comment]
@daixiang0 this folder is for testdata input. It is not intended for users to read.

You could enhance the script I mentioned to only pull in relevant files (likely just `**/*.yaml`) perhaps

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
