### PR TITLE
Remove implicit usage of 'busybox:latest'

### PR DESCRIPTION
**Pull request by loewenstein**
Cherry-pick of #11812

### CODE REVIEW

**Comment by sdake** [comment]
leets hold off on master prs until we have master in a functional shape.

**Comment by loewenstein** [comment]
Not stale

**Comment by sdake** [comment]
@loewenstein did this make it into 1.1?

If so, I expect someone will perform one last merge from release-1.1 to master.

Cheers
-steve

**Comment by loewenstein** [comment]
@sdake it did. With a merge back this PR will of course be unnecessary.

**Comment by sdake** [comment]
as this work is in master, I am closing this PR.  If you feel this decision was made in error please reopen the PR.

Cheers
-steve

**Pull request closed without merging**
