### PR TITLE
[DO NOT MERGE] Auto PR to update dependencies of istio

### PR DESCRIPTION
**Pull request by sebastienvas**
This PR will be merged automatically once checks are successful.

### CODE REVIEW

**Comment by sebastienvas** [comment]
This looks pretty nice. Thanks @chxchx. Let's see if this gets automerged.

**Comment by yutongz** [comment]
/lgtm cancel
@sebastienvas The issue, we need a github approval in istio/istio

**Comment by sebastienvas** [comment]
So adding the merge robot to skip review does not work since it needs to
create the PR. I guess I need to remove that requirement for admins.

**Comment by sebastienvas** [comment]
I guess I need to give exceptions to istio-testing not the merge bot.
/close

**Pull request closed without merging**
