### PR TITLE
Add unit test for increase test coverage (#15599)

### PR DESCRIPTION
**Pull request by pitlv2109**
Manually cherry-pick from #15599.

### CODE REVIEW

**Comment by pitlv2109** [comment]
Prow tests passed but GitHub failed to pull the results. I will rerun them

**Comment by pitlv2109** [comment]
@fpesce Doesn't seem like commands for tests are executing

**Comment by pitlv2109** [comment]
@howardjohn Tests didn't report results and I couldn't rerun them.

**Comment by fpesce** [comment]
Trying a close/reopen

**Pull request merged**
