### PR TITLE
Bug fixes in SNI forwarding for external services

### PR DESCRIPTION
**Pull request by rshriram**
Multiple filter chains were not being setup properly.
SNI forwarding still does not work when there are multiple hosts on same port
with different filter chains. The issue is in Envoy. But this code should
work once proxy sha is updated or go control plane SHA is updated.
If doing the latter, replace sniDomains by serverNames.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by mandarjog** [comment]
@PiotrSikora cc

**Comment by PiotrSikora** [comment]
> SNI forwarding still does not work when there are multiple hosts on same port
with different filter chains. The issue is in Envoy.

@rshriram Could you elaborate?

**Comment by rshriram** [comment]
This piece of config (ignore camel case as its printed) does not work
```json
{
  "name": "0.0.0.0_443",
  "address": {
    "socketAddress": {
      "address": "0.0.0.0",
      "portValue": 443
    }
  },
  "filterChains": [
    {
      "filterChainMatch": {
        "sniDomains": [
          "google.com"
        ]
      },
      "filters": [
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "deprecated_v1": true,
              "value": {
                    "route_config": {
                          "routes": [
                                {
                                      "cluster": "outbound|443||google.com"
                                    }
                              ]
                        },
                    "stat_prefix": "outbound|tcp|443"
                  }
            }
        }
      ]
    },
    {
      "filterChainMatch": {
        "sniDomains": [
          "www.wikipedia.org"
        ]
      },
      "filters": [
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "deprecated_v1": true,
              "value": {
                    "route_config": {
                          "routes": [
                                {
                                      "cluster": "outbound|443||www.wikipedia.org"
                                    }
                              ]
                        },
                    "stat_prefix": "outbound|tcp|443"
                  }
            }
```

while this config (single SNI match in filter chain) works
```json
{
  "name": "0.0.0.0_443",
  "address": {
    "socketAddress": {
      "address": "0.0.0.0",
      "portValue": 443
    }
  },
  "filterChains": [
    {
      "filterChainMatch": {
        "sniDomains": [
          "www.wikipedia.org"
        ]
      },
      "filters": [
        {
          "name": "envoy.tcp_proxy",
          "config": {
              "deprecated_v1": true,
              "value": {
                    "route_config": {
                          "routes": [
                                {
                                      "cluster": "outbound|443||www.wikipedia.org"
                                    }
                              ]
                        },
                    "stat_prefix": "outbound|tcp|443"
                  }
            }
        }
      ]
    }
  ],
  "deprecatedV1": {
    "bindToPort": false
  }
},
```

**Comment by PiotrSikora** [comment]
Per discussion offline, filter chain matching works fine, but each of the generated clusters contains  hosts from all clusters in that listener.

**Pull request merged**
