### PR TITLE
Fortio move

### PR DESCRIPTION
**Pull request by ldemailly**
Fortio move to its own repo
GitHub.com/istio/fortio
```release-note
fortio (istio perf tool) is now in its own repo (github.com/istio/fortio)
```

### CODE REVIEW

**Comment by ldemailly** [comment]
side benefits; istio-presubmit is much faster now; as it doesn't build the fortio images anymore

can I have a quick /lgtm ?

**Comment by costinm** [comment]
/lgtm

Do you need bazel for it ? Why not 'go get' from start ?

**Comment by ldemailly** [comment]
I had bazel files to conform with istio/istio practices but yes the new repo has no bazel files (so far)

**Comment by sebastienvas** [comment]
Thanks for doing this and sorry for the delay.

**Pull request merged**
