### PR TITLE
Fix proxy concurrency detection

### PR DESCRIPTION
**Pull request by howardjohn**
Currently, concurrency configuration is pretty broken.

We have 3 knobs:
* ProxyConfig.Concurrency
* --concurrency flag in agent
* Automatic logic during injection that attempts to automatically set --concurrency

In the agent, we also have logic to ignore the default ProxyConfig.Concurrency for gateways.

Concurrency is critical to performance. On my 48 core nodes, with ingress limit=2CPUs, I see 3x higher throughput with 2 CPUs vs 48 CPUs. However, today we would set it to 48 CPUs in most cases. On the flip side, with higher CPU limits, we want higher concurrency. Today, sidecars can never utilize higher CPU limits - the concurrency is always bound to a static value, leaving performance on the table.

The logic today is inconsistent and broken:

**Un-injected gateway:** will read `istio` configmap (only if its in istio-system!) defaultConfig, or proxy.istio.io annotation, or use all cores. Never CPU limit aware
**Injected gateways:** will use defaultConfig or proxy.istio.io annotation if set, or use all cores. Never CPU aware
**Sidecars:** will use defaultConfig or proxy.istio.io annotation if set. Partially CPU aware (see below). Can never "use all cores", even if configured to do so.
**Gateway/waypoint auto deployed:**   will use defaultConfig or proxy.istio.io annotation if set, or use all cores. Never CPU aware

All injection logic is broken, because it only evaluates the `sidecar.istio.io/proxyCPULimit` annotation, which is only one of many ways to set the CPU limits. We need to process the CPU limit *after* the result of injection.

---

This PR introduces new logic, which is far simpler:

```
if --concurrency set (it never will be in default installs) { use it }
else if ProxyConfig.Concurrency is explicitly set { use it }
else { detect based on CPU limit }
```

This logic is the same between sidecars, gateways, waypoints, etc - injected or otherwise.

This means, out of the box, all users will have concurrency=2 set, because the default CPU limit we set on Gateways and sidecars is "2". As CPU limit is adjusted, the concurrency will scale with it. Users can override this with proxyConfig, either mesh-wide or per-pod with annotation.

---

Related: https://github.com/istio/istio/issues/41351

---

Currently, the ProxyConfig API:

```
	// The number of worker threads to run.
	// If unset, this will be automatically determined based on CPU requests/limits.
	// If set to 0, all cores on the machine will be used.
	// Default is 2 worker threads.
```
The last line will be removed. Note the *behavior* of "2 worker thread defaults" will be preserved, but only because of the default limits set in the default install. Also, that only applied to sidecars, so it was misleading.

### CODE REVIEW

**Review by dhawton — APPROVED** [review]
Release note looks good.

**Comment by kyessenov** [comment]
running gateways with 2 cores is never really recommended? why would we set it as default?

**Comment by howardjohn** [comment]
> running gateways with 2 cores is never really recommended? why would we set it as default?

Feel free to submit a PR to change the default if you believe it should. I don't think asking "why" we made a decision ~5 years ago is productive (unless someone wants to dig up ancient history), nor should it block this PR given this adapts to whatever CPU limit we set (2 or otherwise)

**Comment by kyessenov** [comment]
I think we should be very careful about changing any behavior, no matter how broken it is, because users depend on the "brokenness" in weird ways. 

This PR specifically is modifying the injection templates and important logic in obscure ways, and that's a substantial change.

**Comment by kyessenov** [comment]
In particular the original estimates for CPU/memory per core were not updated in more than a year - we don't even know if the estimation logic is helpful?

**Comment by howardjohn** [comment]
This PR is reverting a behavioral regression introduced in https://github.com/istio/istio/pull/32928, which made it so that gateways no longer detect concurrency appropriately, leading to substantial performance regression for most gateway users who run with the default limit of 2 CPUs on >2 CPU nodes.

> This PR specifically is modifying the injection templates and important logic in obscure ways, and that's a substantial change.

I don't know that its obscure... We used to have complex + incorrect logic in the injection code to determine what concurrency to set, now just use standard k8s mechanism to have an environment variable tell us the CPU limit and set concurrency to match that. I am not sure it can get much simpler than that.

---

**Review by ramaraochavali — APPROVED** [review]

**Review by hanxiaop — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Comment by Kyslik** [comment]
@howardjohn we are experiencing:

```
Invalid template: template: inject:212:12: executing "inject" at <.EstimatedConcurrency>: can't evaluate field EstimatedConcurrency in type *inject.SidecarTemplateData
```

Which is indeed:

```
{{- if gt .EstimatedConcurrency 0 }} <- line 212
  - --concurrency
  - "{{ .EstimatedConcurrency }}"
{{- end -}}
```

Is this related to what you refer to in your PR description, or I should open new Issue?

> All injection logic is broken, because it only evaluates the sidecar.istio.io/proxyCPULimit annotation, which is only one of many ways to set the CPU limits. We need to process the CPU limit after the result of injection.

For context: we are upgrading from `1.13.x` to `1.17.1` and we are using official chart.

**Comment by Shadowssong** [comment]
@Kyslik Did this resolve for you when upgrading past 1.17?  I ran into the exact same issue and verified that its fixed if I remove those lines from the sidecar-injection template config map.  I don't install with the chart, we are installing via istioctl but I'm not sure if that also pulls the same manifests that the chart uses

**Comment by huggsboson** [comment]
As a note: Count my company amongst the users relying on the "brokeness" we relied on --concurrency=0 to achieve auto-detection behavior and while upgrading versions discovered the behavior had changed when we were running out of memory.

**Comment by chlunde** [comment]
In case someone else stumbles upon this: A very small pod (cpu req 0.025 cores) with a sidecar without CPU limits, on a large 192 core node, seems to cause envoy to spend 10% of a core on internal work due to the number of threads. This in turn can cause the HPA to scale it up to a lot of pods.

**Comment by lucytang2017us** [comment]
May I get a bit clarification on this feature:
--This would allow auto-determination of worker threads in a sidecar based on its CPU limit, not actual CPU usage? if true, we would still need to determine the CPU limit properly.
--Would it be feasible to auto-scale the worker threads based on actual CPU utilization? this might introduce concerns such as continuously watching the usage stats/trending, so won't scale it too frequently, any negative impact when scale down and tear down existing connections, etc. This could solve the challenge today: endless performance tests required in order to determine/adjust the number of worker threads for each sidecar. Especially in large scaled/complicated topology with multi consumers <=> multi producers communications.

Appreciated.

**Comment by howardjohn** [comment]
> --Would it be feasible to auto-scale the worker threads based on actual CPU utilization? this might introduce concerns such as continuously watching the usage stats/trending, so won't scale it too frequently, any negative impact when scale down and tear down existing connections, etc. This could solve the challenge today: endless performance tests required in order to determine/adjust the number of worker threads for each sidecar. Especially in large scaled/complicated topology with multi consumers <=> multi producers communications.

I don't think Envoy can change the number of threads dynamically. So hypothetically you could have something like VPA that tunes it, but that would need to be built. If you had VPA configure CPU limit based on CPU usage, that would automatically tune the threads as well with htis PR

**Comment by lucytang2017us** [comment]
See your point: The VPA is a proper solution for the sidecar resource usage limit concern. 
The number of worker threads could be determined by other factors, not only or directly by the CPU usage/limit, such as the traffic throughputs and the nature of the collocated application.

Appreciated.

**Pull request merged**
