### PR TITLE
Update to latest images

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR attempts to restore working state for e2e tests.

Reviewers: please confirm that the image tags are appropriate. I updated the mixer tag to `gcr.io/istio-testing` and a build tag generated by gcb from the most recent PR (at time of this PR). I couldn't find any recent builds on docker hub, and I wasn't sure what was going on with the jenkins builds.

### CODE REVIEW

**Comment by kyessenov** [comment]
This isn't using tip of pilot, which is 5b55952f9c27d6a29a8cbcdcbd522de1cff44e9e.

**Comment by douglas-reid** [comment]
@kyessenov thanks. testing local and then will push correct SHA here.

**Comment by douglas-reid** [comment]
PTAL. Updated to pilot tip.

**Comment by douglas-reid** [comment]
build istio/presubmit

**Comment by ldemailly** [comment]
looks like something is off with istioctl url/path ?

/home/jenkins/workspace/istio-armada-release-test/tests/commonUtils.sh: line 61: ../istioctl: cannot execute binary file: Exec format error

**Comment by douglas-reid** [comment]
yes. after i pushed the PR, i had to go and manually update the binaries. the IBM test started after i built and pushed the linux version. restarting it should fix it.

**Comment by sebastienvas** [comment]
What kind of SHA is this for MIXER_TAG ? does it map back to a SHA in mixer repo ?

**Pull request merged**
