### PR TITLE
Add config option 'imagePullSecret' to the installation options file

### PR DESCRIPTION
**Pull request by johnma14**
This feature was added last year and is part of the Helm charts ( istio/istio@7759947) but this option never got included in the installation options file. This PR is to fix the issue reported in this original PR: https://github.com/istio/istio.io/pull/4446

### CODE REVIEW

**Comment by johnma14** [comment]
@howardjohn it wasn't included in the installation options file because it did not have a value. So for example, consider these examples:
1) global:
       imagePullSecret:
         - foo1
         - foo2

2) global:
       imagePullSecret: 

In 1), global does not have a value since it is part of a nested element, whereas imagePullSecret has values. So the way the generator script works is, it needs to filter this so that we correctly
get global.imagePullSecret = ['foo1', 'foo2']

In 2), global and imagePullSecret both have no value, so it is ignored (which is what was happening with this value in the values.yaml file). Instead, if it is empty we should either use an empty string "" or empty list or dictionary.

Regarding the change in description, @brian-avery wanted an updated description. Hope this helps.

**Comment by sdake** [comment]
> Why wasn't it included before? It seems like it already had a comment?

good question, perhaps the docification code doesn't handle multiple line comments?  If that is the case, it should.  Still this docification is easier for mere humans to understand :)

**Comment by howardjohn** [comment]
All authors explicitly sent this work, cla bot is just not very smart... Setting to yes

**Comment by sdake** [comment]
> @howardjohn it wasn't included in the installation options file because it did not have a value. So for example, consider these examples:
> 
> 1. global:
>    imagePullSecret:
>    - foo1
>    - foo2
> 2. global:
>    imagePullSecret:
> 
> In 1), global does not have a value since it is part of a nested element, whereas imagePullSecret has values. So the way the generator script works is, it needs to filter this so that we correctly
> get global.imagePullSecret = ['foo1', 'foo2']
> 
> In 2), global and imagePullSecret both have no value, so it is ignored (which is what was happening with this value in the values.yaml file). Instead, if it is empty we should either use an empty string "" or empty list or dictionary.
> 
> Regarding the change in description, @brian-avery wanted an updated description. Hope this helps.

I'm not sure using an empty list or dictionary or string will work for all cases.  The installation code assumes an empty list is not the determining factor, but whether the value is defined at all (I think, but am not 100%).

It would be far better to make the documentation parser parse these comments and produce correct output when not key/value pair is found.

**Comment by johnma14** [comment]
@sdake Key value pairs without a value get ignored at this line: https://github.com/istio/istio.io/blob/master/scripts/tablegen.py#L242. So the description gets processed only for the key-value pair that makes it into the `prdict` dictionary. I will see if there is a way I can modify the code to correctly identify valid empty key-value pairs.

**Pull request merged**
