### PR TITLE
annotation deprecation and alpha status analyzer (#29918)

### PR DESCRIPTION
**Pull request by esnible**
Cherry pick https://github.com/istio/istio/pull/29918 into 1.9

### CODE REVIEW

**Comment by esnible** [comment]
I don't understand why the release notes test is failing with

```
failed to find any release notes.
No release notes files found in '/releasenotes/notes/'.
```

**Comment by stevenctl** [comment]
`destination branch: master`.. I'll check the prow job config.

**Comment by stevenctl** [comment]
Oh, did you change the target branch after creating the PR? Looks like the failing job isn't required.

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
