### PR TITLE
Fix: adsc is blocked by sync chan

### PR DESCRIPTION
**Pull request by zhaohuabing**
Signed-off-by: huabing zhao <huabingzhao@tencent.com>

Please provide a description for what this PR is for.

Fix the issue in adsc: handleRecv is blocked by sync chan.  

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@googlebot I fixed it.

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by zhaohuabing** [comment]
@hzxuzhonghu thanks for the reviewing.  

integ-pilot-multicluster-test_istio failed.  I'm sorry I can't figure out the reason. I'm not familiar with the integration tests.  Is the failure relevant to this pr?

+ kubectl apply --kubeconfig=/tmp/tmp.FS0ZOQRmcW/cluster2 -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
error: unable to recognize "https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
+

**Comment by hzxuzhonghu** [comment]
I donot think it is related, adsc is actually not used by multicluster test

**Pull request merged**
