### PR TITLE
Improve security/registry coverage

### PR DESCRIPTION
**Pull request by diemtvu**
https://github.com/istio/istio/issues/3957

### CODE REVIEW

**Comment by ldemailly** [comment]
please update the title of the pr to be informative like from "Fixit" now to "Improve security coverage"

the codecov numbers seems out of whack (-22%...), @sebastienvas any idea?

**Comment by diemtvu** [comment]
Does anyone know why ci/circleci: test fail? I don't think this PR cause that.

**Comment by myidpt** [comment]
I don't know why these tests fail... Can you rebase to trigger the circleci again?

**Comment by myidpt** [comment]
I ignored the codeCov change since it can't be decreasing.

**Pull request merged**
