### PR TITLE
Add release-1.17 branch to dependabot go configuration

### PR DESCRIPTION
**Pull request by pmerrison**
**Please provide a description of this PR:**
This is the release-1.17 version of this PR https://github.com/istio/istio/pull/45598

### CODE REVIEW

**Comment by zirain** [comment]
@pmerrison wrong target branch?

**Comment by pmerrison** [comment]
> @pmerrison wrong target branch?

No, dependabot configuration should be in the default branch of the repository.  As far as I know, it ignores configuration that's in any other branch.

**Comment by ericvn** [comment]
Note from my Slacks yesterday, the we can specify additional branches but they are only used for version updates which we do not have configured. The docs state that the security updates will only run against the default branch. I believe that is why we aren't seeing any security updates against the 1.18 branch.

**Comment by pmerrison** [comment]
> Note from my Slacks yesterday, the we can specify additional branches but they are only used for version updates which we do not have configured. The docs state that the security updates will only run against the default branch. I believe that is why we aren't seeing any security updates against the 1.18 branch.

I just caught up with that, how annoying - I'll close this PR then, thanks @ericvn

**Pull request closed without merging**
