### PR TITLE
move pkg/mcp/configz to pkg/mcp/configz/client

### PR DESCRIPTION
**Pull request by clyang82**
As part for this feature #12298, I have introduced `pkg/mcp/configz/server` so that move the rest to `pkg/mcp/configz/client`

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by clyang82** [comment]
/assign @hzxuzhonghu
Could you help to review this PR? Thanks.

**Comment by kyessenov** [comment]
Removing myself since I'm not an owner or approver for pkg/mcp.

**Comment by ozevren** [comment]
You'll need to rebase or merge changes.

**Pull request merged**
