### PR TITLE
fix envoyFilter order

### PR DESCRIPTION
**Pull request by rokkiter**
**Please provide a description of this PR:**

Fix https://github.com/istio/istio/issues/45089

If the EnvoyFilter has a delete operation, there will be problems in the following scenarios:  
1. Delete filter A and then add filter A, the added filter A will still be deleted

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Thanks for the PR! Nice find. Can you extend the unit tests here to provide coverage?

**Comment by hzxuzhonghu** [comment]
Run delete at last was intended originally, but good to change this as we have introduced priority concept, so it makes sense to me first we run patching according to the priority, and within same priority run delete at last

**Comment by rokkiter** [comment]
thanks to review, I'm going to add unit tests, but I tried it yesterday, and the results of the unit tests confuse me, I may need some time to understand the relevant code

**Review by hzxuzhonghu — COMMENTED** [review]
Do i misread it, i could not fund the tests with different priorities

**Comment by rokkiter** [comment]
I'm very sorry, I think I misunderstood your meaning before, UT has been updated, please review

**Review by hzxuzhonghu — APPROVED** [review]
LGTM

**Comment by wulianglongrd** [comment]
envoyfilter's `priority` feature looks like an incomplete implementation, it is only used for sorting in `initEnvoyFilters`. In the XDS translation, most places are processed according to the order of `patch.operation`, but not `priority`, for example, CDS patch MERGE first and then ADD, HTTP_ROUTE patch REMOVE/MERGE first, then ADD, and so on.

**Comment by psinghal20** [comment]
@rokkiter @hzxuzhonghu are there any plans to backport this change to 1.17 and older releases?

**Comment by hzxuzhonghu** [comment]
I'd suggest not, because what it fixes is not a common case, and we may need this patch to be tested thoroughly

**Comment by epaulson10** [comment]
> what it fixes is not a common case

This add and delete functionality is explicitly recommended in this issue: https://github.com/istio/istio/issues/29425

I am a sample size of one, but this broke a custom EnvoyFilter that I had to write to reorder the Cors filter above an ExtAuthz filter.

**Comment by nils-dehn-db** [comment]
For those who came here to look for a solution to the REMOVE op bug until it gets released:
The mentioned REMOVE op problem applies to NETWORK_FILTER but not to LISTENER.
So what you can do is REMOVE the listener and ADD the same listener again in the same EnvoyFilter with the original filter_chain patched.

~~~
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
      listener:
        portNumber: 1234
    patch:
      operation: REMOVE
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: "0.0.0.0_1234"
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 1234
        filter_chains:
          - filter_chain_match:
              server_names: ["myserver.mydomain.com"]
            filters:
              - name: "envoy.filters.network.tcp_proxy"
                typedConfig:
...
~~~

**Pull request merged**
