### PR TITLE
Remove a push before ready race condition

### PR DESCRIPTION
**Pull request by sdake**
Fixes: https://github.com/istio/istio/issues/28055

The per-connection ADS mainloop races with XDS discovery. XDS discovery
pushes prior to a receive goroutine starting. This isn't all that problematic,
but the code as is could use a small improvement.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by sdake** [comment]
Please go gentle on my first pilot PR - in what feels like about 2 years 🥇

**Comment by sdake** [comment]
This is indeed a race condition (exposed during ACK PR development). There is another, more difficult [race condition](https://github.com/istio/istio/blob/master/pilot/pkg/xds/ads.go#L260-L263):

I see a complete crater without this PR of the ACK PR. With this PR, this second race condition comes into play:

My (instrumented code) logs:
```
...
020-10-18T16:40:44.935167Z     info    starting Http service at [::]:8080
2020-10-18T16:40:44.935178Z     info    starting webhook service at [::]:8080
2020-10-18T16:40:44.935213Z     info    starting gRPC discovery service at [::]:15010
2020-10-18T16:40:44.937773Z     info    ads     Push debounce stable[1] 112: 100.120737ms since last change, 108.155612ms since last push, full=true
2020-10-18T16:40:44.944376Z     info    ads     XDS: Pushing:2020-10-18T16:40:44Z/0 Services:9 ConnectedEndpoints:0
2020-10-18T16:40:45.857951Z     info    ads     Push debounce stable[2] 2: 100.107594ms since last change, 135.693221ms since last push, full=false
2020-10-18T16:40:45.858049Z     info    ads     XDS: Incremental Pushing:2020-10-18T16:40:44Z/0 ConnectedEndpoints:0
2020-10-18T16:40:46.791716Z     info    ads     ADS: new connection for node:router~172.17.248.1~cluster-local-gateway-78d94954f8-9sls8.istio-system~istio-system.svc.cluster.local-1
2020-10-18T16:40:46.791765Z     info    ads     Should respond
2020-10-18T16:40:46.791772Z     info    ads     semrecv: SIGNAL%!(EXTRA string=type.googleapis.com/envoy.config.cluster.v3.Cluster)
2020-10-18T16:40:46.791777Z     info    ads     semrecv: DONE SIGNALING - UNBLOCKING%!(EXTRA string=type.googleapis.com/envoy.config.cluster.v3.Cluster)
2020-10-18T16:40:46.791781Z     info    ads     semrecv: DONE UNBLOCK%!(EXTRA string=type.googleapis.com/envoy.config.cluster.v3.Cluster)
2020-10-18T16:40:46.791992Z     info    ads     Should respond
2020-10-18T16:40:46.792000Z     info    ads     semrecv: SIGNAL%!(EXTRA string=type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment)
2020-10-18T16:40:46.792005Z     info    ads     semrecv: DONE SIGNALING - UNBLOCKING%!(EXTRA string=type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment)
2020-10-18T16:40:46.792009Z     info    ads     semrecv: DONE UNBLOCK%!(EXTRA string=type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment)
2020-10-18T16:40:46.792258Z     info    ads     Should respond
2020-10-18T16:40:46.792283Z     info    ads     semrecv: SIGNAL%!(EXTRA string=type.googleapis.com/envoy.config.listener.v3.Listener)
2020-10-18T16:40:46.792292Z     info    ads     semrecv: DONE SIGNALING - UNBLOCKING%!(EXTRA string=type.googleapis.com/envoy.config.listener.v3.Listener)
2020-10-18T16:40:46.792299Z     info    ads     semrecv: DONE UNBLOCK%!(EXTRA string=type.googleapis.com/envoy.config.listener.v3.Listener)
2020-10-18T16:40:46.793374Z     info    ads     semsend: BLOCK receive thread%!(EXTRA

```

```
2020-10-18T16:40:46.793374Z     info    ads     semsend: BLOCK receive thread%!(EXTRA string=type.googleapis.com/envoy.config.cluster.v3.Cluster)
2020-10-18T16:40:46.793425Z     info    ads     semsend: BLOCK DONE / UNBLOCK receive thread%!(EXTRA string=type.googleapis.com/envoy.config.cluster.v3.Cluster)
2020-10-18T16:40:46.793653Z     info    ads     semsend: UNBLOCK done%!(EXTRA string=type.googleapis.com/envoy.config.cluster.v3.Cluster)
20
```

essentially
1. Pilot (the server) starts out receiving a response from the client of CDS then EDS,  then LDS.
2. Pilot (the server) sends a push of CDS and deadlocks (in my implementation).

I had been incorrectly assuming that respond comes before push - even though it made little logical sense to me. I think instead, I am running into this race. Without this PR, however, things get really unintelligible.

**Review by howardjohn — COMMENTED** [review]
@sdake I am not sure I understand how this can fix a bug, or what the bug is. Is this change relevant on the current `master` code, or is the bug only present with your other PR for changed ACK handling? Your issue mentioned strange logging and ack handling but I am not sure what this means in practice. I am not seeing the significant of the `receive` goroutine starting, given we signal it has started before we do anything at all within `receive`.  Please let me know what I am missing - thanks!

**Comment by sdake** [comment]
@howardjohn I thought this was right, but now I'm not certain. This PR doesn't break anything, but it may not be necessary. I have been working for a few days on the per-channel per resource-`type` model and _was_ very close. Unfortunately, it appears I suffered some sort of environmental malfunction of my virtual network. Diagnostics didn't detect any problems, but a reboot of my 15 virtual machines has got master working again (it was broken - for the last four days........)

I'll let you know if this PR makes sense. I mostly like to run these smaller PRs through CI - as there are tons of tests that run much faster than I can run them individually to identify problem spots.

The reqChannel is created prior to the goroutine and passed into the goroutine, so receive should be fine. More problematic is 

It may be that this PR just changed the timing a bit to make things look a little more understandable for me.

A more pressing problem appears to be con.pushChannel, which can run prior to `receive`.

I have finally figured out the NACK/ACK behavior. ShouldRespond NACKS in the continue loop, and ACKS when the `!shouldRespond()` conditional is not executed. 

Can you confirm the following (after I re-read the XDS spec, I believe the following are true):
- The client is Envoy, the Server is Istio in the XDS specification (this seems fairly definitive [https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#client-behavior](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#client-behavior).
- Your desire for per-connection, per `resource` semaphores are more accurately stated as per-connection, per `resourceType` semaphores.
- The current approach I am using is communicating via channels between `send` and `receive` and creating a channel per resource `type` as these are both goroutines and can be GCed without deadlock, which we want to avoid.

I have become much more advanced with my understanding of Pilot. If I could actually get 24 hours of rest, my brain would settle on a solution :)

Thank you so much John,
-steve

**Comment by hzxuzhonghu** [comment]
Just from the implement view, it is not right. Aa you can see that only when `receive` routine started the connection is initiated and added to connection pool `adsClients`. That is to say before pilot receives the first cds request, no push can happen.

**Comment by sdake** [comment]
Right, thanks. The stack trace looks like receive() then initConnection()
then addCon().

Thanks for the extra information related to first cds request as well. I
now understand that the first cds request is a receive from `Envoy`. I
think this part of the spec applies:

```
Each xDS stream begins with a DiscoveryRequest
<https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/discovery.proto#envoy-api-msg-discoveryrequest>
from
the client, which specifies the list of resources to subscribe to, the type
URL corresponding to the subscribed resources, the node identifier, and an
optional resource type instance version indicating the most recent version
of the resource type that the client has already seen (see ACK/NACK and
resource type instance version
<https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#xds-ack-nack>
for
details).
```

Thanks again,
Cheers,
-steve

**Pull request closed without merging**
