### PR TITLE
use common var for ambient namespace label

### PR DESCRIPTION
**Pull request by GregHanson**
**Please provide a description of this PR:**

add constant for `istio.io/dataplane-mode` namespace label

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ X ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by GregHanson** [comment]
@howardjohn for the lint failure, those imports in go.mod and .sum haven't changed recently - assuming there was an update to the linter tools/image?

**Comment by howardjohn** [comment]
https://github.com/istio/tools/pull/2337#issuecomment-1403895757

**Pull request merged**
