### PR TITLE
[Kiali] [release-1.1] use the citadel certificate given to kiali so it can be deployed behind https

### PR DESCRIPTION
**Pull request by jmazzitelli**
This supercedes https://github.com/istio/istio/pull/10305 as this will merge into release-1.1 branch (master is currently frozen).

@sdake @gbaufake

### CODE REVIEW

**Comment by jmazzitelli** [comment]
related to: https://github.com/istio/istio/issues/10317 (Most/all addons do not implement https)

**Comment by jmazzitelli** [comment]
FWIW: the annotation `nginx.ingress.kubernetes.io/secure-backends: "true"` was required in order to access Kiali over https via browser through a Kubernetes Ingress.

Need to test with the istio gateway and make sure the gw/vs that ships with istio is configured properly. But by testing with a k8s ingress, I can confirm https access to kiali works.

**Comment by jmazzitelli** [comment]
I would prefer https://github.com/istio/istio/pull/10349 get merged first. I can then rebase and clean this up.

Note that this does not work with istio gateways yet, only get https through k8s ingress. I may write a separate PR for gateway support rather than piggy back on this one.

**Comment by jmazzitelli** [comment]
/hold

put this on hold, not sure if this is how we want it to work yet

**Comment by jmazzitelli** [comment]
we may not need this now if https://github.com/istio/istio/pull/10363 is good enough

**Comment by sdake** [comment]
@jmazzitelli can you file an issue for release 1.2 p1 to add TLS in the internal network of Istio addons?  I think edge is good enough for 1.1 since it defaults to off and is configurable.  After filing the issue to track the work, please close this PR.

Thanks for the great work in this area - much appreciated!

Cheers
-steve

**Comment by jmazzitelli** [comment]
> @jmazzitelli can you file an issue for release 1.2 p1 to add TLS in the internal network of Istio addons?

@sdak https://github.com/istio/istio/issues/10587

Closing this issue as per previous discussion.

**Pull request closed without merging**
