### PR TITLE
Adding aliases for OWNERS

### PR DESCRIPTION
**Pull request by utka**
I added OWNERS_ALIASES file with reviewers/approvers for prow. 
In the future we should have aliases for all the groups.
I specified label to add for any change happening in prow folder
I also specified that only people in prow/OWNERS should be reviewers with an option no_parent_owners: true

### CODE REVIEW

**Comment by geeknoid** [comment]
I wasn't aware of all these OWNERS features. DO you have a doc pointer?

"sig" is a Kubernetes thing, we don't use that term in Istioland. We have working groups instead.

**Comment by geeknoid** [comment]
Found the docs: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners-spec

I suggest that OWNERS_ALIASES contain workgroup-related stuff, not directory-related stuff. We don't want sig-prow, that's not a workgroup. Instead, I suggest two entries per workgroup:

  wg-networking
  wg-networking-leads

Then wg-networking can be used for reviewers: and wg-networking-leads can be used for approvers

**Comment by louiscryan** [comment]
@utka I think Martin's comments are on point but don't want to block

**Comment by utka** [comment]
Updated with wg-testing/wg-testing-leads

**Comment by geeknoid** [comment]
This is great. I'll take the AI to expand this to include all working groups and apply it through the source base.

**Pull request merged**
