### PR TITLE
Avoid panic when deleted object is cache.DeletionFinalStateUnknown

### PR DESCRIPTION
**Pull request by ymesika**
`release-0.8` target per request by @costinm in #5951.

### CODE REVIEW

**Comment by ymesika** [comment]
To be honest I don't know what's wrong with CircleCI builds on this and #5951.
Comparing the environment variables again other PR that passes shows that mine misses:
`CIRCLE_PULL_REQUEST`, `CIRCLE_PULL_REQUESTS`, `CI_PULL_REQUEST` and `CI_PULL_REQUESTS`.
Might be the reason for the overall errors while uploading results to GCS.

**Comment by rshriram** [comment]
We need this in master as well.

**Comment by ymesika** [comment]
@rshriram #6007

**Comment by rshriram** [comment]
FYI @hklai merging into 0.8 branch? or do we cherry pick from master ?

**Comment by hklai** [comment]
@rshriram We have not yet decided to cut 0.8.1, and we are still collecting data (https://github.com/istio/istio/issues/5982).

Please merge all fixes to master, and when 0.8.1. happens, they will have to be cherrypicedk to release-0.8.

**Comment by ymesika** [comment]
@hklai So I guess this one should be closed if the fix has already been merged to master?

**Pull request closed without merging**
