### PR TITLE
Cleaning up some duplicate code in the list checker.

### PR DESCRIPTION
**Pull request by smawson**
Also added tests for some regex validation that we didn't test, and added some pre-validation for regex overrides.

### CODE REVIEW

**Comment by ldemailly** [comment]
There is some overlap between this PR and #4056

**Comment by geeknoid** [comment]
I also have #4056 which bumps code coverage for the list adapter and add proper validation for regex stuff... Sorry for the duplicated work...

**Comment by smawson** [comment]
OK I'll wait till yours goes in and merge, mine is mostly code refactoring, just increased coverage while I was there for fun :)

**Comment by smawson** [comment]
PTAL, now this is just pure refactoring to remove some duplication lint warnings and clean up the code a bit.

**Pull request merged**
