### PR TITLE
Convert istio-on-istio to v2 bootstrap

### PR DESCRIPTION
**Pull request by costinm**
First step is pilot, will add mixer after this works. 
It seems there are some problems with the cert...

### CODE REVIEW

**Comment by costinm** [comment]
+Piotr 

Can you take a look at the pilot auth configs - I get:

s_client -connect localhost:15003
CONNECTED(00000003)
139909474432664:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1520977598
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

So TLS works, but no certificates sent - I checked that the certs are there.

Tried all combinations ( one port has sni '*', other has empty list and I tried with no sni match as well ).

**Comment by PiotrSikora** [comment]
1. Cluster `in.15010` in `envoy_pilot_auth.json` is still in v1 format, so the config doesn't work.
2. Port `15003` doesn't use TLS in `envoy_pilot.json` and `enovy_pilot_auth.json` doesn't work, so you're presumably using the first one, and you're trying to connect with TLS client to a plaintext TCP port, which matches the error you're seeing, which actually says that TLS handshake failed.

**Comment by PiotrSikora** [comment]
FWIW, this uncovered https://github.com/envoyproxy/envoy/issues/2800, but that's not an issue that you're hitting.

**Comment by costinm** [comment]
Plan is for pilot to handle mtls directly.

**Pull request closed without merging**
