### PR TITLE
fix incorrect code style

### PR DESCRIPTION
**Pull request by UramnOIL**
**Please provide a description of this PR:**

Fixed incorrect code style.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ericvn** [comment]
/retest

@UramnOIL You still need to satisfy the CLA requirements.

**Review by ericvn — APPROVED** [review]

**Comment by UramnOIL** [comment]
@ericvn I've agreed the CLA, is there anything I still have to do?

**Comment by ericvn** [comment]
@UramnOIL No. The test is now showing as passed.

**Pull request merged**
