### PR TITLE
add e2e for MetricDefinition (#42563)

### PR DESCRIPTION
**Pull request by kyessenov**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Comment by kyessenov** [comment]
/retest 

Crash present: 
```
2023-01-20T19:52:18.253932Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:104	Caught Segmentation fault, suspect faulting address 0x0	thread=216
2023-01-20T19:52:18.276450Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:91	Backtrace (use tools/stack_decode.py to get line numbers):	thread=216
2023-01-20T19:52:18.276474Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:92	Envoy version: 7424dcd0b7931cfc550776ed2824a50e61fba50c/1.26.0-dev/Clean/RELEASE/BoringSSL	thread=216
2023-01-20T19:52:18.277120Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:98	#0: [0x7fbdb3488520]	thread=216
2023-01-20T19:52:19.554674Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:96	#1: event_base_loop [0x564ab8e8da01]	thread=216
2023-01-20T19:52:21.021456Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:96	#2: Envoy::Server::InstanceImpl::run() [0x564ab836b91b]	thread=216
2023-01-20T19:52:23.988662Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:96	#3: Envoy::MainCommonBase::run() [0x564ab6d246f4]	thread=216
2023-01-20T19:52:25.136870Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:96	#4: Envoy::MainCommon::main() [0x564ab6d24f76]	thread=216
2023-01-20T19:52:26.363048Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:96	#5: main [0x564ab6d2252c]	thread=216
2023-01-20T19:52:26.363434Z	critical	envoy backtrace external/envoy/source/server/backtrace.h:98	#6: [0x7fbdb346fd90]	thread=216
```

But this is not related to metric definition. Will need further investigation for security-multicluster-istio @lei-tang

**Comment by howardjohn** [comment]
That is the one I have been trying to debug but have been blocked due to debug builds failing for other reasons

**Comment by kyessenov** [comment]
@howardjohn https://github.com/istio/istio/pull/41470 was very effective in triage of the stats crash. Authz tests are superflakey with Asan because of hard coded time outs. We should adjust timeouts, bump memory, and will get proper trace out.

**Comment by kyessenov** [comment]
Shouldn't we block the release until we know why Envoy crashes sometimes? Once this code makes it production, it'll be near impossible to diagnose intermittent crashes without managed proxies.

**Pull request merged**
