### PR TITLE
Add missing imagePullSecrets to helm charts

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**

### CODE REVIEW

**Comment by kramerul** [comment]
I confirm my consent

**Comment by c0d1ngm0nk3y** [comment]
@hklai Could you check the CLA label? The bot seems not to like pair programming :(

**Comment by morvencao** [comment]
Can you add `imagePullSecrets` to serviceaccount, like: https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/certmanager/templates/serviceaccount.yaml#L3-L8 ?

**Comment by c0d1ngm0nk3y** [comment]
@morvencao So basically what you did in #11666?

**Comment by morvencao** [comment]
@c0d1ngm0nk3y Yep!

**Comment by c0d1ngm0nk3y** [comment]
Is anything missing?

**Comment by c0d1ngm0nk3y** [comment]
Who can merge?

**Comment by c0d1ngm0nk3y** [comment]
What means `Waiting on: prow/istio-presubmit.sh`? What is missing for this little PR?

**Comment by c0d1ngm0nk3y** [comment]
@ymesika Do you know why there are no test results? (waiting for `prow/istio-presubmit.sh`)

**Comment by ymesika** [comment]
There were issues with the tests on master yesterday.
You may want to push something (merge master) to re-trigger them.

**Pull request merged**
