### PR TITLE
Update proxy sha with stripped binary

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by costinm** [comment]
Thanks !!
/lgtm
/approve

**Comment by ldemailly** [comment]
This is going to make it hard (impossible?) to get profile/flamegraph info ? Premature optimization?

**Comment by hklai** [comment]
Manually merging since circleci tests are not running (and the required prow tests look fine).

**Comment by kyessenov** [comment]
Can we do it once again? There is another PR merged that fixes a blocking
issue.

**Comment by hklai** [comment]
I suppose the bot is going to update it in the next schedule.

/cc @rkpagadala

**Pull request merged**
