### PR TITLE
Fix multiple control plane pruning

### PR DESCRIPTION
**Pull request by howardjohn**
Alternative to https://github.com/istio/istio/pull/22361 and
https://github.com/istio/istio/pull/22337

Currently there are a few issues with multi control plane pruning

If I install revision="", revision="foo", then revision="" again, the
last step will delete "foo".

EnvoyFilter is currently broken, as it gets the istio.io/rev label,
making it only apply to a single revision. Whichever one is applied last
"wins". If we made it so that it had a suffix on the name, this still
would not work, as we may end up with a global revision and then we end
up with 2x EnvoyFilters.

The goal of this PR is to make the minimal amount of changes to the "non multiple control plane" support, so people who don't care can just go about doing things the old way and things just work. If no revision is specified, everything will use the same names as previously. However, internally, this will be treated as a special `default` revision. By treating it as a revision internally, we avoid all the issues of having a global revision that messes with things

### CODE REVIEW

**Comment by sdake** [comment]
@howardjohn EnvoyFilter is (or was) used by multicluster. EF may be used by telemetry as well. Might sync with @ayj. I will provide a more thorough review this afternoon.

Cheers
-steve

**Comment by howardjohn** [comment]
The MC EnvoyFilter is in ingress so its not relevant here, this is mostly about the telemetry v2 stuff

**Comment by linsun** [comment]
@howardjohn thank you for the PR, Pls let me know if I'm interpreting this correctly:

1. when no revision is specified, default revision will be used.
2. if a cluster has istio with default revision, and user is trying to install a newer version of istio also with default revision, it will do an in place upgrade of istio to the newer version.  In place upgrade may have slight control plane downtime but should be no data plane downtime.

for scenario 2, there is no istiod endpoint change because it is in place upgrade.

**Comment by howardjohn** [comment]
@linsun yes, if the user never sets the revision they should see no change. Upgrade will be done in place, and all resources will rename the same as they are today (eg `istiod`, not `istiod-default`).

**Comment by linsun** [comment]
@howardjohn thanks, i think that works and maintains a nice backwards compatible for things.  I appreciate you taking on the challenge to solve it with the default revision!

**Review by sdake — APPROVED** [review]
This PR seems related to https://github.com/istio/istio/issues/22095.

This PR LGTM. Thanks, @howardjohn for your patience with my nonstop questions on this topic 👍 

Cheers
-steve

**Pull request merged**
