### PR TITLE
Update istio.RELEASE to 0.2.1

### PR DESCRIPTION
**Pull request by rvkubiak**
```release-note
None
```

### CODE REVIEW

**Comment by rshriram** [comment]
And this is a regression FYI. We do not have health checks (more like we have disabled health checks).

**Comment by ldemailly** [comment]
it's been discussed for weeks how we'd make weekly builds (not releases) as long as the tests passes.

this being said, collecting release notes would be useful, and emailing people a reminder about the plans

**Comment by sebastienvas** [comment]
Sorry @rshriram. I did not get around to update to use docker.io. This release was an experiment to get our @rvkubiak familiar with process and also to understand what we can improve short term for 0.2 and also for 0.3. We did not update the downloadIstio.sh script because we don't expect people to use it.

**Comment by thisisnotapril** [comment]
Can we make it super clear that this is not a release for public consumption?

**Comment by ldemailly** [comment]
@thisisnotapril do you think this isn't clear enough : 
screen shot 2017-08-07 at 8 03 34 pm
can you suggest a different text ?

**Comment by ldemailly** [comment]
ps: we could delete the artifacts but I think that would be a mistake - I think it's important for the community to see we are going to make (more) frequent builds and not all of them are "releases" that are usable (and the only way we can mark the difference in github is that red "pre-release" vs the green "Latest Release" - and the text)

as we discussed weeks ago, the real 0.2 release may well be the 10th such release (ie 0.2.10) but should be clearly identified on github, and will come with an official announcements on the mailing lists etc

**Comment by thisisnotapril** [comment]
Text is good, but we have had several tweets, etc. from people confused. I suspect it has to do with how Github notifications show; email alerts don't show the pre-release flag. Additionally, we should document the release process for the community so it's clear how the tests work, what we mean when we say pre-release, etc.

**Comment by ldemailly** [comment]
@thisisnotapril yes it's unfortunate github spams on pre-releases. I'm happy to sit with you to help write or review something explaining our process (maybe a summary of what was sent on istio-dev@) (and I'm sure Seb would too)


and if anyone reads this in the meantime, if it's not sent to istio-announce@, posted by the @istiomesh official twitter account, it's not a release ready to be consumed :-)

**Pull request merged**
