### PR TITLE
fix deprecated xds config struct

### PR DESCRIPTION
**Pull request by monsteredc**
This PR is to fix the issue #33980. The old struct is deprecated, and i just revise it to the new one.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by shamsher31 — COMMENTED** [review]
@monsteredc Can you please add or update test accordingly?

**Comment by monsteredc** [comment]
@shamsher31 PTAL.

**Review by hzxuzhonghu — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
Nice!

My only concern is this seems like its changing `istioctl` and `istiod` code together. does this mean a mismatch of versions between the two would result in this not working?

We may need to make istioctl support both the old and new version?

**Comment by monsteredc** [comment]
@howardjohn Done. Good point, thanks!

**Comment by howardjohn** [comment]
Thanks! I am not an expert on this code so defering to @therealmitchconnors

**Review by therealmitchconnors — APPROVED** [review]

**Pull request merged**
