### PR TITLE
update go mod vendor for istio.io/api

### PR DESCRIPTION
**Pull request by ckcd**
update istio.io/api to latest which is changed to:

```
replace github.com/gogo/protobuf => github.com/istio/gogo-protobuf v1.2.2-0.20190726125433-4c9abdb3090c

require (
	github.com/gogo/googleapis v1.2.0
	github.com/gogo/protobuf v1.2.1
	google.golang.org/grpc v1.21.0
)
```
as shown in https://github.com/istio/api/blob/master/go.mod

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rshriram** [comment]
Please close this PR. #15928 takes care of teh issue.

**Comment by geeknoid** [comment]
This is now redundant, vendor just has been updated. So closing.

**Comment by sdake** [comment]
@ckcd thank you for the work.  There were a bunch of prerequisite PRs needed before istio/istio could be updated - that has been sorted out (there are links in the various other PRs related to unblocking).

Thanks again for the contribution.

Cheers
-steve

**Pull request closed without merging**
