### PR TITLE
Fix base templates for shared control plane when remotePilotAddress is a hostname

### PR DESCRIPTION
**Pull request by ecrousseau**
Extends the change in https://github.com/istio/istio/pull/24219 by @linsun to cover cases where remotePilotAddress is a hostname and Istio is being installed in the "shared control plane" topology.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ecrousseau** [comment]
@googlebot I signed it!

**Review by morvencao — COMMENTED** [review]
/ok-to-test

**Comment by stevenctl** [comment]
This looks great to me. Let me see if I can find a good place to add a test.

**Review by stevenctl — APPROVED** [review]

**Comment by stevenctl** [comment]
I also suspect that we have other places where we assume this is an IP.

**Comment by stevenctl** [comment]
https://github.com/istio/istio/blob/ed6ea08274e8d905127059e4aeeddbd57a2ca03f/operator/cmd/mesh/manifest-generate_test.go

If you can add a test for this change that would be great

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by Gaurang10** [comment]
Can you please reopen this issue? Need this fix to deploy multi remote setup on aws env.

**Pull request closed without merging**
