### PR TITLE
Revert "samples/bookinfo: migrate `apiVersion` of deployments to `apps/v1`"

### PR DESCRIPTION
**Pull request by howardjohn**
Reverts istio/istio#13030

This change was made without owners approval

### CODE REVIEW

**Comment by howardjohn** [comment]
@frankbu if you are fine with the original change I suppose you can give a retroactive approval to avoid just revert-reverting after this

**Comment by frankbu** [comment]
@howardjohn yeah, I'm not sure about all these labels. It sounds like selector matchLabels are required in app/v1 (even though it says it's an optional field in the doc) or the deployment won't know which pods it's managing. I'm also not sure if metadata.labels are really needed, but since we've been adding them in most of the deployments before, we might as well put them everywhere for consistency.

I suppose it is harmless anyway, so maybe we should just leave the merge for now. We can revisit and change it again in the future if we want to. It's just a sample.

I am surprised that @caohe had the authority to approve/merge the PR himself.

**Comment by caohe** [comment]
@frankbu @howardjohn  I am really sorry for adding the approved label manually. Now I know the approved label must be added by the approval of an owner.

**Comment by howardjohn** [comment]
No worries, I actually thought I commented and mentioned it and you added it again after that but I guess I never hit send

**Comment by caohe** [comment]
I found you deleted the label. But I didn't receive the comment. Anyway it's my fault.

**Pull request closed without merging**
