### PR TITLE
Make priorityClass of cni in helm chart config

### PR DESCRIPTION
**Pull request by venkatk-25**
The priorityClassName is hardcoded in helm charts of cni. We need it to be configurable to deploy in our custom enviroment.

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
Could you explain a bit why `system-node-critical` does not work within your environment?

**Comment by venkatk-25** [comment]
> Could you explain a bit why `system-node-critical` does not work within your environment?

We have calico as cni daemonset in on premise cluster and want to run istio-cni as chained cni to that. 
We want to make sure calico-cni gets scheduled first and istio-cni after that on addition of new nodes to cluster.
So we are planning to use `system-cluster-critical` to ensure slightly lesser priority

**Comment by bianpengyuan** [comment]
@venkatk-25 istio-cni should block and wait for main CNI plugin to be ready. Is that not the case? Did you observe some problem? If yes we need to fix that instead of relying on priority class.

**Comment by venkatk-25** [comment]
> @venkatk-25 istio-cni should block and wait for main CNI plugin to be ready. Is that not the case? Did you observe some problem? If yes we need to fix that instead of relying on priority class.

I didn't know it will wait, our internal team has raised it as a race condition for adoption. Can you point to related docs/code

**Comment by bianpengyuan** [comment]
@venkatk-25 Wait logic is around https://github.com/istio/istio/blob/8d40d0fd16a9c8401f607eab61d6116a76c43e31/cni/pkg/install/cniconfig.go#L195.

**Comment by venkatk-25** [comment]
> @venkatk-25 Wait logic is around
> 
> https://github.com/istio/istio/blob/8d40d0fd16a9c8401f607eab61d6116a76c43e31/cni/pkg/install/cniconfig.go#L195
> 
> .

@bianpengyuan thank you

**Pull request closed without merging**
