### PR TITLE
improve helloworld/dockerfile

### PR DESCRIPTION
**Pull request by my-git9**
**Please provide a description of this PR:**
improve sample/helloworld/dockerfile

### CODE REVIEW

**Comment by litong01** [comment]
@my-git9 not really sure this is an improvement or really needed. can you elaborate?

**Comment by my-git9** [comment]
> @my-git9 not really sure this is an improvement or really needed. can you elaborate?

1、If it is not built in stages, WORKDIRE only needs to be declared once. 
2、After specifying WORKDIR, the dockerfile specifies that the current path is the directory of WORKDIR

**Comment by litong01** [comment]
@my-git9 What I think will be nice to improve this is to remove the need to have multiple version of the helloworld images. Since the python app takes a parameter already to show the version. For example, I normally just use this to create different version of the pod.

```
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        env:
        - name: FLASK_RUN_PORT
          value: "5000"
        - name: FLASK_RUN_HOST
          value: "::"
        - name: FLASK_ENV
          value: "development"
        - name: SERVICE_VERSION
          value: "v1"
        - name: FLASK_APP
          value: "/opt/microservices/app.py"
        command: ["flask", "run"]
```
It will be very nice to actually improve the docker file to run flask so that helloworld app does not need multiple container images in the container repo. and yet, one can create as many versions of helloworld as they wish for various tests.

**Comment by my-git9** [comment]
> @my-git9 What I think will be nice to improve this is to remove the need to have multiple version of the helloworld images. Since the python app takes a parameter already to show the version. For example, I normally just use this to create different version of the pod.
> 
> ```
>       containers:
>       - name: helloworld
>         image: docker.io/istio/examples-helloworld-v1
>         resources:
>           requests:
>             cpu: "100m"
>         env:
>         - name: FLASK_RUN_PORT
>           value: "5000"
>         - name: FLASK_RUN_HOST
>           value: "::"
>         - name: FLASK_ENV
>           value: "development"
>         - name: SERVICE_VERSION
>           value: "v1"
>         - name: FLASK_APP
>           value: "/opt/microservices/app.py"
>         command: ["flask", "run"]
> ```
> 
> It will be very nice to actually improve the docker file to run flask so that helloworld app does not need multiple container images in the container repo. and yet, one can create as many versions of helloworld as they wish for various tests.

Great idea, I will try it

**Comment by frankbu** [comment]
> It will be very nice to actually improve the docker file to run flask so that helloworld app does not need multiple container images in the container repo. and yet, one can create as many versions of helloworld as they wish for various tests.

That's already how it works. You can create as many versions as you like, as described in the README:
```
./gen-helloworld.sh --version customversion | \
    kubectl apply -f -
```
They all use the same image (helloworld-v1).

We need the helloworld-v2 image in the repo as well, just because the canary doc refers to it.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
