### PR TITLE
Fix for Istio security 2020 004

### PR DESCRIPTION
**Pull request by brian-avery**
This adds the fix for CVE 2020 004 to Master.

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
/lgtm

**Review by jmazzitelli — APPROVED** [review]
/lgtm

**Review by elfinhe — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by jmazzitelli** [comment]
@googlebot I consent

**Pull request merged**
