### PR TITLE
build the dev/perf test setup with optimization

### PR DESCRIPTION
**Pull request by ldemailly**
adding -c opt more than doubles throughput

### CODE REVIEW

**Comment by andraxylia** [comment]
Can you elaborate on what throughput is doubled?
Does this remove the debug symbols?

**Comment by ldemailly** [comment]
I emailed the perf numbers, they are halved without this

I don't think opt mode strips debug but I can check. I also haven't checked how we build on jenkins, this is the script I use to build locally on Raw VM

**Comment by andraxylia** [comment]
So this optimizes latency.
Unless we are sure we can still debug this image, I do not see the benefit of enabling optimization at this point and merging this change.

**Comment by ldemailly** [comment]
@andraxylia I checked the symbols are still there

and again, these scripts are what I use for perf testing so even it it didn't it would still be useful

**Pull request merged**
