### PR TITLE
change the default resyncPeriod for galley

### PR DESCRIPTION
**Pull request by irisdingbj**
suppose this will release api server's pressure.

### CODE REVIEW

**Comment by ozevren** [comment]
I thought resyncPeriod = 0 implied no resyncs?

**Comment by ozevren** [comment]
https://github.com/kubernetes/client-go/blob/37c3c02ec96533daec0dbda1f39a6b1d68505c79/tools/cache/shared_informer.go#L574

**Comment by irisdingbj** [comment]
@ozevren Looking a little bit in kubernetes part so seems the resyncPeriod make more sense in controllers and for list/watcher we can leave it as 0. In such case, can we remove this parameter in our command options? "rootCmd.PersistentFlags().DurationVar(&flags.resyncPeriod, "resyncPeriod", 1000000000,
		"Resync period for rescanning Kubernetes resources")"?

**Comment by irisdingbj** [comment]
@ozevren Looking a little bit in kubernetes part so seems the resyncPeriod make more sense in controllers and for list/watcher we can leave it as 0. In such case, can we remove this parameter in our command options? "rootCmd.PersistentFlags().DurationVar(&flags.resyncPeriod, "resyncPeriod", 0,
"Resync period for rescanning Kubernetes resources")"?

**Comment by ozevren** [comment]
I think we should leave this as is. Resync period is useful in cases where a controller can have an internal bug that causes events to be missed. With a resync, the controller can reconcile.

This should be set to 0 (as we don't expect bugs, and we don't want to put load on API Server), but in case we do have bugs, it is an important ops feature that would allow them to remedy the situation.

**Pull request closed without merging**
