### PR TITLE
update: bug and feature template

### PR DESCRIPTION
**Pull request by Xunzhuo**
**Please provide a description of this PR:**

update: bug and feature template

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [x] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by Xunzhuo** [comment]
Hi @linsun , could u take a look at this PR?

**Comment by Xunzhuo** [comment]
cc @howardjohn cc @nmittler

**Comment by Xunzhuo** [comment]
Hi, @linsun @costinm @howardjohn @nmittler A ping on this, thanks!

**Comment by howardjohn** [comment]
Can you give more context on why we want to change it?

**Comment by Xunzhuo** [comment]
@howardjohn As you can see the rich diff: 
image
according to markdown syntax , the selected checkbox should be like `- [ ]` not `[ ]`,

**Comment by Xunzhuo** [comment]
If someone creates a issue , they should just click the checkbox for selecting labels,  not put a `x` into it.

**Comment by howardjohn** [comment]
That turns it into a "task list" and will report things like "2/12" done on the github UI. This is misleading IMO.

**Comment by Xunzhuo** [comment]
But it seems like that  the pull request template uses checklist as well

**Comment by howardjohn** [comment]
IMO pull request shouldn't use it either

**Comment by Xunzhuo** [comment]
That is all right, this is just my suggestion, if it is not OK, I will just close the PR~

**Pull request closed without merging**
