### PR TITLE
remove old mcp stack

### PR DESCRIPTION
**Pull request by ayj**
The [revised MCP API](https://github.com/istio/api/tree/release-1.1/mcp) replaced the original MCP API in 1.1. The older implementation was retained during the transition. 1.1 ships with the new API enabled and the older version should not be used. This PR removes the old implementation to avoid confusion with ongoing enhancements to MCP.

### CODE REVIEW

**Comment by ayj** [comment]
@ozevren - thoughts on cherry-picking this change into 1.1 as well?

**Comment by ozevren** [comment]
/lgtm
modulo the lint/codecov failures.

**Comment by ozevren** [comment]
@ayj, please rebase & update.

**Comment by ayj** [comment]
@rshriram - can you /lgtm for the pilot change

@geeknoid - can you /lgtm for the updated codecov.threshold change.

**Comment by ozevren** [comment]
@geeknoid can you lgtm for the codecov changes?

**Comment by ozevren** [comment]
@geeknoid any change we can get an lgtm?

**Comment by ozevren** [comment]
@ayj can you fix the conflicts?

**Comment by ayj** [comment]
@geeknoid, this is ready to merge

**Comment by ozevren** [comment]
@ayj can you rebase again?
@geeknoid Once rebased, can you approve?

Thanks

**Comment by ayj** [comment]
@geeknoid, this is ready for final approval.

**Comment by geeknoid** [comment]
/lgtm
/approve

But it needs to be rebased, so I'll have to approve again....

**Pull request merged**
