### PR TITLE
fix(mixer): remove signalfx adapter

### PR DESCRIPTION
**Pull request by douglas-reid**
Fixes https://github.com/istio/istio/issues/18434.

### CODE REVIEW

**Comment by geeknoid** [comment]
Did you do "BUILD_WITH_CONTAINER=1 make gen" from the top? I would expect some changes in the licenses directory as a result...

**Comment by douglas-reid** [comment]
@geeknoid That command fails for me:

```
Traceback (most recent call last):
  File "/usr/local/bin/autopep8", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
common/Makefile.common.mk:73: recipe for target 'format-python' failed
make: *** [format-python] Error 123
make: *** [Makefile:104: gen] Error 2
```

But, it did seem to delete license files.

Updated.

**Pull request merged**
