### PR TITLE
Setup default passthrough TCP route in proxy

### PR DESCRIPTION
**Pull request by rshriram**
This will allow traffic to unknown egress destinations to pass through as is, for any port that does not match the listeners.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by rshriram** [comment]
should fix #3876

**Comment by mandarjog** [comment]
We should model this in Istio, this is hidden behaviour. 

I want to be able to say,  
Ports 50001, 50002 should be pass thru.
All other ports should log and terminate connection.

**Comment by rshriram** [comment]
we can do that with envoy v2 apis.. once filter chain match is implemented.

**Comment by kyessenov** [comment]
ref https://github.com/envoyproxy/data-plane-api/issues/208

**Comment by kyessenov** [comment]
Please make this optional. We may want to fail-close and not let arbitrary traffic through. Some of the authz assumption are based on the proxy applying the right filters. Also, please don't use the bootstrap. That will freeze the listener in place, preventing any future upgrades from the control plane.

**Comment by costinm** [comment]
Well - the bootstrap will not be 'frozen in place' - we do plan to allow
more configuration to it, in particular
for fail-safe. But it may be ok for now to keep it in LDS (as long as it's
LDSv2, as we agreed no more v1 features :-)

The CDS part is pretty static - that's the one I was suggesting for
bootstrap.

**Comment by kyessenov** [comment]
Please, we don't need more YAML templates. Bootstrap should be generated by
pilot to the extent needed to allow live deployment. This pre-generated
bootstrap should be served dynamically to avoid freezing it, using
pilot-agent or something else.

**Comment by costinm** [comment]
That is one option. However we are using templates more - for auto-inject,
helm, and we'll
likely continue to use them for bootstrap.

**Comment by loewenstein** [comment]
> But it may be ok for now to keep it in LDS (as long as it's LDSv2, as we agreed no more v1 features :-)

@costinm Didn't you raise https://github.com/istio/istio/pull/4360#issuecomment-374352571 above the bar for adding something to v1?

**Pull request closed without merging**
