### PR TITLE
[Test Framework] Always apply config for Native Echo

### PR DESCRIPTION
**Pull request by nmittler**
Currently the native echo component only applies a configuration to Galley if it has a sidecar. This means that other echo instances will never receive an outbound configuration for it.

### CODE REVIEW

**Comment by nmittler** [comment]
@ozevren PTAL ... I fixed an issue in the Galley file source related to dropping Watcher signals.

**Comment by ozevren** [comment]
Do you have an exact understanding of the problem? The ordering of things should not cause Watcher signal dropping. Multiple signals will get dropped (or rather coalesced), but events should not be getting missed.

The sequences for both processes should be:
 (file change) => (trigger send)
 (trigger read) => (read file)

If the read does not drain a previous send (because of processing of an older event), the channel should still hold a notification that holds a trigger. As long as trigger is put to channel after the file change, there shouldn't be a gap in processing.

**Comment by nmittler** [comment]
@ozevren 

> Do you have an exact understanding of the problem? The ordering of things should not cause Watcher signal dropping. Multiple signals will get dropped (or rather coalesced), but events should not be getting missed.

Yes, I think so ... I was debugging a bit this morning.  I was definitely seeing that the watcher was dropping events.

The file write (via yaml.Cache.Apply) is generally fine since they will occur synchronously (cache.Apply locks):
a->writeFile
b->writeFile
c->writeFile

However, the signals are sent after the write without any lock:

a->notify(SIGUSR1)
b->notify(SIGUSR1)
c->notify(SIGURS1)

So we could have scenarios such as this:

a->WriteFile(complete)
b->WriteFile(partial ... Galley read will fail and drop the resource)
a->Signal

Leading to only a being read and no event for b will ever occur.

**Comment by nmittler** [comment]
@ozevren ok I think I understand the issue better now.  The problem was due to the fact that the file source was using a zero-length channel to read signals. This means that when the watcher goes to put a signal on the channel, there has to already be a consumer ready to receive it ... otherwise it's dropped on the floor.

I believe the behavior we wanted was to have a channel of size 1.  This way the watcher will buffer one signal at a time to the file source ... additional signals are lost, which is fine. But this ensures that the file source will not lose signals.

**Pull request merged**
