### PR TITLE
remove limits.cpu from values.yaml

### PR DESCRIPTION
**Pull request by shippo-eric**
**Please provide a description of this PR:**

When Istio chart is imported as dependency chart, it is unable to unset `limits.cpu`. The change is really about supporting wider adoption. Keeping original values commented out for referencing and can be restored if desired.

If the change is accepted, feel free to let me know necessary change to increment chart version.

### CODE REVIEW

**Review by hanxiaop — CHANGES_REQUESTED** [review]
I think this may affect existing users' clusters with unintended resource allocation. The general best practice should be set the limit based on scales.

**Comment by shippo-eric** [comment]
@hanxiaop thanks for the comment.  

It is my belief that setting cpu limits in Kubernetes an anti-pattern.  I am sure there are situations where cpu limit is desired.  But it is also a wide known issue that cpu limit triggers unwanted throttling and leads to artificial higher latency.  The purpose of the PR is simply making that setting optional when importing Istio helm chart as dependency chart.

Here are a few blogs for reference:
- https://home.robusta.dev/blog/stop-using-cpu-limits
- https://maxanuj.medium.com/cpu-limits-cpu-request-and-aggressive-throttling-in-kubernetes-d0d74e4d64ff
- https://erickhun.com/posts/kubernetes-faster-services-no-cpu-limits/
- https://www.numeratorengineering.com/requests-are-all-you-need-cpu-limits-and-throttling-in-kubernetes/

**Comment by kirecek** [comment]
You should be able to unset it by zero value:

```yaml
istiod:
  global:
    proxy:
      resources:
        limits:
          cpu: "0"
        requests:
          cpu: "0"

  pilot:
    resources:
      limits:
        cpu: "0"
      requests:
        cpu: "0"
```

For Chart defined as:

```
dependencies:
- name: istiod
  version: "1.20.0"
  repository: "https://istio-release.storage.googleapis.com/charts"
```

**Comment by shippo-eric** [comment]
@kirecek Thanks for the suggestion.  Your approach that requires not setting both `cpu.request` and `cpu.limits` is a nice work around.  Since we don't normally autoscale our pods based on Istio-proxy sidecar container, I agree that this is a good compromise. On the other hand, this workaround also removes the ability to autoscale ingressgateway, something that is critical to production operations.

I have updated the PR to only comment out `gateway` cpu.limits, and restored Istio-proxy sidecar original cpu.limits. Thanks.

**Comment by shippo-eric** [comment]
Hi @hanxiaop Do you have other concerns with the PR? Or is there something else I can help with explaining the request?

**Pull request closed without merging**
