### PR TITLE
[release-1.7] Workloadentry add should trigger push to the proxy (#28785)

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fixes: #28819

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Can you provide a release note for this?

**Comment by jwendell** [comment]
@hzxuzhonghu ping

**Review by jwendell — APPROVED** [review]

**Review by jwendell — CHANGES_REQUESTED** [review]
release notes missing

**Review by jwendell — APPROVED** [review]
@hzxuzhonghu I'm approving it so that this gets in 1.7.5, but we still need an entry for this in the release note. Please write here and we can use it properly. What issue does this fix?

Thanks.

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/28743

It solves vm application missing listeners when the workloadentry registered later than it connects to istiod

**Pull request merged**
