### PR TITLE
Treat JSON values as string for translation

### LINKED ISSUE #24318: meshConfig.accessLogFormat doesn't work
**Bug description**

setting meshConfig.accessLogFormat has no effect. had to fallback to global.proxy.accessLogFormat

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Setting meshConfig.accessLogFormat should change the log format

**Steps to reproduce the bug**

This configuration doesn't change log format:
```
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: "/dev/stdout"
    accessLogFormat: |
      {
        "log_type": "access_log",
        "start_time": "%START_TIME%",
        "route_name": "%ROUTE_NAME%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "duration": "%DURATION%",
        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "user_agent": "%REQ(USER-AGENT)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "authority": "%REQ(:AUTHORITY)%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
      }
```
This works:
```
  meshConfig:
    enablePrometheusMerge: false
    accessLogEncoding: JSON
    accessLogFile: "/dev/stdout"

  values:
    global:
      proxy:
        accessLogFormat: |
          {
            "log_type": "access_log",
            "start_time": "%START_TIME%",
            "route_name": "%ROUTE_NAME%",
            "method": "%REQ(:METHOD)%",
            "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
            "protocol": "%PROTOCOL%",
            "response_code": "%RESPONSE_CODE%",
            "response_flags": "%RESPONSE_FLAGS%",
            "bytes_received": "%BYTES_RECEIVED%",
            "bytes_sent": "%BYTES_SENT%",
            "duration": "%DURATION%",
            "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
            "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
            "user_agent": "%REQ(USER-AGENT)%",
            "request_id": "%REQ(X-REQUEST-ID)%",
            "authority": "%REQ(:AUTHORITY)%",
            "upstream_host": "%UPSTREAM_HOST%",
            "upstream_cluster": "%UPSTREAM_CLUSTER%",
            "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
            "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
            "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
            "requested_server_name": "%REQUESTED_SERVER_NAME%",
            "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
            "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
          }
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (9 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Not using helm

**How was Istio installed?**
I've tried this on three different clusters.
Two were installed with istioctl and the third with istio-operator controller

**Environment where bug was observed (cloud vendor, OS, etc)**
aws kops 1.16.2 - ubuntu 20.04

### PR DESCRIPTION
**Pull request by ostromart**
Fixes https://github.com/istio/istio/issues/24318.

### CODE REVIEW

**Review by richardwxn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
Can you remind me why we actually treat string as yaml? I vaguely recall this but forgot. It feels "wrong" but hard to say without know why we do it

**Comment by ostromart** [comment]
to support patching a path with an object rather than a scalar. there may be some other way to do this but fundamentally the problem is that yaml expects a scalar for this:
```
key: value
```
and there's no way that i know of that would let you also support this: 
```
key:
  key2: value
```
other than passing a scalar string:
```
key: |
  key2: value
```

**Comment by howardjohn** [comment]
@ostromart makes sense. I have no clue what this would look like in practice, but in theory you could have it be a custom type like IntOrStr in k8s, where we determine the type during unmarhal. Probably a HUGE pain to do though, go is not good that this stuff

**Comment by ostromart** [comment]
the difficulty is that objects in yaml don't unmarshal into an interface{} type - you need something like map[string]interface{}, in which case then scalars won't unmarshal. we'd probably have to create both versions of IstioOperatorSpec and then see if either one would unmarshal or do some crazy stuff with reflect.

**Comment by howardjohn** [comment]
Can we not make a custom type like StringOrMap following intOrStr? Not sure how that works with our "proto first" apis though. yaml/proto suck 🙂

**Pull request merged**
