### PR TITLE
Create OWNERS

### PR DESCRIPTION
**Pull request by sebastienvas**
Ad myself and @ldemailly as the owner for release dir.

```release-note
NONE
```

### CODE REVIEW

**Comment by sebastienvas** [comment]
assign @ldemailly

**Comment by rshriram** [comment]
Can you also add @linsun please?

**Comment by yutongz** [comment]
@rshriram  sorry, but you can't cancel other people's approval :)

**Comment by yutongz** [comment]
It seems we misses the "/lgtm" again. I recorded it.

**Comment by sebastienvas** [comment]
@rshriram Added linsun

**Comment by linsun** [comment]
Thank you guys!!

**Comment by ldemailly** [comment]
maybe we should move istio.VERSION into release/ as people seem to update it manually to strange shas

**Pull request merged**
