### PR TITLE
readiness revert to update status stats

### PR DESCRIPTION
**Pull request by ramaraochavali**
If readiness probe continues to have issues after https://github.com/istio/istio/pull/18679 , this PR is to get back to the old functionality

### CODE REVIEW

**Comment by howardjohn** [comment]
Some logs with the other change in:

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_installer/496/noauth_installer/160/artifacts/kind/istio-testing-control-plane/pods/istio-micro_istio-ingressgateway-86d769f88-9bbvk_bfc18407-5ea3-47f2-b29e-ccc4a85d400b/istio-proxy/0.log

Works but has a lot of timeouts

Seem to work
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_installer/496/noauth_installer/160/artifacts/kind/istio-testing-control-plane/pods/simple-micro_echosrv-deployment-1-546748f44-q9bmt_39d2301f-12ed-4137-846c-59a5a810758c/istio-proxy/0.log
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_installer/496/noauth_installer/160/artifacts/kind/istio-testing-control-plane/pods/simple-micro_echosrv-deployment-2-69bb9b79f7-6twzv_9f49ed76-5d0f-4adf-b109-2c82df515850/istio-proxy/0.log

**Comment by ramaraochavali** [comment]
@howardjohn Timeouts are very surprising though. Suspecting that reducing the timeout to 1s causing these many timeouts?
So what do we do with this PR? Should we watch for some more time or merge this?

**Comment by ramaraochavali** [comment]
@howardjohn this got merged. So let us leave it with this for now and when we find a problem with hot-restarts may be we can revive my fix if needed

**Pull request merged**
