### PR TITLE
Update operator CRD file to sync with generated file

### PR DESCRIPTION
**Pull request by jasonwzm**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
thanks!

**Comment by howardjohn** [comment]
can you run `BUILD_WITH_CONTAINER=1 make gen`? We are working on a README to explain all the steps needed but for now that should be good

**Comment by howardjohn** [comment]
sorry I lied.. you also need `UPDATE_GOLDENS=true go test ./operator/...`. Sorry the process isn't streamlined yet

**Comment by jasonwzm** [comment]
> sorry I lied.. you also need `UPDATE_GOLDENS=true go test ./operator/...`. Sorry the process isn't streamlined yet

Yes, did that. Also adding the a line at the end of update script to update the golden files.

**Pull request merged**
