### PR TITLE
Fix crd filter

### LINKED ISSUE #45137: discoverySelector should also limit gateway deployment controller
when ENABLE_ENHANCED_RESOURCE_SCOPING = true, discoverySelector should also take effect on gateway deployment controller.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

fix #45137 crd part

And also fix the integration test 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by kfaseela** [comment]
thanks @hzxuzhonghu !

**Comment by kfaseela** [comment]
Changes LGTM

**Review by howardjohn — COMMENTED** [review]
Can we add a unit test in crdclient

**Pull request merged**
