### PR TITLE
Add standalone istioctl to the release and update to use new dev builds

### PR DESCRIPTION
**Pull request by howardjohn**
@davidebbo @sushicw @irisdingbj this will get istioctl standalone archives you have been asking about

@sdake this will fix cni

### CODE REVIEW

**Review by sdake — APPROVED** [review]
looks good.

**Review by geeknoid — APPROVED** [review]

**Comment by sushicw** [comment]
Awesome, thanks @howardjohn !

**Review by linsun — APPROVED** [review]

**Review by rshriram — APPROVED** [review]

**Pull request merged**
