### PR TITLE
test not set inbound alpn

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@howardjohn From the failure it seems inbould listener downstream tls context alpnProtocol can be any value. 

The only requirement is for TCP mx is it should include "istio-peer-exchange"

That's very weird.

**Comment by howardjohn** [comment]
I think envoy doesn't really do ALPN negotiation. But the MX filter explicitly looks for that ALPN

**Comment by hzxuzhonghu** [comment]
I guess you are right

**Pull request closed without merging**
