### PR TITLE
Fix potential fd leak

### PR DESCRIPTION
**Pull request by zrss**
Fixes: #9760

### CODE REVIEW

**Comment by zrss** [comment]
ping @nmittler for reviewing too, and it should be fixed ...

**Comment by ymesika** [comment]
/ok-to-test

Replaces #9761

**Comment by ymesika** [comment]
@zrss Do you mind rebasing to try to fix the failed required test?

**Comment by zrss** [comment]
:smile: i would do

**Comment by ymesika** [comment]
@zrss can you please merge `release-1.1` into your branch? There are changes required for the tests to pass.

**Comment by howardjohn** [comment]
@zrss can you reopen this under master branch and/or rebase your changes?

**Comment by zrss** [comment]
@howardjohn , done

**Comment by zrss** [comment]
see #13310

**Pull request closed without merging**
