### PR TITLE
Fix: allow enableNamespacesByDefault when revision tag is set

### PR DESCRIPTION
**Pull request by cnvergence**
**Please provide a description of this PR:**
If a previous installation existed and revision tag is used, users can't change the _enableNamespacesByDefault_ setting.
- https://github.com/istio/istio/issues/39604

### CODE REVIEW

**Comment by litong01** [comment]
@cnvergence added the label so that you do not need to add a release note.

**Comment by zirain** [comment]
cc @ericvn same issue with https://github.com/istio/api/pull/2409?

**Review by GregHanson — APPROVED** [review]

**Review by ericvn — APPROVED** [review]
Release note looks good.

**Review by litong01 — APPROVED** [review]
looks good to me. Thanks Karol for your contributions.

**Pull request merged**
