### PR TITLE
move to newer grafana

### PR DESCRIPTION
**Pull request by linsun**
to address some of the security issues with older grafana.

### CODE REVIEW

**Comment by linsun** [comment]
@duderino can we get this merged?  Our security scan tool raised issues with 5.4 and suggested us to move.

**Comment by howardjohn** [comment]
Is this safe to bump in 1.1? Did you do any testing to make sure our dashboards still work?

**Comment by linsun** [comment]
@howardjohn yes, I just tested it on a 1.1 system manually it works fine.

**Comment by duderino** [comment]
@therealmitchconnors I hear you did something like this.  can you comment?

**Comment by therealmitchconnors** [comment]
I upgraded the release qual test cluster to 6.0.1 and experienced no difficulties.  Also, the new metrics explorer feature makes it much easier to build new dashboards.

Not sure about the test failures, but I would guess that's just flakiness...

/lgtm

**Pull request merged**
