### PR TITLE
[WIP] Further stabilization of the racetest

### PR DESCRIPTION
**Pull request by ymesika**
A [racetest recently failed](https://circleci.com/gh/istio/istio/126732) with the following the following relevant log:

```sh
=== RUN   TestErrors
=== RUN   TestErrors/0
=== RUN   TestErrors/1
2018-06-28T23:22:17.060641Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2018-06-28T23:22:17.061528Z	warn	error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
=== RUN   TestErrors/2
2018-06-28T23:22:17.452662Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc427f76220, CONNECTING
2018-06-28T23:22:17.454710Z	info	grpc: addrConn.createTransport failed to connect to {[::]:38146 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::]:38146: connect: cannot assign requested address". Reconnecting...
2018-06-28T23:22:17.455584Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc427f76220, TRANSIENT_FAILURE
=== RUN   TestErrors/3
=== RUN   TestErrors/4
2018-06-28T23:22:19.152646Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc427f76220, CONNECTING
=== RUN   TestErrors/5
2018-06-28T23:22:19.166544Z	info	grpc: addrConn.createTransport failed to connect to {[::]:38146 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::]:38146: connect: cannot assign requested address". Reconnecting...
2018-06-28T23:22:19.167700Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc427f76220, TRANSIENT_FAILURE
=== RUN   TestErrors/6
FAIL	istio.io/istio/mixer/pkg/server	8.751s
```

This fix is using a different port to avoid conflict with previous iteration which used the same port.
Test logic isn't affected.

### CODE REVIEW

**Comment by ymesika** [comment]
Adds to #6730

**Comment by geeknoid** [comment]
May I ask why you closed this? It seems like a useful change.

**Comment by ymesika** [comment]
@geeknoid I used this PR for building/testing/debugging purposes. Unfortunately I can't recreate any of the racetests failures when running locally.

Now that I think I've targeted the root cause I'm making this PR avail but will re-run the racetest on CircleCI with this change to see if we hit that failure again. This is a failure with no details (as you can see in the log above) which makes it quite difficult to spot the reason.

In addition, I'm adding a change proposed in https://github.com/istio/istio/pull/6625#discussion_r198612433 and I didn't get the chance to change it before that got merged.

**Comment by ymesika** [comment]
This failure is still happening although I tried several approaches.
The most difficult part is the lack of information in the log about why it failed. Beside the `FAIL` message there is no hint in the log.

@geeknoid @rshriram @douglas-reid  Maybe you have some suggestion about how to "reveal" the source of the failure? Where to add debugging logging messages?
It happens only when the race test runs in CircleCI which makes it more difficult to debug.

**Comment by rshriram** [comment]
closing.. as smaller fixes for the race test went into 1.0

**Pull request closed without merging**
