### PR TITLE
style: remove unused code

### PR DESCRIPTION
**Pull request by drivebyer**
**Please provide a description of this PR:**

This PR remove unused code.

### CODE REVIEW

**Comment by howardjohn** [comment]
Is there more context for this? This is intended to use slice to avoid extra allocations of sets. Also I don't see how this can compile without changing call sites?

**Comment by drivebyer** [comment]
> Is there more context for this? This is intended to use slice to avoid extra allocations of sets.

hi @howardjohn , in my view, if the return value is a slice, there is still a memory allocation. Maybe the return type of `Set` can provide more methods for caller for lating use.

>  Also I don't see how this can compile without changing call sites?

Actually, this method has no caller.

**Comment by howardjohn** [comment]
I think we can just delete it then. The original PR adding it ended up just using Difference, I think it was merged in mistake

**Review by ericvn — APPROVED** [review]
LGTM

**Pull request merged**
