### PR TITLE
Change downloadIstio to use latest github release

### PR DESCRIPTION
**Pull request by javier-b-perez**
Change to use latest github release instead of static version.

Signed-off-by: Javier B Perez <jbperez@google.com>

### CODE REVIEW

**Comment by sebastienvas** [comment]
build istio/presubmit

**Comment by ldemailly** [comment]
I think having control on the release is better for now - we don't release that often and that version is the "stable" one

**Comment by ldemailly** [comment]
Doesn't seem to work on my mac:
```
ldemailly-macbookpro:mixer ldemailly$ LATEST_RELEASE_URL="https://api.github.com/repos/istio/istio/releases/latest"
ldemailly-macbookpro:mixer ldemailly$ ISTIO_VERSION="$(curl -sX GET ${LATEST_RELEASE_URL} | sed -En 's/\s+\"tag_name\": \"([^\"]+)\",$/\1/p')"
ldemailly-macbookpro:mixer ldemailly$ echo $ISTIO_VERSION

```

**Comment by sebastienvas** [comment]
It does work on linux. sed might be behaving differently on mac

**Comment by javier-b-perez** [comment]
The script could be automatically updated as part of the release process to always point to the last release. There is no need to use latest github tag.

**Pull request closed without merging**
