### PR TITLE
Reduce cache.Get lock conflict

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

For #40744

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Yes, i see the ut raced.

**Comment by hzxuzhonghu** [comment]
It is not evict, but `c.evictList.MoveToFront(ent)`

**Comment by hzxuzhonghu** [comment]
looks like this should be fixed in upstream

**Comment by stevenctl** [comment]
That repo hasn't seen a commit in > 1.5 year. If we want the change we probably have to contribute it ourselves. 
I wonder if we're hitting the ceiling (XDSCacheMaxSize) of the LRU in practice.

**Comment by jefferai** [comment]
It's really not clear from the issue reported in `golang-lru` what the problem is, or from this PR. Happy to have this fixed in `golang-lru`, especially if you know what's wrong and can PR it.

**Comment by howardjohn** [comment]
I don't think its a bug in golang-lru at all; by nature of the implementations Get() in the LRU mutates data (to evict data/record use), so using a read lock only (rather than write lock) is not sufficient on Get().

**Comment by jefferai** [comment]
Ah, OK, a misunderstanding. I will close the upstream bug then.

**Pull request closed without merging**
