### PR TITLE
commit Gopkg.lock and change docs to use Go build

### PR DESCRIPTION
**Pull request by rshriram**
Update guides.

Also add Gopkg.lock and use the lock file for keying circleci

### CODE REVIEW

**Comment by rkpagadala** [comment]
@rshriram why do we need to lock down with Gopkg.lock

**Comment by rshriram** [comment]
Its the cache key.. We need a unique key everytime the dependencies are updated.. Since we are not using WORKSPACE, we are switching over to go dep's Gopkg.lock for uniquely identifying the cache keys..

**Comment by douglas-reid** [comment]
/hold

looking quickly, but there are still items in this repository that are *only* generated via bazel. don't we have to undo that first, before deleting the WORKSPACE file?

**Comment by rshriram** [comment]
@costinm said that you confirmed we are using go generate for everything.. If thats not the case, lets park this PR.

**Comment by douglas-reid** [comment]
@rshriram oh how I wish. working on it. just taking a few.

**Comment by costinm** [comment]
For the failing test: you need to replace downloading of the envoy with 'bin/init.sh' 
( I updated all other places - missed this one)

**Comment by mattdelco** [comment]
The debian images for pilot and security are still based on bazel (in each's respective bin/push-debian.sh) .

**Comment by rshriram** [comment]
restored WORKSPACE file. WE can remove it later..

**Comment by rshriram** [comment]
merging, per offline conversation with @douglas-reid ..

**Pull request merged**
