### PR TITLE
remove experimental feature flag METRIC_ROTATION_INTERVAL

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

This will not be promoted as part of Telemetry API, users who want to use can use following envoyfilter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metric-rotation
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: istio.stats
      patch:
        operation: MERGE
        value:
          name: istio.stats
          typedConfig:
            "@type": type.googleapis.com/stats.PluginConfig
            rotationInterval: 10m
            gracefulDeletionInterval: 5m
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: istio.stats
      patch:
        operation: MERGE
        value:
          name: istio.stats
          typedConfig:
            "@type": type.googleapis.com/stats.PluginConfig
            rotationInterval: 10m
            gracefulDeletionInterval: 5m
```

### CODE REVIEW

**Comment by keithmattix** [comment]
Need to think/discuss this more but this needs a release note IMO

**Comment by hzxuzhonghu** [comment]
We should provide a simple way to do this. We have seen too many cases about memory increase because of stats

**Comment by zirain** [comment]
> We should provide a simple way to do this. We have seen too many cases about memory increase because of stats

this should be configed per proxy, maybe worth a API change(not sure where's the right place), but absolutely not be in pilot feature flag.

**Comment by hzxuzhonghu** [comment]
ProxyConfig sounds good to me

**Comment by howardjohn** [comment]
I would very much like to get to a point where a user does not need to think about this (i.e. zero config), and we do not have memory issues. Can we work towards that goal.

**Comment by zirain** [comment]
> ProxyConfig sounds good to me

`NOTE: fields in ProxyConfig are not dynamically configured - changes will require restart of workloads to take effect.`

It's gonna be a little weird to use ProxyConfig to config `istio.stats` filter.

**Comment by zirain** [comment]
> I would very much like to get to a point where a user does not need to think about this (i.e. zero config), and we do not have memory issues. Can we work towards that goal.

We cannot find a suitable default value to enable it by default.

**Comment by hzxuzhonghu** [comment]
Brain storm a fixed value,  move it to proxyConfig is more flexible

**Comment by howardjohn** [comment]
> > I would very much like to get to a point where a user does not need to think about this (i.e. zero config), and we do not have memory issues. Can we work towards that goal.
> 
> We cannot find a suitable default value to enable it by default.

In the original PR we were talking about times like 5 min and 10 min. What if we just set it to 12 hours? is there risk there?

**Comment by zirain** [comment]
> > > I would very much like to get to a point where a user does not need to think about this (i.e. zero config), and we do not have memory issues. Can we work towards that goal.
> > 
> > 
> > We cannot find a suitable default value to enable it by default.
> 
> In the original PR we were talking about times like 5 min and 10 min. What if we just set it to 12 hours? is there risk there?

12h maybe too long for some high load traffic proxy/gateway, then we back to need to provide a way to change/disable/enable it.

**Comment by howardjohn** [comment]
Its better than nothing... how many people are getting such extreme leaks that reseting every 12hr would not be ok?

And 12hr is extreme, probably 1hr is more than enough

**Comment by zirain** [comment]
> Its better than nothing... how many people are getting such extreme leaks that reseting every 12hr would not be ok?
> 
> And 12hr is extreme, probably 1hr is more than enough

I agree that 1h is enough, we can use it by default, now the next question how can use disable it(people who want to keep everything like before?) or change the value? EnvoyFilter seems not be able to disable it?

**Pull request closed without merging**
