### PR TITLE
Add flag to enable STS

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Add flag sts.servicePort that enables STS server for sidecars when port is non-zero.
Also enable STS config in bootstrap config when flag is set.

The following files are not changed
manifests/istio-control/istio-config/templates/deployment.yaml
manifests/istio-control/istio-discovery/templates/deployment.yaml
manifests/istio-control/istio-autoinject/files/injection-template.yaml
manifests/istio-telemetry/mixer-telemetry/templates/deployment.yaml

#20133

### CODE REVIEW

**Review by liminw — APPROVED** [review]
/lgtm

**Review by richardwxn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
is gcp_envoy_bootstrap actually used? can you send the link where we select this?

**Comment by kyessenov** [comment]
I think gcp_envoy_bootstrap is used in google repos.

**Review by bianpengyuan — COMMENTED** [review]
Should we also add `tokenManagerPlugin` option here and make it default to `GoogleTokenExchange`?

**Pull request merged**
