### PR TITLE
fix 404 url

### PR DESCRIPTION
**Pull request by tanjunchen**
fix 404 url
/bug

### CODE REVIEW

**Comment by tanjunchen** [comment]
@rootsongjc  can you give ok-to-test? thanks

**Comment by rootsongjc** [comment]
@tanjunchen I have no privilege to set ok-to-test.

**Comment by tanjunchen** [comment]
<a href="https://istio.io/docs/reference/config/template/metric/">metric</a>.
<a href="https://istio.io/docs/reference/config/template/checknothing/">checknothing</a>.
<a href="https://istio.io/docs/reference/config/template/reportnothing/">reportnothing</a>.
<a href="https://istio.io/docs/reference/config/template/quota/">quota</a>.</p>
I try to change these files to 
<a href="https://istio.io/docs/reference/config/policy-and-telemetry/templates/metric/">metric</a>.
<a href="https://istio.io/docs/reference/config/policy-and-telemetry/templates/checknothing/">checknothing</a>.
<a href="https://istio.io/docs/reference/config/policy-and-telemetry/templates/reportnothing/">reportnothing</a>.
<a href="https://istio.io/docs/reference/config/policy-and-telemetry/templates/quota/">quota</a>.</p>

But,These files are generated by command(BUILD_WITH_CONTAINER=1 make gen).
But There files are error urls. How can i change there files?

@richardwxn @jasonwzm  Thanks

**Comment by jasonwzm** [comment]
You should change in `mixer/adapter/bypass/config/config.proto`.

**Comment by tanjunchen** [comment]
@jasonwzm  Thanks!

**Comment by tanjunchen** [comment]
@jasonwzm done

**Comment by tanjunchen** [comment]
@jasonwzm Thanks! How can i cc them?

**Comment by tanjunchen** [comment]
@bianpengyuan Thanks

**Pull request merged**
