### PR TITLE
Cleanup makefile and prow scripts

### PR DESCRIPTION
**Pull request by howardjohn**
Our prow scripts and makefiles have a *lot* of magic that is very difficult to understand.

This change is a step in the direction of simplifying and making the `prow/` scripts obsolete -- ideally we can have most tests just `make xyz` and not have all of these scripts.

This change:

* Sets pipefail global makefile level, so all targets don't need to simplify it
* Removes unnecessary junit stuff. Lint doesn't output any junit, and racetest should reuse the same junit stuff as other targets.
* Remove ARTIFACTS_DIR. Prow already sets ARTIFACTS variable we can reuse. Just changing this won't help too much yet, but eventually I hope to remove the reliance on `setup_and_export_git_sha` which will allow the targets to just be makefiles. I didn't want to do this in on PR though since its hard to review large refactoring PRs.

### CODE REVIEW

**Comment by sdake** [comment]
not sure why there is a duplicate comment.  I left only one...

**Comment by howardjohn** [comment]
> Note that its possible with the new prow to completely remove the /prow dir

that's the plan, or to get pretty close at least

**Comment by howardjohn** [comment]
/retest

@utka I had to rebase

**Comment by howardjohn** [comment]
@sdake @utka can you give another lgtm, I had to rebase

**Pull request merged**
