### PR TITLE
envoy: remove extension lookup by name

### PR DESCRIPTION
**Pull request by kyessenov**
The runtime flag is being deprecated and has issued warnings by istioctl for quite some time already.
Ref: https://github.com/envoyproxy/envoy/issues/23598

### CODE REVIEW

**Comment by howardjohn** [comment]
For others reference this is warned in https://github.com/istio/istio/blob/d8b21e02e754b6e93bf259ff7e226fafaa9c16d3/pkg/config/validation/validation.go#L987

**Comment by howardjohn** [comment]
We should probably add a release note about this? And mention there is a deprecation warning already so `istioctl analyze` can check the existing configs or something similar

**Comment by kyessenov** [comment]
@howardjohn Good idea. Sadly, `istioctl` cannot detect nested extension lists so that might need a manual intervention. That's the price of EnvoyFilter.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
