### PR TITLE
Add multicluster CA main function.

### PR DESCRIPTION
**Pull request by myidpt**
This is the initial version for the multicluster CA main function.
Docker image build script, tests and deployment yaml files are coming in following PRs.

### CODE REVIEW

**Comment by wattli** [comment]
High-level question, this is for intermediate CA or root CA?

**Comment by myidpt** [comment]
@wattli That's good question. We name it as multi-cluster CA to avoid confusion. Because on one hand, this CA can take an intermediate cert given by operator; and on the other hand, our cluster CAs can be self-signed root CAs.

**Pull request merged**
