### PR TITLE
Deprecate values.yaml trustDomain setting

### PR DESCRIPTION
**Pull request by howardjohn**
Part of https://github.com/istio/istio/issues/27734

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
@linsun @sdake @costinm PTAL

**Review by sdake — APPROVED** [review]
approve

**Review by morvencao — APPROVED** [review]
/test release-notes_istio

**Pull request merged**
