### PR TITLE
Does renaming support ipv4/6 field names

### PR DESCRIPTION
**Pull request by ChenglongGao327**
rename field name ipv4Support to ipv4  and ipv6Support to ipv6

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Any specific reason for this change? In dual IP proxies it indictates whether the proxy supports ipv4 or ipv6 - In that sense `ipv4Support` may be more meaningful

**Comment by hzxuzhonghu** [comment]
yes, the rename looks meaningless. I am thinking we should leave one field, currently, they are opposite, looks redundant

**Comment by howardjohn** [comment]
They are not opposites, you can support one or both (although neither is
probably not possible).For dual stack

**Comment by hzxuzhonghu** [comment]
@howardjohn At least for now, the values are opposite.  For dual stack, i am not sure how it is supported.

If we make it one day in future.
`IPMode`  [ `IPV4`, `IPV6`, `DUAL_STACK`]looks more reasonable.

**Pull request closed without merging**
