### PR TITLE
[WIP] Combine envoy test utils in mixer and test/framework

### PR DESCRIPTION
**Pull request by m1093782566**
Fixes: #8465

/assign @nmittler @ozevren 

NOTE: It's still WIP and will let you know when it's ready for review.

### CODE REVIEW

**Comment by nmittler** [comment]
@m1093782566 if you want to keep it simple, you could just move the envoy files in one PR and then merge in another?

**Comment by m1093782566** [comment]
@nmittler 

Sounds fair. I just created a PR, xref: #8740. PTAL, THANKS!

**Comment by nmittler** [comment]
@m1093782566 just checking ... is this still on your radar?

**Comment by m1093782566** [comment]
@nmittler 

Yes but please feel free to take this if you want to push it forward quickly because it may take me a couple of days to finish the task and I am currently looking into using kind(kubernetes in docker) to set up an Istio testing environment.

Sorry for delay...

**Comment by nmittler** [comment]
not stale

**Comment by nmittler** [comment]
@m1093782566 any progress here?

**Pull request closed without merging**
