### PR TITLE
Update templates (once again)

### PR DESCRIPTION
**Pull request by kyessenov**
@yutongz @sebastienvas we have to fix duplicates of installation files ASAP. This is a constant problem in pilot.

### CODE REVIEW

**Comment by yutongz** [comment]
Totally understand your pain. Right now, we are all working on migrations, version update and since everything is failing after we move to 1.7, we are also trying to fix that. Will help you on this painful stuff as next week if we can make CI green on istio/istio.

**Comment by sebastienvas** [comment]
@kyessenov Did you use the script to generate the other files ?

**Pull request merged**
