### PR TITLE
download script should fail early when the download failed

### PR DESCRIPTION
**Pull request by spacewander**
**Please provide a description of this PR:**

Currently, when the `curl -fsL -o "${tmp}/${filename}" "$ARCH_URL"` failed, the download will continue with msg `istioctl-xxx download complete!` and exit successfully. This behavior reports a successful download even when it failed.

### CODE REVIEW

**Comment by ericvn** [comment]
Would you expand on why the curl failed?

**Review by howardjohn — COMMENTED** [review]
LGTM

**Review by dhawton — COMMENTED** [review]
LGTM.. think this should be ok to cover an *if* the curl command fails.

**Comment by spacewander** [comment]
> Would you expand on why the curl failed?

The curl failed because of the timeout caused by the slow network.

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
Thank you.

**Pull request merged**
