### PR TITLE
Add more values to recognized templates to mixer integration test

### PR DESCRIPTION
**Pull request by johnholiver**
- Improve error verbosity

### CODE REVIEW

**Comment by johnholiver** [comment]
Assigning Mandarjog cause these changes are just an addition to his previous string slice of crs. Should be a super quick review for him. :)
/assign @mandarjog

**Comment by johnholiver** [comment]
@kyessenov could you have a look at this PR? It is super simple and it has been open for more than a month. I've just added the other templates that can be used during integration testing. I've noticed you even added the apa template here like 2w ago (made me rebase).
This will allow ppl that are following the OOT adapter walkthrough to do integration test to adapters that are not based on metric template (mine, for example, is based on authorization). Otherwise, devs can be confused by the failures in their integration tests.

**Comment by johnholiver** [comment]
@kyessenov just rebased it and pointed the PR to release-1.1
Not sure why but the tag cla:yes got removed by doing that

**Comment by kyessenov** [comment]
CLA bot has a random bug that invalidates PRs switching the base...
I assume the CLA is signed since the bot has not complained the first time.

**Pull request merged**
