### PR TITLE
[Kiali][release-1.0] upgrade kiali version

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
How are these lint errors even able to get committed into the branch? I don't understand. Do I have to wait for someone to fix this, and then rebase?

```
please run bin/fmt.sh against: ./addons/servicegraph/promgen/promgen.go
Makefile:266: recipe for target 'lint' failed
make: *** [lint] Error 1
```

**Comment by gyliu513** [comment]
Want to get some comments from @linsun to see if we need to update 1.0 version.

**Comment by jmazzitelli** [comment]
a new kiali release was made recently, so this PR is superceded by https://github.com/istio/istio/pull/10705

closing this PR in favor of that new one.

**Pull request closed without merging**
