### PR TITLE
Use jaeger for zipkin service

### PR DESCRIPTION
**Pull request by douglas-reid**
This switches out the image used for the deployments matching the `zipkin` service to use the `1.4.1` version of `jaeger` instead.

The PR adds a service port of `80` for ui concerns (forwarded here to jaeger's `16686` container port).

Based on discussions with: @costinm @mandarjog

### CODE REVIEW

**Comment by douglas-reid** [comment]
It appears prow is having issues. Neither of those test failures have anything to do with this PR.

**Comment by rshriram** [comment]
merging due to prow issues

**Pull request merged**
