### PR TITLE
Ambient ignore system namespace

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fix https://github.com/istio/istio/issues/52343

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is removing our ability to read pods entirely. This is not what we want, and would introduce a bug we had in Istio 1.0 times where you cannot communicate to anything in kube-system.

What we want, at most, is to not allow _enrolling a pod in kube-system_ into the mesh, like we do with injection. But service discovery must support pods in these namespaces.

So this should be in the CNI code at most

**Comment by hzxuzhonghu** [comment]
should default to passthrough, nobody want service mesh to manage connect to kube-apiserver

**Comment by bleggett** [comment]
Ambient is opt-in (pod or namespace).

What is to be gained by adding code to forcibly ignore these namespaces, when people can simply not label them, and they will be ignored anyway?

There are no special namespaces.
Namespaces are an operational preference.

**Comment by howardjohn** [comment]
> should default to passthrough, nobody want service mesh to manage connect to kube-apiserver

this code isn't making it passthrough, it's blocking all traffic.

**Comment by hzxuzhonghu** [comment]
Isn't ztunel use passthrough in outbound.rs? 
As to why ignore services, pods., etc in these namespaces. 
First because this is too wasty to push a lot of useless resources. And second it is confusing, may ontroduce mistakes if we support global settings

And I wish to add `istio-system` as well. 

Or we can introduce a mesh config

**Comment by howardjohn** [comment]
Istio-system is pretty critical namespace to support.

I don't think it makes sense to make these changes when we haven't even
made them in sidecars?

Is there really a performance impact from kube-system that is causing
issues for users?

**Comment by hzxuzhonghu** [comment]
Not much performance influence. We have a dataplane watching all the workloads, and only deployed sleep and httpbin for test, but found more than 10 others showing there. 
linkerd also ignores endppoints in kube-system. I would prefer starting from ambient.  
Ambient constructs workloads from all pods, no matter they have bound services or not.  Is there any bad effect ignoring them?

**Comment by howardjohn** [comment]
Well right now this is keeping the services but ignoring the workloads which breaks service traffic entirely. But even without that.. 

The cost of each workload is about 200bytes. That is incredibly small compared to sidecars, so I would really not use xds performance as a motivator - we can easily scale to 100k pods so why does 10 extra matter? 

Having the proper information enables a few things... 
* We can get proper telemetry when we connect to these workloads
* We act as a DNS server,so we would break DNS for these
* We could act as  a full kube-proxy replacement ,but not if we ignore these
* Consistent behavior across the cluster 
* Any features we might add in the future can apply to this type of traffic


On istio-system specifically I expect users to have many workloads in istio-system in the mesh actually, and do with users today, so that would definitely be a bigger issue.

**Pull request closed without merging**
