### PR TITLE
replace ldap with openid

### PR DESCRIPTION
**Pull request by rramirz**
The with operator is looking at the same value the strategy is suppose to be. If ".Values.kiali.dashboard.auth.strategy" equals ldap it should look under ".Values.kiali.dashboard.auth.ldap"

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by shamsher31** [comment]
Hey @rramirz, can you please sign CLA.

**Comment by rramirz** [comment]
I sign the CLA on May 28, 2020 19:49 PDT

**Comment by rramirz** [comment]
@googlebot I signed it!

**Review by morvencao — COMMENTED** [review]
This looks good to me, what is the status of this? Any blockers to merge this? 
@jmazzitelli PTAL

**Comment by jmazzitelli** [comment]
That looks good to me. Just realize the addons are going away from istioctl very soon (1.7 I believe?). In addition, the ldap auth strategy has been deprecated within Kiali itself and will be removed soon (replaced with the OAuth auth strategy such that OID can be used in front of the ldap provider).

**Comment by rramirz** [comment]
Yea, I did see that ldap is getting deprecated soon. I updated the template to include an option for openid as well.

**Comment by rramirz** [comment]
I actually just went ahead and replaced the ldap options with openid since the ldap option no longer supported in the later versions.

**Comment by howardjohn** [comment]
@rramirz thanks for the efforts in this area. We have decided to change our approach for addons, and as a result this code is no longer part of the repo so I don't think this PR is still required. See https://istio.io/latest/blog/2020/addon-rework/ for more info. Thanks!

**Pull request closed without merging**
