### PR TITLE
Cherrypick #6121 and #6394 to ship multiplexing in snapshot release.

### PR DESCRIPTION
**Pull request by incfly**
#5059

### CODE REVIEW

**Comment by incfly** [comment]
@hklai I've updated the istio/proxy's SHA in to https://github.com/istio/proxy/pull/1823 in `istio.deps`.

PTAL, thanks!

**Comment by hklai** [comment]
@incfly I think it will take a while for the proxy image to be built (in proxy post-submit) for all these tests here. And I will merge once the tests have passed here.

**Comment by incfly** [comment]
/hold

I think some API dependency stuff needs to be aligned...

There's an API change that's already included in istio/api release-1.0-snapshot.0 branch.
But istio/proxy:release-1.0-snapshot.0 does not have that... :( 

Control plane (istio/istio:release-1.0-snapshot.0) is good enough already
https://github.com/istio/istio/blob/release-1.0.0-snapshot.0/vendor/istio.io/api/authentication/v1alpha1/policy.proto#L29:53

**Comment by hklai** [comment]
The branches should be created from a consistent set of SHAs.

What API change are you referring to?

**Comment by incfly** [comment]
@hklai Some tests like `ci/circleci: e2e-simple` are hanging there, not reporting status. Any idea?

**Comment by hklai** [comment]
@incfly not sure, but I can manually merge once the corresponding jobs have passed in prow.

**Pull request merged**
