### PR TITLE
[release-1.12] Fix docker.save tar targets

### LINKED ISSUE #36072: [release-1.12] Fix docker.save tar targets
Manual cherrypick required.

#36041 failed to apply on top of branch "release-1.12":
```
Applying: Remove -default rather then DEFAULT_DISTRIBUTION
Using index info to reconstruct a base tree...
M	tools/istio-docker.mk
Falling back to patching base and 3-way merge...
Auto-merging tools/istio-docker.mk
CONFLICT (content): Merge conflict in tools/istio-docker.mk
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Remove -default rather then DEFAULT_DISTRIBUTION
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by sergii-ssh**
**Please provide a description of this PR:**
Manual cherry-pick for #36041
Fix #36072

### CODE REVIEW

**Comment by sergii-ssh** [comment]
for some reason `retest` didn't trigger any tests. Pushed empty commit to rerun all tests

**Comment by sergii-ssh** [comment]
@dgn or @ericvn PTAL, tests are passing now

**Review by dgn — APPROVED** [review]

**Pull request merged**
