### PR TITLE
multi-network: fix eastwest gateway endpoint filtering

### PR DESCRIPTION
**Pull request by stevenctl**
I think this fixes/helps with https://github.com/istio/istio/issues/38704

Gateways care about server settings only (authn, and tlsMode labels) when doing this filtering. 

We will filter out servers that we don't think accept mTLS (DISABLED or tlsMode: none). If a client somehow sent non-mTLS traffic, they would have to spoof SNI and then the server would deny them anyway.

### CODE REVIEW

**Comment by nmittler** [comment]
@stevenctl can you also update [this test](https://github.com/istio/istio/blob/master/tests/integration/security/authorization_test.go#L887) to include a Count > 1? This test passing in multi-network actually relies on `Count==1`, which is incredibly fragile.

**Review by hzxuzhonghu — COMMENTED** [review]
It needs a test

**Comment by stevenctl** [comment]
Adjusted a test per @nmittler comment. His PR https://github.com/istio/istio/pull/37914/ improves coverage much more.

**Comment by stevenctl** [comment]
> It needs a test 

Nathan's PR added tests. This PR removed the need for the global DestinationRule

**Comment by hzxuzhonghu** [comment]
What;'s the behavior with tls disabled before and after? IIUC, for east-west gateway the cluster will include cluster local endpoints.

**Comment by stevenctl** [comment]
This makes it so TLS disabled in DR doesn't affect passthrough gateways (the endpoint will remain). That DR based filtering makes it so clients can't send plaintext that will inevitably fail since we require TLS/SNI. 

If a server is plaintext, we still remove the endpoint from the gateway.

**Comment by stevenctl** [comment]
>  will include cluster local endpoints.

Network local, non plaintext endpoints.

**Comment by hzxuzhonghu** [comment]
>Network local, non plaintext endpoints.

Looks good

**Review by GregHanson — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Comment by nmittler** [comment]
I opened https://github.com/istio/istio/issues/39330

**Pull request merged**
