### PR TITLE
test pkg/... common packages with make go-test

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Comment by mandarjog** [comment]
looks like this is failing because of Gomega missing from `Gopkg.lock`

**Comment by ldemailly** [comment]
I expect this should fix #2403 ?

**Comment by chxchx** [comment]
@jmuk this common-test target is not included in `ci/circleci: test`. I see you guys are calling make manually with `make localTestEnv make pilot-test mixer-test broker-test security-test` and you can avoid this problem with `make localTestEnv go-test`.

Once CircleCI is updated, I look forward to remove unit test from Prow presubmit.

cc @rshriram / @costinm

**Comment by GregHanson** [comment]
@chxchx @jmuk `make test` is called in this circleci job: https://github.com/istio/istio/blob/master/.circleci/config.yml#L361

and `common-test` is included in `make test` here:
https://github.com/istio/istio/blob/master/Makefile#L373

but I don't see the `./pkg` dir in the codecov output, any thoughts?

**Comment by jmuk** [comment]
It seems code coverage is different make target. Filed https://github.com/istio/istio/issues/3695

**Pull request merged**
