### PR TITLE
Fixes some minor bugs in multicluster e2e tests

### PR DESCRIPTION
**Pull request by john-a-joyce**
A few bugs with respect to error handling have been
noted in the multicluster e2e tests,  This change fixes
these bugs.

### CODE REVIEW

**Comment by sdake** [comment]
can you rebase this against release-0.8

Regards,
-steve

**Comment by john-a-joyce** [comment]
CC @costinm 
CC @yutongz
CC @sdake 

This isn't required for 0.8 so I still think it this should be merged to Master.  It's a pretty small fix can someone approve it so it can merge.

**Pull request merged**
