### PR TITLE
move back the weight for pod antiaffinity term.

### PR DESCRIPTION
**Pull request by morvencao**
Merge #14038 to master

### CODE REVIEW

**Comment by sdake** [comment]
@morvencao 1.2 backports should not be needed as mergify will automatically generate these backports.  See following screenshot for details on annotations:

Screen Shot 2019-05-29 at 4 13 15 AM

**Comment by morvencao** [comment]
@sdake Thanks, it's awesome!

**Comment by sdake** [comment]
> @sdake Thanks, it's awesome!

agreed.  @geeknoid has really done a nice job here 👍 Should save the maintainers significant time.

Cheers
-steve

**Comment by sdake** [comment]
@morvencao it appears the work with mergify is not completed for `istio/istio`.  Can you cherry-pick with `-x` flag?

Cheers
-steve

**Comment by morvencao** [comment]
@sdake Done, see: https://github.com/istio/istio/pull/14418/commits/dbaf20f607c6aa5d30defbba9db8b36b6f113394

**Pull request merged**
