### PR TITLE
Add missing space in log statement

### PR DESCRIPTION
**Pull request by luksa**
Previously, the log statement was: "Failed to generate bootstrap
configopen /etc..." (note that there's no space in configopen).

This commit fixes the statement, so it reads "Failed to generate
bootstrap config: open /etc/..."

### CODE REVIEW

**Comment by mbanikazemi** [comment]
Now that you are making this change, why not fix this for other similar log.Errora() calls.
I see a couple of other cases that can be fixed in following files:
tests/util/pilot_server.go
mixer/pkg/api/grpcServer.go

**Comment by luksa** [comment]
@mbanikazemi done.

**Comment by luksa** [comment]
review plz?

**Comment by ayj** [comment]
cc @geeknoid for mixer and other logging related changes

**Comment by howardjohn** [comment]
@luksa can you fix the lint failure?

**Pull request merged**
