### PR TITLE
file watcher fixes

### PR DESCRIPTION
**Pull request by ramaraochavali**
Fixes https://github.com/istio/istio/issues/37592

This fixes couple of things
- It does not check for already watching any more because we do not need to check for duplicate events. We have debounce implemented now.
- It does not handle REMOVE event. Remove event has a bug
     - We are triggering update callback for Remove which actually will fail because file is not there
     

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@howardjohn PTAL

**Comment by ramaraochavali** [comment]
Interesting in CI, atomicwrite generates CHMOD followed by REMOVE events. So earlier the REMOVE event logic was helping. https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/37679/unit-tests_istio/1499324591892336640/build-log.txt

Now changed to handle CHMOD for rename cases.

**Comment by ramaraochavali** [comment]
@howardjohn PTAL when you get chance. Definitely not urgent. Just want to get this on your list.

**Review by howardjohn — COMMENTED** [review]
I am still seeing TestFileSecrets failures when running locally

**Comment by ramaraochavali** [comment]
ok. Let me take a look :-).

**Comment by ramaraochavali** [comment]
With the recent fix I made to validate cert before delivering to Envoy, the REMOVE part is handled. So I am closing this PR.

**Pull request closed without merging**
