### PR TITLE
Update the base image versions for bookinfo sample apps

### PR DESCRIPTION
**Pull request by johnma14**
Fixes Bug: #16545

### CODE REVIEW

**Comment by linsun** [comment]
@johnma14 @sdake could we cherry pick this for 1.3 given it is moving these to latest images?

**Comment by sdake** [comment]
@geeknoid there appeared to be a problem with assigning codeowners.  Did this PR hit prior to the codeowners change?

Cheers
-steve

**Comment by linsun** [comment]
@rlenglet this should be no impact to docs... not sure why you are asking doc maintainer to review.

**Comment by rlenglet** [comment]
> not sure why you are asking doc maintainer to review.

I think GitHub had indicated that the docs team was required for approval.

**Pull request merged**
