### PR TITLE
IPv6 e2e-simple fixes

### PR DESCRIPTION
**Pull request by tiswanso**
e2e Test case fixes for IPv6

- values-e2e.yaml change is for liveness probes used in e2e tests and applies generally.
- ingress-nginx service type moved to ClusterIP due to k8s IPv6 kube-proxy behavior of not creating clusterIP NAT rules on every node for Loadbalancer/NodePort service types.  This should not effect any test envs since the test case always uses a pod in the k8s cluster as the ingress client.

Tested via circleci e2e-simple test for k8s IPv6 using DinD via KDC (kubeadm-dind-cluster) in istio/cni#100

Partially-fixes: #13129

### CODE REVIEW

**Comment by costinm** [comment]
Should this move to new  installer ?

**Comment by tiswanso** [comment]
> Should this move to new installer ?
@costinm  -- This PR is intended to add a gate for istio/istio PRs on IPv6 functionality.

**Comment by costinm** [comment]
Yes, I know - we want to gate istio/istio on new installer and all other
install environments. Abd we certainly want to test new installer with ip6.

My plan was to clone or vendor installer and run it's makefile for e2e.

**Comment by tiswanso** [comment]
@costinm  -- Ok cool.  Sure, let me know if I should move that circleci DinD stuff out to istio/installer.  The other files in the diff stand as testcase changes needed for e2e-simple w/ IPv6.

**Comment by costinm** [comment]
Please - we want to test multiple install options with this if possible.

**Comment by tiswanso** [comment]
@andraxylia @costinm @nmittler @rshriram @ZackButcher  --  this review needs some attention.

**Pull request merged**
