### PR TITLE
improve envoy formatter

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Allows not using dynamic metadata in some cases.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM assuming tests pass

**Comment by kyessenov** [comment]
@howardjohn Lint flakes?

**Comment by howardjohn** [comment]
I think there is a fix in https://github.com/istio/common-files/pull/766#pullrequestreview-1269897414, should be merged into istio/istio within an hour and then retest should fix it

**Comment by ericvn** [comment]
Wonder if you need to rebase to pick up the common-files update?

**Comment by ericvn** [comment]
Actually, no. I need to do a common-files update to this branch.

**Comment by kyessenov** [comment]
How do I manually bump common-files?

**Comment by howardjohn** [comment]
Rebase is never needed, prow rebases all PRs before running tests

**Pull request merged**
