### PR TITLE
support kubeconfig and context for manifest generate command

### LINKED ISSUE #28611: eastwest gateway fails to start
following guide in https://preliminary.istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/

the eastwest gateway can not be started due to the required mount `istio-token` does not exist.

### PR DESCRIPTION
**Pull request by irisdingbj**
fix: https://github.com/istio/istio/issues/28611

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I am not sure this is the right approach, because `manifest generate` may/will be used when connected to different cluster than when applied, for example in CI. the doc should use `istioctl install` instead IMO

**Comment by irisdingbj** [comment]
I recalled that `istioctl install` will prune other resources so this is the reason why we use `istioctl manifest generate` and then `kubectl apply` @stevenctl and @nmittler may have more background

for the issues @howardjohn mentioned, after we add the --kubeconfig support into manifest generate, we can specify what ever kubeconfig we need and when we apply we can specify kubeconfig to others as well.  So this should not be an issue for the scenario you mentioned.  
@howardjohn @linsun @nmittler @stevenctl WDYT? We need a fix for this issue in 1.8 as this will block user to try our latest MC doc.

**Comment by howardjohn** [comment]
it used to, should he fine now as long as the IOP has a distinct name which
I believe the east west one does

**Comment by irisdingbj** [comment]
Thanks for the info. @howardjohn @stevenctl are we working to change the doc on istio.io to reflect this?  

Meanwhile, do you think this PR is  good add for the `istioctl manifest generate`?

**Comment by linsun** [comment]
@irisdingbj is this the doc that installs the east-west gw?  If so, yes, I do intend to change it to use istioctl install in istio.io.  The only reason why I haven't done it is I can't get tests passing with the change, see https://github.com/istio/istio/pull/28296

cc @stevenctl @howardjohn

**Comment by irisdingbj** [comment]
@linsun Thanks for the info!  
While we change to use `istioctl install` directly to solve the eastwest issue. I do think we need make `isitoctl manifest generate` support --kubeconfig then it can detect the cluster settings when generating manifests.  

The change in this PR will support this and it also  work as before if user does not specify --kubeconfig.

**Comment by howardjohn** [comment]
> While we change to use istioctl install directly to solve the eastwest issue. I do think we need make isitoctl manifest generate support --kubeconfig then it can detect the cluster settings when generating manifests.

Will it default to the users current kubeconfig if not set? I think both behaviors are problematic

* If we default, users accidentally get "smart" settings for the wrong cluster
* If we do not default, its inconsistent/confusing behavior with istioctl and kubectl

**Comment by howardjohn** [comment]
Perhaps we could have a dedicated flag like `--apply-cluster-defaults`? cc @sdake @ostromart @esnible

**Pull request closed without merging**
