### PR TITLE
update proxy SHA

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Update Proxy SHA to d2d0c62a045d12924180082e8e4b6fbe0a20de1d

### CODE REVIEW

**Comment by hklai** [comment]
why not the latest?
https://github.com/istio/proxy/commits/release-1.1

**Comment by JimmyCYJ** [comment]
> why not the latest?
> https://github.com/istio/proxy/commits/release-1.1

The proxy SHA is updated to latest one.

**Comment by JimmyCYJ** [comment]
@hklai Could you take a look? Thanks!

**Pull request merged**
