### PR TITLE
update istio proxy

### PR DESCRIPTION
**Pull request by crazyxy**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by crazyxy** [comment]
> looks like it's missing some libraries or something?

I am looking at e2e-dashboard-master. 
```
2019-08-06T00:25:05.048886Z	info	Command error: exit status 1
2019-08-06T00:25:05.049397Z	info	Deployment rollout ends after [9m53.677018817s] with err [deployment.extensions/istio-egressgateway in namespace istio-system failed]
2019-08-06T00:25:05.049470Z	error	Failed to deploy Istio.
2019-08-06T00:25:05.049534Z	error	Failed to complete Init. Error deployment.extensions/istio-egressgateway in namespace istio-system failed
2019-08-06T00:25:05.049543Z	info	Saving logs
2019-08-06T00:25:05.049594Z	info	Creating status file
2019-08-06T00:25:05.050154Z	info	Created Status file /logs/artifacts/dashboard-test-d990fdcb013347b1a2c113/dashboard_test.json
2019-08-06T00:25:05.050176Z	info	Running command kubectl get ingress --all-namespaces --kubeconfig=
2019-08-06T00:25:05.313907Z	info	Command output: 
No resources found.
```

I am running e2e locally to debug this.

**Comment by crazyxy** [comment]
@howardjohn  find something, 

/home/prow/go/bin/envoy: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/prow/go/bin/envoy)

**Comment by rshriram** [comment]
Please fix and merge

**Pull request merged**
