### PR TITLE
bump dependency on code.cloudfoundry.org/copilot

### PR DESCRIPTION
**Pull request by zachgersh**
Just a periodic bump of Cloud Foundry copilot - we haven't updated since December

### CODE REVIEW

**Comment by rosenhouse** [comment]
This says merging is blocked because it needs "one approved review" but I see @kyessenov already said `/lgtm`.  What do we need to do?

**Comment by rkpagadala** [comment]
/approve
@rosenhouse @zachgersh fyi both lgtm and approve labels are required for automerge

**Comment by kyessenov** [comment]
I guess I am not an owner anymore?
lgtm used to approve automatically.

**Pull request merged**
