### PR TITLE
Broken productpage css and glyphicons fonts

### LINKED ISSUE #13244: Bookinfo CSS broken in master
Caused by https://github.com/istio/istio/commit/e9a94e4b4d5f44942d92d249d1647fa079c43815#diff-84a607622f5980c681c4c6ce0fe61c7d

The new ProductPage image serves .css files from /static instead of the https://ajax.googleapis.com/ location used in earlier Istio versions.

The _samples/bookinfo/networking/bookinfo-gateway.yaml_ does not include `/static` in the prefixes exposed.

Either the ProductPage must stop offering /static URLs or the gateway VirtualService must expose them.

cc @venilnoronha @yubingjiaocn

### PR DESCRIPTION
**Pull request by rvennam**
- Expose /static in the bookinfo-gateway.yaml VirtualService
- Add missing bootstrap fonts (glyphicons)
- Maintain the bootstrap directory structure
- Update index.html to use the local static assets as well
- Update Flask version to get fix for a known issue with serving static files

Fixes #13244

### CODE REVIEW

**Comment by rvennam** [comment]
cc: @yubingjiaocn

**Comment by vikramkhatri** [comment]
@frankbu - can you please review and approve this PR? We are seeing this defect on productpage where glyph icon is not displaying and this PR seems to fix this defect. Thanks.

**Comment by frankbu** [comment]
@rvennam To get this to pass the e2e tests, you need to rebuild the bookinfo images, push them to dockerhub, and update the yamls to use the newly pushed version of the images.

**Comment by rvennam** [comment]
@frankbu I was thinking I would rebuild the images and update yamls in another PR. Do you want it to be part of this one? 

Feels wrong to update docker hub images with code changes that haven’t been merged into the src repo

**Comment by frankbu** [comment]
@rvenum, I think there's no choice or the e2e is broken because of the incompatibilities between the config files here and the images that are running. Right?

**Comment by frankbu** [comment]
@rvennam please see comment I added in #13316

**Comment by rvennam** [comment]
@frankbu @vadimeisenbergibm 
New bookinfo images are built, pushed to docker hub and image tags in the yamls are updated in this PR

**Comment by frankbu** [comment]
hmm, any idea why the bookinfo tests are failing? Is there some kind of output format change happening?

**Pull request merged**
