### PR TITLE
Add resync period to namespace controller

### PR DESCRIPTION
**Pull request by howardjohn**
Attempt to mitigate https://github.com/istio/istio/issues/22463

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@howardjohn this takes no effect, resync only triggers OnUpdate callback

**Comment by howardjohn** [comment]
I see, thanks. We should probably still do this to be consistent though with the rest of pilot? What do you think?

**Comment by hzxuzhonghu** [comment]
I kind of think namespace is a different resource, which if added once, then it works. So this is actually a redundant ops.

**Comment by lei-tang** [comment]
This PR has been cherry picked into the 1.5 branch as #22773.

**Pull request merged**
