### PR TITLE
Add the ability to fail tests when using an Envoy deprecated feature

### PR DESCRIPTION
**Pull request by jwendell**
Through the flag `-istio.test.deprecation_failure`.

Currently it inspects proxy logs looking for deprecated
messages. This can be enhanced in the future to cover other
deprecations.

### CODE REVIEW

**Comment by jwendell** [comment]
Then we could have one or more CI jobs with that flag activated. Not marked as required in the beginning.

**Comment by howardjohn** [comment]
does envoy have any thing like metrics when depreciation things are used, fail instead of warning, etc that we could leverage instead of logs?

**Comment by ramaraochavali** [comment]
Yes. Envoy emits a stat of deprecated feature use https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime.html?highlight=runtime%20deprecated_feature_use#statistics

**Comment by howardjohn** [comment]
> Yes. Envoy emits a stat of deprecated feature use https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime.html?highlight=runtime%20deprecated_feature_use#statistics

I guess this doesn't indicate what features we used, so we still may need the logging, but maybe logging + this stat. Not sure.

**Comment by ramaraochavali** [comment]
I thought we just want to fail the test if there is deprecation usage - Do we need feature info as well?

**Comment by howardjohn** [comment]
Well we know we use a ton of deprecated features so I'm not sure failing is
useful since it will always fail?

**Comment by ramaraochavali** [comment]
Based on PR description,  I thought the intention was to fail when run with a flag. But you point is valid, it will always fail -  Was n' completely sure, what is the intention here though?

**Comment by jwendell** [comment]
I ran a few tests locally with that flag on, and had no failures. So, I'm not sure if we use tons of deprecated features or if they just don't show up on Envoy logs.

**Comment by howardjohn** [comment]
it's because of the log level, we set misc:error to hide them?

**Comment by jwendell** [comment]
Now I'm changing the Envoy log level when the CLI flag is used.
The intention with this PR is to cover https://github.com/istio/istio/issues/16275.

**Pull request merged**
