### PR TITLE
try to fix TestJobComplete flake

### LINKED ISSUE #15396: TestJobComplete flakes often
Example failures:

- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14614/istio-pilot-e2e-envoyv2-v1alpha3-master/3062
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14614/istio-pilot-multicluster-e2e-master/2355
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14614/istio-pilot-multicluster-e2e-master/2496
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14769/istio-pilot-e2e-envoyv2-v1alpha3-master/3058
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14821/istio-pilot-multicluster-e2e-master/2325
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14856/istio-pilot-multicluster-e2e-master/2319
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14904/istio-pilot-multicluster-e2e-master/2334
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14911/istio-pilot-e2e-envoyv2-v1alpha3-master/3075
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14911/istio-pilot-multicluster-e2e-master/2450
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14922/istio-pilot-multicluster-e2e-master/2343
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14944/istio-pilot-multicluster-e2e-master/2292
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/14985/istio-pilot-multicluster-e2e-master/2448
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15064/istio-pilot-multicluster-e2e-master/2311
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15110/istio-pilot-multicluster-e2e-master/2380
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15110/istio-pilot-multicluster-e2e-master/2381
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15136/istio-pilot-multicluster-e2e-master/2328
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15137/istio-pilot-multicluster-e2e-master/2363
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15138/istio-pilot-e2e-envoyv2-v1alpha3-master/2925
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15138/istio-pilot-multicluster-e2e-master/2347
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15139/istio-pilot-multicluster-e2e-master/2352
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15139/istio-pilot-multicluster-e2e-master/2364
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15147/istio-pilot-multicluster-e2e-master/2293
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15147/istio-pilot-multicluster-e2e-master/2294
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15160/istio-pilot-multicluster-e2e-master/2304
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15181/istio-pilot-multicluster-e2e-master/2338
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15181/istio-pilot-multicluster-e2e-master/2339
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15195/istio-pilot-multicluster-e2e-master/2356
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15202/istio-pilot-multicluster-e2e-master/2367
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15202/istio-pilot-multicluster-e2e-master/2384
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15202/istio-pilot-multicluster-e2e-master/2403
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15203/istio-pilot-multicluster-e2e-master/2405
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15223/istio-pilot-multicluster-e2e-master/2415
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15223/istio-pilot-multicluster-e2e-master/2467
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15223/istio-pilot-multicluster-e2e-master/2485
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15224/istio-pilot-multicluster-e2e-master/2428
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15227/istio-pilot-multicluster-e2e-master/2453
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15254/istio-pilot-multicluster-e2e-master/2449
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15262/istio-pilot-multicluster-e2e-master/2472
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15263/istio-pilot-multicluster-e2e-master/2480
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15278/istio-pilot-multicluster-e2e-master/2484
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15282/istio-pilot-multicluster-e2e-master/2486
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15284/istio-pilot-multicluster-e2e-master/2488
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15284/istio-pilot-multicluster-e2e-master/2489
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15297/istio-pilot-multicluster-e2e-master/2523
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15320/istio-pilot-multicluster-e2e-master/2545
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-e2e-envoyv2-v1alpha3-master/3246
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-multicluster-e2e-master/2558
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-multicluster-e2e-master/2572
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-multicluster-e2e-master/2582
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-multicluster-e2e-master/2588
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-multicluster-e2e-master/2595
- https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15343/istio-pilot-multicluster-e2e-master/2569
-

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Hope to fix #15396

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Let it in, and observe the ci for a long period.

**Comment by howardjohn** [comment]
Maybe better to put the curl in a loop? This should be an example of how users can use this as well, probably best not to just sleep 15s. BTW you can see in the logs the reason for the failure: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15336/istio-pilot-e2e-envoyv2-v1alpha3-master/3246/artifacts/pilot-test-3a9744106b4b4aed8ce0567ac5/test-job-jfx76_container:test.log

**Comment by hzxuzhonghu** [comment]
Thanks @howardjohn , i have seen the log, makes curl in a loop sounds good

**Comment by duderino** [comment]
@geeknoid how hard would it be to prevent self-merges like this? 

I'm not sure if @hzxuzhonghu realized that adding a lgtm label would result in a self-merge, but seems like the merge bot should ignore labels added by the user that created the PR.

**Comment by geeknoid** [comment]
@duderino This  will become impossible when we switch this repo to Mergify.

**Comment by hzxuzhonghu** [comment]
I know that @duderino , as this is just a flake fix, just want it in soon, and observe if this really fix the problem.

**Comment by fpesce** [comment]
@hzxuzhonghu self-lgtm'ing to force merge is never OK. Please don't do it.
If you're needing an exception, please reach out to release managers (for release branch) or member of TOC (admin).

**Comment by hzxuzhonghu** [comment]
IC， would follow the rule

**Pull request merged**
