### PR TITLE
Fix debug assert due to missing start time

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I did not add the StartTime because i am not sure if it can cause assert failure

**Comment by howardjohn** [comment]
> I did not add the StartTime because i am not sure if it can cause assert failure

I did not think it can, its exactly the same as a XDS request?

If it does we have a test now :slightly_smiling_face:

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
