### PR TITLE
[Testing] Default all tests to presubmit unless postsubmit specified

### PR DESCRIPTION
**Pull request by nmittler**
Also adding a new label "flaky" used to denote that a test is unstable. Flaky tests are not included in pre or post submit.

### CODE REVIEW

**Comment by nmittler** [comment]
@ozevren I didn't see where the postsubmit task is set up.  Can you point me to it?

**Comment by howardjohn** [comment]
The test take really long on circle CI. I think if we want to do this we need to split the target up so we can run multiple tests in parallel. or we can just use prow and make it required, prow finished in 1h24m circle is still running at 1hr50min. We will block everything with circle if we have this test running for 2+ hours each PR, especially since the tests aren't cancelled when new changes come in, etc.

**Comment by nmittler** [comment]
@howardjohn Agreed ... we'll need to address the time issue before this lands.

One big issue on k8s is the setup/teardown of the environment. We can probably start by reducing the number of test suites, so that we run more tests against the same Istio environment.

cc @ozevren @duderino

**Comment by howardjohn** [comment]
I am doing some work to allow running only tests that don't require special setup (tracking under https://github.com/istio/istio/issues/13765) since this is what we want to test the new installer. May be somewhat related

**Comment by ozevren** [comment]
/lgtm
/approve

We should aggressively tackle the current flaky tests once this lands.

**Comment by howardjohn** [comment]
I think we should address the time issue before this merges @ozevren @nmittler.

I thought the CircleCI one was a required test, but it doesn't appear to be. So what does this change really do? We have always ran all of the tests in prow, so now we just run them in prow and circle but neither is required?

**Comment by howardjohn** [comment]
/hold
CircleCI is still running 2h40min in, it just isn't feasible to run all of these in circle

**Comment by ozevren** [comment]
We really should split the tests into their own jobs, ala e2e tests.

**Comment by nmittler** [comment]
@howardjohn @ozevren I've got a start at refactoring tests to share istio environments: https://github.com/istio/istio/pull/13793

**Comment by nmittler** [comment]
@howardjohn @ozevren also FYI Circle took 3 hours and 6 minutes to complete the test ... we have some work to do :)

**Comment by ozevren** [comment]
Is this PR still relevant? There are Galley changes here.

**Comment by nmittler** [comment]
no I don't think it is ... closing.

**Pull request closed without merging**
