### PR TITLE
Remove Ansible as it is unmaintained

### PR DESCRIPTION
**Pull request by sdake**
In the future if individuals wish to maintain Ansible installation,
that would be fine. The environments WG sees the role of Ansible to
handle mesh expansion automation.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
/lgtm /approve

I'll close https://github.com/istio/istio/pull/15437 for this one

**Comment by gbaufake** [comment]
@sdake 
I wish I could still maintain it, but I was told the work on https://github.com/istio/operator will be deprecating the ansible installer on near future.

**Comment by sdake** [comment]
Note to all, I force merged this PR at a later hour to determine how the workflow works with force merging with the github UI for release manager work for 1.3.  I thought it better to do while the project wasn't heavily active, versus when the release 1.3 force merge work needs to be done.

Cheers
-steve

**Comment by fpesce** [comment]
@sdake please, try to not force merge anything on master, it's already too relaxed in regards to tests to allow any force merge.
As release manager on 1.2, I only merged things on 1.2, master should be outside of the scope of a RM merge power, if there was one exception to be made, it would be for older code from older branch that has not yet been cherry-picked to master but should be before 1.3 freeze/cut: but this is no more of a problem, as master has been the source of truth since end of 1.1 and early days of 1.2, so everything in master should be there.

**Comment by sdake** [comment]
@fpesce yes I understand, force merges irritate me as well.  AFAIK @geeknoid is sorting out a mechnaism to remove force merge as a capability from everyone except a selecct few for escape hatch purposes.

FWIW I force merged this at midnight as I didn't think it would have much impact on the project in that timeframe and wanted to test out the force merge workflow in prep for release management of the 1.3 branch.

Cheers
-steve

**Pull request merged**
