### PR TITLE
Update zipkin deployment

### PR DESCRIPTION
**Pull request by howardjohn**
The image used is quite old. In updating, I found a number of issues
impacting startup speed. We have a delay of 200s to the readiness probe,
so we will never startup in less than 200s. Additionally, because the
CPU limit is so small, startup takes 50s, vs 5s now that the limit is
bumped up a little bit. Memory is also raised, as this is a JVM
appliction so it uses a lot of memory, and has often been OOMKilled in
my tests.

Additionally, I cleaned up a TODO in the tests so that the correct
OWNERS get assigned here.

### CODE REVIEW

**Comment by howardjohn** [comment]
This brings telemetry tests from 28min -> 18min

**Review by richardwxn — APPROVED** [review]

**Review by elfinhe — APPROVED** [review]
Lgtm

**Review by bianpengyuan — APPROVED** [review]
Slim `doesn't support messaging transports like Kafka or RabbitMQ`, which should be fine considering we don't include those use cases in Istio guide, and user should have their own zipkin deployment setup if they use zipkin that way.

**Comment by howardjohn** [comment]
> Slim doesn't support messaging transports like Kafka or RabbitMQ, which should be fine considering we don't include those use cases in Istio guide, and user should have their own zipkin deployment setup if they use zipkin that way.

Yeah sorry forgot to mention this in the PR description, that was my thought as well.

**Comment by howardjohn** [comment]
Or they can also `--set` override it if they care

**Pull request merged**
