### PR TITLE
Implementation to enable TCP keepalive configuration.

### PR DESCRIPTION
**Pull request by shakti-das**
This is the implementation for API PR https://github.com/istio/api/pull/718. Corresponding Issue #9378.

Signed-off-by: Shakti shaktiprakash.das@salesforce.com

### CODE REVIEW

**Comment by shakti-das** [comment]
@hklai @rshriram I rebased the changes. I would really appreciate if it gets merged. Thanks.

**Comment by rshriram** [comment]
I am confused. what was the other PR I merged? it too had the same code..

**Comment by shakti-das** [comment]
Thanks @rshriram

**Pull request merged**
