### PR TITLE
Add priority class to istio gateway chart

### PR DESCRIPTION
**Pull request by 4c74356b41**
Add priority class to istio gateway chart

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by 4c74356b41** [comment]
validated this is working with:
```
helm template . --set priorityClassName=test | k apply -f - --dry-run=client
serviceaccount/release-name created (dry run)
role.rbac.authorization.k8s.io/release-name created (dry run)
rolebinding.rbac.authorization.k8s.io/release-name created (dry run)
service/release-name created (dry run)
deployment.apps/release-name created (dry run)
horizontalpodautoscaler.autoscaling/release-name created (dry run)
```

**Review by howardjohn — COMMENTED** [review]
Can you describe a bit the use case, how its generally applicable, and if why/if https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/ works as an alternative?

**Comment by 4c74356b41** [comment]
the use case is - setting a Priority Class for gateway pods. Similar to how this is possible with istiod: https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L74

Yes, you can fix it with Kustomize, but I dont see any reason why such an important\basic property should be omitted from the chart

**Comment by 4c74356b41** [comment]
I'd never seen anybody argue something as important and as basic as priorityClass is not important to everybody. why is it in istiod chart then?

**Comment by 4c74356b41** [comment]
and in the other gateway charts? https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml#L201

but not in the one thats actually being used?

**Comment by 4c74356b41** [comment]
@costinm @Monkeyanator @jacob-delgado please review this PR

**Review by howardjohn — CHANGES_REQUESTED** [review]
https://github.com/istio/istio/pull/41200#issuecomment-1260963496

**Comment by brainfair** [comment]
@howardjohn the option to set the class priority for critical infrastructure components is very useful.
I support that this should be available by default in the base chart, especially since it was in the old chart

**Comment by sylus** [comment]
Can we re-open this ticket and merge the M.R.?

We need to set a priorityClass to all of our critical components of which Istio Ingress Gateway is one.

We use Argo CD with Helm so this is an important requirement for us and priorityClass is one of the default standards that should be in most Helm templates by default.

**Comment by sylus** [comment]
@howardjohn I don't suppose you might be able to re-open this if possible?

I apologize for the direct ping.

**Pull request closed without merging**
