### PR TITLE
docs: add samples for the route directive demo

### PR DESCRIPTION
**Pull request by kyessenov**
Two large sample YAMLs that are better packaged as samples for the release documentation.
Source: https://github.com/istio/istio/pull/12505

/assign @geeknoid 

@duderino This is purely a documentation change.

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
Doc PR https://github.com/istio/istio/pull/12524

**Comment by geeknoid** [comment]
/lgtm
/approve

@duderino Let's merge this for the sake of the docs.

**Comment by kyessenov** [comment]
@rshriram @wenchenglu or anyone else with admin rights.

**Comment by duderino** [comment]
Yeah that's fine

**Pull request merged**
