### PR TITLE
Add milliseconds duration to dashboard

### LINKED ISSUE #16799: V2 telemetry emits durations in `millis` instead of `seconds`
V2 telemetry in 1.3.0.rc1 emits latency numbers in `milliseconds`.
Mixer telemetry emits them in `secods`, which is what the dashboard assumes.

Update the dashboard so that it works both with the `istio_requests_duration` and `envoy_requests_duration_seconds` and scales `envoy_requests_duration_seconds` by `/1000.0`

### PR DESCRIPTION
**Pull request by bianpengyuan**
fixes #16799

mesh: https://snapshot.raintank.io/dashboard/snapshot/3J0i1zMhKRr54iQWchmR7SDnJIq6MJrc
workload: https://snapshot.raintank.io/dashboard/snapshot/gpmaOtGDrxeD63bKUEnSXL9bKg8gGknp
service: https://snapshot.raintank.io/dashboard/snapshot/x29FrzqKkEkNltjGQ09n7U3rsD040W6c

### CODE REVIEW

**Comment by bianpengyuan** [comment]
I will also send a same pr to installer.

**Comment by bianpengyuan** [comment]
Installer PR: https://github.com/istio/installer/pull/380

**Comment by bianpengyuan** [comment]
After proxy SHA update PR: https://github.com/istio/istio/pull/16861 we could update dashboard test to also verify milliseconds metric.

**Comment by bianpengyuan** [comment]
The test failure is actually because of some bad change. Dashboard test should pass now.

**Review by douglas-reid — APPROVED** [review]
/lgtm

**Comment by bianpengyuan** [comment]
@istio/wg-environments-maintainers Ping, please help to take a look at this. Thanks!

**Review by ayj — APPROVED** [review]

**Pull request merged**
