### PR TITLE
[release-1.3] upgrade istio/proxy to 47e4559b8e4f0d516c0d17b233d127a3deb3d7ce (#16248)

### PR DESCRIPTION
**Pull request by crazyxy**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
@crazyxy you can add the cherrypick label or `/cherrypick release-1.3` in the future

**Comment by rlenglet** [comment]
@crazyxy Please add the link to the original master PR in master into this PR's description. I need to see whether there are any differences, and who approved it.

**Comment by rlenglet** [comment]
Putting this on hold until we can see the original master PR.

**Comment by rlenglet** [comment]
@crazyxy The `cherrypick/release-1.3` label needs to be set on the original PR against master.

**Comment by crazyxy** [comment]
https://github.com/istio/istio/pull/16248

**Pull request merged**
