### PR TITLE
[release-1.11] revert /host prefix from CNI log volume mount path. (#36038)

### PR DESCRIPTION
**Pull request by johnma14**
(cherry picked from commit 8dcf53141d6d50efef56da1506b3d1076a93450a)

 Fixes: #35902

### CODE REVIEW

**Comment by johnma14** [comment]
@bianpengyuan not sure if I did this cherry pick correctly. Can you help verify. Thanks.

**Review by bianpengyuan — COMMENTED** [review]
Looks like no file changes. I think you will need to cherry-pick the securityContext change first, then add this commit on top of that.

**Comment by johnma14** [comment]
Done @bianpengyuan. That actually worked. Thank you for the pointer.

**Review by bianpengyuan — APPROVED** [review]

**Comment by johnma14** [comment]
Adding a little context to help with reviewing. 

We first made this change #35986 to fix the issue with the CNI plugin not starting for non-root users. In that PR, we also made an additional change to change the mountPath for the logUDSPath. We had to revert that specific change in another PR [#36038], since it was breaking the logging feature. So I manually cherry picked the commit id for both these PR's and you can see that it removed the changes related to the mountPath. Hope that helps. Thanks for the review.

**Review by jwendell — APPROVED** [review]

**Pull request merged**
