### PR TITLE
use 1s refresh delay and connect timeout

### PR DESCRIPTION
**Pull request by rshriram**
**What this PR does / why we need it**:
same as what we used in 0.1.6. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kyessenov** [comment]
We did not use 10ms delay in 0.1.x. I'm not sure about the implications of extremely short update durations.

**Comment by kyessenov** [comment]
Sorry, disregard. Was looking at email, not the updated PR.

**Comment by rshriram** [comment]
yeah.. I set it to 1s after looking at 0.1.7 values..

**Comment by rshriram** [comment]
my hunch was not correct. So, no point changing this.

**Pull request closed without merging**
