### PR TITLE
[release] Update release procedure doc with update_rel_branches flag

### PR DESCRIPTION
**Pull request by chxchx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by chxchx** [comment]
Could you guys LGTM again? I fixed a typo.

**Comment by yutongz** [comment]
OK, it rerun tests twice because there was new change into master during the first rerun. Good job @istio-merge-robot

**Pull request merged**
