### PR TITLE
Adapt to the change in DestinationRule api

### PR DESCRIPTION
**Pull request by kentchenjh**

### CODE REVIEW

**Comment by kentchenjh** [comment]
https://github.com/istio/api/issues/1269
https://github.com/istio/api/pull/1285

**Comment by kentchenjh** [comment]
@rshriram maybe merge istio/api#1285 first, the test cannot pass since `cannot use cookie.GetTtl() (type *time.Duration) as type *types.Duration in argument to gogo.DurationToProtoDuration`

**Comment by rshriram** [comment]
you have to add the api change to your PR (go mod ..).

**Comment by kentchenjh** [comment]
ok. will commit this change soon.

**Comment by hzxuzhonghu** [comment]
@kentchenjh you also need to change the validation part, and maybe you need to run make gen as well

**Pull request merged**
