### PR TITLE
Clean up the mixer/test directory

### PR DESCRIPTION
**Pull request by geeknoid**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by geeknoid** [comment]
@ayj @andraxylia @guptasu @ldemailly 

This is currently claiming a build failure and tells me to run scripts/generate-protos.sh to fix it. Several issues:

- My build worked fine locally. I've now wasted time because of generate protos not being up to date.

- There is no scripts/generate-protos.sh. It's bin/generate-protos.sh

- Running bin/generate-protos.sh on my Mac results in:

~/go/src/istio.io/istio$ bin/generate-protos.sh 
INFO: Found 416 targets...
ERROR: missing input file '//pilot/platform/kube:config'.
ERROR: /Users/mtail/go/src/istio.io/istio/pilot/platform/kube/BUILD:34:1: //pilot/platform/kube:kubeconfig: missing input file '//pilot/platform/kube:config'.
ERROR: /Users/mtail/go/src/istio.io/istio/pilot/platform/kube/BUILD:34:1 1 input file(s) do not exist.

So at this point, I can't check in this change due to proto non-sense.

**Comment by geeknoid** [comment]
Kuat helped me figure out why the script was failing... Maybe I'll be able to commit my changes now.

**Comment by guptasu** [comment]
@geeknoid what was the reason for the `scripts/generate-protos.sh` failing for your PR ? Was it the out of date error message since @kyessenov, I suppose, has renamed the file ?

**Comment by ayj** [comment]
`script/generate-protos.sh` was failing because I invoked it too late in the presubmit script after some other builds and tests ran and generated their own intermediate output files.

**Comment by guptasu** [comment]
@ayj I see, so fixed now ?

**Comment by ayj** [comment]
It's fixed in the sense that I commented out the call to `scripts/generate-proto.sh` and corresponding `git status` check to unblock PRs over the holiday weekend. @jmuk seems to be hitting a similar issue with his PR to verify formatting/buildifier (see https://github.com/istio/istio/pull/1818)

**Comment by ldemailly** [comment]
can we put back the check now ?

**Pull request merged**
