### PR TITLE
Remove bad sample

### PR DESCRIPTION
**Pull request by frankbu**
**Please provide a description of this PR:**

Remove sample because it doesn't work on Mac or Windows, it only works on Linux.

### CODE REVIEW

**Comment by zirain** [comment]
this sample is very useful for local development, can you keep them but add some warning message?

**Comment by litong01** [comment]
I use it everyday for my dev and test. I think it is very useful. I do not mind at all to add some warnings if detected in non Linux env.

**Comment by frankbu** [comment]
@litong Can you send a PR to add another prereq check in the script to make sure it's running on a platform that will work, and also add a warning in the README? I'm not sure it belongs in samples/ anyway, maybe better to move somewhere else (e.g., istio-ecosystem), but for now let's at least make sure that people don't run it on Mac or Windows just to find out later it isn't working when they try to use it.

**Comment by frankbu** [comment]
We could also add something in the wiki about it, but the script, itself, still needs to live somewhere. I guess leaving it in samples is probably best, since it's there already :-)

**Comment by frankbu** [comment]
Closing in favour of #38181

**Comment by craigbox** [comment]
Just to check: _why_ doesn't this work on Mac or Windows?  `kind` is available there, is it `metallb` that's the problem?  I've seen a few posts talking about workarounds: https://www.thehumblelab.com/kind-and-metallb-on-mac/, for example

**Pull request closed without merging**
