### PR TITLE
Remove VALIDATION_ENABLED env

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
We should enforce crd validation, otherwise there maybe unknown error.

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
I think there are use cases where we do not want the webhook patcher to run - possible external Istiod? @costinm ?

**Comment by hzxuzhonghu** [comment]
For external istiod,  it should be no diff from local mode unless i missed something. @costinm Need your comments

**Comment by SpecialYang** [comment]
We use some invalid crd format for convenience. For example, we allow https field of VirtualService can be zero, which will be denied by istiod if the validation switch is opening. 

Now we upgrade istiod from 1.8 to 1.12. But, this upgrade process is blocked by this enforce policy.

Is there a alternative way to fix my case?

**Comment by hzxuzhonghu** [comment]
You can delete the validatingwebhookconfiguration `istio-validator-istio-system`

**Pull request merged**
