### PR TITLE
avoid calling servicesForNamespacedName for headless services

### PR DESCRIPTION
**Pull request by ramaraochavali**
- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
is there any test we should have to cover this case?

**Comment by ramaraochavali** [comment]
> Actually, do we need some logic to detect that smething actually changed? Worry about excessive NDS pushes

I am also worried about  that - but not sure what can we do/check when endpoint update comes?

**Comment by howardjohn** [comment]
> > Actually, do we need some logic to detect that smething actually changed? Worry about excessive NDS pushes
> 
> I am also worried about that - but not sure what can we do/check when endpoint update comes?

Not sure ,but its pretty concerning that this makes a push to 1 endpoint push the full NDS (which is for all services). I think this may be a major performance regression

**Comment by ramaraochavali** [comment]
I have put a hold on it. Let us see if we can find some better solution.

**Comment by ramaraochavali** [comment]
I have verified again and not able to reproduce the problem. May be some inconsistent Istiod state. Looking further in the code, we are actually doing a full push for headless services https://github.com/istio/istio/blob/2b39b30c7f69efdf2421482662540455a37584b9/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go#L68 - So this should take care.

I just added few comments and moved condition above. @howardjohn  PTAL. If it looks good, please remove DNM label.

**Review by hzxuzhonghu — APPROVED** [review]
LG

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
