### PR TITLE
Place istio/istio on BUILD_WITH_CONTAINER=1 plan

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by howardjohn** [comment]
I think this may be a blocker https://github.com/istio/istio/issues/19943

**Comment by ericvn** [comment]
While I'm all for the change and @sdake being around for changes (as well as some others), I'm thinking there were a few blockers before the holidays.

**Comment by ericvn** [comment]
First problem is that `make init` still gets the linux envoy into the darwin folder on Mac:

```
file envoy
envoy: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

**Comment by ericvn** [comment]
Also, should `make clean` remove the `out\linux_amd64` directory on a Mac?

Aside, I will create issues for this and prior remark if we just want to merge this PR.

**Comment by ericvn** [comment]
If I wanted to start getting nit-picky I would but the `build-linux` dependency on `docker` and not `build` for non-linux machines. Not sure why I want to build the linux executables on my Mac unless I'm making Docker images? ie. `make clean build` generates the linux images on my Mac when it shouldn't.

**Comment by ericvn** [comment]
Found another issue with `BUILD_WITH_CONTAINER=1 make istioctl.completion` when using MacOS. It will fail since it will build the Mac version of the istioctl binary and then try to use that to generate the completion files. Obviously, using the Mac version of the istioctl binary doesn't work in the container.

**Comment by sdake** [comment]
@ericvn after you finish up your Mac support work, I'd like to get this PR merged. This will permit the community to fix areas in which they are SMEs. I am struggling to resolve on of the integration test cases `test.integration.pilot.local`and could use @nmittler's help on this particular test case.

Cheers
-steve

**Comment by sdake** [comment]
@howardjohn I think now is a good time to merge this if you would oblige.

Thanks
-steve

**Pull request merged**
