### PR TITLE
Add perf WG to GROUPS.md (on hold)

### PR DESCRIPTION
**Pull request by ldemailly**
tentative based on steering committee's blessing
```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
@ZackButcher I was waiting for the reviewers I set (martin or sven) to clear this (steering committee notes seems be ok but I want to make sure)

**Comment by ZackButcher** [comment]
Turns out I don't have owners anyway ;). I figured it was fine given we've talked about the WG before (I was surprised an entry didn't exist already).

**Comment by geeknoid** [comment]
There is strong belief that we want the perf & scalability working group, but as was mentioned in the steering group meeting notes, we'd like to try out the "adding a new workgroup" process using this perf working group.

So first step will be to define the "adding a new workgroup" process. I'm going to be writing this process down in the next few days, then we'll iterate on this for a bit and make it the POR. Then we should come back to this PR.

So can you park this for a little while?

**Comment by ldemailly** [comment]
Sure, as long as it's complete before next wednesday (next perf WG meeting) that sounds good, thanks

**Comment by ldemailly** [comment]
doc moved https://github.com/istio/community/pull/8

**Pull request closed without merging**
