### PR TITLE
[Test Framework] Fix duplicate echo workloads

### LINKED ISSUE #30880: TestRevisionedUpgrade test flake
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1361869884937474048

cc @Monkeyanator

### PR DESCRIPTION
**Pull request by nmittler**
Fixes #30880

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by Monkeyanator — APPROVED** [review]

**Comment by howardjohn** [comment]
@nmittler @Monkeyanator the test is still failing

**Comment by nmittler** [comment]
@howardjohn yeah, still actively debugging

**Comment by nmittler** [comment]
Closing since the original PR was reverted.

**Pull request closed without merging**
