### PR TITLE
Fixing wrong message level mapping in validationMessages

### PR DESCRIPTION
**Pull request by xeviknal**
Fixes https://github.com/istio/istio/issues/29445
Relates to https://github.com/kiali/kiali/issues/3505

The severity level for the `validationMessages` in the status field are not present.
It looks like the mapping from Message descriptor the the message object was wrong (needs to be uppercased).

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
LGTM but I would hope a test changed in response to this - do we not have coverage?

**Comment by xeviknal** [comment]
@howardjohn added the test covering this method output specifically. Thanks!

**Review by howardjohn — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
