### PR TITLE
remove service resource handling

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

See https://github.com/istio/ztunnel/pull/659, ztunnel only request for workload address now

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
? Weird... Where does envoy use it

**Comment by kyessenov** [comment]
Yes, it's used [here](https://github.com/istio/proxy/blob/master/source/extensions/common/workload_discovery/discovery.proto). It's important to keep multiple xDS clients since once it's not data plane independent, it's no longer xDS.

**Comment by hzxuzhonghu** [comment]
Add as we need, otherwise confusing to me

**Pull request merged**
