### PR TITLE
cleanup tunneling code

### PR DESCRIPTION
**Pull request by ramaraochavali**
Cleans up some of the tunneling code which is not used.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by GregHanson — DISMISSED** [review]

**Review by jewertow — APPROVED** [review]
LGTM

**Review by howardjohn — COMMENTED** [review]
Oops got this mixed up originally. This is a continuation of https://github.com/istio/istio/pull/39488. LGTM

thanks

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
gencheck fix is incoming as part of another PR. Once that merges, we can rerun the test here.

**Pull request merged**
