### PR TITLE
Add linter test for prow

### PR DESCRIPTION
**Pull request by howardjohn**
I tested this on the prow-staging branch and it passed, see https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14934/istio-lint-master/10

Execution time is 1min faster than circle (sample size: 1)

Will add to test-infra after this merges so that we don't have tests blocked by it: https://github.com/istio/istio/pull/14934

### CODE REVIEW

**Comment by howardjohn** [comment]
The circle lint failing here is fitting :slightly_smiling_face:

**Comment by icygalz** [comment]
tide will not able to merge this PR as long when circleci:lint test is failing. We need to change the infra to make circleci: lint non-blocking.

otherwise,
/lgtm 
/approve

**Comment by howardjohn** [comment]
@icygalz lets run the prow lint for at least a few PRs to make sure it works ok. I checked in https://github.com/istio/test-infra/pull/1345 as non-required just in case there are some issues (a bit scared since last time it had some, but I think I had the wrong junit file is all).

**Comment by fpesce** [comment]
Going to override the circleci:lint fail here.

**Comment by icygalz** [comment]
Please make circleci: lint as non-required in the test-infra PR... If not,
it would block everybody..

**Pull request merged**
