### PR TITLE
switch stable download to 1.0.5 (from 1.0.2)

### PR DESCRIPTION
**Pull request by shalk**
switch stable download to 1.0.5 (from 1.0.2)

### CODE REVIEW

**Comment by shalk** [comment]
for CLA
I signed it!

**Comment by geeknoid** [comment]
@mjog @hklai 

In master, this version is set to 1.0.2. In the release-1.0 branch, this is currently set to 0.8.0. Is this script actually useful given that it's so out of date in the release-1.0 branch? Should we delete the script?

If we need to keep this script, then updating this version needs to be part of the todo list when we make a new release.

**Comment by hklai** [comment]
@geeknoid yeah I don't see why we need this when we already have https://github.com/istio/istio/blob/master/release/downloadIstioCandidate.sh, which can find the latest release version.

**Comment by geeknoid** [comment]
OK, we're deleting this file, so I'm going to close this PR.

**Pull request closed without merging**
