### PR TITLE
Support mounting volumes to gateway via Helm chart

### PR DESCRIPTION
**Pull request by maxhov**
**Please provide a description of this PR:**
This PR enables the mounting of volumes to a gateway via the Helm chart 'istio/gateway'. Mounting a volume is for instance necessary to supply the needed tokens for the oauth2 filter, such as described in issue #36999

### CODE REVIEW

**Comment by maxhov** [comment]
Not sure how to fix the issue with gencheck_istio. Seems like the makefile in common is having an issue, but the build output does not show what it is. Ran the helm lint check locally, but gave no issues.

**Comment by zirain** [comment]
> Not sure how to fix the issue with gencheck_istio. Seems like the makefile in common is having an issue, but the build output does not show what it is. Ran the helm lint check locally, but gave no issues.

do your run `make gen` local

**Comment by ristox1** [comment]
I'm facing the same issue and thus I'm "bumping" this issue to be reopened if possible :)

> **Please provide a description of this PR:** This PR enables the mounting of volumes to a gateway via the Helm chart 'istio/gateway'. Mounting a volume is for instance necessary to supply the needed tokens for the oauth2 filter, such as described in issue #36999

**Pull request closed without merging**
