### PR TITLE
Move envoy test utils to pkg/test

### PR DESCRIPTION
**Pull request by m1093782566**
It's a sub-PR of #8715. I am doing this for the sake of making #8715 simpler and easier to review.

### CODE REVIEW

**Comment by m1093782566** [comment]
/assign @nmittler @ozevren 

for review :)

**Comment by nmittler** [comment]
@m1093782566 I think you really only want to move `envoy.go` and `admin_util.go`.

**Comment by m1093782566** [comment]
@nmittler 

I just pushed an update, PTAL.

**Comment by m1093782566** [comment]
@nmittler @ozevren 

I think this PR is ready to get in.

**Pull request merged**
