### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ipedrazas**
Clean up instruction has a typo which makes the clean up fail.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by frankbu** [comment]
`kubectl delete` should work equally well using the unmodified version of the yaml file (`helloworld.yaml`). What kind of cleanup failure did you observe?

**Comment by ipedrazas** [comment]
You're right. I'm not sure what happened this morning, but I was following the steps and it gave an error (not finding resources) and then it worked with the modified version.

**Comment by ldemailly** [comment]
ok so closing this as there is no such file as helloworld-istio.yaml

**Comment by frankbu** [comment]
@ldemailly there is a file named helloworld-istio.yaml, if you follow the instructions in the README, but the bottom line is that the instructions are fine as they are, so this issue should be closed.

**Comment by ldemailly** [comment]
oh searched failed me - I just looked at the directory, not the file content

**Pull request merged**
