### PR TITLE
Fix data race between LDS and CDS

### PR DESCRIPTION
**Pull request by rshriram**
BuildListeners does an in inplace sort operation on a services array that happens to be shared across multiple concurrent push operations. This leads to potential data races, where one thread is iterating over the array in buildClusters for CDS, while another is sorting the array in buildListeners for LDS, leading to situations where the CDS output misses clusters that should otherwise have been there.

This is probably the cause of missing clusters issue that @mandarjog found while debugging issues reported by @markns . This could also potentially contribute to reducing proxy startup times.

Moved the sort operation to push context initialization as a solution.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by mandarjog** [comment]
Resolves #8083

**Comment by kyessenov** [comment]
Would be nice to add a regression test. Not at all clear where deletion happens due to re-ordering of operations.

**Comment by kyessenov** [comment]
A race test that invokes CDS and LDS should be effective here, right?

**Comment by rshriram** [comment]
please show me sample code to use.

**Comment by kyessenov** [comment]
@rshriram Filed issue #8090 for a more systematic solution.

**Comment by andraxylia** [comment]
I do not see how this solves deterministically data races, though it may reduce their likelihood. We need a design of the current data structures used for serving to Envoy, with proper separation and/or locking where needed.

**Pull request merged**
