### PR TITLE
[WIP] Merge multiple metric endpoints

### PR DESCRIPTION
**Pull request by xvzf**
Signed-off-by: Matthias Riegler <matthias.riegler@taotesting.com>

**Please provide a description of this PR:**
This PR enables the istio sidecar to scrape multiple metric endpoints and merge those.
This is useful when there is more than one container deployed next to the sidecar, e.g.:
- Istio Proxy
- Application (serving metrics)
- Database Proxy (serving metrics)

It is not intended to have breaking changes but extends the existing functionality to provide an additional Pod annotation which is JSON encoded, e.g.:

```yaml
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"
  prometheus.io/additional: '[ {"port": "9010", path: "/metrics"} ]'
```

There are no test-cases yet as I am looking for review if this is a wanted feature or not.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by howardjohn** [comment]
Is this a novel feature for Istio, or something possible with Prometheus today without Istio?

**Comment by xvzf** [comment]
@howardjohn This would be a novel feature for Istio. With prometheus you can make it work in a tricky way but with the Istio metric merging feature it would be a very clean solution. An issue on the Prometheus project discussing it: https://github.com/prometheus/prometheus/issues/3756.

**Comment by xvzf** [comment]
@howardjohn How should I proceed with this PR / feature addition?

**Comment by georgiiturevich-uw** [comment]
This feature would be usefull as it allows to scrape metrics from multiple containers inside a pod without injecting an Istio sidecar to Prometheus pods. My colleague reported the issue here https://github.com/istio/istio/issues/41276

I am interested to invest some time for helping to complete this PR.

**Comment by suxiaoxiaomm** [comment]
Hi, 
Has this change merged yet? 
Anyone know does istio support multiple scraping ports for one pod now?  Which version it is?

**Pull request closed without merging**
