### PR TITLE
virtualservice set default delegate namespace to root's

### LINKED ISSUE #33251: Delegate virtualservice without specified namespace is invalid
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-delegate
  namespace: default
spec:
  http:
  - route:
    - destination:
        host: productpage
        port:
          number: 9080
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example
  namespace: default
spec:
  hosts:
  - "example"
  http:
  - delegate:
      name: example-delegate
```

This VirtualService is invalid and no rules pushed to envoy if deletegate's namespace is empty.

Then it's valid after i specified delegate namespace to default.

But from this document: https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate

> Namespace specifies the namespace where the delegate VirtualService resides. By default, it is same to the root’s.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (5 proxies)

I update istiod to 1.10 and the problem also happens.

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

### PR DESCRIPTION
**Pull request by fatedier**
Fix #33251

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
The delegate ns must not be different from root

**Comment by fatedier** [comment]
> The delegate ns must not be different from root

What's the problem if delegate ns isn't same with root?

I test with https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate and it works.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-delegate
  namespace: foo
spec:
  http:
  - route:
    - destination:
        host: productpage
        port:
          number: 9080
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example
  namespace: default
spec:
  hosts:
  - "example"
  http:
  - delegate:
      name: example-delegate
      namespace: foo
```

And this PR is aim to set default delegate ns to root's. I'm not sure what's the problem.

**Comment by hzxuzhonghu** [comment]
It is intended, just like a `service` must reside in same namespace as `endpoints`

**Comment by fatedier** [comment]
> It is intended, just like a `service` must reside in same namespace as `endpoints`

@hzxuzhonghu Your idea is really different with current design. Maybe some users already use this feature, it will break their usage.

Is there any problem now?  I think it's useful to forward requests to services in different namespace by path.

And it seems not releated to this PR? This PR sets the delegate default ns to root's. Maybe we'd better create another issue to describe your proposal.

**Comment by hzxuzhonghu** [comment]
Sorry, i was totally misunderstood.

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
