### PR TITLE
workloadInstancesByIP add RClock

### PR DESCRIPTION
**Pull request by andrewshaoyu**
Signed-off-by: shaoy <andrew.shaoyu@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

fix fatal error: concurrent map read and map write

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
is this fixing a bug?

**Review by hzxuzhonghu — APPROVED** [review]
/ok-to-test

good catch

**Comment by andrewshaoyu** [comment]
how to add label  ```release-notes-none``` to ignore the test. If this pull request has no user facing changes, please add the release-notes-none label to the pull request. Note that the test will have to be manually retriggered after adding the label.

**Comment by andrewshaoyu** [comment]
@hzxuzhonghu how to solve ```release-notes_istio``` error, i have no idea

**Pull request merged**
