### PR TITLE
do not run gateway secret fetcher for file mounted certs [cherry pick of 26978]

### PR DESCRIPTION
**Pull request by ramaraochavali**
Manual cherry pick of https://github.com/istio/istio/pull/26978

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
Can you provide a release note for this?

**Comment by ramaraochavali** [comment]
@jwendell added release notes

**Review by jwendell — APPROVED** [review]

**Pull request merged**
