### PR TITLE
Include js/css files into static folder

### PR DESCRIPTION
**Pull request by clyang82**
Some private cloud environments, they cannot have internet accessed and cannot download required js/css from internet so that the ctrlz page is abnormal.

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by geeknoid** [comment]
Could you name the files with the version number of the imported content? This'll make it possible to understand what's what in the future.

Thanks.

**Comment by clyang82** [comment]
> Could you name the files with the version number of the imported content? This'll make it possible to understand what's what in the future.
> 
> Thanks.

@geeknoid Done. Thanks for your comment.

**Comment by geeknoid** [comment]
Thanks. When I have a few moments, I'll update this code to remove all these dependencies. I originally created the ControlZ stuff by cloning what I had done for istio.io. Since then, I've improve istio.io quite . bit, including removing all these expensive dependencies... 

/lgtm
/approve

**Comment by clyang82** [comment]
> remove all these dependencies

What does this mean? I think some of dependencies are required for page render normally. for example: bootstrap

**Comment by clyang82** [comment]
@geeknoid any suggestions for the codecov failed? I googled this error `codecov bufio.Scanner: token too long`, it seems share the same reason with https://github.com/codeclimate/test-reporter/issues/282#issuecomment-357558280

**Comment by geeknoid** [comment]
Sadly, the code coverage job sometimes has false positives. I kicked it off again, hopefully it'll be happy this time around.

**Comment by ozevren** [comment]
This looks like a problem with the codecov infrastructure itself. 
The codecoverage.html parser is failing.

**Pull request merged**
