### PR TITLE
operator only prunes the resources from enabled components.

### LINKED ISSUE #30833: Canary Upgrade from 1.8.X -> 1.9.0 - Can't remove old Operator
**Bug description**

Did a canary upgrade from 1.8.3 - > 1.9.0
After upgrade was complete I did a: 
kubectl delete istiooperators.install.istio.io -n istio-system istiocontrolplane-1-8-3

Run kubectl get operators and still see the old operator present
Logs for operator are showing:
```
2021-02-12T13:35:00.485810Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:00.488110Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
2021-02-12T13:35:00.845347Z     info    installer       Watching a change for istio resource: istio-system/istiod-1-8-3
2021-02-12T13:35:00.845428Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:00.847588Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
2021-02-12T13:35:00.867348Z     info    installer       Watching a change for istio resource: istio-system/istiod-1-8-3
2021-02-12T13:35:00.867414Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:00.869180Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
2021-02-12T13:35:00.937490Z     info    installer       Watching a change for istio resource: istio-system/istiod-1-8-3
2021-02-12T13:35:00.937562Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:00.939400Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
2021-02-12T13:35:01.063066Z     info    installer       Watching a change for istio resource: istio-system/istiod-1-8-3
2021-02-12T13:35:01.063137Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:01.065417Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
2021-02-12T13:35:01.128722Z     info    installer       Watching a change for istio resource: istio-system/istio-1-8-3
2021-02-12T13:35:01.128777Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:01.130429Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
2021-02-12T13:35:01.177043Z     info    installer       Watching a change for istio resource: istio-system/istio-sidecar-injector-1-8-3
2021-02-12T13:35:01.177114Z     info    installer       Reconciling IstioOperator
2021-02-12T13:35:01.179044Z     info    installer       Ignoring IstioOperator CR istiocontrolplane-1-8-3 with revision 1-8-3, since operator revision is 1-9-0.
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ X] Upgrade

**Expected behavior**
Old operator should show as deleted
**Steps to reproduce the bug**
Canary upgrade of operator and then remove old operator
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.0
**How was Istio installed?**
Istio Operator
**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/30833

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by shamsher31 — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by ostromart** [comment]
@morvencao see my comment in the original issue, then let's discuss if this PR is still needed. sorry i didn't see this sooner.

**Review by richardwxn — APPROVED** [review]
I believe this is the correct fix, thanks for fixing it!

**Comment by richardwxn** [comment]
should also fix this one: https://github.com/istio/istio/issues/31304

**Comment by richardwxn** [comment]
@morvencao for 1.8 there is conflict, can you manually cherrypick?

**Comment by morvencao** [comment]
Weird why it reports error for cherrypick to release-1.8, but PR to 1.8 was actually created: https://github.com/istio/istio/pull/32374

**Pull request merged**
