### PR TITLE
echo server: bind to multiple pod IPs

### PR DESCRIPTION
**Pull request by howardjohn**
For dualstack testing

### CODE REVIEW

**Review by leosarra — APPROVED** [review]
Thank you. LGTM.
I will use it for DS testing

**Comment by kfaseela** [comment]
Thanks @howardjohn !

**Comment by kfaseela** [comment]
Should we wait for Leonardo's test results or can this be merged?

**Comment by leosarra** [comment]
> Should we wait for Leonardo's test results or can this be merged?

It is safe to merge now. I will use it for the upcoming tests, there is no need to block the merge in the meantime

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
