### PR TITLE
Add OpenShift install profile

### PR DESCRIPTION
**Pull request by hickeyma**
Adds an install profile to help users install Istio on an OpenShift platform.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by sdake — APPROVED** [review]
lgtm - may need some additional integration work - definitely needs a readme. I'll submit a readme now.

**Comment by linsun** [comment]
@jwendell can you take a look at this?  I believe this provides simplification for this instruction for openshift:  https://istio.io/latest/docs/setup/additional-setup/cni/#hosted-kubernetes-settings

Anything else we should consider adding to this profile?

cc @knrc

**Comment by jwendell** [comment]
LGTM. Note however that, in order to Istio completely work in OpenShift, these steps are still necessary: https://istio.io/latest/docs/setup/platform-setup/openshift/

**Comment by hickeyma** [comment]
@jwendell That is a good point. If I update the doc adding the install part using the profile, would this be sufficient?

**Comment by jwendell** [comment]
Yeah, I think you can append something like "or install using the [openshift profile](https://istio.io/latest/docs/setup/install/istioctl/#install-a-different-profile)" to the warning on the top of that page...

**Comment by sdake** [comment]
I will add a release note in the overall README once this profile merges.

**Comment by sdake** [comment]
@linsun as per approved [RFC](https://docs.google.com/document/d/1N_yC9vi4Jt3auMLLSOkavQb6qgbJKr-Mp4kUL3GOmEc/edit), we require two maintainers. I have recruited @jwendell and @irisdingbj to be lead maintainers of the OpenShift vendor optimized platform a few days ago.

Cheers,
-steve

**Comment by linsun** [comment]
Thanks @sdake, and @hickeyma @jwendell @irisdingbj !

**Comment by sdake** [comment]
README PR: https://github.com/istio/istio/pull/28155

**Comment by sdake** [comment]
> @jwendell That is a good point. If I update the doc adding the install part using the profile, would this be sufficient?

@hickeyma you can see the docs requiring an update in  https://github.com/istio/istio/pull/28155 in the release note. If you don't want to do that to istio/istio.io, that's cool. If so, that's also cool :) Either way, it needs to be done, just let me know. Most of my pressure has let up now that the release is branched, so I can do this if you prefer.

Cheers,
-steve

**Comment by hickeyma** [comment]
Thanks @sdake @linsun @jwendell for the reviews and @sdake for the merge.

**Pull request merged**
