### PR TITLE
format naming convention: operator watchedNamespaces

### PR DESCRIPTION
**Pull request by nicole-lihui**
**Please provide a description of this PR:**
 - consistent with the `.Values.watchedNamespaces` field definition in the `manifests/charts/istio-operator/templates/deployment.yaml`.
 - Improve code readability, resolve the old name will be misleading.
- fix unit test not compare multiple YAML files

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
This seems like a breaking change

**Review by morvencao — COMMENTED** [review]
Any strong reason for this change?

**Review by howardjohn — COMMENTED** [review]
I noticed you rerequested my review, but my comments in https://github.com/istio/istio/pull/35448#issuecomment-941243308 have not been addressed

**Comment by nicole-lihui** [comment]
Then i want fallback commit, but this pr is unclear, I will close it and new a clear pr .
resolve by #35616

**Pull request closed without merging**
