### PR TITLE
Fix allows repeated headers

### PR DESCRIPTION
**Pull request by wzshiming**
https://github.com/istio/istio/blob/8b14ab5fc044727ea2bae271599328479aa9ec3a/pkg/kube/apimirror/probe.go#L40-L42

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by bianpengyuan — CHANGES_REQUESTED** [review]
This reverts a previous fix for https://github.com/istio/istio/issues/28466, so does not seem to be right. I don't think the same header needs to be added by kubelet and istio agent for two times.

**Comment by wzshiming** [comment]
> This reverts a previous fix for #28466, so does not seem to be right. I don't think the same header needs to be added by kubelet and istio agent for two times.

I got it, maybe the documentation should be updated?

**Review by bianpengyuan — APPROVED** [review]

**Comment by howardjohn** [comment]
I am not sure I understand this. istio's probe logic should be identical to Kubernetes. So either this PR is wrong (documentation is different) or the existing code is wrong (behavior is different)?

**Comment by wzshiming** [comment]
> I am not sure I understand this. istio's probe logic should be identical to Kubernetes. So either this PR is wrong (documentation is different) or the existing code is wrong (behavior is different)?

Yes, In k8s, header repetition is allowed, but Istio is changed by PR #28537, so this PR ensure that the comments are consistent with the code.

I think the existing code may be wrong (behavior is different with Kubernetes)

**Comment by howardjohn** [comment]
Can we do a fix to match k8s behavior and add tests for it?

**Pull request merged**
