### PR TITLE
fix(canonical service): add env vars for canonical service

### PR DESCRIPTION
**Pull request by douglas-reid**
The primary purpose of this PR is to expose canonical service information in a way that can be leveraged by Envoy to add custom trace span tags for the service. Envoy supports a few different types of custom tag extraction, including `Environment`.

[ X ] Policies and Telemetry

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
We can also do this in the code - we already have access to all labels via downward API. This may be preferred though for explicitness

Do we need this for gateway?

**Comment by douglas-reid** [comment]
> We can also do this in the code - we already have access to all labels via downward API. This may be preferred though for explicitness

I was trying to avoid any code changes, if possible. This seemed like the simplest approach (?), but I don't have strong feelings.

> Do we need this for gateway?

Yes. I always forget those yamls.

**Review by howardjohn — APPROVED** [review]
I have a vision of the Gateway deployment being simple enough that its not much more complicated than just `image: proxyv2` and whatever customization the user wants, and they can control it just like any other application. That would be the motivation for moving logic into code. However, we are far away from that (if ever) and this is clear until then I think

**Pull request merged**
