### PR TITLE
Gateway API: Implement of GEP-995

### PR DESCRIPTION
**Pull request by wulianglongrd**
fix https://github.com/istio/istio/issues/52744

WIP: Please ignore this, wait until gateway-api is released and I will fix the failing tests.

### CODE REVIEW

**Comment by wulianglongrd** [comment]
Noted https://github.com/istio/istio/pull/53164 already implemented this API, so closed.

**Comment by howardjohn** [comment]
Sorry @wulianglongrd, didn't remember this PR when I was working on the bump.

**Comment by wulianglongrd** [comment]
> Sorry @wulianglongrd, didn't remember this PR when I was working on the bump.

Never mind. This PR was just an early revision and took very little time.

**Pull request closed without merging**
