### PR TITLE
Cherry-pick of PRs from release-1.0 branch

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR consists of a few related cherry-picks from the `release-1.0` branch. All
cherry-picked PRs were related to the introduction of metrics expiry in the
Prometheus adapter.

All of the code in this PR has been fully-reviewed and should require no further vetting.

Source PRs:
- \#8035
- \#8079
- \#8144

### CODE REVIEW

**Comment by douglas-reid** [comment]
Friendly Ping.

**Comment by douglas-reid** [comment]
Ping.

**Comment by douglas-reid** [comment]
@rshriram @mandarjog any thoughts here? This is important to have in `master`.

**Comment by rshriram** [comment]
FYI @costinm , When we merge cherry pick PRs, we need to do a merge commit. Not a squash and merge. Otherwise, the history of whoever contributed that code is completely lost. To do a merge commit, you have to go to settings, enable merge commit, then merge this PR as a merge commit. And then make sure to disable the merge commit setting. Otherwise, every PR will become a merge commit and that is not good.

**Pull request merged**
