### PR TITLE
telemetry api: allow default json format for envoy file logger

### PR DESCRIPTION
**Pull request by douglas-reid**
Currently, with the Telemetry API and EnvoyFileAccessLogger extension provider, there is no easy way to select the Istio-default JSON logging format. This PR attempts to add support for that behavior by treating an empty `labels` set as an indication of selection of default behavior (as there is no point to having an empty access log).

- [ X ] Policies and Telemetry
- [ X ] User Experience

Fixes: #37663

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by zirain** [comment]
@douglas-reid need lint

**Comment by sedflix** [comment]
@douglas-reid any example of how this can be used?

**Comment by Anand25021998** [comment]
+1. I couldn't find any example usage for this.

**Pull request merged**
