### PR TITLE
refactor keep alive settings

### PR DESCRIPTION
**Pull request by ramaraochavali**
Keep Alive settings logic checks the same conditions at multiple places. This PR simplifies that logic. There is no functional change.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
I think we need test cases covering this refactor.

**Comment by ramaraochavali** [comment]
I looked at existing test cases and they seem sufficient. Do you have any specific test in mind? I can add.

**Comment by hzxuzhonghu** [comment]
You mean `TestApplyTCPKeepalive`? It lacks specify keepalive both in mesh and connectionPool setting

**Comment by ramaraochavali** [comment]
I mean this https://github.com/istio/istio/blob/c017654753cd8f4254abbe0567ff9c728d2034d2/pilot/pkg/networking/core/v1alpha3/cluster_test.go#L621 - It covers those cases

**Review by hzxuzhonghu — APPROVED** [review]
LGTM, hard to trace the test cases

**Pull request merged**
