### PR TITLE
Fix data races in sidecar scope processing

### PR DESCRIPTION
**Pull request by johnma14**
We hit an issue in our test clusters where we have defined a SidecarScope for the root (istio-system) namespace and we expect all the user namespaces created to inherit this sidecarscope and that was not happening. Instead of getting the 'default' sidecarscope definition of the istio-system ns, it was getting the 'default-sidecar' sidecarscope. In big clusters, this leads to OOM.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Its not clear to me what this is fixing or how. Can you elaborate or add a test?

**Comment by hzxuzhonghu** [comment]
Better provide the panic stack

**Comment by johnma14** [comment]
I will go ahead and add a test case for this. I will see if I can add a stack trace as well. Thank you.

**Comment by johnma14** [comment]
Fixed by https://github.com/istio/istio/pull/40575. Locks used in the sidecarIndex processing was refactored in: https://github.com/istio/istio/pull/40688. Unit tests for #40575 added here: https://github.com/istio/istio/pull/41038

**Pull request closed without merging**
