### PR TITLE
Revise istioctl global flags displaying in options, and organize flag sets

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Originally https://github.com/istio/istio/issues/37938 was resolved in https://github.com/istio/istio/pull/38236. However it broke all `--help` commands, see https://github.com/istio/istio/pull/38236#pullrequestreview-1106554433. This PR addresses the problem, and organizes all the flags of a command in a new `Options` section like `kubectl`. For example:
```
istioctl admin log -h
Retrieve or update logging levels of istiod components.

Aliases:
log, l

Examples:
  # Retrieve information about istiod logging levels.
  istioctl admin log

  # Retrieve information about istiod logging levels on a specific control plane pod.
  istioctl admin l istiod-5c868d8bdd-pmvgg

  # Update levels of the specified loggers.
  istioctl admin log --level ads:debug,authorization:debug

  # Reset levels of all the loggers to default value (info).
  istioctl admin log -r

Options:
    --ctrlz_port=9876:
        ControlZ port

    --level='':
        Comma-separated list of output logging level for scopes in format
        <scope>:<level>[,<scope>:<level>,...]Possible values for <level>: none, error, warn, info, debug

    -o, --output='short':
        Output format: one of json|short

    -r, --reset=false:
        Reset levels to default value. (info)

    -l, --selector='app=istiod':
        label selector

    --stack-trace-level='':
        Comma-separated list of stack trace level  for scopes in format
        <scope>:<stack-trace-level>[,<scope>:<stack-trace-level>,...] Possible values for <stack-trace-level>: none,
        error, warn, info, debug

Usage:
  istioctl admin log [<pod-name>] [--level <scope>:<level>][--stack-trace-level
<scope>:<level>]|[-r|--reset]|[--output|-o short|yaml] [options]

Use "istioctl options" for a list of global command-line options (applies to all commands).

```

### CODE REVIEW

**Review by GregHanson — APPROVED** [review]
release note looks good

**Comment by howardjohn** [comment]
Why is this better? it just seems needlessly verbose?

**Comment by hanxiaop** [comment]
> Why is this better? it just seems needlessly verbose?

@howardjohn Some of the global flags are displayed in the help func but some of them are in the `istioctl options` command. I think it is better to organize them into the same place to avoid of confusion? Here are some comments: https://github.com/istio/istio/pull/38236#pullrequestreview-930518925, https://github.com/istio/istio/issues/37938#issuecomment-1087744545. I'm not really sure about why we marked those log flags as hidden flags. What do you think?
The changes of persistent flags are only due to unfriendly displaying of flags of subcommands, as a result I revised them all to get better user experience.

**Pull request closed without merging**
