### PR TITLE
Drop support for policy v1beta1

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
From which release k8s policy API GA?

**Comment by dhawton** [comment]
> From which release k8s policy API GA?

`policy/v1` has been part of k8s since 1.21

**Review by dhawton — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Review by ymesika — APPROVED** [review]
LG

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
