### PR TITLE
fix error in requirements and remove unneeded initializer code

### PR DESCRIPTION
**Pull request by linsun**
see https://github.com/istio/istio/issues/2935

### CODE REVIEW

**Comment by linsun** [comment]
cc @ayj @sdake

**Comment by luisyonaldo** [comment]
the `sidecar-injector` was added by https://github.com/istio/istio/pull/2830, is not even a helm chart, can you leave `initializer` and remove `sidecar-injector` dependency (only remove it from `requirements.yml`, don't remove the chart).

I'll convert that to a helm chart after addons PR. The chart need to have both `sidecar-injector` and `initializerz since the injector only work with k8s `1.9` so for older versions the old initializer need to be used

**Comment by ayj** [comment]
> The chart need to have both sidecar-injector and initializer since the injector only work with k8s 1.9 so for older versions the old initializer need to be used.

Which version of the initializer would you use? Initializer support was removed in 0.5.0. You'd need to use a 0.4.0 image and corresponding configuration.

**Comment by luisyonaldo** [comment]
sorry didn't know. so what happen if the k8s cluster doesn't support mutating webhooks? how will init proxy container will be created? how does initializer functionality is manage now?

If initializer is deprecated then is ok to remove it, just not sure how will still be compatible with old cluster.

**Comment by ayj** [comment]
Users will need to select between manual inject (i.e.`kube-inject`), upgrading to k8s 1.9, or using an initializer image from an older release.

**Comment by luisyonaldo** [comment]
in that case I'll let initializer files, and fall back to initializer if webhook admin is not available or if user enables it by `initializer.enabled`

**Comment by linsun** [comment]
do we really want to support initializer in helm given it is removed in non helm install in 0.5? I'd vote for no to keep it simple.   prior to 1.9 should use manual injection since the initializer was an alpha feature anyway.

**Comment by luisyonaldo** [comment]
fine by me. I'll update my cluster then :)

**Comment by linsun** [comment]
thank you @luisyonaldo for your understanding!

**Pull request merged**
