### PR TITLE
Fix filename convention

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
Following #2886:

1. Moved the underscore file convention to Directory and file conventions
2. Removed camel case convention for file and directory names
3. Add camel case convention for Go types

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
@costinm The proposal is for the new files only, though I think we can write a script and perform the change on the old files automatically.

Statistics on Istio: out of 698 Go files, 64 use underscore (not including _test.go files), and 63 use an uppercase letter in the file name, 77 files have uppercase either in their directory or their file name.
```
$ find . -name "*.go" | wc -l
     698
$ find . -name "*.go" -exec basename {} \; | grep _ | grep -v '_test.go' | wc -l
      64
$ find . -name "*.go" -exec basename {} \; | grep [A-Z] | wc -l
      63
$ find . -name "*.go" | grep [A-Z] | wc -l
      77 
```
Statistics on Kubernetes, after removing `vendor` directory: out of 6321 Go files, 1690 use underscore (not including _test.go files), and 5 use an uppercase letter in the file name. Also note that no uppercase letters are used in the directories of Kubernetes.
```
$ find . -name "*.go" | wc -l
    6321
$ find . -name "*.go" -exec basename {} \; | grep _ | grep -v '_test.go' | wc -l
    1690
$ find . -name "*.go" -exec basename {} \; | grep [A-Z] | wc -l
       5
$ find . -name "*.go" | grep [A-Z] | wc -l
      5
```

In https://golang.org/src/net/, no uppercase letters.

I guess we can consider Kubernetes and https://golang.org/src/net/ as de-facto standards. I did not find other references.

**Comment by ijsnellf** [comment]
@vadimeisenbergibm: I also was not able to find any definitive style guide, but looking through the Go source code the convention seems to be lowercase with no underscores, except for `_test.go`, `_stub.go` and platforms. For example, from https://golang.org/src/net/:

sendfile_bsd.go
sendfile_linux.go
sendfile_solaris.go
sendfile_stub.go
sendfile_test.go
sendfile_windows.go

Note than `sendfile` is not separated by underscores.

**Comment by vadimeisenbergibm** [comment]
@ijsnellf I see what you mean. It seems in Go core libraries, the convention is to use underscores `_` for _qualifiers_ like `OS`, `test`, `stub` etc. However it seems that Kubernetes follows this convention only partially. Some files are according to the convention, like  `globalflags_linux.go` and
`globalflags_other.go`, others are not: [device_allocator.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/device_allocator.go)

See below some other names  that do not follow the convention of Go core libraries. You can find them by running: `find . -name "*.go" -exec basename {} \; | grep _ | grep -v '_test.go' | less` on the Kubernetes source (with the `vendor` directory removed). These appear among the first 40 go files.
```
elasticsearch_logging_discovery.go
check_cli_conventions.go
swagger_type_docs.go
import_known_versions.go
make_secret.go
sorted_event_list.go
```

My take on it - the GO convention is maybe OK for https://golang.org/src/net/ with names like `sendfile` and `dnsclient`. Once you have names like `import_known_versions` or `sorted_event_list`, this convention is probably not so good.

 This PR is a follow up of #2886, where it is was decided in favor of the convention to use underscores between any two words.

**Comment by ijsnellf** [comment]
I would argue that filenames like `elasticsearch_logging_discovery.go`, `check_cli_conventions.go` are simply too long and that filenames in https://golang.org/src/net/ were carefully selected to be shorter. I am not strongly opinionated, though.

**Pull request merged**
