### PR TITLE
Remove mTLS analyzer

### PR DESCRIPTION
**Pull request by diemtvu**
This analyzer only work for v1alpha1 authentication API, which has been removed.

### CODE REVIEW

**Comment by esnible** [comment]
Is there a replacement for this analyzer?

**Comment by ayj** [comment]
AFAICT, this API is still included in the base manifest and present in istio.io/api. Support may have been removed from istiod itself, however, it is still likely a user upgrades from a previous version with meshpolicy applied expecting it to work. It would be nice to catch this and direct the user toward the supported API. The implication analyzers for deprecated APIs are only removed when the last supported Istio version no longer supports it. wdyt @esnible ?

**Comment by esnible** [comment]
I need to know two things.

Is there an analyzer for the new authentication API?

If the old API is no longer functional, is there an issue or PR to cause the analyzer to report that deprecated APIs are present?

If we don't have those things please create issues for them and I will triage them.

**Comment by diemtvu** [comment]
> I need to know two things.
> 
> Is there an analyzer for the new authentication API?
> 
> If the old API is no longer functional, is there an issue or PR to cause the analyzer to report that deprecated APIs are present?
> 
> If we don't have those things please create issues for them and I will triage them.

I've created https://github.com/istio/istio/issues/22602 for API clean up task. Afaik, we do not plan to add a new analyzer for the new authentication API at this point.

**Comment by diemtvu** [comment]
Ping. What is the decision we want for this?

**Pull request merged**
