### PR TITLE
[WIP] Merge proxy repo

### PR DESCRIPTION
**Pull request by kyessenov**
Warning: NEEDS TO BE MERGE COMMITTED

Performed using: 
```
git subtree add --prefix=proxy ...
git mv proxy/WORKSPACE .
find . -type f -name BUILD -exec sed -i 's/\/\/src/\/\/proxy\/src/g' {} +
find . -type f -name BUILD -exec sed -i 's/\/\/include/\/\/proxy\/include/g' {} +
find . -type f -name BUILD -exec sed -i 's/\/\/:darwin/\/\/proxy:darwin/g' {} +
find . -type f -name BUILD -exec sed -i 's/\/\/:deb_version/\/\/proxy:deb_version/g' {} +
find . -type f -name "*.h" -exec sed -i 's/\#include "src\/envoy\/alts/\#include "proxy\/src\/envoy\/alts/g' {} +
find . -type f -name "*.h" -exec sed -i 's/\#include "src\/envoy\/http/\#include "proxy\/src\/envoy\/http/g' {} +
find . -type f -name "*.h"  -exec sed -i 's/\#include "include/\#include "proxy\/include/g' {} +
find . -type f -name "*.h"  -exec sed -i 's/\#include "src\/istio/\#include "proxy\/src\/istio/g' {} +
find proxy/ -type f -name "*.py"  -exec sed -i 's/\#include "src\/istio/\#include "proxy\/src\/istio/g' {} +
git mv proxy/tools/bazel.rc* tools/
git mv proxy/tools/bazel_get_workspace_status tools/
# patch JWT integration test config paths
# patch Makefiles to prefix proxy\. and include to top-level, patch style check root path
# merge proxy circle ci into istio ci
```

Fixes https://github.com/istio/istio/issues/7841
/assign @qiwzhang

### CODE REVIEW

**Comment by rshriram** [comment]
?

**Comment by costinm** [comment]
Is this a joke ? 
/Hold

**Comment by kyessenov** [comment]
@costinm This is not a joke. See relevant issue (and it's WIP).

**Comment by costinm** [comment]
No point debating this - if you believe it is critical, escalate to the TOC. 
No way.

**Comment by kyessenov** [comment]
cc @PiotrSikora

**Pull request closed without merging**
