### PR TITLE
pilot: allow enabling gRPC logging with --log_output_level

### LINKED ISSUE #28482: Allow enabling gRPC logging with --log_output_level
Currently we hard code disable: https://github.com/istio/istio/blob/961d87dec7c13d9fe0b428adf2fa48280d064e50/pilot/cmd/pilot-agent/main.go#L174

Would be great if this is controlled by log_output_level so users can control this

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

Fix #28482

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
This is not right, should fix it in the log lib.

**Review by howardjohn — CHANGES_REQUESTED** [review]
I agree, we should be able to control it with `--log_output_level=grpc:debug` for example, to enable it. and still off by default

**Comment by daixiang0** [comment]
I see, just remove hardcode it works, refer to
https://github.com/istio/pkg/blob/master/log/config.go#L336-L339

**Review by howardjohn — COMMENTED** [review]
How do you enable this? I do not think this actually allows us to enabled it. if you do `--log_output_level=grpc:debug` it will have no impact

**Comment by daixiang0** [comment]
Do you mean implement it in `pkg/log`?

**Comment by howardjohn** [comment]
yeah

**Comment by daixiang0** [comment]
depend on [pkg#269](https://github.com/istio/pkg/pull/269)

**Comment by daixiang0** [comment]
@howardjohn it needs latest `istio/pkg`, so i update `go.mod` or wait `istio/pkg` upgrade to a new rc?

**Comment by howardjohn** [comment]
just do `go get istio.io/pkg@latest; go mod tidy`

**Comment by daixiang0** [comment]
@howardjohn done.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
