### PR TITLE
Update Global Meshpolicy on upgrades

### LINKED ISSUE #16170: Helm upgrade not updating meshpolicy for mtls
**Bug description**
Isito 1.2.2 - Helm upgrade does not update meshpolicy.  

few examples:
1) Manually delete the default created meshpolicy, running helm upgrade does not recreate it.  
2) Setting mtls in values.yaml from false to true or vice versa, the meshpolicy and destination rules are not updated/created

However, In istio-security-custom-resources configmap, I do see the custom-resources.yaml key being updated.  

```
apiVersion: v1
data:
  custom-resources.yaml: |-
    # Authentication policy to enable permissive mode for all services (that have sidecar) in the mesh.
    apiVersion: "authentication.istio.io/v1alpha1"
    kind: "MeshPolicy"
    metadata:
      name: "default"
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
    spec:
      peers:
      - mtls:
          mode: PERMISSIVE
```

I did some research, and tried rerunning the following jobs as well thinking it creates it from a job:

```
NAME                COMPLETIONS   DURATION   AGE
istio-init-crd-10   1/1           7s         15d
istio-init-crd-11   1/1           10s        15d
istio-init-crd-12   1/1           9s         15d
```

However, that has no impact as well

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Running helm upgrade should also update the meshpolicy and correct destinationrules when mtls is set from false to true and vice versa.

**Steps to reproduce the bug**
1) Set mtls enabled from false to true
```
  mtls:
    enabled: true
```
Run helm upgrade
` helm upgrade --install --force istio install/kubernetes/helm/istio --namespace istio-system -f install/kubernetes/helm/istio/values.yaml`

2) Delete the default meshpolicy from original installation
`kubectl delete meshpolicy default`

Upgrade istio via helm
` helm upgrade --install --force istio install/kubernetes/helm/istio --namespace istio-system -f install/kubernetes/helm/istio/values.yaml`

For both scenarios, deleted jobs istio-init-crd-10 to 12, reran helm upgrade to recreate jobs. Confirmed jobs ran, and meshpolicy still doesnt exist/updated

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: 1.2.2
devcourseherocom-ingressgateway version:
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.13

### PR DESCRIPTION
**Pull request by nrjpoddar**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Fixes: #16170

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@howardjohn is there any side affect of doing this? I tested it manually and `helm upgrades` work with mTLS toggle now but I don't have extensive experience with helm hooks.

**Comment by howardjohn** [comment]
I am not too familiar with helm hooks either. If you use helm template, you would create the job on install + upgrade, and now with tiller you would too. Seems like this should work. @sdake?

**Comment by nrjpoddar** [comment]
This needs to be back ported in 1.2, 1.1 and 1.3?

**Review by morvencao — COMMENTED** [review]
It makes sense, leave this to @sdake for approval.

**Review by howardjohn — COMMENTED** [review]
I think this is fine but it doesn't solve the whole problem. If you change `mtls` setting, the job spec will be the same, so you cannot switch from enabled to disabled. See https://github.com/istio/istio/issues/14650

**Comment by nrjpoddar** [comment]
> I think this is fine but it doesn't solve the whole problem. If you change `mtls` setting, the job spec will be the same, so you cannot switch from enabled to disabled. See #14650

@howardjohn yes, this only addresses if you're Helm & Tiller for install/upgrades. Helm + kubectl/installer is still broken.

**Review by howardjohn — APPROVED** [review]

**Comment by nrjpoddar** [comment]
@howardjohn any clues as to why `integ-istioctl-k8s-tests_istio` is failing? https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/17033/integ-istioctl-k8s-tests_istio/2021/build-log.txt is not that helpful.

**Comment by howardjohn** [comment]
Looks like an infra flake, I've been trying to squash these. Should be
unrelated to your change

**Comment by nrjpoddar** [comment]
> Looks like an infra flake, I've been trying to squash these. Should be unrelated to your change

Thanks since this test is marked "required", this PR won't be mergeable until it passes. :(

**Pull request merged**
