### PR TITLE
Update adapter.prometheus.config.pb.html

### PR DESCRIPTION
**Pull request by pandaamanda**

### CODE REVIEW

**Comment by pandaamanda** [comment]
adapter.prometheus.config.pb.html is auto-generated from the config.proto? what is the generation mechanism? 
thanks.

**Comment by douglas-reid** [comment]
Look at `prometheus.go` for a line like:

`//go:generate $GOPATH/src/istio.io/istio/bin/mixer_codegen.sh -a mixer/adapter/prometheus/config/config.proto -x "-n prometheus -t metric"`

You can generate with something like: `go generate ./mixer/adapter/prometheus`

**Comment by geeknoid** [comment]
The underscores in the metric names is confusing the markdown parser. It's treating this as the start of a sequence in italics.

I'm going to close this PR and fix the config.proto file to avoid this issue.

**Comment by geeknoid** [comment]
See #9072

**Pull request closed without merging**
