### PR TITLE
ambient: fix WasmPlugin bind to Service

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/51014

Need tests

The issue is in the LDS gen we lookup with Service, but in the ECDS request we don't so we don't find it.

Actually, the lookup in ECDS is not needed in general, not just in ambient: the proxy already requested a lsit of names, so we can just return those.

**Please provide a description of this PR:**

### CODE REVIEW

**Comment by howardjohn** [comment]
> > The issue is in the LDS gen we lookup with Service
> 
> Can you elaborate on this?

Yep: https://github.com/istio/istio/blob/febaa74b1a207e895f12610a2ce424158e01f26a/pilot/pkg/networking/core/listener_waypoint.go#L376

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Nit: we should comment 

WasmPluginListenerInfo.Service only used by waypoint in ambient mode. Otherwise we could not know which function should use when trying to get wasmplugins

**Comment by kfaseela** [comment]
@adilmp1 once this PR gets merged, please verify if it works for you. Also this will be a good area for you to add integration tests too.

**Pull request merged**
