### PR TITLE
fix addon component name validation.

### LINKED ISSUE #22092: --set addonComponents.<component>.enabled is case-sensitive
To reproduce, notice that
`istioctl manifest generate --set components.base.enabled=false --set components.pilot.enabled=false --set addonComponents.prometheus.enabled=false --set components.ingressGateways[0].enabled=false` produces only comments, but if we use `--set addonComponents.Prometheus.enabled=false` we still get a Prometheus.

The names are checked, e.g. `--set addonComponents.promethios.enabled=false` will fail with "Asset charts/addons/promethios not found".

Either the chart checking should be case sensitive or the disabling should be case insensitive.

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/22092

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by morvencao** [comment]
Looks like the failing tests isn't caused by this PR.

**Comment by howardjohn** [comment]
I am working on it

**Review by elfinhe — APPROVED** [review]

**Review by richardwxn — CHANGES_REQUESTED** [review]
Instead of adding back the addon component names from name.go, can you read it from the data file, e.g. names-1.6.yaml under translateConfig which we define the built in addon names for specific version.

**Comment by morvencao** [comment]
> Instead of adding back the addon component names from name.go, can you read it from the data file, e.g. names-1.6.yaml under translateConfig which we define the built in addon names for specific version.

I tried your proposal, looks like ii will make things more complicated. I mean if I just read the `translateConfig` file, we need to update the version for each release. As an alternative, I can import translate pkg, but that will introduce much more components for validate pkg. Not sure if this is a good idea, since we should keep the validate pkg independent of others.

**Comment by dgn** [comment]
But we're already loading the names from the file?

**Comment by dgn** [comment]
@morvencao if you don't want to use the file, have a look at https://github.com/istio/istio/pull/21410 - if that is merged we don't require the files anymore, it will read addonComponentNames straight from the charts

**Comment by morvencao** [comment]
@dgn Thanks for your suggestion, it helps a lot.

**Review by dgn — APPROVED** [review]

**Comment by morvencao** [comment]
@richardwxn PTAL

**Review by richardwxn — APPROVED** [review]

**Pull request merged**
