### PR TITLE
Ensure annotations from podRedirectAnnot are injected by the webhook

### LINKED ISSUE #22902: When CNI is installed, traffic.sidecar.istio.io annotations are not injected to Pods
**Bug description**

When CNI plugin is enabled and and `spec.values.global.proxy.excludeIPRanges` or `spec.values.global.proxy.includeIPRanges` is set, corresponding `traffic.sidecar.istio.io` annotations are not injected to Pods. This causes the configuration value to be ignored in the Pod.

Moreover, `istio-validation`  init container successfully passes, giving the impression that correct iptables settings are applied on the Pod.

`istio-sidecar-injector` ConfigMap have the correct values after installation. This `podRedirectAnnot` configuration is probably ignored by the sidecar injector itself.

I have only tried with `excludeIPRanges` and `includeIPRanges` but there is a high chance that this bug applies to all values defined in `podRedirectAnnot`.

See istio/cni#293 for more context.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 505cb62a5169c3752bbea0decedac9a40f10b87b-dirty
control plane version: 1.6-alpha.505cb62a5169c3752bbea0decedac9a40f10b87b
data plane version: 1.6-alpha.505cb62a5169c3752bbea0decedac9a40f10b87b (10 proxies)

**How was Istio installed?**

Via istioctl using the following configuration:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  tag: latest
  hub: gcr.io/istio-testing
  components:
    cni:
      enabled: true
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
    global:
      proxy:
        excludeIPRanges: 188.166.192.215/32
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

### PR DESCRIPTION
**Pull request by luksa**
Fixes #22902

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jbilliau-rcd** [comment]
Any update on this? @cagataygurturk did you ever find a way to resolve this? Im having the exact same issue, which was posted in #22902 , but closed without resolution; not sure why.

**Comment by nrjpoddar** [comment]
This should have been cherry-picked as it has been broken for several releases. Should we do that?

**Comment by nrjpoddar** [comment]
@luksa can you get this merged? AFAICT pod annotations and using macvlan with istio-cni on selective pods still doesn't work.

**Comment by jbilliau-rcd** [comment]
I concur; even on Istio 1.7.4 it doesn't.

**Comment by luksa** [comment]
/reopen

Give me 30 minutes to rebase and update this.

**Comment by nrjpoddar** [comment]
Thank you. Note that @howardjohn made some changes in this [PR](https://github.com/istio/istio/pull/26596) that might affect your implementation.

**Comment by luksa** [comment]
@nrjpoddar Thanks. That PR removed the injection of podRedirectAnnot in kube-inject. I've now submitted #28864 which adds it back. Since the injection code is now shared between kube-inject and the webhook, the annotations are now injected in both cases.

**Pull request closed without merging**
