### PR TITLE
fix galley fssource flakey test

### PR DESCRIPTION
**Pull request by irisdingbj**
resubmit for 1.1

### CODE REVIEW

**Comment by ayj** [comment]
Thanks! 

/lgtm

**Comment by ayj** [comment]
circiecli seems to be stuck. @irisdingbj, are you able to manually re-trigger the circleci/build job via their UI?

**Comment by irisdingbj** [comment]
@ayj  seems I have no authority to trigger the circiecli, can you help on this?

**Comment by ayj** [comment]
cc @kyessenov for trivial mixer formatting change

**Comment by ozevren** [comment]
Fixes #8957

**Comment by kyessenov** [comment]
/lgtm
/approve
for mixer bits; sorry to make you wait, I cannot filter github emails effectively.

**Pull request merged**
