### PR TITLE
Fix values settings being overridden by k8s overlays

### LINKED ISSUE #28489: Operator resources ignored
```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 30m
            memory: 65Mi
          limits:
            memory: 512Mi
    gateways:
      istio-ingressgateway:
        resources:
          requests:
            cpu: 30m
            memory: 65Mi
          limits:
            memory: 512Mi
```

```
$ ik manifest generate -d manifests -f /tmp/iop.yaml | k grep Deployment/istio-ingressgateway | rg resources: -A 6
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

You can see it does nothing

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/28489

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
ping @sdake @ostromart

**Review by ostromart — APPROVED** [review]

**Comment by ostromart** [comment]
post-approval comment: it's not clear how the change relates to the PR title, it seems to be about fixing indentation rather than fixing override logic. could you either change the title or update the PR description? then feel free to remove the hold.

**Comment by howardjohn** [comment]
Indentation is needed to be fixed because the old overlay marhsals and unmarshals it, fixing any trailing space. Because we no longer overlay, we needed to fix it at the source.

This does fix the original bug. The overlays of the default profile are taking priority over `values` settings. So this removes the overlays in the profile.

**Comment by howardjohn** [comment]
I will let you remove the hold since I suspect the change may not have been clear when you approved

**Comment by ostromart** [comment]
the part of this pr i'm not really enthusiastic about defaulting the values for gateways through values.yaml just to support an API that's on the way out in 1.9. but if you feel this is a real problem i'm ok with it.

**Comment by howardjohn** [comment]
I am not sure how its possible to remove the values.yaml API when we just added back helm support.

**Pull request merged**
