### PR TITLE
#2651 switch to use non-debug ingress to try tests

### PR DESCRIPTION
**Pull request by linsun**
Testing for https://github.com/istio/istio/issues/2651

### CODE REVIEW

**Comment by ldemailly** [comment]
@ozevren same failure in the perf test. do you have a quick fix ? maybewe should disable it if not

**Comment by ozevren** [comment]
I don't have a quick fix. Still looking at trying to repro. No objections
to disabling the test for the time being.

**Comment by ldemailly** [comment]
/lgtm
(if this passes tests it should go in)

**Comment by ldemailly** [comment]
if you look in the ingress log:
http://gcsweb.k8s.io/gcs/istio-prow/pull/istio_istio/2669/e2e-smoke/1578/artifacts/istio.e2e.792543437/

it seems the error is
```
[2018-01-19 03:56:29.717][17][warning][upstream] external/envoy/source/common/upstream/cds_subscription.cc:68] cds: fetch failure: JSON at lines 3-9 does not conform to schema.
 Invalid schema: #/properties/name
 Schema violation: maxLength
 Offending document key: #/name
```
so no amount of retries will help

**Comment by ldemailly** [comment]
from slack chat in #pilot the assumption is the max len is mismatched between pilot and that envoy build - and given it seems to work with the debug image it can be as simple as those 2 being built differently wrt to that constant (thanks @kyessenov  for the insights)

**Comment by linsun** [comment]
mystery solved see my commits @ldemailly, can I get a lgtm?  thanks.

**Comment by ldemailly** [comment]
/lgtm
grats on mystery solving Lin !

**Pull request merged**
