### PR TITLE
add exportTo support for gateways

### PR DESCRIPTION
**Pull request by ramaraochavali**
Enhances exporTo with support for gateway so that services can be exported to gateways to be be used in Envoy filters.

For #3 in https://github.com/istio/istio/issues/29131

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Still need to add release notes and tests.

**Review by howardjohn — COMMENTED** [review]
We discussed in networking WG (https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit#bookmark=id.z02np8mw7xzx)

and some feedback was this may make more sense on the Envoyfilter itself. So we could add a `dependencies` field or similar

**Comment by ramaraochavali** [comment]
I responded there - I think if we want to add explicit dependency list - it may be better to add to gateway rather than EnvoyFilter.

**Comment by ramaraochavali** [comment]
Closing this since there are other ideas to do it.

**Pull request closed without merging**
