### PR TITLE
pilot-agent: clean up all cached TCP connections when shutting down

### PR DESCRIPTION
**Pull request by panjf2000**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
What user facing impact does this have?

**Comment by panjf2000** [comment]
This is a slight improvement for the system, the GC, to be precise. I don't think our users will feel it.

**Comment by howardjohn** [comment]
This only happens when the container shuts down. I am personally not a fan of theoretical performance improvements which in reality just make the code more complex. Maybe we should keep it simple. See https://en.wikipedia.org/wiki/KISS_principle and http://wiki.c2.com/?PrematureOptimization

**Comment by panjf2000** [comment]
> This only happens when the container shuts down. I am personally not a fan of theoretical performance improvements which in reality just make the code more complex. Maybe we should keep it simple. See https://en.wikipedia.org/wiki/KISS_principle and http://wiki.c2.com/?PrematureOptimization

You've also made a good point here, tiny improvements may not make a conspicuous difference, however, many little drops make an ocean and program optimization should be considered all the time, I believe it is a good habit to release all the resources you can when the programs/servers/containers exit, even we are using Go which has runtime.

Personal opinion, open to discussion.

**Comment by hzxuzhonghu** [comment]
I think we donot need to manage connections which are not created by us manually

**Comment by panjf2000** [comment]
> I think we donot need to manage connections which are not created by us manually

I wouldn't say that we are managing connections, It should be understood as a resource cleanup effort which is common and widely used in a number of well-known open-source projects when exiting/closing the servers/clients:

1. [etcd](https://github.com/etcd-io/etcd/blob/ae7862e8bc8007eb396099db4e0e04ac026c8df5/server/etcdserver/api/rafthttp/transport.go#L222-L226)

2. [caddy](https://github.com/caddyserver/caddy/blob/bd17eb205d6ac464c64eb888a6f4b57445b6c59c/modules/caddyhttp/reverseproxy/httptransport.go#L281)

3. [consul](https://github.com/hashicorp/consul/blob/b5abf61963c7b0bdb674602bfb64051f8e23ddb1/agent/checks/docker.go#L59)

3. [k8s](https://github.com/kubernetes/kubernetes/blob/17376e6aef0fe1e2646b30a4d2e08c62329585a8/test/images/agnhost/netexec/netexec.go#L374)

**Comment by howardjohn** [comment]
@panjf2000 as I have mentioned, I do not plan to approve this PR

**Comment by panjf2000** [comment]
Got your point.

**Pull request closed without merging**
