### PR TITLE
Removed legacy chrion webhook controller

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Cleanup, istio is not using the secret chrion created any more.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by howardjohn** [comment]
I believe this is part of the API now and users have come to depend on it for other purposes @nrjpoddar ?

**Comment by nrjpoddar** [comment]
> I believe this is part of the API now and users have come to depend on it for other purposes @nrjpoddar ?

That's partially correct. Can you explain if Chiron is linked with workload certificate or purely for generating webhook certificates signed by K8s apiserver? Why are we not using this mechanism in latest Istio release?

**Comment by hzxuzhonghu** [comment]
I guess since 1.5 this is not used anymore. At least the certificate signed is not referred by pilot and other modules

**Comment by lei-tang** [comment]
As mentioned in the comments, the DNS certificate provisioning is an API in the istio API repository:
https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L936. Should the discussion of removing this API start from the istio API repository https://github.com/istio/api/? If the API implementation is removed before the API declaration, the API will be broken.

**Comment by nrjpoddar** [comment]
@hzxuzhonghu I think you're removing a broader feature here. We need to continue supporting https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate API but you can remove the implementation of generating cert/secret for istiod as it's no longer used.

Now does https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate actually work?

**Comment by lei-tang** [comment]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate works and the workflow is as folllows:
-  In initCertController(), the meshconfig for the certificates to be generated (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate) is read.
-  Based on the configuration read in the above step, a certificate controller is created in initCertController() to provision the certificates.

**Comment by hzxuzhonghu** [comment]
@lei-tang The after the above step how does the certificate used by pilot? I could not find that

**Comment by hzxuzhonghu** [comment]
Why would not they sign it with k8s directly?

**Pull request closed without merging**
