### PR TITLE
Remove discarded code which still uses authentication/v1alpha1 api

### PR DESCRIPTION
**Pull request by domgoer**
Please provide a description for what this PR is for.

Since `authentication/v1alpha1/Policy` has been removed, clear the method that is still using it and is not called

PRs: [istio/istio#22972](https://github.com/istio/istio/pull/22972)

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nschhina** [comment]
Can you also please link the PR that removed authentication/v1alpha1/AuthenticationPolicy, would make it easier to review

**Comment by domgoer** [comment]
@nschhina Thanks for the suggestion, I have linked it

**Pull request merged**
