### PR TITLE
Validate proxy more in fuzz tests

### PR DESCRIPTION
**Pull request by howardjohn**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
@howardjohn tests/fuzz/testdata/FuzzValidateClusters/6380814220263424 added by mistake?

**Comment by howardjohn** [comment]
> @howardjohn tests/fuzz/testdata/FuzzValidateClusters/6380814220263424 added by mistake?

no, it's a regression test

**Comment by hzxuzhonghu** [comment]
I remember it is auto generated to cache some state

**Comment by howardjohn** [comment]
the fuzzer auto generates test cases theb when we hit failures we check in
the failed case as a regression test and fix the failure

**Comment by hzxuzhonghu** [comment]
I am wondering this can not be called fuzz, isn't it fixed test cases then

**Comment by howardjohn** [comment]
We run a few fixed test cases in unit test for known regression tests, then
continuously we are generating new cases. The checked in ones are just a
small check to verify things compile and run properly and we don't regress
- most of the work is on the real fuzzing (which is how we found the bug)

**Comment by hzxuzhonghu** [comment]
That make sense

**Review by hzxuzhonghu — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
