### PR TITLE
[ci skip] Add a script to query pilot for proxy configurations

### PR DESCRIPTION
**Pull request by baodongli**
This script issues curl requests to pilot for LDS/RDS/CDS/SDS configurations.

What this PR does / why we need it:
This script issues curl requests to pilot for LDS/RDS/CDS/SDS configurations. It makes it easier for the user to examine the current proxy configurations in the system for debugging and learning purposes.

Which issue this PR fixes
fixes https://github.com/istio/old_pilot_repo/issues/1641

Special notes for your reviewer:

```release-note
NONE
```

### CODE REVIEW

**Comment by ldemailly** [comment]
I fixed up your initial comment to add correct issue link and correct way to set release-note

**Comment by ldemailly** [comment]
/ok-to-test

great idea/script ! thx !

**Comment by baodongli** [comment]
Thanks for your approval. I renamed it as istio-proxy-cfg as you suggested. The new name looks better.

**Comment by ldemailly** [comment]
a neat followup would be to add a test for this script to make sure it doesn't start breaking when pilot changes

**Comment by baodongli** [comment]
Let me think about adding a test like that. Any suggestions?

**Comment by ldemailly** [comment]
you could run said test in e2e / demo test to check one of the bookinfo pods for instance
but it can be later too

**Comment by yutongz** [comment]
@ldemailly The status is not sent to submit queue properly, could you check if there is a webhook set to send event to "http://35.197.104.17:8080/webhook"

**Comment by yutongz** [comment]
kick

**Comment by ldemailly** [comment]
@yutongz it was not, but when I try to add it (with PR related events) I get
screen shot 2017-11-08 at 12 08 49 am

**Comment by yutongz** [comment]
Yeah, it used to be there, someone removed it. The webhook needs the secret to verify. I will work with you tomorrow.

**Comment by baodongli** [comment]
Anything that I need to do to move this forward? Thanks.

**Pull request merged**
