### PR TITLE
Remove consul service registry

### PR DESCRIPTION
**Pull request by howardjohn**
Per discussions in networking WG, external service registry support will
be done via MCP-over-XDS rather than in-tree

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rshriram** [comment]
RIP

**Comment by howardjohn** [comment]
Discussed and approved in networking meeting last week

**Comment by hzxuzhonghu** [comment]
Isn't is safer to announce the deprecation first? So the users of consul can have more time before migrating to MCP

**Comment by howardjohn** [comment]
> Isn't is safer to announce the deprecation first? So the users of consul can have more time before migrating to MCP

I believe we did announce this? And if not, this will be in 1.8 so we can announce deprecation in the 1.7 release

**Comment by hzxuzhonghu** [comment]
Better to have a release note

**Pull request merged**
