### PR TITLE
Bump viper to the latest.

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

Bump spf13/viper to the latest. [1.14 changed](https://github.com/spf13/viper/compare/v1.13.0...v1.14.0)

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by yanggangtony** [comment]
image
I have no idea about the ci error.

**Comment by howardjohn** [comment]
I think relatred to https://github.com/istio/istio/issues/42118

**Pull request merged**
