### PR TITLE
WIP: Cherry-pick mTLS analyzer for 1.4

### PR DESCRIPTION
**Pull request by selmanj**
Including these PRs: #18700, #19055, #18350, #18478, #18917, #18935, #19244 

Note that this adds the structured format options to istioctl analyze. It's not needed for the mTLS analyzer, but including it means the cherry-picks apply cleanly.

I briefly tested it by hand and both structured output and the mTLS analyzer seem to work as expected:

```
jsselman-imacpro:~/g/s/i/istio (mtls-analyzer-1.4|✔) $ ~/go/out/darwin_amd64/release/istioctl  x analyze -k -o json
[
        {
                "code": "IST0113",
                "level": "Error",
                "message": "A DestinationRule and Policy are in conflict with regards to mTLS for host *.svc.cluster.local in namespace istio-system. The DestinationRule \"(none)\" specifies that mTLS must be false but the Policy object \"default\" specifies Strict.",
                "origin": "MeshPolicy default"
        }
]
Error: Analyzer found issues.
```

### CODE REVIEW

**Comment by selmanj** [comment]
Ah dang, apparently the config output change has some linter issues. The fix is here:
https://github.com/istio/istio/pull/19137

but it's huge and certainly wont apply cleanly. Should I manually fix them?

**Comment by selmanj** [comment]
Also, note that there were more stylistic changes that I didn't include here that were applied to the analyzer. Should I pull those in too? They're not functionally required, but it'll make easier cherry-picks more likely to apply cleanly (at the expense of this PR getting bigger)

**Comment by selmanj** [comment]
Unfairly assigning to @howardjohn since he left a single innocent comment on the mTLS PR, and is therefore an expert on the feature.

**Comment by howardjohn** [comment]
@selmanj this got delayed due to security release. Is this still up to date? Do we have the fixes for the excessive error messages from this analyzer? Should we be cherrypick new features to the analyzer given our docs encourage users to install from master anyways?

**Comment by selmanj** [comment]
This doesn't contain those fixes, yet. I assumed #19360 was actually blocking this PR. 

I'm working on adding public docs right now, which should close out #19360 and presumably unblock this PR. I'd like a chance to update this though so that it includes _all_ the relevant fixes.

marking this WIP for now.

**Comment by howardjohn** [comment]
Lets push this in 1.5. This is to big a change for a patch release and 1.5 is coming in weeks

**Pull request closed without merging**
