### PR TITLE
Fix New Test Framework tests running in kubernetes environment

### PR DESCRIPTION
**Pull request by gargnupur**
After the change https://github.com/istio/istio/pull/10562 Istio Deployment in new test framework started failing.
This PR tries to fix that

### CODE REVIEW

**Comment by hklai** [comment]
/hold
That test is still failing.

**Comment by nmittler** [comment]
@hklai we don't want to hold up development. Should we make istio-integ-k8s-tests optional until this is resolved?

**Comment by gargnupur** [comment]
@hklai : failure looks like is in setting up of the environment and not in test specifically...
Can you please help debug this error: "Failed to get a Boskos resource"?

**Pull request merged**
