### PR TITLE
Increase test coverage in operator/pkg/version

### PR DESCRIPTION
**Pull request by rytswd**
--

I wanted to contribute back to Istio for the first time, and picked up relatively easy looking issue. I increased the test coverage from 59.8% to 96.7% on operator/pkg/version without touching the main source file at all.

I could not achieve 100% coverage, with the following lines missing coverage:

- line#134 seems to be duplicate error check from line#125
- line#284 - couldn't figure how to get error from `vfs.ReadFile`
- line#289 - couldn't figure how to test against unmarshal error
- line#323 - could be done by providing a real uri, but that probably won't work on CI env

Apologies how it's all over the place, and I'm sure there are some incorrect approaches to other tests as well. Some feedback will be really appreciated!

--

Updates #21886

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
/ok-to-test

**Review by dgn — APPROVED** [review]
> I wanted to contribute back to Istio for the first time, and picked up relatively easy looking issue. I increased the test coverage from 59.8% to 96.7% on operator/pkg/version without touching the main source file at all.

Welcome to Istio and thank you very much @rytswd! Very much appreciated :)

>     * line#134 seems to be duplicate error check from line#125

Agreed. I think we could safely just use v.OperatorVersion instead of running NewConstraint again. It looks like the Constraints do not mutate its contents, so it should be safe to not even deepcopy. Then again, we know this can never really happen so no need to make code changes.

>     * line#284 - couldn't figure how to get error from `vfs.ReadFile`

I think the only reliable way is to give it a filename that doesn't exist - which doesn't work here because the filename is hard-coded. I think it's fine to leave this untested.

>     * line#289 - couldn't figure how to test against unmarshal error

It's possible but the error seems weirdly formatted; you'd need to match differently (instead of using reflect.DeepEqual probably a prefix match would work).

>     * line#323 - could be done by providing a real uri, but that probably won't work on CI env

I agree, I'd prefer not to do that. I know that some people (including us at Red Hat) run tests in (almost) air-gapped envs, so this wouldn't work.

I think this is great as it is - we don't necessarily need to have 100% test coverage, especially if it means making the code harder to follow.

Thanks again for your contribution!

**Comment by rytswd** [comment]
Thanks for the comment and clarification @dgn! I'd leave the PR as is in that case.

As to the linked issue, should I re-phrase to get it fixed upon merge?

**Comment by dgn** [comment]
> As to the linked issue, should I re-phrase to get it fixed upon merge?

You can - maybe you're quick enough ;) Otherwise I'll just close it when this is merged

**Comment by rytswd** [comment]
Seems I wasn't quick enough ;-) Thanks very much for your support!

**Pull request merged**
