### PR TITLE
presubmit to check the generated files in sync

### PR DESCRIPTION
**Pull request by jmuk**
**What this PR does / why we need it**:

We chose to check in generated files (like `.pb.go` files), but sometimes the checked-in version
can be out of sync from the actual source files, which would cause pain. `bin/bazel_to_go.py` script
(called by `bin/linters.sh`) will do the regeneration, so presubmit test should check the diffs and
raises errors to prevent this kind of thing happening.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by jmuk** [comment]
re: the presubmit failure

this is actually the expected one, it should fail until #1565 and #1597 are merged.

**Comment by mandarjog** [comment]
@jmuk the check is still failing, I think fmt.sh has formatted the file and that is why they are different.

**Comment by jmuk** [comment]
Indeed the check fails, some others came in meanwhile. Added to this PR for the changes happening through `bin/linters.sh` and `bin/fmt.sh`. PTAL.

**Pull request merged**
