### PR TITLE
move simple TLS to file based SDS

### PR DESCRIPTION
**Pull request by ramaraochavali**
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nschhina** [comment]
Thanks for this PR, Ref:https://github.com/istio/istio/issues/24921
I have concerns regarding the test coverage for this. I think it'd be better if we wait till https://github.com/istio/istio/pull/24786 gets merged first. 
Any plans to document file-based SDS feature on istio.io @ramaraochavali

**Comment by nschhina** [comment]
cc: @JimmyCYJ  @myidpt

**Comment by ramaraochavali** [comment]
I am planning to add integration tests for the entire file based certs in separate PR. Let us keep that issue https://github.com/istio/istio/issues/24921 open till tests are added. File based SDS for the certs specified in destination rule configuration is an implementation detail - we do not have to document that.

**Comment by nschhina** [comment]
@ramaraochavali  agreed we should keep that issue open. By document I mean- there's TLS origination tasks in istio.io user guide which use old file mount approach, maybe adding/editing the task to show file watcher support is a plus. Not hugely important though as secret based SDS should be out soon anyways along with a new task on istio.io explaining usage

**Pull request merged**
