### PR TITLE
Add configurable scaling behavior for Istiod's HPA in helm chart

### LINKED ISSUE #42634: Support configurable scaling behavior for Istiod's HPA in helm chart
**Describe the feature request**

The `HorizontalPodAutoscaler` created by the `istio-discovery` helm chart to deploy istiod on Kubernetes uses the CPU utilization to determine the recommended number of replicas.
As istiod's CPU utilization is very spiky during config pushes, I can observe the number of pods increasing from ~5 to 30+ pods on a couple of clusters.
This creates a lot of thrashing, as these newly created pods don't even participate in the push and will be scaled down again after a couple of minutes.

The  `HorizontalPodAutoscaler` from the `autoscaling/v2` API supports customizable scaling behavior which allows me to create [policies for the scaling activity](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior).

**Describe alternatives you've considered**

I considered disabling the HPA from the helm chart and provide my own HPA instead, but I believe that this feature might be useful for other people as well.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by oliviermichaelis**
This PR fixes #42634

**Please provide a description of this PR:**

Users can optionally specify scaling behavior for the autoscaling/v2 HPA for istiod in the `istio-discovery` helm chart.
The `behavior` was stabilized in Kubernetes 1.23, and is therefore only applied for the `autoscaling/v2` apiVersion, not for `autoscaling/v2beta1`.

Here is an example configuration for the helm `values.yaml`:
```yaml
pilot:
  autoscaleEnabled: true
  autoscaleBehavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
```

### CODE REVIEW

**Comment by eugenestarchenko** [comment]
Can this PR be reviewed and pushed further?

**Review by keithmattix — COMMENTED** [review]
We already have an autoscale field here so I'm not too opposed to this. I'm curious to what @howardjohn thinks though

**Review by howardjohn — COMMENTED** [review]
Seems reasonable for me, I am not an approver on this folder though

**Comment by oliviermichaelis** [comment]
Thanks for the reviews! Is there anything I can do to help get this PR reviewed by the right people?

**Review by GregHanson — APPROVED** [review]
release note looks good

**Review by howardjohn — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Comment by oliviermichaelis** [comment]
I haven't had time or access to a suitable machine to rebase the PR, but will do so soon.
I can imagine that reviewer's resources are scarce, but I would highly appreciate if one of the missing code owners could review the PR to prevent the frequent required rebases :)

**Comment by craigbox** [comment]
reopen

**Comment by zirain** [comment]
image

cc @craigbox

**Comment by ericvn** [comment]
A test comment

**Pull request closed without merging**
