### PR TITLE
trust domain validation cherry pick for release-1.6

### PR DESCRIPTION
**Pull request by incfly**
#26435

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by incfly** [comment]
@googlebot I consent

**Comment by incfly** [comment]
#26435

**Comment by nschhina** [comment]
LGTM but do you also plan to cherrypick integ test PR? Or we'll be skipping that?

**Comment by incfly** [comment]
@yangminzhu would CP the test i assume.

**Pull request merged**
