### PR TITLE
Fix name of pilot component file in updateVersions.sh

### PR DESCRIPTION
**Pull request by christian-posta**

### CODE REVIEW

**Comment by andraxylia** [comment]
@jmuk prow fails because there is inconsistency for the probe path. Is it livenessProbePath=/live or probe-path? I searched in the code and both are still present.

**Comment by jmuk** [comment]
The flag name itself should be sane. The error message looks to me like the mixer binary (docker image) isn't referring to HEAD, a bit older so it does not yet know the flag?

**Comment by ldemailly** [comment]
this should pass as soon as #3016 is merged

**Pull request merged**
