### PR TITLE
Install Galley with sidecar in helm

### PR DESCRIPTION
**Pull request by myidpt**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ozevren** [comment]
Has this changed substantially compared to the original PR? And, are you planning to push forward with this?

**Comment by howardjohn** [comment]
Still desired? Or just keeping this in operator only?

**Comment by ayj** [comment]
Galley already has a sidecar in the istio/installer charts and istioctl/operator. Are there any other install methods we're planning to support for 1.4?

**Comment by howardjohn** [comment]
> Galley already has a sidecar in the istio/installer charts and istioctl/operator. Are there any other install methods we're planning to support for 1.4?

the istio/istio one will ship in 1.4 due to lack of testing/docs for the operator. Even once we have those ready though we probably need to keep the old one around for at least a release so users can transition

**Pull request closed without merging**
