### PR TITLE
Remove Dockerfile.proxytproxy

### PR DESCRIPTION
**Pull request by howardjohn**
This was added without testing, documentation, or ownership, and as such doesn't
meet the requirements to be included in the project. We had an issue
requesting maintainers for months, and no one was interested. If anyone
does want to have this file, they should do the above. Until then, we
should not ship untested images to customers.

See https://github.com/istio/istio/issues/17199

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@rlenglet doesn't Cilium use this? Could you ping someone there to see if they want to maintain it, before we rip it out?

/hold

**Comment by rlenglet** [comment]
> doesn't Cilium use this? Could you ping someone there to see if they want to maintain it, before we rip it out?

Cilium hasn't updated [their proxy images](https://hub.docker.com/r/cilium/istio_proxy/tags) for 4 months. The last one is based on Istio 1.2.5, which has known vulnerabilities. This seems abandoned.

@jrajahalme Are you OK with dropping the `proxytproxy` images? Cilium could use the `proxyv2` images instead. It won't be a big change.

**Comment by sdake** [comment]
@howardjohn I understand the desire to merge this work - would you mind waiting for https://github.com/istio/istio/pull/19322#issuecomment-567602348 to land? I am out of time for rebases and more debug work before year-end.

Cheers
-steve

**Comment by howardjohn** [comment]
No problem

**Comment by jrajahalme** [comment]
@rlenglet Cilium still needs this, will update to the latest soon. So please do not remove this!

**Comment by jrajahalme** [comment]
I'll look into building the proxytproxy image from the cilium-proxy repo.

**Comment by ericvn** [comment]
@jrajahalme Were you able to satisfy your proxytproxy image? I don't see any response in the last 25 days.

**Comment by rlenglet** [comment]
I see that @jrajahalme has built Cilium images for 1.4.3: https://hub.docker.com/r/cilium/istio_proxy/tags.

**Pull request merged**
