### PR TITLE
Fix MutableBag.Merge performance

### PR DESCRIPTION
**Pull request by mandarjog**
Merge contract is that it does not overwrite values.
Implementation was using bag.Names() to loop thru, this was very expensive, as `Names()` allocated a new array on every invocation. 

This PR introduces `bag.Contains(string) bool` to specifically answer the question if a key is contained in a bag. This is a fast and alloc free operation.

Addresses https://github.com/istio/istio/issues/8818

Previous:
```
// Original        100000	     20527 ns/op	    9624 B/op	      12 allocs/op
// with Contains() 1000000	      1997 ns/op	       0 B/op	       0 allocs/op

```

### CODE REVIEW

**Comment by geeknoid** [comment]
Out of curiosity, did this function show up as a bottleneck in a perf test?

**Comment by mandarjog** [comment]
@geeknoid, it did. 
There a link from the attached issue that you can follow.

**Comment by mandarjog** [comment]
Under load before change
```
POD                                         NAME                       CPU(cores)   MEMORY(bytes)
istio-telemetry-7c8cbc8565-2rm2v            mixer                      3900m        417Mi
istio-telemetry-7c8cbc8565-2rm2v            istio-proxy                201m         118Mi
istio-telemetry-7c8cbc8565-7fv4d            mixer                      3596m        357Mi
istio-telemetry-7c8cbc8565-7fv4d            istio-proxy                187m         102Mi
istio-telemetry-7c8cbc8565-xrrf4            mixer                      4051m        378Mi
istio-telemetry-7c8cbc8565-xrrf4            istio-proxy                276m         110Mi
```
Total = 11547 m CPU

After the change
```
istio-telemetry-79b944b46-dt75w             mixer                      3247m        1343Mi
istio-telemetry-79b944b46-dt75w             istio-proxy                241m         86Mi
istio-telemetry-79b944b46-dvsfh             mixer                      3384m        993Mi
istio-telemetry-79b944b46-dvsfh             istio-proxy                232m         100Mi
istio-telemetry-79b944b46-g5g6r             mixer                      3256m        377Mi
istio-telemetry-79b944b46-g5g6r             istio-proxy                213m         60Mi
``` 
Total = 9887 m CPU

**Pull request merged**
