### PR TITLE
Fix envoy_bootstrap agent cluster name

### PR DESCRIPTION
**Pull request by wzshiming**
Fix the name here is repeated with prometheus_stats. Although it works, it's better to modify it.

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by wzshiming** [comment]
@hzxuzhonghu

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by wzshiming** [comment]
`release-notes-none` label cannot be added. Could you give me some help.

https://github.com/istio/bots/blob/57d0287718a4bfb6a39a9b3d30b4505730fdf712/policybot/config/autolabels/release-notes.yaml#L1-L6

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
