### PR TITLE
make use of  existing  kube.WaitForCacheSync

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
this is moving from listening on a channel (instantly returns once complete) to polling (slow)

**Comment by hzxuzhonghu** [comment]
Much performance influence? 

And preciously, `waitForCacheSync` has no timeout to return.

**Comment by howardjohn** [comment]
there is no need for a timeout since it takes a `stop` channel. 


The polling delays at one point made Istio's unit tests *2x slower* overall which is crazy. A bit improved because we now poll more aggressively in unit tests but still not good at all. Why poll when we have a channel, it's strictly worse, even if not a huge impact..

**Comment by hzxuzhonghu** [comment]
Without timeout, it stops until the channel closed or synced,.

But the time ticker, seems to indicate after 5s it will return true

**Comment by howardjohn** [comment]
I am not sure what 5s timeout you are talking about. there is no timeout?

**Comment by howardjohn** [comment]
Maybe https://github.com/istio/istio/blob/8d2e2000c16296ec247b642bb49da56b1f4d6988/pkg/kube/client.go#L706 you mean? This just makes it log every 5s, there is no timeout.

**Comment by hzxuzhonghu** [comment]
You are right, there is a second loop forever

**Pull request closed without merging**
