### PR TITLE
proxy: test minimal SDS

### PR DESCRIPTION
**Pull request by kyessenov**
Change-Id: I9be4b0244a349876edfd0bad895406a1face91b2

WIP, please don't review yet.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
I know its a WIP, but want to give feedback early. I am pretty strongly against throwing out the stable battle tested implementation to reduce the binary size a bit. The risk vs benefit is way off here. And there are alternatives here, too, to reduce the binary, by making the XDS engine we use less strictly tied on imports.

Maybe it would make sense for your build to just not include SDS at all and use files

**Comment by kyessenov** [comment]
What's so difficult about 50 lines of an xDS server? There's only one 1 client and 2 resources -what's the value of bringing all this machinery from Istiod that handles all sorts of edge cases, when we can just fix Envoy client directly to make it behave better?
 
I'm not able to decouple SDS as it is implemented from Istiod internals, so I declare a loss in that battle. If we are not willing to consider a lighter SDS as an alternative (maybe opt-in for now), then indeed we have to make a fork for our build.

**Comment by howardjohn** [comment]
> What's so difficult about 50 lines of an xDS server? There's only one 1 client and 2 resources -what's the value of bringing all this machinery from Istiod that handles all sorts of edge cases, when we can just fix Envoy client directly to make it behave better?

Because the 50 lines doesn't handle all the use cases and requirements of the system, Its untested, doesn't handle edge case, ...

Once we meet those requirements it will quickly be at least 500 lines of code

> I'm not able to decouple SDS as it is implemented from Istiod internals, so I declare a loss in that battle. If we are not willing to consider a lighter SDS as an alternative (maybe opt-in for now), then indeed we have to make a fork for our build.

Ok, sounds like we should go down that path.

**Comment by kyessenov** [comment]
I'm really not sure why it would take 500 lines to send 2 protos. The implementation is basically a glorified file system, since there's no true push mechanism. If Istio maintainers do not feel it is valuable to have a more generic SDS and insist on forcing Istiod xDS server semantics, then I will leave #50134 for the other maintainers to close. We have the checks in `check-agent-deps` to keep the rest of the agent fairly small.

**Comment by howardjohn** [comment]
> I'm really not sure why it would take 500 lines to send 2 protos.

And I am not sure why it takes Envoy 1M LOC to send a few HTTP requests :slightly_smiling_face:. Any application can be reduced to a trivial statement if we ignore all the requirements.

**Pull request closed without merging**
