### PR TITLE
cherry pick changes for verify-install into 1.2 release

### PR DESCRIPTION
**Pull request by irisdingbj**

### CODE REVIEW

**Comment by howardjohn** [comment]
@irisdingbj it is much easier for reviewers and release managers (and you, maybe) if you cherry pick after merging. This way we don't have to go back and check if all the revisions on the master branch made it in, etc. 

For example, there are a few open comments on the master one. It is easier to fix them once then cherry-pick rather than fixing them in both places, or comments go on one and not the other and are lost, etc

**Comment by fpesce** [comment]
What is the master PR to this change?

**Comment by howardjohn** [comment]
Master PR are https://github.com/istio/istio/pull/14688
and
#14688

Both of these PRs changed on master (or at least the first one) though, so this needs to be updated @irisdingbj

**Comment by fpesce** [comment]
Fixes #14647

**Comment by howardjohn** [comment]
Already merged:
* https://github.com/istio/istio/pull/14799
* https://github.com/istio/istio/pull/14807 (not merged yet but about to be)

Going to close this

**Pull request closed without merging**
