### PR TITLE
[WIP]: Add the command 'gateway install' to install the ingress gateway

### PR DESCRIPTION
**Pull request by houshengbo**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
Hey @houshengbo, thansk for the PR! Can you add a link to a design doc or some discussion about this feature? I think I am a bit out of the loop and initially this does not seem directionally consistent with where we are trying to move Gateways (https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit?ts=5fa915aa#)

**Comment by houshengbo** [comment]
The design doc is here: https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit?ts=5fa915aa#heading=h.xw1gqgyqs5b.

**Comment by howardjohn** [comment]
@houshengbo I am a bit confused since I don't see how that design doc relates to this PR?

**Comment by ostromart** [comment]
Even without the long term plan to separate gw installation from the install manifest, I'm not sure why we'd need a specific command for gw, since these are already included in IstioOperator. Some kind of doc would be ideal, otherwise could you provide some rationale in this PR?

**Pull request closed without merging**
