### PR TITLE
Remove legacy coredns install in operator

### LINKED ISSUE #25925: Deprecate istio coredns plugin in favor of native envoy DNS
This issue tracks deprecation of the istio coredns plugin, not that we have native DNS support.

Requirements:
* Ensure we have feature parity
* Write a migration guide (can be upgrade notes, nothing too fancy needed)
* Ensure envoy DNS is as stable as coredns implementation
* Update documentation (is there even any for coredns?)
* Provide a 1+ release migration window with both supported

cc @rshriram

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/25925

We announced this in 1.8 release notes and istioctl warnings.

### CODE REVIEW

**Review by sdake — APPROVED** [review]
@howardjohn - overall PR is hard to review since it touches 192 files. It looks GTM, although I have added the proper WG for the approval of extensions and telemetry.

**Comment by hzxuzhonghu** [comment]
I am mostly concerned that the local dns requires xds-proxy enabled too. It is an alpha or pre-alpha feature.  Shouldn't we keep the istio-coredns for a while?

**Comment by howardjohn** [comment]
@hzxuzhonghu istio coredns is not an official istio product, is deprecated (https://github.com/istio-ecosystem/istio-coredns-plugin) and has had no updates in 2+ years. In accordance with https://istio.io/latest/blog/2020/addon-rework/, we will stop shipping external products with `istioctl install`. Users can still install them if they need to through other means

**Pull request merged**
