### PR TITLE
Add two sample deployments for user guide of Istio Vault integration [cherrypicked from release-1.1 branch]

### PR DESCRIPTION
**Pull request by lei-tang**
Add two sample deployments for user guide of Istio Vault integration.

This PR is cherrypicked from https://github.com/istio/istio/pull/12917 on the release 1.1 branch.

### CODE REVIEW

**Comment by frankbu** [comment]
Is this needed? Isn't branch `release-1.1` going to get merged into `master` anymore?

**Comment by lei-tang** [comment]
Based on https://github.com/istio/istio/pull/12685, the commits in release-1.1 are going to get merged into master branch.

**Comment by lei-tang** [comment]
Test comment.

**Comment by frankbu** [comment]
Closing since this is done already

**Pull request closed without merging**
