### PR TITLE
Skip push cds for sidecar when virtualService updated

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

VirtualService and Gateway both donot influence sidecar cds.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]
Thanks for adding that test

**Comment by howardjohn** [comment]
I recall we added this for a reason.. will try to see if I can find it and
if it still applies

**Comment by hzxuzhonghu** [comment]
@howardjohn How did you find the context? I will take a look. thanks

**Comment by howardjohn** [comment]
just vaguely remembered a PR about it and looked at git history

**Pull request merged**
