### PR TITLE
Re-set metadata if it is empty.

### PR DESCRIPTION
**Pull request by elfinhe**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by douglas-reid** [comment]
What is the motivation here?  What is the reason for making this change?

IIRC, this was intentionally NOT a sync.Once when when updated because Metadata retrieval had proven to be flaky, and there was a concern that if the initial retrieval failed, we wouldn't get the proper Metadata when needed.

Also, the way this is structured, we end up with nested sync.Once calls. That doesn't seem useful.

**Comment by elfinhe** [comment]
> What is the motivation here? What is the reason for making this change?
> 
> IIRC, this was intentionally NOT a sync.Once when when updated because Metadata retrieval had proven to be flaky, and there was a concern that if the initial retrieval failed, we wouldn't get the proper Metadata when needed.
> 
> Also, the way this is structured, we end up with nested sync.Once calls. That doesn't seem useful.

The logics are the same as the current one. The same issue could happen if metadata retrieval failed the logic won't update metadata in the second attempt because of the check at L140-144:
'''
	e.Lock()
	defer e.Unlock()
	if e.metadata != nil {
		return e.metadata
	}
'''

Can you expand with an example of why it will end up with nested sync.Once calls?

**Comment by douglas-reid** [comment]
I do not agree that the logic is the same. If there is a temporary metadata failure, we would expect that e.metadata would not get populated with any values, right?

But even if the logic was the same, then what is the value in changing it? I still don't understand the motivation here.

RE: nesting - the `parseGCPMetadata` uses `env.Once`.

**Comment by douglas-reid** [comment]
Whoops. Sorry, you are right. we should be checking that metadata is empty, not nil.

**Comment by elfinhe** [comment]
> Whoops. Sorry, you are right. we should be checking that metadata is empty, not nil.

yep, I will revert sync.Once. The original motivation is for readability, but now i guess it is only my personal preference.

I am proposing we start relying on this code to fetch GKE cluster info used in isito-agent without user input. It is nice to have you revisit this code here as well.

**Comment by elfinhe** [comment]
@douglas-reid can take one more round of review?

**Pull request closed without merging**
