### PR TITLE
Fix config package

### PR DESCRIPTION
**Pull request by douglas-reid**
Depends on https://github.com/istio/api/pull/356.

Removes problematic `mixer/pkg/config/proto` pkg.

Signed-off-by: Douglas Reid <douglas-reid@users.noreply.github.com>

### CODE REVIEW

**Comment by douglas-reid** [comment]
I cannot duplicate the linter errors locally. Nor can I diagnose a fix. Running `bin/fmt.sh` generates a bunch of changes to files, none of which are in this PR.

Thoughts?

**Comment by geeknoid** [comment]
What do you get if you run goimports/gofmt explicitly on the specific
source files:

mixer/template/sample/createinstance_test.go:1::error: file is not
goimported (goimports)
mixer/template/sample/createinstance_test.go:1::error: file is not gofmted
with -s (gofmt)
mixer/template/sample/template.gen_test.go:1::error: file is not goimported
(goimports)
mixer/template/sample/template.gen_test.go:1::error: file is not gofmted
with -s (gofmt)

**Comment by geeknoid** [comment]
I copied your tree and ran bin/fmt.sh and also saw a bunch of files being touched. This means we're not actually checking their format (and who knows what else we're not checking). *sigh*.

**Comment by douglas-reid** [comment]
@geeknoid https://github.com/istio/istio/issues/3198

When I run locally specifically on my files, I see absolutely no changes.  I am at a complete loss.

**Comment by geeknoid** [comment]
I'm looking into the formatting problem. We're not detecting errors we
should.

**Comment by douglas-reid** [comment]
Switching back from a `go version go1.10rc1`  to a `go version go1.9.2`, I was able to find the linter issue.

Fixed with this diff (hopefully):
```
$ git diff mixer/template/sample/createinstance_test.go
diff --git a/mixer/template/sample/createinstance_test.go b/mixer/template/sample/createinstance_test.go
index c67b9446..980c8dfc 100644
--- a/mixer/template/sample/createinstance_test.go
+++ b/mixer/template/sample/createinstance_test.go
@@ -687,7 +687,7 @@ func generateReportTests() []createInstanceTest {
        emptyFieldsParam := sample_report.InstanceParam{
                // missing all fields
                Res1: &sample_report.Res1InstanceParam{
-                       // missing all fields
+               // missing all fields
                },
        }
        t = createInstanceTest{
$ git diff mixer/template/sample/template.gen_test.go
diff --git a/mixer/template/sample/template.gen_test.go b/mixer/template/sample/template.gen_test.go
index 1ab7e534..00e69618 100644
--- a/mixer/template/sample/template.gen_test.go
+++ b/mixer/template/sample/template.gen_test.go
@@ -1086,7 +1086,7 @@ func TestProcessReport(t *testing.T) {
                                "foo": &sample_report.InstanceParam{
                                        // missing all fields
                                        Res1: &sample_report.Res1InstanceParam{
-                                               // missing all fields
+                                       // missing all fields
                                        },
                                },
                                "bar": &sample_report.InstanceParam{
```

**Comment by douglas-reid** [comment]
how can the PR pass everything and then fail everything on the re-verification run of the tests? i feel like i'm taking crazy pills.

**Comment by ldemailly** [comment]
> Switching back from a go version go1.10rc1 to a go version go1.9.2, I was able to find the linter issue.

hmmm maybe we need to stay on 1.9 for a while ? (cc @costinm )

**Pull request merged**
