### PR TITLE
fix debian minikube install

### PR DESCRIPTION
**Pull request by m1093782566**
Fixes:

* use `apt-get install -y` to avoid input prompt.

* use curl -L -o to download docker-ce.deb

* install libltdl7 since docker-ce depends on it.

### CODE REVIEW

**Comment by sdake** [comment]
@m1093782566 Nice job on your first contribution!  looks good - nice catch!  Begs the question, is this currently used.

/lgtm
/approve

**Comment by m1093782566** [comment]
@sdake 

Yes, we are currently using minikube to deploy a local test environment - therefore I can find some nits.

**Comment by m1093782566** [comment]
@gargnupur

Would you please give a `/approve` label? I assume  Approver should have the privilege.

**Comment by m1093782566** [comment]
/assign @costinm 

for approval :)

**Pull request merged**
