### PR TITLE
Add release-note instruction.

### PR DESCRIPTION
**Pull request by yutongz**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

Add instruction about how to get collect release-note from PR description.

Should merge after https://github.com/istio/test-infra/pull/441

### CODE REVIEW

**Comment by ldemailly** [comment]
thx !
/lgtm

**Comment by yutongz** [comment]
@ldemailly Do you know why this test failed?

**Comment by ldemailly** [comment]
some connection error:

W0929 00:30:29.029] W0929 00:30:29.027468     891 mixer_test.go:684] Error communicating with http://35.188.246.118/productpage: Get http://35.188.246.118/productpage: dial tcp 35.188.246.118:80: i/o timeout

was there a network outage ?

**Comment by ldemailly** [comment]
or maybe we ran out of ip/firewalls again - did we ever find out why we seem to leak them?

**Comment by yutongz** [comment]
Right before this error message, it shows all pods are ready and running, it's wired.
Quota is fine. But yes, it seems when delete a cluster, GCP didn't properly handle some of the resources, not only firewall rule, but also forwarding rule and target pools.

**Pull request merged**
