### PR TITLE
Update pr template for more clear instruction

### PR DESCRIPTION
**Pull request by yutongz**
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yutongz** [comment]
@ldemailly

**Comment by ldemailly** [comment]
ps: does the git command line know about this ? or is that just a github ui stuff that many people won't know about ? does the github desktop client know ?

pps: can the bot auto put lgtm if I github approved ?

**Comment by ldemailly** [comment]
> /test all [submit-queue is verifying that this PR is safe to merge]
why is that necessary ? it was already being tested

we should try to keep bot message traffic minimal, it generates notifications each time there is an update, that one is just noise (imo)

**Comment by yutongz** [comment]
What did "it" means in your first comment, pr template or release-note in pr description?

About letting robot reads github approve, well, the main concern is we don't want to confuse people by having two system related to each other. Ideally we should gradually roll out from github approval like the way k8s folks do. But we don't need to push that right now cause I understand sometimes people want one change get in really fast to avoid blocking other stuff. We can keep two systems but don't want to mix them up. 
I understand it's a little bit inconvenient to approve twice, actually, I am think about auto adding "approved" plus "lgtm" when people say "/approve".

About the bot messages, at least for the "test all" message, it is the way mungegithub triggers prow to rerun tests. About other messages, you made the point, some of messages are not really useful, I did think about remove some of them. But the difficulty is, we don't own that code, the thing we can do is trying to ask k8s folks if we can make that configurable.

**Comment by ldemailly** [comment]
bot said:

> /test all [submit-queue is verifying that this PR is safe to merge]

I asked : 

>> why is that necessary ? it was already being tested

you replied (I think) : 

>>> What did "it" means in your first comment, pr template or release-note in pr description?

it is this PR, the tests were already running, like they do on any pr done by someone already in the org, so not sure what that bot message was doing (beside noise) - but maybe it's for the case the PR wouldn't have been from the org ?


About the Github UI - it has a review tab that people do use to leave feedback on the PR, the bots aren't / can't replace that - and it also has a conclusion : 
screen shot 2017-08-22 at 4 15 31 pm

I think we should preserve the meaning of the settings there. ie approve == /lgtm

**Pull request merged**
