### PR TITLE
Fix dual-stack TestIngress/status postsubmit test failure

### PR DESCRIPTION
**Pull request by kfaseela**
**Please provide a description of this PR:**

Fixes: https://github.com/istio/istio/issues/49300

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM especially for short term. Do we know why it randomly started failing? Should we improve to check all IPs in dualstack mode -- I think this test would pass if we only wrote 1 IP but we are supposed to write 2, right? I think the code is correct btw, just the test doesn't verify that fully

**Comment by kfaseela** [comment]
> LGTM especially for short term. Do we know why it randomly started failing? Should we improve to check all IPs in dualstack mode -- I think this test would pass if we only wrote 1 IP but we are supposed to write 2, right? I think the code is correct btw, just the test doesn't verify that fully

Yes, the test framework does not seem to support dual-stack for the default ingress part. So @leosarra will take a look and fix it properly, so that we check both the IPs as part of the test for long term. Did we change anything anywhere so that the cluster became v6 first? Usually in such cases is where the order of the IP changes, here, consistently the v6 IP was listed down first, and v4 next which made the test fail. However when I run the test locally, the failure is not observed, because the v4 ip is always first for the loadblanacer ingress

**Comment by kfaseela** [comment]
@leosarra : Probably this needs to be enhanced so that we can check all the IPs: https://github.com/istio/istio/blob/master/pkg/test/framework/components/istio/ingress/interface.go#L39

**Comment by kfaseela** [comment]
> LGTM especially for short term. Do we know why it randomly started failing? Should we improve to check all IPs in dualstack mode -- I think this test would pass if we only wrote 1 IP but we are supposed to write 2, right? I think the code is correct btw, just the test doesn't verify that fully

https://github.com/istio/istio/issues/49344

**Pull request merged**
