### PR TITLE
envoy: use new connection pool

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]
Thanks! I thought we reverted it when doing 1.11 proxy sha update..

**Comment by kyessenov** [comment]
Yes, it was a mistake to ship it in 1.11, so we should patch it now.

**Comment by jwendell** [comment]
Not sure I understand. This was explicitly changed before 1.11 because of issues: https://github.com/istio/istio/pull/33473

Now we are adding it it back to 1.11?

**Comment by howardjohn** [comment]
This seems risky to add in patch release

**Comment by kyessenov** [comment]
@jwendell The upstream breaking change has long been fixed and the remediation is not necessary. It should have been removed when proxy was updated. The risk is that the override we apply triggers code that is no longer default in Envoy and about to be removed. We will not be able to apply future bug fixes for this portion of the code in Envoy.

**Comment by jwendell** [comment]
@kyessenov  We are currently using commit `release: v1.19.0` in 1.19 branch: https://github.com/envoyproxy/envoy/commits/release/v1.19

Is it this one when you say `has long been fixed`?

**Comment by kyessenov** [comment]
@jwendell The fix is linked into the istio issue: https://github.com/envoyproxy/envoy/pull/16993 from Jun 15.

**Pull request merged**
