### PR TITLE
remove duplicated condition in gateway.

### PR DESCRIPTION
**Pull request by morvencao**
Remove duplicated condition in gateway, since they have defined in `requirements.yaml`

### CODE REVIEW

**Comment by ymesika** [comment]
So what's the purpose of `.Values.enabled`? Can it be removed from the values.yaml?

**Comment by morvencao** [comment]
@ymesika I think `enabled ` field can be remove from `values.yaml` for each subchart, while it should be kept in top parent’s `values.yaml`, because we need it in `requirements .yaml`.

**Comment by sdake** [comment]
@morvencao I believe the subtly of these configuration options are difficult to understand.  IIRC, the objective was to permit all services to be enabled and disabled independently of whether or not the gatways are enabled or enabled.

Use Case: Enable all addons, but only eanble gateways for kiali and grafana.

I think this PR breaks that use case.  If not, I'd suggest opening against master, as release-1.1 is frozen without an issue ticket.

Cheers
-steve

**Comment by jmazzitelli** [comment]
> IIRC, the objective was to permit all services to be enabled and disabled independently of whether or not the gatways are enabled ... Use Case: Enable all addons, but only eanble gateways for kiali and grafana.

This is correct. This PR breaks that functionality. It was requested (I forget by whom) that we provide a way to enable the addons independently of whether or not some or all are exposed via the gateway. That feature goes away if we merge this PR.

**Comment by sdake** [comment]
/hold

Holding until we can sort out what the proper behavior should be from other reviewers.

Sadly I don't recall who requested this functionality.  @douglas-reid any ideas?

**Comment by morvencao** [comment]
Thanks @sdake

**Pull request closed without merging**
