### PR TITLE
group manifestSet contents by component type

### LINKED ISSUE #53875: Upgrade from 1.23 to 1.24 incomplete
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are running version 1.23.2 of Istio and we have two ingress-gateways installed. We built our operator manifest for installation. When we tried to upgrade to 1.24.0, the installation never completed and it got stuck at installing the second gateway which has deployment and service overlay. So we ended up with one gateway updated to 1.24 and the other is still on 1.23. No debug logs showed me why it was stuck. Please advise. 

### Version

```Text
❯ istioctl version
client version: 1.24.0
istiod version: 1.23.2
istiod version: 1.24.0
data plane version: 1.23.2 (2 proxies), 1.24.0 (26 proxies)
> ❯ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.2-eks-7f9249a
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ilrudie**
**Please provide a description of this PR:**

fixes https://github.com/istio/istio/issues/53875

### CODE REVIEW

**Comment by howardjohn** [comment]
I believe we have tests that exercise this code path, maybe we can add one with multiple gateways

**Comment by ilrudie** [comment]
100% agree John, I left it in draft while I figure out the best way to test this to ensure we don't regress

**Review by howardjohn — APPROVED** [review]

**Review by howardjohn — CHANGES_REQUESTED** [review]
This makes the output non-deterministic due to the map ordering. Can we make sure we have stable ordering

**Review by howardjohn — APPROVED** [review]
NVM, did a bad test

**Pull request merged**
