### PR TITLE
Add updating of distroless image to update_deps.sh

### LINKED ISSUE #30796: [release-1.9] Add updating of distroless image to update_deps.sh
Manual cherrypick required.

#30778 failed to apply on top of branch "release-1.9":
```
Applying: run UPDATE_BRANCH=master ./bin/update_deps.sh; make gen
Using index info to reconstruct a base tree...
M	go.mod
M	go.sum
M	istio.deps
M	prow/release-commit.sh
Falling back to patching base and 3-way merge...
Auto-merging prow/release-commit.sh
CONFLICT (content): Merge conflict in prow/release-commit.sh
Auto-merging istio.deps
CONFLICT (content): Merge conflict in istio.deps
Auto-merging go.sum
CONFLICT (content): Merge conflict in go.sum
Auto-merging go.mod
CONFLICT (content): Merge conflict in go.mod
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 run UPDATE_BRANCH=master ./bin/update_deps.sh; make gen
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by xichengliudui**
cherry-pick 2342789b76
Fixes #30796

### CODE REVIEW

**Review by shamsher31 — APPROVED** [review]

**Comment by jacob-delgado** [comment]
@googlebot I consent.

**Pull request merged**
