### PR TITLE
Remove ForCA from CsrRequest.

### PR DESCRIPTION
**Pull request by myidpt**
ForCA is not used by Citadel any more.

Instead, Citadel decides whether to sign certificate for workload or CA from the flag `sign-ca-certs`:
https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L218

### CODE REVIEW

**Comment by myidpt** [comment]
@incfly Clarified in the description. Basically ForCA is not used. Citadel takes a flag for signing certs for CA. If so, the secret controller and CA server will request signing a CA cert when calling ca.Sign().

**Comment by incfly** [comment]
@myidpt and so we'll only use fields from `csr_pem` to determine whether it's for CA or not?

**Comment by myidpt** [comment]
@incfly `CsrRequest.csr_pem` does not have a field "ForCA". Actually, the node agent has no control to choose whether the requested cert is for a CA or workload. We control this on the CA. If the CA has `sign-ca-certs=true`, every cert it signs is a CA cert, otherwise, every cert it signs is a workload cert. Does this make sense?

**Pull request merged**
