### PR TITLE
Makes Waypoint TopologySpreadConstraints, Tolerations & NodeSelector Configurable

### LINKED ISSUE #52901: Install: Makes Waypoint TopologySpreadConstraints, Tolerations & NodeSelector Configurable
**Describe the feature request**
Provide the ability to customize waypoint deployment topology spread constraint, tolerations & nodeSelector during installation through Helm values.
I have already done the code here: https://github.com/istio/istio/compare/master...bmagic:istio:feature/waypoint-scheduling-options
I'm waiting for your approval to open a PR here. 

**Describe alternatives you've considered**

- Manually reconfiguring configmap/static-waypoint-config with the necessary config.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
This request is similar to https://github.com/istio/istio/issues/51496 & https://github.com/istio/istio/issues/52883

### PR DESCRIPTION
**Pull request by bmagic**
**Please provide a description of this PR:**
Provide the ability to customize waypoint deployment topology spread constraint, tolerations & nodeSelector during installation through Helm values.

Fix #52901

### CODE REVIEW

**Comment by bmagic** [comment]
I pushed a modification because the indentation wasn't good (but functional) and didn't match what had been done with the affinities.

**Comment by bmagic** [comment]
I have to use `.Values.global.` to have something functionnal. 

I've also corrected affinity, which wasn't working for me without `.global`.
https://github.com/istio/istio/pull/52919/files#diff-bd23661d98745c4cf580be1d1ee08e08572867f1d8ca535883c06aaa591b5760R71

**Review by howardjohn — APPROVED** [review]

**Comment by zhuoyang** [comment]
How is label selector in TopologySpreadConstraints handled here? Ideally we would need to inject in the label for that specific instance of waypoint right?

**Comment by howardjohn** [comment]
@zhuoyang see here for guaranteed resource name and label values: https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#resource-attachment-and-scaling

**Comment by zhuoyang** [comment]
@howardjohn I understand there's a guaranteed label, but in the case of more than one waypoint deployed it is impossible to specify the correct topologySpreadConstraints label for both waypoint in the helm values

**Comment by howardjohn** [comment]
@zhuoyang ah yes, that is true. a global config would not be appropriate for things that need the label.

One thing the design of the PR left room for is to apply templating to the override. So then you could do something like `label: {{.Name}}` or similar

**Comment by zhuoyang** [comment]
Had a quick look at the code, it seems like the gateway templating uses sprig template function, which doesn't support `tmpl` like helm template does, we can definitely reimplement the function, but I am not sure if that's the way moving forward.

**Pull request merged**
