### PR TITLE
test framework: centralistio retry patch custom host

### PR DESCRIPTION
**Pull request by stevenctl**
This may help with #25659

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
Should we be retrying the IP lookup not the patch?

**Comment by stevenctl** [comment]
> I don't see failed to patch istiod with in the logs, am I looking int the wrong place?

Since we're patching in the errgroup, if it fails we won't see it till the entire group finishes which is hanging on the istio deploy.

**Comment by stevenctl** [comment]
> Should we be retrying the IP lookup not the patch?
I think that's already the case

**Pull request closed without merging**
