### PR TITLE
Use fake kubeconfig in addtomesh test

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/16639

### CODE REVIEW

**Comment by howardjohn** [comment]
@esnible 
https://github.com/istio/istio/blob/53691c3cea725e4a9ce76ab21efded032f1035fe/istioctl/cmd/root.go#L170-L182

is the problem. It happens after that code. Its about setting up the namespace it seems

I don't follow the code well since there's a bunch of globals and stuff so I didn't have time to find a better solution

**Comment by esnible** [comment]
I can reproduce this locally.  I am working on a non-hacky fix I will complete this weekend.

**Comment by howardjohn** [comment]
thanks!

**Comment by irisdingbj** [comment]
@howardjohn @esnible I have the fix ready at https://github.com/istio/istio/pull/16745. Please help review. Thanks!

**Comment by howardjohn** [comment]
#16752

**Pull request closed without merging**
