### PR TITLE
Consolidate on a single diff library

### PR DESCRIPTION
**Pull request by howardjohn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by douglas-reid** [comment]
curious: any reason to prefer `cmp.Diff` to `messagediff.PrettyDiff` ?

**Comment by howardjohn** [comment]
> curious: any reason to prefer cmp.Diff to messagediff.PrettyDiff ?

Mostly because we use it in a lot more places. It also has special support for protobuf which may or may not be helpful

**Comment by mandarjog** [comment]
Pretty diff was significantly better. when I was working on proto encoder, pretty diff output was much easier to read.
Can you paste output from this in the affected cases?

**Comment by kyessenov** [comment]
Please just use the official `go-cmp/cmp` that works with `testing/protocmp` and don't reinvent the wheel. Protobuf equality is complicated with floats and unknown fields, and most solutions are half-baked.

**Comment by howardjohn** [comment]
@kyessenov I wasn't clear if you were saying this PR should do that instead, or agreeing this is the right direction, but to clarify, this will now move us towards go-cmp/protocmp.

**Comment by mandarjog** [comment]
he is suggesting continue using google official packages, go-cmp/protocmp, I agree. I was not aware of the official nature.

**Review by mandarjog — APPROVED** [review]
Lgtm

**Review by nmittler — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
