### PR TITLE
Sidecar readiness: handle wildcard addresses

### LINKED ISSUE #13067: Sidecar readiness doesn't handle inbound wildcard addresses
Taken from https://github.com/istio/istio/issues/9504#issuecomment-479981385.

The readiness logic for checking application ports doesn't appear recognize wildcard addresses (`0.0.0.0`) as inbound:

```
kind: Deployment
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      k8s-app: echo
  template:
    metadata:
      labels:
        k8s-app: echo
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: echo-service
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
  selector:
    k8s-app: echo

NAME                   READY   STATUS    RESTARTS   AGE
echo-95894744f-72kdn   2/2     Running   0          2m
echo-95894744f-7dwst   2/2     Running   0          2m
echo-95894744f-c84fv   1/2     Running   0          2m
echo-95894744f-cdsc5   1/2     Running   0          2m
echo-95894744f-fr9bn   1/2     Running   0          2m
echo-95894744f-ftbfw   2/2     Running   0          2m
echo-95894744f-hfbgm   2/2     Running   0          2m
echo-95894744f-hvpk7   2/2     Running   0          2m
echo-95894744f-ks7vf   2/2     Running   0          2m
echo-95894744f-kvbd5   2/2     Running   0          2m
echo-95894744f-mdl86   2/2     Running   0          2m
echo-95894744f-nckdf   1/2     Running   0          2m
echo-95894744f-nfm8f   2/2     Running   0          2m
echo-95894744f-nz4mn   1/2     Running   0          2m
echo-95894744f-p74mq   1/2     Running   0          2m
echo-95894744f-stz7s   2/2     Running   0          2m
echo-95894744f-vrfjl   1/2     Running   0          2m
echo-95894744f-whn64   2/2     Running   0          2m
echo-95894744f-zcsbl   2/2     Running   0          2m
echo-95894744f-zjcp7   1/2     Running   0          2m

$ k logs -f echo-95894744f-vrfjl -c istio-proxy

* failed checking application ports. listeners="0.0.0.0:15090","10.0.5.201:443","10.0.2.108:15029","10.0.10.235:42422","10.0.9.253:443","10.0.11.84:8443","10.0.5.153:15011","10.0.2.108:443","10.0.2.108:31400","10.0.2.108:15443","10.0.2.210:443","10.0.0.10:53","10.0.3.24:443","10.0.0.1:443","10.0.0.13:443","10.0.2.108:15030","10.0.4.88:443","10.0.2.108:15031","10.0.2.108:15032","10.0.3.222:80","10.0.2.108:15020","10.0.3.24:15443","0.0.0.0:15010","0.0.0.0:15004","0.0.0.0:80","0.0.0.0:9901","0.0.0.0:9091","0.0.0.0:8060","0.0.0.0:8080","0.0.0.0:15014","0.0.0.0:15001"
* envoy missing listener for inbound application port: 8080
```

It's not immediately clear if Pilot changes have introduced this issue, but the readiness logic should account for it.

### PR DESCRIPTION
**Pull request by nmittler**
Fixes #13067

### CODE REVIEW

**Comment by nmittler** [comment]
@costinm @rshriram This attempts to address #13067, where a user was seeing an Envoy listener for `0.0.0.0:8080`, but the readiness probe was failing when looking for inbound port `8080`.

This was because the readiness logic was looking for `podIP:8080` rather than `0.0.0.0:8080`. Apparently a listener for `podIP:8080` is received and the readiness succeeds. Do you know what might be happening here? Is this fix correct?

**Comment by rshriram** [comment]
as I noted in that issue, there is no case where Pilot generates wildcard inbound listeners. Inbound listeners are generated only for the pod IP

**Comment by nmittler** [comment]
Closing this as it turns out not to be an issue with the readiness logic, since the sidecar would eventually get the config from Pilot.  #13106 has been opened to address the underlying issue.

**Pull request closed without merging**
