### PR TITLE
Revert #19270 and remove flaky label

### PR DESCRIPTION
**Pull request by pitlv2109**
Replace for #19279 and remove flaky label for ingress sds tests (have them run as part of presubmit tests).

### CODE REVIEW

**Comment by pitlv2109** [comment]
@howardjohn  @JimmyCYJ ingress sds tests passed as part of presubmit. I'll rebase the PR soon to pick up the change that fix the gencheck test.

**Comment by howardjohn** [comment]
Tests now takes over an hour, so I think this is not reasonable to merge

**Comment by pitlv2109** [comment]
> Tests now takes over an hour, so I think this is not reasonable to merge

This is what happens if you add more tests (assuming you don't change anything to the tests), right? The sds ingress test suite adds about 15 minutes to the whole test run. https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/19329/integ-security-k8s-tests_istio/4657/build-log.txt.

@JimmyCYJ do you think it's bad to not have these tests as part of presubmit?

**Comment by howardjohn** [comment]
Yes its just as a result of adding more tests, but its not acceptable to have tests that run over an hour long. The security tests are already way to long as is

**Comment by pitlv2109** [comment]
> Yes its just as a result of adding more tests, but its not acceptable to have tests that run over an hour long. The security tests are already way to long as is

I think one of the main reasons is because we have many tests compared to other part of Istio and we want to keep a good coverage. Hopefully native Citadel can help in the future. Anyway, I removed the tests from presubmit so this PR is just a revert of the other PR. I'll file an issue to track the presubmit thing.

**Comment by JimmyCYJ** [comment]
> I think one of the main reasons is because we have many tests compared to other part of Istio and we want to keep a good coverage. Hopefully native Citadel can help in the future. Anyway, I removed the tests from presubmit so this PR is just a revert of the other PR. I'll file an issue to track the presubmit thing.

Yes, we are trying to keep cover every ingress SDS flow using one integration test. The ingress SDS tests are consuming reasonable times. In the coming 1.5, we will have more integration tests for new security features. Perhaps we can split the security tests into several jobs.

**Comment by JimmyCYJ** [comment]
> @JimmyCYJ do you think it's bad to not have these tests as part of presubmit?

The bad effect is that a PR that breaks the ingress SDS could get merged, and we need to manually trace test failures in test grids to identify the PR.

**Pull request merged**
