### PR TITLE
Fix linter by removing unused tests that don't compile

### PR DESCRIPTION
**Pull request by howardjohn**
This is a cleanup but I also think this is breaking the linter because
it doesn't build.

### CODE REVIEW

**Review by geeknoid — APPROVED** [review]

**Comment by howardjohn** [comment]
Wow so basically this test failed to build, which caused the linter to ignore all errors for a month. See https://github.com/golangci/golangci-lint/issues/866
I just sent another commit with fixes for all the lint errors that have stacked up

**Review by rlenglet — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Review by sdake — APPROVED** [review]

**Review by incfly — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
