### PR TITLE
Add delete configmap privilege to fix distribution report cleanup

### PR DESCRIPTION
**Pull request by luksa**
This fixes the following error during istiod shutdown when PILOT_ENABLE_STATUS=true:

error   status  failed to properly clean up distribution report: configmaps "istiod-649887579d-rck66-distribution" is forbidden: User "system:serviceaccount:istio-system:istiod" cannot delete resource "configmaps" in API group "" in the namespace "istio-system"

### CODE REVIEW

**Comment by luksa** [comment]
/hold 

I'll move the privilege to the Role

**Review by howardjohn — APPROVED** [review]

**Comment by jewertow** [comment]
@luksa could you add a "bug-fix" release note?

**Comment by luksa** [comment]
@jewertow What's the correct [area](https://github.com/istio/istio/tree/master/releasenotes#area) for the release note?

**Comment by jewertow** [comment]
Good question... You modify helm templates, so I would say this is installation area.

**Review by jewertow — APPROVED** [review]

**Pull request merged**
