### PR TITLE
envoy: move integration testing to istio/istio

### PR DESCRIPTION
**Pull request by kyessenov**
Change-Id: I1c5c71e15da4f2d229aaa4f5c95640ffb297990a

Complement to https://github.com/istio/proxy/pull/5787

### CODE REVIEW

**Comment by howardjohn** [comment]
why do we want to dettach the test from the thing we are testing? I get it if we kill istio/proxy but it's not clear we will actually do that or on what timeline, seems we could make this the last step? 

worried these become a slow, flaky test that isn't testing code in this repo and maintainers of this repo don't have ownership over. If we are moving Istio code to envoy why are we not moving the tests along with it?

**Comment by kyessenov** [comment]
Forgot to mention. The value of this is two fold: 1) consolidate Go code maintenance to one repo (Proxy is pure C++), 2) prepare Istio Proxy to be closer to merge able state with upstream Envoy.

**Comment by howardjohn** [comment]
> When we add an extension to Envoy, we have to write C++ tests so this Go framework cannot be ported. When an extension is migrated to upstream, the associated test in this PR can be deleted. I don't think there's any material change within Istio org with the move.

Is it not a requirement to add new code into Envoy that it is tested? Wouldn't they want these tests in Envoy?

**Comment by kyessenov** [comment]
> Is it not a requirement to add new code into Envoy that it is tested? Wouldn't they want these tests in Envoy?

Yes, but the tests must be C++. These go tests will be deleted once Istio filters are upstreamed.

**Comment by howardjohn** [comment]
>  These go tests will be deleted once Istio filters are upstreamed.

But they are (or rather, moving them -- they are fine in istio/proxy) useless until they are upstreamed? So why not just move them directly to envoy

**Comment by kyessenov** [comment]
I don't understand - the current Istio Envoy extensions have no tests except Go tests. However, they don't change much, so there's no point in rewriting Go tests to C++ as-is. We can delete these tests from both places as well, but there'll be some coverage loss.

**Comment by howardjohn** [comment]
Doesn't "Yes, but the tests must be C++. These go tests will be deleted once Istio filters are upstreamed." imply we will need to port these tests to C++ in order to get them into envoy?

**Comment by kyessenov** [comment]
> Doesn't "Yes, but the tests must be C++. These go tests will be deleted once Istio filters are upstreamed." imply we will need to port these tests to C++ in order to get them into envoy?

The filters have to be rewritten from scratch since they are too Istio specific. Both tests and code need to be rewritten.

**Comment by howardjohn** [comment]
Is this right:

**Current state:** code and tests in istio/proxy
**Proposed middle state:** code in istio/proxy, tests in istio/istio
**End state:** code and tests in envoyproxy/envoy

?

if so, I don't get why we need the middle state at all...?

**Comment by kyessenov** [comment]
Like any cleanup - it's not necessary, but it helps to turn down Go development in istio/proxy and corresponding CI jobs.

**Comment by dhawton** [comment]
I'm in agreeance with John here. One thing I kind of fear is, and we see it in docs every minor release cycle (ie https://github.com/istio/istio.io/pull/15595 which is blocking PRs from merging into master), changes occurring in Envoy or istio/proxy that result in broken tests, and we end up with PRs getting stuck until someone gets caught up with the changes and fixes the test. If it's in another repo, it's easy to forget. Why not leave it in istio/proxy until it's upstreamed and no longer needed, then dropped? It feels to me to keep the tests in the same repo as the code they're testing.

**Comment by dhawton** [comment]
> @dhawton Isn't that consistent with my argument? istio/proxy is effectively archived, almost no changes come in there and no one is paying attention to the fixes with regards to go upkeep (see failures here with go linters, etc). If we do want tests, they need to be kept up, and the best place to do it is in the main repo. Besides, if one day we delete istiod/repo, we still need some place to run tests to at least evaluate conformance against the old test suite, so the tests will naturally outlast the source code.

I'd argue that moving the tests away from the code they test is not going to help with upkeep. You end up with a situation of istio/proxy getting a change and the test here not reflecting it, getting missed, etc. Changing the golinter affects multiple repos. I'd like to see the tests kept with the code they're testing. If we need e2e testing once it's upstreamed to Envoy, then sure. But if it's testing of what is in istio/proxy, I'd argue that is more confusing and more likely to lead to unmaintained tests. We see it in istio.io all the time. Code changes made to istio/istio break docs tests, and the docs team is left trying to figure out what changed, what broke, and what needs to be fixed and get them fixed so other PRs can continue merging. Moving tests for istio/proxy to istio/istio just opens that can of worms here. My personal opinion.

**Comment by kyessenov** [comment]
The tests that are added are integration, black-box tests. They are no different in substance than any other integration test in Istio.  All that you mentioned already happen, e.g. when upstream Envoy makes a subtle behavior change that breaks Istio integrations.

**Comment by hzxuzhonghu** [comment]
I also think if some integration test is missing from istio side, should add tests in black box. Not separating istio/proxy code and test.

**Comment by kyessenov** [comment]
OK, there seems to be some misunderstanding about the tests in Istio/proxy. They are Istio tests not extension tests, but adding them as Istio integration tests would quickly overwhelm the CI due to all the edge cases. I'll close this PR, but do keep in mind that we will delete those files eventually as we're migrating to upstream, so Istio needs to create black box tests to keep the coverage.

**Pull request closed without merging**
