### PR TITLE
Cherrypick #20555(INSERT_FIRST) and #20592(Remove mxc hack)

### PR DESCRIPTION
**Pull request by gargnupur**
Cherrypick #20555(INSERT_FIRST) and #20592(Remove mxc hack)
Also updates istio/api to release-1.5

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by ayj — APPROVED** [review]

**Comment by howardjohn** [comment]
@jasonwzm any reason we do https://github.com/istio/istio/blob/22b1cdcec8b872156f6ae75fcaadfb8b8e960141/bin/update_crds.sh#L41 instead of just `git clone && git checkout $SHA`? Seems like this is causing some weird behavior

**Comment by howardjohn** [comment]
I tried this locally and it failed too so I am not really sure why/how it worked before? Maybe it only works for SHAs on the master branch or something?

**Comment by fpesce** [comment]
Same comment than @howardjohn 
```
git clone "https://github.com/istio/api" . && git merge $SHA
```
instead of the git init... git merge line would work.

**Comment by gargnupur** [comment]
@fpesce @howardjohn : trying "git clone "https://github.com/istio/api" . && git merge $SHA" then...

**Comment by fpesce** [comment]
> @fpesce @howardjohn : trying "git clone "https://github.com/istio/api" . && git merge $SHA" then...

has been implemented here -> @gargnupur https://github.com/istio/istio/pull/20682

**Pull request merged**
