### PR TITLE
Incorporate API changes in SIdecar resource

### PR DESCRIPTION
**Pull request by nrjpoddar**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by esnible — APPROVED** [review]

**Comment by nrjpoddar** [comment]
@esnible do we need a release note for analyzer being removed? I'm not sure since this was always hidden and never implemented.

**Review by howardjohn — APPROVED** [review]

**Comment by nrjpoddar** [comment]
Closing as #25677 has changes from this PR.

**Pull request closed without merging**
