### PR TITLE
Remove DNS search namespace from injection

### PR DESCRIPTION
**Pull request by sdake**
[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by sdake** [comment]
https://github.com/istio/istio/pull/25349/

**Review by dgn — APPROVED** [review]
just needs a `make gen`

**Pull request merged**
