### PR TITLE
add validation for local origin errors

### PR DESCRIPTION
**Pull request by ramaraochavali**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
When SplitExternalLocalOriginErrors set, does `Consecutive_5Xx` takes effect?

**Comment by ramaraochavali** [comment]
> When SplitExternalLocalOriginErrors set, does Consecutive_5Xx takes effect?

Yes it does unless we set it to zero

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
