### PR TITLE
go get cloud.google.com/go/compute

### PR DESCRIPTION
**Pull request by therealmitchconnors**
needed for bugfix in v1.9.0.  master updated in #40597

### CODE REVIEW

**Review by lei-tang — APPROVED** [review]

**Comment by ericvn** [comment]
Not sure if this needs the updated 1.13 build tools image, but I notice the RMs haven't allowed the new image to merge. I do think it related to a new gcloud version.

**Comment by Random-Liu** [comment]
In k8s, it just check the local file /sys/class/dmi/id/product_name to decide whether it is on GCE or not
https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/gcp/metadata.go#L137

Could istio reuses the same logic?

**Pull request merged**
