### PR TITLE
fix gateway validation for tcp termination

### PR DESCRIPTION
**Pull request by ramaraochavali**
Gateway validation incorrectly rejects TCP protocol with TLS settings.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ramaraochavali** [comment]
The following gateway definition fails with validation error `server cannot have TLS settings for non HTTPS/TLS ports` which I think is incorrect because TCP can have TLS certs for termination.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: ns`
  resourceVersion: "2761351996"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: tcp-secure-2222
      number: 2222
      protocol: TCP
    tls:
      caCertificates: /server-certs/ca.pem
      mode: SIMPLE
      privateKey: /server-certs/server/keys/server-key.pem
      serverCertificate: /server-certs/server/certificates/server.pem
```

**Comment by ramaraochavali** [comment]
@howardjohn can you PTAL?

**Comment by rshriram** [comment]
So that is intentional. if you want TLS settings, mark the port as a TLS port (termination or otherwise). Is that breaking something for you?

**Comment by ramaraochavali** [comment]
@rshriram Thank you. I did not try with setting protocol as `TLS` because the [TLS port](https://github.com/istio/api/blob/master/networking/v1alpha3/gateway.proto#L480) says it does not terminate. I can try setting to TLS and will close this PR.

Thanks again

**Comment by ramaraochavali** [comment]
@rshriram Changed to TLS and ingress gateway config seems to be generated correctly. Have n't tested the flow, but I think we are good. Will reopen if there is any other issue.

**Pull request closed without merging**
