### PR TITLE
Ingress Conversion should retain namespace

### PR DESCRIPTION
**Pull request by esnible**
Resolves Issue 5817

### CODE REVIEW

**Comment by linsun** [comment]
seems useful and low risk for 0.8, i'd vote to get it in @costinm

**Comment by linsun** [comment]
@costinm @hklai if there is another 0.8 build, I would like to get this in.

Every user will hit this when moving to 0.8 and use the converter tool.

**Comment by linsun** [comment]
ok opened a release note limitation for this. let's get this in for 0.8.1 @costin @hklai 

https://github.com/istio/istio.github.io/pull/1401

**Comment by esnible** [comment]
Closing in favor of https://github.com/istio/istio/pull/5973 .  That one was targeted against _release-0.8_ and had merge conflicts when I attempted to rebase against _master_.

**Pull request closed without merging**
