### PR TITLE
Remove dead code in kubeyaml_test.go

### PR DESCRIPTION
**Pull request by selmanj**
Fixes failure in https://github.com/istio/istio/pull/19048

### CODE REVIEW

**Comment by jasonwzm** [comment]
interesting the master PR linter did not catch this.

**Comment by sushicw** [comment]
> interesting the master PR linter did not catch this.

This is a known issue, I've run into it a few times as well. For some reason the 1.4 linter is more restrictive than what's in master.

**Comment by selmanj** [comment]
Abandoning this change - I'm going to revert the PR that left this code dead. See #19045 for more details.

**Comment by selmanj** [comment]
Reopening. We ended up fixing the original PR this is based off of in a separate commit rather than reverting. This PR is valid again.

**Pull request merged**
