### PR TITLE
Convert deprecated filter names to canonical one

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

Currently we can get a deprecated name in listener.  Below is an example

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: size-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.buffer
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            value:
              maxRequestBytes: 1073741824
```

### CODE REVIEW

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/blob/da6178604559bdf2c707a57f452d16bee0de90c8/releasenotes/notes/envoy-filter.yaml - We mentioned we will not supported deprecated filter names going forward. I am wondering it is a continuous maintenance headache to covert back and forth.

**Comment by hzxuzhonghu** [comment]
Yes,  i totally agree. But we can not eliminate this immediately, otherwise could break backward compatibility if a name is removed from the envoy. So this is better to have

**Comment by ramaraochavali** [comment]
Should we add a feature flag to support old names so that the hit is taken by people who use it and we can default it to false and we can remove that flag couple of releases down the line?

**Comment by howardjohn** [comment]
I am not sure I understand the motivation here. There should be no expectation that EnvoyFilters are compatible on upgrade

> NOTE 1: Some aspects of this API are deeply tied to the internal implementation in Istio networking subsystem as well as Envoy’s XDS API. While the EnvoyFilter API by itself will maintain backward compatibility, any envoy configuration provided through this mechanism should be carefully monitored across Istio proxy version upgrades, to ensure that deprecated fields are removed and replaced appropriately.

From https://istio.io/latest/docs/reference/config/networking/envoy-filter/

I am actually glad that we break compatiblity here; similar to the reasons in https://sre.google/sre-book/service-level-objectives/#xref_risk-management_global-chubby-planned-outage, it sets expectations that we **will** break EnvoyFilters. This is especially needed for the next few releases where I expect the internal XDS shape will change quite a bit.

**Comment by hzxuzhonghu** [comment]
Do both of you feel we should remove the canonical name convert since we have the notes?

**Comment by hzxuzhonghu** [comment]
Normally support deprecated name for some releases and removing it totally is ok. But as you can see, still many users are using the deprecated name.  This is the motivation here. 

If both of you agree, I am ok with completely clean up all the temporary conversions.

**Comment by howardjohn** [comment]
Why not just keep things the way they are? Then we do not need to expand the workarounds but also do not break existing users?

**Comment by hzxuzhonghu** [comment]
I could not understand this philosophy.

**Comment by hzxuzhonghu** [comment]
With this theory, i doubt what's the effect of the deprecation release note.  Normally, we will announce the deprecation of something and then after some releases remove them, otherwise the deprecation stuff will become more and more. And eventually it would be more difficult to clean up

**Pull request closed without merging**
