### PR TITLE
istioctl: check revision exists before uninstalling

### LINKED ISSUE #40598: "failed to get proxy infos: unable to find any Istiod instances" when trying to uninstall a revision
### Bug Description

Note : asdf below is used to switch to different istioctl CLI version

```
$ kind create cluster --image=kindest/node:v1.22.9
[...]

$ k version --short
Client Version: v1.22.11
Server Version: v1.22.9

# Use 1.12.9 CLI version
$ asdf global istioctl 1.12.9

$ istioctl version --remote=false
1.12.9

$ istioctl install --set revision=1-12-9 -y
✔ Istio core installed                                                                                                                                                                                      
✔ Istiod installed                                                                                                                                                                                          
✔ Ingress gateways installed                                                                                                                                                                                
✔ Installation complete                                                                                                                                                                                     Making this installation the default for injection and validation.

Thank you for installing Istio 1.12.

$ k get deploy,svc -n istio-system
NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istio-ingressgateway   1/1     1            1           65s
deployment.apps/istiod-1-12-9          1/1     1            1           81s

NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                      AGE
service/istio-ingressgateway   LoadBalancer   10.96.249.71   <pending>     15021:30051/TCP,80:32292/TCP,443:31853/TCP   64s
service/istiod-1-12-9          ClusterIP      10.96.94.8     <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP        81s

$ istioctl version
client version: 1.12.9
control plane version: 1.12.9
data plane version: 1.12.9 (1 proxies)

# Use 1.13.7 CLI version
$ asdf global istioctl 1.13.7

# Install a canary release
$ istioctl install --set revision=1-13-7 -y             
WARNING: Istio is being upgraded from 1.12.9 -> 1.13.7.
WARNING: Before upgrading, you may wish to use 'istioctl analyze' to check for IST0002 and IST0135 deprecation warnings.
✔ Istio core installed                                                                                                                                                                                      
✔ Istiod installed                                                                                                                                                                                          
✔ Ingress gateways installed                                                                                                                                                                                
✔ Installation complete                                                                                                                                                                                     
Thank you for installing Istio 1.13. 

$ istioctl version                          
client version: 1.13.7
istiod version: 1.12.9
istiod version: 1.13.7
data plane version: 1.13.7 (1 proxies)

```

Now trying to uninstall the old revision displays the message `failed to get proxy infos: unable to find any Istiod instances` and does nothing :

```
$ istioctl x uninstall  --revision istiod-1-12-9
failed to get proxy infos: unable to find any Istiod instances
No resources will be pruned from the cluster. Please double check the input configs

✔ Uninstall complete       
```

Additional note : If I use the `--purge` option, it removes all istio resources and that is not what I want (as I am using canary releases and want to only uninstall a revision)

### Version

```prose
$ istioctl version                          
client version: 1.13.7
istiod version: 1.12.9
istiod version: 1.13.7
data plane version: 1.13.7 (1 proxies)

$ k version --short
Client Version: v1.22.11
Server Version: v1.22.9
```

### Additional Information

<details>
<summary>istioctl bug-report</summary>
Target cluster context: kind-kind

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-08-22 22:13:22.799293285 +0200 CEST

Cluster endpoint: https://127.0.0.1:38603
CLI version:
version.BuildInfo{Version:"1.13.7", GitRevision:"0a6c3a4ae3f1f34e7a33dd6a2a4cbdffc8d32daa", GolangVersion:"go1.17.12", BuildStatus:"Clean", GitTag:"1.13.7"}

The following Istio control plane revisions/versions were found in the cluster:
Revision 1-13-7:
&version.MeshInfo{
    {
        Component: "istiod",
        Info:      version.BuildInfo{Version:"1.13.7", GitRevision:"0a6c3a4ae3f1f34e7a33dd6a2a4cbdffc8d32daa", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.13.7"},
    },
}

Revision 1-12-9:
&version.MeshInfo{
    {
        Component: "istiod",
        Info:      version.BuildInfo{Version:"1.12.9", GitRevision:"d85042dbcde912bd21e26c19f283414fc6346f9f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.9"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision 1-13-7: Versions {1.13.7}

Fetching proxy logs for the following containers:

istio-system/istio-ingressgateway/istio-ingressgateway-65c4fcff9b-vq2wd/istio-proxy
istio-system/istiod-1-12-9/istiod-1-12-9-df74db6b5-md9tl/discovery
istio-system/istiod-1-13-7/istiod-1-13-7-6c4c8d47d7-db569/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /home/guillaume/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

</details>

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

fix: #40598

check revision exists before uninstalling

### CODE REVIEW

**Comment by zhlsunshine** [comment]
LGTM, thanks zirain!

**Review by zhlsunshine — APPROVED** [review]
LGTM, thanks zirain!

**Review by GregHanson — APPROVED** [review]

**Comment by ericvn** [comment]
Is it possible to add a test for this?

**Comment by zirain** [comment]
> Is it possible to add a test for this?

updated

**Review by ericvn — APPROVED** [review]

**Review by irisdingbj — APPROVED** [review]

**Pull request merged**
