### PR TITLE
Support service-apis TCPRoute, traffic weighting

### PR DESCRIPTION
**Pull request by howardjohn**
* Update the API
* Rename TcpRoute -> TCPRoute (part of the api update)
* Implement support for TCP, with unit/integ test

### CODE REVIEW

**Comment by howardjohn** [comment]
@costinm can you take a look when you have a chance?

**Comment by hzxuzhonghu** [comment]
I think it is very tricky to bump every commit of service-apis, do you use it internally?

**Comment by howardjohn** [comment]
@hzxuzhonghu is there any issue with updating? This code is entirely off by default and doesn't impact other code at all. By keeping up to date we are able to provide feedback on the API and provide a implementation for users to try, both of which are extremely valuable. We are working very closely on the api

**Comment by howardjohn** [comment]
@costinm

**Pull request merged**
