### PR TITLE
Don't pass tracing addresses if tracing disabled

### PR DESCRIPTION
**Pull request by howardjohn**
Without this change, clusters are created for tracing services when the
are not even abled, which causes additional DNS requests.

Related: https://github.com/istio/istio/issues/12968

### CODE REVIEW

**Comment by howardjohn** [comment]
@rshriram sounds reasonable. It seems like we only push out the config for Zipkins by default. Should we do this for lightstep/datadog too?

**Comment by rshriram** [comment]
Also clusters for tracing are created independent of these settings. A cluster is created for every service in the system. IF someone had hardcoded zipkin in the bootstrap, then thats where you should look at. but that would be a breaking change since people now assume zipkin config is always present and can be enabled by actually creating a zipkin service and forwarding trace headers in the application.

**Comment by rshriram** [comment]
https://github.com/istio/istio/blob/master/tools/deb/envoy_bootstrap_v2.json#L172

**Comment by howardjohn** [comment]
It is effectively hardcoded, zipkinsAddress can never be `""` because of this:

https://github.com/istio/istio/blob/de0a6b712755e2b926964de75837e66f34102d26/install/kubernetes/helm/istio/templates/configmap.yaml#L213-L219

**Comment by howardjohn** [comment]
@rshriram given Zipkins is effectively hardcoded does that change your mind? If not feel free to close this

**Comment by rshriram** [comment]
I was unaware of this zipkin hardcoding. The helm charts need fixing. The bootstrap has conditionals to enable zipkin or light step or datadog. How come zipkin gets hard coded ?

**Comment by howardjohn** [comment]
@douglas-reid do you have any background here?

**Comment by bianpengyuan** [comment]
@howardjohn I am wondering why do you think zipkin address is hardcoded and cannot be empty? If customer set tracer as lightstep or datadog, then the meshconfig won't have zipkin section in it, right?

**Comment by howardjohn** [comment]
Look at https://github.com/istio/istio/blob/de0a6b712755e2b926964de75837e66f34102d26/install/kubernetes/helm/istio/templates/configmap.yaml#L213-L219

There is always a zipkins address configured. Haven't look at what happens if they enable lightstep or datadog, but there is no way to get no tracing

**Comment by bianpengyuan** [comment]
I think if you set `global.proxy.tracer` to empty, then tracing section will be empty here and tracer cluster won't show in bootstrap, which makes envoy stops tracing.

**Comment by howardjohn** [comment]
I think you are right, so this change probably isn't needed. The tracing config seems really complicated though

**Pull request closed without merging**
