### PR TITLE
add all whitelist pruning types to pilot

### LINKED ISSUE #21159: Pilot deployment not pruned on istioctl upgrade from 1.4 to 1.5
Repro steps:

```
~/istio/istio-1.4.4/bin/istioctl manifest apply --set values.grafana.enabled=true
~/istio/master/bin/istioctl manifest apply -y --set values.grafana.enabled=true
```

You will find pilot instance remains. This is likely caused by `--prune-whitelist=envoyfilter` making it not prune deployments

Likely broken by https://github.com/istio/istio/pull/21055#discussion_r378061346

### PR DESCRIPTION
**Pull request by richardwxn**
resolves: https://github.com/istio/istio/issues/21159

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
All other components will not set --prune-whitelist at all, right?

**Comment by richardwxn** [comment]
@howardjohn the mapping has only one key right now, which is for pilot, so this would only applies to pilot

**Comment by howardjohn** [comment]
what about other components? do they pass --prune-whitelist or do they use
the default? they should use the default

**Comment by richardwxn** [comment]
@howardjohn yes, if we do not pass the prune-whitelist to other components, they are just using default

**Review by elfinhe — APPROVED** [review]

**Review by howardjohn — CHANGES_REQUESTED** [review]
You are pruning the clusterroles, thats why pod fails to startup

```
running command: apply --prune --force --selector operator.istio.io/component=Pilot --prune-whitelist core/v1/Pod --prune-whitelist core/v1/ConfigMap --prune-whitelist core/v1/Service --prune-whitelist core/v1/ServiceAccount --prune-whitelist core/v1/Endpoints --prune-whitelist apps/v1/Deployment --prune-whitelist rbac.authorization.k8s.io/v1/ClusterRole --prune-whitelist rbac.authorization.k8s.io/v1/ClusterRoleBinding --prune-whitelist admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration --prune-whitelist admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration --prune-whitelist autoscaling/v2beta1/HorizontalPodAutoscaler --prune-whitelist policy/v1beta1/PodDisruptionBudget --prune-whitelist authentication.istio.io/v1alpha1/MeshPolicy --prune-whitelist networking.istio.io/v1alpha3/DestinationRule --prune-whitelist networking.istio.io/v1alpha3/EnvoyFilter -f - <use --verbose to see stdin string>
running command: apply -n istio-system --prune --force --selector operator.istio.io/component=Pilot --prune-whitelist core/v1/Pod --prune-whitelist core/v1/ConfigMap --prune-whitelist core/v1/Service --prune-whitelist core/v1/ServiceAccount --prune-whitelist core/v1/Endpoints --prune-whitelist apps/v1/Deployment --prune-whitelist rbac.authorization.k8s.io/v1/ClusterRole --prune-whitelist rbac.authorization.k8s.io/v1/ClusterRoleBinding --prune-whitelist admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration --prune-whitelist admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration --prune-whitelist autoscaling/v2beta1/HorizontalPodAutoscaler --prune-whitelist policy/v1beta1/PodDisruptionBudget --prune-whitelist authentication.istio.io/v1alpha1/MeshPolicy --prune-whitelist networking.istio.io/v1alpha3/DestinationRule --prune-whitelist networking.istio.io/v1alpha3/EnvoyFilter -f - <use --verbose to see stdin string>
```

The second run prunes the first

**Comment by howardjohn** [comment]
probably don't want to prune cluster resources, we should stick to the defaults (https://github.com/kubernetes/kubernetes/pull/35220/files#diff-b3aa1e4377838f45d595f8ecca3c2619R344) + CRDs?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
