### PR TITLE
Sync operator with istio/operator@release-1.3

### PR DESCRIPTION
**Pull request by ostromart**
This is the same as https://github.com/istio/istio/pull/16625 but with go-bindata PR removed.

### CODE REVIEW

**Comment by rlenglet** [comment]
@ostromart Why is this PR still pulling go-bindata as a dependency?

**Comment by ostromart** [comment]
There's still use of go-bindata here: https://github.com/istio/istio/tree/master/vendor/istio.io/pkg/ctrlz/assets
This is not included in istioctl however.

**Comment by rlenglet** [comment]
Tests keep failing on this PR. :/

/test e2e-bookInfoTests-trustdomain-release-1.3
/test istio-unit-tests-release-1.3

**Comment by ostromart** [comment]
The failures look like flakes?

**Pull request merged**
