### PR TITLE
add downstream_cx_active stats only when ExitOnZeroActiveConnections is used

### PR DESCRIPTION
**Pull request by ramaraochavali**
add downstream_cx_active stats only when  ExitOnZeroActiveConnections is enabled.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Put a hold because https://github.com/istio/istio/blob/master/pkg/envoy/agent.go#L187 needs to be handled for prometheus as well. Might need regex change

**Comment by ramaraochavali** [comment]
@howardjohn This as a fix to avoid `downstream_cx_active` metrics when the feature is not used is fine. 

I thought we can avoid http.downstream_cx_active also since we can just rely on listener stats only as was done in the code but it is not possible to do that because we can not add/change the regex. So this is the best we can do. WDYT?

**Review by howardjohn — APPROVED** [review]

**Comment by mandarjog** [comment]
I think this is ok as a strict feature flag based solution.
However customers do want to know number of downstream active connections specifically at ingress.
Previously this was possible by adding a new inclusion, not it will be magically filtered out unless you also enable this feature.

**Comment by mandarjog** [comment]
Cc @douglas-reid

**Pull request merged**
