### PR TITLE
Add OIDC authenticator to XDS path

### PR DESCRIPTION
**Pull request by howardjohn**
Currently it was accidentally only for CA

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
/hold

Give security guys a chance to have a look

**Review by costinm — APPROVED** [review]

**Comment by liminw** [comment]
/hold 

We should not enable all the authenticators automatically. Depending on the deployment environment, Istiod may support one or a few authenticators. k8s allows the admin to configure the authenticator used for API server, but does not enable all authenticators automatically. We should also make it configurable.

**Comment by howardjohn** [comment]
@liminw I think I agree with you, but FWIW this is just making the (brand new) XDS auth path consistent with the (stable for a long time) CA auth path.

**Comment by liminw** [comment]
> @liminw I think I agree with you, but FWIW this is just making the (brand new) XDS auth path consistent with the (stable for a long time) CA auth path.

But the pure effect of it is to make XDS auth require all three authenticators, which may break some existing deployment environments. Can we add an authenticator configuration along with this change?

**Comment by howardjohn** [comment]
I do not have the time to do that. Anyone from @istio/wg-security-maintainers are welcome to add this security configuration and I will include it in this PR

**Comment by hzxuzhonghu** [comment]
>But the pure effect of it is to make XDS auth require all three authenticators, which may break some existing deployment environments.

@liminw  I understand if one of the authenticators authenticated, then it works. Is this wrong?

**Comment by lei-tang** [comment]
> > But the pure effect of it is to make XDS auth require all three authenticators, which may break some existing deployment environments.
> 
> @liminw I understand if one of the authenticators authenticated, then it works. Is this wrong?

With the implementation in this PR, if any authenticator in the following three authenticators returns authentication success, the authentication succeeds, which may not necessarily be the desired authentication behavior. For example, in some scenarios, users may only want to use one authenticator and only allow access if that single authenticator returns success.

authenticate.ClientCertAuthenticator{},
kubeauth.NewKubeJWTAuthenticator(),
authenticate.NewJwtAuthenticator()

**Comment by hzxuzhonghu** [comment]
I do think anyone pass auth model is good, consistent with k8s

**Comment by costinm** [comment]
Yes, K8S apiserver also support mTLS and JWT and few other auth. 

In Istio the 3 authenticators are equivalent - if a user has a JWT it can get an mTLS token. And we have had this
model of accepting both mTLS and JWT for CA since before 1.0, and so far we didn't have any user requesting
us to turn one off.

The 3rd auth is the faster/more scalable replacement for TokenReview - once k8s OIDC discovery is more 
available we could turn off TokenReview. 

Re. API and giving user control: we do have already well defined APIs for this purpose, but Istiod doesn't 
implement them ( i.e. a RequestAuthn config with workload selector selecting istiod is not doing anything ). 
I am strongly against defining a duplicated API when Istio already has one. Also against exposing internal 
details about how we authenticate JWTs ( TokenReview vs OIDC). 

For upgrade purpose we will need to preserve current behavior - both JWT and mTLS, and when someone
either adds a sidecar to Istiod or directly implements the existing RequestAuthm for Istiod - I am all for 
giving user more control, in a future release. 

Since this PR doesn't really change anything - XDS already accepts JWT, we're just providing a more 
scalable way to verify the JWT, since TokenReview has problems at high QPS - I don't see any problem.

**Pull request closed without merging**
