### PR TITLE
[WIP] Fix a memory leak in pilot

### PR DESCRIPTION
**Pull request by jsPlachetka**
Please provide a description for what this PR is for.
See: https://github.com/istio/istio/issues/14782

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
without looking too much into it, I'd worry this will crash places in the code that try to use the push context from env. I think we want to keep it to the previous context if it fails to update (I remember seeing s comment that said exactly this)

Where is the memory leak here?

**Comment by phil9909** [comment]
I'm aware this is not a perfect solution to the problem (hence the WIP tag). But the influence on the memory footprint is tremendous (exponential vs. quadratic / see graph). Maybe this information (i.e. the code change) help someone with better knowledge of the pilot code to find the actual root cause.

Memory usge (KB) vs  Object Count

**Comment by howardjohn** [comment]
interesting.. I wonder why your fix helps, it seems like it should be garbage collected. I wonder if it is because push context and env both have pointers to each other?

**Comment by phil9909** [comment]
> I wonder if it is because push context and env both have pointers to each other?

That's the reason I came up with this work-around (let's not call it "fix" because I don't think it addresses the root cause, my bad).
My idea was: the `PushContext` init code might pass the `Env` to some other pice of code, which in turn accesses the `PushContext` pointer of the `Env` (which is not the same as the new `PushContext`)  and stores a reference to this old `PushContext`, which would lead to an endless chain of `PushContext[n]` storing references to `PushContext[n-1]`.
But we couldn't find any further evidence for this.

---

@kramerul and I went further down this rabbit hole today. Maybe the work-around only helps, because it slows down the pushes. We could also prevent the pilot from crashing by adding a 10 second delay between the updates.
Out new theory is, that the updates for the sidecars pile up, because the envoy is to slow processing the new configuration. @howardjohn Do you think this is possible?

**Comment by howardjohn** [comment]
> Out new theory is, that the updates for the sidecars pile up, because the envoy is to slow processing the new configuration. 

Yes that makes sense! I have been working on this exact thing at https://github.com/istio/istio/pull/15405

I was not able to reproduce this memory issue, any chance you could try it with that change?

This really seems the case because when any config change happens we create the push context (in your case, very large) and then attempt to push each config change in order. If the rate of changes > rate of pushes (very reasonable if pilot is too slow to push due to massive config, the config generation is slow until https://github.com/istio/istio/pull/15632 lands), then an unbounded amount of push contexts can stick around. The change I linked above changes this so that pushes to the same proxy will be merged, so there *should* only be a couple of push contexts around at once at most - it would be great to see if thats the case though, as I didn't attempt to optimize for that.

**Comment by phil9909** [comment]
Obsolete due to #15810

**Pull request closed without merging**
