### PR TITLE
Update cluster_lib.sh

### LINKED ISSUE #3518: prow error "1.9.2-gke.0" is invalid.
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3517/istio-pilot-e2e/3061/

```
0215 17:53:40.674] + gcloud container clusters create e2e-pilot-933b850d --zone us-central1-f --project istio-testing --cluster-version 1.9.2-gke.0 --machine-type n1-standard-4 --num-nodes 1 --no-enable-legacy-authorization --enable-kubernetes-alpha --quiet
W0215 17:53:43.706] ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Version "1.9.2-gke.0" is invalid.
```

cc @hklai

### PR DESCRIPTION
**Pull request by rkpagadala**
fixes #3518 #2929

### CODE REVIEW

**Comment by ayj** [comment]
LGTM assuming the default selected version is >= 1.9. Otherwise we should
continue to hardcore version to avoid breaking features that depend on 1.9.

**Comment by sebastienvas** [comment]
Thanks I was going to do the same PR.

**Comment by rkpagadala** [comment]
@ayj I checked the release is 1.9.2-gke.1 as of now

**Pull request merged**
