### PR TITLE
Fix describe po not finding vs when protocol is https

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Fix https://github.com/istio/istio/issues/35301

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]
Verified the code works using https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ as a reference

**Review by zhlsunshine — APPROVED** [review]

**Comment by hanxiaop** [comment]
@istio/wg-networking-maintainers PTAL.

**Comment by hanxiaop** [comment]
@istio/wg-networking-maintainers PTAL, thanks!

**Pull request merged**
