### PR TITLE
Cherry-pick PR#16459 into Release 1.3

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Please provide a description for what this PR is for.

The auto cherry-pick failed #16459 (comment), this PR manually cherry-picks that PR.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
The auto cherry-pick failed https://github.com/istio/istio/pull/16459#issuecomment-525080014, this PR manually cherry-picks that PR.

**Comment by JimmyCYJ** [comment]
cc @myidpt

**Comment by rlenglet** [comment]
The `istio-pilot-e2e-envoyv2-v1alpha3-release-1.3` test failed:
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16677/istio-pilot-e2e-envoyv2-v1alpha3-release-1.3/182
```
--- FAIL: TestTempWorkspace (16.75s)
    --- PASS: TestTempWorkspace/StoreInvariant (4.40s)
    --- FAIL: TestTempWorkspace/istioConfig (0.07s)
        config.go:454: Post(ClusterRbacConfig) => got the server could not find the requested resource (post clusterrbacconfigs.rbac.istio.io)
    --- PASS: TestTempWorkspace/controllerEvents (6.53s)
    --- PASS: TestTempWorkspace/controllerClientSync (4.40s)
    --- PASS: TestTempWorkspace/controllerCacheFreshness (0.80s)
FAIL
FAIL	istio.io/istio/tests/e2e/tests/controller	16.765s
tests/istio.mk:189: recipe for target 'test/local/noauth/e2e_pilotv2' failed
make[1]: *** [test/local/noauth/e2e_pilotv2] Error 1
make[1]: Leaving directory '/home/prow/go/src/istio.io/istio'
tests/istio.mk:132: recipe for target 'with_junit_report' failed
make: *** [with_junit_report] Error 2
```

**Comment by JimmyCYJ** [comment]
> --- FAIL: TestTempWorkspace (16.75s)
>     --- PASS: TestTempWorkspace/StoreInvariant (4.40s)
>     --- FAIL: TestTempWorkspace/istioConfig (0.07s)
>         config.go:454: Post(ClusterRbacConfig) => got the server could not find the requested resource (post clusterrbacconfigs.rbac.istio.io)
>     --- PASS: TestTempWorkspace/controllerEvents (6.53s)
>     --- PASS: TestTempWorkspace/controllerClientSync (4.40s)
>     --- PASS: TestTempWorkspace/controllerCacheFreshness (0.80s)
> FAIL
> FAIL	istio.io/istio/tests/e2e/tests/controller	16.765s
> tests/istio.mk:189: recipe for target 'test/local/noauth/e2e_pilotv2' failed
> make[1]: *** [test/local/noauth/e2e_pilotv2] Error 1
> make[1]: Leaving directory '/home/prow/go/src/istio.io/istio'
> tests/istio.mk:132: recipe for target 'with_junit_report' failed
> make: *** [with_junit_report] Error 2

I think that is not relevant to this PR. Maybe TestTempWorkspace is flaky.

**Comment by rlenglet** [comment]
> I think that is not relevant to this PR. Maybe TestTempWorkspace is flaky.

This is not flaky. All PRs against istio/istio:release-1.3 are now have that same failure.
Resolution is tracked in https://github.com/istio/istio/pull/16428.

**Comment by rlenglet** [comment]
The `istio-pilot-e2e-envoyv2-v1alpha3-release-1.3` test will be fixed by https://github.com/istio/istio/pull/16682.

**Pull request merged**
