### PR TITLE
add istio sidecar injection labels for addon deployments.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
These are generated from `manifests/addons/gen.sh`.

The goal of these is to be as minimal configuration as possible from upstream installation. Maybe we can add the inject=false label but I strongly discourage other changes unless there are significant benefits

**Comment by morvencao** [comment]
@howardjohn PTAL

**Review by bianpengyuan — COMMENTED** [review]
This is probably fine for now, but we'd need to figure the way to do mtls between addons, which will need sidecar injection. @douglas-reid wdyt?

**Comment by douglas-reid** [comment]
> This is probably fine for now, but we'd need to figure the way to do mtls between addons, which will need sidecar injection. @douglas-reid wdyt?

I agree with your assessment. Until we figure out how we want to secure the add-ons, ensuring no sidecar is fine.

**Review by bianpengyuan — APPROVED** [review]

**Comment by morvencao** [comment]
@howardjohn PTAL

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
