### PR TITLE
Remove support for consul service registry

### PR DESCRIPTION
**Pull request by shamsher31**
Based on https://github.com/istio/istio/pull/25824#issuecomment-663364210. 

External service registry support will be done via MCP-over-XDS rather than in-tree.
https://github.com/istio/api/tree/master/mcp

More Info:
https://github.com/istio/istio/pull/25521
https://github.com/istio/istio/pull/25824
https://github.com/istio/istio/pull/6218

### CODE REVIEW

**Comment by sdake** [comment]
@shamsher31 - is the goal to ensure all registries are external - including that of Kubernetes?

Cheers,
-steve

**Review by howardjohn — APPROVED** [review]
Oops wish I saw this before I made https://github.com/istio/istio/pull/25846! Thanks!

**Comment by howardjohn** [comment]
We do not plan to externalize the kubernetes registry - it's counter to the Istiod direction.

**Review by hzxuzhonghu — APPROVED** [review]

**Review by frankbu — APPROVED** [review]

**Comment by zhaohuabing** [comment]
Will there be any repos under istio to accommodate MCP servers? I will be happy to write a Consul MCP server.

**Pull request merged**
