### PR TITLE
[Test Framework] Cleanup logic for cluster types

### PR DESCRIPTION
**Pull request by nmittler**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by stevenctl — APPROVED** [review]
I think there are some call sites that need to be change, causing the build failures. But this looks _great_!

**Review by lei-tang — APPROVED** [review]

**Review by gargnupur — APPROVED** [review]

**Pull request merged**
