### PR TITLE
Update envoyproxy/go-control-plane

### PR DESCRIPTION
**Pull request by yangminzhu**
Ran `dep ensure -update github.com/envoyproxy/go-control-plane`

### CODE REVIEW

**Comment by rshriram** [comment]
fyi @kyessenov said that there was some grpc version update that prevented us from updating go cp easily. I don't know what it involves but you might want to talk with him.

**Comment by kyessenov** [comment]
The incompatibility should result in a build error. If it builds, you are fine.

**Comment by yangminzhu** [comment]
@kyessenov  @rshriram All required tests passed, please take a look, thank you!

**Pull request merged**
