### PR TITLE
remove the install comment

### PR DESCRIPTION
**Pull request by linsun**
@stevenctl I don't think the comment is correct because your gw is named as east-west gateway which is different than the default ingress gw.  I've also tried this to validate.

```
$ istioctl install -f cluster1-east-west-gateway.yaml 
This will install the Istio 1.9.0 profile into the cluster. Proceed? (y/N) y
✔ Ingress gateways installed                                             
✔ Installation complete                                                  (⎈ |cluster1/bu9dtn9w0gtrfrgelj40:default)
~/go/src/istio.io/demo ⌚ 17:05:59
$ k get pod -n istio-system                  
NAME                                     READY   STATUS    RESTARTS   AGE
istio-eastwestgateway-74fc586f46-4sg47   1/1     Running   0          3m19s
istio-ingressgateway-58c995cd55-p6hbm    1/1     Running   0          45m
istiod-7cdbdf9dd4-bjj6d                  1/1     Running   0          45m

```

and

```
$ cat cluster1-east-west-gateway.yaml                      
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
spec:
  # Only generate a gateway component defined below.
  # Using this with "istioctl install" will reconcile and remove existing control-plane components.
  # Instead we use "istioctl manifest generate" and "kubectl apply".
  hub: gcr.io/istio-testing
  tag: latest
  profile: empty
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
          topology.istio.io/network: network1
        enabled: true
        k8s:
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
            # traffic through this gateway should be routed inside the network
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: network1
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  values:
    global:
      meshID: mesh1
      network: network1
      multiCluster:
        clusterName: cluster1%   
```
[ ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by stevenctl** [comment]
Great! I had observed different behavior but I'd this works that's great. We can also update the docs on `.io`. Would you mind updating the tests by making eastwest.go use install?

**Review by stevenctl — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by linsun** [comment]
@stevenctl Thanks, will do!

**Pull request merged**
