### PR TITLE
Add istio-system namespace to zipkin-to-stackdriver yaml

### LINKED ISSUE #2333: Zipkin-to-Stackdriver Service Missing Namespace
The `/install/kubernetes/addons/zipkin-to-stackdriver.yaml` file is missing the `namespace` declaration for the Service. It now defaults to `default`. Assume it should be `namespace: istio-system`.

```bash
...
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-to-stackdriver
  namespace: istio-system # <-- missing namespace
spec:
  ports:
  - name: zipkin
    port: 9411
  selector:
    app: zipkin-to-stackdriver
---
```

### PR DESCRIPTION
**Pull request by bianpengyuan**
to fix #2333

### CODE REVIEW

**Comment by ldemailly** [comment]
so this was reverted @ozevren ? is it needed/need fixing ?

**Comment by douglas-reid** [comment]
it is needed, and should not have been reverted. there is no way that this should have impacted anything related to testing, etc.

@bianpengyuan can you re-submit?

**Pull request merged**
