### PR TITLE
No need to apply istio-root-ca-cert configmap to special kubernetes system namespaces.

### PR DESCRIPTION
**Pull request by SpecialYang**
We no need to apply `istio-root-ca-cert` configmap to special kubernetes system namespaces, because istio never use these namespaces, such as kube-system, kube-public.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
This seems like a good idea but would be good to get some feedback from others as well

**Review by hzxuzhonghu — COMMENTED** [review]
We have clusterlocal namespaces, maybe add them all to it.

**Comment by SpecialYang** [comment]
> We have clusterlocal namespaces, maybe add them all to it.

Now, these special kubernetes system namespaces are included in sidecar inject module which will do not inject sidecar for pods in these namespaces. So these namespaces no need istio-root-ca-cert. Do you mean we should add other namespaces in ignored namespaces?

**Comment by hzxuzhonghu** [comment]
I mean in `pilot/pkg/model/cluster_local.go` there is a `defaultClusterLocalNamespaces` var

**Comment by SpecialYang** [comment]
> I mean in `pilot/pkg/model/cluster_local.go` there is a `defaultClusterLocalNamespaces` var

Currently, the namespaces in `defaultClusterLocalNamespaces ` only have `kube-system` and I did not find any place to modify this var. So I think we only need to consider `IngoredNamespaces` var in inject module which also have `kube-system` namespace.

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
