### PR TITLE
operator init `--dry-run` should not create ns

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
Looks like we have `createNamedspace` with `dryRun` option in reconciler
see: https://github.com/istio/istio/blob/62b77cc3b0fe96eb3b9c85e70642aed9468c3d9a/operator/pkg/helmreconciler/reconciler.go#L599-L604
Maybe we can enhance it there.

**Review by dgn — APPROVED** [review]

**Comment by monsteredc** [comment]
> Looks like we have `createNamedspace` with `dryRun` option in reconciler see:
> 
> https://github.com/istio/istio/blob/62b77cc3b0fe96eb3b9c85e70642aed9468c3d9a/operator/pkg/helmreconciler/reconciler.go#L599-L604
> 
> 
> Maybe we can enhance it there.

@morvencao Thanks!

**Comment by howardjohn** [comment]
Maybe we shouyld have a test with `--dry-run` using fake k8s client and assert no write actions.

**Comment by monsteredc** [comment]
> Maybe we shouyld have a test with `--dry-run` using fake k8s client and assert no write actions.

@howardjohn Sounds great. I'll look into it.

**Pull request merged**
