### PR TITLE
istioctl: change default kube-inject behavior back to --meshConfigMap…

### PR DESCRIPTION
**Pull request by ayj**
…Name=istio

### CODE REVIEW

**Comment by ldemailly** [comment]
so it now works again if you do 

istioctl kube-inject -f any.yaml ?

(and have a functional cluster attached)

/lgtm

**Comment by ayj** [comment]
Yup. Updated PR to restore the original error message about needing to ensure MeshConfig exists in the specified namespace.

**Comment by mandarjog** [comment]
@ayj can we put an additional message if this does not work?
If I run this and it fails because I cannot access config map, It would be good to show the option right then.

**Comment by linsun** [comment]
discussed on #pilot slack, recommendation is force merge.  cc @rshriram for the issue, we may need to increase users on the pilot reviews.  Also, looks like owner/maintainer can't approve a subdirectories either.

**Pull request merged**
