### PR TITLE
generalize artifact injection into Docker images

### PR DESCRIPTION
**Pull request by listx**
Instead of just adding LICENSES.txt only, also optionally add in the
source code as well, gating on the new EXTRA_ARTIFACTS and
EXTRA_ARTIFACTS_CNI environment variables.

Change-Id: Iab8fadfbcbbaa8906491e12324fae20185d9f33e

### CODE REVIEW

**Comment by listx** [comment]
FWIW I tested this in our internal build process https://pantheon.corp.google.com/cloud-build/builds/49c82d81-3fc9-424c-89e4-b0705f84638d?project=louhi-qa. The license text and source code both got injected correctly, as below:

```
 $ docker run --rm -it --entrypoint bash gcr.io/louhi-qa/istio/app:1.1.0-snapshot.5-gke.0
Unable to find image 'gcr.io/louhi-qa/istio/app:1.1.0-snapshot.5-gke.0' locally
1.1.0-snapshot.5-gke.0: Pulling from louhi-qa/istio/app
7b722c1070cd: Already exists 
5fbf74db61f1: Already exists 
ed41cb72e5c9: Already exists 
7ea47a67709e: Already exists 
bc1793a25173: Pull complete 
7823e27b4150: Pull complete 
1dd4c94c6eb7: Pull complete 
1d490e0309c3: Pull complete 
50f5431c6143: Pull complete 
af856d0b134d: Pull complete 
5bacfcc3c187: Pull complete 
Digest: sha256:5c84b115606387566686687f2704156dfbc6e09566915f8ec50206a16c783137
Status: Downloaded newer image for gcr.io/louhi-qa/istio/app:1.1.0-snapshot.5-gke.0
root@e865c6f256a8:/# ls
LICENSES.txt  bin  boot  cert.crt  cert.key  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  source.tar.gz  srv  sys  tmp  usr  var
root@e865c6f256a8:/# ls -alhs
total 214M
4.0K drwxr-xr-x   1 root root 4.0K Mar  2 05:37 .
4.0K drwxr-xr-x   1 root root 4.0K Mar  2 05:37 ..
   0 -rwxr-xr-x   1 root root    0 Mar  2 05:37 .dockerenv
5.9M -rw-r--r--   1 root root 5.9M Mar  2 05:12 LICENSES.txt
4.0K drwxr-xr-x   1 root root 4.0K Feb  7 21:57 bin
4.0K drwxr-xr-x   2 root root 4.0K Apr 12  2016 boot
4.0K -rw-r--r--   1 root root 1.3K Mar  2 05:09 cert.crt
4.0K -rw-r--r--   1 root root 1.7K Mar  2 05:09 cert.key
   0 drwxr-xr-x   5 root root  360 Mar  2 05:37 dev
4.0K drwxr-xr-x   1 root root 4.0K Mar  2 05:37 etc
4.0K drwxr-xr-x   2 root root 4.0K Apr 12  2016 home
4.0K drwxr-xr-x   1 root root 4.0K Feb  7 21:57 lib
4.0K drwxr-xr-x   2 root root 4.0K Jan 22 19:22 lib64
4.0K drwxr-xr-x   2 root root 4.0K Jan 22 19:22 media
4.0K drwxr-xr-x   2 root root 4.0K Jan 22 19:22 mnt
4.0K drwxr-xr-x   2 root root 4.0K Jan 22 19:22 opt
   0 dr-xr-xr-x 439 root root    0 Mar  2 05:37 proc
4.0K drwx------   2 root root 4.0K Jan 22 19:22 root
4.0K drwxr-xr-x   1 root root 4.0K Jan 22 19:22 run
4.0K drwxr-xr-x   1 root root 4.0K Feb  7 21:57 sbin
208M -rw-r--r--   1 root root 208M Mar  2 05:12 source.tar.gz
4.0K drwxr-xr-x   2 root root 4.0K Jan 22 19:22 srv
   0 dr-xr-xr-x  13 root root    0 Feb 16 09:21 sys
4.0K drwxrwxrwt   1 root root 4.0K Feb  7 21:57 tmp
4.0K drwxr-xr-x   1 root root 4.0K Jan 22 19:22 usr
4.0K drwxr-xr-x   1 root root 4.0K Jan 22 19:22 var
root@e865c6f256a8:/# exit
exit
```

**Comment by utka** [comment]
What is added to Dockerfile ? Can you copy paste the example here

**Comment by listx** [comment]
> What is added to Dockerfile ? Can you copy paste the example here

The idea of this patch is to allow arbitrary paths to be injected into the Docker image. Currently we inject LICENSES.txt only (and there is no way to inject other artifacts). So, this patch modifies the dynamic Dockerfile on the fly to accommodate extra artifacts, as in https://github.com/istio/istio/pull/12203/files#diff-44e9bb2bf111a66d351867dc96aca22cR68.

Not sure what to copy/paste --- can you clarify?

**Comment by utka** [comment]
How Docker file looks like if you added EXTRA_ARTIFACTS args?

**Comment by listx** [comment]
Instead of

```
FROM istio/${IMAGE_NAME}:${TAG}	
COPY LICENSES.txt /
```

it will look like

```
FROM istio/${IMAGE_NAME}:${TAG}
${add_cmd}
```

where `${add_cmd}` will expand to

```
COPY $(basename "${extra_artifact}") /
```

and `${extra_artifact}` will be expanded from EXTRA_ARTIFACTS via the call to `add_extra_artifacts_to_tar_images()`.

**Comment by listx** [comment]
ping?

**Comment by listx** [comment]
All of the test failures have the same
```
... skipping 523 lines ...
+ ready=false
+ [[ false == true ]]
+ kill -s 0 1198
+ exited=false
+ [[ false == true ]]
+ sleep 10
+ echo 'failed to get a Boskos resource'
failed to get a Boskos resource
+ return 1
+ cleanup
+ [[ True == \T\r\u\e ]]
+ unsetup_clusters
++ kubectl config current-context
error: current-context is not set
+ PILOT_CLUSTER=
```

Is it worth doing /retest here? What is the bar I have to clear in order to get this merged?

**Comment by utka** [comment]
All required tests should pass

**Comment by listx** [comment]
Is there a reason why /retest isn't working?

**Comment by listx** [comment]
Note to self: change Istio prow jobs so that the test names match the job names. It's super confusing as, e.g., the command to rerun `prow/e2e_pilotv2_auth_sds.sh` is `/test istio_auth_sds_e2e` (notice the semi-reversed word order............)

**Pull request merged**
