### PR TITLE
Test staging - Test current master branch in prow-staging withistio-builder:v20190607-32702dcd

### PR DESCRIPTION
**Pull request by ericvn**

### CODE REVIEW

**Comment by howardjohn** [comment]
just the release test right? I think there is no risk making the branch, or even just ignore the error if it's just one test. In rare case that means we ignore a bug see could roll back so not the worst thing

**Comment by icygalz** [comment]
I think it is expected for release-test.sh to not pass. We only created prow-staging for istio/istio.
"
+ git clone -b prow-staging https://github.com/istio/cni.git
Cloning into 'cni'...
fatal: Remote branch prow-staging not found in upstream origin
"

**Comment by ericvn** [comment]
@howardjohn Also `prow/integ-pilot-k8s-presubmit-tests.sh` which I resubmitted but still waiting to see if the results change.

@icygalz I agree with what we did, `release-test.sh` should not pass. If we are fine with that, then we don't need to do anything. I'm not sure how much we would try using the `prow-staging` branch to test a new image, so not sure if it makes sense to get the test to pass going forward.

**Comment by howardjohn** [comment]
what was the pilot failure? when I look at it I think it's just a normal flake . if it passes the next time I wouldn't be too worried

**Comment by ericvn** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14757/integ-pilot-k8s-presubmit-tests-master/1651/

```
helper.go:178: got codes [503], expected [200]
				from junit_unit-tests.xml
```

**Comment by howardjohn** [comment]
@ericvn it seems to happen every 10 or 15 tests: https://testgrid.k8s.io/istio-presubmits-master#integ-pilot-k8s-presubmit-tests

If it doesnt happen again I would worry about it for this change in particular, we should fix it long term though

**Comment by howardjohn** [comment]
@ericvn everything looks good. Is this with Go 1.12?

**Comment by ericvn** [comment]
Also want to verify image since that's what caught the issue of not moving last time:
```
docker run gcr.io/istio-testing/pilot:4b80960677bddbdee7e8f7f6344c231e128b18cb-e2e_simple version 
Unable to find image 'gcr.io/istio-testing/pilot:4b80960677bddbdee7e8f7f6344c231e128b18cb-e2e_simple' locally
4b80960677bddbdee7e8f7f6344c231e128b18cb-e2e_simple: Pulling from istio-testing/pilot
9ff7e2e5f967: Already exists
59856638ac9f: Already exists
6f317d6d954b: Already exists
a9dde5e2a643: Already exists
83b31743e954: Pull complete
a56063ae74a8: Pull complete
5b9fac5cfb8f: Pull complete
Digest: sha256:52f4fcb4ddf7017d0fcbec8d14efda1e503ca5a3eb33acbfc668484f0d32edd7
Status: Downloaded newer image for gcr.io/istio-testing/pilot:4b80960677bddbdee7e8f7f6344c231e128b18cb-e2e_simple
version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.12.5", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
```

@howardjohn I believe this should be a go to using Golang 1.12 in master. I will create a PR in `test-infra` which can be merged to make it happen. I think we want to do it whenever there is coverage from the `test-infra` team to do a potential revert if things don't go as planned.

**Comment by ericvn** [comment]
Close issue as testing of updated images is complete.

**Pull request closed without merging**
