### PR TITLE
fix inject with label more than 63 characters

### PR DESCRIPTION
**Pull request by believening**
**Please provide a description of this PR:**

We use a CRD management workload (pod), and there are no restrictions on the name of the custom resource. When using Istio, we encountered an injection failure issue because the name of the CR was used as the value of  the `service.istio.io/canonical-name` label, and this name exceeds 63 characters in length.

A reproduction only using pod(Of course, k8s does not recommend using more than 63 characters as the pod name):
``` shell
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  # more then 63 characters
  name: httpbin-1234567890-2234567890-3234567890-4234567890-5234567890-6234567890
  namespace: default
  labels:
    #app: httpbin
    version: v1
spec:
  containers:
  - image: docker.io/kennethreitz/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
    ports:
    - containerPort: 80
$ istioctl kube-inject --filename pod.yaml | kubectl apply -f -
The Pod "httpbin-1234567890-2234567890-3234567890-4234567890-5234567890-6234567890" is invalid: metadata.labels: Invalid value: "httpbin-1234567890-2234567890-3234567890-4234567890-5234567890-6234567890": must be no more than 63 characters
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Pod name cannot exceed 63 characters either. So why do we need such change?

**Comment by believening** [comment]
> Pod name cannot exceed 63 characters either. So why do we need such change?

The pod name is suggested to be within 63 characters instead of being prohibited, this is the case when creating a pod in a k8s cluster of version 1.27.3.

``` shell
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  # more then 63 characters
  name: httpbin-1234567890-2234567890-3234567890-4234567890-5234567890-6234567890
  namespace: default
  labels:
    #app: httpbin
    version: v1
spec:
  containers:
  - image: docker.io/kennethreitz/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
    ports:
    - containerPort: 80
EOF
Warning: metadata.name: this is used in the Pod's hostname, which can result in surprising behavior; a DNS label is recommended: [must be no more than 63 characters]
pod/httpbin-1234567890-2234567890-3234567890-4234567890-5234567890-6234567890 created
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-09-07T08:11:47Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

Using a pod is a simple way to reproduce, and we encounter actual scenarios that are closer to the following example:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  # less then 63 characters
  name: httpbin-xxx-xxx
  generateName: httpbin-xxx
  namespace: default
  labels:
    #app: httpbin
    version: v1
  ownerReferences:
  - apiVersion: foo.com/v1
    kind: Bar
    # more then 63 characters
    name: xxx-1234567890-2234567890-3234567890-4234567890-5234567890-6234567890
    controller: true 
spec:
  containers:
  - image: docker.io/kennethreitz/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
    ports:
    - containerPort: 80
```

```

**Review by hanxiaop — COMMENTED** [review]
Can you add a test for this?

**Comment by hzxuzhonghu** [comment]
Oh, i am suprised namespace can not exceed 63, while pod can.

**Comment by believening** [comment]
> Can you add a test for this?

already added, please review again, thx.

**Review by hzxuzhonghu — APPROVED** [review]
LGTM

**Review by hanxiaop — APPROVED** [review]
Looks good, can you also add a release note?

**Comment by believening** [comment]
> Looks good, can you also add a release note?

@hanxiaop added, and please review again.

**Comment by hanxiaop** [comment]
> > Looks good, can you also add a release note?
> 
> @hanxiaop added, and please review again.

@believening LGTM, thanks

**Pull request merged**
