### PR TITLE
Move dump_kubernetes.sh to tools/ (gets copied to istio-archive)

### PR DESCRIPTION
**Pull request by Tahler**
Confirmed by running `make istio-archive`.

### CODE REVIEW

**Comment by Tahler** [comment]
I wonder if this would be better placed in tools? Probably less confusing for the general Istio customer if the script isn't the only thing next to `bin/istioctl`.
@mandarjog @costinm

**Comment by mandarjog** [comment]
I agree, lets move it to tools/* in archive.
It should also go into tools in the source code though, but that can happen later.

Can you submit this PR on release-1.0 ?

**Comment by Tahler** [comment]
It was actually easier to just move the dump script to tools/, since that entire directory gets copied. I'll update the wiki page to reflect the new script location once this PR goes in.

**Comment by mandarjog** [comment]
What about circleci changes that call this script?

**Comment by Tahler** [comment]
Good call. Done.

**Pull request merged**
