### PR TITLE
Revert "More testing for XDS"

### PR DESCRIPTION
**Pull request by cmluciano**
Reverts istio/istio#4582

This is failing all pilot e2es and blocking merges

[prow e2e failure](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/4582/istio-pilot-e2e/4970/)

### CODE REVIEW

**Comment by costinm** [comment]
How is it affecting prow - the PR is only for v2 stuff that is not yet tested ?

**Comment by kyessenov** [comment]
It's a guess. Master is currently broken -- even non-functional change fail
at linting and unit testing.

**Comment by rshriram** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/4580/istio-pilot-e2e/4968/ was also failing.. PTAL at the PR for it.. same rrors

**Comment by cmluciano** [comment]
closing for now

**Pull request closed without merging**
