### PR TITLE
fix pilot  goroutine leak

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is a pick from #10892 and #10998

### CODE REVIEW

**Comment by rshriram** [comment]
should I force merge?

**Comment by hzxuzhonghu** [comment]
Yes, I think the ci lint is failure

**Comment by hzxuzhonghu** [comment]
Not sure what's the tool version CI used, seems all prs to release-1.0 are merged by hand recently.

**Comment by hzxuzhonghu** [comment]
@rshriram Could you merge it?

**Pull request merged**
