### PR TITLE
Refactor installation scripts to reduce dependencies on sed, sort, grep, and tail

### PR DESCRIPTION
**Pull request by bitmvr**
This pull request removes several dependencies:

- tail
- sed
- grep
- sort

It also alleviates the usage of the Github API and makes a direct request to using the latest URL and reads the location header for the redirect.

All changes are POSIX compliant and have been checked via [shellcheck.](https://github.com/koalaman/shellcheck)

### CODE REVIEW

**Comment by bitmvr** [comment]
@googlebot I signed it!

**Comment by bitmvr** [comment]
Why would you tag a patch release 1.4.X as "Latest"?

**Comment by howardjohn** [comment]
My understand is github automatically determines the "latest". We have no control over it. If that is wrong I would be pretty happy to make always set it to the true latest one

**Comment by bitmvr** [comment]
> My understand is github automatically determines the "latest". We have no control over it. If that is wrong I would be pretty happy to make always set it to the true latest one

Just verified this is correct, which is arguably _really_ dumb. 👏 Thanks Github 😢. Let me mull over a solution that might still be better than the current implementation. 

Thanks @howardjohn

**Comment by bitmvr** [comment]
@howardjohn - How reliable would it be to obtain the version information from here and then build the URL for Github?

> **istio-release**
> https://gcsweb.istio.io/gcs/istio-release/releases

**Comment by howardjohn** [comment]
@bitmvr that seems reasonable although you may have similar issues finding out what the latest one is? All releases will go there though so its definitely a stable location

**Comment by bitmvr** [comment]
The main reason for the pull request was due to the fact the open API endpoint hits its limit. So there are some alternatives...

Using the GitHub Release page, it's possible to do this:

**Github Requeste**
```
curl -sL https://github.com/istio/istio/releases | grep -o 'releases/[0-9]*.[0-9].[0-9]*/' | sort --version-sort | tail -1 | awk -F'/' '{ print $2}'
```
**Result**
```
1.5.2
```
- or - 

**istio.io Request**

```
curl -sL https://gcsweb.istio.io/gcs/istio-release/releases | grep -o 'releases/[0-9]*.[0-9].[0-9]*/' | sort --version-sort | tail -1 | awk -F'/' '{ print $2}'
```
**Result**
```
1.5.2
```

**Comment by ericvn** [comment]
Some quick testing shows that the `Github Releases Request` doesn't return a full list of releases. I recall some earlier discussion that it only returns some limited recent set. But since we are only looking for the most recent, that should OK.

**Comment by ericvn** [comment]
I'm fine updating this PR,  just maybe edit the title to say something about working around the rate limit

**Pull request closed without merging**
