### PR TITLE
Enable Analysis for all tests

### PR DESCRIPTION
**Pull request by therealmitchconnors**
This is in preparation for promotion to Beta of the Analysis portions of Istio Status in 1.10.

### CODE REVIEW

**Review by mandarjog — APPROVED** [review]
Lgtm for testing.

**Comment by howardjohn** [comment]
please enable in the integration test file only

**Comment by mandarjog** [comment]
What is the right way to enable feature to ensure that all tests including long running tests use it?

**Comment by howardjohn** [comment]
Update tests/integration/iop-integration-test-defaults.yaml, then update
the configs in istio/tools

**Pull request closed without merging**
