### PR TITLE
Updated OPA to 0.10.3

### PR DESCRIPTION
**Pull request by sjb933**

### CODE REVIEW

**Comment by kyessenov** [comment]
Please run `dep ensure` after changing the lock file.
/ok-to-test

**Comment by sjb933** [comment]
Just signed the google CLA.

**Comment by sjb933** [comment]
@kyessenov Apologies, but I'm ill-equipped to triage issues or generate new lock files, etc.. 

I do not normally work in a go environment and I'm not setup to run `go` or `dep`.  I quickly installed daily dep and go via homebrew to run `dep ensure`. I ran into issues that are no doubt trivial to the trained eye, but I don't have time at the moment to learn all the nuance of go environments and pkg management.

The goal here is to simply update the embedded OPA engine so we can utilize the newer functionality in policies.

```
shane@Shanes-MacBook-Pro ~/C/i/s/istio> dep ensure
Solving failure: No versions of cloud.google.com/go met constraints:
	v0.26.0: Could not introduce cloud.google.com/go@v0.26.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.35.1: Could not introduce cloud.google.com/go@v0.35.1, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.35.0: Could not introduce cloud.google.com/go@v0.35.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.34.0: Could not introduce cloud.google.com/go@v0.34.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.33.1: Could not introduce cloud.google.com/go@v0.33.1, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.33.0: Could not introduce cloud.google.com/go@v0.33.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.32.0: Could not introduce cloud.google.com/go@v0.32.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.31.0: Could not introduce cloud.google.com/go@v0.31.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.30.0: Could not introduce cloud.google.com/go@v0.30.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.29.0: Could not introduce cloud.google.com/go@v0.29.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.28.0: Could not introduce cloud.google.com/go@v0.28.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.27.0: Could not introduce cloud.google.com/go@v0.27.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.25.0: Could not introduce cloud.google.com/go@v0.25.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.24.0: Could not introduce cloud.google.com/go@v0.24.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.23.0: Could not introduce cloud.google.com/go@v0.23.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.22.0: Could not introduce cloud.google.com/go@v0.22.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.21.0: Could not introduce cloud.google.com/go@v0.21.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.20.0: Could not introduce cloud.google.com/go@v0.20.0, as its subpackage cloud.google.com/go/contextgraph/apiv1alpha1 is missing. (Package is required by (root).)
	v0.19.0: Could not introduce cloud.google.com/go@v0.19.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.18.0: Could not introduce cloud.google.com/go@v0.18.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.17.0: Could not introduce cloud.google.com/go@v0.17.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.16.0: Could not introduce cloud.google.com/go@v0.16.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.15.0: Could not introduce cloud.google.com/go@v0.15.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.14.0: Could not introduce cloud.google.com/go@v0.14.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.13.0: Could not introduce cloud.google.com/go@v0.13.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.12.0: Could not introduce cloud.google.com/go@v0.12.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.11.0: Could not introduce cloud.google.com/go@v0.11.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.10.0: Could not introduce cloud.google.com/go@v0.10.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.9.0: Could not introduce cloud.google.com/go@v0.9.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.8.0: Could not introduce cloud.google.com/go@v0.8.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.7.0: Could not introduce cloud.google.com/go@v0.7.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.6.0: Could not introduce cloud.google.com/go@v0.6.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.5.0: Could not introduce cloud.google.com/go@v0.5.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.4.0: Could not introduce cloud.google.com/go@v0.4.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.3.0: Could not introduce cloud.google.com/go@v0.3.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.2.0: Could not introduce cloud.google.com/go@v0.2.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	v0.1.0: Could not introduce cloud.google.com/go@v0.1.0, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	master: Could not introduce cloud.google.com/go@master, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	cellsordering: Could not introduce cloud.google.com/go@cellsordering, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	datastore-grpc-replay: Could not introduce cloud.google.com/go@datastore-grpc-replay, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	profiler-test: Could not introduce cloud.google.com/go@profiler-test, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
	pubsub-instrumented: Could not introduce cloud.google.com/go@pubsub-instrumented, as it is not allowed by constraint >=0.20.0, <1.0.0 from project istio.
```

**Comment by kyessenov** [comment]
cc @costinm 

Sorry, I'm ill-equipped in fixing dep dependencies. It does not look like it is caused by OPA, so not sure what the underlying cause is.

**Pull request closed without merging**
