### PR TITLE
Kubecon-2024-test

### PR DESCRIPTION
**Pull request by mrlunchbox777**
**Please provide a description of this PR:**

### CODE REVIEW

**Comment by mrlunchbox777** [comment]
still WIP

**Comment by mrlunchbox777** [comment]
> What is it you are trying to achieve?

This was part of the Kubecon 2024 istio contribfest, backporting https://github.com/istio/istio/issues/52285

**Comment by mrlunchbox777** [comment]
i'm not sure what the long term plan with these are, but i think this is ready now

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by linsun** [comment]
for contribfest ones, we don't plan to merge the PR, but rather, provide a playground for folks to understand the PR process and reviewing test.

**Pull request closed without merging**
