### PR TITLE
Fix other IPv6 SE test

### PR DESCRIPTION
**Pull request by howardjohn**
Two tests with similar names, missed this one in my last PR and it accidentally merged since the test is optional

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
Looks like there's one more that needs the same change - approving anyway since there's a hold and it's an optional suite either way (and it looks like the same fix)

**Comment by kfaseela** [comment]
@howardjohn will wait for the pending test to be fixed before merging

**Comment by howardjohn** [comment]
OK this is passing now. A few skips and followups though

**Review by zirain — APPROVED** [review]

**Review by MorrisLaw — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
