### PR TITLE
Backport: #17866 Allow setting lifecycle to proxy containers

### PR DESCRIPTION
**Pull request by k0da**
This is backport of https://github.com/istio/istio/pull/17866

Signed-off-by: Dinar Valeev <k0da@opensuse.org>

### CODE REVIEW

**Comment by ericvn** [comment]
It looks like this is a back port of #17866.

**Comment by k0da** [comment]
@ericvn yup

**Comment by ericvn** [comment]
As mentioned in #17866 we would want a cherry pick of https://github.com/istio/installer/pull/605 to keep things in sync.

**Comment by k0da** [comment]
@ericvn istio/installer#605 got merged

**Comment by ericvn** [comment]
@k0da But does it need to be cherrypicked as well?

**Comment by k0da** [comment]
@ericvn to installer 1.4 branch?

**Comment by ericvn** [comment]
@k0da Yes, if think so. As I understand it, correct me if I'm wrong, we had #17866 and https://github.com/istio/installer/pull/605 as a pair of PRs across repos that went into _master_. If we back port this to 1.4, shouldn't we back port the pair?

**Comment by k0da** [comment]
@ericvn sure, makes sense now to me. We just don't use installer (yet) and our use case is old fashioned helm chart. Opened backport PR https://github.com/istio/installer/pull/609

**Pull request merged**
