### PR TITLE
Remove poorly maintained code.

### PR DESCRIPTION
**Pull request by sdake**
generate an Istio operator manifest from the helm charts as part of the build process:

https://github.com/istio/istio/tree/master/manifests/charts/istio-operator

Since we have duplicate operator manifests I wish to delete these first, and then add them to the release generation process.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Approved but youll need to fix release builder. I didn't think about this type of issue when I added all thees tests..

**Comment by sdake** [comment]
Aware of release builder changes. just haven't had time to get to it.

**Comment by howardjohn** [comment]
@sdake can you rebase

**Review by elfinhe — APPROVED** [review]

**Comment by sdake** [comment]
not stale.

**Review by morvencao — APPROVED** [review]
@sdake Need rebase to get this in.

**Comment by sdake** [comment]
depends-on: https://github.com/istio/release-builder/pull/320

**Comment by sdake** [comment]
https://github.com/istio/istio/issues/27139

**Pull request merged**
