### PR TITLE
remove IsXDSMarshalingToAnyEnabled in authz plugin

### PR DESCRIPTION
**Pull request by yangminzhu**

### CODE REVIEW

**Comment by yangminzhu** [comment]
> Are we know determined to do `always marshaling to any`? Would be nice to provide some context/link.

It's already the default behavior as I understand. @howardjohn has more background on this.

**Comment by howardjohn** [comment]
Any is 10x more performant and has been stable for ~3 releases and I think
Envoy is removing Struct soon

**Pull request merged**
