### PR TITLE
Zipkin adapter supporting the tracespan template (#11282)

### PR DESCRIPTION
**Pull request by bianpengyuan**
Cherry pick #11282 into release-1.1 branch.

/cc @douglas-reid

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@wenchenglu Hi, can you please help to merge this? This added a new adapter that nobody yet uses so risk is low. Thanks!

**Comment by wenchenglu** [comment]
@bianpengyuan could you associate this PR with a 1.1 issue? if this feature is not really for a 1.1, could you check it in master rather than 1.1?

**Comment by douglas-reid** [comment]
Note: the original PR adding this functionality was first submitted in June of last year. This _should_ have been many months ago.

**Comment by wenchenglu** [comment]
@douglas-reid thanks for the clarifying it

**Comment by douglas-reid** [comment]
@wenchenglu thank you!

**Pull request merged**
