### PR TITLE
revive the liveness/readiness probe config

### PR DESCRIPTION
**Pull request by jmuk**
The real problem of 'crash loop' of mixer is failure of initialization;
the mixer CRD store will wait for up to 30 seconds for init.
(see
https://github.com/istio/istio/blob/master/mixer/pkg/config/crd/store.go#L52)

Considering this, this PR sets the initial delay for liveness
to be 60 seconds for safety.

### CODE REVIEW

**Comment by myidpt** [comment]
I'm also a little worried about this. Can we have two different config files:
istio-with-control-plane-health-check.yaml
istio-auth-with-control-plane-health-check.yaml
And have our users try out these config first, before we set them to default? How does this sound like?
@ldemailly @jmuk

**Comment by ldemailly** [comment]
probably istio-auth-with-control-plane-health-check.yaml is enough but yes, pending helm settings adding this to the default has proven risky in the past

**Comment by myidpt** [comment]
I think we can have both non-auth and auth config files. This fits the needs for different users. For example, Oath don't have auth enabled :)

**Comment by myidpt** [comment]
@jmuk Please see the PR for CA:
https://github.com/istio/istio/pull/3620

**Comment by jmuk** [comment]
Okay, separated the liveness / readiness for mixer into a different file. PTAL.

**Pull request merged**
