### PR TITLE
Add telemetry-gateway subchart to helm requirements.yaml file

### PR DESCRIPTION
**Pull request by cezarsa**
This is a resubmission of #9606 targeting the release-1.1 branch, following @sdake's request.

### CODE REVIEW

**Comment by cezarsa** [comment]
@linsun From what I've seem the conditions always refer to a flag belonging to the subchart itself and since the `telemetry-gateway` subchart didn't have a single `enabled` option I chose not to add a condition in the requirements file, the subchart itself already handles rendering only if one of `grafanaEnabled` or `prometheusEnabled` is true.

As you suggested it would also be possible to tie them to the ingress gateway being enabled, however I think this could look weird, the condition would look something like `gateways.istio-ingressgateway.enabled`, and we would have the `telemetry-gateway` subchart referencing flags from the `gateways` subchart.

**Comment by linsun** [comment]
Ok, fair point.  I think you could have global value too:  https://docs.helm.sh/developing_charts/#tags-and-condition-fields-in-requirements-yaml

**Comment by sdake** [comment]
@linsun i really think what needs to happen here is these gateway implementations need to be moved around to their respective directories (e.g. prometheus to the prometheus chart, grafana to the grafana chart).  Then they would be enabled by default - as the rest of our ingressgateway stuff works.

However, this is simply a backport, so I think for know, this looks good.

/lgtm

**Comment by sdake** [comment]
@cezarsa if your interested in fixing this is master, you might try taking a look at how kiali was done for ingressgateway:

https://github.com/istio/istio/pull/8971

The general proposal is to separate out grafana's gateway implementation and prometheus's gateway implementation into the respective subcharts.

**Comment by cezarsa** [comment]
@sdake Thank you for these suggestions, I've just created a new PR with this idea in mind: #9640

**Comment by sdake** [comment]
@cezarsa this is superseded by other work taking place in release-1.1.  I want to thank you for your contributions - they were a major component of the new work.

Cheers
-steve

**Pull request closed without merging**
