### PR TITLE
Restoring TESTOPTS which was accidentally removed

### PR DESCRIPTION
**Pull request by nmittler**
Removed by abcd9d417b51a1a4cc4a1827654b062f7a38bda6

### CODE REVIEW

**Comment by nmittler** [comment]
@ldemailly note that the tests won't pass until #3517 lands

**Comment by nmittler** [comment]
@ldemailly not sure what's going on with the tests ... is the prow environment experiencing issues ATM?

**Comment by mattdelco** [comment]
The prior 13 runs of istio-pilot-e2e completed successfully.

**Comment by mattdelco** [comment]
The only thing I noticed was a unspecified -n parameter:

<pre>Run "kubectl delete --kubeconfig /home/bootstrap/.kube/config -n  -f -" on input:</pre>

possibly from either of <pre>tests/e2e/tests/pilot/util/infra.go:	return util.RunInput(fmt.Sprintf("kubectl delete --kubeconfig %s -n %s -f -",
tests/util/kubeUtils.go:	_, err := Shell("kubectl delete -n %s -f %s", namespace, yamlFileName)</pre>

One of the callers says <pre>// automatic injection webhook is not namespaced.</pre>

So I'm not sure if -n shouldn't be specified if there's not a namespace (or if the %s should be quoted so at least the empty string is passed [which seems to match the default]), but in any case I'm probably chasing after a symptom rather than a problem.

**Comment by nmittler** [comment]
@mattdelco good find, but I don't think that's anything new.  Probably worth raising an issue, however.

I'm able to run successfully on GKE with the following parameters:

```
-tag f2c06884184c2e496398760868402b5778420f25 -logtostderr -mixer=true -use-sidecar-injector=true -use-admission-webhook=false
```

This matches prow's command-line from the failing test. It's a mystery why prow isn't working.

**Pull request merged**
