### PR TITLE
update chart version for release.

### PR DESCRIPTION
**Pull request by morvencao**
Resolve: https://github.com/istio/istio/issues/14290

Only update the version and appVersion for Istio and Istio-init chart, not including subcharts.

### CODE REVIEW

**Comment by howardjohn** [comment]
We fixed this (in master) in https://github.com/istio/istio/pull/13993/files. We should probably just backport that to 1.1, unless there are issues with that one that are fixed in this?

**Comment by utka** [comment]
I hope 1.1 is done and we are moving to 1.2

**Comment by morvencao** [comment]
Yes, this has been fixed in `master` and `release-1.2`, if we don't need this for `release-1.1`, I'll close this.

**Comment by sdake** [comment]
I think we should expect a few more z streams for the 1.1 series to fix critical defects.  We should be ready to go with those critical defects once they are approved, so I'd recommend sorting out a solution to semver for the charts for 1.1.

Cheers
-steve

**Comment by howardjohn** [comment]
Looks like this is now a cherry pick of  #13993, so lgtm this means we won't have to manually fix the release

/lgtm

**Comment by linsun** [comment]
good to get this in 1.1, think we will have more releases for 1.1.x.

/test e2e-mixer-no_auth

**Comment by linsun** [comment]
+@duderino merging

**Comment by duderino** [comment]
> I hope 1.1 is done and we are moving to 1.2

@utka we have to support 1.1 for 3 months after 1.2 is released.

**Pull request merged**
