### PR TITLE
apply labels for empty CR name and namespace.

### LINKED ISSUE #29633: Operator prunes too much a named and unnamed IOP
If I install two IOPs, one like
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: install
spec: {}
```

and one

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec: {}
```

The second will prune the first.

I think it should only prune resources where name is explicitly ""; essentially treating missing name as `""` instead of a special case.

This would likely involve either enhancing the selector here: https://github.com/istio/istio/blob/443c1df1ec77e52d4a0f5ee60ab4f96837207c2e/operator/pkg/helmreconciler/prune.go#L305

or always writing the name label even if its empty

### PR DESCRIPTION
**Pull request by morvencao**
partly resolve: https://github.com/istio/istio/issues/29633

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — DISMISSED** [review]
can we add unit tests for this type of thing? I notice we have a lot of PRs to the operator without tests, which is likely why we end up with many minor bugs like this one

**Comment by morvencao** [comment]
@howardjohn Add operator test for case:
1. Install **istiod** with `minimal` profile in the first IOP
2. Install **gateways** with `empty` profile and `values.gateways.istio-ingressgateway.enabled=true` set flag in the second IOP
3. Make sure all resources for the first IOP are not pruned after the second gateways IOP is applied.

**Review by howardjohn — COMMENTED** [review]
I am fine with this being an integration test, but I worry about the long term feasibility of this. We should have many many tests. The install process with pruning, multiple IOPs, upgrades, revisions becomes quite complicated, and there are a lot of edge cases that we should be capturing. However, adding an integration test is extremely costly (and only covers the in cluster operator, not istioctl!). Also, the entire test suite is skipped due to https://github.com/istio/istio/issues/28863.

I would encourage us to add solid unit tests

**Comment by richardwxn** [comment]
I am working on fixing the postsubmit test, the operator test was disabled because it failed the postsubmit test

**Pull request closed without merging**
