### PR TITLE
Add a integration test for tracing header in mixer report

### LINKED ISSUE #13391: mixer-based tracing with zipkin adapter doesn't work properly with 1.1.2
**Bug description**
I try to use the zipkin adapter to customized the span format with bookinfo example, but can't get the right trace spans(show below), also the istio-ingressgateway span not showed.  
Istio was installed with helm install. To disable the envoy-based tracing, I set the global.enableTracing to false in the values.yaml and tried to remove the --zipkinAddress config from sidecar-injector-configmap.yaml.   I can find that lots of **"duplicate span IDs, skipping clock skew adjustment"** warnings from the jaeger response. Also, I dumped the requests with tcpdump, found that no x-b3-parentspanid was propagated.  But if used the envoy-based tracing(global.enableTracing=true, mixer.telemetry.enabled=false), everything works fine.

image

image

image

Here are the tracespan configs below:
```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: tracespan
metadata:
  name: zipkin-span
  namespace: istio-system
spec:
  traceId: request.headers["x-b3-traceid"] | ""
  spanId: request.headers["x-b3-spanid"] | ""
  parentSpanId: request.headers["x-b3-parentspanid"] | ""
  spanName: destination.service.host | destination.service.name | destination.workload.name | "unknown"
  startTime: request.time
  endTime: response.time
  httpStatusCode: response.code | 0
  sourceName: source.workload.name | ""
  sourceIp: source.ip | ip("0.0.0.0")
  destinationName: destination.workload.name | ""
  destinationIp: destination.ip | ip("0.0.0.0")
  requestSize: request.size | 0
  requestTotalSize: request.total_size | 0
  responseSize: response.size | 0
  responseTotalSize: response.total_size | 0
  apiProtocol: api.protocol | ""
  clientSpan: (context.reporter.kind | "inbound") == "inbound"
  rewriteClientSpanId: "false"
  spanTags:
    request_operation: conditional((context.protocol | "unknown") == "grpc", request.path | "unknown", request.method | "unknown")
    request_protocol: context.protocol | "unknown"
    request_path: request.path | ""
    request_size: request.size | 0
    response_code: response.code | 0
    response_size: response.size | 0
    source_workload_namespace: source.workload.namespace | "unknown"
    source_workload_name: source.workload.name | "unknown"
    source_ip: source.ip | ip("0.0.0.0")
    destination_service_host: destination.service.host | "unknown"
    destination_ip: destination.ip | ip("0.0.0.0")
    destination_service_name: destination.service.name | "unknown"
    destination_service_namespace: destination.service.namespace | "unknown"
    destination_port: destination.port | 0
    destination_workload_namespace: destination.workload.namespace | "unknown"
    destination_workload_name: destination.workload.name | "unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: zipkin
metadata:
  name: zipkin-handler
  namespace: istio-system
spec:
  url:  http://zipkin.istio-system:9411/api/v2/spans
  sampleProbability: 1
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: zipkin-tracing-rule
  namespace: istio-system
spec:
  match: context.protocol == "http" || context.protocol == "grpc"
  actions:
  - handler: zipkin-handler.zipkin.istio-system
    instances:
    - zipkin-span.tracespan.istio-system
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
> istioctl version>

> version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}

>  kubectl version>
> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.10", GitCommit:"be1a908c6aa47e0ae1b1dc861a1de6ccfe963aa2", GitTreeState:"clean", BuildDate:"2018-11-13T11:45:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.10", GitCommit:"be1a908c6aa47e0ae1b1dc861a1de6ccfe963aa2", GitTreeState:"clean", BuildDate:"2018-11-13T11:33:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS Linux release 7.2.1511 (Core)

### PR DESCRIPTION
**Pull request by bianpengyuan**
cherry-pick #13671 into master. Update proxy sha into the latest. fixes #13391.

### CODE REVIEW

**Comment by kyessenov** [comment]
The new test seems to fail on CI.

**Comment by bianpengyuan** [comment]
@geeknoid Can I get a top-level approval? Thanks! This change is to pick a fix in proxy with a newly added integration test.

**Comment by bianpengyuan** [comment]
@geeknoid gentle ping. Thanks!

**Comment by bianpengyuan** [comment]
@kyessenov @douglas-reid rebase to pick the latest proxy SHA update. There no code change to the test. Could you lgtm again?

**Pull request merged**
