### PR TITLE
Speed up unit tests

### PR DESCRIPTION
**Pull request by Kaushal28**
**Please provide a description of this PR:**

Opening a PR for https://github.com/istio/istio/issues/37555

Made the following changes and applied [stress test](https://github.com/istio/istio/wiki/Test-Flakes#reproducing-test-flakes) to all these tests:

- Reduced retry delay from 1s to 1ms for `TestUpdateAll` in `controller_test.go`. Now it's executing in ~0.11s. It is reporting 0 failures in 23585 runs in 15 minutes using stress test.
- Reduced sleep time to 500ms for `TestTcpEchoServer` in `main_test.go`. Now it's executing in ~0.503s. It is reporting 0 failures in 1718 runs in 15 minutes using stress test with `-p 1`.
- Removed sleep of 1s from `TestWatchDNSCertForK8sCA` in `server_test.go`. Now it's executing in ~0.4s. It is reporting 0 failures in 8942 runs in 15 minutes using stress test.
- Removed sleep of 1s from `TestGRPC` in `grpcgen_test_test.go`. Now it's executing in ~0.28s. It is reporting 0 failures in 11361 runs in 15 minutes using stress test.

Eager to have feedback / suggestions.

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
As long as this doesn't cause CI flakes LGTM - random sleeps in test code without a comment describing exactly _why_ they are there are always good to drop - if they really need to be there they can go back with a comment.

**Review by ericvn — APPROVED** [review]
I did go back and verify that there wasn't a specific reason the sleep for the samples change was set to what it was. Looks like it might have just been arbitrary when written.

But should watch for any test flakes as random sleeps seem to have flakes.

**Comment by Kaushal28** [comment]
@ericvn, @bleggett Thanks for the review. To ensure there are no test flakes, as mentioned in the description, I did [stress test](https://github.com/istio/istio/wiki/Test-Flakes#reproducing-test-flakes) on all the changed tests for 15min and they are reporting 0 failures.

**Review by hzxuzhonghu — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Pull request merged**
