### PR TITLE
Update GROUPS.md

### PR DESCRIPTION
**Pull request by Brian-Xincheng-Zhang**
**Release note**:

```release-note
<PLEASE PUT RELEASE-NOTE HERE, PUT NONE if NO RELEASE-NOTE>
```

### CODE REVIEW

**Comment by rshriram** [comment]
Close until Andra's pr passes

**Comment by Brian-Xincheng-Zhang** [comment]
I signed it!

-- Brian

**Comment by rshriram** [comment]
non functional change to docs. merging.

**Pull request merged**
