### PR TITLE
Rename `chained` to `provider`, as it is more appropriate

### PR DESCRIPTION
**Pull request by dgn**
**Please provide a description of this PR:**

The pilot.cni.chained is really about whether to inject a multus-specific annotation rather than whether the CNI plugin is executed in chained or standalone mode (with multus it just so happens to be standalone).

### CODE REVIEW

**Review by bleggett — COMMENTED** [review]
Generally LGTM but is `k8s.v1.cni.cncf.io/networks` _actually_ multus-specific? It seems to be general purpose and often used _with_ multus but I see it mentioned in other contexts such as: https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/multi-nic?


It's just a label - do we actually need to add a `multus` flag to the Helm API that eventually translates to slapping this label on things, or should we just let the `openshift` profile customize\append labels generically and add this via normal label customization?

**Comment by dgn** [comment]
> Generally LGTM but is `k8s.v1.cni.cncf.io/networks` _actually_ multus-specific? It seems to be general purpose and often used _with_ multus but I see it mentioned in other contexts such as: https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/multi-nic?
> 
> It's just a label - do we actually need to add a `multus` flag to the Helm API that eventually translates to slapping this label on things, or should we just let the `openshift` profile customize\append labels generically and add this via normal label customization?

Yes, it's a label that is generally used for multi-NIC configuration, and that's the issue actually- when using multus we "pretend" to add another NIC but we don't actually do that, it's just a vehicle for us to add our iptables rules. So I'd say touching the label is multus-specific in this case as it shouldn't be required anywhere else. And in fact, we're getting in trouble internally for doing it this way, so I'm in the process of removing the multus (ab)use. TL;DR while we could make this a more generic flag (as it's a rather generic annotation) it should never have been used this way so I'd say let's not generalize it but rather move it into the multus corner and then slowly but surely get rid of that whole corner.

**Comment by jacob-delgado** [comment]
LGTM, but looking for others' feedback before I approve.

The use of "chained" has been especially confusing for people. I'd prefer to even comment out section in values.yaml if possible (I know it's a non-default value of true) and just comment it out. Upgrade issues are my only concern for people.

**Comment by bleggett** [comment]
> > Generally LGTM but is `k8s.v1.cni.cncf.io/networks` _actually_ multus-specific? It seems to be general purpose and often used _with_ multus but I see it mentioned in other contexts such as: https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/multi-nic?
> > 
> > It's just a label - do we actually need to add a `multus` flag to the Helm API that eventually translates to slapping this label on things, or should we just let the `openshift` profile customize\append labels generically and add this via normal label customization?
> 
> Yes, it's a label that is generally used for multi-NIC configuration, and that's the issue actually- when using multus we "pretend" to add another NIC but we don't actually do that, it's just a vehicle for us to add our iptables rules. So I'd say touching the label is multus-specific in this case as it shouldn't be required anywhere else. And in fact, we're getting in trouble internally for doing it this way, so I'm in the process of removing the multus (ab)use. TL;DR while we could make this a more generic flag (as it's a rather generic annotation) it should never have been used this way so I'd say let's not generalize it but rather move it into the multus corner and then slowly but surely get rid of that whole corner.

SGTM, ty!

**Review by bleggett — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
