### PR TITLE
Make stat charts to display last not null instead of mean

### PR DESCRIPTION
**Pull request by carolynhu**
https://github.com/istio/istio/issues/28730

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by douglas-reid** [comment]
Do we need to do this for the other stat boxes as well?

**Comment by carolynhu** [comment]
> Do we need to do this for the other stat boxes as well?

Yes, I just checked, those might cause misleading as well. We should update those charts to reflect this change.

**Comment by carolynhu** [comment]
Verified in one stat chart: https://snapshot.raintank.io/dashboard/snapshot/kQfLCcPkRlUfDehkgnvJahKd07S4I1tL?orgId=2
which send some request in a short period of time, and waiting for 5min, the chart still showing the last not null value.

**Comment by carolynhu** [comment]
One thing strange to me, even if I display the last not null:
https://snapshot.raintank.io/dashboard/snapshot/5PJ0x6YS90tng5U6K5gQf7A1fXfhqf6u
as you can see this general section, still shows the 0ops, and as you can see `Last not null` is correctly populated to the chart.
Screen Shot 2020-11-19 at 10 38 19 PM

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
