### PR TITLE
[release-1.15] Deny h2c upgrade traffic around the code base (#41885)

### LINKED ISSUE #42966: [release-1.15] Deny h2c upgrade traffic around the code base
Manual cherrypick required.

#41872 failed to apply on top of branch "release-1.15":
```
Applying: Deny h2c upgrade traffic around the code base
Using index info to reconstruct a base tree...
M	common/config/.golangci.yml
M	pilot/pkg/bootstrap/server.go
M	pkg/istio-agent/xds_proxy.go
Falling back to patching base and 3-way merge...
Auto-merging pkg/istio-agent/xds_proxy.go
Auto-merging pilot/pkg/bootstrap/server.go
Auto-merging common/config/.golangci.yml
CONFLICT (content): Merge conflict in common/config/.golangci.yml
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Deny h2c upgrade traffic around the code base
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by kfaseela**
Manual cherry-pick of [#41885](https://github.com/istio/istio/pull/41885)

In the Go upstream http2 library, a DOS vector was introduced. The fix for the DOS introduces a request smuggling vulnerability. See https://github.com/golang/go/issues/56352.

All of these are related to h2c upgrades; we don't actually care about this - we only want HTTP/2 prior knowledge and HTTP/1.1.

This PR introduces a wrapper around the h2c library denying h2c upgrades. It also enforces via linting that this is used.

Co-authored-by: John Howard <howardjohn@google.com>

Fixes #42966

### CODE REVIEW

**Comment by kfaseela** [comment]
should be paired with https://github.com/istio/common-files/pull/763

**Comment by kfaseela** [comment]
cc @ericvn @howardjohn

**Review by dhawton — APPROVED** [review]

**Pull request merged**
