### PR TITLE
[TF] Temporarily switch back to RR LB for tests

### PR DESCRIPTION
**Pull request by nmittler**
This is a temporary work-around for #36791 while we investigate.

**Please provide a description of this PR:**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by nmittler** [comment]
@howardjohn the errors don't seem related to this PR. Perhaps https://github.com/istio/istio/pull/37378 broke the security tests somehow?

**Comment by hzxuzhonghu** [comment]
seems no effect at all

**Comment by nmittler** [comment]
Seems like this isn't the cause of the test flakes. Closing.

**Comment by howardjohn** [comment]
On this failure it was a 503 actually: `    multicluster_test.go:144: failed calling a (cluster=remote)->'http://b.echo-1-80610.svc.cluster.local:80/': call failed from a (cluster=remote) to http://b.echo-1-80610.svc.cluster.local:80 (using http): timeout while waiting after 105 attempts, 0/3 successes (last error: response[19] Status Code: 503)`. The flakes are not.

A bit worried turning off the flag breaks everything, and I don't think we have proven it is not the flake cause yet per ^

**Pull request closed without merging**
