### PR TITLE
Import and enforce all XDS config types

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/23909 and related problems

### CODE REVIEW

**Comment by haf** [comment]
How does this PR fix the linked issue?

**Comment by howardjohn** [comment]
The issue is about `unknown message type`. This can no longer happen with this PR, unless they are using a completely custom filter (not supported) or a brand new filter that hasn't been added to the go-control-plane version we are using (could happen, but hopefully unlikely since we update it often)

**Comment by haf** [comment]
Thanks: and it fixes it by at compile-time fetching the list of protos from github? What about reproducible builds?

**Comment by howardjohn** [comment]
It's not fetched at compile time, its fetched one time and the results are
checked into a file; our CI ensures its not out of date. Also its not
calling out to github but looking at its local dependencies as imported by
go tooling, so even if it was compile-time it should still be reproducible

**Comment by haf** [comment]
Ok, thanks!

**Pull request merged**
