### PR TITLE
Cleaning up remaining references to glog.

### PR DESCRIPTION
**Pull request by nmittler**
Removing build dependencies and imports.

Partially addresses #2174

### CODE REVIEW

**Comment by rshriram** [comment]
please update Gopkg.lock by running dep ensure..

**Comment by nmittler** [comment]
@rshriram 

> please update Gopkg.lock by running dep ensure..

Done.

**Comment by ldemailly** [comment]
close in favor of #3163 ?

**Comment by ldemailly** [comment]
^ ?

**Comment by nmittler** [comment]
yeah let's close this one.

**Pull request closed without merging**
