### PR TITLE
build default transport socketmatch each time instead of using shared

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

To prevent cluster patch mutating the sharing default transport socket match

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Comment by howardjohn** [comment]
Wish we use a way to do copy on write. So we can do efficient code like this but if it's patched by envoy filter (which means advanced user) they pay a small penalty to copy it. Not sure how to do that

**Comment by hzxuzhonghu** [comment]
I did think about this, original thought is: check the envoyfilter to decide whether copy or not.

**Comment by ramaraochavali** [comment]
@hzxuzhonghu thinking about this, what would people change in the default socket match via envoy filter?

**Comment by hzxuzhonghu** [comment]
Not intended, could change it by mistake. Say a patch could be applied to all without specifying match conditions.

**Pull request merged**
