### PR TITLE
test changes to support revised ztunnel logic

### PR DESCRIPTION
**Pull request by ilrudie**
**Please provide a description of this PR:**
Change testing to handle the ztunnel svc-addressed traffic changes in https://github.com/istio/ztunnel/pull/873

### CODE REVIEW

**Comment by ilrudie** [comment]
zt changes look like they are ready to merge so we push ahead with this for feedback

**Comment by ilrudie** [comment]
integ-ambient test failure is expected. this PR relies on https://github.com/istio/ztunnel/pull/873 to fully pass testing (locally)

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
