### PR TITLE
refresh Gopkg.lock for k8s release-1.9 update

### PR DESCRIPTION
**Pull request by ayj**

### CODE REVIEW

**Comment by costinm** [comment]
Also, I know it's not related to this PR - but is a good practice to keep the linter green...

**Comment by ayj** [comment]
@costinm, can you /approve?

**Comment by costinm** [comment]
Unfortunately (or fortunately?) they added lint to required.

make fmt 

and

diff --git a/lintconfig_base.json b/lintconfig_base.json
index 4caac077..3ad6ff14 100644
--- a/lintconfig_base.json
+++ b/lintconfig_base.json
@@ -53,6 +53,9 @@
         "mixer/adapter/doc.go",
         "mixer/pkg/config/proto/combined.go",
         ".*.gen.go",
+       "mixer/template/doc.go",
+       "mixer/template/sample/doc.go",
+       "mixer/test/spyAdapter/template/doc.go",
         "should have a package comment",
         "genfiles"
     ]

**Comment by rshriram** [comment]
Closing in favor of #2442

**Pull request closed without merging**
