### PR TITLE
Templates istio.mixer.v1.config.descriptor.ValueType to istio.mixer.v1.template.Value

### PR DESCRIPTION
**Pull request by guptasu**
After this change, all the templates just import proto files only from within api/mixer/v1/template dir.

### CODE REVIEW

**Comment by guptasu** [comment]
@mandarjog (oncall) @rshriram (circleci expert) any idea why CircleCI is failing..

**Comment by rshriram** [comment]
There was a slack discussion. Costin has a pr to fix the missing Envoy thing.

**Comment by guptasu** [comment]
@geeknoid re-lgtm please

**Pull request merged**
