### PR TITLE
Change master to use 1.10 images

### PR DESCRIPTION
**Pull request by jacob-delgado**
Update the version and base image version to point to 1.10

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @howardjohn we will need 1.10-dev.1 images

**Review by howardjohn — APPROVED** [review]

**Comment by jacob-delgado** [comment]
see https://github.com/istio/istio/issues/29490

**Pull request merged**
