### PR TITLE
update Kiali to 1.55 (for Istio 1.15)

### LINKED ISSUE #5396: Update Istio 1.15 upstream release to Kiali 1.55.
The release branch has been cut, so this should be done ASAP.

### PR DESCRIPTION
**Pull request by jmazzitelli**
cc @howardjohn

fixes: https://github.com/kiali/kiali/issues/5396

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Someone please test this :) I just generated it as we usually do, but I have not yet actually installed this new kiali addon to Istio 1.15. So a quick smoke test would be "helpful" :)

**Comment by jmazzitelli** [comment]
@howardjohn the last time we did this we did not include release notes (https://github.com/istio/istio/pull/38671/files) -- is that still the same going forward?

**Comment by jmazzitelli** [comment]
My smoke testing looks good (I have Istio 1.14 but it shouldn't matter just to see kiali come up with the new 1.55 addon yaml)

```
$ kubectl apply -f samples/addons/kiali.yaml 
serviceaccount/kiali created
configmap/kiali created
clusterrole.rbac.authorization.k8s.io/kiali-viewer created
clusterrole.rbac.authorization.k8s.io/kiali created
clusterrolebinding.rbac.authorization.k8s.io/kiali created
role.rbac.authorization.k8s.io/kiali-controlplane created
rolebinding.rbac.authorization.k8s.io/kiali-controlplane created
service/kiali created
deployment.apps/kiali created

$ kubectl get pods -n istio-system -l app.kubernetes.io/name=kiali
NAME                     READY   STATUS    RESTARTS   AGE
kiali-585d856766-svpbc   1/1     Running   0          44s

$ kubectl logs -n istio-system -l app.kubernetes.io/name=kiali --tail=-1
2022/08/22 15:23:59 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2022-08-22T15:23:59Z INF Kiali: Version: v1.55.0, Commit: f1c32fc6abb0ad590cd75715b94054622a98d8f3

2022-08-22T15:23:59Z INF Using authentication strategy [anonymous]
2022-08-22T15:23:59Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2022-08-22T15:23:59Z INF Some validation errors will be ignored [KIA1201]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2022-08-22T15:23:59Z INF Mesh Name: [Istio], Mesh Version: [1.14.1]
2022-08-22T15:23:59Z INF Server endpoint will start at [:20001/kiali]
2022-08-22T15:23:59Z INF Server endpoint will serve static content from [/opt/kiali/console]
2022-08-22T15:23:59Z INF Starting Metrics Server on [:9090]
2022-08-22T15:23:59Z INF Initializing Kiali Cache
2022-08-22T15:23:59Z INF Kiali Cache is active for namespaces [.*]
...
```

**Comment by ericvn** [comment]
I see release notes for other products including version updates, and it seems that it would be good here as well. That said, I know we don't necessarily mention Envoy updates other than maybe version with each minor update, so I could see not doing it here as well.

**Comment by jmazzitelli** [comment]
release notes yaml added

**Review by ericvn — APPROVED** [review]
RN looks good.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
