### PR TITLE
Skip upstream tls if the traffic is already tls encrypted

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

fixes: #17031

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rshriram** [comment]
@howardjohn / @yxue / @vadimeisenbergibm what do you guys think of this? I think this wont break anything but want to pick your brains to see if you foresee other issues here.

**Comment by howardjohn** [comment]
@hzxuzhonghu needs a rebase

**Comment by howardjohn** [comment]
still needs a rebase

**Comment by hzxuzhonghu** [comment]
Let's discuss it in #17031

**Comment by rshriram** [comment]
@hzxuzhonghu let us reopen the request. I think there is value in restricting this to just the sidecars. Because in sidecars, a port that is marked as HTTPS will have a sni match in the listeners. If an end user creates a destination rule by mistake, then it would become double encrypted and fail.

**Comment by hzxuzhonghu** [comment]
@rshriram https://github.com/istio/istio/issues/17031#issuecomment-531760062 This config also applies to sidecars, which still not work.

**Comment by rshriram** [comment]
hmm.. okay

**Pull request closed without merging**
