### PR TITLE
Merge collab-gcp-identity with master .

### PR DESCRIPTION
**Pull request by incfly**

### CODE REVIEW

**Comment by wattli** [comment]
Can we merge from istio:master to istio:collab-gcp-identity directly?

**Comment by incfly** [comment]
I tried that once, but that not works well. Because people are constantly
pushing new commits into istio:master, which removes the LGTM label and
invalidate the presubmit run.

**Comment by incfly** [comment]
But I can manually `git pull upstream master into incfly:collab-gcp-identity` once https://github.com/istio/istio/pull/6305 is merged.

**Comment by wattli** [comment]
okay, 

/lgtm

**Comment by wattli** [comment]
https://screenshot.googleplex.com/QCuZPoqW3Cp, seems github does not recognize this merge, any ideas?

**Comment by incfly** [comment]
I've did some experiments at https://github.com/incfly/github-mergeflow

It turns out we should use "merge with all commits", not "Squash and merge" when merging master into `collab-gcp-identity`. Only in this way, git can recognize the previous existing commits by comparing their SHA. And when merge collab-gcp-identity back to the master, IMO, we should also use "merge with all commits" and not squash.

To fix the current situation, we can revert this and create another merge using "merge with all commits."

@hklai Could you comment on above proposal?

**Comment by hklai** [comment]
Yes merge commit is preferred. And only admin can do it. 

My question however is whether it is safe to merge these changes to master now? Are they needed for 1.0?

**Comment by incfly** [comment]
@hklai Thanks, but we're supposed have the permission to merge commit in collab-gcp-identity right?

We don't need to merge to master at this point, this is just to prepare for the future.

Will do
1. Revert this PR and redo the merging commits from master.
2. Update the wiki corresponding section.

**Comment by hklai** [comment]
It is a repo-wide setting, not per branch. It is disabled currently to prevent people from populating the codebase.

And normally I enable the setting, perform a commit merge, and disable it again,

> We don't need to merge to master at this point, this is just to prepare for the future.
What is the risk however? If it is high and it is not needed, we probably should defer it.

**Comment by incfly** [comment]
> What is the risk however? If it is high and it is not needed, we probably should defer it.
We don't have concrete schedule to merge back to master, but it will happen eventually.

**Pull request merged**
