### PR TITLE
Fixes 'No Data Points' error for out of process adapter

### PR DESCRIPTION
**Pull request by PhilipGough**
Port #10903 of to 1.1

### CODE REVIEW

**Comment by PhilipGough** [comment]
Dashboard : https://grafana.com/dashboards/9669

**Comment by mandarjog** [comment]
Looks like you replace an equality check with a regex match. A better approach would be to un-escape pattern and then apply equality check, can you investigate that?

**Comment by PhilipGough** [comment]
@mandarjog I can take a look at that for sure but the regex match is used elsewhere in the file also.

**Comment by PhilipGough** [comment]
@mandarjog from what I can see, there is no mechanism (open to correction) to unescape queries to Prometheus datasource. I do have an alternative approach though. 

The `$adapter` values are gathered from a call to `label_values()` call to Prometheus. Out of process adapters are returned in the format `<adapter-name>.adapter.<adapter-namespace>`.

 We could add a top level regex to strip this down to the first `.` and everything would work fine. Only problem I could see with this would be if it is possible to deploy adapters in namespaces outside of `istio-system` there would be a potential clash. WDYT?

**Comment by PhilipGough** [comment]
@mandarjog any suggestions/comments on how to progress this PR?

**Comment by PhilipGough** [comment]
not stale

**Comment by PhilipGough** [comment]
@mandarjog rebased

**Comment by douglas-reid** [comment]
@duderino can you please merge this for 1.1?  thanks.

**Comment by bianpengyuan** [comment]
not stale

**Comment by duderino** [comment]
@PhilipGough this has been languishing, sorry.  @mandarjog or @douglas-reid please regive this a lgtm or express concerns.  If none then it'd be good for @wenchenglu to merge this into 1.1.4 next week.

**Comment by PhilipGough** [comment]
Not stale /retest

**Comment by douglas-reid** [comment]
This change cannot be impacting anything but dashboards. It is safe to merge and we _should_ add it ASAP.

**Comment by douglas-reid** [comment]
I suspect a rebase is needed to pass the tests, but I'm gonna try one more time.

**Comment by PhilipGough** [comment]
@douglas-reid hey, sorry for delay had been swamped. Rebased

**Comment by douglas-reid** [comment]
@duderino can we merge?

**Comment by douglas-reid** [comment]
@PhilipGough I took a different approach to getting this PR in, as time was of the essence with the pending 1.2 cu. I added it to a clean up PR for the new installer (which should be backported to `master` here).

Thanks again for calling this to our attention and developing the fix. I'm sorry we could not get this PR in directly.

**Pull request closed without merging**
