### PR TITLE
Remove SyntheticServiceEntry artifacts from galley

### PR DESCRIPTION
**Pull request by Nino-K**
This is part of the istiod cleanup work.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
In order to catch up, without SSE, how will incremental mcp implemented now?

**Comment by esnible** [comment]
TestAnalyzers unit test is failing.  Please fix the tests in _galley/pkg/config/analysis/analyzers/analyzers_test.go_.  Perhaps _galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go_ is the problem ... it checked Synthetic Service Entries.

**Comment by ayj** [comment]
The syntheticServiceEntry snapshot should also be removed.

**Comment by Nino-K** [comment]
The failure in the following test `TestAnalyzers/virtualServiceDestinationHosts` is due to the analyzer framework relies on SyntheticSerivceEntries for both hand define resources like ServiceEntries CRs and discovered services. This is definitely going to break in istiod work. I think for now it would make sense to remove the SSE code in galley that is intended for Pilot over MCP however leave galley's SSE processing pipeline intact since analysis framework relies on that.  Please let me know WDYT.

**Comment by Nino-K** [comment]
> In order to catch up, without SSE, how will incremental mcp implemented now?

@hzxuzhonghu since as part of istiod work galley and pilot will be merged so we can orchestrate that internally as opposed to over MCP.

**Comment by hzxuzhonghu** [comment]
Then how can we do that when deploying istiod delegate.

**Comment by ayj** [comment]
@hzxuzhonghu, can you clarify your case re: istiod delegate?

**Comment by hzxuzhonghu** [comment]
@ayj I mean istiod works as a standalone MCP server to support multi-clusters. This is a case required, IIRC

**Comment by ayj** [comment]
If we still want to distribute SEE from cross-cluster it should use Pilot's logic. @nmittler was also working on some enhancements to endpoint distribution which may relevant here.

**Comment by hzxuzhonghu** [comment]
I think @seflerZ should reply on this.

**Comment by seflerZ** [comment]
1. If SSE will be removed from Galley, how about the SSE controller in Pilot.
2. If SSE controller in Pilot will also be removed, how do we send services incrementally through MCP? Currently, only the SSE implemented the incremental MCP. Does that mean we will implement another incremental interface?

**Comment by nmittler** [comment]
@ayj should we just switch over the MCP client in pilot to use incremental at this point?

**Comment by ayj** [comment]
> should we just switch over the MCP client in pilot to use incremental at this point?

Is the proposal to use normal ServiceEntry (not SSE) for endpoint distribution? Enabling incremental for ServiceEntry collections (or all collections) is an option. With the switch to istiod we no longer don't have great e2e test coverage of MCP. @Nino-K @seflerZ @hzxuzhonghu, do you know the current state of e2e testing for the projects that use MCP to program Pilot?

**Comment by Nino-K** [comment]
@ayj currently we do have a basic MCP test in our e2e that uses an in-memory MCP client to configure pilot. However, it does not test the incremental. Looking at the test (tests/e2e/tests/pilot/mcp_test.go) it looks like it was added during development of MCP and some features of MCP that were added later are not tested here.

**Comment by seflerZ** [comment]
@ayj Switching to ServiceEntry for service and endpoints distribution is acceptable. The question is whether is previously implemented MCP incremental will be transferred to normal MCP controller. I don't see other MCP test coverage except "mcp_test.go"

**Comment by ayj** [comment]
> The question is whether is previously implemented MCP incremental will be transferred to normal MCP controller(Maybe this feature has been used in production environment). I don't see other MCP test coverage except "mcp_test.go"

The underlying MCP incremental machinery has some stress tests under istio.io/istio/pkg/mcp/tests/stress. Enabling incremental requires setting [Incremental=true](https://github.com/istio/istio/blob/6a6c3a08dd883a3828e28b4883cf6d74bb07dac6/pkg/mcp/source/source.go#L96) on the server and client for the service entry collection.

**Pull request merged**
