### PR TITLE
Cleaning up RBAC permissions part 1

### PR DESCRIPTION
**Pull request by sbezverk**
**What this PR does / why we need it**: 

This PR is a part of "excessive RBAC permissions cleanup process". It limits RBAC permissions for 

configmaps  to: get, list, watch, update

endpoints, pods, services to:  get, list, watch

```release-note
Limiting  RBAC rules to what is only required.
```

### CODE REVIEW

**Comment by andraxylia** [comment]
Please edit the description of the PR and add a short release note : https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#write-release-notes-if-needed

**Comment by sbezverk** [comment]
@andraxylia done. Please let me know is it is sufficient.

**Comment by andraxylia** [comment]
Can you click on the istio link in "you can't request testing unless you are a istio member" and request to be added to Istio Organization? After you are added, you will get an email, you will need to accept.

**Comment by sbezverk** [comment]
I tried to access the link in that message and it only gives a list of istio members. I do not see any place where the membership can be requested, I guess I am missing something here ☹
Serguei

**Comment by andraxylia** [comment]
@geeknoid can you please help with adding to Istio org?

**Comment by geeknoid** [comment]
Done, the invitation to join the team has been sent via email.

**Comment by sbezverk** [comment]
@geeknoid @andraxylia thanks a lot, appreciate your help.

**Comment by sbezverk** [comment]
@andraxylia can you lgtm this PR?

**Comment by andraxylia** [comment]
The PR was in approved state, but the branch is out-of-date with master, the bot was supposed to merge it automatically @yutongz

**Comment by yutongz** [comment]
/test prow/e2e-smoke.sh

@andraxylia Yes, it's going to be fine. Robot can handle from here. The issue is we just maked the e2e-smoke public so we have to rerun it to allow result being reported back.

**Pull request merged**
