### PR TITLE
Fix generate.main indents

### PR DESCRIPTION
**Pull request by kebe7jun**
This change makes the results of `go run generate.main.go messages.yaml messages.gen.go` match messages.gen.go file.

[X] User Experience

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by esnible — COMMENTED** [review]
I use ```
export REPO_ROOT=~/go/src/istio.io/istio
cd galley/pkg/config/analysis/msg
go generate
```

On OSX to make the messages.  They seem to match.  In the past there may have been times I needed to use `BUILD_WITH_CONTAINER=1 time make go-gen` which took a long time but let the build happen in Istio's dev container.

How are you testing this and how is it failing without these changes?

**Comment by kebe7jun** [comment]
If only run `go run "$REPO_ROOT/galley/pkg/config/analysis/msg/generate.main.go" messages.yaml messages.gen.go`, they are not matching, but it will be fixed by goimports. 
I would close this pr if it wasn't necessary.

**Comment by esnible** [comment]
> If only run `go run "$REPO_ROOT/galley/pkg/config/analysis/msg/generate.main.go" messages.yaml messages.gen.go`, they are not matching, but it will be fixed by goimports.

I believe you.  I've seen this before on my own system.  Currently I **don't** see this, and what I'm asking is what OS you are using.  We want these scripts to work independent of your OS and settings, but it would help with the review to know how to reproduce the problem.

**Comment by kebe7jun** [comment]
> > If only run `go run "$REPO_ROOT/galley/pkg/config/analysis/msg/generate.main.go" messages.yaml messages.gen.go`, they are not matching, but it will be fixed by goimports.
> 
> I believe you. I've seen this before on my own system. Currently I **don't** see this, and what I'm asking is what OS you are using. We want these scripts to work independent of your OS and settings, but it would help with the review to know how to reproduce the problem.

OS: MacOS Catalina 10.5.7
Go Version: go1.15 darwin/amd64

Reproduction Steps:

```bash
➜  msg git:(master) ✗ uname -a
Darwin Kebes-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
➜  msg git:(master) ✗ go version
go version go1.15 darwin/amd64
➜  istio git:(master) cd /Users/kebeliu/workspace/istio/galley/pkg/config/analysis/msg
➜  msg git:(master) git --no-pager diff
➜  msg git:(master) rm messages.gen.go 
➜  msg git:(master) ✗ go run generate.main.go messages.yaml messages.gen.go                                                       
➜  msg git:(master) ✗ git --no-pager diff
diff --git a/galley/pkg/config/analysis/msg/messages.gen.go b/galley/pkg/config/analysis/msg/messages.gen.go
index a9ab07c247..7dfd35ac98 100755
--- a/galley/pkg/config/analysis/msg/messages.gen.go
+++ b/galley/pkg/config/analysis/msg/messages.gen.go
@@ -1,3 +1,4 @@
+
 // GENERATED FILE -- DO NOT EDIT
 //
 
@@ -12,181 +13,183 @@ var (
        // InternalError defines a diag.MessageType for message "InternalError".
        // Description: There was an internal error in the toolchain. This is almost always a bug in the implementation.
        InternalError = diag.NewMessageType(diag.Error, "IST0001", "Internal error: %v")
-
+       
        // Deprecated defines a diag.MessageType for message "Deprecated".
        // Description: A feature that the configuration is depending on is now deprecated.
        Deprecated = diag.NewMessageType(diag.Warning, "IST0002", "Deprecated: %s")
-
+       
        // ReferencedResourceNotFound defines a diag.MessageType for message "ReferencedResourceNotFound".
        // Description: A resource being referenced does not exist.
        ReferencedResourceNotFound = diag.NewMessageType(diag.Error, "IST0101", "Referenced %s not found: %q")
-
+       
        // NamespaceNotInjected defines a diag.MessageType for message "NamespaceNotInjected".
        // Description: A namespace is not enabled for Istio injection.
        NamespaceNotInjected = diag.NewMessageType(diag.Info, "IST0102", "The namespace is not enabled for Istio injection. Run 'kubectl label namespace %s istio-injection=enabled' to enable it, or 'kubectl label namespace %s istio-injection=disabled' to explicitly mark it as not needing injection.")
-
+       
        // PodMissingProxy defines a diag.MessageType for message "PodMissingProxy".
        // Description: A pod is missing the Istio proxy.
        PodMissingProxy = diag.NewMessageType(diag.Warning, "IST0103", "The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.")
-
+       
        // GatewayPortNotOnWorkload defines a diag.MessageType for message "GatewayPortNotOnWorkload".
        // Description: Unhandled gateway port
        GatewayPortNotOnWorkload = diag.NewMessageType(diag.Warning, "IST0104", "The gateway refers to a port that is not exposed on the workload (pod selector %s; port %d)")
-
+       
        // IstioProxyImageMismatch defines a diag.MessageType for message "IstioProxyImageMismatch".
        // Description: The image of the Istio proxy running on the pod does not match the image defined in the injection configuration.
        IstioProxyImageMismatch = diag.NewMessageType(diag.Warning, "IST0105", "The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: %s; injection configuration image: %s). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.")
-
+       
        // SchemaValidationError defines a diag.MessageType for message "SchemaValidationError".
        // Description: The resource has a schema validation error.
        SchemaValidationError = diag.NewMessageType(diag.Error, "IST0106", "Schema validation error: %v")
-
+       
        // MisplacedAnnotation defines a diag.MessageType for message "MisplacedAnnotation".
        // Description: An Istio annotation is applied to the wrong kind of resource.
        MisplacedAnnotation = diag.NewMessageType(diag.Warning, "IST0107", "Misplaced annotation: %s can only be applied to %s")
-
+       
        // UnknownAnnotation defines a diag.MessageType for message "UnknownAnnotation".
        // Description: An Istio annotation is not recognized for any kind of resource
        UnknownAnnotation = diag.NewMessageType(diag.Warning, "IST0108", "Unknown annotation: %s")
-
+       
        // ConflictingMeshGatewayVirtualServiceHosts defines a diag.MessageType for message "ConflictingMeshGatewayVirtualServiceHosts".
        // Description: Conflicting hosts on VirtualServices associated with mesh gateway
        ConflictingMeshGatewayVirtualServiceHosts = diag.NewMessageType(diag.Error, "IST0109", "The VirtualServices %s associated with mesh gateway define the same host %s which can lead to undefined behavior. This can be fixed by merging the conflicting VirtualServices into a single resource.")
-
+       
        // ConflictingSidecarWorkloadSelectors defines a diag.MessageType for message "ConflictingSidecarWorkloadSelectors".
        // Description: A Sidecar resource selects the same workloads as another Sidecar resource
        ConflictingSidecarWorkloadSelectors = diag.NewMessageType(diag.Error, "IST0110", "The Sidecars %v in namespace %q select the same workload pod %q, which can lead to undefined behavior.")
-
+       
        // MultipleSidecarsWithoutWorkloadSelectors defines a diag.MessageType for message "MultipleSidecarsWithoutWorkloadSelectors".
        // Description: More than one sidecar resource in a namespace has no workload selector
        MultipleSidecarsWithoutWorkloadSelectors = diag.NewMessageType(diag.Error, "IST0111", "The Sidecars %v in namespace %q have no workload selector, which can lead to undefined behavior.")
-
+       
        // VirtualServiceDestinationPortSelectorRequired defines a diag.MessageType for message "VirtualServiceDestinationPortSelectorRequired".
        // Description: A VirtualService routes to a service with more than one port exposed, but does not specify which to use.
        VirtualServiceDestinationPortSelectorRequired = diag.NewMessageType(diag.Error, "IST0112", "This VirtualService routes to a service %q that exposes multiple ports %v. Specifying a port in the destination is required to disambiguate.")
-
+       
        // MTLSPolicyConflict defines a diag.MessageType for message "MTLSPolicyConflict".
        // Description: A DestinationRule and Policy are in conflict with regards to mTLS.
        MTLSPolicyConflict = diag.NewMessageType(diag.Error, "IST0113", "A DestinationRule and Policy are in conflict with regards to mTLS for host %s. The DestinationRule %q specifies that mTLS must be %t but the Policy object %q specifies %s.")
-
+       
        // DeploymentAssociatedToMultipleServices defines a diag.MessageType for message "DeploymentAssociatedToMultipleServices".
        // Description: The resulting pods of a service mesh deployment can't be associated with multiple services using the same port but different protocols.
        DeploymentAssociatedToMultipleServices = diag.NewMessageType(diag.Warning, "IST0116", "This deployment %s is associated with multiple services using port %d but different protocols: %v")
-
+       
        // DeploymentRequiresServiceAssociated defines a diag.MessageType for message "DeploymentRequiresServiceAssociated".
        // Description: The resulting pods of a service mesh deployment must be associated with at least one service.
        DeploymentRequiresServiceAssociated = diag.NewMessageType(diag.Warning, "IST0117", "No service associated with this deployment. Service mesh deployments must be associated with a service.")
-
+       
        // PortNameIsNotUnderNamingConvention defines a diag.MessageType for message "PortNameIsNotUnderNamingConvention".
        // Description: Port name is not under naming convention. Protocol detection is applied to the port.
        PortNameIsNotUnderNamingConvention = diag.NewMessageType(diag.Info, "IST0118", "Port name %s (port: %d, targetPort: %s) doesn't follow the naming convention of Istio port.")
-
+       
        // JwtFailureDueToInvalidServicePortPrefix defines a diag.MessageType for message "JwtFailureDueToInvalidServicePortPrefix".
        // Description: Authentication policy with JWT targets Service with invalid port specification.
        JwtFailureDueToInvalidServicePortPrefix = diag.NewMessageType(diag.Warning, "IST0119", "Authentication policy with JWT targets Service with invalid port specification (port: %d, name: %s, protocol: %s, targetPort: %s).")
-
+       
        // InvalidRegexp defines a diag.MessageType for message "InvalidRegexp".
        // Description: Invalid Regex
        InvalidRegexp = diag.NewMessageType(diag.Warning, "IST0122", "Field %q regular expression invalid: %q (%s)")
-
+       
        // NamespaceMultipleInjectionLabels defines a diag.MessageType for message "NamespaceMultipleInjectionLabels".
        // Description: A namespace has both new and legacy injection labels
        NamespaceMultipleInjectionLabels = diag.NewMessageType(diag.Warning, "IST0123", "The namespace has both new and legacy injection labels. Run 'kubectl label namespace %s istio.io/rev-' or 'kubectl label namespace %s istio-injection-'")
-
+       
        // InvalidAnnotation defines a diag.MessageType for message "InvalidAnnotation".
        // Description: An Istio annotation that is not valid
        InvalidAnnotation = diag.NewMessageType(diag.Warning, "IST0125", "Invalid annotation %s: %s")
-
+       
        // UnknownMeshNetworksServiceRegistry defines a diag.MessageType for message "UnknownMeshNetworksServiceRegistry".
        // Description: A service registry in Mesh Networks is unknown
        UnknownMeshNetworksServiceRegistry = diag.NewMessageType(diag.Error, "IST0126", "Unknown service registry %s in network %s")
-
+       
        // NoMatchingWorkloadsFound defines a diag.MessageType for message "NoMatchingWorkloadsFound".
        // Description: There aren't workloads matching the resource labels
        NoMatchingWorkloadsFound = diag.NewMessageType(diag.Warning, "IST0127", "No matching workloads for this resource with the following labels: %s")
-
+       
        // NoServerCertificateVerificationDestinationLevel defines a diag.MessageType for message "NoServerCertificateVerificationDestinationLevel".
        // Description: No caCertificates are set in DestinationRule, this results in no verification of presented server certificate.
        NoServerCertificateVerificationDestinationLevel = diag.NewMessageType(diag.Error, "IST0128", "DestinationRule %s in namespace %s has TLS mode set to %s but no caCertificates are set to validate server identity for host: %s")
-
+       
        // NoServerCertificateVerificationPortLevel defines a diag.MessageType for message "NoServerCertificateVerificationPortLevel".
        // Description: No caCertificates are set in DestinationRule, this results in no verification of presented server certificate for traffic to a given port.
        NoServerCertificateVerificationPortLevel = diag.NewMessageType(diag.Warning, "IST0129", "DestinationRule %s in namespace %s has TLS mode set to %s but no caCertificates are set to validate server identity for host: %s at port %s")
-
+       
        // VirtualServiceUnreachableRule defines a diag.MessageType for message "VirtualServiceUnreachableRule".
        // Description: A VirtualService rule will never be used because a previous rule uses the same match.
        VirtualServiceUnreachableRule = diag.NewMessageType(diag.Warning, "IST0130", "VirtualService rule %v not used (%s).")
-
+       
        // VirtualServiceIneffectiveMatch defines a diag.MessageType for message "VirtualServiceIneffectiveMatch".
        // Description: A VirtualService rule match duplicates a match in a previous rule.
        VirtualServiceIneffectiveMatch = diag.NewMessageType(diag.Info, "IST0131", "VirtualService rule %v match %v is not used (duplicates a match in rule %v).")
-
+       
        // VirtualServiceHostNotFoundInGateway defines a diag.MessageType for message "VirtualServiceHostNotFoundInGateway".
        // Description: Host defined in VirtualService not found in Gateway.
        VirtualServiceHostNotFoundInGateway = diag.NewMessageType(diag.Warning, "IST0132", "one or more host %v defined in VirtualService %s not found in Gateway %s.")
-
+       
        // SchemaWarning defines a diag.MessageType for message "SchemaWarning".
        // Description: The resource has a schema validation warning.
        SchemaWarning = diag.NewMessageType(diag.Warning, "IST0133", "Schema validation warning: %v")
-
+       
        // ServiceEntryAddressesRequired defines a diag.MessageType for message "ServiceEntryAddressesRequired".
        // Description: Virtual IP addresses are required for ports serving TCP (or unset) protocol
        ServiceEntryAddressesRequired = diag.NewMessageType(diag.Warning, "IST0134", "ServiceEntry addresses are required for this protocol.")
-
+       
        // DeprecatedAnnotation defines a diag.MessageType for message "DeprecatedAnnotation".
        // Description: A resource is using a deprecated Istio annotation.
        DeprecatedAnnotation = diag.NewMessageType(diag.Info, "IST0135", "Annotation %q has been deprecated and may not work in future Istio versions.")
-
+       
        // AlphaAnnotation defines a diag.MessageType for message "AlphaAnnotation".
        // Description: An Istio annotation may not be suitable for production.
        AlphaAnnotation = diag.NewMessageType(diag.Info, "IST0136", "Annotation %q is part of an alpha-phase feature and may be incompletely supported.")
+       
 )
 
 // All returns a list of all known message types.
 func All() []*diag.MessageType {
        return []*diag.MessageType{
-               InternalError,
-               Deprecated,
-               ReferencedResourceNotFound,
-               NamespaceNotInjected,
-               PodMissingProxy,
-               GatewayPortNotOnWorkload,
-               IstioProxyImageMismatch,
-               SchemaValidationError,
-               MisplacedAnnotation,
-               UnknownAnnotation,
-               ConflictingMeshGatewayVirtualServiceHosts,
-               ConflictingSidecarWorkloadSelectors,
-               MultipleSidecarsWithoutWorkloadSelectors,
-               VirtualServiceDestinationPortSelectorRequired,
-               MTLSPolicyConflict,
-               DeploymentAssociatedToMultipleServices,
-               DeploymentRequiresServiceAssociated,
-               PortNameIsNotUnderNamingConvention,
-               JwtFailureDueToInvalidServicePortPrefix,
-               InvalidRegexp,
-               NamespaceMultipleInjectionLabels,
-               InvalidAnnotation,
-               UnknownMeshNetworksServiceRegistry,
-               NoMatchingWorkloadsFound,
-               NoServerCertificateVerificationDestinationLevel,
-               NoServerCertificateVerificationPortLevel,
-               VirtualServiceUnreachableRule,
-               VirtualServiceIneffectiveMatch,
-               VirtualServiceHostNotFoundInGateway,
-               SchemaWarning,
-               ServiceEntryAddressesRequired,
-               DeprecatedAnnotation,
-               AlphaAnnotation,
+                       InternalError,
+                       Deprecated,
+                       ReferencedResourceNotFound,
+                       NamespaceNotInjected,
+                       PodMissingProxy,
+                       GatewayPortNotOnWorkload,
+                       IstioProxyImageMismatch,
+                       SchemaValidationError,
+                       MisplacedAnnotation,
+                       UnknownAnnotation,
+                       ConflictingMeshGatewayVirtualServiceHosts,
+                       ConflictingSidecarWorkloadSelectors,
+                       MultipleSidecarsWithoutWorkloadSelectors,
+                       VirtualServiceDestinationPortSelectorRequired,
+                       MTLSPolicyConflict,
+                       DeploymentAssociatedToMultipleServices,
+                       DeploymentRequiresServiceAssociated,
+                       PortNameIsNotUnderNamingConvention,
+                       JwtFailureDueToInvalidServicePortPrefix,
+                       InvalidRegexp,
+                       NamespaceMultipleInjectionLabels,
+                       InvalidAnnotation,
+                       UnknownMeshNetworksServiceRegistry,
+                       NoMatchingWorkloadsFound,
+                       NoServerCertificateVerificationDestinationLevel,
+                       NoServerCertificateVerificationPortLevel,
+                       VirtualServiceUnreachableRule,
+                       VirtualServiceIneffectiveMatch,
+                       VirtualServiceHostNotFoundInGateway,
+                       SchemaWarning,
+                       ServiceEntryAddressesRequired,
+                       DeprecatedAnnotation,
+                       AlphaAnnotation,
        }
 }
 
+
 // NewInternalError returns a new diag.Message based on InternalError.
 func NewInternalError(r *resource.Instance, detail string) diag.Message {
        return diag.NewMessage(
                InternalError,
                r,
-               detail,
+                       detail,
        )
 }
 
@@ -195,7 +198,7 @@ func NewDeprecated(r *resource.Instance, detail string) diag.Message {
        return diag.NewMessage(
                Deprecated,
                r,
-               detail,
+                       detail,
        )
 }
 
@@ -204,8 +207,8 @@ func NewReferencedResourceNotFound(r *resource.Instance, reftype string, refval
        return diag.NewMessage(
                ReferencedResourceNotFound,
                r,
-               reftype,
-               refval,
+                       reftype,
+                       refval,
        )
 }
 
@@ -214,8 +217,8 @@ func NewNamespaceNotInjected(r *resource.Instance, namespace string, namespace2
        return diag.NewMessage(
                NamespaceNotInjected,
                r,
-               namespace,
-               namespace2,
+                       namespace,
+                       namespace2,
        )
 }
 
@@ -232,8 +235,8 @@ func NewGatewayPortNotOnWorkload(r *resource.Instance, selector string, port int
        return diag.NewMessage(
                GatewayPortNotOnWorkload,
                r,
-               selector,
-               port,
+                       selector,
+                       port,
        )
 }
 
@@ -242,8 +245,8 @@ func NewIstioProxyImageMismatch(r *resource.Instance, proxyImage string, injecti
        return diag.NewMessage(
                IstioProxyImageMismatch,
                r,
-               proxyImage,
-               injectionImage,
+                       proxyImage,
+                       injectionImage,
        )
 }
 
@@ -252,7 +255,7 @@ func NewSchemaValidationError(r *resource.Instance, err error) diag.Message {
        return diag.NewMessage(
                SchemaValidationError,
                r,
-               err,
+                       err,
        )
 }
 
@@ -261,8 +264,8 @@ func NewMisplacedAnnotation(r *resource.Instance, annotation string, kind string
        return diag.NewMessage(
                MisplacedAnnotation,
                r,
-               annotation,
-               kind,
+                       annotation,
+                       kind,
        )
 }
 
@@ -271,7 +274,7 @@ func NewUnknownAnnotation(r *resource.Instance, annotation string) diag.Message
        return diag.NewMessage(
                UnknownAnnotation,
                r,
-               annotation,
+                       annotation,
        )
 }
 
@@ -280,8 +283,8 @@ func NewConflictingMeshGatewayVirtualServiceHosts(r *resource.Instance, virtualS
        return diag.NewMessage(
                ConflictingMeshGatewayVirtualServiceHosts,
                r,
-               virtualServices,
-               host,
+                       virtualServices,
+                       host,
        )
 }
 
@@ -290,9 +293,9 @@ func NewConflictingSidecarWorkloadSelectors(r *resource.Instance, conflictingSid
        return diag.NewMessage(
                ConflictingSidecarWorkloadSelectors,
                r,
-               conflictingSidecars,
-               namespace,
-               workloadPod,
+                       conflictingSidecars,
+                       namespace,
+                       workloadPod,
        )
 }
 
@@ -301,8 +304,8 @@ func NewMultipleSidecarsWithoutWorkloadSelectors(r *resource.Instance, conflicti
        return diag.NewMessage(
                MultipleSidecarsWithoutWorkloadSelectors,
                r,
-               conflictingSidecars,
-               namespace,
+                       conflictingSidecars,
+                       namespace,
        )
 }
 
@@ -311,8 +314,8 @@ func NewVirtualServiceDestinationPortSelectorRequired(r *resource.Instance, dest
        return diag.NewMessage(
                VirtualServiceDestinationPortSelectorRequired,
                r,
-               destHost,
-               destPorts,
+                       destHost,
+                       destPorts,
        )
 }
 
@@ -321,11 +324,11 @@ func NewMTLSPolicyConflict(r *resource.Instance, host string, destinationRuleNam
        return diag.NewMessage(
                MTLSPolicyConflict,
                r,
-               host,
-               destinationRuleName,
-               destinationRuleMTLSMode,
-               policyName,
-               policyMTLSMode,
+                       host,
+                       destinationRuleName,
+                       destinationRuleMTLSMode,
+                       policyName,
+                       policyMTLSMode,
        )
 }
 
@@ -334,9 +337,9 @@ func NewDeploymentAssociatedToMultipleServices(r *resource.Instance, deployment
        return diag.NewMessage(
                DeploymentAssociatedToMultipleServices,
                r,
-               deployment,
-               port,
-               services,
+                       deployment,
+                       port,
+                       services,
        )
 }
 
@@ -353,9 +356,9 @@ func NewPortNameIsNotUnderNamingConvention(r *resource.Instance, portName string
        return diag.NewMessage(
                PortNameIsNotUnderNamingConvention,
                r,
-               portName,
-               port,
-               targetPort,
+                       portName,
+                       port,
+                       targetPort,
        )
 }
 
@@ -364,10 +367,10 @@ func NewJwtFailureDueToInvalidServicePortPrefix(r *resource.Instance, port int,
        return diag.NewMessage(
                JwtFailureDueToInvalidServicePortPrefix,
                r,
-               port,
-               portName,
-               protocol,
-               targetPort,
+                       port,
+                       portName,
+                       protocol,
+                       targetPort,
        )
 }
 
@@ -376,9 +379,9 @@ func NewInvalidRegexp(r *resource.Instance, where string, re string, problem str
        return diag.NewMessage(
                InvalidRegexp,
                r,
-               where,
-               re,
-               problem,
+                       where,
+                       re,
+                       problem,
        )
 }
 
@@ -387,8 +390,8 @@ func NewNamespaceMultipleInjectionLabels(r *resource.Instance, namespace string,
        return diag.NewMessage(
                NamespaceMultipleInjectionLabels,
                r,
-               namespace,
-               namespace2,
+                       namespace,
+                       namespace2,
        )
 }
 
@@ -397,8 +400,8 @@ func NewInvalidAnnotation(r *resource.Instance, annotation string, problem strin
        return diag.NewMessage(
                InvalidAnnotation,
                r,
-               annotation,
-               problem,
+                       annotation,
+                       problem,
        )
 }
 
@@ -407,8 +410,8 @@ func NewUnknownMeshNetworksServiceRegistry(r *resource.Instance, serviceregistry
        return diag.NewMessage(
                UnknownMeshNetworksServiceRegistry,
                r,
-               serviceregistry,
-               network,
+                       serviceregistry,
+                       network,
        )
 }
 
@@ -417,7 +420,7 @@ func NewNoMatchingWorkloadsFound(r *resource.Instance, labels string) diag.Messa
        return diag.NewMessage(
                NoMatchingWorkloadsFound,
                r,
-               labels,
+                       labels,
        )
 }
 
@@ -426,10 +429,10 @@ func NewNoServerCertificateVerificationDestinationLevel(r *resource.Instance, de
        return diag.NewMessage(
                NoServerCertificateVerificationDestinationLevel,
                r,
-               destinationrule,
-               namespace,
-               mode,
-               host,
+                       destinationrule,
+                       namespace,
+                       mode,
+                       host,
        )
 }
 
@@ -438,11 +441,11 @@ func NewNoServerCertificateVerificationPortLevel(r *resource.Instance, destinati
        return diag.NewMessage(
                NoServerCertificateVerificationPortLevel,
                r,
-               destinationrule,
-               namespace,
-               mode,
-               host,
-               port,
+                       destinationrule,
+                       namespace,
+                       mode,
+                       host,
+                       port,
        )
 }
 
@@ -451,8 +454,8 @@ func NewVirtualServiceUnreachableRule(r *resource.Instance, ruleno string, reaso
        return diag.NewMessage(
                VirtualServiceUnreachableRule,
                r,
-               ruleno,
-               reason,
+                       ruleno,
+                       reason,
        )
 }
 
@@ -461,9 +464,9 @@ func NewVirtualServiceIneffectiveMatch(r *resource.Instance, ruleno string, matc
        return diag.NewMessage(
                VirtualServiceIneffectiveMatch,
                r,
-               ruleno,
-               matchno,
-               dupno,
+                       ruleno,
+                       matchno,
+                       dupno,
        )
 }
 
@@ -472,9 +475,9 @@ func NewVirtualServiceHostNotFoundInGateway(r *resource.Instance, host []string,
        return diag.NewMessage(
                VirtualServiceHostNotFoundInGateway,
                r,
-               host,
-               virtualservice,
-               gateway,
+                       host,
+                       virtualservice,
+                       gateway,
        )
 }
 
@@ -483,7 +486,7 @@ func NewSchemaWarning(r *resource.Instance, err error) diag.Message {
        return diag.NewMessage(
                SchemaWarning,
                r,
-               err,
+                       err,
        )
 }
 
@@ -500,7 +503,7 @@ func NewDeprecatedAnnotation(r *resource.Instance, annotation string) diag.Messa
        return diag.NewMessage(
                DeprecatedAnnotation,
                r,
-               annotation,
+                       annotation,
        )
 }
 
@@ -509,6 +512,7 @@ func NewAlphaAnnotation(r *resource.Instance, annotation string) diag.Message {
        return diag.NewMessage(
                AlphaAnnotation,
                r,
-               annotation,
+                       annotation,
        )
 }
+

➜  msg git:(master) export REPO_ROOT=/Users/kebeliu/workspace/istio  
➜  msg git:(master) ge generate
zsh: command not found: ge
➜  msg git:(master) go generate
go: downloading istio.io/api v0.0.0-20210115162953-da389fc06d2c
go: downloading github.com/envoyproxy/go-control-plane v0.9.9-0.20210115003313-31f9241a16e6
➜  msg git:(master) git --no-pager diff
➜  msg git:(master) 

```

**Comment by esnible** [comment]
@howardjohn @ericvn Can you suggest someone to review this?  I fear a fix that works for @kebe7jun 's setup will fail in continuous integration and for others.  Yet his tests pass.  What am I missing?

**Comment by howardjohn** [comment]
I am pretty sure if you run `make gen` it will run gofmt/goimports which makes this not matter?

**Comment by howardjohn** [comment]
Do not run it like this, do `go generate ./galley/pkg/config/analysis/msg/...`.

We can approve or not - it has no impact on correct usage via `go generate`

**Comment by ericvn** [comment]
My comments are if you are on a Mac, you should never run the go commands in your terminal. You would always run them in the build container's terminal (you can do a `make shell` to get to a terminal). Once you are in the terminal window, things should behave the same as they would in the CI system, so running the go command there would use the same go version we currently have in the pipeline, etc. Changes will be written to the local Mac file system, so once you edit the shell, you will see the changes.

Running `make xyz` is basically a `make shell` and then a `make xyz` within that terminal.

I hope that helps.

**Comment by kebe7jun** [comment]
Thanks you a lot, these really don't affect, I'll close this.

**Pull request closed without merging**
