### PR TITLE
cherry-pick: do not update root certs for destination rule certs (#27268)

### PR DESCRIPTION
**Pull request by yskopets**
Signed-off-by: Yaroslav Skopets <yaroslav@tetrate.io>

## Summary

* cherry-picking https://github.com/istio/istio/pull/27268 into `release-1.7`

### CODE REVIEW

**Comment by yskopets** [comment]
@googlebot I consent.

**Comment by yskopets** [comment]
@ramaraochavali Could you please consent to cherry-picking your PR https://github.com/istio/istio/pull/27268 into `release-1.7`  ?

**Review by howardjohn — APPROVED** [review]
cc @JimmyCYJ

**Review by Mythra — APPROVED** [review]

**Pull request merged**
