### PR TITLE
Apa Template bootstrap codegen.

### PR DESCRIPTION
**Pull request by guptasu**
**What this PR does / why we need it**:
It does the generation of instances that are dispatched to APA adapters
and also generates new attributes from the response of the adapter.

This PR finishes the APA support in Mixer.

Next:
- Change the Kubernetes adapter to use the new model.
- Finally cleanup the old model.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by guptasu** [comment]
@geeknoid @douglas-reid @mandarjog @ozevren friendly ping.

**Comment by elevran** [comment]
bazel vs go toolchain issue. This seems to happen for quite a few PRs that introduce new functionality that uses auto-generated files.

```sh
+ go test -coverprofile=/tmp/coverage/istio.io-istio-mixer-template-sample-quota.txt istio.io/istio/mixer/template/sample/quota
# istio.io/istio/mixer/template/sample
mixer/template/sample/template.gen_test.go:39:2: no Go files in /go/src/istio.io/istio/mixer/template/sample/apa
FAIL	istio.io/istio/mixer/template/sample [setup failed]
```

Generated files are not present in package directory which is then imported. Import of package with no Go files is an error.

**Comment by guptasu** [comment]
Is go test required ? Bazel test is the only required build system for now,
afaik. Go test only executes within circleci and circleci is not required.

**Comment by vadimeisenbergibm** [comment]
@guptasu Note that `go test` is used by https://circleci.com/gh/istio/istio, so it is required. circle-ci is one of the Continuous Integration checks of the  PRs.

**Pull request merged**
