### PR TITLE
Stop skipping lint/format in integration tests

### PR DESCRIPTION
**Pull request by howardjohn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Review by stevenctl — APPROVED** [review]

**Review by lei-tang — APPROVED** [review]

**Comment by ericvn** [comment]
Not sure if you want to pull the automated common-files update PR: https://github.com/istio/istio/pull/28492 into this PR or not.

**Comment by howardjohn** [comment]
Ill pull it in manually

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
