### PR TITLE
do not repeat trust id in logs

### PR DESCRIPTION
**Pull request by ramaraochavali**
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
Service entry can select k8s pods

**Comment by ramaraochavali** [comment]
> Service entry can select k8s pods

Yes. Added that condition.

**Comment by hzxuzhonghu** [comment]
For se + wle, the service account conversion is also base on spiffe

**Comment by ramaraochavali** [comment]
Looks like it needs more thought - I have just left this PR for log changes.

**Comment by ramaraochavali** [comment]
@hzxuzhonghu PTAL when you get chance?

**Comment by ramaraochavali** [comment]
@howardjohn can you PTAL when you get chance?

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by ramaraochavali** [comment]
@istio/wg-security-maintainers Can you PTAL?

**Comment by ramaraochavali** [comment]
@howardjohn can you PTAL when you get chance?

**Review by irisdingbj — APPROVED** [review]
LGTM

**Comment by ramaraochavali** [comment]
@istio/wg-security-maintainers can you PTAL?

**Pull request merged**
