### PR TITLE
[release-1.14] wasm: enhance fallback logic for the Wasm module download failure (#41416)

### PR DESCRIPTION
**Pull request by ingwonsong**
Fixes https://github.com/istio/istio/issues/41749

### CODE REVIEW

**Comment by ericvn** [comment]
Just a note that in the main branch PR there is a comment that the PR may be causing some post-submit tests to fail.

**Comment by ingwonsong** [comment]
@lei-tang FYI, actually, this is a kind of a major bug fix, which is fixing the edge case behavior regarding WASM plugin.

**Comment by lei-tang** [comment]
@ingwonsong Can you take a look at Eric's comment?

**Comment by ingwonsong** [comment]
@lei-tang by the two commits (https://github.com/istio/istio/pull/41795 and https://github.com/istio/istio/pull/41776) it had been solved.

**Comment by ingwonsong** [comment]
@lei-tang the issue @ericvn raised is related to the post submit error which was happen by two bugs. (wrong annotation + short timeout in new restarting logic). it has been fixed a few weeks ago, and now it does not happen again.

**Comment by ericvn** [comment]
@lei-tang Yes, I believe there was a change made in the main thread resolving the issue which is also now made in this PR.

**Review by lei-tang — APPROVED** [review]

**Pull request merged**
