### PR TITLE
Fix a typo in values.yaml template.

### PR DESCRIPTION
**Pull request by yusuoh**
Fix a typo: The yaml file generated by gen-deploy cannot be parsed by Helm.

### CODE REVIEW

**Comment by sdake** [comment]
/lgtm
this was a change in the Helm templates to make them more consumable and missed during the review of gendeploy.

**Comment by ZackButcher** [comment]
You'll need to update the golden file too: https://github.com/istio/istio/blob/aaf54b09fa40dea8e67fc59abf672d36d4991b09/pilot/cmd/istioctl/gendeployment/testdata/default-values.yaml.golden#L1

**Pull request merged**
