### PR TITLE
fix k8s overlay for addon components.

### LINKED ISSUE #23048: K8s resource overlays for addon components do not work
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

It should be possible to overlay the generated K8s resources for addon components with user-defined overlays.

```
cat << EOF >
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    prometheus:
      enabled: true
      k8s:
        overlays:
        - kind: Service
          name: prometheus
          patches:
          - path: spec.ports.[name:http-prometheus].port
            value: 9091 # OVERRIDDEN
EOF
```
```
# out/linux_amd64/istioctl manifest generate -f k8s-service-overlay.yaml | grep http-prometheus -C 3
  selector:
    app: prometheus
  ports:
  - name: http-prometheus
    protocol: TCP
    port: 9090
```

Should be `9091` for `http-prometheus` port.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

### PR DESCRIPTION
**Pull request by morvencao**
Please provide a description for what this PR is for.
resolve: https://github.com/istio/istio/issues/23048

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by elfinhe — COMMENTED** [review]
LGTM, maybe we need input from other reviewers.

**Comment by morvencao** [comment]
@ostromart @dgn PTAL

**Review by dgn — COMMENTED** [review]
lgtm, should we add a test?

**Comment by morvencao** [comment]
@dgn add test cases, PTAL

**Review by richardwxn — APPROVED** [review]

**Pull request merged**
