### PR TITLE
simplify validatingwebhookconfiguration mgmt (cherry-pick of #21164)

### PR DESCRIPTION
**Pull request by ayj**
The validatingwebhookconfiguration has historically had many problems
during install and uninstall. More and more logic has been added to
the control plane to migate the problem without complete success. This
PR takes the opposite approach. Here's how it works:

1- The validatingwebhookconfiguration YAML is added to the manifests
applied directly by istioctl and the operator. istiod no longer
creates the validatingwebhookconfiguration from a template in a
configmap.

2- The initial failure policy has been changed to FAIL-OPEN. Any Istio
configuration applied during install should not be blocked by
istiod not being ready.

3- istiod will update the caBundle and change the failure policy to
FAIL-CLOSED when it is validation endpoint is ready.

4- un-installed and re-installing istio will reset the failure policy
back to FAIL-OPEN. The only requirement here is that the
validatingwebhookconfiguration be applied earlier in the install
sequence before Istio CRs.

5- Reverting back to FAIL-OPEN during an upgrade creates a small
window where invalid configuration could be created. This may be
undesirable for some production users. They can use a k8s overlay
to modify the default failure policy in the

cherry-pick of #21164 from master

### CODE REVIEW

**Comment by ayj** [comment]
This includes the port fix from https://github.com/istio/istio/pull/21242. cc @howardjohn

**Comment by ayj** [comment]
This is ready for review - @istio/release-managers-1-5

**Comment by dgn** [comment]
@ayj this has broken the postsubmit webhook tests: https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/130

note that we're running the postsubmits using the helm charts. could you look into this?

**Comment by ayj** [comment]
Looking into this issues now.

**Comment by ayj** [comment]
Already fixed in master (see https://github.com/istio/istio/pull/21349). The automatic cherry-pick failed. https://github.com/istio/istio/pull/21425  is the manual cherry-pick of this fix into the release 1.5 branch.

**Pull request merged**
