### PR TITLE
[release-1.4] fix(injection template): correct owner string format

### PR DESCRIPTION
**Pull request by douglas-reid**
manual cherry-pick of #18485 .

the release bot couldn't cherry-pick due to minor conflicts in a few files. This PR is the result of:

`$ git cherry-pick 93567f77d855d215f66cce087c42f1cede93cb28`

with a few manual "accept current change" fixes.

### CODE REVIEW

**Comment by douglas-reid** [comment]
@jwendell done.

**Comment by jwendell** [comment]
@howardjohn edit the message on github ui is not enough. Take a look at `git log` locally.

**Comment by douglas-reid** [comment]
@jwendell i really wish that we could fix any diffs between the github commit msg and what ends up in the git log. This seems like something our commit logic in github could handle.

**Pull request merged**
