### PR TITLE
Add short-circuiting support to LAND.

### PR DESCRIPTION
**Pull request by ozevren**
This adds short-circuiting support to the emitted AND IL code.

### CODE REVIEW

**Comment by ldemailly** [comment]
NIce! can we test that this makes https://github.com/istio/istio/blob/master/tools/cache_buster.yaml#L21-L24 work as expected ? I guess I'll try after this merges but would be nice to confirm

**Comment by mandarjog** [comment]
Thanks, this was missing before.
Can you add a testcase that confirms the behaviour ?

**Comment by ozevren** [comment]
Sure. Where are the attribute tracking tests? It is probably the best place to put.

**Comment by mandarjog** [comment]
`mixer/pkg/attribute/bag_test #TestReferenceTracking`
You should be able to write tests locally though, by using a trivially tracked attribute bag.
You can use protoBag if you must, but I think a mock bag that tracks attributes would be better.

**Comment by ozevren** [comment]
Ah, apparently we don't have comprehensive tests covering this, just unit
tests.

I'll try to add some infrastructure to IL testing to cover this
holistically. It will probably take a while though. I'll try to push it in
a separate PR.

**Comment by mandarjog** [comment]
@ozevren it should be easy add attribute tracking to your fakebag and then use IL to actually add a testcase here.

**Pull request merged**
