### PR TITLE
Remove legacy "ingress" component from Istio installer

### PR DESCRIPTION
**Pull request by philrud**
This PR removes legacy "ingress" component from Istio installer. It focuses on the "ingress" component only, not the complete removal of Kubernetes Ingress resource support.

Specifically:
* This PR removes "Ingress" component only and corresponding flags (i.e. "ingress.enabled"), branches, etc.
* It does NOT remove "global.k8sIngress.*" flags.
* "global.k8sIngress.gatewayName" now defaults to "ingressgateway" (i.e. the default gateway, not "ingress").
* This PR does not remove "Ingress" resource templates of optional components – they create generic "Ingress" resources and do not depend on/require "Ingress" component.

As demonstrated in the Istio.io "Example" (https://github.com/istio/istio.io/pull/3498) K8s Ingress resource support is natively handled by a "standard" gateway (e.g. istio-ingressgateway installed by default) and can be optionally enabled/configured via the "global.k8sIngress.*" flags. 'Ingress' component is not a requirement for K8s Ingress support and only adds up to the confusion.

Complete removal of Kubernetes Ingress resource support is intentionally left out of the scope of this PR. If necessary this can be done separately when the consensus is reached.

### CODE REVIEW

**Comment by duderino** [comment]
@philrud thank you

**Comment by philrud** [comment]
cannot assign @linsun in some reason
@linsun could please also take a look when you have chance? thanks!

**Comment by duderino** [comment]
e2e-pilot-cloudfoundry-v1alpha3-v2 failure not related:

```
Started local etcd and apiserver!
sudo apt update
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
make: *** [test/local/cloudfoundry/e2e_pilotv2] Error 100
Exited with code 2
```

The e2e-pilot-noauth-v1alpha3-v2 failure I've seen on several other PRs:

```
TestIngressGateway503DuringRuleChange - pilot
Failed
gateway "istio-ingressgateway" created
destinationrule "destination-rule-c" created
virtualservice "gateway-bound-route" created
destinationrule "destination-rule-c" configured
virtualservice "gateway-bound-route" configured
destinationrule "destination-rule-c" configured
virtualservice "gateway-bound-route" deleted
destinationrule "destination-rule-c" deleted
gateway "istio-ingressgateway" deleted
ingressgateway_test.go:258: Got non 200 status code while changing rules: map[200:499 503:1]
```

**Comment by sdake** [comment]
@duderino this ```
Started local etcd and apiserver!
sudo apt update
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
make: *** [test/local/cloudfoundry/e2e_pilotv2] Error 100
Exited with code 2
``` is caused by https://github.com/istio/istio/issues/11374.

Cheers
-steve

**Comment by philrud** [comment]
thanks Steve, appreciate your help

**Pull request merged**
