### PR TITLE
loose telemetry accesslogging validation 

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

after https://github.com/istio/istio/pull/39521  we should loose telemetry accesslogging validation

### CODE REVIEW

**Comment by zirain** [comment]
> /cherrypick release-1.14

this's a new feature, and should not backport to v1.14

**Comment by GregHanson** [comment]
@zirain you are right, sorry.  I thought I remembered it going in but verified that is not the case

**Review by hzxuzhonghu — APPROVED** [review]
Does it need to be in 1.15

**Comment by zirain** [comment]
> Does it need to be in 1.15

yes, v1.15 is still alpha.

**Pull request merged**
