### PR TITLE
OutboundTrafficPolicy configurable per workload

### PR DESCRIPTION
**Pull request by howardjohn**
Copy of https://github.com/istio/istio/pull/12910 but at annotation level instead of a full API change

### CODE REVIEW

**Comment by howardjohn** [comment]
>What is the point of defining an API for group of sidecars but then forcing people to do this per workload instead? 

This doesn't require making an API change late in the 1.1 release that we will need to support, has not gone through API review, etc. As Costin mentioned, the change at the API level would be fine in the master branch.

> And in a world where pods come and go, what is the end user experience when she wants to configure this exception rule for pods in a particular namespace? Editing the Istio YAML blobs to create custom sidecar injectors for specific namespaces is definitely not a good user experience.

You just need add the annotation to the Deployment. I am not sure what you mean about custom injectors or pods coming and going.

**Comment by rshriram** [comment]
So what happens to non K8S environments?

**Comment by rshriram** [comment]
adding arbitrary annotations (esp ones that allow traffic to go unchecked) poses a security issue as well. Atleast the sidecar CRDs can be gated using RBAC rules.. annotations on deployments owned by service teams cannot be gated

**Comment by howardjohn** [comment]
> adding arbitrary annotations (esp ones that allow traffic to go unchecked) poses a security issue as well. Atleast the sidecar CRDs can be gated using RBAC rules.. annotations on deployments owned by service teams cannot be gated

You can already just add `sidecar.istio.io/interceptionMode: NONE` and disable iptables entirely. I agree its a security issue though, that is a great point, but it also isn't a new one.

We already have many (20+) annotations, what happens in non k8s environments for all of those?

From what I can tell, you are against any/most changes with annotations, and @costinm is generally in favor of annotations for turning features on/off per workload. Can we come to a general consensus of when we should and shouldn't use annotations?

**Comment by hzxuzhonghu** [comment]
Personally, I am in favor of reducing the use of annotation if we can do it in API level.

**Comment by rshriram** [comment]
I am not in favor of adding arbitrary annotation based switches in the proxy to control the configuration generation. This has several drawbacks.. The most important of which is that its not applicable for VM based environments where the proxy and bootstrap config are baked into the base VM image. Unlike k8s, there is no concept of a deployment or the ability to dynamically edit a "pod spec" to add these annotations. We have realized this the hard way, when deploying Istio purely on VMs for some of our customers. I do agree that we already have a huge list of annotations and I am working to get rid of them one by one. But the Sidecar is an integral piece in the mesh. I dont want to fragment this feature by adding k8s-only hacks in the metadata creating a partial solution and backward compatibility issues when we introduce an API driven way of controlling the outbound traffic policy per Sidecar. We might as well push this to 1.2 and do it the proper way.

**Comment by howardjohn** [comment]
Don't think this is happening for 1.1.

Lets get a real API change for Sidecar in for 1.2 instead

**Pull request closed without merging**
