### PR TITLE
Bump to Kubernetes 1.19 client libraries

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/istio/issues/25119

### CODE REVIEW

**Comment by shamsher31** [comment]
Not sure why but I got this https://github.com/istio/istio/pull/25241#issuecomment-681575398 error while upgrading to 1.19 for using ProxyGet from k8.

**Comment by howardjohn** [comment]
> Not sure why but I got this #25241 (comment) error while upgrading to 1.19 for using ProxyGet from k8.

Ah didn't see that. I updated the logr library in this PR, maybe that is why

**Review by hzxuzhonghu — APPROVED** [review]
/retest

**Pull request merged**
