### PR TITLE
Create an istio-operator generated manifest for development

### PR DESCRIPTION
**Pull request by sdake**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
What will this be used for?

**Comment by sdake** [comment]
@howardjohn in 1.7, I deleted the [built manifests](https://github.com/istio/istio/pull/22982#issue-404078067) to replace them with generated manifests from the existing operator, effectively reducing duplication and double maintenance. The Issue filed on this brought this to memory that I should actually finish the job and build the manifests here in this PR.

**Comment by sdake** [comment]
https://github.com/istio/istio/issues/27139

**Comment by sdake** [comment]
@howardjohn added a release note, which should provide more context for users.

Cheers,
-steve

**Review by richardwxn — APPROVED** [review]

**Pull request merged**
