### PR TITLE
Add missing descriptions to fields in values_types.proto

### PR DESCRIPTION
**Pull request by luksa**
**Please provide a description of this PR:**
Many fields in values_types.proto were missing descriptions, but they were documented elsewhere (e.g. in values.yaml). This PR adds descriptions to most of the fields. Adding these descriptions is a first step towards making the values a part of the official Istio API.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I am happy to see more documentation of course, but what does it mean "path towards making these an official API"? What does that entail? Is there a plan laid out somewhere?

**Review by howardjohn — APPROVED** [review]

**Comment by luksa** [comment]
> I am happy to see more documentation of course, but what does it mean "path towards making these an official API"? What does that entail? Is there a plan laid out somewhere?

We'd like to see the Helm values become a proper API, with proper documentation and a guarantee to stay backwards compatible. I believe @costinm also suggested the community should start moving towards this goal. My point was merely that adding the descriptions is a good first step, as it will allow us to generate the reference docs for the Helm values from the values_types.proto file.

**Comment by costinm** [comment]
Agree, having docs on all fields - with some triage identifying at least things that should not be used or are clearly experimental - would be a great start.

Ambient charts are at least more consistent with helm naming and practice - I wish we could do something about istiod, like a clean chart with ambient and nothing else ( injection is a lot of complexity in the chart), and no  option for istiod that is not really install only and we are committed to it as API.

**Pull request merged**
