### PR TITLE
remove istio cni subchart tar from source.

### PR DESCRIPTION
**Pull request by morvencao**
Since we get `istio-cni` with `helm dep update` from istio chart repo, we don't need `istio-cni` subchart tar package in source tree.

### CODE REVIEW

**Comment by sdake** [comment]
@morvencao can you please add an issue for 1.1 so this can be tracked properly for 1.1?

**Comment by morvencao** [comment]
@sdake Logged an issue: https://github.com/istio/istio/issues/11549

**Comment by linsun** [comment]
/lgtm
/approve

nice - it was just discussed we should do this in the env WG mtg yesterday

**Comment by linsun** [comment]
@wenchenglu can we get this approved for 1.1?

cc @costinm

**Pull request merged**
