### PR TITLE
minor test fixes

### PR DESCRIPTION
**Pull request by ramaraochavali**
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
These don't look like test fixes. It looks like the removal of tests.

**Comment by ramaraochavali** [comment]
No. It is just setting the VerifyAtClientCert feature back to its old value after test - otherwise we will run in test flakiness if we do not consider old value and the default is changed in future.

**Review by ericvn — APPROVED** [review]

**Comment by ramaraochavali** [comment]
@hzxuzhonghu can you PTAL?

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
