### PR TITLE
switch download to 0.1.4

### PR DESCRIPTION
**Pull request by ldemailly**

### CODE REVIEW

**Comment by ldemailly** [comment]
build istio/presubmit

**Comment by sebastienvas** [comment]
Can you increase istio.RELEASE to point to next release as well ?

**Comment by sebastienvas** [comment]
Nevermind I ll do it directly on the repo

**Comment by ldemailly** [comment]
I wanted to just change the download that in case my archives aren't actually correct and more is needed tag or otherwise with 0.1.4 but I can ammend

**Comment by sebastienvas** [comment]
Don t worry about it. I ll do it after.

**Pull request merged**
