### PR TITLE
WIP: probe through envoy

### PR DESCRIPTION
**Pull request by howardjohn**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
@ramaraochavali curious what you think of this? this is for https://github.com/istio/istio/issues/21345.

**Comment by ramaraochavali** [comment]
@howardjohn  the new workers started stat check that I added recently does ensure workers are up . Did you see that envoy is ready (with that stat) and still it is not processing requests - that is why you want to change? I

**Comment by howardjohn** [comment]
Specifically the issue was seen on 1.4 which doesn't have that, but
something went wrong causing the worker thread to get stuck at max CPU and
accepting no connections or anything. So o think even on master it would
still pass the readiness probe

**Comment by ramaraochavali** [comment]
I see. Interesting. Let me think about it.

**Comment by ramaraochavali** [comment]
I guess we should probably look at configuring watchdog in bootstrap https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/bootstrap/v2/bootstrap.proto.html?highlight=watchdog#config-bootstrap-v2-watchdog rather than proxying readiness probes  via worker threads. Watchdogs https://www.envoyproxy.io/docs/envoy/latest/operations/performance#watchdog generally provide better behaviour looking at multiple worker threads.

**Comment by Stono** [comment]
I actually think a belt and braces approach is better, both watchdog and a readinessProbe that truly indicates readiness feels like the right thing to do.

**Comment by howardjohn** [comment]
I agree, both seem useful. it's like a readiness vs liveness probe in some ways

if there's no objections I'll send a pr out to master to turn these both on by default

**Comment by ramaraochavali** [comment]
I do not have a strong objection to proxying readiness probes via Envoy, however I do think
- It may be redundant because watchdog would have already detected and killed Envoy by that time readiness probe fails (with 5 or whatever attempts that it takes to fail)
- The readiness probe only looks at one worker thread (through which it is going) while watchdog looks at all.

Having said that, I do see the point of readiness probe being an additional safety measure that could detect cases which watch dog could not (which I doubt would be the case, but possible) also I can not think of any side affects of routing it via Envoy - So no harm in trying I guess.

**Comment by howardjohn** [comment]
Yeah I pretty much agree with you. I'll close this an open another or against master later. thanks!

**Pull request closed without merging**
