### PR TITLE
Bump Kubernetes client libraries (patch version update only)

### PR DESCRIPTION
**Pull request by elfinhe**
Bump Kubernetes client libraries only. Quite similar to https://github.com/istio/istio/pull/24399, but without changes in pilot/pkg/leaderelection/leaderelection.go.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by brian-avery** [comment]
@howardjohn What are your thoughts on this? It's a Kubernetes patch release, so it shouldn't have any breaking changes, that said, I'm not sure what to look for here.

**Comment by howardjohn** [comment]
I am fine with it if we have a good reason, but this PR does not provide one

**Comment by brian-avery** [comment]
@elfinhe Can you please update the PR description with reasoning for why this is needed?

**Comment by elfinhe** [comment]
> @elfinhe Can you please update the PR description with reasoning for why this is needed?

This will include fixes and improvements  in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1182.

**Comment by elfinhe** [comment]
We haven't yet seen impact from those bugs to Istio directly. But staying with the first version of v0.18 (v0.18.0) may not be a good idea.

**Comment by howardjohn** [comment]
I disagree. Its much higher risk to update now, we have no known bugs and
we have done extensive testing of 1.6 already; patch releases get minimal
testing in comparison.

**Pull request closed without merging**
