### PR TITLE
Adding Informers and Listers to vendor

### PR DESCRIPTION
**Pull request by sbezverk**
Add missing libraries from k8s client-go

### CODE REVIEW

**Comment by nmittler** [comment]
FYI added a hold on this until you have your other PR approved ... once that's the case, I'll release the hold on this.

**Comment by nmittler** [comment]
@sbezverk let's go ahead and add your full change to this PR so we can review the vendor change in context.

**Comment by costinm** [comment]
Or the other way around: add vendor to your main PR.

**Pull request closed without merging**
