### PR TITLE
telemetry: fix datadog hostname

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

envoy: https://github.com/envoyproxy/envoy/pull/23910

fixes: #41829

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by GregHanson** [comment]
@zirain does this one need to be cherry-picked to the release-1.16 branch

**Comment by zirain** [comment]
> @zirain does this one need to be cherry-picked to the release-1.16 branch

this required envoy backport and update go-control-plane version

**Comment by melchiormoulin** [comment]
Hey, how do i know which release contains this fix please ?

**Comment by zirain** [comment]
> Hey, how do i know which release contains this fix please ?

should be v1.17

**Pull request merged**
