### PR TITLE
Kubeinject revision check

### LINKED ISSUE #38083: Kube-inject panic when using revisions
### Bug Description

I Get a panic when I try to manual sidecar injection and revisions

My kubernetes is simple as I only do the following command

Installed istio 1-13-2 with revision
`istioctl install --set profile=demo -y --revision 1-13-2`

Installed the bookinfo sample application
`kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`

Finally try to do the manual injection using meshConfigMapName and injectConfigMapName
```
istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --meshConfigMapName istio-1-13-2 --injectConfigMapName istio-sidecar-injector-1-13-2  | kubectl apply -f -

2022-03-23T00:58:42.302388Z	warn	failed to get injection config from mutatingWebhookConfigurations "istio-sidecar-injector", will fall back to get injection from the injection configmap "istio-sidecar-injector" : could not find valid mutatingWebhookConfiguration "sidecar-injector.istio.io" from cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x178 pc=0x102b709b0]

goroutine 1 [running]:
istio.io/istio/pkg/kube/inject.RunTemplate({0x1400077f000, {{0x14000feb540, 0xa}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
	istio.io/istio/pkg/kube/inject/inject.go:412 +0x6f0
istio.io/istio/pkg/kube/inject.injectPod({0x1400077f000, {{0x14000feb540, 0xa}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
	istio.io/istio/pkg/kube/inject/webhook.go:330 +0xa4
istio.io/istio/pkg/kube/inject.IntoObject({0x103eea1c0, 0x14000fe8c00}, 0x1400080e660, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x103f28818, 0x140004cd680}, ...)
	istio.io/istio/pkg/kube/inject/inject.go:786 +0xcec
istio.io/istio/pkg/kube/inject.IntoResourceFile({0x103eea1c0, 0x14000fe8c00}, 0x1400080e660, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x103eeb640, 0x14000113778}, ...)
	istio.io/istio/pkg/kube/inject/inject.go:574 +0x2c0
istio.io/istio/istioctl/cmd.injectCommand.func1(0x14000f6c780, {0x14000b67d40, 0x0, 0x6})
	istio.io/istio/istioctl/cmd/kubeinject.go:594 +0x384
github.com/spf13/cobra.(*Command).execute(0x14000f6c780, {0x14000b67ce0, 0x6, 0x6})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x14000f6c500)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0x114
service/details unchanged
serviceaccount/bookinfo-details unchanged```

This definitely worked on previous versions of istio, 1-8-3 was the last time I tested this.
If I am doing it wrong any help would be appreciated but regardless it shouldn't be giving a null pointer exception.

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (2 proxies)
$ kubectl version --short
Client Version: v1.23.4
Server Version: v1.22.5
```

### Additional Information

After doing a bit of poking around in the kube-inject source code I possibly see the problem and perhaps a solution.

At line 397 it returns nil for meshConfig which is the cause of the nil pointer later
https://github.com/istio/istio/blob/2bcfd34cb20812b988597299191d11cc041e54f6/istioctl/cmd/kubeinject.go#L389-L401

At line 766 proxyConfig gets set to nil and then gets tripped here
https://github.com/istio/istio/blob/2bcfd34cb20812b988597299191d11cc041e54f6/pkg/kube/inject/inject.go#L748-L773
https://github.com/istio/istio/blob/2bcfd34cb20812b988597299191d11cc041e54f6/pkg/kube/inject/inject.go#L409

<h3>Possible Solution</h3>

Interestingly if I comment line 397 out and force it to proceed to get the meshConfig it appears to work fine
https://github.com/istio/istio/blob/2bcfd34cb20812b988597299191d11cc041e54f6/istioctl/cmd/kubeinject.go#L397-L401

Possible alternate fixes could involve patchBytes not returning false during inject. But it's client config seems to always be nil causing the inject to also return nil.
https://github.com/istio/istio/blob/2bcfd34cb20812b988597299191d11cc041e54f6/pkg/kube/inject/inject.go#L731-L748
https://github.com/istio/istio/blob/2bcfd34cb20812b988597299191d11cc041e54f6/istioctl/cmd/kubeinject.go#L74-L78

### PR DESCRIPTION
**Pull request by dhawton**
**Please provide a description of this PR:**
Fixes #38083 

When providing an injection configmap specifically without a revision flag passed, non-default revisions cause a nil pointer exception panic. This patch applies a check for the configmap revision label to provide a cleaner error message.

### CODE REVIEW

**Comment by zirain** [comment]
@dhawton you need run `make lint` in local.

**Comment by linsun** [comment]
@dhawton the change LGTM! try to get lint passing as @zirain suggested.

**Comment by dhawton** [comment]
Ran make lint locally and adjusted.

**Review by linsun — APPROVED** [review]
LGTM

can someone from @istio/wg-user-experience-maintainers PTAL?

**Comment by linsun** [comment]
cc @GregHanson to review on behalf of release-mgrs

**Review by GregHanson — APPROVED** [review]

**Review by therealmitchconnors — APPROVED** [review]
Welcome to the team, Daniel!

**Pull request merged**
