### PR TITLE
Fix locality aware routing to be applied when proxy has empty locality config set

### PR DESCRIPTION
**Pull request by aattuluri**
Make sure empty proxy locality will fall back to using proxy service's instance locality.

### CODE REVIEW

**Comment by aattuluri** [comment]
@ymesika I finally fixed the CLA issue. Please approve this one and I can close the other one.

**Comment by aattuluri** [comment]
Fixes issue https://github.com/istio/istio/issues/11609

**Comment by ymesika** [comment]
/lgtm

cc @wengchung

**Pull request merged**
