### PR TITLE
Cleanup legacy ENABLE_LEGACY_LB_ALGORITHM_DEFAULT flag

### PR DESCRIPTION
**Pull request by howardjohn**
This has been around for 1 year and was added for backwards compat opt-out; time to remove

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Comment by Minh-Ng** [comment]
Should this have been removed without an alternative for setting mesh policy? LEAST_REQUEST in rare scenarios can result in poorer performance than ROUND_ROBIN, especially in scenarios where a service hosts endpoints with varying endpoint latency compared to round robin. While the LB algorithm can be specified in DestinationRule, the need to apply the LoadBalancing algorithm to every single DestinationRule creates a new problem in and of itself that adds unnecessary complexity compared to an option from the administrators of Istiod. 

Those who opted-out using the env variable may like to keep it in perpetuity and it would probably be better to move it from an env var to a separate configuration rather than removing the possibility altogether.

**Comment by ramaraochavali** [comment]
As mentioned the env is only intended during transition period. Also as you mentioned the change is needed only in rare cases - why can't you use Round Robin for such cases with a single/few DR changes?

**Comment by Minh-Ng** [comment]
> As mentioned the env is only intended during transition period. Also as you mentioned the change is needed only in rare cases - why can't you use Round Robin for such cases with a single/few DR changes?
The problem lies with discovery and configurability.

We could look at service metrics and identify ones with varying latency for that specific issue but there may be other patterns which work with round robin and not with least connections. 

As the cluster maintainers of Istio and service owners usually have separate domains of understanding where workload owners are responsible for custom DestinationRules they deploy. Verification of workloads falls upon a service owner when developed + deployed. When the default (cluster admin responsibility) is changed that responsibility is shifted to the team performing the upgrade and maintaining the deployed Istio version. In large clusters, while we can scan all DR it is infeasible to always be up to date on the traffic specifics of each service, similar to as how as a maintainer of Istio it is impossible to know how the traffic patterns of all applications running Istio in the wild. Or if a service owner is unaware of the change notes and deploys a new DestinationRule that overwrites the default system DestinationRule without knowing the update has changed the default LB policy and the update is gradually rolling out to the cluster. As a result many issues are only found upon change/upgrade and in environments with specific traffic patterns (i.e. if production has traffic that is not simulated in a pre-production environment).

On the note of the transition period, I can understand it the env var being transitory, but as for load balancing configuration it seems that anyone who opted to use the legacy flag would have kept it until it was no longer supported. This just pushed the investigation into dealing with incompatible workloads until the upgrade where the configurability was removed. A configuration of the default behavior seems like a reasonable tradeoff to changing the default behavior without being able to guarantee its compatibility with all existing workloads. We would be in the same scenario if LEAST_CONN was the old default and we changed to ROUND_ROBIN. Or if we removed the ability to enable localityLoadBalancing from meshConfig and required a DestinationRule to enable it without DestinationRule inheritance/merging.

Of course, using a DR to configure is the solution here but the problem is caused in totality by changing the default + having no way to configure the default. The result is that a cluster upgrade is now tied with workload semantics that were previously verified during workload development and ultimately complicates upgrades in larger deployments.

**Comment by ramaraochavali** [comment]
> but the problem is caused in totality by changing the default + having no way to configure the default.

> but the problem is caused in totality by changing the default + having no way to configure the default. 

It was never intended to make the default configurable at Mesh wide. I do not think ROUND ROBIN was the right default. As you mentioned any default across mesh has issues with this specific config and depend on workloads.That is why we introduced that env var and kept it for 4 releases so that there are no surprises. When you started using the env flag, you should have planned for DR changes if the default is not appropriate for you and not wait till the upgrade that removed it.

**Comment by Minh-Ng** [comment]
I think that it’s reasonable that the default was changed if it was determined round robin was an insufficient default. However least conns has issues as a default as we have observed in our clusters as well. Like I mentioned before I think the change of default is more of an issue than the actual default itself.

Sure it’s accurate and fair to day there were 4 releases to work on the issue but the best solution for those 4 releases was changing the default to the legacy behavior. However, the problem is the same 4 releases ago or now. There is no good alternative to reverting the default lb algorithm rather than hunting down every single workload that is incompatible in its current state with the new default.

I would be inclined to say that providing the ability to alter the default is a sound decision because it is low effort compared to pushing users to find workarounds and the reason we have lb options is so that users may control the algorithm that suits them best. If a cluster is more suited to a specific algorithm it seems only reasonable that the cluster admin should be able to make that decision knowing their own circumstances.

**Pull request merged**
