### PR TITLE
make bookinfo sample build repeatable

### LINKED ISSUE #7097: bookinfo build is not repeatable
I've been hacking on some very minor changes to the bookinfo sample app in an attempt to resolve #7047.

In doing so, I've discovered that the bookinfo build is not deterministic / repeatable for at least two reasons-- there may be others, but these are the two I was able to identify and quickly correct.

1. The first is that the productinfo flask app doesn't specify versions of its dependencies in its `requirements.txt`. This means that a build automatically gets the latest version of each package listed in that file. There _are_ breaking changes in the latest version of at least one of those packages that break compatibility with the productinfo app.

2. The second is that the `niaquinto/gradle` Docker image used to facilitate the build of the reviews service service no longer exists.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #7097 

I determined the exact correct set of versions required for each productinfo dependency by doing this:

```
docker run -it istio/examples-bookinfo-productpage-v1:1.5.0 pip freeze
```

For the gradle build of the reviews service, it wasn't possible to determine what version of Java and gradle were previously used because the `niaquinto/gradle` no longer exists. I opted to use the latest _official_ gradle image instead. This seems to work fine.

### CODE REVIEW

**Comment by krancour** [comment]
CI failure doesn't look related to these changes.

**Comment by rshriram** [comment]
You have to update all bookinfo images

**Comment by krancour** [comment]
> You have to update all bookinfo images

Not sure how to go about that. I can update all references to those images, but I don't know how I could push them-- I obviously do not have permissions.

**Comment by krancour** [comment]
I updated all files to reference bookinfo 1.6.0 images, but they don't exist. Someone else needs to push them from the source in this branch.

**Comment by vadimeisenbergibm** [comment]
@krancour I see the updated docker images https://hub.docker.com/r/istio/examples-bookinfo-productpage-v1/tags/. Please merge the bookinfo changes from the `release-0.1` branch.

screen shot 2018-07-15 at 8 46 29 am

**Comment by krancour** [comment]
How did those get there?

**Comment by vadimeisenbergibm** [comment]
> How did those get there?

By this script - https://github.com/istio/istio/blob/master/samples/bookinfo/build_push_update_images.sh .

**Comment by vadimeisenbergibm** [comment]
One must have permissions to upload images to https://hub.docker.com/r/istio.

**Comment by krancour** [comment]
Right. I understand how they were made. I was more curious about who pushed them. It doesn't seem that building/pushing these is integrated into the CI process.

**Comment by vadimeisenbergibm** [comment]
I pushed the 1.7.0 images by running that script.

**Comment by krancour** [comment]
> I pushed the 1.7.0 images by running that script.

What branch did you build and push them from? I ask because this PR would have created 1.6.0 images; not 1.7.0.

So you can probably see why I am confused...

**Comment by krancour** [comment]
I've also just pulled the 1.7.0 productpage image that you recently pushed and found that it definitely does _not_ include anything that was in this branch.

**Comment by vadimeisenbergibm** [comment]
> I've also just pulled the 1.7.0 productpage image that you recently pushed and found that it definitely does not include anything that was in this branch

By _this branch_, do you mean `krancour:repeatable-bookinfo-build` or `release-1.0`? I built the images from `release-1.0`.

**Comment by krancour** [comment]
> By this branch, do you mean krancour:repeatable-bookinfo-build or release-1.0? I built the images from release-1.0.

I mean `krancour:repeatable-bookinfo-build`.

Again-- I'm confused. I don't understand what the `release-1.0` branch has to do with _this_ PR.

Just trying to understand the process here.

**Comment by krancour** [comment]
Also-- slight tangent-- you were probably only able to build these images in the first place because of things that already exist in your Docker (and maybe pip) cache. Absent the changes from this PR, producing new images for productpage and reviews shouldn't even be possible without a primed cache. _i.e. This process seems as if it is currently dependent on your machine_.

**Comment by vadimeisenbergibm** [comment]
Hmm, let me merge the PR #6988 to master first, and then you merge it from the master. The issue is that while you are working on bookinfo, I already changed it in istio/istio, in the release-1.0 branch.

**Comment by krancour** [comment]
> Hmm, let me merge the PR #6988 to master first, and then you merge it from the master. The issue is that while you are working on bookinfo, I already changed it in istio/istio, in the release-1.0 branch.

Ok... that may simplify the equation here to something I can understand. :) . Appreciate it.

**Comment by vadimeisenbergibm** [comment]
@krancour Please wait until https://github.com/istio/istio/pull/7151 is merged and then merge the master from istio into your branch.

**Comment by krancour** [comment]
@vadimeisenbergibm sgtm. Thanks.

**Comment by rshriram** [comment]
rebase to release-1.0 branch

**Comment by krancour** [comment]
@rshriram, I am assuming then that `release-1.0` is also the desired merge target for this?

If so, I'll have to close this and open a new PR. Happy to do it.

**Comment by krancour** [comment]
Superseded by #7152

**Pull request closed without merging**
