### PR TITLE
Don't hardcode versions in upgrade test

### PR DESCRIPTION
**Pull request by jwendell**
Instead, rely on the contents of the VERSIOn file

### CODE REVIEW

**Comment by jwendell** [comment]
upgrade test will fail right now because 1.18.0 does not exist yet.

also, the tag `1.17.0` is not present on gcr.io/istio-release. Not sure how to fix this.

cc @jacob-delgado

**Review by howardjohn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
> also, the tag `1.17.0` is not present on gcr.io/istio-release. Not sure how to fix this.

I hate to say it, but can we check for `1.17.0` in either of the strings and simply change to `1.17.1`?

**Comment by ericvn** [comment]
> upgrade test will fail right now because 1.18.0 does not exist yet.

This would always be the case from the time we branch cut until we publish the release. So maybe 3-4 weeks every 3 months or approximately 1/4-1/3 of the time. At least it's early in a given release's dev cycle. I'm not sure it it makes sense to test to see if the image exists, and then a) drop both version strings one version or b) not do the test. I think I like option a as  it means we are at least still running tests.

**Comment by jwendell** [comment]
@ericvn I have addressed both issues

@howardjohn I added the DNM label to allow a second review if necessary.

**Review by ericvn — APPROVED** [review]
LGTM. Thanks.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
