### PR TITLE
[release-1.11] grpcgen: inbound configuration (#34423)

### LINKED ISSUE #34576: [release-1.11] grpcgen: inbound configuration
Manual cherrypick required.

#34423 failed to apply on top of branch "release-1.11":
```
Applying: grpcgen: port-level lds filter
Applying: grpcgen: inbound listener
Applying: mtls support with test
Using index info to reconstruct a base tree...
M	pilot/pkg/networking/grpcgen/grpcgen_test.go
M	pkg/istio-agent/grpcxds/grpc_bootstrap.go
Falling back to patching base and 3-way merge...
Auto-merging pkg/istio-agent/grpcxds/grpc_bootstrap.go
Auto-merging pilot/pkg/networking/grpcgen/grpcgen_test.go
CONFLICT (content): Merge conflict in pilot/pkg/networking/grpcgen/grpcgen_test.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0003 mtls support with test
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by stevenctl**
Manual cherry-pick of #34423 (fixes #34576)

### CODE REVIEW

**Comment by stevenctl** [comment]
I'll add release notes later. I'm hoping to publish a blogpost/guide alongside this feature.

**Comment by jwendell** [comment]
Is this really supposed to go in 1.11?
1.11.0 is about to be released.

**Comment by stevenctl** [comment]
It would be _really nice_ to have this in 1.11.0; it doesn't really affect any code for production users, it's an isolated generator separate from what Envoy uses. If I can slip this in due to other release blockers, it would be nice. If this slips to 1.11.1 that is okay too. 

cc @howardjohn @costinm if either of you think this has risk for the release.

**Comment by howardjohn** [comment]
IIRC this has no impact on existing code so I am not overly concerned with
it

**Review by jwendell — APPROVED** [review]

**Pull request merged**
