### PR TITLE
Fix potential fd leak

### PR DESCRIPTION
**Pull request by zrss**
Fixes: #9760

### CODE REVIEW

**Comment by zrss** [comment]
@hanxiaoshuai

**Comment by howardjohn** [comment]
is your branch fully up to date? test failures should he fixed in some recent changes

**Comment by zrss** [comment]
yes, i cherry-pick the commit to the latest master branch ...

**Comment by howardjohn** [comment]
No your branch is really old, from 2018. You need to rebase

**Comment by zrss** [comment]
oh, thx for pointing that out ... i forgot to fetch the latest code

**Pull request merged**
