### PR TITLE
fix duplicated mixer crd.

### LINKED ISSUE #20774: Mixer CRDs are defined multiple times
**Bug description**

Two mixer CRDs:

- `instances.config.istio.io`
- 'handlers.config.istio.io'

are defined multiple time in chart, see:
https://github.com/istio/istio/blob/master/manifests/base/files/crd-all.gen.yaml#L4569
https://github.com/istio/istio/blob/master/manifests/base/files/crd-mixer.yaml#L34

https://github.com/istio/istio/blob/master/manifests/base/files/crd-all.gen.yaml#L4405
https://github.com/istio/istio/blob/master/manifests/base/files/crd-mixer.yaml#L94

This results in resource cache expire in immediately for operator controller:, this can be confirmed through controller logs, you will find multiple logs for expired resource cache:

```
2020-02-02T10:00:13.489043Z     info    Changed object list:
 - CustomResourceDefinition::handlers.config.istio.io
 - CustomResourceDefinition::instances.config.istio.io
...
2020-02-02T10:00:17.589281Z     info    Changed object list:
 - CustomResourceDefinition::instances.config.istio.io
 - CustomResourceDefinition::handlers.config.istio.io
...

```

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/20774

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
this was attempted before and caused test failures , we should make sure the optional tests pass

**Comment by howardjohn** [comment]
I think the issue is the CRDs are different, and the ones we are now using are wrong? I have an optimization for CRD apply that is broken by this as well so definitely interested in fixing this as well

**Review by howardjohn — APPROVED** [review]
I put a hold, can you remove if mixer test passes?

thanks!

**Comment by morvencao** [comment]
Ok @howardjohn Thanks.

**Pull request merged**
