### PR TITLE
Fix in dump_kubernetes.sh to make it work on Ubuntu

### LINKED ISSUE #8140: Dump script to produce archive fails on Ubuntu
**Describe the bug**

Following the steps in 
https://istio.io/about/bugs/#generating-a-cluster-state-archive, the dump script (https://github.com/istio/istio/blob/master/tools/dump_kubernetes.sh) to produce archive fails on Ubuntu:

```
$ curl https://raw.githubusercontent.com/istio/istio/release-1.0/tools/dump_kubernetes.sh | sh -s -- -z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7573  100  7573    0     0  70294      0 --:--:-- --:--:-- --:--:-- 70775
sh: 143: Syntax error: "(" unexpected (expecting "}")
```

**Expected behavior**

Dump script should work as expected on Ubuntu.

**Steps to reproduce the bug**

```
$ curl https://raw.githubusercontent.com/istio/istio/release-1.0/tools/dump_kubernetes.sh | sh -s -- -z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7573  100  7573    0     0  70294      0 --:--:-- --:--:-- --:--:-- 70775
sh: 143: Syntax error: "(" unexpected (expecting "}")

$ echo $SHELL
/bin/bash
```

**Version**

```
$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**

No.

**Environment**

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

$ echo $SHELL
/bin/bash
```

### PR DESCRIPTION
**Pull request by ymesika**
Tested on Xenial.

Fixes #8140

### CODE REVIEW

**Comment by ymesika** [comment]
There aren't other places and after this change the script grabs a dump with no other error on Ubuntu's bash.

**Comment by vhosakot** [comment]
Thanks for fixing this @ymesika! - helps debugging istio issues :)

**Comment by ymesika** [comment]
@Tahler that's weird. I tested on Xenial and got the same error as @vhosakot and with this fix the error is gone.

**Comment by Tahler** [comment]
@ymesika Do you have any trouble running the snippet from my previous comment on Xenial?

**Comment by ymesika** [comment]
@Tahler no, snippet works fine:

```sh
a
b
c
a
b
c
```

**Comment by ymesika** [comment]
@Tahler for this one I get an error:

```sh
tap_containers() {
  local functions=( "$@" )
  for arg in "${args[@]}"; do
    echo "$arg"
  done
}

main() {
  parse_args "$@"

  tap_containers a b c
}

main "$@"
```

```
line 11: parse_args: command not found
```

**Comment by Tahler** [comment]
Any suggestions on how I can replicate the problem locally?

**Comment by ymesika** [comment]
What I did to test this was:
1. Run `/bin/bash` in an `ubuntu:xenial` image
1. apt-get update and apt-get needed commands
1. Configure `KUBECONFIG` to my cluster
1. Install kubectl
1. Download the dump script with curl
1. Execute it before and after the change

**Comment by ymesika** [comment]
@mandarjog one last lgtm plz

**Pull request merged**
