### PR TITLE
[release-1.8] Fix: telemetry httpmx filter patch at Gateway should have wasmEnabled option

### PR DESCRIPTION
**Pull request by carolynhu**
As in 1.8 we have more telemetry charts there, i need to make a separate PR for fixing this bug.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by carolynhu** [comment]
I removed telemetryv2_1.6.yaml, since we do not support cross two versions upgrade.

**Comment by howardjohn** [comment]
You should cherrypick only after the `master` PR is merged to avoid accidental merges or code drift if there are review comments

**Comment by carolynhu** [comment]
@bianpengyuan suggests not remove 1.6 yaml, so I will close this PR and let bots to do the cherry-pick.

**Pull request closed without merging**
