### PR TITLE
Use syncmap to protect fileBasedMetadataConfigAnyMap from race conditions

### LINKED ISSUE #12432: pilot crash 'fatal error: concurrent map writes`
**Background**
when sds enabled hit error logs in pilot which cause pilot crash
```
2019-03-12T20:09:52.627598Z	info	ads	Push debounce stable[2] 22: 100.21642ms since last change, 122.768213ms since last push, full=true
fatal error: concurrent map writes

goroutine 316 [running]:
runtime.throw(0x1bbca4b, 0x15)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0xc420922898 sp=0xc420922878 pc=0x42b381
runtime.mapassign(0x19211c0, 0xc4200af3b0, 0xc420922978, 0x0)
	/usr/local/go/src/runtime/hashmap.go:607 +0x553 fp=0xc420922928 sp=0xc420922898 pc=0x408593
istio.io/istio/pilot/pkg/model.findOrMarshalFileBasedMetadataConfig(0x1bd3702, 0x23, 0x1bceb64, 0x20, 0xc4201f7310, 0x3a2274416465)
	/usr/local/google/home/quanlin/go/src/istio.io/istio/pilot/pkg/model/authentication.go:281 +0x111 fp=0xc4209229a8 sp=0xc420922928 pc=0x1356fb1
istio.io/istio/pilot/pkg/model.constructgRPCCallCredentials(0x1bd3702, 0x23, 0x1bceb64, 0x20, 0x29906c0, 0x0, 0xc420a70280)
	/usr/local/google/home/quanlin/go/src/istio.io/istio/pilot/pkg/model/authentication.go:241 +0x107 fp=0xc420922a18 sp=0xc4209229a8 pc=0x1356ca7
istio.io/istio/pilot/pkg/model.ConstructSdsSecretConfig(0x1ba85eb, 0x7, 0xc42051e480, 0x1a, 0xc420890001, 0x0, 0x80)
	/usr/local/google/home/quanlin/go/src/istio.io/istio/pilot/pkg/model/authentication.go:138 +0x216 fp=0xc420922ad8 sp=0xc420922a18 pc=0x13562f6
istio.io/istio/pilot/pkg/networking/core/v1alpha3.applyUpstreamTLSSettings(0xc4202de500, 0xc42057fc80, 0xc4200dfb60, 0x0)

```

**Possible Solution**
use syncmap for fileBasedMetadataConfigAnyMap

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Fixes #12432

### CODE REVIEW

**Comment by duderino** [comment]
@mandarjog @costinm @rshriram @hzxuzhonghu this PR just barely missed the 1.1rc4 cutoff and we thought that 1.1rc4 was likely the final release.  I'm OK creating another release candidate for this, but I'm worried about the risk of accepting additional serialization this late in the game. 

Thoughts?

**Comment by wenchenglu** [comment]
I vote for merging this into 1.1. This is a trivial fix for an important bug.

**Comment by rshriram** [comment]
Can you fix the helm templates please? Currently SDS.enabled is not used as a guard for setting the sds.udsPath in the global mesh config map. And if someone accidentally adds some dummy path to this udsPath (while setting sds.enabled=false), it literally enables SDS in pilot. This will cause all envoys to crash.

**Comment by rshriram** [comment]
All the SDS fields in the mesh config are unguarded completely!

**Comment by quanjielin** [comment]
today's pilot generate sdsconfig based on meshconfig.sdsudspath set or not, as put in [doc](https://preliminary.istio.io/docs/tasks/security/auth-sds/), [values-istio-sds-auth.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values-istio-sds-auth.yaml) is config users should use if they want to try sds in 1.1.

**Comment by hzxuzhonghu** [comment]
But should validate these sds related fields in MeshConfig, this is the last guard.  In case users modify the value, it may cause critical system down.

**Comment by quanjielin** [comment]
Could you be more specific where to validate which meshconfig param ? [proto](https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L187) documented 'use secret mount instead of SDS if path set to empty' long time ago; there may be better user interface to adopt SDS, feel free to open another issue to track this(as https://github.com/istio/istio/issues/12442) for future work, let's limit this PR's scope to fix race condition.

**Comment by hzxuzhonghu** [comment]
Like these `SdsUdsPath, EnableSdsTokenMount, SdsUseK8SSaJwt`,  if users enable these, does it depend on some others settings or are they mutual exclusive?

**Comment by wenchenglu** [comment]
+1
the helm change should be handled in a separate PR

**Comment by wenchenglu** [comment]
@quanjielin 
Quanjie, could you file a separate issue to track the helm change? I don't think that is related to https://github.com/istio/istio/issues/12442, but for better usability on SDS config. And I guess that fix can wait till 1.1.1 unless it is very trivial fix.

**Comment by JimmyCYJ** [comment]
> Quanjie, could you file a separate issue to track the helm change? I don't think that is related to #12442, but for better usability on SDS config. And I guess that fix can wait till 1.1.1 unless it is very trivial fix.

I filed https://github.com/istio/istio/issues/12443 to keep tracking of the SDS config improvements.

**Comment by quanjielin** [comment]
Thanks @JimmyCYJ , filed https://github.com/istio/istio/issues/12444(to track work in 1.2 when we support per-pod SDS rollout(migration) and SDS in control plane, which may introduce more customer facing settings).

**Comment by duderino** [comment]
This will go int 1.1rc5

**Pull request merged**
