### PR TITLE
trim circleci jobs

### PR DESCRIPTION
**Pull request by rshriram**
Remove unused job definitions
Remove nightly and periodic builds that take up resources
Disable jobs that are already run by prow.

### CODE REVIEW

**Comment by rshriram** [comment]
This should significantly cut down @louiscryan 's bill :)

**Comment by duderino** [comment]
/approved
/lgtm

@louiscryan told me he doesn't mind the CC charges.  Want the number, exp date, and CCV?

**Comment by rshriram** [comment]
merged. this is CI change - disabling redundant jobs, per last TOC meeting. Lint failure is known. Also synced with all release-xx branches

**Comment by geeknoid** [comment]
Er, is passing lint no longer a requirement? Sure looks like it. Did someone turn that off?

**Pull request merged**
