### PR TITLE
fix flaky workload entry to ports

### PR DESCRIPTION
**Pull request by timonwong**
**Please provide a description of this PR:**

Fix flaky test introduced in #36504

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/36930/unit-tests_istio/1486955106078298112

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Comment by timonwong** [comment]
should we label `release-notes-none` ?

**Review by howardjohn — COMMENTED** [review]
Thanks! I think container Port may not be unique always so it could still be non deterministic

https://github.com/istio/istio/pull/37045 has similar change fwiw but happy to merge this as well if it gets approved. Thanks for caring about test stability

**Comment by timonwong** [comment]
> Thanks! I think container Port may not be unique always so it could still be non deterministic
> 
> #37045 has similar change fwiw but happy to merge this as well if it gets approved. Thanks for caring about test stability

@howardjohn Thanks for pointing out the port number issue, now it's sorted by port name instead.

**Review by stevenctl — APPROVED** [review]

**Comment by timonwong** [comment]
Since #37045 is merged, is this PR still useful?

**Pull request closed without merging**
