### PR TITLE
Fix grace period issues in secret controller.

### PR DESCRIPTION
**Pull request by myidpt**
Fixes https://github.com/istio/istio/issues/3753

Also make our unit tests with more explicit values.

### CODE REVIEW

**Comment by ldemailly** [comment]
I'm looking at the test failure in #3760

**Comment by charleslieferando** [comment]
I'm seeing this issue using latest istio 0.6.0

```
2018-03-08T09:47:59.447533Z	info	Istio CA has started
2018-03-08T09:47:59.447575Z	info	Starting GRPC server on port 8060
2018-03-08T09:47:59.480852Z	info	Istio secret for service account "default" in namespace "kube-public" has been created
2018-03-08T09:47:59.624824Z	info	Istio secret for service account "fluentd-service-account" in namespace "kube-system" has been created
2018-03-08T09:48:00.273505Z	info	Istio secret for service account "heapster" in namespace "kube-system" has been created
2018-03-08T09:48:00.668968Z	info	Istio secret for service account "kube-dns" in namespace "kube-system" has been created
2018-03-08T09:48:00.858188Z	info	Istio secret for service account "registry" in namespace "kube-system" has been created
2018-03-08T09:48:00.978199Z	info	Istio secret for service account "default" in namespace "rook-system" has been created
2018-03-08T09:48:01.097015Z	info	Istio secret for service account "rook-operator" in namespace "rook-system" has been created
2018-03-08T09:48:01.237137Z	info	Istio secret for service account "custom-metrics-apiserver" in namespace "custom-metrics" has been created
2018-03-08T09:48:01.657457Z	info	Istio secret for service account "prometheus" in namespace "rook" has been created
2018-03-08T09:48:02.144716Z	info	Istio secret for service account "default" in namespace "istio-system" has been created
2018-03-08T09:48:02.322547Z	info	Istio secret for service account "default" in namespace "rook" has been created
2018-03-08T09:48:02.580641Z	info	Istio secret for service account "metrics-server" in namespace "kube-system" has been created
2018-03-08T09:48:03.219028Z	info	Istio secret for service account "rook-api" in namespace "rook" has been created
2018-03-08T09:48:03.537629Z	info	Istio secret for service account "istio-pilot-service-account" in namespace "istio-system" has been created
2018-03-08T09:48:04.415413Z	info	Istio secret for service account "istio-ca-service-account" in namespace "istio-system" has been created
2018-03-08T09:48:04.796586Z	info	Istio secret for service account "prometheus-operator" in namespace "default" has been created
2018-03-08T09:48:05.320847Z	info	Istio secret for service account "rook-ceph-osd" in namespace "rook" has been created
2018-03-08T09:48:05.518719Z	info	Istio secret for service account "istio-ingress-service-account" in namespace "istio-system" has been created
2018-03-08T09:48:05.676221Z	info	Istio secret for service account "rook-agent" in namespace "rook-system" has been created
2018-03-08T09:48:05.830553Z	info	Istio secret for service account "default" in namespace "default" has been created
2018-03-08T09:48:06.024217Z	info	Istio secret for service account "default" in namespace "kube-system" has been created
2018-03-08T09:48:06.201693Z	info	Istio secret for service account "kube-dns-autoscaler" in namespace "kube-system" has been created
2018-03-08T09:48:06.620466Z	info	Istio secret for service account "kubernetes-dashboard" in namespace "kube-system" has been created
2018-03-08T09:48:07.176789Z	info	Istio secret for service account "weave-net" in namespace "kube-system" has been created
2018-03-08T09:48:07.353284Z	info	Istio secret for service account "istio-mixer-service-account" in namespace "istio-system" has been created
2018-03-08T09:48:07.451954Z	info	Istio secret for service account "default" in namespace "custom-metrics" has been created
2018-03-08T09:48:33.665976Z	info	adding registry entry "spiffe://cluster.local/ns/istio-system/sa/prometheus" -> "spiffe://cluster.local/ns/istio-system/sa/prometheus"
2018-03-08T09:48:33.779496Z	info	Istio secret for service account "prometheus" in namespace "istio-system" has been created
2018-03-08T09:48:34.261759Z	info	adding registry entry "spiffe://cluster.local/ns/default/sa/prometheus" -> "spiffe://cluster.local/ns/default/sa/prometheus"
2018-03-08T09:48:34.669239Z	info	Istio secret for service account "prometheus" in namespace "default" has been created
2018-03-08T09:48:59.366846Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.366952Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367030Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367121Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367204Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367283Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367362Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367460Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367534Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367626Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367734Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367826Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367902Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.367989Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.368099Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.368210Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.368299Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.368419Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
2018-03-08T09:48:59.368523Z	warn	gracePeriod (19h0m0s * 0.500000) = 10m0s is less than minGracePeriod %!v(MISSING). Apply minGracePeriod.
```

**Comment by myidpt** [comment]
Sorry, unfortunately this change is not made into 0.6.0...

**Comment by charleslieferando** [comment]
@myidpt  do you know if this issue has consequences for the istio dashboard in 0.6.0? Since I updated, in addition to the issue here my istio dashboard doesn't show any metrics. The mixer and pilot dashboards are fine though...

**Comment by myidpt** [comment]
No, this change is not in V0.6.0 release, so there shouldn't be any relations:
https://github.com/istio/istio/commits/release-0.6

**Comment by zvikaga** [comment]
Observing this issue in 0.6.0. Any idea how to fix it w/o upgrading...

**Comment by myidpt** [comment]
Try to set --workload-cert-min-grace-period=10h (or any period you want):
https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L206

**Comment by zvikaga** [comment]
Hi ,
Sorry for the delay. I have tried already using 15m. That didn't work. It
actually put the entered value as the result of the calculation of workload
cert timeout multiplied by the factor.

**Pull request merged**
