### PR TITLE
Create short names for pilot's CRD

### PR DESCRIPTION
**Pull request by jwendell**
Closes: #2650

### CODE REVIEW

**Comment by costinm** [comment]
Happy to type less :-), but seems like an API issue - do we need to update the api repo/examples ? 
Any doc to update ?

**Comment by rshriram** [comment]
Is this some kube thing? Also how do you delineate v1alpha2 route rule? I don’t mind short names. And this short name thing is new to me. We have been using long names everywhere. I think this becomes useful when you use kubectl to do things like kubectl list rr, etc. right ?

**Comment by jwendell** [comment]
@costinm I don't see a doc that explicitly talks about istio resources, for example, teaching a command like `kubectl get destinationpolicies`. What I see are rare usages of them (for example in https://istio.io/docs/tasks/traffic-management/request-routing.html). I'll open a PR on istio website repo adding a note there.

@rshriram Yes, this is a kube thing. It allows you to type less (eg. `kubectl get svc` instead of `kubectl get services`). Indeed, its usage is restrict to CLI commands like kubectl. It's just an alias for the actual resource.

I've updated this PR also adding this short name feature to `istioctl` binary as well.

Note that not all resources have short names (this is also valid for kubernetes, try `kubectl get`). If we decide to add short names for more types in the future, it will be easy to do so after this PR is merged.

**Comment by frankbu** [comment]
I like the short names, but it seems like there is a good chance of conflicts, esp with such short names like `rr`, `er`, etc. What happens if there are conflicts? If, for example, kubernetes adds a conflicting one in a future release? Will that break our CRD registration during install?

**Comment by jwendell** [comment]
@frankbu I'm not sure about breaking the installation. From what I have tested locally, it seems that the CRD will be installed fine, although things are quite inconsistent in my opinion.

My experiments:
- Installed a CRD (DestinationPolicy) with the short name 'svc': Install went ok and `kubectl get svc` returned services
- Changed this CRD short name to 'dp'
- Installed another CRD (EgressRule) with the short name 'dp': Install was not so ok. Status reported a conflict in the short name and `kubectl get egressrule` fails with the message `the server doesn't have a resource type "egressrules"`
- Changed this CRD short name to 'svc'. `kubectl get svc` returned egress rules!!

This sounds like a [bug in k8s for me](https://github.com/kubernetes/kubernetes/issues/59812).

However I don't think this should block us from using short names...

**Comment by ldemailly** [comment]
@louiscryan can you make a call
thx

**Comment by rshriram** [comment]
deferring to @frankbu

**Comment by frankbu** [comment]
I'm still a little worried about the potential conflicts, but that said, I do like short names, I always use them myself for kube resources (e.g., `po`, `svc`, `ing` ...).

I wonder if we should defer this until we switch to the new routing model, since the resources are different - which would also suggest different short names. For example, in the new model: `RouteRule` -> `VirtualService`, `EgressRule` -> `ExternalService`, and `DestinationPolicy` -> `DestinationRule`.

**Comment by louiscryan** [comment]
I defer to Frank on this too :)

**Comment by costinm** [comment]
It seems the PR is still stuck, sorry for failing to follow up. 

Since we're planning to deprecate alpha1, I think this can be closed - I really liked the idea, it would be great if you can apply the same change to alpha3.

**Pull request closed without merging**
