### PR TITLE
Sync pilot dashboard file name with its title name

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

**Please provide a description of this PR:**

sync pilot dashboard file name with its title name, we should better call it istio-control-plane-dashboard.json not pilot-dashboard.json, it is not synced with its dashboard title name and current architecture.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by zirain — APPROVED** [review]
lgtm

**Review by howardjohn — COMMENTED** [review]
I am not sure about this. The file name is not something the user typically sees so it shouldn't bother them what its named. However, I worry it may break some automation, etc changing the value. Especially in the configmap

**Pull request closed without merging**
