### PR TITLE
enable mc tests for status

### PR DESCRIPTION
**Pull request by therealmitchconnors**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Do the tests check that we write status to all clusters?

**Comment by therealmitchconnors** [comment]
> Do the tests check that we write status to all clusters?

As I understand it, the multicluster tests us a single control plane, and therefore only one cluster contains configs, and only that cluster should receive status updates.  Is that correct?  Or are we running multiple control planes (in which case, how do I write a virtual service to all clusters containing config?)

**Comment by howardjohn** [comment]
Ah good point. There are multiple primaries (see diagram in https://docs.google.com/document/d/1rZ_WmRV0AZqjWWss5Hci18zn_2h9o-M4Wu0OmlRIfHE/edit?usp=sharing) but one cluster should only have one source of config so maybe it doesn't matter too much?
cc @stevenctl

**Pull request merged**
