### PR TITLE
Add connection_mtls to dashboard.

### PR DESCRIPTION
**Pull request by JimmyCYJ**
screenshot from 2018-03-07 14-56-17
https://github.com/istio/istio/issues/4002#event-1505533824

### CODE REVIEW

**Comment by douglas-reid** [comment]
@JimmyCYJ Can you please add a screenshot showing the new additions to the PR description ?

**Comment by JimmyCYJ** [comment]
@douglas-reid I have added a screenshot to the PR description. Thanks!

**Comment by JimmyCYJ** [comment]
@rshriram It is mTLS between two services. 
[virtual bool Connection::peerCertificatePresented() const PURE;](https://github.com/envoyproxy/envoy/blob/1db0c7ace77263c554d18dfffa21ea2b5ea6f3b9/include/envoy/ssl/connection.h#L20) tells whether a request is from a mtls connection.

**Comment by douglas-reid** [comment]
@rshriram this isn't using envoy metrics, but rather attributes sent to the Mixer. The attribute derivation logic PR was here (i believe): https://github.com/istio/proxy/pull/1003.

The fact that the difference in Secured v. Unsecured is ~1 RPS in this example is related to the lack of mTLS at Ingress.

**Pull request merged**
