### PR TITLE
xds: enable skip node ID

### PR DESCRIPTION
**Pull request by howardjohn**
Forking https://github.com/istio/istio/pull/17361 to get this moving

### CODE REVIEW

**Review by douglas-reid — APPROVED** [review]
Approving, as I already approved the original PR.

**Comment by howardjohn** [comment]
/retest

opening an issue for flake

**Comment by howardjohn** [comment]
/retest

https://github.com/istio/istio/issues/19269

**Review by rshriram — APPROVED** [review]

**Comment by howardjohn** [comment]
We are somehow getting a XDS request as the initial request that looks like:
`version_info:"2019-12-20T00:45:40Z/124" type_url:"type.googleapis.com/envoy.api.v2.Cluster" response_nonce:"fLWnqSbM7Ms=553cbca6-69b2-4aea-ac9b-2858d998c36c" `

Probably this means we are missing the first one somehow

**Comment by kyessenov** [comment]
How are tests passing without node id?

**Comment by howardjohn** [comment]
@kyessenov to be honest, I have no clue why it works sometimes. The one test that is failing is how I was able to consistently reproduce. Maybe digging into that case more will be needed to understand this more.

**Review by hzxuzhonghu — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Pull request merged**
