### PR TITLE
Fixing test compilation and error on master pilot/pkg/config/monitor/

### PR DESCRIPTION
**Pull request by ldemailly**
fixing auto merge error between #3847 and #3887

### CODE REVIEW

**Comment by wattli** [comment]
Many unrelated tests are failing, so is my PR https://github.com/istio/istio/pull/3891, i will ping oncall on slack

**Comment by ldemailly** [comment]
merging as this at least fixes circleci
the pilot error is unrelated / related to minikube api server errors costin is tracking in the other pr

**Pull request merged**
