### PR TITLE
Remove redundant type conversion

### PR DESCRIPTION
**Pull request by sevenNt**

### CODE REVIEW

**Comment by sevenNt** [comment]
Hi, @andraxylia some test scripts executed failed, is there something wrong with this PR?

**Comment by andraxylia** [comment]
The test were flaky, nothing wrong with the PR. I re-triggered them. If they fail again, could you please merge with latest master? If it still fails, @wattli is on call and can help to get it in.

**Comment by sevenNt** [comment]
OK, thank you andraxylia.

**Comment by sevenNt** [comment]
@wattli , would you mind merge the PR into master?

**Pull request merged**
