### PR TITLE
add echo-grpc sample for doc

### PR DESCRIPTION
**Pull request by stevenctl**
see https://github.com/istio/istio.io/pull/10168

### CODE REVIEW

**Comment by ericvn** [comment]
The one question I have is do you want to use `samples/echo` (as in the blog post PR), or `samples/echo-grpc` as shown here?

**Comment by stevenctl** [comment]
Good point - also should we make this more generic and open up the same set of ports we have for integration tests? Then we can use the same sample for tcp, http and a bunch of other stuff.

**Comment by ericvn** [comment]
> Not really. This is actually a different app, and it supports pretty much any protocol (tcp, gRPC, http, etc) - while my doc is gRPC based, this could be used for other things if needed

I notice that the yaml does call out the echo-grpc namespace as well as other grpc values.

**Comment by stevenctl** [comment]
I guess with all the special annotations it's not worth trying to make this re-usable. Renamed back to echo-grpc, will update the blogpost.

**Comment by ericvn** [comment]
I'm fine with `echo-grpc`, although I understand @rvennam comment about switching the order so echo is `grpc` is first as `tcp` is first

**Pull request merged**
