### PR TITLE
remove unused func makeFakeKubeAPIController and pollUntil in controller_test.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
remove unused func makeFakeKubeAPIController and pollUntil in controller_test.go

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Is the build failure related to this?

**Comment by hanxiaoshuai** [comment]
@hzxuzhonghu OK, Thanks

**Comment by hzxuzhonghu** [comment]
@hanxiaoshuai Would you rebase?

**Comment by hanxiaoshuai** [comment]
@hzxuzhonghu I have rebased it. Thanks

**Comment by hzxuzhonghu** [comment]
The build failure I think was fixed by vendor update.

**Pull request closed without merging**
