### PR TITLE
Revert "Support k8s version <= 1.15"

### PR DESCRIPTION
**Pull request by sdake**
Reverts istio/istio#24228

### CODE REVIEW

**Comment by howardjohn** [comment]
Why? No problem reverting if this causes issues but I don't have any context

**Comment by sdake** [comment]
@howardjohn The only problem I perceive this causing is that it opens Istio up to a 5 release K8s support window expectation for now in the future. How do we drop 1.14 if we just added 1.14 support in 1.6 backport?

We had 3 or 4 hours of conversation that led to the 3 K8s window + occasionally 4 windows in T&R and TOC. The decision was agreed upon, and this reverts that decision:

See:
https://github.com/istio/istio/pull/24228#issuecomment-636318648

**Comment by hzxuzhonghu** [comment]
I do agree with the [k8s support matrix](https://docs.google.com/document/d/14Xfe9V0vv8d7W75c21d-cY2XyK6xvRH0_Kg8j_zfh4Y/edit#bookmark=id.3gi4mzlz3xnp).  This is a better to have stuff.

**Pull request merged**
