### PR TITLE
Update package versions in docker-dev Dockerfile

### PR DESCRIPTION
**Pull request by rlenglet**
Update the versions of gcloud and kubectl CLI packages.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

### CODE REVIEW

**Comment by rlenglet** [comment]
All required tests passed.

**Comment by sdake** [comment]
@rlenglet we are attempting to cease dev in istio/istio:tools and move all new work to istio/tools/docker

Would you consider moving this file to that location as a PR?

**Comment by rlenglet** [comment]
Moved to https://github.com/istio/tools/pull/258. Closing.

**Pull request closed without merging**
