### PR TITLE
enable default sidecarscope

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Enable get DestinationRule and Services from default sidecarScope

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
We are in 1.2 period, and it's secure to enable it.

**Comment by linsun** [comment]
What is the user impact for this?  Does this mean default sidecarScope is always configured?

**Comment by hzxuzhonghu** [comment]
>What is the user impact for this?  Does this mean default sidecarScope is always configured?

1. Should have no impact on users.     
2. Yes, for a namespace, if there is no sidecar defined, a default one will be generated, this is also 1.1 behavior. But in 1.1 in order to reduce risk, the Service() and DestinationRule() interface still use the original ones.

**Pull request merged**
