### PR TITLE
Do not set fsGroup when its not needed

### PR DESCRIPTION
**Pull request by howardjohn**
For issues like https://github.com/istio/istio/issues/26882

On Kubernetes 1.19+ we can avoid this issue. This adds a flag to disable
setting this option, and automatically disables this if we are on
Kubernetes 1.19+

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by howardjohn** [comment]
@FrimIdan I think this can solve your case with first party jwt as well? WDYT?

**Comment by FrimIdan** [comment]
> @FrimIdan I think this can solve your case with first party jwt as well? WDYT?

@howardjohn Does this fix automatically disable the fsGroup injection when running with first party jwt or we need to also disable to set ENABLE_LEGACY_FSGROUP_INJECTION to false?

**Comment by howardjohn** [comment]
> Does this fix automatically disable the fsGroup injection when running with first party jwt or we need to also disable to set ENABLE_LEGACY_FSGROUP_INJECTION to false?

No, but I suppose we should do that as well? I don't see any risk here, do you?

**Comment by FrimIdan** [comment]
> > Does this fix automatically disable the fsGroup injection when running with first party jwt or we need to also disable to set ENABLE_LEGACY_FSGROUP_INJECTION to false?
> 
> No, but I suppose we should do that as well? I don't see any risk here, do you?

This was my intention in the first place - If we run first party we definitely don't need the injection - I've tested it

**Comment by FrimIdan** [comment]
@howardjohn What was changed in K8s 1.19 that the fsGroup injection is not needed?

**Comment by howardjohn** [comment]
@FrimIdan https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d is the fix

**Comment by FrimIdan** [comment]
> @FrimIdan [kubernetes/kubernetes@3db7275](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d) is the fix

Thanks, looks like if the main container will run with runAsUser != 1337 we will have the same problem - only the main container will have permissions to access the projected SA , or I misunderstand the fix?

**Comment by howardjohn** [comment]
@FrimIdan I think we hit the "fallback" case listed in https://github.com/kubernetes/enhancements/pull/1598?

**Comment by FrimIdan** [comment]
> @FrimIdan I think we hit the "fallback" case listed in [kubernetes/enhancements#1598](https://github.com/kubernetes/enhancements/pull/1598)?

You probably right - thanks for the info and for the update!

**Review by rlenglet — APPROVED** [review]

**Comment by howardjohn** [comment]
@FrimIdan added the logic for 1p jwt as well. Thanks for pointing this out!

**Review by ericvn — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Comment by howardjohn** [comment]
@esnible

**Review by esnible — APPROVED** [review]

**Pull request merged**
