### PR TITLE
Update proxy sha

### PR DESCRIPTION
**Pull request by bianpengyuan**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by rshriram — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/25159/integ-operator-controller-tests_istio/3601/artifacts/operator-573ee727e6d346cb91aa15/TestController/default-1-80943-state145871668/client-v1-86748ccc8f-hg5pj-istio-proxy.log

wasm code changed?

**Comment by bianpengyuan** [comment]
@howardjohn yeah, hopefully the last commit fix stats config. The other issue is `use_origin_dst` option. Looks like envoy is rejecting that now. Are we ready to avoid setting that field now? Or is there a way to work around that validation? @lambdai 

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/25159/integ-distroless-k8s-tests_istio/8405/artifacts/security-4009871b6fb743a5859e71/TestReachability/reachability-1-46717-state337422130/a-v1-6cd4cc47d6-rf6zp-istio-proxy.log

**Comment by bianpengyuan** [comment]
I probably need some one from networking team to take over this change, if stats configuration is no longer a problem and fix for deprecated envoy configuration is not trivial..

**Comment by howardjohn** [comment]
https://github.com/envoyproxy/envoy/pull/11160 is the breaker

@bianpengyuan looks like stats may also be not working though?
```
virtualInbound: Unable to parse JSON as proto (INVALID_ARGUMENT:(config.configuration): invalid value "{
  "debug": "false",
  "stat_prefix": "istio"
}
" for type type.googleapis.com/google.protobuf.Any): {"config":{"root_id":"stats_inbound","configuration":"{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n","vm_config":{"vm_id":"tcp_stats_inbound","code":{"local":{"inline_string":"envoy.wasm.stats"}},"runtime":"envoy.wasm.runtime.null"}}}
```

**Comment by howardjohn** [comment]
oh maybe that was an old log. Anyhow I am looking into it

**Comment by bianpengyuan** [comment]
Yeah, stats config should be fixed now. All test failures are because of use_original_dst.

**Comment by howardjohn** [comment]
```diff
diff --git a/tools/packaging/common/envoy_bootstrap.json b/tools/packaging/common/envoy_bootstrap.json
index 6d39f1e1fd..492f461b0a 100644
--- a/tools/packaging/common/envoy_bootstrap.json
+++ b/tools/packaging/common/envoy_bootstrap.json
@@ -21,6 +21,20 @@
     },
     "metadata": {{ .meta_json_str }}
   },
+  "layered_runtime": {
+      "layers": [
+          {
+              "name": "deprecation",
+              "static_layer": {
+                  "envoy.deprecated_features:envoy.config.listener.v3.Listener.hidden_envoy_deprecated_use_original_dst": true
+              }
+          },
+          {
+              "name": "admin",
+              "admin_layer": {}
+          }
+      ]
+  },
   "stats_config": {
     "use_all_default_tags": false,
     "stats_tags": 
```

**Comment by lambdai** [comment]
> I tested this fixes it:
> 
> ```diff
> diff --git a/tools/packaging/common/envoy_bootstrap.json b/tools/packaging/common/envoy_bootstrap.json
> index 6d39f1e1fd..492f461b0a 100644
> --- a/tools/packaging/common/envoy_bootstrap.json
> +++ b/tools/packaging/common/envoy_bootstrap.json
> @@ -21,6 +21,20 @@
>      },
>      "metadata": {{ .meta_json_str }}
>    },
> +  "layered_runtime": {
> +      "layers": [
> +          {
> +              "name": "deprecation",
> +              "static_layer": {
> +                  "envoy.deprecated_features:envoy.config.listener.v3.Listener.hidden_envoy_deprecated_use_original_dst": true
> +              }
> +          },
> +          {
> +              "name": "admin",
> +              "admin_layer": {}
> +          }
> +      ]
> +  },
>    "stats_config": {
>      "use_all_default_tags": false,
>      "stats_tags": 
> ```

Thank you for finding out the workaround. I need to pick up the pilot change now

**Review by howardjohn — APPROVED** [review]

**Review by rshriram — APPROVED** [review]

**Review by mandarjog — APPROVED** [review]
Lgtm

**Pull request merged**
