### PR TITLE
Add find root cert fuzzer to tests

### PR DESCRIPTION
**Pull request by howardjohn**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by lei-tang — COMMENTED** [review]
"tests/fuzz/testdata/FuzzFindRootCertFromCertificateChainBytes/6118602084843520" is an empty file. Is it needed?

**Comment by howardjohn** [comment]
Yes, its a regression test case. Generally the idea so far as has been that
test cases the fuzzer generates that fail the test are added as regression
tests. it being empty is a bit trivial, but in this case it did trigger a
failure previously so its good to keep around as reference and to ensure it
doesn't break in the future, IMO.

**Comment by lei-tang** [comment]
Nit: why is the file named as "6118602084843520"? Will a name such as "empty-file" also work?

**Comment by howardjohn** [comment]
Its correlated to the OSS fuzz test case. This is accessible only to PSWG.
This is the same pattern https://go.dev/blog/fuzz-beta uses

**Review by lei-tang — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Pull request merged**
