### PR TITLE
provide option to support always valid token to keep stream open

### PR DESCRIPTION
**Pull request by quanjielin**
one example of always valid token is normal k8s jwt, in this case, node agent don't send err by envoy to end the stream, instead just push the update key/cert to envoy directly

and merge https://github.com/istio/istio/pull/11101

https://github.com/istio/istio/issues/9035

### CODE REVIEW

**Comment by quanjielin** [comment]
@hklai , could you pls merge this PR ? thanks!

**Comment by hklai** [comment]
Manual merge due to flaky pilot test.

**Pull request merged**
