### PR TITLE
envoy: enable workload discovery (ambient-only)

### PR DESCRIPTION
**Pull request by kyessenov**
Attempt to fix the ambient post-submit.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM, not sure what is broken in postsubmit though? seems to work

**Comment by kyessenov** [comment]
https://testgrid.k8s.io/istio_istio_postsubmit#integ-ambient_istio_postsubmit

We should probably not merge envoy changes that break ambient (intentional or not).

**Comment by kyessenov** [comment]
Where do I see ambient pre-submit now?

**Comment by howardjohn** [comment]
/test integ-ambient

I think it will show up now. i had a PR to make it always run but forgot to submit it, thanks for the reminder: https://github.com/istio/test-infra/pull/4602

**Comment by kyessenov** [comment]
@howardjohn Looks like DELTA wasn't actually flipped in ambient:
```
     "ads_config": {
      "api_type": "GRPC",
      "grpc_services": [
       {
        "envoy_grpc": {
         "cluster_name": "xds-grpc"
        }
       }
      ],
```

**Pull request merged**
