### PR TITLE
Update API version for PSP security sample

### PR DESCRIPTION
**Pull request by pipo02mix**
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
@myidpt

**Comment by nschhina** [comment]
This seems reasonable as extensions/v1beta1 was deprecated since 1.16. And policy/v1beta1 is supported since 1.10

**Comment by nschhina** [comment]
Maybe we should also update it everywhere in istio/istio.io together as well

**Comment by pipo02mix** [comment]
> Maybe we should also update it everywhere in istio/istio.io together as well

I can push a PR later

**Comment by pipo02mix** [comment]
I am pretty sure my change has not trigger the failure in the mutlicluster test suite

**Pull request merged**
