### PR TITLE
[release-1.23] networking: match multiple VIPs in sidecar outbound listener

### PR DESCRIPTION
**Pull request by jewertow**
**Please provide a description of this PR:**

This is a manual cherry-pick of #51967, because the automated [one](https://github.com/istio/istio/pull/52148) can't be merged due to a conflict.

### CODE REVIEW

**Comment by jewertow** [comment]
@thedebugger can you approve?

**Review by mikemorris — APPROVED** [review]
Approving per 👍 in Slack from @howardjohn @ilrudie

**Pull request merged**
