### PR TITLE
align init role label.

### PR DESCRIPTION
**Pull request by morvencao**

### CODE REVIEW

**Comment by morvencao** [comment]
My understanding is that the label here will be not used for selection during upgrade, it should be working to modify it.

**Comment by morvencao** [comment]
I would like to manually test this after https://github.com/istio/istio/issues/12855 is fixed!

**Comment by hobbytp** [comment]
Can I understand that we shall use "helm upgrade --force" to do upgrade instead of "helm upgrade"? But I think they are different. I found the fixing is only update the lable from "istio-init" to "init", this can not fix the problem when I only use "helm upgrade" instead of "helm upgrade --force", anyone can help clarify this?

**Comment by morvencao** [comment]
@hobbytp Sorry for the confusion, this PR isn't meant to address the issue: https://github.com/istio/istio/issues/12855

And you are right, we still need add `--force` when upgrading `istio-init` chart, because we need to make sure the crd creation job to run again during upgrading.

**Pull request merged**
