### PR TITLE
Switch fortio tags to "latest_release" to not get -pre intermediate versions

### PR DESCRIPTION
**Pull request by ldemailly**
Switch fortio tags to "latest_release" to not get -pre intermediate
versions by default

Some tricks to get the right version to show despite building from
source

Updated runtime go for fortio to 1.9 on VM setup (somehow 1.10 doesn’t show up yet)

### CODE REVIEW

**Comment by mattdelco** [comment]
Possibly also:
samples/rawvm/Makefile
tests/helm/values.yaml
Regardless it seems like many of these cases should be trying harder to pick up what's in istio.VERSION but I suppose that's more like a feature request than a bug fix,

**Comment by costinm** [comment]
We are trying to deprecated updateVersion and istio.VERSION ( i.e. to not included them releases ), use istioctl gen-deploy instead.

**Comment by costinm** [comment]
Also: we are trying to deprecated updateVersion and istio.VERSION ( i.e. to not included them releases ), use istioctl gen-deploy instead. We should use 'latest_release' or semantic version everywhere. Both minikube and regular k8s with keel support upgrading on tag.

**Pull request merged**
