### PR TITLE
Fixes #26668. Annotation to enableCoreDump fixed.

### LINKED ISSUE #26668: Annotation `sidecar.istio.io/enableCoreDump` no longer works
**Bug description**
The annotation `sidecar.istio.io/enableCoreDump` added in https://github.com/istio/istio/issues/19932 and related tickets no longer works. This means that you have to enable core dumps across the entire mesh if you need a user to send you one for debugging. 

The problem is a straightforward fix, adding the conditional statement from https://github.com/ckcd/istio/blob/a7d19495f98d8af19bf0d344f80ca7718285bb13/install/kubernetes/helm/istio/files/injection-template.yaml#L61 back into the manifest in https://github.com/istio/istio/blob/8f5b742435f532399024383a0f2ec21f5d354239/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L91, and testing that it works.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by sha-rath**
This PR adds back the functionality to enable core dumps using the annotation `sidecar.istio.io/enableCoreDump`. So, core dumps can now be enabled either across the entire mesh or for a specific deployment.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
may also want to look into https://github.com/istio/istio/issues/32009

**Comment by sha-rath** [comment]
> may also want to look into #32009

Looks promising. Can take a look into it.

**Comment by sha-rath** [comment]
@googlebot I signed it!

**Review by morvencao — COMMENTED** [review]
/ok-to-test

**Pull request merged**
