### PR TITLE
fix: NodeAgent CrashLoopBackOff if enabled

### PR DESCRIPTION
**Pull request by rjshrjndrn**
If nodeagent enabled in values.yml, by default it'll crashloop.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ x ] Configuration Infrastructure
[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by clyang82** [comment]
Thanks for your contribution. if you want to add, it should be in https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/nodeagent/values.yaml. And we have provided this file - https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values-istio-sds-auth.yaml for nodeagent case.

**Comment by rjshrjndrn** [comment]
My assumption was that ./values.yml is the generic file for istio and nodeagent/values.yml is for that specific chart. If we don't convolute that chart with istio specific values, which the above values are, that'll be good.

And if we have to have a seperate file for the nodeagent, I think removing the nodeagent section from values.yml makes more sense, as I see issues regarding nodeagent restarts.

**Review by rshriram — APPROVED** [review]

**Review by howardjohn — DISMISSED** [review]
changes should be in nodeagent values.yaml

Top level values.yaml should just be for `enabled` flags and global settings

**Comment by howardjohn** [comment]
> 
> My assumption was that ./values.yml is the generic file for istio and nodeagent/values.yml is for that specific chart. If we don't convolute that chart with istio specific values, which the above values are, that'll be good.
> 
> And if we have to have a seperate file for the nodeagent, I think removing the nodeagent section from values.yml makes more sense (which will make new people like me to enable that field and fall into the crash loop), as I see issues regarding nodeagent restarts.

That seems like a reasonable pattern, but its not how we have it structured right now. We generally just have the `enabled` fields in the top level one, and then the specific options in the subchart

See https://github.com/istio/istio/issues/16705 -- I think this basically fixes that issue if we move it to the nodeagent/values.yaml. Please let @JimmyCYJ or @pitlv2109 take a look though

Thanks!

**Comment by rjshrjndrn** [comment]
Hi @JimmyCYJ, friendly reminder.

**Comment by rjshrjndrn** [comment]
@howardjohn Made changes as per your guidelines. Please have a look

**Review by JimmyCYJ — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
