### PR TITLE
move to the latest kiali 1.13 release

### PR DESCRIPTION
**Pull request by jmazzitelli**
This updates Kiali to the latest version 1.13.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I do not understand the test failures - they do not look like anything that is related to the files changed in this PR.

**Comment by dgn** [comment]
> I do not understand the test failures - they do not look like anything that is related to the files changed in this PR.

Yes, they seem to be flakes. Don't worry about it

**Review by dgn — APPROVED** [review]

**Review by linsun — APPROVED** [review]

**Comment by jmazzitelli** [comment]
What's that definition of insanity again? :) 

/retest

**Review by elfinhe — APPROVED** [review]

**Comment by dgn** [comment]
> What's that definition of insanity again? :)
> 
> /retest

in this case it's 'rebase' ;) we had a line of broken yaml in master

**Comment by howardjohn** [comment]
the mixer test was broken by another pr and we made it required now so that won't happen again. retest should fix

**Pull request merged**
