### PR TITLE
WIP: making proxy resource override mutually exclusive

### PR DESCRIPTION
**Pull request by shriramsharma**
**Please provide a description of this PR:**
Fixes: #52693

### CODE REVIEW

**Comment by shriramsharma** [comment]
@keithmattix @howardjohn , can I get some initial review on this?
Please let me know if I'm missing something. Thanks

**Comment by howardjohn** [comment]
The commit has 0 lines changed I think?

**Comment by ilrudie** [comment]
Looks like `make gen` reverted your original changes

**Comment by shriramsharma** [comment]
@howardjohn @ilrudie , sorry I mistakenly reverted my changes. Can you please review? Thanks

**Comment by shriramsharma** [comment]
@howardjohn @keithmattix , whenever you get a chance, please review. Thanks

**Review by howardjohn — CHANGES_REQUESTED** [review]
Regardless of what is the most preferred behavior this seems like a breaking change. And it might make it impossible to unset a field?

**Comment by shriramsharma** [comment]
> Regardless of what is the most preferred behavior this seems like a breaking change. And it might make it impossible to unset a field?

@howardjohn I completely agree it is a breaking change but the current way of unsetting a field itself seems very unintuitive. If I need to unset memory then I'm forced to set CPU annotation.
Do you think adding a separate annotation for unsetting a specific field is an option?

**Comment by shriramsharma** [comment]
hey @howardjohn what do you recommend should be the path forward?

**Pull request closed without merging**
