### PR TITLE
Automated branching step 1

### PR DESCRIPTION
**Pull request by aryan16**

### CODE REVIEW

**Comment by hanxiaop** [comment]
@aryan16 I noticed you are merging commits from istio's `automatedBranchStep1` branch to istio's `master`. This can be done within your own Istio repo like normal Istio PRs. For example: https://github.com/istio/istio/pull/48617

**Comment by aryan16** [comment]
> @aryan16 I noticed you are merging commits from istio's `automatedBranchStep1` branch to istio's `master`. This can be done within your own Istio repo instead of creating a branch in Istio repo. For example: #48617

I tried the same thing before but somehow my branch is not getting pushed for some reason when I go with my own repo. I'll try it again, thanks!!

**Comment by ericvn** [comment]
Also noting that the commit is not with the GH id (why the EasyCLA fails), and instead a user name (no link provided). This has happened in the past and looking into that. I believe this is a local only issue as I fixed this before which broke the pipeline.

**Review by howardjohn — APPROVED** [review]

**Comment by hanxiaop** [comment]
> but somehow my branch is not getting pushed for some reason when I go with my own repo.

@aryan16 Did you get auth errors?

**Comment by ericvn** [comment]
I am able to get around the commit auth problem by making the following change locally. I've made this change before and merged it and then some of the pipeline jobs fail. We can just doc this in the issue if you find it works, or maybe add a check to see if this snippet is included (IIRC, there is a env var set in the pipeline). Note that I git clone with ssh and mount my .ssh into the directory and set GITHUB_TOKEN, `ADDITIONAL_CONDITIONAL_HOST_MOUNTS="--mount type=bind,source=${HOME}/.ssh,destination=/home/user/.ssh,readonly " GH_TOKEN=$GH_GITHUB_TOKEN make shell`. With the above, `gh auth status` shows me logged in.
```
git diff
diff --git a/example/manifest_branch.yaml b/example/manifest_branch.yaml
index 5ed53c2..c749125 100644
--- a/example/manifest_branch.yaml
+++ b/example/manifest_branch.yaml
@@ -1,6 +1,6 @@
 # Version specifies which version is being being branched
 # The new branch will be of the form release-${version}
-version: 1.19
+version: 1.21
 
 # We need to set the docker in the manifest so it can be used as HUB in
 # the release builder standard environment. HUB is required to be set for
diff --git a/pkg/util/git.go b/pkg/util/git.go
index 924d558..53a86e1 100644
--- a/pkg/util/git.go
+++ b/pkg/util/git.go
@@ -19,11 +19,9 @@ import (
        "fmt"
        "os"
        "strings"
-       "time"
 
        "github.com/go-git/go-git/v5"
        "github.com/go-git/go-git/v5/plumbing"
-       "github.com/go-git/go-git/v5/plumbing/object"
        "github.com/go-git/go-git/v5/plumbing/transport/http"
        "github.com/google/go-github/v35/github"
        "golang.org/x/oauth2"
@@ -87,11 +85,11 @@ func PushCommit(manifest model.Manifest, repo, branch, commitString string, dryr
                        user.Email = &emptyString
                }
                commit, err := w.Commit(commitString, &git.CommitOptions{
-                       Author: &object.Signature{
-                               Name:  *user.Name,
-                               Email: *user.Email,
-                               When:  time.Now(),
-                       },
+                       // Author: &object.Signature{
+                       //      Name:  *user.Name,
+                       //      Email: *user.Email,
+                       //      When:  time.Now(),
+                       // },
                })
                if err != nil {
                        return true, fmt.Errorf("failed to create commit: %v", err)
@@ -99,9 +97,10 @@ func PushCommit(manifest model.Manifest, repo, branch, commitString string, dryr
                log.Infof("commit created:\n%v", commit)
 
                // Push to the upstream repo.
+               log.Infof("Username: %s   Password: %s   name: %s\n", *user.Login, githubToken, *user.Name)
                err = r.Push(&git.PushOptions{
                        Auth: &http.BasicAuth{
-                               Username: *user.Name, // yes, this can be anything except an empty string
+                               Username: *user.Login, // yes, this can be anything except an empty string
                                Password: githubToken,
                        },
                })
lines 47-57/57 (END)
```

**Pull request closed without merging**
