### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by plallin**
This PR is simply fixing a typo I noticed while working. I don't think tests are necessary.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

```

release-note
NONE

```

### CODE REVIEW

**Comment by plallin** [comment]
@googlebot I signed it!

**Review by morvencao — APPROVED** [review]

**Review by morvencao — COMMENTED** [review]
/ok-to-test

**Comment by plallin** [comment]
@morvencao How do I add the `release-note-none` label?

**Pull request merged**
