### PR TITLE
Only use gateways for servers being processed

### LINKED ISSUE #10313: VirtualService applies rule to wrong Gateway
**Describe the bug**
According to https://istio.io/docs/tasks/traffic-management/ingress/#configuring-ingress-using-an-istio-gateway, a VirtualService only applies its rules to the Gateways specified in the `gateways` field; however, my VirtualService applies to all the Gateways in the same namespace. For example, I created the following 3 Gateways(listen port 80, 81 and 82):
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: case-d-gateway-1
  namespace: chenxma
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
        number: 80
        name: http
        protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: case-d-gateway-2
  namespace: chenxma
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
        number: 81
        name: http
        protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: case-d-gateway-3
  namespace: chenxma
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
        number: 82
        name: http
        protocol: HTTP
    hosts:
    - "*"
---
```
and 3 VirtualServices apply to the above Gateways respectively:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: case-d-virtualservice-1
  namespace: chenxma
spec:
  hosts:
  - "*"
  gateways:
  - case-d-gateway-1
  http:
  - match:
    - uri:
        prefix: /fortio1/
    route:
    - destination:
        port:
          number: 80
        host: fortio-svc-1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: case-d-virtualservice-2
  namespace: chenxma
spec:
  hosts:
  - "*"
  gateways:
  - case-d-gateway-2
  http:
  - match:
    - uri:
        prefix: /fortio2/
    route:
    - destination:
        port:
          number: 80
        host: fortio-svc-1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: case-d-virtualservice-3
  namespace: chenxma
spec:
  hosts:
  - "*"
  gateways:
  - case-d-gateway-3
  http:
  - match:
    - uri:
        prefix: /fortio3/
    route:
    - destination:
        port:
          number: 80
        host: fortio-svc-1
```
and now if do:
```
curl <gateway_svc_ip>:80/fortio1/
curl <gateway_svc_ip>:81/fortio2/
curl <gateway_svc_ip>:82/fortio3/
```
I will get 200 return codes as expected.

But soon I found the following cases also return 200:
```
curl <ingressgateway_svc_ip>:80/fortio2/
curl <ingressgateway_svc_ip>:80/fortio3/
curl <ingressgateway_svc_ip>:81/fortio1/
curl <ingressgateway_svc_ip>:81/fortio3/
curl <ingressgateway_svc_ip>:82/fortio1/
curl <ingressgateway_svc_ip>:82/fortio2/
```
which I think is not expected according to Istio docs.
So I get into my Ingressgateway pod and dump the routing configs:
```
{
   "@type": "type.googleapis.com/envoy.admin.v2alpha.RoutesConfigDump",
   "dynamic_route_configs": [
    {
     "version_info": "2018-12-06T08:02:17Z",
     "route_config": {
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "*:80",
        "domains": [
         "*",
         "*:80"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/fortio1/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio1/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            }
           }
          }
         },
         {
          "match": {
           "prefix": "/fortio3/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio3/*"
          },
          "per_filter_config": {
           "mixer": {
            "mixer_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "forward_attributes": {
             "attributes": {
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              }
             }
            }
           }
          }
         },
         {
          "match": {
           "prefix": "/fortio2/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio2/*"
          },
          "per_filter_config": {
           "mixer": {
            "mixer_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "forward_attributes": {
             "attributes": {
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            }
           }
          }
         }
        ]
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2018-12-06T08:02:44.814Z"
    },
    {
     "version_info": "2018-12-06T08:02:17Z",
     "route_config": {
      "name": "http.82",
      "virtual_hosts": [
       {
        "name": "*:82",
        "domains": [
         "*",
         "*:82"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/fortio1/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio1/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              }
             }
            }
           }
          }
         },
         {
          "match": {
           "prefix": "/fortio3/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio3/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            }
           }
          }
         },
         {
          "match": {
           "prefix": "/fortio2/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio2/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            }
           }
          }
         }
        ]
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2018-12-06T08:02:44.814Z"
    },
    {
     "version_info": "2018-12-06T08:02:17Z",
     "route_config": {
      "name": "http.81",
      "virtual_hosts": [
       {
        "name": "*:81",
        "domains": [
         "*",
         "*:81"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/fortio1/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio1/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            }
           }
          }
         },
         {
          "match": {
           "prefix": "/fortio3/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio3/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            }
           }
          }
         },
         {
          "match": {
           "prefix": "/fortio2/"
          },
          "route": {
           "cluster": "outbound|80||fortio-svc-1.chenxma.svc.cluster.local",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "fortio-svc-1.chenxma.svc.cluster.local:80/fortio2/*"
          },
          "per_filter_config": {
           "mixer": {
            "forward_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              }
             }
            },
            "mixer_attributes": {
             "attributes": {
              "destination.service.namespace": {
               "string_value": "chenxma"
              },
              "destination.service.name": {
               "string_value": "fortio-svc-1"
              },
              "destination.service": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.host": {
               "string_value": "fortio-svc-1.chenxma.svc.cluster.local"
              },
              "destination.service.uid": {
               "string_value": "istio://chenxma/services/fortio-svc-1"
              }
             }
            }
           }
          }
         }
        ]
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2018-12-06T08:02:44.814Z"
    }
   ]
  }
```
Note for each `route_config`, all the three VirtualServices rules(i.e. prefix `/fortio1/`, `/fortio2/` and `/fortio3/`) have been included. 
**Expected behavior**
With my VirtualService and Gateway setup, the following requests should return 404:
```
curl <ingressgateway_svc_ip>:80/fortio2/
curl <ingressgateway_svc_ip>:80/fortio3/
curl <ingressgateway_svc_ip>:81/fortio1/
curl <ingressgateway_svc_ip>:81/fortio3/
curl <ingressgateway_svc_ip>:82/fortio1/
curl <ingressgateway_svc_ip>:82/fortio2/
```

**Steps to reproduce the bug**
described above

**Version**
Kubernetes: 
```
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-413+a6fbb4730262ed-dirty-dirty", GitCommit:"a6fbb4730262ed86a30aa1543631784f67be6692", GitTreeState:"dirty", BuildDate:"2018-12-05T10:14:34Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Istio: 1.0.2

**Installation**
manually installed via `istio-demo.yaml` with mesh disabled

**Environment**
CentOS Linux release 7.5.1804 (Core)

**Cluster state**
N/A

### PR DESCRIPTION
**Pull request by rshriram**
fixes #10313 
Signed-off-by: Shriram Rajagopalan <rshriram@gmail.com>

### CODE REVIEW

**Comment by rshriram** [comment]
@mbanikazemi can you please test with this patch?

**Comment by frankbu** [comment]
Seems like there are several open issues related to this problem.

#10313 
#12336 
#12603 

@rshriram, I think this will fix all of them, right?

**Comment by rshriram** [comment]
oh sheesh, yes. this should fix all of them

**Comment by rshriram** [comment]
cc @arnecls as well

**Comment by mbanikazemi** [comment]
@rshriram Tested with this patch. The routes gets populated *correctly* in my test with this patch.

**Comment by haf** [comment]
No unit tests?

**Pull request merged**
