### PR TITLE
fix release script

### PR DESCRIPTION
**Pull request by mandarjog**
Fix options processing release script so that it correctly processes destination directory.

### CODE REVIEW

**Comment by mandarjog** [comment]
https://github.com/istio/istio/pull/4642#discussion_r179337708 This is what broke it earlier.
Testing was done before that last change.

**Comment by mandarjog** [comment]
@hklai we need to create 0.7.2 so that it includes the correct artifacts.

**Comment by mandarjog** [comment]
At present the the istio archive is not packaging artifacts that are created with helm.

**Comment by mandarjog** [comment]
The target directory now has the newly generated files that include the mixer split.

```
mjog@devinstance:/mnt/disks/sdb/go/out/linux_amd64/release/archive/install/kubernetes$ grep istio-policy istio.yaml
        regex: istio-system;istio-policy;http-monitoring
    mixerCheckServer: istio-policy.istio-system:15004
  name: istio-policy
  name: istio-policy
        - istio-policy
```

**Comment by hklai** [comment]
@mandarjog as mentioned earlier, there is no plan for 0.7.2.  if there is any workaround, please add it to release notes.

Also please add some test case to cover this fix.

**Comment by ldemailly** [comment]
0.7.1 works for me

I don't understand how come the 0.8 daily failed basic reg patrol yet passed tests ? Are we not qualifying the nightly artifacts ? Only the monthlies ?

**Comment by mandarjog** [comment]
I don;t think we are qualifying nightly build archives. regpatrol is the qualifier.

**Comment by ldemailly** [comment]
no daily today ? is it related ? @hklai @rkpagadala what happened ? 

also can you edit https://github.com/istio/istio/wiki/Daily-builds to add some link/info on where to check status of why there isn't a new build so it can be more self service ?

**Pull request merged**
