### PR TITLE
Set readOnlyRootFilesystem to true for istio-init with Istio CNI is enabled

### LINKED ISSUE #22695: cni enabled: InitContainer fails pod security policy with readOnlyRootFilesystem=false
**Bug description**
Fresh install of kubernetes on GKE with pod security policies enabled. Installed Istio 1.5.1 with cni enabled as per instructions (including platform setup firewall change):-

istioctl manifest apply --set values.cni.cniBinDir=/home/kubernetes/bin \
    --set components.cni.enabled=true \
    --set components.cni.namespace=kube-system

My pod security policy for app pods has restriction of readOnlyRootFilesystem=true.

Deployed app fails to start with..

pods "load-68b699c7bb-" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.readOnlyRootFilesystem: Invalid value: false: ReadOnlyRootFilesystem must be set to true]

On face of it, looks like istio-validation initcontainer has readOnlyRootFilesystem: false.

**Expected behavior**

With cni enabled, I expected the initcontainer not to require elevated permissions.

**Steps to reproduce the bug**

See above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl...

client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)

kubectl...

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl 1.5.1 on Windows 10 in powershell window. Also tried in GKE CloudShell.

**Environment where bug was observed (cloud vendor, OS, etc)**

Client: Windows 10 and GKE CloudShell. against GKE

### PR DESCRIPTION
**Pull request by rlenglet**
When Istio CNI is enabled, the `istio-init` container is injected. Set `readOnlyRootFilesystem: true` in this case, since the container only checks that `iptables` redirection is setup and doesn't need to write to the filesystem. This allows using PodSecurityPolicies that forbid writable filesystems.

Fixes: https://github.com/istio/istio/issues/22695

### CODE REVIEW

**Review by lambdai — APPROVED** [review]
This is awesome! 
Thank you!

**Comment by rlenglet** [comment]
@istio/wg-environments-maintainers please review.

**Review by howardjohn — APPROVED** [review]
do we need wrote access for non cni?

**Comment by rlenglet** [comment]
> do we need wrote access for non cni?

I don't know, which is why I've been conservative here.
Anyway, running as UID 0 is a bigger problem in this case.

**Pull request merged**
