### PR TITLE
lint fixing.

### PR DESCRIPTION
**Pull request by incfly**
run bin/fmt.sh and check in all changes.

### CODE REVIEW

**Comment by irisdingbj** [comment]
The galley codes have already passed lint testing , so not sure what error you want to address for this PR.

**Comment by ozevren** [comment]
AFAIK, there is a problem with the linter @hklai 
The lint job is made optional now. It is probably worth syncing with test&release folks to ensure that any fix to this problem is coordinated.

**Comment by incfly** [comment]
@ozevren @irisdingbj Got it. (I run into this for my own PR where lint failed on unchanged files...) Thanks. Sorry about the spamming. I'll sync with testing team.

**Comment by hklai** [comment]
It is apparently due to https://github.com/golang/go/issues/28200.

One thing we can possibly do is to build our own goimport/linter using a
known good version in our own circle base image. It should remove the
changing external dependencies.

**Comment by ozevren** [comment]
@hklai https://github.com/istio/istio/issues/7395

**Pull request closed without merging**
