### PR TITLE
Fix alt-host generation when hostname has a partial overlap with cluster domain

### PR DESCRIPTION
**Pull request by howardjohn**
For example, a service `foo.bar.local` behaves incorrectly because we
incorrectly match the `.local` up with `.cluster.local`

Fixes https://github.com/istio/istio/issues/35676

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by howardjohn** [comment]
This is currently only fixed in 1.13.0+

**Comment by fams** [comment]
Yes, I saw this. My question is: Do you guys have plans to fix this issue in 1.11.X? This release is still in maintenance, I think.

**Pull request merged**
