### PR TITLE
Helm chart: Respect custom proxy_init image value for enable-core-dump container

### PR DESCRIPTION
**Pull request by ewbankkit**
Fixes https://github.com/istio/istio/issues/7857.
Used the same logic as for the `istio-init` container.

### CODE REVIEW

**Comment by ewbankkit** [comment]
Rebased.

**Comment by sdake** [comment]
I kicked off circleci tests.  You may need to rebase.  circleci needs a rebase in some conditions to pull in fixed tests and code.

**Comment by ewbankkit** [comment]
Rebased. Fingers crossed...

**Pull request merged**
