### PR TITLE
Update Jaeger version to 1.14

### PR DESCRIPTION
**Pull request by objectiser**
Please provide a description for what this PR is for.

This PR updates the Jaeger version to 1.14 and changes the prometheus metrics and readiness probe port to use the admin endpoint.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by objectiser** [comment]
cc @clyang82

**Review by douglas-reid — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
Regarding the lint error, we do this confusing thing where we rebase your
PR with latest changes in HEAD and then run the tests. So if its failing
here but passes locally you may need to rebase

**Comment by goruha** [comment]
@howardjohn @objectiser 
When the changes would be released?
I see the old helm chart in [1.3.2](https://github.com/istio/istio/releases/tag/1.3.2) release
https://storage.googleapis.com/istio-release/releases/1.3.2/charts/istio-1.3.2.tgz

**Comment by howardjohn** [comment]
This will be in 1.4.0 shipping next month https://github.com/istio/istio/wiki/Istio-Release-1.4

**Comment by goruha** [comment]
@howardjohn is there any chance to release it as quick-fix to `1.3.x`?

**Comment by smeena667** [comment]
@howardjohn 
Agree with @goruha . All `1.3.x` releases are broken. Can we have a patch in `1.3.x` please?

**Comment by howardjohn** [comment]
Already done on 1.3: https://github.com/istio/istio/pull/18274

**Pull request merged**
