### PR TITLE
Allow setting lifecycle to proxy containers

### PR DESCRIPTION
**Pull request by k0da**
Signed-off-by: Dinar Valeev <k0da@opensuse.org>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by k0da** [comment]
ok to test

**Comment by k0da** [comment]
activity

**Comment by k0da** [comment]
@googlebot I signed it!

**Comment by k0da** [comment]
activity

**Comment by k0da** [comment]
activity

**Review by howardjohn — APPROVED** [review]
Can you add submit this for https://github.com/istio/installer? or let me know if not. The new istioctl/operator install is based on that and is the new default install method

**Comment by k0da** [comment]
@howardjohn I'll take a look at installer

**Pull request merged**
