### PR TITLE
remove all bazel-genfiles for every presubmit build

### LINKED ISSUE #1689: presubmit can fail randomly for nonexistent autogen files
from https://github.com/istio/istio/pull/1672:

the presubmit fails with missing `mixer/template/authz` files, but those files do not exist on master, on the base branch, nor on the PR. We need to figure out the solution.

cc: @mandarjog @yutongz

### PR DESCRIPTION
**Pull request by jmuk**
Fixes #1689, all of the genfiles artifacts should be cleaned up.
This can decrease the continuous build performance, although
I hope the effect is tiny -- running codegen tools, recompiling
some files, and re-linking the result (but most of the cases
re-linking would happen anyways).

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1689

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by jmuk** [comment]
@yutongz can you check the performance effect on this PR?  This should fix the problem, but the effect can be small, since it just removes the autogen files only. If the performance is okay, I think this solves the problem.

**Comment by yutongz** [comment]
Thanks, I will keep an eye on that.

**Comment by yutongz** [comment]
First run failed with the same issue we had last friday and second run failed on auto-generated files.

**Comment by nlandolfi** [comment]
Yeah, as Yutong said it looks like most recent failed on autogenerated files. could these have diverged back when the check was removed?

**Comment by jmuk** [comment]
Very weird, I have no idea how and where those `mixer/template/authz` come from, since this does not happen locally and no one is referring it. Let me look into the details.

**Comment by yutongz** [comment]
/test istio-presubmit

I clean the Prow cache, let try it again.

**Comment by yutongz** [comment]
There is something wrong in master breaking presubmit for now.

**Comment by jmuk** [comment]
this is not necessary anymore, closing.

**Pull request closed without merging**
