### PR TITLE
Add its own service account for httpbin

### PR DESCRIPTION
**Pull request by pitlv2109**

### CODE REVIEW

**Comment by howardjohn** [comment]
>I think it's easier to control httpbin identity (e.g. if one needs to delete its secret to get a new secret; Citadel doens't generate new certificate for service account if the root cert didn't change). Otherwise, httpbin will use the default service account, which can be used by anything.

Unless we have a specific use case (task in the docs, etc), should we just keep the samples as minimal as possible? Otherwise it is just more the user needs to understand

**Comment by yangminzhu** [comment]
> > Why do we need service account for httpbin?
> 
> I don't see why not? I think it's easier to control httpbin identity (e.g. if one needs to delete its secret to get a new secret; Citadel doens't generate new certificate for service account if the root cert didn't change). Otherwise, httpbin will use the default service account, which can be used by anything.

I'm asking is this needed for any specific change that is depending on it, like are you adding some test or docs that needs httpbin to have the service account?

**Comment by pitlv2109** [comment]
Sorry! This is needed for an upcoming task about trust domain migration. We can get away with it because httpbin can use the default service account, but I thought making it using its own service account could make the task more clear.

**Comment by yangminzhu** [comment]
> Sorry! This is needed for an upcoming task about trust domain migration. We can get away with it because httpbin can use the default service account, but I thought making it using its own service account could make the task more clear.

Okay if this is needed in the upcoming task. For the change, I think you also need to update the `httpbin` deployment to use the service account.

**Comment by pitlv2109** [comment]
> > Sorry! This is needed for an upcoming task about trust domain migration. We can get away with it because httpbin can use the default service account, but I thought making it using its own service account could make the task more clear.
> 
> Okay if this is needed in the upcoming task. For the change, I think you also need to update the `httpbin` deployment to use the service account.

Good catch. Thanks!

**Comment by howardjohn** [comment]
@istio/wg-docs-maintainers

**Comment by pitlv2109** [comment]
@geeknoid @frankbu @sdake Could any of you guys take a look?

**Pull request merged**
