### PR TITLE
manual cherry pick of 3b58e4c5e #25588

### PR DESCRIPTION
**Pull request by GregHanson**
Please provide a description for what this PR is for.

manual cherry pick of #25588
resolves: https://github.com/istio/istio/issues/25749

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nschhina** [comment]
not sure what this pilot failure is cc: @howardjohn

**Comment by howardjohn** [comment]
Looks like CNI wont install. Not sure why, seems like we aren't getting info on CNI logs either...

**Comment by howardjohn** [comment]
I think its failing across PRs

**Pull request merged**
