### PR TITLE
feat:istioctl x add-to-mesh and remove-from-mesh Should not affect OwnerReferences

### PR DESCRIPTION
**Pull request by tanjunchen**
[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by morvencao — APPROVED** [review]

**Review by morvencao — COMMENTED** [review]
cherrypick to 1.6 and 1.7?

**Comment by tanjunchen** [comment]
> cherrypick to 1.6 and 1.7?

I think it is ok.

**Review by shamsher31 — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
