### PR TITLE
Fix tear down of envoy on exit

### PR DESCRIPTION
**Pull request by holgero**
Defered funcs won't be called when os.Exit() is invoked in the
same method.

### CODE REVIEW

**Comment by andraxylia** [comment]
good find!

**Comment by andraxylia** [comment]
@costinm TestMain will run all tests, the change is correct

**Comment by loewenstein** [comment]
@costinm I second what @andraxylia said. This should 'just' fix a hanging process and lead to exactly the behaviour that you describe.

**Comment by holgero** [comment]
@costinm : The envoy is only used in `xds_test.go`, namely in `TestEnvoy`. No other test in the package calls `startEnvoy`, they only call `initLocalPilotTestEnv`.  Also it looks to me as if the tests done with this envoy instance are done in subtests of `TestEnvoy` only and called there explicitly.

To preserve the original intention, we can also do the change like this:
```go
func TestMain(m *testing.M) {
	result := m.Run()
	// tear down cannot be done in a deferred function, because we call os.Exit() at the end
	testEnv.TearDown()
	os.Exit(result)
}
```

Would this be preferred?

**Pull request merged**
