### PR TITLE
bookinfo fixes

### LINKED ISSUE #7047: The "jason" example is quite misleading
[This example](https://istio.io/docs/tasks/traffic-management/request-routing/) shows routing decisions made on the basis of what user is logged in. Most users accessing the bookinfo app see reviews from reviews:v1, while authenticated user "jason" sees reviews from reviews:v2.

I know what is _really_ being demonstrated here is the ability to route traffic based on headers. Cookies, like the `user` cookie, after all, are sent from client to server in an HTTP request header.

_However_, most readers probably walk away from this example with a different takeaway-- "Istio lets me route different users to different endpoints." This is obviously a valuable idea. Imagine that during a blue/green deployment, for instance, you might want your product owner to get into the new version first to do some UAT before you start using weights to shift traffic from everyone else over.

The problem is that this notion of "Istio lets me route different users to different endpoints" doesn't hold up in the real world.

The bookinfo app is a toy. The current user's username is stored in plain text in a cookie that can be edited, allowing an attacker to assume the identity of another user. Apps in the real world do not work this way. Any cookie that plays a role in user identity / session is either going to be encrypted or might even be an opaque token that is correlated to identity or session on the server side. Obviously, this is to prevent identity / session hijacking.

My point is only that the "jason" example sets readers up with a false notion that Istio can be used in this desirable way in the real world, when really, it cannot. Is there, perhaps, a less misleading demonstration of routing requests based on a header that could replace this example?

### PR DESCRIPTION
**Pull request by krancour**
Fixes #7047 

Important: requires #7098 to be merged first since that make some critical fixes to the bookinfo sample app's build process, which fails in its current state.

This PR corrects unrealistic behavior in the sample app.

Currently, the productpage app stores user identity in a cookie that is neither encrypted nor signed. It is easily tampered with by even the most novice attacker. Additionally, the productpage app _forwards_ that same cookie to the downstream reviews service. This is also bad. Both of these, however, were obviously done to facilitate an impactful demo that shows request routing decisions being done on the basis of user identity.

This PR transforms the example to use more realistic behavior without compromising on the demo's impact. The cookie is now encoded and digitally signed (the flask framework automatically encodes any session data that is kept in a cookie-based session store). It can be decoded, but tampering with it (successfully) is not possible due to the signature. The productinfo page also ceases to share this cookie with the downstream review service. Instead, it injects the end-user's username into a custom `end-user` header on the outbound requests to the reviews service. The end result is that there is _still_ a plain text header present that routing decisions can be based on, but from start to finish, we didn't have to compromise on security to make that possible.

All sample routing rules (used by tasks in the documentation) are also updated by this PR.

Note that the images referenced in the various `yaml` files do not exist yet in dockerhub because I don't have permissions to push them and, as far as I can tell, there isn't any _automated_ build/push process for those. So someone else needs to build and push these, I guess?

Will open a complementary PR in the docs repo momentarily.

### CODE REVIEW

**Comment by rshriram** [comment]
@krancour Thanks for this PR. Can you push the changes to your dockerhub account and update the bookinfo YAMLs to point to your version ? Once they pass,  I can copy and push them into istio's official docker hub and update the YAML references in a separate PR

**Comment by rshriram** [comment]
Also, please rebase the PR to release-1.0 branch

**Comment by krancour** [comment]
@rshriram sure thing. Will wait for #7152 to be merged first.

**Comment by rshriram** [comment]
I have merged the other PR. Please rebase this to release-1.0 branch

**Comment by krancour** [comment]
@rshriram working on it. Seems I did break the e2e tests, so I am trying to resolve that before continuing.

**Comment by rshriram** [comment]
You have to close this PR and open a new PR for release-1.0 branch.. changing the target branch in Github doesn't seem to work properly (if thats what you did).

**Comment by krancour** [comment]
> changing the target branch in Github doesn't seem to work properly (if thats what you did).

I changed the target branch, but didn't push anything that I have rebased yet. That's why this looks all screwy.

I'll have this all fixed up as soon as I get those e2e tests fixed.

**Comment by rshriram** [comment]
@krancour please debug fro release-1.0 branch. Lots of fixes went in. Master may be very much outdated.

**Comment by krancour** [comment]
@rshriram updating e2e tests took me a little while, but I think this should be g2g now. lmk

**Comment by rshriram** [comment]
Please fix lint..
Also, I am unable to build the reviews image
```
~/go/src/istio.io/istio/samples/bookinfo/src/reviews ~/go/src/istio.io/istio/samples/bookinfo
src/build-services.sh: line 42: PWD: command not found
Unable to find image 'gradle:4.8.1' locally
4.8.1: Pulling from library/gradle
55cbf04beb70: Already exists 
1607093a898c: Pull complete 
9a8ea045c926: Pull complete 
d4eee24d4dac: Pull complete 
c58988e753d7: Pull complete 
794a04897db9: Pull complete 
70fcfa476f73: Pull complete 
0539c80a02be: Pull complete 
54fefc6dcf80: Pull complete 
facf6a71baf4: Pull complete 
38ca283ac663: Pull complete 
Digest: sha256:2963e0798bf2c32630485a0ef8000ca17fd220be1ebacbdeb880ca29e97fbf88
Status: Downloaded newer image for gradle:4.8.1

Welcome to Gradle 4.8.1!

Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time

For more details see https://docs.gradle.org/4.8.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by krancour** [comment]
@rshriram your issue with building reviews images seems to have been introduced by a recent PR other than my own:

https://github.com/krancour/istio/commit/b0a1c95b19310eefc92b99967959f365b6285101#diff-030573cbbec06dc83bf87af67b0ae74eL42

I'm happy to fix this, however.

Ack on lint error.

**Comment by rshriram** [comment]
I see this in release-1.0 branch
```
pushd $SCRIPTDIR/reviews
  #java build the app.
  docker run --rm -v $(PWD):/home/gradle/project -w /home/gradle/project gradle:4.8.1 gradle clean build
  pushd reviews-wlpcfg
    #plain build -- no ratings
    docker build -t istio/examples-bookinfo-reviews-v1:${VERSION} -t istio/examples-bookinfo-reviews-v1:latest --build-arg service_version=v1 .
    #with ratings black stars
    docker build -t istio/examples-bookinfo-reviews-v2:${VERSION} -t istio/examples-bookinfo-reviews-v2:latest --build-arg service_version=v2 \
           --build-arg enable_ratings=true .
    #with ratings red stars
    docker build -t istio/examples-bookinfo-reviews-v3:${VERSION} -t istio/examples-bookinfo-reviews-v3:latest --build-arg service_version=v3 \
           --build-arg enable_ratings=true --build-arg star_color=red .
  popd
popd
```

**Comment by rshriram** [comment]
which came from your prior PR https://github.com/istio/istio/blob/release-1.0/samples/bookinfo/src/build-services.sh#L42 ?

**Comment by krancour** [comment]
@rshriram I changed that line, yes, but the problem you are facing (pwd related) came from #6988

**Comment by krancour** [comment]
Also, `make lint` passed for me. It's not clear to me why that stage failed in the CI pipeline.

**Comment by krancour** [comment]
@rshriram thanks for the help with this!

**Comment by krancour** [comment]
@rshriram just a reminder that official Docker images still need to be published and references to my dockerhub repos need to be corrected in a follow-up. If you publish the updated images, I'd be happy to submit that follow-up.

**Pull request merged**
