### PR TITLE
[release-1.10] Backport destination rule does not trigger LDS 1.10 

### PR DESCRIPTION
**Pull request by EItanya**
**Please provide a description of this PR:**

fixes https://github.com/istio/istio/issues/34970

### CODE REVIEW

**Comment by EItanya** [comment]
@googlebot I consent.

**Comment by linsun** [comment]
@stevenctl can you make google bot happy?  may need you to consent too.

**Review by Monkeyanator — APPROVED** [review]

**Comment by linsun** [comment]
not sure why the release-notes test failed, the release note is already in the PR.

**Comment by Monkeyanator** [comment]
> not sure why the release-notes test failed, the release note is already in the PR.

we're having trouble with release notes tooling in this branch, although I thought the fix (updating `gh` dep) was put through yesterday

**Comment by linsun** [comment]
ah thanks @Monkeyanator!

**Pull request merged**
