### PR TITLE
update proxy SHA for websocket fix

### PR DESCRIPTION
**Pull request by rshriram**
Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@rshriram Looks like this already contains the memory leaking / CPU spinning code.

**Comment by kyessenov** [comment]
@rshriram @PiotrSikora can you guys please test locally before merging to proxy? You don't need to block proxy every time you want to update the SHA.

**Comment by rshriram** [comment]
The memory leak is present even before this SHA.

**Comment by rshriram** [comment]
The memory consumption of Envoy (before running any test) is 300M (even without this PR).

**Pull request closed without merging**
