### PR TITLE
Trim Go dependencies

### PR DESCRIPTION
**Pull request by howardjohn**
* New docker/cli version lets us drop docker/docker. Update it
* mcs-api has not had a release in many years so pulling in ancient versions. Update to `master`.
* `godebug` used only for testing operator. No need, we have the same functionality already. Replace it, and move the test util to a test package so it is not imported in the final binary.
* `kr/pretty` is pulled in to format a single go struct. No need, `%#v` is sufficient
* Minor drop of go-homedir (code is used only in tests anyways)

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]
Will this reduce the binary size for istiod?

**Comment by howardjohn** [comment]
> Will this reduce the binary size for istiod?

technically yes but only 4kb so effectively not relevant from a binary size perspective

**Comment by howardjohn** [comment]
The goal was fewer deps (for CVE management, etc) not binary size here

**Review by costinm — APPROVED** [review]
Great change !

**Pull request merged**
