### PR TITLE
Replace the logging time formatter with a much faster version.

### PR DESCRIPTION
**Pull request by geeknoid**
Execution time went from ~340ns to ~85ns. We also now log to microsecond precision instead of merely milliseconds.

### CODE REVIEW

**Comment by wora** [comment]
The Go format matches proto3 format. Since most Envoy and Istio specs are
using proto3, I think we should stuck with it. Istio will support millions
of services. Anything we decide will have broader impact. Let's stay with
existing spec for global consistency.

Z suffix means UTC. We cannot omit it. Without suffix means local time.

**Comment by geeknoid** [comment]
Do you have a pointer to the text format recognized by the proto3 parsers?
I'm happy to stick with a well-known format, although I'd like to include
at least microseconds in the output which the zap logger didn't do by
default.

**Comment by wora** [comment]
Google search proto3 should point to the spec. Or the proto file itself.

**Comment by geeknoid** [comment]
This now outputs the same ISO8601 format than we did before, except with microsecond precision instead of just millisecond. And perf is still ~4x compared to the original code.

**Pull request merged**
