### PR TITLE
break loop if collection and peerAddr exists

### PR DESCRIPTION
**Pull request by ChangyuWang**
break outer loop if collection and peerAddr found in StatusInfo

### CODE REVIEW

**Comment by howardjohn** [comment]
Can you provide a description of what this fixes and/or tests to ensure we don't have a regression

**Comment by ChangyuWang** [comment]
@howardjohn  TestCreateWatch has covered it.

**Comment by howardjohn** [comment]
There should be a test that fails before the PR and passes with the changes in the PR

**Pull request merged**
