### PR TITLE
Pull in fix for https://github.com/istio/istio/issues/14707.

### PR DESCRIPTION
**Pull request by duderino**

### CODE REVIEW

**Comment by fpesce** [comment]
@duderino do you have a master change for this?

**Comment by duderino** [comment]
@fpesce and I realized that the istio/proxy shas are different for each branch :)

**Comment by duderino** [comment]
circle ci galley failure:

```
2019-06-14T22:42:38.035759Z	error	Failed to delete namespace istio-system after 180 seconds
```

**Comment by duderino** [comment]
prow/istio-unit-tests.sh failure:

```
pod_test.go:63: failed creating test service account: etcdserver: request timed out
```

**Pull request merged**
