### PR TITLE
exclude unsafe 503 from default RetryPolicy

### LINKED ISSUE #50506: Add feature flag to disable default retry policy
There is default retry policy hard coded which will retry twice on connection issue or 503 introduced by https://github.com/istio/istio/pull/10566:
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/route/retry/retry.go#L34-L48
```
func DefaultPolicy() *route.RetryPolicy {
	policy := route.RetryPolicy{
		NumRetries:           &wrappers.UInt32Value{Value: 2},
		RetryOn:              "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
		RetriableStatusCodes: []uint32{http.StatusServiceUnavailable},
		RetryHostPredicate: []*route.RetryPolicy_RetryHostPredicate{
			// to configure retries to prefer hosts that haven’t been attempted already,
			// the builtin `envoy.retry_host_predicates.previous_hosts` predicate can be used.
			xdsfilters.RetryPreviousHosts,
		},
		// TODO: allow this to be configured via API.
		HostSelectionRetryMaxAttempts: 5,
	}
	return &policy
}
```

In our production environment we have thousands of VirtualServices created without retry policy which means it's using the default. 

For most cases we don't see issue but we are seesing problems with idempotent POST request retry and some POST requests are actually payout, which eventually caused double payout issue.

Here is one case we got for the double pay due to retry:

```
IngressGateway access log
2024-04-14 08:31:51.000 
bytes_received=85 bytes_sent=0 configId= duration=0 filename=accesslog method=POST path=/create_repayments protocol=HTTP/1.1 response_code=0 response_code_details=downstream_remote_disconnect response_flags=DC start_time=2024-04-14T00:31:51.244Z 

Sidecar access log
2024-04-14 08:31:52.000 
bytes_received=85 bytes_sent=0 configId= duration=0 filename=accesslog method=POST path=/create_repayments protocol=HTTP/1.1 response_code=0 response_code_details=downstream_remote_disconnect response_flags=DC route_name=default start_time=2024-04-14T00:31:51.244Z 
```

So we want to disable the default retry and instead one by one by setting the VirtualService retry num to 0, it could be better to have a feature flag globally. 

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

### PR DESCRIPTION
**Pull request by ramaraochavali**
Fixes https://github.com/istio/istio/issues/50506

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I think we could not simply change a setting there for more than five years . The right way is to propose discussion swithin the TOC meeting.

**Comment by ramaraochavali** [comment]
@howardjohn WDYT? If you think it should go to TOC, can you please help with brining this in TOC?

**Comment by howardjohn** [comment]
We discussed this in the WG meeting today. There was a general consensus that this change is a better default, with the risks largely being from changing the default which is mitigated by compatibility versions. 

WDYT @hzxuzhonghu @ramaraochavali

**Comment by hzxuzhonghu** [comment]
I am afraid issued fixed by https://github.com/istio/istio/pull/10566 will occur, 

https://github.com/istio/istio/issues/7665
https://github.com/istio/istio/issues/9113

**Comment by ramaraochavali** [comment]
> I am afraid issued fixed by https://github.com/istio/istio/pull/10566 will occur,

https://github.com/istio/istio/issues/7665
https://github.com/istio/istio/issues/9113

I do not think retries is a safe solution for 503s coming because of scale down. We have to enable proper draining behaviour (which we mostly do).

**Comment by ramaraochavali** [comment]
> We discussed this in the WG meeting today. There was a general consensus that this change is a better default, with the risks largely being from changing the default which is mitigated by compatibility versions.

+1 for this. Safety on "retry on 503" is not some thing that we can decide. It has to be decided by application and can configure it if it is safe. I would actually treat this as a bug.

**Comment by ramaraochavali** [comment]
@howardjohn @hzxuzhonghu how do we move forward with this?

**Comment by hzxuzhonghu** [comment]
Whatever even it is not very right, at least it is being relied for years.  i donot want to break existing users rely on this to handle case like `scale down`.  

We donot want to see 503 error reported again and again. 


I would agree with this if the scaling down 503 can be overcome

**Comment by ramaraochavali** [comment]
> Whatever even it is not very right, at least it is being relied for years. i donot want to break existing users rely on this to handle case like scale down.

It does not break them immediately. They have to adjust the retry policy if 503 is safe to them. Otherwise users unknowingly retry non idempotent requests which is a big problem compared to scale down 503.  They may not be realizing it. There are options to solve scale down 503s

**Comment by howardjohn** [comment]
FWIW it is also a 1 line tweak to mesh config to add this back where desired.

**Comment by hzxuzhonghu** [comment]
All the comments make sense. However It is indeed a behavior change, turned on by default. We donot need to magnify this issue, I would treat idempotent as application developer's self bussiness , and for these years we have only one issue reported right?  I I donot want to see istio become a child's play, changing day by day

It cannot achieve idempotent ops simply via undelying tranport layer http/tcp protocol. Without server's own logic, even no proxy put on the path, idempotent cannot be achieved.

**Comment by ramaraochavali** [comment]
>   However It is indeed a behavior change, turned on by default.

That is why compatibility versions exist. If do not want behaviour change, run with that compatibility version and change. Also I do not think this is a huge problem turn this off or change it via MeshConfig - both are pretty straight forward solutions.

>We donot need to magnify this issue, I would treat idempotent as application developer's self bussiness , and for these years we have only one issue reported right?

I do not think any serious user would rely on default retry policy for POST/PUT/DELETE requests. Every one might have changed because of this policy. See https://github.com/istio/istio/issues/13851 and specifically this [comment](https://github.com/istio/istio/issues/13851#issuecomment-503586648).  503 default retry policy was added because at that we were retuning lot of 503s during scale down and we knew very well that it was a band aid. The proper fix was to implement draining - we added several features both in Envoy and Istio to improve the draining behaviour

> It cannot achieve idempotent ops simply via undelying tranport layer http/tcp protocol. Without server's own logic, even no proxy put on the path, idempotent cannot be achieved.

But that does not mean, we just retry assuming that app handles - think about other way, when there is no Envoy infront, they never get duplicate request and with automatic retries in place they get these requests without they knowing it.,


Just because it has been there for 5 years does not make it right. IMO, this is similar to load balancing algo change we did (convert from RANDOM -> LEAST_REQ), it may not work for some but it is better default and we should be open changing the behaviour if there are issues with it.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
