### PR TITLE
Fix filterchain match's incorrect early match

### PR DESCRIPTION
**Pull request by mandarjog**
Fixing incorrectly matched filterchain if `lMatch.FilterChain==nil`.
This moves filtering unrelated to `lMatch.FilterChain` before the nil check.

Signed-off-by: Mandar U Jog <mjog@google.com>

manual cherry pick for https://github.com/istio/istio/pull/35836

### CODE REVIEW

**Comment by jwendell** [comment]
@mandarjog Is this worth a release note entry?

**Comment by mandarjog** [comment]
@jwendell This is a bug fix. it just ensures that multiple chains are no inadvertently matched.

**Comment by mandarjog** [comment]
@jwendell ping !

**Comment by jwendell** [comment]
@mandarjog I know this is a bug fix. That's exactly why I asked about a release note. Given .z releases mostly contain bug fixes, users like to know what's new in a .z release.

Let me know if you still don't think a release note entry is not needed in this case and I'll approve it. Thanks.

**Review by jwendell — APPROVED** [review]

**Pull request merged**
