### PR TITLE
Fix Compilation errors on non-linux platforms

### LINKED ISSUE #49907: Compilation errors on non-Linux platforms
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The master branch has compilation errors on non-Linux platforms that affect the execution of unit tests.

截屏2024-03-14 16 27 46

### Version

```Text
master branch
```

### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### PR DESCRIPTION
**Pull request by fyuan1316**
**Please provide a description of this PR:**

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**
close #49907 
- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by hanxiaop — COMMENTED** [review]
/ok-to-test

I think the test doesn't work on non-Linux platforms anyway, even after fixing the compile error.

**Comment by fyuan1316** [comment]
Thank you for your reply. @hanxiaop 
Sorry, maybe I wasn't clear. I know I don't want the tests in `netns_linux_test.go` to be executed on non-Linux platforms.
It's just that this error prevents the test cases in `cni_watcher_test` from being executed correctly.

**Review by hanxiaop — APPROVED** [review]
Thanks!

**Pull request merged**
