### PR TITLE
Upgrade rules_go to 0.5.2

### LINKED ISSUE #429: bazel 0.5.x build error on macos
On the same mac, pilot/ and mixer/ build fine but not istio/ (probably I'm missing some simple step)
```
ldemailly-macbookpro:istio ldemailly$ bazel build ...
INFO: Found 16 targets...
ERROR: /private/var/tmp/_bazel_ldemailly/b3234b5df793e8ff590992c9cc08b3a3/external/com_github_golang_glog/BUILD:5:1: null failed: Process exited with status 1 [sandboxed].
github.com/golang/glog/external/com_github_golang_glog/glog.go:74: can't find import: "bufio"
Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
INFO: Elapsed time: 1.994s, Critical Path: 1.22s
ldemailly-macbookpro:istio ldemailly$ bazel build --strategy=GoCompile=standalone ...
INFO: Found 16 targets...
ERROR: /private/var/tmp/_bazel_ldemailly/b3234b5df793e8ff590992c9cc08b3a3/external/org_golang_google_grpc/keepalive/BUILD:3:1: null failed: go_default_library.a.GoCompileFile.params failed: error executing command  ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
google.golang.org/grpc/external/org_golang_google_grpc/keepalive/keepalive.go:38: can't find import: "time"
INFO: Elapsed time: 0.444s, Critical Path: 0.10s

ldemailly-macbookpro:istio ldemailly$ bazel version
Build label: 0.5.1-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 6 12:34:07 2017 (1496752447)
Build timestamp: 1496752447
Build timestamp as int: 1496752447
```

### PR DESCRIPTION
**Pull request by lizan**
Fixes #429

### CODE REVIEW

**Comment by lizan** [comment]
Note this will require Bazel 0.5.2 or newer for building. DO NOT MERGE until test infra gets update.

**Comment by ldemailly** [comment]
I wonder why jenkins is happy and prow isn't

**Comment by lizan** [comment]
@sebastienvas @yutongz When can this be merged? Prow seems failing every PR at the moment.

**Comment by yutongz** [comment]
@ldemailly  The OWNERS file just got merged in. So now, if you would like to try "/approve" again, it should work :)

**Comment by sebastienvas** [comment]
We already using bazel 0.5.2.

**Comment by lizan** [comment]
@sebastienvas linters even fails on master, with same messages.

**Comment by sebastienvas** [comment]
I am not convinced. We submitted multiple PRs today without failures.

**Comment by ldemailly** [comment]
merged as it passed linters on prow/istio-presubmit.sh (not sure where Jenkins presubmit went)

**Comment by sebastienvas** [comment]
Jenkins presubmit is disabled because there are too many tests running on the e2e cluster.

**Pull request merged**
