### PR TITLE
bump istio api

### PR DESCRIPTION
**Pull request by bianpengyuan**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
shouldn't this be automated? I suspect its blocked by some failure?

**Comment by bianpengyuan** [comment]
Yeah I was also expecting the automation. Does not seem to kick in.

**Comment by bianpengyuan** [comment]
The new external field of authorization policy causes fuzz package to crash.
```
fuzz_test.go:113: Observed a panic: "Can't handle <nil>" (Can't handle <nil>)
        goroutine 39532 [running]:
        istio.io/istio/pkg/config/schema_test.logPanic(0xc0010c0480, 0x3076e80, 0xc001000360)
        istio.io/istio/pkg/config/schema_test.TestValidationFuzzing.func1.1(0xc0010c0480, 0xc001ab3d18)
        panic(0x3076e80, 0xc001000360)
        github.com/google/gofuzz.(*fuzzerContext).doFuzz(0xc001000250, 0x31c4000, 0xc000f56140, 0x194, 0x0)
        github.com/google/gofuzz.(*fuzzerContext).doFuzz(0xc001000250, 0x33be360, 0xc000f56118, 0x199, 0x0)
        github.com/google/gofuzz.(*fuzzerContext).doFuzz(0xc001000250, 0x33000c0, 0xc000f56000, 0x199, 0x0)
        github.com/google/gofuzz.(*Fuzzer).fuzzWithContext(...)
        github.com/google/gofuzz.(*Fuzzer).Fuzz(0xc00165c370, 0x3514240, 0xc000f56000)
        istio.io/istio/pkg/config/schema/fuzz.fuzzInternalObject(0xc0010c0480, 0xc00165c370, 0x38bf420, 0xc000f56000, 0x0, 0x0)
        istio.io/istio/pkg/config/schema/fuzz.Fuzz(0xc0010c0480, 0x3568790, 0x11, 0x3558159, 0x7, 0x356aab8, 0x13, 0xc00084c1c0, 0xc00165c370, 0x488827, ...)
        istio.io/istio/pkg/config/schema_test.TestValidationFuzzing.func1(0xc0010c0480)
        testing.tRunner(0xc0010c0480, 0xc001790220)
        created by testing.(*T).Run
    fuzz_test.go:70: panic on process (*config.Config)(nil)
```

I cannot tell what is special in there that would cause this: https://github.com/istio/api/commit/ae1b3ec96a8645b8c492550ab1e024ef3f101600#diff-30b88b2500cd44b6dafb84e087afaa4338225e74ddcad2b49e86449b2b21a8fd @howardjohn any idea? Might be a bug in fuzz library.

**Comment by howardjohn** [comment]
@bianpengyuan basically ther fuzz library cannot handle interface types. All Enums, oneofs, and more in proto are interfaces. So it fails like this. WE need to add it to https://github.com/istio/istio/blob/fe30e28a982c341ad19b9c6ca5cca10a7c54de6a/pkg/config/schema/fuzz_test.go#L117

We probably need to come up with a better solution for this.. its pretty painful. I don't know of a better option though

**Pull request merged**
