### PR TITLE
Refactor Eventually() to return error for testing

### PR DESCRIPTION
**Pull request by m1093782566**
This PR:

* Add some comments.

* Refactor Eventually() to return error for testing.

/assign @nmittler @ozevren 

/cc @hklai

### CODE REVIEW

**Comment by nmittler** [comment]
@m1093782566 can you explain the purpose of this change?

**Comment by m1093782566** [comment]
I want to test `Eventually()` but has no way to know if it succeed or failed without returning errors. So this PR has `Eventually()`  return error.

**Comment by ozevren** [comment]
Can't you create an error variable and use it through closure?

**Comment by nmittler** [comment]
@m1093782566 why would you test `Eventually`? It's a test utility.

**Comment by m1093782566** [comment]
i think we also need to make sure test util is properly tested



--------------------------------------------------
m1093782566<tel:1093782566>
发件人：Nathan Mittler
收件人：istio/istio,
抄 送：dujun (D),Mention,
时间：2018-09-26 23:41:48
主 题：Re: [istio/istio] Refactor Eventually() to return error for testing (#8974)


@m1093782566<https://github.com/m1093782566> why would you test Eventually? It's a test utility.

**Comment by nmittler** [comment]
@m1093782566 

> i think we also need to make sure test util is properly tested

That doesn't mean we should change it's API. The point of it is to free the caller from having to check errors. Instead, it just fails the test. We don't want to change that.

**Comment by m1093782566** [comment]
@nmittler 

Can you tell me how to test the function without returning errors? BTW,  I think returning errors give caller a chance to better handle and check errors, you can find similar codes here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L297-L311

**Comment by hklai** [comment]
This change makes this even more similar to https://github.com/istio/istio/blob/master/pkg/test/util/retry.go

And there may be value to consolidate them.  In a way, return error is more generic so this can actually be used outside of tests, if needed.

**Comment by m1093782566** [comment]
@hklai 

I can not agree more!! I have the same feeling to consolidate them. 

BTW, as `retry` and `wait` is a generic mechanism and they should be used in some places other than tests, why not move these utils to pkg/util? WDYT ^_^

**Comment by ozevren** [comment]
I think this is quite testable without changing its structure. Instead of passing ```*testing.T```, you can pass ```testing.TB```, which allows you to mock testing.T behavior while changing the signature for the better.

Also, if you need, you can inject back-off methods, similar to how it is done in Mixer server code, with patch table: https://github.com/istio/istio/blob/93dcee50428e1b65f03b0b4c65f46f1cd9e5968e/mixer/pkg/server/server.go#L76

As for consolidating utility methods, it requires a bit more thought. The test code here depends on testing.T, which is deliberate, and useful for writing tests cleanly. The test utility code that does waits does not use testing.T, and is a bit more opinionated.

**Comment by m1093782566** [comment]
> I suppose a generic Retry (that returns) can be moved to a generic util and then a wrapper can be added in test/util that makes use of it, and deal with *testing.T. Will that make everyone happy? =)

I have no objections and will to see if it is feasible.

**Comment by nmittler** [comment]
I'm fine with consolidating the retry logic into a single function that makes sense and then having Eventually wrap this function.  We already have a few custom `retry` functions lying around the codebase.  There are 3rd party libraries out there that do retry such as https://github.com/avast/retry-go and https://github.com/cenkalti/backoff (the latter does exponential backoff).  Perhaps we should just be using one of these instead?

**Pull request closed without merging**
