### PR TITLE
deps: update proxy

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by hklai** [comment]
Need to wait for the proxy image to be published....

**Comment by ldemailly** [comment]
@hklai / @sebastienvas can you configure the bot to not ask me for reviews ? tia!

**Comment by hklai** [comment]
> @hklai / @sebastienvas can you configure the bot to not ask me for reviews ? tia!
@ldemailly probably remove yourself from the istio teams on github. -_-

**Comment by kyessenov** [comment]
can someone retrigger circle? I don't have access...

**Comment by ldemailly** [comment]
@hklai there should be a way to stay in team
without the bot assigning reviews (leave mode or blacklist ...)

**Comment by rshriram** [comment]
@costinm i believe this fixes the upgrade issue.

**Comment by kyessenov** [comment]
No it doesn't. @costinm wants to keep old envoy (0.8 or earlier) to accept new pilot configs. There are 
a lot of new things in envoy which are likely to not be available in 0.8, but he is just nuking mixerfilter functionality at the moment. My change fixes 1.0 onwards.

**Comment by kyessenov** [comment]
Why is circle broken again? Need force merging...

**Comment by kyessenov** [comment]
@rshriram I can't login to circle, and it doesn't run the tests. Please force merge, we need the compatibility fix to be in 1.0.

**Pull request merged**
