### PR TITLE
[release-1.21] manifests: fix gateways.securityContext not work

### PR DESCRIPTION
**Pull request by timonwong**
**Please provide a description of this PR:**

Manual cherry-pick of #51654

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
this's more like a new feature rather than a bug-fix(and without release-notes).

**Comment by timonwong** [comment]
@zirain this is a bug fix for #51234. In #51234, it only works when you deploy gateway standalone (not using auto-injection, which is recommended). And it's not cusomizable using istioctl (can only be done using helm)

**Comment by zirain** [comment]
> @zirain this is a bug fix for #51234. In #51234, it only works when you deploy gateway standalone (not using auto-injection, which is recommended). And it's not cusomizable using istioctl (can only be done using helm)

you should provide release-notes for backport.

**Comment by timonwong** [comment]
> you should provide release-notes for backport.

@zirain This addresses #51234 (which is backported), but they are not released. 

In https://github.com/istio/istio/tree/master/releasenotes, it states that:

> No release notes are required for changes to:
> Tests
> Build Infrastructure
> Fixes of bugs that have not been released.

Though this is a bugfix for a unreleased feature, i think there is no need to draft a release note?

**Review by zirain — APPROVED** [review]

**Pull request merged**
