### PR TITLE
implement max connection duration

### PR DESCRIPTION
**Pull request by ramaraochavali**
Implements https://github.com/istio/api
Fixes https://github.com/istio/istio/issues/22635

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
Approve test and release notes.

**Review by GregHanson — CHANGES_REQUESTED** [review]
is there any validation that needs to be added to pkg/config/validation/validation.go?  Our API specifies duration must be at least 1ms.

**Review by hzxuzhonghu — COMMENTED** [review]
Donot we need to set MaxConnectionDuration to inbound listener?

**Comment by ramaraochavali** [comment]
> is there any validation that needs to be added to pkg/config/validation/validation.go? Our API specifies duration must be at least 1ms.

Good point. Added

**Comment by ramaraochavali** [comment]
> Donot we need to set MaxConnectionDuration to inbound listener?

I do not think we need. The use cases for max connection duration are for outbound only.

**Comment by hzxuzhonghu** [comment]
OK, SG

**Review by hzxuzhonghu — APPROVED** [review]

**Review by GregHanson — APPROVED** [review]

**Pull request merged**
