### PR TITLE
Bump grafana image to 5.2.3

### PR DESCRIPTION
**Pull request by jwendell**
As it has important security fixes

### CODE REVIEW

**Comment by jwendell** [comment]
If accepted, will this commit be backported to master or should I open a new PR against master?

**Comment by sdake** [comment]
@jwendell My recommended workflow is to commit to master first, then git cherry-pick -x the commit onto the release-1.0 branch.  We generally don't forward port changes to master from the release branch after the release has been in the wild for some time.

Also please see: https://istio.io/about/security-vulnerabilities/

Cheers
-steve

**Comment by jwendell** [comment]
@sdake thanks, just opened https://github.com/istio/istio/pull/8346

**Pull request closed without merging**
