### PR TITLE
Update setupMeshEx.sh to work on Mac

### PR DESCRIPTION
**Pull request by craigbox**
**What this PR does / why we need it**:
Makes setupMeshEx.sh work on Mac.

base64 -d on GNU, -D on Mac.

--decode works for both.

### CODE REVIEW

**Comment by ldemailly** [comment]
/ok-to-test
/lgtm

thx!

**Comment by craigbox** [comment]
erm, this isn't how I left my PR :)

**Comment by ldemailly** [comment]
can you refork and re-apply
https://github.com/istio/istio/commit/7bc74b7797717e3a50759eb244319c5ae62e8ec5.diff

**Comment by ldemailly** [comment]
fixed in #1298

**Pull request closed without merging**
