### PR TITLE
Use updated networking x-k8s for service api

### LINKED ISSUE #24599: service api does not work with networking.x-k8s.io CRD although it works with old networking.x.k8s.io
**Bug description**

- When using the new service apis feature (Gateway, GatewayClass), does not work with networking.x-k8s.io CRD but work with networking.x.k8s.io.
- The CRD was changed by https://github.com/kubernetes-sigs/service-apis/commit/3a0c01addfafb5ebe83cddc43d76909644c864e7.
- It seems Istio 1.6.1 imports old service api version.

[x] Networking

**Expected behavior**

- New networking.x-k8s.io should work.
- networking.x.k8s.io should be obsolete.

**Steps to reproduce the bug**

#### 1. Install the latest CRD

```
kubectl apply -k github.com/kubernetes-sigs/service-apis/config/crd
```

#### 2. Deploy Gateway and GatewayClass

<details><summary>Deploy Gateway and GatewayClass</summary><div>

```
kubectl apply -f - <<EOF
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  class: istio
  addresses:
  - type: NamedAddress
    value: gateway.local
  listeners:
  - protocol: HTTP
    routes:
      namespaceSelector: {}
      routeSelector:
        matchLabels:
          "app": "istio"
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: http
  # TODO use different namespace
  namespace: istio-system
  labels:
    app: istio
spec:
  hosts:
  - hostname: "gateway.local"
    rules:
    - match:
        pathType: Prefix
        path: /get
      filter:
        headers:
          add:
            my-added-header: added-value
          remove: [my-removed-header]
      action:
        forwardTo:
          targetRef:
            name: httpbin
            group: v1
            resource: Service
EOF
```
</div></details>

#### 3. Deploy httpbin

<details><summary>Deploy httpbin</summary><div>
```
kubectl apply -n istio-system -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  ports:
  - name: http
    port: 80
    targetPort: 80
EOF
```
</div></details>

```
curl $INGRESS_HOST:$INGRESS_PORT/get -H "Host: gateway.local"
(gets 404 not found or timeout).
```

__NOTE__:  Verified it works with `networking.x.k8s.io/v1alpha1`

**Version

- Istio v1.6.1
- Kubernetes v1.18.3

**How was Istio installed?**

```
istioctl manifest apply  --set values.pilot.env.PILOT_ENABLED_SERVICE_APIS=true
```

### PR DESCRIPTION
**Pull request by shamsher31**
To Fix https://github.com/istio/istio/issues/24599

Not sure if this will be backward compatible with previous k8s versions, Needs more testing. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
I do have a pr for doing this https://github.com/istio/istio/pull/24001.I think this one is not really completely sufficient as there were also changes to the API not just the crd name was changed

**Comment by howardjohn** [comment]
We could also merge this then update the API later though

**Comment by shamsher31** [comment]
> We could also merge this then update the API later though

Sounds good, that will be easy to test and review.

**Comment by shamsher31** [comment]
Closed by #24001

**Comment by howardjohn** [comment]
Sorry we duplicated some work - happy to see others interested in this area
though!

**Pull request closed without merging**
