### PR TITLE
Update proxy sha

### PR DESCRIPTION
**Pull request by bianpengyuan**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by gargnupur — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by bianpengyuan** [comment]
/retest

Known flake: https://github.com/istio/istio/issues/28315

**Comment by bianpengyuan** [comment]
Looks like proxy somehow never becomes ready: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/28500/integ-security-k8s-tests_istio/1323388107118088192/artifacts/security-3f86303d15a44484b894a6/TestMtlsHealthCheck/_test_context/healthcheck-20-79114-state326770396/cluster-0/rewrite-success-v1-948484486-w7g6r_istio-proxy.log

**Comment by howardjohn** [comment]
Deployed locally

netstat -nl shows no envoy listeners. /listeners shows them


[logs.txt](https://github.com/istio/istio/files/5478791/logs.txt)

Relevant parts:
```
2020-11-03T01:05:59.057019Z     debug   envoy init      added target Listener-init-target 3cd758c7-edf2-4af3-8d4a-6227cd92e5ac to init manager Server
2020-11-03T01:05:59.057035Z     debug   envoy config    Create listen socket for listener 3cd758c7-edf2-4af3-8d4a-6227cd92e5ac on address 0.0.0.0:15021
2020-11-03T01:05:59.057039Z     debug   envoy config    Set listener 3cd758c7-edf2-4af3-8d4a-6227cd92e5ac socket factory local address to 0.0.0.0:15021
2020-11-03T01:05:59.057041Z     debug   envoy config    add active listener: name=3cd758c7-edf2-4af3-8d4a-6227cd92e5ac, hash=9872086206848846795, address=0.0.0.0:15021
```

**Comment by howardjohn** [comment]
Hm, I notice it also has no dynamic listeners. I think it requests CDS from istiod but never lds:
```
2020-11-03T01:08:54.214761Z     info    ads     ADS: new connection for node:sidecar~10.88.2.147~svc00-0-7-0-7b7c4664b-lwfqt.service-graph00~service-graph00.svc.cluster.local-3499
2020-11-03T01:08:54.216627Z     info    ads     CDS: PUSH for node:svc00-0-7-0-7b7c4664b-lwfqt.service-graph00 resources:38 size:34.6kB
2020-11-03T01:08:54.216802Z     info    ads     EDS: PUSH for node:svc00-0-7-0-7b7c4664b-lwfqt.service-graph00 resources:34 empty:0 cached:34/34
```

**Review by howardjohn — APPROVED** [review]

**Comment by bianpengyuan** [comment]
So.. looks like SDS change is not the root cause? We are still seeing blocked start up here.. cc @lambdai

**Comment by howardjohn** [comment]
the revert was only for 1 of the 2 envoy PRs. maybe the other one broke the warming

**Comment by lambdai** [comment]
https://github.com/envoyproxy/envoy/pull/13875 may fix the envoy cluster never ready which we are seeing in this thread.

And the reverted PR is to address cluster early ready. Lizan has some long term and short term plan.

**Pull request merged**
