### PR TITLE
operator: update ARCHITECTURE

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by sdake** [comment]
@daixiang0 thanks for the improvement. We have not met on Slack. It's a pleasure to see more contributors!

Cheers,
-steve

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
