### PR TITLE
telemetry: tuning client-side telemetry

### PR DESCRIPTION
**Pull request by kyessenov**
- populate `source.uid` for static bootstraps (used by telemetry sidecars to identify the mixerclient source)
- set unknown service destination for TCP outbound (otherwise, mixer fails to resolve config)
- set unknown service destination for HTTP inbound (routes properly identify services, prior to this, picking the first one was incorrect )
- [undone] enable basic gateway telemetry (check and report are called on the call from the gateway to the service, source is the gateway) _causes 503 during rule change error, will be fixed later_

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
I've noticed that enabling telemetry on the gateway seems to trigger `TestIngressGateway503DuringRuleChange` test failure. @ostromart @rshriram any leads? Telemetry should have no effect on routing, so this must be something about how the config is updated by pilot.

**Comment by kyessenov** [comment]
Let's get this in without gateway first, and then debug the segfault separately.

/assign @douglas-reid @mandarjog

**Comment by kyessenov** [comment]
/hold

@douglas-reid you are now an owner in the mixer plugin. There's little effect on general pilot operation from this plugin, it's augment-only and gated by mesh config.

**Comment by kyessenov** [comment]
/hold cancel

I think this is the situation where mixer team probably knows best what to set in the mixer filter.

**Comment by ostromart** [comment]
I agree you guys know best with these changes. One caution though - the 503 has been disabled for long periods of time due to breakage in the past and it took a lot of effort to get it running again. Actually it's been a really good lightning rod for all sorts of problems. Let's be careful about not leaving it in a broken or skipped state for too long.

**Comment by kyessenov** [comment]
Yes, I deliberately left out the gateway change. It's indicative of some
larger problem. I have no intentions to remove or disable tests.

**Comment by kyessenov** [comment]
looks like circle is stuck. can someone merge this manually? @rshriram

**Comment by kyessenov** [comment]
@geeknoid circle is not responding, and I cannot find the button to start it... Do you mind merging this?

**Comment by kyessenov** [comment]
@bianpengyuan I was able to finally get a segfault sometimes (not always!). However, not using debug envoy made the resulting trace useless. Trying to get a debug build of envoy through circle.

**Comment by kyessenov** [comment]
plot thickens... segfaults do not happen with the debug build...

**Comment by ostromart** [comment]
That's exactly what I observed in the past too. It may be due to heavy optimization. I'd stick to working with the core file if possible.

**Pull request closed without merging**
