### PR TITLE
Fix submessage support part1

### PR DESCRIPTION
**Pull request by guptasu**
**What this PR does / why we need it**:
NOTE: The changes in this PR were already approved by @douglas-reid @geeknoid. Old PR contained 12 files (https://github.com/istio/istio/pull/1617) but was reverted because of missing 2 generated pb.go file. I have added the missing 2 generated file in this PR (this PR therefore contains 14 files).

Note this is part 1 of sub message support. It is based on the proposal https://docs.google.com/document/d/1GL_EOitfBJDfgbQJOSROceK5RdqNPuiggeAebaNqyf8/edit#
This PR contains the code generation for the go Instances and the augmented proto messages (Type and InstanceParam)

Part 2 (following [PR](https://github.com/istio/istio/pull/1702)) will contain the bootstraping code generation (code that runs at run-time, inside Mixer framework and instantiates these sub-message artifacts generated in this PR).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by douglas-reid** [comment]
/lgtm

(already previously approved and submitted).

**Comment by guptasu** [comment]
@geeknoid @douglas-reid re-lgtm please

**Pull request merged**
