### PR TITLE
Add Ztunnel Dockerfile to update_deps script

### PR DESCRIPTION
**Pull request by yankay**
**Please provide a description of this PR:**

Distroless images should be updated periodically. 
Add Ztunnel Dockerfilecapability to update_deps.sh so it gets updated.

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- Test and Release

**Please check any characteristics that apply to this pull request.**

- Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
Thanks.

**Comment by ericvn** [comment]
/retest

Not sure why the particular test is failing as the script should not affect that. Looking, the test appears to be passing in other PRs.

**Review by howardjohn — APPROVED** [review]

**Comment by yankay** [comment]
Thanks @ericvn , @howardjohn for the PR review. :-)

**Pull request merged**
