### PR TITLE
wasm: use the cloud provider credentials when available to pull images

### PR DESCRIPTION
**Pull request by nacx**
Configures the WASM image fetcher with a keychain that loads the major cloud provider authenticators (GKE, AKS, EKS), so that `imagePullSecrets` are not needed when pulling WASM extensions from the corresponding registries.

### CODE REVIEW

**Comment by nacx** [comment]
The test that fail is the binary size test:
```
=== RUN   TestBinarySizes/pilot-agent
    binaries_test.go:112: Actual size: 60mb. Range: [30mb, 45mb]
    binaries_test.go:114: Binary size of 60mb was greater than max allowed size 45mb
```
The binary size has grown probably due to the cloud provider dependencies (mostly AWS and Azure) pulled from the container registry authentication module. +15MB increase just for this is probably too much for the convenience of the feature?

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by nacx** [comment]
I intentionally did not modify the binary size test to bring some attention to the fact that this PR increases the size of the pilot-agent by ~15MB. I see the PR is approved now. Does it mean the size increase is acceptable for this feature? If so, I'll update the test accordingly, but I didn't want to do that directly without discussing it :)

**Comment by zirain** [comment]
> :

15M seems too much, curious why

**Comment by nacx** [comment]
It looks like it's due to the indirect dependencies that are pulled for the cloud provider authn providers:
https://github.com/istio/istio/pull/41970/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R112-R133

**Comment by howardjohn** [comment]
@ingwonsong did a lot of research on this and I think decided against this object. I'd like them to weigh in here.

**Review by howardjohn — CHANGES_REQUESTED** [review]
see previous comments

**Comment by nacx** [comment]
It looks like there were [previous attempts](https://github.com/google/go-containerregistry/issues/1263#issuecomment-1020556974) at reducing the dependency footprint of the `go-containerregistry` k8s module, that did not progress because the main efforts were not getting merged in the upstream libraries. Fixes there are kinda unlikely to happen given how modular the dependencies are and how everything depends on everything there, so probably it's worth just closing this PR as it's unlikely the dependencies needed to implement it will become smaller in the near term.

**Comment by ingwonsong** [comment]
Hi @nacx 

This PR was my previous approach: https://github.com/istio/istio/pull/39487.

In short, there were discussions about static linking platform-specific libraries. 
The key thing was that it introduces dependency management issues as well as increasing memory usage. 

In Knative, AFAIK, the dependency causes painful issues, and one of the reason why K8S decided to peel off the platform-specific codes. In addition, the Wasm is an important feature, but is optional, so the added memory size would be burden to the users who don't use Wasm.

As alternative solutions, we discussed following ways.
1) Shipping `crane` in istio-proxy container together and calling `crane` command to get the credential 
    * `authconfig --server $REGISTRY_SERVER` 
    * Still `istio-proxy` docker image has a `crane` binary dependency
2) Having a gateway for accessing platform-specific registries
    * you can see a prototype in https://github.com/ingwonsong/docker-credential-magic-proxy
    * Cons: adding a new component

another interesting approach is https://github.com/docker-credential-magic/docker-credential-magic.
This project provides a way to inject the platform specific binaries.

If you have any question, please feel free to ask me.

**Comment by nacx** [comment]
Thank you for all the details and context, much appreciated! I didn't know there was prior work on this.
I'll close the PR for now, as this dependency is a no-go, and take a look at the provided links and initiate some discussion.
Thank you!

**Pull request closed without merging**
