### PR TITLE
Revise IncludeRequestHeadersInCheck to use new envoy allowed_headers field

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
The old field is deprecated in https://github.com/envoyproxy/envoy/pull/22877. The new field maintains the same behavior as the old one.
Verified it is working as expected.

### CODE REVIEW

**Comment by ymesika** [comment]
Isn't this breaking backward compatibility?

**Comment by ramaraochavali** [comment]
I think it should not. It is released in 1.25 of Envoy which is shipped with Istio 1.16.

**Comment by hanxiaop** [comment]
@istio/wg-security-maintainers PTAL.

**Comment by ramaraochavali** [comment]
@hzxuzhonghu PTAL

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
