### PR TITLE
[test pr] check if 503s and other known bugs are fixed

### PR DESCRIPTION
**Pull request by ldemailly**
For issue #1038 

removing the t.Skip()

Should fail in CI until we have a fix

### CODE REVIEW

**Comment by rshriram** [comment]
We already have a test for 503.. And this test will likely never pass because its using old v1 and  old v1alpha1 format.

**Comment by ldemailly** [comment]
> We already have a test for 503

where ?

**Comment by ldemailly** [comment]
@andraxylia can you please retroactively approve the comment and yaml changes that accidentally made it early to master

**Comment by ldemailly** [comment]
the revert from service back to ip missed a couple of character changes: #5241

**Pull request merged**
