### PR TITLE
remove the old version of token verification

### PR DESCRIPTION
**Pull request by williamaronli**
right now we use credential fetcher to fetch the token. This function are first used in old fetch method. So remove it

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by liminw — APPROVED** [review]
/lgtm

**Pull request merged**
