### PR TITLE
make istio release version configurable and flexible in istio setup with ansible

### PR DESCRIPTION
**Pull request by LillyWu**
To fix issue: https://github.com/istio/istio/issues/7250

1. The default build istio version is still the latest release one

2. Users could choose the istio version throught command, for example `ansible-playbook main.yml -e '{"cluster_flavour": "k8s", "istio_release_tag": "tag/1.0.0-snapshot.1"}`

### CODE REVIEW

**Comment by LillyWu** [comment]
It works well with default `latest` release in k8s. The setup command is 
`ansible-playbook main.yml -e '{"cluster_flavour": "k8s"}'`

But when I test with the new released `1.0.0-snapshot.1`, with command 
```
ansible-playbook main.yml -e '{"cluster_flavour": "k8s", "istio_release_tag": "tag/1.0.0-snapshot.1"}'
```
It will be failed. As there is a rate limitation for url `https://api.github.com/repos/istio/istio/releases/tag/1.0.0-snapshot.1`

The detail error log is 
```
TASK [istio : include_tasks] ***************************************************************************************************
included: /home/ibmadmin/istio/install/kubernetes/ansible/istio/tasks/determine_release_version.yml for localhost

TASK [istio : Set release tag to latest] ***************************************************************************************
ok: [localhost] => {"ansible_facts": {"release_tag": "tag/1.0.0-snapshot.1"}, "changed": false}

TASK [istio : Get the tagged release] ******************************************************************************************
fatal: [localhost]: FAILED! => {"access_control_allow_origin": "*", "access_control_expose_headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval", "changed": false, "connection": "close", "content": "{\"message\":\"API rate limit exceeded for 129.42.208.184. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://developer.github.com/v3/#rate-limiting\"}", "content_length": "248", "content_security_policy": "default-src 'none'", "content_type": "application/json; charset=utf-8", "date": "Fri, 20 Jul 2018 09:27:20 GMT", "json": {"documentation_url": "https://developer.github.com/v3/#rate-limiting", "message": "API rate limit exceeded for 129.42.208.184. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}, "msg": "Status code was 403 and not [200]: HTTP Error 403: Forbidden", "redirected": false, "referrer_policy": "origin-when-cross-origin, strict-origin-when-cross-origin", "server": "GitHub.com", "status": 403, "strict_transport_security": "max-age=31536000; includeSubdomains; preload", "url": "https://api.github.com/repos/istio/istio/releases/tag/1.0.0-snapshot.1", "x_content_type_options": "nosniff", "x_frame_options": "deny", "x_github_media_type": "github.v3; format=json", "x_github_request_id": "CD31:2A3E:6E0689:D6C816:5B51AAF8", "x_ratelimit_limit": "60", "x_ratelimit_remaining": "0", "x_ratelimit_reset": "1532078951", "x_runtime_rack": "0.023534", "x_xss_protection": "1; mode=block"}
	to retry, use: --limit @/home/ibmadmin/istio/install/kubernetes/ansible/main.retry
```

So if we want to enable this function,  the project owner need to set he rate limitation to a larger number or enable the access with token like the previous `release/latest` url

**Comment by geoand** [comment]
Thanks for taking the time to look at this @LillyWu !

Here are my comments (copied from #7250)

We used to have support for multiple istio versions like your PR adds, but it turned out to be a hassle because it's hard for the playbooks to account for the differences between Istio versions so it was removed.

In my mind what we need is the following:

The playbooks should operate under the assumption that they are part of an Istio release, that is that all the necessary Kubernetes - Istio resources can be found in a path relative to the playbooks.
Provide an override to the location of the Kubernetes Istio Resources. This should only be necessary for those who develop the playbooks because when working from source the Kubernetes Istio resources needed by the playbooks are not available.

**Comment by geoand** [comment]
Also @LillyWu there is a the `github_api_token` flag that you can use to overcome the rate limiting issue

**Comment by LillyWu** [comment]
@geoand  thanks for your comments, and you already point out the critical point that the differences between version.

About the solution: 
If your suggested requirement 1 is satisfied: 

```
The playbooks should operate under the assumption that they are part of an Istio release, that is that all the necessary Kubernetes - Istio resources can be found in a path relative to the playbooks.
```
Then it makes thing easier. Users download the istio project with ansible playbook inside and setup it with ansible playbooks for the present version. And it's also easier for future ansible playbook development. 

Besides,  I came up with a question that whether it's necessary to enable ansible setup as its prerequisites already include kubernetes, and users could install with kubectl in a quick way. Would you mind to share your idea?  

To make ansible setup richer

1.  Users could customize their cluster, and install istio in remote cluster.
  in ansible project, we could add inventory, hostvars ..etc

1.  Include the kubernetes installation in playbook for users who don't use the PaaS, like GKS, IKS...

**Comment by geoand** [comment]
@LillyWu There are definitely a lot of things that can be done (like the ideas you suggested) to make the Ansible installer a lot better. Another thing would be to use templates in order to customize the Kubernetes resources instead of relying on the pre-built ones.

As it stands, the Ansible installer is only able to deploy vanilla/demo versions of Istio onto Kubernetes and Openshift, and it's basically a substitute for performing the operations mentioned in the docs by hand.
The reason it has not been extended further is that currently we haven't seen a tremendous amount of interest in it :) 

So my view is that we should first make it work in the way users would expect it to when the download an Istio release (which is probably fairly easy to do based on my previous comments) and then ponder / experiment on how we can extend it for subsequent releases.
Would you like to work on implementing the fix I suggested and which you seem to agree with? Otherwise I will probably have some time to do it next week :)

**Comment by geoand** [comment]
@LillyWu Sounds great!

**Comment by sdake** [comment]
cc @andraxylia @costinm 

@geoand Regarding interest in the Ansible playbook, I think the following things would make the Ansible based installer more usable:

1. use `istioctl` or `helm template` with the `--set` option to permit setting options so Istio has *one set* of options that are documented and work.
2. An Ansible installation gate
3. Once these convergence options are settled, I think mesh expansion would be of huge value.

Cheers
-steve

**Comment by geoand** [comment]
@sdake Thank you for the insight!

**Pull request merged**
