### PR TITLE
remove duplicated service account for constructing sds config

### PR DESCRIPTION
**Pull request by quanjielin**
https://github.com/istio/istio/issues/6411

Fix [multiple TLS certificates are not supported for client contexts](https://github.com/envoyproxy/envoy/blob/9c492a01db235d5f3b2871adff906784f789b8be/source/common/ssl/context_config_impl.cc#L148) error when pilot push cds to ingress-gateway

### CODE REVIEW

**Comment by wattli** [comment]
Any test we can add?

**Comment by quanjielin** [comment]
Integration test needs to be added later, which pending on mock CA or citadel interface change done.

**Pull request merged**
