### PR TITLE
change custom-gateway label

### PR DESCRIPTION
**Pull request by husnialhamdani**
**Please provide a description of this PR:**

Change `custom-gateway` label https://github.com/istio/istio/issues/48295

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
you should also update the file `tests/integration/pilot/common/routing.go`

**Comment by husnialhamdani** [comment]
> you should also update the file `tests/integration/pilot/common/routing.go`

updated

**Comment by husnialhamdani** [comment]
> you should also update the file `tests/integration/pilot/common/routing.go`

Can you please check again @hzxuzhonghu?

**Comment by hzxuzhonghu** [comment]
Do you miss pushing new commit for https://github.com/istio/istio/pull/48594#issuecomment-1876179616

**Comment by husnialhamdani** [comment]
> Do you miss pushing new commit for [#48594 (comment)](https://github.com/istio/istio/pull/48594#issuecomment-1876179616)

I pushed the [commit](https://github.com/istio/istio/pull/48594/commits/793775bbd7ef250a3ff23cc9230bc96a49f4d93d)

**Comment by hzxuzhonghu** [comment]
you cannot directly update all the labels in tests/integration/pilot/common/routing.go. Because it is a shared file for other tests as well

**Comment by husnialhamdani** [comment]
> you cannot directly update all the labels in tests/integration/pilot/common/routing.go. Because it is a shared file for other tests as well

Shall I pass the variable in this part?
```
config: httpGateway("*", gatewayListenPort, gatewayListenPortName, "TCP", "custom-gateway") + // use the default label since this test creates its own gateway
```

**Comment by hzxuzhonghu** [comment]
I am not sure. Maybe try that

**Pull request closed without merging**
