### PR TITLE
Delete legacy E2E tests

### PR DESCRIPTION
**Pull request by howardjohn**
These have not been running in CI for over a month

### CODE REVIEW

**Comment by howardjohn** [comment]
For #20441

**Comment by bianpengyuan** [comment]
At least for the sd test, it does not really get much attention and maintenance, and it is mixer based.. So not sure keeping that test will bring any value. We just added a new e2e to test the sd filter: https://github.com/istio/istio/pull/19893, though it does not test the same pipeline as the legacy one.

**Comment by howardjohn** [comment]
@douglas-reid all tests that were run in our CI pipeline have been moved over. I don't think the stackdriver test was run? At least not when I moved things over...

**Comment by howardjohn** [comment]
@istio/wg-policies-and-telemetry-maintainers any objections? These tests have not run for ~month or so, this is just clean up since its confusing developers

**Pull request merged**
