### PR TITLE
Update istio-remote to match mixer rename

### PR DESCRIPTION
**Pull request by sdake**
Mixer was renamed to two components.  This makes an istio-remote
for both of them.

### CODE REVIEW

**Comment by sbezverk** [comment]
@sdake Please investigate Circle CI e2e pilot failure..

**Comment by ldemailly** [comment]
What is istio-remote ?

**Comment by sdake** [comment]
@ldemailly it is hopefully a temporary helm chart that is run on the main Istio Control plane via `helm template` to produce a list of services and endpoints for all remote clusters in a multicluster scenario.

It is further documented here:
https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install.html#use-kubectl-with-helm-to-connect-the-remote-cluster

**Pull request merged**
