### PR TITLE
ingress: remove

### PR DESCRIPTION
**Pull request by kyessenov**
Removes dead code since pilot no longer consumes ingress resources directly.
We should not be writing ingress status if we do not handle them programmatically.
/assign @nmittler @rshriram

### CODE REVIEW

**Comment by rshriram** [comment]
? We do read ingress and convert it into v1alpha3 configs.

**Comment by kyessenov** [comment]
Oh, didn't know that. How is port name handled?

**Comment by rshriram** [comment]
port names are rejected..

**Comment by costinm** [comment]
Do we still need this ? Not aware of any plan to drop ingress for now.

**Pull request closed without merging**
