### PR TITLE
Added --log_as_json container arg to all istio components in helm chart

### PR DESCRIPTION
**Pull request by rajusharma**
Currently there is no option in helm charts to output Istio components logs in JSON format. By default all the component logs are in TEXT format.
Each istio component container have option to change output as JSON using `--log_as_json` argument but in helm charts there is no way to add this argument
```
--log_as_json | Whether to format output as JSON or in plain console-friendly format

```
Added global variable called `logAsJson` in values.yaml and updated helm charts to use `--log_as_json` container argument

### CODE REVIEW

**Comment by rajusharma** [comment]
@geeknoid @mandarjog 
Would you please kindly review the changes

**Comment by howardjohn** [comment]
@rajusharma Thank you for the PR! This is pretty cool, I didn't know we had this option :slightly_smiling_face:. sorry this went under the radar for so long, we have a ton of PRs which is why we are trying to go through them all now and clean them up. 

We are moving over all changes to the install charts to https://github.com/istio/installer, which will be alpha in 1.2 and should be the only install option in 1.3 and beyond. Because of that, we are trying to restrict changes to the installer here to a bare minimum and only letting in critical bug fixes. This PR would be very welcomed there

Sorry again for telling you this so long after the change was submitted.

**Comment by rajusharma** [comment]
@howardjohn 
I want to ask about this issue 
Previously you mentioned that installer will be the only option in 1.3 and beyond, because of that you didn’t accept this PR to add `--log_as_json`  option. But i see that still there is no proper documentation for installer and everyone(including us) are using helm to install and upgrade istio. 
So each time we upgrade istio, we face this issue to add --log_as_json  manually, therefore shall i raise this PR and would you please kindly accept the PR 🙇

**Comment by howardjohn** [comment]
The istioctl installation is now the default which uses the charts in istio/installer

**Pull request closed without merging**
