### PR TITLE
Fix Kubernetes Ingress and Gateway prefix match

### PR DESCRIPTION
**Pull request by Monkeyanator**
Imagine a Kubernetes Ingress with `path: /sample` and `pathType: Prefix`:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /sample
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

In our current implementation we append a `/` to  `/sample` which turns into an exact string prefix match for `/sample/`:

https://github.com/istio/istio/blob/db4afa01f9a696a2c77528d75dacccffa565ea13/pilot/pkg/config/kube/ingressv1/conversion.go#L166-L172

We do this to prevent `/sample` from matching `/samplerandomtext`. However, it also prevents us form matching on `/sample`, which must match per the Ingress spec. Need to use a smarter regex instead to make it so that we match the prefix without trailing slash AND match with additional path components after the prefix.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Thanks!

can you set https://github.com/istio/istio/blob/c526ddcbb37edee38df09290796af7bcb7cb22a1/pilot/pkg/config/kube/gateway/conversion.go#L856? Double check the spec but I think it has the same logic

**Comment by Monkeyanator** [comment]
All the Gateway API spec mentions for `PathMatchType.Prefix`: 

> For prefix paths, a trailing ‘/’ character in the Path is ignored, e.g. /abc and /abc/ specify the same match ([here](https://gateway-api.sigs.k8s.io/references/spec/#networking.x-k8s.io/v1alpha1.PathMatchType)).

This is less specific than what the old `Ingress` spec describes:

> Matches based on a URL path prefix split by /. Matching is case sensitive and done on a path element by element basis. A path element refers to the list of labels in the path split by the / separator. A request is a match for path p if every p is an element-wise prefix of p of the request path.

I _think_ that since the spec doesn't say either way it's safe to go with the old Ingress behavior...

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
