### PR TITLE
'helm/support-termination-grace-period'

### PR DESCRIPTION
**Pull request by Rez0k**
gateway helm chart support termination grace period (if not mentioned 30 seconds is the default)

- [ ] Ambient
- [ X] Configuration Infrastructure
- [ ] Docs
- [ X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hanxiaop — APPROVED** [review]
thanks

**Comment by Rez0k** [comment]
> thanks

I think adding support for lifecycle hooks in the helm chart can be good as well.
After some games with istio-ingressgateway, I noticed that on rolling update or termination of pods the pods instantly get replaced, so I was wondering what happens to requests that take some time to process.
One solution I came up with is adding preStop lifecyle that will allow the ingress gateway to sleep before termination - resulting in a better and safer rollout.

what do you think?

https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks

if it is relevant I will be happy to add these ability to the helm chart

**Comment by hanxiaop** [comment]
> > thanks
> 
> I think adding support for lifecycle hooks in the helm chart can be good as well. After some games with istio-ingressgateway, I noticed that on rolling update or termination of pods the pods instantly get replaced, so I was wondering what happens to requests that take some time to process. One solution I came up with is adding preStop lifecyle that will allow the ingress gateway to sleep before termination - resulting in a better and safer rollout.
> 
> what do you think?
> 
> https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
> 
> if it is relevant I will be happy to add these ability to the helm chart

I think our gateway chart cannot contain all the values you might want to add, especially things like preStop hooks, which can vary across cluster environments. In such situations, I prefer using custom Helm logic to apply the patch.

**Comment by Rez0k** [comment]
> release-notes_istio

how can I skip running the release-notes test?

**Comment by hanxiaop** [comment]
> > /test release-notes
> 
> how can I skip running the release-notes test?

If you apply for a member then you can add the `release-notes-none` label. You can apply once you successfully merged one PR.

**Comment by clayvan** [comment]
@Rez0k it looks like this value is being backported to older chart versions?

Any chance we could just backport it to all of them? Specifically I'm looking for 1.17.5 and 1.18.2, but this seems like a really basic requirement for any production Istio Ingress Gateway deployment.

**Pull request merged**
