### PR TITLE
Use watching instead of polling to get update from Consul catalog

### PR DESCRIPTION
**Pull request by zhaohuabing**
Using watching can significantly reduce the CPU resource usage and the number of TIME_WAIT socket introduced by polling
Change-Id: I966690ecfaa79364997e94e81559acaab46d6a9d
Signed-off-by: Huabing Zhao <zhaohuabing@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
it's no a good practice to reply on a ticket that is closed two years.

In latest version, istio support this scenario with mcp-over-xds.

**Comment by chenzhiguo** [comment]
> it's no a good practice to reply on a ticket that is closed two years.
> 
> In latest version, istio support this scenario with mcp-over-xds.

Do you mean that MCP replaces the above solution that adapts to different centers? I thought MCP was abandoned, and was it alive?

**Comment by zirain** [comment]
MCP was abandoned, the new solution called mcp-over-xds.

IIRC, nacos supported this from v2.0.1, aeraki-mesh also use it.

**Comment by zhaohuabing** [comment]
@zirain https://github.com/aeraki-mesh/dubbo2istio

**Pull request merged**
