### PR TITLE
revert locality lb change

### PR DESCRIPTION
**Pull request by ramaraochavali**
Revert of https://github.com/istio/istio/pull/29238
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@nmittler @ericvn @duderino @hzxuzhonghu PTAL. Once it is merged, let us cherry pick to 1.9 and test. I have reopened the original issue.

**Comment by hzxuzhonghu** [comment]
If this is proved the cause, feel free to unhold. We could not do back forth work without even a test.

**Comment by ericvn** [comment]
We might be able to test the revert without pushing to 1.9 first. I've created a PR which will use the current latest master commit for the istio.io tests, https://github.com/istio/istio.io/pull/8875. I'm not sure if other changes in `master` will case all tests to fail (some framework change for example), but if we see the load balancer test fail similarly in `master`, we could try running again against the master commit with this revert and see if the tests pass.  This is probably easier than trying to set up the tests locally and trying running against local changes.

**Comment by ericvn** [comment]
The idea of using master to test the revert doesn't seem to be working as it looks like there are other issues that might have to be fixed to move the istio.io tests back to master.

But, I see https://github.com/istio/istio/pull/30483 and that it might fix the issue and then issue would be closed.

**Comment by nmittler** [comment]
Agreed. Please don't just revert without verifying that this actually fixes the problem.

**Comment by ramaraochavali** [comment]
@ericvn Sure. Let me know how that goes.

**Comment by ericvn** [comment]
@ramaraochavali I did need to make one update in the istio.io tests and I can now specify a `main` branch commit to run against in a test PR (currently https://github.com/istio/istio.io/pull/8883 is pointing at the commit that is currently the latest). My thought was to try and run some older commits (like just before the suspicious PR) and see if it worked, and just after the PR went in to see if it failed. Unfortunately, the Istio test framework had some changes as well as some module changes which prevent that.

If we did merge this PR so it was reverted in `main`, I could run a test against the the current commit to see if things worked.

Also, just running through the documentation with a local build should show the same behavior (round-robin). You could build new images locally with revert (no need to check in) and try running through the documentation to see if the problem is fixed.

I'm not sure if one could run the tests against a local build, but setting the HIB and TAG to the local images may work.

**Comment by ramaraochavali** [comment]
> Also, just running through the documentation with a local build should show the same behavior (round-robin). You could build new images locally with the revert (no need to check in) and try running through the documentation to see if the problem is fixed.

Can you please explain what needs to be done to run through the documentation?

**Comment by ericvn** [comment]
It should this page, https://preliminary.istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/distribute/, that is failing. The test basically runs the curl 50 times (and then multiplies the number of times each zone is hit by 2).

To see the test, you can start at https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/test.sh.

As noted above, you can see the artifacts from a run in: https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_istio.io/8852/doc.test.profile_default_istio.io/1354179789530861568/artifacts/tests-setup-profile-default-816/TestDocs/tasks/traffic-management/locality-load-balancing/distribute/test.sh/test.sh/_test_context/

test.sh_output.txt contains the script output while test.sh_debug.txt contains a lot more debug output.

I believe @nmittler did the test writing so could talk some more about it.

I don't know enough about how things are done during the test with labeling etc. Prior to this I would test this manually using clusters I spun up in different regions.

**Comment by ericvn** [comment]
So I did try and see if a revert might fix the problem by building and pushing the current `master` to images in my private repo. Because they were in my repo, my IKS (or kind) clusters should able to pull them so expecting the tests should able to find them. Running the tests and describing istiod in the test cluster shows the built images are being used. The test did fail the same as it is in the pipeline (roughly 1/3 of requests going to each zone). I manually applied the revert locally and built and pushed new images. When I ran the test again, it also failed. I suspect that the revert might not be the answer.

**Comment by ramaraochavali** [comment]
@ericvn Thank you for testing it. I was also wondering how this could have caused this. Since you are able to run the tests, is it possible to capture config_dumps on both 1.9 and 1.8 to see if any thing is different? If there is no difference, probably localities are not coming correctly or some thing changed in Envoy?

**Comment by ericvn** [comment]
Just a pointer to the dumps I believe you wanted in https://github.com/istio/istio/issues/30181. Making sure the issue and PR at least get linked.

**Comment by ramaraochavali** [comment]
I am closing this PR as @hzxuzhonghu found the root cause for the failure.

**Pull request closed without merging**
