### PR TITLE
hard disable sidecar injection in istio-cni pods

### PR DESCRIPTION
**Pull request by tariq1890**
I use Istio in a namespace other than `istio-system`, it would be good to have this annotation as with the other istio-related resources

### CODE REVIEW

**Comment by tariq1890** [comment]
@howardjohn thoughts?

**Review by dgn — APPROVED** [review]
LGTM. I put it on hold so @howardjohn has a chance to review as you explicitly asked for his feedback

**Comment by tariq1890** [comment]
I had only pinged him since I was requesting attention on this PR. I believe he's on vacation. If you think this PR is fine, I think we can merge it :)

**Comment by tariq1890** [comment]
Thanks for the review @dgn !

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
