### PR TITLE
Fix data races in tests

### PR DESCRIPTION
**Pull request by ozevren**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ozevren** [comment]
@howardjohn Any chance you can give this PR a whirl in your (Linux) system to see if you run into any issues? This should fix all race/flake issues in the config package. However, I only have a Mac to test it, so I'd like to get some confirmation from a Linux box before checking this in.

**Comment by howardjohn** [comment]
@ozevren yes ill try it out

**Comment by howardjohn** [comment]
lgtm

**Pull request merged**
