### PR TITLE
Fix nil stackdriver environment variables

### PR DESCRIPTION
**Pull request by gargnupur**
Fix nil stackdriver environment variables. 
Ref: https://github.com/istio/istio/issues/18680

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
Need port to istio/installer

**Comment by gargnupur** [comment]
> Need port to istio/installer

@howardjohn : where do we need to make changes for that?

**Comment by gargnupur** [comment]
@mandarjog : cherrypick this to 1.4?

**Pull request merged**
