### PR TITLE
ShellCheck: Enable and fix SC1090 and SC1091

### PR DESCRIPTION
**Pull request by Tahler**
Enable and fix [SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090) and [SC1091](https://github.com/koalaman/shellcheck/wiki/SC1091). Both are related to verifying how scripts are used as dependencies (through `source` or `.`).

Many scripts, such as `$HOME/.istiorc` do not exist in the repository so those instances are disabled.

These are the final two violated rules for ShellCheck 5.0!

/cc @mandarjog
/assign @mandarjog

### CODE REVIEW

**Comment by rshriram** [comment]
can you move the ShellCheck job into lint? Don't want to overload circleci with lots of tiny jobs.

**Comment by Tahler** [comment]
@rshriram That will make it required, right? Is that what we want?

**Comment by rshriram** [comment]
This is lint in some form. And once we fix all existing shell checks, any future additions of shell scripts needs to follow some sane format for readability, etc. So, might as well add this to the lint. If it fails constantly, we can disable it or move it to separate test

**Pull request merged**
