### PR TITLE
Enable prometheus rewrite by default

### LINKED ISSUE #21366: Configure standard prometheus annotations for Istio scraping
Here is the idea:
We put standard annotations on control plane/ingress like `prometheus.io/port`. This gives us scraping out of the box without requiring users to use our custom scraping configs
For sidecars, the problem is the user application may also have metrics. We don't want to just mangle their annotations. Instead, we can have an aggregation layer in pilot-agent. The idea is we configure prometheus to scrape :15020/stats through annotations. If the use had these labels already set, we add these as env vars on the pod. When :15020/stats is called, we will take :15000/stats, the user defined application metrics, and pilot-agent metrics (not currently exposed), and merge them into one response to prometheus.

Benefits:
* We no longer need to maintain a custom prometheus scraping config. Users can just install Istio, and their existing prometheus config will start scraping out of the box
* Reduce the load on prometheus. Currently prometheus is calling the same pod 2x, one for envoy metrics and one for application metrics
* Expose pilot-agent metrics. Currently we do not do this
* Resolve the strict mTLS issue. Out of the box we will use plaintext for prometheus scraping even if strict mTLS is used. This won't work for all users needs, so for those cases we can also lock this down (then the user would be required to set up the certs for prometheus)

Risks:
* This may change the shape of metrics that are reported to Prometheus
* Unclear if there is a safe way to merge prometheus metrics
* Need to ensure we don't up a security hole by trampolining off pilot-agent to application, bypassing rbac, etc.
* This idea is mentioned in a design doc here: https://docs.google.com/document/d/1S6O1czHtjR2DGfK2zeZDLr88wxyLRXB2JpH5g7YM1J8/. It is regarded a a bad idea.
* The `prometheus.io` labels are just a standard practice, they are not a part of prometheus - what happens if user uses different configs? Will we break them? will we lose metrics?

### LINKED ISSUE #21457: Stop running Envoy during prometheus sidecar
Right now we have a very complex setup just to get prometheus a certificate. We run Envoy, then envoy connects to pilot, then pilot sends SDS config for secret `default`, then envoy sends an SDS requests to the agent, then the agent fetches the secret and writes it to a file.

This is incredibly complicated just to fetch a file and write it to disk. All we need to do is

```
callCsr()
writeToDisk()
go func() {
  every once and a while {
     refresh cert
   }
}
```

The installation can be as simple as 
```
- name: istio-proxy
image: proxyv2
command: agent --only-dump-cert
```

rather than the huge amount of yaml config we provide today

### LINKED ISSUE #21720: Remotely accessing telemetry results in error indications in Prometheus
**Bug description**
I executed the task here: https://preliminary.istio.io/docs/tasks/observability/gateways/ (only the HTTP portion). While HTTP worked, it appears as though Prometheus has some form of error.

**Expected behavior**

No errors reported within Prometheus.

**Steps to reproduce the bug**

Follow the task. Open Chrome to port 15031 of the ingress gateway. Select `Status->Targets`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0 beta 5

**How was Istio installed?**
via standalone operator

**Environment where bug was observed (cloud vendor, OS, etc)**
K8s 1.17.2 Bare Metal + Metallb 0.8.3 + calico 3.8 via kubeadm

screenshot:
Screen Shot 2020-03-02 at 12 29 30 PM

PDF of prometheus page: 
[PrometheusTargets.pdf](https://github.com/istio/istio/files/4277487/PrometheusTargets.pdf)

### LINKED ISSUE #21986: istio 1.5 prometheus target errors
**Bug description**
Prometheus target errors in 1.5 Prometheus installation

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
There should be no target errors
**Steps to reproduce the bug**
Install demo profile and go to the Prometheus UI target.this seems harmless though it is a terrible experience.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
istioctl demo profile installation

**Environment where bug was observed (cloud vendor, OS, etc)**
KOPS AWS 
Screen Shot 2020-03-09 at 10 58 48 am

### PR DESCRIPTION
**Pull request by howardjohn**
This feature was release in 1.6 off by default. Now that 1.6 is branched we can turn it on by default for 1.7 now to maximize testing

Fixes https://github.com/istio/istio/issues/21457
fixes #21366
Fixes https://github.com/istio/istio/issues/21986
Fixes https://github.com/istio/istio/issues/21720

### CODE REVIEW

**Comment by howardjohn** [comment]
/retest

inrfa flake

**Comment by douglas-reid** [comment]
Do we know of any particular users that exercise this feature yet?  Curious about getting early feedback.

**Comment by howardjohn** [comment]
@douglas-reid not yet, it was only in 1.6 which hasn't released. Maybe @kramvan1 can give some feedback if he has a chance to try this out, as I recall he had an issue upgrading to v2 telemetry because this was missing

**Review by costinm — COMMENTED** [review]
Can you make sure MeshConfig defaults match ? 

I suspect the only reason we need it in the yaml file is to support the prometheys template conditional ? 
Could we remove it from global.yaml ( since the default is set in MeshConfig ) and add a specific flag in prometheus template to turn off ?

**Comment by howardjohn** [comment]
@costinm its used in every template since it also controls if prometheus.io annotations are added to gateway/pilot/mixer/etc

**Comment by howardjohn** [comment]
/retest

unrelated test flake

**Comment by howardjohn** [comment]
fixes https://github.com/istio/istio/issues/21366

**Comment by nrjpoddar** [comment]
I'm not sure if approving this now seems appropriate. We haven't yet shipped a release with this functionality (default off) or got any feedback from users.

I feel we need to wait before enabling this by default.

**Comment by howardjohn** [comment]
@nrjpoddar what better way is there to get people to use it then make it default? That gives us 3+ months to revert if we see any issues. Also note this was very close to being approved as enabled by default in 1.6

We also have clear feedback that *not* having this enabled doesn't work - see the issues this fixes

**Comment by kramvan1** [comment]
+1 @howardjohn   This needs to be the default.   Will for one will be trying this out for 1.6.

**Comment by douglas-reid** [comment]
@howardjohn i'll raise this tomorrow in the P&T WG to get consensus.

**Comment by nrjpoddar** [comment]
I forget that this will be part of 1.7 and not cherry-picked to a patch release. I'm good with making it default for 1.7.

**Review by mandarjog — APPROVED** [review]
lgtm

decided at the Telemetry WG meeting.

**Comment by mandarjog** [comment]
@myidpt This is now OK per P&T, please review and approve. Thanks.

**Review by myidpt — APPROVED** [review]

**Comment by myidpt** [comment]
Synced with Jianfei. He's aligned with the idea.

**Review by costinm — APPROVED** [review]

**Pull request merged**
