### PR TITLE
Remove conformance test suite

### PR DESCRIPTION
**Pull request by howardjohn**
This test currently has two purposes:

* Testing MCP source. This is no longer a supported feature
* Testing traffic. There is currently one traffic test, that is a
duplicate of routing_test.go

Based on this, I don't think its worth the complexity to keep it around.
Opening this as a PR instead of an issue as its trivial to `rm -r` the
code - would like to get peoples opinions on this.

My personal thoughts are that this is providing us 0 value but has a
maintainence and CI cost, so its not worth keeping around.

### CODE REVIEW

**Comment by kishorejonnala** [comment]
@howardjohn  Can you suggest what would be the best alternative to this test suite to run on a local kubernetes environment.

**Comment by kishorejonnala** [comment]
@howardjohn  Can you suggest an alternative to conformance test suite which is removed here, to run on a local kubernetes environment.

**Comment by howardjohn** [comment]
You can run all of the tests under test/integration

**Comment by kishorejonnala** [comment]
Wouldn't that be a lot more time consuming than just running one test-suite alone? I was hoping there is a subset of these tests which would cover most of the functionality.

**Comment by howardjohn** [comment]
It would be more time, yes. But the test was removed because it provides
essentially no coverage at all, so while it was fast it wasn't really
proving much for correctness

**Pull request merged**
