### PR TITLE
Implement service selector for gateway

### PR DESCRIPTION
**Pull request by howardjohn**
Implements https://docs.google.com/document/d/1gDhj058q2PKKI9SWpxE23ExEXdOkLiueT8JA_oEJ8Mo/edit#

Changes since the original design:
* Default gateway service (https://docs.google.com/document/d/1gDhj058q2PKKI9SWpxE23ExEXdOkLiueT8JA_oEJ8Mo/edit#heading=h.1k50uys9xuhy) not yet implemented
* Route name will change (https://docs.google.com/document/d/1gDhj058q2PKKI9SWpxE23ExEXdOkLiueT8JA_oEJ8Mo/edit#heading=h.fcde4dlwfl1e)

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
/test all

**Review by costinm — APPROVED** [review]

**Pull request merged**
