### PR TITLE
[release-1.18] Always send new healthy endpoints

### LINKED ISSUE #48458: [release-1.18] Always send new healthy endpoints
Manual cherrypick required.

#48408 failed to apply on top of branch "release-1.18":
```
Applying: always send new healthy endpoints
.git/rebase-apply/patch:69: trailing whitespace.
issue: 
warning: 1 line adds whitespace errors.
Using index info to reconstruct a base tree...
M	pilot/pkg/model/endpointshards.go
M	pilot/pkg/xds/eds_test.go
Falling back to patching base and 3-way merge...
Auto-merging pilot/pkg/xds/eds_test.go
Auto-merging pilot/pkg/model/endpointshards.go
CONFLICT (content): Merge conflict in pilot/pkg/model/endpointshards.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 always send new healthy endpoints
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by dddddai**
**Please provide a description of this PR:**
Fixes #48458

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Ambient
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by hanxiaop — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
isn't 1.18 EOL?

**Comment by hanxiaop** [comment]
> isn't 1.18 EOL?

Not quite sure yet, needs to confirm with @pmerrison . However I think it's ok to merge in case we are going to have a last release.

**Comment by hzxuzhonghu** [comment]
I am concerned if merged but no other newer release. Feel free to remove the hold once confirmed

**Comment by hanxiaop** [comment]
> I am concerned if merged but no other newer release. Feel free to remove the hold once confirmed

Sounds good. From here https://istio.io/latest/news/support/announcing-1.18-eol/, the EOL date for 1.18 is December 26. Hopefully, we can schedule one final release after that date.

**Comment by hanxiaop** [comment]
Let's merge this, I'll try to release 1.18.7

**Pull request merged**
