### PR TITLE
istioctl --xds-san and --insecure options for testing XDS

### PR DESCRIPTION
**Pull request by esnible**
Adds `--insecure` option to `istioctl x verify`.  This debugging option works the same as `--insecure` on _grpcurl_.

### CODE REVIEW

**Comment by esnible** [comment]
@costinm The option I have introduced, `--insecure`, causes the *client*, _istioctl_, to skip verifying the server certificate matches the server name.  `--insecure` doesn't affect the security provided by Istiod.  See https://github.com/istio/istio/pull/25197 for some logging to help diagnose.

There are three cases to consider.
- *Direct connection to XDS with real DNS hostname.*  Works as-is, without `--insecure`.
- *Direct connections to XDS, no real DNS*.  This is for testing.  User is running _pilot-discovery_ locally, on `localhost`, but it is presenting a cert for istiod.istio-system.svc.  I introduced `--insecure` for developers testing this case.  I chose to use `InsecureSkipVerify` from cypto/tls instead of using the XDSSAN you provided because pilot-discovery is not guaranteed to present a certificate for istiod.istio-system.svc
- *Connection via port-forward to XDS*.  When Istiod is on the customer's cluster we port-forward into it and connect ADSC to the `fw.Address()` which will be `localhost:<random>`.  This is the same as the case above.  I could use XDSSAN, but have no guarantee Istiod is identifying as istiod.istio-system.svc and not istiod-canary.istio-system.svc.

**Comment by esnible** [comment]
@costinm @howardjohn If you don't like `--insecure` I can replace

- `istioctl x version --xds-address localhost:15012 --insecure`

with

- `istioctl x version --xds-address localhost:15012 --xds-san istiod.istio-system.svc`

and get the functionality I need.  Is that the correct direction?

(The other direction is to get Istiod to offer a certificate identifying itself as `localhost`.  I don't know how to do that but I could learn.)

**Comment by costinm** [comment]
My comment was that we need both - insecure can be useful, but xds-san should be provided as an option, and the default value should be istiod.istio-system.svc ( i.e. same as the default value when we install istiod ).  Or even better: istiod-$REV.$ISTIO_NAMESPACE.svc - using the 'revision' and '-i' flags. If xds-san is provided - will be used instead of the default. 

I'm not against having an insecure as well, but not as the main option.

**Comment by costinm** [comment]
And certainly we shouldn't have istiod get a cert for localhost !

**Pull request merged**
