### PR TITLE
Migrate istio.io test for SDS to istioctl instead of helm template

### PR DESCRIPTION
**Pull request by dgn**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by nmittler** [comment]
@dgn, I'm not absolutely certain but I suspect this is breaking the secureSDS tests. Example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20040/integ-istioio-k8s-tests_istio/2920

Can you take a look or rollback?

FYI @howardjohn

**Comment by howardjohn** [comment]
SDS does not work with istioctl right now

**Comment by dgn** [comment]
Strange. This worked fine locally, using a slightly older version of istioctl I assume. Feel free to revert to unblock people, but IMO the real problem is that istioctl is broken. Will look into this tomorrow

**Comment by howardjohn** [comment]
1.5 SDS with istioctl is based on local SDS not using the nodeagent, so
there are some minor changes needed for the test/values passed to get that
working I think

**Pull request merged**
