### PR TITLE
Fix CNI environmental detection

### PR DESCRIPTION
**Pull request by howardjohn**
Notably, this makes IPv6 work with CNI

### CODE REVIEW

**Comment by bleggett** [comment]
If we could have caught this sooner by flipping on V6 support for an existing integ suite, maybe we just do that.

**Comment by kfaseela** [comment]
https://github.com/istio/istio/pull/51767/files is needed for the new job to kick start. Sorry for the trouble

**Comment by bleggett** [comment]
> Notably, this makes IPv6 work with CNI

(context for future travelers): This makes IPv6 work with _sidecar_ CNI, which has been broken (or rather, untested) for a while.

_Ambient_ CNI V6 support doesn't exercise this code path at all, and wouldn't be affected one way or the other.

Neither has test coverage yet tho, and things without test coverage don't work, as a matter of general principle.

This is actually why I want to unify the sidecar and ambient iptables logic (and associated netns detection/pod hopping logic) - they are entirely separate logic paths ATM in the same component, this is unavoidably going to be a source of bugs.

**Review by bleggett — APPROVED** [review]

**Comment by kfaseela** [comment]
The ambient ipv6 test suite ran fine!!! i will make sure post submit tests are also fine in my other PR. Thanks a lot @howardjohn

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
