### PR TITLE
Remove redundant security tests

### PR DESCRIPTION
**Pull request by howardjohn**
These are testing SDS, and just do a simple call from client to server.
This is now the default config, so its covered by every other tests
already. Because of this, these are pretty much entirely redundant.

### CODE REVIEW

**Comment by myidpt** [comment]
I think we still want to keep the "control plane auth disabled" one?

**Comment by howardjohn** [comment]
We could, its still not actually testing anything though. This only controls communication to galley and mixer which are disabled in the test

**Comment by howardjohn** [comment]
TBD if we will remove this in `master` as well, I have it on the agenda for P&T + security meetings

**Comment by myidpt** [comment]
No, I think "control plane auth disabled" impacts how every sidecar talks to istiod, right? :)

**Comment by howardjohn** [comment]
```
$ diff <(go run ./istioctl/cmd/istioctl manifest generate) <(go run ./istioctl/cmd/istioctl manifest generate --set values.global.controlPlaneSecurityEnabled=false)
0a1
> 2020-03-03T01:18:47.926148Z   warn    feature validation: security: auto mtls is enabled, but control plane security is not enabled
7471c7472
<         - --secureGrpcAddr=:15011
---
>         - --secureGrpcAddr=
7608c7609
<         "controlPlaneSecurityEnabled": true,
---
>         "controlPlaneSecurityEnabled": false,
```

It only opens up a new port that 1.4 pods will use to connect to Istiod. it is NOT used by new proxies. We can remove it in master as well

**Comment by myidpt** [comment]
OK I see. So the workloads will always talk to istiod via mTLS. That's good.

**Pull request merged**
