### PR TITLE
Operator - expose generic function and improve helmreconciler reusability

### PR DESCRIPTION
**Pull request by deva26**
We would like to reuse helmreconciler and translate packages for our custom operator solution and want to generalise the packages by exposing a couple of generic functions. The changes are minimum and local without virtually any impact to the existing operator code base. 
It is understood that there is no guarantee for third party integrations and  this code may break anytime.

Summary of the changes in this PR:
**package translate: (exposed function)**
MergeK8sObject and ProtoToHelmValues from translate package. They are generic and useful to be called from third party applications. This change is local.

**package helmreconciler:**
To the function NewHelmReconciler added the other parameters RenderingCustomizer and Client for more utility value. This change is very local with minimum impact.
HelmReconciler struct - changed member instance from type *iop.IstioOperator to runtime.Object. This change allows helmreconciler package to be more generic and making code reusable through embedding.Checks are already in place to verify if the instance is of type *iop.IstioOperator before using it. So this change has very minimum impact.

### CODE REVIEW

**Comment by deva26** [comment]
ping @istio/wg-environments-maintainers

**Comment by deva26** [comment]
ping @istio/wg-environments-maintainers

**Comment by ostromart** [comment]
No objection to the change but I'd feel more comfortable approving this when https://github.com/istio/istio/pull/22477 goes in, since we don't have a real e2e test for the controller until it does. Can this wait a few days for that to merge and tests to be running?

**Comment by deva26** [comment]
Hi Martin,
This change is a bit urgent and we can't wait that long for the other PR. We are happy to add e2e test cases after the merge, if need be. Thanks for your attention.
Regards.

**Review by ostromart — APPROVED** [review]

**Pull request merged**
