### PR TITLE
Remove unused helm makefile

### PR DESCRIPTION
**Pull request by jacob-delgado**
Unused makefile for helm.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by jacob-delgado** [comment]
It's possible that this file is used somewhere I'm not familiar with.

**Review by howardjohn — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
