### PR TITLE
Add arg in istioctl manifest generate for specific components

### PR DESCRIPTION
**Pull request by elfinhe**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by morvencao — APPROVED** [review]

**Comment by howardjohn** [comment]
What is the use case? I am a bit concerned it is offering two (really 3) ways to do the same thing and doesn't have a matching config in the IOP so the ux is inconsistent

**Comment by elfinhe** [comment]
> What is the use case? I am a bit concerned it is offering two (really 3) ways to do the same thing and doesn't have a matching config in the IOP so the ux is inconsistent

What are the other two options to do the same? The use case - for those who only want to inspect one component for example ingressgateway without looking through a long manifests.

**Comment by howardjohn** [comment]
components.x.enabled and values.x.enabled do similar. Does this only apply
for generate and not install?

**Comment by elfinhe** [comment]
Yep, only for istioctl manifest generate, not for istioctl install or operator.

**Comment by howardjohn** [comment]
it seems confusing to me to not have the same options for the two. The
inconsistency between all of the manifest commands is just finally in a
state where its improving

**Pull request merged**
