### PR TITLE
samples: Expose some metrics from productpage app

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>

**Please provide a description of this PR:**

This simple change will make it possible to test merged metrics or scrape metrics with mTLS.

### CODE REVIEW

**Comment by ericvn** [comment]
Some input from @istio/wg-policies-and-telemetry-maintainers

**Review by lei-tang — COMMENTED** [review]
Thanks for the PR! 

> "This simple change will make it possible to test merged metrics or scrape metrics with mTLS."

Do you have a PR for the corresponding user guide? For example, how to test the metrics exposed? How to scrape metrics with mTLS?

**Comment by jewertow** [comment]
> Do you have a PR for the corresponding user guide?

No, I don't. I was thinking about it, but I wasn't sure if this is necessary, because there already is a guide about configuring [Prometheus to use mTLS](https://istio.io/latest/docs/ops/integrations/prometheus/#option-2-customized-scraping-configurations). The only missing thing in that section is a relevant job to scrape application metrics. I didn't extend that example, because I'm using Prometheus Operator and ServiceMonitor, but I could do it as a follow-up.

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: custom-prometheus
spec:
  securityContext: {}
  serviceAccountName: prometheus-k8s
  podMonitorSelector: {}
  podMonitorNamespaceSelector:
    matchNames:
    - custom-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector:
    matchNames:
    - custom-prometheus
  podMetadata:
    annotations:
      sidecar.istio.io/inject: "true"
      # do not intercept any inbound ports
      traffic.sidecar.istio.io/includeInboundPorts: ""
      # do not intercept any outbound traffic
      traffic.sidecar.istio.io/includeOutboundIPRanges: ""
      # configure an env variable `OUTPUT_CERTS` to write certificates to the given folder
      proxy.istio.io/config: |
        proxyMetadata:
          OUTPUT_CERTS: /etc/istio-output-certs
      # mount the shared volume at sidecar proxy
      sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
  volumes:
  - name: istio-certs
    emptyDir:
      medium: Memory
  volumeMounts:
  - mountPath: /etc/prom-certs/
    name: istio-certs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-metrics-monitor-mtls
  namespace: custom-prometheus
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: productpage
  namespaceSelector:
    matchNames:
    - bookinfo-2
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true
```

**Comment by lei-tang** [comment]
From the technical perspective, the PR LGTM. I will defer to the doc maintainers for reviewing the user guide of the configurations proposed in the PR.

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
