### PR TITLE
Graduate convert-ingress, dashboard, and metrics

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/istio/issues/15973 by moving three commands out of experimental, adding a notice to experimental that the commands have moved, and adding a note to non-experimental about "auth" which did not move.

### CODE REVIEW

**Comment by esnible** [comment]
@howardjohn Can you re-add the CLA?  It was removed when I rebased.

**Comment by howardjohn** [comment]
Somehow 1.3 tests are being run here? something went funky

**Comment by esnible** [comment]
@howardjohn What should I do about the 1.3 tests?  I suspect that I edited the title and changed the target from master to 1.3 and back by accident.

**Comment by howardjohn** [comment]
I tihnk its fine ,they aren't marked as required

**Pull request merged**
