### PR TITLE
Fix broken link in README.md

### PR DESCRIPTION
**Pull request by haorenfsa**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by rshriram — APPROVED** [review]

**Review by sdake — DISMISSED** [review]
Thank you for your contribution. Please remove the word "standalone" from line 81.

Cheers,
-steve

**Comment by sdake** [comment]
I am not a reviewer for the top level readme, so I have placed a hold on the review until line 81 is fixed. After that is fixed, if you re-review, feel free to remove the hold.

**Comment by haorenfsa** [comment]
> Thank you for your contribution. Please remove the word "standalone" from line 81.
> 
> Cheers,
> -steve

done

**Comment by sdake** [comment]
Thank you for the improvement!

**Pull request merged**
