### PR TITLE
Istio Performance Dashboard

### PR DESCRIPTION
**Pull request by mandarjog**
* Istio cpu cost per 1k requests
* Istio memory costs - This is a bit tricky to include 1k requests across the board. Mixer is normalized with number of requests. Proxies are normalized across number of proxies.
* Add bytes transferred
* Add total Istio CPU consumed by datapath components.

https://snapshot.raintank.io/dashboard/snapshot/3SROmk1jM5oJ48BLm7rkh6PMujvtufnU

### CODE REVIEW

**Comment by mandarjog** [comment]
@suryadu @jnativio

**Comment by jnativio** [comment]
@mandarjog  I made a modification in the queries to deal with the lack of traffic problem, when the dashboards for cpu and mem / 1k rps report extremely high values. Basically, I divided the original statements by: 

(sum(irate(istio_requests_total{source_workload="istio-ingressgateway"}[1m])) >bool 10)

, which gives 0 if the traffic in the ingress is below 10 tps and 1 if is above (arbitrary value). I found out it is okay to divide by zero: the datapoints just do not show up. Another alternative is to multiple by it, then chart goes to zero when there is no traffic.

See the original and modified charts below, with periods of traffic and no traffic:

image

In the original ones you cannot see the curve during traffic periods because it is overwhelmed by the "fake" values of no traffic periods. Still seeing some issues in my environment with high traffic. It appears the is no report when cpu usage is too high.
Also, does it make sense the memory usage per 1k rps metric? It seems you are going to get very different values depending on the  traffic volume.

**Comment by douglas-reid** [comment]
The dashboard looks good to me.

One thing you may want to consider is adding a panel that links to a description of the metrics and how to interpret the values. This description would, ideally, live on istio.io, but could be a wiki link or whatever too.

**Comment by mandarjog** [comment]
@jnativio you have a good point. Can you submit a followup PR to this?
I would like to get this in. Thanks.

**Pull request merged**
