### PR TITLE
adding workloadIP to istioctl config workload

### LINKED ISSUE #32462: Setting workloadIP when configuring workloads
By default, when creating the configuration for a workload:
```
istioctl --context="cluster1" x workload entry configure \
    -f workloadgroup.yaml -o ./workload-files/ \
    --clusterID "cluster1" \
    --autoregister
```
We set up all the configurations needed for registering to the remote cluster. The issue is that as an IP address is determined by:
```
ISTIO_SVC_IP=$(hostname --all-ip-addresses | cut -d ' ' -f 1)
```

This works fine when the workload is in the same network but not when it is in a separate network.

We need a argument to specify the workload IP manually

### PR DESCRIPTION
**Pull request by rinormaloku**
This PR resolves #32462 

[x] User Experience

[x] Does not have any changes that may affect Istio users.

---
This update adds the ability to specify the workload IP when configuring a new VM-based workload.

By default, when creating the configuration for a workload:
```
istioctl --context="cluster1" x workload entry configure \
    -f workloadgroup.yaml -o ./workload-files/ \
    --clusterID "cluster1" \
    --autoregister
```

We set up all the configurations needed for registering to the remote cluster. The issue is that as an IP address is determined by:
```
ISTIO_SVC_IP=$(hostname --all-ip-addresses | cut -d ' ' -f 1)
```
This works fine when the workload is in the same network but not when it is in a separate network. 

With the update you can define the workload IP manually:
```
istioctl --context="cluster1" x workload entry configure \
    -f workloadgroup.yaml -o ./workload-files/ \
    --clusterID "cluster1" \
    --workloadIP "108.47.9.33" \
    --autoregister
```

### CODE REVIEW

**Comment by howardjohn** [comment]
@liminw were you looking into something similar?

**Comment by howardjohn** [comment]
LGTM, letting @stevenctl take a look as well before approving

**Comment by brian-avery** [comment]
Should we consider this behavior to potentially affect users since it adds a new  istioctl argument that they can use?

**Review by stevenctl — APPROVED** [review]
LGTM – only nit: consider not creating the file if it's going to be empty?

**Comment by brian-avery** [comment]
Based on https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes, I think this needs a release note

**Review by shamsher31 — APPROVED** [review]
Please add a release notes. Thanks.

**Comment by rinormaloku** [comment]
@stevenctl updated to address your nit :P

@shamsher31  and @brian-avery added the release note

**Review by howardjohn — APPROVED** [review]

**Comment by stevenctl** [comment]
Should be good to remove the hold @rinormaloku ?

**Comment by rinormaloku** [comment]
@stevenctl according to me yes.

**Pull request merged**
