### PR TITLE
[Release 1.5] Make mounted mTLS key and certs optional.

### PR DESCRIPTION
**Pull request by myidpt**
Cherrypick https://github.com/istio/istio/pull/20786 to 1.5 branch.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by dgn** [comment]
Is this required for 1.5?

**Comment by howardjohn** [comment]
this is required. without this expired certificates will be mounted and in
45 days everys certs will expire and break their cluster

**Comment by myidpt** [comment]
@dgn Can we merge this in? Thanks!

**Comment by myidpt** [comment]
Put on hold. I need to check with @mandarjog whether we also need to take care of the MixerV1 secret volume mounts.

**Comment by howardjohn** [comment]
if you want mixer with control plane security you need citadel (is how it works now, anyways)

**Comment by myidpt** [comment]
Unblock this PR. I will track how we can run Mixer with istiod.

**Pull request merged**
