### PR TITLE
cleanup pkg/monitoring

### PR DESCRIPTION
**Pull request by zirain**
**Please provide a description of this PR:**

- remove unused hooks
- remove unused int64 options

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
The hooks was intended for vendor extensions: https://github.com/istio/pkg/pull/142. Perhaps not a compelling motivation to keep it, but we are using it in our builds.

**Comment by zirain** [comment]
> The hooks was intended for vendor extensions: [istio/pkg#142](https://github.com/istio/pkg/pull/142). Perhaps not a compelling motivation to keep it, but we are using it in our builds.

can you share more details about it, need consider about it when moving to `prometheus/client_go` or `opentelemetry-go`

**Comment by howardjohn** [comment]
> > The hooks was intended for vendor extensions: [istio/pkg#142](https://github.com/istio/pkg/pull/142). Perhaps not a compelling motivation to keep it, but we are using it in our builds.
> 
> can you share more details about it, need consider about it when moving to `prometheus/client_go` or `opentelemetry-go`

Yes, we offer a different set of metrics: https://cloud.google.com/monitoring/api/metrics_istio#istio-istio. So we have hooks to capture one metric and increment another with a different name/tags/etc. So I would like to keep as much of that complexity in our own code to avoid making OSS more complex but we will need some way to retain that. Can I do a bit of research and get back to you?

Re int64 - I am actually not sure we need that at all even today, will check that.

In abstract I feel like we want some very very lightweight pluggable mechanism. Like in pkg/log we have TeeToStackdriver, we should probably make it just a lightweight pluggable mechanism using slog middleware (when we do https://github.com/istio/istio/issues/44683). Not sure how that fits into metrics though

**Comment by zirain** [comment]
> Can I do a bit of research and get back to you?

Looking forward to your investigation conclusion

**Comment by howardjohn** [comment]
For background knowledge, in prom float64 == int64. In Stackdriver they are not though

Ok found our current usage:
1. We have some new metrics. We report to SD int64 schemas, so we use the WithInt64Values option.
2. We have some derived metrics, where we use RecordHook to add some new metrics. Note these only use OnRecordFloat64Measure since all existing metrics are Float64 based.

Case (1) is easier to manage - if needed we can just have all our own code for these.

Case (2) is a bit harder if we merge this, not sure how this would be done

**Comment by zirain** [comment]
for case2, what's google's plan after July 31st, 2023? move to [OpenTelemetry-go bridge](https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge)?

**Comment by howardjohn** [comment]
I will do a prototype of using otel and see how it goes

**Comment by zirain** [comment]
replaced by https://github.com/istio/istio/pull/45341

**Pull request closed without merging**
