### PR TITLE
Add/Increase retry timeout due to delay for GKE on AWS platform in config propagation

### PR DESCRIPTION
**Pull request by Adarsh-Prakash-Agarwal**
Add/Increase retry timeout due to delay in config propagation for GKE on AWS platform

### CODE REVIEW

**Review by hemendrateli — APPROVED** [review]

**Comment by hemendrateli** [comment]
> what do you mean `GKE on AWS platform`

We basically create k8s clusters on AWS VM instances and use Elastic load balancers.

**Comment by hzxuzhonghu** [comment]
so the `config propagation` is not istio, but aws, right?

/retest

**Comment by hemendrateli** [comment]
> so the `config propagation` is not istio, but aws, right?
> 
> /retest

It is due to using AWS load balancer.

**Review by hzxuzhonghu — APPROVED** [review]
LGTM Since it increase test delay for github tests

**Comment by Adarsh-Prakash-Agarwal** [comment]
@hzxuzhonghu how can we cherry pick this to 1.23 branch?

**Pull request merged**
