### PR TITLE
Allow Helm users to specify sds secrets lookup namespace

### PR DESCRIPTION
**Pull request by mmckane**
The TLS Secrets lookup namespace is currently hard coded to look for TLS secrets in the same namespace as the gateway. This PR allows users to define a specific namespace to lookup secrets that isn't necessarily in the same namespace as the gateway. This will allow users to create specific namespaces to specifically store certificates that have tightly controlled access via RBAC and automation, while still allowing users to deploy gateways in their own namespaces.

### CODE REVIEW

**Comment by mmckane** [comment]
Is anyone available to review this?

**Comment by howardjohn** [comment]
I am not sure if this is still relevant, but unfortunately I don't think this is going to be reviewed as its so old it has been forgotten

**Pull request closed without merging**
