### PR TITLE
enable ISTIO_MULTIROOT_MESH by default

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Please provide a description of this PR:**

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
I am not so sure about the stability or quality of this feature, can investigate a bit more before we merge?

**Comment by costinm** [comment]
Agree, also not sure about the documentation around this feature.

AFAIK we have supported 'multiple roots' since the beginning of the project
- the ca pem can include
more than one CA cert, including different types (RSA/EC256). Even this
feature is under-documented.

We have a huge number of options and complexity around CAs even with the
current defaults.

I would also like confirmation that ztunnel ( and perhaps proxyless gRPC or
similar apps natively using
istio certs) are able to handle this feature.

**Comment by hzxuzhonghu** [comment]
There are integration tests running for years. 

>I would also like confirmation that ztunnel ( and perhaps proxyless gRPC or
similar apps natively using
istio certs) are able to handle this feature.

I think standard language tls implement can support this, i have tried golang with this.

**Comment by howardjohn** [comment]
> There are integration tests running for years.
> 
> > I would also like confirmation that ztunnel ( and perhaps proxyless gRPC or
> > similar apps natively using
> > istio certs) are able to handle this feature.
> 
> I think standard language tls implement can support this, i have tried golang with this.

Ztunnel and proxyless do not handle PCDS.

I am concerned that we will enable this PCDS which is confusing, wasteful, and risky, for users who do not use multiroot -- which is >99% of users.

For example, with DNS proxy, users need to opt in to get NDS

**Comment by costinm** [comment]
It's not if they can implement - anything can be implemented.

The issue is if they _want_ to implement istio-specific things - and
usually the answer is no.
Even for ztunnel we are trying to keep things simpler.

I still don't even fully understand what multiroot does and how is it
different from having multiple roots in the CA file...

**Comment by howardjohn** [comment]
I think the root cert distribution we have is pretty weird overall. We get the root by looking at the cert we got back from the CSR. What if the peers have a different root? What if we need to update the root? What if we are ztunnel, and have many certs, and they have different roots?

All questions caused by our 'unique' model. I think others are just doing a stream of root certs or similar. Which maybe we do, and just make it always behave that way, not just for 'multiroot'. And then maybe it makes sense beyond sidecars, and in ztunnel and beyond. But another question -- should this be pushed by the XDS server or the CA?

**Comment by hzxuzhonghu** [comment]
I can recall multi-root is for mesh federation, so within it enabled, multi mesh can communicate with each other. Unlike DNS proxy, the motivation to make it by default is that if we donot use pcds, it has no effect on proxies.

Not sure ambient will support this feature in future, at least not now.

**Pull request closed without merging**
