### PR TITLE
Allow extra spaces between namespaces in networking.istio.io/exportTo annotation

### PR DESCRIPTION
**Pull request by yfuruyama**
**Please provide a description of this PR:**

This PR allows users to put extra spaces between namespaces in `networking.istio.io/exportTo` annotation.

Currently, adding extra spaces between namespaces in `networking.istio.io/exportTo` annotation causes unexpected behavior. For example, `networking.istio.io/exportTo: ns1, ns2` is recognized as `ns1` and ` ns2` namespaces (Note the extra space in `ns2` namespace), and as a result it's not exported to `ns2` namespace properly.

This PR trims the extra spaces after splitting the value into multiple items. In Kubernetes, Namespace must be [RFC 1123 label name](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns), so this doesn't break backward compatibility.

Fix: #53429

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]

**Comment by yfuruyama** [comment]
@MorrisLaw Thank you for approving this PR. It looks like we need two additional reviews for this PR. Could you help me assign reviewers?

**Comment by yfuruyama** [comment]
@howardjohn Hi John, could you help review this PR?

**Comment by yfuruyama** [comment]
I added a release note as a "feature" kind because current behavior doesn't clearly look like a bug, but please let me know if I should change the kind to "bug-fix".

**Comment by yfuruyama** [comment]
@istio-testing /retest

**Review by ramaraochavali — APPROVED** [review]

**Pull request merged**
