### PR TITLE
Fix error when calling lua script for fixed window in redisquota adapter

### PR DESCRIPTION
**Pull request by gargnupur**
Fix error when calling lua script for fixed window in redisquota adapter
Add an e2e test for fixed window rule too

### CODE REVIEW

**Comment by mandarjog** [comment]
Can you explain why math.floor is needed?

**Comment by gargnupur** [comment]
@mandarjog : math.floor is needed because error from redis was that "it's not an integer or out of range". Based on numbers I saw for infoExpire and timestamp, it was not out of range(https://docs.google.com/spreadsheets/d/1MqFKYZMpwd10RSXtimbQyU9uEkOYz1kCR_URgoOg1KE/edit#gid=1791955750).. but a float.

**Comment by costinm** [comment]
Please merge and retest (flaky tests should be fixed). 
Mixer reviewers - is it needed for 1.0 ? Anyone can approve/lgtm ?

**Comment by gargnupur** [comment]
Rebased the PR

**Comment by gargnupur** [comment]
@costinm : when I ran it locally before, it was passing consistently.
Here also I saw once both redis tests pass and ingresscheckcache test fail, then one redis test failed and now both of them failed...

I am trying to see what has changed, couple of things I am noticing that are different from what I saw locally are as follows:
1) Multiple istio-telemetry instances
2) istio_requests_total reported by different instances

I will try to repro locally and see how it goes..

**Comment by gargnupur** [comment]
Test passes locally consistently, and last time all tests passed but it failed in clean-up of junit test case (I think)
I still made some calculations in redisQuota test more accurate based on source attribute only

**Comment by gargnupur** [comment]
@costinm : ok to merge now?

**Pull request merged**
