### PR TITLE
Fix missing blank line for Kiali to load properly during demo profile install

### LINKED ISSUE #7572: White Space error in the demo.yaml profile for 1.5 and 1.6 for linux x86
The last two lines for the demo.yaml file in the /manifest/profiles location has a missing nl/cr (mising blank line) that causes kiali not to load correctly. Due to not creating a kiali demo secret.

I had this problem with both 1.5 and 1.6 on a REHL platform using the newest version of Go and KinD.  

The "values" segment of the file looks like this:
```
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi

    pilot:
      autoscaleEnabled: false

    mixer:
      adapters:
        useAdapterCRDs: false
        kubernetesenv:
          enabled: true
        prometheus:
          enabled: true
          metricsExpiryDuration: 10m
        stackdriver:
          enabled: false
        stdio:
          enabled: true
          outputAsJson: false
      policy:
        autoscaleEnabled: false
      telemetry:
        autoscaleEnabled: false

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
    kiali:
      createDemoSecret: true

```

When you add the the blank line like this it deploys fine

```
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false

    kiali:
      createDemoSecret: true
```

Otherwise you get various errors that only sometimes reference a missing kiali secret and manually creating a secret doesn't help because it gets placed in the wrong location.

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio.io/issues/7572

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
How does this fix the problem? I read the issue but I don't understand it so I suspect this may not be the root cause?

**Comment by shamsher31** [comment]
I was not able to test it properly because of this issue https://github.com/istio/istio/issues/24323. pod crashes after 5 mins.

**Comment by shamsher31** [comment]
But I was able to reproduce it with 1.6.2.

```
Events:
  Type     Reason       Age    From                                  Message
  ----     ------       ----   ----                                  -------
  Normal   Scheduled    3m42s  default-scheduler                     Successfully assigned istio-system/kiali-d45468dc4-s4s5r to istio-testing-control-plane
  Warning  FailedMount  3m40s  kubelet, istio-testing-control-plane  MountVolume.SetUp failed for volume "kiali-secret" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  3m40s  kubelet, istio-testing-control-plane  MountVolume.SetUp failed for volume "kiali-cert" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  3m40s  kubelet, istio-testing-control-plane  MountVolume.SetUp failed for volume "kiali-configuration" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  3m40s  kubelet, istio-testing-control-plane  MountVolume.SetUp failed for volume "kiali-service-account-token-8p854" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulled       3m38s  kubelet, istio-testing-control-plane  Container image "quay.io/kiali/kiali:v1.18" already present on machine
  Normal   Created      3m38s  kubelet, istio-testing-control-plane  Created container kiali
  Normal   Started      3m38s  kubelet, istio-testing-control-plane  Started container kial
```

**Comment by howardjohn** [comment]
And this fixes it? I don't see how a new line can impact it though, yaml should not be impacted by this as far as I know..

**Comment by shamsher31** [comment]
Not sure, it needs more testing.

**Review by dgn — COMMENTED** [review]
I don't see how this would fix a broken kiali deployment

**Comment by dgn** [comment]
Looking at the original issue, it looks like quay.io was down, which happened a few times over the last few weeks. So it might have seemed to the creator of that issue that the blank line fixed the issue, it was simply connectivity issues

**Comment by shamsher31** [comment]
> Looking at the original issue, it looks like quay.io was down, which happened a few times over the last few weeks. So while it might have seemed to the creator of that issue that the blank line fixed the issue, it was simply connectivity issues that were resolved when they started the attempt with the blank line

I agree, that might be the case. As I mentioned I was not able to test it properly, so not sure whether the blank line will fix it or not. I will close it for now and we can re-open it if we will get a better fix. Thanks.

**Comment by Stormarov45** [comment]
> Looking at the original issue, it looks like quay.io was down, which happened a few times over the last few weeks. So while it might have seemed to the creator of that issue that the blank line fixed the issue, it was simply connectivity issues that were resolved when they started the attempt with the blank line

No, the issue is reproducible here still, and Quay was up the entire time since I could pull the image at any given time. 

This was not a fluke timing incident.

**Pull request closed without merging**
