### PR TITLE
Update Istio API dep SHA

### PR DESCRIPTION
**Pull request by ymesika**

### CODE REVIEW

**Comment by hklai** [comment]
Is this needed in release-1.1?

**Comment by ymesika** [comment]
@hklai this is needed for #9453 which is generally planned for 1.1 but I wouldn't add it yet.
I will ask you to pick it if/when the other PR is ready to make its way into 1.1.

**Comment by ymesika** [comment]
@hklai Can you please cherry pick this one into 1.1?
I will then submit the #9453 to `release-1.1` instead.

**Comment by hklai** [comment]
@ymesika it looks like @rshriram will do bulk merge from master to release-1.1 at some point.

**Pull request merged**
