### PR TITLE
ext-authz: add e2e tests and example configuration for local ext-authz server in the same pod

### PR DESCRIPTION
**Pull request by yangminzhu**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by yangminzhu** [comment]
@incfly @liminw could you help review the PR, this adds some more tests and examples, thanks.

**Review by liminw — APPROVED** [review]
/lgtm

**Pull request merged**
