### PR TITLE
fix: revision value should be respected for remote cluster svc/endpoint

### LINKED ISSUE #47552: Primary-Remote cluster in multiple network installation not working with revisioned control plane
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Following https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/
If the control plane is installed with revision, the remote cluster can not properly injected with sidecars. 

Observation:
If the remote cluster is installed with `--set revision=...`, the `MutatingWebhookConfiguration` would point to a `Service` `istiod-{revision}` but only `Service` created is `istiod`

If the remote cluster is installed without the revision, the webhook call would fail with the eastwest gateway on the primary cluster report
```
0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - {ip} {ip} istiod.istio-system.svc
```

which is not there since revisioned installation would not create `istiod` service but `istiod-{revision}` service.

### Version

```Text
client version: 1.18.2-asm.4
control plane version: 1.18.2-asm.4
data plane version: 1.18.2-asm.4 (2 proxies)

primary cluster version:

Client Version: v1.23.5
Server Version: v1.27.4-gke.1600
```

Remote cluster version
```
Client Version: v1.23.5
Server Version: v1.27.4-gke.1600
```
```


### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by xu-jianchu**
remote cluster with revision specificied should repsect the value. fix #47552

**Please provide a description of this PR:**

### CODE REVIEW

**Review by linsun — COMMENTED** [review]
lgtm - not sure if we have tests for this tho

**Comment by ymesika** [comment]
LG but you need to update the generated files as well.

**Comment by zirain** [comment]
you can run `make gen` locally, also add release notes for this.

**Comment by linsun** [comment]
@frankbu can you give a quick review to see if you have any concerns?

**Comment by xu-jianchu** [comment]
@frankbu gentle nudge on the review. Also is it ok I cherry-pick it to release 1.20?

**Comment by frankbu** [comment]
Should the documentation be updated to say (maybe a tip) that if exposing an istiod revision, you should configure the VS with `expose-istiod-rev.yaml.tmpl` instead of just `expose-istiod.yaml`?
https://preliminary.istio.io/latest/docs/setup/install/multicluster/primary-remote/#expose-the-control-plane-in-cluster1

**Comment by xu-jianchu** [comment]
Thanks @frankbu, I've created a separate PR to update the doc https://github.com/istio/istio.io/pull/14571

**Review by frankbu — APPROVED** [review]
> Thanks @frankbu, I've created a separate PR to update the doc https://github.com/istio/istio.io/pull/14571

Thanks, LGTM.

**Review by howardjohn — APPROVED** [review]

**Comment by xu-jianchu** [comment]
@frankbu Do you think there'll be any issue cherry-picking it to 1.20?

**Comment by frankbu** [comment]
@xu-jianchu I don't think there's any issues with cherry-picking this to 1.20, but note that the corresponding doc PR can't be cherry-picked to 1.20 once 1.21 is released (i.e., docs are only generated/updated for the current and next release).

**Comment by xu-jianchu** [comment]
@frankbu Thanks. I assume this PR alone can reduce one potential failure when installing remote clusters. If that's fine with you, should I reply with "/cherrypick release-1.20" to trigger it?

**Comment by frankbu** [comment]
> @frankbu Thanks. I assume this PR alone can reduce one potential failure when installing remote clusters. If that's fine with you, should I reply with "/cherrypick release-1.20" to trigger it?

Sure, fine with me. Go ahead and also do the `/cherrypick release-1.20` in the doc PR asap, so we can get it into the 1.20 docs before 1.21 is released.

**Comment by xu-jianchu** [comment]
@frankbu oh it seems like I can't not being member. Could you help? Thanks!

**Pull request merged**
