### PR TITLE
[release-1.24] enable configuration of global.proxy.outlierLogPath for waypoints

### PR DESCRIPTION
**Pull request by eitansuez**
**Please provide a description of this PR:**

fixes https://github.com/istio/istio/issues/54408

propagates helm configuration value outlierLogPath to waypoint template.

this PR is a cherry pick of this one that was merged into master last week (dec 12 2024): https://github.com/istio/istio/pull/54283

### CODE REVIEW

**Review by dhawton — CHANGES_REQUESTED** [review]
This should be made to the master branch first, then cherrypicked to release branches if it fixes a bug.

**Review by dhawton — APPROVED** [review]
clarified this is a cherrypick from a PR to master, asked to have title clarified

**Comment by eitansuez** [comment]
this PR addresses issue #54408

**Comment by eitansuez** [comment]
/release-note-edit ```Enables configuration of Helm value outlierLogPath for waypoints```

**Pull request merged**
