### PR TITLE
Add an e2e test for RedisQuota Adapter 

### PR DESCRIPTION
**Pull request by gargnupur**

### CODE REVIEW

**Comment by gargnupur** [comment]
@mandarjog @geeknoid : E2E test seems to be working for ROLLING_WINDOW algo.. should we try to push this further?

**Comment by mandarjog** [comment]
@gargnupur thanks for PR.
We need to make sure that there are at least 2 istio-policy pods available.
This ensures that we are testing redis quota in a realistic way. With a single pod, it is very similar to mem quota.

**Comment by gargnupur** [comment]
@mandarjog : I don't see two istio-policy pods:
gargnupur@gargnupur0:~/go/src/istio.io/istio$ kubectl get pods -n istio-system
NAME                                       READY     STATUS      RESTARTS   AGE
details-v1-57546d558d-dtl6t                2/2       Running     0          8m
istio-citadel-854fb94455-zwnjl             1/1       Running     0          9m
istio-cleanup-old-ca-pwbn6                 0/1       Completed   0          9m
istio-cleanup-secrets-8wmj2                0/1       Completed   0          9m
istio-egressgateway-7dc4889594-8w7pz       1/1       Running     0          9m
istio-galley-7c77946769-cs2qw              1/1       Running     0          9m
istio-ingress-54bf467988-w9h5d             1/1       Running     0          9m
istio-ingressgateway-68c86b8c54-w7wxz      1/1       Running     0          9m
istio-mixer-post-install-7vfgb             0/1       Completed   0          9m
istio-pilot-7f7845564-gp6sn                2/2       Running     0          9m
istio-policy-fd4c5f567-ncszw               2/2       Running     0          9m
istio-sidecar-injector-c46bc5c7d-wbjjx     1/1       Running     0          9m
istio-statsd-prom-bridge-949999c4c-v2h95   1/1       Running     0          9m
istio-telemetry-67c7c579b-lls4d            2/2       Running     0          9m
mongodb-v1-7b75bb78c6-tjwgx                2/2       Running     0          8m
productpage-v1-757bb75976-xthcg            2/2       Running     0          8m
prometheus-86cb6dd77c-95z4c                1/1       Running     0          9m
ratings-v1-7746bf494d-hm96l                2/2       Running     0          8m
ratings-v2-7c6495bdc9-z9xxb                2/2       Running     0          8m
reviews-v1-f4bcfd9fb-7zk4s                 2/2       Running     0          8m
reviews-v2-55cfd999fb-nvh44                2/2       Running     0          8m
reviews-v3-b8d4b75f6-g4fbm                 2/2       Running     0          8m
sleep-58546698bf-zwjht                     2/2       Running     0          8m

But when I tested I did see redisquota mixer returning resource exhausted errors

**Comment by mandarjog** [comment]
@gargnupur before starting this test, you should scale up istio-policy pod (or run 2 tests, one with pod scaled to 2, and one scaled to 1).

number of pods >1 is qualitatively important because we recommend customers using redis quota when pods are scaled up.

**Comment by gargnupur** [comment]
@mandarjog : e2e-dashboard test failed because of deadline error and mixer tests are passing now

**Pull request merged**
