### PR TITLE
test: prefer hbone by default

### PR DESCRIPTION
**Pull request by kyessenov**
checking coverage of hbone

### CODE REVIEW

**Comment by kyessenov** [comment]
Looks like a lot of stuff is broken with HBONE by default.
cc @hzxuzhonghu

**Comment by howardjohn** [comment]
Would be great to open an issue for these and start delegating them out and chipping away

**Comment by kyessenov** [comment]
@howardjohn Pilot tests alone have 840/1200 failing tests. I can take a look at policy & telemetry but there just seems to be some big gap somewhere.

**Comment by kyessenov** [comment]
Several issues noticed:
* HTTP MX is enabled for tunneled HTTP
* X-F-Client is not available at the payload level

**Pull request closed without merging**
