### PR TITLE
[Auto Release] Update istio.Version

### PR DESCRIPTION
**Pull request by ayj**
Update istio.Version for 0.2.9 release
```release-note
none
```

### CODE REVIEW

**Comment by sebastienvas** [comment]
Do we know why this is failing ?

**Comment by ayj** [comment]
```bash
I1018 16:55:49.754] --- FAIL: TestSvc2Svc (1.53s)
I1018 16:55:49.755] 	simple1_test.go:116: kubectl failure to run fortio command failed: "Fortio running at 0 queries per second, 4->4 procs, for 10s: http://echosrv.simple-auth-test-60e369ef04e040a0ac8a:8080/echo\nAborting because error -1 for http://echosrv.simple-auth-test-60e369ef04e040a0ac8a:8080/echo: \"\"\n16:55:49 I httprunner.go:75> Starting http test for http://echosrv.simple-auth-test-60e369ef04e040a0ac8a:8080/echo with 4 threads at 0.0 qps\n16:55:49 E http.go:424> Unable to connect to {10.23.250.225 8080 } : dial tcp 10.23.250.225:8080: getsockopt: connection refused\n" exit status 1
```

**Comment by ayj** [comment]
/test e2e-suite-rbac-no_auth

Re-running to see if its a flake.

**Comment by sebastienvas** [comment]
I was going to do the same. Yes seems that way

**Pull request merged**
