### PR TITLE
Allow Mixer adapters to respect upstream sampling decisions

### LINKED ISSUE #9530: Honor trace sampling decisions when using mixer
**Describe the feature request**
I'd like mixer to honor the [`x3-b3-sampled` HTTP header](https://github.com/openzipkin/b3-propagation#sampling-state-1). This header is set by upstream tracers to indicate that a request was sampled for tracing and should therefore be traced at further hops.

High traffic meshes use a low trace sample rate (i.e. 1% of requests or less). With each hop making a sampling decision without knowledge of upstream decisions it's unlikely that any one request will actually be sampled all the way along the route.

I'd be happy to contribute this functionality to the existing Stackdriver and SignalFX tracing implementations, assuming there was a point in doing so given their impending migration to out of process adapters. This would look something like:

1. Add a `sampled` field to the existing `tracespan` template such that it could be extraced from `x-b3-sampled` similar to how the other `x-b3-` propagation headers are populated.
2. Use the [existing Opencensus B3 propagation code](https://github.com/census-instrumentation/opencensus-go/blob/3a82755/plugin/ochttp/propagation/b3/b3.go#L101) to extract the sampling decision from the `tracespan`.
3. Force sampling of the relevant traces.

### PR DESCRIPTION
**Pull request by negz**
Fixes #9530

This PR allows the in process Mixer adapters that support the tracespan template (SignalFX and Stackdriver) to honor upstream sampling decisions, for example those specified by the `x-b3-sampled` header. Full details in #9530.

### CODE REVIEW

**Comment by douglas-reid** [comment]
Thanks for the submission!  In general, I think adding this to a template is an OK way to handle trace-specific notions.

However, as mentioned on the related issue, we want to provide a generic sampling capability for Rules. It would be wonderful if we could work to add this type of conditional support there. We added bits to the API, but have not started on the implementation yet. It would be better, I think, to spend our effort there.

Until we have a clear path on that, I'm going to add a:

/hold

But add a:

/ok-to-test

cc: @geeknoid @mandarjog @kyessenov for their thoughts.

**Comment by kyessenov** [comment]
@douglas-reid The way I interpret this is that `x-b3-sampled` is just another attribute being used to decide on rule sampling. As we discussed earlier, we could use an expression to make a judgement on rule sampling. This way client proxy or anything prior can throw the coin and control the overall sampling, on top of and optional independent sampling by individual components.

**Comment by negz** [comment]
It sounds like there's work underway for a generalised sampling strategy for rules that should cover my use case. I'm excited for that to land, but to me Mixer's existing tracing support is essentially useless without this functionality. I can't wait for 1.1 or 1.2, and sadly I don't have the bandwidth to help implement the generalised sampling API.

I'm happy for this PR to be closed if you think it will distract from those efforts; I submitted it largely because I need to solve this problem for my purposes and thus will likely run this code myself until a better solution appears.

**Comment by kyessenov** [comment]
not stale

**Comment by negz** [comment]
I realised a while ago that this PR won't work as expected. While it will force sampling when the `x-b3-sampled` header is true, it fails to do the opposite and disable sampling when `x-b3-sampled` is false. We decided Istio was a little too complicated for our needs at the moment and thus I haven't had any further time to work on this.

**Pull request closed without merging**
