### PR TITLE
Revert "Use read lock when building endpoints from shards"

### PR DESCRIPTION
**Pull request by howardjohn**
Reverts istio/istio#36657
fixes https://github.com/istio/istio/issues/36658

### CODE REVIEW

**Comment by dddddai** [comment]
The root cause is:
https://github.com/istio/istio/blob/c151f81ab7e0934269ad660b49bb2f1317ef55fa/pilot/pkg/xds/endpoint_builder.go#L323

The endpoint is modified and then read by another goroutine
But in terms of the result, it should not matter as `ep.EnvoyEndpoint` is always the same for each endpoint

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by ramaraochavali** [comment]
@howardjohn Sorry did not understand what is the problem with just read lock there? It does not seem to be modifying shards?

**Comment by dddddai** [comment]
> Sorry did not understand what is the problem with just read lock there? It does not seem to be modifying shards?

The root cause is:
https://github.com/istio/istio/blob/995ded3d2b93a2dbf70a1bc51a71057f5f03d318/pilot/pkg/xds/endpoint_builder.go#L323

The endpoint is modified and then read by another goroutine
But in terms of the result, it does not matter since `ep.EnvoyEndpoint` is always the same for each endpoint, maybe we should revert it to get rid of the race before we come up with a better solution though

**Comment by howardjohn** [comment]
It is not safe to write concurrently to the same location in memory even if
you are writing the same data, assignments are not always atomic. Even if
it was it is breaking tests at the very least

**Pull request merged**
