### PR TITLE
Enable HttpsRedirect for Kubernetes Ingresses with TLS

### PR DESCRIPTION
**Pull request by sathieu**
Note: initial PR title was:

> Add `gateway.istio.io/httpsRedirect` annotation to `Ingress` to set Gateway's httpsRedirect

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by sathieu** [comment]
This PR is raw, I'll add doc and tests once the design is approved.

**Review by howardjohn — CHANGES_REQUESTED** [review]
Thanks for the PR! While other projects have chosen to extend Ingress with a lot of annotations, Istio has chosen to adopt our own resource (Gateway) and adopt the new Kubernetes http://gateway-api.org/. We do not currently have any annotation-driven behavior on ingress - only the barebones functionality of the API, and I don't think we should add any.

**Comment by sathieu** [comment]
@howardjohn I want to use Helm charts and other installers with changing only the minimum. Even, without any change but by using a [mutating admission controler](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook).

Also Istio's gateway is Istio-specific, and Gateway-API is not ready yet (and not widely used). Ingress resources are here to stay (as said in Gateway API docs), and easier to understand (IMO).

Another suggestion: What about having the default for `httpsRedirect` configurable (for Ingresses and for Gateways)?

**Comment by sathieu** [comment]
@googlebot I signed it!

**Comment by sathieu** [comment]
@googlebot I signed it!

**Comment by sathieu** [comment]
@howardjohn I've read the [k8s gateway api](https://gateway-api.sigs.k8s.io/), but couldn't find any replacement for `httpsRedirect`.

I've also searched to create a match-all HTTP [Gateway](https://istio.io/latest/docs/reference/config/networking/gateway/), and haven't found.

**Comment by sathieu** [comment]
@howardjohn I've taken a different route: Enable HttpsRedirect for all Kubernetes Ingresses with TLS.

This changes behavior (and needs to be added to release notes), but I think nowadays defaulting to http->https redirection is good practice. WDYT?

Notes:
- This also the [behavior of ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#server-side-https-enforcement-through-redirect)
- Alternative would be to use the [same annotations as contour](https://projectcontour.io/docs/v1.14.0/config/annotations/#other-annotations)

**Review by howardjohn — CHANGES_REQUESTED** [review]
Always enabling HTTPS redirect is not a safe default in my opinion - even if it was, we cannot make breaking changes.

Istio's stance on Ingress is to implement the spec and nothing else. If you have advanced use cases beyond what the spec provides, you would need to use Gateway. Sorry if this doesn't work for our use case, but especially with the new http://gateway-api.org/ coming I don't think we want to invest into making Ingress more customizable

**Comment by sathieu** [comment]
@howardjohn OK I understand.

I've started to re-implement the conversions in Python, using metacontroller. Hope to post it there (see https://github.com/metacontroller/metacontroller/issues/2).

**Pull request closed without merging**
