### PR TITLE
Fix sts port node metadata

### PR DESCRIPTION
**Pull request by bianpengyuan**
add sts port to node metadata as string instead of integer.

### CODE REVIEW

**Comment by howardjohn** [comment]
why? seems like port should be a number

**Comment by bianpengyuan** [comment]
Good point. I switched back integer, except the final assignment to node metadata, which needs to be a string map.

**Comment by bianpengyuan** [comment]
@howardjohn ptal. thanks!

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
