### PR TITLE
Move common istio helpers to the parent helm chart

### PR DESCRIPTION
**Pull request by Rigdon**
Multiple subcharts would break if the istio ingress was disabled during helm templating/installation due to being unable to find the helper functions. This moves those functions to the top-level chart.

### CODE REVIEW

**Comment by Rigdon** [comment]
@costinm I was thinking about that yesterday. I'd be happy to work on that in another PR. Do you have a suggestion for which test suite it should be in or how we might want to run it?

**Comment by costinm** [comment]
Just a small shell script would be fine IMHO, we can add it to the unit-test target since it doesn't require 
any cluster. It can save the output to $OUT/something - the goal is to verify typical combinations can 
be generated. The unit test env includes a standalone apiserver, so we can even apply it so it's validated, but it won't start pods.

We'll also need a couple of tests in the integration, to verify it works with tiller.

**Comment by Rigdon** [comment]
@costinm Thanks, will work on that 👍

Will that block this PR at all? I only ask because we're currently not using an ingress and so disabling it breaks the chart and is blocking us from having repeatable deployments using helm at the moment.

**Pull request merged**
