### PR TITLE
fix typo in snapshot log/comments

### PR DESCRIPTION
**Pull request by lichuqiang**
typo fix

### CODE REVIEW

**Comment by lichuqiang** [comment]
Thanks, @ozevren , I think also need "/ok-to-test" :)

BTW, I'm new to istio, and hope to be involved in the contribution.
So, wondering if you have anything that I can help? Or any suggestion for new guys?

**Comment by ozevren** [comment]
The best place to start looking at is Github issues that are tagged with community/help-wanted and community/good-first-issue. The issues probably need some cleanup, so even if you want to tackle the issue, I'd suggest first sending a message to the issue/area owner to get more details.

Depending on your interest level and area, you can ping WG area leads to see if there is more substantial work you can contribute to. I am the WG area lead for config, so if you're interested in this area I can help. The best place to reach the dev community is slack and mailing list. You can find various communication paths listed at the bottom of the main page https://istio.io/

**Comment by lichuqiang** [comment]
> The best place to start looking at is Github issues that are tagged with community/help-wanted and community/good-first-issue. The issues probably need some cleanup, so even if you want to tackle the issue, I'd suggest first sending a message to the issue/area owner to get more details.

Yeah, I used to working on kubernetes for a time, so I basically know how the community works.
I guess what I need most is, like you said, the way to contact to WG  leads of my interested areas.
I tried to join in the istio slack channel, but it seems only istio members have the right to join it :(

>  I am the WG area lead for config, so if you're interested in this area I can help

That would be great. In fact I tried to send you message on slack, but seems you are always offline.
So, is there a quicker way to talk to you?

**Comment by ozevren** [comment]
I am generally available in Slack (though notifications for messages are blocked due to snooze hours). Can you try again? If it works, we can stop abusing Github comments. :)

You can also try the istio-dev mailing list.

**Comment by lichuqiang** [comment]
> I am generally available in Slack (though notifications for messages are blocked due to snooze hours)

Oh, really? Then maybe I've mistaken someone else for you.
Is "ozben" your slack ID? If not, can you send me a message on slack if free?(mine is same to my github ID: lichuqiang)

Thanks a lot!

**Pull request merged**
