### PR TITLE
Enable update dependency for proxy debian package

### PR DESCRIPTION
**Pull request by sebastienvas**
```release-note
none
```

### CODE REVIEW

**Comment by ldemailly** [comment]
not sure how you get hit by updateVersion check though
sounds like a bug somewhere ?
/retest

**Comment by ldemailly** [comment]
the error is because #857 was merged while it needed a rerun because of #793

**Comment by ldemailly** [comment]
just need to rerun install/updateVersion.sh
(or accept #833 where I also made the update)

**Comment by sebastienvas** [comment]
@ldemailly thanks.

**Pull request merged**
