### PR TITLE
[Dual-Stack] Use dual-stack pods in reachability tests

### PR DESCRIPTION
**Pull request by kfaseela**
Add dual-stack test specific pods to nonRegular pods, so that they will not be skipped for connectivity tests.
See: https://github.com/istio/istio/blob/master/pkg/test/framework/components/echo/echotest/filters.go#L74

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by kfaseela** [comment]
There are failures in TestAuthz_Conditions in dual-stack scenario, when the additional dual-stack services are added. Need to look into the failures before we can merge the PR. cc @zhlsunshine

**Comment by zhlsunshine** [comment]
Hi @kfaseela, okay, let's check it.

**Review by zhlsunshine — APPROVED** [review]
Great to see all integration test passed, thanks @kfaseela, LGTM!

**Comment by kfaseela** [comment]
> There are failures in TestAuthz_Conditions in dual-stack scenario, when the additional dual-stack services are added. Need to look into the failures before we can merge the PR. cc @zhlsunshine

The failures in the tests were due to AuthorizationPolicy specifying only single IP in the source-ip/destination-ip tests, but in reality the dual-stack pods have two IPs. I have modified the test framework to fetch both the PodIPs, so that the AuthorizationPolicy is complete.

**Comment by zhlsunshine** [comment]
> > There are failures in TestAuthz_Conditions in dual-stack scenario, when the additional dual-stack services are added. Need to look into the failures before we can merge the PR. cc @zhlsunshine
> 
> The failures in the tests were due to AuthorizationPolicy specifying only single IP in the source-ip/destination-ip tests, but in reality the dual-stack pods have two IPs. I have modified the test framework to fetch both the PodIPs, so that the AuthorizationPolicy is complete.

Yeah, basically, we need to pay attention to such test cases in really scenario:
Assume that: 

- Service A with Dual Stack 
- Service B with Single IPv4
- Service C with Single IPv6 

The compatibility should be for **A and B** or **A and C**, it means that A can communicate with B via its IPv4 and communicate with C via its IPv6.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
