### PR TITLE
Add AWS CloudwatchLogs Adapter (code from #10400)

### PR DESCRIPTION
**Pull request by douglas-reid**
I'm submitting this PR on behalf of @karanvasnani. @karanvasnani had submitted the source PR at least twice, perhaps three times, each time getting hung up on test failures, etc. Unfortunately, for some strange reason, I was not able to restart the CI tests on their behalf. So, in an attempt to be proactive about the content and the code, I'm submitting a copy of that PR in hopes that I'll be better able to guide it through the hurdles.

NOTE: All of the code was produced by @karanvasnani. I had previously reviewed it and LGTM'd it, but I am *not* the author of this code.

### CODE REVIEW

**Comment by karanvasnani** [comment]
@douglas-reid Thanks for taking this forward. For some reason the circleci tests keep failing on my PR https://github.com/istio/istio/pull/10400 even after rerunning the workflow several times through circleci.com. The same tests are passing here for your PR. Hope this gets approved soon.

**Comment by douglas-reid** [comment]
@karanvasnani unfortunately, we now have a codecov drop: `istio.io/istio/mixer/adapter/cloudwatch/cloudwatch.go:-13.200000% (77.800000% to 64.600000%)`. I'll take a quick look to see why in a few.

**Comment by douglas-reid** [comment]
Added `TestBasic` to cover `Build()` in unit tests.

**Pull request merged**
