### PR TITLE
release: Update latest stable Istio CNI SHA

### PR DESCRIPTION
**Pull request by tiswanso**
Make istio releases & nightlies pick up latest stable istio-cni.

Fixes: #13171

### CODE REVIEW

**Comment by edude03** [comment]
Any movement on this or anything I/we can do to help?

**Comment by linsun** [comment]
/approve 

if i can type :)

**Comment by linsun** [comment]
for release-1.1 since it is sensitive to breakage, would be great to demonstrate some testing around the new CNI SHA before merge.

**Comment by linsun** [comment]
per offline discussion with Tim, this is already tested with release-1.1 in PR gates for CNI project.

**Pull request merged**
