### PR TITLE
Making IstioOperator an Istio type

### PR DESCRIPTION
**Pull request by esnible**
This PR is an Work In Progress toward https://github.com/istio/istio/issues/21473

**THIS PR FAILED WHEN BUILT LOCALLY, IT IS HERE TO TROUBLESHOOT, NOT MERGE**

### CODE REVIEW

**Comment by esnible** [comment]
@ostromart Can you comment on why we have an IstioOperatorSpec in istio/api but the IstioOperator is not?

Why is there no .proto file for the IstioOperator? (There is one for the IstioOperatorSpec). The file operator/pkg/apis/istio/v1alpha1/operator_crd.pb.go says

proto.RegisterFile("pkg/apis/istio/v1alpha1/operator_crd.proto", fileDescriptor_8eb082c28e72c148)
There is no actual operator_crd.proto.  The fileDescriptor_8eb082c28e72c148 is there. Every other proto message has an actual .proto file, this one doesn't, I don't understand why.

**Comment by esnible** [comment]
@ostromart After some fixes this is failing with 

```
* proto message not found: istio.operator.v1alpha1.IstioOperatorSpec
```

The cause is that _ istio.io/api/operator/v1alpha1/operator.pb.go_ uses `proto "github.com/golang/protobuf/proto"` not `"github.com/gogo/protobuf/proto"`

Unless a protobuf is registered with the Gogo version it can't participate in the `go generate` of _pkg/config/schema_.

@ostromart @howardjohn I attempted the simple fix of changing which Protobuf package in a local copy of istio/api but a bunch of other things failed.  I recall there was some work to make all our types use the same protobuf library but now I can't find any such PR.  Please advise.

**Comment by ostromart** [comment]
@esnible per our offline discussion I think it will be challenging to make the proto representation work correctly due to the fact that proto cannot represent the Metadata object field correctly (it's an anonymous embedded struct in the Go struct representation). It may require post-compile hacks to make this work. However, for the purposes of documentation and analyze I think we could create a dummy IstioOperator proto with just the spec field and continue to use the Go struct representation we have already in the code.

**Comment by esnible** [comment]
Closing because it needs to be rethought.

**Pull request closed without merging**
