### PR TITLE
check whether if deploy or service exist or not

### PR DESCRIPTION
**Pull request by gy95**
**Please provide a description for what this PR is for.**
when get deployments and services failed, it return `XXXXXXXX does not exist` error regardless of error types, but some another type error may occur.
So we should check error is notExist error or some other types error.
And only when notExist occurs, return `XXXXXXXX does not exist` error

**And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

- [ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by gy95** [comment]
/kindly ping @howardjohn , need release-notes_istio :)

**Review by shamsher31 — APPROVED** [review]

**Pull request merged**
