### PR TITLE
agent: host Envoy readiness port on the agent

### PR DESCRIPTION
**Pull request by kyessenov**
Moves the listener responding to `/healthz/ready` on port 15021 from Envoy to the agent directly.
The rationale is that hosting it on Envoy has disadvantages: 
1. It pollutes troubleshooting Envoy debug logs due to constant traffic.
2. It does not correctly represent the load on Envoy. Health checking is an administrative load that should be tracked separately from the user load, and in particular, should not be shed.

The only benefit of this is weak. The ability of Envoy to respond to the health listener does not directly imply the health of other listeners. The ultimate backend is the agent, which already queries Envoy statistics to track that the other listeners have been accepted and the workers have started.

CC @ramaraochavali @briansonnenberg

### CODE REVIEW

**Comment by howardjohn** [comment]
> It pollutes troubleshooting Envoy debug logs due to constant traffic.

This is much less of an issue after https://github.com/istio/istio/issues/32569. Before there was 1req/2s, now its once /15s. Most users also probably have prometheus polling at 15s interval as well, so its aligned there.

> It does not correctly represent the load on Envoy. Health checking is an administrative load that should be tracked separately from the user load, and in particular, should not be shed.

This seems like something that should be improved in the load shedding mechanism. If we consider broader Envoy ecosystem, most users are not running an "agent", and would health check Envoy directly. Wouldn't those benefit from a mechanism to opt these out?

Alternatively, if we are in an overloaded state and not accepting new connections, is it _correct_ to be come NotReady?

> The ability of Envoy to respond to the health listener does not directly imply the health of other listeners.

No, but it does directly check the health of other _workers_. Without this, there is no protection against a deadlocked (or extremely loaded and thus effectively deadlocked) worker thread.

Overall, I am not sure this is an improvement. Its generally a best practice to have probes go through as realistic serving path as possible (https://www.datree.io/resources/kubernetes-readiness-and-liveness-probes-best-practices#anchor5 for example, although that looks like a low quality source the idea is sound).

**Comment by kyessenov** [comment]
> > It pollutes troubleshooting Envoy debug logs due to constant traffic.
> 
> This is much less of an issue after #32569. Before there was 1req/2s, now its once /15s. Most users also probably have prometheus polling at 15s interval as well, so its aligned there.

Prometheus does not go through a regular listener flow, it's not relevant to this PR.

> > It does not correctly represent the load on Envoy. Health checking is an administrative load that should be tracked separately from the user load, and in particular, should not be shed.
> 
> This seems like something that should be improved in the load shedding mechanism. If we consider broader Envoy ecosystem, most users are not running an "agent", and would health check Envoy directly. Wouldn't those benefit from a mechanism to opt these out?

Admin listeners are not going through the shedding mechanism in Envoy, and run on a distinct thread altogether. Admin and user traffic are hard isolated.
 
> Alternatively, if we are in an overloaded state and not accepting new connections, is it _correct_ to be come NotReady?
> 
> > The ability of Envoy to respond to the health listener does not directly imply the health of other listeners.
> 
> No, but it does directly check the health of other _workers_. Without this, there is no protection against a deadlocked (or extremely loaded and thus effectively deadlocked) worker thread.

Envoy has plenty of statistics around stalled workers and mega misses. The simple yes/no check of a health listener is very rude and is mostly an aspiration without thinking deeply of what stalled workers imply. I agree we need to look into internal self-monitoring better, but that can be done much more intelligently within Envoy rather than via an external prober.

> Overall, I am not sure this is an improvement. Its generally a best practice to have probes go through as realistic serving path as possible (https://www.datree.io/resources/kubernetes-readiness-and-liveness-probes-best-practices#anchor5 for example, although that looks like a low quality source the idea is sound).

The intent is good but the implementation is poor :)

**Comment by howardjohn** [comment]
> Prometheus does not go through a regular listener flow, it's not relevant to this PR.

Its the same as the Envoy readiness: https://github.com/istio/istio/blob/1e9dd6097865b15bc051c8c17e621cbfe56ad157/tools/packaging/common/envoy_bootstrap.json#L501


> Envoy has plenty of statistics around stalled workers and mega misses. The simple yes/no check of a health listener is very rude and is mostly an aspiration without thinking deeply of what stalled workers imply. I agree we need to look into internal self-monitoring better, but that can be done much more intelligently within Envoy rather than via an external prober.

Not sure the stats are terribly relevant given we are not querying them. Maybe we _could_, but currently this PR represents a regression? 

What makes you way the current approach is not considering what a stalled worker implies? The approach seems perfectly valid to me -- if Envoy cannot serve a simple "yes" then it likely cannot serve anything. This seems like a textbook readiness probe.

**Comment by kyessenov** [comment]
> Its the same as the Envoy readiness:

Yes, I know but prom stats are not critical and can be disabled. We can tackle that later.
 
> What makes you way the current approach is not considering what a stalled worker implies? The approach seems perfectly valid to me -- if Envoy cannot serve a simple "yes" then it likely cannot serve anything. This seems like a textbook readiness probe.

Envoy is not some sort of blackbox. We can trust it not to block its event loop or something terribly wrong was shipped. We can install a watchdog to self-crash if necessary, but that would be a behavior change and because, this threat is somewhat theoretical with a base config, it's not required.  The risky features like Wasm/Lua that can stall a worker cannot be solved without re-architecting, and the standard Istio API have a number of internal timeouts to prevent stalling, since that is effectively a CVE.

**Comment by kyessenov** [comment]
In any case, I'd like to hear thoughts from others. In my opinion if we ship an Envoy that stalls (blocks a worker for a long time), this is a CVE, and readiness is not a solution.

**Comment by howardjohn** [comment]
> Envoy is not some sort of blackbox. We can trust it not to block its event loop or something terribly wrong was shipped. We can install a watchdog to self-crash if necessary, but that would be a behavior change and because, this threat is somewhat theoretical with a base config, it's not required. The risky features like Wasm/Lua that can stall a worker cannot be solved without re-architecting, and the standard Istio API have a number of internal timeouts to prevent stalling, since that is effectively a CVE.

What is the point of the readiness probe at all, if not to blackbox test that a system has not unexpectedly failed?

The agent readiness probe\* is also just returning 200 -- why is that useful but Envoy doing the same is not?

Also, I am not sure I understand. You seem to be saying Envoy cannot possibly block, but Wasm/Lua can block?

\* only at _startup_ do we query envoy state/stats/etc

**Comment by kyessenov** [comment]
Wasm/Lua should be used knowing that incorrectly written third-party scripts can block and create a CVE-like situation. It's that we don't guarantee liveness for _every_ script, it's not our responsibility. Users can write production stable Wasm/Lua, but they can also create an outage.

**Comment by howardjohn** [comment]
> Wasm/Lua should be used knowing that incorrectly written third-party scripts can block and create a CVE-like situation. It's that we don't guarantee liveness for _every_ script, it's not our responsibility. Users can write production stable Wasm/Lua, but they can also create an outage.

So before: Bad Lua results in envoy not able to serve traffic. Pod become not ready, so clients stop sending it traffic
Now: Bad Lua results in envoy not able to serve traffic. Pod still is ready, so clients continue to send it traffic and fail

Again, this seems like a regression?

**Comment by kyessenov** [comment]
> > Wasm/Lua should be used knowing that incorrectly written third-party scripts can block and create a CVE-like situation. It's that we don't guarantee liveness for _every_ script, it's not our responsibility. Users can write production stable Wasm/Lua, but they can also create an outage.
> 
> So before: Bad Lua results in envoy not able to serve traffic. Pod become not ready, so clients stop sending it traffic Now: Bad Lua results in envoy not able to serve traffic. Pod still is ready, so clients continue to send it traffic and fail
> 
> Again, this seems like a regression?

Neither Lua nor Wasm are beta features - this is exactly why they are at most alpha and may never graduate. The health listener does not actually solve this either. You can still serve  a health listener on _another_ worker without knowing that one worker is blocked.

**Comment by keithmattix** [comment]
A readiness check that doesn't in some way hit the actual data path feels like an anti-pattern to me. I recognize that the status quo can be improved, but this PR seems strictly _less_ representative of readiness

**Comment by kyessenov** [comment]
> A readiness check that doesn't in some way hit the actual data path feels like an anti-pattern to me. I recognize that the status quo can be improved, but this PR seems strictly _less_ representative of readiness

The existing check does not hit the data path either, it's only an indirect signal that something shared is not blocked (e.g. worker is in the dead loop). This something shared is better tracked via watchdog https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-watchdog. I can double check that it's already activated.

**Comment by kyessenov** [comment]
The default watchdog is active, currently megamiss is 1s. I tested it with a simple wasm plugin that takes >1s compute:

```
  FilterHeadersStatus onResponseHeaders(uint32_t, bool) override {
    std::string s;
    for (int i = 0; i < 100000; i++) {
      s = s + std::to_string(i);
    }
    addResponseHeader("test", s.substr(0, 100));
    return FilterHeadersStatus::Continue;
  }
```

Stats, `server` prefix is allow-listed in Istio:
```
main_thread.watchdog_mega_miss: 0
main_thread.watchdog_miss: 0
server.main_thread.watchdog_mega_miss: 0
server.main_thread.watchdog_miss: 0
server.worker_0.watchdog_mega_miss: 3
server.worker_0.watchdog_miss: 3
workers.watchdog_mega_miss: 3
workers.watchdog_miss: 3
```

**Comment by ramaraochavali** [comment]
This was purposefully moved to Envoy to detect worker thread blocks with readiness. Sure, we may be able to check with stats but what is additional advantage compared to the current implementation?

What are you trying to solve here? Is there a problem going via Envoy (Except for debug log pollution)?

**Comment by briansonnenberg** [comment]
> ... Load-shedding in particular is problematic because Envoy would shed health probes instead of the user load.

FWIW I have [a PR](https://github.com/envoyproxy/envoy/pull/29781) open (working on rebasing it) to address this by providing a mechanism to selectively exclude listeners from the overload manager load shedding.

**Comment by kyessenov** [comment]
@briansonnenberg Yes, that helps, but it only solves the enforcement side. We're still measuring administrative load - e.g. we can trigger overload because admin stats compression or health listener is overshooting the allocated resources.

IMHO, we need strict separation - administrative functions are measured and controlled independently from the user functions. By administrative functions I mean xDS, stats, readiness - these should run on a separate thread relying on OS scheduler fairness.

**Comment by kyessenov** [comment]
> I understand the impact of stats or xds - but a simple health check which runs every x secs - would it really overshoot the calculations? And as @howardjohn not all deployments have agent running, what would they do in such cases?

AFAIK a half of all sidecars barely receive 1 request every 2 seconds. So the traffic is significant because once you run Wasm and extensions, a single request can overshoot the allowed load.

Which configuration does not have an agent? I'd be glad if it's possible, but I don't think it is.

**Comment by ramaraochavali** [comment]
> Which configuration does not have an agent? I'd be glad if it's possible, but I don't think it is.

I meant non Istio installations that run Envoy. May be they use Envoy's admin points derive readiness via custom script so that may be equivalent to hitting Envoy main thread only.

I do not have a strong preference here as long as we enable overload manager  and detect thread blocks

@howardjohn @hzxuzhonghu  WDYT?

**Pull request closed without merging**
