### PR TITLE
Make in-place sed operation portable

### PR DESCRIPTION
**Pull request by sdake**
sed -i is not portable.  GNU sed and Darwin have different
operational behaviors.  This would not be a problem, however,
homebrew is used occassionally on Darwin, which brings in
GNU sed.

### CODE REVIEW

**Comment by sdake** [comment]
https://github.com/istio/issues/issues/139

**Comment by sbezverk** [comment]
@sdake you can check running OS and then use Darwin's version of sed. When you move files you overwrite original file properties. 
Check it out:
https://github.com/istio/istio/blob/master/install/updateVersion.sh#L209

**Comment by sdake** [comment]
That works just fine unless someone has installed homebrew, in which case, the following issue occurs: https://github.com/istio/issues/issues/139

**Comment by sbezverk** [comment]
@sdake I see your point, I still think overwriting files properties is not right thing to do, but I would let community to decide.

**Comment by sdake** [comment]
you raise a valid point related to file properties.  I'll see if there is a way to keep properties intact.  which properties concern you most?  those shown with stat?

Cheers
-steve

**Comment by sbezverk** [comment]
@sdake After checking the changes again, I see that the operation is done mostly on files located in temp dir with the exception of values.yaml which is not big deal. thanks.

**Comment by sdake** [comment]
Lars mentioned cat a > b works to preserve properties - so I'll verify that and push a patch later today if it works (or report back that it doesn't).

**Comment by ldemailly** [comment]
/lgtm

thanks!
(this file should ideally go away soon but for now, this is cleaner/an improvement)

**Comment by sdake** [comment]
If the file is headed for the bitbucket (which IMO is a good idea 👍 - no need to gold plate it with keeping properties intact.

Cheers
-steve

**Pull request merged**
