### PR TITLE
Add use_local_cluster flag to e2e test readme

### PR DESCRIPTION
**Pull request by linsun**
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by yutongz** [comment]
/lgtm
Thanks

**Comment by ldemailly** [comment]
quick question: what does use_local_cluster actually means ?
(what's a local cluster, as opposed to... ?)

**Comment by sebastienvas** [comment]
Something like minikube. If you re own the same network as your cluster.

**Comment by ldemailly** [comment]
Ah thx, yeah so it's not really "use local cluster" as much as "(my) cluster is local/reachable"
(the "use" part is confusing)

https://github.com/istio/istio/blob/5ec8259fa89bd2431ecbd038a7acfb5299bd107c/tests/e2e/framework/kubernetes.go#L127

**Comment by linsun** [comment]
It is a little confusing... you actually should not need minikube or local cluster.   You could point to a cluster using node port as the istio ingress endpoint.

**Comment by yutongz** [comment]
Yes, the main difference is, inside or outside of the cluster. If we want to use in-cluster IP, we need to be inside of the cluster, like minikube or when CI runs tests. While on the other hand, when we connect to a gke cluster and start tests on my machine (laptop, desktop), we need external IP which is hold for load balancer.

**Comment by linsun** [comment]
Reading the util.GetIngressPod() code, it can get the host IP and nodeport, which can be accessible if that host IP is on public internet.   So it doesn't have to be inside of the cluster.

**Comment by ldemailly** [comment]
should be rename to use_pod_ip or local_cluster maybe?

**Comment by sebastienvas** [comment]
Sure local_cluster seems fine. but there are bunch of script to update with that.

**Pull request merged**
