### PR TITLE
Move waitEnvoyReady timeout from 3 seconds to 10 to prevent flakes

### PR DESCRIPTION
**Pull request by therealmitchconnors**
For examples of flakes see: 
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22719/unit-tests_istio/11322/
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22719/unit-tests_istio/11317/
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22719/unit-tests_istio/11320/
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22822/unit-tests_istio/11510/

### CODE REVIEW

**Comment by howardjohn** [comment]
as far as I know the root cause is routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED and @JimmyCYJ has already fixed these. The linked tests are old

**Comment by therealmitchconnors** [comment]
@howardjohn the only PR/issue I can find from Jimmy that you might be referring to is #22729 but that is for a [different](https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2012#1:build-log.txt%3A39868) root cause.  In this scenario, the proxy never becomes available, because we only give it three seconds to do so.  Additionally, this scenario affects more than just the test case that Jimmy has skipped for now.

**Comment by howardjohn** [comment]
#22817 is the PR I think. @JimmyCYJ can be more thorough here but in general all test flakes (at least ones I observe) have issues associated with them

**Comment by JimmyCYJ** [comment]
> #22817 is the PR I think. @JimmyCYJ can be more thorough here but in general all test flakes (at least ones I observe) have issues associated with them

Thanks @howardjohn and @therealmitchconnors for fixing these tests. The SDS test failures are caused by one SDS UDS path shared by multiple tests, and tests are running in parallel. The tests configure mock CA behave differently, so in #22817, I use unique UDS path for each test to make sure that Envoy talks to the expected SDS server.

TestProxyCachedToken fails on SSL handshake failure "OPENSSL_internal:CERTIFICATE_VERIFY_FAILED". There are multiple STS tests running in parallel, and they share the same file to R/W CA cert. I also use a unique file path for each of the tests. I think with that fix, it is not necessary to extend the proxy wait time. If there are any other failures, please let me know, and I will fix them.

**Comment by howardjohn** [comment]
Closing as this has been addressed already by Jimmy's changes

**Pull request closed without merging**
