### PR TITLE
feat(mixer plugin): add support for disableMixerHttpReport mesh config

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR sets the `disable_report_calls` flag in generated `ServiceConfig` to the value taken from `MeshConfig` for `disable_mixer_http_reports`.

This is meant to provide a way to turn off mixer-based telemetry reporting for HTTP calls during the transition to the extensibility v2 architecture.

Addresses: https://github.com/istio/istio/issues/15935. Note: It does not provide disabling purely on the client side. It is a complete disabling of telemetry reporting via Mixer (while preserving checks).

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
one question: why donot just check the `MeshConfig.MixerReportServer`? It means disabling report when it is empty.

**Comment by howardjohn** [comment]
I think this is to disable only http metrics but keep tcp, since mixerv2
doesn't support tcp we fall back to mixer v1 only for TCP and mixer v2 for
http (until v2 gets tcp support)

**Comment by douglas-reid** [comment]
@hzxuzhonghu when we fully support both TCP and HTTP, we can switch to checking for an empty `MixerReportServer`. As @howardjohn notes however, TCP scenarios are not yet supported. `disableMixerHttpReport` is meant as a short-term, undocumented enabler for testing, etc.

**Comment by douglas-reid** [comment]
@howardjohn how do PRs get merged these days?

**Comment by howardjohn** [comment]
@douglas-reid slowly.. you can see its status on https://prow.istio.io/tide. If its all green and not merging it probably means another PR was merged forcing this one to be retest

**Comment by hzxuzhonghu** [comment]
Understood, thanks for clarify.

**Pull request merged**
