### PR TITLE
Add volumeMount for /etc/istio/config in istio-auth.yaml

### PR DESCRIPTION
**Pull request by mwieczorek**
Without this PR if I do:
```
kubectl apply -f ./kubernetes/istio-auth.yaml
```
I get ingress/egress pods in error state and in pod's log I see:

```
Error: failed to read mesh configuration. cannot read mesh config file open /etc/istio/config/mesh: no such file or directory
```

### CODE REVIEW

**Comment by mwieczorek** [comment]
I signed it

**Comment by kyessenov** [comment]
@sebastienvas @andraxylia are we not testing auth YAMLs file? How did this slip through?

**Comment by sebastienvas** [comment]
@kuat @yutongz is currently working on this.

**Comment by yutongz** [comment]
Current e2e smoke test doesn't including auth. I am working to deploy istio-auth in e2e test.

**Comment by andraxylia** [comment]
Do we need a similar change in pilot?

**Comment by sebastienvas** [comment]
@yutongz For whatever reason the submit queue seems to be on Vacation.

**Comment by yutongz** [comment]
@andraxylia which pilot you meant?

**Comment by yutongz** [comment]
@sebastienvas  I didn't notice IBM test is not required any more. Merge-bot still supposes that's required and waits it green. Updating it.

**Comment by ldemailly** [comment]
Any way that the bot uses the same list as GitHub?

**Pull request merged**
