### PR TITLE
remove deprecated code

### PR DESCRIPTION
**Pull request by quanjielin**

### CODE REVIEW

**Comment by incfly** [comment]
iam.go contains `ExchangeToken`, does that mean citadel agent no longer exchanges token with Google? How does it get credential then?

**Comment by quanjielin** [comment]
no, exchange token still there, just switched to a different api interface long time ago, this pr just remove deprecate code.

**Comment by incfly** [comment]
Thanks. I just want to ensure we're still doing token exchange ourselves, not relying on k8s, which is crucial.

**Pull request merged**
