### PR TITLE
Translate Hub an Tag values under component level specs into values.

### LINKED ISSUE #20439: Component level hub/tag overrides are broken
Apply yaml:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: istio-testing
  tag: istio-testing
  
  components:
    cni:
       enabled: true
       hub: gcr.io/istio-testing
       tag: latest
```

`ik manifest generate -f iop.yaml | rg istio-cni-node -C 50`:
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: istio-cni-node
  namespace: istio-system
  labels:
    k8s-app: istio-cni-node
    release: istio
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: istio-cni-node
      annotations:
        # This, along with the CriticalAddonsOnly toleration below,
        # marks the pod as a critical add-on, ensuring it gets
        # priority scheduling and that its resources are reserved
        # if it ever gets evicted.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
        # Make sure istio-cni-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      priorityClassName: system-cluster-critical
      serviceAccountName: istio-cni
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 5
      containers:
        # This container installs the Istio CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: "istio-testing/install-cni:istio-testing"
          imagePullPolicy: Always
          command: ["/install-cni.sh"]
```

Note the image here is wrong.

### PR DESCRIPTION
**Pull request by elfinhe**
Translate Hub an Tag values under component level specs into values.

Fix: https://github.com/istio/istio/issues/20439

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
would be nice to update https://github.com/istio/istio/blob/de16fdc07deb0d839a7279d708fabf548c0211f0/tests/integration/pilot/cni/cni_test.go#L40

Also opened https://github.com/istio/istio/issues/20439

**Comment by elfinhe** [comment]
CNI integ test is updated here: https://github.com/istio/istio/pull/20516

**Pull request merged**
