### PR TITLE
Fix paths in rawvm docs

### PR DESCRIPTION
**Pull request by lizan**
**What this PR does / why we need it**:
- `samples/apps` no longer exists
- rules are now in `kube`

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by ldemailly** [comment]
/lgtm
Thx (it's more of a scratchpad than docs btw, the real docs are the website and the setup* scripts)

**Comment by lizan** [comment]
@ldemailly I was hitting here because it is linked from the end of [sample docs](https://istio.io/docs/guides/integrating-vms.html).

**Comment by ldemailly** [comment]
yeah there is a pr to update that unfornately I haven't yet been able to get it to work because of https://github.com/istio/proxy/issues/588

**Pull request merged**
