### PR TITLE
make bookinfo sample build repeatable

### LINKED ISSUE #7097: bookinfo build is not repeatable
I've been hacking on some very minor changes to the bookinfo sample app in an attempt to resolve #7047.

In doing so, I've discovered that the bookinfo build is not deterministic / repeatable for at least two reasons-- there may be others, but these are the two I was able to identify and quickly correct.

1. The first is that the productinfo flask app doesn't specify versions of its dependencies in its `requirements.txt`. This means that a build automatically gets the latest version of each package listed in that file. There _are_ breaking changes in the latest version of at least one of those packages that break compatibility with the productinfo app.

2. The second is that the `niaquinto/gradle` Docker image used to facilitate the build of the reviews service service no longer exists.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #7097

Replaces #7098 

cc @rshriram @vadimeisenbergibm

### CODE REVIEW

**Comment by krancour** [comment]
@rshriram from #7109:

> Can you push the changes to your dockerhub account and update the bookinfo YAMLs to point to your version ? Once they pass, I can copy and push them into istio's official docker hub and update the YAML references in a separate PR

Shall I do the same here?

**Comment by rshriram** [comment]
Its fine to do this in one Pr

**Comment by krancour** [comment]
> Its fine to do this in one Pr

Not sure what you're referring to.

As it stands now. This PR references images that do not exist. In the other PR, you asked that I push images to a new location and temporarily reference those. I'm just asking if the same approach is to be employed here.

I'm so sorry... I know I must sound so confused about the process here. I am. And tbh, I think that says something about this process being broken.

My other PR notwithstanding, please help me understand what needs to be done to get _this_ one through?

**Comment by krancour** [comment]
@rshriram similar to what you have suggested in #7109, I've pushed the new images to someplace temporary and added a commit (which can be reversed later) that references those temporary images so that these tests have a chance of passing.

lmk if this meets expectation and if not, what I can do to fix.

**Comment by rshriram** [comment]
This is good.. lets get the other PR also merged and then I will copy the images and push them to docker hub..

**Comment by rshriram** [comment]
Lets do this first thing in the morning.

**Pull request merged**
