### PR TITLE
samples/helloworld: update README

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by sdake — APPROVED** [review]
/ok-to-test

PR looks good. I am not clear where the link checker went for the Istio repo.

**Review by ericvn — APPROVED** [review]
You could have left the `latest` out of the link. The former would still work and since no version was on the URL, latest would be assumed.

**Comment by frankbu** [comment]
There is another error in this README on line 27. 

@daixiang0 Can you please also change line 27:
```
kubectl apply -f helloworld.yaml -l app=helloworld
```
to:
```
kubectl apply -f helloworld.yaml -l service=helloworld
```

**Comment by ericvn** [comment]
Added the DNM for Frank's remark. Once it's fixed, the label can be removed.

**Comment by daixiang0** [comment]
@frankbu @ericvn done.

**Pull request merged**
