### PR TITLE
Convert more reachability tests into multicluster support

### PR DESCRIPTION
**Pull request by jtrbs**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[X] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Comment by jtrbs** [comment]
Test passed: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28594/integ-security-multicluster-tests_istio/1324163431191810048

**Comment by jtrbs** [comment]
Test passed at: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28594/integ-security-multicluster-tests_istio/1324436839905366016

**Comment by jtrbs** [comment]
Test passed at https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28594/integ-security-multicluster-tests_istio/1326043647895932928

**Review by stevenctl — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
