### PR TITLE
envoy filter: merging struct into any util

### PR DESCRIPTION
**Pull request by rshriram**
this is a prep for upcoming additions to EnvoyFilter where
we need to merge user provided structs into the Any typed
filters in HCM or network filter stack.

Signed-off-by: Shriram Rajagopalan <rshriram@tetrate.io>

### CODE REVIEW

**Comment by howardjohn** [comment]
` @golangcibot is blocked in the organization`? did you block this bot or something wrong with our github?

Overall looks good. How often will this be called? I would imagine performance here is probably not great with all the marshalling going on

**Comment by rshriram** [comment]
yeah I had blocked that bot.. unblocked it. This code while not so fast, is as fast as things can get when we have to deal with struct and any. And today, we have completely disabled xdsMarshalingToAny feature. So I expect it wont be used for a while.

**Comment by howardjohn** [comment]
I think we determined the any marshaling was safe to turn back on so we may ship with that - not 100% sure @mandarjog?

**Comment by howardjohn** [comment]
I'm not say we should block this btw, just something we should be aware of and make sure we profile once this is used

**Comment by rshriram** [comment]
Yep. Will know once we have the full setup. Also, the EnvoyFilter is break glass. So we can side step the perf issue if it arises, as the number of people using this is going to be relatively few. You will see in the implementation PR that will follow.

**Pull request merged**
