### PR TITLE
[Wip] unify tests, use fortio client/echo library for pilot client/server

### PR DESCRIPTION
**Pull request by ldemailly**
Not ready for review yet

Need to change client side more to reuse fhttp client

### CODE REVIEW

**Comment by kyessenov** [comment]
There's nothing special in the test app. It was written more than a year,
and noone bothered to update it. The only difficulty is probably replacing
echo gRPC server with the one in istio, and matching the test result
checking.

**Comment by ldemailly** [comment]
as mentioned in the pr description, this is wip and not ready for review - I just "saved" it in case my mac crashes and burn

**Comment by ldemailly** [comment]
the websocket part is why I need to keep "server" (for now) - it also helps with backward compatibility and to stage the change

**Comment by ldemailly** [comment]
closing this for now
fortio as a library - as partially shown in this PR - as all pilot tests would need except websocket so I strongly recommend this work to be done soon

**Comment by ldemailly** [comment]
cc @nmittler I guess you'll take this on

**Comment by nmittler** [comment]
@ldemailly yes, makes sense.

**Pull request closed without merging**
