### PR TITLE
Fix inject validata

### PR DESCRIPTION
**Pull request by champly**
#28696 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
Its looking for cla under email at dmall.com. looks like you signed with a different email

**Comment by champly** [comment]
Recommit #28732

**Pull request closed without merging**
