### PR TITLE
optimize: register CRD in parallel

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@ymesika PTAL :)

**Comment by YaoZengzeng** [comment]
Oh.. I see, so should I push the change to master? 😂 

And where could I get the community announcement?

For example, when should I only push bug fix and which branch to push ?

**Comment by ymesika** [comment]
It was in the Slack's #general channel.
Please change to `master` if it's not fixing anything.

**Comment by YaoZengzeng** [comment]
@ymesika Thanks!

Already change to master, ref #11227

**Pull request closed without merging**
