### PR TITLE
remove prometheus from release archives

### PR DESCRIPTION
**Pull request by rkpagadala**

### CODE REVIEW

**Comment by ldemailly** [comment]
I wonder if people would think that's a bug / we should replace it with a file with just a comment ?

**Comment by ldemailly** [comment]
also need to update
https://sourcegraph.com/search?q=prometheus.yaml&sq=repo%3A%5Egithub%5C.com%2Fistio%2Fistio%5C.github%5C.io%24

**Comment by rkpagadala** [comment]
fixes https://github.com/istio/istio/issues/5111

**Comment by linsun** [comment]
can we make sure the doc is updated?  https://preliminary.istio.io/docs/tasks/telemetry/metrics-logs.html#before-you-begin

**Comment by rkpagadala** [comment]
@linsun will update the docs also

**Comment by ldemailly** [comment]
lin, fyi, there is more than 1 page to update as I mentioned in https://github.com/istio/istio/pull/5150#issuecomment-383770436

**Comment by rkpagadala** [comment]
Corresponding pull request for documentation https://github.com/istio/istio.github.io/pull/1199

**Pull request merged**
