### PR TITLE
Update Wasm Dashboard Default Time

### PR DESCRIPTION
**Pull request by Xunzhuo**
**Please provide a description of this PR:**

Update Wasm Dashboard Default Time 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Please check any characteristics that apply to this pull request.**

- [x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
/lgtm

**Review by howardjohn — APPROVED** [review]
can you run `./manifests/addons/gen.sh` as well?

Thanks for the fix!

**Comment by zirain** [comment]
> can you run `./manifests/addons/gen.sh` as well?
> 
> Thanks for the fix!

run `make gen` would be ok too.

**Review by linsun — APPROVED** [review]
Nice fix!

**Pull request merged**
