### PR TITLE
fix cd path for istio repo checkout in prow

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @ostromart

### CODE REVIEW

**Comment by ldemailly** [comment]
this script is still a mystery to me, who/what uses it, what for...

**Comment by krzyzacy** [comment]
this script is used for testing istio addon on kubernetes, it's used in https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L10329-L10330

**Comment by ldemailly** [comment]
neat, where do the results show up ?

/lgtm

**Comment by krzyzacy** [comment]
the result is in https://k8s-testgrid.appspot.com/istio#istio-gke-addon

**Comment by ldemailly** [comment]
Thanks ! very red atm :-) but I guess if it has the wrong dir, that explains that

**Comment by krzyzacy** [comment]
yeah, the test is not going to work on gke yet as we need to wait for some upstream api changes to kick in, I added a gce suite in the PR referenced above.
(seems the presubmit is busted?)
/retest

**Comment by ldemailly** [comment]
https://github.com/istio/istio/issues/3082 for the test failure

/test istio-presubmit

**Comment by krzyzacy** [comment]
this will be covered within #3121

**Pull request closed without merging**
