### PR TITLE
Moving more config utilities to subpackages

### PR DESCRIPTION
**Pull request by nmittler**
This is part of the cleanup of pkg/config. Planning on moving everything here to subpackages.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
@geeknoid you turned off the /lgtm /approve commands.

@ozevren is the only one that can approve this.

**Comment by nmittler** [comment]
@howardjohn 

> @ozevren is the only one that can approve this.

How did you determine that? I've been looking for a way to figure out what approvals are lacking.

**Comment by howardjohn** [comment]
@nmittler "Waiting on code owner review from ozevren" it says it above the status checks

**Comment by nmittler** [comment]
@howardjohn oof ok, thanks ... I'm certain it didn't say that earlier ... maybe I'm just crazy then :)

**Comment by nmittler** [comment]
@howardjohn @geeknoid oz is out for another week ... do we have a way of force merging this?

Also, we should probably add some folks to owners of certain directories so we don't suffer the bus factor problem in the future.

**Pull request merged**
