### PR TITLE
access logs: add support for CEL formatter

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by ramaraochavali** [comment]
Do we have any test cases for other formatters? If yes, should we extend that test case to validate Cel formatter?

**Review by zirain — APPROVED** [review]
LGTM, I'm supposed to do this long ago.

**Comment by hzxuzhonghu** [comment]
please supplement the pr title, support for what?

**Comment by howardjohn** [comment]
@hzxuzhonghu updated, sorry

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
