### PR TITLE
set envoy drain duration to min drain duration if specified

### PR DESCRIPTION
**Pull request by ramaraochavali**
Without this Envoy uses default drain duration

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
Do we have a test coverage, it has been there for many years.

**Comment by hzxuzhonghu** [comment]
We have proxyCOnfig DrainDuration. And always use that, why should tansit to this one. And what's the difference? Can user really understand that?

**Comment by ramaraochavali** [comment]
>We have proxyCOnfig DrainDuration. And always use that, why should tansit to this one. And what's the difference? Can user really understand that?

When user uses EXIT_ON_ACTIIVE_CONNECTIONS and specifies MIN_DRAIN_DURATION we sleep for MIN_DRAIN_DURATION before checking EXIT_ON_ACTIIVE_CONNECTIONS. But Envoy's draining depends on proxyConfig's drainDuration. We can say user have to set proxyConfig's drainDuration also get envoy drain duration. I am trying to simplify that here.

**Comment by howardjohn** [comment]
Drain duration impacts more than shutdown. 

Why do we even need to change it when in exit_on_zero_connections mode..?

**Comment by ramaraochavali** [comment]
> Why do we even need to change it when in exit_on_zero_connections mode..?

As I said currently, when MinDrainDuration is set to 60s, we sleep for 60s but the actual draining happens for 5s (default drain duration) which is kind of waste. I agree that it also affects other listener draining, this case is confusing. May be we just update the docs?

**Comment by howardjohn** [comment]
isn't the default 45s ?

**Comment by ramaraochavali** [comment]
> isn't the default 45s ?

Sorry. Yes. Mis typed

**Comment by ramaraochavali** [comment]
@howardjohn circling back on this, the terminationDrainDuration is actually defaulted to 5s not 45s https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.proto#L536. Envoy's drain duration is 45s.

**Comment by howardjohn** [comment]
But this pr isn't setting termination drain?

**Comment by ramaraochavali** [comment]
Correct. It is not. I was just clarifying the default values - nothing to do with this PR

**Pull request closed without merging**
