### PR TITLE
operator: drop `profile diff` command

### PR DESCRIPTION
**Pull request by howardjohn**
We really do not need to re-invent the `diff` command. This has next to
no value and is not where we should be spending time maintaining

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]
🔥

**Review by zirain — APPROVED** [review]

**Comment by bleggett** [comment]
I don't object to this at all, but we should have relnotes for this (user-facing) removal right? Especially since `operator` itself isn't actually deprecated yet?

**Comment by howardjohn** [comment]
@bleggett we should definitely, I was mostly being lazy since this was the first of a few and I was going to bundle all the release notes

**Pull request merged**
