### PR TITLE
Fix metrics error rps stats incorrect

### PR DESCRIPTION
**Pull request by kebe7jun**
HTTP Status code less than 400 means normal.

https://httpstatuses.com/

For: https://github.com/istio/istio/issues/24322

[X] Policies and Telemetry

### CODE REVIEW

**Comment by mandarjog** [comment]
@douglas-reid do we need to change this in our grafana queries too?

**Comment by douglas-reid** [comment]
Related issue: #24309

**Comment by douglas-reid** [comment]
@mandarjog i don't believe so, but it couldn't hurt to recheck them all when we are working on improving/refactoring the dashboards. iirc, most of the queries on the dash distinguish between 5xx and 4xx responses directly.

**Comment by douglas-reid** [comment]
@esnible can you approve ?

**Pull request merged**
