### PR TITLE
Update dependencies, and fix the validation webhook with required value

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
Updating client-go library results in the failure of validation tests. I've introducted ignore exception to the crdvalidator to ignore some configs that are intended to be invlid in tests. Also, fix the validation test since the invalid case may be `Required value` which is introduced recently in the API repo.

### CODE REVIEW

**Comment by hanxiaop** [comment]
I suspect integ-telemetry-istiodremote_istio is failing since we are still appling CRs(Envoyfilter) in tests together with our components:
```
- Processing resources for Istiod remote.
✘ Istiod remote encountered an error: failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.17: Internal error occurred: failed calling webhook "rev.validation.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
```
And the installation order is changed in https://github.com/istio/istio/pull/47007. I think the test logic may need to be revised.

**Review by howardjohn — CHANGES_REQUESTED** [review]
This is skipping way to many tests. I can work on a more robust fix

**Comment by hanxiaop** [comment]
Will be replaced by https://github.com/istio/istio/pull/47377; only dependency updates will be needed after its merge.

**Pull request closed without merging**
