### PR TITLE
Add an openshift flag to integration tests

### PR DESCRIPTION
**Pull request by jwendell**
And make the helm tests to pass on OpenShift by using this flag.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
I kind of don't like this because its not scalable, but I don't have any clear recommendations otherwise

@stevenctl @keithmattix any ideas? will approve if not

**Comment by jwendell** [comment]
@howardjohn what do you mean by not scalable?

More context: The long term goal is to have CI tests to run on OpenShift. Short term goal is to run those jobs in a mirror (fork) we have under another org, just because currently setting up jobs to run on OpenShift here on upstream is not feasible for a number of reasons.

What we will do (in our fork) after this is merged is to mimic the behavior of prow/integ-suite-kind.sh but deploying an openshift cluster, and then run the tests passing this new flag.

**Comment by howardjohn** [comment]
I mean if we add GKE,AKS,EKS,... soon we will have an insane mess. That is only considering vendors too -- there is also distroless,ipv6,arm64,CNI,ambient, ..... So many different modes without much consistent or sane strategy for enabling them.

**Comment by howardjohn** [comment]
Not saying you need to solve this problem, its quite large/hard and I don't have much direction. Just wanted to get a check from others if there were any easy wins in the short term, else I will approve

**Comment by keithmattix** [comment]
This is ok with me as an exception since OpenShift has its own profile. But I am a -1 on doing this for every distro/cloud provider; Cilium does that (they may need to) and it's a mess. My preference is to have our e2e test flags reflect the actual behavior being changed and vendors can maintain their own presets

**Comment by stevenctl** [comment]
The two things I see here are:

* Overriding the profile
* Checking for CNI

We could add two flags for those. When running open shift run with `--istio.test.overrideProfile=openshift` or `openshift-ambient`. CNI check will be `ambient || istio.test.ensureCNI`

**Comment by howardjohn** [comment]
We do have '--istio.test.istio.enableCNI=true' already which could probably
be utilized as well?

**Comment by jwendell** [comment]
@stevenctl  I'm not sure how we could use a flag such as `overrideProfile` when helm tests use multiple profiles. Some tests use the default profile (which correspond to openshift), and some tests use the ambient profile (which correspond to openshift-ambient).

@howardjohn That flag is only available in the Istio component. Helm tests do not use Istio component to install Istio, i.e. it's not available in framework.TestContext, unless I'm missing something...

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
