### PR TITLE
proxy: narrow down dependencies

### PR DESCRIPTION
**Pull request by kyessenov**
Change-Id: I9312bde62a74d4c267b50e28241da2bb5ef08d5b

Code re-factor to restrict the use of k8s libraries in the proxy agent. This doesn't fully get rid of them, but the linter will prevent future additions.

Issue: #50134

### CODE REVIEW

**Comment by kyessenov** [comment]
Tests fail for a good reason - Protos are not force linked.

**Review by howardjohn — APPROVED** [review]
LGTM

**Comment by howardjohn** [comment]
> Tests fail for a good reason - Protos are not force linked.

I think we can probably fix that by importing them in the tests only right? We don't need them in the main path

**Comment by kyessenov** [comment]
> > Tests fail for a good reason - Protos are not force linked.
> 
> I think we can probably fix that by importing them in the tests only right? We don't need them in the main path

Yeah, it appears to be a test only dependency.

**Pull request merged**
