### PR TITLE
Revert "sidecar: trim service ports based on egress listeners and merge services"

### PR DESCRIPTION
**Pull request by howardjohn**
Reverts istio/istio#18111

@ramaraochavali sorry to revert another one of your PRs... we can see if this fixes the issue and close if it does not.

See https://github.com/istio/istio/issues/18211

### CODE REVIEW

**Comment by incfly** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18212/pilot-multicluster-e2e_istio/2092
seems brosko resource allocation failure...

**Comment by howardjohn** [comment]
hmm
Seems like there are 2 issues, failure to setup the tests, which is likely the result of a gcp service outage, then normal test failures. I think both happened at around the same time so hard to distinguish root cause

**Comment by howardjohn** [comment]
The multicluster test still failed here a couple of times, but only because 2 things independantly broke the test for different reasons. See https://github.com/istio/istio/issues/18211#issuecomment-545511143. With this change, the sidecar scope test has never failed, so I think we should merge this

**Pull request merged**
