### PR TITLE
 Stop using github.com/bradfitz/slice.Sort (clone of #7775 with go dep fixes)

### PR DESCRIPTION
**Pull request by ayj**
This is a copy of https://github.com/istio/istio/pull/7775 with `go dep` linter fixes so it can be merged.

> It's in Go's sort package as of Go 1.8, and Istio depends on Go 1.9
> (docs) or Go 1.10 (CircleCI config). In any case, stop using my
> package, which isn't updated for new architectures now that it's in
> Go's std.
> 
> Background: I received a bug report that Istio didn't build on
> somebody's non-x86 big endian architecture. (Bug report didn't say
> which)

### CODE REVIEW

**Comment by ayj** [comment]
Manually approved the CLA since this is a clone of https://github.com/istio/istio/pull/7775 which was already auto-approved.

**Comment by kyessenov** [comment]
Thanks, something is still wonky with lint/dep job.

**Comment by kyessenov** [comment]
/lgtm
/approve

Sorry @bradfitz it took this long...

**Comment by bradfitz** [comment]
My one contribution to Isitio and my name got squashed away in the git history. Oh well.

I'm not going to cry over that, but be careful with other new contributors. We've found ourselves having to be pretty gentle with new Go contributors over the years and guiding them through the process so they stick around, even when it's faster to just do it ourselves.

**Comment by ayj** [comment]
Sorry about that =/. 

Based on the original PR description I incorrectly assumed you just wanted Istio to stop depending on your unsupported library. I also incorrectly assumed you didn't want to have to deal with our flaky presubmit queue. Two bad assumptions on my part -- apologizes again and thanks for recommendation re: guiding new contributors.

**Pull request merged**
