### PR TITLE
istioctl: fix experimental ps compare error while configs are different

### PR DESCRIPTION
**Pull request by hanxiaop**
**Please provide a description of this PR:**
This fixes the issue when proxy config from Envoy and Istiod differ, leading to marshaling errors due to unrecognized types. 

~Also, this PR removes the difflib library from the comparator, as it is no longer maintained, and switches to using cmp.Diff instead. I'm not sure if the switch makes sense, but I think the output with the cleaner cmp codes is readable to users as well.~

Assuming https://github.com/istio/istio/pull/47740 will be merged in this release, I've only fixed the `experimental ps`.

### CODE REVIEW

**Comment by syw14** [comment]
@hanxiaop could you please add an example output when there's diff?

**Review by howardjohn — APPROVED** [review]

**Comment by syw14** [comment]
1. I'm not super familiar with `difflib`, but I think 
    a. ) it compares diff per line, For me the output is clearer for the user perspective. 
    b. ) it might process the string before prints diff such that unnecessary string diff won't be printed. 
3.  "It's no longer maintained" - meaning we plan to deprecate it soon? Can we investigate more before removing it?

**Comment by hanxiaop** [comment]
> @hanxiaop could you please add an example output when there's diff?

@syw14  will be something similar to:
```
Clusters Don't Match. Diff:
  (
  	"""
  	... // 3 identical lines
  	            "cluster": {
  	                "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
- 	                "name": "inbound-vip|9080|http|ratings.default.svc.cluster.local",
+ 	                "name": "inbound-vip|9999|http|ratings.default.svc.cluster.local",
  	                "type": "EDS",
- 	                "edsClusterConfig": {
- 	                    "edsConfig": {
- 	                        "ads": {
-
- 	                        },
- 	                        "initialFetchTimeout": "0s",
- 	                        "resourceApiVersion": "V3"
- 	                    },
- 	                    "serviceName": "inbound-vip|9080|http|ratings.default.svc.cluster.local"
- 	                },
  	                "commonLbConfig": {

  	... // 24 identical lines
  	"""
  )

Listeners Don't Match. Diff:
  (
  	"""
  	... // 118 identical lines
  	                                        "serverName": "istio-envoy",
  	                                        "streamIdleTimeout": "0s",
- 	                                        "useRemoteAddress": false,
  	                                        "forwardClientCertDetails": "APPEND_FORWARD",
  	                                        "setCurrentClientCertDetails": {
  	... // 96 identical lines
  	                                    "typedConfig": {
  	                                        "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
- 	                                        "statPrefix": "inbound_0.0.0.0_9080",
+ 	                                        "statPrefix": "inbound_0.0.0.0_9999",
  	                                        "routeConfig": {
  	                                            "name": "inbound-vip|9080|http|details.default.svc.cluster.local",
  	... // 782 identical lines
  	"""
  )

Routes Don't Match (RDS last loaded at Mon, 04 Mar 2024 16:37:44 CST)
  (
  	"""
  	... // 3 identical lines
  	            "routeConfig": {
  	                "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
- 	                "name": "inbound-vip|9080|http|reviews-v3.default.svc.cluster.local",
+ 	                "name": "inbound-vip|9999|http|reviews-v3.default.svc.cluster.local",
  	                "virtualHosts": [
  	                    {
  	... // 12 identical lines
  	                                    "timeout": "0s",
  	                                    "maxStreamDuration": {
- 	                                        "maxStreamDuration": "0s",
  	                                        "grpcTimeoutHeaderMax": "0s"
  	                                    }
  	... // 13 identical lines
  	"""
  )
```

**Comment by syw14** [comment]
@hanxiaop Thanks! Do you think it's clearer if we also prints which one (- or +) is istiod config and which one is Envoy config?

**Comment by hanxiaop** [comment]
> @hanxiaop Thanks! Do you think it's clearer if we also prints which one (- or +) is istiod config and which one is Envoy config?

@syw14 After some testing, I realized that the old library is more stable when comparing the Envoy config JSONs, so I switched back to the old library. I'll leave it there unless we encounter issues with the config in the future. I also added a sample output in the test. https://github.com/istio/istio/pull/49713/files#diff-27fadb008fa613995ff1bf633399518a771f44d071acada2a0c5cc405d4f94a2

**Pull request merged**
