### PR TITLE
shifting test: use 2 pods when vms are disabled

### PR DESCRIPTION
**Pull request by stevenctl**
prevent test failures in `--skipVM` mode

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Code and PR title do not seem to match? Is that intended?

**Comment by stevenctl** [comment]
They should now, thanks. 

I'm not sure what I think about changing it to skip. Without the alarm of this test failing, we wouldn't easily know that we lost coverage.

**Review by howardjohn — APPROVED** [review]
I agree, skipping was a bit concerning. This LGTM

**Pull request merged**
