### PR TITLE
Add duration proxy status

### PR DESCRIPTION
**Pull request by MorrisLaw**
This was the [original PR](https://github.com/istio/istio/pull/8254) for my changes to add duration to the proxy status. I closed it out and opened a new PR against release-1.1

This addresses issue [#6518](https://github.com/istio/istio/issues/6518)

### CODE REVIEW

**Comment by MorrisLaw** [comment]
Not sure what happened, I'll fix the commit history.

**Comment by liamawhite** [comment]
fix the conflicts and I'll get this merged 🙂

**Comment by liamawhite** [comment]
@MorrisLaw did you rebase? that test failure is fixed in the 1.1 branch.

**Comment by MorrisLaw** [comment]
@liamawhite it should be good now. The latest release-1.1 branch with just my changes on top.

**Comment by MorrisLaw** [comment]
Not sure why those tests would be failing @liamawhite 🤔

**Pull request merged**
