### PR TITLE
use common util for json marshal

### PR DESCRIPTION
**Pull request by shamsher31**

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
Does this fix https://github.com/istio/istio/issues/25194, I thought that issue is relevant to the `UnmarshalIstioOperator` function we use, maybe caused by operator api changes.

**Comment by shamsher31** [comment]
No this won't fix #25194 , This PR only removed redundant code which I found during debugging #25194 .

**Review by howardjohn — APPROVED** [review]

**Review by esnible — APPROVED** [review]

**Review by morvencao — APPROVED** [review]

**Comment by shamsher31** [comment]
@howardjohn will this require manual merge?

**Comment by shamsher31** [comment]
I observed that commenting on PR is also triggering builds.

**Comment by howardjohn** [comment]
Its just a bit slow sometimes since it will retest things if another PR
merges. See https://prow.istio.io/tide for the status

**Pull request merged**
