### PR TITLE
Moving envoy startup code out of pilot

### PR DESCRIPTION
**Pull request by nmittler**
We have a few places in the codebase that duplicate the logic for starting up envoy instances. This is the first part of an effort to merge all of these into a common utility.  For now, this is just moving the code as-is.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by kyessenov** [comment]
Should we donate this code to envoy org?

**Comment by nmittler** [comment]
@kyessenov 

> Should we donate this code to envoy org?

Possibly after the refactor, we can revisit that.  I wouldn't in its current form.

**Comment by kyessenov** [comment]
Well, it would be better to submit the refactored version upstream, and then simply delete existing code IMHO. I don't understand why we need to move so much code, unless there is some short term goal that I don't know about.

**Comment by nmittler** [comment]
@kyessenov this is a code health effort primarily, but with long-term goals of having a more maintainable codebase.

The pilot package has become a dumping ground for library code. I'm working on identifying and moving as much code out of pilot as possible with the ultimate goal of boiling pilot down to just the code specific to the discovery server. Once we get there, we can then begin the process of trying to clean up the discovery server codebase.

**Pull request merged**
