### PR TITLE
Add doc on where distroless is built from

### PR DESCRIPTION
**Pull request by howardjohn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[ ] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by sdake — APPROVED** [review]
good improvement. DIdn't know distroless built this in their images.

Cheers
-steve

**Comment by howardjohn** [comment]
@sdake I think you were OOO during discussions around this, but disrtoless is not officially building iptables, we are holding a fork with iptables added (in https://github.com/istio/distroless/tree/iptables)

**Comment by sdake** [comment]
@howardjohn - cool - still LGTM.

**Comment by howardjohn** [comment]
not stale

**Review by GregHanson — APPROVED** [review]

**Pull request merged**
