### PR TITLE
[Ansible Installer] Fixing the ansible installer for previous version to 0.8.0

### LINKED ISSUE #6190: Ansible Installer is not working for previous versions to 0.8.0
When you use ansible installer from master, with `istio.release_tag_version` with 0.7.1, it results on the following error.

> TASK [istio : Copy definition file] ********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cp", "~/.istio/istio-0.7.1/install/kubernetes/istio-demo.yaml", "/tmp/ansible.QlxBG3JcPb/def.yml"], "delta": "0:00:00.920507", "end": "2018-06-12 06:02:08.022152", "msg": "non-zero return code", "rc": 1, "start": "2018-06-12 06:02:07.101645", "stderr": "cp: cannot stat '/home/jenkins/.istio/istio-0.7.1/install/kubernetes/istio-demo.yaml': No such file or directory", "stderr_lines": ["cp: cannot stat '/home/jenkins/.istio/istio-0.7.1/install/kubernetes/istio-demo.yaml': No such file or directory"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/jenkins/workspace/install-istio/istio/install/ansible/main.retry

### PR DESCRIPTION
**Pull request by gbaufake**
This PR fixes #6190.

When you try to use `istio.release_tag_version=0.7.1`, the ansible installer fails because the files were renamed `istio-demo`.

cc @gyliu513 @ymesika 

Best Regards,
Guilherme Baufaker Rêgo

### CODE REVIEW

**Comment by ymesika** [comment]
General comment - IMHO the playbook in master isn't suppose to install previous versions. If one wants to install 0.7.1 for example the source zip for that release is available with ansible playbook that matches that version. Does it make sense?

**Comment by gbaufake** [comment]
@ymesika I see your point.
I was thinking about this because, in the documentation (https://preliminary.istio.io/docs/setup/kubernetes/ansible-install.html), it mentions the `istio.release_tag_name` variable.  Also, it does say  "Any valid Istio release version", so I thought it would be ok to support old releases on the master.

**Comment by gyliu513** [comment]
@gargnupur please check this PR https://github.com/istio/istio/pull/6144 as well

**Comment by geoand** [comment]
PR #6144 was created to fix the various incompatibilities with the latest version of Istio and also drop support for installing previous versions

**Comment by ymesika** [comment]
The drop of support is misaligned with the docs.
Was there a decision to support only latest? If there was then the `istio.release_tag_name` should be removed from doc / playboooks.

**Comment by geoand** [comment]
@ymesika The conversation between myself and @sdake took place in #5985.

If this PR is merged then obviously the docs need to be updated as well in a separate docs related PR which I can of course raise

**Comment by gbaufake** [comment]
@geoand 
When #6144 gets merged, the way to support old versions will be switching the branch to old ones as @ymesika  suggested?

**Comment by geoand** [comment]
@gbaufake Unfortunately I don't see any good way to support old versions.
The playbook tried to do that, but there are just too many things that change between releases (or at least that was the case up until now).

Furthermore, the sources of the ansible playbook are currently not being included in the Istio releases (although there is an open PR for that making things even harder). You could I suppose checkout one of the old release branches and work with the ansible sources there, but there are no guarantees :)

**Comment by gbaufake** [comment]
Ok @geoand 
So, I think the present PR is not necessary to the new direction on ansible playbooks.
Should I close it?

**Comment by geoand** [comment]
@gbaufake I would say yes, it should probably be closed

**Comment by ymesika** [comment]
@geoand Thanks anyway, please keep contributing.

**Pull request closed without merging**
