### PR TITLE
Fix multi-network interfaces issue

### PR DESCRIPTION
**Pull request by zhaohuabing**
The instance IPs const should be "ISTIO_META_INSTANCE_IPS", which matches the meta key in the proxy side.

Change-Id: I9322bac16e46f1cdef1a8e2adbf3436e92547608
Signed-off-by: Huabing Zhao <zhaohuabing@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
The metadata key passed to pilot is without `ISTIO_METAT_` prefix.

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
This is not what we want.

**Comment by zhaohuabing** [comment]
> The metadata key passed to pilot is without `ISTIO_METAT_` prefix.

Actually it's with `ISTIO_META_` prefix.

**Comment by hzxuzhonghu** [comment]
I guess you see this with a lower version

**Pull request closed without merging**
