### PR TITLE
Add Service entities to Stackdriver Context Graph Adapter

### PR DESCRIPTION
**Pull request by jeffmendoza**
Stackdriver adapter is not enabled in default istio.yaml / istio-demo.yaml installs. Context Graph is not easily usable by Istio users. Therefore risk to 1.1 release is negligible.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
cc @omaray @supriyagarg

**Comment by douglas-reid** [comment]
Can you provide an example of the config that would be used here?  For instance, where is `destination.service.name` coming from and how is it determined?  Will this be OK for external services (where the namespace of the destination service will be unknown) ?

**Comment by jeffmendoza** [comment]
Hi Doug, the example config is updated at the top of [template.proto](https://github.com/istio/istio/pull/11276/files#diff-d82df93abecc703b020763761f6d0459R57). destination_service_name and destination_service_namespace should be set in config to the [standard attributes](https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/) as provided by istio: destination.service.name and destination.service.namespace.

Context Graph will accept "Unknown" services by having an Unknown node in the graph, no special handling.

**Comment by douglas-reid** [comment]
@jeffmendoza thanks, i missed that in a quick skim. does this match the earlier design here?  are the issues around service identification resolved to everyone's satisfaction?

**Comment by jeffmendoza** [comment]
Replaced by #11426

**Pull request closed without merging**
