### PR TITLE
Update stable downloader to 0.2.12 (pending 'baking' of 0.2.12)

### PR DESCRIPTION
**Pull request by ldemailly**
```release-note
NONE
```

do not yet merge, to be tested first after #1272

### CODE REVIEW

**Comment by ldemailly** [comment]
0.2.10 seems to work well so I'd tend to switch for good old 0.1.6 now ?

**Comment by andraxylia** [comment]
We will move to 0.2.11, so this is not longer needed, right?

**Comment by ldemailly** [comment]
well 5 days later we still don't have 0.2.11 and it will need to bake 1 week at least before being "stable" but sure, it's been 0.1.6 for months, it can wait some more

**Comment by ldemailly** [comment]
might go directly for 0.2.12 in a few days

**Comment by ldemailly** [comment]
let's let 0.2.12 bake until next week and then we can merge this
(before we change "latest" to 0.3.0)

**Comment by yutongz** [comment]
It seems you have to manually update branch to get new circleci scripts.

**Pull request merged**
