### PR TITLE
feat added arm64 to ArchConfig of operator

### PR DESCRIPTION
**Pull request by morlay**
I built multi arch images (amd64 & arm64) for istio https://github.com/querycap/istio
but without `arm64` arch config, i could not install istio by `istioctl` with simple command.

```bash
istioctl install --dry-run --set hub=querycapistio --set values.global.arch.arm64=2
```

now I have to overwrite `affinity` like
https://github.com/querycap/istio/blob/master/deploy/istio-operator.yaml#L13
```yaml
         affinity: &affinity
            # important overwrites.
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                          - arm64
                          - amd64
```

This pr will fix this.

I hope arm64 version could be merged to istio, 
but some issues may be resolved as i list https://github.com/istio/istio/issues/26652#issuecomment-714858976

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Pull Request Attributes

Please check any characteristics that apply to this pull request. 

[x] Does not have any changes that may affect Istio users.

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
/ok-to-test

Also you need to know that it is recommended to set affinity by the k8s overlay, the old helm values are deprecated.
If you try set affinity with old helm values for istiod, it should not be working any more.

**Comment by morlay** [comment]
Yes. but now still use `global.values.arch` to render `affinity`.
There have no flags of `istioctl` to disable it.

**Pull request closed without merging**
