### PR TITLE
Sync list.gen.go with global_dict.yaml in api

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by douglas-reid** [comment]
cc: @theganyo 

I believe we need to get the attributes into 0.8 somehow.

**Comment by qiwzhang** [comment]
No,  Proxy of release-0.8 did not get these two attributes.  So Mixer should not use them

https://github.com/istio/api/blob/release-0.8/mixer/v1/global_dictionary.yaml

**Comment by qiwzhang** [comment]
Global dictionary is just an optimization.   Proxy still send these two attributes in 0.8,  but the transport layer needs to use string type to send them instead of integer type.

**Comment by theganyo** [comment]
There is a blocking issue where the point is to get request.auth.claims (and request.auth.raw_claims) into 0.8.

**Comment by mandarjog** [comment]
This needs to be done the other way around. 
Even though `request.auth.claims` is an optimization, we should include them in both cases since we have added this as an Istio attribute.

1. reconcile yml files so that they are identical *and* contain all necessary keys.
2. generate successive go files from it.

**Comment by douglas-reid** [comment]
how much trouble is it going to be to update the istio/api to get the updated dictionary into 0.8?

**Comment by mandarjog** [comment]
@qiwzhang which dictionary is 0.8 proxy using? how do we verify that ?

**Comment by qiwzhang** [comment]
The work to add these two attributes into api is 4 PR
1) add to api,  2) update istio api-sha,  3) update proxy api-sha,  and 4) update istio proxy-sha

**Comment by qiwzhang** [comment]
OK,  I will take care of this.  I will add these two attributes into api release-0.8 branch and do the necessary dance for istio/proxy to get it

**Pull request closed without merging**
