### PR TITLE
Remove test skips for Ambient Peer Authn

### PR DESCRIPTION
**Pull request by jaellio**
**Please provide a description of this PR:**

Support added for Ambient Peer Authentication  #42696.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]

**Comment by jaellio** [comment]
Requests from an uncaptured src to a dst with a waypoint proxy succeed unexpectedly when a PeerAuthentication is applied with `STRICT` mtls and a DestinationRule with the tls mode set to `ISTIO_MUTUAL`. With the PeerAuthentication and DestinationRule resources applied requests in this configuration should fail. The unexpected results might be related to https://github.com/istio/istio/issues/44671.

**Comment by jaellio** [comment]
Currently blocked on #43698 and #44671. The existing echo framework design does not support verifying mTLS for ambient. The tests are reliant on the presence of the `X-Forwarded-Client-Cert` HTTP [request header](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert) to determine mTLS.

**Comment by howardjohn** [comment]
@jaellio https://github.com/istio/istio/pull/44536 would provide us a way to determine if mTLS is used as well

**Comment by keithmattix** [comment]
Not stale, but we really need to unblock the various ambient test skips. #44536 was closed to keep things minimal, but the echo framework needs to have a way to determine whether or not mTLS was initiated for Ambient

**Pull request closed without merging**
