### PR TITLE
integrate new MCP source/sink stack into galley/pilot/mixer

### PR DESCRIPTION
**Pull request by ayj**
This PR integrates the new MCP source/sink stack into Galley, Mixer, and Pilot. The old stack will be temporarily retained in case we need to interactively debug perf/stability issues. In this temporary "dual" stack Galley supports both old and new gRPC services. Pilot and Mixer can be configured to use the old service by setting the `USE_MCP_LEGACY=1` environment variable. 

This PR also updates the MCP client diagnostic tool (mcpc) to support the new API and also a new output mode to print a summary view of received configuration.

Fixes https://github.com/istio/istio/issues/11094.

This also always us to "incrementally" enable IncrementalMCP support using this new API (xref https://github.com/istio/istio/issues/10497 and https://github.com/istio/istio/issues/10497)

### CODE REVIEW

**Comment by ozevren** [comment]
lgtm. Let's complete this PR, stabilize and land it.

**Comment by ayj** [comment]
> curl: (7) Failed to connect to prometheus port 9090: Connection timed out

/test e2e-simpleTests

**Comment by geeknoid** [comment]
Mixer changes look good.

/lgtm

**Comment by ayj** [comment]
fixes https://github.com/istio/istio/issues/11094

**Pull request merged**
